### ISSUE TITLE
atom.workspace.observeTextEditors gets fired multiple times and also for non-existent panes.

### ISSUE THREAD

**Issue by gandm** [atom/atom#10022]
using some code that fires on a textEditor save event e.g.
```coffee
    @disposable.add  atom.workspace.observeTextEditors (textEditor) =>
      @disposable.add textEditor.onDidSave (event) =>
          textEditor.setCursorBufferPosition [0,0]
```
1. On saving a a file e.g. test,js the above code fires once - correct
2. Now split screen to have two edit panes/tabs for test.js and save file - above code fires twice - I would expect only one firing of this code ( corresponds with https://github.com/atom/atom/issues/8853)
3. Now remove one of the tabs for test.js and save the test.js - above code still fires twice! but one of the calls to textEditor.setCursorBufferPosition gets a stack trace and message `This TextEditor has been destroyed` obviously because the pane no longer exists.

This all seems a bit flaky to me! Surely an onDidSave event should only fire once for all instances of the same file and never when a tab has been removed!!!!

**Comment by lee-dohm** [comment]
The behavior you describe is the expected behavior:

1. The `onDidSave` handler fires once
1. The `onDidSave` handler fires twice because there are two `TextEditor` objects, one in each pane. But the underlying `TextBuffer` is shared between them. So when you save in one, both `TextEditor` objects get notified and the `onDidSave` fires in both.
1. The `onDidSave` handler fires twice because in your example code, you never clean up the `onDidSave` handler when a `TextEditor` is closed. A better example would be:

```coffee
@disposable.add atom.workspace.observeTextEditors (editor) ->
  onSaveDisposable = editor.onDidSave ->
    editor.setCursorBufferPosition [0, 0]
  
  editor.onDidDestroy ->
    onSaveDisposable.dispose()
```

**Comment by gandm** [comment]
Yes I know that an I will code accordingly. At the moment  I do dispose of the subscriptions but not until the end.

I still think this is a bug as onSave events shouldn't be being sent to a non existent textEditor regardless of whether subscriptions remain. This is bad!
