### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by meat147** [atom/atom#10047]
Hello,

i just wanted to start Atom after installing it a few days ago.
Now i get this Error message. I found this Issue https://github.com/atom/atom/issues/10015 tried to delete everything in appdata and temp but still issue is there.

I installed one plugin: https://github.com/acemod/language-arma-atom

OS: Windows 10 64-Bit
Atom version: Latest Stable and Beta from the Website

![image](https://cloud.githubusercontent.com/assets/3389721/11774409/2222249c-a235-11e5-966d-1dec72ce7aac.png)

```
SyntaxError: Unexpected token 
    at Object.parse (native)
    at FileSystemBlobStore.load (C:\Users\Meat\AppData\Local\atom\app-1.3.1\resources\app.asar\src\file-system-blob-store.js:31:31)
    at Function.load (C:\Users\Meat\AppData\Local\atom\app-1.3.1\resources\app.asar\src\file-system-blob-store.js:10:14)
    at window.onload (file:///C:/Users/Meat/AppData/Local/atom/app-1.3.1/resources/app.asar/static/index.js:18:39)
```

**Comment by Zireael07** [comment]
Do you have the stable and beta at the same time? Find your blob-store file and delete it, this should resolve it.

**Comment by as-cii** [comment]
Hi @meat147, thank you for reporting this issue! It seems like our `blob-store/MAP` file is malformed, for some reason, and `JSON.parse` is having troubles parsing it. Could you find and paste the contents of that file here (or in a gist)?

As a temporary stopgap measure, you should be able to delete the file as @Zireael07 suggested and the issue should disappear automatically. If it doesn't, I would say it's likely that you're deleting a file which is not the same as the one referenced by Atom.

By default, we should search for that file under the `ATOM_HOME` environment variable, where other files related to Atom are also stored. If you manage to find that file, it would be awesome if you could share it so that we can inspect it and find the root of the issue. 

I am sorry this is causing troubles to you, your help on this would be super appreciated! Thanks. :sparkles:

**Comment by meat147** [comment]
Hey @as-cii,
blob-store\MAP
 4894 lines of
```
0000 0000 0000 0000 0000 0000 0000 0000
```

sorry i could not find the Json.parse in appdata local / roaming, or userprofile\.atom can you point me to it ?

And there is no Enviroment Variable in my OS called ATOM_HOME.

Thanks for all your Help guys!

**Comment by as-cii** [comment]
> 4894 lines of
> 
> 0000 0000 0000 0000 0000 0000 0000 0000

That's weird. That file is supposed to be a JSON, human-readable file: I am wondering what's causing it to become a sequence of zeroes.

@meat147: I'm glad that deleting it solved your issue! Did you save a copy so that we can inspect it and find what causes this problem? It would be awesome if you could upload the file somewhere, so that we can download it and have a look locally.

Thanks again!

**Comment by ratkingsminion** [comment]
I had the same issue just today. Using Win 7, 64bit. Here's the content of the "blob-store" folder I deleted to get it working again: https://dl.dropboxusercontent.com/u/10650964/_trash/blob-store.zip
