### ISSUE TITLE
Instructions on how to make Atom portable

### ISSUE THREAD

**Issue by Zireael07** [atom/atom#10072]
I have Atom 1.3.1. As I recall, we were supposed to get instructions upon updating on how to make our install portable. I have looked everywhere and the program doesn't tell me how. Neither does your homepage, whether by itself or via Help/Documentation.

I need to move Atom off my C drive. Help?

**Comment by 50Wliu** [comment]
`atom --portable`
Does that work for you?

**Comment by Zireael07** [comment]
Well, it works. But I still don't understand what that command line switch does. And I'm afraid to experiment with moving the Atom folder wholesale...

More documentation is definitely needed for this switch and what exactly it does. 
Searching for "portable" on atom.io doesn't find anything regarding the switch anywhere, just an old FAQ and forum discussions from Feb and Jul, so long before the switch was implemented. This needs to be rectified ASAP.

**Comment by raelyard** [comment]
Adding to docs so it will be there.  In the meantime, a quick description here.

Portable mode is triggered by having a directory named .atom as a sibling to the directory in which atom.exe lives.  Atom will use this as the home directory instead of the .atom directory in the default location (~\..atom).

Atom's order of preference for finding the home directory is:
1. if an environment variable named ATOM_HOME exists, use the path specified there
2. if the Atom Portable directory exists (.atom as sibling of the parent directory of the atom.exe), use that
3. default location (~\..atom)

The command line switch takes the content of the default home directory and copies it the the portable location.  If, for instance, you have the atom.exe in a folder in your Dropbox called atom and run it with the command line switch, it would make a copy of the Atom Home from your home directory as a sibling of the atom directory in your Dropbox.

**Comment by eugenesvk** [comment]
Pasting here from https://github.com/atom/atom/pull/8442#issuecomment-186853783, with details on why this priority order is incorrect.
Would you kindly make **Atom** prioritize a simple local setting `.alwaysportable` instead of trying to guess the user's setup system?

I have Atom installed locally with a custom path set to a Dropbox folder (so ATOM_HOME is defined in my environment).
Then I've downloaded and unpacked the zipped Atom version to my USB drive. However, when I run it, it still reads the Dropbox settings.
Starting from a command line with atom.exe --portable doesn't change anything either (it doesn't even create any sibling folders (on a side note: a portable app shouldn't have any siblings, everything should be in one folder)).

Would you kindly implement the .alwaysportable option or something instead of the not working rules-based system from first option in the TODO list? I'm not sure it's worth trying to make up a set of rules that would work universally while there is a much simpler and less error-prone solution.
Nothing in the system (no preset environment variable) should interfere with the portable installation, it should be just ignored.

**Comment by Zireael07** [comment]
So if I have Atom already installed, it'd still use ATOM_HOME?

I still need to move Atom off C: drive.

Can I get step-by-step instruction?

**Comment by DoumanAsh** [comment]
@raelyard 
Is there can be any reason why Atom would ignore sibling directory ```.atom``` alongside with binary?
```ATOM_HOME``` works fine and i used it to set Atom's home in directory with binary.
But when i remove it, Atom defaults to ```~/.atom```

It is on 1.5.3 but i didn't saw any significan changes related to that in 1.6.0 beta

**Comment by raelyard** [comment]
@DoumanAsh  The location for the portable home directory is not as sibling to the executable, but sibling to the directory holding the executable.  The intent is to play nicely with the Squirrel.Windows installer that puts the executable in a version directory.

**Comment by raelyard** [comment]
@Zireael07 @eugenesvk  The expressed intent I received was that if the ATOM_HOME is set, that should be used.  It would have first priority.  I believe the idea is that if you've gone to the trouble of creating an environment variable, that's what you want to use and it would override whatever else.  I can see your point that you might want to have different installation at different places using different configs.  Would it make sense to just have the config with the app instead of using the ATOM_HOME.  Maybe run the exe from Dropbox?

**Comment by Zireael07** [comment]
@raelyard: I want to move as much Atom stuff as possible off C drive without having to uninstall/reinstall. This includes the packages, configs and whatever. Preferably while keeping the autoupdate support. I have still to see any instructions on how to accomplish this.

The .portable switch creates a sibling .atom directory and that's as far as I understand it.

**Comment by eugenesvk** [comment]
> Maybe  run the exe from Dropbox?

I don't really want to pollute dropbox with 0.5Gb+ for two versions of an app when all I need is a few megs for settings.
But more importantly, the app is still not portable due to some confusion I don't even understand the source of.

The ATOM_HOME is for a completely separate issue — it's needed to be able to move the config folder where the user wants. I don't see how it connects to a portable app when the definition of portable is being independent from the host system (and, by definition, ignoring if said system sets ATOM_HOME).

Would you kindly go through the last trouble and change priorities in your list of checks so that ATOM_HOME would be of lower priority than a sister folder with .atom?
Or introduce another check of the highest priority for a `.portable` file?

**Comment by eugenesvk** [comment]
@Zireael07 the ATOM_HOME variable can be set by yourself. That's how I did it to move config files to my Dropbox folder. So you can easily move the settings off C.
Not sure about the app itself, whether changing its location would stop autoupdates. As a (bad) alternative, you can create symlinks to another drive so that the installer wouldn't even know folder is not on drive C, so it'd continue to create new versions wherever you want it to.

**Comment by j3g** [comment]
ATOM_HOME being top priority can be a security issue. It is trivial for any unknown actor to modify that setting and cause Atom to load malicious code.

**Comment by 50Wliu** [comment]
This updated documentation should be available starting in Atom 1.7.0.

**Comment by damieng** [comment]
@j3g How do you see ATOM_HOME being trivially modified?

Anyone who can modify the ATOM_HOME environment variable to point somewhere under their control could also modify PATH, TEMP and COMSPEC all of which would be much worse.

**Comment by eugenesvk** [comment]
@50Wliu 
I don't understand why the issue is closed when it's not fixed. There can be no instructions on how to make Atom portable because it's not portable yet due to the `ATOM_HOME` var :)

**Comment by damieng** [comment]
@eugenesvk You do not need to set ATOM_HOME to use portable mode.

**Comment by julmot** [comment]
@damieng he means that if it is necessary to set a environment variable we can not say it is "portable". I think this is because he doesn't know about the `--portable` argument (which I also didn't know at first glance as there is no documentation about it).

**Comment by eugenesvk** [comment]
@julmot nothing of the sort as I've described above and as the docs acknowledge themselves. And `--portable` changes nothing (besides being misleading).

**Comment by damieng** [comment]
@eugenesvk Either you want atom to be self-contained on a portable device or you want it to store config's on a specific shared folder like Dropbox.

Which is it?

**Comment by damieng** [comment]
Please also review the latest docs on this at https://github.com/atom/docs/commit/a63474fc5530818dd48bea8ce966dc8f77ecc105 

There is no --portable command line switch.

**Comment by Zireael07** [comment]
>Please also review the latest docs on this at atom/docs@a63474f
@damieng: Done!

**Comment by eugenesvk** [comment]
@damieng 
> Either the application and its data would exist on your Dropbox or it would exist on a USB drive.

No, these serve completely different purposes. Dropbox is for sharing settings (not apps) across my computers.
Portable version (e.g. running from a USB stick) is to have settings (and app) on any computer, even where I don't have (and don't want to have) Dropbox installed.
There could be other cases (e.g. you might want to have a separate portable app to test settings/addons etc without affecting your main version).
Also, imagine that someone else has Atom setup with his environment variable (e.g. to change location of settings file) and you want to launch your own version with your own settings off a USB drive and oops, can't load your settings because it's sourced from `ATOM_HOME` var.
All of this is precisely because you can't call an app portable if it's integrated with the system it's run on. And env var pointing to settings is such an integration. As is storing files outside of the app data folder (as some other people have reported is happening).

**Comment by damieng** [comment]
I'm not sure why ATOM_HOME takes precedence over a .atom folder but going with that first and then falling back to ATOM_HOME would solve the problem @eugenesvk ?

**Comment by damieng** [comment]
So the scenario we're talking about here is:

- I've set ATOM_HOME because I want my config elsewhere
- I'm running atom.exe from a portable device
- I actually want the config to come from the portable device

The primary scenario for which is:

- I'm on my main development machine that has Atom in non-portable mode
- I wanted my config file moved somewhere other than %USERPROFILE%
- I'm trying to setup atom in portable mode and need to test it

The easiest fix for that is to create an atomportable.cmd file on the portable device alongside atom.exe that simply has the contents:

````powershell
@echo off
set ATOM_HOME=
start atom.exe %*````

Which will launch the app with no ATOM_HOME.

**Comment by eugenesvk** [comment]
@damieng
Thank you, that's a very easy fix for testing indeed! Didn't know you could  unset env var for the process only without affecting the user environment variable.
Is there something that would prevent this from working elsewhere? Does the `set ATOM_HOME=` require any privileges or something? 
If not, then this would be the portable solution for the settings and the only thing remaining would be to make sure portable version didn't leave any files, even temp, on the host machine.

**Comment by damieng** [comment]
Yeah settings like that is not very well-known thing but doesn't require any permissions at all.

I'm not sure about the temp, cache, crashdump scenarios. It's possible they leave stuff on the host - that would require more investigation (I was only planning on documenting what we had). 

Glad we have a workaround for now. 

If other people run into the same scenario we should add this to the docs or consider an alternative solution such as prioritizing portable .Atom over ATOM_HOME (probably breaks somebody's scenario) or a marker file like .force-portable that tells it to ignore ATOM_HOME.

**Comment by eugenesvk** [comment]
@damieng thanks for sharing the secret :)
Would you kindly add this nugget to the documents so that at least the settings portability is finally resolved? I'd only note that if Atom doesn't find a sibling-folder with settings then it creates a new one on the host system in user folders. So you need to first create/copy your settings to the parent folder, then run the portable.cmd.

The general solution already exists, it's #2 on the TODO list in https://github.com/atom/atom/pull/8442 **Add .alwaysportable directive (Gonna see if people want this or not)**. This won't break anyone's scenario.
It's just that for some reason the concept of portability has been misunderstood for way too long, and this led to such a confusing implementation.
But anyway, thanks for finally moving this one step forward toward portability!

**Comment by S-ed** [comment]
Why does set ATOM_HOME override portable mode?

**Comment by damieng** [comment]
Portable mode is just atom detecting a .atom config and data folder in the
the same parent folder as the Atom application folder so it all runs from
the same location e.g. a thumb drive.

If you set ATOM_HOME you have explicitly told atom where you want the .atom
to be live.

The two options are mutually exclusive.

Is there a specific configuration you're trying to get working?

**Comment by S-ed** [comment]
@damieng the problem of this approach is - I can't use a portable Atom distribution from USB stick on PC where ATOM_HOME is defined.

**Comment by damieng** [comment]
You can... but the portable installation is going to store it's config where ATOM_HOME points to.

Do you have two copies of Atom?  Why is ATOM_HOME set on a machine you want to have a portable installation on?

**Comment by S-ed** [comment]
Most obvious reason, for maintenance purposes. Mine is on USB, as I've set it up. And the other one is on User's pc.

> you want to have a **portable installation** on

Sounds like oxymoron.
Portable is meant to have on your usb, in your pocket, or on Cloud storage. You just run it and it works.
But some Users already have their own Atom, with ATOM_HOME defined.

**Comment by damieng** [comment]
Probably the simplest workaround would be to add a line to the atom.cmd file on your USB drive with

```SET ATOM_HOME=```

Note that this doesn't affect ATOM_HOME for the rest of the machine but just for the command window it's run in.  The full atom.cmd would look like this just in case there isn't one on your USB drive today;

```
@echo off

SET ATOM_HOME=
SET EXPECT_OUTPUT=
SET WAIT=
SET PSARGS=%*

FOR %%a IN (%*) DO (
  IF /I "%%a"=="-f"           SET EXPECT_OUTPUT=YES
  IF /I "%%a"=="--foreground" SET EXPECT_OUTPUT=YES
  IF /I "%%a"=="-h"           SET EXPECT_OUTPUT=YES
  IF /I "%%a"=="--help"       SET EXPECT_OUTPUT=YES
  IF /I "%%a"=="-t"           SET EXPECT_OUTPUT=YES
  IF /I "%%a"=="--test"       SET EXPECT_OUTPUT=YES
  IF /I "%%a"=="-v"           SET EXPECT_OUTPUT=YES
  IF /I "%%a"=="--version"    SET EXPECT_OUTPUT=YES
  IF /I "%%a"=="-w"           (
    SET EXPECT_OUTPUT=YES
    SET WAIT=YES
  )
  IF /I "%%a"=="--wait"       (
    SET EXPECT_OUTPUT=YES
    SET WAIT=YES
  )
)

IF "%EXPECT_OUTPUT%"=="YES" (
  SET ELECTRON_ENABLE_LOGGING=YES
  IF "%WAIT%"=="YES" (
    powershell -noexit "Start-Process -FilePath \"%~dp0\..\..\atom.exe\" -ArgumentList \"--pid=$pid $env:PSARGS\" ; wait-event"
    exit 0
  ) ELSE (
    "%~dp0\..\..\atom.exe" %*
  )
) ELSE (
  "%~dp0\..\app\apm\bin\node.exe" "%~dp0\atom.js" %*
)
```

**Comment by S-ed** [comment]
@damieng Haha. Yep, i'm using bat with SET to override the ATOM_HOME.
To be precise this code from another thread: https://github.com/atom/atom/pull/8442
```
@echo off
pushd %~dp0
if not exist .atom mkdir .atom
if not exist .atom\AppData mkdir .atom\AppData
if not exist .atom\AppData\Roaming mkdir .atom\AppData\Roaming

:: Trick emmet or other plugin to think profile directory is in our data directory
set "USERPROFILE=%~dp0\.atom"

:: Set Atom base directory
set "ATOM_HOME=%~dp0\.atom"

:: Boot
start atom
```
Author claims that USERPROFILE also need to be set, for some plugins, but I have no any issues yet.

And, getting back to my original post:
Why is ATOM_HOME overrides .atom folder near Atom binary folder?
```
.atom
Atom
```
This rule should be stronger than ATOM_HOME IMO.
By default install path is like:
```
C:\Users\-user-\AppData\Local\atom\app-0.0.0\atom.exe
```
And .atom path:
```
C:\Users\-user-\.atom
```
It's not even a security issue, any user could use SET.

**Comment by damieng** [comment]
I'm not sure what the original intention was in giving precedence of ATOM_HOME over .atom but it does seem from the commit history it was intentional. Changing it right now would also break a bunch of people so we'd need to understand why it was given this precedence and what the trade-off is for their use cases.

**Comment by S-ed** [comment]
@damieng Totally agree here. Hope, at least it will be discussed. Thank You.

**Comment by raelyard** [comment]
The implementation of ATOM_HOME as an option for where to find the Atom configuration predated the implementation of the portable mode option.  If I understand correctly, I think it was the first attempt at satisfying the desire for a portable mode by allowing the configuration to live somewhere other than the default.  I think (don't know for certain) that it pre-existed was a  part of why it was decided that it should take priority.  I also think (don't know for certain) that there was a sentiment of thinking that if you set your machine to look for that config in a custom spot via environment variable, that's a pretty strong statement that that's what you want to use on that machine.  The use case of support and being a guest on someone else's machine and bringing your own setup with you was probably not considered.  When I worked on portable mode I was instructed that the environment variable should take precedence and I didn't challenge that because these arguments (that may or may not have been the real reasons), in my mind, seemed to make sense.

**Comment by damieng** [comment]
Thanks for the update @raelyard! It's sounding like we might be able make portable mode take priority over the ATOM_HOME as long as we had some messaging in the release notes for people who get unexpected behavior to turn to.

**Comment by eugenesvk** [comment]
@damieng yes, please finally clear up the confusion with portable modes and allow us to have a truly portable Sublime, which doesn't depend in any way on the settings of the host machine!

**Comment by lxdlam** [comment]
Hi everyone!
I'm using portable fine and I'm building gcc-compiler.
I'm wondering how to use the portable .atom path.
I mean that I copied the whole MinGW folder to my USB drive's .atom folder, how to set the package's path so that I can use anywhere?

**Comment by damieng** [comment]
@lxdlam You can use portable mode by just creating a .atom folder alongside the path where atom lives, e.g. if your USB drive is e:

e:\.atom  <- your config
e:\atom <- your app folder containing atom.exe

or;

e:\atom\.atom <- config
e:\atom\app <- app folder containing atom.exe

It doesn't matter as long as the .atom folder is alongside the app folder.  (It can't be inside because of the way the update system works)

As an aside the Windows version of Atom is only supported compiling from source using Visual C++ not MinGW/gcc.

**Comment by julmot** [comment]
@damieng I don't have any problem with the portable mode after creating the `.atom` folder back in February. I just want to participate because I had to invest a lot of time because IMHO the portable thing is to little or not documented. I found the information about the `.atom` folder inside a GitHub issue...

**Comment by damieng** [comment]
The portable mode is documented in the flight manual http://flight-manual.atom.io/getting-started/sections/installing-atom/
