### ISSUE TITLE
Prevent buggy packages from breaking other packages

### ISSUE THREAD

**Issue by peterhal** [atom/atom#10091]
When a buggy package throws in an event handler, other packages subscribed to that event are not notified. We see this pretty regularly in Nuclide, where a Nuclide feature stops working because a user has installed a buggy third party package. Recently a user had a buggy package installed which threw on TextBuffer will-save preventing the user from saving their file which was particularly frustrating.

I think Atom should catch all exceptions thrown by installed packages, while still reporting the exception in some way. This should give a good balance between robustness and debugability.

I have a pull request coming (https://github.com/peterhal/event-kit/commit/83ac63055b76d5ec74e551dfea7ebb5e09e62b82) for event kit emit which should make this proposal concrete. Beyond events, I would also like to see a solution for other places where Atom calls 3rd party packages including package activation/deactivation.

**Comment by nathansobo** [comment]
Thanks for taking the initiative on this. I think these are good insights.

As we discussed in chat, I'm on board with this. I'd prefer to allow global handlers to be registered on `event-kit`'s `Emitter` class, via some static method like `Emitter.onUncaughtException` or whatever name makes the most sense. That would keep global assumptions out of `event-kit` and also allow the behavior to be selectively enabled (we wouldn't try/catch if there were no uncaught exception handlers registered).

To start with, I'd like to see this behavior behind an option in Atom so we can experiment. I was thinking you could set it in Nuclide, but I think adding a core config option would be a clearer path for the ecosystem as a whole. Then we can encourage people to try the option and report on any unexpected bad experiences.

**Comment by lee-dohm** [comment]
I agree that limiting the amount of damage a buggy package can do is a good thing. I also agree with @nathansobo that we should be cautious about this. I think moving the error handling out of event-kit is definitely the correct approach.

My concern is that naïve "catch, report and continue" can cause problems too. If a package behaves improperly, let's say corrupting the `config.cson`, that can cause the next package in the event handler chain to do something incorrectly as well. Maybe that's still better than what is happening now, maybe not. I feel it bears investigating.

Tools to surface to the user *when* a package is behaving badly and helping the user zero in on *which* package is the problem is even better.

**Comment by peterhal** [comment]
@lee-dohm Not calling a registered handler on an event is always a bug. At worst this fix gets from a state of always being a bug to state of might be a bug.

Agreed that better tools for reporting buggy packages would be a good thing.

**Comment by nathansobo** [comment]
I've upgraded event-kit in core with functionality based on your pull request. Next step is adding an option in core that conditionally registers a handler via `Emitter.onEventHandlerException`.

**Comment by peterhal** [comment]
Groovy - thanks for merging this in.
