### ISSUE TITLE
Keybinding for toggling comments duplicated

### ISSUE THREAD

**Issue by cpgo** [atom/atom#10104]
How can I solve this:
ctrl-/ Toggles line comments
ctrl-; Also toggle line comments but is not listed on keybindings
Now I want to make a new keybinding for ctrl-; but the line comment bind always overrides my keybind.

**Comment by lee-dohm** [comment]
See the [Atom Flight Manual for more information on keybindings](https://atom.io/docs/latest/behind-atom-keymaps-in-depth). If you have more questions, you can make a post on [Discuss, the official Atom forum](https://discuss.atom.io) and lots of folks there can help you.

You also may be running into this known issue: https://github.com/atom/atom-keymap/issues/35

**Comment by mpathy** [comment]
Yes he will - and the result will be to stop using Atom.

Even the last issues with international keyboards - which btw none of the other editors out there has - are now fixed in Chromium since November and there is no reason for this still be open.

This bug affects almost the entire world except the US!

I think everybody here would be lucky if a developer may comment on why it isnt fixed for a while.

At least to show that somebody cares.

**Comment by Ben3eeE** [comment]
This came up again in https://github.com/atom/atom/issues/13076 because we are testing all keybindings in the beta.

The extra "keybinding" comes from the menu. We add `/` as an accelerator for this menu item which [Electron doesn't support](https://github.com/electron/electron/blob/master/docs/api/accelerator.md#available-key-codes)?

![pasted image at 2016_10_28 10_39 pm 1](https://cloud.githubusercontent.com/assets/1058982/19830290/f64fd03c-9df4-11e6-96b4-0e5328b64185.png)

For me the accelerator is activated by <kbd>Ctrl+'</kbd> when the command is bound to <kbd>Ctrl+/</kbd>. Anything I bind to <kbd>Ctrl+/</kbd> that is also in the menu will activate with <kbd>Ctrl+'</kbd>.

I can only reproduce this on Swedish keyboard layout. US seems to work just fine.

**Comment by Ben3eeE** [comment]
I opened an Electron issue for this: https://github.com/electron/electron/issues/8741.
