### ISSUE TITLE
Python autocomplete not working

### ISSUE THREAD

**Issue by elebumm** [atom/atom#10137]
Hi, so I am using atom to code in Python however the autocomplete isn't working only in Python. It works with others such as html and javascript. I have python-jedi and the autocomplete python packages enabled. Any help?

**Comment by elebumm** [comment]
Figured out why I was having this problem. Currently it seems like the [Python Jedi](https://github.com/saravanan-k90/python-jedi) atom plugin is broken and disables it completely.

**Comment by saravanan-k90** [comment]
Python Jedi (https://github.com/saravanan-k90/python-jedi) is not broken. Clarified the same issue raised by elebumm @ python-jedi repository.

**Comment by Aaron-joshua** [comment]
i installed auto complete python but it seems not work help me out

**Comment by saravanan-k90** [comment]
i am extremely sorry @Aaron-joshua ., my position is bad now(no job, less money, less internet, old linux system... due to these reasons i haven't really checked plugin working in any new versions of atom for the past 6 months)... so i may not be able to try to check or solve the issue you have opened. But i really appreciate for opening issue.
