### ISSUE TITLE
Look into VS Code editor implementation (Improve editor performance)

### ISSUE THREAD

**Issue by YemSalat** [atom/atom#10188]
Hi,

I have been following the latest versions of Atom and VS Code (looking for ST replacement).

'Ideologically' I would prefer Atom because it is 'more' open source and seems much more flexible compared to VS code. However, performance, especially UX performance has always been the major factor stopping me from switching from ST (I am guessing that I am not alone in this)

And at the moment it seems like VS Code has the edge in that respect. Its editor has better performance compared to Atom.

For example, when I test the _Find_ command in  this file: https://github.com/YemSalat/spark-lang/blob/master/src/parser/parser.js

And search for things like 'peg', 'this', etc. A clean install of Atom takes between _1s - 1.5s_, while VS Code does it almost instantly (I would say no more then _250ms_). It is also much better at 'live-updating' the search results as you are typing. I am testing this on a 3 year old i5 8GB laptop.

I think looking into their implementation could be helpful, as in my opinion improving editor performance can highly increase the editor adoption rates among developers who have not made the switch yet.

PS The VS Code editor can be found here: https://github.com/Microsoft/vscode/tree/master/src/vs/editor

**Comment by thiagolucio** [comment]
It's another approach VS Code and technology. I think the two editor's totally different on back end development tools I think. ATOM is much more personalized with VS Code and VS is a Microsoft and much more Native in windows for example.
The compare is lost of time.

**Comment by iclanzan** [comment]
I don’t think it would be wasted time at all. They are both JavaScript running in Chromium after all. Microsoft is doing amazing work with VS Code. It feels as fast as a native editor. I’m sure we can learn a few tricks from them.

**Comment by thiagolucio** [comment]
Yes, VS Code is great  tool and I use to. I think the same about the ms team. But I think this compare is not good option but get the good points in VS to show a correct path from ATOM in strict running(s) cases is a good option.
ATOM have your own way and focused history. Compares insidious in copies without personality :(
Good new year about that:) for all!

**Comment by nfour** [comment]
I disagree with you @thiagolucio. I've been committed to Atom over the last month since working with an Atom-only team. We run it on linux and performance, even on $2500 systems is quite poor at times. Opening an 18k line file accidentally pretty much destroyed atom once. It's MUCH better than it used to be in quite a few ways though, I appreciate that.

Some performance differences I've noticed on Linux & Windows

Atom:
- Has poor render performance when scrolling. Even when a large file is set to "plain text", although it is a significant difference.
- Multi cursor (200+) lags so much the editor actually freezes at times or outright crashes!
- Opening command pallet, packages section can be slow
- Chokes on 20k line files.

VSCode:
- Scrolling performance is near perfect.
- Multi cursor (200+) is very fast, though sometimes doesnt work.
- Entire interface feel like native.
- Handles 20k line files almost as well as sublime-text

Atom is faster on linux over windows I've found, but not by much. I'd like to see 64bit versions on windows.

If Atom could have VSCode's performance in these areas, it would dominate the code editing world considering the package ecosystem, so in that way I want Atom to learn as much as possible from VSCode. I just hope that it's actually doable without breaking backwards compat with packages.

**Comment by thiagolucio** [comment]
It's a big analysis for your system environment. Good work.
We'll, what can I say...
It's not a question to how is the best editor. The question is the "compares".

I like very much ATOM and the community people to development them make a great work. When we compare with another project, I think this denigrate the hardworking team. In this case, the ATOM team.

ATOM for me is a first editor can you make totally personalize. Editor with your identity. Have a lot of passion's contributed and make this change first different  in mi opinion. Nobody here need agree with me but I think ATOM have you own way to be growing. Not need to another editor to show the path. 

I believe the ATOM team continuous have your good work, good ideas and great dev from make originals solution's from innovation the editor.

Copy solutions from VS Code or Sublime is make the same tool with another face. A very grateful from ATOM team because that form to think. With you like VS Code or Sublime still them ( I have this two editor's in mi PC) but I always believed in ATOM in your own and originals way.
Sorry mi English.

**Comment by YemSalat** [comment]
@thiagolucio I think you misunderstood what I was saying (I tried to 'parse' your English the best I can)

Yes, ATOM is great 'Ideologically', but performance is clearly lacking.
VS Code uses exactly the same technology stack as Atom, yet it is much better in terms of editor performance. For me personally, all the perks that Atom brings to the table, no matter how great they are - become plain useless because it does not allow me to work comfortably.

Again, this will differ from person to person. My personal 'editor journey' is: Notepad++ __->__ Vim __->__ ST
I am used to things being instant. VS Code is good enough for me, Atom is not.

If Atom had the same performance as VS Code - I would switch right now.

**Comment by nfour** [comment]
@YemSalat Exactly. Atom's customizability is admittedly fantastic and super refreshing, but you can't just put your head in the sand because most people who want to get shit done NEED good performance. They NEED their laptop battery to not drain 30% faster. They NEED to not get lockups and they needn't have to use a different editor to open large files.

Fix this and Atom will be the defacto GUI editor hands down. I honestly didn't think it was possible before I saw what VSCode could do, so now I'm kind of excited. Would love to get an atom contributors opinion on the task at hand.

**Comment by thiagolucio** [comment]
I'm not putting my head in the sand. Nor am I denying the drawbacks of ATOM. This is not religion, it is a simple development tool. What I am trying to show in my opinion is that the ATOM worth it, even with the problems we will have with him. VS Code is a proprietary editor and so it is not customizable. The Microsoft dictates the rules so there is no democracy in that. Until then any other proposal.
It is free for clear reasons. The Microsoft found that the market is losing by not offering something to that effect.

ATOM is a free tool and sustained by the community that develops by passion and made to please everyone, even if you do not like it should be able to understand this.

Be patient, it will improve. But if it's bothering you that much simply uninstall it from your computer and forget it.
I believe contribute to the development of it is much more constructive than getting detonating the work of those who contrary to VC Code works for passion and not for wages.

**Comment by rjv** [comment]
@thiagolucio The full code base for VS Code lives on GitHub with an MIT license (https://github.com/microsoft/vscode). I'm not sure I understand where the "proprietary" comment comes from. It's clear to me that with both projects being open-source, there's no reason not to explore the techniques used and potentially leverage code that has been explicitly labeled as "open."

**Comment by 50Wliu** [comment]
*Disclaimer: I am not a GitHub employee.*

> Would love to get an atom contributors opinion on the task at hand.

Performance is definitely one of the bigger concerns, and there's been a lot of work recently at improving it.  Some of the more notable ones in 1.3.0 include a general 20-30% speedup (partly due to #9318, among other PRs), find-and-replace speed improvements (#9426), and lazy snippet loading (#9507).  In 1.2.0 the Tree View's performance was increased a lot through atom/tree-view#616.  I think the Atom blog does a really good job of bringing attention to the various performance work being done: http://blog.atom.io.  @nathansobo and @as-cii in particular have really been going at it, and I'm sure there'll be more improvement soon :).

@samccone also did an excellent analysis on why startup time is so slow in #9720, so feel free to check that out (also #3673, which is a general tracking bug).

> Applying syntax highlighting to a new file is quite delayed

You may want to subscribe to #9561 for updates if you're experiencing this.

> Multi cursor (200+) lags so much the editor actually freezes at times or outright crashes!

While I'm pretty sure there's a dedicated issue to this, I can't actually find it right now.  Sorry.

> I believe contribute to the development of it is much more constructive than getting detonating the work of those who contrary to VC Code works for passion and not for wages.

While I don't work for GitHub, I'm pretty sure that the core employees working on Atom are getting paid for doing so by GitHub, just as Visual Studio Code employees are being paid by Microsoft.  I think portraying Microsoft as "inherently evil" here isn't a fair comparison.

I hope this answered some of your questions!

**Comment by thiagolucio** [comment]
Open source project is one thing...but...
https://en.wikipedia.org/wiki/Visual_Studio_Code

**Comment by YemSalat** [comment]
@thiagolucio 
![screenshot from 2016-01-02 22 43 37](https://cloud.githubusercontent.com/assets/2361381/12074369/83b7a664-b1a3-11e5-8b7f-bdd6343751eb.png)

I am convinced you are trolling.

**Comment by thiagolucio** [comment]
I'm not trolling. My only intention here is convinced  it to don't give up ATOM because there's problem's. 
All Editor's are good. We need have patient with that only. All ATOM problem's still OK one day.

**Comment by YemSalat** [comment]
You edited your precious message so that mine looks out of place now, I will report you to GitHub staff

**Comment by nfour** [comment]
@50Wliu thanks for that! I've poked some of the performance related discussions so it's good to get a summary.

Drama aside...

In regards to startup; [VSCode](https://code.visualstudio.com/docs/extensions/our-approach) handles a bit better at first glance. Extensions are run in their own process and also may be lazy loaded, to listen on events to self activate.

I suspect VSC extensions have less power than Atom's, though. Reading [this issue about adding buffer tabs](https://github.com/Microsoft/vscode/issues/224) it becomes clear that tabs can't be added to the editor through the extension interface. The owner of the repo actually implies tabs aren't necessary which then managed to spawn a whole debate about such a fundamental, polarizing, potentially optional feature. In fact I've not seen a single extension modify the core package at all.

So I wouldn't worry about Atom being trumped in terms of extensibility any time soon :).

**Comment by joshaber** [comment]
We're definitely interested in learning as much as we can from Visual Studio Code. That said, they have a pretty different architecture from Atom, so it's not so simple as finding This One Weird Trick® in their code and copying it over.

As @50Wliu said, we've done a lot of performance work recently and we have more coming down the pipeline.

All that said, if there are concrete lessons you think we could learn, absolutely open a new issue! :metal:

**Comment by bddenhartog** [comment]
@nfour I'd question why you have an 18k line file.

**Comment by corysimmons** [comment]
@YemSalat Thanks for opening the issue. Not even gonna waste time reading the arguments against it. Atom should learn something from VSCode and until they do I'm switching editors.

**Comment by mkraft** [comment]
Microsoft has stood on the shoulders of Github's giant Atom editor to make something very performant. You both deserve a lot of credit. Thank you.

**Comment by samosale** [comment]
Yeah, the biggest problem with Atom is performance... It is slow on startup and slow when opening large files. VS code is so fast that sometimes I can't belive it is written in JavaScript... I am on Linux.

**Comment by nick-walt** [comment]
Is Microsoft contributing back into Electron to improve the platform?

Is it possible that Code's great performance, and apparently superior architecture, could be attributed to significant C# experience in those using TypeScript to generate the JavaScript? Could C# be influencing their design and be a key reason why their architecture is so different?

Are the people at Atom using Typescript?

**Comment by jt3k** [comment]
If microsoft something touches it only for their own benefit. I think you should not even look in their direction. It is better to avoid them, and try less to mention them

**Comment by rattrayalex** [comment]
Let's keep open-source positive 😄

**Comment by jt3k** [comment]
[open-source](https://en.wikipedia.org/wiki/Open-source_software)  is sux
[free software](https://en.wikipedia.org/wiki/Free_software) is rox

Now look at [their license](https://code.visualstudio.com/license)

**Comment by 50Wliu** [comment]
Please keep this discussion on-topic and related to the original concern, that is learning from Visual Studio Code to improve Atom's performance.  Thanks.

**Comment by liujingbreak** [comment]
I recently want to port one of my ATOM plugin to Visual code extension, just found out a difference of VC using electron from ATOM is that the whole ATOM editor is in almost a single chromium browser window while VC is consist of multiple browsers, each editor is a separate browser window.

That might be why VC always starts more 'helper' processes than ATOM does, which also makes VC not able to be hacked, no way to hack DOM structure of VC, it doesn't expose that way like ATOM.

And I am guessing, this is one of the reasons why VC's UI feels more fast than ATOM, ATOM is like a huge web page with complex layout and different parts, while VC has couple web pages, each of them just renders simple UI content, has independent render process.

But I still like ATOM as its hackbility is super.

**Comment by russoue** [comment]
@liujingbreak's finding is interesting.  It reminds me of the difference between the Firefox and the Chrome browser. The latter is extending its lead everyday now with its superior performance and reliability.  I think if needed the Atom developers should re-architect the editor.  On my maxed out MacBook Pro (Retina, 15-inch, Mid 2015) VS Code is significantly faster than Atom.  As someone also mentioned I sometimes forget that VS Code is also written in JS.  Please do whatever needs to be done to make Atom the fastest editor out there, at least the fastest one written in JS.

**Comment by nathansobo** [comment]
We're working on a complete rewrite of the rendering layer [right now](https://github.com/atom/atom/pull/13880) and have spent a bunch of energy on deeper layers of the system. Optimizing the autocomplete menu is something on my radar that should improve typing responsiveness as well.

I know performance can be challenging to diagnose, but any concrete information on where and how you're noticing the lag would be really helpful. Keep in mind that Atom is very different from VSCode in that it's a core value of ours to allow packages to run in process and hook into low level editor events, so make sure you don't have a package that's ruining your experience. I'd like to someday get some better user-facing analytics on packages that slow down keystrokes.

**Comment by jcrben** [comment]
I feel kind of bad for posting this, but this is the gap you need to should shoot to close: https://blog.xinhong.me/post/sublime-text-vs-vscode-vs-atom-performance-dec-2016/

**Comment by 50Wliu** [comment]
Those benchmarks were performed before [significant large file improvements](http://blog.atom.io/2017/02/08/atom-1-14.html) were released, so those are now out of date.

**Comment by zinkkrysty** [comment]
I am using Atom-beta 1.18.0 and VS Code 1.12.1 (on Mac) and opening a 3mb xml file took 4 seconds on VS Code and takes more than 1 minute on Atom and maxes out my CPU. Not to mention I do not want to touch "Beautify file" function in Atom, VS Code performs it in less than 5 seconds.

So any optimizations done to Atom in regards to handling large files are paling in comparison to current VS Code performance (1600% better).

I love Atom but I cannot stop thinking about how VS Code manages to open and handle files so quickly, where Atom does not. Might be some low-level optimizations that are necessary, or the general strategy of handling streams. I do not know the internals of Atom, but de-coupling IO processing tasks from the UI sounds like a reasonable start.

**Comment by 50Wliu** [comment]
@zinkkrysty Performance is still a top priority.  Regarding low-level optimizations, we are currently in the process of dropping much of Atom's underlying text buffer code down to C++ to improve performance.  If you're interested, https://github.com/atom/superstring/pull/5 and https://github.com/atom/atom/pull/14435 contain the details.  While that change does not specifically address the time it takes to open a file, it should improve general editing performance once the file is opened.

**Comment by nathansobo** [comment]
@zinkkrysty Does this slowness reproduce in `--safe` mode? We have work to do for large files, some of which is landing soon in the aforementioned PRs, but a minute to load a 3mb file doesn't square with my experience.

**Comment by zinkkrysty** [comment]
Here's the file gzipped in case you want to try it. It's a public sitemap that is not beautified (has long lines). I haven't tried `--safe` mode yet

[autouncle_it1.xml.gz](https://github.com/atom/atom/files/1060291/autouncle_it1.xml.gz)

**Comment by ungb** [comment]
@zinkkrysty, can you provide which OS you're using and which version of atom you're using?  We have an issue in Windows that doesn't occur in mac or linux https://github.com/atom/spell-check/issues/190

Also since you aren't using safe mode can you provide the list of packages you have installed? `apm list` to get the community packages.
