### ISSUE TITLE
Autocomplete suggestions are rendered on top of panes other than the one that the suggestions come from when scrolling

### ISSUE THREAD

**Issue by MrEikono** [atom/atom#10192]
When using multiple panes stacked on top of each other, you can currently scroll with the mousewheel to move the selected pane's autocomplete suggestions so that they render on top of the other panes. The suggestions move out of view (as I expected them to) only after going past the end of the bottom-most pane.

**Steps to reproduce:**
* **1)** Have panes open in the editor arranged similarly to the ones in the image below.

![Panes](http://i.imgur.com/UzlEnjS.png)

* **2)** Enter part of a tag, selector, etc. etc. and let autocomplete suggest the rest of it for you in its tab.

* **3)** Scroll with the mousewheel. The autocomplete tab will move in the unwanted way.

**Expected behavior:**
I expected the autocomplete tab to move out of view, while staying inside the correct pane, when scrolling out of view, and to be viewable again once I got back to where the suggestions originated. 

[Here's a GIF showing this issue.](https://imgur.com/EKTaHQD)

**Comment by lee-dohm** [comment]
Thank you for reporting this. Problems with autocomplete should be reported on the https://github.com/atom/autocomplete-plus repository. Since there is an existing Issue there, https://github.com/atom/autocomplete-plus/issues/716, I'm going to close this in favor of that one.

You may want to subscribe there for updates.
