### ISSUE TITLE
Freezes when dragging Atom to left or right edge of the screen

### ISSUE THREAD

**Issue by arliang** [atom/atom#10218]
1. It works well when putting **two undefined tabs** into one pane.
   But it freezes when putting **two tabs(the same file opened)** into one pane, I have to relaunch Atom to solve this.
 
2. It freezes when **dragging Atom window to the left or right edge of the screen**, I solve this by re-sizing the Atom window.

All these are found in **Atom 1.3.2 (Windows 10)**. I didn't test in other versions or platforms.

**Comment by lee-dohm** [comment]
The first issue is almost assuredly a duplicate of https://github.com/atom/atom/issues/10043. The fix for it is in the Beta channel.

As for the second problem, what do you mean by "freezes" if you're able to get it back by resizing the window?

-----

In the future, please open separate Issues for each problem. This allows us to track things better by being able to close an Issue when the original problem is fixed.

**Comment by arliang** [comment]
I said freeze means the UI did not respond.
It also happens in atom dev-tool.
But I can't reproduce it just by now.
╮(╯﹏╰)╭
