### ISSUE TITLE
Entering path for new file or renaming file scrolls horizontally instead of vertically 

### ISSUE THREAD

**Issue by GradyD** [atom/atom#10242]
Super long path names scroll horizontally instead of vertically

**Comment by ntwcklng** [comment]
Current:
![](http://i.imgur.com/CSIcTsp.png)

Modified:
![](http://i.imgur.com/V9ZRaQi.png)

In order to get this, i removed the `max-height: 27px` in /Applications/Atom.app/Contents/Resources/app.asar/static/atom.less

And added `padding-right: 8px` to `atom-panel atom-text-editor[mini] { }` for a consistent look in /Users/ntwcklng/.atom/packages/native-ui/index.less

I think its much better, when the whole filename/path is visible instead of scrolling.
