### ISSUE TITLE
has "remove project folder" event?

### ISSUE THREAD

**Issue by xnat9** [atom/atom#10255]
has "remove project folder" event?
how to to get the folder path , when i remove project folder. thanks

**Comment by lee-dohm** [comment]
There is an [`onDidChangePaths` event](https://atom.io/docs/api/latest/Project#instance-onDidChangePaths) for when the list of root paths changes. In order to know what path was removed, you would have to know what paths existed in the project beforehand, but that isn't that hard.

Let us know if I misunderstood what you're asking!

**Comment by xnat9** [comment]
"In order to know what path was removed" ? how? onDidChangePaths callback projectPaths, which is left paths, is not was removed.

**Comment by xnat9** [comment]
why when newWindow is false, but isn't open in exist window for api atom.open?

**Comment by lee-dohm** [comment]
If you collect a list of project paths when your package is activated, then any time `onDidChangePaths` is called, you can get the paths missing from the second list that exist in the first.
