### ISSUE TITLE
I can not install atom editor in arch linux 

### ISSUE THREAD

**Issue by Wahab-Dev1** [atom/atom#10260]
![issue](https://cloud.githubusercontent.com/assets/15833995/12078441/cc15abd0-b212-11e5-8106-533397b72149.png)

**Comment by mnquintana** [comment]
How are you installing Atom? It looks like this is just a permissions error – have you tried installing as root?

**Comment by arcticicestudio** [comment]
Works fine on my system, but i install my AUR packages manually. Try to install is via `makepkg` and `pacman -U` if it fails as root too. May be a problem with yaourt.

**Comment by Wahab-Dev1** [comment]
!!!! i have no idea about this problem @arcticicestudio @mnquintana , the same problem with makepkg and pacman as root, please help

**Comment by arcticicestudio** [comment]
>("Unsupported package: Potentially dangerous ! )

Because I've never used yaourt, I don't know if it checks for a valid GPG signature in your keyring, but this message at the bottom looks some security checks have failed.
I've build atom own my own using my local custom pacman repository, so there is no way for me to test if the signature is invalid/missing on the keyserver.
Read this [Arch Linux WIki](https://wiki.archlinux.org/index.php/Pacman/Package_signing#Verifying_the_five_master_keys) article about verifying and adding keys, maybe it'll solve your problem.
If this isn't working too, try to contact the package maintainer of the [atom-editor AUR package](https://aur.archlinux.org/packages/atom-editor/).

**Comment by Wahab-Dev1** [comment]
Resolved : Sorry friends it just dependencies problem, thanks for all
