### ISSUE TITLE
File(s) opens in wrong window

### ISSUE THREAD

**Issue by molteber** [atom/atom#10283]
When having two atom windows open, one with a project and one without. If you want to open a file that belongs to the project opened in window 1, and opens the file in window 2, it will be opened in window 1 instead.

**Reproduction Steps:**
1. Open a project / folder, refered to as window 1
2. Open another atom window, refered to as window 2
3. Open a file in window 2 that belongs to the project / folder opened in window 1

**Expected behavior:**

When opening a file from a window, it is expected that the file will open in the window you try to open it in.

**Observed behavior:**

When opening a file from window 2, the file was added to the view of window 1.
This happens both when drag-and-dropping* and using the open file dialog 

\* from the explorer window. I can drag-and-drop from a atom window to another when dragging from tab to tab  
**Atom version:** 1.3.2
**OS and version:** Window 7 Enterprise 64-bit

**Installed packages:**
atom-pair@2.0.10
merge-conflicts@1.3.7
minimap@4.19.0
minimap-git-diff@4.1.8
script@3.3.0
Sublime-Style-Column-Selection@1.3.0

**Additional information:**
- Problem can be reproduced in safe mode: Yes
- Problem started happening recently, didn't happen in an older version of Atom: Unknown
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- Problem happens with all files and projects, not only some files or projects: Yes

**Comment by amytruong** [comment]
Thanks for the feedback! Some of the people here want to overhaul the file opening experience. This would most likely be part of that effort when it happens. :+1:

**Comment by lee-dohm** [comment]
I wrote these up for another Issue (https://github.com/atom/atom/issues/10724) and I think they're a little clearer on what the problem is.

I was able to reproduce this using Atom v1.6.0-dev-ed43eda on Mac OS X 10.11.3. Here are some more detailed repro steps:

1. Change to the directory where the `atom/atom` repo is stored locally (on my system it is in `~/Source/atom`)
1. Launch normal mode Atom with the command: `atom .`
1. Go back to the terminal using <kbd>Cmd+Tab</kbd>
1. Launch Atom in Safe Mode with the command: `atom --safe` (note: **do not** include the period)
1. Open the File Open dialog with <kbd>Cmd+O</kbd>
1. Navigate to the `appveyor.yml` file in the root of the repository and double-click it

**Expected:** `appveyor.yml` to open in the Safe Mode window
**Actual:** `appveyor.yml` opens in the normal mode window
