### ISSUE TITLE
No font subpixel antialiasing on OS X with retina display

### ISSUE THREAD

**Issue by emlai** [atom/atom#10291]
I noticed that Atom doesn't use subpixel font rendering on OS X El Capitan with a retina display. I've tried setting `-webkit-font-smoothing` to `subpixel-antialiased`, `antialiased` and `auto` in my stylesheet but all of them use grayscale antialiasing, not subpixel antialiasing.

Here's an example of how text looks like in TextEdit, with subpixel antialiasing (top), and the same in Atom, with the One Light themes and all settings at default (bottom):

<img src="https://cloud.githubusercontent.com/assets/7543552/12122809/0060da8e-b3e6-11e5-984b-cf13c13a8ed9.png" width="662" height="182">

I initially [reported this on the Atom support forum](https://discuss.atom.io/t/how-to-enable-font-subpixel-antialiasing/24185). According to a reply, this happens because Chromium doesn't use subpixel antialiasing on Retina displays.

So, is there any way to enable subpixel antialiasing or does Chromium completely prevent this?

**Comment by lee-dohm** [comment]
@zcbenz, do you have any insight into this?

**Comment by AndreasBackx** [comment]
@lee-dohm you can look at #1650 where I posted comparisons 1.5 years back.

**Comment by lee-dohm** [comment]
@emlai I've talked with the developers and what it boils down to is that there is no way to force Chromium to use subpixel antialiasing. The `-webkit-font-smoothing` CSS rule is a recommendation, not a requirement.

Because of our choice to use Chromium as the rendering engine, there will be differences between how Atom renders things and how other applications that use native font rendering display things. Unless we decide to switch completely to native font rendering across the board, this will continue to be the case. That change is far too expensive for us to consider at this point in time.

With that said, there are cases where there are bugs, not simply differences, in rendering and we are interested in finding and fixing those. If in doubt, please report any problems and we'll work with you to help track things down.

Thanks for your feedback!
