### ISSUE TITLE
Opening files that use atom:// URIs create fake folders

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#10297]
Opening Settings or any other file that uses a URI will cause a fake folder to appear in the Tree View (eg config, init-script) and `Settings - atom://config` or similar to show up in the titlebar. Reproduce by using a new window.

Tested using safe mode and also reported in #10194, atom/tree-view#690.

**Comment by lee-dohm** [comment]
This is harder to reproduce than it once was, but I still managed:

### Repro Steps

1. Open a Terminal window
1. Execute the command `rm -rf ~/.atom/storage`
1. Change directory to your atom/atom repository
1. Launch Atom with `atom --safe .`
1. Open a new window with <kbd>Shift+Cmd+N</kbd>
1. Open Settings View by clicking the menu `Atom > Preferences` (or any of the Create Your items)

**Expected:** Settings View opens without creating a project root
**Actual:** Settings View opens, Tree View opens and a fake `config` project root is created

**Comment by demhydraz** [comment]
Similar, probably related issue, happens if you open your keymap/init script/config/stylesheet. Reproduction steps are similar to @lee-dohm's:

1. Open a Terminal window
2. Execute the command rm -rf ~/.atom/storage
3. Change directory to your atom/atom repository
4. Launch Atom with atom --safe .
5. Open a new window with Shift+Cmd+N
6. Open your Keymap/Stylesheet/Config/Init Script by using the Command Palette.

**Comment by 50Wliu** [comment]
(@maxbrunsfeld: I assigned you based on your previous assignment in #8227)

**Comment by maxbrunsfeld** [comment]
OK, this bug is caused by changes that were made to allow custom directory providers. Currently, we add project folders even if `existsSync()` returns false for the corresponding `Directory` object. We have to do this because custom directory providers are not registered until after the Project has already been deserialized.

To fix this, we need to register custom directory providers before deserializing the project. We'll have to look for that service (`atom.directory-provider`) in packages' metadata, and conditionally require their main modules and register that service early.

Then, we can change `Project::addPath` to bail out of `Directory::existsSync()` returns false. Packages that provide the `atom.directory-provider` service (e.g. `nuclide`) will need to make sure that `existsSync()` returns true at first, even if the directory provider is not fully initialized (e.g. the user hasn't logged into the remote machine yet).

/cc @nmote @peterhal

We will start work on this shortly.

**Comment by peterhal** [comment]
Special casing the atom.directory-provider service during Atom initialization is extremely fragile.
The directory-provider implementation will need to be able to give an answer even though its containing package's Activate method has not been called.

IIUC the current order is:

- Atom deserializes the project state
- Atom attempts to restore previously open files/directories

- Atom activates packages

**Comment by nathansobo** [comment]
@peterhal: A big complaint from Atom users is startup time, and package activation makes up a large portion of that time. We want to move in the direction of activating packages later rather than earlier so we can give users feedback as soon as possible. So we don't want to do anything that would add an assumption of all packages being activated at a specific early phase of the startup process.

You're right that calling a service hook prior to package activation could be a surprising behavior, however, I'm not completely convinced that it's unworkable. Could you go into some specific details about how you see things potentially going wrong with this? Startup is a very performance-sensitive time for Atom and we're willing to make things slightly less convenient for package authors to do fairly niche things in the name of keeping our options for improving startup performance open.

**Comment by maxbrunsfeld** [comment]
Sorry for this weirdness everyone. This will be fixed in Atom 1.12. We will probably release 1.12-beta0 at the beginning of October.
