### ISSUE TITLE
Marker.getScreenRange() is empty on top-level folded row

### ISSUE THREAD

**Issue by benogle** [atom/atom#1031]
- Create a marker on a folded row
- `marker.getScreenRange().isEmpty()` returns true

It seems like this should return false. Note this example in find and replace:

![marker-view](https://f.cloud.github.com/assets/69169/1403163/013f3bdc-3cef-11e3-9377-25427c4587fb.gif)

**Comment by as-cii** [comment]
I couldn't reproduce the issue myself, partly because I didn't quite understand what was the expected final behavior (and I couldn't infer it from the attached gif).

Since this hasn't received attention lately, I have a couple of questions:

1. Was this solved?
  1. If yes, can we close the issue?
  2. If not, can you give more insights on how to reproduce the issue?

Thanks! :smile_cat:

**Comment by benogle** [comment]
It's still an issue. You can reproduce with find and replace:

1. Open coffee file with a class
1. cmd-f and search for a method name
1. Fold that method
1. Note that the marker view box hides when it's folded. This is because `marker.getScreenRange().isEmpty()` returns false on the folded line.

IMO, the marker view box should show when the method is folded because the method name is still visible.
