### ISSUE TITLE
"todo" and "hack" are highlighted in plain text files

### ISSUE THREAD

**Issue by Tyriar** [atom/atom#10354]
Little odd to have these words highlighted in the middle of text files, capitalization doesn't matter.

![todo_hack](https://cloud.githubusercontent.com/assets/2193314/12220220/8c504338-b71d-11e5-9f11-909d9cf51543.png)

Under Atom 1.3.3, Windows 10

**Comment by mnquintana** [comment]
That syntax highlighting is added by https://github.com/atom/language-todo/blob/master/grammars/todo.cson, and [is intentional](https://github.com/atom/language-todo/blob/master/grammars/todo.cson#L3) – this way you can write TODO (or similar) items in plain text files, and not just in comments in programming languages.

As far as I can tell, capitalization does matter:
<img width="606" alt="untitled_ _atom___about_and__todo__and__hack__are_highlighted_in_plain_text_files_ _issue__10354_ _atom_atom" src="https://cloud.githubusercontent.com/assets/823545/12221805/850bf8a6-b777-11e5-9b90-4be954716b48.png">

If you don't like this behavior you can always disable the language-todo package.

Let me know if I'm misunderstanding!
