### ISSUE TITLE
'CMD + W' will close an Atom window if no tabs are open

### ISSUE THREAD

**Issue by algt** [atom/atom#10410]
As the title says, hitting CMD + 'W' will close the entire window if there are no open tabs to close, despite the hotkey being set to Shift + CMD + 'W' for 'Close Window'.

Only happens as of 1.4.0, running OS X 10.11.2

**Comment by mnquintana** [comment]
Sorry for the confusion here! That was an intentional change added in https://github.com/atom/atom/pull/9607 to finally make Atom more consistent with other OS X apps. To disable this new functionality, just disable Close Empty Windows in Settings:

<img width="736" alt="settings" src="https://cloud.githubusercontent.com/assets/823545/12327409/3893b66e-ba8b-11e5-89e8-cbae601ad64f.png">

Hope that helps!
