### ISSUE TITLE
Convert from CoffeeScript to JavaScript

### ISSUE THREAD

**Issue by MetaMemoryT** [atom/atom#10418]
because of https://github.com/atom/electron/pull/4065

**Comment by lee-dohm** [comment]
We have no plans to convert wholesale from CoffeeScript to JavaScript at this time. Thanks for your passion and feedback!

**Comment by LongLiveCHIEF** [comment]
darn. Death to coffeescript.

**Comment by STRML** [comment]
This would be a boon not only to the performance of atom (e.g. argument splats use `[].slice.call()` which is death for V8 performance), but also to how it can be contributed to.

It would be nice if the team would express whether or not it is open to this sort of migration, so that a contributor can create a JS conversion with confidence.
