### ISSUE TITLE
Atom fails to create folder with same name of a file that already exists

### ISSUE THREAD

**Issue by jersten** [atom/atom#10434]
Atom 1.4.0 Mint 17.2 see pic:

![selection_001](https://cloud.githubusercontent.com/assets/7646510/12360051/9a6c9966-bb83-11e5-9e26-ef1c6f169422.png)

**Comment by StanleySathler** [comment]
Same happens when you try the opposite: create a file with the same name of an already existent folder. I think that it is from the Operating System, which returns it's own error.

I tried to prove this hyphotesis using:

**$ echo "Something" >> fileWithDirectoryName**, and got the error *fileWithDirectoryName is a directory*.

Got the same message when tried to create this file using VIM.

**Comment by jersten** [comment]
Yea, I do not think it's an atom issue; I can reproduce within Bash.

**Comment by lee-dohm** [comment]
The file system won't allow directories with the same name as files and vice versa (though variations in case are allowed on some file systems). Names have to be unique, Atom can't change that :grinning:
