### ISSUE TITLE
Unable to paste in "New Folder" input when saving file (OS X)

### ISSUE THREAD

**Issue by greggb** [atom/atom#10446]
Repro Steps:
- Attempt to save a new file or "save as" an existing file
- Click "New Folder" in bottom left of window
- Try to paste some text in the new folder input using Command-V keyboard shortcut

Expected result:
- Text is pasted as the name of the new folder

Actual result:
- highlighted text is not removed or un-highlighted
- text from clipboard is not pasted
- sadness

Additional Notes:
- You _are_ able to right-click and select paste, which works as expected.
- Actions in the Menubar's Edit menu are greyed out in this mode as well

**Comment by amytruong** [comment]
I was able to recreate this. Thanks!

**Comment by greggb** [comment]
Great, thanks Amy.

**Comment by kepta** [comment]
I was also able to recreate this, and further this is an electron issue.
As all electron apps suffer from this.

**Comment by zcbenz** [comment]
The new folder dialog opens as a new window instead of a sheet, I think that's why the copy/paste do not work.

OS X automatically decides whether a menu item should be enabled by checking its native `action` property, Atom doesn't set it so OS X disabled the copy/paste menu items in the new folder window. In Electron the `role` property of `MenuItem` is introduced to solved this problem, but it would then move the handling of the menu item completely to the system, which doesn't fit Atom's menu handling very well.

**Comment by kepta** [comment]
@zcbenz So is it possible to just set role property solely for this particular menuItem i.e. Save As?

**Comment by zcbenz** [comment]
@kepta No.

**Comment by Eptin** [comment]
I was able to reproduce this issue on macOS on Atom 1.19.5, which is currently the newest version.

**Comment by 50Wliu** [comment]
Sorry about that @Eptin.
