### ISSUE TITLE
Closed A Window And a Background Atom Window Closes too

### ISSUE THREAD

**Issue by GuacheSuede** [atom/atom#10480]
When does this happen ? Is it a bug ? The font window did not have any unsaved files

**Comment by GuacheSuede** [comment]
On what circumstances /conditions will atpm automatically close a background window, will ther ebe unsave/untitled buffers tehre and clsoed withotu  being saved Z?

**Comment by mnquintana** [comment]
Thanks for the report! We're going to need [a lot more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) to help you debug this though:

- What OS (and version) are you using?
- What version of Atom?
- Can you reproduce this behavior in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? (`atom --safe`)

**Comment by GuacheSuede** [comment]
Windows 8.1

1.4.0

Nope, all methods exhausted.

**Comment by 50Wliu** [comment]
Assuming "nope" means that you could not reproduce this behavior in safe mode.  In that case:

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
