### ISSUE TITLE
Clean up OS X Dock right-click menu

### ISSUE THREAD

**Issue by vtimbuc** [atom/atom#10513]
![mac image](https://vtimbuc.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-01-20-5-46-44-AM.png)

this looks messy

**Comment by lee-dohm** [comment]
Thanks for the feedback. Do you have any suggestions for rules to follow to make it look clean?

**Comment by vtimbuc** [comment]
![atom img](https://vtimbuc.s3-eu-west-1.amazonaws.com/atom.png)

More like this, a little bit more organized, maybe have the recent projects in a pop out menu like the options.

**Comment by valtlait** [comment]
Hey!
Is there a way to remove all the recent files from the list?

**Comment by glennleekg** [comment]
@valtlait 
For Mac, recent files list is located at ~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.github.atom.sfl

**Comment by valtlait** [comment]
Thanks, @glennleekg!

**Comment by lee-dohm** [comment]
It looks like this is fixed in the latest development version at least:

<img width="481" alt="screen shot 2016-06-29 at 1 47 19 pm" src="https://cloud.githubusercontent.com/assets/1038121/16468299/0a1e8d38-3e00-11e6-8cc0-25d8a8d48bec.png">

Let me know if you think this is still a problem on the current Stable version, v1.8.0. For now, I'm going to close the Issue unless there's more feedback.
