### ISSUE TITLE
Atom launch story is complicated and confusing

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#10517]
How to launch Atom in specific states is a bit of magic that is only known to a few. Some features are more obvious like Dev Mode and Safe Mode, but even then the full effects of each of these modes are not fully documented anywhere and therefore they are often misunderstood even by people who use these modes often. The purpose of this Issue initially is to capture the list of initial states that people want to launch Atom into. Eventually we will create a plan and design for making each of them easy, well understood and as obvious as possible to newcomers to Atom. If possible, I'll add links to other Issues, PRs, Discuss topics and other sources to illustrate.
## Atom Launch Modes

These are the modes that Atom more-or-less supports or are implied by the modes that Atom does support.
- Project (whether with single or multiple roots)
- No project &mdash; Open specific files with no tree view
- Restore last state (project or no project)
- Restore specific project state
- Dev Mode &mdash; Since this is designed as an aid for Atom development, it mostly only makes sense in combination with the project mode (but perhaps I'm overlooking something)
- Safe Mode &mdash; Can be combined with any of the above modes (other than Dev Mode)

Each of these should have an obvious and unambiguous way of launching them both from the command line and from the GUI.
### Additional Command Line Thoughts

Sometimes people want to modify the state of Atom from the command line and sometimes they don't. Some consideration should be given to these scenarios:
- Add a file to an open session of Atom
- Add a project root to an open session of Atom
- Launch Atom in any mode when an open session of Atom is running (even when it may seem the user may want one of the two above but doesn't ... for instance "open a file that exists in the project that is open in the current session of Atom, but I want it in a new Atom session with **no** project")
## Mode State

There are things that are serialized and stored when Atom exits. It is completely non-obvious what items belong to this set and what items do not as well as how to restore the saved items when next launching Atom. Decisions should be made about whether some of these items belong to the specific mode that Atom is in or if they are more global state that people expect to be in place the next time Atom is launched (or even an individual file is opened post-launch) no matter what mode Atom is launched in.
- List of open tabs
- Editor state &mdash; Where the cursor is in the file, etc
- Unsaved changes to files
- Untitled buffers
- Per file indentation settings
- Per file line ending settings
- Per file encoding settings
- [Pane configuration](https://github.com/atom/atom/issues/10545)

**Comment by jeancroy** [comment]
Regarding `Unsaved changes to files` & `Untitled buffers` across the different projects state, I'd like to propose a start notification along the line of 

    Atom have made a backup copy of the following modified files in a different project:
       - SomeFile
       - SomePath/SomeOtherFile
       - Untitled *snippet of first line*  
     [Click here to open project XYZ]



Regarding the existence of the different project state maybe a `recent projects` list can be useful.


Lastly it's not super clear how [serialization](https://atom.io/docs/v0.189.0/behind-atom-serialization-in-atom) for package author is scoped. Global or per project ? Any chance to have both and choose ?

**Comment by calebmeyer** [comment]
+1 to adding another project root to running atom. I like one window per project (most of the time), but I know my coworkers like to bring up their whole workspace (all the projects we work on) at once.

I'd also like (occasionally) to bring up something like a dotfile (.zshrc?) in my current instance of atom without opening up my dotfiles dir.

**Comment by stereobooster** [comment]
Related:
 - https://github.com/atom/atom/issues/10528
 - https://github.com/atom/atom/issues/12860
 - https://github.com/atom/atom/issues/11853
 - https://github.com/atom/atom/issues/11293
 - https://github.com/atom/atom/issues/12904
 - https://github.com/atom/atom/issues/10474

**Comment by anatoli26** [comment]
Could someone please comment on what's happened to the already complicated and confusing story  in Atom 1.12.1-3 on Linux (don't have other OS to test)? Before (1.11.x) when the editor was already opened and I was opening a new file with Atom from cli o using the shell integration (Open with Atom or double-click on associated file type), the new file was added to the currently opened Atom window.

Now, no matter if the window is opened or not, opening a new file always opens it in a new window. What has changed? How to restore the previous behavior? And better yet, (how to|please) implement the behavior as requested in a number of issues, that were all consolidated in the #9643?

**Comment by anatoli26** [comment]
FYI, just found the cause of this particular problem: #13326.

**Comment by lee-dohm** [comment]
Related: https://github.com/atom/atom/issues/13488

**Comment by earthbound19** [comment]
My preference default behavior would be "Restore Last State" (such as in Notepad++, Quiver, and every other advanced text editor I've used behavior). Atom repeatedly forgets what open files I had when I restart it, and I have no idea why, and it's a deal killer. My strong preference would be for advanced features (which IMO projects are) to be *disabled* by default, to be enabled by folks who have any idea how the &*#! :) they work.

**Comment by calebmeyer** [comment]
@earthbound19 I also love that notepad++ remembers the exact state it had last every time I open it. The only time I've had atom discard my state was when I intentionally summoned it using `atom .` or `atom --clear-window-state`.

However, I depend on the project related features all the time. Built in features like the fuzzy finder don't work if you don't have a list of open projects to search through. Extensions like git-plus also would not work correctly. If you don't like projects, you can almost entirely avoid them just by closing/disabling the tree-view.

**Comment by earthbound19** [comment]
The tree view often re-opens when I don't expect it. I must always re-close it; I've never had a use for it, as it doesn't behave like my OS navigator; --for me it's an annoyance. My OS is my file navigator. I prefer not duplicating OS functionality in my text editor.

Also could there not be (or is there not) an active dependencies check for every plugin?

I think this preference stands between laypeople and experts. I *strongly* suggest preferring the layman behavior where the expert behavior can easily be enabled.

In my strong opinion, the "startup story" (whatever the heck that really means--a "story?") seriously needs simplification.

PLEASE, Atom, for the love of people who know less than yourself ;) simplify. Especially, I think it should not be imposed on folks with simpler use cases to disable features for advanced use cases which they probably don't understand--so they don't even know to disable them; they are just confused. Look at the virtually countless issue reports flowing from this (linked from this issue). It is a serious source of confusion and a turn-off; and wherein it causes more trouble for noobs than it does for experts, there is no compelling reason to leave advanced features on by default.

**Comment by underctrl** [comment]
@calebmeyer said:

> If you don't like projects, you can almost entirely avoid them just by closing/disabling the tree-view.

I find this to be untrue... The "everything is a project" mentality seems to be fully baked-into Atom, and without the tree-view popping open as a reminder of that, then certain things seem even more "magical" when they happen...

As an example, here is a scenario that is one of my "deal breakers" (to use a phrase from someone else above...)

I'll open several, entirely unrelated, individual files - and I would never expect them to then be forever associated with each other. However, with Atom, that is exactly what happens... Because I'll exit out of Atom entirely, then later reopen Atom (empty, with no files open) and reopen just one of those files and, whether I like it or not (I do _not_), all those other, entirely unrelated files will auto-open right alongside it (as though they're all part of some parent project, which they're not, except that Atom shoe-horned them into one).

And the only way to prevent this is to close each and every tab I have open _before_ I exit the entire editor... Which is a huge pain and is something I shouldn't have to do.

For the record, my perfect "persistant state" story would look like this:

1) Atom acts like most other editors do whenever I open _individual files_, and shouldn't try to force them into any kind of persisted-state (shouldn't group them together, shouldn't create a "project" around them, should ask me to save changes on exit, etc) unless I have special features enabled/disabled (remember/forget my last open state, do/don't auto-open a file's parent folder as a project when no other project is open, ask/don't ask to save files on close, etc...)

2) Atom acts like a more-advanced IDE whenever I open _a folder or multiple folders_ - Once I've done that, I can expect to be inside a "project" (and the tree-view should pop-open, etc) whose state is only persisted when I later reopen said project - meaning if I reopen a single file that _just so happens_ to exist within a project I've opened before (but that isn't currently open), don't force me to reopen the entire project... I only wanted to open that single file...

Thank you for listening - I've only recently discovered Atom and it instantly made me want to switch from Notepad++ (even though I've been using it for 10+ years), except for this idea that "it'll do everything for you automagically" even though I'd rather actually know exactly what's going on with my files at all times please :)

**Comment by underctrl** [comment]
The more I read through Atom's history, the more I feel I shouldn't hold-out hope for Atom to work any differently than how it already does... Which is fine (you do you, Atom)... I just wanted to provide this declaration as a follow-up to my previous comment...

I say this mainly because I keep finding comment after comment like [this one](https://github.com/atom/atom/issues/1847#issuecomment-42521114) (which is from three years ago):

> Would be nice to be able to disable automatically opening the parent folder when opening a file.

Note, also, that the linked issue has many follow-up comments (even as recently as April) like:

> this seemingly will never be addressed

p.s. I realize that this could possibly be addressed with a custom package (and I might just look into it)... However, I feel (personal opinion here) that a text editor should handle single files _first_ and groups of files _second_ (as a "progressive enhancement" to simple, bare-bones, single-file editing). As it is, it seems to me like Atom is suffering similar problems as CommonMark - namely, that people can't all agree on what should be in the "core" of the thing and what should be an "extension"...

**Comment by maltalef** [comment]
hello? do you guys think this super old thing about **"whole directory being added each time a single file is opened"** is ever going to be looked at? sorry to be mean but I'd really like to know if learning the ropes for this editor will end up a waste of time for me :/

**Comment by lee-dohm** [comment]
@maltalef your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

I can understand your frustration at issues you care about not being addressed. Intentionally being mean about it isn't the way to get what you want, though.

**Comment by maltalef** [comment]
@lee-dohm I'm sorry about that, you're right. If there's any indication of plans to address this in the mid-term future that you could publicly speak of, I'm honestly interested, since there's not much recent activity on this issue. Sorry again for the tone, it was uncalled for.

**Comment by lee-dohm** [comment]
Thanks @maltalef, I appreciate that :grinning:

I don't have anything to report right now. However, I would recommend keeping an eye on the [weekly focus docs](https://github.com/atom/atom/pull/16763) that the team has started using. It's something we're experimenting with to try and keep the community more informed of how the maintainer team is investing its energy.

**Comment by Crapshit** [comment]
It would be great to have this here finally:
No project - Open specific files with no tree view

Always adding the complete folder as a project is anoying and slow.
Sorry, but it is how it is.

It would be great to see an update here.

**Comment by chuntr** [comment]
I'm a little astounded to find out that a problem I've experienced for years (where upon re-open after a crash usually, the project folder list is empty and I have to rebuild it completely) is probably intentional behavior. I would wholeheartedly agree that the actual behavior is complicated and confusing because I had no idea that Atom behaved in such a context-specific way.  And unlike many others, I'm nearly always opening Atom with exact same method, from a shortcut icon.

I started researching this today because while I'm normally using the Linux build, today I saw similar behavior on my Mac, which has a different version of Atom. Specifically when I did a "Restart and install update", it didn't re-open, so I started a new process, and found the project folder list empty. However I noticed the dock icon still indicated a process was open, so I probably just did not wait long enough. I did a second "Restart and install update", and this time the process completely terminated and restarted on it's own, and the project folders were then restored. In hindsight, I highly suspect that seeing this happen on the Linux side was probably due to the crashed process not being fully closed (or left in a bad open state), and the restart app dialog actually opens a "second" instance in a new project context.

I guess the point of all this is to note that there are other use cases where the launch behavior can lead to a situation that appears "buggy" (but is not), even when launching Atom via the same method. 

A more important point is that while the way Atom behaves when opening is flexible and may be actually quite powerful, it's definitely not intuitive. I had assumed like many others in related issue comments, that the list was a "pinned" set of different project folders, and not that each set of folders was defined in it's own project. I'm not sure what dictates your priorities, but I can say without question this is the number one thing that has always bothered me about Atom. It's almost disappointing to now find it's not even really a bug.
