### ISSUE TITLE
Opening multiple windows with the same folder(s) leads to improperly restored state

### ISSUE THREAD

**Issue by hansonw** [atom/atom#10528]
Repro:
1. Open two windows with the same set of folders open.
2. Open different files in each window.
3. Close Atom with `cmd + q`.
4. Restore Atom from the Dock/Finder. Both windows will have the state of one of the previous windows; the other is permanently lost.

I understand this is due to the way Atom saves project state - it appears to be based off a hash of the set of working directories (which is recorded in `~/.atom/storage/application.json`).

I don't have a great proposal about how to fix this; perhaps in the case of multiple windows the hash could include the window index? It seems to be a fairly uncommon use case, anyhow.

**Comment by xixixao** [comment]
This is not an uncommon use case, if you are for whatever reason splitting your workspace across windows. Bad bug.

**Comment by hansonw** [comment]
@benogle: The repro in the task description seems pretty clear, and this is still the case with 1.5.3 (also in safe mode). Do you need any other information?

**Comment by benogle** [comment]
The steps seem good, we just need a person to reproduce it and spend some time thinking about what we might do to combat this.

**Comment by ramikassab** [comment]
This has been a bug that has been around for quite some time and has really messed with my workflow. I sure hope we do find a solution to this. I quite often work on the same project across multiple windows and panes. I typically organize organize my windows and panes by file type (HTML in one, CSS in another and JS in another) and also by project areas. I work on a large complex website platform that's built on top of Django and is comprised of MANY applications that each add their own bits of functionality to the platform. It's imperative to be able to segregate everything in order to keep my workspace sane.

I'm not sure as to which window it is that Atom chooses to be the set of tabs and panes it restores but I think it might be the first one that wins. Regardless, if I have to quit Atom for any reason, restoring it opens the same number of windows I previously had opened all working on the same project but each of the windows shows only the tabs from the winning window (I believe it's the first) before Atom was closed. This means that I lose the tab information for any other losing window(s) that were opened and I have to recreate my workspace from scratch. It's very frustrating especially since the files you have open tend to remind you what area of the platform you left off on.

Atom's project state saving logic simply needs to be expanded to store separate tab and pane information for each of the project's windows. The only way I've been able to skirt my way around this a bit has been to open up each window with slightly different project folder selections. This fools Atom into creating a separate saved state for each window but this is far from ideal. I really do want all of the same project folders to be available in every Atom window.

Has there been any further discussion on the forums around this? I'm a bit surprised that reports and discussion around this very undesirable state saving and restoration behavior seem quite scarce. We really can't be the only people working on the same Atom project across multiple windows.

I'd be happy to offer whatever assistance is needed in further defining this bug and compiling videos to demonstrate the behavior. It's really quite easy to re-produce. A solution to this really doesn't seem like it'd be that difficult either. The state saving logic just needs to be expanded to recognize each of the project's windows as separate entities with their own tabs and pans that would need to be restored rather than just picking one windows state and only restoring that. Atom is already restoring the same number of project windows I had open, it's just using one of the windows' states and restoring that for each of the restored windows.

**Comment by lee-dohm** [comment]
I've reproduced the described behavior using Atom v1.10.0-dev-08a3582 on Mac OS X 10.11.5.

**Comment by haoliu119** [comment]
Bug still exists on the latest release for Mac. This messes with my workflow because I use multiple monitors.

**Comment by lee-dohm** [comment]
This isn't a bug. The project system (and by extension the project state storage system) wasn't designed to support multiple copies of the same project (as defined by the set of project root folders) open at the same time. While it may be useful to some workflows to have that ability, it isn't something that we're going to be redesigning Atom's project system to support anytime soon.
