### ISSUE TITLE
Atom Linux deletes data on remote filesystems

### ISSUE THREAD

**Issue by jrkoenig** [atom/atom#10580]
Atom on Linux deletes data on remote filesystems like sshfs in a somewhat contrived but real worlds scenario (this has happened to me twice now):
1. Remote FS is mounted, open file in Atom.
2. Close Atom. Filename is saved so it is automatically opened next time Atom is started.
3. Unmount FS.
4. Open Atom. File is automatically opened, but because it is not mounted, the buffer is empty.
5. Mount remote FS.
6. Switch to the empty buffer file.
7. Contents of file are now deleted, i.e. Atom saved its empty buffer to the disk, overwriting the existing data with nothing. No prompt or warning is given to the user.

This is happening on Atom 1.4.0.

**Comment by glebtv** [comment]
This is also reproducible on atom 1.5.3 on windows using simple samba network shares. And i've seen it on mac also using sshfs.

**Comment by paulondc** [comment]
I'm getting this issue in atom 1.6.2 when handling files from a sshfs mount in osx. 

By just trying to load a folder that is under a sshfs mount inside atom, it shows the directory structure perfectly. Also, the 'search in project' is able to find and display all matches perfectly. But it seems there's a bug when a file gets loaded in the 'editor' that makes the editor to show an empty file (since the "file in project" is able to look through the file contents).

**Comment by paulondc** [comment]
There is a duplicated issue about this: https://github.com/atom/atom/issues/11327
