### ISSUE TITLE
"Ignored Names" in Preferences has no effect in TreeView

### ISSUE THREAD

**Issue by yalla** [atom/atom#10684]
The list of ignored names in the preferences don't have any effect in the TreeView. Letting it to the defaults still shows files/directories like .git, Thumbs.db and the such. Even explicitly defining these has no effect.
Starting atom in safe-mode did not help.
The error is there since I installed it in the first place and I didn't bother to report it until now.

OS: OSX 10.10.5
Atom build: 1.4.3 (official build from website)
Installed additional community packages:
* git-plus
* plantuml-viewer
* vim-mode

I've attached a screenshot. Anything else I need to provide?
![bildschirmfoto 2016-02-04 um 13 41 38](https://cloud.githubusercontent.com/assets/350047/12815347/35b88930-cb46-11e5-8585-c31c4dc2d30a.png)
Thanks, Alex.

**Comment by 50Wliu** [comment]
Tree View has a separate options "Hide VCS Ignored Files" or something like that which you need to enable in order to hide those files (alternatively, try pressing <kbd>i</kbd> while the Tree View is focused).  Hope that helps!

**Comment by yalla** [comment]
You probably mean "Exclude VCS Ignored Paths"? That is also enabled. Pressing "i" didn't help either. I'm kinda lost. It's not like my life depends on it, I'm just wondering if I'm doing something wrong.

**Comment by lee-dohm** [comment]
He meant "Hide VCS Ignored Files" in the Tree View Settings:

<img width="792" alt="screen-shot-hide-vcs-ignored-files" src="https://cloud.githubusercontent.com/assets/1038121/12829643/14749b98-cb40-11e5-9789-59792b5a34b8.png">

1. Launch Atom
1. Open Settings View with <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on other platforms
1. Click the Packages tab
1. Search for "tree-view"
1. Click the Settings button in the tree-view package box
1. Check "Hide VCS Ignored Files"

Pressing <kbd>I</kbd> probably didn't help because you have to have the Tree View focused before it will work.

**Comment by yalla** [comment]
@lee-dohm Thanks, that helped, although I also had to check "Hide Ignored Names". "i" didn't work because I don't have a .gitignore file (I guess) in some project directories. I find it a little confusing that the Ignored Names from the Core Settings don't have any effect unless you check the "Hide Ignored Names" in tree-viewer's settings. Thanks for your support!

**Comment by lee-dohm** [comment]
I'm glad that I was able to help. We agree that this is confusing. We just haven't thought of a better system yet :laughing:

Thanks for using Atom!
