### ISSUE TITLE
Proposal: API enhancement for editors with block decorations

### ISSUE THREAD

**Issue by abe33** [atom/atom#10699]
I fiddled with the block decoration features to check how this would affect the minimap and as I suspected it completely breaks the sync between the two views.

The biggest concern I have for the moment is that there is no public API to get the height and the y position of a line with a block decoration attached. Since I guess these are quite costly operations that are already handled by the editor's view I would expect it to expose these informations publicly so that we don't need to traverse all the editor's layers and decorations to compute these values. 

Another approach would be to have two sets of scroll values, one that account for the decorations and one that doesn't. For instance with a block decoration of 100px height at one line, the first method would return a scroll height equal to the height of all lines + 100 and the other one would return the just the height of all lines. Same goes for the scroll position, the first one would returns the scroll as it's used in the view, the other one would return the scroll position ignoring the block decoration (clamping the value to the start/end y of the line depending on whether the block is displayed before or after the line).

A third possibility is to have a scroll position defined as a couple of value: the first visible line index and a position within the line (in the range 0-1). If we have access to the line y position and height through an API, we can compute the corresponding scroll top, or map this to any other type of grid and still be in complete sync with the editor.

Another concern for the minimap is that block decorations breaks the assumption that an editor's lines all fit on a predefined grid. It means that I can no longer use a ratio to transpose a line height and position and still get an integer value at the end - let say a line takes 17px in the editor, and 3px in the minimap, I can always assume that line 11 will be at y=30px in the minimap. Now with block decorations, a line can have an arbitrary height, which means that if I apply this ratio to get the line height I'll probably end up with a decimal value. And as the minimap is using a canvas, decimal values need to be avoided at all cost to preserve the crispness of the minimap render. To workaround that I would probably need to map every line heights from the editor to a rounded value more suited to the minimap. But same thing here, it would better if I could avoid traversing all the editor's lines to make this computations. 

How do you feel about this?

cc/ @nathansobo, @as-cii

**Comment by abe33** [comment]
So, after discussing that with @as-cii I may be able to wrokaround the lack of API. So I close the issue for now and I'll reopen if I see that I can't do without some changes in the editor API.

**Comment by abe33** [comment]
Sorry for the late follow up, I got a carried away with other things. 

So I just started to look at the feasibility ot the solution we discussed with @as-cii, namely using `pixelPositionForScreenPosition` to get the line offsets and deduce the line heights from that, but sadly it looks like a no go from a performance point of view. 
I'll spare you the implementation details, but basically, when rendering the minimap I need to know the first and last visible rows in the minimap, previously I could just get these values by using simple arithmetic involving the scroll ratio, the editor's height and the line height (which was constant). With block decorations I need to call `pixelPositionForScreenPosition` for pretty much every line so that I can find which is the first and last visible rows. I made a quick test on a ~440 lines file and computing the offsets takes ~1.2s, on a ~1820 lines files it takes ~6.3s, and this is just by calling the function for each line and push the top value in an array. As you can imagine, the longer the file the longer it will take to process these offsets.

So, as is, I fear I'll have to abandon the idea of supporting block decorations in the minimap (I mean supporting the offset applied by these decorations). Sadly it's now already in use and the first related issue just landed (atom-minimap/minimap#462).

Ideally, I want to be able to render a placeholder in the minimap for block decorations so that the scale of the minimap says consistent with the editor, but a solution that would allow me to at least keep the minimap in sync when the editor scroll would be enough. In the end I still think there's a need for an API that allows packages authors to work with block decorations and editor's scroll in a smooth way. As is, the cost is too important if we have to use `pixelPositionForScreenPosition` for that.
 
I'm open to any suggestions on this matter.

cc @atom/feedback

**Comment by lee-dohm** [comment]
> With block decorations I need to call pixelPositionForScreenPosition for pretty much every line so that I can find which is the first and last visible rows. I made a quick test on a ~440 lines file and computing the offsets takes ~1.2s, on a ~1820 lines files it takes ~6.3s, and this is just by calling the function for each line and push the top value in an array.

Since you don't need the position of *every* line, just the first and last visible ones, could you use a binary search pattern to find them? This should reduce it from an O(n) to an O(log n) operation, yes? I don't know if that will help enough ... but it is worth a try, I would think?

It looks like there is an average of about 3ms ± 1ms per line in the above measurements. If that holds, the average case for the 440 line file should be 9 lines * 3ms per line * 2 (for both first and last) = ~54ms and 11 lines * 3ms per line * 2 = ~66ms ? Please double-check my calculations because my maths are pretty rusty :laughing:

**Comment by abe33** [comment]
> Since you don't need the position of every line, just the first and last visible ones, could you use a binary search pattern to find them

I'll do need their position when rendering them, since each line can have a different height due to the block decorations they'll have a different location in the minimap, and I need to compute that location. It's also the case for every decorations displayed in the minimap. And a typical minimap displays easily four to five times the amount of lines in the editor. 
But even if I use a binary search and let's assume its cost is close to your estimation, I need to do that operation on each frame during a scroll and on each change in the editor. 54ms is clearly out budget. And there's the cost of building and updating the tree, updates which occurs on potentially every changes made in the editor. 
Actually, a repaint on scroll or edit with dozen of decorations is between 2ms and 4ms depending on the size of the window and the minimap settings. 
I can't make all the efforts on performances made in the past months go to hell because of a single feature that most users willl probably never encounter. I wish I could easily support them, but that's not the case, and I'm really wondering if it's worth the effort. I mean I won't rewrite all the minimap and killl the performances just for that.

**Comment by abe33** [comment]
I do think there's a need for a text editor element API around that, we need to be able to get this kind of information without losing performances.

**Comment by as-cii** [comment]
Hey @abe33, thanks for the thorough write-up. Could you profile what's slow in the benchmark you have performed and post it here? I suppose that `pixelPositionForScreenPosition` is slow because it's forcing some DOM elements to be added on screen, thus involving some pretty serious layout thrashing (i.e. if a line isn't visible because of the current scroll position, we add it and then remove it after measuring it).

> I do think there's a need for a text editor element API around that, we need to be able to get this kind of information without losing performances.

If the assumption above is correct, I wonder if we can just add a performance optimization to `pixelPositionForScreenPosition`, which won't involve the DOM at all if the asked position is `{row: y, column: 0}`. :zap: 

If that is still slow, we might want to expose the `LineTopIndex`, which in turn could provide an iterator that would enable an in-order traversal of the tree without the need of necessarily starting from the root node every time we want to know the position of a contiguous set of lines. You would use it like this:

```js
let startRow = 100
let endRow = 400
let iterator = textEditorElement.buildLineTopIterator()
iterator.seekToScreenRow(startRow)
do {
  let top = iterator.getTop()
  // perform the needed math
} while (iterator.getScreenRow() < endRow && iterator.moveToSuccessor())
```

I'd resort to this only if the more high-level `pixelPositionForScreenPosition` approach described above is not enough.

Thoughts? :thought_balloon:

**Comment by abe33** [comment]
> Could you profile what's slow in the benchmark you have performed and post it here

Sure things, here the CPU profile: 
https://gist.github.com/abe33/28b62272790fc591e964

**Comment by as-cii** [comment]
Based on the CPU profile above, we have confirmed the assumption that converting screen position to pixel positions causes some pretty serious layout thrashing.

So, after talking about this with @nathansobo, we concluded that optimizing `pixelPositionForScreenPosition` in the `{column: 0}` case is not sufficient, as it provides unpredictability both in terms of performance (calling that method is :racehorse: in some cases, and :snail: in others) and behavior (soft-wrapped lines may not have a `0` screen column, so we need to deal with that differently).

Thus, we concluded that some new APIs are necessary in order to query block decorations and lines in a fast and performant manner. :zap: The new methods we have in mind are:

* `TextEditorElement.prototype.blockDecorationsForScreenRowRange(startRow, endRow)`
* `TextEditorElement.prototype.verticalPixelPositionForScreenRow(row)`
* `TextEditorElement.prototype.screenRowForVerticalPixelPosition(pixelPosition)`

We want to expose all three of these methods under `TextEditorElement` as they all describe spatial attributes of lines and block decorations. Their usage in minimap might go like the following:

```js
let minimapScrollTop
let minimapScrollBottom = minimapScrollTop + minimapHeight

let minimapScrollTopInEditor = minimapScrollTop * scaleFactor
let minimapScrollBottomInEditor = minimapScrollBottom * scaleFactor

let firstVisibleRowInMinimap = editorElement.screenRowForVerticalPixelPosition(minimapScrollTop)
let lastVisibleRowInMinimap = editorElement.screenRowForVerticalPixelPosition(minimapScrollBottom)
let blockDecorationsByScreenRow = editor.blocksDecorationForScreenRowRange(firstVisibleRowInMinimap, lastVisibleRowInMinimap)

let blockDecorationsForRow5 = blockDecorationsByScreenRow.get(5)
for (let blockDecoration of blockDecorationsForRow5) {
  let {decoration, height} = blockDecoration
  let {position, item, minimapItem} = decoration
  if (position === 'after') {
    // render after
  } else {
    // render before
  }

  if (minimapItem) {
    // render custom minimapItem
  } else {
    // render placeholder
  }
}
```

This should be very efficient in the case of computing visible rows in the minimap, as I think the overall cost of the function approximates to `O(n)` in the worst case, where `n = lastVisibleRowInMinimap - firstVisibleRowInMinimap`. As a bonus, with this approach people might provide a custom `minimapItem` for atom-minimap to render instead of a placeholder: that's totally optional though, and I guess that item needs to be something like a canvas so that you can copy its pixels right into the minimap canvas.

@abe33: what do you think? It'd be awesome to get your feedback on the proposal above, so that we can start implementing those APIs and provide them right in the next beta (or maybe even in a hotfix?).  :sparkles: 

Thanks!

**Comment by abe33** [comment]
Sorry for the late reply I was at work when I posted the profile, I wanted to reply more in depth about you previous proposal but I just forgot ^^. So I'll reply only for your latest proposal. 

As far as I can tell it's much closer to what I was suggesting in my first post.

> The new methods we have in mind are:
> -  TextEditorElement.prototype.blockDecorationsForScreenRowRange(startRow, endRow)
> -  TextEditorElement.prototype.verticalPixelPositionForScreenRow(row)
> -  TextEditorElement.prototype.screenRowForVerticalPixelPosition(pixelPosition)

:+1: Looks perfect for the minimap use case. I'm already seeing how I will be able to use these methods, there might be a bit of a performance loss in the minimap before I completely grasp how to make use of these new APIs but it looks like a good start. 
Maybe I would add a method to know whether a text editor has block decorations or not so that I can switch the implementation and keep the current one for editors without block decorations (at least it should make the migration less painful for users that don't use packages that create block decorations).
In combination with the `onDidAddDecoration` event I could even switch the implementation after the creation of the editor.

> As a bonus, with this approach people might provide a custom minimapItem for atom-minimap to render instead of a placeholder

That would be totally awesome! 

>  that's totally optional though, and I guess that item needs to be something like a canvas so that you can copy its pixels right into the minimap canvas.

Exactly, there never was a good way to copy HTML into a canvas, the only method currently available involve converting the markup to XML and then render the XML into the canvas, but there're many security issues that make it really hard to use (images, fonts, styles may not be loaded properly due to sandboxes). Another way to achieve the same result would be to pass a function instead of a bitmap so that I can call that function with the contextual data so that the package can creates the proper placeholder based on the current state of the minimap. But that's not really urgent to settle on that, we'll see how block decorations get adopted and if the need for a specific API on the minimap is required for that as well.

> we can start implementing those APIs and provide them right in the next beta (or maybe even in a hotfix?)

Just beta should be fine, I don't think block decorations are so widely spread yet that it would require a patch on stable immediately. And I'll be able to switch the implementation if needed based on the presence of these new methods on the text editor element class so that people using stable still get a working minimap (even if block decorations lead to inconsistencies in the render).
