### ISSUE TITLE
Way to use Canary dev tools

### ISSUE THREAD

**Issue by jordwalke** [atom/atom#10726]
Hello,
There are some new features in the Canary developer tools that I would like to use while debugging Atom plugins. Does anyone know how to do this?

**Comment by 50Wliu** [comment]
@jordwalke I don't believe so.  You'll have to wait until Atom updates to a version of Electron that has the new features that you're asking for.  Sorry!

**Comment by jordwalke** [comment]
Is there any way to merely build Atom against the latest Chromium?

**Comment by 50Wliu** [comment]
@jordwalke The problem is that Atom doesn't directly depend on Chrome - it depends on Electron, which in turn runs a specific Chrome version.  To build Atom against the latest Chrome, you'd have to first update Electron to that Chrome version, which as I understand requires a considerable amount of work in different submodules.

**Comment by jordwalke** [comment]
Cool, thanks for the info. I'm guessing that I would manage to get that working if you happen to stumble upon useful docs related to the matter.
