### ISSUE TITLE
Atom --safe is talking to other Atom instances

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#10724]
`atom --safe` spawns an (supposedly) isolated instance of Atom without any plugins/themes, but the reality is that the "safe" instance isn't isolated.
1. Open a normal Atom instance.
2. Open a "safe" Atom instance.
3. Try to open a file from the "safe" Atom instance. 
4. Bug: file is opened in the normal Atom instance window

**Comment by lee-dohm** [comment]
I was able to reproduce this using Atom v1.6.0-dev-ed43eda on Mac OS X 10.11.3. Here are some more detailed repro steps:

1. Change to the directory where the `atom/atom` repo is stored locally (on my system it is in `~/Source/atom`)
1. Launch normal mode Atom with the command: `atom .`
1. Go back to the terminal using <kbd>Cmd+Tab</kbd>
1. Launch Atom in Safe Mode with the command: `atom --safe` (note: **do not** include the period)
1. Open the File Open dialog with <kbd>Cmd+O</kbd>
1. Navigate to the `appveyor.yml` file in the root of the repository and double-click it

**Expected:** `appveyor.yml` to open in the Safe Mode window
**Actual:** `appveyor.yml` opens in the normal mode window

**Comment by lee-dohm** [comment]
With that said, Safe Mode isn't intended as a completely isolated environment. It is designed to launch a session of Atom without:

* Loading community packages
* Executing the `init.coffee`
* Possibly other things I'm forgetting

I just did a simple test in the Safe Mode window I still had open from my repro steps above. I attempted to execute a command from my [tabs-to-spaces package](https://atom.io/packages/tabs-to-spaces) and it wasn't available in the Safe Mode window. It was available from the normal mode window.

**Comment by alexandernst** [comment]
Even so, I'd expect to be able to open files in the safe editor (if I have more editors open). Anyways, the mere fact this is happening proves that there is come kind of communication between atom instances, which could be a place for bugs to appear.

**Comment by lee-dohm** [comment]
I agree that people should be able to open files in the intended instance (which is why I labeled this as a `bug`). If solving that isn't your intention with this Issue and you want Safe Mode to be a complete isolation from the other running instance, that's an architectural thing that should be addressed separately.

Should I open another Issue for the file open bug?

**Comment by alexandernst** [comment]
@lee-dohm Yes, another issue for the file open bug would be fine, thank you!

**Comment by lee-dohm** [comment]
Tackling this isn't something that we intend to address any time soon since it would require a significant rearchitecture of how Atom functions. Additionally, since the intent of Safe Mode is mostly to determine if there is a problem with Atom itself or a problem caused by community packages or themes, complete isolation isn't required.
