### ISSUE TITLE
Setting a keybinding to the empty string silently invalidates all the following entries

### ISSUE THREAD

**Issue by mattecapu** [atom/atom#10738]
If in keymap.cson a keystroke is set to the empty string (`''`), the entire file from there on is ignored.
I'd expect Atom to raise an error/warning and save some headaches.

I'm experiencing this problem on Atom 1.4.3 on Windows 10. [This Atom Discuss topic](https://discuss.atom.io/t/cant-override-f2-keybinding/25077/7) features the same problem.

Here's a problematic keymap.cson file

``` cson
'atom-text-editor':
    'f2': 'refactor:rename'

'body':
    'ctrl-shift-S': 'window:save-all'
    'alt-1': ''
    'alt-2': 'unset!'

'.platform-win32 atom-workspace':
    'ctrl-alt-shift-T': 'unset!'
    'ctrl-shift-C': 'open-terminal-here:open'
```

`ctrl-shift-S` will work, but `ctrl-shift-C` won't.

![atom-bug](https://cloud.githubusercontent.com/assets/5738009/12910238/0dbaf9a6-cf09-11e5-8abc-289e268472cb.gif)

**Comment by Volox** [comment]
I think i the problem is with the `ctrl-shift-C` key binding. I have a similar problem with my keybindings and the `ctrl-shift-C` is the only non working binding. If you open the Key Binding Resolver `cmd-.` (on OSX) you can find which command responds to the keybinding:
![screen shot 2016-03-18 at 11 49 20](https://cloud.githubusercontent.com/assets/1468697/13875662/80ad1822-ecff-11e5-99b2-cdab8701b8c0.png)


Here is my config:
```cson
'.platform-darwin atom-text-editor:not([mini])':
  'cmd-d': 'pane:split-right'
  'ctrl-alt-down': 'editor:duplicate-lines'
  'ctrl-alt-up': 'editor:duplicate-lines'
  'alt-down': 'editor:move-line-down'
  'alt-up': 'editor:move-line-up'
  'ctrl-d': 'editor:delete-line'
  'alt-shift-up': 'editor:upper-case'
  'alt-shift-down': 'editor:lower-case'
  'ctrl-shift-C': 'emmet:toggle-comment' # wont work :(
```

**Comment by mattecapu** [comment]
I can't see how the two issues are related
