### ISSUE TITLE
Command+a is picked up by editor while typing in the help search field

### ISSUE THREAD

**Issue by abedef** [atom/atom#10735]
While editing a file, attempting to select search text in the _Help_ menu bar item (using `cmd+a`) closes the menu and instead selects all text in the editor pane.

**Comment by lee-dohm** [comment]
I can reproduce this using Atom v1.6.0-dev-ed43eda on Mac OS X 10.11.3.

**Comment by elliottkember** [comment]
A related note - CMD+Shift+/ doesn't open the Help menu as expected. The help search box is a useful find-as-you-type reference for menu items.

**Comment by jaepage** [comment]
+1 for this bug. 

To reproduce: 
1) Press <kbd>command</kbd><kbd>shift</kbd><kbd>/</kbd> to trigger `Menubar / Help` search input (or click it). 
2) Type anything to populate the search input. 
3) Press <kbd>command</kbd><kbd>a</kbd>. 
- Expected behavior (convention for Mac OS native and major third-party apps): Typed search input should highlight entirely. 
- Observed behavior: Keyboard focus is lost from the search input, and the file's contents are highlighted entirely instead. 

Mac OS 10.11.6 (El Capitan)
Atom 1.9.9
