### ISSUE TITLE
Atom doesn't update Tab Type after "Convert Spaces To Tabs"

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#10745]
After converting a file from space-based indentation to tab-based indentation (or vice versa), Atom continues to insert spaces (or tabs) for newlines or tab-keypresses.

**Comment by abejfehr** [comment]
I think the "Convert Space To Tabs" option is a feature of the [whitespace package](https://github.com/atom/whitespace). Should this issue be placed there?

By the same token, the "Tab Type" is a Settings option within Atom, I'm not 100% certain that the whitespace package would have the authority to change that, especially since that's a global setting rather than per-file.

Usually, if the Tab Type is set to "auto", it works for me to close the file and re-open it, and the tab type should be automatically re-detected correctly.

**Comment by alexchandel** [comment]
@abejfehr hah the confusion of who should change it is why I opened it here.

That's the workaround I use too. However it should not be necessary to use the close/reopen workaround.

**Comment by lee-dohm** [comment]
I agree that this should be on the [tabs repository](https://github.com/atom/tabs). Thanks for moving it!
