### ISSUE TITLE
Moved/renamed files (via tree view) with open tabs not linked anymore after operation

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#10751]
If I have a file open in Atom that I want to rename/move, and use tree view to do this, the tabs of the files lose track of where the file source is, and continuing to edit in the file tab causes the old file to be re-created on save.

Is it possible to have tree view inform the tab package of the file rename/move somehow, so that the source of the tab is updated and we can keep editing the file?

Having to close the tab and reopen it for the new file seems a bit 1990's :)

Possibly related: https://github.com/atom/atom/issues/9875
Although I would not propose to close the file buffers, just point them to the right folder/files again.

Maybe this is not something that's normal/common in Windows apps, but on Mac it's pretty common. Any file that I'm editing, I can just move it around or rename it freely, and any app using the file will still have a pointer to the correct file location.

**Comment by curtisforrester** [comment]
A note on this: Most of the time I can do this - rename an open file and the tab changes - but not always. It might be a separate issue, but I just renamed a Python file in treeview that was open and the tab name did not change. When I closed the tab and clicked the file in the treeview the file contents was old. There had been no warning when I closed the tab and there was no "dot" indicating that there was unsaved work. I'm also on Mac/OSX.

**Comment by brutalcrozt** [comment]
i on windows also hit this.

**Expected behavior:** move, rename or drag file should reflect tabs on opened file

**Actual behavior:** not reflect, move -> edit and save create 2 files

### Versions

atom version `1.6.0` .

**Comment by jamespatterson** [comment]
I am finding with `1.6.0` that a rename from the tree view does not update the leaf node in the tree or an open tab of the file. The rename actually happens, but subsequent renames in Atom report the file does not exist because it continues to use the old filename. The workaround I am using:

1. Close the tab (if editing the file).
2. Rename the file.
3. Collapse and reopen the tree view parent node so it will refresh the file listing.

It seems like an event trigger is missing on the rename, or maybe the tab and tree itself have no listener for a "rename" event (if there is one).

**Comment by jamespatterson** [comment]
With Atom v1.6.2, I am not experiencing this issue anymore.

**Comment by adambuczynski** [comment]
No longer seems to be an issue in 1.10.0-dev-672cf6d, so I will close this now.
