### ISSUE TITLE
Improvements on file deletion dialog

### ISSUE THREAD

**Issue by 0x1ad1b88** [atom/atom#10811]
Hi there,

i would to suggest to add a few improvements to the file deletion dialog.
![atomeitordeletedialog](https://cloud.githubusercontent.com/assets/16868514/13030065/4576cd64-d29e-11e5-872f-0a4812828373.jpg)

**First:**
if deleting a bunch of files it gets hardly to read... so please put the filenames into a x/y scrollable area.

**Second:**
if I detect a "wrong" filename, i need to cancel the dialog, and search for it in the tree nav... and start deletion again... so please put checkboxes in front of the file name which allows to deselect a file to exclude it from deletion

**Third:**
Add a dialogtitle :) currently the dialog has a blank title bar... 

**Forth:**
The lightbulb indicates a hint... Add an exclamation mark which would indicate a dangerous operation, or a question mark that indicates its a question...

**Fifth:**
Don't switch phrasing... i start the operation with an option that's labelled "delete", i read delete in the dialog text, then i need to "move it to trash" instead of simple "delete" it. Name the button please "Yes, delete" or change wording on action and dialogs. Oh, and i'm about to delete the files... i am not currently deleting them if the dialog is displayed

**Comment by brutalcrozt** [comment]
IMO, there is a reason behind "move it to trash".
i want add new enhancement related to file deletion, this happen when accidentally i want delete folder which also opened by other app. Like so :

**Current result** 
delete locked file -> no report of that promise.
**Expected result**
delete locked file -> report of that promise if it's rejected with some reason i.e `unable to delete, cause file or dir is locked`

since it's related i post the issue here, please let me know if better to create new issue.
Thanks :love_letter:

**Comment by mindtonic** [comment]
When attempting to delete a lot of files through the Atom interface, the dialog stretches off the screen and I am unable to click the "Move To Trash" button. This requires that I force quit Atom in order to regain access to the program. Of course I can do the deletes through Terminal or the Finder, but it would be much better to have a usable dialog within Atom itself.
