### ISSUE TITLE
Files excluded from navigation tree that should be included

### ISSUE THREAD

**Issue by ericandrewlewis** [atom/atom#10877]
I have unchecked the "Exclude VCS Ignored Paths" core setting.

However, VCS ignored paths are not showing up in the navigation tree (e.g. files listed in .gitignore).

**Comment by lee-dohm** [comment]
Tree view has its own setting for this:

1. Launch Atom
1. Open the Settings View using <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on other platforms
1. Click the Packages tab
1. Search for `tree-view`
1. Click the Settings button on the tree-view listing
1. Uncheck "Hide VCS ignored files"

The reason that the tree view has its own setting is because many people want to see everything in the tree, but still have things ignored by most other parts of Atom, i.e. find-and-replace, fuzzy-finder, etc.

**Comment by ericandrewlewis** [comment]
Oh man I am so sorry, thank you for the direction.

**Comment by lee-dohm** [comment]
You're welcome! I realize that it is a confusing feature at times :grinning:
