### ISSUE TITLE
Cannot close tab in latest bracket

### ISSUE THREAD

**Issue by oeichenwei** [atom/atom#10883]
MAC OS, every time I try to close the tab with the x button in the tab, it will open a new tab. It has been after I upgraded to 
Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) 
build timestamp: Tue Jan 12 2016 05:35:00 GMT-0800

**Comment by lee-dohm** [comment]
Is this a bug report for [Atom](https://atom.io)? Or [Brackets](http://brackets.io/)? This is the repository for the Atom editor. Our build information doesn't look like that.

**Comment by 50Wliu** [comment]
I'm going to assume this is Brackets since their 1.6.0 version was released on January 12 as commit adobe/brackets@3df0ac6fa18b1ccfc34f6d234da2aa8c43643a93, which conveniently matches with the release info @oeichenwei reported.

@oeichenwei please report this instead to https://github.com/adobe/brackets/issues.  Thanks!
