### ISSUE TITLE
Add an API to disable selectively disable IME dialog

### ISSUE THREAD

**Issue by mcolyer** [atom/atom#1092]
If a user long presses `l` while in vim-mode an IME dialog appears. We want to keep IME support on by default, but it would be nice to allow vim to disable it while in command mode.

Therefore I propose we adding `editor.setImeVisible(boolean)` to the public API so that packages can control it.

Refs atom/atom-shell#47

**Comment by izuzak** [comment]
In https://github.com/atom/vim-mode/issues/175, @rastasheep shared an approach which allows users to disable the popup for Atom only: https://gist.github.com/rastasheep/bfc8266eeb58b899054c

Here it is inline as well, just in casse the gist gets eaten by the ever-hungry gist monster :japanese_ogre::

```
defaults write com.github.atom ApplePressAndHoldEnabled -bool false

# Alternately, if you want this feature disabled globally, you can enter this:

defaults write -g ApplePressAndHoldEnabled -bool false

# In either case you'll need to restart Atom for the change to take place.
```

Not closing this issue since it still might make sense to have an API in Atom for this.

**Comment by hh9527** [comment]
#10713

**Comment by t9md** [comment]
Original request for this issue is to provide API to control IME from package.
I still want Atom to provide API to control IME.

I'm maintaining [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) and want to disable IME when escaped from `insert-mode`.
So I tried suggested implementation in atom/electron#47. 
Suggestion was set input `type` attribute to `password`.

Like below
```coffeescript
      if settings.get('disableInputMethodExceptInsertMode')
        # [FIXME] See #98.
        if @hiddenInputElement ?= @editorElement.component?.hiddenInputComponent.getDomNode()
          if mode is 'insert'
            @hiddenInputElement.removeAttribute('type')
          else
            @hiddenInputElement.setAttribute('type', 'password')
```

It works, but it has side effect.
Tab bar become undraggable(t9md/vim-mode-plus#193) when set hiddenInputElement attribute `type` to `password`.
When I dragged tab bar, [tabs](https://github.com/atom/tabs)'s `dragover` event get not fired if `type=password`.

I believe this is one of example of unexpected side-effect.
So we still can't find solution for original request.
