### ISSUE TITLE
System for managing focus within the workspace

### ISSUE THREAD

**Issue by kuychaco** [atom/atom#10938]
Thoughts aren't fully formed on this yet, but just thought I'd jot down some things and start a conversation.

Currently there is a blue bar (in the One UI themes) that indicates
- which tab corresponds to the active pane item
- that the tree-view has focus

As we add features and integrations that utilize our panel system, we'll want to make it clear which part of the workspace has focus so that our users can quickly identify where they are and act accordingly. Thereby avoiding unexpected behavior, like when [this user](https://github.com/atom/atom/issues/8102) almost accidentally deleted a file in tree-view when trying to delete text in an editor.

Currently when switching focus from an editor to tree-view there are two blue bars indicating focus:
![screen_shot_2016-02-19_at_3_50_05_pm](https://cloud.githubusercontent.com/assets/7910250/13192472/304cd76c-d721-11e5-88b5-1ab75cc1e4c2.png)
Ideally, when the focus is outside of the editor the tab blue bar would disappear.

@maxbrunsfeld and I discussed the notion of an optional **active panel** and introducing a Workspace API for activating a panel to model the fact that a panel is focused and not the panes. The tabs package would not show the blue bar when there is an active panel.

Alternatively, we could go with a DOM-based solution implemented in the tabs package where we check if the active element is in the active pane. If not, then we don't show the blue bar.

I'm leaning towards adding a Workspace API for activating a panel and baking this concept into our Workspace model. It's more explicit and could be a good feature especially considering that panels will likely come more into play as integrations are added to Atom.

Interested in your thoughts @atom/core. Thanks!

**Comment by benogle** [comment]
cc @simurai

**Comment by simurai** [comment]
This would be great to fix: https://github.com/atom/one-dark-ui/issues/75

Currently in the One theme, the blue markers get added like this:

- `atom-pane.active`
- `.tree-view:focus`

We could

- just use `atom-pane:focus`, but it currently doesn't seem to work. Maybe it got disabled for some reason?
- Or remove the `.active` class on `atom-pane` when focus moves to somewhere else. Not sure if `.active` is needed for something else and should stay.
- Workspace API. Maybe introduce a new class like `.has-focus` or `.focus` that would jump between panes and panels and maybe status-bar or more. I guess kinda mimicking the `:focus` selector.

**Comment by nathansobo** [comment]
Panes can be focused, but they immediately *transfer* focus to the pane item if it is focusable. So we need either a really complicated selector like `atom-pane:contains(:focus)` (does that even work) or we need a class. A class sounds better.

We already add a class in the text editor called `is-focused`, since it has a similar problem where the focus is *actually* on a hidden input field inside the editor to capture keystrokes. You could argue that `.has-focus` is a better name for the pane, since it *isn't* actually focused. That's true with the editor but it's more of an implementation detail in that case. Or you could argue the distinction is unimportant and we should use `is-focused` for consistency. I tend to favor `is-focused` for both unless anyone disagrees.

Unless we want a crazy selector, we'll need to add logic to the pane system to make this work. It's not a CSS-only change.

**Comment by simurai** [comment]
Unfortunately there isn't something like `atom-pane:contains(:focus)`. You only can select children/siblings in a DOM tree but not parents (once :focus is found).

:+1:  On adding a `atom-pane.is-focused`.
