### ISSUE TITLE
Subpixel font rendering is not working / inferior

### ISSUE THREAD

**Issue by hnry** [atom/atom#10977]
This issue is related to Chrome (or Chromium) and not specific to atom. But I am seeing it in atom as well.
It may be an issue specific to Mac OS X 10.11.3.

I am posting it in atom because... well I could be wrong so having other people be able to confirm this would be great. If there _is_ an issue, then it's mutually beneficial for atom to also raise attention to have this fixed in chromium.

---

I noticed text in atom look pretty good, but Sublime always looked better. And I looked more closely and the rendering doesn't look like it's using subpixel rendering but instead some sort of grayscale. 

After double checking with 
`  -webkit-font-smoothing: subpixel-antialiased;` 
I could not get a different result. So I decided to see if in Chrome it does better rendering, and I see the same result in Chrome. So I wondered if this existed in Firefox or Safari, it does not. In Firefox and Safari the font rendering look similar. And they look similar to what I am seeing in Sublime.

The report on chromium side is here: https://bugs.chromium.org/p/chromium/issues/detail?id=581166

In the attached picture, this is the result I am seeing when comparing 3 browsers, they are a close up of a piece of text being rendered on webpages (github homepage in this specific picture).
![chrome-safari-firefox](https://cloud.githubusercontent.com/assets/25837/13341888/93dab900-dc0a-11e5-9b2f-757397100d1e.png)

I used the Digital Color Meter app in OS X to zoom in on the pixels, and then looked at the same page on all 3 browsers while taking that screen grab. Ideally I should've shown the picture example on a webpage that was "neutral" where I know for sure the CSS wasn't affecting the font rendering. But the issue exists no matter what page you are viewing, and also exists in atom.

The results I am seeing between chrome and safari / firefox is the same thing as when comparing atom and sublime.

So far  I and the original bug report creator (on chromium) are both running OS X 10.11.3. So whether this exists in any other OS X version, or another OS, I don't know.

**Comment by lee-dohm** [comment]
Thanks for the detailed write-up! It's great to see this level of analysis :grinning:

Let me start by saying that, yes, Chrome renders fonts differently than applications that use the native OS X font rendering engine. At least that far you are absolutely correct. Chrome makes different antialiasing choices at different font sizes and DPI, for performance reasons from what I have read on the Chromium bug tracker. Specifically, Chrome will fall back to grayscale antialiasing rather than subpixel antialiasing in situations where the native font rendering will not. There are a few situations where this will happen that we have noticed (or I've read about):

* When rendering against a semi-transparent background, Chrome will switch to grayscale antialiasing
* At certain ratios of DPI to font size, Chrome will switch to grayscale antialiasing (this also means that on Retina screens, Chrome will much more frequently use grayscale antialiasing)

The Chromium team is aware of this, it's a specific design choice that they have made. From what I have read in various bug reports, they are unwilling to change their minds on it.

With regards to Atom:

* Atom could switch to a completely different rendering engine
* Atom could fork Chromium and completely replace the font rendering
* Atom could fork Chromium and change the values in the font rendering

All of these are more resources than the Atom team has available to bring to bear on the problem.

We do have font rendering bugs from time to time that are not due to this design choice by the Chromium team. So please continue bringing things that you notice to our attention!

Thanks so much for your interest in Atom!

**Comment by hnry** [comment]
thanks @lee-dohm for the response, wasn't aware of the ratio issue.

And yea I kind of get the feeling the Chrome team won't really fix this either. Which is why I hoped to try to get enough interest as far as starring the issue to get more demand for chromium team to fix it.

Unfortunate, especially since atom is moving along to be a great editor (as well as Chrome is a great browser). But the difference is crispness is noticeable even when not trying to look for it.

Oh well, sorry for filing a known issue.
