### ISSUE TITLE
Feature Request: Distribute Atom through the Mac App Store

### ISSUE THREAD

**Issue by landocloud** [atom/atom#10976]
IANAL.  Please can anyone confirm whether the [Atom MIT license](https://github.com/blog/1831-atom-free-and-open-source-for-everyone) is compatible with the Mac App Store?

Now that Electron 0.34.0 supports the Mac App Store https://github.com/atom/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md, is it possible to submit Atom to the Mac App Store so that the app auto-updates?

As of Atom 1.0 to 1.6, the OS X auto-update framework is borked as per https://github.com/atom/atom/issues/2860

Thanks!

**Comment by lee-dohm** [comment]
To my knowledge, there is no restriction against open source software on the Mac App Store. On the other hand, an application on the Mac App Store is restricted to a sandbox that precludes reading from and writing to files outside certain areas. Since editing files anywhere on your system is one of the features of Atom, until that requirement changes I don't believe we'll be pursuing publishing on the Mac App Store.

Thanks for your feedback!
