### ISSUE TITLE
Flaky TextEditorPresenter and TextEditorComponent specs

### ISSUE THREAD

**Issue by kuychaco** [atom/atom#11019]
https://travis-ci.org/atom/atom/jobs/112746205

<img width="1162" alt="job__5290_3_-_atom_atom_-_travis_ci" src="https://cloud.githubusercontent.com/assets/7910250/13438280/38360f78-df9d-11e5-8a2f-e870edf71acb.png">

For reference:
https://github.com/atom/atom/issues/10840
https://github.com/atom/atom/issues/10435

**Comment by nathansobo** [comment]
Bumped the timeouts in f26c0c0b15231f853f82a8fc6c7e527a27154d89. Moving this to blocked status until we iron out the issues in Electron.

**Comment by joshaber** [comment]
Why are our test windows even in the background to begin with?

**Comment by nathansobo** [comment]
@joshaber I'm not sure, but the fact that we're timing out at 30 seconds makes me strongly suspect we're getting throttled. The timeout for each animation frame was 30 seconds, and since we waited multiple times in that test it looks suspicious. That said, I still can't explain the bizarre transposition of the stack trace to a totally different test. So maybe I'm wrong.

**Comment by 50Wliu** [comment]
This has definitely been fixed.
