### ISSUE TITLE
XML grammar autodetection failed for Visual Studio project files

### ISSUE THREAD

**Issue by AlexeyKryshen** [atom/atom#11018]
### Description

Atom doesn't detect Visual Studio project file as XML file and doesn't apply XML syntax highlight automatically.

### Steps to Reproduce

1. Open any *.vcproj file

**Expected behavior:** [What you expected to happen]

XML syntax highlight applied

**Actual behavior:** [What actually happened]

No XML syntax highlight

### Versions

Atom 1.5.3

**Comment by thomasjo** [comment]
Thanks for the report! The fix is available on `master`, and will become available in a future release.

---
**Side note:** The `vcproj` extension was deprecated a few years ago, and was replaced with `vcxproj` (which the language-xml package already recognises). Visual Studio is supposed to automatically convert any `vcproj` file to `vcxproj` when opened.
