### ISSUE TITLE
"The editor has crashed", no way to know what's really happening.

### ISSUE THREAD

**Issue by zb3** [atom/atom#11075]
I've build `atom` on archlinux, but everytime I run it, I eventually get `The editor has crashed`.

The fact that editor crashes is nothing special, in fact not an issue, but I am literally unable to provide any further information! This message is the only thing that appears. I **DO** know that this is unhelpful, and that's exactly the problem.

What I've done:
-> Tried checking `/tmp/Atom Crashes`, but it was... empty
-> Tried running with the `-f` option, only find out that it's impossible to get crash dump id:

```
$ atom -f
[1928:0305/185349:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[1928:0305/185350:INFO:audio_manager_pulse.cc(257)] Failed to connect to the context.  Error: Connection refused
[1928:0305/185351:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[1928:0305/185351:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[1928:0305/185351:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[1928:0305/185351:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
App load time: 2081ms
[1928:0305/185354:INFO:CONSOLE(52)] "Window load time: 1539ms", source: file:///usr/local/share/atom/resources/app.asar/static/index.js (52)
[1928:0305/185356:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
Failed to get crash dump id.
Report Id: 
```

-> I've read the [debugging](https://atom.io/docs/latest/hacking-atom-debugging) info, only to find out that I am not as lucky not to have this issue in `--safe` mode, and I can't check my settings since the editor crashes

->`~/.atom/nohup.out` shows nothing more (and this super secret file location wasn't included in the debugging document....)

I don't know any other secret tricks to get more info.

**Comment by drewmnoel** [comment]
What version of `freetype2` do you have installed? There's a known issue with electron and `freetype 2.6.3-1`, so you have to pin it at `2.6.2-1`. [There's a fix](https://github.com/atom/electron/releases/tag/v0.36.9) but atom is painfully slow to pull it.

**Comment by zb3** [comment]
I have `2.6.3-1`, but I'm currently using the binary package and it works. (I didn't reinstall anything)
So either the package author has pulled the fix, or it's a different bug, but unfortunately I can't test because I no longer have the build directory and I'm unable to build it again due to lack of time.

**Comment by drewmnoel** [comment]
That version of `freetype2` has an issue with electron that will be fixed when PR #10983 is merged. That was most likely your issue.

**Comment by libeclipse** [comment]
+1 for version 1.7.0-beta2 under Arch Linux.

**Comment by thedanielhanke** [comment]
+1 for version 1.7.4 under Arch Linux.

guess its related to the actual issue headline.

```
atom -df    
[2127:0530/132223:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[2127:0530/132223:INFO:audio_manager_pulse.cc(257)] Failed to connect to the context.  Error: Connection refused
App load time: 547ms
Failed to get crash dump id.
Report Id: 

 atom --version 
Atom    : 1.7.4
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1

```

honestly, i dont need sound in atom.

**Comment by DamnedScholar** [comment]
Try building from `git checkout b9dbb81`. That's the version of 1.9.0-dev that I currently have running on my Manjaro box.

**Comment by jolsenmultiad** [comment]
This thread has diverged from the original post and thread title. I suggest opening an new thread regarding the linux freetype issue, because while that is a problem, it has no bearing on the fact there is little to no useful information provided with "the editor has crashed" alert. I've ran into this alert on Windows when adding a specific project folder to an empty Atom window (other project folders do not cause crashes) and I was hoping this thread (given the title) might help provide where to look for info or how to get it. While the last post in this thread is from May 2016, the lack of information on this type of crash is still an issue in the most recently release beta 1.15.0-beta3 x64 on Windows.

Anyhow, I'd like to see this topic remain true to it's origin: more information should be provided when Atom crashes with the "The editor has crashed" dialog.

**Comment by drewmnoel** [comment]
In this case, the crash was caused by an upstream issue in Electron. The crash dump provided enough information for diagnosis. The issue was diagnosed in another thread and I recognized the same environment here.

I don't think the intention of this thread was ever to discuss how Atom handles crashes in general. If you feel the way Atom handles crashes in general isn't enough, you should create an issue and/or visit the Slack channels to discuss it.

**Comment by DamnedScholar** [comment]
I was affected by this problem back in the day, and it got fixed via the natural process of updates percolating through the ecosystem. This issue can be closed.
