### ISSUE TITLE
Cant keep tabs

### ISSUE THREAD

**Issue by Showian** [atom/atom#11131]
Atom is the best text editor everything is good, But the only reason that make me to avoid using Atom is that its not possible to keep tabs. Wen you worked on several files at different directory you need to switch context, But its happened with lose all of the tabs and you can keep the tabs wen you close and re-open Atom. even some times you create a pans without saving because you want use it as a note or .. but you again lost this tab. and at notepad++ I don't have this problem because I can keep all of my tabs even if I not saved them. If its possible please add this features to Atom to keep tabs.

Thank you

### Versions
1.5.4

**Comment by lee-dohm** [comment]
Atom has this feature already. Atom has the concept of a "project" which is defined as a specific set of root folders. Atom stores certain state information by project, including open tabs, when you exit the application. If you open the same project again, Atom will restore that saved state.

For example, if I open the `/Users/Lee/Source/atom` directory with the command `atom /Users/Lee/Source/atom`, this causes Atom to create a project that is defined as that one root directory. When I close Atom, all of my open tabs will be saved for that project. If I open a different directory, like `/Users/Lee/Source/foozle`, with the command `atom /Users/Lee/Source/foozle`, then Atom will open with no open tabs because I've never had this project open before. When I go back to the original project by executing `atom /Users/Lee/Source/atom`, Atom will launch with all of my open tabs associated with the `atom` project.

Thanks for reaching out and let me know if you have any more questions!

**Comment by Showian** [comment]
Thank you for your reply. But this is not invalid, let me give you a clear example
For example if I have 3 files at E:/myproject/  file1.html , file 2 .html , files 3 .html and I oped them by Atom and I also want worked at this file at E:/myproject/css style1.css style 2 .css or maybe want to compare to another file  D:/myoldproject/ file1. html . So up to now I opened all of this file by Atom, so what happens if I closed Atom and re-opened again. It only show me html tabs at E:/myproject/  directory. and about non-saved tab same problem.

I hope you add this features to Atom

**Comment by Zireael07** [comment]
@Showian: This is related to another issue then, one about Atom's launch state not being clear.

**Comment by lee-dohm** [comment]
@Showian If you have steps that I can use to reproduce the behavior you're seeing, please share them. You can see my [blog post on writing repro steps](http://www.lee-dohm.com/2015/01/04/writing-good-bug-reports/) for more information on how to do that.

**Comment by Showian** [comment]
I am a web programmer. Imagine I have 3 files at E:/myproject/ file1.htm,, file 2 .html , files 3 .html
Ok now i want to start programming First I open file1.htm at E:/myproject/ by Atom I also need to work on my css files, so I open style1.css from E:/myproject/css style1.css in Atom too and I want to compare my files with another files at  D:/myoldproject/ file1. html  so I opened it on Atom too. I also need to write some notes, so I open a new tab and write somethings without saving. then I close Atom. and again open Atom, Atom only show me E:/myproject/ file1.htm this tab. This is not good that Atom only show the first files that I opened.

Please fix this bug. this is really big bug

**Comment by mnquintana** [comment]
@Showian Atom should be restoring your session completely – what version of Atom are you using? Can you reproduce this after quitting Atom completely and restarting in safe mode? (`atom --safe`)

**Comment by Showian** [comment]
Tested not worked! Only open the first files that I opened by Atom
