### ISSUE TITLE
Cursor disappearing when using arrow keys or clicking

### ISSUE THREAD

**Issue by ctcrnitv** [atom/atom#11140]
### Prerequisites
- [ y] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [ y] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [ y] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [ y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [ y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

The cursor tends to stop blinking over certain portions of my code. 
### Steps to Reproduce
1. Open Atom
2. Move cursor through code using arrow keys, cursor disappears
3. Move cursor around code using mouse, cursor disappears

[screencap of issue](http://g.recordit.co/pkiVPd6eJw.gif)

**Expected behavior:** Cursor blinks throughout code without gaps. 

**Actual behavior:** Cursor disappears over different gaps through the code.
### Versions

1.5.4

**Comment by lee-dohm** [comment]
What OS are you running?

**Comment by amytruong** [comment]
I know this is unlikely but are you on a VM? I've had issues with this on VMWare before.... :thought_balloon:

**Comment by skr5e** [comment]
Running OSX Yosemite 10.10.5, no VM.

**Comment by as-cii** [comment]
Hey @skr5e, thanks for reporting this issue! It'd be awesome if you could help us answer a couple of questions:

1. What syntax theme are you using? (name and version)
2. What UI theme are you using? (name and version)
3. What's the content of your personal stylesheet?
4. If possible, could you post here the content of your personal Atom configuration file?
5. Which packages do you have installed? Can you reproduce with `atom --safe`?
6. Is it something that happens consistently?

Sorry for the pretty long list :sweat_smile:, but that should help us track down the root cause of the issue. :zap: 

Thanks! :sparkles:

**Comment by lee-dohm** [comment]
Thank you for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/11140#issuecomment-202424043. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
