### ISSUE TITLE
Unable to debug a crash caused by a plugin

### ISSUE THREAD

**Issue by thedrow** [atom/atom#11250]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I have installed an Atom plugin that crashes Atom on large Ruby projects.
I tried to output the logs using --log-file but the file is not created.
I do have crash dumps but there are no instructions on how to read and analyze them.
Atom works fine in safe mode.

### Steps to Reproduce

I have no idea how to reproduce the issue since I don't know which plugin causes the issue.

**Expected behavior:** [What you expected to happen]
Atom should at least output logs with the exception message in order to debug crashes.

**Actual behavior:** [What actually happened]
No log file is created.

### Versions
atom --version
1.6.0
apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4

**Comment by amytruong** [comment]
Hi! 
To find out which package is causing the issue, start Atom normally again and open Settings (cmd-,). Since Settings allow you to disable each installed package, you can disable packages one by one until you can no longer reproduce the issue. Restart (cmd-q) or reload (cmd-ctrl-alt-l) Atom after you disable each package to make sure it’s completely gone.

When you find the problematic package, you can disable or uninstall the package, and consider creating an issue on the package’s GitHub repository.

**Comment by thedrow** [comment]
Thanks. This does help.
