### ISSUE TITLE
Softwrap should match indent

### ISSUE THREAD

**Issue by cameronmcefee** [atom/atom#1125]
Ok, this one may be a personal preference, but it drives me nuts that softwrap doesn't match the indent.

![screen shot 2013-11-18 at 5 18 17 pm](https://f.cloud.github.com/assets/72919/1568843/7c5b0c10-50b8-11e3-961b-0650f94008c4.png)

**Comment by ioquatix** [comment]
+1.0

**Comment by joshrowley** [comment]
+1, just showing my support for this, great work team!

**Comment by as-cii** [comment]
I would like to tackle this (or, at least, offer my help), but I need guidance in order to get started. This should affect only rendering, therefore my understanding of the code led me to `TokenizedLine`. 

In particular, `softWrapAt(column)` contains the code which converts one `TokenizedLine` into a left fragment (the line which will fit the current row) and a right fragment (the line which, probably, needs further splitting because it doesn’t fit the current line). The process repeats until no overflowing characters are found.

I have noticed also that `TokenizedLine` accepts an `indentLevel` parameter which, unfortunately, doesn’t have any effect on the resulting rendering (I assume this is why the issue hasn’t been solved yet, otherwise it would have been too simple :wink:).

Thus, as far as I understand, we would need a way to move the `rightFragment`s towards right. However, this should be just a visual effect: even though my knowledge of the codebase is relatively limited, I’d say this change should not involve any modification in `TokenizedLine`’s tokens or text.

Now, a couple of questions:

1. Do you agree with my last assertion (e.g. indenting should be only a visual effect)?
2. Is there anyway to position a tokenized line arbitrarily (or in a way that could fit our purpose, e.g. `renderFromColumn: 2`)?
3. An alternative could be to place a “fake” token in front of the `rightFragment`s (which would contain as many spaces as `leftFragment`’s indentation).
4. Is there any other pitfall which I am totally ignoring and that causes this to be tricky?

Thanks in advance to anybody who will help me out :pray:

**Comment by thedaniel** [comment]
Pinging @atom/core re @as-cli's questions

**Comment by nathansobo** [comment]
> Do you agree with my last assertion (e.g. indenting should be only a visual effect)?

Yes, but we model it. The `DisplayBuffer` is responsible for the non-linear relationship between lines/characters on screen and lines/characters in the buffer, dealing with folds and soft-wraps.
> Is there anyway to position a tokenized line arbitrarily (or in a way that could fit our purpose, e.g. renderFromColumn: 2)?

No, you're going to need to insert a phantom token. More details below.

> An alternative could be to place a “fake” (read: special) token in front of the rightFragments (which would contain as many spaces as leftFragment’s indentation).

Check out how we handle hard tab characters, which map multiple spaces in screen coordinates to a single character in the buffer. This should be similar, but would map to zero characters in the buffer causing the cursor to skip that leading whitespace.

> Is there any other pitfall which I am totally ignoring and that causes this to be tricky?

I think your phantom token approach sounds promising and was what I had in mind. It's hard to say what kind of issues might crop up with our coordinate mapping going from multiple characters on screen to zero in the buffer since we've never done that... with tab we map to one character. So that could be interesting. You'll just have to see what emerges I guess.

**Comment by Josiah** [comment]
:trophy: Awesome - really wanted this feature!

**Comment by joshrowley** [comment]
This is fantastic, nice work.
