### ISSUE TITLE
How to debug atom package without stacktrace?

### ISSUE THREAD

**Issue by flip111** [atom/atom#11356]
Hi i'm running atom 1.6.1 and i'm trying to develop a package. The problem is that i don't get a stacktrace when an error occurs in the package. Not in the red popup and also i don't see any errors in the console related to my package files. So i enabled breakpoint on error and made a screenshot (below). I actually know line 37 is causing problems because when i comment that out the rest of the functionality works. But i would like to dive into the function calls caused by line 37 ..

![screenshot](https://i.imgur.com/9qwfVb1.png)

Also i would like to know if `addFooterPanel` causes an element to render. Because i think some functions only work on elements if they are already rendered.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
