### ISSUE TITLE
Auto Indent for HTML Puts Extra Indents

### ISSUE THREAD

**Issue by juilyoon** [atom/atom#11428]
When there is a new line before a closing `pre` or heading tag and you auto indent the following code, Atom will put an extra indent into the rest of the code.
### Steps to Reproduce
1. Newlines before the closing heading and `pre` tags:

``` html
<h1>Some Sort of Title That Feels Too Long to Put on One Line
  </h1>
<h2>Subtitle</h2>

<p>
  <pre>
.somecode {
  width: 100%;
}</pre>
</p>
```
1. Highlight and auto indent the page:
   `Edit -> Line -> Auto Indent`

**Expected behavior:**

``` html
<h1>Some Sort of Title That Feels Too Long to Put on One Line
  </h1>
<h2>Subtitle</h2>

<p>
  <pre>
.somecode {
  width: 100%;
}</pre>
</p>
```

**Actual behavior:**

``` html
<h1>Some Sort of Title That Feels Too Long to Put on One Line
  </h1>
  <h2>Subtitle</h2>

  <p>
    <pre>
      .somecode {
        width: 100%;
      }</pre>
    </p>
```
### Versions

Atom 1.6.2
apm 1.6.0
OSX 10.10.5

**Comment by v95** [comment]
It looks like the root of the issue is the placement of `</pre>`. Shifting it to a new line and then using the `Auto Indent` function doesn't reproduce the problem anymore. I guess the Auto Indentation code is not context-aware; it uses the position of `</pre>` to indent the next line, ignoring the context (e.g. `</pre>` being positioned right next to the previous line (`}`)).

**Comment by rhaphazard** [comment]
The problem is that the behaviour of ```<pre>``` forces you to put ```</pre>``` on the last line of code, because it would display a newline otherwise.

It is also weird that this behaviour happens with ```<h1></h1>``` as well.
