### ISSUE TITLE
Bulk Enable/Disable packages based on programming language they belong to

### ISSUE THREAD

**Issue by the100rabh** [atom/atom#11424]
Now that atom can help with so many languages, the list of packages that I have with it has grown too long. This makes the packages menu options go beyond the screen. It would be great if there was an option to group a bunch of packages and be able to enable/disable them in bulk. This would make sure that while I working on Java or Javascript, the packages for python or ruby remain disabled.

**Comment by Zireael07** [comment]
This is a great idea!

**Comment by arcticicestudio** [comment]
I think it would be very [usefull](usefull) to

**Comment by ethernal** [comment]
The ideas from  11570 are very much valid here.

I'll keep using "perspective" here as this is a good explanation of what we need here.

One of the most important features is to keep separate SETTINGS per "perspective" / config. Ex. Imagine creating a full blown Markdown editor, then you add Go-Lang support, but you want to use same components with different configuration.

Better yet simpler situation - you want your FlexToolbar plugin to be configured differently if you are switching to "perspective X" or in "Y", and before someone says that it can be based on ACTIVE plugins - what I mean is that config should be based on ACTIVE "perspective" instead of plugin. One plugin can be active in both "perspectives".

This would actually allow to create slimmer atom customizations. If I need to add 5 plugins to already 500mb installation and configure them it's more "space effective" to just configure a "perspective" that uses them instead of creating a separate package. Maintaining it will be also much easier.

Just my 3 cents.

**Comment by AlynxZhou** [comment]
And I think taking control different keymaps is also hard, they are added in a mess and it's not easy to disable a group of keys because there is no way to describe them (like regex?)
