### ISSUE TITLE
Atom open files as empty and no git integration

### ISSUE THREAD

**Issue by Bertutchio** [atom/atom#11481]
Hello,

Since i've upgraded from Atom 1.5.4 to the latest 1.7.1 on my mac i can't use it anymore.
All files that i open from my project are empty. Even more strange i get no git integration (no branch name).
I tried the safe mode but get the same result.

I tried with severals version and it first appear on the 1.6.0 version.
Downgrading to the 1.5.4 solved my problem but i would like to try the latests features.

I'm using a mounting point (sshfs) but ii doesn't seems to be the problem as i'm able to get the file content from another editor. 

Any ideas of where does it come from ?

**Comment by johnwalshuk** [comment]
I'm getting the same issue, I try to open a file, some times it does not open, click again it opens an empty file and then eventually around 2/3 minutes later the file finally opens with the contents in it :confused: 

Also, when I save the file I'm getting a weird bug that reverts the changes I've made and adds lines of code to the end of the file? 

No plugins added. Windows 7. Atom 1.7.1

**Comment by Bertutchio** [comment]
Haha i'm not alone :)

I just tried the latest beta 1.8.0-beta1 and i dont't have this issue, but there is a latency. The editor open the file as empty and 1or 2 seconds later the content is displayed.

And the git integration is back.

**Comment by andyrichardson** [comment]
I can confirm I have the same issue when trying to edit files from an _sshfs_ mount. I did not have this issue when running v1.6.x

Fedora 23, Atom 1.7.1

**Comment by 50Wliu** [comment]
As this appears to have been fixed in Atom 1.8.0, I'm closing this out.

**Comment by Bertutchio** [comment]
Sure it seems to be solved in 1.8.0.
Hope it will be released soon.

**Comment by jolsenmultiad** [comment]
It's great that it is already fixed in 1.8.0-b2. I wanted to share the following information for the users who aren't using beta builds (or cannot or do not want to):

For those affected and not wanting to upgrade, @lee-dohm posted this awhile ago in an older thread:
> You may also want to delete or move the ~/.atom/storage directory. You may have a project with an invalid cached state.

This seems to have worked for me once. Other times simply closing down Atom and restarting it resolved the issue. These attempts to work around the issue could be working coincidentally. Interestingly, only of my projects seems to encounter this issue repeatedly and only when I open a new window to reopen the project. 

Hopefully, these may help others having the same problem until a stable 1.8.0 is released.
