### ISSUE TITLE
Atom Universal Windows Platform (UWP) app

### ISSUE THREAD

**Issue by MadSpindel** [atom/atom#11499]
### Description

Convert Atom to a Universal Windows Platform (UWP) app and be able to install it from Windows Store with automatic update facilities.
https://msdn.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root

### Steps to Reproduce

1. Go to Windows Store
2. Search for "atom"
3. Install Atom Editor

**Expected behavior:**
Atom is installed and auto updated from Windows Store.

**Actual behavior:**
Atom Editor was not found.

### Versions

```
Atom    : 1.7.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by damieng** [comment]
Until Chromium supports UWP this is impossible for Atom to do.

**Comment by lee-dohm** [comment]
@MadSpindel Thanks for the feedback. At this time, we don't have any plans to make Atom available in either the Windows or the Mac app stores.

**Comment by mattiascibien** [comment]
Can this change by using http://electron.atom.io/docs/tutorial/windows-store-guide/

**Comment by db2k** [comment]
@lee-dohm I think this is interesting now since we have the UWP Desktop Converter. I already tried converting Atom but had the problem that I didn't found any `silent` hook for the exe-installation.

Otherwise it might work pretty fine.
I also tried to convert Sublime Text and Brackets,

Brackets had no problems after converting to UWP
Sublime only had a bug with the `Tools => Open Package Folder` command since the "base" package folder was inside the appx-container. Packages for Sublime also worked so there was no problem in "modding the editor".

Otherwise for atom everything should work fine since everything is installed in the users directory under `%USER%/.atom/`. so please do!

**Comment by db2k** [comment]
You can get the converter here:
https://www.microsoft.com/en-us/download/details.aspx?id=51691

Instructions how to use the converter:
https://msdn.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter

Seriously converting only takes 5 minutes, it only costs 14 € for a Developer License for Microsoft and Windows 10 users would love it.

**Comment by damieng** [comment]
It would require a little more work than that - for a start our updater would need to be somehow disabled in this additional Windows build and we'd have to include the steps to build and package the UWP into our deployment process.

We'd also have to  manually submit packages to the store for review every time we produce an update and figure out what we want to do with the beta channel. There would I am sure also be lots of caveats or gotcha's given we're not a simple app but a dev tool that performs all sorts of network installs, downloads of packages and themes, etc.

I'm struggling to come up with a list of positives other than "we're listed in the Windows 10 store"

**Comment by nickpassarodesigns** [comment]
I'm pretty sure you can distribute UWP apps without the Windows store. There's and app that comes with Windows 10 called App Installer and as long as the ability to sideload apps is enabled in the Settings App, which in all of my Windows 10 installations, it is by default, you should be able to just distribute UWAs through your website. When the user double-clicks the downloaded UWA, App Installer should move it to the directory where Windows keeps the apps you've installed.

**Comment by bdbch** [comment]
@damieng with the latest news about the Microsoft Store could you consider rethinking the decision to not create a converted app?

There will be a big lack of code editors on Windows 10 S since there is currently no good editor in the Windows 10 Store. With bigger apps like Spotify, Itunes and Chat Tools like Telegram etc. I expect other developers to follow and release their software for Windows users inside the Store directly.

Telegram for example just kept their updater and allows updates via the Store or directly from the application.

**Comment by damieng** [comment]
I have been investigating this more and talking with a bunch of people at Build about it last week.

The basic problem comes down to the extension system inside Atom.  The store doesn't specifically allow additional binaries to be downloaded and Windows S actually enforces that.

We would need to write tools that scan the Atom Package repository including their npm dependencies to identify packages that used additional .exe files or required C++ build tools (native modules) and then flag them as such and subsequently prevent them from being installed.

Not an impossible task but one that does require some planning and effort.

**Comment by bdbch** [comment]
Sounds troubling but it's nice that you talked to other people about this issue. If I can support on this task somehow let me know.

Is there a list of software which requires external binaries for now or is it a bit hard to overlook since atom is split up into multiple subcomponents?

**Comment by damieng** [comment]
The stuff that ships with Atom isn't a problem as that would be signed. It's the entire collection of 3rd party packages that would need to be filtered to those that actually would work and be allowed - i.e. no exes or dlls in them or their downstream npm dependencies.

**Comment by richpeck** [comment]
Microsoft's UWP ecosystem is a trainwreck.

Instead of opening up their Windows API like they did with .NET & VC++, they've bottle-necked progress by preventing access to even the most basic of functionality. Preventing access to the likes of DLLs and other things is going to make it a new Windows RT.

They have the perfect chance to create a central repository of GREAT applications which are silently updated, work across ALL Windows powered devices and can be extended to work across the entire Windows system (such as introducing live tiles on the desktop for App previews -- having a game with latest screencasts for example, or having a central repo of "connected" apps (APIs) which the user is able to integrate into their Windows applications, allowing Streamers to upload directly to Youtube etc). Much like the apt/yum/brew system in unix but better.

Instead of that, they're worrying about trying to build their own - shittier - version of iTunes. I'd love to just look up Atom in the Microsoft Store, download and install it. I'll be happy in the knowledge that the app will be continually updated and my preferences saved to a central cloud repo. But no... the app cannot do anything even remotely ambitious.

I'd love to see this functionality but until Microsoft lift some of UWP's restrictions, or you create a way to get the extensions to pass through, it's going to take ingenuity or time to develop.
