### ISSUE TITLE
the atom clean the all content of my files which has been saved in early

### ISSUE THREAD

**Issue by kwin-wang** [atom/atom#11521]
I am very disappointed with this software!
because when I exit the atom, it clean  all content of my files which has been saved early and make my work result loss. Moreover, it doesn't  prompt me for unsaved file when I exit it.

**Comment by lee-dohm** [comment]
I'm sorry to hear that you're disappointed with Atom. Can you give us any indication of how to reproduce this problem? We haven't ever seen Atom delete content from files after they have already been saved successfully.

As for not prompting to save unsaved files when you exit, this is the expected behavior due to the crash recovery features in Atom:

http://blog.atom.io/2016/04/12/atom-1-7-and-1-8-beta.html#crash-recovery

If you can supply steps to reproduce the behavior you're describing, please feel free to open a new Issue with that information.
