### ISSUE TITLE
`core:paste` of text copied using `editor:copy-selection` pastes at start of line, instead of cursor.

### ISSUE THREAD

**Issue by MichaelJCole** [atom/atom#11542]
### Background

Hi, pressing ctrl-c on an empty line, copies the whole line.  Which is fine, except it deletes what's on the clipboard which is incredibly annoying.  I'd select the line if I wanted it.

A work-around, from this merge: https://github.com/atom/atom/pull/8025
and described here: https://github.com/atom/atom/issues/7103
is to use this in keymap.cson:

```
'atom-text-editor':
  'ctrl-c': 'editor:copy-selection'    # linux and windows
```

But unfortunately that pastes at the start of the line, instead of the cursor.  I'm using Atom 1.5.3 on Ubuntu 14.04.

Thanks!

### Steps to Reproduce

1.  Edit -> Preferences -> keybindings -> tiny link at top: 'your keymap file'
2.  paste above code
3. Save `keymap.cson`
4.  Open file.  Select some text in middle of line.  ctrl-c
5.  Ctrl-v and it's pasted at start of line.

**Expected behavior:** [What you expected to happen]

pasted at cursor

**Actual behavior:** [What actually happened]

pasted at start of line

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Atom 1.5.3 on Ubuntu 14.04

**Comment by MichaelJCole** [comment]
@lpommers @maxbrunsfeld Hey, am I using this right?  Thanks!

**Comment by lee-dohm** [comment]
Copying the entire line when there is no selection is the intended behavior. If you wish to have <kbd>Ctrl+C</kbd> mapped to `core:copy-selection` for your own use, you can add the entry you give to your `keymap.cson`.

Please let me know if I've misunderstood your submission.

**Comment by MichaelJCole** [comment]
Hi @lee-dohm , I think you misunderstood. 

I'm having a bug with `'editor:copy-selection'`.  It pastes incorrectly.

Here's a demo video:  [demo.ogv.zip](https://github.com/atom/atom/files/231827/demo.ogv.zip)

`core:copy-selection` has a different issue.  I'll make another issue for that.

**Comment by lee-dohm** [comment]
`editor:copy-selection` doesn't do any pasting, so I'm not sure what you mean by "pastes incorrectly".

**Comment by MichaelJCole** [comment]
Yes, thank you!  I rarely think about editors my life is so full of them :-)

**Comment by sinisarudan** [comment]
the suggested solution doesn't work in newer versions (e.g. ver 1.22.1), as worked before, because of different coding of the `keymap.cson` file:
but these steps work:

Atom -> Preferences -> Keybindings -> Click link at very top "your keymap file"
This should open a `keymap.cson` file in the editor.

Paste this:
```
'body':
  'cmd-c': 'editor:copy-selection' # mac os
  'ctrl-c': 'editor:copy-selection'    # linux and windows

```
(I tested it on Mac, if it doesn't work on Win, you might need to adjust 'ctrl-c' code)

P.S. if the internal coding of the `keymap.cson` file changes over time, you can go to 
Atom -> Preferences -> Keybindings
and then you find there an entry with 'Keystroke' equal to 'cmd-c' and Selector equal to 'body'.
You should copy the code of this settting by clicking on the icon on the left of that entry-row, and use it as a model for your entry in  `keymap.cson`

Here is screenshot (for Mac) of the above-writen:
<img width="575" alt="screen shot 2017-11-20 at 11 36 25" src="https://user-images.githubusercontent.com/1769627/33014283-1f5f0ff6-cde7-11e7-9fe2-e1e63ba06572.png">
