### ISSUE TITLE
Feature request: html syntax definition inside es6 template literals.

### ISSUE THREAD

**Issue by aminroosta** [atom/atom#11589]
I have implemented this feature for sublime before, how can i implement the same thing for atom?

here is a screen shot for sublime, as you can see html tags inside es6 strings are highlighted.

![typescript_syntax_definition-changed](https://cloud.githubusercontent.com/assets/2920178/7555396/5c84f424-f75f-11e4-92d5-f9e304bb1ff5.png)

**Comment by 50Wliu** [comment]
If your function has the world `html` in it language-javascript will highlight the code as HTML.  Not sure when that feature became available though.

In the future please use https://discuss.atom.io for questions like these.

**Comment by devboxr** [comment]
Hi there @50Wliu,

you closed this topic but it was not a very helpful answer. Maybe you can briefly elaborate on what exactly you meant, as this page pops up on top of Google when looking around for the solution.

Cheers

**Comment by 50Wliu** [comment]
For example:
```js
/* some js code, maybe implementing the html function */
html: `
  <h1>A header!</h1> <!-- This will be highlighted as HTML -->
`
```
As long as your template function ends with `html` in it the template string's contents will be highlighted as HTML.

**Comment by baffleinc** [comment]
Are there any better solutions to this? In my case the property must be `template` not `html`.

**Comment by felipeccastro** [comment]
You can use a [tagged template literal](http://www.2ality.com/2015/01/template-strings-html.html) named as `html`.

<img width="423" alt="screen shot 2016-10-17 at 1 15 51 pm" src="https://cloud.githubusercontent.com/assets/3835098/19443561/e0e1a618-946b-11e6-84da-d7edcc1a6276.png">

**Comment by PapyElGringo** [comment]
html: ` is not working only html ` (without the : ) so html function is undefined

**Comment by felipeccastro** [comment]
the `html` tag template helper is a function that must be declared before you use it. The article linked in my previous comment shows a possible implementation. Here's [another](https://github.com/AntonioVdlC/html-template-tag)

**Comment by AlexanderElias** [comment]
I created a grammar injection which provides HTML and CSS syntax highlighting. Its called [language-javascript-plus](https://atom.io/packages/language-javascript-plus)

Usage is easy, simply declare a variable or property with the name html, template, css, or style then use the backtick. HTML and CSS will be using their own syntax highlighting. 

Let me know what you think suggestions are welcome and please inform me of any bugs.

**Comment by skylize** [comment]
> Are there any better solutions to this? In my case the property must be template not html.
> edit: https://atom.io/packages/language-babel

The `language-babel` package is passing it off to other grammars. This makes it more easily extensible because you can use any grammar, not just html, but it means the javascript inside your template string doesn't get parsed as javascript.

___
I think this feature should be extended with an option for any arbitrary regexp match for the tag instead of just "html". My use case is `hyperhtml` where I'm passing templates to a `wire()` function like so:
```
const someComponent = wire()`
  <div>${ getDivContents() }</div>
`
```

I cannot just rename `wire`, because `wire` needs to called fresh each time it's given a new template. It _is_ actually possible to convert this example to work with Atom by adding a single line of code to each file.
```
const html = (...args) => wire()(...args)
```
But this line of code has no business in any of my source files, because it doesn't do anything except hack my editor. And `wire` also accepts arguments before giving it a template, which doesn't work at all with this hack.

```
// How am I supposed to hack this one? I guess I must define `html`
// again locally every time I need to pass arguments to wire?

const someOtherComponent = wire({ props })`
  <div>${ getDivContents({})</div>
`
```

I should be able to define a tag match in Settings like `/wire\([{},\w\s]*\)/` to match the tag I'm actually using, instead of being stuck with only one option of 'html' for my tag.

**Comment by GuyMograbi** [comment]
Anyone reaching here and still searching for an answer I just installed 'language babel` and it solved this issue for me.
