### ISSUE TITLE
The TextEditor.softTabs-implementation favors SoftTabs over HardTabs

### ISSUE THREAD

**Issue by florianb** [atom/atom#11611]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
  - Yes, there are some open Issues (like #10169) which are related to `softTabs`, but i guess nobody did track down what may go wrong.

> ℹ️ I open this issue as a result of my investigations on https://github.com/sindresorhus/atom-editorconfig/issues/81.
I tried to lay this down as condensed as possible - i rely on the codebase of the current master-branch.

- The current `TextEditor.softTabs`-implementation knows two states, being `true` to enable soft tabs and being `false` to enable hard tabs.
- `.softTabs` is amongst others being interpreted by [`.shouldUseSoftTabs()`](https://github.com/atom/atom/blob/master/src/text-editor.coffee#L2618) and the following line (if the softTab-config is set to **auto**):

`@usesSoftTabs() ? defaultValue ? @config.get('editor.softTabs') ? true`

In my understanding this chain will always prefer a `true` over a `false`, respectively a soft tab over a hard tab.

This leads in at least one situation to a unexpected switch of the softTabs-setting: if the user (f.e. by a package) manually sets hard tabs and the handleTokenization is being called afterwards. I couldn't find out when this happens actually, but it happens and breaks [atom-editorconfig](https://github.com/sindresorhus/atom-editorconfig).

📌  I created a hopefully self-explaining spec: https://gist.github.com/florianb/ccc1ec184b86f139f9cadee71dc26f7b

Give me a hint if i am wrong or if you need more information. I will try to help however i can.

Thanks so far! 🍬

**Comment by hawsome** [comment]
I'm starting to believe it may have to do with some conflicts with language packages like `language-babel` that might be overwriting settings.

**Comment by florianb** [comment]
💡 I started working on a spec, to show what's going on.

**Comment by florianb** [comment]
I suppose making softTabs officially a tristate-value would solve the problem (`null`/`undefined`, `true` and `false`).

Of course, the evaluation of `.usesSoftTabs()` must be fixed, too. Since the case where it might return `undefined` is being treated as a "false", which is wrong.

**Comment by lee-dohm** [comment]
From the description, I'm not sure what the fix is. Can you explain what actually happens and what you expect to happen in each case?

**Comment by hawsome** [comment]
steps to reproduce and temporary fix by switching syntax to `Babel`:
![tabs](https://cloud.githubusercontent.com/assets/567126/14871470/40f4871c-0c97-11e6-8aaa-933c8d8ec2d4.gif)

**Comment by florianb** [comment]
That's maybe a problem. I investigated the issue due to debug-measurements for https://github.com/sindresorhus/atom-editorconfig. I will try to explain what happens in overall:

You need to have `config.softTab` being set to `auto`.
1. Editorconfig hooks into the `observeTextEditors` subscription and locally changes all settings accordingly to the config in duty.
2. Saying now you're in a file where `.setSoftTabs(false)` has been invoked (f.e. by Editorconfig). You start writing, leaving `\t` (hard tabs) whenever tabbing around.
3. If the buffer now gets tokenized (you may provoke that by changing the language) the softTabs are [**always**](https://github.com/atom/atom/blob/79fa94e720f50557cddb25c1cd288d72767b914e/src/text-editor.coffee#L2660) being [reset](https://github.com/atom/atom/blob/79fa94e720f50557cddb25c1cd288d72767b914e/src/text-editor.coffee#L3193) to `true`.

I would expect that an explicitly set `.softTabs`-attribute survives as long as the TextEditor lasts.

**Comment by lee-dohm** [comment]
I can't reproduce what you're describing. Here is what I did using Atom v1.9.0-dev-c4d4e0f on Mac OS X 10.11.4:

1. Launched Atom
1. Opened Settings View
1. Set Tab Type to `auto`
1. Unchecked Soft Tabs
1. Opened a file (using only spaces for indentation because that's normal for me)
1. Used my [tabs-to-spaces package](https://atom.io/packages/tabs-to-spaces) to change the indentation to tabs
1. Opened the Developer Tools console using <kbd>Cmd+Alt+I</kbd>
1. Entered your code `atom.workspace.getActiveTextEditor().setSoftTabs(false);`
1. Entered `atom.workspace.getActiveTextEditor().getSoftTabs()` which returned `false`
1. Focused the editor and changed the syntax from Elixir to Ruby
1. Entered `atom.workspace.getActiveTextEditor().getSoftTabs()` which returned `false`
1. Entered `atom.workspace.getActiveTextEditor().softTabs` which also returned `false`

As far as I can see, the explicitly set `.softTabs`-attribute is surviving here.

Additionally, this code:

```coffee
@usesSoftTabs() ? defaultValue ? @config.get('editor.softTabs') ? true
```

Doesn't always return `true`. If any of those items returns false, then that expression is false. For example, if `@usesSoftTabs()` returns `false` because it detected that the file contains tab indentation, it will return false. The `?` operator in CoffeeScript coalesces `undefined` and `null` values. If you go to http://try.coffeescript.org and enter the code:

```coffee
foo = undefined ? null ? false ? true
alert(foo)
```

The alert dialog will display `false`.

Now, if the file contains a mixture of spaces and tabs for indentation, the expression you're pointing to *can* return true. It will return true if the first non-comment line in the file that has leading whitespace has a space as the first character. This is easily fixed by setting TabType to `hard`.

If you're saying that changing the grammar of a file should not cause autodetection to happen again, that might be something we can look into. Though I think the easier fix here would be for editorconfig to subscribe to the grammar changed event and set the tab type again.

**Comment by florianb** [comment]
Thank you @lee-dohm for the time you spent - i believe i made a mistake and did make a Freudian assumption about the root of the behavior, leaving out to check the transpiled js-source (and relying instead on a misleading StackOverflow-post about the `?`-operator). This was definitely not my week. 😩 

Dropping softTab-detection after tokenization would perhaps be a performance-enhancement, but is for sure not paying out the efforts to do so.

So i am closing this issue, trying to figure out why my specs failed.

Thanks again, i really appreciate your patience.

💐

**Comment by lee-dohm** [comment]
@florianb You're most welcome! Thank you for digging in and working on this with me :grinning:
