### ISSUE TITLE
[Feature] Notification about update (instead of auto download + install)

### ISSUE THREAD

**Issue by rejhgadellaa** [atom/atom#11654]
I had to disable "check for updates" under Help > About because Atom would download updates over a roaming connection (wifi tethererd via phone). But now I have to remember to check for updates. Wouldn't it be better if it would still check for updates but give a notification for it when one is available?

The default behaviour could still be to automatically download and install them, but instead of a checkbox with "Check for updates" I'd rather see a "Automatically download updates" option and a notification if it isn't checked.

Or maybe this is an idea for a package? I have no experience with building those for atom so... uuhm.. I'd need help with that :)

**Comment by bj7** [comment]
Doesn't the little blue squirrel on the status bar indicate if new updates are available? Or am I completely confused on that, or does it only show if you have auto-update enabled? If I'm not confused, would the squirrel do the trick, or are you looking for something more in lines of a popup notification?

**Comment by rejhgadellaa** [comment]
Uhm which squirill..? Did I miss that? Anyway, i think that would not work when atom doesn't check for updates at all when the box is unchecked and that's the only option we have atm.

By popup you mean a dialog? Nah, something like a native windows or osx notif should do the trick (just slide in to view and dismissed after a bunch of seconds) just to let you know it's there.

**Comment by lee-dohm** [comment]
As discussed in https://github.com/atom/about/pull/12, the Squirrel framework (which we use for our autoupdating support) doesn't currently support this mode of operation. Until that changes, we're not going to be able to offer this ability.

Also, since all of our updating functionality is now in the [about package](https://github.com/atom/about), this Issue should be on that repository. Would you mind reopening it there?
