### ISSUE TITLE
Tabbing forward and back

### ISSUE THREAD

**Issue by Kaperstone** [atom/atom#11780]
Atom version: 1.7.3
OS: Ubuntu 14.04 LTS 
(experienced the same behaviour on Fedora 23 with earlier version and 1.8.x beta version)

There are two issues I am having with the tabbing.
The first is that alt-tab chooses the tab on the left side, while alt-shift-tab chooses the tab on the right.
Before recently (not sure when it appeared, I upgraded from 1.6.x and it suddenly started to happen) it worked the opposite and sometimes it works like so.

I tried to override it with the keymap, but it completely fucked up my tabbing navigation, somtimes had to click twice to go to any of the tabs, sometimes once and sometimes it even stuck. (not switching to any tab)

Another issue is that it jumps between tabs.
As an example: say we have 4 tabs
| tab1 || tab2 || tab3 || tab4 |
and I am currently on tab3, pressing alt-tab would open me tab2, pressing again would open tab4 and again will open tab1 and then back to tab3
continuing to press these keys will travel the same way.

I don't know what causes any of two, but it happens randomly, meaning that sometimes it works properly and sometimes it doesn't.

Last but not least, while selecting a file, it opens it in a read mode causing the next file select to take place of the current tab, in other words, won't open in a new tab.
I know that double clicking will open it in write, but can an option be added to disable opening files in read mode completely ?

I am experiencing this issue for a long time, and I thought its minor problem and it will be fixed at some version, but it didn't and it starts to really bother me and makes Atom really uncomfortable to me.

*Side note*: I am not an expert nor package rich user, I only have the Atom setup and minimap and pigments as installed packages.

**Comment by thomasjo** [comment]
The tabbing behavior is caused by https://github.com/atom/atom/pull/10737, and there's currently an [open issue](https://github.com/atom/atom/issues/11035) for making the new behavior configurable.

The other behavior (the so-called "read mode") is the pending item functionality, which was introduced in https://github.com/atom/atom/pull/10178. The feature was made configurable in https://github.com/atom/atom/pull/10846.

![image](https://cloud.githubusercontent.com/assets/3622/15333667/02e848a8-1c6b-11e6-8b02-fd7f792c842f.png)
