### ISSUE TITLE
Tabbing appears to not follow visual order

### ISSUE THREAD

**Issue by neilwhitespace** [atom/atom#11789]
### Description

The tab order appears to now be following visual order when switching using the `pane:show-next-item` or `pane:show-previous-item` commands (regardless of the shortcut used to initiate this command)

### Steps to Reproduce

1. Open a number of tabs
2. Close a tab (not the last one)
3. Open a new tab

**Expected behavior:** The tabs should switch as order of display.

**Actual behavior:** The tabs switching to the new tab before the tab which was the last in the list before the new tab was opened.

### Versions

Atom: 1.7.3
APM: 1.9.2
Running Mac OS X 10.11.4

**Comment by albertosantini** [comment]
In Atom 1.7, ctrl-tab will switch between the most recently used (MRU) tabs in an Atom window instead of switching to the tab to the right of the current tab.

http://blog.atom.io/2016/04/12/atom-1-7-and-1-8-beta.html

Generally speaking, you may read a recent [post](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html) about managing issue.

**Comment by Ben3eeE** [comment]
There was a bug with tab index being incorrect if you used the Add new tabs at end configuration option.
This was fixed in 1.7.4, can you still reproduce this in 1.7.4?

**Comment by neilwhitespace** [comment]
This actually appears to be working again in 1.8.0 and I can no longer reproduce the above.

**Comment by Ben3eeE** [comment]
Then it is likely that this was fixed by https://github.com/atom/tabs/pull/302.

**Comment by lee-dohm** [comment]
Thanks @neilwhitespace for following up. Let us know if you can reproduce this again in the future!
