### ISSUE TITLE
Flatpak release support

### ISSUE THREAD

**Issue by xavier83** [atom/atom#11837]
### Prerequisites
- [x ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [ x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [ x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Need release of linux sandboxed apps [Flatpack](http://flatpak.org/).
### Steps to Reproduce
1. Goto atom release page https://github.com/atom/atom/releases/

**Expected behavior:** [What you expected to happen]
Find flatpak atom package.

**Actual behavior:** [What actually happened]
Can't find flatpak atom package.
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by jokeyrhyme** [comment]
Ubuntu has "click" packages:

- https://developer.ubuntu.com/en/publish/packaging-click-apps/

For everyone else (including Ubuntu):

- http://flatpak.org/

LibreOffice is now available via Flatpak:

- https://whatofhow.wordpress.com/2016/06/01/libreoffice-5-2-beta-flatpak/

Although there are some caveats:

> Flatpak-based apps are not yet able to reach out to other applications installed on the machine (like browsers) to e.g. open URLs through them. That means that e.g. clicking on a hyperlink in a LibreOffice Writer document might not work yet.

Besides being a path to having a single Linux bundle format, there are also sandbox features that might be appealing. Might be nice to know that an Atom extension can't modify /boot, etc.

**Comment by Yajo** [comment]
Another cool thing is that it can include a native update mechanism, so it would fix #2956 BTW.

**Comment by diegobfernandez** [comment]
Flatpak have [Portals](https://github.com/flatpak/flatpak/wiki/Portals) now that fixes the reaching out other applications problem.

**Comment by jokeyrhyme** [comment]
Looks like Flatpak is currently the better cross-distribution bet: https://kamikazow.wordpress.com/2017/02/09/adoption-of-flatpak-vs-snap/

**Comment by exploide** [comment]
In case someone of you wants to try out an Atom flatpak, I found that the Flathub repository includes it. https://flathub.org/apps.html#Atom

But I want to note that I'm not confident that this will fit a lot of common development workflows!

The sandboxing makes it impossible to call applications from the outside. So all the extension packages making use of external tools will not work out of the box. You cannot just call your favorite linter, attach with gdb to an already running program or just use the version of the compiler you deliberately installed instead of the older one included in the flatpak runtime.

For that reason, the Atom flatpak from Flathub bundles the python-language-server, as of this writing, to make Python development somewhat possible. But this is rather inflexible and simply does not scale for everything a developer can wish.

So while I liked the idea of Flatpak, I do no longer think it is a proper solution for a versatile development tool. (if of interest, my thoughts came out of this conversation: https://github.com/flathub/io.atom.Atom/issues/2)

**Comment by Croydon** [comment]
This is still relevant.

**Comment by joshcangit** [comment]
Yes, but the Flatpak version of Atom can be very buggy at times due to packages requiring the directory to be in **~/.atom** rather than **~/.var/app/io.atom.Atom/data**.

**Comment by xavier83** [comment]
Since the original issue is resolved, I'm closing this issue. Thanks to the authors and users of atom, flatpak  for making it happen.
Also a better place for filing bugs in the flatpak package would be at https://github.com/flathub/io.atom.Atom/issues
