### ISSUE TITLE
Move Line Up

### ISSUE THREAD

**Issue by A-Shleifman** [atom/atom#11848]
### Description

If I want to move the last line in a file up I can do it by pressing Ctrl+Cmd+Arrow (Mac)

**Proper behavior:** 

If there is a newline character at the end of that line, it will change from 

```
Previous line
Last line
```

to

```
Last line
Previous line
```

**Wrong behavior:** 

But if there is no newline character at the end of the last line, the hotkey will just concatenate it with the previous line

```
Last linePrevious line
```

---

Version 1.7.4
Problem persists in safe mode.

**Comment by hultberg** [comment]
Confirmed on OSX El Captain using atom 1.7.4 in safe mode.

**Comment by mxmlnkn** [comment]
Can also reproduce on Debian sid with Atom 1.8.0.

**Comment by alexrussell** [comment]
Just discovered this myself in 1.9.0-beta0, OSX 10.10.5.

Presumably due to the fact that `move-line-*` commands assume that all lines end in a `\n` (or whatever the platform newline character is) and therefore it ends up placing the content of "Previous Line" directly after the contents of "Last Line" which ends up adding it on with no newline as there is no newline on "Last Line"
