### ISSUE TITLE
Exposing state-store.js

### ISSUE THREAD

**Issue by rageandqq** [atom/atom#11851]
Would you consider exposing the `StateStore` class in a seperate `npm` module?
https://github.com/atom/atom/blob/f6352cb47bb579e0848d1d3aa73a573cd3585d98/src/state-store.js

I think it'd be really useful for other projects in general, as it essentially provides a non-blocking async alternative to `localStorage`. I've looked around and can't seem to find anything that simplifies the `IndexedDB` interface to a key-value store like what's been done here!

**Comment by mehcode** [comment]
@rageandqq 

https://www.npmjs.com/package/focalstorage is the close/best that I found from a cursory search.

It's more-or-less the localStorage API but powered by IndexedDB. 

---

As Atom more-or-less re-implements this.. does it make sense to just use this guys package instead of the home-rolled code in atom?
