### ISSUE TITLE
Studying the evolution of Atom's project

### ISSUE THREAD

**Issue by gustavopinto** [atom/atom#11878]
Hi there, 

I'm a researcher studying software evolution. I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers Atom was in my list. 

To further analyze the impacts of Atom’s migration, we analyzed the git log commit history of your project in terms of _number of contributions_, _number of newcomers_, and _number of contributors per month_. The following figure presents a temporal perspective regarding these three measures. 

![atom](https://cloud.githubusercontent.com/assets/235062/15728231/1bf2b7b0-2810-11e6-9636-319e9fd20c87.png)

Given the numbers presented in the graphic, we would like to ask Atom developers the following questions:

1. What motivated the project to open its source code at Github? How do you evaluate the benefits of this migration?
2. Does this snapshot make sense? Did you find any inconsistency on the data?
3. Do you have any internal policy to promote/attract/retain newcomers? If so, do them succeed?
4. Why the number of contribution did not increase while the number of contributors increased?
5. Did you expect an increasing number of newcomers joining the project right after it became open-source?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by lee-dohm** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster. For your specific questions, I'll be happy to take a look on Discuss since this isn't a bug or feature request that needs to be addressed within Atom.
