### ISSUE TITLE
Ctrl-/ doesn't work 

### ISSUE THREAD

**Issue by fuuccker** [atom/atom#11877]
When I press ctrl+/, comment doesn't work. I change the keymap to use ctrl-7 instead:

`'ctrl-7': 'editor:toggle-line-comments'`

But it didn't work too.
I press ctrl-. for keymap resolver, and when I press ctrl-7 this is what I get:

`tree-view.open-selected-entry-in-pane-7  .platform-win32.tree-view  .platform-linux.tree-view   /opt/atom/resources/app.asar/node_modules/tree-view/keymaps/tree-view.json`

**Comment by hultberg** [comment]
This issue is missing required information as provided in the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md). Some important thins we would like to know is:
- What operativ system are you using?
- What version of atom are you using?
- Do you see the same behaviour with `atom --safe`?

**Comment by 50Wliu** [comment]
Information not provided, closing.
