### ISSUE TITLE
Debugging .Net Core apps

### ISSUE THREAD

**Issue by jbeckton** [atom/atom#11944]
I want to switch to Atom from VS Code but I cannot find any info on whether or not there is a debugger available for .net core on atom. Google searches are not producing anything helpful.

**Comment by arcticicestudio** [comment]
There are better ways to search for packages:
  - terminal via `apm`
  - in Atom via *Settings* > *Install*
  - the website/webinterface at [https://atom.io/packages](https://atom.io/packages)

You can read the [Atom Documentation](https://atom.io/docs) ([Atom Flight Manual - Atom Packages](http://flight-manual.atom.io/using-atom/sections/atom-packages/))

I've never coded in .NET, but there are several packages if you [search for ".NET"](https://atom.io/packages/search?q=.NET) like [omnisharp-atom](https://atom.io/packages/omnisharp-atom), which uses Mono and a build-in server to transform Atom into a C# IDE.

Anyway, I love Atom and it runs almost the whole day (work  + private) on my maschine, but I also think Atom or VS Code aren't the best solution if you want to code Java/C#/C++/C etc. since it is basically a web development IDE, even if it is "hackable" and can be extended to do almost everything. It lacks in support of so many things like debugging, autocomplete e.g. the JDK and features like that.

You should check out JetBrains [Project Rider](https://blog.jetbrains.com/dotnet/2016/01/13/project-rider-a-csharp-ide), the new C# IDE currently in early access.

**Comment by jbeckton** [comment]
@arcticicestudio I have searched the Atom packages site prior to Google, there may be a debugger I am just not sure where or how to access it.

I stumbled across that JetBrains "Project Rider" and it looks promising. When I am not doing .Net I use WebStorm, love the JetBrains tools. I got some stuff to get done so I am a little reluctant to use an early release IDE as I don't have time to deal with any issues that may arise at least for this project.

I was using VS Code for a web app for almost 3 months, figured I'de give it a fare shake. As my project grows VS Code is not helping much with the UX side while trying to visually keep track of files and project structure. I often find myself getting lost in the project structure and I need to have several files open on multiple monitors and tabs to stay focused. VS Code is just not there yet.

**Comment by 50Wliu** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
