### ISSUE TITLE
upgrade electron version to latest stable version

### ISSUE THREAD

**Issue by muayyad-alsadi** [atom/atom#11967]
### Description

It seems that atom is designed to work a legacy version of Electron (namely version "0.37.8")
While the latest stable version is "1.2.2".

- https://github.com/atom/atom/blob/master/package.json#L15
- http://electron.atom.io/

Actually Electron 1.x works fine.

**Expected behavior:** use latest stable version.

**Actual behavior:** use of very old legacy version.

### Additional information

Fedora copr and Arch AUR ship atom that uses latest Electron and it's working fine.

Some minor issues that can be easily fixed are reported and can be fixed like this one

https://github.com/atom/autocomplete-plus/pull/726

**Comment by muayyad-alsadi** [comment]
please if this is not a valid issue, please please provide a link to milestone or a published discussion why you want this specific version and when you plan to upgrade.

**Comment by Nikki1993** [comment]
@muayyad-alsadi 0.37.8 is actually a 1.0.1 version of Atom so it's not THAT old. Reason why Atom only incrementally updates electron is to minimize application breakage due to Atom project's size. 

No one here will give you a definitive **when** the upgrade is planned. If you wish to speed up the process, build atom with latest electron, test, fix regressions if any and provide review. Testing will be needed and that can takes a month (like with 0.37.8) before it reaches even beta version. 

And again, just to reiterate, even if the fix looks simple, do not treat it as such. Like and old pic says http://i.imgur.com/HTisMpC.jpg

**Comment by muayyad-alsadi** [comment]
> if you wish to speed up the process, build atom with latest electron, test, fix regressions if any and provide review. 

@Nikki1993  I'm using atom with the new the electron, so technically I'm doing what you have suggested, so do most fedora/arch users. as our provider shipper new electron (maybe by mistake)

I've submitted a patch that fix something when using 1.2.2 and does not break in 0.37.9. And it was rejected just because it works on 1.2.2.

If you want it to gradually move to 1.2.2, we should accept such PR.
But from what I see, you are not accepting PR because there seems to be an aware decision not to move to 1.2.2

There should be a milestone and maybe branch for such crazy changes, those PR should be accepted in that specific branch.

BTW: I'm not sure how the silly "if" statement added in my PR caused so much discussion. it's a simple "if". actually I don't know why it's related to electron in the first place. it's about calling get file basename on a undefine.

**Comment by Nikki1993** [comment]
@muayyad-alsadi I am not affiliated with the atom team though :)

I totally get you, but most likely team is not switching to newest electron due to lack of manpower internally. A lot of people are on vacation so I guess they don't want to introduce major upgrades until everyone is back. My guess though, not an actual reason :)

**Comment by 50Wliu** [comment]
The much larger blocker to updating Electron is community packages\*.  A decent amount of packages use Electron APIs, and package authors should be given time to update their packages.

> If you want it to gradually move to 1.2.2, we should accept such PR.
> But from what I see, you are not accepting PR because there seems to be an aware decision not to move to 1.2.2

That was not what @lee-dohm said when he closed your PRs:
>It is true that we'll have to address this eventually, but I think we'll address it in a more comprehensive way.

At least for me, that does not imply that the Atom team does not want to update to a newer Electron version.

> There should be a milestone and maybe branch for such crazy changes, those PR should be accepted in that specific branch.

While the Atom team does not use milestones, there will be a branch dedicated to updating Electron (as there always has been).

\* This is my personal opinion.  Other members of the Atom team may have different opinions on the upgrade to Electron 1.x.

_Disclaimer: I am not an Atom employee, only a community volunteer, and some of the above information may be incorrect._

**Comment by Nikki1993** [comment]
@50Wliu @lee-dohm I am curious, since I am no hardcore dev, is there a possibility of upgrading atom core to the latest electron version, while 3rd party packages would still utilize older version of electron? or is that going to cause some sort of version mismatch error, etc? 

I do believe there is little benefit in falling so far behind in package updates (looking at you, Ubuntu :D) so if atom were able to update electron version to latest upon release that would be a blast.

**Comment by 50Wliu** [comment]
> or is that going to cause some sort of version mismatch error, etc?

I'm not familiar with the Node/Electron internals but I'm pretty certain that will cause all kinds of module mismatch errors (as well as drastically increase the download size, since now we need to ship two versions of Electron...).

**Comment by lee-dohm** [comment]
The request here is for us to upgrade to the latest version of Electron as soon as it is released. We won't do that if it breaks Atom for people who just want it to work without having to patch it themselves. What we will do, and have done in the past, is upgrade to the latest version that makes sense as soon as we can. We do this by opening a PR (with an underlying branch of course) and making changes to that PR, asking people to help us test it and fix it as we go. Then when everything is ready, we merge the whole thing.

This strategy:

1. Allows us to continue focusing on moving Atom forward without getting bogged down by Electron changes
1. Allows us to focus the people who are interested in having the latest Electron in one place
1. Allows us to make sweeping changes when they are necessary without having to nickel-and-dime ourselves with one- or two-line PRs *ad infinitum*
1. Allows us to ensure that packages remain compatible with the older version of Electron even as they are updated
1. Allows us to easily abandon Electron changes when it makes sense (such as to skip Electron versions)

As I stated [in my recent blog post](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), we have too many Issues to handle well even when we are only counting Issues that apply to the current set of three platforms (Windows, macOS and Linux) multiplied by three released versions (dev, beta and stable). Multiplying this again by a hodge podge of versions of Electron people think we should be on already is unsustainable with the resources we have.

So we will move to new versions of Electron as we can, when it makes sense, when we can guarantee a certain level of stability for *all* users of Atom, when we can work with our package authors (who we feel are a significant part of Atom's success) to ensure that their hard work isn't broken or at least they have fair warning, and when the benefits outweigh the downsides. We won't commit to a timeline because every new version of Electron brings with it new challenges. Some take longer and some are easier.

I hope that makes clear our general Electron upgrade strategy.

**Comment by lee-dohm** [comment]
@Nikki1993 

> is there a possibility of upgrading atom core to the latest electron version, while 3rd party packages would still utilize older version of electron?

No, Electron doesn't work like that. There can be only one version of Electron loaded within a process space. We *might* be able to have community packages use an older version of Electron if we ran them in a separate process, but that would require completely rewriting the way Atom packages work ... and then rewriting all packages to work that way. It would be far less work to just fix the packages that break on the latest Electron.

**Comment by muayyad-alsadi** [comment]
> The request here is for us to upgrade to the latest version of Electron as soon as it is released. 

I said

> please if this is not a valid issue, please please provide a link to milestone or a published discussion why you want this specific version and when you plan to upgrade.

so clearly this this issue here is not a valid issue, no problem. no need to upgrade Electron. Just document that, have a milestone or a wiki page or open issue or whatever you use to manage this product indicating how, when, why, ... you choose versions.

my problem is not refusing to upgrade instantly, the problem is that we (the community outside core employee/church) don't know why, when, how the upgrade will happen and how we can help getting it done.

> is there a possibility of upgrading atom core to the latest electron version, while 3rd party packages would still utilize older version of electron?

or make them carry some metadata which version of atom they are expected and tested to work.

**Comment by lee-dohm** [comment]
> Just document that

Look for my document in atom/design-decisions later today. It'll basically be the same thing I posted above.

> or make them carry some metadata which version of atom they are expected and tested to work.

We already have that, [see the engines field in the `package.json` of one of my packages](https://github.com/lee-dohm/tabs-to-spaces/blob/43f66d344aa9d8eaddc2f790f3d82e2d8705d94b/package.json#L15-L17).
