### ISSUE TITLE
Inconsistency in keybindings configuration

### ISSUE THREAD

**Issue by rfjhslfk** [atom/atom#11975]
If I copy a keybinding from Preferences -> Keybindings and add it to my keymap.cson, Atom's behaviour should not change.  Here is an example where this doesn't hold.

Using Atom 1.8.0 with a fresh home folder just for this test (ATOM_HOME=...) on Ubuntu 14.04.

Create a new file, change the grammar from Plain Text to Python, and paste the following:

    asdf = 0
    as

Now place the cursor after the `as` on the 2nd line and type `d`.  The autocomplete offers `asdf` as the only suggestion.  Press tab.  `asdf` is autocompleted.

Now add to keymap.cson the following:

    'atom-text-editor:not([mini])':
      'tab': 'editor:indent'

This exact binding (including the selector) was copied straight from Preferences -> Keybindings - search for "tab" and you will see it with source "Core".

Repeat the test - place the cursor after the `as`, type `d`, and press tab.  A tab is inserted.

**Comment by lee-dohm** [comment]
> If I copy a keybinding from Preferences -> Keybindings and add it to my keymap.cson, Atom's behaviour should not change.

This would be the case except for the fact that keybindings are given a priority based on [CSS specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity). The one overarching rule of specificity is that all things being equal, the last rule encountered wins. Since the user's `keymap.cson` is always loaded last, placing a rule in there can indeed change behavior. For example, if you have the following in a CSS file:

```css
.foo { color: red; }
.foo { color: white; }
.foo { color: blue;}
```

The color assigned to the `.foo` class will be blue. But if you do this:

```css
.foo { color: red; }
.foo { color: white; }
.foo { color: blue;}
.foo { color: red; }
```

The color assigned to the `.foo` class will now be red, even though I just copied a rule that already existed and pasted it at the end.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions or other discussions like this one, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
