### ISSUE TITLE
Ctrl+S

### ISSUE THREAD

**Issue by dingv** [atom/atom#11996]
Every time I use Ctrl+S in Atom I get the message "The editor has crashed / Please report this issue [to this repository]". If I open the file again it actually does save the material, but this will be just a bit annoying until I can figure out a way to stop it from happening.

**Comment by arcticicestudio** [comment]
Is this happening in `atom --safe` mode too? There's maybe a bug in on of yout installed packages which occures when the save event gets triggered.

**Comment by hultberg** [comment]
Please fill out the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) as provided when you create new issues.

**Comment by thomasjo** [comment]
@dingv As pointed out by @hultberg, please fill out the issue properly by following our [issue template](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md) (which gets added to new issues automatically).

Following the template leads you through verifying if the problem is present in safe mode or not, which is a crucial piece of information required to help you resolve this issue.

**Comment by lee-dohm** [comment]
Closing due to lack of response.
