### ISSUE TITLE
Building a release

### ISSUE THREAD

**Issue by jsloyer** [atom/atom#12012]
I am curious how atom builds a release.  I know atom uses Travis and appveyor to build commits but is there any kind of automation that you all use to build releases or do you manually generate them by hand

**Comment by lee-dohm** [comment]
Parts of the process are manual and parts of the process are automated (like almost every release process I've ever been involved with). We're working on documenting the parts that we think are relevant to people outside of GitHub so that people can be more aware of what goes on behind the scenes. Keep an eye on the [docs directory](https://github.com/atom/atom/tree/master/docs) for updates.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
