### ISSUE TITLE
[improvement] Decouple palette rendering from result gathering.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#12014]
This change becomes necessary when sifting through many results in the palette. For example, when pressing ctrl+p to open the file palette, typing something in is very laggy while Atom looks for matching files character by character.

To improve performance, we can decouple (run on separate ticks) rendering of the palette and result gathering (and possibly provide a loading animation while results are being gathered).

This will make typing always smooth regardless of how long it takes to load results.

Was the design of the palette meant to be synchronous? The only advantage I see for synchronous rendering is that typing and pressing enter will guarantee a certain result to exist by the time enter is pressed, while decoupling rendering will cause enter to possibly do nothing until enter is pressed when a result is present, and the present result might not be the exact result that the user intended. (This is how OS X's Spotlight Search palette works, the latter asynchronous form).

**Comment by lee-dohm** [comment]
In order to make this improvement, the fuzzaldrin and fuzzaldrin-plus modules would need to be updated to support being called asynchronously. Then all packages that depend on those modules would need to be updated to call them asynchronously. Please open Issues on [fuzzaldrin](https://github.com/atom/fuzzaldrin) and [fuzzaldrin-plus](https://github.com/jeancroy/fuzzaldrin-plus) to start this process.

**Comment by trusktr** [comment]
Opened https://github.com/atom/fuzzaldrin/issues/29

**Comment by jeancroy** [comment]
Also opened https://github.com/jeancroy/fuzzaldrin-plus/issues/19
