### ISSUE TITLE
Implement clear for TextEditor in mini mode

### ISSUE THREAD

**Issue by bastilian** [atom/atom#12048]
It would be useful to implement a "clear" function on TextEditor when mini is enabled, that is optional and would allow to easily clear a field with a click as well as provide an event that is fired when the fields value becomes an empty string.

Visually it can look something like this and is only visible when the field has focus: 
![clear_field](https://cloud.githubusercontent.com/assets/7757/16361433/61a15ed0-3b91-11e6-965b-e044f6cf695f.png)

If this would be an acceptable feature I would start implementing it to introduce it into [atom/settings-view](/atom/settings-view) to clear package searches.

**Comment by 50Wliu** [comment]
I like it :+1:.

**Comment by Ben3eeE** [comment]
/cc: @simurai Do you have any thoughts about reopening/triaging this issue? Is it something we should add?

**Comment by simurai** [comment]
> Is it something we should add?

I wouldn't be against it. But not sure how often I would use the x button. Since my hands are on the keyboard, I would have to switch to the mouse, click the x and then move back to the keyboard.

A common pattern is to add the x, but then also be able to clear the input with `esc`. Get's tricky because we Atom uses `esc` to close panels, modals. 🤔
