### ISSUE TITLE
some suggesstion and bugs

### ISSUE THREAD

**Issue by QiiSyhx** [atom/atom#12058]
ctrl+r, find function and variables,if find,shuld be slide to top this function or variables. if a variables find too much, should be filter or show backend,likes id.
if a variable or a string has selected,the same  variable or string should be highlight,like sublime text.
atom will append a new line in file when save. i think it should be optional.

i had disabled all plugin i had installed, and use the default theme. the html syntax highlight seems wrong.
![qq 20160628115331](https://cloud.githubusercontent.com/assets/2001704/16403446/c7539c4c-3d27-11e6-8bac-349b23365031.png)
![qq 20160628115402](https://cloud.githubusercontent.com/assets/2001704/16403447/c753dd10-3d27-11e6-9937-ffb6417ee351.png)
![qq 20160628115504](https://cloud.githubusercontent.com/assets/2001704/16403448/c7547aa4-3d27-11e6-8d9f-2ed5df38dd00.png)

**Comment by lee-dohm** [comment]
Thanks very much for the feedback. The syntax highlighting problem you're mentioning is due to the fact that Atom gives up highlighting after 100 tokens on a single line. It does this for performance reasons.

If you want to give feedback on the [symbols-view package](https://github.com/atom/symbols-view), please file an Issue there.
