### ISSUE TITLE
 Incorrect file association when I run specs

### ISSUE THREAD

**Issue by DoranYun** [atom/atom#12107]
I'm write a atom package specs.I want to open a file in  `specs/` folder, so I use `atom.workspace.open('./test.we')`, but I can not get anything.so I'm print the path  `/Applications/Atom.app/Contents/Resources/app.asar/spec/test.we` , but the real path is 
'~/.atom/packages/we-beautify/spec/test.we'

When I use absolute path， this's right, so I can not use relative path in specs file?

Atom version 1.8.0

```
'use babel';

import MyPackage from '../lib/my-package';

// Use the command `window:run-package-specs` (cmd-alt-ctrl-p) to run specs.
//
// To run a specific `it` or `describe` block add an `f` to the front (e.g. `fit`
// or `fdescribe`). Remove the `f` to unfocus the block.

describe('MyPackage', () => {
  let workspaceElement, activationPromise;
  let editor;

  beforeEach(() => {
    workspaceElement = atom.views.getView(atom.workspace);
    activationPromise = atom.workspace.open('../spec/test.we');
  });

  describe('when the my-package:beautify event is triggered', () => {
    it('can format the whole text this editor', () => {
      // Before the activation event the view is not on the DOM, and no panel
      // has been created

      // This is an activation event, triggering it will cause the package to be
      // activated.

      waitsForPromise(() => {
        return activationPromise.then(edit => editor=edit);
      });

      runs(() => {
        let text = atom.workspace.getActiveTextEditor().getText();

        console.log(atom.workspace.getActiveTextEditor().getPath());
        console.log(editor.getPath());

        atom.commands.dispatch(workspaceElement, 'my-package:beautify');

        expect(editor.getText()).not.toBe(text);
      });
    });
  });
});

```

**Comment by DoranYun** [comment]
when I use 

```
activationPromise = atom.workspace.open('/Users/YunDong/.atom/packages/my-package/spec/test.we');
```

it's success

**Comment by thomasjo** [comment]
How are you running the specs?

**Comment by DoranYun** [comment]
@thomasjo `apm test`  or   `view->developer->run package specs `

**Comment by thomasjo** [comment]
OK, then I'm pretty sure the problem is that the CWD (current working directory) is being used indirectly in `Workspace::open` instead of being "rooted" in the project (or the current file as you seem to be expecting). There is no way for `Workspace::open` to behave correctly when using relative paths when there are more than project part of the current workspace. I'm assuming that is one of my main reasons for the current behavior and it will likely never change.

Regardless, using unresolved relative paths in code such as this is typically a bad idea since it is rather fragile, as you have just experienced first hand. Instead what you should do is to either use the `fs` module to resolve the paths, or you can exploit the fact that specs are being run in a separate workspace and project, so you can do e.g 
~~~ js
const somePath = atom.project.resolvePath('../spec/test.we');
activationPromise = atom.workspace.open(somePath);
~~~

**Comment by DoranYun** [comment]
@thomasjo yeah, I use the fs module to resolve the path , it's success! Thanks!
