### ISSUE TITLE
Remove uses of nodegit

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#12159]
We're seeing crashes in Atom stable. We believe that the crashes are caused by nodegit (introduced in https://github.com/atom/atom/pull/9213). So for now, we're going to back out all of our usage of nodegit in core and bundled packages:

* [x] git-diff (https://github.com/atom/git-diff/pull/105)
* [x] fuzzy-finder (https://github.com/atom/fuzzy-finder/pull/236)
* [x] open-on-github (https://github.com/atom/open-on-github/pull/75)
* [x] status-bar (https://github.com/atom/status-bar/pull/155)

Refs https://github.com/atom/atom/issues/12153

**Comment by lee-dohm** [comment]
I suspect https://github.com/atom/atom/issues/11358 is related to this also.

**Comment by subesokun** [comment]
@maxbrunsfeld @lee-dohm Does this mean that the new async Git API will be removed for the time being and it's unclear if it will be shipped again in Atom 1.10?

This causes quite some troubles for me as I've already completely migrated the [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package onto the new async API as the old sync API didn't work any longer. It was really a big effort to migrate to the async API and now I've to undo everything again? ... just wondering why such breaking changes are not causing a major version bump of Atom ...

**Comment by lgeiger** [comment]
@maxbrunsfeld @lee-dohm @smashwilson I there a way we could revisit this issue?

Opening a git repository over a the network (e.g. via a SSHFS mounted network drive) can take multiple seconds. Due to the synchronous `git-utils` API this may completely block Atom which makes accessing git repositories over Wifi completely unusable.

Here is a CPU profile that illustrates this issue when adding a remote git repository to the tree view:
[git-repo.zip](https://github.com/atom/atom/files/1489468/git-repo.cpuprofile.zip)

I'm happy to help with this problem and provide more information if needed.

**Comment by maxbrunsfeld** [comment]
@lgeiger Yeah, this is a really big known problem, and I think it needs to be a fairly high priority for us. We definitely want to remove all uses of synchronous `git-utils` calls. I don't think that necessarily means we're going to use `nodegit` again (although that is an option). We've already replaced some of the synchronous APIs in `git-utils` with async ones: see https://github.com/atom/git-utils/pull/80, and that has been fairly painless. I don't know the status of `nodegit` since we attempted to use it in Atom (and experienced intermittent crashes) last year.

It's great to hear that you're interested in helping. There are three main components to this effort:
1. Implement async versions of all of our `GitRepository` APIs. I can see two ways of doing this:
  a. Add async variants of these methods to `git-utils`, similar to what I did in https://github.com/atom/git-utils/pull/80.
  b. Implement these methods using `nodegit`, and verify with very high confidence that `nodegit` won't cause the app to crash anymore.
2. Update all of our bundled packages to use the new APIs.
3. Deprecate the old synchronous APIs.

Do you have thoughts on this? Would you like to help do some of this work?

**Comment by lgeiger** [comment]
Thanks for the detailed explanation!
Sorry for not getting back to you earlier.

I didn't find time to try one of the above options but for now I made some CPU profiles to help illustrate the problem. All of the profiles where taken using a network mounted folder via `sshfs` while on a stable wireless internet connection.

### Adding git repo to project and open file
<img width="1552" alt="add_project_and_open" src="https://user-images.githubusercontent.com/13285808/34575547-804d5a7c-f17b-11e7-920e-34e12fa961ae.png">

### Open file from already loaded git repo
<img width="1552" alt="open_file_from_loaded_project" src="https://user-images.githubusercontent.com/13285808/34575553-85fae462-f17b-11e7-93f3-994b618dda6b.png">

Here is the full profile: [sshfs_load.zip](https://github.com/atom/atom/files/1604109/sshfs_load.zip)

Have you though about making use of the [github package](https://github.com/atom/github) to get the diff and status of the repo?
It shells out via [`dugite`](https://github.com/desktop/dugite) instead of relying on `git-utils`/`libgit2`. Apart from that it would remove the need to maintain two different git tools bundled inside Atom.
