### ISSUE TITLE
Atom UI elements with selectable text don't respect system default copy/paste keys

### ISSUE THREAD

**Issue by petetnt** [atom/atom#12193]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Some UI elements with text in Atom can be selected/highlighted and then copy pasted. Some examples of this are some of the texts in the Settings-menu and errors messages on Linter panels.
The usually use-case for me is taking an error message spat out by the linter (or other checker) from a panel and Googling it.  On MacOS, unlike on Windows, the default copy-paste combinations are `cmd`-based, `cmd-c`, `cmd-v` (while the Windows ones are `ctrl-c, ctrl-v`). However, the only way to copy selected text from Atom UI is through the `ctrl`-key, despite `cmd` being the preferred key on MacOS.

### Steps to Reproduce

0. On MacOS X...
1. Open Settings
2. Highlight some text
3. Copy the text with `cmd-c` and paste it
4. Copy the text with `ctrl-c` and paste it

**Expected behavior:**

Clipboard contains the copied text during step 3, nothing is copied during step 4.

**Actual behavior:** 

Nothing is copied to clipboard during step 3, text is copied during step 4.

### Versions

MacOS X El Capitan (10.11.6)
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.2

Quite a minor issue, but still an annoyance. 🐈

**Comment by simurai** [comment]
I can't reproduce the `ctrl-c` (5th step), but selecting text and copying, for example the intro text in the Core settings, doesn't work.

<img width="399" alt="screen shot 2016-07-23 at 3 22 49 pm" src="https://cloud.githubusercontent.com/assets/378023/17076261/681963a8-50e9-11e6-9ed5-809966969d57.png">

For those places, I guess we have two options:

1. Disable the text selection, so that copying text isn't expected.
2. Enable copying by adding the `.native-key-bindings` class to those elements (or some parent element).

Any specific place you'd like to copy the text? For linter, it seems they opted to use a "copy to clipboard" button: https://github.com/steelbrain/linter-ui-default/issues/78

**Comment by petetnt** [comment]
Weird, I cannot replicate it in the Core settings anymore either 🤔

My primary use case is the linter-panel (not the linter pop-ups, but I don't see the "Copy to clipboard"-icon either and there's no option to enable it as far as I can see). `.native-key-bindings` class would work, I guess I'll take that suggestion it to the linter repo 👍 

Thanks @simurai, closing this one.
