### ISSUE TITLE
Uncaught TypeError: item.save is not a function

### ISSUE THREAD

**Issue by Sirpyerre** [atom/atom#12209]
1. I Closed a tab: a document without title.
2. I have a init script:

```
atom.getCurrentWindow().on 'blur', ->
  for pane in atom.workspace.getPanes()
    for item in pane.items
      if item.isModified?
        item.save() if item.isModified()
      else
        item.save()

```

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: item.save is not a function

```
At /home/peter/.atom/init.coffee:18

TypeError: item.save is not a function
    at /home/peter/.atom/init.coffee:18:14
    at /home/peter/.atom/init.coffee:14:5
    at CallbacksRegistry.apply (/usr/share/atom/resources/atom.asar/common/api/lib/callbacks-registry.js:58:39)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:236:28)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.9
emmet, v2.4.3
php-analyser, v0.2.0
php-integrator-base, v1.0.7
php-integrator-linter, v1.0.1

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Your init script makes the assumption that all open pane items will implement the `save` method, but only `TextEditor` pane items will out of the box. If you had any UI tabs open, like Settings, or About, or Find results, then this would throw an error.

Since this is an issue with your init script and not with Atom, I'm going to close this out.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
