### ISSUE TITLE
Globally store node_modules for packages

### ISSUE THREAD

**Issue by BladeMight** [atom/atom#12225]
Can you make atom to somehow store globally all needed node_modules(dependencies) for packages, so they can be installed just once for all packages instead of having much of them, for every packages taking some space on disk if much packages installed.
\- _BladeMight_

**Comment by 50Wliu** [comment]
This is a built-in feature of npm v3.  See #11897 for the progress of integrating that into Atom.

**Comment by Arcanemagus** [comment]
@50Wliu I thought the general package structure was staying the same with this move, the only difference being `npm@3` is used to install _within the package folder_. I'm interpreting this to mean a _global_ `node_modules` for all the packages, not individual ones for each package.

As for the request itself, it would be great for space saving, but can cause major issues with support, such as how would a package be uninstalled cleanly?

**Comment by 50Wliu** [comment]
Yeah, if that's what @BladeMight is asking for, that doesn't sound realistically possible due to differing dependency versions, uninstallation problems, etc. etc.

**Comment by BladeMight** [comment]
@50Wliu yes that is it. Why not? If any package uses this node_module with this version then leave it, else delete. I think this way would be a lot cleaner, and faster due to usage **same** scripts, **not new**.

**Comment by Arcanemagus** [comment]
@BladeMight how do you propose implementing that?

* Atom packages aren't NPM packages, so you can't just list them in a global `package.json` without rewriting quite a bit of what NPM does
* A corrupted update of one package can destroy another package, for example if Atom crashes while updating a shared dependency (unlikely, but _possible_)
* An update to a different package may break an installed package, since the newer one updates a shared dependency to a newer version that may not work perfectly with the existing one (not everyone follows semver correctly...)

A few of those are _solvable_ yes, but they require a large amount of work for extremely little benefit.

**Comment by BladeMight** [comment]
I propose:
1.To parse each new installed package's _packages.json_ for finding dependencies and check if they are installed, or install them into specific global dir, with /module_name-version/ pattern, so the needed versions of modules for specific packages will not be deleted, due to _packages.json_ dependencies parse.
2.Make references to package in global dir.
3.Parse all package's _packages.json_ on Update/Delete/Modify to get to know what still needed, what not.
So what do you say?

**Comment by tomachinz** [comment]
@BladeMight I think Arcanemagus means the effort required costs more than the disk space used, and I would tend to agree with him. It's probably to better to have compatibility and reliability higher priority than efficient use of disk with shared libs.

**Comment by BladeMight** [comment]
So that isn't possible anyway...
