### ISSUE TITLE
when opening a file with a line number, atom should scroll down to display that line number at the top of the view

### ISSUE THREAD

**Issue by niahmiah** [atom/atom#12253]
### Description

When opening atom from the command line, to a specific file and line number, atom does not scroll the content in the most desirable manner...
### Steps to Reproduce
1. atom text/someFile.txt:115

**Expected behavior:** I expect Atom to scroll so that line number 115 is at the top of my editor

**Actual behavior:** Atom scrolls to the line number, but only far enough for it to be presented at the bottom of the screen. Furthermore, plugins like JSHint that are displayed at the bottom will cover the desired line number. Therefore, the user still has to scroll the content to view the line number, defeating the entire purpose of this feature.
### Versions

$ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by mnquintana** [comment]
I think this is a regression – this (and most other actions that are supposed to scroll a line into view) is supposed to vertically center that line.

**Comment by martindale** [comment]
Any updates on this?

**Comment by martindale** [comment]
One year later, asking for updates again!

**Comment by martindale** [comment]
Another year, another hopeful request...

**Comment by jasonrudolph** [comment]
> I think this is a regression – this (and most other actions that are supposed to scroll a line into view) is supposed to vertically center that line.

Thanks for this clarification, @mnquintana.

#19272 restores the previous behavior. With the changes in #19272, when opening a file at a specific line, Atom will now:

- Attempt to scroll the editor as needed so that the specified line is centered vertically
- If the file is already open and the requested line is hidden by a fold, unfold so that the line is visible

This change is slated for inclusion in the Atom 1.38.
