### ISSUE TITLE
overriding keymap.cson (up and down keystrokes) causes keystrokes to be cached

### ISSUE THREAD

**Issue by jasonmamy** [atom/atom#12266]
### Description
Overriding basic keys, causes the keystroke that was overridden needing to be pressed twice, which in turns seems to 'cache' the previous keystroke.

### Steps to Reproduce

1. override ~/.atom/keymap.cson with contents:

'body':
  'ctrl-i': 'core:move-up'
  'ctrl-k': 'core:move-down'

2. Restart editor
using ctrl-i and ctrl-k to move cursor results in a 'delay' of one keystroke upon first time using that keystroke.  So ctrl-i then pressing 'end' key would result it this situation:

Initial:
`line 1`
`line <cursor is here> 2`
`line 3`

First keystroke:
`line 1`
`line <press ctrl-i here> 2`
`line 3`

Result (cursor moves up a line as expected):
`line <cursor moves here as expected> 1`
`line 2`
`line 3`

Second keystroke:
`line <now press ctrl+k here> 1`
`line 2`
`line 3`

Expect:
`line <cursor is still here> 1`
`line <expect cursor to be here> 2`
`line 3`

Third keystroke (the 'cached' keystroke)
`line <press end key> 1`
`line 2`
`line 3`

Result:
`line <press end key> 1`
`line 2 <cursor is now at end of line2>`
`line 3`

I've tried using different keystrokes but they all seem to have the same issue.

I'm running Linux:

Linux jasona-desktop 3.16.0-30-generic #40-Ubuntu SMP Mon Jan 12 22:06:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

And atom (in --safe mode):

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by Ben3eeE** [comment]
This seems specific to <kbd>ctrl+k</kbd> any other combination works fine. Maybe it is a matter of how you write the keybinding for <kbd>ctrl+k</kbd> in keymap.cson since it has some magic partial stuff?

![ctrl-k](https://cloud.githubusercontent.com/assets/1058982/18123122/c0eb616a-6f6c-11e6-8910-107f68bbf8a4.PNG)

**Comment by lee-dohm** [comment]
Because <kbd>Ctrl+K</kbd> on Windows and Linux and <kbd>Cmd+K</kbd> on macOS is used as the root of several compound keybindings (such as [opening new panes](http://flight-manual.atom.io/using-atom/sections/panes/)), that delay is in place to determine the difference between <kbd>Ctrl+K</kbd> and <kbd>Ctrl+K</kbd> plus something else. If you want to not experience that delay with <kbd>Ctrl+K</kbd> you will have to unbind all of the keybindings that start with <kbd>Ctrl+K</kbd> in your `keymap.cson`. See the [Atom Flight Manual for details](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#removing-bindings).

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
