### ISSUE TITLE
[1.9.0] Problem with highlighting RTL language text 

### ISSUE THREAD

**Issue by morajabi** [atom/atom#12282]
### Description

After upgrading to the new version (from 1.8 to 1.9) I can't correctly select Persian text and it won't highlight it.
I use Operator Mono font but i tried Monaco with no luck.
### Steps to Reproduce
1. Type some Persian/ Arabic text
2. try to select it! (by double click or regular selecting)
3. You can't!

**Expected behavior:** Should be highlighted as En text

https://i.imgsafe.org/05a5625be9.png
![EN text selecting](https://i.imgsafe.org/05a5625be9.png)

https://i.imgsafe.org/05a55ccc06.png
![bad FA/ARABIC text selection in 1.9 version](https://i.imgsafe.org/05a55ccc06.png)

**Actual behavior:** But it highlights only 1 character.
### Versions

atom 1.9.0
OSX El Captian 10.11.5

**Comment by morajabi** [comment]
Any news? It's a terrible bug for those who write Right-to-Left in atom, please take look ASAP.

**Comment by 50Wliu** [comment]
@nathansobo @as-cii

**Comment by as-cii** [comment]
Hi @morajabi, apologies for this rendering bug but unfortunately we don't officially support RTL characters for now. This is due to the text-selection routine that we currently employ which assumes glyphs have a left-to-right layout and, therefore, doesn't work properly when dealing with text that is rendered in the inverse direction. We plan to do so in the future and provide better overall internationalization support in Atom. In the meantime I'll share this with the team too. 👍 

Thanks for the report! 🙇

**Comment by morajabi** [comment]
Don't atom team want to do something with this soon? I'm sure so many people leaving Sublime Text and joining Atom community just for bad support for RTL in ST, same as all of my friends.

**Comment by Ojvar** [comment]
I have same problem
Please correct this problem

**Comment by 50Wliu** [comment]
I believe @farnabaz is working on this, and we've already merged a related PR: #13194.

**Comment by Ojvar** [comment]
thank you

**Comment by iraniamir** [comment]
Bracket is cool with RTL languages !

**Comment by salehmosleh** [comment]
I have same problem :-(

**Comment by amzaf** [comment]
Why you guys build something on the assumption that you'll never ever encounter RTL and now you have an ecosystem built around something that is too risky or too late to fix.

**Comment by farnabaz** [comment]
Hi
Is there any way that we can create a global grammar in atom, in order to wrap all RTL chars inside a node?
Atom uses binary search to find cursor position in screen, If we can wrap RTL chars in  a `TextNode` we can create another RTL binary search and find correct position of cursor in RTL text

@as-cii @50Wliu @nathansobo

**Comment by nathansobo** [comment]
@farnabaz I don't have enough context to really answer to your question. We will get to this someday, but right now we just don't have the bandwidth to take it on. If you or another community member is interested in doing some deep research around what it would take to accomplish this, that would be helpful. I'm worried that it goes beyond just measurement issues at the DOM level.

**Comment by saeedhei** [comment]
I want to Make a Rtl Telegram Bot With Many Keyboards,  I have highlight problem too. Vscode is okey but why atom isn't?

**Comment by Superpencil** [comment]
@as-cii In case you don't have internal statistics regarding rtl usage in atom; a little over 1.5 billion people use rtl languages, or about 20% of the world population

I imagine this happened due to your new C++ editor for bigger files?

I too can attest to personal experiences of long-time sublime users moving to atom for its rtl support.

**Comment by hakamaq** [comment]
Still having this problem please find a fix

**Comment by morajabi** [comment]
Use VSCode!

**Comment by morajabi** [comment]
@hakamaq If it's really bothering you, you can check out VS Code editor, I think the RTL situation there is better.

**Comment by hakamaq** [comment]
I am actually using VSCode however I love everything Atom offers that I think It should be implemented on it

**Comment by fariszaher** [comment]
Quite ridiculous that this isn't prioritised. Any estimate for when it gets selected?

**Comment by morajabi** [comment]
@fariszaher The maintainers who work on the project, have the control to prioritise what's most important based on user needs. If it's very important for you, you can always start working on it if you prefer! 👍

**Comment by lajmikhalil** [comment]
I'm still encountering this issue. 

Atom V. 1.41.0
macOs 10.14.6

You can simply reproduce the issue while selecting syntax on any file containing both RTL and RTL languages. This is most common within .json translated content files. More and more apps are being localized to RTL and I'm seeing teams switch editor cause of this.
