### ISSUE TITLE
Parts of window dont render / appear black

### ISSUE THREAD

**Issue by OnkelDittmeyer** [atom/atom#12319]
Hey,
im working on a rather small js document and parts of the entire window dont render/appear black until i either scroll, refresh this part or move the mouse cursor over the area.

Working on Atom 1.9.2 on OSX 10.9.5. Safe mode shows the same issue, other files/file types as well.

Screenshot attached.

Thanks!
M
![screen shot 2016-08-04 at 11 41 02](https://cloud.githubusercontent.com/assets/5214267/17388868/f887d0ce-5a39-11e6-9256-33310035bd0a.png)

**Comment by ricardograca** [comment]
I had this issue as well recently, but it seemed to be related to overheating since my PC was doing some heavy CPU work as well when the black bars appeared. Not sure if it's a driver issue or Atom issue.

As soon as the CPU load decreased and I reloaded Atom there were no more black bars.

Also on OSX 10.9.5.
