### ISSUE TITLE
macOS: When Atom window is closed and re-opened, the app completely rerenders

### ISSUE THREAD

**Issue by FezVrasta** [atom/atom#12497]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Everytime the Atom window is opened, it re-renders the whole UI. This is in contrast with the behavior of all the other macOS applications.  
Usually when you close an application with the red button and then you re-open it from Dock, the UI is instantly available exactly as you left it when the window was closed.
Seems like there are two different problems:
1. The UI completely re-renders on window open
2. The window state is not preserved when the window is re-opened

Logically I have not checked "Open empty editor on start".
### Steps to Reproduce
1. Open an Atom's window
2. Open a project, a file, a tab, whatever
3. Close the opened Atom's window using the red button
4. Click on the Atom icon in the Dock to re-open the window

**Expected behavior:** The window is instantly re-opened and I can continue from where I left.

**Actual behavior:** The window is created from scratch, takes several seconds to render its content, and once rendered, I have to reopen the tab/project I was using before I closed it.
### Versions

```
~$ atom --version
Atom    : 1.11.0-dev-579e6b2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
~$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.2
```

The same problem happens with all the Atom versions

**Comment by abarisain** [comment]
I'm sorry, but I fail to see how that is expected behaviour from macOS.

>Usually when you close an application with the red button and then you re-open it from Dock, the UI is instantly available exactly as you left it when the window was closed.

Not at all. Many single window/non document-based apps (such as slack, spotify) do that, but standard Apple apps (and 3rd party) don't.
Atom is document based, as many windows can be opened with different content.

Examples:
 - Open a safari window, and some tabs. Close it with the red button. Click on the safari icon. You get a new window, with your tab closed. Only the pinned tabs stay. Chrome works almost the same.
- Open pages on a document saved on your drive. Close the window, open it using the doc, your document isn't loaded.
 - Sublime Text does the same

Non document apple apps work the way you describe though:
 - iTunes
 - Messages
 - Calendar

The only times document based window apps restore their windows, is if it is enabled in your macOS settings, and you quit the app (Cmd Q) rather than closing the windows. In document based apps, the red button means you want to close the specific document window, not hide it.

**Comment by FezVrasta** [comment]
@abarisain yours are good points, but the only official Apple IDE (Xcode) re-opens the document when you re-open the app.

Also, in Atom I have not checked "Open empty editor on start" and the `autosave session` plugin is enabled, so I would expect Atom to re-open my last session.

**Comment by nesk** [comment]
Atom is not an IDE, it is closer to TextEdit (file editing) than Xcode (file editing, simulating, debugging, testing, etc…). And TextEdit is document based, thus I expect Atom to work like TextEdit.

**Comment by abarisain** [comment]
@FezVrasta  When re-opening, sure. Atom does that for me too. (Talking about Cmd-Q)

But, if I click on Xcode's doc icon after closing the last project window (using the red button), it will show me the welcome screen, which allows me to pick a project.

**Comment by abarisain** [comment]
Then you've got another issue that the one described here, which is why we got confued

My only argument was that atom should not restore the workspace once you close the last window using the red button, rather than quitting it with Cmd-Q.

I agree about the rendering time, but it allows the editor to free the ram used by an open editor window. It's a huge downside of electron, the first display time of a window is pretty slow.

**Comment by yuanwhy** [comment]
I fixed the bug https://github.com/atom/atom/pull/12486,
@50Wliu could you review this code when you get a chance? I tested it on macOS and  everything seemed ok.

**Comment by abarisain** [comment]
Does this patch makes it so when you close atom's last window (but not the app!), clicking the dock icon opens the last closed window, or will it open an empty editor?

**Comment by yuanwhy** [comment]
@abarisain  it will open the last closed window !

**Comment by abarisain** [comment]
Sorry, I edited my comment higher up before you answered.

I don't understand why that is the expected behaviour, as it is totally opposed to what other OSX apps do (sublime, Xcode, etc...)

**Comment by abarisain** [comment]
Checking "Open Empty Editor On Start" will make it so atom always opens an empty editor, disregarding last state.

Unchecking it makes it behave like a normal osx app.

**Comment by FezVrasta** [comment]
About the `CMD Q` I confirm that it doesn't restore the state once Atom is started over.

**Comment by abarisain** [comment]
That's another issue, I think. "Open Empty Editor On Start" seems to be totally bugger. Whatever its state is, it shouldn't stop Atom's status to be restored when the app is quitted with opened windows.

I was merely expressing my disagreement that #12486 fixes this issue, as it introduces (to my eyes) an unwanted behaviour :)

**Comment by Seth10001** [comment]
I'm having this same problem. I've tried the latest beta and it's still an issue.
