### ISSUE TITLE
newly installed Atom 1.9.9 in Ubuntu 16.04 (unity) - *poor* font rendering

### ISSUE THREAD

**Issue by Dowwie** [atom/atom#12507]
I've used Atom editor for a long while.  I just installed an Ubuntu 16.04 instance and with it the newest version of Atom, 1.9.9.  The fonts aren't rendering in the Atom editor as they used to, in prior versions.  I've tried a range of different fonts using the fonts package.  I've tried to tweak my stylesheet yet still no improvement:

.editor {
  -webkit-font-smoothing: antialiased;
}

This is what my editor looks like, using the Iosevka font:  http://imgur.com/a/NXhKq

Please, help.  This font rendering problem is a show-stopper for me as it is affecting focus.
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

[Description of the bug or feature]
### Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Menci** [comment]
The font is nice, isn't it?

**Comment by Dowwie** [comment]
@Menci the font is nice but it's not "smooth" because the rendering seems off

**Comment by damieng** [comment]
Can you be more specific?

**Comment by ndavidow** [comment]
Atom 1.10.2
Ubuntu 16.04

I have a possibly related issue, the example given is a proportional font but the same effect happens with any monospace font I tried (albeit slightly less conspicuous)

![rendering](https://cloud.githubusercontent.com/assets/7731545/18457314/af86f034-7925-11e6-86d6-cc326564f41f.png)

Atom/Chromium appears to have subpixel positioning/spacing. This can be advantageous to fixed layouts but is almost universally disabled for text editors, because it makes small font rendering look "bad"; characters are rendered inconsistently as shown. Note that the system has subpixel antialiasing, this is fine, but the character width is fixed to an exact whole pixel integer, so it renders consistently across the run.

Here's a paper if you are unfamiliar with text rendering, [http://goo.gl/yf3M7](http://goo.gl/yf3M7)

The paper is written by Behdad Esfahbod, who works on open source font rendering and contributed to a good portion of the Chromium text rendering system. He could potentially provide input, [behdad@chromium.org](mailto://behdad@chromium.org)

**Comment by damieng** [comment]
Hi there.  We are aware of sub-pixel positioning and the problems it causes.  We are however also at the mercy of Chromium which has made this change and does not expose many options to tweak the appearance. We will continue to investigate.

**Comment by 50Wliu** [comment]
I believe this should be fixed in Atom 1.20 and above.
