### ISSUE TITLE
Graphical glitch after window snapping.

### ISSUE THREAD

**Issue by ghost** [atom/atom#12531]
First of all, thanks for great work with the editor. It is getting better and better with every release.

I noticed a small graphical glitch that I don't know how to fix. In every Linux distribution I tried, whenever I snap Atom to either left or right side of the screen (Ubuntu or Gnome window snap) a white line appears on the right side of the window (always right no matter which side of the screen I snap it to). The window looks fine when it is not snapped and it is theme independent.

Small thing but would be great if it could be addressed.
![screenshot from 2016-08-27 02-20-54](https://cloud.githubusercontent.com/assets/18163728/18014372/9dd28770-6bfd-11e6-8f27-cb9c2c837ef5.png)

![screenshot from 2016-08-27 02-21-17](https://cloud.githubusercontent.com/assets/18163728/18014379/a9b770d2-6bfd-11e6-9524-b31b99973c21.png)

Many thanks!

**Comment by 50Wliu** [comment]
Some questions:
1. What Atom version are you using, and where did you install it from?
2. What Linux distros have you tried this on?
3. How long has this been happening?
4. Is the issue still reproducible in safe mode (`atom --safe`)?

In the future, please *completely* fill out the provided issue template so that we can better assist you.  Thanks!

**Comment by JLCCI** [comment]
Apologies for not providing the details.

1. I used Atom versions between 1.7 and 1.9. I have it on couple of machines so installed either through PPA or Pacman.
2. Arch Linux (with newest Gnome) and Ubuntu 16.04.
3. It has always been there since the first install.
4. Yes, its still there.

Additional two information - I have just noticed (it's easier to see with safe mode) that the white line appears both on the right and bottom side of the window. It is difficult to take a snapshot to show it. Secondly, I have a 4K screen and use scaling. Not sure if this matters.

Thanks for looking into this!

**Comment by Ben3eeE** [comment]
> so installed either through PPA or Pacman

Are you perhaps running Atom with a newer version of Electron? Please provide the output of `atom --version` and `apm --version`

**Comment by JLCCI** [comment]
In Ubuntu:
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.7.4

In Arch:
Atom    : 1.8.0
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1
apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.2
git 2.9.3 

Both have the white line at the right side though only arch has the line at the bottom side of the window.

**Comment by 50Wliu** [comment]
Thanks for the extra info!  If you upgrade the Atom version on Arch to 1.9.9, does the bottom line disappear?

**Comment by JLCCI** [comment]
Made a fresh install on Arch which updated all the packages. The line is still visible both on the right and bottom side of the window - perhaps it's an Gnome vs Ubuntu GUI thing with the bottom line.
Atom    : 1.9.9
Electron: 1.3.4
Chrome  : 52.0.2743.82
Node    : 6.3.0
apm  1.12.6
npm  3.10.6
node 6.5.0
python 3.5.2
git 2.9.3

**Comment by JLCCI** [comment]
FYI changing theme in Gnome does not get rid of the issue. Happy to provide more info.

**Comment by 50Wliu** [comment]
If you disable GPU rendering through `atom --disable-gpu`, does that help?

**Comment by JLCCI** [comment]
Unfortunately not. Has anyone else with Ubuntu 16.04 seeing this?

**Comment by equinusocio** [comment]
I have some visual glitches too, on MacOS Sierra with electron 1.10. Running `atom --disable-gpu` fix the problem. The question is.. why?

The problem
![Uploading Screen Shot 2016-09-19 at 15.06.40.png…]()

**Comment by 50Wliu** [comment]
@equinusocio You have a different issue: #12634.
