### ISSUE TITLE
auto new line

### ISSUE THREAD

**Issue by krishnaTORQUE** [atom/atom#12602]
when saving files, its automatic adding new line.

**Comment by DeanmvSG** [comment]
Settings -> Packages -> Whitespace -> turn off "Ensure Trailing Newline"

**Comment by krishnaTORQUE** [comment]
thank you so much :+1:

**Comment by thomasjo** [comment]
Closing this since this has been resolved (and is also a duplicate of numerous closed issues).

For future reference, consider searching the FAQ category on Discuss. It specifically answers this issue:
https://discuss.atom.io/t/why-is-atom-deleting-trailing-whitespace-why-is-there-a-newline-at-the-end-of-the-file-why-are-there-all-these-changes-in-the-file-diff/19189
