### ISSUE TITLE
how can i connect my github account in atom

### ISSUE THREAD

**Issue by Kongdy** [atom/atom#12644]
### Description

as the title say.
how can i set my github account in atom that i can commit my project easily.

### Steps to Reproduce

1. Open a atom on my PC with windows.
2. import a project
3. i can't find out the options that it can connect on my github account when i want to commit my project into github.

**Expected behavior:** i can commit my project and use it happily.

**Actual behavior:** i can't find out where i can set my git server path.

### Versions

Atom    : 1.10.2

**Comment by lee-dohm** [comment]
Atom doesn't have the feature you're asking for built-in. There is no way to connect Atom to your GitHub account directly. You have to use [Git](https://help.github.com/articles/creating-a-new-repository/) or an application like [GitHub Desktop](https://desktop.github.com/) to connect to GitHub and import your new project. Once that is done, you can use Atom to interact with the local copy of your repository.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

I hope that helps!

**Comment by Kongdy** [comment]
Thank you very much every day! in the morning! on the tree!

**Comment by RyenRerbertson** [comment]
so my question is is how do I login on atom? I keep getting an error (will need to censor some of the code due to my privacy on pc)

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got '*censored*@DESKTOP-*censored to be safe*.(none)')

**Comment by ghonchesefidi** [comment]
I have same issue like @RyenRerbertson

**Comment by Georjay** [comment]
@RyenRerbertson in order to commit in Git, you will need to set a username and an email so that Git can tell who is making the commit.
In order to do so, 
1. Download and install Git
2. Open command prompt in your repository where you want to make a commit and type 
**git config --global user.email "type_your_email_here"** and press **Enter**
3. Then type **git config --global user.name "type_your_name_here"** and press **Enter**

**Note: When typing the commands, you can omit "--global" if you don't want the email and username you are providing to be the default for every commit you may make later**

**Comment by ghonchesefidi** [comment]
Thanks for your reply,@Georjay

**Comment by Georjay** [comment]
You are welcome @ghonchesefidi

**Comment by djhepz** [comment]
omfg thank you guru

**Comment by Georjay** [comment]
You are welcome @djhepz
