### ISSUE TITLE
Opening a recent file causes an "item selected is unavailable" error

### ISSUE THREAD

**Issue by pflannery** [atom/atom#12655]
### Description

Trying to open a recent file from the taskbar on windows causes an error.
### Steps to Reproduce
1. Right click on atom icon on the taskbar
2. Click on a recent file to open

![image](https://cloud.githubusercontent.com/assets/1727302/18408474/4c10ef28-7763-11e6-8acc-a89fc69074fc.png)

**Expected behavior:**

Atom should open the file in to the editor

**Actual behavior:** 

Error is shown

![image](https://cloud.githubusercontent.com/assets/1727302/18408473/438519ec-7763-11e6-885e-e4ae6e742801.png)
### Versions

Windows 10 64 bit

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.9.0.windows.1
visual studio 2015

**Comment by damieng** [comment]
You can get this error if you have subsequently deleted or otherwise moved/relocated the file.   If you hover over it the tooltip should show you the full path it is looking for.

**Comment by pflannery** [comment]
@damieng Nope, the file exists and the tooltip points to correct location

**Comment by damieng** [comment]
I suspect this is caused by the fact atom.exe changes path between upgrades.  

In the new version (on master) we rewrite the jumplist on launch to address most of this although pinned ones that are would have no longer been on the main list would still get missed.

The new version of Squirrel is going to stop moving the .exe between upgrades that will solve this problem.
