### ISSUE TITLE
Upgrading packages doesn't recalculate canDeferMainModuleRequire using new code

### ISSUE THREAD

**Issue by matthewwithanm** [atom/atom#12650]
Recently, we (the Nuclide team) got bitten by what seems to be a bug in Atom's package manager when we switched from loading our "sub-packages" during Nuclide's activation phase to its loading phase.

It seems that, if you upgrade a package from within Atom, its new metadata (including the version) will be loaded immediately but `Package::load()` will still load the old version of the package ([because of the require cache][1]). It'll then use that code to determine whether requiring the main module can be deferred and cache that in local storage. The next time Atom's loaded, it uses the (potentially inaccurate) cached value.

We noticed this because our code changed from allowing the deferment of requiring the main module to not, but Atom continued to defer loading.

Related:

* facebook/nuclide#698
* facebook/nuclide#699
* facebook/nuclide#700
* facebook/nuclide#701

[1]: https://github.com/atom/atom/blob/v1.11.0-beta5/src/package.coffee#L441

**Comment by nathansobo** [comment]
Worked with @as-cii this morning on this one, and we concluded that it's basically caused by Node's `require` caching the main module of the package, so when we examined it to populate the cache again we were getting the previous version.

We took this as the opportunity to do something we've been meaning to do for a long time, and just give up on trying to hot-reload packages. You can read more about the rationale in https://github.com/atom/settings-view/pull/851, but updating packages now prompts the user to restart Atom in order to clear out the module cache.
