### ISSUE TITLE
Suggestion: Use webpack to reduce `require` calls

### ISSUE THREAD

**Issue by amilajack** [atom/atom#12693]
Using webpack can significantly reduce the number of require calls during startup time. Are there any plans for it?

**Comment by thomasjo** [comment]
We have no plans to start using webpack in the foreseeable future for a multitude of reasons. One of which is that while it might reduce I/O, it does incur other runtime costs due to everything being shimmed/inlined. 

Since we're trying to control [the deluge of issues](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), I'm closing this issue since we're unlikely to consider this in the foreseaable future, as mentioned above.

Thanks for suggesting this though 🙇

**Comment by amilajack** [comment]
@thomasjo I've just [asked the webpack maintainers](https://github.com/webpack/webpack/issues/2997#issuecomment-247641497) if targeting 'node' will add shims or not. Waiting for a response
