### ISSUE TITLE
Close this issue because it only has a title

### ISSUE THREAD

**Issue by mattdipasquale** [atom/atom#12724]

**Comment by lee-dohm** [comment]
@mattdipasquale Your previous Issues, https://github.com/atom/atom/issues/12680 and https://github.com/atom/atom/issues/12681, [didn't have enough information to be actionable](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html) and was rightfully closed by one of our maintainers for that reason. This Issue appears to be nothing more than an attempt to troll or harass our maintainers and is therefore a violation of our [Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md). Because of this, I'm banning you from participation in the Atom and Electron organizations. If you wish to be reinstated, you may contact me at atom@github.com and we can discuss it.
