### ISSUE TITLE
Bracket matching is hidden by line background-color (due to z-index)

### ISSUE THREAD

**Issue by lukebarton** [atom/atom#12722]
### Description

When a line has a `background-color`, `.highlights .highlight .region`s (specifically bracket-matcher) are not visible because they are `z-index: -1;`

Search results are not affected, because they override to `z-index: 0;`

```
atom-text-editor .find-result .region, atom-text-editor::shadow .find-result .region {
    background-color: transparent;
    border-radius: 3px;
    border: 1px solid #969896;
    box-sizing: border-box;
    z-index: 0;
}
```
### Steps to Reproduce
1. apply `background-color` style to `.cursor-line`
2. Put cursor on `(`, `{` or `[` with matching `]`, `}`, or `)` on the same line

**Expected behavior:**
Should see underline

**Actual behavior:**
No underline visible
### Versions

1.10.2

**Comment by mikol-styra** [comment]
I ran into this issue as well. The root cause is that the cursor line highlight is rendered at a higher z-index than the matching bracket highlight. Well, the fix for that is pretty straightforward: bump the `class="highlights"` container up a notch so that it renders over its `class="lines"` sibling.

However, setting the z-index of the highlights container higher breaks portals like “conflict blocks”. Because conflict block portals (and presumably others) live within the lines container, and the highlights container is z-indexed above it, the portals are insensitive to mouse events (over, click, …). The DOM has put us between a rock and a hard place.
