### ISSUE TITLE
GitHub Desktop for Windows launches old version of Atom

### ISSUE THREAD

**Issue by MattMS** [atom/atom#12778]
When I launch Atom Editor using the "Atom" button in GitHub Desktop, it launches an old version (1.9.9) rather than the currently installed one (1.10.2).
When I launch it any other way (like from Start Menu), then it launches the current version.

Is there a way for me to remove previous versions or update GitHub Desktop to point to the current version?

I could not find the GitHub Desktop repo to post this issue.
I thought it still could apply here because it involves removing old versions of Atom Editor.

### Description

GitHub Desktop launches an old version of Atom

### Steps to Reproduce

(With multiple versions of Atom installed)

1. Open GitHub Desktop
2. Click "Atom" button in top right corner

**Expected behavior:** [What you expected to happen]

Launch current version of Atom installed.

**Actual behavior:** [What actually happened]

Launches old version of Atom (1.9.9) instead of current (1.10.2)

### Versions

- Atom 1.9.9
- Atom 1.10.2
- GitHub Desktop 3.3.0.0
- Windows 10 Home 64 bit

**Comment by Ben3eeE** [comment]
Try this:

1. Completely exit all instances of Atom.
2. Launch Atom 1.10.2.
3. In the `settings-view` open the Systems tab and check all three options.
4. Close Atom and try to reproduce this issue.
5. In the settings-view systems tab check all options as you want.

There was an issue introduced in 1.10 that caused these issues which will be fixed in the next Atom upgrade, I don't know if the issue would affect GitHub Desktop but it is still worth trying.

**Comment by MattMS** [comment]
Works perfectly!

For clarification, I closed all Atom and GitHub Desktop instances, after checking those settings.
Then I launched Atom using the button in GitHub Desktop and it was all good.

Thanks heaps!
