### ISSUE TITLE
implement smooth scrolling speed setting

### ISSUE THREAD

**Issue by alvarolm** [atom/atom#12848]
a general scroll speed setting in the same manner sublime "scroll_speed" (http://docs.sublimetext.info/en/latest/reference/settings.html)  

why ?
the current atom editor has all the proper looks like any other major one, but severely lacks the feeling. Sublime, textmate and others have implemented smooth scrolling which gives an easy to fallow sensation when scrolling thru the code, this is a feature that makes an incredibly difference in terms of comfort and new users adoption.

whats wrong with the current alternatives ?
the css wont work with the new tile rendering system, see https://github.com/atom/atom/issues/5359
"scroll sensitivity" works only when using a mouse or trackpad, besides the "steeps" between every scroll update aren't smooth at all.

I propose an artificial delay in the same way that a linear transition of -webkit-transform would work over the tiles.

rel https://github.com/atom/atom/issues/1666

**Comment by slayerjain** [comment]
I'm new to electron, but have experience in nodejs, wanna try!

**Comment by lee-dohm** [comment]
@alvarolm Please update this Issue with a more detailed explanation of what it is you're requesting. External documentation links can be moved or change. We need to have a more permanent record of what it is you're asking for so that we can a) make a determination as to whether this is something we want to do and b) ensure that if it is something we want to include that we have actually achieved the goals when we make a change.

**Comment by Ben3eeE** [comment]
What is wrong with the current setting that changes scroll speed?

![image](https://cloud.githubusercontent.com/assets/1058982/19068830/7f38bcb8-8a24-11e6-9a09-24957b6fc673.png)

**Comment by alvarolm** [comment]
@lee-dohm  @Ben3eeE updated

**Comment by alvarolm** [comment]
https://www.facebook.com/notes/daniel-colascione/buttery-smooth-emacs/10155313440066102/
