### ISSUE TITLE
On MacOS X "Home" and "End" keys do not work as expected

### ISSUE THREAD

**Issue by r-owen** [atom/atom#12875]
### Description

On MacOS 10.11.6 Atom 1.10.2 (even in safe mode) the "home" and "end" keys on my extended keyboard don't do the right thing. "home" moves to the start of the line and "end" moves to the end of line.

The key resolver shows that this is caused by:

```
"atom-text-editor": {
    "home": "editor:move-to-first-character-of-line",
    "end": "editor:move-to-end-of-screen-line",
    "shift-home": "editor:select-to-first-character-of-line",
    "shift-end": "editor:select-to-end-of-line"
  },
```

in `/Applications/Atom.app/Contents/Resources/app.asar/keymaps/base.json`

Bindings for what appear to be more traditional behavior, e.g. `core:move-to-top` for `home`, are also present in /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/keymaps/e-view.json` but are being overridden by the above.

I realize I can work around this, but it seems to me that the default ought to be fixed.

**Comment by cy4n** [comment]
i guess the Problem is that on windows and linux the home/end keys do jump to start/end of line.
macOS uses cmd+arrows for this (so changing this default behaviour will anger the win/linux users)
with that in mind, you can also use cmd+up/down for start/end of file.

another solution for your Problem would be to remap the home/end keys with an app like karabiner.

**Comment by MoritzKn** [comment]
@cy4n I don't think that special bindings for macOS would be the problem. There are already many platform specific defaults. See: [keymaps/darwin.cson](https://github.com/atom/atom/blob/master/keymaps/darwin.cson).
