### ISSUE TITLE
Several parts of code are missing upon file download from remote FTP server to Atom editors

### ISSUE THREAD

**Issue by FilipeCF** [atom/atom#12899]
### Prerequisites
- [\* ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [ *] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [\* ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [ *] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ *] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [\* ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Sometimes when I open php/html large files last lines of code are missing. No specific file or behavior.
### Steps to Reproduce
1. Open file from remote ftp server.

**Expected behavior:** [What you expected to happen]

File should appear with all lines of code.

Files sometimes are truncated - several lines of code at the end of the file are missing.
### Versions

Running macOS Sierra (10.12)
Atom version 1.10.2

**Comment by uberubert** [comment]
This has now happened for the third time for me. It has almost killed our project all three times, but thanks to backup and a hint of luck we were able to save most of the lost data.
This is actually so bad that I'm giving up on using Atom/Remote FTP, until this has been resolved.

**From our viewpoint:**
Upon downloading, it seems that the last part(s) of the file is not fully loaded.
The file is cut at some random place, even randomly in the middle of a line of code.
This means that the bottom of the file, which is usually not visible (because of fixing code in the top or middle of the file), will not provide any visual hints to the now current problem, leaving the coder oblivious to the ensuing consequences.
After performing code-changes and saving, this file (with missing parts) is pushed to the server.
Testing the code will now reveal some error, because of missing code.
CTRL+z will only bring back the original file with the missing chunks, and no part of the undo-history contains the entire file without the recent changes.

**Ideas/Thoughts/Speculation:**
I have noticed that downloading a file will sometimes "render" the file multiple times, almost like it is downloading the file in chunks and inserting chunk after chunk into the editor view as they arrive.
I'm almost certain that this is mostly true for large enough files.
My theory is that editing the file before those last chunks are loaded, will prevent the file from fully loading, and thus never enter the full file into the undo-history.

**Comment by FilipeCF** [comment]
Thats exactly what happens to me on RemoteFTP.

Usually the last part of my files are jquery,  javascript and ajax scripts, with a little impact on frontend structure, so I only detect the missing code lines later on testing when Im unable to roll back using Cmd or Ctrl+Z.

I also noticed that this occurs on larger files upon download, namely when I start to edit or scroll before the file transfer is supposed to transfer completely .

Now I always check the bottom lines after file download.
