### ISSUE TITLE
Running Stable Atom shows macOS Notifications from Atom Beta

### ISSUE THREAD

**Issue by kevinastone** [atom/atom#12906]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The notifications I receive are shown from the Atom Beta app that I installed.  But I'm running Atom stable (currently v1.10.2) which generated the notification.

### Steps to Reproduce

1. Download and install Atom Beta.
2. Run Atom Stable.
3. Trigger an OS Notification

**Expected behavior:** [What you expected to happen]

Notif from Atom with Green Icon

**Actual behavior:** [What actually happened]

Notif from Atom Beta with Gold Icon
<img width="331" alt="screenshot 2016-10-07 09 31 36" src="https://cloud.githubusercontent.com/assets/1234915/19197911/41c2d0ea-8c71-11e6-93a1-aa95301c4fb7.png">

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by andyrichardson** [comment]
I've looked through the code and resources for v1.10.3 and nothing looks unusual. Here's a few suggestions: 

1. Atom beta may have added a new daemon service to run in the background and intermittently check for updates.
2. Closing Atom (Beta) windows doesn't terminate the Atom process on mac, maybe it's still running. You have to right click the app icon in the dock and quit.
3. APM may be installed globally (likely) and only support one version installed at a time. Because of this, the beta version of apm used by the stable version of atom.

I think the third suggestion is most likely to be the case. Can you edit your post to add the versions of atom and apm you're using. For reference, I have apm v1.12.5 installed while using v1.10.3.

**Comment by thomasjo** [comment]
@kevinastone I'm assuming you're using [auto-update-packages](https://atom.io/packages/auto-update-packages), since Atom doesn't perform any automatic package updates out of the box, nor does it use any native OS notifications.

I suggest you open a new issue on the [package's GitHub repo](https://github.com/yujinakayama/atom-auto-update-packages).

**Comment by kevinastone** [comment]
Yes I am.  It looks like it's due to both the Beta and Stable release using the same bundle identifier:

https://github.com/yujinakayama/atom-auto-update-packages/blob/master/lib/package-updater.coffee#L17-L18

```
kstone@kstone-mbp ~> grep BundleIdent -A 1 /Applications/Atom\ Beta.app/Contents/Info.plist 
    <key>CFBundleIdentifier</key>
    <string>com.github.atom</string>

kstone@kstone-mbp ~> grep BundleIdent -A 1 /Applications/Atom.app/Contents/Info.plist 
	<key>CFBundleIdentifier</key>
	<string>com.github.atom</string>
```
