### ISSUE TITLE
"Unexpected token :" when saving keymap.json

### ISSUE THREAD

**Issue by styurin** [atom/atom#12964]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

Yes
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?

Yes
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?

No
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?

No
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?

Yes, I hope so
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

Yes
### Description

Getting error message when trying to save keymap:

Failed to load /Users/tyurins/.atom/keymap.json
Unexpected token :
### Steps to Reproduce
1. Open Settings -> Keybindings
2. Copy a keybinding (first one in my case)
3. Open keymap.json (from settings page or from Atom menu)
4. Paste and Save

**Expected behavior:** [What you expected to happen]

No error

**Actual behavior:** [What actually happened]

Error
### Versions

$ atom --version
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by mnquintana** [comment]
This is because copying a keybinding from `Settings -> Keybindings` copies CSON, rather than JSON, which you tried pasting into `keymap.json` – if you rename that to `keymap.cson` it should work.

But, settings-view should probably be smart enough to detect which format `keymap.cson` is in and copy the right format for keybindings. We should also probably make this error more descriptive.
