### ISSUE TITLE
Error in launching (Scientific Linux 6)

### ISSUE THREAD

**Issue by mariob6** [atom/atom#13049]
I just installed for the first time atom on my system. 

when I try to launch it for the first time I get the error:

`usr/share/atom/atom: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
`

Since I'm quite new to SL6, I could use some help figuring out what is the issue and how to solve it!

**Comment by lee-dohm** [comment]
Thanks for reaching out.

It sounds like you haven't installed all of the requirements that Atom requires to run on the system. We don't have a build specifically for Scientific Linux, so you may want to find out how you can get libnotify installed on your system so that Atom can run. Doing a quick search for `libnotify.so.4 scientific linux 6` I was able to find this: https://rpmfind.net/linux/rpm2html/search.php?query=libnotify.so.4

I hope that helps :grinning:
