### ISSUE TITLE
Atom as a daemon

### ISSUE THREAD

**Issue by thomastjeffery** [atom/atom#13062]
This was already brought up and dismissed in issue #6352, but this is *not* about startup time. (Although that is a neat side-effect ;)

One of my favorite features of Emacs is that I can [run it as a daemon](https://www.emacswiki.org/emacs/EmacsAsDaemon) and even [start it as a systemd service](https://www.emacswiki.org/emacs/EmacsAsDaemon#toc8).

When emacs-server is running, I can make another window instantly with emacsclient and have access to all of the buffers that I had open already.

On top of this, if emacs is running as a systemd service, I get the same advantages as before, but now that instance of emacs-server is already running before I start emacs, so every new window
* has access to all of the buffers I had open before
* starts within milliseconds

and the server keeps running **even when all the windows are closed.**

How difficult would it be to implement this in Atom?

**Comment by lee-dohm** [comment]
The architecture of Atom and Emacs is different. Atom uses Electron which has a single main process and then a renderer process for each new window. Because each of these processes is a separate, OS-level process, the only way to share access to the buffers that you had open before would be the way that Atom already offers that feature, by serializing the state of the project. The Electron main process already serves as a sort of daemon, it just exits when all windows are closed on Windows and Linux. (On Mac it is common for document applications to continue running even when all windows are closed, so that is how Atom operates on the Mac.) But because each window is a completely separate environment with their own copies of packages and everything, your suggestion wouldn't have the effect on startup time that you're hoping for without an extreme rearchitecture of Atom.

In any case, this isn't something that we're going to be working on. As we stated in the previous #6352, we have other ideas around improving performance and the other feature that you mention is already covered by built-in functionality of Atom.

Thanks for your interest and obvious excitement about Atom :grinning:
