### ISSUE TITLE
Weird characters after hard reseted PC

### ISSUE THREAD

**Issue by klapuch** [atom/atom#13079]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

My computer unexpectedly stopped working while I had open a few files in Atom. I was forced to hard reset the computer. When I reopened Atom I end up with files like these:
![weird_chars](https://cloud.githubusercontent.com/assets/17772194/19738453/c8f2638c-9bb7-11e6-81c5-a10cdeed7232.png)

When I used git diff, there were no differences. Is there any possibility how to avoid similar error next time?
### Versions

```
Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by lee-dohm** [comment]
I know this kind of thing can be really frustrating, thanks for reaching out! You can check the `~/.atom/recovery` directory to see if Atom stored a copy of the file. It stores a copy of the file in the recovery directory so that if the save fails for any reason the copy is still available in the recovery directory. Then when the save succeeds, it deletes the recovery copy. This only protects against failures during the save process though.

Is this the contents of the file as shown in Atom? Or is this the contents of the file on disk too? The reason why I ask is that Atom stores the state of your editor periodically, which isn't a normal save operation (because it doesn't save over the file in your file system) and therefore isn't protected by the file recovery system. But, when you launch Atom again, it loads the old state of the editor ... which if corrupted could show you screwy files like this even though the files in your filesystem are fine.

Once we diagnose what may have actually happened, I'll see what we can do to:

1. Fix the problem
1. Give you some tips for how to avoid what happened, if possible

**Comment by klapuch** [comment]
Thanks for detailed explanation. I was in rush and I didn't check the recovery directory, so I can't say if there were some stored files. The files were probably screwed only in editor, because git status showed nothing and all tests passed even though there were still screwed files in my Atom.

**Comment by lee-dohm** [comment]
@klapuch Thanks for that information. Yeah, it sounds like it was the persisted editor state that was corrupted and not the files themselves. We are aware that in exceptional circumstances this can happen, it's just hard to tell the difference between the saved state doesn't match because it should (like when you close the editor without saving your file intentionally) or doesn't match because something went wrong (like in your case).

What you can do if you notice a situation like this again is to simply close the files, selecting "Don't Save" in the process, and then reopen them. It will load the version from disk and everything will be fine.

I hope that helps!
