### ISSUE TITLE
Multi-cursor movement shouldn't jump to the last cursor

### ISSUE THREAD

**Issue by vjeux** [atom/atom#13108]
Repro steps:
- Open a file with a few hundred lines
- Find a word that's used in many parts of the file
- cmd-ctrl-g on this word to create a cursor on all the occurrences
- see that it moves to the last occurrence. **Intended behavior:** shouldn't move
- scroll all the way up to the first occurrence
- hit the right arrow
- see that it moves to the last occurrence. **Intended behavior:** shouldn't move

Why does it happen?

The screen movement logic is encoded in the single cursor implementation:
https://github.com/atom/atom/blob/0e992326154d387611543f618ad5872dc4665586/src/cursor.coffee#L255-L268

And the cursor movement action just delegates to all the cursors:
https://github.com/atom/atom/blob/f726dcc81bcd88eb7aff1e61bd77484b875f0854/src/text-editor.coffee#L2153-L2154

So, what happens is that we're going to iterate over all the cursors, and set the screen position on all of them and the last one is going to win.

Instead, **what should happen** is that if the screen is currently under any of the cursors, don't move. If not, then find the nearest cursor and move to that one, instead of the last one.

cc @nathansobo do you have advice on how I can refactor this piece of code to solve the issue?

**Comment by nathansobo** [comment]
Hey I'm out right now and on my phone, so I'll need to take a closer look tomorrow. But I wanted to pull the logic up out of cursor and into the editor for a long time.  Basically, if we can eliminate the cursor class entirely I think that would be a win.

**Comment by nathansobo** [comment]
So what we'll need to do is explicitly pass `autoscroll: false` when manipulating the cursors from the editor to suppress the auto-scrolling behavior of the last cursor.

I'm open to suggestions on what the behavior should be instead... Do we want to autoscroll the screen in some other way, rather than to the last cursor? For example, should we try to keep the set of cursors visible before the move still visible? Regardless of what we choose, autoscroll can be implemented in the movement methods of TextEditor directly.

If I had it to do over again, the individual cursor objects wouldn't even exist... cursors would be nothing more than state in the selections marker layer of the editor. Unfortunately, they're part of the public API now so we'll have to keep the existing autoscroll behavior working outside of the batch-oriented context since individual cursors can be moved.

**Comment by vjeux** [comment]
It's still reproducible

**Comment by nathansobo** [comment]
Yeah, kind of glad the stale bot put it back on my radar.
