### ISSUE TITLE
Can't tell if a marker has been decorated synchronously

### ISSUE THREAD

**Issue by QwertyZW** [atom/atom#13114]
There's currently no API that can be used to detect whether a marker has actually been decorated or not (if the class has been added)

This creates race conditions for me if I wanted to do something with the class on its creation. For example currently  doing something like this doesn't work:

```
decoration = editor.decorateMarker(marker, type: type, class: "my-special-class")
edview = atom.views.getView(atom.workspace.getActiveTextEditor()
match = edview.shadowRoot.querySelector(".my-special-class")
```

match would return null, However if we put the querySelector call in a setTimeout's callback set to something like ~100 ms it would then work.

I tried using a MutationObserver but that didn't make a difference, it too required a setTimeout's callback to work 

```
observer = new MutationObserver (mutations) ->
  for mutation in mutations
    stocb = ->
      match = edview.shadowRoot.querySelector("my-special-class")
      if (match != null)
        #Our decoration has finally been added
        #We don't need to observe the tree for it anymore
        observer.disconnect();
        #Get our jQueryObject and play around with it
        jQueryObject = View.$(match)
        jQueryObject.mouseover (ev) =>
          console.log("moused over!")
        decoration.onDidDestroy () =>
          #once the decoration is gone
          #we have to stop tracking the line-number div
          jQueryObject.off()
    #
    setTimeout stocb, 10


#configuration of the observer:
config = { attributes: true, subtree: true };

# pass in the target node, as well as the observer options
observer.observe(edview, config);
```

Hopefully we can get something a callback parameter (which takes a cb and calls it once the decoration's been added...)

I see something like 
 ```
setUpdatedSynchronously: (@updatedSynchronously) ->
```
In https://github.com/atom/atom/blob/master/src/decoration-manager.coffee
but this class doesn't seem to be documented

**Comment by lee-dohm** [comment]
Thanks for reaching out.

Because Atom is built using JavaScript, there are a number of APIs that have to be designed to work asynchronously like this for performance reasons. For this reason, we aren't going to be adding a synchronous API for decorations.

If you'd like to discuss your design and see if there are alternatives to requiring a synchronous API, [Discuss, the official Atom and Electron message board](https://discuss.atom.io) is a great place to talk over such things with the community of Atom enthusiasts and package developers. You may want to check it out!

Thanks again :+1:
