### ISSUE TITLE
https://atom.io/ is broken

### ISSUE THREAD

**Issue by diracdeltafunk** [atom/atom#13153]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? **N/A**
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? **N/A**
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? **N/A**
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

![capture](https://cloud.githubusercontent.com/assets/1844060/20043329/797c7798-a440-11e6-8f7b-c5e9e8380fb2.PNG)

### Steps to Reproduce

1. Go to https://atom.io/ in Chrome Version 54.0.2840.71 m (64-bit).

**Expected behavior:** The website looks normal

**Actual behavior:** The website does not look normal

**Comment by jsolisu** [comment]
I'm using Chrome Version 54.0.2840.87 m (64-bit) and it all works.

**Comment by shiftkey** [comment]
Looks like some intermittent issues with resources not being served by the Fastly CDN.

@diracdeltafunk is this repeatable? If so, can you open the Network tab in the Chrome Dev tools, reload the page and show what the response headers are for 
`https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/application-ba07c5c2889a34307a4b7d49410451d9.css` (should be the second entry)

**Comment by diracdeltafunk** [comment]
I'm now using Chrome Version 54.0.2840.87 m (64-bit) but the problem persists. @shiftkey, Here's what I see:

![capture](https://cloud.githubusercontent.com/assets/1844060/20044664/84d71d0a-a44f-11e6-8cb5-af2752156dcb.PNG)

**Comment by jsolisu** [comment]
From Edge Version 38.14393.0.0 works

![image](https://cloud.githubusercontent.com/assets/3818673/20044737/f3ec4e0c-a460-11e6-81e0-ad9d372af6ce.png)

On Chrome Version 54.0.2840.87 m (64-bit) (There are some errors)

![image](https://cloud.githubusercontent.com/assets/3818673/20044753/18759c6a-a461-11e6-904c-34b62229f30f.png)

**Comment by diracdeltafunk** [comment]
@jsolisu it seems that the issue does not affect you, but the website is broken for both edge and chrome on my PC. It's also clearly an issue for other people:

https://twitter.com/div3rse_/status/795156008108695553
https://twitter.com/hideo54/status/794826282840113153
https://twitter.com/BashfulMonk/status/794621268612050945
https://twitter.com/yamarten/status/794531721068716034

**Comment by shiftkey** [comment]
This is what I was looking for:

<img width="453" alt="screen shot 2016-11-06 at 9 47 14 pm" src="https://cloud.githubusercontent.com/assets/359239/20045924/a1a9f84c-a46a-11e6-9e03-1ba47a6d04a6.png">

Looks like the HTTPS handshaking is failing on fastly. Gonna ask around to see if it's a known issue.

@diracdeltafunk what OS are you running? (the more details, the better)

**Comment by shiftkey** [comment]
>  but the website is broken for both edge and chrome on my PC. 

@diracdeltafunk do you see the same HTTP 503 response in Edge as well?

**Comment by olamedia** [comment]
Failed to load resource: the server responded with a status of 503 (error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error)
VM84:1 Refused to load the script 'https://static.ads-twitter.com/oct.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com https://github-atom-io-herokuapp-com.global.ssl.fastly.net".

atom.io/:271 Uncaught ReferenceError: twttr is not defined
VM84:6 Refused to load the script 'https://js-agent.newrelic.com/nr-998.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com https://github-atom-io-herokuapp-com.global.ssl.fastly.net".
r @ VM84:6
https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/ZeroClipboard-1271a06aa3ba38e76fdbc8393d3d0b9e.swf?noCache=1478494473578 Failed to load resource: the server responded with a status of 503 (error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error)
https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/application-ba07c5c2889a34307a4b7d49410451d9.css Failed to load resource: the server responded with a status of 503 (error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error)

**Comment by gbrayut** [comment]
May be isolated to a few PoPs. Check the X-Served-By header to see where your requests are served from. They also display per pop stats on their dashboards.

**Comment by olamedia** [comment]
Accept-Ranges:bytes
Connection:keep-alive
Content-Length:625
Content-Type:text/html; charset=utf-8
Date:Mon, 07 Nov 2016 05:10:25 GMT
Retry-After:0
Server:Varnish
Via:1.1 varnish
X-Cache:MISS
X-Cache-Hits:0
X-Served-By:cache-fra1231-FRA
X-Timer:S1478495425.339600,VS0,VE187

**Comment by arcticicestudio** [comment]
Same problems for Firefox `v49.0.2` on Arch Linux.
Getting a `503` for `https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/application-ba07c5c2889a34307a4b7d49410451d9.css`

**Comment by gbrayut** [comment]
Repro here using https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/application-ba07c5c2889a34307a4b7d49410451d9.css on Chrome 54 in Android 6. Served from JFK, and I see LAX, DEN, FRA in other reports. 

Is fastly using HTTPs to your origin? In that case have there been any changes in your servers around TLS cyphers? "SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error" seems to have reports online as an issue with misconfigued cyphers, which could be from fastly to the origin if that is also set to use TLS. You may only see issues now that cached assets are expiring.

**Comment by rosspi** [comment]
Same issue here

**Comment by solobat** [comment]
+1

**Comment by Tiendq** [comment]
+1 with Chrome 54.0 on OSX.

**Comment by Ben3eeE** [comment]
Thanks for the report everyone. We are tracking this in https://github.com/atom/atom.io/issues/99.

**Comment by diracdeltafunk** [comment]
@shiftkey Yes, I get the same 503 in Edge. I'm running Windows 10 Pro N, Version 10.0.14393 Build 14393

@gbrayut Here's what I see right now in Chrome:

```
Request URL:https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/application-ba07c5c2889a34307a4b7d49410451d9.css
Request Method:GET
Status Code:503 error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Remote Address:151.101.24.249:443

HTTP/1.1 503 error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Server: Varnish
Retry-After: 0
Content-Type: text/html; charset=utf-8
Content-Length: 625
Accept-Ranges: bytes
Date: Mon, 07 Nov 2016 06:36:59 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-lax8644-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1478500619.456833,VS0,VE144

GET /assets/application-ba07c5c2889a34307a4b7d49410451d9.css HTTP/1.1
Host: github-atom-io-herokuapp-com.global.ssl.fastly.net
Connection: keep-alive
Cache-Control: max-age=0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36
Accept: text/css,*/*;q=0.1
Referer: https://atom.io/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,fr;q=0.6,zh-CN;q=0.4,zh;q=0.2
```

**Comment by gbrayut** [comment]
Any reports of the above URLs actually working on a cleared cache and a miss from fastly x-cache header? Pretty sure fastly uses haproxy to terminate https, so an error message from varnish likely means it can't connect to the origin over TLS. Easy test would be changing the [fastly config](https://docs.fastly.com/guides/securing-communications/connecting-to-origins-over-tls) to use port 80 instead of 443 for the origin. If that resolves issues then there is something broken with fastly connecting to the origin over TLS.
