### ISSUE TITLE
I can't reinstall Atom anymore

### ISSUE THREAD

**Issue by yonaclementie** [atom/atom#13150]
### Description

I launched Atom the first time and it could install well, but I had problems saving files and running Python files and tried to reinstall it. As I couldn't find the uninstall application, I used the windows program uninstall. Only the shorcut on the desktop disappeared though, while the other files created by the installation remained. So I deleted them permanently (Sorry I am a totaly beginner in anything related to these things...) and the installation didn't worked anymore the second time I launched it. The loading gif shows for one or two seconds, then disappears and I have this error message:

![image](https://cloud.githubusercontent.com/assets/23275730/20031640/ed5a1126-a38b-11e6-9b25-9d5db623540b.png)

This is the content of the setup log:

[SquirrelSetup.pdf](https://github.com/atom/atom/files/573335/SquirrelSetup.pdf)

I have been downloading Atom from https://atom.io and I am using a Windows 7 32bits. My antivirus is Avast and I am an administrator on the computer. I tried to download again the application but the installation didn't worked. I also tried to install Atom on an other user account and the installation worked, but when opening the application the Atom Welcome Screen doesn't open correctly and only displays a grey window.

### Versions
My Atom version is 1.11.2.0

**Comment by GabrielAPass** [comment]
I find the same problem.  Possibly I should have used the upgrade button from within Atom.  
However, I opted to uninstall and re-install the noticing that 64bit architecture is now the default offering.

The problem seems to be a file/folder access problem.  Beginning with the inability to access or create the path below:

`Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\*username*\atom\packages\.betaId'.`

Again, this problem appeared after uninstalling a previous version and attempting to install Atom 1.16.0.
I tried to "Run as Administrator" from an already admin account and also verified that I have read write access to all folders listed in the log

My SquirrlSetup.log file is attached.
[SquirrelSetup.pdf](https://github.com/atom/atom/files/949875/SquirrelSetup.pdf)
