### ISSUE TITLE
MAC: atom --profile-startup doesn't work on 1.12.0 

### ISSUE THREAD

**Issue by ungb** [atom/atom#13171]
Bug:  running `atom --profile-startup` in terminal doesn't work

Steps to Reproduce

1. Make sure you have latest installed from atom.io (currently it is 1.12.0).
2. run: `atom --profile-startup`

**Expected behavior:** Open Atom with dev tools open showing how long it took to load to startup
**Actual behavior:** For me, it just crashes.  Atom doesn't open.

**Versions**
Atom: 1.12.0
apm: 1.12.9
macbook pro 2015:  10.12.1

**Comment by Alhadis** [comment]
I came here to report similar behaviour with `atom --dev`, probably related.

**Output of `apm --version`**:

	apm: 1.12.9
	npm:  3.10.5
	node: 4.4.5
	python: 2.7.12
	git: 2.10.2

**Executed path:** `/Applications/Atom.app/Contents/Resources/app/atom.sh -d`

This is still happening even after I:
1. Cleared all caches and storage directories in `~/.atom`
2. Uninstalled and reinstalled Atom
3. Repeated step three after rebooting my computer
4. Removed all packages from `~/.atom/dev/packages`

Outcome of every attempt to reopen in dev-mode:

<img width="532" alt="So I did." src="https://cloud.githubusercontent.com/assets/2346707/20160033/7af4bc02-a738-11e6-8f9c-9bb8d59bb7f5.png" />

**Comment by ungb** [comment]
@Alhadis I'm not sure if it's related, but if you have atom repo checked out in `~/github/atom`.  Try moving that directory and launching atom again with --dev.   

1. Close all Atom instances
2. `mv ~/github/atom ~/github/atom_backup`
3. `atom --dev`

If you don't have Atom repo in `~/github/atom`, it could be located where the environment variable `ATOM_DEV_RESOURCE_PATH` is set.

**Comment by Alhadis** [comment]
Nope, and there're no ATOM_* variables except `$ATOM_THEME`, which is just a shortcut pointing to my heavily-customised Atom setup (that takes the form of a syntax theme... don't ask).

So as far as I can tell, there's no obvious reason this should be happening... :\

**Comment by ungb** [comment]
do you have the repo checked out in `~/github/atom`?

**Comment by Alhadis** [comment]
No. I'm running a stable version; I just upgraded to Atom v1.12.0 earlier before...

**Comment by Alhadis** [comment]
This mightn't be related after all; I've narrowed the culprit down to a [language package](https://github.com/nwhetsell/language-csound) I had installed, which is causing the editor to crash when it's opened in dev-mode (for reasons I've yet to determine).

So far, my theory is it might have something to do with needing to rebuild native modules or something... the `language-csound` package has [`first-mate`](https://www.npmjs.com/package/first-mate) as a hard dependency, which in turn requires [`oniguruma`](https://www.npmjs.com/package/oniguruma) (that needs compiling). Otherwise, I'm drawing blanks here.

@ungb What packages do you have installed/enabled? Can you confirm if this issue still occurs with every community package disabled?
