### ISSUE TITLE
event.target no longer hold text-editor-element from 1.13.0-beta0

### ISSUE THREAD

**Issue by t9md** [atom/atom#13189]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

What `event.target` is holding was changed from Atom v1.13.0-beta0.
Which was hold text-editor-element in v1.12 but its changed to hold hidden-input-element.
So code like `event.target.getModel()` no longer work from v1.13.

Is this intentional change or accidential change?

### Steps to Reproduce

Define following command in `init.coffee`, and invoke it via command-pallette or via keymap(both results are same).

```coffeescript
atom.commands.add 'atom-text-editor', 'dev:show-event-target-of-text-editor-scope', (event) ->
  console.log event.target
  # following line throw exception from v1.13.0 since its no longer hold texxt-editor-element
  # console.log event.target.getModel()
```

- In atom v1.12.0: `<atom-text-editor class="editor vim-mode-plus normal-mode" tabindex="-1" data-grammar="source coffee" data-encoding="utf8"></atom-text-editor>`
- In atom v1.13.0-beta: `<input class="hidden-input" tabindex="-1" data-react-skip-selection-restoration="true" style="transform: translateZ(0px); top: 155px; left: 84px; width: 7px; height: 18px;">`

So package code `event.target.getModel()` no longer work from v1.13.0

### Versions

- atom-beta
```
$ atom-beta --version
Atom    : 1.13.0-beta1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

- apm-beta
```
$ apm-beta --version
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.6
git 2.7.4
```

**Comment by t9md** [comment]
When I clicked editor, event.target also hold text-editor-element which was very useful, but from v1.13.0-beta0 it just return `<div>` or `<span>`(just exact element which was clicked), which is not useful.
My package need big rewriting to fix this, before that I want to confirm this change is intentional and also want to know alternative way to get editorElement clicked from event.

**Comment by 50Wliu** [comment]
I think there's a `.closest()` method you can use?  /cc @as-cii

**Comment by t9md** [comment]
Thanks @50Wliu , I'll try, but I'm also curious if code like [this](https://github.com/t9md/atom/blame/master/src/pane-element.coffee#L31) still work on latest atom? If event.target point exact clicked element, its no longer point to paneElement which this line of code assuming.

**Comment by as-cii** [comment]
@t9md thanks for the report, and apologies for breaking your package!

> but I'm also curious if code like this still work in latest atom?

This change should apply only to editor elements, so I think `PaneElement` should still work fine.

> My package need big rewriting to fix this, before that I want to confirm this change is intentional and also want to know alternative way to get editorElement clicked from event.

Yes, the change was intentional and was caused by removing the shadow DOM boundary from `atom-text-editor` elements. However, I wonder if, while we're still in beta, we should provide a shim when packages try to access the `.target` property on an `Event` object, although that would be somewhat inconsistent with `document.activeElement`, which we cannot provide a shim for.

Searching for usages of `target.getModel()` in packages yielded the following results:

* atomic-emacs/lib/atomic-emacs.coffee
* choose-pane/lib/main.coffee
* context-git/lib/command.js
* cursor-history/lib/main.coffee
* elmjutsu/lib/autocomplete-provider.js
* expand-region/lib/selector.coffee
* extract-component/lib/extract-component.js
* finalbuilder/lib/finalbuilder-utils.coffee
* gherkin-table-formatter/lib/gherkin-table-formatter.coffee
* haskell-ghc-mod/lib/upi-consumer.coffee
* haskell-pointfree/lib/haskell-pointfree.coffee
* ide-haskell/lib/ide-haskell.coffee
* ide-haskell-hasktags/lib/ide-haskell-hasktags.coffee
* ide-haskell-repl/lib/ide-haskell-repl.coffee
* line-ending-selector/lib/main.js
* line-ending-selector-unix/lib/main.js
* nvatom/lib/notational-velocity.coffee
* open-html-in-browser/lib/main.coffee
* quick-file-actions/lib/quick-file-actions-view.js
* quick-query/lib/quick-query-result-view.coffee
* vertical-motion/lib/vertical-motion.coffee

Interestingly, the `line-ending-selector:convert-to-LF` and `line-ending-selector:convert-to-CRLF` commands seem to be broken on beta because of the same problem, so I am going to change that package to use `target.closest('atom-text-editor')` instead, and prepare a hotfix to release later today.

@nathansobo: what do you think? I am a little concerned about packages breakage at this point, although (based on the search above) it seems like only a few are using `event.target` and assume it is a `TextEditorElement`, so hopefully they can be fixed during the beta period. Still, a shim is probably warranted, as there might be usages of the `.target` property that are difficult to catch with a regular expression.

**Comment by t9md** [comment]
@as-cii 

> This change should apply only to editor elements, so I think PaneElement should still work fine.
Got it, thank you for clear explanation, I've already fixed my package using `closest('atom-text-editor')`.
