### ISSUE TITLE
Atom spawning zsh which consumes 100% CPU and other bugs in latest version 1.12.4-1

### ISSUE THREAD

**Issue by ed-torvalds** [atom/atom#13279]
I am using Arch Linux with GNOME v3.22.2, Atom v1.12.4-1, apm v1.14.1-1, ZSH v5.2-1 (ZSH is my default shell)  
With last upgrade: 
1. Atom ( v1.12.4-1) is spawning  ZSH as child process and this ZSH process is consuming 100% CPU continuously. (screen shot below)

![screenshot from 2016-11-20 00-03-40](https://cloud.githubusercontent.com/assets/15322797/20461683/620973e0-af2b-11e6-8333-12b3ffd4fa5d.png)

But when I close Atom editor, this ZSH process becomes child of PID 1 (systemd) (screen shot below) and still consumes 100% CPU

![screenshot from 2016-11-19 17-16-42](https://cloud.githubusercontent.com/assets/15322797/20461696/b266c68a-af2b-11e6-969c-fd8ae275d35d.png)

2. I cannot open Settings tab from Menu > Edit > Preferences, instead I have to use keyboard shortcut Ctrl + ,

3. I cannot create new file from menu nor open a file from folder not in project folder.

**Please note**: these all problems go away if I run Atom in safe mode. I tried removing `~/.atom` folder and installing all packages again but I still face these problems.

Please ask me for details in case I have not included them here, thanks for your help.

`Update`: Starting atom with `----clear-window-state` once did not help.

**Comment by arcticicestudio** [comment]
This is related to #13084 you can subscribe to.
You can try to start atom from the terminal with the `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=true atom .` command and see if it still happens.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---
Additionally, this is almost surely caused by using an unofficial build of Atom. The only officially supported way of installing Atom on Arch is building from _pristine_ source code.
