### ISSUE TITLE
Error: spawn clang ENOENT  in saving the c++ file.

### ISSUE THREAD

**Issue by akshayarise** [atom/atom#13278]
while saving this insertion.cpp file in atom editor in ubuntu 16.04 given below :-
```js
/*
 * C++ Program to Implement Insertion Sort
 */
#include <iostream>
using namespace std;
int main()
{
    int a[16], i, j, k, temp;
    cout<<"enter the elements\n";
    for (i = 0; i < 16; i++)
    {
        cin>>a[i];
    }
    for (i = 1; i < 16; i++)
    {
        for (j = i; j >= 1; j--)
        {
            if (a[j] < a[j-1])
            {
                temp = a[j];
                a[j] = a[j-1];
                a[j-1] = temp;
            }
            else
                break;
        }
    }
    cout<<"sorted array\n"<<endl;
    for (k = 0; k < 16; k++)
    {
	cout<<a[k]<<endl;
    }
}
```
It is showing this error :-
`Error: spawn clang ENOENT at exports._errnoException (util.js:890:11) at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32) at onErrorNT (internal/child_process.js:348:16) at _combinedTickCallback (internal/process/next_tick.js:74:11) at process._tickCallback (internal/process/next_tick.js:98`

how to resolve this issue ? please help

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by thomasjo** [comment]
Additionally, Atom has zero "on-save" behavior outside of stripping whitespace, so your problem is caused by one of your installed community packages (which would have been uncovered while filling out the issue template).
