### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by CodehanBK** [atom/atom#13280]
My atom editor has crashed. After a full uninstall/reinstall the problem still occurs. 

Is there a way to fix this issue?

This is what I get when I open the editor:

![atom](https://cloud.githubusercontent.com/assets/15932236/20467523/c0938db6-af89-11e6-8253-cb053ae17aca.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
***
In addition, I have a hunch that if you rename your `~/.atom` folder to something like `~/.atom-backup`, the crash will go away.  This is most likely being caused by one of your community packages or a bad serialized state.  You can test out those theories by launching Atom using `atom --safe` or `atom --clear-window-state`, respectively.

**Comment by griffithben** [comment]
Just to follow up, I had the exact same situation.  I found that going into `~/.atom/packages/` and removing one package at a time until I found the culprit solved this for me.  Hope this helps someone else.

**Comment by euggrie** [comment]
Thanks @griffithben, that fixed it for me too.
