### ISSUE TITLE
Additional quotes on win32 in BufferedProcess

### ISSUE THREAD

**Issue by bmaschio** [atom/atom#13295]
I am trying to run a simple bat ( for a linter ) and at the BufferedProcess execution try I get the process variables that look like this
Command : C:\Windows\System32\cmd.exe"
Parameter of execution :
""C:\Windows\System32\jolie.bat "--check" "C:\Progetti\PortaleManutenzioneAndroid\Leonardo\leonardo.ol"""

Where the Linter execution path is 'C:\Windows\System32\jolie.bat'

It is symilar to the problem raised on #3208

my Atom version is 1.12.4

Regards 
Balint

**Comment by thomasjo** [comment]
Thanks for contributing!

It appears that this is being caused by the [sb-exec](https://github.com/steelbrain/exec) npm package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

It could also be caused by a problem in your configuration if you've actually entered `'C:\Windows\System32\jolie.bat'` as the executable path in linter-jolie. The quote wrapping should not be done by you. Additionally, this has nothing to do with `BufferedProcess`, since none of the relevant code paths use that class.
