### ISSUE TITLE
the bug of lose response when edit an url.

### ISSUE THREAD

**Issue by ValkyriaLenneth** [atom/atom#13309]
hello,I'm a user of ATOM from China.
When I use ATOM to copy an url,the editor will lose response for about 3 seconds. It happens when I do the work about URL.
My PC's OS is win10.
And I asked servel friends using Atom about this question,they said they met it sometimes.
I hope you can give me a solution ,because I really like this editor,it's amazing,and I hope it can be better.
thanks alot.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the issue template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
***
To answer your question, try running Atom in safe mode: `atom --safe`.  If that doesn't help, fill out the issue template and notify us when you do.
