### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [atom/atom#13301]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures in order to verify easily and quickly of your source code releases.

**Overview of the required tasks:**
* Please [create and/or use a 4096-bit RSA keypair](https://wiki.archlinux.org/index.php/GnuPG#Create_key_pair) for the file signing
* The key may be used for [email encryption](https://www.enigmail.net/index.php/en/) too
* Keep your key secret, use a strong unique passphrase for the key
* [Sign every new commit by default](https://help.github.com/articles/signing-commits-using-gpg/)
* [Sign new tags](https://help.github.com/articles/signing-tags-using-gpg/)
* Verify the Github Release tarball download against your local source
* [Sign Github Release tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Additional Information: **
* https://help.github.com/categories/gpg/
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work https://www.qubes-os.org/doc/verifying-signatures/
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

Thanks.

**Comment by lee-dohm** [comment]
Thanks for the feedback! We're aware of the benefits of encryption and digital signatures. Many of our more prolific contributors, including myself, have adopted configurations where their contributions are digitally signed. We use HTTPS connections as much as possible. And we will continue to expand our use of encryption and digital signatures where it makes sense.

However:

* Requiring that all commits be digitally signed would put a heavy burden on brand new contributors, potentially preventing some from contributing at all, for very little real benefit
* Digitally signing tags provides no benefit
* Digitally signing released tarballs can provide some benefit if they are stored after they are downloaded but since you can always download a tarball from a verifiable secure connection via HTTPS, it is unclear whether this is of enough benefit to balance out the maintenance overhead to our build process

I've brought your requests up to the team and we will periodically review our practices to see if any of these factors change.

Thanks again for your feedback!

**Comment by NicoHood** [comment]
I think you are partly right, that not everyone will understand the needs of PGP, even for "just" adding smaller changes. However the more we use GPG, the more people will understand its needs and also how easy it is too use and how much we can gain from that.

HTTPS downloads are very important, however this still does not solve the problem fully. I think that an official pgp signature for every release would not hurt too much. It is common practice to sign software sources. As Linux distribution it is extremely difficult to provide the user with safe built packages. And gpg is the only real solution that covers this. Please consider to at least sign every major release with gpg.

Thanks for taking the time and also giving back feedback :)

**Comment by eli-schwartz** [comment]
Huh, found this via the NicoHood [Wall of Shame](https://github.com/NicoHood/gpgit/wiki/TODO).

Some observations:

- Requiring that everyone sign every commit is not necessary. The goal of digitally signing the development history is fulfilled as long as direct commits are signed by a trusted Atom developer, and external contributions are merged via a merge commit that was signed by a trusted Atom developer (this does require merging via the command line rather than the button on the website). Joe Contributor's signature doesn't actually tell us anything useful regarding the Atom project anyway. 😄 That being said, it certainly isn't a bad thing if they do!
This does ensure that the latest HEAD commit is always signed, which is useful for the [atom-editor-git](https://aur.archlinux.org/packages/atom-editor-git) package. The next minor release 5.1 of makepkg (used for creating Arch Linux packages) supports verifying the GPG signature of the commit or tag used as the git source for building the package, assuming that upstream projects actually commit to a policy of ensuring that all commits merged/pushed to master are actually signed by the GPG keys listed as the release signing keys for said project.
- Digitally signing tags provides a benefit to anyone looking to build Atom from a tagged release in their git clone of the repository. For example, the Arch Linux package for electron is built from a git clone, since the build process makes heavy use of submodules. (Arch Linux packages can use git repositories as the package source.) As it happens, Atom is built from the release tarball...
- Digitally signing release tarballs, provides the general benefit of GPG over mere transport encryption. As long as the GPG signing key is securely held by a person who knows what they are doing, it tells you that your HTTPS connection was neither hacked nor rendered moot by a server-side hack. It also tells you that in the unlikely case that Github Inc. somehow goes rogue and cuts off commit access to the developers and generally starts messing with the project source code, they cannot replace stuff with malicious content, without again failing the GPG validity check. HTTPS tells you nothing, except that the download transport and **only** the download transport was encrypted with an SSL certificate issued by a generically trusted provider.

**Comment by lee-dohm** [comment]
Even though we may not agree on things, I appreciate that @NicoHood was respectful in both their post here and their treatment on the listing linked above.

Starting off a conversation by calling shame is not respectful and does nothing to convince me that I want to work with the person treating people that way.

**Comment by eli-schwartz** [comment]
I intend no shaming. 😄 I just wanted to clarify what GPG signing would actually entail, and possibly be a little less extreme than NicoHood.  (No need to persecute third-party contributors over it, for one.)

As for the wall of shame, I have no idea why NicoHood wants to shame people, but if you follow his links to e.g. JoeLametta/whipper#77 and hyperion-project/hyperion#730 that is certainly what he seems to be doing... I find it amusing in a vaguely-horrifying manner. But you are definitely being shamed.

**Comment by NicoHood** [comment]
Just about the "shame" part. You are right and this was removed long time ago. I learned from that. I will no longer call it shame, but I will track unsigned packages as its a possible risk at the packaging stage. The whole project will be a way more detailed analysis of all ArchLinux packages. Its goal is to secure every package as best as possible and to encourage other developers to also sign their sources.

I hope we can see GPG signed atom releases in the future as we all wish a secure operating system.
