### ISSUE TITLE
atom tool issue about edit methold while using GUI

### ISSUE THREAD

**Issue by LuoLynne** [atom/atom#13306]
Hi, maybe, someone already asked you about this kind of question, but I also want to report some issues while finding in using atom to edit code.
1. Code can not be dragged in the edit panel to move to another line in the current file by mouse in GUI.
2. The edit tool do not support the hotkey "ALT+mouse drag"  and "CTRL+mouse drag", "ALT+mouse drag" should be able to select the same column from different rows which is Adjacent, besides, editing the same column(identical) can not affect the content behind the edit place.the Effects as notepad++.
3. It's to slow while start up atom, will it be faster than now.
4. How can I call the chrome console tool in internal of atom  while developing WEB.
thanks.

**Comment by lee-dohm** [comment]
Thanks for reaching out :grinning: Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

To specifically answer your questions:

1. This is being tracked in https://github.com/atom/atom/issues/1909
1. This is being tracked in https://github.com/atom/atom/issues/2306
1. Please see the [entry in the Atom FAQ about performance concerns](https://discuss.atom.io/t/atom-feels-slow-or-is-consuming-too-much-cpu-or-memory/32662)
1. Atom doesn't support debugging of web applications (or any other application for that matter). The built-in Chrome developer tools are designed to be used for debugging Atom itself.
