### ISSUE TITLE
Tab names are invisible

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [atom/atom#13328]
Most of the time when I put my computer in sleep mode, all the tab names become invisible, and I have to restart Atom to make them visible again. This has been a problem for a long time now.
I can't reproduce it intentionally, because when I put my computer in sleep mode and use it in a few minutes, the problem doesn't occur.

Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
Windows 10 x64
[Image](https://i.gyazo.com/399b4f0b4d6ae31dc1cdf6cd28330430.jpg)

Installed packages:

advanced-open-file
atom-beautify
atom-html-preview
atomic-chrome
atom-keyboard-macros
emmet
file-icons
git-time-machine
highlight-selected
jade-beautify
javascript-snippets
js-hyperclick
language-autohotkey
language-ejs
open-in-browsers
project-plus

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
