### ISSUE TITLE
editing php-file cause atom crashed with `lf` line-end-style;  while with 'crlf' style that  is normal

### ISSUE THREAD

**Issue by netmou** [atom/atom#13332]
atom version 1.12.5
there are some  package installed which has related with php like follow:
1. Atom-Autocomplete-Php version 0.20.2
2. linter-php version 1.3.1

![image](https://cloud.githubusercontent.com/assets/7068058/20639859/17e84834-b40a-11e6-9243-e6c5387de3f8.png)
like the  above picture ,press enter key to start new line then atom crashed on `lf` line-end-style

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
