### ISSUE TITLE
Failed to spawn command python3. Make sure python3 is installed and on your PATH

### ISSUE THREAD

**Issue by sherlockhoatszx** [atom/atom#13330]
I use mac OS X system. And have successfully installed Anaconda and run python2.7 for a long time. Today I try to switch my editor to ATOM, so i download it from official page. and when i try to build a new test.py, error happens:Failed to spawn command python3. Make sure python3 is installed and on your PATH. 
what i have tried:
I checked my PATH, type in the terminal: echo $PATH, which python, and the terminal shows :/Applications/anaconda/bin/python.   
and i add these in the top of my code script  
#!/usr/bin/env python
#!/Applications/anaconda/bin/python

But same errors still reported.
What i want :  i want to use Atom using python2.7(installed in my macbook)

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---
As a side note, Atom does absolutely nothing with respect to Python out of the box, so your problem is caused by one of the Python-related community packages you've installed.
