### ISSUE TITLE
Search simply doesn't work at all.

### ISSUE THREAD

**Issue by tenten8401** [atom/atom#13333]
### Description

Search simply does not work, it may be after a certain line number, I'm unsure, but it's always when I'm editing code.

### Steps to Reproduce

1. Get an insanely long file
2. Search for something in it
3. No results found, despite it being in the file

**Expected behavior:**
It should be able to find what I ask it to

**Actual behavior:**
It claims there are no results found

**Screenshots:**
![image](https://cloud.githubusercontent.com/assets/6174343/20640414/2ce95a7a-b3ab-11e6-87ca-dd9bb828b3c5.png)

### Versions
Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python
git
visual studio 2015

**Comment by undefinedvar** [comment]
You are searching for SUFI_Map_ar_baggage, where in your file is SFUI_Map_ar_baggage. What's the problem then xD ?

**Comment by tenten8401** [comment]
@undefinedvar directly above the search bar.

**Comment by thomasjo** [comment]
You have a typo in your search string... the text clearly contains `SFUI_Map_ar_baggage`, but you are searching for `SUFI_Map_ar_baggage`. This is exactly what @undefinedvar was trying to tell you.

**Comment by tenten8401** [comment]
Corrected my screenshot. Straight copy/paste from the string above:
![image](https://cloud.githubusercontent.com/assets/6174343/20641071/9686fc78-b3bd-11e6-8de3-4758f0eee41a.png)

**Comment by thomasjo** [comment]
OK, looks like this is an actual bug/limitation, but since searching is handled by the [find-and-replace](https://github.com/atom/find-and-replace) package, please re-open the issue there (with the correct screenshot).

I'm unsure if the limitation is directly controlled in that package due to markers and highlighting being disabled on large files, or some file length check in the package. Regardless, there issue belongs in that repo, and if it turns out to be a limitation in Atom core, we'll have to implement some type of informative message in the find-and-replace package to make the user aware of the (current) limitation.

Thanks!

**Comment by tenten8401** [comment]
Done.
