### ISSUE TITLE
Feature Request Automaticaly add Script tag also link tag for external libraries like for jquery,Bootstrap or our own external css/js etc

### ISSUE THREAD

**Issue by MandarSant** [atom/atom#13339]
I am requesting for feature that whenever we download external libraries like jquey,bootstrap and etc....
we have to add script tag to html so when we download it the script should automaticaly generated insted of typing for save time same feature can work for external our own css/javascript and also same for cdn link insted of copy paste the tag will be auto generated

i am just a beginer so i cant create a screen shot

**Comment by arcticicestudio** [comment]
As far as I understand you're talking about editing HTML/Markup based files, right?
This repository is for the Atom Core, but the related should be the [`language-html`](https://github.com/atom/language-html) package repository.

But anyway it's not necessary to create another issue because you requested feature can be done easily with [snippets](http://flight-manual.atom.io/using-atom/sections/snippets) and it looks like there is a package called [`cdn-libs`](https://atom.io/packages/cdn-libs) which does exactly what you like to have 😄

**Comment by MandarSant** [comment]
@arcticicestudio i am talking about snippets the tag should be auto genrated

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
