### ISSUE TITLE
What file for windows x64

### ISSUE THREAD

**Issue by Jawanet** [atom/atom#13345]
Hi

I not see zip file with name windows-x64 like in intro.

What file for  windows x64

Tanks you

**Comment by thomasjo** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by thomasjo** [comment]
The preliminary work has been done, and 64-bit releases for Windows will likely start showing up in the very near future. For reference, Windows 64-bit binary generation shipped in https://github.com/atom/atom/pull/13135.

**Comment by Jawanet** [comment]
Sorry if I've been disrupting team atom

I wanted to try the atom, but not know the files for x64 os. Or atom-windows.zip can be for all types of windows?

**Comment by thomasjo** [comment]
@Jawanet No problem, just that this is not the place to ask questions.

To answer your question though, yes, you can run 32-bit binaries on 64-bit Windows. Easiest way of getting Atom is to navigate to http://atom.io, and clicking on the download button.

**Comment by alrz** [comment]
Do we need to uninstall the previous x86 version?
