### ISSUE TITLE
Why bundled themes are broken (in their git repo)?

### ISSUE THREAD

**Issue by felixsanz** [atom/atom#13359]
I'm posting here because it's not specific to one theme, but all.

Examples:
https://github.com/atom/solarized-dark-syntax
https://github.com/atom/base16-tomorrow-light-theme

If you check `index.less`, appears this:

```less
@import "colors";
@import "syntax-variables";

// Editor
@import "editor";

// Languages
@import "syntax/_base";
@import "syntax/c";
// ...
```

But that directory structure doesn't exist! Everything is inside  `styles` folder.

So.. how does the less files resolves correctly?

I also noticed that doing `apm install <theme>`, installs the package with the same contents (so apparently broken and unresolvable)

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by felixsanz** [comment]
@Ben3eeE  This is not a question. An unresolvable path is an issue.

**Comment by simurai** [comment]
@felixsanz I'm actually not quite sure why it works without `styles`. Maybe it's aliased for some reason. Found [this](https://github.com/atom/atom/blob/master/src/theme-manager.coffee#L296).

Anyways, it's probably a good idea to just write out the paths without taking the shortcut, like `@import "styles/colors.less";`. Should avoid confusion.

// @atom/feedback if somebody has more insights.
