### ISSUE TITLE
feature request：give one line a special color

### ISSUE THREAD

**Issue by ylqhust** [atom/atom#13367]
### sometimes I want to emphasize one line code,if I can give the line a special color,it's will be good

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
