### ISSUE TITLE
Splash-screen rocket does not launch after installation

### ISSUE THREAD

**Issue by rickydutton** [atom/atom#13362]
![image](https://cloud.githubusercontent.com/assets/11612282/20763572/82bac48c-b722-11e6-9a6c-f80ff70141a8.png)

Disappointingly the rocket never launches, despite clearly being loaded with cargo. The graphic then disappears and, rather crudely by comparison, the atom window pops up. 

I know this might seem minor to some, but if that rocket launched at the end of the installation I would be  copying atom directly over the top of notepad.exe in system32 _and_ sysWOW64  but until then I'm afraid I'm going back to Sublime Text.

**Comment by lee-dohm** [comment]
Thanks for reaching out!

I have passed along the information to the maintainers team for review after the holidays. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.
