### ISSUE TITLE
Terminal window not closing when program terminates

### ISSUE THREAD

**Issue by inspiralpatterns** [atom/atom#13368]
### Description

After the program terminates and I'm prompted to 

> press any key to continue...

I get no results and the compiler shows me

> 27:35: execution error: Atom Helper got an error: Application isn’t running. (-600)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...507 completed.

[Process completed]

### Steps to Reproduce

1. press command+F7 to build and run the code
2. the programs runs
3. the program terminates and the user is prompt to press a key to go back to Atom editor

**Expected behavior:** The first times I used Atom the terminal used to be close with success.

**Actual behavior:** Now the terminal is not closed automatically after the program terminated and I press any key to continue.

### My Atom version:
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by 50Wliu** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
