### ISSUE TITLE
Custom build with modified atom.sh doesn't work?

### ISSUE THREAD

**Issue by jaredreich** [atom/atom#13379]
I tried doing a custom build by cloning and then modifying atom.sh, changing the application name to "Atom2.app" and the settings folder to ".atom2", but none of the atom.sh settings persisted. It was still created as "Atom.app" and the settings folder remained ".atom".

Can anybody point me in the right direction?

The main reason for doing this is to have multiple separate instances of Atom running on one machine, all using different setting folders and being recognized as different apps from the OS.

Thanks very much.

**Comment by ios122** [comment]
the key is at   ./script/lib/package-application.js

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
