### ISSUE TITLE
Active tab not showing in tabs

### ISSUE THREAD

**Issue by pptyasar** [atom/atom#13371]
When there is too many tabs in atom. Current active tab is not highlighted . In sublime there is one icon to scroll in tabs. But atom does not have icon or not automatically highlighting the active tab.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the issue template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
