### ISSUE TITLE
small icons missing after update to latest version - showing rectangles instead

### ISSUE THREAD

**Issue by jhegedus42** [atom/atom#13381]
<img width="841" alt="screen shot 2016-12-04 at 14 36 02" src="https://cloud.githubusercontent.com/assets/6671476/20866190/4fed4736-ba2f-11e6-8b37-d1094b5cfb1a.png">

Version 1.12.4 on Mac

I'm using nuclide.

What might be wrong ?

Anyone seen this before ?

Notice the rectangles instead of the icons? What might be the problem?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
