### ISSUE TITLE
file content gone

### ISSUE THREAD

**Issue by BgR8** [atom/atom#13395]
a project file content i worked on every detail is saved after electricity came back is gone. is there any solution to get contents back.

**Comment by MadLittleMods** [comment]
The file could be in `~/.atom/recovery`

Related to

 - https://github.com/atom/atom/issues/11406
 - https://github.com/atom/atom/issues/4161

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by BgR8** [comment]
i tried but it didnt
