### ISSUE TITLE
atom crashed  when i enter space or Tab in the comments, screenshot below.

### ISSUE THREAD

**Issue by 92hackers** [atom/atom#13392]
atom crashed  when i enter space or Tab in the comments, 

Atom    : 1.12.2
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

screen shot:

<img width="441" alt="screen shot 2016-12-06 at 13 35 59" src="https://cloud.githubusercontent.com/assets/5372618/20914210/f571aeec-bbb8-11e6-9b02-8755f728f64e.png">

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
