### ISSUE TITLE
Question: How to close buffer without killing it?

### ISSUE THREAD

**Issue by arnm** [atom/atom#13393]
I am used to Emacs where I can close a buffer but not kill it (meaning it is still in memory). This is useful for example when I'm running a REPL in a buffer. I would like to close/hide the buffer and quickly open it back up when I need to. How can this be done?

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
