### ISSUE TITLE
Scrolling through document is too slow

### ISSUE THREAD

**Issue by Saim-Ehsan** [atom/atom#13407]
its the issue that has been solved before but i am having this issue in the new update of atom

my atom version: 1.12.6

issue that occured before:
https://github.com/atom/atom/issues/9549

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
