### ISSUE TITLE
Dynamic text substitution for pretty symbols?

### ISSUE THREAD

**Issue by adjl** [atom/atom#13418]
Hi, a question: can Atom "replace" the presentation (display) of certain text patterns while keeping the underlying char sequences intact?

To be clear, I'm wondering if it would be possible for a package to imitate Spacemacs Clojure layer's fancify-symbols [feature](https://github.com/syl20bnr/spacemacs/blob/c788da709bb1c74344f5ab1b6f18cfdf6b930df8/layers/%2Blang/clojure/funcs.el#L12). What it does is replace instances of the `fn`, `partial`, `comp`, `#()`, `#{}` keywords and literals with the symbols `λ`, `Ƥ`, `∘`, `ƒ`, `∈`, respectively. The substitutions are done _as you type_.

To illustrate:
```clojure
;; Insertion
(fn_
(λ _
(λ [] (partial_
(λ [] (Ƥ _
(λ [] (Ƥ (comp_
(λ [] (Ƥ (∘ _
(λ [] (Ƥ (∘ #_
(λ [] (Ƥ (∘ ƒ(_
(λ [] (Ƥ (∘ ƒ(inc %) ƒ(dec %))) ; #_
(λ [] (Ƥ (∘ ƒ(inc %) ƒ(dec %))) ; ∈{_

;; Deletion

(λ [] (Ƥ (∘ ƒ(inc %) ƒ(dec %))) ; ∈{_
(λ [] (Ƥ (∘ ƒ(inc %) ƒ(dec %))) ; ∈_
(λ [] (Ƥ (∘ ƒ(inc %) ƒ(dec %))) ; ∈_{
(λ [] (Ƥ (∘ ƒ(inc %) ƒ(dec %))) ; _{

(λ [] (Ƥ (∘ ƒ(_
(λ [] (Ƥ (∘ ƒ_
(λ [] (Ƥ (∘ ƒ_(
(λ [] (Ƥ (∘ _(

(λ [] (Ƥ (∘_
(λ [] (Ƥ (com_
(λ [] (Ƥ_
(λ [] (partia_
(λ_
(f_
```

Cheers, and thanks for Atom. :)

**Comment by 50Wliu** [comment]
Yes, I believe these are called ligatures.  The easiest way to achieve this would probably be to use a font that has those ligatures (maybe try [FiraCode](https://github.com/tonsky/FiraCode))?

Also, next time you have a question please ask it on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the [Atom Slack](http://atom-slack.herokuapp.com/) instead.  Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).  On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by adjl** [comment]
Oops, sorry. :x

---
I have found a solution, and here is what I learnt:

Following the lead on ligatures, I happened upon this [thread](https://github.com/i-tu/Hasklig/issues/12). It appears that this effect is best done with a **concealer** rather than through a font (the more you know). And luckily, there already _is_ a [package](https://atom.io/packages/conceal) that does this!

Documenting this here for similar seekers.

Thanks
