### ISSUE TITLE
atom considers my fr-layout as an us/en one for keybinds

### ISSUE THREAD

**Issue by Piczel** [atom/atom#13439]
### Prerequisites

Using archlinux 4.8.11
fr-layout
Atom : 1.12.7
Electron : 1.4.12
Chrome : 53.0.2785.143
Node : 6.5.0

### Description

Atom seems to use an en/us layout for keybinds, ctrl+q acts like ctrl+a and vice-versa, same for ctrl+w/z
That has been like this for 1 or 2 updates.

### Steps to Reproduce

1. use a fr layout ?

feel free to ask me anything.

Regards,
Piczel

**Comment by 50Wliu** [comment]
> Electron : 1.4.12

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.

**Comment by sveinburne** [comment]
Same goes for me, from [`webupd8`](https://launchpad.net/~webupd8team/+archive/ubuntu/atom) repo, guess it's the same issue here !
