### ISSUE TITLE
can not close

### ISSUE THREAD

**Issue by nibnait** [atom/atom#13435]
<img width="1207" alt="2016-12-13 18 58 54" src="https://cloud.githubusercontent.com/assets/16975751/21137853/6c20d56a-c166-11e6-8fd7-d50003fd200f.png">

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
