### ISSUE TITLE
Atom can not select all the strings marked with a regular expression

### ISSUE THREAD

**Issue by iisimpler** [atom/atom#13433]
In sublime, I can select all the strings marked with a regular expression  by click the button `Find All` (shortcut key is `atl + enter`), but unfortunately the atom can not complete this function in the current version 1.12.7. 

I hope atom will has this feature very much.

**Comment by lee-dohm** [comment]
Thanks for taking the time to contribute!

Atom already has this feature. If you open the Find and Replace panel with <kbd>Cmd+F</kbd> on macOS or <kbd>Ctrl+F</kbd> on other platforms, search for a pattern and then press <kbd>Alt+Enter</kbd>, all matches will be selected. We just don't have a button for it because we want to save space for smaller screens.

Thanks again!

**Comment by iisimpler** [comment]
I'm so glad to hear that atom already has this feature.

Thanks for your reply.
