### ISSUE TITLE
Shortcuts incorrect Keyboard layout

### ISSUE THREAD

**Issue by arctiq1** [atom/atom#13432]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [no idea...] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

After the latest update the shortcut ctrl-z does not work - instead I need to press ctrl-y on a qwertz keyboard. The letters z and y work correctly otherwise. Using an on-screen keyboard the layout seems to switch qwertz->qwety but letters still work correctly while the shortcut doesn't.

Reverting to 1.23.5 fixes the issue.

### Steps to Reproduce
On a qwertz keyboard
1. Update to Atom 1.12.7  
2. Do something
3. Press ctrl-z

**Expected behavior:** [What you expected to happen]
undo...

**Actual behavior:** [What actually happened]
literally nothing. The shortcut is mapped to ctrl-y instead.

### Versions

```shell
arctiq@arctiqpc pkg $ apm --version
(node:6770) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.14.1
npm  4.0.3
node 7.2.1
python 3.5.2
git 2.10.2
arctiq@arctiqpc pkg $ atom --version
Atom    : 1.12.7
Electron: 1.4.12
Chrome  : 53.0.2785.143
Node    : 6.5.0
arctiq@arctiqpc pkg $ uname -a
Linux arctiqpc 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```
OS: Arch linux

**Comment by 50Wliu** [comment]
> Electron: 1.4.12

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

---
Multiple users have confirmed that uninstalling and reinstalling from https://atom.io fixes the issue.  Whatever distribution you're using from the AUR is causing this bug.
