### ISSUE TITLE
for golang "go to declaration" dont work

### ISSUE THREAD

**Issue by Menogus** [atom/atom#13445]
when i step on some function and press in menu "Go to Declaration" - nothing happend :(

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by kenorb** [comment]
See: #9034
