### ISSUE TITLE
ctrl-z doesn't undo anymore

### ISSUE THREAD

**Issue by 47bytes** [atom/atom#13448]
ctrl-z doesn't undo anymore but ctrl-y does now.
My keybindings are set to ctrl-z
![Keybindings](http://i.imgur.com/aBZdlTn.png)
My keymap file is empty.

The issue persists if I run atom in safe mode.  
I also deleted my .atom folder and the issue is still there.

I'm runnning atom on arch linux

```
$ atom --version
Atom    : 1.12.7
Electron: 1.4.12
Chrome  : 53.0.2785.143
Node    : 6.5.0
```

Unfortunately I cannot tell you how to reproduce the issue because it was all of a sudden there (I didn't update atom, I didn't reboot my system, I was working on a project and all of a sudden ctrl-z didn't work anymore).  
In any other program ctrl-z still works so it's not a system wide problem.

**Comment by Ben3eeE** [comment]
> Electron : 1.4.12

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.
