### ISSUE TITLE
Popular "linter" package does not show up when searching for packages

### ISSUE THREAD

**Issue by adrian5** [atom/atom#13454]
When searching for `linter`, the core package enabling other linters does not show up. Since these packages don't appear to pull it in as a dependency (and don't bother mentioning that you even need it), this feels like an oversight. I would have expected it to be the very top result.

https://atom.io/packages/linter

**Comment by thomasjo** [comment]
Thanks for reaching out!

We have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.
