### ISSUE TITLE
International layouts: ctrl-{smth}

### ISSUE THREAD

**Issue by feakuru** [atom/atom#13461]
Running latest Atom on Xubuntu 16.04, when switching to Russian kb layout, ctrl-c and other ctrl-modified keys stop resolving to the commands needed.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
