### ISSUE TITLE
Disturbed layout

### ISSUE THREAD

**Issue by scazzy** [atom/atom#13477]
Reproduce:
1. Clicked on `Uncommited changes ` in left panel.

Tried to resolve by:
a. Resizing atom, toggling full-screen
b. Clicking other tabs and options, toggling other panes

![image](https://cloud.githubusercontent.com/assets/1681586/21353128/ad95aaf0-c6ea-11e6-87ad-9f954cd715c1.png)

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [Nuclide](https://github.com/facebook/nuclide), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by scazzy** [comment]
Thanks @50Wliu
