### ISSUE TITLE
Size grip on the main window

### ISSUE THREAD

**Issue by mika76** [atom/atom#13478]
I think a sizing grip on the main window would be great. I'm not sure where this great usability feature has disappeared lately with apps, but it's so much easier to grip a block then a corner...

Atom version: 1.12.7

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by mika76** [comment]
But it's a feature request - not a bug report...?

**Comment by mika76** [comment]
Might I add that your own rules state that I can use the template "if I like"...

From https://github.com/atom/atom/blob/master/CONTRIBUTING.md#suggesting-enhancements
> When you are creating an enhancement suggestion, please include as many details as possible. **If you'd like**, you can use this template to structure the information.

... and what more do you need except the version number, which I supplied?

**Comment by 50Wliu** [comment]
Yes, we accept that template as well as the default one.  **All** issues require the template to be filled out.
