### ISSUE TITLE
DeprecationWarning while installing thru apm in Linux (Arch)

### ISSUE THREAD

**Issue by ron4stoppable** [atom/atom#13476]
Node produces a warning to use os.tmpdir instead of os.tmpDir while installing the packages manually from apm.

`DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

---
System: Arch Linux

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.
