### ISSUE TITLE
Replacing project folder from CLI in open atom editor window

### ISSUE THREAD

**Issue by dimitrieh** [atom/atom#13483]
### Proposal

open a project folder within an already open atom editor window while automatically removing the existing project folder it had open from the CLI?

`atom -a .` only adds the current project folder

I want to replace it

*please close if already possible*

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
