### ISSUE TITLE
Atom.io spaces are too wide

### ISSUE THREAD

**Issue by somethingedgar** [atom/atom#13484]
Ever since I downloaded Atom I noticed the spaces being wider than usual and I've tried googling the problem but nothing works. It's really annoying. Its not only in the code editor but in theory typing box. How can I fix this?
![screen shot 2016-12-21 at 10 57 08 am](https://cloud.githubusercontent.com/assets/20056979/21402201/51fd0fa8-c76c-11e6-9cb9-d45be6d2e3a3.png)
![screen shot 2016-12-21 at 10 57 39 am](https://cloud.githubusercontent.com/assets/20056979/21402203/5219a15e-c76c-11e6-94ae-d485ac4146ec.png)
![screen shot 2016-12-21 at 10 57 20 am](https://cloud.githubusercontent.com/assets/20056979/21402202/521788ce-c76c-11e6-8149-4f5d55eab30d.png)

**Comment by mnquintana** [comment]
It looks like your font family is set to a typeface that doesn't exist on your system, so it's falling back to a non-monospace font, which just Gets Weird (Atom only supports monospace fonts). You'll need to set your `Font Family` to a monospace font on your system (that field is case sensitive though, so `roboto mono` won't work if the font name is actually `Roboto Mono`). Hope that helps!

However, because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
