### ISSUE TITLE
"Open with atom" context menu action should not open a new instance of the editor

### ISSUE THREAD

**Issue by alittlerabbi** [atom/atom#13488]
Using the "Open with atom" context menu shortcut, it can be a little frustrating when a new instance of atom has to start up just to see the contents of a file. True, i could drag the file into the current editor window, but usually i'm on another screen, or in a foreground explorer window somewhere... Seems to make sense that opening a new editor should happen via this context menu action (and should continue to be a user action from within atom or from the taskbar/application icon).

i'm writing of the behavior as it is in Windows 8 (Atom 1.12.7). i'm not sure if this behavior is the same on other OS's. Also, the system settings for enabling the context menu should all be checked on:
![open-with-atom-system-settings](https://cloud.githubusercontent.com/assets/12688631/21417992/51a8597e-c7ec-11e6-9632-44c827b21635.gif)

**Current Behavior (using the "Open with atom" context menu):**
1. Open a file from one directory. Then open another file in a neighboring directory. Notice how the two tabs are within the same editor, but only the contents of the first directory make it into the tree-view:

![open-with-atom-neighboring-files](https://cloud.githubusercontent.com/assets/12688631/21417942/e09c3d86-c7eb-11e6-878e-923709b3128e.gif)

2. Open a file or directory in atom. Then open another neighboring/parent/child/or even distant directory. Notice how the target is opened in a new instance of atom:

![open-with-atom-neighboring-directories](https://cloud.githubusercontent.com/assets/12688631/21418025/7dae893a-c7ec-11e6-88ae-3e447e6254a2.gif)

i realize that this is probably trivial to implement. All that's required is "-a" being inserted into windows registry value for the atom cli interaction. i modified src/main-process/win-shell.coffee and tested a build... and it works.

**Suggested Behavior (using the "Open with atom" context menu):**

![open-with-atom-suggested-behavior](https://cloud.githubusercontent.com/assets/12688631/21418055/ae712e6a-c7ec-11e6-947f-1285e0db9908.gif)

**Comment by lee-dohm** [comment]
Thank you for your submission!

I have passed along the information to the maintainers team, for review after the holidays have passed. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. 

I've also referenced this in our tracking issue #10517 where we're collecting various problems with Atom's launch story in general to make future improvements.
