### ISSUE TITLE
Doesn't render compound emoji

### ISSUE THREAD

**Issue by odedharth** [atom/atom#13498]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom doesn't support the [new emojis](http://www.macworld.com/article/3138106/ios/check-out-every-single-new-emoji-in-ios-102.html#slide4) that were released recently. 
### Steps to Reproduce

1. Enter the[ emoji 👨‍⚕️](https://www.evernote.com/l/ADme4QjNScdIGJYokhtj_ik6c1DnI2x8iPQ)  (a compound emoji consisting of 👨 and ‍⚕️)

**Expected behavior:** [What you expect to happen]

https://www.evernote.com/l/ADme4QjNScdIGJYokhtj_ik6c1DnI2x8iPQ

**Actual behavior:** [What actually happens]

https://www.evernote.com/l/ADkQ5MNddFxNCqQ642TxhdNdgQmI1nU4uSA

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

I'm entering the emoji on the macOS 10.12.2

**Comment by Ben3eeE** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13360. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by odedharth** [comment]
@Ben3eeE Got it, and subscribed the original. Thanks!
