### ISSUE TITLE
Feature Request "New folder" option

### ISSUE THREAD

**Issue by MandarSant** [atom/atom#13495]
Feature request for New folder option in file menu it will save time insted of creating new folder at desired location ,it can be created directly from the editor and desired location link can be given from command pallet with filename.extension

**Comment by chriswburke** [comment]
This currently exists in tree view

**Comment by lee-dohm** [comment]
Thanks for reaching out!

We require [the template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

**Comment by MandarSant** [comment]
@chriswburke u r talking about to create folder in project folder but i am talking about creating main project folder

**Comment by MandarSant** [comment]
@lee-dohm  should i again submit feature request?

**Comment by lee-dohm** [comment]
@MandarSant it does sound like this is something that Atom already does and adding another menu item to an already crowded menu isn't something that we're going to do lightly. But perhaps I'm not understanding what you're suggesting, that's why we need you to fill in the template if you decide to submit this again.

**Comment by MandarSant** [comment]
@lee-dohm  i am talking about creating main project folder but atom can create sub folder in project folder and this option can be added to file menu
