### ISSUE TITLE
[wish-list] Can atom have some standard infrastructures like quickfix window ?

### ISSUE THREAD

**Issue by skywind3000** [atom/atom#13502]
I was a vim/emacs user before. after switching from vim to emacs I found the most unaccaptable thing is emacs is lack of standard infrastructures, after switching from Emacs to Atom I found same problem.

May I have a chance to explain why standard infrastructures are important to an editor ?

Let me take emacs as an example:

Emacs is lack of standard infrastructures like quickfix, jumplist, buflisted, preview window etc. Yes, I know elisp can implement such things. but once again, no standard. You can implement your own one, but no package will use it. You can't modify every single package yourself to get corresponding experience. Every package in emacs implement their own quickfix window, so when I build my project or run grep, or search a tag, many different windows are open. many different buffers are created. But Vim got standard quickfix, preview window , jump list and provide corresponding API to plugins. Many plugins in vim work with them. Compilation and grepping and tag searching plugins will all display them result in quickfix window and other plugins will highlight my source code by analyzing the content in quickfix they are fully cooperative. But in emacs each one has their own implementation just like many fragments. I was tired from swithing buffers and windows and killing many outdated buffers. In vim I never feel it like a burden.

Now I am using Atom as my main editor, I even write [a package](https://atom.io/packages/atom-shell-commands) for Atom which has more than 5000+ downloads. I found the same problem in both Emacs and Atom: Each packages are trying to implement their quickfix window, too many fragments. A lot of different quickfix/location list like panels from different packages occupy my screen space, I have to keep closing or folding newly open panels again and again, some of them are still buggy or have limitation (atom-message-panel).

If Atom can provide a standard quickfix window / location list / preview window , packages will work with them and get cooperative. Compilation result can be display in quickfix window in realtime, tag result can display in quickfix and so does grep result, linting result. Some packages analyse data from it. And most important thing is people can get corresponding experience from different packages in Atom.

Or at least, have a tab manager in the bottom panel, each package can use a tab in the bottom panel. not pile up. We can open a quickfix window and a mini terminal and a manual help window in different tabs in the bottom panel at the same time. Now if I am using two packages which will both display a panel in the bottom of the window, my workspace is totally messed up.

**Comment by JonasT** [comment]
Debuggers have the same problem in Atom. As far as I have seen, everyone just implements their own plugins for that from scratch.

Why not have a default package for this for which then everyone else implements an API? Having more standardized default ways of doing things would certainly help everyone a lot. (both the people implementing it which don't need to redo as much, and users who get a more coherent experience between different language plugins)

**Comment by skywind3000** [comment]
Sublime has a output panel on bottom.

**Comment by JonasT** [comment]
Ok maybe we should try to make a list of useful things (if you don't mind me doing this in this ticket) which Atom should preferably try to do in a more central, directed manner with officially chosen plugins to handle this instead of everyone rewriting it again and again.

Here is what I gathered from the comments so far:

- Quickfix error window / unified output panel on the bottom for running programs or debuggers
- Jump list
- Debugger UI integration (like https://atom.io/packages/dbg but preferably one officially recommended package, similar to the current official linter integration or autocomplete integration)

**Comment by lee-dohm** [comment]
Thanks for taking the time to contribute!

I have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. 

This is definitely something that we are looking at for the future. If you're interested in giving more detailed design feedback to the development team for various items that you feel should be in this "base UI primitives" collection, please feel free to discuss and present them on [Discuss, the official Atom message board](https://discuss.atom.io). I'll keep an eye there and ensure that it all makes it back to the development team.
