### ISSUE TITLE
When you have Atom running on Mac OS X Mavericks or Sierra and choose Restart, it will prevent the restart

### ISSUE THREAD

**Issue by jianlin** [atom/atom#13509]
I am using Atom 1.12.7 
On Mavericks, it will block the Mac's restart by showing a dialog that says Cancel or Try Again.
On Sierra, it will show that same dialog (about cannot restart), but will restart _anyway_

(note that nothing was edited, meaning there is no "unsaved content" so restart should not be blocked).

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
