### ISSUE TITLE
Zoom In  Operation make spell-checker  enable  after spellcheck toggle

### ISSUE THREAD

**Issue by epirus** [atom/atom#13501]
Atom Version  1.12.7 on Mac OS Sierra 

Cmd + +/- Shortcut will make spellcheck  enable ,After I toggle spellcheck.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
