### ISSUE TITLE
Freeze...

### ISSUE THREAD

**Issue by atao** [atom/atom#13513]
Atom freeze...
All is blocked...
I've the latest version on Windows 10.

**Comment by mnquintana** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
