### ISSUE TITLE
Atom not responding after hitting return key.

### ISSUE THREAD

**Issue by bbush91** [atom/atom#13522]
The only time it seems to lock up though is on this line of code:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional/EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

If  I try to hit the return key to move this line of code down in atom, it locks up. No other lines (code or no code) seem to have this issue and the return key works as normal. 

Things I have tried are:
- install updates
- restarting atom
- quitting atom completely
- restarting my computer
- testing the return key on this line of code in other files (same result)

I have a base model 2015 macbook pro retina.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
