### ISSUE TITLE
Any support on symbol jump?

### ISSUE THREAD

**Issue by m1911star** [atom/atom#13551]
### Description

Any support on symbol navigation ? I have tried some other addons, but can't help. 

Would you like to add native support navigation on current workspace?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
