### ISSUE TITLE
Using "Open with Atom" on files from same folder results in multiple windows

### ISSUE THREAD

**Issue by jjensson** [atom/atom#13570]
This bug was reproduced by a moderator at Atom and he asked me to file this bug report.

### Description

In Windows 10 Home 64bit, with Atom closed, choosing multiple files (HTML, CSS) in the same folder in explorer, and "open with Atom" results in a mess of differently sized Atom windows with partly redundant tabs.

### Steps to Reproduce

1. Atom should be closed.
2. Select multiple files (HTML, CSS) from the same folder in explorer.
3. Context menu, "Open with Atom"

**Expected behavior:** Atom should open a single window

**Actual behavior:** Atom opens multiple windows

**Reproduces how often:** 100%

### Versions

Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5

Windows 10 Home 64bit, current version

**Comment by damieng** [comment]
Unfortunately the way "Open with" works on Windows it fires off a command for each individual file selected rather than one command with all the files which makes this kind of interaction fraught with issues.

If you want to do this on a regular basis I'd recommend following the steps in https://github.com/atom/atom/issues/8222#issuecomment-218530819 which shows you how to setup Atom in the "Send to" menu of Windows Explorer which supports a single application being given all the files.
