### ISSUE TITLE
The editor is not responding.

### ISSUE THREAD

**Issue by ravid7000** [atom/atom#13580]
The editor is not responding when file is changed externally. I'm using grunt to compile scss. When I compiled scss and return back to atom window, it stop responding and I need to force close it.
![screen shot 2017-01-10 at 6 34 33 pm](https://cloud.githubusercontent.com/assets/16535293/21807182/90591d8a-d763-11e6-9785-52625a72dadd.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
