### ISSUE TITLE
Windows 64-bit version

### ISSUE THREAD

**Issue by modulexcite** [atom/atom#13595]
Hi,

Thank you for an excellent tool; life won't be the same without it.
I no longer see an option to download 64-bit version of Atom for Windows going back to version 1.12.7 production release even though the `ReadMe` section does mention it under the __Installing__ section, however I do see 64-bit version for beta versions such as 1.14.0-beta0.
Will atom no longer be distributed as a 64-bit version?

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

The 64-bit WIndows version was added in Atom 1.14.

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by modulexcite** [comment]
Thank you for the information.
