### ISSUE TITLE
Search in Directory does not update the directory to search in when opend with shortcut

### ISSUE THREAD

**Issue by lkappeler** [atom/atom#13603]
### Description

If I select a directory, right click to a folder and select "Search in Directory" the selected directory is added to the filed "File/directory pattern."... 
If I select a directory and use the shortcut "cmd + shif + f" to search in a directory the selected directory doesn't gets added to the "File/directory pattern." field.

### Steps to Reproduce

1. Select a directory with left click
2. Toggle shortcut  "cmd + shif + f"

**Expected behavior:** The selected directory should be added to the "File/directory pattern." field as it happen when using the context menu.

**Actual behavior:** The selected directory doesn't gets added.

**Reproduces how often:** Every time.

### Versions

Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
OSX: 10.11.6

**Comment by lee-dohm** [comment]
Thanks for reporting.

When pressing <kbd>Cmd+Shift+F</kbd>, we don't have enough context to be sure that the selection of the directory in the tree view was intended to be associated with the execution of the command via the key binding. Even if we used the fact that the Tree View is focused as an indicator, there are many situations where the Tree View will be focused and someone's intention is not for <kbd>Cmd+Shift+F</kbd> to include the selected directory in the filter pattern. The only clear indicator of someone's intention that the directory be included in the filter pattern is when they right-click it and select "Search in Directory".

Because we feel that this suggested change would cause more confusion than it would help speed things up for people, we're not going to implement this change.

Thanks again for reaching out!
