### ISSUE TITLE
Rename, reveal in tree view, and show in finder with split files can affect the wrong split 

### ISSUE THREAD

**Issue by feakuru** [atom/atom#13617]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I open 2 files in horizontal split and try to rename (RMB on file tab -> "Rename") the right one, it shows the name of the left one and renames it, not the right one.  Reveal in tree view and show in finder are similarly affected.

### Steps to Reproduce

1. Open two files
2. Drag one of them to the right until editor highlights a right split for it
3. Focus the file on the left.
3. Right-click the file on the right and try to rename it.

**Expected behavior:** a pop-up appears with an input box for renaming the "right" file

**Actual behavior:** a pop-up appears with an input box for renaming the "left" file

**Reproduces how often:** was able to catch it once

### Versions

Xubuntu 16.04
atom v6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

### Additional Information

*none*

**Comment by feakuru** [comment]
update: i seem to have incorrectly understood the nature of the issue. the renaming of the wrong file happens if the wrong tab is active. however, i still believe that the behaviour discovered is faulty and am not closing the issue.

**Comment by 50Wliu** [comment]
Thanks @feakuru, confirmed.  I've updated your reproduction steps with the extra information in your update.  Looks somewhat related to #13398.

**Comment by jeffreyscottfrench** [comment]
I'm also experiencing this (Atom 1.18.0 on MacOS 10.12.5) - contextual menu from right-click appears over the click point, not the active tab. Right click should activate the tab underneath the click, or not display options that can't be performed on an inactive tab (as it does when right-clicking elsewhere in the top of an open pane with tabs). Thanks!

**Comment by rsese** [comment]
Updating the issue title and body since the bug includes Reveal in Tree View and Show in Finder 
 x-ref: https://github.com/atom/atom/issues/16586

**Comment by damieng** [comment]
Part of the problem here is that these menu options do things like;

`tree-view:reveal-active-file` 
`tree-view:show-current-file-in-file-manager`

And the active file is always the one with the cursor, not the one you clicked the menu on.

We have some other limitations here with the right-click menu such as if you're not in a file (e.g. in search results) then you won't see these context menu options no matter what you right click on.  Basically the menu's contents are controlled by the current active file, not by the context menu target.

Options are

* Make the right menu button for tabs be completely based on the target - this is most likely what people expect but is a larger piece of work and will involve new commands etc.
* Make the current 'hide-half-the-menu-except-on-the-active-window-tab' which we use on other tabs in the split pane also apply to other split panes.  Less useful but consistent with what we do today and is doable in the time we have.
