### ISSUE TITLE
Atom crashed when I add a certain directory into the project

### ISSUE THREAD

**Issue by yuliji** [atom/atom#13637]
### Description

Everytime after I added one of my project by menu-> File -> Add project folder, Atom crashes.

### Versions

1.13.0 x64 on OS X El Capitan, Version 10.11.6

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
