### ISSUE TITLE
keybinding use-selection-as-find-pattern

### ISSUE THREAD

**Issue by Si7ius** [atom/atom#13638]
In version 1.13.0-beta8.
If I want to find selected word first I need to push `Ctrl-f` and after that `Ctrl-e`.
Before it was done by pushing once `Ctrl-e`. Can you return this option?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
