### ISSUE TITLE
Snippet not working

### ISSUE THREAD

**Issue by mcocdawc** [atom/atom#13641]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I try to write a snippet for a TeX file.When I start to write`$in_R` the following snippet is not working:
```
'.text.tex.latex .string.other.math.tex':
    'in_R':
      'prefix': 'in_R'
      'body': "\\\\in \\\\mathbb{R}"
```

On the other hand, if I am not in math-mode in LaTeX everything works fine with this code:
```
'.text.tex.latex':
    'in_R':
      'prefix': 'in_R'
      'body': "\\\\in \\\\mathbb{R}"
```

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS is Ubuntu 16.04 LTS

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lee-dohm** [comment]
Thanks for contributing!

This doesn't appear to be a bug but more of a question about how to get a particular snippet to work in a specific way. Unfortunately, I don't use TeX or the [language-latex package](https://atom.io/packages/language-latex) (I assume that's the package you're referring to here), so I have no way of reproducing this problem. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members (including ones that use TeX regularly) that should be willing to point you in the right direction.
