### ISSUE TITLE
Correct PUG-Filters incorrectly marked as syntax--invalid and syntax--illegal

### ISSUE THREAD

**Issue by karland** [atom/atom#13648]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:

...

### Description

Correct PUG-Code with filters defined at [PUG filters](https://pugjs.org/language/filters.html) incorrectly marked as `.syntax--invalid` and `.syntax--illegal`

![2017-01-18 11 35 28](https://cloud.githubusercontent.com/assets/4803370/22061094/c1171844-dd73-11e6-8f00-89e1a97c0075.png)

### Steps to Reproduce

1. Type into any `.pug`-file:

```PUG
div
  :markdown-it(html typographer plugins=['markdown-it-sup', 'markdown-it-deflist', 'markdown-it-attrs'])
```

and see wrong syntax-highlighting.

### Versions

```bash
Microsoft Windows [Version 10.0.14393]

$ atom --version

Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [language-pug](https://atom.io/packages/language-pug) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
