### ISSUE TITLE
libXss.so.1 error on Fedora 25

### ISSUE THREAD

**Issue by christiano** [atom/atom#13650]
Hello,

There is an error with libXss.so.1 when trying to update to Atom 1.13 RPM on Fedora 25. 

When using --nodeps option, it works fine:

rpm -Uvh --nodeps atom.x86_64.rpm

Thanks

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
