### ISSUE TITLE
The Enter key doesn't work when I try to create whether file or folder

### ISSUE THREAD

**Issue by AbirkulovSherali** [atom/atom#13655]
I use the latest version of Atom Code Editor. Today I found out that while creating whether file or folder the Enter key doesn't fire. When I typed the file name and tried to press Enter nothing happened. But if I write text in any file the Enter key works perfectly. What is the problem?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
