### ISSUE TITLE
Adopt Sublime Text's handling of punctuation at the start of alt-left/right

### ISSUE THREAD

**Issue by daviddoran** [atom/atom#13651]
### Description

Atom alt-left/right and alt-shift-left/right (skip over or select word) should ignore certain punctuation characters in front of the cursor. This makes it easier to select parts of a JavaScript property chain, for example.

### Steps to Reproduce

Tab through this text in Atom vs. Sublime Text:

    this.props.horse.cart.battery.staple

Tab through this text in Atom vs. Sublime Text:

    this.props.horse.cart['battery'][staple]

Screencast showing Sublime Text vs. Atom behaviour:
https://www.youtube.com/watch?v=qovtU8MIygo&feature=youtu.be

**Expected behavior:**

In the first example when you start a selection before a period Sublime Text includes the period and continues to the next punctuation character. In the second example Sublime Text also skips over `['` at the beginning of the selection.

**Actual behavior:**

Atom stops at every punctuation character.

### Versions

Atom 1.13.0 x64 Mac

**Comment by lee-dohm** [comment]
I'll bring this to the dev team. It is unlikely that we will replace the current behavior, though we may add new commands that behave in the way this specifies.

**Comment by lee-dohm** [comment]
I reviewed this with the development team and they agree that it would be a nice option to have. On the other hand, this is not something that we will get the chance to work on any time soon. Because we treat the open issues list as our backlog of what we will be working on, I'm going to close this.

We would be open to accepting a well-crafted pull request that implements new commands for these movements, so I'll mark this with `help-wanted`.

**Comment by a00958821** [comment]
Hello, im new here but i would like to help with this feature
