### ISSUE TITLE
Atom Crashes Every Several Minutes.

### ISSUE THREAD

**Issue by TomerHeber** [atom/atom#13675]
Hi Atom keeps crashing every several minutes.

I'm using Windows 10 x64.

Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Attaching some relevant files. Unfortunately, the dump seems to be outdated - last time it was modified was 9 days ago.

[dump.zip](https://github.com/atom/atom/files/721376/dump.zip).

Please let me know if any additional details are required.

Thanks,
Tomer.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
