### ISSUE TITLE
Losing current tree view on cancelled large file

### ISSUE THREAD

**Issue by remibreton** [atom/atom#13670]
### Description

When Atom is cancelled while processing a large file, it restarts, and loses the current tree view in the process.

Combined to the fact that toggling the tree view using `View` > `Toggle Tree View` does nothing (read: no error or warning) when you have no project folder added, this behavior is confusing and frustrating.

### Steps to Reproduce

1. Opening a large file.
2. Continuing at Atom's prompt that the system may be unresponsive.
3. Cancel when Atom prompts if I want to continue, effectively shutting down Atom.
4. Atom restarts, and loses my previous tree view.

**Expected behavior:** Atom restarts, preserving my current tree view.

**Actual behavior:** Atom restarts, with the tree view pane closed.

**Reproduces how often:** Every time Atom closes due a large file being opened, then cancelled.

### Versions

- Atom : 1.13.0
- Electron : 1.3.13
- Chrome: 52.0.2743.82
- Node: 6.5.0

### Additional Information

File size seems irrelevant.

**Comment by lee-dohm** [comment]
Do you have an example file that reproduces the problem you're experiencing?

**Comment by remibreton** [comment]
Unfortunately, the file I used contains confidential client data. It was 65Mb.

**Comment by lee-dohm** [comment]
Can you tell us anything else about the file? What file type? Does it consist of long lines (greater than X number of characters)? etc

**Comment by remibreton** [comment]
Yes, of course.

It was a CSV. There was a great deal of lines (~600k) but the lines themselves were relatively short (I'd say around 100 characters per line).

There was no empty line, and every line was properly formatted in CSV (using `,` as a delimiter and `"` as enclosure).

Opening this file in Atom was a mistake. My macOS associated `.csv` extensions with Atom. I wanted to open it in Excel or Numbers. Double-clicked too fast.

That's how I discovered the problem: I didn't want my atom to crash, so I let it try to open the file. When it prompted me to cancel the file opening, I did, and _then_ Atom crashed, losing my tree view in the process.

**Comment by lee-dohm** [comment]
Thanks @remibreton ... I'll see about reproducing this later this afternoon :grinning:

**Comment by adamreisnz** [comment]
@lee-dohm @remibreton 

I've tried to reproduce this, but was unable to.

1) Had a project window open with tree view expanded on several folders and in a particular scroll position
2) Opened a large (95mb) file with Atom
3) Pressed `proceed` when advised it might hang Atom
4) Waited for Atom to freeze, then pressed `close` to close the editor window
5) Re-opened the project
6) Tree view was in the same position, with the same folders open as before

This was with Atom 1.15.0-dev-8b36693 on OS X 10.11.5

I've tried it several times (one of the times it actually opened the file, but crashed when closing it).
I also tried modifying the tree view just prior to opening, but even that change was preserved.

**Comment by remibreton** [comment]
@adamreisnz @lee-dohm Thank you for looking into this!

I've made a video reproducing the issue. Hope it can help! Here: [atom-issue.zip](https://github.com/atom/atom/files/739172/atom-issue.zip).

- At 0:01, you can see that the file is 66.5Mb.
- At 0:01, my Atom version is 1.13.
- At 0:32, I click folders to confirm the editor is unresponsive, as expected.
- At 0:42, force closing opens up a new editor window on my main screen (offscreen in the video)
- At 0:54, I drag the new editor window in the video, fresh with an untitled document and no tree view.

**Comment by adamreisnz** [comment]
@remibreton thanks for the video and steps description.

I think I realise now what the problem is, but I don't think it's a bug in Atom.

So what happens is that if you only have the one window open, Atom will close it as per your request when you press the Close button. 

Then, after clicking the Atom icon again, if there are no other windows open, Atom will open the default view which is a new window with a blank file. This does not have tree view active, because there is no project or existing file open. You will find that even toggling tree view doesn't work in this state.

So what I'd recommend you to do (if you don't have it already), is use the Atom Project Manager package (https://github.com/danielbrodin/atom-project-manager/), which will allow you to quickly open existing projects (folders), which always opens up with tree view present.

This way, if you are forced to close the window and want to re-open it, you can do so with a couple of keystrokes from within the new window.

Hope this helps and clarifies. If you think this is still an issue let me know, but otherwise I would recommend we close this ticket. (cc @lee-dohm )

**Comment by remibreton** [comment]
@adamreisnz Thank you for the suggestion. I see now that I may have used Atom in an unexpected way, as far as project management goes.

That said, I've tried Atom project Manager and switching from project to project is a bit tedious for me, as I tend to switch frequently.

I'd suggest that Atom could "silently" remember the state of the tree view on add/remove project folders and loads the same view (although, closed) upon opening a new editor window. In my opinion, that would help getting feedback on opening/closing empty tree views and lost tree views on unexpected crashes.

I hope I didn't come across as negative. ❤️  Atom!

**Comment by adamreisnz** [comment]
@remibreton well, we all have our preferences of course. I think once you get used to having each project in it's own window, you will find it much easier to navigate and work with projects. Yes, I switch projects often as well, that's why I have maybe 3-4 project windows open with what I'm working on at present, and I toggle between them using CMD-\` (switch window command on mac, maybe an equivalent exists on Windows). 

The added benefit is that when searching for files, you can search within a project easily rather than searching in all your projects at once. The same goes for jumping to a file.

So I don't find switching tedious at all, and think the benefits outweigh any possible cons.

While I understand your suggestion would be useful for this particular use case and your way of working, I think most people, when they open a new Atom window, wouldn't necessarily want it to be opened with all previous folders/files. 

But I'll leave it to the project maintainers to decide on your suggestion! :+1:

**Comment by 50Wliu** [comment]
> I'd suggest that Atom could "silently" remember the state of the tree view on add/remove project folders

Now, I'd like to preface this with the warning that 1) I don't use macOS and 2) I am not familiar with how the project state serialization works.

However, https://github.com/atom/atom/pull/13564 does look somewhat relevant to this.  @remibreton would that solve your use case?

**Comment by remibreton** [comment]
@50Wliu Sure seems like it! I'll try Atom 1.14 beta ASAP.

**Comment by ungb** [comment]
@remibreton Has this issue been fixed?  I believe that #13564 is now on stable, if so, we can close this issue out! if not, we can further investigate to get to the bottom of it.

**Comment by remibreton** [comment]
@ungb Funny you ask! I'm now using Atom 1.15.0 and ran into the very exact same issue yesterday.

**Comment by remibreton** [comment]
To be clear: tree view is still resetting when the editor is closed due to hanging on a large file.

**Comment by ungb** [comment]
@remibreton there's been a few [changes](https://github.com/atom/atom/pull/14435) that has gone in that should make this situation better.  Any change this has been fixed in 1.18?

**Comment by remibreton** [comment]
@ungb I am currently using 1.18. I managed to make Atom crash while trying to auto-indent a very large file (I think), losing my tree view _again_.

This time around, I found an option in the `File` menu. It was exactly what I was looking for:

<img width="254" alt="capture d ecran 2017-07-17 a 09 11 20" src="https://user-images.githubusercontent.com/1278973/28269505-50419a50-6ad0-11e7-883b-2b4b3119e65a.png">

I don't for how long that option has been there, but kudos! This fixes everything!
