### ISSUE TITLE
Tab close button area

### ISSUE THREAD

**Issue by alexrodi** [atom/atom#13686]
Click area for close (x) buttons on tags too wide, while dealing with files with small names it is very easy to constantly close tabs wile switching from one to the other.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
