### ISSUE TITLE
Hide hidden files by default

### ISSUE THREAD

**Issue by jpike88** [atom/atom#13681]
I shouldn't have to install a package to hide hidden files...

I had to look this up to disable such a basic setting.

http://blog.lukebennett.com/2015/09/21/show-hidden-files-in-atom-sidebar/

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
