### ISSUE TITLE
Atom and git - open files in already opened window

### ISSUE THREAD

**Issue by Mezrin** [atom/atom#13684]
How to use Atom for editing of git temp files (commit messages, rebase commands etc.) without opening new window?

I found numerous feature-requests and work-arounds for this since 2013 year.
Still not implemented?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
