### ISSUE TITLE
Python autocomplete for gi.repository module

### ISSUE THREAD

**Issue by Kierek** [atom/atom#13697]
I'd really love to use Atom for my Python development needs, but I cannot get autocompletion to work for PyGObject module. I use Arch Linux and I have pygobject-devel packages installed.

On the Atom side I have autocomplete-python and python-tools plugins. PyGObject itself works fine, since I can perfectly fine run any gui program.

I experience no problems with django autocomplete which was installed the same way (python-django from Arch repo) so I guess it's some problem with atom.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
