### ISSUE TITLE
Unstable when reaching 41 lines of large text

### ISSUE THREAD

**Issue by manalj** [atom/atom#13693]
I'm using Atom on mac, and the editor becomes unstable when I reach exactly 41 lines of long lines of text. I'm editing an .md file, if that has anything to do with it.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
