### ISSUE TITLE
Atom 1.13.0 doesn't Open and Installation is Crashed in Windows 10

### ISSUE THREAD

**Issue by Aakash30Sethiya** [atom/atom#13694]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Atom 1.13.0 doesn't Open and Installation is Crashed in Windows 10]

### Steps to Reproduce

1. [Open Atom or install atom.exe]
2. [A pop up shows message with three option (1. close the program, 2. reload the program, 3. Cancel)]
3. [Choose any of them result is program doesn't work and doesn't open]

**Expected behavior:** [Open Atom Quickly as other text editor opens]

**Actual behavior:** [crashed application]

**Reproduces how often:** [2-3min]

### 1.13.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Atom is good, but it gets slow when a large project work is held on it.

**Comment by damieng** [comment]
Atom is tested (and in fact developed) on Windows 10 so there is no major incompatibility there.

We'll need more information as to why it isn't working on your specific version and environment.  Can you confirm it crashes in safe mode `atom --safe`

**Comment by Aakash30Sethiya** [comment]
nope!

**Comment by Aakash30Sethiya** [comment]
why did I alway test this in safe mode when I use normal mode could you not
test on normal mode ????

on every query you all told that please test on safe mode????

I use stable version of the atom so why I test anything on the safe mode...

I'm not here for testing or not use beta unstable version for development I
think thats your work not mine.....

**Comment by lee-dohm** [comment]
This is an official warning that your tone and demeanor in your comments is a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. If you continue in this way, you will be banned from the Atom and Electron organizations.

@Aakash30Sethiya We ask for people to try to reproduce problems in Safe Mode for multiple reasons:

1. Because Atom doesn't load community packages in Safe Mode, it is an easy way to determine if there is a problem that is definitely in Atom itself or could be because of a community package
1. Any troubleshooting process is about narrowing down the list of possibilities from essentially an infinite list to one specific cause. Whether something reproduces in Safe Mode is the first step in a several step process of elimination, kind of like a binary search if you're familiar with common computer science algorithms.
1. Safe Mode disables the execution of the `init.coffee`. This can also be the source of errors and crashes and is another clue in what may be causing any given problem.

> I'm not here for testing or not use beta unstable version for development I
think thats your work not mine.....

If we knew exactly what was going wrong based on your meager description, we would say so, but we don't. So we need to ask for more information because we haven't seen the problem you're describing before. When you say that you're having a problem but then you tell us that you can't tell us any more information because figuring out the problem is our job, that's the same as if you go into an electronics repair shop to tell them that your phone won't turn on but when they ask to take it apart to see what's wrong you say you left it at home. And then you yell at them because you're "not here for testing".

We can't fix this problem that you're having without more information. If you're unwilling to give us more information by answering questions, then we have other problems that we _can_ fix that we will work on instead. And other people that frankly treat us with more respect than you are now and [have in the past](https://github.com/atom/atom/issues/12121).

The choice is yours.

**Comment by Aakash30Sethiya** [comment]
You take my words as a wrong way, I'm not try to insult anyone, if this may
happen *I'm Sorry *for that.

But I again try to say that, I have no Idea about you testing criteria. It
was more complicated to me even to report an issue is more complicated. I
think that you may develop that on that point like when we report for any
plugin I just simple click on report an issue button and the whole details
related to you are on your mail right! like this.

I again say Sorry for that, I'm not try to insult you or any other.

I just says that I'm not a tester and I do not know how to test.

Thanks I think you understand my problem. and sorry again...

**Comment by lee-dohm** [comment]
I understand that you're not a tester. We ask questions of people who report issues, like if things can reproduce in Safe Mode, in order to get more information about what might be going wrong because we understand that people aren't professional testers :grinning: All we expect in return is that people cooperate with our process of trying to find out more about what is going wrong. We both want the same thing, to fix the problem.

So, at this point, I have to ask again: have you been able to reproduce this crashing problem when running Atom in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by Aakash30Sethiya** [comment]
sorry but I don't know how to run atom in safe mode???

**Comment by Zireael07** [comment]
@Aakash30Sethiya: Launch Atom with the command atom --safe

**Comment by Aakash30Sethiya** [comment]
and where would I type this???

**Comment by Zireael07** [comment]
The easiest way for a windows user: create a shortcut to atom (e.g. by copying the one that installation added to your start menu/desktop), add --safe after the path to atom.

**Comment by Aakash30Sethiya** [comment]
I download new version of atom which works thanks for your time and support.

Look don't take it negative but this the 4rth time when I solve atom
problem myself when you start supporting the problem is solved hence I say
that please improve this point.

Thanks again for support....
