### ISSUE TITLE
Alt+E accelerator not working on windows/mac

### ISSUE THREAD

**Issue by nishant09** [atom/atom#13702]
Electron version : 1.3.1
OS :Windows/MAC

Hi, 

I am trying to use "Alt+E" shortcut to open the Edit menu(similarly View & Help menu too) in my app. But it's not working. It doesn't open the menu. However, I've other accelerators in the sub menu which seems to be working fine. Below is the menu template. Can you tell me if this is an issue or I am not using it correctly ?

menuTemplate.push({
        label: "Edit",
        accelerator: "Alt+E",
        submenu: [
            {
                label: "Copy",
                accelerator: "CmdOrCtrl+C",
                role: "copy"
            },
            {
                label: "Cut",
                accelerator: "CmdOrCtrl+X",
                role: "cut"
            },
            {
                label: "Paste",
                accelerator: "CmdOrCtrl+V",
                role: "paste"
            }
        ]
    });

Thank you

**Comment by lee-dohm** [comment]
Thank you for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
