### ISSUE TITLE
 notification.onDidDisplay()'s cb is never called

### ISSUE THREAD

**Issue by pkpkpk** [atom/atom#13714]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Notification.onDidDisplay() is a publically documented API and does not work. A quick search through the main repo shows that the private [notification.setDisplayed()](https://github.com/atom/atom/blob/master/src/notification.coffee#L76) is never called, so the 'did-display' event is never fired. 

### Steps to Reproduce

1. 
```js
// works
atom.notifications.addInfo("hey!",{dismissable: true})
  .onDidDismiss(() => {console.log("dismissed")});

// does not work
atom.notifications.addInfo("hey!",{dismissable: true})
  .onDidDisplay(() => {console.log("displayed!")});
```
### Versions
1.13.1 x64 Ubuntu 16.04

**Comment by deprint** [comment]
The 'did-display' event is fired by the [notifications package](https://github.com/atom/notifications/blob/master/lib/main.coffee#L97).

The reason why your code example does not work is because you register the callback __after__ the package displays it. The order is wrong:

1. You call `atom.notifications.addInfo`
2. `addInfo` creates a new notification
3. `addInfo` adds the notification and fires `did-add-notification`
4. The notifications package receives `did-add-notification`, displays it and calls `notification.setDisplayed`, which fires `did-display`
5. `addInfo` returns the notification after `did-display`
6. You register your callback but the event already happened

If you need a callback for this, create a notification manually:

```js
Notification = require('atom').Notification;
n = new Notification("info", "hey!", {dismissable: true});
n.onDidDisplay ...
atom.notifications.addNotification(n);
```

`addNotification` is not part of the public API, so this looks like a documentation problem.

**Comment by pkpkpk** [comment]
@deprint Thankyou for the explanation
