### ISSUE TITLE
100% CPU on startup with opened files from $HOME folder (electron compile-cache.js, Linux)

### ISSUE THREAD

**Issue by BlueMax** [atom/atom#13724]
Hallo,
i get 100% CPU (one core) when opening files from $HOME folder (like .xinitrc). This does not happen when i copy the file to a subfolder (like $HOME/myfolder). I already deleted $HOME/.atom and $HOME/.config/Atom folders to start from scratch but without success. 
This also affects next empty Atom start (hogs CPU if the last opened file was from $HOME folder). It somehow remembers the last file (or path) even though its not opened.

Arch Linux, xfce, Atom 1.13

[![pic](http://abload.de/thumb/atm9zrpl.png)](http://abload.de/img/atm9zrpl.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
