### ISSUE TITLE
Atom v1.12.0 breaks hotkeys.

### ISSUE THREAD

**Issue by notiv-nt** [atom/atom#13728]
#### Atom v1.12.0 breaks hotkeys.
I have dvorak-qwerty keyboard https://sourceforge.net/projects/dvorakqwerty/
It means layout on dvorak, but hotkeys like on qwerty. (Ctrl + C, and ...) working well in every apps, exclude Photoshop -_-.

But atom's update from 1.11.2 (working), to 1.12.0 (not working) breaks this hotkeys.

### Steps to Reproduce

1. Install layout
2. Install atom

**Expected behavior:** hotkeys shoud work well.

**Actual behavior:** They doesn't work well =(. I have to press Ctrl + I for copy something (C on dvorak === I on qwerty)

### Versions

Windows 10

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by notiv-nt** [comment]
Facepalm, atom, going back to sublime -_-
