### ISSUE TITLE
Lag since 1.13.1

### ISSUE THREAD

**Issue by visualcookie** [atom/atom#13734]
Hi,

the recent update kinda broke the editor for me under Windows 10. It keeps freezing randomly after typing 2-3 chars and gets back after 3-5 secs.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
