### ISSUE TITLE
Cut-copy-paste shortcuts not working in russian/ukrainian keyboard layouts

### ISSUE THREAD

**Issue by notuxius** [atom/atom#13741]
ctrl-x, ctrl-c and ctrl-v shortcuts not working in russian/ukrainian keyboard layouts in normal mode - but other shortcuts like ctrl-s, ctrl-p, ctrl-g... are working in these layouts in normal mode.

OS: Manjaro 16.10.3
Atom: 1.13.1

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by Ben3eeE** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom-keymap/issues/203. This issue has already been fixed in Atom 1.14 currently in beta ✨ 

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
