### ISSUE TITLE
Error copy paste Ubuntu 12

### ISSUE THREAD

**Issue by zaqueoae** [atom/atom#13740]
Hi,

I just installed atom in a distribution of ubuntu 12. I do not know if the error is from my computer or atom, but I can not copy or paste text.

Thanks you very much

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
