### ISSUE TITLE
[Beta 1.14.0] APM or github packages and Portable mode

### ISSUE THREAD

**Issue by TigersWay** [atom/atom#13762]
Hi,
1> apm cannot be run from atom folder and need a complete path.
2> apm installs and "builds" the installed package in the not-portable user folder, for windows `C:\Users\myself\.atom`
My setup is somewhere on my D disk and works fine except that :-)
```
Windows 7 x64
Atom    : 1.14.0-beta4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
Thanks

**Comment by AndreaGriffiths11** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
