### ISSUE TITLE
Use <details> elements in releases

### ISSUE THREAD

**Issue by j-f1** [atom/atom#13779]
Please change the [release descriptions](https://github.com/atom/atom/releases) to use `<details>` elements so we don’t have to scroll through a list of every change.

For example:

<details><summary>Details</summary>

> **Markdown** works if you put a *blank line* between the start tags and the content.
</details>

**Comment by maxbrunsfeld** [comment]
This is really nice idea, but release descriptions currently don't render the same way as issue descriptions and comments; the `<details>` tag does not properly surround its content. I'll see if this can be fixed.

**Comment by AndreaGriffiths11** [comment]
Thank you for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.
