### ISSUE TITLE
Default file encoding for python interpreter.

### ISSUE THREAD

**Issue by kyleduo** [atom/atom#13771]
Is there a configuration file in Atom where I can specific the default encoding of python file?
In VSCode, I can use `settings.json` file.
<img width="638" alt="2017-02-08 2 57 44" src="https://cloud.githubusercontent.com/assets/7019092/22726745/03fe3b9a-ee10-11e6-9c30-b0e40d9e826b.png">
I what to find a way to prevent writing
```python
# -*-coding: utf-8-*-
```
in every file。
I'm using mac, The same file contains just this line code:
```python
print("中文")
```
runs correctly in both VSCode and terminal, but there will be an error when using Atom
```
SyntaxError: Non-ASCII character '\xe4' in file
```
I'm new in Python and I've google a lot but no result.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
