### ISSUE TITLE
Atom 1.15.0 Beta0 Keep Pulling updates 1.14.0 (stable channel?)

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom/atom#13773]
I just update my Atom beta to 1.15.0, but I notice that the squirrel icon won't go away. When I click in and check, I saw Atom trying to pull update 1.14.0 which I assume it's from the stable channel. No matter how may times I click install and restart, the updates just won't go away.

For that, I did a clean installation of Atom beta, just to find nothing changes as shown in the screenshot below. I wiped out everything and haven't installed any packages.

![image](https://cloud.githubusercontent.com/assets/17170199/22764405/accd397a-eebe-11e6-8496-d627722235e6.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by corydeppen** [comment]
### Steps to Reproduce

1. Confirm `atom.exe` isn't running
2. Download and install the latest [beta release](https://atom.io/beta)
3. Observe update (1.14.0) automatically downloads
4. Click Restart and install
5. Observe update (1.14.0) automatically downloads
6. Click Restart and install
7. Rinse, repeat

**Expected behavior:**

Atom is updated and doesn't show additional updates are available. Further, if it shows an update is available, it shouldn't revert to the previous stable release.

**Reproduces how often:**

Each restart produces the same behavior.

### Versions

```
atom --version

Atom    : 1.15.0-beta0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --version

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python
git 2.11.0.windows.1
visual studio 2015
```

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/atom/issues/13607.
