### ISSUE TITLE
Windows 10 1607 x64 - Atom 1.14.1 x64 - icon mismatching (bug)

### ISSUE THREAD

**Issue by ChesterCloud** [atom/atom#13798]
Hello everyone. I have installed atom 1.14.1 x64 version on my laptop with windows 10 1607 x64. Before this new Atom release I used 1.13 version. I mentioned that Atom 1.14.1 x64 does not have an icon in Windows 10 1607 x64 - Settings - Apps & Features, or in Control Panel - Programs and Features there is no an icon after Atom installation. In older releases there were Atom icons. It's not a bug, but I mentioned this changes in installation.
Below you may see this behaviour.

![1](https://cloud.githubusercontent.com/assets/13395076/22861127/07be2ec2-f133-11e6-9fed-f64119fe98f6.PNG)
![2](https://cloud.githubusercontent.com/assets/13395076/22861129/0caca0a8-f133-11e6-8294-6dc572c5a966.PNG)

**Comment by AndreaGriffiths11** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
