### ISSUE TITLE
Can atom be modified and used for commercial purpose ?

### ISSUE THREAD

**Issue by user-12345** [atom/atom#13797]
Hi there i was wondering if Atom can be modified and used for any type of commercial activity.

By modifying i mean changing any part of Atom to fit an enterprise's need.

It would be great if someone from Atom could answer this. 

Thank you,
Regards,
User-12345

**Comment by 50Wliu** [comment]
I am not a legal expert, but it appears that you can from [the license](https://github.com/atom/atom/blob/master/LICENSE.md).  However, since this issue is something that cannot be actioned upon, I'm going to close it.  If you have further questions, please create a new topic on [Discuss, the Atom forum](https://discuss.atom.io).

**Comment by user-12345** [comment]
What if i only change the styling ( color of variables and overall color ) of atom. Can i then still do that and use that version of atom for commercial purpose ?

**Comment by AndreaGriffiths11** [comment]
You may want to checkout [GitHub's logos and policy for usage](https://github.com/logos), please email support@github.com if you have further questions.
