### ISSUE TITLE
Not compiling c++ file on pressing F5

### ISSUE THREAD

**Issue by anirtek** [atom/atom#13796]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have installed Atom recently and configured it as per the specified instructions. g++ is installed in /usr/bin/ directory. But when I press F5 to compile my c++ file, its just not responding.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** Compile and run program

**Actual behavior:** No action. No compilation or execution 

**Reproduces how often:** Everytime

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
