### ISSUE TITLE
Win10 x64 - Atom_1.14.1 - Scratch on UI when fullscreen and scolling

### ISSUE THREAD

**Issue by DrkCore** [atom/atom#13799]
Editor seems to be scratched when I scroll it in fullscreen mode, just see the photo:

![20170212_201624](https://cloud.githubusercontent.com/assets/16048187/22862004/e481dd40-f160-11e6-8696-495e60033275.jpg)

**Comment by settenop** [comment]
I've just compiled and it seems that i am unable to reproduce it.
Could it be already fixed? (1.16.0-dev-c4abeba)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
