### ISSUE TITLE
Atom not read files into sub-repository Git

### ISSUE THREAD

**Issue by jR0driguez** [atom/atom#13805]
Hi, 

I'm newer with atom, but i not found anything about this (probably I don't know how find it), The thing is,
I have projects that use the same main "subfolder" example:

- App (current app)
-CommonLibrary (git repository)
-Htdocs (current app)

De _CommonLibrary_ folder is a git repo that I include into my app, but i need Read the files and In atom this appear as "node_modules" (like disabled) and the commands like "ctrl+T" for find files does not listing the "commonLibrary" files. There is some way that i can include as part of my project? I understand that atom ignore "node_modules" because we don't need read all files into that librearies, but in this case is not the same.

Thanks.

**Comment by AndreaGriffiths11** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
