### ISSUE TITLE
Fail to install some packages because not found the tree.h

### ISSUE THREAD

**Issue by Lutreer** [atom/atom#13802]
### Steps to Reproduce

1. Install a package behind aproxy `apm install project-view`
2. got an error:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | win32 | ia32
gyp http GET https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp WARN download ignoring invalid "proxy" config setting: "socks5://127.0.0.1:1080"
gyp http 200 https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: ENOENT: no such file or directory, lstat 'C:\Users\Leasong\.atom\.node-gyp\.node-gyp\iojs-1.3.13\deps\uv\include\tree.h'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Users\\Leasong\\AppData\\Local\\atom\\app-1.14.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Leasong\\AppData\\Local\\atom\\app-1.14.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.3.13" "--dist-url=https://atom.io/download/electron" "--arch=ia32" "--ensure" "--proxy=socks5://127.0.0.1:1080"
gyp ERR! cwd C:\Users\Leasong\.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

### Versions  
```
Atom    : 1.14.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

I really can't find the file:`.atom\.node-gyp\.node-gyp\iojs-1.3.13\deps\uv\include\tree.h`

**Comment by AndreaGriffiths11** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue on the [APM repo](https://github.com/atom/apm/issues) and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
