### ISSUE TITLE
Repport BUG

### ISSUE THREAD

**Issue by squattydent** [atom/atom#13814]
Hello, can help me please ?
why this ATOM Editor Error ???

![asldha](https://cloud.githubusercontent.com/assets/23291592/22926927/3ccb8376-f2e1-11e6-8984-22afeaf74e4a.JPG)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
