### ISSUE TITLE
Change the paths %USERPROFILE%/AppData/Roaming/Atom and %USERPROFILE%/.atom

### ISSUE THREAD

**Issue by stla** [atom/atom#13839]
Hello,
 I've just installed Atom on Windows, by unzipping `atom-x64-windows.zip`.

Just after I ran Atom by clicking on `atom.exe` (or after I run the package installer), Atom created the folder `%USERPROFILE%/AppData/Roaming/Atom` to put some stuff there (such as the `Cache` folder). Atom also created the folder `%USERPROFILE%/.atom`.

Is it possible to change these two paths *without admin's rights* ? The problem is that I have a limited storage at these locations (I'm using the computer of my job company and this is the policy of the company).

**Comment by AndreaGriffiths11** [comment]
Thanks for reaching out!

If you want to move the location of the `.atom` directory, you can set the `ATOM_HOME` environment variable and restart Atom. If you are required to have admin rights to permanently set an environment variable then is not possible. Since this is more of question than an issue I'm going to close it.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by jordwms** [comment]
@AndreaGriffiths11 can the `%APPDATA%/Roaming/` directory be changed to point to a different location?

**Comment by jordwms** [comment]
@AndreaGriffiths11 can the %APPDATA%/Roaming/Atom directory be changed to point to a different location?

**Comment by jordwms** [comment]
@AndreaGriffiths11 can the `%APPDATA%/Roaming/Atom` directory be changed to point to a different location?

**Comment by jordwms** [comment]
If I understand this PR: https://github.com/atom/atom/pull/5385, then it seems that setting `ATOM_HOME` will also move `%USERPROFILE%/AppData/Roaming/Atom`. I know that @AndreaGriffiths11 implied as much, but just wanted to clarify that point.
