### ISSUE TITLE
Copy/paste bug extra characters attached

### ISSUE THREAD

**Issue by liveresume** [atom/atom#13834]
Create a js file.

Use this code and copy `this.`

```js
xxx = {
  xxx: ...this.xxx.xxx.xxx
}

export default xxx
```

Try pasting it.  I get:  `..this.`

**Comment by AndreaGriffiths11** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
