### ISSUE TITLE
User keymap override not stable on MacOS

### ISSUE THREAD

**Issue by bimalkharel** [atom/atom#13841]
Hi,

On MacOS Sierra 10.12.3 and Atom 1.14.2, I set the following (tested one at a time) keymap

'body':
  'cmd-`': 'pane:show-next-item'
  'cmd-shift-`': 'pane:show-previous-item'

OR

'atom-text-editor':
  'cmd-`': 'pane:show-next-item'
  'cmd-shift-`': 'pane:show-previous-item'

The mapping works for about 10 switches and then stops working. Could you help me fix that and let me know which one is the correct mapping to use (both work)

Thanks,

Bimal

**Comment by AndreaGriffiths11** [comment]
Thanks for contributing!

I'm able to use your `pane:show-previous-item` keybinding without error. On the `pane:show-next-item` binding you want to remove the dash ie:
'body'
   'cmd': 'pane:show-next-item'

That should work without errors, since this is more a question than an issue I'm closing this. Please post to [Discuss, the official Atom message board,](https://discuss.atom.io) if you have any other questions. Thanks again :)

**Comment by bimalkharel** [comment]
Hi @AndreaGriffiths11 the actual keymap is cms-<tick_symbol_under_tilde>. Looks like Github formatting removed it. Can you test with the tick?
Thanks
