### ISSUE TITLE
Why atom doesn’t have this feature yet?

### ISSUE THREAD

**Issue by touqeerkhan11** [atom/atom#13866]
The idea is that you start working on your atom editor by logging into your account, all your working directories gets fetched from the remote server as repositories, you pick a repository or create new one, do your thing, and when you change your machine, you can start from where you left without worrying about pushing the code on git when its not ready to be commited yet.

Just like google chrome has this thing of picking from where you left when you change a device!

Wouldn't that be game changing!! is someone working on this? is there a package that does this already?

**Comment by lee-dohm** [comment]
We envisioned Atom as a more conventional programmer's editor rather than a cloud-based editor like [Cloud9](https://c9.io/). There are some packages that emphasize working on remote files like [remote-ftp](https://atom.io/packages/remote-ftp) or [Facebook's Nuclide](https://nuclide.io/). You may want to take a look at those as well.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
