### ISSUE TITLE
Proposal: User-Controlled View Locations (Workspace Views)

### ISSUE THREAD

**Issue by matthewwithanm** [atom/atom#13878]
Currently, each package that defines a UI tool is responsible for creating and managing its own panels. This means that (1) there's not consistent UI for toggling panels and (2) users don't have any control over the placement of their tools. In Nuclide, we've tackled this with a feature called “workspace views.” It has two main goals:

* Provide a way for package authors to make location-agnostic views.
* Provide containers for displaying these views.

We'd like to get this functionality into Atom core 😊

![wspv3b](https://cloud.githubusercontent.com/assets/126263/23325856/6786fd74-faad-11e6-926c-3b51838c3949.gif)

Nuclide's workspace views package is based on a lot of the abstractions and concepts already in Atom:

* It exposes an `addOpener()` API for registering model factories.
* It exposes an `open()` function for showing them.
* It creates three panels (left, right, and bottom), each with its own PaneContainer and tab bar.

This allows interop with the workspace pane container (i.e. users can move things into the main workspace when they want it to appear larger) and lends itself to adoption into Atom by extending existing APIs.

# Proposal

We propose extending the existing `atom.workspace.open()` API to support multiple “locations,” including each of the panels. `addOpener()` shouldn't require any changes, but there are some workspace-level which would be helpful to add:

### `destroyItemWhere(predicate: (item: Object) => boolean): void`

Package authors can use this to destroy all of the views they've created when their package is deactivated.

### `toggle(uri: string, options?: Object): void`

Allows toggling visibility of specific items. If a matching item is already visible in a panel, that panel gets hidden.

So far, we haven't had a reason to require inspection of the panels, so we don't have any analogues to `getPanes()`, etc. but it probably makes sense for hackability.

## Model Additions

As far as the view model goes, we followed the precedent set by `getTitle()`, `getIconName()`, et. al. and added a few optional methods:

### `getDefaultLocation?: () => string`

With Nuclide's workspace views, users decide where to place their views (as opposed to package authors specifying a location when they call `open()`). If they move the file tree to the right panel, that location will get serialized and used the next time they open the file tree. This method gives package authors to specify the default location. Allowed locations are “left-panel”, “right-panel”, “bottom-panel”, and “pane” (which corresponds to the workspace's pane container). Nuclide also has an API for registering custom locations, but we probably don't need to support this in Atom at this point.

### `getPreferredInitialHeight?: () => number`

The size of panels is controlled by users and serialized, but these two methods provide a way for package authors to provide an initial size when a panel is first shown.

### `didChangeVisibility?: (visible: boolean) => void`

This one's kinda orthogonal, but really useful. It allows models to be notified when they're being displayed so that they can make optimizations.

# Open Questions

There are a few open questions we'll need to figure out:

* What methods should be added to inspect locations and their contents?
* What theme compatibility concerns are there?
    * We only really support the big four (Atom & One Light/Dark)
* How should we deal with tabs?
    * We've vendored parts of [atom/tabs](https://github.com/atom/tabs) and create them ourselves. Should that package be updated to decorate these new panels instead?
* What language?
    * Is the doc situation solved for mixed CS/JS repos?
* What dependencies can we bring along?
    * Our current implementation uses both React and RxJS

Let the discussion begin! 😊

cc @nathansobo @maxbrunsfeld @joefitzgerald @BinaryMuse

**Comment by maxbrunsfeld** [comment]
:zap: Really great proposal; thanks for doing such a nice writeup about this @matthewwithanm! I love this feature and I want it to be in core.

My main concern is a kind of vague and conceptual - how do these new panels relate to our existing panels? Like, is there a mental model and naming scheme that we can use to think about these new panels vs the old ones?

Like currently, you can add and remove, and retrieve panels. Should `getLeftPanels()` include the new left panel, or should we consider it a different kind of object? Maybe there should be a `getMainLeftPanel()` that gets the new one, and allows you directly inspect its contents, e.g.

```
atom.workspace.getMainLeftPanel().getActiveItem()
```

Do these concerns make sense? I'm just trying to fit these into our story of how the Atom workspace works.

**Comment by simurai** [comment]
❤️  that you can move panels around.

> @maxbrunsfeld how do these new panels relate to our existing panels?

Would it be possible to extend the current [Panel API](https://atom.io/docs/api/v1.14.3/Workspace#section-Panels)? So that existing packages automatically are part of this proposal.

![panels](https://cloud.githubusercontent.com/assets/378023/23329485/ebffdff6-fb7c-11e6-8aa0-f1cd602bfa76.png)

- `Header/Top/Footer` panels stay as is
- **New**: `Left/Right/Bottom` panels would share the same space/container and get tabs.
  - Can be rearranged like in the gif above.
  - Add an option for the tab label. Maybe use the package name if no label is passed in. E.g. 👉  `[ Tree View ]` and a default initial width/height.
- **New**: `LeftEdge/RightEdge` panels. This new type of panel can be used by packages that don't want to be part of the "tabbed" panels. [tool-bar](https://atom.io/packages/tool-bar) is the only one that comes to mind. Ideally this panel doesn't take up too much space and is more meant for narrow "bars".

**Comment by simurai** [comment]
> What theme compatibility concerns are there?
> We only really support the big four (Atom & One Light/Dark)

> How should we deal with tabs?

Ideally it should look ok-ish with any Atom theme. That's probably not that easy because atom/tabs don't have much styling and every theme added their own kind of tabs. Also, the atom/tabs feel too large to be used inside panels where space is precious. Well, at least with most themes. Hmmm..

1. Adjust atom/tabs to be also used for panels. Most likely use a different class name and make them smaller by default. Downside: Themes would have to customize again, if they want.
2. Use different tabs only for the panels. Smaller and simpler (like no close button). Downside: Looks a bit odd, having two different kind of tabs. Panel vs pane. There is actually a PR open https://github.com/atom/atom-ui/pull/15 that would introduce new navs and tabs.
  ![image](https://cloud.githubusercontent.com/assets/378023/23329800/fa700772-fb82-11e6-92dd-4ac5a08b987e.png)

**Comment by nathansobo** [comment]
I'm really looking forward to this.

My comments are mostly concerned with transitioning from the existing panel API to this new approach, then I have some open questions at the end.

## Vocabulary

In the new API, we should be clear on what constitutes a **panel**. Currently, there are zero to N "panels" around each border of the window. I think we should change our narrative, so that there are **only 4 panels in Atom**: left, right, top, and bottom. Like panes, these panels can contain multiple items, but the items themselves are not considered to be "panels".

This leaves us needing new vocabulary for the case where we want to stack elements at the window edge, which is still needed for things like toolbars. I have a proposal but I'm open to others. I think we call them *headers*, *footers*, *left margins*, and *right margins*. They don't need a general name because ultimately they're just elements that we stack up.

## Changes to the existing API

I think we need to change our API in the following way to deliver a coherent narrative where a "panel" is a clearly-defined concept.

* Deprecate `add(Left|Right|Top|Bottom)Panel`. Change their behavior to add the given model/element as an *item* in the desired panel, activate it, etc. Going forward, the preferred way of adding a panel will be to use `workspace.open` as described in the body of the proposal.
* Deprecate `add(Header|Footer)Panel` and rename them to `addHeader` and `addFooter`. We'll need to continue to respect the `priority` flag to determine the stacking order.
* Add new methods: `addLeftMargin`, `addRightMargin`. These can to add an element to the left or right "edge" of the workspace. Package authors that were previously using `addLeftPanel` and friends that didn't want to be included in the new panels, which I'm assuming will be the minority, can switch to calling these to continue to be added as a stacked element.
* Deprecate `getLeftPanels` and replace them with `get(Headers|Footers|LeftMargins|RightMargins)`.

## Possible API additions

Will package authors want to interact with panel items? I can see a range of methods of varying power. The basics would just be some way of accessing the items of all panels, a particular panel, or the whole workspace.

* `Workspace` methods:
  * `getPanelItems` This would return all panel items. It is similar to the existing `getPaneItems` but for panels instead of the main panes.
  * `observePanelItems`, `onDidAddPanelItem`, `onDidRemovePanelItem` These go along with `getPanelItems` and blend in with similar workspace methods for pane items.
  * `getItems` This would return all items in the entire workspace, combining the main pane items and panel items into a single returned array. In my mind, this could supplant the proposed `destroyItemWhere` method, allowing users to loop over all items and do anything they like, including destroying some of them.
  * `observeItems`, `onDidAddItem`, `onDidRemoveItem` Similar, these aggregate observations for items *anywhere* in the workspace.
  * `get(Left|Right|Top|Bottom)Panel` This would return a `Panel` instance. `Panel`s will presumably wrap `PaneContainers`, but may warrant being their own object for the sake of this API.
* `Panel` Each panel would expose a way to interact with its items, like the workpace does currently for its pane items.
  * `Panel.getItems`
  * `Panel.observeItems`, `Panel.onDidAddItem`, `Panel.onDidRemoveItem`
  * Do we want a more fine-grained imperative API beyond workspace openers for interacting with these panel objects? Methods like `addItem`, `activateItem` etc that appear on panes? Maybe not at first.

Eventually, we may want to open `PaneContainer` as part of our public API so package authors can manipulate splits in the central container and each panel. I don't think we need to do that right now.

## Questions / Concerns

* I think we need a better name for the center of the workspace. Currently, you're proposing to call that location `pane`, but panels have panes too, so it's a bit ambigous. A good name for the part of the workspace that contains the primary content being edited or viewed would help this API I think. I don't have an idea I currently love though... "central panel"? "main pane container"?
* When you call `Workspace.open`, can you specify a location? If you do, does it take precedence over the preferred default location of the opened item? Maybe we should only ever ask the item, but there might be some use cases where the thing doing the opening expresses a preference. We currently have a `split` option which seems similar.
* It seems like there's some assymetry with toggling panel items. If I want to show a panel item, clearly what I want to do is show its containing panel and then activate that item within it. But when I want to *hide* an item, do I hide its containing panel or just destroy the panel item? If the item is the current visible tab in a panel, I can see hiding the containing panel making more sense. Otherwise toggling just switches me to another panel item which is weird.
* When you call `Workspace.open`, does it show the item if it is already visible? Would you ever want to open the same URL in multiple panels or panes within the same panel like you can with panes? If so, how would you do that?

**Comment by matthewwithanm** [comment]
Thanks for all the great responses!!

**@simurai said:**
> Would it be possible to extend the current Panel API? So that existing packages automatically are part of this proposal.

Opting in current panels automatically is doable, but tricky. They may have their own UI for toggling or resizing, or the panel and may not respond well to having its container resized. It's also a bit weird that `addLeftPanel()`, for example, may not always add the panel to the left.

**@maxbrunsfeld said:**
> Do these concerns make sense? I'm just trying to fit these new things into our story of how the Atom workspace works.

Definitely. We didn't really have to (get to?) worry about this in Nuclide but it's super important if this is going to be a core feature.

**@nathansobo said:**
> In the new API, we should be clear on what constitutes a panel. Currently, there are zero to N "panels" around each border of the window. I think we should change our narrative, so that there are only 4 panels in Atom: left, right, top, and bottom. Like panes, these panels can contain multiple items, but the items themselves are not considered to be "panels".

That makes a lot of sense to me (these correspond to Nuclide's [PanelLocation][1]). It makes more sense imo than nesting "panel" objects in some kind of uber-panel.

> Deprecate add(Left|Right|Top|Bottom)Panel. Change their behavior to add the given model/element as an item in the desired panel, activate it, etc.

By "desired," do you mean desired by the package author or user? i.e. Are panels created with the legacy API movable? This is basically what @simurai was talking about (but just for the short-term), I think, so the same concerns apply: how do they respond to resizing, do they duplicate toggle UI, etc. On the one hand, that might be a good forcing function to migrate; on the other, it might be less gross to forward the legacy panel API to sidebars instead.

> Possible API additions

This all sounds 💯. "items" is super generic, but I guess it's familiar enough to Atom devs.

> Do we want a more fine-grained imperative API beyond workspace openers for interacting with these panel objects? Methods like addItem, activateItem etc that appear on panes? Maybe not at first.
> Eventually, we may want to open PaneContainer as part of our public API so package authors can manipulate splits in the central container and each panel. I don't think we need to do that right now.

👍 Adding them after the new system is established seems like a good idea. We want to discourage manual management as much as possible but allow for hacking.

I think we'll probably also want a declarative way to do splits too so people don't have to reach to the imperative API and risk losing placement serialization or something. Either another model method or maybe just allowing `getDefaultLocation()` to return `{location: string, split: string}` or something too.

> I think we need a better name for the center of the workspace. Currently, you're proposing to call that location pane, but panels have panes too, so it's a bit ambigous. A good name for the part of the workspace that contains the primary content being edited or viewed would help this API I think. I don't have an idea I currently love though... "central panel"? "main pane container"?

I've struggled with this 😊. Originally we actually called it "active-pane" (which was probably a more descriptive name) and sometimes when I'm talking to people, I just call it the workspace. As far as the API goes, I think just calling it "main" might be good. We could also go with "document area" or something, to emphasize its normal use. It makes non-document views feel like interlopers in it, but it's also immediately grokkable.

> When you call Workspace.open, can you specify a location? If you do, does it take precedence over the preferred default location of the opened item? Maybe we should only ever ask the item, but there might be some use cases where the thing doing the opening expresses a preference.

Since the thing doing the opening is also creating the item, it could express its preference by passing it to the location (to be returned by `getDefaultLocation()`) so it seems like the only use this would have is if we wanted to allow package authors to disregard users' decisions. My gut reaction is that that's bad, but it's also easy enough to add later, so maybe start without it?

> We currently have a split option which seems similar.

Oops, I got ahead of myself 😊

Yeah, I'd like to see this move to be a suggestion from the models too. So maybe we ignore the option to `open()` for panels? In the long term, maybe it could be deprecated entirely, though you would have a better idea about how realistic that is than me.

> It seems like there's some assymetry with toggling panel items. If I want to show a panel item, clearly what I want to do is show its containing panel and then activate that item within it. But when I want to hide an item, do I hide its containing panel or just destroy the panel item? If the item is the current visible tab in a panel, I can see hiding the containing panel making more sense. Otherwise toggling just switches me to another panel item which is weird.

Totally agreed; that's how hiding works in Nuclide now (we hide the whole panel if the item's already visible).

> When you call Workspace.open, does it show the item if it is already visible? Would you ever want to open the same URL in multiple panels or panes within the same panel like you can with panes? If so, how would you do that?

Nuclide's workspace views service's `open()` [has a `searchAllPanes` option][2] just like `atom.workspace`'s. (The idea was that if we could merge it, Atom would just search the panels' panes too). Our only use case currently is with our console: you can have several instances of it, each with a different filter. (Since it aggregates messages from various sources, it's sometimes useful to split them into separate panes.) Currently, the only way to do that in Nuclide is to split an existing console, though, so I'm not sure too many people do it.

## Next Steps

It seems like we've got a pretty good road plan here 😊. What are the next steps? Do I just start hacking on a giant PR? Or is there some way to break it up?

![giphy](https://cloud.githubusercontent.com/assets/126263/23388593/e80ee0d0-fd17-11e6-801e-9467555db638.gif)

[1]: https://github.com/facebook/nuclide/blob/7baf65daad81194ef9073de3c1dcc8ba3659e938/pkg/nuclide-workspace-view-locations/lib/PanelLocation.js
[2]: https://github.com/facebook/nuclide/blob/169aae1228982d21341359577e2315944d0ff0bb/pkg/nuclide-workspace-views/lib/redux/Epics.js#L126-L131

**Comment by matthewwithanm** [comment]
Oh! I forgot to mention!

> getItems This would return all items in the entire workspace, combining the main pane items and panel items into a single returned array. In my mind, this could supplant the proposed destroyItemWhere method, allowing users to loop over all items and do anything they like, including destroying some of them.

Yeah, definitely. `destroyItemWhere()` (`destroyWhere()` [in the current Nuclide API][1]) was just meant to reduce some of the boilerplate in cleaning up [that every (view providing) package has to do][2]. Ideally (and this is kinda separate from this proposal) Atom would track which package was responsible for creating each view and automatically destroy the views when their package was deactivated. I don't know how you would track it generally, since views can be added via the global API, but it could be done with the view providers.

[1]: https://github.com/facebook/nuclide/blob/48f8e88821a5e5a50ac79674864acd6b6cb17276/pkg/nuclide-workspace-views/lib/main.js#L105-L108
[2]: https://github.com/facebook/nuclide/blob/3b33dd436e7a1380596abce7eb8087ca4cd60726/pkg/nuclide-workspace-views/README.md#cleanup

**Comment by simurai** [comment]
> @matthewwithanm Opting in current panels automatically is doable, but tricky. They may have their own UI for toggling or resizing, or the panel and may not respond well to having its container resized. It's also a bit weird that addLeftPanel(), for example, may not always add the panel to the left.

I see. Right, that could be quite messy.

Also, wow.. I haven't realized it when looking at the gif, but later tried it out in Nuclide: You can move an "item" anywhere you want (center/main, left, right, bottom), not just left/right/bottom. So also the settings-view or any file can be moved to the "sides". Or something intended to be on the sides can be moved to the center if you like more space for it. Aaaand each of those panels can be split infinitely. :scream_cat: That's really awesome and super flexible. 💯

**Comment by nathansobo** [comment]
> Are panels created with the legacy API movable? This is basically what @simurai was talking about (but just for the short-term), I think, so the same concerns apply: how do they respond to resizing, do they duplicate toggle UI, etc.

I think we should flag panels created with the legacy API and make them not resizable at the very least. Perhaps we limit movement to a similarly-oriented panel (right can move to left, top to bottom, vice versa) or eliminate movement entirely. Come to think of it, it might make sense to offer these kind of options via non-deprecated usage of the API for panels that don't make sense in certain contexts, even though it does add some complexity to the UI interaction.

> What are the next steps? Do I just start hacking on a giant PR? Or is there some way to break it up?

That is really up to you. If you can break it into smaller pieces it will be easier on us to review it and probably move in more smoothly. But if that's not possible I'm okay upgrading in one shot.

Another thought... I think you should convert any `.coffee` files in your path to non-Babel vanilla JS before making major changes to conform to our "no new CoffeeScript" policy. You can run `decaffeinate --keep-commonjs --prefer-const  --loose-default-params --loose-for-expressions --loose-for-of` to get pretty close these days. Is that something you'd be down to do as a prerequisite?

**Comment by matthewwithanm** [comment]
> I think we should flag panels created with the legacy API and make them not resizable at the very least. Perhaps we limit movement to a similarly-oriented panel (right can move to left, top to bottom, vice versa) or eliminate movement entirely.

How does the UI respond when switching from a non-resizable item to a resizable one? Having the panel change size seems a little weird, especially in the case of the bottom panel where it'll affect the tab bar position more drastically.

> Another thought... I think you should convert any .coffee files in your path to non-Babel vanilla JS before making major changes to conform to our "no new CoffeeScript" policy. You can run decaffeinate --keep-commonjs --prefer-const --loose-default-params --loose-for-expressions --loose-for-of to get pretty close these days. Is that something you'd be down to do as a prerequisite?

Sure 😊

**Comment by nathansobo** [comment]
> How does the UI respond when switching from a non-resizable item to a resizable one? Having the panel change size seems a little weird, especially in the case of the bottom panel where it'll affect the tab bar position more drastically.

Ah, yeah, good point. I still really want to find a way to integrate legacy panels into this new system though. What about auto-resizing left and right panels and just leaving empty space for top and bottom panels? @simurai any better ideas?

**Comment by simurai** [comment]
We _could_ try to override the width/height of packages but I agree with:

> @matthewwithanm Opting in current panels automatically is doable, but tricky. They may have their own UI for toggling or resizing, or the panel and may not respond well to having its container resized.

For example [platformio-ide-terminal](https://atom.io/packages/platformio-ide-terminal) changes the height of some "random" child element and not the `atom-panel`. So that would be hard to prevent. Also that package is designed to be more stand-alone with the maximize/minimize/close button and would feel awkward inside a tab.

So, yeah.. considering this, opt-in feels like the better approach for existing packages. We can convert all the bundled ones and then maybe also make issues/PRs to some popular community packages.

There are lots of "abandoned" packages and some would move from being at the bottom to be in the footer (full width) which might upset some people, but it should still stay useable and wouldn't be completely broken.

**Comment by nathansobo** [comment]
Okay, if we're going to make this opt-in, then it has implications for my proposal about what to do with the old `addLeftPanel` etc methods. We should still deprecate them, but the deprecated methods should just call `addLeftSidebar` etc.

**Comment by joefitzgerald** [comment]
I personally think that this shouldn't be opt in and existing panels should be pushed into it. This will result in an odd UX for some packages initially but if you don't do this you will essentially lose all screen real estate because it'll be panels all over the place.

We should prioritize the preservation of screen real estate over preservation of close / hide / resize behavior. It also may be possible to make the show / hide logic work seamlessly.

**Comment by nathansobo** [comment]
@joefitzgerald makes a pretty convincing argument and I agree with him. @matthewwithanm / @simurai what's your response?

**Comment by matthewwithanm** [comment]
I'm not sure I'm following…it'll be strictly better than the current situation, right? (At least some items will share a container whereas currently none do.)

imo it boils down to how much breaking existing panels matters.

**Comment by vjeux** [comment]
One thing to consider is that "find-and-replace" is using a panel. We've played with putting it in workspace view but it looks really odd. So there are cases where I think we want to keep the old behavior.

**Comment by nathansobo** [comment]
You do make a good argument that this is strictly an improvement over what we had and there may be cases where it appears odd. One challenge in this case is that making find-and-replace a footer will cause it to go full width underneath the tree view. Not sure about the implications of that. Why did find-and-replace make a bad panel?

**Comment by maxbrunsfeld** [comment]
Is the problem that `find-and-replace` does not look good if it's moved to the left or right sides? Maybe we could allow items to specify that they only work in certain panels?

**Comment by nathansobo** [comment]
And if we're worried about size snapping, I do see the drawback of the tab bar moving if you select a different panel, but I'm not convinced it's a deal-breaker interaction-wise. The value of allowing panels to specify that they *don't* resize while still being incorporated in this framework still seems like it could be worth it to me.

**Comment by vjeux** [comment]
The fact that it doesn't resize cleanly is one issue.

At a more fundamental level, the find panel is an in and out experience where most other panels are supposed to be long lived. If you already have things in the bottom panel like your console, you don't want to hide it while you are searching in the file and restore it when you are not.

IntelliJ: https://www.jetbrains.com/help/idea/2016.3/finding-and-replacing-text-in-file.html
![image](https://cloud.githubusercontent.com/assets/197597/23567296/7ebffef2-000a-11e7-8639-531b4a508105.png)

Xcode:
![image](https://cloud.githubusercontent.com/assets/197597/23567351/bfd02a98-000a-11e7-9bbd-1f03b4cdaac7.png)

Visual Studio:
![image](https://cloud.githubusercontent.com/assets/197597/23567409/f3e1ba68-000a-11e7-89d3-08dec685decd.png)

Now, there are two use cases for find and replace. The first one is inside of the current file and this should be quick and not a panel. But you may also want to search the entire codebase. In this case, in all the IDEs this is in a panel.

**Comment by nathansobo** [comment]
I just wanted to summarize some conclusions we came to on a video conference this afternoon. I really think good software depends on good narratives, and I'm pretty excited about what we arrived at.

We've decided that this proposal is really about adding a brand new concept to Atom, which we're naming "docks". The term "dock" is familiar from macOS and it connotes a kind of flexible resting place for pieces of the UI to live. Panels will still be a thing in Atom, but we'll encourage package authors to use docks if possible to offer users more control over workspace layout. For certain cases, such as interfaces requiring a fixed size or orientation or fundamental facilities such as find-and-replace, panels will remain an option.

Dock will live on the left, right, and bottom of the screen, but not the top. Top panels and headers remain available for authors wishing to add items to the top, but we've agreed that an affordance for toggling dock visibility would be a nuissance at the top of the workspace where lots of clickable affordances already live. Panels can be added at either side of a dock, with negative-priority panels appearing outside the dock and positive-priority panels to the inside.

Locations will continue to be named directionally, allowing package authors to specify a preferred location of `left`, `right`, `bottom`, or `center`. "Center" is the best name we could come up with for the main pane container at the center of the workspace.

The workspace API can be extended as needed with methods to query and manipulate the state of Atom's three docks. We'll add enough API to extend the tabs package to decorate panes within docks the same way it decorates panes in the main pane container, but iterate on the rest of the API on as-needed basis... when we do, docks will probably have methods that look a lot like methods on the workspace as a whole, like this:

```js
const dock = atom.workspace.getLeftDock()
dock.getItems() // get all items in the dock
dock.observeItems((item) => /* ... */) // observe items in the dock
dock.getActivePane().activateItem(diagnostics) // add a dock view
```

The workspace API can be extended to talk about *items in general* to abstract across items in panels and items in the center panes.

```js
atom.workspace.getActiveItem()
atom.workspace.getItems()
atom.workspace.observeItems()
// etc
```

I'm really happy about the name "dock". Props to @maxbrunsfeld for coming up with it. In a single word it really helps convey to users and package authors alike the purpose of this new feature.

**Comment by AndreaGriffiths11** [comment]
:heart: "docks"

**Comment by 50Wliu** [comment]
I believe this was implemented in #13977.

**Comment by p-boiko** [comment]
Hi!
This feature just arrived in [v1.17.0](https://github.com/atom/atom/releases/tag/v1.17.0-beta0)
But can't find how to disable it. Is it possible? Thanks

**Comment by Njke** [comment]
There are now `Window: Toggle (Left | Right | Bottom) Dock` commands in the Command Palette.

And the buttons are displayed when you hover the sides of the Editor View.

**Comment by bjmiller** [comment]
I don't mind having the unified docking available.  But, I'd love to be able to turn off that semicircular control that pops in and out.  It's very distracting.
