### ISSUE TITLE
Newbie - Atom not appearing in the Start Menu

### ISSUE THREAD

**Issue by jwakolbi** [atom/atom#13876]
I  recently downloaded and installed Atom.  It opened after it finished downloading.  However, I can't find it in the start menu, program list, and I can't make a shortcut to the desktop.  I can't even find a folder with a shortcut or program.  I just find the download file.

Is this normal?  Anyone have a solution?

**Comment by AndreaGriffiths11** [comment]
Thanks for reaching out!

The setup program will install Atom to the local user account (i.e. under %LocalAppData%), you will then add the atom and apm commands to your PATH and create shortcuts on the desktop and in the start menu. As detailed in the [installing Atom in Windows section of the Atom Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/#installing-atom-on-windows).

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by 50Wliu** [comment]
Please make sure that you used AtomSetup.exe and not AtomSetup.msi (or their -x64 equivalents).
