### ISSUE TITLE
 Unexpected character '' in grunt build. Atom adding wierd characters on Windows and showing up strange in linux console. 

### ISSUE THREAD

**Issue by danrossi** [atom/atom#13894]
I am trying to edit in Atom on windows and build on Linux. Everytime I save , the editor is adding strange characters everywhere and is hard to cleanup because they are only visible on the Linux console. 

I get errors like " Unexpected character ''" when running grunt builds. 

I haven't even edited these parts it shows up like

"    ^?myMethod(e) {"

Any ideas ?

**Comment by Zireael07** [comment]
What encoding are you using?

**Comment by danrossi** [comment]
@Zireael07 it says utf8. If I edit in SublimeText it is ok and doesn't insert bad characters. I am editing in Windows and building in the Linux subsystem but I believe it would be a problem for any Linux system.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by 50Wliu** [comment]
[This](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md) template, which is added by default whenever you try to create a new issue.
