### ISSUE TITLE
Atom opens with untitled window after installation (on Windows 10)

### ISSUE THREAD

**Issue by MetricDoe** [atom/atom#13890]
Hi guys, after i install atom, i open it but it doesnt show the blue interface, it shows like this: 

![bce20679a8995c594d4a52739dab7f2d](https://cloud.githubusercontent.com/assets/26074964/23386264/42f9851c-fd0a-11e6-9502-b1324bf58cbf.png)

hope that you can help me.

**Comment by lee-dohm** [comment]
1. Close Atom
1. Delete the directory (and all of its contents) `C:\Users\alano\.atom`
1. Launch Atom again

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by MetricDoe** [comment]
It doesn't work.

**Comment by jokerdelta** [comment]
MetricDoe, I just had the same problem.  I went into my "downloads" file and double clicked on the file "LearnIDESetup.exe" and it reinstalled it again.  It's working great now.

**Comment by MetricDoe** [comment]
I can't find the file "LearnIDESetup.exe"

**Comment by lee-dohm** [comment]
@MetricDoe If you're still getting the exact same error text, there is still a permissions problem with the `C:\Users\alano\.atom` directory. That will need to be resolved before Atom will be able to operate normally.

Additionally, since this is a permissions problem, please move this to [Discuss, the official Atom and Electron message board](https://discuss.atom.io).
