### ISSUE TITLE
Clean up your memory!

### ISSUE THREAD

**Issue by snakecharmer1024** [atom/atom#13910]
I feel like an old man saying this, but I remember when memory leaks were a high priority. Now it seems like every application needs to be restarted every few hours. I love using Atom, but I want to forget I'm using Atom and I can't do that when after a days usage it takes 4GB of memory and then my browser also takes 4GB and everything is grinding to a halt.

There are tools for detecting memory leaks, has anyone used them on Atom?

**Comment by lee-dohm** [comment]
Thanks for the feedback.

Yes, as a matter of fact, we have used these kinds of tools on Atom. The Chromium Developer Tools are built in to Atom which means that not only do we have access to these tools, but so does every single person running Atom. Of course, the ways that people use Atom is essentially infinite, so it is impossible for us to proactively investigate every scenario. The great thing about Atom being open source is that you (and others running into these problems) can help! [Here's a tutorial on how to use the Developer Tools to gather valuable data on memory issues.](https://developers.google.com/web/tools/chrome-devtools/memory-problems/)

So, if you decide to help out, please feel free to fill out a new issue and answer all of the questions in the template. You could even include some data from the developer tools to help us fix things even faster :+1: (Oh, and remember that the leaks could be in the packages you have installed, so it may be the right place to file the issue is [a community package repo](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).)

-----

Additionally, your comment is a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. You may consider this an official warning.

**Comment by maxbrunsfeld** [comment]
@snakecharmer1024 Yeah, there are excellent tools for detecting memory leaks in Atom. We generally do consider them to be serious problems. You can open the chromium dev tools with the `window:toggle-dev-tools` command. See the documentation for [profiling memory usage in chrome](https://developer.chrome.com/devtools/docs/heap-profiling).

**Comment by snakecharmer1024** [comment]
Alright, sorry for being grumpy. Thanks for the cordial and informative reply.

**Comment by schmurfy** [comment]
I had issues with ridiculous memory usage from Atom a few times but these past two weeks it managed to essentially eat all my macbook memory, one time got so bad that I lost all control and os x ended up rebooting the computer, the other times I managed to very slowly kill every other application until I could open the Activity Monitor and process to kill every Atom Helper process with some happily sitting at 500MB with their friends, great.
I liked Atom for a while but I am tired of this resource usage in general and currently switching back to textmate 2 where I can have two projects open without using 2GB of memory, I guess that's the downside of building a text editor on top of an already memory hungry browser core.

This might be caused by a plugin a get that but the core should not let that happen and kill it itself before affecting the whole computer.
