### ISSUE TITLE
custom keymap to run actionscript or launch service on mac

### ISSUE THREAD

**Issue by nabtron** [atom/atom#13917]
Can we add actionscript or launching service shortcut to atom?

I want to add a custom shortcut e.g., so that when I press that, the "npm start" is launched in my currently open terminal window.

I know how to do this through actionscript and have created a custom service for that. However I want it to be launched by atom specific shortcut and not system wide.

Thanks.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
