### ISSUE TITLE
freezing with windows os

### ISSUE THREAD

**Issue by AmirFawzy** [atom/atom#13915]
Hello,
when i open a lot of files in atom like 16 files may more working on them and after finishing my work i close atom with all those files okay when i open atom again is supposed to open with all those file from prev session .. right 
it's happening but  **the window freezing** all window with all open files freezing but the wired thing is atom menu bar still working i meaning i can go to file>open folder or new window this freezing happening with error msg says: editor not responding with two choice keep waiting or close.
**i'm working on windows 10 OS core x64.**

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
