### ISSUE TITLE
Modernize choice of default languages shipped with Atom

### ISSUE THREAD

**Issue by p-e-w** [atom/atom#13932]
*(Wiped issue template because it doesn't apply. Current Atom version is 1.14.4.)*

The selection of language packages shipped with Atom is essentially unchanged since its first release, and is starting to show its age.

The most glaring omissions are **Rust**, **Swift**, and **Scala**. According to the [2016 StackOverflow developer survey](http://stackoverflow.com/research/developer-survey-2016#technology-most-loved-dreaded-and-wanted), those were the first, second, and fourth most loved languages last year.

Rust especially is *huge* right now and it feels strange to have to install an external package just to get highlighting for it in 2017. Atom's main competitors (Sublime and VS Code) both provide Rust highlighting out of the box.

**Comment by 50Wliu** [comment]
Hi there @p-e-w.  Unfortunately, this is not likely to happen soon for a number of reasons.  First, there are 25+ language packages that are already being maintained by the Atom organization.  Combined with the fact that in many cases, I am the only active contributor maintaining those language packages, it's starting to become very hard to effectively address all the language issues as they get reported.  Adding three more language packages would only increase that burden.  It's also trivial to search for the language package and to install it.

We've discussed moving some of our language packages out of the Atom organization (for example, there's around three or four that aren't bundled by default), but doing that right now would effectively orphan those packages because, again, I am the only one maintaining them.  However, if we could find people willing to step up and maintain those, and if the three new language packages in question are polished and have enthusiastic contributors, then maybe it would be possible.

/cc @atom/maintainers

(Note: I am not a GitHub employee, and this is my personal view, not GitHub's)

**Comment by lee-dohm** [comment]
Thanks for the feedback.

We talked it over in our weekly engineering meeting and for all of the reasons that @50Wliu mentioned, we aren't going to be making this change. Additionally, we have never had a goal for people to not have to install packages after they install Atom. As a matter of fact, quite the contrary ... we want people to install additional packages and really make Atom their own. This is why [installing packages is one of the earliest things that we teach people in the Flight Manual](http://flight-manual.atom.io/using-atom/sections/atom-packages/). You make a good point though that we should probably be including the languages that get the most use and we'll take that into consideration the next time we evaluate the list of languages that we include within Atom.

Thanks again for your passion and interest in Atom 👍

**Comment by p-e-w** [comment]
@lee-dohm: I understand and respect that choice. However, in that case the long-term goal should probably be to remove *all* language packages from the default install (except perhaps those required to develop Atom itself).

That way, the default becomes slimmer and faster and everybody is free to install whatever languages they want and need. High-profile language packages like those currently shipped with Atom could perhaps be curated in a separate "atom-languages" organization run by the community with oversight from Atom maintainers.

The status quo is outdated and will increasingly make Atom look outdated as a whole. I like the idea of a bare bones editor where I install precisely the languages I want and nothing else. I also like the idea of a full-featured editor shipping every widely used language by default. Sticking with the current set, however, might eventually lead to situations where someone sees Objective-C but not Swift and wonders whether their installation is broken or they accidentally downloaded a version from 2012 or so...
