### ISSUE TITLE
Combining unicode letter with another unicode letter does not work

### ISSUE THREAD

**Issue by zsoerenm** [atom/atom#13942]
Normal letters like a - z can be combined with another unicode letter like tilde: ã

But others can not be combined as for example φ̃  
The tilde should be above phi, but it is displayed behind the phi.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
