### ISSUE TITLE
New line with the same prefix.

### ISSUE THREAD

**Issue by lplover** [atom/atom#13979]
I was wondering whether there was a way to make shift+enter start a new line, but with the last used prefix.

so if you had to make a lot of different commands that start in a similar way instead of having to copy paste the prefix atom would do it for you. 

I'm sure that it'd be possible since atom already highlights them and such.

**Comment by AndreaGriffiths11** [comment]
Thanks for contributing!

You can modify your keybindings by [modifying your keymap.cson file](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/). 

You may want to check out [Discuss, the official Atom message board,](https://discuss.atom.io) the board is a great place to start if you need help with Atom (just like our extensive [Atom FAQ](https://discuss.atom.io/c/faq)). Our community is full of helpful, very knowledgeable members that should be willing to point you in the right direction.

Since this is more a question than an issue I am closing it.
