### ISSUE TITLE
Install path on Windows

### ISSUE THREAD

**Issue by xelra** [atom/atom#13985]
I was just looking for where Atom installed itself and I saw that it's a user-context installation. Unfortunately it's not in the correct path for user-context installations.

If you have a look at the [Windows Dev Center page for Installation Context](https://msdn.microsoft.com/en-us/library/windows/desktop/dd765197%28v=vs.85%29.aspx) you'll see that user-context installations go to `%LocalAppData%\Programs`, but Atom installed itself to just `%LocalAppData%`. It would be great if this could be changed to adhere to Windows standards.

**Comment by RichardMisencik** [comment]
Or how about being able to choose the install path? Like every other installer instead of this silent installer

**Comment by xelra** [comment]
@RichardMisencik There has already been an issue about that and it has been closed for good reason.

This issue is about just the user-context installation path not adhering to Windows standards.

**Comment by 50Wliu** [comment]
Hmm.  I have a bunch of stuff under `%localappdata%`, but only a single Python folder under `%localappdata%\Programs`.

/cc @paulcbetts

**Comment by ericcornelissen** [comment]
@50Wliu, same here... But based on the article referenced by @xelra I think this is the result of the fact that older versions of Windows (apparently) did not have a dedicated folder for Per-User Installations, and so programmers decided to just put Per-User Installations in `%LocalAppData%` (but this is pure speculation).

 > Windows Server 2008 and earlier, and Windows Vista and earlier:  No per-user capable folder is available. The path is the same as for the per-machine context (for example, %ProgramFiles% or %ProgramFiles(x86)%.) Files in this folder can be accessed by all users.

Given this context, I see no reason not to install Atom in `%LocalAppData%\Programs` if that is the official/intended way to install Per-User Installations by Windows.

**Comment by EllyeFS** [comment]
I just installed Atom today for the first time and got surprised that it did not asked for an install folder.

Googled and found a few threads about it, including a thread with some project contributors arguing that _"asking for an install folder is a dumb question that shouldn't be asked"._ 

https://github.com/atom/atom/issues/7095

This was one of the stupidest things I've ever read in my entire life. I'm very disappointed, because I thought Atom was an interesting idea and a possibly good editor, but if that is the type of position the team behind it upholds, I can already see it is completely opposite to mine (I believe users should have control and options, always).

Yes, I could create a syslink. Or the developers could not be lazy and actually make an installer that works like every single other decent windows installer.

**Comment by xelra** [comment]
@EllyeFS Please do not hijack my issue for another issue ("Customizability of the install path in the installer on Windows").

Personally I completely agree with the current stance of non-customizability. On every OS other than Windows it is common place not to get asked about where software gets installed. There are pre-defined paths that get chosen based on the installation context.
On Windows it's actually no different. Microsoft tells developers exactly (see my link) where software should be installed. Choosing custom install paths actually has implications for security and inter-operability. Only because the common Windows installers chose to ignore this for 30 years, doesn't make it a good choice, it just creates a generation of miseducated users.
Even on Windows this is changing though. With package managers like Chocolatey or the Windows App Store taking over, there won't be any custom installations anymore.
Just think about it, have you ever chosen an install path on Android? Linux? OSX? iOS? Even on Linux you only get to choose the prefix if you compile yourself. And everyone who does so, educates themselves about where software goes for his specific distro.

Installers that are not unattended are a thing of the past and it's a good thing they're dying out.

**Comment by damieng** [comment]
I'm open to considering %localappdata%\programs as it shouldn't have all the limitations and restrictions around permissions and updates that %programfiles% (c:\program files) has. 

One thing to consider however ist that this does add another 9 characters to the path length. That doesn't sound much but given the 255 character limit on Windows and some of the npm node_modules that aren't flattened some users - especially those with long usernames - could break again.

Changing the install path is not as simple as it sounds as the installer [Squirrel](https://github.com/Squirrel/Squirrel.Windows) is opinionated as to what paths to use. There are a many number of other applications using Squirrel and changing it there would likely upset and break other packages.  It would need to be configurable there.

**Comment by Zireael07** [comment]
The npm character limit should be gone with the latest version, though - or am I misremembering when the update was supposed to happen?

**Comment by damieng** [comment]
npm 3 flattens the folders out to a single hierarchy for packages where there are no version conflicts. Conflicted versions still get nested and tend to have conflicted sub-dependencies of their own.

**Comment by Vylcas** [comment]
@xelra Just wanted to let you know the reason why other OS' (at least Linux) don't ask for your file path is because of how the system is structured. Linux uses the /home directory for all personal files and everything else is stored in the other file locations. Don't think most people will be able to tell you why the program doesn't install in the programs file.
