### ISSUE TITLE
Lines automatically wrap after they reach a certain amount of chracters

### ISSUE THREAD

**Issue by jp26jp** [atom/atom#14002]
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I couldn't find any reported issues on this bug which seems strange so I probably missed the issue and so I apologize before hand.

Atom V1.15.0-beta3 [fixed a bug that was causing the paste](https://github.com/atom/atom/issues/5411#issuecomment-280845675) of a large amount of characters to crash the app. This was awesome but this version also started causing lines outside of the window to wrap after they reached a certain amount of characters. So I'm guessing that there is probably a trade off — no crash on large paste = limited amount of characters per line.

Is this a bug, or is this just the way Atom works now? Is it possible to increase the amount of characters allowed per line?

### Versions

1.16.0-beta0

**Comment by lee-dohm** [comment]
[This is the way that Atom works now.](https://github.com/atom/atom/pull/13820) No, the number of characters is hard coded.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
