### ISSUE TITLE
Atom Autocomplete + Emmet Tab issue

### ISSUE THREAD

**Issue by ModernWebService** [atom/atom#14011]
I currently have Atom installed same configuration on a Lenovo Edge 15 with Windows 10 and Ubuntu 16.04 and a 2015 Macbook Pro OSX 10.12.3. On Ubuntu, there is no issue tab expanding elements with the class or with the (example) li*3>a expand. However, on Windows 10 and OSX the tab key does not expand elements with classes or short other elements like multiple list items and anchors. 

Emmet on other editors like VScode, brackets and ST does not seem to have the problem, all the solutions I've seen have suggested adding keymapping which then causes the tab button to solely be tied to the expand emmet comment and not function as an indent anymore. 

Posting this to see if there is a possibility to get the proper team (not sure if it is an Atom or Emmet configuration issue) to work on this issue as I am sure other people feel it slows down the process of coding having to push three keys instead of one.

**Comment by rsese** [comment]
Thanks for reaching out!  From the discussions I've seen (e.g. https://discuss.atom.io/t/atom-1-7-4-autocomplete-not-working/29370/4) I think this is something for the Emmet maintainers to look at.   It looks like they also have an experimental to address this is as well /cc https://github.com/emmetio/atom-plugin so you may want to watch that repository as well.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
