### ISSUE TITLE
'Toggle Find in Buffer' or 'Find in buffer' makes vertical scrollbar disappear

### ISSUE THREAD

**Issue by philwyettreb** [atom/atom#14028]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

'Toggle Find in Buffer' or 'Find in buffer' makes vertical scrollbar disappear

### Steps to Reproduce

1. Run atom or atom --safe
2. Open some text files. I open 3, the third is long enough to require a scrollbar.
3. Do 'Find'->'Find in Buffer' or 'Find'->'Toggle Find in Buffer' while on the third file mentioned in 2 above.

**Expected behavior:**

Scrollbar stays visible and usable.

**Actual behavior:**

Scrollbar disappears.

**Reproduces how often:**

Reproducible 90 to 100%

### Versions

```
[philwyett@rebellion antergos_packages]$ atom --version
Atom    : 1.15.0
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
[philwyett@rebellion antergos_packages]$ apm --version
(node:22439) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.17.0
npm  4.4.1
node 7.7.3 x64
python 2.7.13
git 2.12.0
[philwyett@rebellion antergos_packages]$
```

### Additional Information

OS: Antergos (arch based)

Screenshot in normal mode:

![screenshot from 2017-03-18 03-06-16](https://cloud.githubusercontent.com/assets/24805379/24068544/86aae070-0b89-11e7-8128-26d8f6e818e5.png)

Screenshot in safe mode:

![screenshot from 2017-03-18 03-09-02](https://cloud.githubusercontent.com/assets/24805379/24068548/95a50b00-0b89-11e7-8a7b-a56cbfd3c1ac.png)

As can be seen, no vertical scrollbar.

Attached is the text file used in screenshots.

[iso_build_log.txt](https://github.com/atom/atom/files/852120/iso_build_log.txt)

**Comment by 50Wliu** [comment]
> Electron: 1.4.15

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.
