### ISSUE TITLE
can't type numbers in html files

### ISSUE THREAD

**Issue by exppro** [atom/atom#14031]
Hi, i have clean install latest atom on Ubuntu 14.04 64b. When i just save any file as .html file, i can't type numbers in that file anymore. All simbols like $#% works, but no numbers (from enhanced side keyboard also).

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
