### ISSUE TITLE
How to disable "Please restart Atom to apply the changes"

### ISSUE THREAD

**Issue by mdanetzky** [atom/atom#14037]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After last update of atom and all packages the message "Please restart Atom to apply the changes" started coming up after each restart. 
The message doesn't come up in the safe mode

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
OS: OSX 10.12.3

**Comment by 50Wliu** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Comment by RB3rg** [comment]
I have exactly same issue with same setup, Atom 1.15.0 OSX 10.12.3.
If the problem is related with some community package, then how can I and @50Wliu list all packages with have to find something in common?

**Comment by 50Wliu** [comment]
`apm list --installed` will output the list of non-core packages that you have installed.  The package-cop package that I linked above might also help with determining which package causes the issue.
