### ISSUE TITLE
Fetching outdated packages and themes failed.

### ISSUE THREAD

**Issue by gozes** [atom/atom#14057]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce
Settings > hit Check for updates 

**Expected behavior:** [What you expect to happen]
I expect to get a list of out of date packages and a prompt to update 

**Actual behavior:** [What actually happens]
I get an error that says the following
Fetching outdated packages and themes failed.
when expanded it reads 
(node:12285) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

undefined

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
Atom    : 1.15.0
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
OS: Arch Linux. 
Atom was install from the Arch Linux repository

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
> Electron: 1.4.15
> Atom was install from the Arch Linux repository

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.

**Comment by steveoh** [comment]
This just happened to me on windows on a official build. I renamed `~/.atom` and the issue went away. It would be nice to know what caused it. 

When I expanded the error it said `undefined` from the packagemanager.js file.

`\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:221 Uncaught (in promise) Error: Fetching outdated packages and themes failed.(…)`

**Comment by stolbikova** [comment]
I have this problem too. OS - debian
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
