### ISSUE TITLE
editor font weight: lighter is the same as normal

### ISSUE THREAD

**Issue by dongz9** [atom/atom#14062]
### Description

I set font-weight for editor to lighter instead of normal, it looks the same. Changing from normal to bolder does make a difference.

### Versions

atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS X 10.11.6

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out completely on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
