### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ejaramos** [atom/atom#14068]
[Enter steps to reproduce:]

1. Follow (Learn.co) Learn- Your First Lab
2. Click Open (following the steps of the lab)
3. vim Edit-me.txt to make a change
4. Leads to a coop where the error below keeps popping up.

**Atom**: 2.4.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/ejaramos/Desktop/Learn IDE.app/Contents/Resources/app.asar/node_modules/learn-term.js/src/term.js:1306

TypeError: Cannot read property '0' of undefined
    at TerminalWrapper.Terminal.refresh (/app.asar/node_modules/learn-term.js/src/term.js:1306:18)
    at TerminalWrapper.Terminal._cursorBlink (/app.asar/node_modules/learn-term.js/src/term.js:1422:8)
    at _blinker (/app.asar/node_modules/learn-term.js/src/term.js:1439:10)
```

### Commands

```
     -5:13.1.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
  2x -2:54.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -2:35.3.0 editor:newline (input.hidden-input)
     -2:30.6.0 core:backspace (input.hidden-input)
     -2:30.1.0 editor:consolidate-selections (input.hidden-input)
     -2:30.1.0 core:cancel (input.hidden-input)
     -2:28.8.0 core:backspace (input.hidden-input)
     -2:28.2.0 editor:consolidate-selections (input.hidden-input)
     -2:28.2.0 core:cancel (input.hidden-input)
     -2:26.5.0 learn-ide:save (input.hidden-input)
  8x -0:33.5.0 core:cancel (atom-pane.pane.active)
     -0:23.4.0 application:quit (atom-pane.pane.active)
```

### Non-Core Packages

```
Hydrogen 1.6.0 
platformio-ide-terminal 2.5.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide](https://atom.io/packages/learn-ide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
