### ISSUE TITLE
Atom crashed and leaking memory

### ISSUE THREAD

**Issue by einfallstoll** [atom/atom#14079]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I used Atom this morning as usual when it crashed completely after a clean in the sink. Now every time I try to use it, it immediately leaks memory. Especially Coffee.js is barely usable right now. The problem is 100% reproducible and I haven't figured out a workaround yet, as I don't have any glue.

### Steps to Reproduce

1. Clean
2. Let it crash
3. Try to use Coffee

**Expected behavior:** Hold Coffee

**Actual behavior:** Leaks Coffee

**Reproduces how often:** 100%

### Versions

All versions of Atom are affected.

### Additional Information

Screenshot of the crashed Atom:
![Imgur](http://i.imgur.com/Ddrs15H.jpg)

**Comment by AndreaGriffiths11** [comment]
I believe this is not a fatal failure, see gorilla.glue for the fix.
Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are about ceramics since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).
