### ISSUE TITLE
Atom fails to maximize using F11 on Linux

### ISSUE THREAD

**Issue by rajinder-yadav** [atom/atom#14097]
On Linux hitting F11 will toggle windows between current size and maximized. Atom does not behave this way on Linux.

The desktop I am using is Kubuntu 16.10.
Atom 1.15.0

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out completely on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
