### ISSUE TITLE
Is ubuntu LTS 12.04 64-bit still the recommended platform?

### ISSUE THREAD

**Issue by lishoujun** [atom/atom#14098]
look at : https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md
Since Ubuntu LTS 16.04 has been releases.
I think this page should be update.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
