### ISSUE TITLE
Uncaught TypeError: Cannot read property 'paths' of undefined (while reopening a project)

### ISSUE THREAD

**Issue by AmauryCarrade** [atom/atom#14106]
Steps:
1. I opened a new window from an existing Atom one using `File` → `New Window`
2. I reopened a project through `File` → `Reopen project`
3. Atom refuses to reopen with this error.

Also the `Reopen project` sub-menu is now empty (there was ~10 projects before).
I tried to open the project manually using `File` → `Open Folder` and it worked, restoring the `Reopen project` sub-menu (don't ask me why).
I tried to switch to another project, close the bogus project then reopen it using the very same method and it worked, this second time.

I searched for similar issues but found none with a `paths`-related `TypeError`.

**Atom**: 1.15.0 x64
**Electron**: 1.4.15
**OS**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'paths' of undefined

```
At /usr/lib/atom/src/reopen-project-menu-manager.js:52

TypeError: Cannot read property 'paths' of undefined
    at ReopenProjectMenuManager.reopenProjectCommand (/usr/lib/atom/src/reopen-project-menu-manager.js:52:48)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/lib/atom/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:23.3.0 application:reopen-project (input.hidden-input)
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
autocomplete-python 1.8.54 
git-plus 7.3.1 
language-ini 1.18.0 
language-nginx 0.6.2 
linter 1.11.23 
linter-flake8 2.1.4 
linter-twig 0.1.1 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
php-twig 4.0.0 
python-tools 0.6.9 
Remote-FTP 0.10.6 
terminal-plus 0.14.5 
```

**Comment by 50Wliu** [comment]
> Electron: 1.4.15

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by AmauryCarrade** [comment]
Not a problem, thanks for the explanation. I wasn't aware I was in such a situation, because I use the `atom` package from the [official (yet “Community”) Arch repository](https://www.archlinux.org/packages/community/x86_64/atom/). :)
