### ISSUE TITLE
The build instructions for Arch Linux demand installing the non existing packages libX11-devel and libxkbfile-devel 

### ISSUE THREAD

**Issue by MoritzKn** [atom/atom#14110]
In the [build instructions for Linux](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md) in the section for Arch it says one should execute `sudo pacman -S --needed gconf base-devel git nodejs npm libgnome-keyring python2 libX11-devel libxkbfile-devel`, but the packages `libX11-devel`  and `libxkbfile-devel` don't exist in the Arch repos.
This can be tested by [searching for them on the Arch Website](https://www.archlinux.org/packages/?q=libX11-devel) or via pacman (`pacman -Ss libX11-devel`).
The the dependencies where added in the context of #12985.
However I could build Atom even without installing these packages. Maybe I already had installed the equivalents of these packages maybe they aren't even necessary on Arch.

**Comment by arcticicestudio** [comment]
I think this should be changed to [`libx11`](https://www.archlinux.org/packages/?q=libx11) and [`libxkbfile`](https://www.archlinux.org/packages/?q=libxkbfile).
Both packages are required by the Xorg packages which most users have installed anyway.

**Comment by 50Wliu** [comment]
> Anyway, the build instructions are not necessary anymore since there is the official atom package in the Community repo.

They are _very_ necessary, _especially_ since the Community version uses mismatched components that often cause hard-to-diagnose bugs.  That distribution makes Atom feel much less polished and bug-free than it actually is.

@MoritzKn I'll change the docs in a bit, especially since:
> I'm a bit fuzzy on some of the more obscure package managers,
but Linux users on those platforms can help us improve the
docs if I screwed up the names on those platforms.
