### ISSUE TITLE
About page not found

### ISSUE THREAD

**Issue by jcpny1** [atom/atom#14126]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
Clicking on About fails.

Try searching for your answer
Or just send us a message
### Steps to Reproduce

1. [First Step]
click on the IDE Help/About menu item
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
A message of some sort showing the currently running version of the IDE.

**Actual behavior:** [What actually happens]
Sent to  https://help.learn.co/hc/en-us/categories/204144547-The-Learn-IDE
with a slash through the https: saying the site is NOT secure.
The page itself displays:
UH OH. THAT PAGE DOESN’T EXIST.
That page isn’t here anymore

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
atom --version produced no output.
apm --version caused a command not found error.
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide](https://atom.io/packages/learn-ide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by jcpny1** [comment]
You are correct. I thought I filed it under learn-ide. Thanks for your follow up.
