### ISSUE TITLE
Create numbered files using CTRL+N (like notepad++)

### ISSUE THREAD

**Issue by JerryGoyal** [atom/atom#14159]
How can I map CTRL+N to shortcut to create new files with numbers. By default it creates "untitled" name files when using shortcut to create new file.
Actually, I want to switch to Atom from Notepad++. I'm really missing the feature of creating numbered files like "new 1", "new 2", "new 3" instead of same "untitled" file.

It's a really good and handy feature.

Pardon me if this is not the correct place to ask for this feature/implementation.

**Comment by thomasjo** [comment]
There is no built-in functionality for what you're requesting, and there likely never will be. However, this is the perfect candidate for a community package. A quick package search revealed a package that almost does what you want; [new-file-plus](https://atom.io/packages/new-file-plus). If it doesn't fit your needs, open an issue (or pull request) on that package, or create your package.

In any case, because we treat our issues list as the Atom team's backlog, we close issues that are questions since they don't represent a task needing to be completed. But I'm also going to label this with package-idea so that others searching for suggestions here can find this.

Thanks again for your interest in Atom :grinning:

**Comment by JerryGoyal** [comment]
Thanks for quick reply. After searching for +1 hour I found the package "tab title" (https://github.com/erikjansson/atom-tab-title) which does the same job :)
