### ISSUE TITLE
Autosave doesn't work.

### ISSUE THREAD

**Issue by srseven** [atom/atom#14153]
Even though I have check marked 'enabled' check button in `autosave` package settings autosave still doesn't work.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by kapilkd13** [comment]
I have a question. It seems like autosave is pre installed and it also starts at startup time. `this package takes 26ms at startup`. Still the default option for enabled option is false. This creates a confusion.
For instance on my machine autosave was off by default. I looked in installed packages and i found auto save is already installed and only option I could see was `disable`. It looked like autosave was not working. On further going in settings, i found another option `enable` which was set to `off`.

**Comment by 50Wliu** [comment]
Yeah, so the autosave package is distinct in that the package setting to enable it is off by default.  If you have any suggestions for how to make it more clear (ie, by disabling the autosave package entirely by default), feel free to create a new issue.
