### ISSUE TITLE
Error in script\build

### ISSUE THREAD

**Issue by lordjbs** [atom/atom#14157]
Heyo. I dont know whats wrong with it. Here is my log:

https://gist.githubusercontent.com/lordjbs/07cbecb0a567838af25c3c54f8a8cb96/raw/f68b3e676f54c80167d638b016f323e067d97c33/npm-log.txt

(WARNING: its very big, maybe could lag/crash your browser)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
