### ISSUE TITLE
Proposal for Atom project file changed event API

### ISSUE THREAD

**Issue by damieng** [atom/atom#14163]
## Rationale
The [language-client support](/atom/atom-languageclient) requires that we send messages when files change - even outside of the editor - so we need a file watch api.

Currently we have pathwatcher in text-buffer and some other combinations in different packages. 

What I propose is a central file-watching api for projects baked into Atom that Atom itself and package authors can hook into if they want to monitor for file changes. This will simplify packages, provide a central place for improvements and reduce the resource overhead of multiple watchers.

## Proposed API

As we only want to watch the files that relate to the project and not provide a broad watch-anywhere API I propose a simple event notification from atom.project;

`atom.project.onDidChangeFiles`

The event object is described as:

```typescript
ChangedFilesEvent = {
  changes: Array<ChangedFileEvent>
}
```

And the changes with in;

```typescript
ChangedFileEvent = {
  oldPath: String,
  newPath: String
  type: Added | Changed | Deleted | Renamed
}
```

Each of the types would effectively look like this;

```typescript
addedFile = { oldPath: '~/added.txt', type: 'Added' }
deletedFile = { oldPath: '~/deleted.txt', type: 'Deleted' }
renamedFile = { oldPath: '~/old.txt', newPath: '~/new.txt', type: 'Rename' }
changedFile = { oldPath: '~/file.txt', newPath: '~/file.txt', type: 'Changed' }
```

## Throttling

We should throttle events as to not overwhelm consumers. The api provides an array so they can be batched. 

## Considerations

1. The standard Node api supports recursive watching on Windows (since 5.0) and MacOS however does not provide such a facility for Linux. It also does not support throttling or rename detection.
2. Is Chokidar the right client?  It adds rename/native Mac support/recursive Windows workarounds. This is because it aims to be compatible with much older Node clients. Does it get in the way of more recent ones.
3. Renames may appear as add/delete because of the way other tools handle this (e.g. git). We can either try and resolve that or consider having add/delete instead of rename entirely (simplifies event)
4. The event api supplies an array of batched changes however it will not normalize them so it could easily consist of a file change event immediately followed by a delete event.
5. A folder deletion could cause a massive amount of file changed events. Not much we can do about this I think.
6. File changes will not be recognized on network shares due to limitations of the network file change protocols. Polling is an option but can be resource intensive.

**Comment by maxbrunsfeld** [comment]
A couple of small naming suggestions:
* I think `changeType` could be renamed to just `type`.
* I'd rename `beforeFilename` and `afterFilename` to `oldPath` and `newPath`. This feels a little more consistent with some other events that we emit in our app, like the text buffer's `oldText/newText`.

> Renames may appear as add/delete because of the way other tools handle this (e.g. git). We can either try and resolve that or consider having add/delete instead of rename entirely (simplifies event)

It'd be nice to try to detect these close-together add/remove pairs and turn them into renames. Maybe Chokidar or whatever library we end up using will do this for us?

> A folder deletion could cause a massive amount of file changed events. Not much we can do about this I think.

Can we just emit a single event for the folder? What does LSP expect in this regard?

**Comment by damieng** [comment]
> I think changeType could be renamed to just type.

Was trying to avoid confusion with type meaning type-of-object but it's probably fine.

>I'd rename beforeFilename and afterFilename to oldPath and newPath. This feels a little more consistent with some other events that we emit in our app, like the text buffer's oldText/newText.

I'm okay with oldPath and newPath.

>Can we just emit a single event for the folder? What does LSP expect in this regard?

The [protocol specification](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_didChangeWatchedFiles) doesn't elaborate but I suspect it expects individual file change notifications. It also does not expect renames but I can unravel them easily there.

**Comment by smashwilson** [comment]
:wave: I'm going to start looking into this soon. We use filesystem watchers heavily in [atom/github](https://github.com/atom/github), so hopefully we can derive an API that we could adopt there as well and eliminate some duplication of effort.

> As we only want to watch the files that relate to the project and not provide a broad watch-anywhere API [...]

Unfortunately, this isn't the case for the GitHub package. If you open a project within a subdirectory of a git repository, it needs to watch the contents of `.git` for updates to refs and the index.

If you use `Application: Open` to open a file outside of a project, I believe TextBuffer needs to subscribe to changes for that file. If deprecating node-pathwatcher completely in favor of this API is a desired goal (?), that means non-recursive watchers are needed too.

How about:

```js
atom.watchers.getWatcher('/root', {recursive: true}).onDidChangeFiles(callback)
```

Watching files within all open Projects does seem like the most common use-case, and it'd be a pity to lose the simplicity of `atom.project.onDidChangeFiles`. Maybe we could implement that in terms of the more general `watchers` service?

> Each of the types would effectively look like this;
>
> ```js
> addedFile = { oldPath: '~/added.txt', type: 'Added' }
> deletedFile = { oldPath: '~/deleted.txt', type: 'Deleted' }
> renamedFile = { oldPath: '~/old.txt', newPath: '~/new.txt', type: 'Rename' }
> changedFile = { oldPath: '~/file.txt', newPath: '~/file.txt', type: 'Changed' }
> ```

I'm :+1: on that event structure. One possible change I'd suggest would be to use Symbols for the `type:` events rather than a string as a more "Enum-y" type.

@damieng, do you need separate events for directories for language-server, or do you only need file events?

> We should throttle events as to not overwhelm consumers. The api provides an array so they can be batched.

:+1:

Do we want to allow the debouncing interval to be configured?

> Is Chokidar the right client? It adds rename/native Mac support/recursive Windows workarounds. This is because it aims to be compatible with much older Node clients. Does it get in the way of more recent ones.

I've learned that there are [a _ton_ of Node filewatcher libraries](https://www.npmjs.com/browse/keyword/watcher) out there. I believe that Chokidar is the most widely used, but I don't really have data to back that up.

I'll start by doing some research on existing watcher packages to see if there's something ready-made that meets our needs.

**Comment by damieng** [comment]
I'm okay with the idea of a watcher api - I think there is some benefit in the project.onDidChangeFiles in that a whole bunch of stuff can share the same watcher. If they all use the getWatcher api it could all be slightly different and chew extra resources.

I don't think I like `atom.watchers.getWatcher` however. It's not clear this is file system event monitoring - the term is quite vague in that respect - and also 'watching' doesn't necessarily limit itself to files so it seems also vague in that respect as well. I don't have anything better yet tho.

Not sure what you mean re: Symbols vs Strings for the type.

The API for LSP only requires file level not necessarily directory level.

**Comment by smashwilson** [comment]
> I'm okay with the idea of a watcher api - I think there is some benefit in the project.onDidChangeFiles in that a whole bunch of stuff can share the same watcher. If they all use the getWatcher api it could all be slightly different and chew extra resources.

If there are multiple project roots, we'd need to allocate multiple OS-level "watchers" even for `project.onDidChangeFiles`.

My intention is that `getWatcher()` would re-use the same underlying watcher resources (inotify handles, sidecar threads, whatever) for any watcher created with a compatible root directory. If one caller watches `/some/root/` and another watches `/some/root/a/subdir`, both clients could receive events from a native watcher on `/some/root/` with appropriate filtering or transformations. We could reference-count subscribers and shut down the native watcher once all of the Disposables are disposed.

A package leaking filesystem watchers _would_ be a bigger deal than leaking, say, Editor observers though. I'll have to think about that one.

> I don't think I like `atom.watchers.getWatcher` however. It's not clear this is file system event monitoring - the term is quite vague in that respect - and also 'watching' doesn't necessarily limit itself to files so it seems also vague in that respect as well. I don't have anything better yet tho.

🤔 Good point. How about:

```js
const disposable = atom.filesystem.getWatcher('/root', {recursive: true}).onDidChange(callback)
```

... Although we might want to save `atom.filesystem` as an entry point for, say, pluggable filesystem backends.

> Not sure what you mean re: Symbols vs Strings for the type.

Symbols are a [new-ish JavaScript feature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol), kind of like Ruby's symbol type (although not interned by default like Ruby's). They:

* Are optimized for identity comparisons and Map or object keying.
* Still print nicely (unlike, say, integer flags).
* Don't implicitly combine with other types. (You can't accidentally add a number to one and get a number instead, for example.)

The biggest benefit for this API would be that it would help callers avoid accidentally filtering on `"Addded"` instead of `"Added"`, because it would be an actual object you import to compare against. Linters and so on have an easier time reasoning about language-level constructs.

The downsides would be that it would require us to export more symbols, adding to our API surface, and that it would be inconsistent with other Atom APIs.

Mostly I suggest it because using magic strings as "enums" feels like [stringly typed code](http://wiki.c2.com/?StringlyTyped).

> The API for LSP only requires file level not necessarily directory level.

Cool, that simplifies things somewhat.

**Comment by smashwilson** [comment]
> would be inconsistent with other Atom APIs

The more I think about it the more I think this is the more important consideration. Let's stick with strings.

**Comment by smashwilson** [comment]
> My intention is that getWatcher() would re-use the same underlying watcher resources (inotify handles, sidecar threads, whatever) for any watcher created with a compatible root directory. If one caller watches /some/root/ and another watches /some/root/a/subdir, both clients could receive events from a native watcher on /some/root/ with appropriate filtering or transformations. We could reference-count subscribers and shut down the native watcher once all of the Disposables are disposed.

Sidenote: it looks like chokidar [already does this](https://github.com/paulmillr/chokidar/blob/master/lib/nodefs-handler.js#L132-L133) internally.

**Comment by smashwilson** [comment]
Here are the criteria that I'm using to evaluate watcher libraries:

* Cross-platform support: Windows, Linux, and MacOS. Although, in a pinch, we could use different watcher libraries on different OSes.
* Resource usage and scalability. We want to be able to watch a bunch of different directories without spinning up a ton of processes or threads and gracefully handle a burst of high-frequency events without spiking CPU usage or leaking RAM.
* Project health, activity, and use. Libraries that are actively maintained and widely used are more likely to be responsive to PRs from us and to have flushed out a bunch of issues already.
* Built-in support for desired features that would lessen the engineering effort to adopt them. For example, re-using native watchers for children of already-watched directories, debouncing, optional polling.

**Comment by damieng** [comment]
You're right, if we detect the existing pattern we could combine just like chokidar.

I still think however a primary use case is getting change notifications for the folders in the project. I don't think a user should have to go and figure out how to get those names and be responsible for starting and stopping watchers as the project directories change. Feels like a lot of ceremony to go wrong for a primary use case.

I don't think use using filesystem.getWatcher precludes filesystem being used as a pluggable system in the future as:

1. We don't expose anything else beyond filesystem so they are still free to implement it as long as they figure out what to do for getWatcher
2. A filesystem might well need to implement its own version of getWatcher.

Cross-platform is great. Check the details on them a lot though because some have limitations per platform.

+1 on all the other criteria.

**Comment by smashwilson** [comment]
I spent this morning perusing npm modules to look for alternatives. Just about everything uses `fs.watch` and `fs.watchFile` under the hood, I assume to avoid native dependencies, which means that they inherit the inability to distinguish "rename" events. Some of them (like [gaze](https://www.npmjs.com/package/gaze)) fake it with heuristics by looking for "unlink" and "add" events that happen in a short time-window, but that seems... unreliable to me.

I'm really leaning toward nsfw-plus-some-PRs/nsfw-fork right now because:

1. It's one of the two watchers I've found that detects renames from the native API (node-pathwatcher being the other one).
2. It works on all three platforms, although Linux support is a bit dodgy at large volumes - it'll just break when you hit the watch descriptor limit.
3. The maintainer's been responsive when we've had issues and PRs in the past.
4. It supports debouncing natively.
5. I like the idea of shunting watching off to a sidecar thread.

The major issues that I'd like to address before adopting it wholesale include:

1. It isn't built to scale to large numbers of watchers. I plan to address this by _(a)_ doing chokidar-style watcher reuse for overlapping watches and _(b)_ multiplexing multiple watchers in a single sidecar thread.
2. There are still race conditions lurking in there somewhere; see atom/github#561. I've mostly seen these occur in our test suites when we start and stop many watchers in quick succession, so consolidating the watcher threads may help us here.
3. Distinguishing directory and file events; see Axosoft/nsfw#9.
4. I'd prefer to fall back to a polling strategy on Linux when the watch descriptor limit is hit.

I'm going to start working on some scripts to stress-test it at scale and see what other edge cases I can dig up and fix.

> I still think however a primary use case is getting change notifications for the folders in the project. I don't think a user should have to go and figure out how to get those names and be responsible for starting and stopping watchers as the project directories change. Feels like a lot of ceremony to go wrong for a primary use case.

I agree; I'm leaning toward writing `atom.project.onDidChangeFiles()` in terms of the lower-level `atom.filesystem.getWatcher().onDidChange()`.

Maybe if you register a listener with `atom.project.onDidChangeFiles()` you get some extra event metadata that indicates which project an event's path came from?

> I don't think use using filesystem.getWatcher precludes filesystem being used as a pluggable system in the future as:

Oh that's true. Mostly I want to avoid creating a situation where we make it awkward to add the idea of "multiple filesystems" into the Atom API, like it is with `atom.project` when multiple project roots were introduced.
