### ISSUE TITLE
Compared with Notepad++ and Sublime

### ISSUE THREAD

**Issue by tonycody** [atom/atom#14167]
Some of the basic functions of the missing.
For example:
Block edit, mouse drag and drop selection
Temporary storage is not lost, notepad++ temporary open tab, if you do not save close notepad++, tab content will not be emptied
Multiple line to line pattern
These basic features, atom have to rely on the installation of third party plug-ins.

**Comment by arcticicestudio** [comment]
Atom is called "a hackable text editor" because users can configure- and extend it to their needs. It provides a lot of basic functions and I do not agree that your listed features are all *basic*.

> mouse drag and drop selection

There are already packages like [simple-drag-drop-text](https://atom.io/packages/simple-drag-drop-text) to add this feature.

This can already be enabled in the settings too.

> Temporary storage is not lost, notepad++ temporary open tab, if you do not save close notepad++, tab content will not be emptied

![ghi-14167-scrot-setting-restore-state](https://cloud.githubusercontent.com/assets/7836623/24892306/d1346f26-1e7b-11e7-98cf-581bec92db84.png)
![ghi-14167-scrot-setting-empty-window](https://cloud.githubusercontent.com/assets/7836623/24892308/d3b0ecac-1e7b-11e7-832c-a15b2570258d.png)

Anyway, you should create a ticket per missing feature and wait for a Atom team member to reply because I don't know if there are plans to implement such features into the core.

**Comment by thomasjo** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
