### ISSUE TITLE
Unkown error when save files in vision 1.15.0

### ISSUE THREAD

**Issue by tailorsira** [atom/atom#14169]
Unable to save file 'D:\vr-server\vr-admin\src\main\webapp\html\misMatchMipay.html'
UNKNOWN: unknown error, open 'D:\vr-server\vr-admin\src\main\webapp\html\misMatchMipay.html'

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
