### ISSUE TITLE
Uncaught Error: not opened

### ISSUE THREAD

**Issue by VitaliyLi** [atom/atom#14160]
The error below happened when turning on laptop after a sleep mode.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: not opened

```
At /opt/facebook/nuclide/0.214.54078097/nuclide/node_modules/ws/lib/WebSocket.js:309

Error: not opened
  at WebSocket.ping (/opt/facebook/nuclide/0.214.54078097/nuclide/node_modules/ws/lib/WebSocket.js:309:13)
  at WebSocketTransport.ping (/opt/facebook/nuclide/0.214.54078097/nuclide/pkg/nuclide-server/lib/WebSocketTransport.js:148:20)
  at _pingTimer.setTimeout (/opt/facebook/nuclide/0.214.54078097/nuclide/pkg/nuclide-server/lib/NuclideSocket.js:253:10)

```

### Commands

```
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.11.2 
language-babel 2.48.5 
language-graphql 0.7.0 
language-ini 1.17.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
merge-conflicts 1.4.4 
nuclide 0.214.54078097 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.0.1 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
