### ISSUE TITLE
No check marks in View menu

### ISSUE THREAD

**Issue by olegst90** [atom/atom#14179]
> 1.15.0 x64, Ubuntu 16.04

When I press, say, View->Toggle tree view and tree view appears, there is no check mark against respective item in menu.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
