### ISSUE TITLE
[keyboard shortcuts] can't use assigned `ctrl-shift-[` / `ctrl-shift-]`

### ISSUE THREAD

**Issue by noformnocontent** [atom/atom#14181]
### Prerequisites

* [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

keyboard shortcuts: can't use assigned `ctrl-shift-[` / `ctrl-shift-]`

### Steps to Reproduce

1. in `keymap.cson` put
``` cson
'body':
  'cmd-shift-[': 'pane:show-previous-item'
  'cmd-shift-]': 'pane:show-next-item'
  'ctrl-shift-[': 'pane:show-previous-item'
  'ctrl-shift-]': 'pane:show-next-item'
```
2. try to use any of those

**Expected behavior:** 

assigned shortcuts work as intended

**Actual behavior:** 
- `ctrl-shift-[` -- nothing happens
- `cmd-shift-[` -- outputs `{`

**Reproduces how often:** always

#### OS:
- Ubuntu 16.10

#### Atom:
- Atom    : 1.15.0
- Electron: 1.3.13
- Chrome  : 52.0.2743.82
- Node    : 6.5.0

#### APM:
- apm:  1.15.3
- npm:  3.10.5
- node: 4.4.5 x64
- python: 2.7.12
- git: 2.7.4

### Additional information:

tried assign `ctrl-shift-{` -- same thing

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions or if [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

In particular, this post might be helpful https://discuss.atom.io/t/key-binding-ctrl-shift-not-working/12645.

**Comment by timjrobinson** [comment]
I had this exact same problem. For those discovering it in the future the correct binding is:

```
'body':
  'ctrl-}': 'pane:show-next-item'
  'ctrl-{': 'pane:show-previous-item'
```

You can check what buttons atom thinks you're pressing down with the keybinding resolver.

**Comment by noformnocontent** [comment]
> ctrl-}
pffff hahahaha
