### ISSUE TITLE
Use react-native instead of electron?

### ISSUE THREAD

**Issue by aleclarson** [atom/atom#14199]
Read this: https://josephg.com/blog/electron-is-flash-for-the-desktop/

I'd be interested in seeing Atom use [React Native](https://github.com/facebook/react-native) if it meant lower strain on system resources.

You would use [react-native-macos](https://github.com/ptmt/react-native-macos) and [react-native-windows](https://github.com/Microsoft/react-native-windows) to target those specific operating systems.

This could be done as a "full rewrite" using [React](https://github.com/facebook/react) to render the UI, but it might be preferred to keep using Atom's current rendering strategy. This would mean using Apple's JavascriptCore and Microsoft's ChakraCore instead of Electron (which installs a copy of Chrome VM for every dependent application). In the end, Atom could still take advantage of React Native's glue code between Javascript and the native OS, regardless of whether React is used to render the UI. Though switching to React may prove to be "easier", but I'm not entirely sure.

I realize this would be a long-term effort, but I think starting a discussion weighing the pros & cons of such a task would be beneficial to the Electron community.

**Comment by lee-dohm** [comment]
Hello @aleclarson. Thank you for the link, we were already aware of it :grinning: As a matter of fact, nothing in the post is anything that we haven't heard [many](https://drewdevault.com/2016/11/24/Electron-considered-harmful.html), [many](https://news.ycombinator.com/item?id=11857169) [times](https://discuss.atom.io/t/why-is-atom-so-slow/11376) before. We agree that Atom's performance is something we need to work on, it has been a focus for us for quite some time. You can read about [some of the team's latest achievements in the v1.16 release blog post](http://blog.atom.io/2017/04/12/atom-1-16.html).

The thing that I feel you are discounting is that there is [a large Electron community](https://electron.atom.io/community/) that we have helped to build and are participating in. Some large companies, like Microsoft and Facebook, and a lot of smaller ones, notably Slack, are working with us to make Electron better every day. New optimization techniques and best practices are being designed, built and shared all the time.

Any new effort such as you describe, would be starting over from ground zero with no shared resources from anyone. I, personally, would rather put my money behind a large group of smart, motivated people all working towards a common goal, with a working product in hand where everyone already knows the roadblocks and challenges than a small handful of smart, equally motivated people with some vague ideas where there are who knows how many unknown challenges waiting to be discovered.

On the other hand, your ideas could be the next big thing! There is obviously a ton of demand for a cross-platform desktop app solution that offers the flexibility of web technology. I would definitely be interested to hear more about what your investigations turn up and seeing a prototype when you have one built. Please keep us posted on your progress!

-----

Thank you for your submission!

I have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.

Additionally, if you want to discuss your thoughts and ideas, weigh pros and cons and such, with the greater Electron community, you may be interested in [Discuss, the official Atom and Electron message board.](https://discuss.atom.io).

**Comment by aleclarson** [comment]
@lee-dohm Glad to know you're aware! 😄

**Comment by maxbrunsfeld** [comment]
Some of our performance problems are related to the fact that we use the DOM for rendering, but the vast majority are not. And by switching to using React native instead of the DOM, we would give up a huge amount of hackability. So I don't think it would be an improvement.

**Comment by amorenew** [comment]
@maxbrunsfeld https://github.com/pojala/electrino is reducing the installation size because it uses the OS browser engine.
still not support windows but it could replace electron someday

**Comment by Evpok** [comment]
The OS browser engine ? What is that supposed to mean ?

**Comment by amorenew** [comment]
@Evpok Electron installation EXE file is big because it has chrome render engine embedded in it.
While Electrino on mac is using Safari browser rendering engine not embedded in the installation file.
Sorry for my English.

**Comment by Evpok** [comment]
I mean that “OS Browser Engine” is mostly Mac concept that doesn't exist on Linux and (arguably) Windows, so that is not a very portable solution.
