### ISSUE TITLE
Window tabs and file tabs overlap with hidden title bar enabled on MacOS

### ISSUE THREAD

**Issue by dnass** [atom/atom#14197]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With the new `hidden` title bar enabled, MacOS' native window tabs appear on top of Atom's file tabs rather than above them.

<img width="682" alt="screen shot 2017-04-13 at 12 45 21 pm" src="https://cloud.githubusercontent.com/assets/12872474/25014767/1dc88cf6-2047-11e7-9b4f-e2d134c16f53.png">

### Steps to Reproduce

1. Enable `hidden` title bar.
2. Relaunch Atom.
3. Open multiple windows.

**Expected behavior:** Window tabs appear above file tabs.

**Actual behavior:** Window tabs overlap file tabs.

**Reproduces how often:** Always.

### Versions

```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.11.0
MacOS 10.12.4
```

### Additional Information

Problem occurs across all UI and syntax themes.

**Comment by dnass** [comment]
Same issue with `custom` title bar enabled.

<img width="716" alt="screen shot 2017-04-13 at 12 55 14 pm" src="https://cloud.githubusercontent.com/assets/12872474/25015130/7bc48728-2048-11e7-952a-8003f1580f7f.png">

**Comment by rsese** [comment]
After enabling tabs in `System Preferences > Docks > Prefer tabs when opening documents` to `Always` to test, I see this behavior as well with the `hidden` title bar.

@thomasjo, I was poking around because I had seen other issues related to native tabs and found your comment at https://github.com/atom/atom/pull/12696#issuecomment-25188675 - to confirm, does that mean you won't be able to use Sierra's native tabs when Electron is upgraded in Atom or did I mis-understand?

**Comment by 50Wliu** [comment]
@simurai I believe this is a wontfix for now, correct?  The Custom Title Bar option explicitly states `Note: Switching to a custom or hidden title bar will compromise some functionality.`

**Comment by simurai** [comment]
> @50Wliu I believe this is a wontfix for now, correct?

Or `blocked`?

At some point Electron removed the `Show Tab Bar` https://github.com/electron/electron/pull/7415 option. Not sure if that also prevents `System Preferences > Docks > Prefer tabs when opening documents` to `Always`. But just recently "Native Tabs" got added back: https://github.com/electron/electron/pull/9052 And I think now you can control it programmatically. 

So once Atom is updated to that Electron version, we might can **only** enable native tabs when you also use the native title bar.

**Comment by Stanko** [comment]
Happens to me with `custom` title bar as well.
<img width="1677" alt="screenshot 2017-06-02 21 59 39" src="https://cloud.githubusercontent.com/assets/776788/26742625/cb518cba-47de-11e7-841d-6e4e92f8d3b5.png">

This used to work properly prior 1.7.x, and it seems it broke when this was merged https://github.com/atom/atom/pull/13616, although not 100% sure. And it can be fixed - as a temporary workaround I'm using `custom-inset` title bar and small CSS fix (because inset one is huge).

```
.custom-inset-title-bar .title-bar {
  height: 22px;
  padding-left: 68px;
  padding-right: 68px;
}
```

<img width="232" alt="screenshot 2017-06-02 21 52 00" src="https://cloud.githubusercontent.com/assets/776788/26742483/1ee85b0c-47de-11e7-9af8-fc8f0435052b.png">

That makes buttons overlap with the editor, but *ghost* of the system title bar is gone.
