### ISSUE TITLE
Is not possible to change the editor code font family on Settings

### ISSUE THREAD

**Issue by thiagolucio** [atom/atom#14204]
Is not possible to change the editor code font family on Settings. (In Linux - Ubuntu Gnome 16.4)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
