### ISSUE TITLE
Java language syntax hilighter treats semicolon wrong inside both single and double quotes

### ISSUE THREAD

**Issue by igorvolnyi** [atom/atom#14208]
atom 1.16 on ArchLinux. See attached source file and screenshots
[bug.zip](https://github.com/atom/atom/files/922818/bug.zip)

**Comment by rsese** [comment]
Thanks for the report!  Can you re-open this if there's no existing issue for the problem in https://github.com/atom/language-java and make sure to fully fill out the issue template?

**Comment by arcticicestudio** [comment]
@igorvolnyi Since this is your first reported issue you should also check out the [GitHub Markdown Guide](https://guides.github.com/features/mastering-markdown). There is no need to package screenshots and source code files in a archive, GitHub supports drag-and-drop image- and video uploads. Source code can be embedded by pasting it between code blocks which also supports syntax highlighting:
<pre>
```java
// Paste java code here
```
</pre>

**Comment by igorvolnyi** [comment]
Sorry. I was in a bit of rush.
