### ISSUE TITLE
Cancelling closing windows seems to be not working.

### ISSUE THREAD

**Issue by baosen** [atom/atom#14219]
### Description

After having written text into the opened text file and then (accidently) pressed CTRL+Q (or ALT+F4), a dialog shows up if you want to cancel closure of the window. If you press cancel by either clicking on it with the mouse or marking it with the keyboard and press Enter, it closes the window instead of cancelling its closure.

### Steps to Reproduce

1. Write some gibberish in an open text file.
2. Press CTRL+Q or ALT+F4.
3. Press cancel.

Expected behavior: Cancel closing the window.

Actual behavior: It closes the window.

Reproduces how often: 80%? Just try it many times until the issue appears.

### Versions

Atom    : 1.16.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0

### Additional Information

Running Arch Linux.

**Comment by rsese** [comment]
> Electron: 1.4.16

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).
