### ISSUE TITLE
How to move to the last cursor position?

### ISSUE THREAD

**Issue by avi123456** [atom/atom#14215]
Hi,
I'm using a mac with Atom as a python IDE.
I want to move to the last cursor position.
How could this be done?

Thanks

**Comment by rsese** [comment]
Like I mentioned in your other issue, we require the issue template to be filled out completely.  

Additionally, because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
