### ISSUE TITLE
Atom can't locate modules

### ISSUE THREAD

**Issue by avi123456** [atom/atom#14214]
I'm using atom as a python IDE.
 
When I try pressing some imported module (command + left click), in order to go to it's code, sometimes it seems to be working, and other times it does not.
 
How could this be resolved?
 
Thanks,

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by avi123456** [comment]
Thanks for your response.
Where can I ask my question? 
I have posted it in https://discuss.atom.io/new
Is that ok?

**Comment by rsese** [comment]
Yes, the Atom message board is a great place to ask questions :+1:
