### ISSUE TITLE
Concatenate the directory name with the child's name when it has only a directory.

### ISSUE THREAD

**Issue by GustavoDinizMonteiro** [atom/atom#14238]
When I open a directory that has just another directory inside, it should display the directories as one with the name that is the concatenation of the parent's name with that of the child.

**Comment by rsese** [comment]
Thanks for reaching out!

For completeness, we require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by 50Wliu** [comment]
Enable the "Collapse directories" option in the Tree View settings.
