### ISSUE TITLE
Ubuntu 17.04 unsupported

### ISSUE THREAD

**Issue by tatsujb** [atom/atom#14235]
Right now the .deb package distributed from the website is for 16.04 and under only and refuses to install on ubuntu 17.04.

**Comment by rsese** [comment]
Thanks for reaching out!

For completeness, we require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
