### ISSUE TITLE
Uncaught TypeError: el.getAttribute is not a function

### ISSUE THREAD

**Issue by yacut** [atom/atom#14231]
Steps to reproduce:

1. Create a dock pane
2. Select some element on the pane
3. Drag the selected element

**Atom**: 1.17.0-beta2 x64
**Electron**: 1.3.14
**OS**: elementary OS
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: el.getAttribute is not a function

```
At /usr/share/atom-beta/resources/app/src/workspace-element.js:283

TypeError: el.getAttribute is not a function
  at isTab (/usr/share/atom-beta/resources/app/src/workspace-element.js:283:12)
  at atom-workspace.handleDragStart (/usr/share/atom-beta/resources/app/src/workspace-element.js:141:10)

```

### Commands

```
     -1:13.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
active-editor-info 0.0.0 
atom-beautify 0.29.22 
atom-fuzzy-grep 0.16.0 
atom-jasmine 0.8.1 
atom-ternjs 0.18.2 
atom-typescript 11.0.1 
autocomplete-modules 1.6.9 
autocomplete-paths 1.0.5 
clipboard-plus 0.5.1 
compare-files 0.8.0 
cson 2.0.1 
cucumber 0.6.0 
docblockr 0.9.4 
docker 0.7.0 
docs-snippets 0.8.0 
editorconfig 2.2.2 
escape-utils 0.5.3 
file-icons 2.1.3 
from-and-to-json 1.0.0 
git-blame 1.0.1 
git-plus 7.5.0 
git-split-diff-hyperclick 0.3.12 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick 0.0.40 
js-hyperclick 1.10.1 
language-babel 2.57.3 
language-docker 1.1.7 
language-ini 1.19.0 
language-thrift 1.0.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-docker 0.2.0 
linter-eslint 8.1.6 
linter-flow 5.5.1 
linter-jsonlint 1.3.0 
linter-tslint 1.0.0 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
nuclide 0.217.0 
pdf-view 0.57.0 
pigments 0.39.1 
project-manager 3.3.4 
script 3.14.1 
set-syntax 0.3.2 
sort-lines 0.14.0 
split-diff 1.3.0 
sync-settings 0.8.1 
tester 0.4.6 
tester-jest 0.4.0 
tester-mocha 0.3.0 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 0.89.0 
vim-mode-plus-ex-mode 0.9.0 
```

**Comment by TomYeoman** [comment]
Hi team, I've been able to reproduce this on a fresh install, with no plugins other than core.

Steps to reproduce for me:

1) Open atom (First launch after install, with 0 packages installed)
2) Click on "Hack on the init script" on landing page
3) Error now appears (I think it was as the accordion dropped down. although may have been when I clicked "Open your init Script" button)

It doesn't seem like I can consistently replicate this but hopefully this gets you a little closer to understanding the issue.

Atom version: 1.17.0-beta3

**Comment by Ben3eeE** [comment]
I was able to reproduce using the steps @TomYeoman posted. It happens when you drag text in the welcome guide, see gif:
![el-getattr](https://cloud.githubusercontent.com/assets/1058982/25171988/f7d0a04e-24ef-11e7-9440-516fc8541261.gif)

**Comment by TomYeoman** [comment]
Good spot @Ben3eeE must have highlighted something when messing around on the page. I'd like to start contributing to the atom project is this something I could look @ myself or what's the process?

**Comment by Ben3eeE** [comment]
@TomYeoman We will definitely accept a well written PR for this. A well written PR for a regression would provide information on why it stopped working and an explanation of the changes you have made to solve the problem. Regressions might not be the best choice for a first contribution since they can be prioritized for an upcoming hotfix release.
In the [contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#your-first-code-contribution) you can find information on contributing to Atom and how to find issues where we want help from the community and will accept PRs. 

If you have any more questions please feel free to contact me on Slack.

----

For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by c0fe** [comment]
Dragged by tab up and down and received this error:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: el.getAttribute is not a function

```
At C:\Users\Vlad\AppData\Local\atom\app-1.17.0\resources\app\src\workspace-element.js:283

TypeError: el.getAttribute is not a function
    at isTab (~/AppData/Local/atom/app-1.17.0/resources/app/src/workspace-element.js:283:12)
    at atom-workspace.handleDragStart (~/AppData/Local/atom/app-1.17.0/resources/app/src/workspace-element.js:141:10)
```

### Commands

```
     -1:05.2.0 tabs:close-all-tabs (div.title)
```

### Non-Core Packages

```

```
