### ISSUE TITLE
apm changes home and thus ignore regulare .gitconfig

### ISSUE THREAD

**Issue by YannBrrd** [atom/atom#14267]
HOME environment has been set to %USERPROFILE%\.atom\.node-gyp during plugin installation, which may provock an failure in plugin installation

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
