### ISSUE TITLE
I would like to have permission to publish your app on the Windows Store

### ISSUE THREAD

**Issue by dgsimone15** [atom/atom#14279]
Hi, I'm part of the UWP Open Source Community (https://github.com/UWP-Open-Source-Community). Our intent is to take Win32 Open Source applications and convert them into UWP apps through the Windows Bridge (Project Centennial).
We like your app and that's why we decided to convert it.
In case you would like to take charge of this app and publish it yourself on the store (make us very pleased) contact us the first possible please! Otherwise, we may be responsible for publishing your app.
If you do not want to take over the publication on the Store, can you give us permission to do so?
Sorry for my poor English.
Thanks for your help.

**Comment by lee-dohm** [comment]
Thanks for your interest in Atom!

We don't have any plans on publishing Atom to the Windows Store (or any other platform's store-like feature) at this time. The primary reason being that all of them place restrictions on apps that are problematic with regard to Atom's use as a programmer's editor, whether restricting free access to the user's entire file system or restrictions on downloadable extensions like the packages made available on https://atom.io. We also feel that the Atom installer and auto-update process makes the primary benefits of the Windows Store, easy installation and updating, unnecessary.

With regard to granting permission for others to publish Atom to the Windows Store, the [source code license](https://github.com/atom/atom/blob/master/LICENSE.md) grants you permission to fork the Atom source code. But "Atom" and the Atom logo are trademarks of GitHub, Inc and we are not granting permission for others to publish their fork using the Atom name or logo. So, no, I cannot grant permission for you to publish Atom to the Windows Store. And while, technically, you are within your rights under the license to completely rebrand the source code and publish it under a new name and logo, we believe that the users are best served obtaining Atom only through the official mechanisms, namely via https://atom.io. If you have any further questions, please feel free to contact us at atom@github.com.

Thanks again for reaching out!

**Comment by dgsimone15** [comment]
Thank forum tour response!!!

**Comment by duble0** [comment]
@lee-dohm
Hi! I'm Francesco Venuti and I founded UWP Open Source Community, dgsimone15 already contacted you about UWP, but you didn't seem to understand our intentions, so let me explain better ...
We are a team of Windows lovers and developers without any scope of make money. We would only improve our OS ... in the last year Windows 10 has improved a lot, for example today also incorporates a Linux Subsystem (WSL)... Now Microsoft also engaged the mobile challenge, it seems that they would change the concept of mobile computing ... so not just a smartphone, but real desktop experience that could run on ARM devices like tablets and smartphones (connected with a monitor).
We saw the preview of "Windows Colud Edition", this could be the next edition of Windows for education PC (like Chromebooks). Unfortunately for running win32 software on this edition, the software must be converted into UniversalWindowsPlatform app; after conversion, the software could run even on regular Windows 10 editions. If this could be a problem, you should consider the opportunities like: all UWP could use a telemetry to send information about problems to developer, guarantee automatic update every time you emprove your software, could impact on a larger and younger user base that can give You feedback and also start developing your software.
Furthermore distributing your software as UWP mean that your software run in a sandbox that don't compromise the OS if there are problems.
We don't want make a copy of your work, rather we prefer YOU start publish also on Windows Store as alternative distribution to traditional installer.
We tried the online tool made by Microsoft for convert win32 software to UWP app, if you would use our work to start your experience on Microsoft Store we are pleased to give you all materials and information. Don't be scared about shadow costs, for publish on Microsoft Store you pay only the first time as developer registration, because your app will FLOSS, so there are not fee!
For us is important start Windows Cloud with a large amount of open source apps available for every one.
Scuse me for poor English...😉

**Comment by lee-dohm** [comment]
Hello Francesco. I believe I understand your intentions. Thank you for the extra information. Let me address your points one at a time:

> but real desktop experience that could run on ARM devices like tablets and smartphones (connected with a monitor).

The editor that we want Atom to be isn't designed for mobile devices. Though we have investigated running Atom on low-power desktop ARM devices such as the Raspberry Pi, and some community enthusiasts are building a version that works there, see https://github.com/atom/atom/issues/7822 for details.

> could impact on a larger and younger user base that can give You feedback and also start developing your software.

You may be correct that building an editor that runs on a different type of device would tap into a different market or user base, but that's still not the kind of product we want to make.

> use a telemetry to send information about problems to developer

We already have this via our [metrics](https://github.com/atom/metrics) and [exception-reporting](https://github.com/atom/exception-reporting) packages.

> guarantee automatic update every time you emprove your software

We also have this capability built-in. Additionally, we don't have to go through a third-party's review process in order to publish these updates. If we fix a bug, we can publish it right away and our users can get it the next time they launch Atom. (Or they can disable that if they want too, for example when they have to pay for bandwidth use.)

> your software run in a sandbox that don't compromise the OS if there are problems.

That is actually one of the restrictions that prevents Atom from being used as a programmer's text editor that I mentioned in my previous post: "restricting free access to the user's entire file system". We agree that running in a sandbox is probably best for the majority of apps, just not for a software developer's text editor like Atom. If we wanted a sandbox, we wouldn't have invested all the [effort in circumventing the built-in sandbox of the web technologies we employ to build Atom](http://blog.atom.io/2014/02/26/the-nucleus-of-atom.html).

I appreciate your enthusiasm. Your suggestion isn't the first time we've heard this feedback. This is something that we have thought a lot about over the years, the kind of editor that we want to build, that we want Atom to be and how to best make it available to people. We don't want to make an editor for mobile devices. We do want to make Atom available to the widest reasonable audience we can on desktop-style machines, that's why we support Windows, macOS and Linux. And we already have the capabilities that you're offering on all three major desktop platforms.

Because of all of the above, we have no plans currently to offer Atom via the Windows Store (or any other platform's equivalent). Thanks again for your well-written feedback :+1:

**Comment by paulcbetts** [comment]
Centennial apps (i.e. Win32 apps on Store) don't actually get sandboxed user filesystems (mostly), Atom could be put into the Windows Store and mostly work with some effort. You also don't have to go through any real review process either, it's quite fast.

That being said, I don't really see any _advantage_ to being in the Store either other than being a dog whistle to Microsoft enthusiasts (a legitimate plus if you're targeting that market!), and it'd just be another platform that you'd have to deal with and test.

**Comment by duble0** [comment]
Scuse me for the duplicate.

@lee-dohm 
> The editor that we want Atom to be isn't designed for mobile devices. Though we have investigated running Atom on low-power desktop ARM devices such as the Raspberry Pi, and some community enthusiasts are building a version that works there, see #7822 for details.

@paulcbetts 
> That being said, I don't really see any advantage to being in the Store either other than being a dog whistle to Microsoft enthusiasts (a legitimate plus if you're targeting that market!), and it'd just be another platform that you'd have to deal with and test.

@lee-dohm  The only part of your tought that I'm disagree is in the underestimation of potential about Windows on arm. As you can see in the next links, Microsoft is in partnership with Qualcomm and start using ARM architecture for her servers. Microsoft has also demostrated that Windows On Arm could run Photoshop on a Snapdragon 820 processor, that is largely used on smartphones. Check it: [http://www.zdnet.com/article/windows-server-on-arm-its-happening/
](url)
[http://www.theverge.com/2016/12/8/13881800/microsoft-demonstrates-full-windows-10-with-photoshop-on-arm-chips](url)
Furthermore the barrier between mobile device and personal computer is every year more tight...
check for example this solutions that use Continuum mode to transform a display or a portable display with keybord in a "traditional pc":
[https://www.youtube.com/watch?v=hBU84C9tSao](url)
this example was made with windows10mobile that is a pure mobile OS, but the next step is a complete windows experience with Windows on Arm.
Something similar is made also on Android by Samsung with DeX:
https://www.youtube.com/watch?v=G_Zdq0AjhXo
So I think you need to ask you some questions...where go the future? new generations have more affinity with apps than with pc software...when I was young the informatics students want know Linux, nowdays the students want know how write apps...
I suppose that windows is in your interests if you distribute .exe installer...so, what is the problem to distribute .appx on store?
Any other technical objection is correct, but can be overcome...

**Comment by paulcbetts** [comment]
Centennial apps don't run on ARM, and WOA is mooooostly dead

**Comment by duble0** [comment]
@paulcbetts I'm sorry but in my opinion you are not well informed. UWP (Centennial or native) work everywhere there is a complete Windows10 experience: WindowsOnArm is a complete desktop experience and is very different from Windows10mobile(which also run on ARM). I know that in past also WindowsRT was called WoA, but actually Windows on Arm is quite different. So Centennial UWP can't run on Windows 10 Mobile but only on Windows 10 (with or without ARM architecture).
If you see the link above, you can see a regular Adobe Photoshop run on ARM, you can't distinguish a Centennial UWP from a regular desktop software when starting it!

**Comment by duble0** [comment]
Hi @lee-dohm ! Have you tought to the situation? I don't think that is correct see this situation like: "our Vs your vision" because there are different people needs differents solutions and not exist a correct or wrong. Are you agree?

**Comment by lee-dohm** [comment]
@duble0 I've given you the answer that I have for you which is that we have no plans currently to publish Atom to the Windows Store.

It's obvious that you disagree with our reasoning but as I said before, you're not presenting anything new. The Atom maintainer team is made up of a diverse group of industry professionals, some of us have even worked at Microsoft in the past. We're aware of the trends in the industry, the shift in consumer use away from desktop-style hardware and applications to mobile-style hardware and apps [1], and the use of ARM as a processor architecture. Given all of that, we still have come to a different conclusion from you. Sometimes disagreements between equally informed, equally knowledgeable and equally experienced people do occur. This is one of those times.

[1] As a matter of fact, I even wrote [a blog post seven years ago predicting this shift](http://www.lee-dohm.com/2010/08/08/files-are-an-implementation-detail/)

**Comment by duble0** [comment]
Thank you @lee-dohm! An answer is ever better than silent...we are writing to others developers for other softwares, someone is interested and others, like you, don't beliving in this technology...for us isn't a terrible discovery. The important thing is that you are conscious of possibilities.
