### ISSUE TITLE
i dont see node_modules folder on the Editor , why ?

### ISSUE THREAD

**Issue by jpca999** [atom/atom#14281]
I understand you guys are busy, but when get tie, please let me know. 

![3__jay_jai____movies_dev_meteor_js_stephen-gridr-code_images__zsh__and__gitignore_ ___movies_dev_meteor_js_stephen-gridr-code_images_and_011-first-react-component_and_stephengridr_ meteor___react_ _evernote_basic](https://cloud.githubusercontent.com/assets/1026325/25307265/e9136342-276b-11e7-9e4e-a490e94fb0b8.jpg)

**Comment by ericcornelissen** [comment]
I think [this discussion](https://discuss.atom.io/t/gitignored-files-are-hidden-from-tree-view-regardless-of-setting/8724) might help you 🙂 It seems Atom is hiding the files ignored by your `.gitignore` file, but this can be disabled as explained in the discussion

**Comment by jpca999** [comment]
awesome!

**Comment by ericcornelissen** [comment]
The tree view is a package in Atom. If you go to your Setting (shortcut: `ctrl`+`,`) and head on to "Packages", there you can search for `tree view`. Click on "Settings" button of the "tree-view" package, and there you'll find the option 👍

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
