### ISSUE TITLE
Need a way to auto save the files upon changes are made , can't find any package for that. 

### ISSUE THREAD

**Issue by jpca999** [atom/atom#14282]

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
