### ISSUE TITLE
how do  i remove the Add project folder and add remove project folder from my atom  ide ?

### ISSUE THREAD

**Issue by jpca999** [atom/atom#14280]
![image](https://cloud.githubusercontent.com/assets/1026325/25307034/410968e8-2768-11e7-8365-afdf39658296.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by jpca999** [comment]
lol thats a lot of work ..

**Comment by 50Wliu** [comment]
It is more work for us if you do not fill out the issue template.  We will not be able to help you if you don't.
