### ISSUE TITLE
can't build 1.17 beta 3

### ISSUE THREAD

**Issue by mpkh** [atom/atom#14286]
```
Generating snapshot script at "/var/tmp/portage/app-editors/atom-1.17.0_beta3/work/atom-1.17.0-beta3/out/startup.js" (192)Error: ENOENT: no such file or directory, open 'exception-reporting'
  at Error (native)
  at Object.fs.openSync (fs.js:641:18)
  at Object.fs.readFileSync (fs.js:509:33)
  at /var/tmp/portage/app-editors/atom-1.17.0_beta3/work/atom-1.17.0-beta3/script/node_modules/electron-link/lib/generate-snapshot-script.js:28:27
  at undefined.next (native)
  at step (/var/tmp/portage/app-editors/atom-1.17.0_beta3/work/atom-1.17.0-beta3/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /var/tmp/portage/app-editors/atom-1.17.0_beta3/work/atom-1.17.0-beta3/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361

```

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by conraid** [comment]
I have the same problem in Slackware 64 current trying to compile atom 1.17.0 and atom 1.18.0-beta0, trying with node 6.9.1 or with node 7.10.0 (I know that the max version in verify-machine-requirements.js is 6), npm is 4.6.1.
Same error.
I build packages for a Slackware repository, how can I make with this error?

**Comment by mpkh** [comment]
bug is gone for me, I don't know what were causing it

**Comment by conraid** [comment]
The problem is line 9 in script/lib/generate-startup-snapshot.js
const snapshotScriptPath = path.join(CONFIG.buildOutputPath, 'startup.js')
looking for startup.js that does not exist. 
I did a search in every directory created by the build process but it does not exist.

I'm sorry for my bad english

**Comment by conraid** [comment]
With git master:

Generating snapshot script at "/opt/slackers/git/esterni/atom-build/atom-git/out/startup.js" (188)Error: ENOENT: no such file or directory, open 'exception-reporting'
  at Object.fs.openSync (fs.js:584:18)
  at Object.fs.readFileSync (fs.js:491:33)
  at /opt/slackers/git/esterni/atom-build/atom-git/script/node_modules/electron-link/lib/generate-snapshot-script.js:26:27
  at Generator.next (<anonymous>:null:null)
  at step (/opt/slackers/git/esterni/atom-build/atom-git/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /opt/slackers/git/esterni/atom-build/atom-git/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361
