### ISSUE TITLE
Atom tree view not working 

### ISSUE THREAD

**Issue by repo2kanagaraj** [atom/atom#14299]
Tree view not working in beta3 1.17 

OS: ubuntu 16.04

Steps to reproduce 
1) Start the Atom editor
2) Open tree view 
3) Expand the folders
4) Then it will not work

**Comment by hg42** [comment]
what exactly will not work?
I can expand folders and use the tree view as expected with 1.17.0-beta3 x64 and Debian testing.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
