### ISSUE TITLE
any plugin or way to grab the path when i drop the file on the editor ?  Like textmate does it ?

### ISSUE THREAD

**Issue by jpca999** [atom/atom#14292]
when i drop the file, it should make the path by itself.  

I waste lot of tiem figuring this out. 

![main_js_ ___movies_dev_meteor_js_stephen-gridr-code_shortnlink](https://cloud.githubusercontent.com/assets/1026325/25362940/ec63da58-2924-11e7-86ba-2546e3cdbf43.jpg)

**Comment by rsese** [comment]
Thanks for reaching out!  The Atom message board is the best place for questions like this:

https://discuss.atom.io

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
