### ISSUE TITLE
Code on line wrapping back and forth at same pace as cursor blinking

### ISSUE THREAD

**Issue by adamreisnz** [atom/atom#14305]
Hi team, not sure what package repository to file this issue, so I've just made a recording hoping you can point me in the right direction or shed some light on this behaviour:

https://www.dropbox.com/s/lpkybtzkarehyla/madness.gif?dl=0

Focussing the cursor on the affected line caused it to start dancing at about triple the frequency, but that's not visible in the recorded GIF's as the frame rate is too low.

Widening the editor window caused the dancing to stop.

This was experienced with Atom 1.17.0-dev-4a1f98c on OS X.

**Comment by rsese** [comment]
Hey @adamreisnz - I think this repo is the right one but we do require the issue template to be filled out completely.  If you edit your issue body to fill out the template, feel free to re-open the issue.

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by adamreisnz** [comment]
@rsese It's your prerogative as repo owner to insta-close any issue you don't like or that don't adhere to your template, but I have filed dozens if not hundreds of valid Atom bugs over the course of the last few years across many different core packages, as well as helped to refine or test certain features and issues. Heck I've been filing issues for Atom even before there were any issue templates. So I'd like to think that I have a pretty good understanding of what package an issue relates to, or what additional information might be needed to tackle an issue.

I understand why the Atom team wants people to fill out that template, and I often do when I can spare the time and an issue is really bothering me and easily reproducible, but sometimes, like in this case, an issue could just be a fluke and it might not be worth the time or effort to jump through all the proper issue reporting hoops. Or you just know that if you restart in safe mode it's not going to happen anymore due to some other minor differences or simply due to the fact you restarted at all. 

I love Atom, I use it daily, and if it weren't coded in Coffeescript (:nauseated_face:) I would have actively participated in its development and maintenance and tried to figure out and fix weird stuff like this myself rather than raise an issue about it.

But I consider issues like this to be edge cases with a minor impact overall, and so I raise them here as a courtesy to the Atom team, not to be a pain in the ass. Maybe next time you can consider that before shoving it under the rug immediately.

**Comment by lee-dohm** [comment]
Hey Adam. Thanks for the bug report and for all the work that you've done to help us out. We don't think and are certainly not implying that anyone, least of all you, is being a pain in the ass when filing an issue.

But we do have a huge number of open issues and pull requests to manage. And people are, rightfully, expecting that we be more responsive on the issues and PRs that they bring us. One of the ways that we're trying to handle things faster is by encouraging people to get us more information up front, by expecting people to fill out the templates. If people see that the template says its required but it isn't actually required ... then fewer and fewer people fill it out until the template is useless. And then we're back to the old system of bugs piling up because we're trying to get information out of people that we asked for in the CONTRIBUTING guide, and the template, and in Slack, and on the message board and in the Flight Manual.

If you have suggestions on how we can make the template less of a pain in the ass for you when you just want to report something simple, I'd love to hear them so that I can make the templates better. Or maybe an even better system than using the templates period. Unfortunately, until we have something better in place, we are going to have to stick with the system we have. I hope you can keep working with us by helping us improve our bug reporting system.

Thanks again for all of your myriad contributions to Atom.

**Comment by adamreisnz** [comment]
@lee-dohm Thanks for your reply. Yes, I do understand the need for the template as I am aware of how fast the issues can pile up. I will give it some thought and see if there's a way to make it easier to report simple issues quickly.

**Comment by lee-dohm** [comment]
@adamreisnz Thanks so much! I really appreciate you helping us out with all of this :bow:

**Comment by hg42** [comment]
I switched to Atom recently and was shocked the first time I saw an issue was rejected. I understand why you are doing this but I think you should change the way how it is done. The current method does not take into account several aspects.

Where can we discuss this and give suggestions?

**Comment by Ben3eeE** [comment]
@adamreisnz This issue looks like https://github.com/atom/atom/issues/13769

@hg42 The best place to discuss this would be on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or [Join the Atom Slack team](http://atom-slack.herokuapp.com/) and discuss there. You can also find out more information about why we have chosen to manage our issues this way in [this blog post](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

**Comment by adamreisnz** [comment]
@Ben3eeE you're right, it looks like that's a similar or the same issue

**Comment by adamreisnz** [comment]
@lee-dohm So in my opinion, one problem is the wording around the Prerequisites section in the issue template and the single checkbox to rule them all. I think this section could be improved a bit to feel less hostile.

First of all, the section title "Prerequisites" can be changed to something which sounds a bit friendlier and less demanding, like "Steps taken". This suggests that you give the issue filter the benefit of the doubt, and assume they know what they're doing (even if they don't), instead of mandating that they must follow every rule in this section.

Second, having the single checkbox is problematic as well, because not everything applies to every issue. For example, I am not going to go through the FAQ if I'm raising an issue that I'm positive is a genuine bug, nor am I going to check if there's a package with existing functionality if I'm filing a bug. So by checking the checkbox it, I'm essentially forced to lie. But there's no alternative other than not checking it (even though I did *some* of the items) or not filing the issue.

So maybe a friendlier approach is to simply ask people to mark anything they *have* done, and allow them to check items individually. That way, you will get actually proper visibility over what they have and haven't done, and can target the problems (if any) a bit better. So instead of an all or nothing approach you can give people the benefit of the doubt but still encourage them to take as many steps as possible up front.

Third, I would recommend to categorize the steps so people only have to go through the steps relevant to their issue type (e.g. bug, feature request).

So for example:

### Steps taken

- [ ] **This is a bug report**
  - [ ] I have checked that my issue [isn't already filed](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom)
  - [ ]  I have reproduced the problem in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)
  - [ ] I have tried to narrow down which package is causing the error using [Package Cop](https://atom.io/packages/package-cop)
  - [ ] I have followed all applicable steps in the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)
  - [ ] I have checked the [FAQs on the message board](https://discuss.atom.io/c/faq) for solutions to common issues

- [ ] **This is a feature request**
  - [ ] I have checked that there is not already an [Atom package](https://atom.io/packages) that provides the described functionality
  - [ ] I have [checked that my feature request isn't already filed](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom)
  - [ ] I have checked the [FAQs on the message board](https://discuss.atom.io/c/faq) for common solutions

- [ ] **This is a general query**
  - [ ] I have already asked on the [Atom message board](https://discuss.atom.io) and nobody could answer the question
  - [ ] I believe my question can only be answered by the Atom maintainers

Just an idea of course, but you can take from it what you like.

**Comment by lee-dohm** [comment]
Thanks for the suggestions @adamreisnz. I'll take it back to the triage team and we'll take a look to see what changes we want to make. I can say right off the bat that we got feedback on the initial issue template that:

* Five checkboxes was too confusing (so 13, though better organized, is probably going to be too much also) 
* `[Markdown links](https://example.com)`, while very pleasant in rendered form, are hard to read in text form ... which is why we use the raw URL now

I think asking people to mark things they have done is a good suggestion.

Thanks again for your feedback :heart:

**Comment by adamreisnz** [comment]
Gotcha, about the links. As for the checkboxes, yes I noticed it changed at one point from multiple to the single one. I personally think the opposite is true, as long as the checkboxes are properly readable. I guess the handicap we have is that they aren't rendered markdown that a user can easily mark, so with the links in it it can get a bit messy.

**Comment by lee-dohm** [comment]
@adamreisnz Please take a look at https://atom.io/packages/town-crier. I went one step further than redoing the templates and just built a package for submitting bugs to Atom and Atom packages. For the most part it is a translation of the current template though it is targeted specifically at bug reports. I expect to make separate functions for bugs, enhancements and questions that generally follow your suggestions above. My intention is to eventually bundle it with Atom and have it be the official way to submit feedback. Let me know what you think!

**Comment by adamreisnz** [comment]
That sounds pretty cool, I'll install it tomorrow and have a play with it!

**Comment by adamreisnz** [comment]
@lee-dohm it looks good, I think this will make submitting bugs a lot easier for most people. It would be great to have separate forms for bugs, enhancements and questions.

Some feedback/questions:

- The list of packages to select from is pretty huge and could be daunting for users. Perhaps if there's a way to split it up in core/userland packages, or even categorize them somehow so it makes it easier to find the package you're looking for that'd be great.
- I would make the expected/actual fields a multiline input, often I find myself needing more than just one line to explain properly what the scenario's are.
- Why is the OS field editable?
- How would you handle duplicate reports if a bug has already been submitted?
- How would you encourage people to try safe mode first (if applicable)?

**Comment by lee-dohm** [comment]
1. Please open an issue on atom/town-crier (or I'll attempt to do it justice when I get a chance)
1. Everything can always be edited after it is submitted, I'd rather optimize for the common case
1. Because the OS version detection code isn't perfect
1. The same way that we handle them now
1. See https://github.com/atom/town-crier/issues/10
