### ISSUE TITLE
'Save' for a new file should open within the current project directory

### ISSUE THREAD

**Issue by moenka** [atom/atom#14304]
When creating a new file with Ctrl+N and later saving this file the save dialog starts somewhere within my 'recently used' directory so I need to go through the hassle of navigating to the project directory.

It would be a great thing if the save dialog starts in the current project directory as it is to expected that I want to save it anywhere down there. In really seldom situations I want to save the file outside of the project directory (e.g. in the /tmp directory for a test or so).

I think of this as a bug more then a feature or improvement as it breaks my work flow.

This is what I personally thing. Can't speak for others.
I would appreciate it if this is an option to toggle.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
