### ISSUE TITLE
Uncaught exception when trying to open devtools in atom-html-preview

### ISSUE THREAD

**Issue by codekip** [atom/atom#14308]
### Description

Error when trying to open devtools in atom-html-preview

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-html-preview](https://github.com/webBoxio/atom-html-preview) package 0.1.22

### Stack Trace

Uncaught Error: Cannot call openDevTools because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

```
At C:\Users\Nick\AppData\Local\atom\app-1.16.0\resources\electron.asar\renderer\web-view\web-view.js:412

Error: Cannot call openDevTools because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at webview.openDevTools (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/renderer/web-view/web-view.js:412:15)
    at /packages/atom-html-preview/lib/atom-html-preview-view.coffee:125:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:16.8.0 atom-html-preview:open-devtools (webview.)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-bootstrap3 1.2.12 
atom-css-comb 3.1.0 
atom-html-preview 0.1.22 
browser-plus 0.0.87 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.3 
lorem-insults 0.2.0 
minimap 4.27.1 
my-theme-syntax 0.0.0 
platformio-ide-terminal 2.5.0 
```

### Steps to Reproduce

1. Right click in HTML preview window
2. Select 'open devtools'
3. Error above shown

**Expected behavior:** [What you expect to happen]
Devtools to open

**Actual behavior:** [What actually happens]
Error message is shown

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Windows 10
apm version: 1.16.1
atom version: 1.16.0

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-html-preview](https://github.com/webBoxio/atom-html-preview) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
