### ISSUE TITLE
application.json resets upon application closing.

### ISSUE THREAD

**Issue by RyanIMinnick** [atom/atom#14307]
application.json resets to ```[]``` upon closing the application, meaning my previous file tree is removed and I have to manually re-open it every time. I have deleted and reinstalled the application several times, including removing Users/me/.atom

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by RyanIMinnick** [comment]
@rsese Okay, where can I find the template? Also, should I edit the current thread, or make a new issue?

**Comment by 50Wliu** [comment]
The template should appear automatically when you try to create a new issue.  Please make a new one rather than editing this one.
