### ISSUE TITLE
Can'

### ISSUE THREAD

**Issue by Tectract** [atom/atom#14317]
### Description

Notifications appear. I want them to NOT appear. EVER!!!

### Steps to Reproduce

Open two files. Switch tabs. A notification appears telling you the filename. MAKE IT STOP!! MAKE ALL THE POPUP NOTIFICATIONS STOP, FOREVER!!!

**Expected behavior:** [What you expect to happen]

No notifications.

**Actual behavior:** [What actually happens]

Intrusive notifications.

**Reproduces how often:** [What percentage of the time does it reproduce?]

ALL THE TIME. SO DISTRACTING!!!

NOTIFICATIONS ARE POPUPS. POPUPS ARE MALWARE.

**Comment by hg42** [comment]
I don't see popups when switching tabs. You didn't include the first part of the template.
Did you try all these? especially --safe?

**Comment by lee-dohm** [comment]
Besides @hg42's suggestion of using [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), you should also be able to disable the Notifications package to disable all notifications. If you do that though, when uncaught exceptions happen, the Developer Tools will open. Personally, I think the notification is a better system.

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way.
