### ISSUE TITLE
Atom crashing on Ubuntu (14.04.3)

### ISSUE THREAD

**Issue by RDiotallevi** [atom/atom#14326]
"The editor has crashed" when trying to open Atom on Ubuntu (Trusty Tahr, 14.04.3)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
