### ISSUE TITLE
esc button dosen't work

### ISSUE THREAD

**Issue by gaoshijun1993** [atom/atom#14328]
esc button just can't close the search panel,I have googled and tried all the solutions but didn't word for me,here are my keybinds:

escape	tool-panel:unfocus	Core	.tool-panel.panel-left, .tool-panel.panel-right
escape	editor:consolidate-selections	Core	atom-text-editor , atom-text-editor[mini]
escape	core:cancel	Core	body
escape	autocomplete-plus:cancel	Autocomplete Plus	atom-text-editor.autocomplete-active
escape	core:cancel	Go To Line	.go-to-line atom-text-editor[mini]
escape	core:cancel	Tree View	.tree-view-dialog atom-text-editor[mini]

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
