### ISSUE TITLE
Atom for windows can`t install

### ISSUE THREAD

**Issue by lgw666** [atom/atom#14333]
I used the "AtomSetup-x64.exe" and it said " Failed to extract installer".

**Comment by rsese** [comment]
We require the issue template to be filled out with new issues but you also might want to check out https://github.com/atom/atom/issues/7915.

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
