### ISSUE TITLE
Unable to resolve path to module Error

### ISSUE THREAD

**Issue by casserni** [atom/atom#14336]
There is a "unable to resolve path to module" linter error that occurs when atom is run from the terminal, but the error does not occur when sudo atom is run. Linter runs fine separately, so is it an issue with the start up script? 

[https://cl.ly/2Z1E0f3l3p36]

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
