### ISSUE TITLE
Autoreloading changed files does not work with multiple files

### ISSUE THREAD

**Issue by astralaster** [atom/atom#14351]
### Description

The automatic reloading of files which have changed only works reliable without many tabs.

### Steps to Reproduce

1. Open one file with atom.
2. Change it external. (you should see the changed version in atom)
3. Open 3 more files with atom.
4. Redo step 2. (the chance is high that atom misses the update and shows the old version of the file)

**Expected behavior:** Atom should always show the current state of the file opened.

**Actual behavior:** Atom misses updates of opened files and sometimes shows old states.

**Reproduces how often:** It misses 9/10 updates with 4 tabs open.

### Versions
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

I only used normal txt files with 20-50 lines each. And Im using windows 7 64bit.

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if you can reproduce in safe mode as well (`atom --safe`)?

Also, for your step 2 when you say:

> 2. Change it external. (you should see the changed version in atom)

Can you confirm what you did specifically?  E.g. did you open the file in Notepad and change 1 character?  Knowing exactly what you did will help when trying to reproduce.

---

For future issues, please fill out the issue template completely (e.g. the part that confirms that you've tried the prerequisite steps like trying in safe mode).

**Comment by astralaster** [comment]
I can reproduce it in safe mode as well. I get this behaviour with a selfdeveloped c++ tool, but I cannot share the tool. I will try to export the writing functionality to a simple tool and share that.
But Ive checked the messages with process monitor and found some interesting messages:

High Resolution Date & Time:	05.05.2017 13:29:15,5872384
Event Class:	File System
Operation:	QueryAllInformationFile
Result:	BUFFER OVERFLOW
Path:	*EDITED*
TID:	3588
Duration:	0.0000090
CreationTime:	06.04.2017 14:03:51
LastAccessTime:	12.04.2017 16:37:45
LastWriteTime:	05.05.2017 13:29:15
ChangeTime:	05.05.2017 13:29:15
FileAttributes:	A
AllocationSize:	4.096
EndOfFile:	663
NumberOfLinks:	1
DeletePending:	False
Directory:	False
IndexNumber:	0x1000000005e36
EaSize:	0
Access:	Read Attributes, Synchronize
Position:	0
Mode:	Synchronous IO Non-Alert
AlignmentRequirement:	Byte

It looks to me like atom tries to reread the file before it is closed by the other tool?

**Comment by rsese** [comment]
> I can reproduce it in safe mode as well. I get this behaviour with a selfdeveloped c++ tool, but I cannot share the tool. I will try to export the writing functionality to a simple tool and share that.

I've run into a couple of issues where people mentioned issues when changing a file open in Atom from another program and it worked ok for me (i.e. Atom would reflect the external updates) but that was with a single file test and small edits (e.g. removing a line in Notepad).  But you mentioned 3 or more files and I'm not sure what kind of changes your tool makes so it does seem like a different situation to test.

**Comment by stratacast** [comment]
I am having a similar issue here with Atom now. I just switched from Fedora 26 KDE to Fedora 27 GNOME and just started getting this behavior. Couple sample situations:
1. I have a text file open in Atom, run a Python script that edits said file - Once the process is complete, Atom is clueless. I have to close the pane the file is in and reopen the file in Atom
2. I have a text file open in Atom and add or subtract a line with Gedit - same as 1. Once the file is saved from Gedit, I have to close the pane and reopen it in Atom to see the changes
3. Using mkdir to add a folder to an already opened folder in Atom - to see the newly added folder I have to close out of Atom and reopen Atom.

I have tried safe mode and even nuking everything in `~/.atom` and `~/.config/Atom` so it was 100% vanilla. I also Reinstalled Atom. I originally used Fedy to install Atom. My current install was grabbed straight from https://atom.io (.rpm) and installed with the rpm tool. 

Now it gets interesting. I don't have this issue on Fedora 27 GNOME on my laptop. Each OS install has the same filesystem layout even (/ on ext4 and /home on xfs). I copied `~/.atom` and `~/.config/atom` to my troubled machine and started Atom. Any project folder or file that was already open in Atom on my laptop would autoreload external changes as you would expect (this test is possible for me because most of my files I work on in Atom are in a synced folder). Then if I add a different file or folder again on my desktop in Atom, only those folders/files will show the failed autoreload behavior. I would love to try and give you more information if you wish to pursue this issue. Coding is KILLING ME right now not having my files refresh hehe

**Comment by phord** [comment]
I think I hit this today.  I had about 20 tabs open in two panes.  A file [vectors.cpp] was opened in both panes.  It was not flagged as modified in Atom.  

I did some commandline work in Git to pick and merge changes from another commit.  Two files were modified, including `vectors.cpp`.  When I returned to Atom I didn't see my changes.  I closed the vectors.cpp tab in Atom and reopened it expecting to see my changes.  They still weren't there.

This was confusing.  I checked `git diff` in my shell to confirm my changes were really there and I had the right file and path.  It all looked ok.

Back in Atom I then noticed the file was also open in the 2nd pane.  I double-checked that Atom didn't think the file had unsaved changes.  Then I closed both tabs for this file.  When I reopened it in Atom I could see my changes.

I probably had these two tabs open for at least a day and had Atom mostly unfocused during the past several hours before making my local changes to the file in my shell.

I tried to reproduce the problem by opening a test file in two tabs in two panes, but it updated as expected every time.

Atom 1.23.2
Ubuntu Linux 17.10

**Comment by phord** [comment]
I had this happen again a few minutes later with a different file.  I thought of something else which might be related.  In both cases the file was opened in two panes.  Also in both cases, there were merge conflicts encountered during my git cli work. 

Maybe it's a red herring, though.
