### ISSUE TITLE
Memory explode!

### ISSUE THREAD

**Issue by MartinSuGJ** [atom/atom#14350]
I connected the Kite for Atom. And when I open a python script and import a package, say SNAP(a python package for Social Network), and after several minutes, the memory of my mac just explode, increased from a normal level to an extremely high level. I don't know if this is a bug of Atom.

I tried to shut down the Kite, and reopened my python file, and everything is good. Nothing abnormal. And I also tried to open other python scripts, and it is good as well.

Therefore, I guess this might be the problems of Atom, Kite, and some special python packages. From the perspective of Atom, could you give me some advice?

The screenshot is as follow:
![atom_memory](https://cloud.githubusercontent.com/assets/15654140/25695571/8a54b972-3068-11e7-85a6-177c9031ba48.jpeg)

**Comment by 50Wliu** [comment]
Thanks for contributing!

Since the memory explosion only appears to happen when using Kite, I would suggest filing an issue there asking about it.  However, it may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by MartinSuGJ** [comment]
I think this is the problem of Kite and the Snap package of python.
