### ISSUE TITLE
Cannot read property 'nameOrSourceURL' 

### ISSUE THREAD

**Issue by ahpiau18** [atom/atom#14370]
ATOM version 1.16
Preference -> Install, when i type something in the search text box, it give me this error

Cannot read property 'nameOrSourceURL' of undefined [Hide output…]

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sky790312** [comment]
+1
