### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by KhairiAbidi** [atom/atom#14379]
<!--
### Description

[Description of the issue]
i tried to open Edit->Pereferences to install new packages

### Steps to Reproduce

1. ..
3. ...

**Expected behavior:** [Open pereferences in new tab]

**Actual behavior:** [Atom has crashed]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Atom**   : 1.16.0
**Electron** : 1.4.16
**Chrome**  : 53.0.2785.143
**Node**    : 6.5.0
**OS** : antergos linux x86_64

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
