### ISSUE TITLE
Error in atom for saving file.

### ISSUE THREAD

**Issue by mawk-khan** [atom/atom#14406]
I'm facing this issue from long back. I'm unable to save the file editor, But when running as administrator it save the file correctly. But previously it was working fine without running as administrator. Please help me to solve this issue. And also my atom connected with SourceTree to the files in the git repository.

Unable to save file 'C:\wamp\www\vamico\wp-content\themes\xyz\page.php'
EPERM: operation not permitted, open 'C:\wamp\www\test\wp-content\themes\xyz\page.php'

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
