### ISSUE TITLE
Wrong hightlight? Why this is happens?

### ISSUE THREAD

**Issue by wireinet** [atom/atom#14410]
why this is happens? pug  is strange work!  all is done well, i guess, but syntax  highlighting - is wrong...i try codepen - all is good

![wrong](https://cloud.githubusercontent.com/assets/23517333/26028375/cea7cb84-3827-11e7-8fc5-752bb04ad914.jpg)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by wireinet** [comment]
hello again!  now  i tested this out...only this extensions is work very well with hightlighting pug sintax-  https://atom.io/users/leonschwanitz
