### ISSUE TITLE
cannot create file, if there already exist same name folder

### ISSUE THREAD

**Issue by fewspider** [atom/atom#14423]
version `1.16.0`
mac `10.12.5 (16F73)`

cannot create file, if there already exist same name folder

**Comment by andyrichardson** [comment]
Hi there,

You've provided very little information about this issue. You need to explain:
1. What steps need to be taken for this issue to be arisen
2. What is the result following these steps
3. What did you expect the result to be

If you can answer these three questions, myself and others will be able to take the same steps and see if the same issue arises.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
