### ISSUE TITLE
click tree view file,  tree view will scroll.Sometime it click wrong file, not user expect

### ISSUE THREAD

**Issue by fewspider** [atom/atom#14422]
version `1.16.0`
mac `10.12.5 (16F73)`

Click tree view file,  tree view will scroll. Sometime it click wrong file, not user expect.
You can reduce this, if your tree view is expand too many.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
