### ISSUE TITLE
How can I remove the drawer icon?

### ISSUE THREAD

**Issue by kirkstrobeck** [atom/atom#14455]
v 1.17.0

![screen shot 2017-05-17 at 10 16 26 am](https://cloud.githubusercontent.com/assets/241963/26166863/e6f44860-3ae9-11e7-9315-4ecaf041a9e3.png)

**Comment by 50Wliu** [comment]
Please see the Discuss thread: https://discuss.atom.io/t/hide-the-new-tree-view-dock-toggle-button/42793/2?u=wliu

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
