### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jstnchristian** [atom/atom#14479]
[Enter steps to reproduce:]

1. Open a file in VIM

**Atom**: 2.4.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Applications/Learn IDE.app/Contents/Resources/app.asar/node_modules/learn-term.js/src/term.js:1306

TypeError: Cannot read property '0' of undefined
    at TerminalWrapper.Terminal.refresh (/app.asar/node_modules/learn-term.js/src/term.js:1306:18)
    at TerminalWrapper.Terminal._cursorBlink (/app.asar/node_modules/learn-term.js/src/term.js:1422:8)
    at _blinker (/app.asar/node_modules/learn-term.js/src/term.js:1439:10)
```

### Commands

```
     -2:06.8.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
     -0:52.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide](https://atom.io/packages/learn-ide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
