### ISSUE TITLE
Git-plus push splitting my tree pane

### ISSUE THREAD

**Issue by jjdp** [atom/atom#14505]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whenever i push using the git-plus package my tree view gets split
![split](https://cloud.githubusercontent.com/assets/5244520/26246593/8e610c6c-3ccc-11e7-9fb7-4f2e77ac6326.png)

### Steps to Reproduce

1. push to my git repo

**Expected behavior:** tree view stays the same

**Actual behavior:** it gets split

**Reproduces how often:** 100%

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

using [git-plush 7.9.1](https://github.com/akonwi/git-plus)

**Comment by rsese** [comment]
Thanks for contributing!

It sounds like that this could be caused by [git-plus](https://github.com/akonwi/git-plus), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
