### ISSUE TITLE
Shorthand disappears too quickly

### ISSUE THREAD

**Issue by Midgardum** [atom/atom#14546]
I've just started using atom and I have no idea why shorthand disappears before I have a chance to do something. I can't look closely at the list, because it shows only for maybe one or two seconds and even if I'm fast enough, I can only pick from first two or three propositions. It disappears if I'll go further.  It's annoying. How can I fix it? :( I have win 7, atom 1.17 x64

**Comment by rsese** [comment]
Thanks for taking the time to contribute!  It sounds like you're referring to auto-complete?  If so, can you re-open this in https://github.com/atom/autocomplete-plus if there's no existing issue already so we have it in the right place?  E.g. this recent issue I saw looks similar:

https://github.com/atom/autocomplete-plus/issues/850

Also, if you open a new issue, please completely fill out the issue template, that's super helpful for us.  We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
