### ISSUE TITLE
barra de desplazamiento

### ISSUE THREAD

**Issue by Stivenson02** [atom/atom#14597]
por accidente o no se que paso, la barra de desplazamiento horizontal del panel de edición de código y la barra vertical del menú donde esta la carpeta que se habré o lo proyectos, se desaparecieron, ¿como las puedo sacar de nuevo?

**Comment by rsese** [comment]
Additionally, can you re-phrase your issue in English?  That will allow more folks to help.

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
