### ISSUE TITLE
Flickering Screen - odd GPU issue

### ISSUE THREAD

**Issue by Tectract** [atom/atom#14602]
I have a sort of non-standard GPU multi-screen setup with an older GPU on one of my dev machines, and I was having issues with Atom flickering uncontrollably at start.

Discovered that turning off one screen in the monitor settings then turning it back on alleviated the flickering issue for me. 

Just thought it might be interesting or helpful to some Atom user / dev out there :)

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
