### ISSUE TITLE
Some modified files are not saved when quitting Atom (reproduce systematic)

### ISSUE THREAD

**Issue by RCohenE5Group** [atom/atom#14626]
Hello

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I quit Atom, some unsaved file are not saved and no prompt is open for me to choose to save or not. Some other have a prompt, depending how I open the file (see below)

### Operation ONE

> touch tmp
* open Atom
* drag tmp into Atom
* modify tmp
* type Command-Q
* I expect a prompt to save the file tmp, there isn't.
> more tmp => tmp is empty
* reopen Atom and drag tmp again
* I expect to see an empty file, but the modified unsaved file is displayed (waw!)

### Operation TWO

* Do exactly the same, but instead of dragging tmp into Atom, open it with recent files (package open-recent 5.0.0) : the prompt is asked before quitting which is what I expect !

**Reproduces how often:** [What percentage of the time does it reproduce?]

1OO%

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

MacOsX 10.12.4

**Comment by rsese** [comment]
> Operation ONE

The project state that's saved includes unsaved changes so when you re-open the same project (dragging the file into Atom opens it's containing directory as a project), it's expected behavior that you'll see the modified unsaved file.  That's basically as you described in https://github.com/atom/atom/issues/11193#issuecomment-216018851 yeah @lee-dohm?

**Comment by RCohenE5Group** [comment]
Hello rsese, Thanks for your answer.

All right, I understand the concept of keeping project state. What is not acceptable for me is that on the disk, the file is not saved while application is closed. 

Some arguments against :
* every program on earth do something at quit : saving automatically (ex:google drive), or confirm (ex:libre office), why not Atom ?
* in every mind : application is closed so file is saved
* I can quit Atom and forget that I did not press Command-S. I modified a configuration file, and quit Atom, I've been searching for about 10 minutes why my modification had no effect, nothing told me that the file was not saved.
* restoring full state can have bug (as you mentionned in #11193 ) , there is a high risk of data loss
* there is actually data loss using :
*** operation THREE 
- do beginning of operation ONE dragging tmp and modifying, then quit without save
- instead of dragging it again, open it with menu "Open Recent" from open-recent package
=> the file is empty and not shown as modified. I can type something and loose "previous modification not really saved"

If this behavior is a choice and not an error, I consider it as a design error, even if there is no bug in restoring state process. Maybe I don't understand something, maybe I try to keep "old fashion" behavior, in the mean time I loose time and I loose information.

Please consider adding a priority bug correction with warning before quit. There are numerous people complaining about this and it gives a bad image to your wonderful tool Atom.
Thanks

**Comment by lee-dohm** [comment]
@RCohenE5Group The behavior you're describing is currently the expected behavior. The behavior of storing the project state on exit but not saving the files to their on-disk locations unless explicitly told to is what we believe most people expect of a programmer's editor. We don't have any plans to implement the behavior that you expect, to warn to save on quit in all cases.

This is something that I could see a package offering though, so I'll mark this as a `package-idea` before closing it. If anyone is interested in implementing a package for this, there are some new APIs that would have to be added, so please contact me if you're interested.

Thanks for taking the time to contribute!

**Comment by RCohenE5Group** [comment]
Thanks Lee Dohm. I'm disappointed but I understand.
In the mean time, is it an expected behavior that warning before quit is open when files are open though "recent files" menu ?

**Comment by lee-dohm** [comment]
It is the expected behavior to warn to save before quit when there is no project open, no matter how that comes about. This is behavior that we've put in place temporarily while https://github.com/atom/atom/issues/13318 is still unresolved.

**Comment by RCohenE5Group** [comment]
OK. For me opening a file from "recent files" or opening from "drag" should be exactly the same. I don't see the relation with "projects" functionalities, probably because I don't use project in Atom.
Thanks anyway for your help.
