### ISSUE TITLE
Atom UI got corrupted. 

### ISSUE THREAD

**Issue by DigvijaySinghChampawat** [atom/atom#14620]
I don't  know what happened but, it seems like UI got corrupted.

I tried to reinstall it but, it din't work.
![atom_issue_1](https://cloud.githubusercontent.com/assets/15905741/26403222/191580f4-40ab-11e7-9973-7e15c0461713.jpg)
![atom_issue_2](https://cloud.githubusercontent.com/assets/15905741/26403235/208eef46-40ab-11e7-924d-e6e6f4356502.jpg)

please check the files, i just cant help my self on this.

**Comment by rsese** [comment]
Have you tried the debugging steps in the Prerequisites section of the issue template (e.g. running in safe mode http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
