### ISSUE TITLE
python input not working

### ISSUE THREAD

**Issue by MHJU20** [atom/atom#14630]
Every time i try to use an input command, it doesn't work and has an error message.

example:

Traceback (most recent call last):
  File "C:\Users\Max\Desktop\Python\Basic.py", line 1, in <module>
    a = input("H")
EOFError: EOF when reading a line

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
