### ISSUE TITLE
Scroll Past End retains 3 lines instead of 1

### ISSUE THREAD

**Issue by scorici** [atom/atom#14659]
Scroll Past End retains the last 3 lines instead of just 1.
I would like to modify the behavior of Scroll Past End where it retains only one line instead of three.
I could not find how to do this.
Any help is welcomed.
Atom 1.17.2
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 3.6.1
git 2.13.0
OS: Arch Linux but it does the same on others, Linux Mint 17, 18, Ubuntu Mate 16.04.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
