### ISSUE TITLE
Atom Beta "Search in this directory" missing

### ISSUE THREAD

**Issue by GioLogist** [atom/atom#14650]
### Description

Below you'll see the drop-down menu on Atom Beta vs Atom.

![screenshot 2017-05-25 04 50 34](https://cloud.githubusercontent.com/assets/4120754/26490589/d3bf6206-41c0-11e7-9959-255da38654cf.png)
![screenshot 2017-05-25 04 50 30](https://cloud.githubusercontent.com/assets/4120754/26490588/d3bdfb46-41c0-11e7-9323-456c4aa95901.png)

**Expected behavior:**
"Search in this directory" visible

**Actual behavior:**
"Search in this directory" missing

### Versions

1.18.0-beta0

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by GioLogist** [comment]
Updated.

**Comment by hultberg** [comment]
@GioLogist This issue has been reported multiple times, and is not a real issue in atom core, but in the find-and-replace package. Subscribe to the issue here: atom/find-and-replace#887

**Comment by GioLogist** [comment]
Ah, didn't come up in my searches - gotcha!
