### ISSUE TITLE
"Open with Atom" wont work

### ISSUE THREAD

**Issue by Alivanar** [atom/atom#14666]
Hi there, 

Since 2 days i've been experiencing something strange, now i cannot open a folder by right-clicking on it, and selecting the "open with Atom" option (option that i've selected during the installation). I'm saying it's strange because the option is still visible, but whenever i click on it, it opens a regular "open with" window to select a program... i noticed that the Atom logo was not next to the option, may it be because the menu lost the file to run ? Do you have any idea how to fix that ?

I'm running on W10
Thanks 
Ali

**Comment by A-Casual-Guy** [comment]
Having the same issue.
Same, running Win 10 64 bit, but from a few days the "Open With" option didn't work. Reinstalling Atom seems to fix this though.

**Comment by rsese** [comment]
Thanks for reaching out! 

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Feel free to create a new issue with the template filled out @Alivanar but one thing you can try is to go to `Settings > System` and then checking/unchecking the settings there.  Hopefully you won't have to try re-installing but thanks for letting us know that fixed things up for you @A-Casual-Guy :v:
