### ISSUE TITLE
Feature request: Let Atom run always in background

### ISSUE THREAD

**Issue by evromalarkey** [atom/atom#14673]
### Description
The load times in 1.18 are a lot of better for sure, and everything under 1000ms is really great. And don't get me wrong, it's huge improvement and I love it, but to be honest the time I would really prefer is around 100ms.

Maybe this idea was already mentioned, but what about adding option into system settings to start Atom with OS as background service, so everytime you open file / folder with "Open with Atom", Atom would be already running.

Obviously I have no idea how hard that would be to implement, or if it's even possible with Electron. But I think it would be significant improvement for startup time.

**Comment by rsese** [comment]
Thanks for contributing!  It seems like your request is more about improving startup time rather than particularly making Atom run as a background service?    If that's the case, I think your request is covered in a few open issues e.g. https://github.com/atom/atom/issues/3673.  I'll go ahead and close as a duplicate for now but if there are other reasons that you think Atom would benefit from running as a background service, feel free to let us know :v:
