### ISSUE TITLE
Failed to activate

### ISSUE THREAD

**Issue by tomocrafter** [atom/atom#14681]
i got error

Failed to activate the autocomplete-php package
Arguments to CompositeDisposable.add must have a .dispose() method

**Comment by ungb** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
