### ISSUE TITLE
Copy (ctrl+c) copies only the first character of selection

### ISSUE THREAD

**Issue by zambee** [atom/atom#14683]
### Description

When copying a selection of text, only the first character of the selection is actually copied to the clipboard.
This happens regardless of if I use ctrl+c or right click copy.

### Versions
Atom version 1.17.2
Windows 10

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
