### ISSUE TITLE
Uncaught Error: Requested measurement of a line that is not currently rendered

### ISSUE THREAD

**Issue by mitzkia** [atom/atom#14714]
[Enter steps to reproduce:]

1. There was opened several tabs
2. Used the "Close all tabs" option to close all of the tabs.

**Atom**: 1.19.0-dev-60c1b85ed x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At /home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:2129

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:2127:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:2120:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:370:16)
    at scheduler.readDocument (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:260:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/view-registry.js:191:15)
    at /home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:49.8.0 tabs:close-all-tabs (div.title)
     -0:48 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:45.6.0 core:paste (div.lines)
```

### Non-Core Packages

```
atom-ctags 5.1.0 
atom-material-syntax 1.0.6 
busy-signal 1.4.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-syslog-ng 0.0.6 
linter 2.1.4 
linter-pylama 0.8.20 
linter-ui-default 1.6.0 
python-isort 0.0.7 
seti-ui 1.8.0 
sort-lines 0.14.0 
split-diff 1.4.0 
symbols-tree-view 0.14.0 
```

**Comment by mitzkia** [comment]
Trying to create a fix reproduction.

**Comment by mitzkia** [comment]
Ok, I think I have a fix reproduction, but can not reproduce with --safe mode.

```
Atom    : 1.19.0-dev-60c1b85ed
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

1, atom was started from command line: `./atom`
2, create a new empty page with: File -> New file
3, From the following website [https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_5/section_2.html](url) I copied the following snippet (from "Example: Java file" section):
```
Javaimport org.syslog_ng.*;

import java.io.*;
```
4, Pasted the snippet into the empty page with right menu (using the mouse)

With this reproduction steps, I can reproduce it in every time.

I hope it helps

**Comment by rsese** [comment]
Thanks for the report!  And thanks for sharing steps to reproduce as well.

But because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Comment by mitzkia** [comment]
Thanks for the help. I will check the "package-cop" package as well. 
For now, I tried to enable community packages one by one, and it seem the "linter-ui-default" cause the problem. I will report it there. Thanks again.
