### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by williamhancharek** [atom/atom#14724]
[Enter steps to reproduce:]

1. I was using the learn IDE from learn.co.  
2. I entered git mergetool in a git repository
3. I was hit with the below message

**Atom**: 2.4.2 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/learn-term.js/src/term.js:1306

TypeError: Cannot read property '0' of undefined
    at TerminalWrapper.Terminal.refresh (/app.asar/node_modules/learn-term.js/src/term.js:1306:18)
    at TerminalWrapper.Terminal._cursorBlink (/app.asar/node_modules/learn-term.js/src/term.js:1422:8)
    at _blinker (/app.asar/node_modules/learn-term.js/src/term.js:1439:10)
```

### Commands

```
     -2:25.8.0 window:toggle-full-screen (div.terminal)
  2x -2:20.3.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -2:18.1.0 editor:consolidate-selections (input.hidden-input)
     -2:18.1.0 core:cancel (input.hidden-input)
     -2:17.9.0 editor:consolidate-selections (input.hidden-input)
     -2:17.9.0 core:cancel (input.hidden-input)
     -2:16 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -2:08.3.0 pane:close (ul.list-inline.tab-bar.inset-panel)
     -2:05.9.0 pane:split-up-and-copy-active-item (div.item-views)
  2x -2:04.1.0 pane:close (div.item-views)
     -1:59.7.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
  2x -1:55.3.0 learn-ide:toggle-terminal (div.lines)
     -1:47.5.0 tree-view:show-current-file-in-file-manager (div.lines)
     -0:54.3.0 learn-ide:copy (div.)
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide](https://atom.io/packages/learn-ide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
