### ISSUE TITLE
Cant download for windows 10 why 

### ISSUE THREAD

**Issue by CodingCrabby** [atom/atom#14754]
When The atom setup fineshed i started it up and it did not came up the installer
then i went and found the atominstaller file and double clicked it and then it said :
'This app can't run on your PC
To find a version for your Pc, Check with the software publisher."
Please help i need it for Coding i really like your editer so i had it in my older computer and now i got a new computer so i re-download it but it cant be done 
sorry for the bad english iam rubbish at english

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us (it's ok that some of the template doesn't apply).  If you can also answer the following questions in the new issue, that would be helpful:

* What version of Windows 10 are you running (Enterprise, Home, Professional)?
* Did you download the installer from https://atom.io?

We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
