### ISSUE TITLE
JS file Template String "// " highlighting bug.

### ISSUE THREAD

**Issue by hezedu** [atom/atom#14758]
version: 1.17.2 X 64
OS: window 10
```js
var ws = new WebSocket(`ws://${location.host}`);
```
![qq 20170612171815](https://user-images.githubusercontent.com/8508437/27027379-c4056320-4f93-11e7-9a02-3cc3b0872d2e.png)

**Comment by 50Wliu** [comment]
I can't reproduce this using language-javascript@14e02bd.  @hezedu please make sure that the issue persists in safe mode.  If it doesn't, it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
