### ISSUE TITLE
Revert back to stable Version

### ISSUE THREAD

**Issue by MandarSant** [atom/atom#14777]
How to revert back from beta version to stable version

**Comment by ungb** [comment]
I'm not certain which OS you're on, but basically you need to go to atom.io, download stable and install it over beta.  If you are on Mac, Beta and Stable are installed side by side.  


Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
Please reopen if this hasn't fixed your issue.

**Comment by MandarSant** [comment]
@ungb i am using win 8.1 and installed beta 1.18 on stable 1.17

**Comment by ungb** [comment]
if you go to https://atom.io/, you should beable to grab stable.  I suggest you go to control panel and remove Atom and then install Atom Stable(from https://atom.io/)

**Comment by MandarSant** [comment]
@ungb but action cant be revert back? tough I installed beta on stable 
and is there any way to have both versions at same time
