### ISSUE TITLE
Best performance by removing  some parts of chrome.

### ISSUE THREAD

**Issue by NickolasGame** [atom/atom#14772]
Atom is very good and very beautiful editor.Howewer, it has some performance problems.
Previous releases was shipped wit such things like 64bit architecture support, better handling of large and minifed files.

I think performance can be hugely improved if from atom will removed such parts of chrome like:
console, viewing of current code and all devtools. This things is unneeded and they slow up editors in meny ways. I thing it will be a good approach if atom will use only interpraing engine for languages, and other  minimal toolset.

**Comment by rsese** [comment]
Thanks for reaching out!

We've passed along your suggestion to the maintainers team - because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.
