### ISSUE TITLE
Question: Opening new projects into same window?

### ISSUE THREAD

**Issue by fmunteanu** [atom/atom#14787]
Running Atom 1.17.2 x64 on a Mac Sierra. I searched into settings, but cannot find an option to open new projects into same window. Current behavior:
1.  View > Show Tab Bar
2. File > Reopen Project

The project will open in a new window, I would like to open the project into a new tab instead. I currently drag the new project tab into previous project, to work with a single window.

Thank you for letting me know if I missed a configuration setting.

Regards,

Floren

**Comment by rsese** [comment]
Thanks for reaching out!   Closing this since we use issues as our backlog (see below for more details).  But I don't believe this is possible with Reopen Project with/without the tab bar and there's already existing request for this /cc https://github.com/atom/atom/issues/13277.  Feel free to subscribe there for updates if you'd like.

--- 

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
