### ISSUE TITLE
Color emoji not displaying

### ISSUE THREAD

**Issue by soleera** [atom/atom#14784]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Color emoji are not being displayed, only their greyscale counterparts.

### Steps to Reproduce

1. Install an emoji font (e.g. Noto Emoji , Twemoji)
2. Open Atom
3. Input Emoji

**Expected behavior:** Color emoji are displayed

**Actual behavior:** Greyscale emoji are displayed

**Reproduces how often:** Always

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Hardened Gentoo (linux kernel 4.11.4)

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
apm  1.16.1
npm  3.10.5
node 6.5.0 x64
python 3.4.5
git 2.13.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

This occurs even when selecting the emoji font directly in atom or prepending the emoji font in fontconfig.

**Comment by andya9** [comment]
Atom    : 1.19.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

I'm using noto emoji on archlinux
Safe mode.

With the new update, emoji are now partly working. The font family is correctly applied, but colors are buggy.
For example this is properly colored: 🙄
Whereas these appear pitch black: 😁; 😃.

**Comment by 50Wliu** [comment]
@soleera Please try using Atom 1.19.0-beta, which upgraded Chrome from v52 to v56.

@andya9 what happens if you don't use an emoji font?  Does Archlinux support native emoji?  For reference, this is what I'm seeing on Windows without a dedicated emoji font:
![windows-10-native-emoji](https://user-images.githubusercontent.com/2766036/27200188-d9b09f64-51e6-11e7-842d-963c49831758.png)

**Comment by andya9** [comment]
Sorry, I wasn't clear: in Atom I'm using as default font Source Code Pro. Noto Emoji is installed (by me) and automatically used whenever the font used in an app doesn't support the character. Just like: I'm reading an english text using DejaVu Sans, a Chinese word is mixed within, it's rendered using Noto CJK because somehow the system detects that DejaVu Sans doesn't support the glyph, whereas Noto CJK does. Sadly I don't really know how fontconfig (the font manager in linux systems) works.

**Comment by soleera** [comment]
Ah I see, I was under the impression that they had already been implemented in 1.16.0: [Emoji image support #8006](https://github.com/atom/atom/issues/8006)

In that case I'm happy to close this issue, since the feature is being worked on already. Thanks for the clarification!

**Comment by anaibol** [comment]
It's also working perfectly for me on Arch Linux after setting fontconfig.

**Comment by Ben3eeE** [comment]
Thanks @anaibol 🙇
