### ISSUE TITLE
Java not running 

### ISSUE THREAD

**Issue by abhay676** [atom/atom#14780]
My java program not running after installing the package Script what the problem please 
![1497463249925230793025](https://user-images.githubusercontent.com/28358818/27147218-91902d18-5159-11e7-857f-46b8488ea0a7.jpg)

**Comment by abhay676** [comment]
I have also installed MinGw and cygwin compiler

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

Additionally, you can checkout the package repository for more information e.g.:

https://github.com/rgbkrk/atom-script/issues/1139
https://github.com/rgbkrk/atom-script/issues/808
