### ISSUE TITLE
Atom installation become corrupted after a while and doesn't start. 

### ISSUE THREAD

**Issue by SMH17** [atom/atom#14793]
Atom on Windows 10 x64 seems very unstable It's the third time that I'm forced to reinstall everything because something goes wrong and corrupt installation causing problems in Atom load that remains with a background process with very high CPU usage without opening. 
Honestly I don't use Atom standalone but with many plugins since the base features are too limited, however after this strange corruption, sometimes is enough to run Atom in safe mode, and after closing and launch normally with all plugin loaded run correctly, other times no cache clean or safe mode start seems able to allow the correct Atom execution and the only way is completely remove Atom and install again (this usually happens when a new update is released, so in this case seems something related to update process).

**Comment by rsese** [comment]
Thanks for reaching out!  This sounds like a tough one to debug but It would be helpful if you can fill out the issue template so it makes it easier for people see all the baseline information.  I'll go ahead and close this one but please create a new issue and fill out the template and we can go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by JayCadilak** [comment]
I have experienced this same issue for much of 2017 and at this point I have no choice but to ditch this software. Free to download but costs a fortune!
