### ISSUE TITLE
Duplicate icons when pinning in taskbar - Windows 10

### ISSUE THREAD

**Issue by garygreen** [atom/atom#14810]
Version: 1.18.0 ia32

This seems to be an ongoing problem, apparently fixed but it isn't. Ref to issue #7374 

![atom duplicate pin](https://user-images.githubusercontent.com/1702638/27232686-dc7afaa0-52ae-11e7-8a61-070c361b59a7.gif)

**Comment by rsese** [comment]
Thanks for opening a new issue @garygreen :+1:  Makes sense at this point since that issue was pretty stale and it's possible it's the same symptom with a different cause at this point - if it's not too much trouble, can you open a new issue with the issue template filled out?  That way folks can have a fresh start with all the information necessary to try and reproduce in the issue body.

**Comment by garygreen** [comment]
Really?! I've kept this straight forward because this should be as much information as needed. Even attached a pretty gif, picture worth a thousand words and all. Anyway, I'll open another issue with the same details.

**Comment by garygreen** [comment]
New issue created #14813
