### ISSUE TITLE
Command Y Not Working Anymore????

### ISSUE THREAD

**Issue by jesskrich** [atom/atom#14815]
Kind of an urgent matter. If there is a fix to this, lmk. Has always worked for me before but now seems to be broken. Command Z still working fine.

*Also, for what it's worth, not just the shortcut, 'Redo' in menu not working either.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
