### ISSUE TITLE
Is possible to copy and paste collapse code?

### ISSUE THREAD

**Issue by AdalbertoMundo** [atom/atom#14816]
Is possible to copy and paste collapse code like Dreamweaver:

![paste-dw](https://user-images.githubusercontent.com/28799590/27250709-5453dfd2-52fb-11e7-9b7f-cd0c352f038e.gif)

And this is Atom:

![paste-atom](https://user-images.githubusercontent.com/28799590/27250711-59dcc392-52fb-11e7-8edf-8064567fa71b.gif)

Thanks

**Comment by rsese** [comment]
Thanks for reaching out!  This isn't possible at the moment but you may want to run a quick package search to see if there's a community package that does what you want.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
