### ISSUE TITLE
Option key is not honored in key bindings when combined with Ctrl

### ISSUE THREAD

**Issue by wsshin** [atom/atom#14819]
I recently upgraded Atom to 1.18.0 on Mac.  Not sure about the exact version number before the upgrade, but probably 1.16.x.

Since the update, the Option key on Mac seems to be ignored in key bindings when pressed with the Ctrl key.  For example, if I press Ctrl-Opt-G, Ctrl-G is executed (which is bound to "Go to Line").  Also, if I press Ctrl-Opt-L, Ctrl-L is executed (which is bound to "Clear Console").

This is problematic, because I have defined Ctrl-Opt-G and Ctrl-Opt-L as the shortcuts to input some unicode characters (Greek letters γ and λ).

Is it possible to make Atom honor the Option key when pressed with the Ctrl key?

**Comment by rsese** [comment]
Thanks for reaching out!  

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us.    I haven't had any issues with the Option key on macOS recently so in your issue, I'd suggest maybe adding a screentshot of what the [keybinding resolver](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings) shows as a first step?

We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
