### ISSUE TITLE
Atom showing tab characters in teal for .eslintrc, forcing spaces

### ISSUE THREAD

**Issue by garretwilson** [atom/atom#14822]
I'm using Atom 1.18.0 ia32.

I'm creating a new project and put in an `.eslintrc` file, copied from another project. I modified the file and changed the spaces to tabs:

```json
{
	"extends": "eslint:recommended",
	"env": {
		"es6": true,
		"browser": true,
		"node": true,
		"mocha": true
	}
}
```

Atom shows all the tab characters with a teal-ish background color (regardless of whether I show or hide invisibles). This does not happen in e.g. `package.json` or `.jsbeautifyrc`.

On top of this, when I hit `<tab>` in `.package.json` or `.jsbeautifyrc`, I get a tab character, but in `.eslintrc` I get two spaces --- even though I have changed `.eslintrc` to use tabs, and reloaded the file (and restarted Atom).

What is different about the `.eslintrc` file that Atom wants to change the colors of the tab characters and force spaces instead of tabs?

In my Atom config I have:
* Soft Tabs: (unselected)
* Tab Type: auto

**Comment by 50Wliu** [comment]
The `.eslintrc` file is detected as a YAML file (as the extension is ambiguous and YAML is technically a superset of JSON).  However, YAML also [forbids](http://www.yaml.org/spec/1.2/spec.html#id2777534) the use of tabs as indentation so language-yaml naturally sets the default indentation to spaces and highlights all tabs used as indentation as illegal.

If you wish to use the JSON highlighter instead, add the following under the `core` section in your `~/.atom/config.cson` file:
```cson
customFileTypes:
  'source.json': [
    'eslintrc'
  ]
```

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by 50Wliu** [comment]
Also, something I forgot to mention: use of the `.eslintrc` file is deprecated.  See http://eslint.org/docs/user-guide/configuring#configuration-file-formats.

**Comment by garretwilson** [comment]
> use of the `.eslintrc` file is deprecated. You should migrate to `.eslintrc.json` instead.

That is so useful to know! This makes the whole auto-YAML-detection issue moot as well. I appreciate your letting me know, @50Wliu . I've switched to `.eslintrc.json`.
