### ISSUE TITLE
Running atom from terminal returns an error: "No such file or directory"

### ISSUE THREAD

**Issue by b94901099** [atom/atom#14850]
On OSX El Capitan 10.11.6.
Running atom from terminal returns an error: "-bash: /usr/local/bin/atom: No such file or directory."
atom is installed in /Applications/Atom.app/...
How do I configure atom command and make it work in terminal?

**Comment by rsese** [comment]
Thanks for reaching out!  Even though some of the issue template might not apply to your situation, it's super helpful if you can fill it for us.  In particular, it would be helpful to know what version of Atom you're running and when you started seeing this behavior (e.g. after updating versions).  Also, can you mention if you tried installing the shell commands from the `Atom > Install Shell Commands` menu item?

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by b94901099** [comment]
Hi, thanks for quick reply.
I just reinstall atom and now it works.
