### ISSUE TITLE
atom from cli not found

### ISSUE THREAD

**Issue by ilhamdoanggg** [atom/atom#14867]
![screenshot from 2017-06-22 01 06 55](https://user-images.githubusercontent.com/9218660/27399667-c286c5e2-56e7-11e7-93b8-de72cd86c70c.png)
what should i do???

**Comment by rsese** [comment]
Thanks for reaching out! Have you tried installing the shell commands from the `Atom > Install Shell Commands` menu item?

As mentioned below, it's super helpful if you can fill out the issue template for us even if some of it doesn't apply. I'll go ahead and close this issue but definitely feel free to open another one with the template filled out and let us know if you tried running the command I mentioned above.  

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
