### ISSUE TITLE
Indentation of large number of lines is very very slow.

### ISSUE THREAD

**Issue by yanzhang0219** [atom/atom#14878]
Hi,

One of my files has about 500 lines and the average length of these lines are about 40 characters. I opened this file and tried to use command+] to indent all the lines. The latency (delay) is very significant (around 1 second) compared to sublime, or even VScode. 

Then I opened a larger file containing 2000 lines and I indented it the same way. The delay is increasing significantly. 

I'm just wondering whether this drawback can be solved and the performance can be improved or not. Thanks.

**Comment by rsese** [comment]
Thanks for reaching out!  

It looks like you've already found the [existing issue](https://github.com/atom/atom/issues/1873) for this but additionally, because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

Also, since I'm not a developer I can't say 100% whether or not the performance can be improved but since the issue is still open, it's just not something the team has had time to look at with all the work they've been doing.  But the team is willing to look at a well-written pull request if someone in the community decides to take a look at the issue.
