### ISSUE TITLE
Crash, Crash and Crash !!!

### ISSUE THREAD

**Issue by peyman2afm** [atom/atom#14872]
Hello!
When I want add new project, atom is show me this error:
![image](https://user-images.githubusercontent.com/20682878/27432051-e3294456-5763-11e7-8393-b78f3bbd5ecb.png)

**Comment by rsese** [comment]
Thanks for reaching out!  It would be super helpful if you can fill out the issue template since that gathers a lot of baseline information - for example, what version of Atom are you running?  Also which operating system (looks like Windows 10)?

And from the Prerequisites section of the issue template, do you have the same problem if you start in safe mode (`atom --safe`)?

Lastly, if you're running 1.18.0, my next question would be to see if temporarily disabling the GitHub package makes any difference, see this comment for more details /cc https://github.com/atom/atom/issues/14806#issuecomment-309546499.

So I'll go ahead and close this issue but if you can open a new one with the template filled out we can go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
