### ISSUE TITLE
git checkout new_branch,the resource manager list content is delayed 

### ISSUE THREAD

**Issue by cloudyan** [atom/atom#14892]
In a git project, when the branch is switched, the resource manager list content is delayed and the refresh is sometimes invalid

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us.   In particular, detailed steps to reproduce the behavior you're seeing, expected and actual behavior, and knowing if you can reproduce in safe mode (`atom --safe`) would be very helpful. Also, if your issue is specific to the GitHub package, please open your issue in the package repository: https://github.com/atom/github/.

We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
