### ISSUE TITLE
Atom crashes when atom-beautfy running

### ISSUE THREAD

**Issue by qiziqiang** [atom/atom#14912]
![18141229569972](https://user-images.githubusercontent.com/25959322/27647143-34e651a0-5c5d-11e7-92ec-0ac674e830f7.png)

**Comment by edwinksl** [comment]
You probably should post (with more details) at https://github.com/Glavin001/atom-beautify instead.

**Comment by rsese** [comment]
> You probably should post (with more details) at https://github.com/Glavin001/atom-beautify instead.

👍 thanks @edwinksl - if the issue is specific to a particular package, the best place to report it is the package repository @qiziqiang.  It may be that there is still a bug in Atom and if so, we'll need the maintainer of the package that is causing the problem to help track that down. So you should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. 

Also in the future, it would be super helpful for us if you can completely fill out the issue template.
