### ISSUE TITLE
Will not run

### ISSUE THREAD

**Issue by ISeeChase2** [atom/atom#14928]
Ok so, I had atom before my PC crashed. It worked beautifully. Now when I get it back with nothing on it (except all updates) it says it cannot run on my pc. I downloaded the exact file I did before... Help?

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us.  If you can share a screenshot of what you see when you say:

>  Now when I get it back with nothing on it (except all updates) it says it cannot run on my pc. 

That would be helpful too.

We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
