### ISSUE TITLE
Auto-complete doubles up on typed input.

### ISSUE THREAD

**Issue by KylerSmith** [atom/atom#14934]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After auto-complete is selected, it will retype the initial input that brought up the auto-complete.

### Steps to Reproduce

1. Open a new file.
2. Select a language that supports auto-complete.
3. Begin typing until auto-complete suggestion is brought up.
4. Select one of the suggestions.

**Expected behavior:** 
Auto-complete should complete the text according to the selected option.

**Actual behavior:**
Auto-complete doubles on the typed input.

![issue-p1](https://user-images.githubusercontent.com/20100206/27762644-226ea7b4-5e2b-11e7-9f37-1478bbce0556.gif)

![issue-p2](https://user-images.githubusercontent.com/20100206/27762660-390161ce-5e2b-11e7-85d2-0b2a3ca16d27.gif)

**Reproduces how often:** 
100%

### Versions
Atom         :1.18.0
Electron    :1.3.15
Chrome     :52.0.2743.82
Node         :6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0

macOS Sierra 10.12.5

**Comment by rsese** [comment]
Thanks for the report!  The snippets I see in the 2 GIFs are:

* `inc`
* `main`

So if you start typing either of those terms only (i.e. without the `#` and `int` respectively) and then select the suggestion, it works ok because the snippets already include the content you're typing in both cases.

If you type <kbd>#</kbd> followed by <kbd>inc</kbd>, you're typing a <kbd>#</kbd> followed by the `inc` snippet which includes the <kbd>#</kbd>.

Hope that makes sense but let me know if I mis-understood anything - also for reference, auto-complete related issues can go in https://github.com/atom/autocomplete-plus.
