### ISSUE TITLE
Canceling "Add project folder" operation leads to a bug

### ISSUE THREAD

**Issue by omerman** [atom/atom#14937]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After clearing the project out of projects and attempting to add the first project folder
and afterwards canceling the operation, Atom will bring back the previous project folders 
I already closed.

### Steps to Reproduce

1. Open Atom
2. Add a project folder
3. Close Atom
4. Open Atom
5. Remove the project folder
6. Attempt to add a project folder, but press Cancel instead.

**Expected behavior:** No project will be added. Editor environment will be clean(Without any open projects)

**Actual behavior:** The Previous closed project appeared again.

**Reproduces how often:** All the time.

### Versions

Atom    : 1.18.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0

**Comment by rsese** [comment]
Thanks for the report! I noticed this part of the template wasn't checked:

> - [ ] Put an X between the brackets on this line if you have done all of the following:

Can you confirm if you can reproduce in safe mode (`atom --safe`)?  I tried to repro with your steps but wasn't able to.

And what operating system are you running?

**Comment by omerman** [comment]
Sorry for the delay!
Im running on Linux.
It didn't come up on safe mode.

**Comment by 50Wliu** [comment]
Thanks for the response @omerman.  Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
