### ISSUE TITLE
error - PHP could not be spawned

### ISSUE THREAD

**Issue by hackerrahul** [atom/atom#14938]
please help me to solve this error in atom 
![error](https://user-images.githubusercontent.com/17741867/27768766-e54e1a22-5f38-11e7-93cd-be2064dcb169.PNG)

please see the image above to see the error and please help me

**Comment by rsese** [comment]
Thanks for reaching out!  I think that error is coming from a community package e.g. one of these PHP auto-complete packages perhaps?

* https://github.com/Azakur4/autocomplete-php/issues/11
* https://github.com/Peekmo/atom-autocomplete-php/issues/305

Since the issue is coming from a community package, you should open an issue for that repository if one doesn't exist already.

Additionally, for future issues it would be super helpful if you can fill out the issue template, it provides a lot of useful baseline information for us when triaging issues.
