### ISSUE TITLE
will text selection and cursor position fix in lines with RTL text ?

### ISSUE THREAD

**Issue by salehmosleh** [atom/atom#14930]
in version 1.18.0 , it still exists. will it solve ? Should we wait for it or not ?
look at :  #13194

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

Additionally, looking at the pull request you linked to and looking at issues like this that are still open:

https://github.com/atom/atom/issues/12282
https://github.com/atom/atom/issues/9078

Addressing these issues just isn't something the team has had time to look at with all the work they've been doing. But they're willing to look at a well-written pull request if someone in the community decides to take it on.
