### ISSUE TITLE
Ctrl+click multiple cursor not working.

### ISSUE THREAD

**Issue by sergeygrigoryan** [atom/atom#14943]
Hello dears. Today my Atom gave me a nice "surprise". After opening Atom multiple cursor not working. How can i fix that?

**Comment by iainvdw** [comment]
Same here, on OSX cmd+click isn't working for multiple selections. Seems to be changed to cmd-alt-click now (maybe ctrl-alt-click on Windows?). 

Is this change deliberate? Can't find anything in the changelog or settings to change it back.

**Comment by rsese** [comment]
Thanks for reaching out!  Filling out the issue template is super helpful for us - e.g. what version of Atom are you running (`atom -v`)?  Is the error reproducible in safe mode (`atom --safe`)?   What operating system and version are you running?

I couldn't reproduce with Atom 1.19.0-beta1 on macOS 10.12.5 or with Atom 1.18.0 on Windows 10, I can create multiple cursors with the <kbd>cmd-click</kbd> and <kbd>ctrl-click</kbd> respectively.

Unless I missed something, there were no specific changes around changing how to create multiple cursors recently.

If either of you can create a new issue with the template filled out we can definitely take a look though.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by iainvdw** [comment]
Thanks for looking into this @rsese! I've checked using safe mode and it does work as expected then. Seems to be an issue with the Hyperclick package, so I will report it there.

**Comment by iainvdw** [comment]
@sergeygrigoryan I've filed an issue on the Hyperclick package: https://github.com/facebooknuclide/hyperclick/issues/20.

**Comment by joedf** [comment]
@sergeygrigoryan  thanks. 

For future readers, update `atom-ide-ui` and/or `hyperclick` and see following:
@hansonw commented on Jul 4
> By default Hyperclick overrides cmd+click, but this is easily configurable in Settings (Atom > Preferences > Packages > Hyperclick > Settings); just change it to something else.
![screenshot](https://user-images.githubusercontent.com/577378/27841143-bd49c9fa-60b3-11e7-872f-dd8b02fd92a1.png)

**Comment by Dayjo** [comment]
@joedf I have the latest version of atom-ide-ui and I don't use hyperclick, but I am having this problem since the latest update (1.21.0)

**Comment by mrpauljbailey** [comment]
I've been having the same issue so i went into teh settings for hyperclick and changed the windows command to shift+ctrl+click and now it works using just ctrl+click....... Go Figure

**Comment by cylosh** [comment]
After installing hyperclick it now works with ctrl+alt+click

**Comment by Keyrainn** [comment]
The settings for this are in the atom-ide-ui package (get there via Settings -> Packages) under the Hyperclick heading.
