### ISSUE TITLE
I can't run python using atom.

### ISSUE THREAD

**Issue by Jake132456** [atom/atom#14942]
down vote
favorite
1
I downloaded anaconada 3 and atom. I installed script etc. When I'm running it using script.

I got this result.

Python - 7.py:8 'python'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ� ��ġ ������ �ƴմϴ�. [Finished in 0.037s]

When I open py file. I got this message.

Provided path doesn't exist. pylama

Please fix pylama path or install latest version.

When I write the python code using atom.

I got this message.

autocomplete-python traceback output: 'python'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ� ��ġ ������ �ƴմϴ�.

Provided path doesn't exist. pylama

Please fix pylama path or install latest version.

How can I solve this problem?

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

Additionally, it looks like the error you're seeing is coming from the lynter-pylama package?

https://github.com/AtomLinter/linter-pylama/issues/33
