### ISSUE TITLE
I need help with a syntax theme from Atom.

### ISSUE THREAD

**Issue by albcntr** [atom/atom#14951]
### Hello, I am trying to create a simple syntax theme like _Classic Plus_ from Dev-C++. 
**My questions are:**

**1**: How i can put `#include <>` with `color: @green;` and `font-weight: normal;` but perserving this:
`&.syntax--control {
    color: @syntax-text-color;
    font-weight: bold;
  }`?

**2**: How i can put `()`,`{}`,`,`,`.`,`;`...  with `color: @red;` and `font-weight: bold;`?

I let you an image in which you can see this stuff in Dev-C++:
![captura devcpp](https://user-images.githubusercontent.com/29888894/27832934-e3edbd42-60d0-11e7-911e-e2c422eaa278.png)

An now, how this code looks on _Atom_:
![captura atom](https://user-images.githubusercontent.com/29888894/27833280-57966964-60d2-11e7-8a47-c24bc570165d.png)
If you need to see my `base.less`, tell me and I'll add it.

Thank you very much. :-)

Alberto.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io) - in particular, be sure to use the `Themes` label for your post.
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
