### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 1024, Creating instance of SequoiaDebuggerS...

### ISSUE THREAD

**Issue by caobokai** [atom/atom#14966]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 1024, Creating instance of SequoiaDebuggerService.

```
At /opt/facebook/nuclide/0.232.60725445/nuclide/node_modules/rxjs/bundles/Rx.min.js:69

RpcTimeoutError: Timeout after 60000 for id: 1024, Creating instance of SequoiaDebuggerService.
    at RpcTimeoutError (/opt/facebook/nuclide/0.233.61365329/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:127:20)
    at Call._timeout (/opt/facebook/nuclide/0.233.61365329/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:173:20)
    at Call._timerId.setTimeout (/opt/facebook/nuclide/0.233.61365329/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:143:12)
```

### Commands

```
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.66.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.236.63305782 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [Nuclide](https://github.com/facebook/nuclide) package, not Atom itself? It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
