### ISSUE TITLE
ctrl+alt+direction keys (up, down, left and right) ignored by atom

### ISSUE THREAD

**Issue by jatubio** [atom/atom#14988]
On Windows. Atom 1.18.0 x64.

Keybinding to ctrl+alt+up it's impossible, because it's ignored by atom. 

Testing on Key Binding Resolver, don't catch them.

**Comment by rsese** [comment]
Thanks for reaching out!  In addition to filling out the template as mentioned below, if the keybinding resolver isn't catching the key combination, then it's possible another application maybe taking the key combo.  See this message board post for example:

https://discuss.atom.io/t/strange-key-binding-behavior-only-alt-cmd-z-combo/43374/2

I also tested on Windows 10 and Atom 1.18.0 but couldn't reproduce.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by jatubio** [comment]
Sorry, but i don't understand what i have to do to. ¿How I filled out the template?

Thank you

**Comment by rsese** [comment]
@jatubio - we need all the information asked for in the when you create a new issue i.e. this template:

```
<!--

Have you read Atom's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md

Do you want to ask a question? Are you looking for support? The Atom message board is the best place for getting support: https://discuss.atom.io

-->

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
```

So for example, the `Prerequisites` section asks if you tried debugging steps like starting Atom in safe mode and going through http://flight-manual.atom.io/hacking-atom/sections/debugging/.

And the `Additional Information` section could be used to share a screenshot of what you see with the [Keybinding Resolver](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings) enabled and trying <kbd> ctrl+alt+up</kbd>.  You could also let us know if this worked previously and randomly stopped working or if the key combination never worked for you.

Do you think you might have another app on your computer that could be taking that key combination?  That's what we found in cases like https://discuss.atom.io/t/strange-key-binding-behavior-only-alt-cmd-z-combo/43374/2.

**Comment by jatubio** [comment]
Thank you @rsese. 

Apologies for not reading the information carefully to create a issue.

Just now i'm a little bussy. But i try to fill the template as soon as i can.
