### ISSUE TITLE
Atom crashes in ubuntu a few times

### ISSUE THREAD

**Issue by ankibalyan** [atom/atom#14989]
Atom is crashing while launching for a particluar project from ubuntu's terminal

Issue occurs once or twice a day, not sure how exactly.

```
/usr/bin/atom: line 130:  2764 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
Failed to get crash dump id.
Report Id: 


```

### Versions
OS: Ubuntu 16.04 LTS

```
$ atom --version
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
```
$ apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.7.4

```

**Comment by rsese** [comment]
Thanks for reaching out!  Filling out the template as mentioned below is super helpful - in particular, please let us know if you can reproduce the crash in safe mode (`atom --safe`) and if the general debugging suggestions help or not:

http://flight-manual.atom.io/hacking-atom/sections/debugging/

So if you can open a new issue with this information we can go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by ankibalyan** [comment]
As I mentioned issue doesn't come every time I open atom from cli. It usually come when system reboots, and directly opening the project from cli.
anyways I'll try debugging.
