### ISSUE TITLE
atom markdown can not reponsing

### ISSUE THREAD

**Issue by guomuye** [atom/atom#14991]
``

I write the above codes,then atom will seizing-up. like this:

**Comment by rsese** [comment]
Thanks for reaching out!  In addition to filling out the template as mentioned below, it looks like your report was cutoff?   

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
