### ISSUE TITLE
Tab selection problem

### ISSUE THREAD

**Issue by ozgrozer** [atom/atom#15021]
This is what it supposed to be:

![sublime](https://user-images.githubusercontent.com/651938/28210161-bb28d86c-689e-11e7-9914-ae1a26a52405.gif)

And this is what happens:

![atom](https://user-images.githubusercontent.com/651938/28210337-81f5a448-689f-11e7-8f97-fcea9a53b2a7.gif)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
