### ISSUE TITLE
Menu focus delay issue

### ISSUE THREAD

**Issue by danqing** [atom/atom#15033]
* Version: 1.18 (but I believe it has happened in previous versions too)
* OS: macOS 10.12

When activating the menu using Cmd + Shift + P, sometimes the menu does not receive focus (the input box is not focused). If I type in this situation, I will still be typing in the code file, not in the menu. I have to get rid of the menu and reactivate it to let it focus.

It's not a big problem, but it has been happening for a while. Occurs like 10% of time (not frequent, but I use Cmd + Shift + P pretty often and I will see this once in a while).

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently (like whether you have been able to reproduce this problem in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)). This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
