### ISSUE TITLE
My editor changes have not been saved ？ 1.18.0

### ISSUE THREAD

**Issue by gclove** [atom/atom#15047]
Does anyone have this problem ?

The file directory has a git repository.

I'm sure I pressed the save shortcut key because the list of files is grey.

editor window is  the modified content. But no really saved to disk.

---

> I have try added a blank line,
> Only the blank lines are preserved
> But other editors see new content that is not saved to disk

Is it based git version control ?

---

> I'm sure I've had this problem, but I don't know how to do it again.

> I'll try a few more times next time I meet

**Comment by lee-dohm** [comment]
From the information you've given, I haven't heard of people having this problem.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
