### ISSUE TITLE
Nomodulenamed tensorflow problem.

### ISSUE THREAD

**Issue by Jake132456** [atom/atom#15058]
I'm using windows OS and anaconda with atom.
I downloaded tensorflow at the anaconda virtual environment.
I can use it anaconda prompt, however, at the atom, I get Nomodulenamed tensorflow error message, when I'm writing import tensorflow as tf.
How can I solve this problem?
How can I use virtual environment at the atom in windows 10 OS?
Any reply will helpful to me.
Thanks.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
