### ISSUE TITLE
atom keeps using my whole cpu

### ISSUE THREAD

**Issue by BMayank0405** [atom/atom#15073]
Atom is using too much of my CPU, even in the safe mode, it is using that much CPU, and also when I am using less numbers of files the CPU usage is quite high
![atom](https://user-images.githubusercontent.com/21199793/28489140-ae5de90c-6ed8-11e7-8991-48c36f21c194.png)

**Comment by BMayank0405** [comment]
when I'm using atom as root user it uses less of CPU

**Comment by rsese** [comment]
Thanks for reaching out!  Filling out the issue template is super helpful for us - e.g. what version of Atom are you running (`atom -v`)?  Is the error reproducible in safe mode (`atom --safe`)?   What operating system and version are you running? 

If you can create a new issue with the template filled out, we can go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
