### ISSUE TITLE
[Suggestion] Support for double tap spacebar for full stop on Mac OS? 

### ISSUE THREAD

**Issue by ozziepeck** [atom/atom#15074]
This would be really good if you could add this.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
