### ISSUE TITLE
This array syntax not working in PHP

### ISSUE THREAD

**Issue by Daijobou** [atom/atom#15087]
Atom : 1.18.0
Electron: 1.3.15
Chrome : 52.0.2743.82
Node : 6.5.0

Windows 10 64Bit

See PHP-file

![grafik](https://user-images.githubusercontent.com/260343/28565424-8185960e-712c-11e7-8a77-138720daadfc.png)

Its happen always after 50 value in a array

**Comment by Ingramz** [comment]
@Daijobou number of tokens per line [has been limited to 100](https://github.com/atom/atom/blob/62c1bad39c5347010c81ee8baf6b607caaa10cb6/src/grammar-registry.coffee#L18) (in your case 50 numbers and 50 commas), so that long lines wouldn't slow down the editor.

This is currently the intended behavior.

**Comment by Daijobou** [comment]
Oh, thanks for your answer. Then I will close this ticket. I hope this cool editor get more performance in the future, so its not need this settings. :)
