### ISSUE TITLE
Drag and open the project in same window

### ISSUE THREAD

**Issue by mittalyashu** [atom/atom#15105]
I really like the feature of dragging the file and dropping inside the ATOM text editor to open as a project in new Window.

Is there is any way to turn that function off to open in new Window, I want that the open drag and drop should open in the same window.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by mittalyashu** [comment]
Can we expect this as a feature request?

**Comment by mittalyashu** [comment]
@rsese. Can you re-open this issue and add this feature request in an upcoming update? 

Becuase it is very handy instead of clicking on the menu, selecting the file and then adding it.

**Comment by rsese** [comment]
Sorry I missed your initial followup - can you describe the behavior you're interested in in more detail?  If I start Atom and then drag a file into the window, it opens in that window - this sounds like what you're asking about?

If you can share specific steps that show the actual behavior vs. the behavior you're interested in, we can go from there.

Additionally, though we can tag issues as feature requests there's no guarantee that it will be implemented.

**Comment by mittalyashu** [comment]
If we start the atom and then drag a **file** to the atom, then it easily opens up.

But if we drag and drop the **folder** it doesn't open in the same atom window. Instead, it opens in a new atom window.

**Comment by rsese** [comment]
Thanks for clarifying :+1:

We have a high level issue about the different ways of launching Atom and I think the behavior you're talking about is basically referenced in that issue (where it talks about multiple project roots) so you can subscribe to that issue for updates if you'd like.

**Comment by mittalyashu** [comment]
Can you share me the link of that issue?

**Comment by rsese** [comment]
Oh sorry!  Forgot the link - here's the issue:

https://github.com/atom/atom/issues/10517

**Comment by mittalyashu** [comment]
Thank you. 👍
