### ISSUE TITLE
The editor has crashed - Please help.

### ISSUE THREAD

**Issue by MahmoudShiref** [atom/atom#15103]
I'm using linux elementary distribution.
atom was working good but recently when I open atom I've the error

> The editor has crashed
> Please report this issue to https://github.com/atom/atom
> Close window | Reload | keep it open

I tried to reinstall and I still have the same problem atom can't start and the same error appears
how to fix it??

**Comment by mpboom** [comment]
Maybe related to #15095?

**Comment by MahmoudShiref** [comment]
@mpboom thanks for replying..
I tried all solutions they suggested and no one worked with me.
please notice that I'm using linux and most of those replies on #15095 are for windows or macOs

**Comment by mpboom** [comment]
But did you try:
1. Disabling Github plugin
2. Run `atom —clear-window-state`
3. Try all steps in the debugging guide
(see previously linked issue)

**Comment by rsese** [comment]
Thanks for reaching out @MahmoudShiref!  @mpboom's suggested steps are good (thanks @mpboom :v:) and aside from the first suggestion about disabling the GitHub package, are referenced in the issue template.  The template provides super helpful baseline information (e.g. what version of Atom are you running, have you tried the debugging steps, etc.)  so if you can create a new issue and fill in the template we can go from there.  

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
