### ISSUE TITLE
Atom Suddenly doesn't work! 

### ISSUE THREAD

**Issue by instinctmodz** [atom/atom#15118]
I use to use Atom all the time until after opening it, it just give me a blank dark grey screen no matter what file I open it never shows up. The top with all the options still works fine. I've re-downloaded and it still is having the same problem. Someone please help me!

![capture](https://user-images.githubusercontent.com/19983539/28726330-b4eb3404-7375-11e7-828e-e9b1e78b4530.PNG)

Also Im running Windows 10.

**Comment by ylavoie** [comment]
Same here. When I check with task manager, it is growing endlessly, ant will eventually crash the PC, having consumed all available memory.

**Comment by mpboom** [comment]
Try the following:
- Run `atom —clear-window-state`
- If that does not help, delete `%appdata%\Atom`

**Comment by sreetamdas** [comment]
Vote to close this issue

**Comment by rsese** [comment]
Thanks for reaching out @instinctmodz - the issue template provides super helpful baseline information so if you can create a new issue and fill in the template we can go from there.  Please also go through the `Prerequisites` section and try the documented debugging steps (http://flight-manual.atom.io/hacking-atom/sections/debugging/
) and let us know if that helps or not.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
