### ISSUE TITLE
--log-file parameter didn't create log file

### ISSUE THREAD

**Issue by kenorb** [atom/atom#15144]
### Description

I'm running Atom with `--log-file` parameter, but the log file isn't created. Tested on macOS Sierra.

### Steps to Reproduce

```
$ /Applications/Atom.app/Contents/MacOS/Atom --help | grep log
  -l, --log-file             Log all output to file.  [string]
$ /Applications/Atom.app/Contents/MacOS/Atom -l ~/.atom/atom.log
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
$ ls -la ~/.atom/
# The log file is not there.
```

**Reproduces how often:** All the time.

### Versions

```
$ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.3
```

**Comment by rsese** [comment]
Reproduced with Atom 1.18.0 on macOS 10.12.6 and Atom 1.17.2 on Ubuntu 16.04.

**Comment by lee-dohm** [comment]
We should probably just remove this option.

**Comment by razvan-panda** [comment]
It is still not working on current version of Atom.

**Comment by sadick254** [comment]
`--log-file` option seem only to used in the context of running tests. This use case doesn't provide much benefits to a developer debugging. 
https://github.com/atom/atom/blob/e3fa3172e0ae58fa023abf1fcb11ec51e81371ee/spec/jasmine-test-runner.coffee#L142
Moving forward in my opinion we should deprecate the `--log-file` option since having a log file could be achieved by redirecting the output to a file.
```
# Unix based systems
atom --dev --foreground --wait > debug.log

# Windows 
atom --dev --foreground --wait >> debug.log
```

**Comment by sadick254** [comment]
Since the `log-file` option has been there for a long time. I think it would be better to clarify its usage other than deprecating it.
