### ISSUE TITLE
How to run background service using electron which runs even after closing the application

### ISSUE THREAD

**Issue by hitesh-soni** [atom/atom#15151]
i'm having an issue i want to start service which runs in background even after closing the application can anyone have solution?

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options - in particular for Electron, check out:

* [Discuss, the official Atom and Electron message board](https://discuss.atom.io) - under the `Electron` category
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/) - there's an `Electron` channel in the Atom Slack

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
