### ISSUE TITLE
CPU Usage dipping and partial freezing

### ISSUE THREAD

**Issue by Gumballll** [atom/atom#15156]
For some reason, every 7 seconds or so, atom freezes, and then about 5 seconds later works again. But it doesn't fade to white, Windows doesn't see it as not responding, it just stops working. When I perform an action, like a left click while it's "frozen", the action will occur when it resumes. When I look in Task Manager, then Atom's CPU usage dips from around 17%, to 0%. Then it goes up as soon as it is done "freezing". I've made a CPU profile report, downloadable here. https://drive.google.com/file/d/0B3GszVzFrkZBcllEaGU4azlnS2c/view?usp=sharing
I ran Atom in Administrator mode, didn't fix the problem. I also ran it in safe mode, didn't fix the problem. This problem started a few weeks ago. I was using a previous version (not sure which) of Atom when this problem started, but updating Atom to the latest (1.18.0) didn't fix it.

**Comment by rsese** [comment]
Thanks for reaching out @Gumballll - can you please either open a new issue with the template filled out or edit your issue body to include the template information?  In particular, thanks for letting us know that you tried in safe mode, but please let us know the results of going through the rest of the `Prerequisites` section (e.g. have you tried temporarily resetting to [factory defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults), etc.).  Also, the `Versions` section asks for your operating system version so please share that information as well.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15156#issuecomment-320328799. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
