### ISSUE TITLE
Double click on folder in folderlist crash atom

### ISSUE THREAD

**Issue by Daijobou** [atom/atom#15152]
Atom : 1.18.0
Electron: 1.3.15
Chrome : 52.0.2743.82
Node : 6.5.0

Windows 10 64bit (Version 1703)

Double click on folder (expand/collapse) in folderlist crash atom. Its happen very rare but today three times, for me, so I want report this issue now. :)

![grafik](https://user-images.githubusercontent.com/260343/28924027-859ee8a4-7860-11e7-8eef-fc90747872ce.png)

**Comment by Keydex** [comment]
How many items does your folder have?

**Comment by Daijobou** [comment]
This folder have only one file.

**Comment by rsese** [comment]
Thanks for reaching out @Daijobou - the issue template provides super helpful baseline information so if you can create a new issue or edit your issue body to fill in the template we can go from there.    In particular, please also go through the `Prerequisites` section if you haven't already and try the documented debugging steps (http://flight-manual.atom.io/hacking-atom/sections/debugging/
) and let us know if that helps or not.

It would also be helpful to know if you see the crash with random folders or the same folder, and if it always happens with the same project or not.

Lastly, sharing any crash logs you find could be helpful too:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
