### ISSUE TITLE
Please include ftp options in atom editor , not plugins!

### ISSUE THREAD

**Issue by lvar** [atom/atom#15167]
I love to use atom...but in my work I need several connection to devs servers and I already try many plugins in atom package store...but always have problems with upload files content to the server or in many cases i'm ending with empty files and all this problems are very anoying, so my options are using other text editors or IDE, but I really like atom....could you please incorporate your own ftp client on the editor ? I think it will be a very nice option and helpful!!!

cheers!

**Comment by rsese** [comment]
Thanks for reaching out!

We've passed along your suggestion to the maintainers team - because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.
