### ISSUE TITLE
Atom keeps crashing on launch.

### ISSUE THREAD

**Issue by ShannuVeeranki** [atom/atom#15187]
As soon after launching Atom application, get a crash message and asks to report to github, reloading the application or reinstalling the application doesn't help.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
