### ISSUE TITLE
Editor freezes trying to update big file

### ISSUE THREAD

**Issue by livace** [atom/atom#15181]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Editor freezes trying to update big file. After reopening it works fine.

### Steps to Reproduce

1. Open file in Atom
2. Edit this file using anoter editor and make it big (~50 000 lines / 400 kb)
3. See Atom freezes

**Expected behavior:** Atom updates file

**Actual behavior:** Atom frezes

**Reproduces how often:** 100%

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1

Windows 10 Pro

### Additional Information
I can't run atom in safe mode to test bug.

**Comment by rsese** [comment]
Thanks for the report - it's super helpful if you can fill out the entire issue template.  In particular, the `Prerequisites` section let's us know if you tried the debugging suggestions like running in safe mode.  Can you update your issue body to let us know if you tried the suggestions in the `Prerequisites` section?

Also, can you try disabling the spell-check package and see if that makes a difference?   There's a Windows specific [bug](https://github.com/atom/spell-check/issues/190) that's fixed in beta I believe but not in 1.18.0 so I'm curious if that's related.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15181#issuecomment-320732420. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
