### ISSUE TITLE
Uncaught TypeError: Cannot read property 'updateCursorBlinkSync' of undefined

### ISSUE THREAD

**Issue by NoelAnderson** [atom/atom#15192]
[Enter steps to reproduce:]

1. Using Mulesoft API-bench
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'updateCursorBlinkSync' of undefined

```
At C:\Users\noela\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:241

TypeError: Cannot read property 'updateCursorBlinkSync' of undefined
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:241:38)
    at etch.getScheduler.updateDocument (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:220:46)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.0/resources/app/src/view-registry.js:187:15)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/view-registry.js:3:65
```

### Commands

```
```

### Non-Core Packages

```
api-workbench 0.8.46 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.3 
```

**Comment by rsese** [comment]
Thanks for the report - is the error reproducible for you?   If so, I'd suggest reporting this to the [api-workbench](https://github.com/mulesoft/api-workbench) maintainers since it sounds like the error happens for you specifically when using that package.  It may be that there is still a bug in Atom however and if so, we'll need the api-workbench maintainers to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
