### ISSUE TITLE
Question : Does the new Github/Git feature contain an api or SCM provider ?

### ISSUE THREAD

**Issue by rwatts3** [atom/atom#15195]
Greetings,

It would be great to provide a package that also adds support similar to the Git integration for other SCM providers such as `hg` and `svn`. 

However I was not able to locate a package that contains the Git part of the feature.

**Comment by Arcanemagus** [comment]
This depends on what you mean by "integration". Do you mean the file change status? Or the ability to push commits and generally manage the repo?

**Comment by rwatts3** [comment]
I believe both . Mainly what they’re are considering the Git / Github new feature.  Is that structured in core or via a core package

**Comment by Arcanemagus** [comment]
That is handled in https://github.com/atom/github. The integration into the editor itself showing the changed lines is handled elsewhere, for `svn` at least there is https://atom.io/packages/svn.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
