### ISSUE TITLE
Atom crashing on Windows 10 , requires constant clear window state. 

### ISSUE THREAD

**Issue by danrossi** [atom/atom#15201]
Safe mode does nothing. Require to launch clearing window state. This same problem was happening on OSX. 

I am not certain yet but the editor on Windows is screwing line feeds in git client. Its not inserting unknown characters anymore and breaking building javascript files in Linux subsystem like it did before however.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by danrossi** [comment]
going back to sublimetext no worries.
