### ISSUE TITLE
Huge memory consumption upon startup

### ISSUE THREAD

**Issue by james-noaa** [atom/atom#15212]
I run Atom inside a VirtualBox (5.1.24) Linux Mint 18.2 MATE guest (on a Win7 host). Any released version of Atom higher than 1.16, including the recently released 1.19, consumes such a huge amount of memory upon startup, that it effectively halts/OOMs my VM.
Watching memory consumption upon startup, in 1.16 it consumes about 1GB total before settling back down to 400-500MB. But above 1.16, it consumes around 2.4GB while starting up - or more likely that is simply all that is available in my VM.
Something changed in 1.17 to gobble up all that memory. Amazing if nobody else is having an issue with this. I have tried disabling all plugins, no diff.
I'm obviously stuck on 1.16 until this is resolved.
Thanks.

**Comment by rsese** [comment]
Thanks for reaching out @james-noaa - can you please either edit your issue body to include the template information or open a new issue with the template filled out?  That'll be helpful for folks that try to reproduce, any VM specific settings could be helpful too.

Also, do you happen to have a particular project open when you see this behavior?  And you reference trying safe mode, did you also try temporarily resetting to [factory defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults)?

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by DarkPurple141** [comment]
Somewhat related. Startup is causing a massive memory and performance hit. This has only occurred since update.

Error from apm test:
`[866:0810/122428.632969:INFO:CONSOLE(108)] "Error: Cannot find module '/Users/Me/.atom/spec'
  at Module._resolveFilename (module.js:470:15)
  at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:350:52)
  at Function.Module._load (module.js:418:25)
  at Module.require (module.js:498:17)
  at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:47:27)
  at requireSpecs (/Applications/Atom.app/Contents/Resources/app/spec/jasmine-test-runner.js:99:7)
  at module.exports (/Applications/Atom.app/Contents/Resources/app/spec/jasmine-test-runner.js:47:7)
  at module.exports (/Applications/Atom.app/Contents/Resources/app/src/initialize-test-window.js:92:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:106:12)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:67:9)
", source: /Applications/Atom.app/Contents/Resources/app/src/initialize-test-window.js (108)
Tests failed`

Package List:

```
Built-in Atom Packages (91)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.5
├── one-light-ui@1.10.5
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.2
├── autocomplete-html@0.8.0
├── autocomplete-plus@2.35.5
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.86.0
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.4
├── exception-reporting@0.41.4
├── find-and-replace@0.208.3
├── fuzzy-finder@1.5.8
├── github@0.3.4-0
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.12
├── metrics@1.2.6
├── notifications@0.67.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.250.0
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.11
├── styleguide@0.49.6
├── symbols-view@0.116.1
├── tabs@0.106.2
├── timecop@0.36.0
├── tree-view@0.217.2
├── update-package-dependencies@0.12.0
├── welcome@0.36.4
├── whitespace@0.37.2
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.3
├── language-coffee-script@0.48.7
├── language-csharp@0.14.2
├── language-css@0.42.2
├── language-gfm@0.89.1
├── language-git@0.19.1
├── language-go@0.44.1
├── language-html@0.47.3
├── language-hyperlink@0.16.1
├── language-java@0.27.2
├── language-javascript@0.126.1
├── language-json@0.19.1
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.39.0
├── language-property-list@0.9.1
├── language-python@0.45.3
├── language-ruby@0.71.1
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.1
├── language-source@0.9.0
├── language-sql@0.25.6
├── language-text@0.7.3
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.1
└── language-yaml@0.30.0

Community Packages (25) /Users/TheHD/.atom/packages
├── Zen@0.18.0
├── autocomplete-java-minus@0.14.0
├── autocomplete-python@1.10.0
├── busy@0.7.0
├── busy-signal@1.4.3
├── file-icons@2.1.10
├── highlight-selected@0.13.1
├── intentions@1.1.5
├── java-classpath-registry@0.4.0
├── java-import-wiz@0.5.0
├── java-plus@0.1.0
├── linter@2.2.0 (disabled)
├── linter-flake8@2.2.1 (disabled)
├── linter-js-yaml@1.2.7
├── linter-ui-default@1.6.4 (disabled)
├── markdown-writer@2.6.5
├── minimap@4.29.6
├── minimap-highlight-selected@4.6.1
├── monokai-seti@0.9.0
├── open-recent@5.0.0
├── pigments@0.40.2
├── script@3.15.0
├── seti-ui@1.9.0
├── sort-lines@0.14.0
└── todo-show@1.11.0
```

**Comment by 50Wliu** [comment]
@DarkPurple141 please make sure that you do not have a `~/.git` folder.  If you do, it should be safe to rename it to `~/.git-backup`.

**Comment by branditodesign** [comment]
@DarkPurple141 
If you're still having issues related to this, I had just installed the pigments package, same version as yourself and it choked my entire computer, using 10GB+ of RAM and upon restarting the computer and starting Atom up, it used 12GB+ of RAM! Disabling the pigments package has fixed this for me.

**Comment by DarkPurple141** [comment]
@50Wliu I don't have a ~/.git folder.

@branditodesign Yeah I've just had it disabled since August tbh. A real shame I guess the root issue is with pigments?

**Comment by branditodesign** [comment]
@DarkPurple141 Sadly I just installed it but a few minutes later, uninstalled it.
There was a similar plugin in Sublime Text 3 which I used although became quite buggy with later releases (the author said he's been adding features on top of a terribly written plugin, since the plugin dates back to Sublime Text 2).

If anyone finds a decent colour highlighting plugin for Atom please let us know!
