### ISSUE TITLE
Weird when editing text which is partial selected

### ISSUE THREAD

**Issue by yubaoquan** [atom/atom#15216]
### Prerequisites

I don't think the prerequistes is needed this time.

### Description

Pretty difficult to describe, this is a [demo](https://raw.githubusercontent.com/yubaoquan/yubaoquan.github.io/master/images/selection.gif) picture.

### Steps to Reproduce

1. Type some text in the editor, for example `aaaaabbbbb`.
2. Select the left part of the text like `aaaaa`.
3. Type a letter `x`.

**Expected behavior:** the text becomes `xbbbbb` and no charcters are selected.
**Actual behavior:** the text becomes `xbbbbb` but the middle 4 `b` are selected.

**Reproduces how often:** Many times, but not every time.

### Versions

1.19.0

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
