### ISSUE TITLE
Please add explicit link to Package’s Github repo on Package settings file in Atom

### ISSUE THREAD

**Issue by brandondurham** [atom/atom#15233]
### Description

[Description of the issue]
The Package view for any particular package doesn’t include a direct link to the Github repo, which cold prove very helpful.

### Steps to Reproduce

1. Open Preferences.
2. Select “Packages.”
3. Select any installed Package.
4. Notice there are only links to that Package’s Atom.io page, Github issues page (close!), the Changelog file, the License, and a “View Code” link.

**Expected behavior:** I come to the Package’s settings page to visit their Github Repo home page.

**Actual behavior:** I come here often expecting to see the link to the repo only to remember that I have to go through Atom.io.

**Reproduces how often:** 100%

### Versions

Atom 1.18.0 x64

**Comment by rsese** [comment]
Thanks for the suggestion!  An enhancement request for the settings-view should go in the [settings-view](https://github.com/atom/settings-view/) repository but I do believe there is a repository link?  

![repo-link](https://github-slack.s3.amazonaws.com/monosnap/Settings__sandboxhello-world_2017-08-10_12-45-58.png)

Maybe missed because it's not a button like the rest of those details?

If I'm mis-understanding please let me know :v:
