### ISSUE TITLE
`git rebase` not working properly with atom editor

### ISSUE THREAD

**Issue by mattcollier** [atom/atom#15246]
I have been using atom as my preferred editor with git for a long time by way of
`git config --global core.editor "atom --wait"`

I commonly do `git rebase -i <hash>`.  As of the 1.19.0 release after putting the rebase command in the console, a list of seemingly unrelated commits is presented to me.  If I delete all the lines/commits presented to me in order to cancel the operation (git responds 'nothing to do'), and repeat the rebase command, the proper commits are listed the *second* time and all is well.

This is on Debian Linux v9 and git version 2.11.0.

**Comment by kodamirmo** [comment]
+1 Same on mac:
- Mac OS Sierra 10.12.6
- Atom 1.21.2
- Git 2.11.0

**Comment by rsese** [comment]
Thanks for the report - I wonder if this was fixed by https://github.com/atom/github/pull/1238? Can either of you confirm if you still see this problem?  The fix is in 1.23, currently in beta.

If either of you can still reproduce in 1.23, please open an issue in https://github.com/atom/github/ and fill out the issue template so the team can take a look.
