### ISSUE TITLE
The editor has always crashed

### ISSUE THREAD

**Issue by ziyu-93** [atom/atom#15250]
The editor always crashes, 5 minutes will happen once, hoping to get help

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
