### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by Ilias48rus** [atom/atom#15259]
Tilting mouse wheel momentary scrolling to horizontal end (shift+scroll working fine),
anyone know how to fix it ? (in window's mouse settings horizontal scrolling set to 1 character,
setting vertical scroll on tilting the wheel and using it do not changing the vertical scrolling behaviour)

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
