### ISSUE TITLE
Cursor is visible on multiple input fields

### ISSUE THREAD

**Issue by Netroxen** [atom/atom#15252]
Since updating to the new Atom 1.20 the cursor is visible on multiple input fields, I tried removing the compiled-cache to no avail. This seems to be a bug or compatibility issue.
![peek 2017-08-11 09-00](https://user-images.githubusercontent.com/7691449/29203820-ad6ad3b6-7e73-11e7-9d98-df2c71832944.gif)

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
