### ISSUE TITLE
"esc to close" is missing from error messages

### ISSUE THREAD

**Issue by willnwhite** [atom/atom#15268]
See https://github.com/prettier/prettier/issues/2615. That error is in prettier-atom, but I think it applies to any error message in Atom.

**Comment by 50Wliu** [comment]
The notifications respond to the `core:cancel` command.  By default, that command is bound to <kbd>Esc</kbd>, but since anyone can rebind it, saying "Press escape to close" is misleading.

In addition, this issue belongs on the [atom/notifications](https://github.com/atom/notifications) repository.  If you decide to file an issue there, make sure you fill out the entire issue template.  Thanks!
