### ISSUE TITLE
code folding using language-blade

### ISSUE THREAD

**Issue by leiangelli** [atom/atom#15269]
I can't seem to "fold" code blocks while using "language-blade" package.
It only seem to happen when I enable language-blade, and only if the **blocks has comments**.

![317277ea74917da05e12c79334ab20c1](https://user-images.githubusercontent.com/7858310/29239908-0eae3eba-7f8c-11e7-997c-f0d52aab2ab6.gif)

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [language-blade](https://atom.io/packages/language-blade) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
