### ISSUE TITLE
GitHub for Mac stopped detecting changes on my repo after installing Atom and opening the repo as a project

### ISSUE THREAD

**Issue by ppazos** [atom/atom#15294]
### Description

Have GitHub (GUI) for Mac, installed Atom and opened a project in Atom.
After that, when I tried to commit my changes using GitHub, none of the changes done appear on GitHub.
Not sure if the GitHub package of Atom is causing problems wit the GitHub app for Mac.
Trying to sync via the GitHub app says "Could not create status list".
Before installing Atom the app worked OK.

### Versions

Atom 1.19.0 x64
MacOS 10.12.6

**Comment by rsese** [comment]
Thanks for the report!  I chatted with our Desktop support folks and though the issue could be Atom related, we'd like to look at it from the Desktop app perspective first - can you open a ticket describing the issue here?

https://github.com/support

I'll keep an eye out for it and if it ends up being an Atom issue, we can open an issue in the https://github.com/atom/github/ repository.

**Comment by ppazos** [comment]
@rsese thanks, will do.

BTW, after trying some things, git add . fixed the issue, after that I started to see the changes on my code from the github desktop app.

**Comment by rsese** [comment]
Ahhh great glad to hear it :+1:
