### ISSUE TITLE
QUESTION - Update 1.18.0 x64

### ISSUE THREAD

**Issue by jonjie0317** [atom/atom#15303]
The last update is great. But I just wanna ask when do you have an update for the optimization, I mean to make atom more faster to load, because sometimes it ends with 

> Atom is Not responding

I really love atom for doing web stuffs, but the only thing it make me sad is the slowing part. I hope you'll have an update for this. Thanks a lot for your effort and making atom FREE. I really appreciate this editor.

Cheers! 👍

**Comment by rsese** [comment]
Thanks for reaching out and for the kind words!  We'll go ahead and close this issue as described below but additionally, if there's been specific performance work done in a particular release, we'll likely describe it in some detail in the release blog post like we did for 1.17 and 1.19:

* http://blog.atom.io/2017/05/16/atom-1-17.html
* http://blog.atom.io/2017/08/08/atom-1-19.html

If you run into a case where Atom hangs though, feel free to open an issue and completely fill out the issue template so we can take a look.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
