### ISSUE TITLE
[VGL] ERROR: in initVW--   88: Invalid argument

### ISSUE THREAD

**Issue by lvzongting** [atom/atom#15304]
I install atom from source release-1.19.1 in rhel7.3 

The install is very smooth and successful. But when I run atom, I get some error in the nohup.out

[VGL] ERROR: in initVW--
[VGL]    88: Invalid argument

what can I do next? Thanks.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out (it's ok if some of the items don't apply to your situation, just provide as much detail as possible), that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
