### ISSUE TITLE
[Feature Request] Easier access to Indent configuration

### ISSUE THREAD

**Issue by mindietea** [atom/atom#15301]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is a small quality of life change-- changing indents should be quick and intuitive. Right now, it's not a good experience to configure indentations in Atom, which is kind of a bother when the rest of Atom is so sleek yet something as important as indentation changes are a bit of a hassle to change.

### Steps to Reproduce

1. Ctrl + Shift + P to bring up the Command Palette and look up "Indent" doesn't produce any results that lead to changing indentation settings. They're all commands to insert indentation which I doubt is used often.
2. So now we dig into File > Settings > Editor. Scrolling down and down and down, we then find the option to change Tab Length. I assume this changes how tabs are inserted from the time of changing this setting? It's also unclear how to not use spaces to represent tabs and instead use tab characters, which it turns out is the "Soft Tab" checkbox which is not necessarily a familiar term.
3. "Whitespace: Convert Tabs to Spaces" doesn't seem to work as intended. I have an open file with tab characters as tabs, I hit Ctrl + Shift + P and select "Whitespace: Convert Tabs to Spaces." The tabs remain tabs. I'm not sure of the difference, so I try the separate option of "Whitespace: Convert All Tabs to Spaces." Still nothing.

**Expected behavior:**

1. Opening the Command Palette and searching "Indent" should lead to the settings for changing indentation.
2. It should be much clearer what your tab settings are and how to change them. I suggest at least putting "Tab Length" and "Soft Tabs" in the same line, because it seems if you have "hard tabs" selected and "tab length" set, the tab length doesn't actually matter. Also why is there both a check box for Soft Tabs and a dropdown to select Tab Type? It's unclear which one is preferred. It should be clearer at a glance what my current tab behavior is and which settings will change it.
3. The commands for "Whitespace" to convert various indentations should work. Also it's unclear if it's changing all whitespace for the current file or active project. It would be nice to have to option to choose the scope of indentation changes.

**Actual behavior:** n/a

**Reproduces how often:** n/a

### Versions

Atom v.1.19.0
Windows 7

### Additional Information

This is mostly a small user experience issue, but Atom is so sleek and smooth to use that I'd love to see it be more user-friendly. I understand that Atom is highly configurable/programmable, but it seems at odds that it requires a LOT of digging/Googling to figure out what configurations do and how to change them when it seems to be aiming to be intuitive and UX-focused.

Thanks for reading!

**Comment by oyeanuj** [comment]
As a tab-user, I'd super upvote this, and add one more point to the expected behavior. 

4. Choosing from the space/tab menu in the bottom bar should reflect in the active/focused file right away. FWIW, that is also the behavior on Sublime!

Thanks @mindietea for filing this and all the contributors for making Atom happen!

**Comment by mindietea** [comment]
@oyeanuj Good thought; yep text editors like Sublime Text and Visual Studio Code find tabs important enough to have real estate in the bottom bar where you can see what your current tab configuration is, and clicking it opens settings to change your tabs.

**Comment by 50Wliu** [comment]
I'll try to answer some of your questions here, but you're right, this area has a lot of room for improvement.

* The Command Palette only lists commands.  Generally, settings aren't commands, so they won't get listed.
* From experience, it would seem that most developers are familiar with the term "soft tabs" vs "hard tabs".  We could add a detail explaining that soft tabs = spaces though.
* There's an open issue for tabs-to-spaces conversion not working at https://github.com/atom/whitespace/issues/149.  Could you please try to add some info to that issue, such as: is the conversion broken on all files?  What line endings do your files have?
* Tab Length is still relevant when hard tabs are selected, as it changes the visual length of the tab character (rather than the amount of spaces inserted when soft tabs are used).
* The Tab Type setting is the primary config value.  If that setting is "auto" and the tab type can't be auto-detected, then it uses the Soft Tabs setting.
