### ISSUE TITLE
The experience of this software on windows is rubbish

### ISSUE THREAD

**Issue by webKity** [atom/atom#15326]
The experience of this software on windows is rubbish！！！！！Frequent crashes！！！！No use after reloading！！！

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by webKity** [comment]
当我打开atom的时候，经常会卡在这里，卸载atom后重装，也还是这样


![Uploading }DUV0W5[LTAG8JL_@(OU]86.png…]()
