### ISSUE TITLE
snippets : "unexpected :"

### ISSUE THREAD

**Issue by inwardmovement** [atom/atom#15321]
Hi,
I can't create snippets, an error "unexpected :"  is returned.
My snippet code is : 
```
'text.plain':
	'HTML Bootstrap':
		'prefix': 'bs'
			'body': 'test'
```

![image](https://user-images.githubusercontent.com/9438102/29330567-e6d86ecc-81f9-11e7-818c-373c5b8eee5d.png)

Can you help please ?

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
