### ISSUE TITLE
Atom显示拼音不完整

### ISSUE THREAD

**Issue by liuqinh2s** [atom/atom#15332]
![Atom显示拼音不完整](https://liuqinh2s.github.io/resource/2.gif)

![sublime text显示拼音完整](https://liuqinh2s.github.io/resource/3.gif)

**Comment by Ben3eeE** [comment]
This looks like the issue that was fixed in Atom 1.19.1 please upgrade to the latest version.

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
