### ISSUE TITLE
Multiple selection in project files tree @featurerequest

### ISSUE THREAD

**Issue by sartatpdev999** [atom/atom#15375]
Hi. It's able to select multiple files/directories in project files tree by Ctrl+Click. But it's unavailable to select multiple items by Shift+Click. Seems to be useful to release this feature.

Thanks.

**Comment by Ben3eeE** [comment]
This issue belongs in the [tree-view](https://github.com/atom/tree-view/issues) repository. Please open an issue there if one does not already exist. We also require that the issue template is filled out on all new issues.

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
