### ISSUE TITLE
Unable to Check for Updates?

### ISSUE THREAD

**Issue by jajaperson** [atom/atom#15398]
### Description

After downloading the **:atom: atom** [1.19.2](https://github.com/atom/atom/releases/tag/v1.19.2) update and restarting atom I received the following alert:

> __There was an error checking for updates__
> The command is disabled and cannot be executed

Atom seems to be working fine and the update did install, but before that I couldn't even get the update to install. I would keep having to download the update and restart atom, but the update didn't install and I would just get this alert.

**Comment by Jahhein** [comment]
I seem to be having an issue with APM, perhaps relating to this.

Can you try running the following command for atom's package manager in the terminal.
apm is the atom package manager command.

`apm outdated; apm update;`

let me know if this gets you your updates, however let me know if a graphical error shows up. Running `apm update` for seems to be all distorted on the output. Nothing shows up correctly since they make it look fancy when updating.

**Comment by rsese** [comment]
Thanks for reaching out!

Feel free to try @Jahhein's suggestion @jajaperson and let us know if that helps but we'll go ahead and close this issue as mentioned below.  

There's a similar issue with more details so you can subscribe there for updates if you'd like /cc https://github.com/atom/atom/issues/15417.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
