### ISSUE TITLE
Moving lines by control-command up/down goes wrong

### ISSUE THREAD

**Issue by ethancfchen** [atom/atom#15405]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I select some lines and want to move it, the editor will also move the line what I don't want to move, or missing some selected lines.

### Steps to Reproduce

1. Insert some random lines.
2. Select the last 2 lines.
3. Moving up 3 times by `control + command + ↑`

**Expected behavior:** [What you expect to happen]

![8 -22-2017 13-41-48](https://user-images.githubusercontent.com/5051791/29550667-7867a320-8741-11e7-9962-da3e4a37e460.gif)

**Actual behavior:** [What actually happens]

![error1](https://user-images.githubusercontent.com/5051791/29550664-73027b08-8741-11e7-84a4-9e18994e17b8.gif)
![error2](https://user-images.githubusercontent.com/5051791/29550665-7460ef02-8741-11e7-812c-3ac5e63b8413.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?]

Sometimes.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

OS: macOS Sierra 10.12.6

```bash
atom --version

Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```bash
apm --version

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.6.4
```

### Additional Information

I'm using trackpad as mouse and not holding any buttons when moving, but I think it's related to #15217.

**Comment by Ben3eeE** [comment]
Thanks you for the report :bowing_man: This does seem related to #15217 as you say. We have a pull request that restores the behavior as it was in Atom 1.18 so that text input does not repeat selections if the mouse is still held down but it seems that commands still can repeat selections as reported in https://github.com/atom/find-and-replace/issues/520.

This issue will be closed when https://github.com/atom/atom/pull/15407 is merged and if you still can reproduce this in Atom 1.19.3 I suggest subscribing to https://github.com/atom/find-and-replace/issues/520 for updates.
