### ISSUE TITLE
Lint Errors Obscure Autocomplete Suggestions

### ISSUE THREAD

**Issue by dominic-p** [atom/atom#15402]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Apologies if this is the wrong repo or this has already been reported (I tried searching a bit before posting). Since updating to 1.19.x I have noticed that linting errors show up more aggressively as I type hiding the autocomplete suggestions (see screenshot).

![atom-screenshot](https://user-images.githubusercontent.com/1195080/29533988-1cee71c8-8669-11e7-8f9c-574374d85a15.png)

### Steps to Reproduce

1. Start typing (almost anything will trigger lint errors as you type)
2. The lint error shows above any autocomplete suggestions

**Expected behavior:** The autocomplete should be visible

**Actual behavior:** The linter error obscures the autocomplete

**Reproduces how often:** ~90% of the time (not always but almost)

### Versions

I'm on Windows 10 build 1607

Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 ia32
python
git 2.11.1.windows.1
visual studio

### Additional Information

I'm using linter-eslint v8.2.1. Maybe this is a bug for that repo, but I'm posting it here since it worked perfectly before update to Atom 1.19 and it seems like there have been some changes in core related to linting lately.

**Comment by 50Wliu** [comment]
Please report this to whatever Linter UI package you're using (most likely [linter-ui-default](https://atom.io/packages/linter-ui-default)).  However, it may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
