### ISSUE TITLE
Terminals don't work on the new update 1.19.2

### ISSUE THREAD

**Issue by codingphasedotcom** [atom/atom#15408]
Hi I just downloaded the latest 1.19.2 version of atom now none of the terminal packages work 
platformio-ide-terminal
terminal-plus
atom-terminal
terminal-panel

**Comment by Ben3eeE** [comment]
Thanks for contributing!

It appears that this is being caused by the various terminal packages you have installed, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
