### ISSUE TITLE
Atom is completely stuck in my computer even after restarting

### ISSUE THREAD

**Issue by dasphillipbrau** [atom/atom#15425]
I used atom for a couple of days and everything was working fine. One day, I closed the program as usual, no problems at all, then I turned off the PC. Next time I turned it back on, I tried opening Atom and I would just get the "loading" cursor, which would immediately disappear and Atom would never open.

Looked for open processes and there's none of them open. Restarted PC, still not opening.

Tried uninstalling and the program is like hard stuck to my system, uninstalling isn't doing jack, it's not uninstalling the program. What can I do?

Wont even launch in safe mode

**Comment by Ben3eeE** [comment]
Please follow the steps in https://flight-manual.atom.io/hacking-atom/sections/debugging/ as mentioned in the required issue template.

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
