### ISSUE TITLE
Toggle Packages per Language in config.cson?

### ISSUE THREAD

**Issue by brograhamer** [atom/atom#15424]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I want to enable / disable (toggle) certain plugins depending on the language. For example, I use `minimap` and `fold-navigator`. On SASS / JADE files I want to toggle the `fold-navigator`, but in PHP files I want to toggle the `minimap`.

### Steps to Reproduce

N/A

**Expected behavior:**

Open `file.jade`, and `plugin-1` is enabled (toggled).

Open `file.php`, and `plugin-2` is enabled (toggled), while `plugin-1` is disabled (untoggled).

**Actual behavior:**

N/A

**Reproduces how often:**

N/A

### Versions

Latest Beta

### Additional Information

Can't find anything on this. Asking here is my last resort.

**Comment by rsese** [comment]
This isn't possible as far as I know - a similar idea I've seen in issues is https://github.com/atom/atom/issues/6619 though yours is a bit more specific.

Going to go ahead and close since we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), and we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).
