### ISSUE TITLE
atom 1.9.2 1.93 there are white block in the bottom and left side in the workspace.

### ISSUE THREAD

**Issue by nikxliu** [atom/atom#15429]
###ENV
window 10
atom 1.19.2 1.19.3
###Problem
After I update my atom to 1.19.2 and 1.19.3.
When I open a new file ,I found there was a white block in the bottom. When I moved the mouse pointer to the white block, I found it is the linter plugin's pop button.
When I click the button , linter plugin pop and click again it was hidden. At the same time the issue disappeared.

following is the image.
![atom white block1](https://user-images.githubusercontent.com/12636544/29646438-0ab4b108-88b6-11e7-9842-70be6b63b01a.png)

**Comment by Ben3eeE** [comment]
Thanks for contributing!

It appears that this is being caused by the [linter-ui-default package](https://github.com/steelbrain/linter-ui-default/issues), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by nikxliu** [comment]
ok. I think i must post this at leat two times to linter ,go-plus.
