### ISSUE TITLE
Analytics from Packages

### ISSUE THREAD

**Issue by Extarys** [atom/atom#15457]
I do understand the need of analytics but I hate Google having all sort of data from all sorts of sources (they can use any data collected for their use too)

I have the metrics package activated because I want to help atom, but it would be nice to have a list of packages that have analytics in them of a toggle to disable analytics from packages.

I discovered a couple of packages that use it and didn't say much about that.

I feel betrayed :P

**Comment by 50Wliu** [comment]
The two core Atom packages that collect metrics are `metrics` and `exception-reporting`.  I see you're already familiar with metrics.  `exception-reporting` reports uncaught exceptions to Atom's [BugSnag](https://www.bugsnag.com/) account and is governed by the same `core.telemetryConsent` setting that `metrics` is.  Technically, `notifications` hits the GitHub API to see if an uncaught exception has already been reported, but you get the final say in whether or not an issue is created.

Community packages, on the other hand, are generally free to do what they want.  While I personally agree that community packages should disclose whether or not they are collecting metrics, Atom does not require them to.  Therefore, Atom also doesn't have a list of packages that collect metrics.

I'm closing this issue because Atom's issue tracker is treated as its [backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), and this issue [doesn't  represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

If you have any further questions/follow-up discussion, I would highly recommend that you create a new topic on [Discuss, the official Atom and Electron message board](https://discuss.atom.io), which is better suited for these types of topics.

**Comment by Extarys** [comment]
Thanks for your answer, I fully understand.

Too bad some people doesn't care :P

I will disable all tracking hosts directly into the router.

Thanks again! Cheers

**Comment by hmadali** [comment]
تعلم الاختراق
