### ISSUE TITLE
'restorePreviousWindowsOnStart: "no"' doesn't work when opened via context menu option

### ISSUE THREAD

**Issue by DominikSerafin** [atom/atom#15452]
### Description

This only involves "Open with Atom" context menu option on Windows. Both ON folder and INSIDE folder. Otherwise this option works as it should.

This is a major issue for me because "Window state load time" takes almost a second (919ms) for me to execute. And also because I always need to close all tabs and tree items in sidebar to start working which is tiring when you switch between projects multiple times a day. 

### Steps to Reproduce

1. Set `restorePreviousWindowsOnStart: "no"` 
2. Open project and open some files/windows
3. Close Atom
4. Open the same project using "Open with Atom" context menu option

**Expected behavior:**
Atom opens project with all the folders in sidebar collapsed and without any files/tabs opened

**Actual behavior:**
Atom opens the project with the exact last state when it was closed

**Reproduces how often:**
100%

### Versions
```
Windows 10 Pro 1703 (OS Build: 15063.540)
```
```
Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 3.6.1
git 2.12.2.windows.2
visual studio
```

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

**Comment by rsese** [comment]
Thanks for the report - as far as I know this is expected behavior whenever you pass a path to Atom (through the command line or through `Open with Atom`) and is also mentioned in the PR that talked about adding `restorePreviousWindowsOnStart` https://github.com/atom/atom/pull/9042#issuecomment-202987038.

But I can see how the behavior could be confusing and startup behavior overall is currently being tracked in https://github.com/atom/atom/issues/10517 so you can subscribe there for updates if you'd like.
