### ISSUE TITLE
Improve the Notifications design

### ISSUE THREAD

**Issue by mittalyashu** [atom/atom#15455]
![image](https://user-images.githubusercontent.com/29014463/29742660-dd59d1ba-8aa0-11e7-90dc-54975c8cc5dc.png)

This notification from Atom seems old fashioned. How we can improve the design of the notification or it will be improved in future updates?

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
