### ISSUE TITLE
The Git files function is not work in beta4 sometimes.

### ISSUE THREAD

**Issue by youngjuning** [atom/atom#15468]
My English is not well，But I love Atom.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
