### ISSUE TITLE
Welcome Guides are shown on every startup

### ISSUE THREAD

**Issue by derwaldgeist** [atom/atom#15473]
I recently updated two packages (not sure which). After Atom reloaded, it reset a lot of my personal settings, like the font I was using and the syntax theme. It also showed the welcome guides (Atom's welcome guide, Nuclide's welcome guide and the Telemetry opt-in) again.

I could reset my other settings and get rid of the Telemetry opt-in dialog, but these ** welcome guides show up every time (!) I reload Atom, even if I close them before reloading Atom. Is there any chance to get rid of these dialogs? It's quite annoying, especially because one of these guides is shown in a separate tab.

The Welcome Page and the Welcome Guide also show up if I run Atom in --safe mode. Only Nuclide's welcome guide is missing then.

**Comment by Ben3eeE** [comment]
https://discuss.atom.io/t/how-do-i-make-the-welcome-screen-stop-showing-up/40403

---

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by derwaldgeist** [comment]
Ah, ok, I see. This was a side-effect of Atom losing my configuration. I didn't remember I had to disable these dialogs using a check-box. 😅

**Comment by 50Wliu** [comment]
Oh yeah, sorry about the config issue.  We're investigating it in #14909.
