### ISSUE TITLE
uninstaller to remove all leftovers(clean uninstall tool)[FR] - Windows

### ISSUE THREAD

**Issue by Sibiraj-S** [atom/atom#15481]
#### Feature Request

Why not have an uninstaller for atom separately since the atom doesn't completely uninstall in windows.
A lot of leftovers are left behind.

Mostly while reinstalling atom. It doesn't install properly due to registry errors(leftovers) and leftovers of the previous installation

**Comment by rsese** [comment]
Thanks for reaching out!  Even though everything in the issue template doesn't necessarily apply to feature requests, it would be really helpful if you could use fill it out, in particular when describing actual vs. expected behavior in detail.  Feel free to open a new issue or edit the issue body in this one.

For example, it would be great if you could share more specifics about what leftovers you think should be removed (or are you just referring to the registry entries?).

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
