### ISSUE TITLE
Slow install from zip/rar

### ISSUE THREAD

**Issue by XDelta** [atom/atom#15484]
Slow install from zip/rar caused by having thousands of small files to be unpacked. Suggested fix consolidate files to reduce file count. Currently ~33,000 files in ~10,800 folders for 516MB

**Comment by rsese** [comment]
Thanks for reaching out!

I believe https://github.com/atom/atom/pull/14682 might help with this.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
