### ISSUE TITLE
Memory is too large

### ISSUE THREAD

**Issue by adustdu2015** [atom/atom#15526]
occupancy  so much memory  in  win7 or other wins,  The experience  is so bad .
 the process is always  no  response.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
