### ISSUE TITLE
Horizontal scrolling is not smooth

### ISSUE THREAD

**Issue by SachinKodagoda** [atom/atom#15525]
i am using the latest atom update and windows 10 updated version
when i do horizontal scrolling it doesn't move smoothly. 
when i have a long code it is hard to do the horizontal scrolling because it is too small. i like to have a "Key+Scrolling" to do the horizontal scrolling easily.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
