### ISSUE TITLE
backticks in Mac OS are dodgy.. 

### ISSUE THREAD

**Issue by ozzie1998** [atom/atom#15531]
This is not an issue I can debug, and it is bloody irritating! 

In order to type backticks, I have to do a ` and then a left arrow on my keyboard, to get the closing backtick. As a note, this does not happen in VSC, and I can type backticks normally.

**Comment by rsese** [comment]
Thanks for reaching out!  Filling out the issue template is super helpful for us since it provides basic details like what version of Atom are you running (`atom -v`), what OS version are you running, etc.  Please open a new issue with the template filled out or edit the issue body and we can go from there.

Also, can you clarify what you mean when you say:

> In order to type backticks, I have to do a ` and then a left arrow on my keyboard, to get the closing backtick. 

Maybe a GIF or screencast of the behavior you're seeing might be helpful.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by ozzie1998** [comment]
There are no error messages, or anything.
