### ISSUE TITLE
When I just opened ATOM, there were several error reports

### ISSUE THREAD

**Issue by BreederBai** [atom/atom#15538]
When I just opened ATOM, the following happens,
![image](https://user-images.githubusercontent.com/27894314/30021417-e54a9c60-9199-11e7-95c7-a11d22e80e98.png)

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
