### ISSUE TITLE
Can't install on windows 10 32bit

### ISSUE THREAD

**Issue by pingping-n** [atom/atom#15532]
this log

[SquirrelSetup.zip](https://github.com/atom/atom/files/1272536/SquirrelSetup.zip)

**Comment by jirawat001** [comment]
https://github.com/atom/atom/issues/5889

**Comment by rsese** [comment]
Thanks for reaching out!

Even though some information may not apply, we require the template to be filled out as much as possible on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
