### ISSUE TITLE
how to config when I open a reopen project in the current window as a different tab?

### ISSUE THREAD

**Issue by huberyh** [atom/atom#15542]
I mean click 'File' -> 'reopen projects' -> [my project],
expected : [my project] be opened in current window as a different tab
actual: [my project] be opened in a new window.

I don't know why it doesn't work since this morning after I update my ATOM packages.
Is there anything I need to set?

BTW, my editor version is 1.19.5.

Thanks.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

The reopen projects menu in Atom does not provide this functionality. Since you mention that you updated packages it may be that one of your packages provided this and then you need to open this issue on their repository. There is an open issue for adding this functionality to Atom /cc: https://github.com/atom/atom/issues/13277. You may want to subscribe there for updates.

The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

---

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by huberyh** [comment]
OH~
but I think it's a ATOM bug, it doesn't mater with packages.
