### ISSUE TITLE
Atom fails to load package preferences in settings-tab

### ISSUE THREAD

**Issue by warcreap** [atom/atom#15558]
Hello,

I am working on a package for my company.

Currently I am having trouble with the config of my package.
Config in my main module looks as follows:
```coffeescript
Main =
  config:
    FirstSetting:
      title: 'Some First Setting'
      description: 'This is the first setting to make'
      type: 'integer'
      default: 1
    SecondSetting:
      title: 'Some second setting'
      description: 'This definitly has to be done second'
      type: 'integer'
      default: 2

  subscriptions: null
  
  activate: (state) -> ...

# ...
# ...

module.exports = Main
```
My problem is, that atom does not load the packages config into the settings view.
Navigating to `Settings/Packages/my-package` results in an errormessage being displayed, telling me, that it `Failed to load my-package - try again later.`.
On the other hand the package works. Config settings are being loaded correctly (in code) and methods are also called and executed properly.

This is no general bug for my atom-installation. It only occures on custom packages. I also want to point out, that this probably has nothing to do with package-activation, because I already removed the `activationCommands` from `package.json` so that the package is activated immediately.
Anyone got an idea?

**Comment by rsese** [comment]
Thanks for reaching out!    Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we'll go ahead and close this since [it doesn't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), but the best places to get help with package development issues are the official message board and the Atom Slack:

* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

There's usually a helpful community member or maintainer willing to lend a hand in one of those channels.
