### ISSUE TITLE
Takes a lot of time to open

### ISSUE THREAD

**Issue by anirudhdggl** [atom/atom#15555]
I am currently having windows 10 and have installed atom for the same. While other text editors like sublime and adobe brackets open instantly, atom on other hand, takes forever to open. After clicking open on atom, I can open the browser, go to the desired website, take out and read the challenge that I have to code for and even then wait for it to open.
I am in love with its functionality, but the only thing that bothers me about atom is that it takes too much of time just to open.
Kindly fix it.

**Comment by ericluuci** [comment]
Try running atom using (--safe, atom --clear-window-state) or uninstall any packages you have and then try again with/without the packages.
Try starting Atom with "Run as Administrator."
If that fails, try uninstalling it completely and then reinstalling it.

**Comment by rsese** [comment]
Thanks for reaching out!  

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
