### ISSUE TITLE
Non-standard scrolling rate in 1.19.6

### ISSUE THREAD

**Issue by billyjanitsch** [atom/atom#15567]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since upgrading from to 1.19.6 on macOS, I've noticed that the scrolling "rate" has slowed down considerably. By "rate", I mean the y-position delta per scroll event. It's hard to measure precisely, but if I compare 1.19.6 to the previous version, or any other native scrolling application (e.g. a browser), the same finger movement on my trackpad results in about 1/3 the movement. Scrolling *isn't* lagging or stuttering; it's just not shifting the viewport by the standard amount (i.e. it takes much longer to scroll through a large text file).

### Steps to Reproduce

1. open a new editor
2. fill it with dummy text
3. scroll around using the trackpad
4. compare to scrolling around in a browser or previous Atom version

**Expected behavior:** the scrolling rate should be standard across all viewports

**Actual behavior:** the scrolling rate is much lower in 1.19.6

**Reproduces how often:** 100%

### Versions

atom 1.19.6
apm 1.18.4
macOS 10.12.6

### Additional Information

I'm using a high-DPI retina display; I don't have a standard display to test on so I'm not sure if this is related to the issue.

**Comment by billyjanitsch** [comment]
A better repro: the tree view (and the settings pane, and basically anything that isn't an editor) retains the correct scrolling behavior in 1.19.6, so you can flip between scrolling in an editor and scrolling the tree view to experience the difference between the two.

**Comment by rsese** [comment]
Thanks for the report - was the fix for https://github.com/atom/atom/issues/15467 mainly about when you scroll so slowly that Atom didn't scroll at all @as-cii?   I feel like I also remember you referencing https://github.com/atom/atom/pull/15310 when we were talking about scrolling issues.  

I do see the difference scrolling in the tree view vs. the editor in terms of speed and how much you scroll in 1.19.6 (though 1.19.5 doesn't seem that much different to me).  If I change `Settings > Editor > Scroll Sensitivity` to 80, the scrolling in the tree view and editor feel a lot closer.

**Comment by as-cii** [comment]
Yeah, as suggested by @rsese, I'd recommend increasing the scroll sensitivity parameter, but I'm open to consider changing the default to `80` if it feels more natural.

**Comment by rsese** [comment]
Thanks @as-cii :bow: Maybe we can leave this issue open for a bit to collect reports from other people so we can consider adjusting the default.

**Comment by onbjerg** [comment]
Thanks! I thought it was just me being tired. 😅 

I think it would at least make sense to "sync up" the scrolling sensitivity in the different panes. For example, the file tree does not honor the scroll sensitivity setting.

**Comment by Ben3eeE** [comment]
@nathansobo This is the report I was telling you about regarding increasing the default scroll sensitivity.

**Comment by eyelash** [comment]
I can reproduce this issue on Linux as well.

**Comment by j127** [comment]
Scrolling is not working correctly on Ubuntu 16.04. It's slowed down compared to other applications (throwing off muscle memory), and jerky when scrolling rapidly with the touchpad. The jerky scrolling also happens with the Slack desktop app, so it might be a problem in Electron.

**Comment by nathansobo** [comment]
@Ben3eeE Do you have any interesting in experimenting with adjusting the sensitivity on Linux?

**Comment by Ben3eeE** [comment]
@nathansobo Yeah I can experiment some. I don't have a touchpad though unless I can manage to get my old laptop up and running and start Atom on it 😅 But I can check out how it works with a mouse.

**Comment by nathansobo** [comment]
If someone could indicate what they think would be an ideal scroll sensitivity on Linux, I could make the default platform-specific.

**Comment by j127** [comment]
Ideally the scroll behavior should be exactly the same as all the other applications on the system, without any special effects added. It's too hard on muscle memory if every application (or website) has its own scroll behavior.

**Comment by Ben3eeE** [comment]
Maybe one problem is that we don't respect the OS settings for the scrolling sensitivity? /cc: https://github.com/atom/atom/issues/11976

On Windows 7 using a mouse this can be set in number of lines that should be scrolled per notch of the scroll wheel.

* Setting it to 20 scrolls 18 lines for me. So the OS scrolling sensitivity does affect how much Atom is scrolling but it's not the correct amount of lines
* Setting it to `One screen at a time` makes Atom scroll a couple of pixels in TextEditors but a lot in other places like the `settings-view`

I wonder if touchpads have similar settings for scrolling sensitivity :thought_balloon:

**Comment by j127** [comment]
> Maybe one problem is that we don't respect the OS settings for the scrolling sensitivity?

That looks like the problem. [Scroll](https://envato.com/blog/scroll-hijacking/) [hijacking](http://trentwalton.com/2013/10/23/scroll-hijacking/) is really inefficient and frustrating for users. A certain distance moved with the touchpad or mouse, should scroll the UI by exactly the same amount in every application and web page on the system. Let each user configure it at the system level. Changing scroll settings is like having the mouse move different distances depending on which window it's hovering over at the moment.

**Comment by Ben3eeE** [comment]
I tested this on Ubuntu 16.04 using a mouse and Atom is scrolling about 1/4 of the distance that gedit does on a single notch of the wheel.

I had to increase the scroll sensitivity setting in Atom to around `160-170` from the default of `40` to get the same distance covered.

I couldn't find any setting to change the scroll sensitivity in the OS. There probably is some way to change it but it's not part of the mouse preferences that I found.

**Comment by nathansobo** [comment]
I wonder if we'll ever be able to deliver a native feeling experience on Linux by interpreting mouse wheel events. It seems like those events are unreliable. @Ben3eeE maybe tweaking our default sensitivity multiplier on Linux could help, but I wonder whether it will create problems for other users with different hardware and configurations.

**Comment by eyelash** [comment]
> A certain distance moved with the touchpad or mouse should scroll the UI by exactly the same amount in every application and web page on the system.

Please note that the native scrolling on Linux (at least for GTK+ applications) is not just a fixed amount but [depends on the size of the view that is scrolling](https://github.com/GNOME/gtk/blob/gtk-3-22/gtk/gtkscrolledwindow.c#L1278-L1306).

**Comment by Ben3eeE** [comment]
> Setting it to One screen at a time makes Atom scroll a couple of pixels in TextEditors but a lot in other places like the settings-view

This changes the events [`deltaMode`](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaMode) to `DOM_DELTA_PAGE` and now the delta is one per notch of the wheel. So we are scrolling one pixel at a time per notch of the wheel.

---

Also found this: https://pavelfatin.com/scrolling-with-pleasure/

**Comment by Ben3eeE** [comment]
> @Ben3eeE maybe tweaking our default sensitivity multiplier on Linux could help, but I wonder whether it will create problems for other users with different hardware and configurations.

@nathansobo I don't think tweaking the default sensitivity or the multiplier would be a good solution and chances are we will get issues where the scrolling is now too fast.

---

I tested other editors using a mouse wheel on Windows 7:

* ST3 honors the scroll settings when changed in Windows
* vscode completely ignores the scroll settings when changed in Windows
* Atom changes the amount scrolled with the scroll settings in Windows but not correctly

**Comment by j127** [comment]
> ST3 honors the scroll settings when changed in Windows

Sublime Text does it correctly on Linux (Ubuntu 16.04) and Windows (8).

Here's [another example](https://github.com/inuyaksa/jquery.nicescroll) of scroll-jacking. Scroll behavior should not be overridden to make it more fancy according to the designers' tastes. Each user has their own muscle memory for operating their computer.

I haven't built anything with Electron so am not sure how scrolling works there, but a similar problem exists in the Slack app too.

**Comment by nathansobo** [comment]
@j127 We're not really overriding scroll behavior as a matter of taste. Because we only render the visible lines, we need to respond synchronously when the scroll position changes in order to redraw content. The browser's scroll events are asynchronous for performance reasons, but if the user scrolls to an area we haven't drawn yet and we don't get a `scroll` event until the next frame, the content flickers. Implementing our own scrolling to avoid flickering is actually a huge source of complexity that I'd love to do away with, but we've never found a way.

We do need to find a solution and it's unclear whether mousewheel events on Linux are a reliable source of scroll information. On macOS they work quite well. We're rendering a *lot* of markup when scrolling, and the overhead of style recalc and layout can sometimes cause long frames on lower end hardware, which is a separate but related issue that's improved with this year's rendering rewrite. This mousewheel issue seems different though. We're just not getting accurate information from the browser.

One thing I've wondered about. We currently render dummy divs to get native scrollbars at the bottom and right of the editor. Could we instead just render a transparent absolutely positioned div over the entire editor and disable click events? When the user scrolled that div, we could respond to its scroll events and then perform synthetic scrolling on the content underneath without the risk of flickering. Another approach might be to render all the text with canvas so we maybe wouldn't need to do partial content rendering, but that's a huge change.

It's a complex issue. I could honestly use help navigating this. If someone can experiment with `TextEditorComponent` and find an approach that gives them better scrolling that could be a good data point, even if it causes problems elsewhere.

**Comment by Ben3eeE** [comment]
If I understand everything correctly. We changed the scroll handler to use `deltaX/Y` instead of `wheelDeltaX/Y` and it's not the same value. wheelDelta is always +/-120 on Linux and delta is +/-53 for me right now. This change would explain why we are seeing a difference on all platforms in 1.19.

https://github.com/atom/atom/blob/05fc82cb8653d0fbc1463acd3a50e340f074ce3a/src/text-editor-component.js#L1513

https://github.com/atom/atom/blob/1f068bde629b8748c7e409e53d56dfadea22108d/src/text-editor-component.coffee#L419

While not the preferred solution of completely honouring the settings in the OS for the best native experience it seems like we can go back to the previous behaviour that was a better default?

**Comment by nathansobo** [comment]
@Ben3eeE Wow good catch. You want to open up a PR that changes this back? We should probably cherry-pick it to 1.21-releases and 1.23-releases since they're going out tomorrow.

**Comment by Ben3eeE** [comment]
@nathansobo I'm in a meeting with Robert for a while right now if you want to hurry and make the change. But I can do it after if we can wait an hour or two.
