### ISSUE TITLE
macOS version on MacOS 10.12.6 is non-functional

### ISSUE THREAD

**Issue by deepgray** [atom/atom#15569]
downloaded the most recent app for macOS.
dropped it in the Applications directory.
double clicked on the app.
App opens to a empty box with no tabs or distinguishable items.
File -> Open selects a file but nothing appears.
File -> open project folder shows the path in the top of the window above the menubar, but does not display anything (like the navigation tree normally on the left).

version 1.2.4 was operational.

update...after several attempts, the app does open and i can add the project folder tree.
that said, i cannot open a text file.

only after exiting and opennig the app a couple of times will it allow me to view text files.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently - at the moment we don't have enough information to further triage this issue.

Thanks for understanding and meeting us half way :grinning:
