### ISSUE TITLE
Scope descriptors and ranges at cursor point

### ISSUE THREAD

**Issue by twifty** [atom/atom#15589]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm not sure if this is a bug or intended behaviour. Would somebody with more knowledge please explain.

Given the string `$foo = "foobar";`, using the PHP grammar, and placing the cursor directly before the first opening quote character.

If I call `editor.scopeDescriptorForBufferPosition(point)`, the scopes returned will include `string.quoted.double.php`. Yet, If I call `editor.bufferRangeForScopeAtPosition('string.quoted.double.php', point)`, it will return `undefined`. There appears to be a disparity between the two calls.

If this is intended behaviour, I can code around it. I'm just worried this is something that will change, breaking my code.

### Versions

1.19.5

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions or [don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

In particular for API questions, Discuss and the Atom Slack are probably the best places to get help.
