### ISSUE TITLE
"Find in file" not always linear results with "find next"

### ISSUE THREAD

**Issue by Daijobou** [atom/atom#15604]
Windows 10: This issue is not only in atom. I have see this in pspad too. (editor I use before atom) So maybe this is a bug in windows? This not happen every time, its a little random. I press STRG+F to search a string and replace this with a other text from clipboard. Now I press F3 to find next result and replace with clipboard (SHIFT+INSERT) again and from time to time its jump to a later result. Simple example: find results in line 3, 5, 7, 21, 9, 11. You see line 21 between line 7 and 9? That should not happen with press F3. But again, I see this issue in "pspad" too with windows 8.1 and windows 10.

**Comment by rsese** [comment]
Thanks for reaching out!  In addition to filling out the template as mentioned below, this issue should be opened in https://github.com/atom/find-and-replace.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
