### ISSUE TITLE
Issue with atom from command line in Windows 10

### ISSUE THREAD

**Issue by Alpha-UMi** [atom/atom#15609]
Hi!

Basically, I've found an issue with Atom.cmd and PowerShell v5 (included in Windows 10). Problem is that PowerShell always complain about a pid not expected when executing an atom command from command line. apm is fine instead. A good guy at the atom.discuss forum tried to help me in resolving this issue, but the only workaround he found is to completely remove and offending line that invokes PowerShell by commenting the line out. Instead of repeating everything, I prefer to point out to the discussion, where the issue is explained in detail:
[https://discuss.atom.io/t/windows-10-help-manually-setting-command-line-variables/47308](url)

**Comment by rsese** [comment]
Thanks for reaching out and for referencing the existing Discuss thread!

No need to repeat everything in the thread but if you can fill out the issue template, that will be super helpful for us.  Feel free to edit the issue body or create a new issue and we can go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
