### ISSUE TITLE
[Eslint] What happened to the error and warning hints?

### ISSUE THREAD

**Issue by Calvin92** [atom/atom#15608]
I don't know what the matter is this, before today, when an error or warning appears, there is a line under the error or warning words, not a messy and nauseating color lump -- it is not readable!

How can I fix it ?

![image](https://user-images.githubusercontent.com/12781397/30267748-20c87dd0-9716-11e7-9155-0079fd53ef97.png)

**Comment by Ben3eeE** [comment]
Thanks for contributing!

It appears that this is being caused by the various linter packages you are using, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
