### ISSUE TITLE
I want to feel of Visual Studio Code

### ISSUE THREAD

**Issue by Extarys** [atom/atom#15607]
This is not an issue but still.

I don't want you guys to feel like I'm bashing Atom - I **LOVE** Atom. It's open source and from a very good company too! (Reputable I mean)

I really don't want to go on the dark side and use Microstuff. So I hope someone will be able to help me.

I started coding in Angular 4 yesterday and I always have 20-30 tabs, it's a pain to search for which one I want.

- Is it possible to have the opened document above the Project Tree Like VSC?

I also love the color palette but seems like the VSC color palette I find doesn't color sass file or js files or typescript.

When there is a lint error, hovering the red shows 2 bubbles.

The code suggestion seems far better in VSC too! Is there a plugin or is it planned to work on that?

I love Atom, I just feel like all the features are addons and it's hard to find the right one, or just one that fit the need and that is actually working properly (I tried 4 terminal addons, 1 is working and it's ugly)

Thanks for any addons/themes suggestions.

**Comment by 50Wliu** [comment]
> Is it possible to have the opened document above the Project Tree Like VSC?

Check out https://atom.io/packages/opened-files or https://atom.io/packages/tree-view-open-files-updated.  Also remember that the Fuzzy Finder is available via `cmd-b`/`ctrl-b`.

> I also love the color palette but seems like the VSC color palette I find doesn't color sass file or js files or typescript.

You can always experiment with styling things yourself via your `~/.atom/styles.less` file, or you could ask the syntax theme author to add support for those files.

> The code suggestion seems far better in VSC too! Is there a plugin or is it planned to work on that?

Without a concrete description of how VSC's code suggestions are "far better", we won't be able to help you.

> I love Atom, I just feel like all the features are addons

Yes, that's one of the fundamental tenets of Atom.  Sorry to hear that you're having trouble finding packages that suit your needs though.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

I highly encourage you to post a topic on [Discuss, the official Atom and Electron message board](https://discuss.atom.io), where there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by Extarys** [comment]
Thanks for the reply and the help!

> Check out https://atom.io/packages/opened-files or https://atom.io/packages/tree-view-open-files-updated. Also remember that the Fuzzy Finder is available via cmd-b/ctrl-b.

Thanks I always forget that one GRR

> Without a concrete description of how VSC's code suggestions are "far better", we won't be able to help you.

Great idea :) Didn't think of that one, I'll send a message.

> Because we treat our issues list as the Atom team's backlog, we close issues that are questions since they don't represent a task needing to be completed.

Normal no worries.

Thank you again you've been helpful!
