### ISSUE TITLE
Text is pulsating at regular intervals in v1.21.0-beta0

### ISSUE THREAD

**Issue by burodepeper** [atom/atom#15626]
### Updated Repro Steps from @ungb (consolidating info from this issue):
1. `apm install minimal-syntax-dark`
1. Open atom and set the following for your theme:
UI Theme: One Dark
Syntax Theme: Minimal Dark
1. Open `styles.less` and add the following and save:
```less
atom-text-editor .cursor {
  transition: opacity 0.333s;
}
```

1. Look at the less file where the number `0.333s` is:
![pulsing](https://user-images.githubusercontent.com/5624870/31413621-06f7a686-adcf-11e7-88b8-0e2c32927b61.gif)

### Description

![atom-pulsating-text](https://user-images.githubusercontent.com/3703530/30348478-c6336416-980f-11e7-823a-900f7f5d4b12.gif)

I have a `transition: opacity 0.333s` on my cursor element, which causes this annoying pulsating effect. I assume that the transition causes Chromium to switch to a different way of rendering the texts, and voila. This was not an issue in either v1.19(.7?, latest stable version) or v1.20 (beta7 I think?), both used today.

### Steps to Reproduce

1. Install `minimal-syntax-dark` (or add the transition on the cursor manually)
2. Create an empty JavaScript file
3. Enter some basic code, like `const test = "test"`

**Expected behavior:**

No pulsating text.

**Actual behavior:**

See .gif in description.

**Reproduces how often:**

Consistently.

### Versions

Atom v1.21.0-beta0 on macOS SIerra 10.12.6

**Comment by rsese** [comment]
Thanks for the report!  I installed `minimal-syntax-dark` but I'm unable to repro with your steps on Atom 1.21.0-beta0 with macOS 10.12.6.

If you can share your cursor styles, I can try that too.

**Comment by burodepeper** [comment]
```less
// styles.less (nothing else is in there)
atom-text-editor .cursor {
  transition: opacity 0.333s;
}
```

```js
// some code for testing
const images = document.querySelectorAll('.images')
images.forEach(image => {
  image.addEventListener('load', event => {
    event.target.classList.remove('loading')
  })
})
```

Syntax theme: One Dark
UI theme: One Light
No custom packages enabled

![atom-bug](https://user-images.githubusercontent.com/3703530/30368774-8e843da2-9872-11e7-80a6-0445cd97537e.gif)

In case this could be hardware related: I'm using a 27'' Imac (late 2013) with a NVIDIA GeForce GTX 780M 4096MB.

I have also replicated the issue on my Macbook Air, and tested in four different typefaces: Courier, Monaco, Menlo and Hack (my default).

**Comment by iolsen** [comment]
@Ben3eeE were you able to reproduce this?

**Comment by Ben3eeE** [comment]
@iolsen Yes I was able to reproduce it on beta.

I had this in my stylesheet on stable and it worked fine. Then I updated to beta and saw this issue. Removing the styles in https://github.com/atom/atom/issues/15626#issuecomment-329106957 resolved the issue.

I was on Windows 7 x64 and did not try without community packages.

**Comment by danqing** [comment]
Sounds like a font antialiasing issue (subpixel).

**Comment by burodepeper** [comment]
Yes, I believe it switches between grayscale and subpixel antialiasing whenever the transition is invoked/playing.

**Comment by ddgromit** [comment]
The blinking cursor also causes atom to run at 20-40% CPU when an editor pane is focused.

With the transition removed, CPU drops back down to single digits:
```
atom-text-editor.is-focused .cursor {
  transition: none;
}
```

**Comment by nathansobo** [comment]
@ungb It's possibly related. We need to figure out why we're bailing out of subpixel anti-aliasing when the cursor opacity is transitioning. At one point in time we rendered cursors on their own GPU layers, and I wonder if that might help in this case so the text is undisturbed. As for the cost of the transition, it's easy to see why CPU utilization might be high if we are re-painting everything.

**Comment by Ben3eeE** [comment]
@nathansobo @ungb #15372 was hotfixed to 1.19 and 1.20. This started in 1.21 beta. The only change I know that was never hotfixed to 1.20 is https://github.com/atom/atom/pull/15486

**Comment by nathansobo** [comment]
I think we're running up against a fundamental limitation of Chrome involving the interaction of subpixel antialiasing with the GPU-composited layers that Chrome automatically creates as part of the CSS transition. Anyone can keep their pulsing cursor at the expense of subpixel antialiasing (which should be no big deal on higher resolution displays) with the following tweak to their style sheet:

```css
atom-text-editor .cursors {
  will-change: transform
}
```

This will disable subpixel anti-aliasing **always** rather than only between blinks, leading to less crisp text on lower resolution displays in exchange for a fancy fading cursor. This isn't a fix we can apply across the board because subpixel antialiasing is an important feature for many users.

For background on this issue, continue reading:

Subpixel antialiasing relies on the fact that each pixel of the display is actually made up of separate red, blue, and green LEDs that are laid out horizontally. By shifting the color of the pixels at the edge of letters, the text rasterizer creates the illusion of a partial pixel being illuminated which makes text look smoother.

![image](https://user-images.githubusercontent.com/1789/31912867-8f34d040-b802-11e7-98db-fb0d6de7dd8d.png)

To apply this technique, the rasterizer needs to know with 100% confidence that it has final say over the color of the pixels it is rasterizing. If the rasterized text is shipped off to the GPU as a bitmap and composited with some other translucent graphics (like a fading cursor for example), then whatever colors were selected to achieve the subpixel rendering effect are now mixed with the colors of the translucent element. Now, instead of subpixel antialiased text you just have weird rainbow colors at the fringes of letters that is serving no purpose.

For this reason, Chrome seems to disable subpixel antialiasing on any layer that needs to be composited with another layer. Such a compositing layer is created automatically during the CSS transition, which causes subpixel antialiasing to be disabled during the transition and reenabled between blinks, leading to this "pulsating" look.

Until the blessed day when operating systems start rendering all their text on the GPU or applications find a way to do that without producing text that feels out of place on its home operating system, we're in a tough position with this approach.

The only solution I can think of right now to get this fading cursor effect while retaining anti-aliasing would probably be to implement the animation manually in JS, which isn't something that's important enough to take on right now.

If anyone has spotted something I am missing here, please let me know.
