### ISSUE TITLE
No Numpad support in kaymap.cson?!?

### ISSUE THREAD

**Issue by q3fuba** [atom/atom#15625]
Why there is no Numpad support for keybinding? Oo

Almost every dirty editor can bind any key to a hotkey and some of them also can globally bind keys...

Tested:
```
'.platform-win32 .image-view':
  'ctrl-num-0': 'image-view:reset-zoom'
  'ctrl-num-insert': 'image-view:reset-zoom'

'.platform-win32 .markdown-preview, .platform-linux .markdown-preview':
  'ctrl-num-0': 'markdown-preview:reset-zoom'
  'ctrl-num-insert': 'markdown-preview:reset-zoom'
```
Does not wok at all!

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

@Ben3eeE I remember this PR of yours /cc https://github.com/atom/atom-keymap/pull/198 but don't have a keyboard with a number pad to test - would it just be `ctrl-numpad0` instead of `ctrl-num-0`?  Not sure about `ctrl-num-insert` though....

**Comment by q3fuba** [comment]
Ofc. i searched the whole Web before i posted here....  
There is nothing about any NumPad, KeyPad or similar in the [Keymaps In-Depth](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/)... -> In-Depth? ^^

Also **numpad0** and **Numpad0** is not working.  
But should working if we take a look in [keymap-manager-spec.coffee](https://github.com/atom/atom-keymap/blob/master/spec/keymap-manager-spec.coffee)

Tested with:
```
'.platform-win32 .markdown-preview, .platform-linux .markdown-preview':
  'ctrl-numpad0': 'markdown-preview:reset-zoom'
```
Also there is nothing usefull about it in any Discuss forums!

Btw.  
I'm using Windows 10 OS but this should not make a difference.

**Comment by Ben3eeE** [comment]
> @Ben3eeE I remember this PR of yours /cc atom/atom-keymap#198 but don't have a keyboard with a number pad to test - would it just be ctrl-numpad0 instead of ctrl-num-0? Not sure about ctrl-num-insert though....

On Windows, pressing `ctrl` and the `0` key on the numpad resolves to:
* `ctrl-numpad0` if `Num Lock` is on
* `ctrl-insert` if `Num Lock` is off

On other platforms it will resolve to `ctrl-numpad0` if `Num Lock` is on. I don't know if those platforms also have `Insert` there when `Num Lock` is off. In the case when it is off it resolves using `KeyboardEvent.key` like almost all other keys in Atom. `KeyboardEvent.key` is the key pressed including software remapping.

We used to resolve it to `ctrl-num-insert` a long time ago but that support was removed /cc: https://github.com/atom/atom/pull/3240
