### ISSUE TITLE
[Enhancement] Toggle pane group shortcuts

### ISSUE THREAD

**Issue by wyqydsyq** [atom/atom#15631]
Recently Atom introduced the ability to toggle "groups" of panes with the popover icons: 
![image](https://user-images.githubusercontent.com/621277/30359934-8dd6c716-9891-11e7-96f5-463312f8e119.png)

It would be ideal to be able to assign a keyboard shortcut to do this.

For example in my current setup, on the left pane group I have the `Project`, `Git` and `Outline View` panes. To show/hide this group of panes, I need to either click the button or use the toggle hotkey for one of the panes inside it (which also activates that pane inside the group). It would be better if I could define a single keyboard shortcut to toggle the group, regardless of what panes are inside it.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

There are commands for this `window:toggle-[direction]-dock`. You can bind them in your keymap file.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
