### ISSUE TITLE
Git indents after Sublime Text 3

### ISSUE THREAD

**Issue by wayheming** [atom/atom#15657]
Hello, I have a problem. I decided to go to Atom's code editor. I used to use Sublime Text 3. My problem is that after saving the file in the atom in the git changes, I get indentions although I just saved the file. And since my colleagues still use Sublime Text 3, we get such a problem. How can I fix this?

Sorry for bad English

[Screenshot](http://prntscr.com/gldmuw)

**Comment by 36864** [comment]
Check your indentation settings in atom. Specifically, soft tabs and tab length.

**Comment by wayheming** [comment]
I tried but did not help

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
