### ISSUE TITLE
The project manager overwrites the files with old data

### ISSUE THREAD

**Issue by callisto2410** [atom/atom#15665]
The project manager overwrites the files with old data, and kills my work.
What am I doing wrong?

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
