### ISSUE TITLE
Atom won't open in normal mode

### ISSUE THREAD

**Issue by codesign5** [atom/atom#15666]
Everything went perfectly last night but when I am today, the atom doesn't show anything only the black screen appears without any file has opened. When I run in safe mode like atom --safe, it works fine but I don't want to do anything in safe mode. Reinstall doesn't seem to be work here

I am using a Mac Yosemite 10.10.1 version

Kindly help

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by codesign5** [comment]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    X Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    X Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    X Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    X Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    X Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Everything went perfectly last night but when I am today, the atom doesn't show anything only the black screen appears without any file has opened. When I run in safe mode like atom --safe, it works fine but I don't want to do anything in safe mode. Reinstall doesn't seem to be work here

I am using a Mac Yosemite 10.10.1 version

**Expected behavior:** It should shows a file or folder like in normal behaviour.

**Actual behavior:** Not showing anything in Atom

**Reproduces how often:** 

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.6
git 2.5.4

### Additional Information

Nope.

**Comment by 50Wliu** [comment]
> When I run in safe mode like atom --safe, it works fine but I don't want to do anything in safe mode.

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, the [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
