### ISSUE TITLE
cmd-g as goto line

### ISSUE THREAD

**Issue by sircola** [atom/atom#15670]
I'm on mac. I would like to set cmd-g as goto line.
I've put this in keymap.cson

'.platform-darwin, .platform-win32, .platform-linux':
  'cmd-g': 'go-to-line:toggle'
'.platform-darwin atom-text-editor':
  'f3': 'find-and-replace:find-next'

F3 works as find, cmd-g is still set to try to find strings. ctrl-g is goto line as default. I really would like cmd-g work as ctrl-g.
This is on mac with atom 1.20.
Also I really love this editor, thanks for making it!

**Comment by Ben3eeE** [comment]
Try this:

```
'.platform-darwin, .platform-win32, .platform-linux atom-text-editor':
  'cmd-g': 'go-to-line:toggle'
'.platform-darwin atom-text-editor':
  'f3': 'find-and-replace:find-next'
```

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
