### ISSUE TITLE
Computer become unresponsive and need to e restart a minute after Atom start

### ISSUE THREAD

**Issue by ChrisCinelli** [atom/atom#15684]
### Description

Currently starting Atom makes my computer become completely unresponsive. The spinning wheel of death appears and it stops spinning in less than 1 minute. I cannot even move the mouse. 
I see that memory usage on the machine quickly climb.  I do not even have time to check in the activity monitor what is the memory consumption for Atom is. The graph does not have time to update but the text value show that all the memory is used. Kernel memory gets to 9GB (I have 16G on my MacBook). I need to restart holding the power button down. Since MacOS restarts the programs that were opened before shut down, I got stuck. I was able to overcome the problem by quickly shut down Atom after login. 

I wonder why the OS does not detect the problem and does something about it.

If I run Atom with `atom --safe` I do not have problems.
I am going to selectively disable plugins to find where the problem is.

But, whatever the problem is I think Atom should not become a problem for the whole system. 

### Versions

```
$ atom --version
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0
```

### Additional Information

This is the list of my packages:

```
Community Packages (31) 
├── atom-format-lua@0.1.5
├── atom-jade@0.3.0
├── autocomplete-js-import@1.4.0
├── autocomplete-modules@1.7.0
├── busy-signal@1.4.3
├── file-icons@2.1.11
├── git-blame@1.2.2
├── hyperclick@0.1.5
├── incremental-search@5.2.2
├── intentions@1.1.5
├── language-babel@2.74.2
├── language-gherkin@1.0.4
├── language-marko@2.9.4
├── linter
├── linter-eslint@8.2.1
├── linter-htmlhint@1.3.3
├── linter-js-yaml@1.2.7
├── linter-jshint@3.1.5
├── linter-luacheck@2.0.1
├── linter-ui-default
├── markdown-writer@2.7.2
├── mocha-test-runner@1.0.0
├── mocha-ui@0.1.8
├── multi-cursor@2.1.5
├── nuclide-test-runner-jest@0.3.0
├── pigments@0.40.2
├── prettier-atom@0.39.0
├── react@0.16.2 (disabled)
├── tab-switcher@1.5.6 (disabled)
├── tabs-to-spaces@1.0.3
└── tree-view-copy-relative-path@1.2.0
```

**Comment by 50Wliu** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, the [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
***
I believe some people have had issues with pigments chewing up memory, you might want to try disabling that package first and seeing if that helps.

**Comment by ChrisCinelli** [comment]
The problem is the pigments the https://github.com/abe33/atom-pigments/issues/340
However this plug end up creating almost hundreds of Atom Helper processes in few seconds.
IMHO, Atom should have a way to monitor this kind of behavior and prevent it to happen.

**Comment by ChrisCinelli** [comment]
Related somehow with https://github.com/atom/atom/issues/12466

**Comment by batmanbury** [comment]
Is this still an active issue? I'm not using the pigments plugin and also have several (at least 3 helpers) immediately spawn when I open Atom. Sounds like it's at least narrowed down to plugins though?

**Comment by rsese** [comment]
This particular issue is closed since the specific problem described was tracked down to pigments - there's a more general issue referenced above that's open however https://github.com/atom/atom/issues/12466.  As mentioned there, multiple helpers isn't unexpected /cc https://github.com/atom/atom/issues/12466#issuecomment-309190890.  I also just started Atom in safe mode on macOS and I also see 3 helpers in activity monitor.
