### ISSUE TITLE
restore unsaved documents on a restart

### ISSUE THREAD

**Issue by mrjayviper** [atom/atom#15686]
I'm currently using TextWrangler (OSX only I think) and 1 neat feature I frequently used used an unsaved documents as my scratchpad. I just dump things there and when I restart my machine and open it up again, the stuff are still there.

Is there a way to get similar feature in atom? I've looked at preferences and can't see anything that will work. I did see "Restore previous windows on restart" but it seems to only work for saved documents.

Thanks

**Comment by rsese** [comment]
Thanks for reaching out!    If an unsaved file is part of a project, it gets saved and restored when you re-open that project.  There's an open issue for the case where there's no project however:

https://github.com/atom/atom/issues/13318

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
