### ISSUE TITLE
Disable extension Docblockr failed

### ISSUE THREAD

**Issue by xdc0209** [atom/atom#15699]
When I click the disable button for extension Docblockr，the config.cson is as blow：
    disabledPackages: [
      "script"
      "docblockr"
    ]

When I modify  config.cson  manually as below, the disable button turn to enable button.
    disabledPackages: [
      "script"
      "Docblockr"
    ]

And extension Script have the same problem, I think it's just a case sensitive problem of atom.

**Comment by xdc0209** [comment]
windows 7
Atom 1.20.1 x64

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

I'm not 100% if this would be a bug or an enhancement (or works as expected) but if you can fill out the template, we can go from there.
