### ISSUE TITLE
Won't build for OpenSuse i586

### ISSUE THREAD

**Issue by HeinrichGit** [atom/atom#15708]
Has anyone tried to build for OpenSuse i586 ?

If you ve overcome your frustration and found a way to do it, could you share it with us ?

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by HeinrichGit** [comment]
Hey, nothing personal, but your pasted answer is worthless ..
