### ISSUE TITLE
installation has failed of win7 x64

### ISSUE THREAD

**Issue by Lizhooh** [atom/atom#15716]
My computer installation failed. Clicking on open setup log didn't respond

![20170922134931](https://user-images.githubusercontent.com/19299088/30731080-cd06c7d4-9f9d-11e7-8c18-e10195b29da9.png)

name | version
--- | ---
node | v8.5.0
system | win7 x64 intel core i5
atom | https://atom-installer.github.com/v1.20.1/AtomSetup-x64.exe?s=1505769323&ext=.exe

**Comment by rsese** [comment]
Thanks for the report - for future issues it would be super helpful if you can fill out the issue template since it provides us with a lot of baseline information.  Can you confirm where you downloaded the installer from?

Do you have any anti-virus software running?  If so, can you try temporarily disabling it and try installing again?

**Comment by Lizhooh** [comment]
@rsese 

I downloaded the latest version from the official website (https://atom.io/).
I shut down all antivirus software, and the installation failed as well.
Now, I can only download `atom-x64-windows.zip` to use.
