### ISSUE TITLE
Opening a file with a space in its name or in the path leading up to its name

### ISSUE THREAD

**Issue by gabrielschulhof** [atom/atom#15752]
Running on Linux:

```
$ atom "/path/with a space/to/file.js"
```

fails. It opens three tabs: "/path/with", "a", "space/to/file.js".

**Comment by rsese** [comment]
Thanks for reaching out!  In addition to filling out the template as mentioned below, I was unable to reproduce with Atom 1.20.1 on Ubuntu 16.04.  But if you can give us more details we can take a look.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
