### ISSUE TITLE
win X64 Unable to save v1.21.0

### ISSUE THREAD

**Issue by train147369** [atom/atom#15815]
win X64 Unable to save v1.21.0

**Comment by aakash4525** [comment]
me too

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by aakash4525** [comment]
That was happening probably because of some installed package.
I was not able to save files due to the `file-header` package with error-
`TypeError: Cannot read property 'undoStack' of undefined (file-header.coffee:299)`
After disabling `file-header`, Atom is saving files without any issue.
