### ISSUE TITLE
Unable to install script

### ISSUE THREAD

**Issue by riomario1** [atom/atom#15826]
Hi,

I am unable to install script in Windows 7 computer.

When I run:

    apm install script

Error:

    Request for package information failed: self signed certificate in certificate chain 
    (SELF_SIGNED_CERT_IN_CHAIN)

-------

When I try to install script from Atom, I get below message in Atom editor:

    self signed certificate in certificate chain

Any help?

**Comment by rsese** [comment]
Thanks for reaching out!  We have a FAQ item for issues with self-signed certificates here:

https://discuss.atom.io/t/im-getting-an-error-about-a-self-signed-certificate-what-do-i-do/39040

For future issues, it would be helpful if you can fill out the issue template as much as possible.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
