### ISSUE TITLE
the installation package is too big and open file slow

### ISSUE THREAD

**Issue by lizhuangs** [atom/atom#15839]
is there any play to streamline the installation package.
it's really too big then other editor,like sublime,vs code and so on.

then when open file,it's slow obviously on windows OS.
these two reasons affected many people for choose it.

hope it gets better.
Tks.

**Comment by youngjuning** [comment]
+1

**Comment by mpboom** [comment]
I do agree that it is a big installer but the files need to be downloaded to your computer anyway. If they aren't already included in the installer the installer will download them (that is the case with most of the other text editor installers you talk about).

I installed Atom a few times and openening the installer after it was downloaded took only about 30 seconds for me. I don't see why people would choose another text editor just because they need to wait 30 seconds until an installer visually pops up.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.

**Comment by lizhuangs** [comment]
@mpboom for some reasons many company limit the network'speed slowly.the vs code and sublime is only about 30MB or less,but the atom is about 130M.

people love editor green and small,editor is not IDE.
maybe atom include much more inside packages.
but vs code also based on electron.
it's my idea,I think many people also think so.
Tks.
