### ISSUE TITLE
snap distributed Atom fails to execute clang

### ISSUE THREAD

**Issue by Palatis** [atom/atom#15842]
### Description

snap tries to set various `LD_LIBRARY_PATH` to `/snap/atom/${VERSION}/usr/lib/${PATH}`, this makes executables tries to resolve runtime libraries over there, making some of them unusable.

such that clang requires `libLLVM-4.0.so.1`, but the library distributed with snap is not providing various symbols, results unresolved symbol during start.

I basically tries to run platform.io, which requires Clang for code-completion.

### Steps to Reproduce

1. install atom via snap: `snap install atom --classic`
2. install platformio-ide: `atom.apm install platformio-ide`
3. install clang: `sudo apt install clang` (installs clang-4.0)

**Expected behavior:**

well... expect it to work...

**Actual behavior:**

unresolved symbol when running `clang --version` inside an `platformio-ide-terminal`

**Reproduces how often:**

Always

### Versions

Atom: 1.21.0
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0

apm: 1.18.1
npm:3.10.10
node: 6.9.5 x64
python: 2.7.13
git: 2.11.0

### Additional Information

I tried to "repack" the `atom_42.snap` and remove all  .so files under `${SNAP_ATOM}/usr/lib/` by doing `find ${SNAP_ATOM}/usr/lib  -type f,l -name \*.so\* -exec rm \{\} \;`, and it now works...
maybe just don't pack the shared libraries dependencies, or pack them with another snap package so user can choose whether or not to use them or not?

**Comment by rsese** [comment]
Thanks for reaching out!

As mentioned in various issues (e.g. https://github.com/atom/atom/issues/2956#issuecomment-302149978 and https://github.com/atom/atom/pull/14313#issuecomment-297754223), the snap distribution is unofficial and not provided by the Atom team so we can't provide help for it.

---

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by Palatis** [comment]
errg, sorry, didn't know that atom over snap is an unofficial distribution.

i'll go bother someone elsefor  that matter :-P
