### ISSUE TITLE
Menu aligned right-to-left in Windows with right-to-left layout

### ISSUE THREAD

**Issue by acrolink** [atom/atom#15875]
How to make it left-to-right despite the Windows layout, never seen such a thing in another software.

**Comment by hgdsraj** [comment]
Could you provide a picture of the specific behaviour?

**Comment by acrolink** [comment]
Here is a screenshot:
<a href="https://ibb.co/fAhPWG"><img src="https://thumb.ibb.co/fAhPWG/atom_rtl_issue.png" alt="atom_rtl_issue" border="0"></a>

**Comment by rsese** [comment]
Thanks for reaching out!  Filling out the template is super useful because it gives us a lot of baseline information and gives you space to provide as much information as possible so we can take a look.  Please be as specific as possible with what you're describing and with your screenshots e.g. when you say "How to make it left-to-right", do you mean the order of the "File", "Edit", "View", etc. menu items is reversed from what you expect?  What does another program look like with this layout?

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
