### ISSUE TITLE
snap package can not be started with simple `atom` command

### ISSUE THREAD

**Issue by nextgenthemes** [atom/atom#15884]
Ubuntu 17.04

I can start atom with `/snap/bin/atom` but not with just `atom` on the commandline (zsh). Launching it with the unity launcher is no problem. I expect this to work normally just like it does with the .deb

The Exec line in the .desktop file is this:

`Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/atom_atom.desktop /snap/bin/atom %U`

Just tested another snap package (youtube-dl-snap) and it did not have this problem.

**Comment by rsese** [comment]
Thanks for reaching out!

As mentioned in various issues (e.g. https://github.com/atom/atom/issues/2956#issuecomment-302149978 and https://github.com/atom/atom/pull/14313#issuecomment-297754223), the snap distribution is unofficial and not provided by the Atom team so we can't provide help for it.

---

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by nextgenthemes** [comment]
@rsese how about doing a official distribution then? You build .deb packages but there is no official PPA AFAIK. That makes no sense. I thought at least the snap was official that why I actually switched.

**Comment by ghisvail** [comment]
> I can start atom with /snap/bin/atom but not with just atom on the commandline (zsh)

Works for me on Ubuntu 17.10. I can launch Atom by typing `atom` in a terminal after install of the snap package. It is most likely an issue with snaps than Atom. @rsese is right to mark this issue invalid.
