### ISSUE TITLE
I need help please

### ISSUE THREAD

**Issue by asianegg** [atom/atom#15889]
https://gist.github.com/anonymous/90ef14b32ac913ffdefef8bdde34a2a0

**Comment by rsese** [comment]
Thanks for reaching out!

In addition to filling out the template as much as possible as mentioned below, I looked at your gist but don't see any entries about Atom in your log file.  If you can confirm that you're trying to install Atom in your new issue that would be great.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
