### ISSUE TITLE
Unexpectedly splits panes

### ISSUE THREAD

**Issue by jimmywarting** [atom/atom#15899]
I'm using a [Mac small Wireless keyboard](https://www.staples.se/content/images/product/148493_1_xnl.jpg) and it doesn't have `end` or `home` buttons
instead I use cmd+shift+arrows or just cmd+arrows a lot to navigate around the code. This results in pane splitting sometimes, 

it's hard to reproduce and i'm not sure what i'm doing. Accordingly you should use cmd+k then arrows to split them but i never hit cmd+k. Maybe is that i'm tabbing around a lot between windows...

Anyhow, now i'm looking for a way to completely disable pane splitting, any help on doing that is appreciated

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
