### ISSUE TITLE
Focus on new file/folder/rename

### ISSUE THREAD

**Issue by axe-z** [atom/atom#15893]
For the love of UI, can you guys please make sure that, like every single app created since 1968, FOCUS is on the input field  when we have to add a file, folder, rename . we click add file, the box is there, everything else is disabled but the field, we type, and nothing happens once every 10 tries. WHY ?? we need to click again IN THE SINGLE , only place there is on screen to get focus. After years on Atom I 'm always entering twice de name of every file. 
this happened to me about a 1000 times.  It did right now 
![capture d ecran 2017-10-14 a 18 04 36](https://user-images.githubusercontent.com/27289270/31579724-37e75190-b10a-11e7-8124-ff37da3c937d.png)

I'm speaking for many right now.

**Comment by StefanoCecere** [comment]
uhmm. strange i have the FOCUS correct (on Mac 1.21.1)

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by axe-z** [comment]
this happens even with all package disabled. but closing this is why everyone is heading to vsc.
