### ISSUE TITLE
atom-editor-git on arch requires nodejs boron?

### ISSUE THREAD

**Issue by StripedMonkey** [atom/atom#15891]
I've recently come into an issue with another project and this one in the AUR (kitch and atom) and it revolves around kitch requiring a higher version of node than 6.11. My question is  whether or not this is necessarily anymore. The last time it was updated was over a year ago and I can't seem to find anything regarding it needing to have boron.

If the answer is yes then is there a particular reason why?
If the answer is no then might I request an updated pkgbuild?

**Comment by the-j0k3r** [comment]
Do you think asking the package maintainer in AUR would be better thing here? Likely the packaging scripts need adjusting.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by StripedMonkey** [comment]
@thomasjo That is a terribly off-topic copy-paste answer. A simple answer of "No, there isn't a particular reason and we don't actually maintain the AUR version so don't ask us if we can update it." would have sufficed and been a hair less work.
