### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\atom-terminal-panel\...

### ISSUE THREAD

**Issue by Wormstalker** [atom/atom#15890]
[Enter steps to reproduce:]
Error appeared when uninstalling atom-terminal-panel.

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Win 10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Mir\.atom\packages\atom-terminal-panel\lib\atp-view.coffee'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'C:\Users\Mir\.atom\packages\atom-terminal-panel\lib\atp-view.coffee'
  at Object.fs.openSync (fs.js:558:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
  at Object.fs.readFileSync (fs.js:468:33)
  at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
  at Object.exports._compileFile (<embedded>:217575:26)
  at getSourceMap (<embedded>:217683:28)
  at getSourceMapping (<embedded>:217691:25)

```

### Commands

```
     -7:58.5.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
git-plus 7.10.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-terminal-panel](https://github.com/styczynski/atom-terminal-panel) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
