### ISSUE TITLE
Incorrect labels for commands in a context menu

### ISSUE THREAD

**Issue by PetrKryslUCSD** [atom/atom#15903]
The right-click context menu  has some incorrect information:
![image](https://user-images.githubusercontent.com/9855832/31618703-8c4f4c18-b247-11e7-9aec-42198e234730.png)
a. The key binding for  "toggle documentation" is apparently ctrl-j ctrl-d (not just ctrl-d).
b. "Go to definition" key binding is ctrl-j ctrl-g (not just ctrl-g).
c. The  "Go to definition"  command name is misspelled.

**Comment by 50Wliu** [comment]
Thank you for reaching out!

Because both of those commands do not appear in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Comment by PetrKryslUCSD** [comment]
Thanks!
