### ISSUE TITLE
atom multi line copy/paste

### ISSUE THREAD

**Issue by frontalnh** [atom/atom#15964]
when i select multi line and copy multi-word and paste it
it does not work well

i searched so many time to solve this problem but i couldn't

---reference---
https://discuss.atom.io/t/multi-caret-copy-paste-wrong-behavior/6108

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

Feel free to comment in that post and as Lee mentions there, share exactly what steps you're trying, what's actually happening, and what you expect to happen.  You can ping me there as well if you'd like, my username is the same on the message board.
