### ISSUE TITLE
Close slow tab, not window with slow tab

### ISSUE THREAD

**Issue by benzen** [atom/atom#15980]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is more a request for change than a bug report.
I'd like to close only the slow tab when the ui feeze.
This may involve opening runing multiple tab of the same window in separate thread.
Just like Chrome does.

### Steps to Reproduce

1. When opening a large file and doing crazy search on it, it will be slow.
2. The ui may freeze.
3. When this happend,  a popup will propose to keep waiting or force close atom.

**Expected behavior:** I would like the close button to only close the slow tab.

**Actual behavior:** When clicking close, then whole window close. Since the window setup can be slow to reproduce, that would help.

**Reproduces how often:** All the time, since it's intened behavior atm.

### Versions

1.21.1

### Additional Information

I'm using macos, but i assume all platform behave the same

**Comment by maxbrunsfeld** [comment]
Each Atom *window* is analogous to a single chrome *tab*. We already have the same overall architecture as chrome in that way; that's what allows you kill an unresponsive window while the App remains running.

The 'tabs' that you see in the Atom editor are just HTML elements; they cannot be isolated to run in separate threads (and we wouldn't want to, because we want them to exist in the same JavaScript context). Long-running JavaScript code is not necessarily associated with one particular 'tab'.
