### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 4319, Calling remote method getAutoFoldRang...

### ISSUE THREAD

**Issue by victorsterling1** [atom/atom#15995]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 4319, Calling remote method getAutoFoldRanges..

```
At /opt/facebook/nuclide/0.247.69331646/nuclide/node_modules/rxjs/bundles/Rx.min.js:23

RpcTimeoutError: Timeout after 60000 for id: 4319, Calling remote method getAutoFoldRanges..
    at Call._timeout (/opt/facebook/nuclide/0.260.75053414/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:181:20)
    at Call._timerId.setTimeout (/opt/facebook/nuclide/0.260.75053414/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
```

### Commands

```
     -7:01.1.0 nuclide-file-tree:add-file (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory)
  3x -6:53.2.0 core:backspace (input.hidden-input)
     -6:51.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.57.2 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
nuclide 0.262.76064527 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
vim-mode-plus 0.85.1 
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
