### ISSUE TITLE
Opening A Project/File Won't Work Until You Open New Window

### ISSUE THREAD

**Issue by tusharshivan** [atom/atom#16019]
This issue has been closed now, [https://github.com/atom/atom/issues/3406](url).
When I install and open the Atom, it is like this...
![stuck](https://user-images.githubusercontent.com/12612322/32135172-499620ba-bc18-11e7-8d0c-5833a18639e1.png)

On this window, I can't do anything like create new file, import folder, open settings, and etc.

There is one more behaviour that I want to mention, if I open new window the folder which I want to import can be done by creating new file and saving this file in the folder. After saving the file, the folder shows up on Atom. Like This...
![stuck1](https://user-images.githubusercontent.com/12612322/32135317-7bb5d534-bc1a-11e7-9c8b-3e14e6e998b0.png)

The issue I mentioned above almost matches exactly what I've been trying to fix.
I am using Atom v1.21.1 On Windows 10.

**Comment by danPadric** [comment]
Hello.

Consider having a conversation at [Atom Community Forum](http://discuss.atom.io) about your case. If nothing else they could help to zoom into the problem.

Things I would ask:
* Have you used Atom before? Is it an upgrade or new install?
* Where did you get the installation file from? Did you install the 64-bit version? 
* Did you try to start Atom in safe mode yet?
* Did you install any additional packages yet? Which?

As a self help reference, have a look at..
 http://flight-manual.atom.io/hacking-atom/sections/debugging/

_PS: I like your choice in desktop picture._
Good luck.

**Comment by tusharshivan** [comment]
Thanks for the advice ... 

Yes I've used Atom on versions before v1. I never had this problem. Sometime before I uninstalled it and then reinstalled now and now I'm struggling with this issue.

Yes I've Downloaded the setup from [https://www.atom.io](url) website. And I have downloaded 64 bit version.

I haven't tried  to start Atom in safe mode yet.

And I haven't installed any additional packages after installation.

**Comment by rsese** [comment]
Thanks for reaching out!

I see you've [posted to the message board](https://discuss.atom.io/t/opening-a-project-file-wont-work-until-you-open-new-window/49176), thanks for doing that.  Let's go ahead and continue the conversation there for now and if we find a reproducible problem, we can open an issue here.

As mentioned below, for future issues please fill out the issue template as much as possible, the information is super helpful for us.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
