### ISSUE TITLE
Uncaught Invariant Violation: Minified React error #188; visit http://facebook.github.io/react/do...

### ISSUE THREAD

**Issue by Atul-Nambudiri** [atom/atom#16010]
[Enter steps to reproduce:]

1. Restart Atom when an update comes in
2. See error message

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Invariant Violation: Minified React error #188; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

```
At /opt/facebook/nuclide/0.259.74448868/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:12

Invariant Violation: Minified React error #188; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at w (/opt/facebook/nuclide/0.259.74448868/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:12:224)
    at ab (/opt/facebook/nuclide/0.259.74448868/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:32:61)
    at findCurrentHostFiber (/opt/facebook/nuclide/0.259.74448868/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:33:178)
    at Object.findHostInstance (/opt/facebook/nuclide/0.259.74448868/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:248:367)
    at /opt/facebook/nuclide/0.259.74448868/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:246:90
    at Object.Dh [as findDOMNode] (/opt/facebook/nuclide/0.259.74448868/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:197:182)
    at FileTree._measureHeights (/opt/facebook/nuclide/0.259.74448868/nuclide/pkg/nuclide-file-tree/components/FileTree.js:77:38)
```

### Commands

```
     -2:33.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
file-icons 2.1.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.66.1 
language-graphql 0.9.0 
language-haskell 1.14.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.11 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.10 
nuclide 0.263.77136278 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
