### ISSUE TITLE
Is there any way to automatically move the cursor around the parentheses?

### ISSUE THREAD

**Issue by isoeugenol** [atom/atom#16028]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

If the line is not empty, the cursor moves to the normal position. 
but if i entered to empty line, cursor go to left position.

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/31752719/32180473-6affe844-bdd5-11e7-8335-0ea6342bdc22.png)

1. [First Step]
entered 9:8 -> cusrsor moved 10:5
2. [Second Step]
entered 10:1 -> cursor moved 11:1
3. [and so on...]

**Expected behavior:** [What you expect to happen]
i expect if i entered 10:1 cursor moved 11:5

**Actual behavior:** [What actually happens]
cursor moved 11:1

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
