### ISSUE TITLE
Can't compile a c file.

### ISSUE THREAD

**Issue by VidarHUN** [atom/atom#16020]
Hi! 

I installed the packages and gave the for the compiler in my computer "C:\MinGW\bin". But i can't compile a file becasue a get this error: 

c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find C:\MinGW: Permission denied 
collect2.exe: error: ld returned 1 exit status 

Somebody could help to me?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
