### ISSUE TITLE
Atom crashed when attempting to install update

### ISSUE THREAD

**Issue by thomruns** [atom/atom#16045]
Downloaded newest version of Atom.

Clicked install and restart.

Alert message: "Editor crashed. Please report this incident."

running Mac OS 10.12.6

**Comment by rsese** [comment]
Thanks for the report @thomruns - is Atom now in a state where it crashes every time you try to start?  Can you start in safe mode (`atom --safe`)?

And does Atom report as the updated version if you run `atom --version`?

---

As a side note, it's super helpful if you can fill out the issue template as much as possible, that's always useful for us.

**Comment by thomruns** [comment]
In order to get out of the crashed state {wherein the alert box was visible but couldn’t be closed); I had to force-quit. When I reopened the app, it appeared as though the the update had not been downloaded (as evidenced by the tiny blue squirrel in the lower right of the window), so I hit the download button again. The same crash happened, but this time I was able to close without force-quitting. Then, on the third try, the app opened, appeared to have updated correctly to the new version (the blue squirrel is gone and the version number says 1.21.2), and appears to be running properly. 

So, it may be a glitch in the update function itself? Hope that helps.

Thom

**Comment by brandonmerritt** [comment]
Prerequisites

Put an X between the brackets on this line if you have done all of the following:
 [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
 [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
 [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq

Description
I'm having the same issue. 

Steps to Reproduce
Reboot machine.
Start Atom
Go to About
Click on "Restart and Install"

Expected behavior: 
Atom should "Restart and Install the Update"

Actual behavior: 
Atom doesn't actually close. You can still see it "active" in the OSX Dock. Force Quit doesn't show it as "Not Responding" it just never closes down. Manually shutting it down results in a return to "About" and shows that the update is still available. Occassionally I'll get a OSX system message saying that Atom is trying to install a "Helper" which requires my password and to click on the "Add Helper" button.

Reproduces how often:
Every time.

Additional Info:
If I choose to ignore the update. I get the "Atom is attempting to install helper" popup window repeatedly. It doesn't break the app, but it is annoying


Versions: 
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

[Atom_2017-10-27-145811_Brandons-MacBook-Pro.pdf](https://github.com/atom/atom/files/1434550/Atom_2017-10-27-145811_Brandons-MacBook-Pro.pdf)
