### ISSUE TITLE
Scrolling error

### ISSUE THREAD

**Issue by naveenpucha8** [atom/atom#16056]
when i try to scroll the files while using the atom text editor, it is not scrolling down

atom version : 1.21.1

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
