### ISSUE TITLE
Some issues with highlighting in pascal sources

### ISSUE THREAD

**Issue by vv7v7** [atom/atom#16057]
Dear developer,
As you see at the picture below there's some issue with pascal's highlighting:

![screenshot_20171101_141550](https://user-images.githubusercontent.com/25136754/32274379-3952abca-bf0f-11e7-9bf0-51234680fb07.png)

So symbols **--** shouldn't be read as comment's start as in pascal's programming language

By the way thank you very much as needed for this type of source editor,

Best regards,
vv7v7

**Comment by rsese** [comment]
Thanks for the report!  Atom doesn't provide Pascal syntax highlighting by default so the issue is likely with whatever community package you have installed for Pascal syntax highlighting (maybe https://atom.io/packages/language-pascal?) - the [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

> By the way thank you very much as needed for this type of source editor,

Thank you for the kind words, we do appreciate it! :bow:

**Comment by vv7v7** [comment]
Daer rsece,

Thank you for your reply, I've posted an issue on their repo.

Best regards,
vv7v7
