### ISSUE TITLE
Can we drop our application bundle size by removing snapshotted scripts?

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#16068]
In Spring 2017, [we shipped v8 snapshots](https://github.com/atom/atom/pull/14080) to improve startup time, which combine most of the source files that we ship into a single binary snapshot. Unfortunately, at that time we were unable to step the debugger through snapshotted code, which made us decide not to enable snapshots in development mode so that package authors could step through Atom source code when debugging their packages.

@as-cii, you mentioned that @hashseed had reached out to you with a patch that fixed the debugging issue. If we apply that in Electron, do you think we'll be in a position to remove any snapshotted scripts from the application bundle? It would save a ton of bandwidth for our users.

I think this is something we should follow up on fairly soon. The potential savings are huge and we've already done 95% of the work.

/cc @damieng @iolsen

**Comment by hashseed** [comment]
You are talking about [this issue](https://bugs.chromium.org/p/v8/issues/detail?id=6274). The fix has been landed in V8 6.0.

It should be safe to always ship snapshot and omit the source files. The snapshot should already contain the script source. I haven't had anyone from Atom verify the fix since then though.

**Comment by as-cii** [comment]
Thanks @hashseed for jumping on this. After our conversation, I opened an issue in the electron repository (https://github.com/electron/electron/issues/10234) that hasn't been addressed yet.

The problem is that the latest stable version of Electron ships with V8 5.8.283.38, and also the most recent beta version (https://github.com/electron/electron/releases/tag/v1.8.1) includes an outdated version of V8 (5.9.211.38).

So our only option if we want to address this now is to backport @hashseed's fix. I am not sure how hard that would be, but it seems like we could save a ton of bandwidth and disk space.

@nathansobo: let's schedule some time this or next week to talk about how we could backport the fix.
