### ISSUE TITLE
Q: Kernels for Literate Programming in Python available in Atom?

### ISSUE THREAD

**Issue by dsanalytics** [atom/atom#16061]
Are there any kernels for Literate Programming in python available in Atom?

It appears that, as of this post's time, pweave (http://mpastell.com/pweave) is just a grammar/syntax coloring lib, and not the actual library that renders pmd file into rich-text-style report - i.e. rich format markdown file would produce, but with dynamic content (e.g. data-driven) and code sections shown/hidden as specified. R language has this through Sweave lib.

Pweave is supposed to work like Sweave, but it does not. Knowing this, some people may find current pweave pages (http://mpastell.com/pweave) highly misleading - which is unfortunate.

Thank you in advance for your input.

P.S. I do know about markdown and jupyter notebook - very nice, but not the same thing.

**Comment by rsese** [comment]
Thanks for reaching out!

The best places to ask questions like this are the [Atom Slack](http://atom-slack.herokuapp.com/) and the [official Atom message board](https://discuss.atom.io) - community members that might have specific experience with what you're trying to setup (I personally don't unfortunately) with Atom can chime in and best help.   

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by dsanalytics** [comment]
@rsese - thanks
