### ISSUE TITLE
Keyboard layout support

### ISSUE THREAD

**Issue by vv7v7** [atom/atom#16082]
Dear developer,

Is it possible to add an indicator of keyboard layout ?

![screenshot_20171102_231843](https://user-images.githubusercontent.com/25136754/32350864-42081eb0-c024-11e7-98a7-70045046f7d8.png)

Best regards,
vv7v7

**Comment by lee-dohm** [comment]
Thank you for the suggestion!

That does sound like an interesting idea for a package :+1: Unfortunately, the Atom maintainer team is already full up handling all of the support and maintenance of the current core packages. There are a couple options:

* Someone may have already created this and we're not aware of it. Have you searched [the Atom package registry](https://atom.io/packages/) or [Atom theme registry](https://atom.io/themes/)?
* You can post a message on [Discuss, the official Atom and Electron message board](https://discuss.atom.io/c/packages) to see if anyone from the community is willing to try and build it

In any case, because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). But I'm also going to label this with `package-idea` so that others searching for suggestions here can find this.

Thanks again for your interest in Atom :grinning:

**Comment by vv7v7** [comment]
Dear lee-dohm,

Thank you for your reply, yes I've searched for community package, but there're only layout packages for panes so one was for atom version < 1.12 for non us localization or something like that. Btw I'll try to figure it out.

Best regards,
vv7v7
