### ISSUE TITLE
My editor has crashed and won't reload

### ISSUE THREAD

**Issue by bellaav** [atom/atom#16093]
I have no idea how to recreate it.

**Comment by Ben3eeE** [comment]
Try `atom --clear-window-state` **Note:** _This will clear the unsaved state of **ANY** project you had opened in Atom_

See: http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state for more information

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
