### ISSUE TITLE
ctrl + alt + up arrow is not work in linux

### ISSUE THREAD

**Issue by isoeugenol** [atom/atom#16098]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
add selection above and add selection below shortcut work in window. 
linux work another shortcut but add selection above, add selection below shortcut is not work.
### Steps to Reproduce

1. [First Step]
ctrl + alt + up arrow or ctrl + alt + down arrow in linux
2. [Second Step]

3. [and so on...]

**Expected behavior:** [What you expect to happen]
select above line or below line

**Actual behavior:** [What actually happens]
changed nothing.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lee-dohm** [comment]
Since it appears that you didn't try the appropriate steps in the [Debugging Guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/) in the [Atom Flight Manual](http://flight-manual.atom.io), I would recommend you check there first. Your best bet would be to start with [the section on keybindings](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings).

Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

**Comment by isoeugenol** [comment]
i checking my key Binding Resolver but ctrl+alt+uparrow is not input. 
like this
![image](https://user-images.githubusercontent.com/31752719/32414679-c8bbe502-c26f-11e7-8c69-f82fd5a9a5c0.png)

**Comment by lee-dohm** [comment]
When that happens, it means that the OS is intercepting that key combination before Atom even sees it.

**Comment by isoeugenol** [comment]
This is my fault. Because I studied with Windows version, I thought Linux would be the same keymaps as Windows but linux verson keymaps have not ctrl-alt shortcut.

**Comment by lee-dohm** [comment]
Glad to hear that things are working for you :+1:
