### ISSUE TITLE
Atom displays only white screen on 1.19 and later

### ISSUE THREAD

**Issue by abletonmaxwell** [atom/atom#16101]
### Description

Atom displays only white screen on 1.19 and later
but if i use 1.18 it runs perfectly fine.

### Additional Information

I'm using hacked Yosemite on unsupported Macbook.

**Comment by lee-dohm** [comment]
Thanks for bringing this up.

This is most likely because of the Electron upgrade from v1.3.x in v1.18 of Atom to v1.6.x in v1.19 of Atom. Between those versions, the required version of macOS was changed. While, technically, Yosemite is v10.10 of macOS and satisfies [Electron's minimum requirements](https://electron.atom.io/docs/tutorial/supported-platforms/), you're not running Yosemite. 

I hope that helps!
