### ISSUE TITLE
special characters in html text and syntax highlighting

### ISSUE THREAD

**Issue by reimax** [atom/atom#16128]
atom 1.22.0
html document
utf-8 charset
ubuntu 16.04

```html
<th class="col-md-1">
                                &nbsp
                            </th>
```

screenshot:
http://i97.fastpic.ru/big/2017/1108/03/9591cf1b8d0d2c50d083a7f016f85d03.png

if remove &nbsp syntax highlighting work success

**Comment by rsese** [comment]
Thanks for reaching out!  I think this is a syntax error because entity references should end with a `;`.  This should work:

```html
<th class="col-md-1">
                                &nbsp;
                            </th>
```

---

We require the template to be filled out on all new issues and pull requests so if you can use the issue template for future issues, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by reimax** [comment]
greate, but 

```html
<a href="/?do=test&show_test_content=list">test</a>
```

& in link give same error

**Comment by rsese** [comment]
I think that issue should go in https://github.com/atom/language-html - 
can you open an issue in https://github.com/atom/language-html and fill out the issue template if there's no existing issue already so we have it in the right place?
