### ISSUE TITLE
Could not create temporary directory: permission denied

### ISSUE THREAD

**Issue by HawkonDK** [atom/atom#16131]
How to fix this? `Could not create temporary directory: permission denied` 

Using Atom 1.21.1 on MacOS 10.13.1

have try to do what is in [#5160](https://github.com/atom/atom/issues/5160) with out luck

**Comment by rsese** [comment]
Thanks for reaching out!  You don't mention specifically what commands you tried from that issue so go ahead and give this a try:

https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054

And if you still have trouble after that, feel free to open a new issue with the issue template filled out and let us know exactly what you tried and we'll take a look.

---

We require the template to be filled out on all new issues and pull requests.  We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
