### ISSUE TITLE
Atom doesn't update directory modification date on file changes

### ISSUE THREAD

**Issue by nsrosenqvist** [atom/atom#16152]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I save a file in a directory the file modification time doesn't get set on the directory. If I would do the same with another text editor (e.g. gEdit) then the modification date is also set on the directory. Then I can for example check if a folder has been updated with PHP's filemtime, but not when editing the files with Atom.

### Steps to Reproduce

1. Get a directory's modification date
2. Edit and save a file within the directory
3. Compare with the save modification with the new modification date

**Expected behavior:** Should be different

**Actual behavior:** Is the same

**Reproduces how often:** 100%

### Versions
**Ubuntu GNOME 17.04 x64**
```
atom --version
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0
```

**Comment by rsese** [comment]
Thanks for the report - I was able to reproduce with Atom 1.22.0 on Ubuntu 16.04.  I did notice that gEdit behaves as you described but vim behaved slightly differently.  With vim, just opening the file updates the directory modification time while with gEdit you need to save the file to update the directory modification time.

**Comment by lee-dohm** [comment]
Thanks for the feedback.

Whether a directory's modified date is updated is something that is done by the operating system based on its own heuristics and isn't something that we want to start adding special cases for. From what I have been able to discover, on Unix-based systems adding a new file to a directory changes that directory's last modified date but changing the contents of a file that already existed within that directory does not. It is possible that the reason for the differences in behavior between Atom, gEdit and vim are due to those other editors storing temporary backup files or doing atomic saves within the same directory where the file in question is saved. Since the timestamp being modified is a side effect of that behavior and not of the saving of the file in question itself, we don't feel that we should attempt to duplicate that side effect of a side effect.

Thanks again for reaching out!
