### ISSUE TITLE
New package input text field backspace and arrow keys

### ISSUE THREAD

**Issue by 6112115** [atom/atom#16163]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

I generated a new package.
I then added a text field to the view.
Using the focus() function, I am able to get the user focused to the text field.
The text field does not allow backspace, arrow keys, or delete. Only characters, and home and end seem to work. Its like the text fields are only half focused.

Here are the text fields in the constructor from the view created by the generator:
```
  constructor(serializedState) {
    // Create root element
    this.element = document.createElement('div');
    this.element.classList.add('pronto-4gl');

	this.textField = document.createElement("input"); //New
	this.textField.type = "text"; //New
	this.textField2 = document.createElement("input"); //New
	this.textField2.type = "text"; //New

       // Create message element
       const message = document.createElement('div');
       message.textContent = 'The Pronto4gl package is Alive! It\'s ALIVE!';
        message.classList.add('message');
        this.element.appendChild(message);
	this.element.appendChild(this.textField); //New
	this.element.appendChild(this.textField2); //New
  }

```

Here is the toggle function in the main javascript file in lib changed to be an if statement with the focus function:

 ```
toggle() {
    console.log('Pronto4gl was toggled!');
      if (this.modalPanel.isVisible()) {
		  this.modalPanel.hide();
	  } else {
		  this.modalPanel.show();
		  this.pronto4glView.textField.focus(); //New focus function
	  }
  }

```

**Expected behavior:** Expecting to be able to use backspace and arrow keys in a text field

**Reproduces how often:** Every time

### Versions

Windows 10. 
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by 50Wliu** [comment]
See the Flight Manual section on native key bindings: https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#forcing-chromiums-native-keystroke-handling

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
