### ISSUE TITLE
Protractor intelisense is missing in Atom

### ISSUE THREAD

**Issue by sunilpatro1985** [atom/atom#16172]
I have installed Atom and all packages to run protractor tests, used package.json as below

```
  "devDependencies": {
    "@types/jasmine": "^2.5.41",
    "@types/node": "^6.0.62",
    "protractor": "~5.1.0",
    "typescript": "~2.2"
  },
```
but when I enter browser., I am not getting any auto populated methods. please guide.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
