### ISSUE TITLE
Live HTML preview not working

### ISSUE THREAD

**Issue by Nilasorai** [atom/atom#16170]
Atom crashes as soon as I start using  **live HTML preview**.Else it works fine but live HTML preview starts the crashing problem.I am on Mac OS Sierra 10.12.4.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
