### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by JueShouGitHub** [atom/atom#16181]
use atom-beautify -->ctil+alt+b --> crashed

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-beautify](https://atom.io/packages/atom-beautify) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
