### ISSUE TITLE
atom-beautify + uncrustify crashes atom when beautifying

### ISSUE THREAD

**Issue by Piussa** [atom/atom#16194]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Trying to beautify causes atom to crash

### Steps to Reproduce

1. Open .c file in atom
2. Select packages>atom beautify>beautify
3. Crash

**Expected behavior:** Beautification of .c file

**Actual behavior:** Crash

**Reproduces how often:** Every single time

### Versions

Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information
Use of atom-beautify package + uncrustify

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-beautify](https://atom.io/packages/atom-beautify) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
