### ISSUE TITLE
Atom Editor change system font-size on win 7

### ISSUE THREAD

**Issue by CagatayUNAL** [atom/atom#16205]
Hello Atom Team,

I love atom editor but when I install atom editor my laptop(win7) then system font-size shrinking.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
