### ISSUE TITLE
Multi cursor commands?

### ISSUE THREAD

**Issue by aleclarson** [atom/atom#16235]
What are the commands for multi-cursor? (eg: `editor:insert-cursor`)

**Comment by 50Wliu** [comment]
There currently are no commands for multi cursors.  This is mostly because the current keymap system does not handle mouse keybindings, and so adding/removing multi cursors is hardcoded.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by aleclarson** [comment]
Sorry, I wasn't clear. I'm actually looking for the command that modifies the functionality of a mouse click to insert a new cursor. The default key binding on macOS is `command+click`.
