### ISSUE TITLE
Check for atom update behind proxy

### ISSUE THREAD

**Issue by hendrikbl** [atom/atom#16240]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm using Atom behind a proxy and configured apm to use it. But when I check for updates in the About tab, the message says `No update available. Version 1.20.1 is the latest version.`. This is clearly wrong. It seems Atom itself isn't using the proxy setting and thus can't reach the update server. If this is the case, it should say something like `Couldn't check for updates.` instead.

### Steps to Reproduce

1. Use corporate proxy
2. Open Atom
3. Configure proxy in `.apmrc`
4. Verify apm is working through the proxy
5. Search for Atom update

**Expected behavior:** Atom should use apm's proxy to search for updates. If a new version is available, it should say so. If it can't reach the update server, it should say so (e.g. `Couldn't check for updates. Check your internet connection.`.

**Actual behavior:** Atom doesn't use apm's proxy and can't reach the update server. Even though it wasn't able to check for a new version, the message says `No update available`.

**Reproduces how often:** 100%

### Versions
Windows 7 Enterprise 64-Bit

`atom --version`
Atom      : 1.20.1
Electron  : 1.6.9
Chrome   : 56.0.2924.87
Node       : 7.4.0

`apm --version`
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python
git 2.14.2.windows.3
visual studio

**Comment by rsese** [comment]
Thanks for the report @hendrikbl - are you able to test when not behind a proxy?  There's an existing issue for this behavior on Windows but it's not specific to being behind a proxy:

https://github.com/atom/atom/issues/8265

If you can confirm that on your computer, checking for updates works when not behind a proxy but doesn't work when behind a proxy, then I think it might be useful to have this separate issue.  Otherwise I think we can close this as a duplicate of https://github.com/atom/atom/issues/8265.

Additionally, it would be very helpful for us if you can update the issue body to use the issue template.  The template gives us a lot of basic information that's helpful when going through issues.

**Comment by hendrikbl** [comment]
Thanks, I updated the issue body.

Searching for updates works fine without the proxy on the same machine. 
#8265 is a different issue because I'ts not related to the network connection. In my case It's about the message when there is no internet connection/a proxy.
