### ISSUE TITLE
Atom app relaunch convert my project tabs into splitted windows

### ISSUE THREAD

**Issue by HectorLS** [atom/atom#16251]
Hello

This is not a code problem, its just that if i had the app opened with... let's say 3 projects in 3 tabs and i close the app, when i relaunch it i got an atom window for each project, so annoying. 

It's a bug or a default setup issue ?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
