### ISSUE TITLE
how to close the old tab after split it to right(left...)

### ISSUE THREAD

**Issue by scotthuang1989** [atom/atom#16265]
The split to right/left is a very handy function. especially when I need review multiple files. but there is a problem. When I split a tab/file to another windows. the old file remains at the same position, so I end up with 2 same file open, each in different window. This is super inconvenient when I use shortcuts, think about this:
split file: ctrl+k   , right arrow 
back to old tab: ctrl+k, ctrl+ left arrow
close old tab: ctrl+w

if atom can close the old tab for me at first step, life should be much easier.

**Comment by 50Wliu** [comment]
@scotthuang1989 see https://github.com/atom/atom/issues/4738#issuecomment-345267165.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by scotthuang1989** [comment]
@50Wliu  thanks, I look at #4738, it is very helpful
