### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by loneshaana** [atom/atom#16279]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:215

RangeError: Invalid string length
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:215:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -5:09.2.0 script:run (input.hidden-input)
     -5:00.0 core:backspace (input.hidden-input)
     -4:56.4.0 core:save (input.hidden-input)
     -4:56 script:run (input.hidden-input)
     -4:53.5.0 editor:consolidate-selections (input.hidden-input)
     -4:53.5.0 core:cancel (input.hidden-input)
  7x -1:30.6.0 core:backspace (input.hidden-input)
     -1:22.8.0 snippets:next-tab-stop (input.hidden-input)
     -1:22.8.0 snippets:expand (input.hidden-input)
     -1:22.8.0 editor:indent (input.hidden-input)
     -1:19.4.0 editor:newline (input.hidden-input)
     -1:02.4.0 core:save (input.hidden-input)
  2x -1:01.3.0 script:run (input.hidden-input)
  5x -0:09.7.0 core:move-right (input.hidden-input)
     -0:06.1.0 core:move-left (input.hidden-input)
     -0:04.3.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-clock 0.1.15 
atom-python-run 0.9.5 
autoclose-html 0.23.0 
autocomplete-modules 1.8.0 
autocomplete-python 1.10.5 
gpp-compiler 3.0.7 
Hydrogen 2.1.1 
ide-python 0.3.0 
javascript-snippets 1.2.1 
kite 0.55.2 
my-theme-syntax 0.0.0 
preview 0.17.0 
python-debugger 0.2.0 
script 3.17.3 
```

**Comment by ungb** [comment]
Hey @loneshaana,

Are you able to provide any more details on what you were doing when this occurred or if you can consistently repro?  

Would be very helpful if we can get consistent repro steps!

**Comment by loneshaana** [comment]
I was doing the LinkedList program using python and suddenly the atom went slow and was consuming 
too much ram and processor, then after a while list of popups where shown on the atom screen 
------>UnCaught RangeError invalid string length <------.The atom was not responding properly ,there was only one solution ForceQuit Atom.
But After Restarting the whole system the problem was still there

**Comment by rsese** [comment]
Can you try starting in safe mode?

```
atom --safe
```

**Comment by loneshaana** [comment]
Hello

If I will run the python using the Atom,then the process of the python is
taking about 4GB of ram even after closing the atom ,even more  I checked
it in Activity Monitor it was taking 20GB of swap memory.
I don't know what is wrong with atom, it might be because the atom is
starting the python service and not closing it after its job is over

**Comment by rsese** [comment]
It sounds like you're using a community package to run Python code in Atom?  So just to confirm, are you able to reproduce the error or memory issue if you start Atom in safe mode?

```
atom --safe
```

**Comment by loneshaana** [comment]
No I didn't get any error in safe mode , the atom is working smoothly in
safe mode

**Comment by 50Wliu** [comment]
> No I didn't get any error in safe mode , the atom is working smoothly in
> safe mode

Thank you for responding!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Comment by croft1** [comment]
I was importing a 350mb geojson text file and it died like this
