### ISSUE TITLE
Atom Helper use 6GB ram

### ISSUE THREAD

**Issue by HawkonDK** [atom/atom#16308]
## Atom Helper use 6GB ram!
Use:
- Atom v1.22.1

On a:

- MacOS 10.13.1 High Sierra
- 8 GB 1600 MHz DDR3
- 2 GHz Intel Core i7

---

The Atom Helper doesn't clean up after itself and after some days use it, use 6GB of ram even if you close the program. Only way to reset it by using the Terminal to close the progress

**Comment by Greenek** [comment]
You still have 2 GB memory free, just enough for one Chrome tab ;)

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---
Further guidance: either fill in the _mandatory_ template in the issue body and re-open the issue, or open a new issue with the filled in template.
