### ISSUE TITLE
Jasmine 1.3

### ISSUE THREAD

**Issue by victorhqc** [atom/atom#16321]
Is there a reason why the specs use Jasmine 1.3? Is there a roadmap to update this eventually or change or support another stack? I'd love to contribute to update this or support it to something like [jest](https://facebook.github.io/jest/).

Lately I've had some issues because Jasmine 1.3 does not have `beforeAll`, `afterAll` and in some other cases, using mocks like [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter) pollutes other `spec` files and I need to use something like

```js
describe('Foo', () => {
  let mockFetch;

  beforeEach(() => {
    mockFetch = new MockAdapter(axios);
  });

  afterEach(() => {
    mockFetch.restore();
  });
});
```

Which is ok, but it is just so much complicated than doing a simple
```js
const mockFetch = new MockAdapter(axios);

describe('foo', () => {
  ...
});
```

**Comment by 50Wliu** [comment]
Yes, the reason is to support legacy package specs.  There have been [multiple](https://github.com/atom/atom/pull/5393) [attempts](https://github.com/atom/atom/pull/6099) to upgrade to Jasmine 2 but the eventual decision was that it would take too much effort to ensure that all community packages' specs would continue to work on Jasmine 2.

However, you _can_ use a different test runner: see https://flight-manual.atom.io/hacking-atom/sections/writing-specs/#customizing-your-test-runner.  Looks like you might find [atom-jasmine2-test-runner](https://www.npmjs.com/package/atom-jasmine2-test-runner) to be helpful.

**Comment by victorhqc** [comment]
Nice! thanks a lot! 😄
