### ISSUE TITLE
Atom opens .deb and .rar (?)

### ISSUE THREAD

**Issue by martinszy** [atom/atom#16334]
Sorry this is the wrong format for the issue.
In my machine atom opens .deb and .rar files by default, I know I have not taken the time to find out why that happens. But it gave me the idea: why doesn't atom open compressed files as folders?
It would be much easier when downloading files just to check what's in them.

You can close it now :P

**Comment by 50Wliu** [comment]
It does, using the [archive-view](https://atom.io/packages/archive-view) package.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
