### ISSUE TITLE
 Uncaught Error: write EOF when toggling comments

### ISSUE THREAD

**Issue by granadasPT** [atom/atom#16331]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[When toggling comments on a .php file using `crtl+a` an error is thrown:]

`Uncaught Error: write EOF
    at exports._errnoException (util.js:1022)
    at WriteWrap.afterWrite (net.js:804)`
### Steps to Reproduce

1. [Open a .php file]
2. [Use `Crtl+A` to select all code]
3. [Use the toggle comments on the edit menu or use the shortcut `Ctrl+~`]

**Expected behavior:** [All code is commented]

**Actual behavior:** [An error is thrown in the console]

**Reproduces how often:** [100%]

### Versions
Atom: 1.22.1
Electron: 1.6.15
Chrome: 56..2924.87
Node: 7.4.0

apm 1.18.8
npm 3.10.10
node 6.9.5 x64
python
git
visual studio

Windows Server 2008 R2 Enterprise 64-bit (6.1, build 7601)

**Comment by 50Wliu** [comment]
I noticed that you didn't specify whether you could reproduce the issue in safe mode or not.  Have you tried safe mode, and if so were you able to reproduce the issue?

**Comment by granadasPT** [comment]
Wasn´t able to reproduce the problem on safe mode but it stil doens´t comment all the lines it just adds  `<!-- and -->` in the top and end of the file

**Comment by 50Wliu** [comment]
Ok, because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

If you could open another issue about the `<!-- -->` not commenting the file that would be appreciated.
