### ISSUE TITLE
Atom has Worked stopped

### ISSUE THREAD

**Issue by hirenkeraliya** [atom/atom#16330]
I have an issue with an atom from last updates and that not work without installing any packages.
`
Atom: 1.22.1
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0
`
And I have used Ubuntu 17.04

Please help me on this issue either I switch to vs code editor.
Thaks

**Comment by rsese** [comment]
Thanks for reaching out! The information in the issue template is super helpful for us when looking at issues - can you update the issue body with the issue template filled out? For example, it would be really helpful to know what you mean when you say Atom stopped working - does Atom just not start at all? Do you get an error message?  Does Atom start in safe mode (`atom --safe`)?  Have you tried any of the other debugging suggestions in http://flight-manual.atom.io/hacking-atom/sections/debugging/?

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16330#issuecomment-349735911. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
