### ISSUE TITLE
Atom main window not showing up; Ubuntu

### ISSUE THREAD

**Issue by LeviMe** [atom/atom#16339]
### **Prerequisites**
[X]  Put an X between the brackets on this line if you have done all of the following: 
- Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
- Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
- Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
- Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
- Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
I'm having some issues with Atom, when running it on Ubuntu 16.04. 
When I launch the program, either from the desktop or the command line, the Atom icon looks open, the top bar with Atom buttons appears, I even can blindly open, write and save files, but the main window is nowhere. Using any of the command line options -which includes obviously the safe mode- doesn't change anything. 

### Steps to Reproduce
I just can't tell it for I don't know the cause of the problem. It appears more related to my OS and computer than to the program itself.

**Expected behavior:** [What you expect to happen]
Open Atom as usual.

**Actual behavior:** [What actually happens]
The main window doesn't shows up.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time.

### Version
Ubuntu 16.04
HP Pavillon 
i5-5200U CPU @ 2.20GHz × 4 
4GB RAM

atom --version

> Atom    : 1.21.1
> Electron: 1.6.15
> Chrome  : 56.0.2924.87
> Node    : 7.4.0

apm --version

> apm  1.18.5
> npm  3.10.10
> node 6.9.5 x64
> python 2.7.12
> git 2.7.4

### Additional Information
This issue isn't restricted to Atom; It also occured with Foxit Reader, after a while.

**Comment by rsese** [comment]
Thanks for reaching out! The information in the issue template is super helpful for us when looking at issues - can you update the issue body with the issue template filled out? For example, it would be really helpful to know what version of Atom you're running.  Also, when you say none of the command line options helped, which ones did you try (did you try safe mode)?  Have you tried any of the other debugging suggestions in http://flight-manual.atom.io/hacking-atom/sections/debugging/?  

There's an existing issue about this issue but specific to screen/monitor changes https://github.com/atom/atom/issues/6939.  Does that apply to your situation?  

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16339#issuecomment-350072224. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
