### ISSUE TITLE
[C++] Type in quotes is bolded

### ISSUE THREAD

**Issue by J-e-r-e-m-i-a-h** [atom/atom#16343]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Words in quote when syntaxing is set up for C++ are bolded

![image](https://user-images.githubusercontent.com/31524381/33743486-3773a72e-db6a-11e7-8c50-d2f832f34bac.png)

Anything that can be done about this?

### Steps to Reproduce

1. Set syntax to C++
2. Put words in quotes

**Expected behavior:** Words not to be bold

**Actual behavior:** Words are bold

**Reproduces how often:** 100%

### Additional Info

I've manually set the font weight to normal for comments and every other extremity possible.
I've installed font weight plugins and antialiasing plugins to see if they could to anything.

**Comment by rsese** [comment]
The styles are set by the syntax theme, looks like it's not bold in One Dark - which syntax theme do you use?

> I've manually set the font weight to normal for comments and every other extremity possible.

How did you try to do this?  I added this to my `styles.css` and I was able to adjust the font-weight:

```css
.syntax--quoted {
  font-weight: normal;
}
```

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
