### ISSUE TITLE
Editor Performance While Connected to FTP

### ISSUE THREAD

**Issue by EliterScripts** [atom/atom#16353]
**Software Versions**
I am using Ubuntu LTS 16.04, using Atom 1.14.4.

**Producing the Problem**
I made a connection to my FTP server (using nautilus's nice feature where you can connect to an FTP server on the left of the window--it like mounts a fake local directory that is on the server), and right-clicked and opened a folder on the FTP server and started editing using Atom.

**Description of Problem**

**Lag**
When I type in the editor, it moves slower than normal. When I save, the blue dot disappears very slowly after (but it updates on the other end--on the server--before it goes away some of the time). When I switch already open tabs, it takes longer. When I open a directory from hiding, it takes longer. Many of this shouldn't lag so much, because it isn't sending anything to the server yet.

**Deleting Stuff**
When I'm trying to delete stuff in the editor, it asks me to move my stuff to trash or cancel. When I choose "move to trash", it gives me an error. I think it's because there is no trash for this situation, so there should be an option either when deleting files, or after it fails to make it to the trash (could you have it able to remember, if it has to fail first?).

**Comment by rsese** [comment]
Thanks for the report @EliterScripts!   I think there are existing issues related to working with remote files for the problems you're reporting e.g. for performance:

https://github.com/atom/atom/issues/1766
https://github.com/atom/atom/issues/2456

I couldn't find the specific issue I was thinking about for that problem with deleting files though, but I believe it's in https://github.com/atom/tree-view/issues.

> Atom 1.14.4.

Unless you're running this version for a particular reason, the latest release version is 1.22.1 and there have been a lot of changes and improvements since 1.14.4 that you might want to check out.  I don't believe upgrading will address these issues in particular however.

And as a side note, for future issues it would be helpful to fill out the issue template with its existing format and to report a single problem per issue.
