### ISSUE TITLE
atom is not download

### ISSUE THREAD

**Issue by Mickey248** [atom/atom#16360]
i can try to download atom but it not work
why? i don't know

**Comment by mittalyashu** [comment]
Are you getting any kind of error or the download button is not working?

**Comment by rsese** [comment]
Thanks for reaching out @Mickey248!  Can you update the issue body with the issue template information?  The information there is very helpful for us when looking at issues.  In particular, please let us know what  version of Atom you're running, what operating system you're running, and if you can reproduce in safe mode (`atom --safe`).  If you can share more details about what you mean when you say Atom doesn't work (screenshots, error messages, etc.), that would be helpful too.

Once you update the issue body, we can re-open and take a look.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
