### ISSUE TITLE
For "Find and Replace: Select Next" please include a counter in status bar about how many were selected

### ISSUE THREAD

**Issue by matias-lopez-mauro** [atom/atom#16374]
The only message is about how many are highlighted when you start pressing Ctrl+D but after each next-selection is made by repeating the keystroke, there is no counter to confirm amont that were selected.
Also, a message that you reached EOF and that selection will return to top will be helpful.
Thank you.
Atom rocks.

**Comment by rsese** [comment]
Thanks for the suggestion!  Since this is related to find and replace, it should go in https://github.com/atom/find-and-replace, but I did notice there are packages that do some of what you want already I think?  E.g. this package shows a count of selections (along with other info) in the status bar:

https://atom.io/packages/selection-counter

> Also, a message that you reached EOF and that selection will return to top will be helpful.

There's a wrap indicator for search when it goes past the end of the file but not for select next -
 feel free to open a request for this in https://github.com/atom/find-and-replace but please fill out the issue template as much as possible.

**Comment by matias-lopez-mauro** [comment]
@rsese
Thank you for that package you mentioned, it helps me a lot.
Sorry for opening this in the wrong report, I thought the find-replace was a basic core mechanism and not a separated package (atom newbie mistake).

**Comment by rsese** [comment]
No problem @matias-lopez-mauro, there are a lot of repositories so it can be easy to miss - for reference, here's our documentation on suggesting features:

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#suggesting-enhancements

And I'm glad that community package is helpful for you 👍
