### ISSUE TITLE
Uncaught TypeError: Cannot read property 'active' of undefined

### ISSUE THREAD

**Issue by borishere** [atom/atom#16403]
[Enter steps to reproduce:]

1. Open big file in Atom

I also use a script in order to turn off annoying spell check when opening a file...
```
atom.workspace.observeTextEditors (editor) ->
  setTimeout ->
    atom.commands.dispatch atom.views.getView(editor), 'spell-check:toggle'
  , 0 if editor.element.spellcheck
```

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise N 2015 LTSB
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'active' of undefined

```
At C:\Users\user\AppData\Local\atom\app-1.23.1\resources\app\node_modules\spell-check\lib\main.js:164

TypeError: Cannot read property 'active' of undefined
    at Object.toggle (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/spell-check/lib/main.js:164:42)
    at HTMLElement.subs.add.atom.commands.add.spell-check:toggle (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/spell-check/lib/main.js:69:32)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:273:23)
    at ~/.atom/init.coffee:17:19
```

### Commands

```
     -0:22 spell-check:toggle (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-live-server 2.2.0 
atom-unsaved-changes 0.4.0 
autocomplete-paths 2.12.1 
block-comment 0.4.3 
build 0.69.0 
build-sass 0.11.0 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
console-log 1.10.0 
ctrl-dir-scroll 0.2.5 
cursor-blink-interval 0.3.1 
fake-image-snippets 1.1.0 
file-icons 2.1.15 
file-watcher 1.2.6 
filesize 3.0.0 
fonts 3.0.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
inc 0.0.4 
intentions 1.1.5 
jquery-snippets 11.0.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-htmlhint 1.4.0 
linter-jsonlint 1.3.0 
linter-markdown 5.2.0 
linter-stylelint 4.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
open-in-browser 0.5.2 
pigments 0.40.2 
project-manager 3.3.5 
random 1.4.1 
split-diff 1.5.1 
sync-settings 0.8.3 
toggle-quotes 1.1.0 
tree-view-autoresize 2.3.0 
```

**Comment by rsese** [comment]
Thanks for reporting!  It looks like this exception was reported in https://github.com/atom/spell-check/issues/210, https://github.com/atom/spell-check is probably the best place for this - I'll go ahead and copy your comment over.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
