### ISSUE TITLE
Editor backgound with letters WTF

### ISSUE THREAD

**Issue by leonardofel** [atom/atom#16415]
![1](https://user-images.githubusercontent.com/34713362/34208575-0cd5b9f6-e576-11e7-8ab9-9a4fe7aa49df.gif)

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
