### ISSUE TITLE
[FEATURE REQUEST] - atom interactive 3d animations as part of the gui

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [atom/atom#16431]
## [FEATURE REQUEST] - atom interactive 3d animations as part of the gui

**from my standing point, it would be really amazing to:**
- *add interactive 3d animatons as part of the gui of the program*

---

**that could be accomplished using a combination of**:
- *p5.js*
- *three.js*
- *openframeworks and cinder compiled via emscripten*

---

**that makes sense for me, as:**
- *as far as i am concerned atom is written in electron*

---

**this would be an advantage because:**
- *it would give the program a more futuristitc feel, definitely contributing to engage and innovate in terms of user experience*

**Comment by rsese** [comment]
Thanks for the feedback!  Though it seems like this would be an interesting idea for a package or theme, we'll pass along your suggestion to the maintainers team - because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.
