### ISSUE TITLE
`git rebase` displays an incorrect list of commits.

### ISSUE THREAD

**Issue by mattcollier** [atom/atom#16468]
Found a way to reproduce issue #15246.

This is on Debian 9, git 2.11.0, Atom 1.23.1

Configure atom as the preferred editor for git with
`git config --global core.editor "atom --wait"`

```
# clone a repo, git or https does not matter
git clone https://github.com/mattcollier/electron-rebuild.git
cd electron-rebuild
git checkout -b fix123
echo hello > some.txt
git add some.txt
git commit -m 'Make a modification.'
git rebase -i HEAD~2
```
Instead of the expected two commits being displayed, a list of 5 commits are shown instead of the expected 2 commits. 

In other instances that I do not know how to reproduce involving `rebase -i`, lists of commits that do not include the latest commits will be produced.

**Comment by rsese** [comment]
Thanks @mattcollier - I can reproduce the behavior your described with your steps to reproduce but  I also don't notice any difference if I don't use Atom as the editor.  E.g. this is what I see in Vim:

![vim-rebase](https://github-slack.s3.amazonaws.com/monosnap/electron-rebuild__vi__git_rebase_-i_HEAD2__8040_2018-01-03_13-14-31.png)

And Atom:

![atom-rebase](https://github-slack.s3.amazonaws.com/monosnap/git-rebase-todo__sandboxelectron-rebuild.gitrebase-merge_2018-01-03_13-13-21.png)

But I might be mis-understanding?

**Comment by mattcollier** [comment]
@rsese thanks for confirming. Do you think this is a `git` issue, and if so, is this unexpected behavior?

**Comment by rsese** [comment]
Since rebase shows the same set of commits with and without Atom, I'd guess it's an issue about how Git works.  I couldn't say if it's expected but we have a Git specific forum and you can ask there if you'd like:

https://github.community/t5/How-to-use-Git-and-GitHub/bd-p/Board_1

Or some place like StackOverflow of course (e.g. I saw this similar-ish post /cc https://stackoverflow.com/questions/26372569/git-interactive-rebase-lists-incorrect-too-many-commits).
