### ISSUE TITLE
does not  update or install packages on versions 1.23.1 - 1.24.0b2

### ISSUE THREAD

**Issue by edarblanco** [atom/atom#16467]
upgrade to version 1.23.1 and when I install a package does not leave me, I return to the previous version and everything is fine, install and update normally but return to the update and the same thing happens to me, update to aversion 1.24.0b2 and the result is the same, and the ip of the server changes constantly and still nothing happens, I leave a photo of what was described, thanks in advance
![image](https://user-images.githubusercontent.com/3819778/34457692-5802ef2a-ed87-11e7-874e-c4b13e62695f.png)

**Comment by rsese** [comment]
Thanks for reaching out! The information in the issue template is super helpful for us when looking at issues - can you update the issue body with the issue template filled out? For example, it would be really helpful to know what operating system you're running.  Also, can you confirm how you installed Atom?

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by edarblanco** [comment]
This issue is close, fix on relaease 1.25.0b3
