### ISSUE TITLE
How to remove or delay Atom top menu bar when in full screen mode?

### ISSUE THREAD

**Issue by abdelfattah10** [atom/atom#16488]
![screen shot 2018-01-04 at 3 14 01 pm](https://user-images.githubusercontent.com/25675663/34565178-6e75e7ce-f162-11e7-9be0-5685295a31b8.png)
It is totally annoying when changing between different tabs and atom menu bar pops up,
How to add delay so when i hover it will not pop up immediately?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
