### ISSUE TITLE
Menu showing wrong key binding

### ISSUE THREAD

**Issue by amejia1** [atom/atom#16509]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The menu for my package ([atom-xterm](https://atom.io/packages/atom-xterm)) shows an incorrect key binding. See the following.

![Atom Xterm menu](https://raw.githubusercontent.com/amejia1/atom-xterm/dab2521a8cbfd72b70e2063e1e23c579bd62e7e1/resources/atom-xterm-menu.png)

All the menu items should have `Ctrl+` at the beginning. The proper key bindings work but using the key bindings as shown above won't do anything.

### Steps to Reproduce

1. `apm install atom-xterm`
2. Click on `Packages > Atom Xterm`

**Expected behavior:** Should show proper key bindings.

**Actual behavior:** Leaves out the `Ctrl+` at the beginning.

**Reproduces how often:** Happens all the time.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

I'm using Windows 10. This also happens in Ubuntu 17.04.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Ingramz** [comment]
My guess is that the key bindings for macOS are trying to be displayed as they are defined the last. You can test that by re-ordering the key bindings so that windows/linux appear after the macOS ones. If it looks fine after that, the real issues seem to be:
1) Why command symbol is not displayed on Windows/Linux.
2) Why command keybindings are allowed outside macOS (maybe warn package authors and/or refuse to load them on platforms not applicable).

You should try splitting these by platform like other packages do. Instead of adding everything to `atom-workspace`, you can have `.platform-win32 atom-workspace, .platform-linux atom-workspace` and `.platform-darwin atom-workspace` which should then contain the appropriate keybindings only. This way menus should display the correct keybindings only for every platform.
