### ISSUE TITLE
Atom Use CPU more than 50%

### ISSUE THREAD

**Issue by burhandodhy** [atom/atom#16505]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom use more than 50% of CPU and it makes the window too slow http://prntscr.com/hx85mr

### Steps to Reproduce

1. Open project in Atom

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
Os : Windows 10 64bit
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
I noticed that you did not check the box signifying that you followed all the steps.  Could you please run through the prerequisites and report back if the issue still occurs?

**Comment by akshaynaik404** [comment]
I have been using atom and now atom beta, for more than a year now and the performance of the editor hasn't seemed to be improved. On a **idle 8GB** ThinkPad (Ubuntu) with **one terminal window** and **one chrome window(** 10 or so tabs) running I have to be **very careful when I open atom** as the laptop **freezes** during the initial load time.

Initially, I thought it was because of some of the plugins, but without all the plugins what is the use of "A hackable text editor for the 21st Century".

I have our entire codebase loaded in an atom, and when I build any one of our projects then editor crashes. Initially, I thought and also found on stack overflow that it might be because of a plugin that might be doing file indexing too much, but the issue still persists.

> I can tolerate bugs.

Because of one of such bugs, I switched to atom beta. 

> But a slow editor frustrates me.

I know I haven't given you any actual useful information that you can use to solve this problem, but I will soon perform all the steps mentioned in the Pre-requisites section and revert back to you guys.

Don't get me wrong. Its a great editor and I want it to be the best. :-)

**Comment by 50Wliu** [comment]
> I know I haven't given you any actual useful information that you can use to solve this problem, but I will soon perform all the steps mentioned in the Pre-requisites section and revert back to you guys.

Thanks!  That would be super helpful.  If possible, could you please create a new issue so we can track it separately?

**Comment by rsese** [comment]
Thanks again for your issue @burhandodhy!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16505#issuecomment-355864164. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
