### ISSUE TITLE
New file don't load javascript default snippets

### ISSUE THREAD

**Issue by treedbox** [atom/atom#16522]
Version: **1.24.0-beta2**
OS: **Ubuntu 17.10**
If i create a new file `ctrl+n`
and change the language `ctrl+shift+L` to `JavaScript`
when i type `lo`, the default snippets for "log" don't show
![screenshot from 2018-01-09 17-09-30](https://user-images.githubusercontent.com/4041664/34741189-8b56d84c-f560-11e7-9675-49c6a9fe93a0.png)

**Comment by rsese** [comment]
Thanks for the report!  The issue template information is super helpful for us -in particular, from the `Prerequisites` section, it would be helpful to know if you can reproduce in safe mode (`atom --safe`)?  

I was unable to reproduce with Ubuntu 17.10 and Atom 1.23.2 and 1.24.0-beta2 in safe mode.

**Comment by treedbox** [comment]
Works fine on Safe Mode
![screenshot from 2018-01-10 15-56-10](https://user-images.githubusercontent.com/4041664/34790012-19174306-f61f-11e7-9de8-33ca4c43fff6.png)

**Comment by 50Wliu** [comment]
Thanks for getting back to us!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop](https://atom.io/packages/package-cop) package has been helpful, you may want to try it. Once you've determined what package is causing the problem, the [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
