### ISSUE TITLE
autocomplete writes previous word again

### ISSUE THREAD

**Issue by manish33** [atom/atom#16549]
I am trying to write console.log in atom editor. when I'm complete writing console on the screen I get suggestions. then I hit enter on log() function suggestion. Ideally, it should print console.log() on the screen. But I'm getting console.console.log() on the screen.

**Comment by 50Wliu** [comment]
This is intentional, what you're seeing is called snippets.  To utilize them properly you should type only `log` and then autocomplete it.

Snippets use the following symbol in the autocomplete dropdown:
![snippet-indicator](https://user-images.githubusercontent.com/2766036/34912948-ec98324a-f8bc-11e7-94a5-7165fb8c1cec.png)
