### ISSUE TITLE
customizing title bar text is awkward

### ISSUE THREAD

**Issue by PerBothner** [atom/atom#16543]
The `updateWindowTitle` function hardwires a window title of the form "itemTitle - projectPath - Atom".  For some packages the concept of a "projectPath" doesn't really make sense.  For example for a terminal emularor you would rather use the "window title" as set by the xterm escape sequence.

I'm aware of the custom-title pacage (and its fork custom-window-title).  However, this just re-implements updateWindowTitle, which is architecturally fragile: It's the sort thing that is likely to break if anything changes in Atom proper.

For `atom-domterm` I hacked around the issue by having `getPath()` return the xterm-window-title and appending `"/."`.  Then the call to `dirname` in updateWindowTitle strips off the added `"/." `and we get the desired xterm-window-title. You can see this in the screenshot [here](https://atom.io/packages/atom-domterm).

However, this is a kludge, and (like custom-title) could easily break if anything changes in Atom.

How about checking for a `getWindowTitle` in the item? If provided, it would be expected to return either a string or an array of titlePart strings:

    var titleParts = [];
    if (typeof item.getWindowTitle === 'function')
        let parts = item.getWindowTitle();
        if (typeof parts === 'string') {
            titleParts.push(parts);
            if (process.platform !== 'darwin')
              titleParts.push(appName)
        } else
            titleParts = parts;
    } else {
        ... existing logic for generating titleParts ...;
    }
    document.title = titleParts.join(' \u2014 ')

**Comment by lee-dohm** [comment]
Thanks for the feedback.

The project path is meant to help differentiate between multiple windows when working on many different projects at the same time. In many context switching environments, the title bar text is used for exactly this purpose. For example, on macOS the Window menu allows one to quickly switch between windows by going to exactly the project one wants:

<img width="293" alt="screen shot 2018-01-18 at 8 21 39 pm" src="https://user-images.githubusercontent.com/1038121/35134754-3a2ea3e4-fc8d-11e7-9056-7f0ade7ff942.png">

If any random package was allowed to override that simply because it was the focused element, important information would be lost.

Given the above, I would be against allowing a change of this nature at the API level. On the other hand, I'm definitely for the Atom user customizing their own title bar to whatever fits their workflow best if they don't believe the above information is useful to them. I don't agree that package authors should be making that decision for all their users based on the package author's preferences.

I'm going to close this for now. Please let me know if there is something I'm missing or not understanding.

**Comment by PerBothner** [comment]
"_If any random package was allowed to override that simply because it was the focused element ..."_

But it can - it just needs to override `getPath`.

What do you suggest atom-domterm should retrutn for getPath?  The current working directory (assuming there is some kind of directory tracking)? The directory when the terminal was started?  The "project" when the terminal was created?

Bear in mind shell init files commonly set prompts so as to set the window title-bar to contain the current working directory. That looks incongruous and confusing next a a similar but different project path.  (And if they're the same, it looks silly.)

**Comment by lee-dohm** [comment]
Most things have a `getTitle` function on them that is used to place the appropriate text in the window title. For example, a text editor supplies the file name without the path as its `getTitle`:

https://github.com/atom/atom/blob/08d5677ddc85b9635327e3d5a9f5cd5b03881386/src/text-editor.js#L1059-L1061

Settings View returns `Settings` as its `getTitle`:

https://github.com/atom/settings-view/blob/b2b12887176e4a4e81f83d9b20dd448bd617ec9d/lib/settings-view.js#L327-L329

Perhaps you could use `Terminal`? Or `Terminal: ~/current/working/directory`?
