### ISSUE TITLE
No Trash for Atom to Move it To

### ISSUE THREAD

**Issue by EliterScripts** [atom/atom#16552]
### Prerequisites

N/A

### Description

When deleting a file from the atom file tree, it gives the error, titled: "The following file couldn't be moved to the trash." in a red dialogue. I am remoting into an FTP/SSH site using Ubuntu's nautilus program.

### Steps to Reproduce

1. Open nautilus
2. Click "Connect to server" (I am connecting to my Ubuntu OpenSSH server that runs my sftp/ssh--it just works)
3. Right-click on a system link on the remote site via nautilus GUI, and open with Atom.
4. delete a file in Atom

**Expected behavior:** [What you expect to happen]
Right-click on Atom's file tree, hit "delete", get a dialogue confirming the deletion. Atom attempts to move file to trash; if atom fails to move it to the trash, it gives another dialogue stating that it failed, asking the user if they would like Atom to just delete the file WITHOUT moving it to the trash. Some systems/directories do not have a trash.

**Actual behavior:** [What actually happens]
I delete the file in atom, it gives the error that there is no trash, and the file remains there and I cannot get rid of the file in atom. The error is quite inconsiderate to what the user might want to do.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time without fail.

### Versions
Operating System (both desktop and server):
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Nautilus:
GNOME nautilus 3.14.3

Atom:
Atom 1.23.3

### Additional Information

N/A

**Comment by rsese** [comment]
Thanks for reporting!

>  if atom fails to move it to the trash, it gives another dialogue stating that it failed, asking the user if they would like Atom to just delete the file WITHOUT moving it to the trash. Some systems/directories do not have a trash.

See Lee's comment about this here:

https://github.com/atom/tree-view/issues/856#issuecomment-357325782

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
