### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by weezixx** [atom/atom#16557]
Hi !

I'm making a program on C, but when I want to build it (F5), it's says : access denied. 

And when I disable my Avast protection, everything works fine. 

But if I put /.atom and my code in the exclusion, it doesn't change anything. 

Any ideas ?

Thanks a lot !

**Comment by rsese** [comment]
Thanks for reaching out!

In addition to your Atom home directory, maybe try adding `%localappdata%\Atom` as well?

In any case, this sounds like an issue with a community package you're using to compile C programs - in addition to the resources mentioned below, the maintainers of the package you're using might be able to help.  The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by weezixx** [comment]
Sorry I'm late, I added %localappdata%\Atom in the exclusion, and … still not working :/
