### ISSUE TITLE
Im not able to add atom to the github desktop.

### ISSUE THREAD

**Issue by mukunda-kn** [atom/atom#16563]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Downloaded 64 bit version of atom for windows 10. But after installing atom(V1.23.3), i am not able to add it to the external editor in GitHub desktop. Also the bin folder under %LOCALAPPDATA%\atom\bin is not created. Squirrel log is attached below.
[SquirrelSetup.log](https://github.com/atom/atom/files/1630776/SquirrelSetup.log)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

atom version: 1.23.3
apm version: 'apm' is not recognized as internal or external command
Windows 10
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Maybe https://github.com/desktop/desktop/issues/2585#issuecomment-326145898 contains the information to solve the issue you are having.

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by mukunda-kn** [comment]
@Ben3eeE Thanks for the reference. It worked. I finally got atom an GitHub desktop. Cheers :-)
