### ISSUE TITLE
Atom not installing behind corperate proxy RHEL 6

### ISSUE THREAD

**Issue by rawsh** [atom/atom#16598]
Proxy config on npm is correct.

Using the tar.gz from the download page gives a glib error in app, trying to compile gives a proxy error when it gets to leveldown. Everything before that downloads fine.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
