### ISSUE TITLE
Enhancement for the switch keyword inside es6 classes

### ISSUE THREAD

**Issue by pavilion** [atom/atom#16605]
Atom recognizes `switch` as a keyword when it is not. An example here.
![image](https://user-images.githubusercontent.com/3165436/35187010-3ca9b134-fe15-11e7-9d72-e7c9fc1c8507.png)

switch is the name of the function and not a keyword over there.
I think that something like an "intelligent switch" would be useful.
This feature already exists in other editors:
![image](https://user-images.githubusercontent.com/3165436/35187018-48f21404-fe15-11e7-83ed-d3ae6ca8723f.png)

**Comment by lee-dohm** [comment]
Thank you for contributing!

This is handled by the [language-javascript package](https://github.com/atom/language-javascript) and should be filed there. Additionally, we require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue on the https://github.com/atom/language-javascript repository and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
