### ISSUE TITLE
Make the app available on the OS X App Store?

### ISSUE THREAD

**Issue by yvan-sraka** [atom/atom#16609]
Hello,

I do not see any problem related to this in this repository after a quick search.

It could be really nice to let the application available in the OS X App Store! I do not know if there is a restriction or a good reason why the app is not already available now?

Thank you for those who could give me an answer.

**Comment by rsese** [comment]
Thanks for reaching out - see Lee's comment here for more details:

https://github.com/atom/atom/issues/10976

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
