### ISSUE TITLE
Ubuntu 17.04 atom Segmentation fault nohup "$ATOM_PATH"

### ISSUE THREAD

**Issue by SumNeuron** [atom/atom#16604]
I have downloaded atom (the .deb file on the homepage) and ran:

`sudo dpkg -i atom-amd64.deb`

Then I go to launch atom for a project:

`atom <project-dir>`

and I get

`/usr/bin/atom: line 129: 129576 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1`

I am running Ubuntu 17.04. 

So what do I do to resolve this?

**Comment by alexnanrick** [comment]
Having the same problem on 17.10

/usr/bin/atom: line 129: 15052 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1`

**Comment by rsese** [comment]
Thanks for reaching out - though the issue specifically mentions Ubuntu 17.10, the error looks exactly the same as described in:

https://github.com/atom/atom/issues/15944

An Electron issue was opened here since it seems to affect other Electron apps besides Atom:

https://github.com/electron/electron/issues/11234

A workaround is mentioned in the the Electron issue that some people have reported to get around the error if you want to give that a try.

I'll go ahead and reopen https://github.com/atom/atom/issues/15944 if you want to subscribe there for updates.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by cyberalex4life** [comment]
I have this problem on Ubuntu 17.10. A workaround would to create a script like this (atom-electron-fix):

```
#! /bin/bash

export XDG_CONFIG_DIRS=""
export GTK2_RC_FILES=""

atom "$@"
```
make this script executable and place it somewhere in your PATH (~/.bin, ~/usr/bin/, ~/usr/local/bin). Then change the Exec line of atom.desktop to this script.
