### ISSUE TITLE
atom file path do not suggest wrong or right

### ISSUE THREAD

**Issue by zitengine** [atom/atom#16602]
atom file path do not suggest wrong or right
for example: i have made a copy form another project, file of image path is [ ../zahed/image.php]
but at my code the path is [ ../zahed/img/image.php] which is wrong path. but i do not show any indicator that the path is wrong. same for PHP include code. so how to solve this issue.
#latest atom version installed

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
