### ISSUE TITLE
Additional keybinding for different JavaScript comment

### ISSUE THREAD

**Issue by svipben** [atom/atom#16625]
I want to suggest to add new keybinding for `/* */` comment block for e.g. for macOS with `cmd + alt + /`. JavaScript/TypeScript file types or any other which support such comment block.

**Comment by rsese** [comment]
Thanks for reaching out - as far as I know, we don't plan on adding anymore default keybindings since there are so many already and since you can manually add keybindings if you want.  For example, if you use the https://atom.io/packages/multi-comment community package, you can add a keybinding for `multi-comment:toggle` set to <kbd> cmd + alt + /</kbd> to give you the behavior you want.
