### ISSUE TITLE
Error: spawn pandoc ENOENT

### ISSUE THREAD

**Issue by Y3z3ki3l** [atom/atom#16667]
[Enter steps to reproduce:]

1. Just toggle preview

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Error: spawn pandoc ENOENT

```
At spawn pandoc ENOENT

Error: spawn pandoc ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -4:07.0 core:confirm (input.hidden-input)
  7x -3:20.4.0 emmet:merge-lines (input.hidden-input)
     -0:06.5.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
anodyne-dark-syntax 0.2.1 
atom-autocomplete-php 0.25.6 
busy-signal 1.4.3 
codeigniter 0.3.2 
codeigniter-nucleus 0.4.3 
docblockr 0.13.6 
emmet 2.4.3 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.83.1 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
MagicPython 1.0.12 
markdown-preview-plus 2.5.1 
merge-conflicts 1.4.5 
remote-atom 1.3.12 
remote-sync 4.1.8 
set-syntax 0.4.0 
seti-icons 1.5.4 
sort-lines 0.18.0 
tool-bar 1.1.4 
```

**Comment by rsese** [comment]
Thanks for the report!  This looks like an issue with  [markdown-preview-plus](https://atom.io/packages/markdown-preview-plus).  You can file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
