### ISSUE TITLE
Handle atom proxy authentication 

### ISSUE THREAD

**Issue by Jargon4072** [atom/atom#16704]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
There is a lot of pain associated with proxy configuration and proxy authentication in atom. So the request is to do something like this: https://github.com/Microsoft/vscode/pull/22369 to handle proxy auth in atom.

### Additional Information

Atom and vscode both are built on electron and js so it is possible to provide global proxy authentication for atom as well. It will reduce time and frustration associated with it.

**Comment by rsese** [comment]
Thanks for the feedback, we'll pass this along to the maintainers team - we'll go ahead and close this since we have more specific issues open related to proxies as mentioned in the Teletype issue (https://github.com/atom/teletype/issues/236#issuecomment-364118183) and because we treat our issues list as the [Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog).
