### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 260, Calling remote method getAutoFoldRanges..

### ISSUE THREAD

**Issue by jaizhu** [atom/atom#16719]
Atom couldn't seem to connect to the web server that I was using.

Repro:
1. Open Atom and try to connect to web server
2. Wait for the error...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 260, Calling remote method getAutoFoldRanges..

```
At /opt/facebook/nuclide/0.273.85332531/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

RpcTimeoutError: Timeout after 60000 for id: 260, Calling remote method getAutoFoldRanges..
    at Call._timeout (/opt/facebook/nuclide/0.277.88025270/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/opt/facebook/nuclide/0.277.88025270/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
```

### Commands

```
     -3:28.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -1:34.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.10 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.69.0 
language-graphql 0.9.0 
language-haskell 1.14.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.11 
nuclide 0.282.91025252 
nuclide-format-js 0.0.43 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
