### ISSUE TITLE
Atom strange render for markdown.

### ISSUE THREAD

**Issue by CoXier** [atom/atom#16713]
The issue is easy to reproduce so I only upload a screenshot here.

<img width="665" alt="2018-02-11 5 49 41" src="https://user-images.githubusercontent.com/18747437/36072063-fbc2dc2c-0f53-11e8-85db-5cdba82643f0.png">

As you see,  `2.2 header` and content after that, are all rendered  wrongly. But the preview is right. I do not know whether it's right to new this issue here? If not, please tell me. Thanks for your good job and I like atom.

**Comment by Aerijo** [comment]
@CoXier You are using invalid markdown (GFM) syntax. Please see [the official specs](https://github.github.com/gfm/#emphasis-and-strong-emphasis) on what is a valid left and right flanking delimiter.

In this case, the second `_` is not valid as a right (closing) delimiter because it is preceeded by a space. The syntax highlighting is correctly showing that the italicised text does not end there.

**Comment by Aerijo** [comment]
@CoXier Also, for future reference, this would have been a [`language-gfm`](https://github.com/atom/language-gfm) issue, not a core Atom issue.

**Comment by CoXier** [comment]
@Aerijo Thanks for your nice explanation.
