### ISSUE TITLE
Atom does not start from MSYS2 (Git Bash) shell on Windows 10

### ISSUE THREAD

**Issue by easybe** [atom/atom#16737]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The reason Atom is not started is due to `$ATOMCMD` not beiing set in `resources/cli/atom.sh`.
This was seen with MSYS2 (http://www.msys2.org/) and Git for Windows (MSYS2 based).
The behaviour was reproduced on another machine with fresh Windows 10 install.

Weirdly following hack in `atom.sh` fixes it:

     @@ -3,6 +3,7 @@
      if command -v "cygpath" > /dev/null; then
        # We have cygpath to do the conversion
        ATOMCMD=$(cygpath "$(dirname "$0")/atom.cmd" -a -w)
     +  echo $ATOMCMD > /dev/null
      else
        pushd "$(dirname "$0")" > /dev/null
        if [[ $(uname -r) == *-Microsoft ]]; then

This almost looks like a Bash bug...

### Steps to Reproduce

1. Install Git for Windows (https://git-scm.com/download/win)
2. Run `atom test.txt` in Git Bash

**Expected behavior:**

Atom should open file.

**Actual behavior:** 

Error:

    'test.txt' is not recognized as an internal or external command, operable program or batch file.

**Reproduces how often:**

Always

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

Git for Windows: 2.16.1.4
GNU bash: 4.4.12(2)-release (x86_64-pc-msys)
Windows 10: 1607

**Comment by rsese** [comment]
Thanks for the report - I just installed the latest Git Bash (2.16.1) and can't reproduce the error with Atom 1.24.0.   If you install 2.16.1 do you still have the same error?

**Comment by easybe** [comment]
I've upgrade Git for Windows to 2.16.1.4 using Chocolatey, same behavior :(
Are you using the same version of Windows (1607)?

**Comment by easybe** [comment]
I just can't wrap my head around this:

    $ atom test.txt
    + command -v cygpath
    + ATOMCMD=
    ++ uname -o
    + '[' Msys == Msys ']'
    + cmd.exe //C '' test.txt
    'test.txt' is not recognized as an internal or external command,
    operable program or batch file.

Add echo:

    $ atom test.txt
    + command -v cygpath
    +++ dirname /c/Users/user/AppData/Local/atom/bin/../app-1.24.0/resources/cli/atom.sh
    ++ cygpath /c/Users/user/AppData/Local/atom/bin/../app-1.24.0/resources/cli/atom.cmd -a -w
    + ATOMCMD='C:\Users\user\AppData\Local\atom\app-1.24.0\resources\cli\atom.cmd'
    + echo 'C:\Users\user\AppData\Local\atom\app-1.24.0\resources\cli\atom.cmd'
    C:\Users\user\AppData\Local\atom\app-1.24.0\resources\cli\atom.cmd
    ++ uname -o
    + '[' Msys == Msys ']'
    + cmd.exe //C 'C:\Users\user\AppData\Local\atom\app-1.24.0\resources\cli\atom.cmd' test.txt

**Comment by easybe** [comment]
Or could it be a bug in `cygpath`? That it doesn't return anything in this certain case.

**Comment by rsese** [comment]
> Are you using the same version of Windows (1607)?

Looks like I'm on 16299.

I also installed MSYS2 and tried there but running Atom there worked ok for me too (I had to update the path first though) .

@ungb are you able to repro on your Windows machine/VM?  Repro steps:

> 1. Install Git for Windows (https://git-scm.com/download/win)
> 2. Run `atom test.txt` in Git Bash

**Comment by easybe** [comment]
> Looks like I'm on 16299.

That doesn't sound right, see: https://en.wikipedia.org/wiki/Windows_10_version_history

**Comment by Arcanemagus** [comment]
> That doesn't sound right

`16299` is a _build_ number, which just happens to correspond to the _version_ number 1709, which is the current version of Windows 10. You are on a _very_ old version of Windows 10 as version 1607 was released back on 2016-08-02.

For the record, I am also unable to reproduce this in either of these combinations:
* `git version 2.16.1.windows.3` + `Build 17101.rs4_release.180211-1040` (x64 Pro)
* `git version 2.16.1.windows.4` + Version 1703 (x64 Enterprise)

**Comment by easybe** [comment]
> You are on a very old version of Windows 10

I am aware of that, but this is what our company makes us use.

**Comment by the-j0k3r** [comment]
This is slightly offtopic but @Arcanemagus should be aware Windows 10 1607 is still a supported and valid Windows 10 version,
Its unrealistic, you/people who think alike and/Microsoft simply cannot expect for everyone to keep up with the 6 monthly upgrade and introduce all manners of issues and instabilities due to their buggy source code which has no time to mature in 6 months.

`</endrant> `

**Comment by lee-dohm** [comment]
@the-j0k3r You are correct, this is off-topic. Additionally, generally talking about people or groups of people, e.g. "you", "people who think alike", "Microsoft", is a quick way to cross the line in Code of Conduct territory.

While Windows 10 1607 may still be supported by Microsoft or others, that doesn't mean that we, the Atom maintainer team, have to support it. We could decide to support only Solaris on Sun Sparc systems, if we so chose. We have to make decisions all the time on what we have and do not have the resources to support. If someone would have the time and resources to donate to test Atom on every version of Windows that Microsoft still has not end-of-lifed, they would have my utmost gratitude. Until such time, supporting only relatively recent versions of Windows is a completely reasonable decision for us to make.

Since this is off-topic, if you would like to discuss this further, please find me in the Atom community Slack team. I would be happy to chat about this in the `#watercooler` channel.

**Comment by the-j0k3r** [comment]
> We have to make decisions all the time on what we have and do not have the resources to support.

if Atom teams so decides (or has decided) then please indicate where it is so documented, so that I will take a better informed decision.

> Additionally, generally talking about people or groups of people, e.g. "you", "people who think alike", "Microsoft", is a quick way to cross the line in Code of Conduct territory.

Noted! I have to work on how we come across to readers, I indeed may have over done it.
May I say though, no offence intended, your reply it is quite passive aggressive.

Thank you.

**Comment by the-j0k3r** [comment]
Sorry, I dont use slack and tbh your reply was ott.

**Comment by lee-dohm** [comment]
You can find documentation of that nature in the atom/design-decisions repo.

**Comment by easybe** [comment]
Currently, with Atom v1.26.1 (Windows 1607, 10.0.14393) I no longer see the problem. Anyway, the problem seems to be very hard to reproduce. I suggest we close this issue. Thanks for trying to help.

**Comment by rsese** [comment]
> Currently, with Atom v1.26.1 (Windows 1607, 10.0.14393) I no longer see the problem. 

Ahh great, thanks for letting us know!
