### ISSUE TITLE
Can't install new packages (gyp WARN install got an error, rolling back install)

### ISSUE THREAD

**Issue by bigifoot** [atom/atom#16760]
Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hi,
I installed the last version of Atom for Windows 7 64bit and i can install any new packages.
yes, i've checked every method/ post that has the same issue and still can't resolve it.
anyone can help please?

also i don't a use proxy and i set:
apm config set proxy null
apm config set https-proxy null

npm config set proxy null
npm config set https-proxy null

Versions
apm -v
apm 1.18.12
npm 3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.14
git 2.16.1.windows.4
visual studio 2015
Windows 7 64bit

![ddddd](https://user-images.githubusercontent.com/36519180/36315001-39eb4cfc-133f-11e8-8a31-c28ccc3cdadf.PNG)

**Comment by lee-dohm** [comment]
Hello Liran ...

You also posted in the Slack team this screenshot:

![dddd](https://user-images.githubusercontent.com/1038121/36326904-95592e20-1311-11e8-8135-6fb9215bb550.PNG)

:point_up: This appears to be the true source of the problem. As we mentioned multiple times on Slack, this appears to be a problem with your machine, network configuration, npm or some combination of those three. Until you clear up that problem, we will be unable to help you since Atom requires npm to be working properly in order to do its job.

I appreciate the frustration this must be causing you. Unfortunately, there is simply nothing Atom can do to fix this problem.

Thanks
