### ISSUE TITLE
Please update github package to 0.10.1 for 1.24 release

### ISSUE THREAD

**Issue by the-j0k3r** [atom/atom#16772]
What title says.

It includes considerable important fixes that shouldn't be held back until 1.25 is out which maybe a long way away still (a month is too long imo) considering the issues.

Please consider it. I would make a PR but, asking instead may be better, who knows..

**Comment by the-j0k3r** [comment]
Its a mixed list of bug/exceptions and other improvements since 0.9.0, if you really need an itemized list Ill set aside some time to dig though and post them if you really want them.

Current Atom stable 1.24 has github 0.8.3 from end of November last year though. But I dont mean to sound like a ranting or ungrateful tom.

**Comment by smashwilson** [comment]
We did consider this, but 0.10.1 had enough new features that we decided to give it some time to percolate on beta to give us a chance to notice any regressions that slipped in. My argument was that we should tend to follow our standard master ➡️ beta ➡️ stable pipeline unless we have a compelling reason not to, like a security issue, or a crash or a lock-up.

With that said: I _also_ support efforts to shorten that pipeline for work in bundled packages, especially ones like github that are more like full products in and of themselves. I hear we've talked about finding a way to release them independently, so that we don't find ourselves waiting multiple months to roll progress out to our users, but I don't believe that has progressed beyond someone saying "this would be good, we should find a way to do this" :smile:

@the-j0k3r, you could always switch over to the beta channel! It's there for people who are willing to accept a bit more risk of finding bugs to see features early and give us feedback. I run a build of Atom that's built fresh from master every morning and even that's perfectly usable day-to-day with very few exceptions.

**Comment by the-j0k3r** [comment]
@smashwilson thanks, I have a test install with beta, and at least github 0.10.1 is not displaying so many issues and I find myself more and more attracted to the betas, because the bug fixes and improvements on this much used package are there and because overall the beta is has been working/performing better than the stable.

It would be nice to see built in packages independently distributed, its nice to dream but I cant see that happening any time soon as you would probably need a downgrade to previous version mechanism to counter any unforeseen stability issues with single package upgrades.

Oh well. I guess the answer to this issue is a fat no, so Ill close it.

Have a nice day guys and girls.
