### ISSUE TITLE
Highlight comment in Python

### ISSUE THREAD

**Issue by HaoyangFan** [atom/atom#16778]
I am new to Atom, but when I make comments in python code using Vim, if I want to highlight those comments so next time I will immediately notice them when I review the code, I can do something like 
`#TODO: comments`
or
`#FIXME: comments`
or
`#BUG: comments`
or
`#XXX: comments`
Vim will put some bright yellow color around `TODO` and `FIXME`. Although in Atom, the color of characters for that that two words will change too, but there is no such color apply on those two words. In my view, they are still too vague and hard to distinguish from other codes(I am using One Light Theme). In addition, I even want Atom to highlight the entire lines of comments with those keywords, not just change the font color. So is there a way I can do/ a package I can install to make Atom behaves like Vim in the way I describe above? 
Thanks

**Comment by Aerijo** [comment]
For this kind of question, we have the [Atom forums](https://discuss.atom.io/).

**Comment by HaoyangFan** [comment]
I try to make a post at there. However, because I am new to that forum, it seem likes I am restricted to publish a new post

**Comment by Aerijo** [comment]
No, anyone can post a question. You may need to make an account though.

**Comment by Ben3eeE** [comment]
@HaoyangFan Your post happened to get caught by the spam filter by mistake and needed approval by a moderator. I have approved it and it is now visible here: https://discuss.atom.io/t/highlight-comment-in-python/52578/1

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
