### ISSUE TITLE
Using Promises with onWillSave()

### ISSUE THREAD

**Issue by Interagierende-Systeme** [atom/atom#16807]
Hi,

I am trying to use buffer.onWillSave(), from the atom documentation (https://atom.io/docs/api/v1.24.0/TextBuffer#instance-onWillSave) to try and force atom to carry out a function first, and then save.

The description says that the function will wait for any promises to be resolved before the Editor saves. However, in my case, the Editor saves regardless of the pending status of the promise.

Is there a particular/correct way I should be implementing my promise for it to work with onWillSave()? It could very well be that the error is on my part. Can anyone give me an example of using Promises with onWillSave()?

Any help would be appreciated.
Thanks.

**Comment by rsese** [comment]
Thanks for reaching out!  Of the resources mentioned below, I think the Atom Slack is probably the best place to ask a question like this, there's a number of folks with experience using the API that are active and helpful there.  Sorry I can't help you myself, but I don't have experience using that API so can't offer any advice unfortunately.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by Interagierende-Systeme** [comment]
Thank you for the helpful reply!

**Comment by Interagierende-Systeme** [comment]
Just in case anyone comes across this thread with a similar problem, check your Atom version. onWillSave() only starts supporting promises from version 1.21 onwards. 

I posted my question on this thread and worked up to the answer. https://discuss.atom.io/t/help-with-onwillsave/52682/13

**Comment by Arcanemagus** [comment]
If you had filled out the template (which includes your Atom version) as is requested of new issues that would have been an easy problem to spot 😉.

**Comment by Interagierende-Systeme** [comment]
Yes, very true.
