### ISSUE TITLE
Text field settings revert to default in package settings UI 1.25.0-beta2

### ISSUE THREAD

**Issue by mshenfield** [atom/atom#16817]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Text field settings revert to default in package settings UI.

![atom-settings-bug](https://user-images.githubusercontent.com/4812055/36533088-2a7b0292-1788-11e8-9bd2-9636d285bb32.gif)

I'm not typing a backspacing or clearing the field manually.  A half second after I stop typing or leave the field it reverts to the default value.

### Steps to Reproduce

1. Open Atom in safe mode (`atom --safe`)
2.  Go to Atom Settings menu (`Cmd + ,`)
3. Go to Packages in the sidebar
4. Select an `atom/language-` package (all packages should reproduce, but `atom/language-` are built-in and have a `Tab Length` and other text field settings)
5.  Try typing into a text field

**Expected behavior:**
The value is preserved.

**Actual behavior:**
The value reverts to the default

**Reproduces how often:**
Always

### Versions

Atom    : 1.25.0-beta2
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by Nxt3** [comment]
This has been happening to me since 1.25.0-beta0.

I noticed it when trying to change the prefered line length per language; if I go to the `typescript-language` and attempt to change the line length, it defaults to whatever the global setting is--just like your GIF above.

**Comment by Arcanemagus** [comment]
This looks like another side effect of #16628 @maxbrunsfeld.

**Comment by maxbrunsfeld** [comment]
It actually looks like this bug has existed ever since https://github.com/atom/settings-view/pull/974. Whenever a valid value is typed into the text editor, we do [this](https://github.com/atom/settings-view/blob/b2b12887176e4a4e81f83d9b20dd448bd617ec9d/lib/settings-panel.js#L272-L274):

```js
if (!this.set(name, value)) {
  this.setText(editor, name, type, atom.config.get(name))
}
```

but the [`SettingsPanel.set` method](https://github.com/atom/settings-view/blob/b2b12887176e4a4e81f83d9b20dd448bd617ec9d/lib/settings-panel.js#L188-L198) has never returned a value:

```js
set (name, value) {
  if (this.options.scopeName) {
    if (value === undefined) {
      atom.config.unset(name, {scopeSelector: this.options.scopeName})
    } else {
      atom.config.set(name, value, {scopeSelector: this.options.scopeName})
    }
  } else {
    atom.config.set(name, value)
  }
}
```

So we currently *always* reset any field value back to the globally-scoped value after the user stops typing.

I think the fix is to make `SettingsPanel.set` *return* the value of `atom.config.set` as was probably always intended.

/cc @50Wliu

**Comment by 50Wliu** [comment]
Thanks, I'm not sure how I didn't find that while testing.

**Comment by mshenfield** [comment]
Thanks for tracking it down so quickly!
