### ISSUE TITLE
Uncaught Can't find <div class="text-center">  <img src="rolex.jpg" class="ima img-thumbnail" a...

### ISSUE THREAD

**Issue by imdavor** [atom/atom#16819]
[Enter steps to reproduce:]
Trying to use shortcut for Toggle Comments. Default is Ctrl+' and my bind was Ctrl+q. Neither is working just throwing bug.

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace
```
Uncaught Can't find <div class="text-center">
  <img src="rolex.jpg" class="ima img-thumbnail" alt="">
</div> file
```

```
At C:\Users\Davor\AppData\Local\atom\app-1.24.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:950

undefined
```

### Commands

```
     -1:34.9.0 editor:indent (input.hidden-input)
     -1:33.6.0 core:backspace (input.hidden-input)
     -1:31.5.0 emmet:encode-decode-data-url (input.hidden-input)
     -1:30.4.0 snippets:next-tab-stop (input.hidden-input)
     -1:30.4.0 snippets:expand (input.hidden-input)
     -1:30.4.0 editor:indent (input.hidden-input)
     -1:29.3.0 core:backspace (input.hidden-input)
     -1:24.7.0 emmet:encode-decode-data-url (input.hidden-input)
     -1:20.7.0 core:save (input.hidden-input)
     -1:14.1.0 core:backspace (input.hidden-input)
     -1:12.3.0 core:confirm (input.hidden-input)
  7x -1:11.5.0 core:backspace (input.hidden-input)
     -0:14.8.0 emmet:encode-decode-data-url (input.hidden-input)
     -0:13.5.0 editor:consolidate-selections (input.hidden-input)
     -0:13.5.0 core:cancel (input.hidden-input)
     -0:12.3.0 emmet:encode-decode-data-url (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-live-server 2.2.0 
atom-shortcuts 0.0.2 
autocomplete-html-entities 0.2.0 
autocomplete-php 0.3.7 
emmet 2.4.3 
file-icons 2.1.16 
pigments 0.40.2 
teletype 0.8.0 
wordpress-autocomplete 1.2.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you reproduce the error in safe mode (`atom --safe`)?

**Comment by 50Wliu** [comment]
This looks like a bug with [emmet](https://atom.io/packages/emmet). It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by imdavor** [comment]
I found solution. 
Toggle comments in Atom > Settings > Keybindings > it is _Ctrl+'_ #this causes error
In Pacakages > Emmet > Settings > shortcut is _Ctrl+Shift+/_  #this works.
Thank you for tip.
