### ISSUE TITLE
If publish fails, version changes are committed 

### ISSUE THREAD

**Issue by surdu** [atom/atom#16836]
If for some reason the `apm publish` failes, like for example the one described in #16835, the changes are committed anyway to the repo. 

This causes problem if this goes unnoticed as it may end up in unnecessary version bumps once the problem is resolved.

**Versions:**
```
$ atom-beta --version
Atom    : 1.25.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm-beta --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-beta1
python 2.7.10
git 2.14.3
```

**Comment by rsese** [comment]
Thanks for this followup issue - looks pretty related to https://github.com/atom/apm/issues/477 I think?  We'll go ahead and close as a duplicate and you can subscribe for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
