### ISSUE TITLE
Publish fails when using two factor authentication 

### ISSUE THREAD

**Issue by surdu** [atom/atom#16835]
When I run `apm-beta publish major` and my GitHub account has TFA enabled, the publish fails with the following error:

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/surdu/typewriter-sounds/'
```

Once I disabled the TFA, everything worked again.

**Versions:**
```
$ atom-beta --version
Atom    : 1.25.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm-beta --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-beta1
python 2.7.10
git 2.14.3
```

**Comment by rsese** [comment]
Thanks for the report @surdu - if you have 2FA enabled you need to use a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) instead of your password.  The apm README was recently updated to mention this:

https://github.com/atom/apm/#two-factor-authentication

**Comment by varemenos** [comment]
It'd be great if that README section would also include which are the minimum required scopes do work things out.
I'd rather not generate a token that has more scopes than needed.

**Comment by sungwoncho** [comment]
@varemenos I have granted my token all the repo scopes and was able to publish. However it would be still good to know the bare _minimum_ required scopes.
