### ISSUE TITLE
Uncaught Error: Failed to fetch

### ISSUE THREAD

**Issue by ZhenjieRuan** [atom/atom#16862]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Failed to fetch

```
At /opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

Error: Failed to fetch
    at /opt/facebook/nuclide/0.284.93285247/nuclide/pkg/fb-phabricator-common/lib/main.js:24:13
    at Generator.throw (<anonymous>)
    at step (/opt/facebook/nuclide/0.245.68217134/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at _throw (/opt/facebook/nuclide/0.245.68217134/nuclide/node_modules/async-to-generator/async-to-generator.js:27:9)
```

### Commands

```
     -0:13.5.0 fb-on-demand:saved-work (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-material-ui 2.1.3 
cursor-history 0.13.0 
dash-ui 0.4.4 
emmet 2.4.3 
ex-mode 0.18.0 
file-icons 2.1.17 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.84.0 
language-cython 0.3.0 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
monokai 0.24.0 
nebula-syntax 0.4.5 
nucleus-dark-ui 0.12.3 
nuclide 0.286.94487657 
nuclide-format-js 0.0.44 
relative-numbers 0.9.0 
set-syntax 0.4.0 
seti-syntax 1.1.3 
seti-ui 1.10.0 
sort-lines 0.18.0 
tool-bar 1.1.6 
vim-mode-plus 1.29.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
