### ISSUE TITLE
Ubuntu 17.04 installing atom results in segmentation fault, using snap results in broken html

### ISSUE THREAD

**Issue by SumNeuron** [atom/atom#16902]
So I am trying to atom with Ubuntu 17.04.
It isn't going very well (see https://github.com/atom/atom/issues/11743 )
So I tried using snap to install atom. Using snap works.... but only if you launch atom with sudo, e.g. `sudo snap run atom <dir>`, as `snap run atom <dir>` does nothing. When launching with sudo 1/10 times you will get atom as it is meant to be,  8/10 times you will get nothing, and 1/10 times you will get the following image

![screenshot from 2018-03-08 09-20-44](https://user-images.githubusercontent.com/22868585/37140632-b2016adc-22b2-11e8-9f1a-44fab4d869a0.png)

I have no idea what is going on.
So any ideas on how to get atom to work properly on 17.04 would be appreciated

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

The snap version of Atom is community-maintained and not officially supported by the Atom maintainers. Therefore, you'll have to ask the snap package maintainers for guidance about issues. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

See https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux for installing Atom from the official repositories.

---

For this issue: You can click the red icon in the top right corner to see an error message that might indicate what the problem is.

**Comment by SumNeuron** [comment]
Hi @Ben3eeE thanks for the prompt response. My issue had two parts, the latter is snap - the former is the segmentation fault (when installed on linux without snap) which makes atom also unusable.

**Comment by Ben3eeE** [comment]
There is an open issue https://github.com/atom/atom/issues/15944 for a segfault on start that has been tracked down to electron and the suggested workaround is to clear `XDG_CONFIG_DIRS` /cc: https://github.com/atom/atom/issues/15944#issuecomment-346597890.

Though this issue is seems to be specific to Ubuntu 17.10?

Other things you can try are listed in the flight-manual debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/

**Comment by SumNeuron** [comment]
@Ben3eeE  Im still working through the debugging guide, but that linked solution does not work in my case

**Comment by SumNeuron** [comment]
@Ben3eeE also, it is interesting that launching via sudo is what aids in making this work
