### ISSUE TITLE
Please support kotlion language.Thanks

### ISSUE THREAD

**Issue by why168** [atom/atom#16901]
Thanks

http://kotlinlang.org/

**Comment by Arcanemagus** [comment]
As Atom is a generic text editor it already "supports" editing those files. If you are looking for syntax highlighting ("colorization") it looks like you would want to install the [language-kotlin](https://atom.io/packages/language-kotlin) to add that to your Atom instance.

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
