### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by benbalter** [atom/atom#1691]
Was using Atom today during a presentation.

While Atom's not necessarily part of that evaluation, I noticed that VoiceOver thought the focus was on the close button the entire time. 

Since we're in a web browser, theoretically accessibility should be a given, but may be something to keep in mind going forward if it's an easy fix.

//cc @muan, @nuclearsandwich, @eanakashima

**Comment by camlorn** [comment]
I for one can +1 this, given that I'm a blind programmer.
I'm going to see how it performs on Windows when I get some time.  Voiceover is one of the worst in terms of accessibility on the web, with all sorts of little quirks and nonstandard behavior (there is a reason that WebAIM surveys  only show macs as around 30% or less, and that's because browsing the web is impractical at best).
Assuming it at least works somewhat, there may be a number of simple fixes which can be done just by adding some Aria to it.  Most of the rest comes for free by making the entire thing useable by the keyboard--the trick is clearly labeling everything that might get focus.
The only major issue here may be in Atom-shell: the web view has to be accessible in the first place.  I know that Chrome has been seeing some improvements of late, but have never played with stand-alone webviews.  The major concern is that they're not actually exposing Aria, in which case there may be nothing to be done without major work on Chromium.
Unfortunately, my web expertise is limited to basics plus accessibility; I'm a C++ and DSP person, mostly.

**Comment by roman01la** [comment]
Hello. What's the status on accessibility in Atom? How good is screen readers support?

**Comment by nathansobo** [comment]
@roman01la It's not something we've had time to work on yet, so it probably doesn't work at all considering the hoops we've jumped through to get performant rendering. If anyone is interested in investigating the issues involved, that would be great.

**Comment by roman01la** [comment]
@nathansobo I'm not familiar with Atom's internals. Where should I start? I guess there's should be UI core or something?

**Comment by nathansobo** [comment]
@roman01la I'm not too familiar with accessibility, so it makes it a bit tough for me to know as well. Maybe an interesting place to start could be figuring out how to present the text in the editor to a screen reader? For that we have `text-editor-element.coffee` and its associated structures, starting with `text-editor-component.coffee`. Beneath this there's a model layer rooted `text-editor.coffee`.

I guess the big question is what kind of APIs exist for presenting a user interface to a reader. I have zero experience in that area. If we could start with a package that adds this sort of functionality from the outside, that would be amazing.

**Comment by mnquintana** [comment]
@roman01la It might be easier to start with some of Atom's bundled packages that provide a UI – [settings-view](https://github.com/atom/settings-view), for instance – and take a look at [the views](https://github.com/atom/settings-view/blob/master/lib/themes-panel.coffee#L16-L43) and see if they're accessible now or require changes (probably the latter). That won't make the core editor accessible, but I do think it's probably a simpler starting point.

**Comment by roman01la** [comment]
Ok, thanks for starting points, I'm going to take a look. Also, maybe it's a good idea to take a look at Eclipse IDE, to see how it behaves with SR, I think it's the most accessible IDE.
@nathansobo @mnquintana what do you think?

**Comment by nathansobo** [comment]
Yeah, looking at Eclipse for the overall user experience seems smart. But I'm not even sure how you do accessibility in web tech. So there's plenty to figure out. Thanks for taking interest!

**Comment by benbalter** [comment]
@nathansobo if the context is helpful, while "does it work with Voice Over" is often the definitive test, here's [what US law defines as "accessible"](https://government.github.com/accessibility/) in the context of GitHub.com and GitHub for Windows/Mac.

**Comment by roman01la** [comment]
@nathansobo Well, basically semantic markup and keyboard accessibility is a starting point, then ARIA — a solid bridge between web platform and assistive technologies. Also we need to take care of focus management (make interactive elements focusable).

**Comment by roman01la** [comment]
@benbalter AFAIK, Section 508 is a standard in US, and others use WCAG 2.0 to meet defined levels (A, AA, AAA), each one has a list of success criterias and includes requirements from previous levels.

**Comment by benbalter** [comment]
> Section 508 is a standard in US,

Of course. Hence the  `what US law defines as "accessible"` qualifier. I'm familiar with WCAG, but thought the GitHub-centric context might be helpful to the conversation.

**Comment by nathansobo** [comment]
We handle focus in a very standard way, so we're good on that front.

**Comment by roman01la** [comment]
@benbalter This is definitely helpful, thank you.

**Comment by acontreras89** [comment]
:+1: 
definitely want to help with this, too

**Comment by camlorn** [comment]
I was going to look at this, but then life happened.  At the moment, I no longer have the time.
Voiceover is not a useful test, in that Voiceover takes a very atypical and annoying approach.  It is possible to make Mac apps that are accessible without even handling focus properly, and the entire experience over there is basically the opposite of friendly to the type of user who would want to use Atom in the first place.  The short version is that a Voiceover user must explicitly navigate the tree of every view  in the hierarchy, even if it's inconsequential.  Web browsing with Voiceover is usually broken and slower than any of the alternatives at best.  The most useful target platform is Windows with NVDA: Windows because it's where all the blind programers are, and NVDA because it doesn't require paying large sums of money and is the most capable screen reader in terms of web browsing.
In terms of the procedure for making Atom accessible, the first step is determining if the web view that Atom uses is exposed properly.  I'm not up on the accessibility situation with Chrome and Chromium (I think this project is using Chromium, anyway), but if the web view doesn't expose anything (which is possible), there's at least a library upgrade and at most a great deal of work by someone who knows Microsoft Com and C++.  The googlable terms here are MSAA, IAccessible2, and User interface Automation; the one that is most applicable in my opinion if someone needed to work on fixing this part is IAccessible2.
After that, the answer is Aria.  Aria is, in most cases, easy.  The one difficulty is that Aria doesn't currently provide anything for rich edit controls.  Consequently, if the main textbox for entering code isn't actually an input element or similar, the screen reader won't be able to interact with it without some work.  Google Docs has solved this with a sub-par solution, but some of the bugs there are annoying and wouldn't actually make Atom something I'd want to use.  One possible option here is to check the screen reader flag, something which Windows at least provides.  The screen reader flag is set by running assistive technology and, if set, it might be possible to swap out any problematic controls for less problematic ones.
the good news is that, if the web view is exposed properly, the techniques for actually making most things accessible are already pretty well-known and well-documented.  This is most definitively not the case for the native app accessibility APIs, which also happen to generally be anywhere from 3 to 10 times more difficult to work with.  
If there are specific questions that need answering and which I can't answer, I do know a number of people who can provide information.

**Comment by paulcbetts** [comment]
> The only major issue here may be in Atom-shell: the web view has to be accessible in the first place. I know that Chrome has been seeing some improvements of late, but have never played with stand-alone webviews. The major concern is that they're not actually exposing Aria, in which case there may be nothing to be done without major work on Chromium.

Nobody answered this - Electron outputs information that at least is readable by NVDA, though if you have a High DPI display, it outputs incorrect information (i.e. if it is reading what is under the mouse cursor, it'll read the wrong point). Atom could make a lot of progress solely via standard Web Accessibility stuff.

**Comment by camlorn** [comment]
This comment kind of got disorganized, but I think the info in it is helpful anyway.  Sorry for that.
The standard tab stop focus methods apply when using tab, but screen readers maintain a "virtual buffer", a term with a somewhat imprecise definition.  It's still sometimes possible to properly activate stuff without focusing it, basically; the screen reader allows navigation of web pages in something usually referred to as browse mode, which makes it somewhat like navigating a word document with the keyboard (save that top-down in this case often means DOM order).  While we probably still need to support tab, getting at least this far will make it technically useable, possibly to the point where testing for more specific issues would be called for.
Chrome also used to have a lot of text editing and Aria bugs, but I've heard from one of the head developers of NVDA that many of these were fixed or being worked on, and that was some time ago.
Anyone who wants to test, though, is going to have to test with the keyboard; this probably means learning some of NVDA beyond tab, though I don't know how much.  Since Atom is probably a lot like a desktop app, tab might be enough.
I've just downloaded and installed atom, and I can see some of the stuff with object nav.  This is not consistent, nor something that applies in the general case of actually using the application.  The biggest immediate problem is that NVDA doesn't seem to recognize that the focus is anywhere, consequently it's not even properly picking up the web view and trying to use browse mode at all. I am nevertheless able to see quite a bit more of the UI than I would have expected (all be it by using the last resort of object nav, which is typically for debugging).
Unfortunately, the main text editing area is only visible with object nav and appears to be made up of multiple controls.  Anything short of an actual input element for code entry is going to require a whole lot of work, and I'm not sure that Aria even has anything in the pipeline for "properly" exposing editing.  If anyone can comment on what Atom is doing for the code editing control itself, I might be able to provide more info, but completely custom editing controls are currently one of the absolutely hardest things to make accessible on the web.
The mouse problems are probably a bug in the Chromium accessibility API, and I'd put them pretty far down the list personally.  It's not unimportant, but it's probably one  of the harder things to fix.  In terms of NVDA, keyboard use is more gainful than mouse use.

**Comment by parhamdoustdar** [comment]
I'm a blind programmer myself, and I haven't used an accessible code editor online ever. The problem is that these editors do not provide a value, and seem to have their value in the DOM outside of the text area. So, the text area itself is empty, and it is a DOM element that is being manipulated with whatever you're doing (e.g. navigating by characters/words, deleting, selecting, typing, etc).

So, even though I can access the text field with NVDA and type in it, navigating through the text doesn't tell me anything because the textarea itself seems to be empty.

**Comment by paulcbetts** [comment]
> The mouse problems are probably a bug in the Chromium accessibility API, and I'd put them pretty far down the list personally. It's not unimportant, but it's probably one of the harder things to fix. In terms of NVDA, keyboard use is more gainful than mouse use.

This is good to know, thanks

**Comment by cklatik** [comment]
I'm not familiar with the Atom roadmap, but what _is_ the prioritized work right now? This is an issue where all users utilizing assistive tech on all platforms cannot utilize Atom...It may not be the largest user base, but it's also not the smallest.

**Comment by benogle** [comment]
Right now, we're focused on the things in https://github.com/atom/atom/issues/7995

https://atom.io/roadmap

**Comment by sethlopezme** [comment]
Perhaps the [ATAG 2.0](http://www.w3.org/TR/ATAG20/) recommendation could help?

**Comment by camlorn** [comment]
That might, but the fundamental problem of not showing up to screen readers as a web view needs to be fixed first.  This is maybe nontrivial, but no one ever answered that question.
@jcsteh, can you help here?  You'd know better what that would entail than I would.

**Comment by parhamdoustdar** [comment]
ping @jcsteh.

**Comment by rbenson** [comment]
Just following up on this. [In much earlier comment](https://github.com/atom/atom/issues/1691#issuecomment-117844035), Section 508 was mentioned. This is a part of the Rehabilitation Act, it is applicable to working with the US Federal Government. Although it has been worked on for years, 508 will eventually adopt WCAG 2.0 straight up. When that happens, Atom would need to comply with ATAG, as @sethlopezme mentioned a year ago.

I know VS Code is decently accessible, so maybe you guys can barrow from there?

**Comment by camlorn** [comment]
I think that a great deal of this simply starts working if one updates and enables accessibility in Chrome.

While VSCode goes further, I've heard from a few people that this is what made the webview start working.  After that, someone has to figure out what approach needs to be taken with the code editing control and fix the menubars, but mostly it appears to just be annotations with Aria.

That said, whoever is in charge of this, please don't make the same mistakes the main GitHub site makes.  There is so much counterproductive misuse of aria on GitHub that we blind people have been complaining about for years, up to and including making Greasemonkey scripts that specifically removes it.

**Comment by craigbrett17** [comment]
Just stumbled across this as I'm on a new project work-wise and the default editor of choice was Atom. However, from reading this it looks like I wouldn't get anywhere trying to use Atom with NVDA. I'll stick to being the outlier and using Visual Studio. 

@camlorn makes good points re Chromium, there's a slew of accessibility niggles which has negatively impacted downstream dependent applications for years. I don't know what the optimum solution is, I'm not sure I'm up to the challenge of fixing Chromium, but I suspect that that's going to make your job harder. I'll be interested to see what solutions can be come up with for Atom. 

Visual Studio Code is still sub-optimum as an IDE for a blind user. I seem to recall it had trouble reading what was in the main text editor window. That might have changed now, I haven't checked it for some time. It was usable though, though nowhere near as efficient as the main Visual Studio product. The Mac version was completely unusable due to the aforementioned Voice Over intricacies. Which is a shame, as I have no IDE on Mac so I don't generally use it for development. 

I would suggest it's worth knowledge sharing with VS Code, at least on accessibility issues in Chromium as an editor.

**Comment by craigbrett17** [comment]
I should add, the fact that you guys are engaging in dialogue about fixing this is a promising sign. I could name and shame other editors and IDEs that have just essentially responded with "meh" or not responded at all when I've asked them to consider making their applications accessible.

**Comment by jcsteh** [comment]
Chromium a11y is improving in leaps and bounds now, and while there are definitely still issues to fix, it shouldn't be a major obstacle for Atom a11y now as far as I can see.

The incorrect mouse cursor coordinates with high DPI suggests that Atom is not a DPI aware application, in which case the screen coordinates Atom sees in its process will be logical, non-DPI aware coordinates. Chromium will just push these straight to the a11y client. Arguably, it's more a quirk of cross-process MSAA/IA2 rather than a bug in Chromium. In fact, if it did convert the coordinates, that would be incorrect for in-process clients. If there are any plans to make Atom a DPI aware application, that would fix this issue too.

**Comment by camlorn** [comment]
I've also heard that Visual Studio code works reasonably.  I tried it briefly, and most of the bugs I found with it are overuse of Aria live regions.  The one big one as far as Electron is concerned is that menu bars still don't work.  There's an issue somewhere, been open forever, but no one is fixing it and I don't have the expertise to do it quickly.

Electron itself could be at the point where I would choose to use it as a blind app developer very quickly nowadays.  If a few more things get fixed, it'll literally be the most accessible method to do desktop apps.  Admittedly you have to write focus handling in JS and know what you're doing with Aria application role, but it has *working tables* with a  bit of work on the app's side, and that's further than any of the other toolkits can take you.

**Comment by LJWatson** [comment]
VSCode is usable with a screen reader when you enable accessibility mode, but doing so means that basic features like word wrapping are not honoured. Line numbering is also not supported when you use a screen reader.

As @jcsteh noted, Chrome a11y is improving.

@camlorn to your question of how things are exposed to ATs like screen readers, the answer is via [platform accessibility APIs](https://www.smashingmagazine.com/2015/03/web-accessibility-with-accessibility-api/). For Chromium it's IAccessibility2.

**Comment by erikpro** [comment]
I am also very interested in improving accessibility on windows. especially with nvda.

**Comment by zersiax** [comment]
It is true that Visual Studio Code was essentially in the same position Atom still is in regards to not seeing any content in the editor. Upgrading the version of Elektron to at least 2.x seems to have fixed some of that, and they added a lot of accessibility-related fixes afterwards. It might be worth looking into how they performed these fixes.
An "Editor for the 21st Century" that "I can make my own" is certainly one I would expect to be accessible, especially since there's been an issue requesting exactly that for almost 5 years now. Can this critical UX bug be looked into?

**Comment by LexiconCode** [comment]
I currently work with open source voice to text such as [Dragonfly](https://github.com/dictation-toolbox/dragonfly) and [Caster](https://github.com/dictation-toolbox/caster/tree/develop) for computer accessibility and to code by voice.

We currently integrated into dragonflies API the ability to interface interface IAccessible2. This allows powerful commands such as selecting text by voice. Currently none of the major editors or IDE's have implemented IAccessible2. I'm hoping Atom will forge the way for programming accessibility.

**Comment by tayarndt** [comment]
Hi all,
I am new to the atom accessibility situation.I am a blind programmer who uses both windows and mac. What is the current status of accessibility? VS code has this accessibility mode where you press alt f1 and you are presented with a better view for screen readers. I am hoping we can get this accessible.
Thanks
Taylor

**Comment by tayarndt** [comment]
I want  to work on this project, because the more accessible options for editors the better.

**Comment by Neurrone** [comment]
@tayarndt the most practical solution is to learn how to use Vs Code, because it has received much more work in this area, and feedback from end-users.

**Comment by tayarndt** [comment]
That is fine, however VS code has some chromium bugs which make screen reader support interesting sometimes

**Comment by Neurrone** [comment]
@tayarndt could you elaborate, and have you reported them to the VS code issue tracker? Chances are that it is already a known limitation.

**Comment by camlorn** [comment]
It's also worth noting that VSCode took at least a year and an entire team to become accessible and that any Chromium bugs they face that aren't VSCode bugs will apply to Atom as well as anything else using Electron.  @neurrone is correct, the practical solution is to use VSCode unless you have enough money/time to fund/do this, a lot of expertise, and/or a way to make this issue high priority with whoever sets priorities.

**Comment by lee-dohm** [comment]
We agree that this is a significant problem and is something that should certainly be addressed. Unfortunately, we don't have the resources to tackle this, rather large, problem in the foreseeable future. Because of this, we don't feel that it is fair to leave this issue open and give the impression that it is something that we are looking into or will be working on soon.

If anyone is interested in working closely with us on this to build an accessibility infrastructure (not just screen readers) for Atom, we would love to hear from you. See the [SUPPORT doc](https://github.com/atom/atom/blob/master/SUPPORT.md) for information on how to contact us.

Thanks everyone for the feedback and information!

**Comment by esr360** [comment]
Why not leave the issue open in case someone else who isn't a core member decides to work on it? Either the issue is valid and unresolved, and hence should remain open, or the issue is invalid and should be closed. Closing a valid but unresolved issue does not seem to benefit anyone.

**Comment by jonathanlinat** [comment]
@lee-dohm You made a very bad decision closing this issue, You should leave it opened. There are developers with accessibility skills that can help to resolve those issues. I personally do and I'll be glad to help to resolve them.

**Comment by tayarndt** [comment]
Hi all,
I completely 100% agree with  Jonathan,  100%. Here is the thing, accessibility is an important issue. As more and more companies have inclusive products, it is time for the open source community to also. Jonathan I will help you with atom accessibility and I think that a slack channel  should be created for the people who are interested in atom accessibility development.  I don’t know, that is my 2 sense and hope it is valuable.

**Comment by tayarndt** [comment]
@jonathanlinat i will make a slack for the descussion I am so so happy people are on my side!!!

**Comment by ahangarha** [comment]
Closing this issue is shamful

**Comment by lee-dohm** [comment]
Thanks everyone for the candid feedback here and elsewhere.

The Atom maintainer team has been listening to what you've been saying and we've decided to reopen this issue. We realize that a number of people were upset by the team deciding to close the issue and we apologize for doing so. This isn't meant to indicate a change in our roadmap or when the maintainer team will be able to work on making Atom more supportive of accessibility technologies, just to reopen it to make it more searchable for the community to discuss and collaborate around.

We would also like to reiterate [the invitation for people to work closely with us](https://github.com/atom/atom/issues/1691#issuecomment-494562625) on creating an accessibility infrastructure. I've created an `#accessibility` channel in [the Atom community Slack team](https://discuss.atom.io/t/join-us-on-slack/16638) for those who would like to collaborate to make this happen. We look forward to people with interest or expertise helping to make this a reality.

We appreciate you sharing your thoughts and feelings with us on this.
