### ISSUE TITLE
Syntax Highlighting not works with files larger than 2 MB

### ISSUE THREAD

**Issue by KTSamy** [atom/atom#16916]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Syntax Highlighting not works with files larger than 2 MB

### Steps to Reproduce

1. Open file "Sample_under_2MB.c"
2. Syntax highlighting will work as expected
3. Open file "Sample_under_2MB.c"  (Just one line more than previous one)
4. Syntax highlighting won't work

**Expected behavior:** Syntax highlighting should work on larger files too

**Actual behavior:** Syntax highlighting not works
**Reproduces how often:** 100%
### Versions

Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm 1.18.12
npm 3.10.10
node 6.9.5 x64
atom 1.24.1
python 3.6.4
git 2.14.3

**Host OS: Mac OS high sierra**

### Additional Information
[Sample_above_2MB.c.zip](https://github.com/atom/atom/files/1797301/Sample_above_2MB.c.zip)
[Sample_under_2MB.c.zip](https://github.com/atom/atom/files/1797302/Sample_under_2MB.c.zip)

**Comment by rsese** [comment]
Thanks for reaching out and for the detailed report - this is currently expected behavior, see https://github.com/atom/atom/issues/11232#issuecomment-336731653 for example.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by Ben3eeE** [comment]
tree-sitter will make us able to apply syntax-highlighting to larger files, though we are not sure what the limit is yet. It's currently available on beta through an experimental configuration option if you want to give it a spin.
