### ISSUE TITLE
"Restore Previous Windows on Start" (NO) option is not effective when the atom is opened by drag on drop OR by open with context menu

### ISSUE THREAD

**Issue by KTSamy** [atom/atom#16917]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

"Restore Previous Windows on Start" (NO) option is not effective when the atom is opened by drag on drop OR by open with context menu

### Steps to Reproduce

1. Open any file & Close the atom by the main close button on the window (not by tab close)
2. Drag on drop a new file or Open a new file from context menu

**Expected behavior:** The previous windows shouldn't be restored

**Actual behavior:** The previous windows are restored

**Reproduces how often:** 100%

### Versions

Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.1
python 3.6.4
git 2.14.3

### Additional Information

**Host: Mac OS High Sierra**

**Comment by rsese** [comment]
Thanks for this report too, this was asked before in https://github.com/atom/atom/issues/15452.   See my comment for more details /cc https://github.com/atom/atom/issues/15452#issuecomment-325504896.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
