### ISSUE TITLE
Add me to atom GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [atom/atom#16929]
Hey,

I am really excited about the active development and wanted to be a part of the **atom** organization on GitHub. In this regard, how can I become a member and would love if somebody would add me to it?

My GitHub username is YoginthS

Thanks, Yoginth

**Comment by Arcanemagus** [comment]
Thanks for your interest in helping out!

We have a guide on contributing to the project [here](https://github.com/atom/atom/blob/master/CONTRIBUTING.md), of particular interest is the [How Can I Contribute?](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute) section. 😉

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
