### ISSUE TITLE
Problem installing clone copy of markdown-preview package

### ISSUE THREAD

**Issue by jfsturtz** [atom/atom#16954]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

First, a disclaimer:  I'm pretty new to atom, so please forgive me if I commit any faux pas.  My problem specifically involves trying to load an installed package from a link in ~/.atom/packages, so I think some of the Prerequisites above are not applicable (e.g., running in Safe Mode, which would clearly bypass the problem).  I checked the box because I think I did all of them I can do.

I am working on a project using Markdown, but the project has some custom syntax.  I wished to hack the markdown-preview package to grok and correctly render the custom elements.  So I did the following:

- Obtained a clone copy (markdown-preview-master.zip) from GitHub.
- Installed (`apm install` from Windows Admin PowerShell)
- Linked to ~/.atom/packages (`apm link`)

All went well; atom seemed to pick up the package, which showed up under Settings->Packages as an installed Community Package.

Then I went and found the place in the source code where the Markdown is rendered to HTML, hacked it to my purposes, and everything was working great.

Until about two hours ago, at which time I started getting the following message when trying to load my clone copy:

**Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.**

It looks like it tried to rebuild the package, which evidently failed.  Error messages are:

```
gyp ERR! clean error 
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\john\.atom\packages\markdown-preview\node_modules\oniguruma\build\Release\onig_scanner.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\john\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\john\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\john\.atom\packages\markdown-preview\node_modules\oniguruma
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\john\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\john\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\john\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\john\\.atom\\.apmrc" "rebuild" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\john\.atom\packages\markdown-preview\npm-debug.log
```

### Steps to Reproduce

At this point, all I need to do to reproduce is start atom.  If I remove my clone copy of the package, atom starts up and loads the Core markdown-preview just fine, and it works.

I have tried re-installing the clone copy:

- Unlink (`apm unlink`)
- Delete entire folder structure where the clone copy of the package resides
- Then install exactly as I did originally:
  - Obtain package zip from GitHub and unzip
  - `apm install`
  - `apm link`

But even the fresh copy (that I have not hacked) will no longer load; I always get the same message.

**Expected behavior:** That the clone copy of markdown-preview will install, as it did a few days ago

**Actual behavior:** It won't

**Reproduces how often:** Always

### Versions

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.14
git
visual studio 2015

Windows 10 Home
Version 1709
OS Build 16299.248

Thanks.  I sure hope someone can help; this was working great, and I'd dearly like to have it back.

/John

**Comment by lee-dohm** [comment]
Thanks for the detailed report.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

----

Given all of the above, the way that you created a copy of the markdown-preview package is rather unorthodox. The way we would typically recommend you do something like this would be to [fork the markdown-preview repo](https://help.github.com/articles/fork-a-repo/), update some of the information in the `package.json` to differentiate your package from ours (maybe name it `mostly-markdown-preview`? :grinning:), then clone your repo to your local machine somewhere other than under the `~/.atom` directory, and finally run `apm link` and `apm install` as you did.

Given the error message:

> Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

mostly what needs to happen is you can:

1. Completely exit Atom
1. Execute `apm rebuild` in your local repository
1. Launch Atom again

If neither of those recommendations work, please check out the resources I mentioned above and someone will be able to help you.

Thanks again.
