### ISSUE TITLE
How to uninstall Atom text editor on Windows from "atom-windows.zip"?

### ISSUE THREAD

**Issue by ruanfeixiong** [atom/atom#16988]
How to uninstall Atom text editor on Windows from "atom-windows.zip"?

**Comment by lee-dohm** [comment]
Check out this topic on the [Official Atom forum](https://discuss.atom.io):

https://discuss.atom.io/t/how-to-completely-uninstall-atom-from-windows/17338/6

Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
