### ISSUE TITLE
Autoindent fails when there's a comment with a single or double quote

### ISSUE THREAD

**Issue by StructByLightning** [atom/atom#16990]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

I didn't do a comprehensive search the Atom packages, but I don't think it should be necessary to install a package to fix something broken.

### Description

Autoindent fails when there's a comment containing a single or double quote

### Steps to Reproduce

Copy this into a JS file, select all, go to Edit > Lines > Auto Indent. I can also press CTRL-I to autoindent, but I think that's a custom shortcut.

```
var removeNode = function(){
if (1 == 1){ //'
if (1 == 1){
var example = 5
}
}
};
```

**Expected behavior:**
```
var removeNode = function(){
  if (1 == 1){ //'
    if (1 == 1){
      var example = 5
    }
  }
};
```

**Actual behavior:** 
```
var removeNode = function(){
  if (1 == 1){ //'
  if (1 == 1){
    var example = 5
  }
}
};
```

**Reproduces how often:** 
Always. It works with a double quote too, and it doesn't matter if there's text before the quote or after it. Other characters might cause the bug too but I haven't tested them.

### Versions
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

Ubuntu 17.10

### Additional Information
Autoindent works if the comment is on it's own line:
```
var removeNode = function(){
//''
if (1 == 1){ //
if (1 == 1){
var example = 5
}
}
};
```

**Comment by rsese** [comment]
Thanks for contributing!

Looks like this was reported in https://github.com/atom/language-javascript/issues/560 so we'll go ahead and close as a duplicate.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
