### ISSUE TITLE
Issue: Atom v1.25 does not launch Hydrogen

### ISSUE THREAD

**Issue by dsanalytics** [atom/atom#16992]
I updated from Atom v1.23.3 to v1.25 and hydrogen no longer works.

Process: Originally, downloaded windows 64bit zip (v1.23.3), unzipped it and copied all files in c:\tools\atom - all has been well and been using atom for some time. Update followed the same process - download windows 64 bit v1.25 zip, unzip, overwrite all in c:\tools\atom. Atom opened properly, but executing a file with hydrogen, that worked before did not work - even trying to run it from the menu no longer works. No errors. That little window 'hydrogen kernels updated' does not show up. Deleted all v1.25 files and unzipped v1.23.3 from before back - ran it and all works just fine. Not sure what other packages are broken with v1.25.

I noticed that new atom has many more files compared to 1.23 - there are some new dlls in atom.exe directory, etc. Perhaps packing the zip was not done properly?

OS: Windows 10 64bit Home Premium
Atom: 1.23.3 (original working)
Atom 1.25 (broken hydrogen)
Hydrogen 2.3.0

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [hydrogen](https://atom.io/packages/hydrogen) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
