### ISSUE TITLE
Uninstall a packages not really uninstall?

### ISSUE THREAD

**Issue by Daijobou** [atom/atom#17004]
I have uninstalled a package (Symbols Tree View) and later I want tried it again and installed it, but now I see all custom settings for this before uninstalled package are restored. Maybe that not a issue.

But when a package make problems and uninstalled it, what is here "uninstalled"? Should not all removed from atom?

**Comment by lee-dohm** [comment]
It is expected that the configuration for a package is saved in case you decide to install it again. When you uninstall a package, it is deleted from your system.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
