### ISSUE TITLE
Use xattr (extended attributes) on macOS to save/load text encoding with file

### ISSUE THREAD

**Issue by gingerbeardman** [atom/atom#17006]
# Proposal
Use xattr (extended attributes) on macOS to save/load text encoding with file.

> BBEdit is the only editor I've found that already does this.

Also Atom should honour any existing `com.apple.TextEncoding` and keep it when saving.

Currently the value is ignored and the encoding is guessed, often incorrectly, by looking at the contents of the file.

## Background
- Text Encoding has to either be set manually, or guessed by scanning the file.
- Both of these tasks take time.

## Benefits
- loading time can be reduced
- text encoding can be more persistent
- can still be changed and rewritten at any point

### Details
debug command:
`xattr -p -l com.apple.TextEncoding "/path/to/file.txt"`

output:
`file.txt`
`com.apple.TextEncoding: Shift_JIS;2561`

to set xattr (from terminal):
`xattr -w com.apple.TextEncoding "Shift_JIS;2561" "/path/to/file.txt"`

### References

these may help with implementation:
- node: https://github.com/LinusU/fs-xattr
- python: https://github.com/xattr/xattr
- obj-c: https://stackoverflow.com/questions/10374580/
- swift: https://github.com/okla/swift-xattr
- obj-c & swift (alt): https://developer.apple.com/library/content/qa/qa1719/_index.html

**Comment by lee-dohm** [comment]
This isn't something that we want to take on since file attributes like this aren't supported cross-platform and may not even be saved when a file is stored in a Git repo. This makes them of limited utility. On the other hand, we can see how this would be a useful feature to have in certain shops, workflows or situations, so we would be willing to review a well-written pull request that adds the feature. Adding `help-wanted` so this can be found by people wishing to do so.

Thanks for the feedback and ideas!

**Comment by gingerbeardman** [comment]
I've moved to VS Code. Best of luck with Atom
