### ISSUE TITLE
Cannot open Atom from command line, cmd.exe: command not found

### ISSUE THREAD

**Issue by adnammit** [atom/atom#17034]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Typing `atom` from the command line does not open any file or directory and instead produces an error that `cmd.exe` cannot be found. Atom operates normally and as expected when I open it from the taskbar and open files/projects from within Atom.

### Steps to Reproduce

1. Install (or uninstall and reinstall) Atom via AtomSetup.exe
2. check $PATH to ensure `atom/bin` is included
3. use `atom` command from the command line to open a file or directory

**Expected behavior:** 
Atom opens with the selected file or directory. Yay!

**Actual behavior:** 
```
/cygdrive/c/Users/<username>/AppData/Local/atom/bin/../app-1.25.0/resources/cli/atom.sh: line 21: cmd.exe: command not found
```
Sad. 

**Reproduces how often:**
Always.

### Versions
Atom v1.25.0
Windows 10 using Cygwin/mntty

### Additional Information
```
$ which atom
/cygdrive/c/Users/<username>/AppData/Local/atom/bin/atom
$ which apm
/cygdrive/c/Users/<username>/AppData/Local/atom/bin/apm
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/home/<username>/bin:/cygdrive/c/Users/<username>/AppData/Local/atom/bin:/cygdrive/c/Program Files/nodejs/:/cygdrive/c/Users/<username>/AppData/Roaming/npm/
```
Other things I tried include running `$ ./atom.exe --squirrel-install` from `cygdrive/c/Users/<username>/AppData/Local/atom` (which did not error nor report anything back), uninstalling and reinstalling Atom a couple of times and restarting my computer.

I've pored through other issues online and it appears that perhaps there needs to be a symlink in `usr/local/bin` but none of the suggested targets exist in my environment.

Thanks in advance!

**Comment by Arcanemagus** [comment]
It looks like you've modified your `$PATH` to remove the Microsoft core paths... including the one that specifies where `cmd.exe` is located. If you fix that things should start working again.

FOr reference, this is being called here:
https://github.com/atom/atom/blob/cc0224a335a996095c693eebd78be50004a8924e/resources/win/atom.sh#L18-L22

**Comment by Arcanemagus** [comment]
@adnammit Fixing your `$PATH` problem as described above should solve this for you. If you are still having any problems after fixing that feel free to comment further and we will try to help out further.

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by adnammit** [comment]
Ah gotcha -- after a bit of follow-up research on your instruction I figured it out. 
Thank you! 🙌
