### ISSUE TITLE
Atom consistently crashes when trying to expand any snippet on line 2044 of this file

### ISSUE THREAD

**Issue by ensigma96** [atom/atom#17035]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom 1.25.0 consistently crashes when trying to expand any snippet on certain lines of some files.

### Steps to Reproduce

1. Compose a text file with 2042 lines of `test`, followed by 2 blank lines and then a line of `test` (2045 lines in total). 
    The last line is optional, just to prevent Atom from removing the trailing blank lines.
2. Open the file with Atom and select any language (e.g. C)
3. Move cursur to line 2044; type anything that can trigger a snippet (e.g. `inc` to trigger `#include ".h"`)
4. "The editor has crashed"!

**Expected behavior:** Snippets get expanded normally

**Actual behavior:** Atom crashes

**Reproduces how often:** 100%

### Versions

Atom    : 1.25.0
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1

### Additional Information

The file: [test.txt](https://github.com/atom/atom/files/1850353/test.txt)
Distro: Arch Linux

**Comment by githubSathishkumar** [comment]
I'm too facing the crashing problem  in Atom 1.25.0. Many times, when I working on other application, popup raised and says `Atom crashed.`

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by eli-schwartz** [comment]
https://bugs.archlinux.org/task/57991

Caused by https://github.com/atom/superstring/issues/57 so our distro build is fixed now. :)
