### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by byrjx** [atom/atom#17043]
OS Version :MAC OS X10.13
ATOM Version: 1.25.0x64
bug :run atom about a hour ,he  is  Accidental withdrawal when i  edit file
i think it  can't  exit ,so  it's bug

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
