### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 65, Calling function FileSystemService/find...

### ISSUE THREAD

**Issue by Nishith** [atom/atom#17048]
1. Tried adding a remote folder
2. Entered the ssh password in the connection dialog
3. Selected push notification, approved from a different device
4. Atom opened a blank window with a certificate expired message in a box asking me to reload Atom
5. Reloaded Atom, went through steps 1 - 4 multiple times
6. Got this error

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 65, Calling function FileSystemService/findNearestAncestorNamed.

```
At /opt/facebook/nuclide/0.290.98502521/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

RpcTimeoutError: Timeout after 60000 for id: 65, Calling function FileSystemService/findNearestAncestorNamed.
    at Call._timeout (/opt/facebook/nuclide/0.290.98502521/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/opt/facebook/nuclide/0.290.98502521/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
```

### Commands

```
     -1:05.8.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-close.has-buttons)
  2x -0:37 nuclide-remote-projects:connect (atom-pane.pane)
```

### Non-Core Packages

```
file-icons 2.1.18 
haskell-ghc-mod 2.2.3 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
ide-haskell 2.3.1 
ide-haskell-hasktags 0.0.14 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.8.0 
language-babel 2.84.0 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.291.99692496 
nuclide-format-js 0.0.45 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
