### ISSUE TITLE
Tree view font size not increasing

### ISSUE THREAD

**Issue by MrShakes** [atom/atom#17044]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode 
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/ 
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Trying to increase the small size of the tree view thats really hurting my eyes, I tried implementing issue #2530 by putting code in `./atom/styles.less` however this did not work as seen below

![screen shot 2018-03-28 at 15 32 03](https://user-images.githubusercontent.com/12875016/38035898-55d09ecc-329d-11e8-96ad-19463ca34ea0.png)

### Steps to Reproduce

1. Open atom, create the file and insert code
```
@font-size: 14px;
html, body, .tree-view, .tab-bar .tab {
  font-size: @font-size;
}
```
**Expected behavior:** Increase tree view font size

**Actual behavior:** Nothing happens

**Reproduces how often:** 100%

### Versions
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.15.1
Mac OS High Sierra version 10.13.2

### Additional Information
None

**Comment by rsese** [comment]
Thanks for reaching out!  It looks like you added a `.atom` directory to your project?  The styles changes should go in your `~/.atom/styles.less` which is off of your home directory.   You can also access it from the `Atom > Stylesheet...` menu item.

It looks like you're using the `Atom Dark` UI theme from your screenshot - if you wanted to try the `One Dark` theme, there's a `Settings > Themes > one-dark-ui > Font Size` setting that lets you change the UI size in that setting.

Going to go ahead and close this as mentioned below - the best place to ask questions and ask for support are the message board and the Atom Slack so feel free to reach out there if you still have trouble.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions or asking for support since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
