### ISSUE TITLE
Restore Previous Windows On Start Behavior?

### ISSUE THREAD

**Issue by tonykaram1993** [atom/atom#17052]
Setting in question is: File>Settings>Core>Restore Previous Windows On Start

First let's open a few files on atom, let's say we opened: banana.txt, apple.txt, and watermelon.txt. Then we close atome.

- If option is set to **NO**: next time atom is launched, everything is blank. If someotherfile.txt is opened via atom, that file will be shown.
- If option is set to **YES**: next time atom is launched, everything is the way it was when atom was closed (banana.txt, apple.txt, and watermelon.txt are shown). If someotherfile.txt is opened via atom, that file will be shown.
-If option is set to **ALWAYS**: next time atom is launched, everything is the way it was when atom was closed (banana.txt, apple.txt, and watermelon.txt are shown). **THIS IS WHERE THIS HAPPENS**. If someotherfile.txt is opened via atom, **TWO** instances of atom are launched, the first containing whatever atom had open when it was last closed, and the second contains someotherfile.txt.

What I normally expect to happen is to open whatever was opened last time atom was closed (banana.txt, apple.txt, and watermelon.txt are shown) and add a new file/tab for the file that was opened (in this situation someotherfile.txt).

Hope I am right about this and that I did not get things messed up. I don't think this is how it's supposed to be right?

**Comment by rsese** [comment]
Thanks for reaching out - yes this is expected behavior, see this comment from the pull request that implemented the `always` option:

https://github.com/atom/atom/pull/13947#issuecomment-285791322.

Though it's expected behavior, we understand that Atom's startup can be confusing in some cases so also see #10517, a high level issue about the different ways you can start Atom.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
