### ISSUE TITLE
the atom has crashed!

### ISSUE THREAD

**Issue by 1453921760** [atom/atom#17059]
Thought I download it again, I does not work!
![7se5_kd8yxyvb3 jja6bbbn](https://user-images.githubusercontent.com/34571148/38161183-91a248fe-34fc-11e8-87fc-a783f6511811.png)

**Comment by MagicMarvMan** [comment]
Please provide more information, e.g. steps to reproduce, OS and more!

**Comment by 1453921760** [comment]
it's Windows. When I open the atom, it crashed.

**Comment by 1453921760** [comment]
I has already installed the Anaconda before I open the atom. Is there some conflicts?

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
