### ISSUE TITLE
Freezes when creating tab in a line comment.

### ISSUE THREAD

**Issue by chapmanethan** [atom/atom#17061]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom continually crashes when I press `tab` key in a comment. I've checked in both `python` and `javascript`; both caused atom to crash.

### Steps to Reproduce
* I've tested in both python and in javascript, but the syntax is generally the same.

* Python:
```
# comment
# comment 2


code
```

* Javascript:
```
// comment
//    comment 2


code
```

* With my cursor on the line above `code` ( line 4 ), I create a comment ( ctrl+/ ), then press the `tab` key, and atom freezes. 

**Expected behavior:**
* Create a new tab.

**Actual behavior:** 
* Atom freezes.

**Reproduces how often:**
* Every time I've tried, in both Python and Javascript.

### Versions

* `atom --version`
```
Atom    : 1.25.0
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1
```

* `apm --version`
```
apm  1.19.0
npm  5.7.1
node 9.10.0 x64
atom 1.25.0
python 2.7.14
git 2.16.3
```

* `hostnamectl`
```
  Operating System: Arch Linux
            Kernel: Linux 4.15.13-1-ARCH
      Architecture: x86-64
```

### Additional Information

* The problem persists when I used `atom --safe`.
* I think that `autocomplete` might be the cause of the problem, because this is what `htop` looks like after atom freezes:
![screenshot from 2018-03-31 13-44-22](https://user-images.githubusercontent.com/22640001/38167008-337a690c-34eb-11e8-932b-4e0f313dd2b5.png)

**Comment by Arcanemagus** [comment]
[`autocomplete-python`](https://atom.io/packages/autocomplete-python) is a 3rd party package, which wouldn't be in effect when running Atom in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode). Could you verify that you are able to reproduce this when you close _all_ instances of Atom, then launch it in Safe Mode?

**Comment by chapmanethan** [comment]
I rebooted my system and started up Atom with `$ atom --safe`.
The `autocomplete-python` thing seemed to be an anomaly, as it was nowhere to be found in my latest reproductions of the problem.
However, the freezing problem persists still.
Right as it freezes I'm shown a coredump in `htop`.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
