### ISSUE TITLE
How can I add DevTools extensions to Atom?

### ISSUE THREAD

**Issue by PoignardAzur** [atom/atom#17067]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I would like to be able to use devtools extensions like [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) to Atom in dev mode. How can I do that?

The official Electron documentation mentions [a way to load devtools extensions in an Electron window](https://electronjs.org/docs/tutorial/devtools-extension), but I haven't been able to apply it to Atom.

I've tried variations of the following code in the init.coffee script of my .atom folder, but they all fail with some variant of "This method you're trying to access doesn't exist".
```
# Your init script
#

BrowserWindow = require('electron').remote.BrowserWindow
BrowserWindow.addDevToolsExtension("~/.config/chromium/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/3.2.1_0/")
```

Which leads me to think I'm missing something. Is there a way to load devtools extensions from init.coffee, or should I try so other method? Either way, which is the simplest way to proceed?

---

Secondary question: I've also found [this npm package](https://github.com/MarshallOfSound/electron-devtools-installer) that provides a simplified way to load devtools extensions in Electron. Is it possible at all to use it in Atom? I don't think you can add node modules to init.coffee.

### Versions

Atom : 1.23.3
Electron: 1.6.15
Chrome : 56.0.2924.87
Node : 7.4.0

**Comment by lee-dohm** [comment]
You may want to see how [Devtron injects itself](https://github.com/atom/atom/pull/11750/files) since that works in Atom.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
