### ISSUE TITLE
atom is using tabs instead of spaces

### ISSUE THREAD

**Issue by kkasra12** [atom/atom#17068]
i have installed 1.26.0-beta0 on my mint and the application is using tabs instead of spaces for indentations.
and i have checked the  `soft tabs` in the settings.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
