### ISSUE TITLE
Editor crashing continously

### ISSUE THREAD

**Issue by PhotonSphere** [atom/atom#17075]
Installed Atom for windows 10 and using it to for python, installed few packages. The program has been crashing continuously, a total of 6 crashes occurred in the span of 1 hour.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
