### ISSUE TITLE
Duplicate file type icons when switching themes

### ISSUE THREAD

**Issue by 8ctopotamus** [atom/atom#17072]
The file type icons in my sidebar are showing double after changing from the Bliss-UI theme to Seti-UI.

How do I go about fixing this? I tried uninstalling Bliss-ui, but that didn't help.

![screenshot- 368](https://user-images.githubusercontent.com/17594101/38263739-7b30f03e-3736-11e8-821b-c45b41e74f2b.jpg)

**Comment by lee-dohm** [comment]
Thank you for reaching out!

It appears that this is being caused by the [seti-ui theme](https://atom.io/packages/seti-ui), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
