### ISSUE TITLE
using back ticks and having // breaks syntax highlighting

### ISSUE THREAD

**Issue by matt3224** [atom/atom#17078]
<img width="1125" alt="screen shot 2018-04-04 at 20 06 06" src="https://user-images.githubusercontent.com/2401925/38329066-9200bd9e-3844-11e8-960e-e6c84a324c83.png">

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by Arcanemagus** [comment]
I did a little bit of research assuming a few things about your setup:

* You are on the latest version of Atom
* You have enabled Tree-sitter parsers

Which leads to this being a duplicate of https://github.com/tree-sitter/tree-sitter-javascript/issues/67. You can disable usage of the experimental Tree-sitter parsers to use the current TextMate based parser which handles that text correctly 😉.

**Comment by matt3224** [comment]
Cool thanks, the issue template was missing for me so i simply uploaded what i was seeing, thanks for finding the corresponding issue
