### ISSUE TITLE
Autosave causes crash requiring force close. Re-opening shows entire file contents deleted and unrecoverable.

### ISSUE THREAD

**Issue by ocssor** [atom/atom#17077]
### Description

When having the Autosave package active, sometimes tabbing out of a window / causing it to lose focus causes it to crash. You can 'keep waiting' for as long as you like but it will never recover, requiring a force close. Once you force close, re-opening the file shows the entire contents deleted and are unrecoverable. Obviously this is a somewhat major issue, because if you haven't staged or committed changes since the last time you saved the file, there's no way to get the contents back.

### Steps to Reproduce

1. Have autosave active on navigating out of Atom
2. Edit files - there seems to be no pattern to what files decide to crash.

**Expected behavior:** No crash to happen or the data able to be recovered.

**Actual behavior:** Tab crashes forcing an autoclose and upon reentry a loss of data

**Reproduces how often:** Since the most recent update (1.25.0), it has happened 5 times in 3 days.

### Versions

1.25.0

### Additional Information

OSX Sierra 10.12.6 (16G29)

**Comment by lee-dohm** [comment]
Thank you for contributing!

Have you been able to reproduce this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
