### ISSUE TITLE
text fields not showing typed characters 

### ISSUE THREAD

**Issue by bidva** [atom/atom#17084]
this is a fresh installation of atom (v 1.25.1 x64) and all my text fields not showing the values . I made a snap shot of these fields and all of those has value but they are invisible. 

![screen shot 2018-04-05 at 9 28 32 am](https://user-images.githubusercontent.com/8351624/38378999-36665348-38b4-11e8-95d5-5b05a51439d2.png)
![screen shot 2018-04-05 at 9 33 31 am](https://user-images.githubusercontent.com/8351624/38379064-6e82b316-38b4-11e8-8b97-607baee0fd54.png)

![screen shot 2018-04-05 at 9 30 31 am](https://user-images.githubusercontent.com/8351624/38379008-3e692b88-38b4-11e8-901c-6f00d0e32e41.png)

**Comment by lee-dohm** [comment]
Thank you for contributing!

I cannot reproduce this using Atom v1.25.1 on Mac OS X 10.13.4. Have you tried reproducing this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
