### ISSUE TITLE
Files deleted outside atom: have an alert to choose if we want to keep the file or delete it (like notepad++)

### ISSUE THREAD

**Issue by EnoraNedelec** [atom/atom#17085]
I am sorry to open a new issue for this, I wanted to comment on this [issue](https://github.com/atom/atom/issues/5394) but it has been closed just 2 days ago.  

It's nice that we have the option to "Close Deleted File Tabs" but it would even be better if we could keep the deleted file in a tab and get get an alert asking "this file has been deleted, would you like to keep it?".  This would allow us to have a per file choice, not a general choice. 

If the feature I propose isn't clear, Notepad++ has such an [option](https://imgur.com/a/c1Gmk). 

Atom: 1.25.1

**Comment by lee-dohm** [comment]
I agree that this would be a nice feature. This isn't something that the Atom maintainer team is going to devote time to working on, however. We would be willing to review a well-written pull request, however. Because of this, I'm going to mark this as `help-wanted` so that people can find your idea more easily.

Thanks for the feedback :+1:
