### ISSUE TITLE
Atom launches with white screen

### ISSUE THREAD

**Issue by apollofernandes** [atom/atom#17098]
When I try to open up atom editor, it shows a blank white screen. I can't edit any files or do anything. What is happening? Screenshot below:
![help needed](https://user-images.githubusercontent.com/20287746/38460103-6cb7575c-3a81-11e8-8801-1b22f47cf76e.png)

**Comment by rsese** [comment]
Thanks for the report - can you share more information about the issue? In particular, the issue template information is really helpful and if you can add more details we can go from there:

* Can you reproduce in safe mode (atom --safe)?  
* Have you tried any of the other [debugging suggestions](https://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* What version of Atom are you running (`atom -v`)?
* What operating system are you running?

If you can share the above details, we can re-open and go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
