### ISSUE TITLE
White screen when opening atom

### ISSUE THREAD

**Issue by j24507** [atom/atom#17101]
I cant use atom, when I try to open the program it appears this:

![image](https://user-images.githubusercontent.com/25712344/38472104-f138d39e-3b48-11e8-96ff-fd34ec626e83.png)

**Comment by rsese** [comment]
Thanks for the report - can you click on the red exclamation point shown in your screenshot and share the error that you see?

Also, can you share more information about the issue? In particular, the issue template information is really helpful and if you can add more details we can go from there:

* Can you reproduce in safe mode (atom --safe)?  
* Have you tried any of the other [debugging suggestions](https://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* What version of Atom are you running (`atom -v`)?
* What operating system are you running?

If you can share the above details, we can re-open and go from there.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by j24507** [comment]
Hello, sorry for the delay, I uninstalled atom a reinstalled again and I have the same issue, here it is the requested information:

![image](https://user-images.githubusercontent.com/25712344/38809341-30db6774-4151-11e8-9850-eb37b37bc2ec.png)

I'm running atom on windows 10.

**Comment by rsese** [comment]
Thanks - go ahead and remove your `~/.atom/compile-cache` folder and try again.  For you that will be at `C:\Users\YOUR_USERNAME\.atom\compile-cache\`.

**Comment by j24507** [comment]
I did what you said and it worked, thanks!!
