### ISSUE TITLE
"Show in explorer" doesn't use third party file browser.

### ISSUE THREAD

**Issue by MargiaviciusK** [atom/atom#17103]
Win10. I use Directory Opus and have it set as the default file browser. "Show in explorer" opens the default OS browser. Is it possible to use a different program?

**Comment by rsese** [comment]
Thanks for reaching out!  Based on https://github.com/atom/tree-view/pull/889, it looks like this isn't possible at the moment on Windows.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
