### ISSUE TITLE
Still: Atom does not start after running once as root due permission of /tmp/atom-nohup.out

### ISSUE THREAD

**Issue by BenjaminFiebig** [atom/atom#17114]
### Description

Atom does no longer start after it has been run by root or probably any other user with a restrictive umask. This is because the atom.sh script pipes out the output to the same shared file /tmp/atom-nohup.out
Was already reported in https://github.com/atom/atom/issues/3056. Issue was closed but problem wasn't solved. It's still reproducible in 1.25.1

### Steps to Reproduce

Run

 $ sudo su - root -c atom
 $ atom
 /usr/bin/atom: Zeile 84: /tmp/atom-nohup.out: Keine Berechtigung

The second call fails because nohup cannot write/access the file. This might work if root has a very permissive umask.

### Versions

1.25.1

**Comment by rsese** [comment]
Thanks for the report - I'm unable to reproduce on Ubuntu 16.04 with Atom 1.25.1.  

 I see https://github.com/atom/atom/issues/3056 was closed after https://github.com/atom/atom/commit/54ce852be495d077f100d20331a5328814da454d which looks like it specifically creates `nohup.out` in your Atom home directory rather than in `/tmp`?

Also, can you share all the information asked for in the issue template?  E.g. what's the full output of `atom -v` and what operating system are you running?

And have you installed Atom with an officially supported install method?

https://flight-manual.atom.io/getting-started/sections/installing-atom/

**Comment by BenjaminFiebig** [comment]
First time I downloaded it as .deb from atom.io and it was working. After I used it from terminal by "sudo atom <file>", I couldn't start it without sudo anymore. Atom started but looked like this:
![screenshot_2018-04-16](https://user-images.githubusercontent.com/38278740/38797377-8a61daf0-415e-11e8-8d81-cdcd0c7f9481.png)

I'm not an Linux expert, so I just tried some hints to fix it: chmod on /tmp/atom-nohup.out, deinstall with apt-get (was throwing errors...), deinstall and reinstall with "software", chown on ~/.atom dir from root to user. Last one fixed it for my local user, but I can't open "sudo atom" anymore (message: Command not found).

I will try to make it work again for root and check if I can reproduce it. But it's annoying for me... I used atom for long time on Mac (also with sudo) and it worked perfectly there.
