### ISSUE TITLE
cannot get active text editor when run spec

### ISSUE THREAD

**Issue by jianhuafan** [atom/atom#17117]
I am currently developing a atom package, and are working on writing test for it using spec. When run spect.js file, atom will open a new panel without any pane or text editor, so if my package use atom.workspace.getActiveTextEditor().getPath(), it won't work because there is no text editor or pane. Is there any solution about this?

**Comment by lee-dohm** [comment]
Yes, you have to instruct Atom to open a text editor before you can get the active one. Check the specs in the [whitespace package](https://github.com/atom/whitespace) for examples.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
