### ISSUE TITLE
atom doesn't install

### ISSUE THREAD

**Issue by Indritindrit** [atom/atom#17118]
Hello,
I am experiencing problems installing atom.
I am using Windows 7  x64. There seems to be a lot of discussions about this problem but I am still not able to find a solution.
Downloaded atom from official site and run it.
Asked for permission:

![1d](https://user-images.githubusercontent.com/38316379/38670705-d8599bac-3e49-11e8-89b7-58b6ad47dd6c.PNG)
Then the update problem:
![2d](https://user-images.githubusercontent.com/38316379/38670745-f073a9bc-3e49-11e8-8b87-8a103505c42f.PNG)
and failed to install
![3d](https://user-images.githubusercontent.com/38316379/38670751-f77d27f6-3e49-11e8-8eb7-9b5c5a194315.PNG)
When I tried it for the second time asked for my permission TWO times 
![1](https://user-images.githubusercontent.com/38316379/38670764-fc9abc1c-3e49-11e8-9e98-aa527bc63a9c.PNG)
I didnt run it as administrator!!

Tried to download some of the other releases ,disabled antivirus and windows defender , none worked .
also my squirrelsetup is empty.
If I try it again asks for my permission two times and "run as a normal user problem".
How do I install it?

**Comment by Indritindrit** [comment]
Has the problem 'run as a normal user instead of run as administrator' been solved before ? Couldn't find nothing.

**Comment by rsese** [comment]
Thanks for reaching out - so it looks like you don't have a long username and you've disabled antivirus which is good since those are 2 common issues.

I haven't seen that "Please re-run this installer as a normal user" popup before either (and as far as I know, even if you try to run as admin, that doesn't actually run as admin).

Not sure if this is a general issue with the installer framework we use:

https://github.com/Squirrel/Squirrel.Windows/issues/482

Does portable mode work for you?

https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode

Lastly, please use the issue template as much as possible when opening issues, the information and organization of the template is super helpful for us.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17118#issuecomment-380903533. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
