### ISSUE TITLE
Failed to deploy to 172.16.234.246 see console output for details.

### ISSUE THREAD

**Issue by tayarubam** [atom/atom#17116]
[Enter steps to reproduce:]

1. Try to deploy a roku channel to roku using cmd+option+shift+d
2. The deploy fails saying issue with Atom

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Failed to deploy to 172.16.234.246 see console output for details.

```
At undefined

undefined
```

### Commands

```
     -4:27.3.0 application:reopen-project (atom-pane.pane.active)
  3x -1:38.6.0 roku-deploy:deployRoku (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-language-brightscript 0.3.0 
busy-signal 1.4.3 
go-plus 5.7.2 
gpp-compiler 3.0.7 
intentions 1.1.5 
language-brightscript 0.6.3 
linter 2.2.0 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
roku-deploy 0.5.1 
roku-develop 0.1.8 
terminal-plus 0.14.5 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [roku-deploy](https://github.com/mmratio/roku-deploy) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
