### ISSUE TITLE
windows platform scipt/build error

### ISSUE THREAD

**Issue by QZSAMA** [atom/atom#17122]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
by the description on the guide, i can run dev mode right after i bootstrap but i could not find any execution file to run in the powershell therefore i tried to build. And the build pop me those error messages.
using: Windows 10 (64bit) and powershell(admin)

PS C:\Users\kelvi\github\atom> .\script\build
Node:   v8.9.4
Npm:    v5.3.0
Python: v2.7.14
Installing script dependencies
Installing apm
npm ERR! path C:\Users\kelvi\github\atom\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\ansicolors
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\kelvi\github\atom\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\ansicolors' -> 'C:\Users\kelvi\github\atom\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kelvi\AppData\Roaming\npm-cache\_logs\2018-04-12T05_36_56_105Z-debug.log
child_process.js:624
    throw err;
    ^

Error: Command failed: C:\Users\kelvi\github\atom\script\node_modules\.bin\npm.cmd --global-style --loglevel=error install
npm ERR! path C:\Users\kelvi\github\atom\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\ansicolors
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\kelvi\github\atom\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\ansicolors' -> 'C:\Users\kelvi\github\atom\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kelvi\AppData\Roaming\npm-cache\_logs\2018-04-12T05_36_56_105Z-debug.log

    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at module.exports (C:\Users\kelvi\github\atom\script\lib\install-apm.js:9:16)
    at Object.<anonymous> (C:\Users\kelvi\github\atom\script\bootstrap:29:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
[Description of the issue]

### Steps to Reproduce

1. git clone 
2.  .\script\bootstrap
3.  .\script\build

**Expected behavior:** sucessfully build

**Actual behavior:**error message shown above

**Reproduces how often:** 100%

### Versions

it is build from source so no version

**Comment by Arcanemagus** [comment]
Can you try running `script/clean` and then `script/build`? This is normally caused by `package-lock.json` files getting stuck around, but `script/clean` should clear up any other potential issues.

----

A few notes:

> .\script\bootstrap
> .\script\build

`script/build` already bootstraps for you, so the first step wasn't actually necessary 😉.

> powershell(admin)

You shouldn't be building this under an admin prompt as there is no reason to do so.

**Comment by Arcanemagus** [comment]
No, I mean `script/build` _already_ runs the same code that is in `script/bootstrap`, so there is no need to run that beforehand.

If you already have an existing version of Atom installed and _all_ you want to do is work on some of the JS code, then the steps to [run in development mode](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#running-in-development-mode) are all you need.

You were asking about creating your own full executable though, which means running `script/build`. As i said the first thing you should try is running `script/clean` before running `script/build` again.

**Comment by QZSAMA** [comment]
GET it 
And for the guide:https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#running-in-development-mode
"Once you have a local copy of Atom cloned and bootstrapped, you can then run Atom in Development Mode. "
For windows system, if there is no execution file(.exe) , it is impossible to run "atom --dev"
It should be "script/build"  Then, at the location of"~\atom\out\Atom x64", 
I can successfully run "atom --dev" now

**Comment by Arcanemagus** [comment]
I'm glad you got it working, feel free to submit a PR over on the [flight manual repo](https://github.com/atom/flight-manual.atom.io) improving the wording 😉.

----

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
