### ISSUE TITLE
atom keep loading and doesn't close after pressing the close arrow button (or chose to "force close")

### ISSUE THREAD

**Issue by WiliTest** [atom/atom#17132]
It's not really a bug, since with some patience (could take 5 min) atom eventually closes itself. But it takes a lot of resources (and time) to open atom, so when I launch it by mistake, especially when I launch 2 or 3 atom windows instance, it takes a while to calm down.

Sometimes a popup alert asks if I want to force to close, but it doesn't "force" much more than the arrow to close the window. 

So, if possible, it could be a nice improvement to be able to close the app, when we close it.

(Windows 10)

**Comment by rsese** [comment]
Thanks for the feedback!  I'm not sure if this much we can do in cases like this but we've passed along your suggestion to the maintainers team - because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.

One related thing that I might suggest is to try Timecop to see if there are particular packages contributing to the slow startup time you're seeing:

https://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-startup-performance

If so, you can disable the package(s) and see how that affects your startup time.
