### ISSUE TITLE
Feature request: Change font size only in one pane

### ISSUE THREAD

**Issue by Raushanka** [atom/atom#17137]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[I did split Atom IDE interface into 3 panes, and wanted to change font size only in one pane. 
However, font size changes in each pane. Think that it would be better to add such features to change font only in particular panes. ]

![gif](https://user-images.githubusercontent.com/23207159/38771338-5f563d54-4043-11e8-82fd-085d85ecfeac.gif)

**Comment by rsese** [comment]
Thanks for the suggestion!  Though I can see how this could be useful in some cases, with all the work [the team has on their plate](https://github.com/atom/atom/tree/master/docs/focus), this isn't something that they would work on any time soon. Because we try to treat the open issues list as our backlog of what we'll be working on, we'll close this for now.

Though it might not be the use case you had in mind, you can do things with your `styles.less` file like setting a different font size of the active pane:

https://discuss.atom.io/t/different-font-size-per-pane-possible/37762
