### ISSUE TITLE
Atom does irrelevant word substitutions

### ISSUE THREAD

**Issue by Raushanka** [atom/atom#17143]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom most of the time gives irrelevant substitutions (suggestions) of typed words. 
I think this kind of behavior annoys some users.  

### Steps to Reproduce

1. I types some word, for example: calculate
2. Atom gives some irrelevant suggestions

**Expected behavior:**give appropriate substitutions or not give at all

**Actual behavior:** irrelevant suggestions

**Reproduces how often:** 100%

### Versions

Windows 8, 64 bit
atom version: 1.25.1

![gif2](https://user-images.githubusercontent.com/23207159/38779811-6d47488e-40ef-11e8-9750-b126c64a73ce.gif)

**Comment by lee-dohm** [comment]
See the settings for the autocomplete-plus package for ways to customize what results are shown. Specifically, "Include Completions From All Buffers", "Use Strict Matching For Built-In Provider", and others.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
