### ISSUE TITLE
Wrong handling "Open new window" for main folder

### ISSUE THREAD

**Issue by Daijobou** [atom/atom#17156]
If click on a folder in project and open context popup, I can open this folder in a new empty window. No files are open. Great.

Now I have different task in my project and must be open many many files everywhere in project. That all in one single window is unmanageable without a feature like grouping tabs with a name. So my only possibility is to open an new window from main folder. But here is my problem. Thats open a copy of the previous window, means with all opened files. But I expect here a empty tablist, like open window from a subfolder.

Next try. I start a blank new atom, add a folder and again its open like magic alle files from my open project in the other atom editor instance. 

So how I can open here my folder a second (or more) time without open all files from other atom instance?

**Comment by rsese** [comment]
Thanks again for reporting @Daijobou - this is expected behavior when opening a project folder and files from that project.  If you open that same folder, Atom remembers that saved state and all the files you had open will be opened in that new window.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by Daijobou** [comment]
I understand that this is the expected behavior for starting a new atom instance, but for me that make no sense when use "open in new window"-function and have the same files open again. So I see, working different tasks in same time in one folder is with atom not intended. I found no way.
