### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 103, Calling function FileSystemService/rea...

### ISSUE THREAD

**Issue by shobzz** [atom/atom#17151]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 103, Calling function FileSystemService/readFile.

```
At /opt/facebook/nuclide/0.291.99692496/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

RpcTimeoutError: Timeout after 60000 for id: 103, Calling function FileSystemService/readFile.
    at Call._timeout (/opt/facebook/nuclide/0.293.101469180/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/opt/facebook/nuclide/0.293.101469180/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.18 
highlight-selected 0.13.1 
language-babel 2.84.0 
language-capirca 0.1.2 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
nuclide 0.296.102271120 
nuclide-format-js 0.0.45 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
