### ISSUE TITLE
"What did that?" log

### ISSUE THREAD

**Issue by saizai** [atom/atom#17157]
Sometimes you forget what package just did something. (E.g. recently for me: adding a newline at the bottom of a file.)

So, please provide a log of actions taken & what package did it, w/ link to that package's settings page.

It can be pretty short (e.g. last 5 minutes). This isn't intended as a long-term log, just a way to identify the package(s) responsible for something you just saw.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
