### ISSUE TITLE
soft TAB not working

### ISSUE THREAD

**Issue by qorka15** [atom/atom#17165]
I changed TAB length from 4 to 2 spaces but it is still 4 spaces per TAB. Indent guide shows also not correct lines.

this behaviour is only in already created and opened projects. If I create new file the indent is two spaces as it should be.

I use atom  1.25.1 x64 for Windows

**Comment by rsese** [comment]
Thanks for reaching out!  It would be great if you can fill out the issue template, the information is really helpful for us when triaging issues.  In particular, please share exact numbered step-by-step instructions to reproduce, what you expect to happen, and what actually happens - if you can share an example file to try, that would be great too.

And please share  what you have set for `Settings > Editor > Tab Type`.

Once you share the template information we can go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17165#issuecomment-382539654. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
