### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by majesty2017** [atom/atom#17171]
My atom crashes or stop responding consistently

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us and we can take a look. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
