### ISSUE TITLE
Atom.exe seen as security risk by Crowdstrike and Cylance

### ISSUE THREAD

**Issue by Cloudmage** [atom/atom#17183]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Had a challenge from a cyber professional who has looked at Atom as Atom.exe has been flagged in Crowdstrike as being as being invasive on devices it is installed onto, recording inputs and monitoring applications. 

I have checked the file uploading to  Virustotal.com and both Crowdstrike and Cylance mark atom as dangerous.

### Steps to Reproduce

Scan the file using Crowdstrike or Cylance 
Check file on Virustotal,com

**Expected behavior:** Would have expected package to not be a threat

**Actual behavior:** Fails checks by Crowdstrike and Cylance

**Reproduces how often:** 

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
![atom](https://user-images.githubusercontent.com/7867701/39033189-cc9d4654-4468-11e8-9ba1-1b8f0af0efc1.JPG)
python 3.6.2
git 2.16.2.windows.1

Windows 10

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16986. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
