### ISSUE TITLE
Select region (option-drag on OSX)

### ISSUE THREAD

**Issue by saizai** [atom/atom#17193]
In OSX TextEdit & TextMate, one can select a region of text using option + mouse drag. 

Once in multi-line select mode, it works with normal cursor and selection range changes (e.g. move to start of line, select next word, etc), and selects by line offset (so e.g. if there are soft-wrapped lines and you select the first section of them, the wrapped portion is not selected). Typing, including deleting, also works as normal, but operating on every place the (multi-)cursor is.

In OSX Atom, option-drag does not work. However, it seems to have some way to get into this mode — if you do a regex find all on `^`, you get a multicursor that sorta kinda works.

a) How can I have option-drag (both on OSX and other Atom platforms)?

b) How exactly does the multicursor mode work? What ways can it be invoked?

Here's a screencap comparison, since this is a bit hard to describe in text: https://youtu.be/uChevnNPY4k

**Comment by lee-dohm** [comment]
You can find some answers to your questions on [Discuss, the official Atom message board,](https://discuss.atom.io) in [this topic](https://discuss.atom.io/t/vertical-column-selection/15913). The easiest way to create multiple cursors is to <kbd>Cmd+Click</kbd> in multiple places.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by saizai** [comment]
Creating multiple cursors is not the same thing as box select.

**Comment by lee-dohm** [comment]
There are other topics there about box select as well.
