### ISSUE TITLE
Line break breaks recommended characters left for commit message.

### ISSUE THREAD

**Issue by Naruyoko** [atom/atom#17219]
I am going simple for this. Normally, Atom shows to use up to 72 characters for commit message. Type a character and it shows 71 next to commit button. They work fine normally, but inserting(or simply pressing enter) line break will make the number to ∞. This looks like it doesn't matter where the line break is, how many lines are or how many characters are there. Here's image.
<img width="292" alt="capture" src="https://user-images.githubusercontent.com/32781397/39279583-0314c8b6-48c8-11e8-96a3-c0cba6f32d65.PNG">

**Comment by Arcanemagus** [comment]
This is because the title line of the commit message is _recommended_ to be limited to 72 characters, however after the title line there is no limit to the number of characters in the message. So as soon as you hit enter you are in the body of the commit message.

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
