### ISSUE TITLE
Problem with tracking files while switching branches

### ISSUE THREAD

**Issue by loratov** [atom/atom#17223]
After creating a new file in a branch and switching to master, that new file remains and is causing me issues that are only resolved if I quit Atom altogether.

Here are my exact steps:

1. Open atom on master branch
2. Switch to new branch
3. Create new file in new branch
4. Save File
5. Stage File
6. Commit File
7. Switch to master branch
8. New file appears in project files tree and in the unstaged sections of the git gui.

The only way to get out of this is to quit Atom after I switch branches, then I'm prompted to save the new file to which I choose not to. Then I reopen Atom and the file is not there anymore.

**Comment by rsese** [comment]
Thanks for contributing!  This sounds like https://github.com/atom/github/issues/1418 which was closed in favor of https://github.com/atom/atom/issues/17013.  You removed the template information so we don't have some details - what version of Atom are you on or and what operating system?

I'll tentatively close as a duplicate for now but if it's a different issue, we should reopen in https://github.com/atom/github.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
