### ISSUE TITLE
Squirrel (windows updater) issues

### ISSUE THREAD

**Issue by zorn-v** [atom/atom#17239]
1. It does not remove old version after update. And I need periodically clean `c:\Users\<user>\AppData\Local\atom\`. Release about of half GB... Perceptibly to have of 500 MB trash (for EACH old release) on SSD.
2. (not so critical) It always download full package because `Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException` 
Filename must be less 260 chars and dirname must be less 248 chars
Something like this
3. Downloaded packages MUST be deleted after success install I think... Or at least old downloads

**Comment by rsese** [comment]
Thanks for the reaching out!

> It does not remove old version after update. And I need periodically clean c:\Users\<user>\AppData\Local\atom\. Release about of half GB... Perceptibly to have of 500 MB trash (for EACH old release) on SSD.

Atom should keep I think 1 old version in addition to the current version and this is expected behavior e.g. /cc https://github.com/Squirrel/Squirrel.Windows/issues/1024.  You don't mention how many versions you have however - there was a bug 1.19 I think where old versions weren't getting removed but that's been fixed (though you'll need to manually remove these).

> (not so critical) It always download full package because Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException
> Filename must be less 260 chars and dirname must be less 248 chars
> Something like this

This has been reported in https://github.com/atom/atom/issues/15664 if you want to subscribe.

> Downloaded packages MUST be deleted after success install I think... Or at least old downloads

Not sure what you mean here can you clarify?

Lastly, it would be super helpful for us if you can use the issue template when opening issues and additionally, report 1 issue per issue.  If multiple issues are reported in a single issue, it's harder to keep track of things and you can't close the issue until all the issues in it are closed.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by zorn-v** [comment]
Yes of cause. Windows updates in the #%$#%@#$@#$@

**Comment by zorn-v** [comment]
I HATE your MAC. Hate you moronic WHITE background for terminal.
I HATE it coz atom-ui is MAC i think.
White terminal IS ugliness
