### ISSUE TITLE
Atom does not have an uninstaller

### ISSUE THREAD

**Issue by eric645** [atom/atom#17249]
**Atom does not have an uninstaller**
GitHub guys should fix the problem that Atom does not have an uninstaller.

**Comment by rsese** [comment]
Thanks for reaching out!  

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Since the template isn't filled out I'm not sure what operating system you're on but on Windows you can uninstall from the control panel.
