### ISSUE TITLE
Dose not work with Ubuntu 18.04

### ISSUE THREAD

**Issue by jokeroller** [atom/atom#17250]
I use the version 1.22.1 .It worked well when I used  Ubuntu 16.04 , however, this days I installed the Ubuntu 18.04, it breaks when I install plugins . I use it for many works it is very important for me.Is there any solutions?

**Comment by rsese** [comment]
Thanks for reaching out!   Can you update the issue body and fill out the issue template? The information is super helpful for us when investigating issues.  In particular, specific steps to reproduce are always helpful.

Also, does it matter what packages you try to install?  And when you say it "breaks", what do you mean by that?  Are you getting an error message that you can copy/paste for us?

> I use the version 1.22.1 

Though not necessarily related to the issue you're having, can you update to the latest  release version (currently 1.26.1) and see if that makes a difference? 

Once you provide this information we can re-open and go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by rsese** [comment]
Oh also, I just installed Ubuntu 18.04 and installed Atom 1.26.1 to test, and I was able to install the Zen package with no errors.
