### ISSUE TITLE
Allow replacing of files in tree view [Feature Request]

### ISSUE THREAD

**Issue by matt3224** [atom/atom#17296]
I run into this daily, if I drag a file like `example.png` into a directory that already has an `example.png` file Atom says something like "Failed to move entry... already exists" which is fair enough.

However it would be massively helpful if instead it could ask "A file called example.png already exists do you want to replace the file or keep both", or cancel.

Thanks!

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

----

And, by the way, these feature requests belong in the https://github.com/atom/tree-view repository, not in atom/atom.
