### ISSUE TITLE
Pandoc could not be spawned error

### ISSUE THREAD

**Issue by c0fe** [atom/atom#17304]
### Description

After installing pandoc and opening an RST file to edit, Atom will show the following error:

`'pandoc' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.`

### Steps to Reproduce

1. Install pandoc via the Atom Settings
2. Open RST file
3. Edit

**Expected behavior:** [What you expect to happen]

No error

**Actual behavior:** [What actually happens]

Error is produced:

`'pandoc' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.`

**Reproduces how often:** [What percentage of the time does it reproduce?]

Constantly

### Versions

**Atom Version:** 1.26.1
**OS:** Windows 10 Professional 64-bit

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [pandoc](https://atom.io/packages/pandoc) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
