### ISSUE TITLE
spec waitForPromise always times out

### ISSUE THREAD

**Issue by twifty** [atom/atom#17315]
A simple reproducible case:
```js
describe('promise', () => {
    describe('should', () => {
        let resolved = false
        beforeEach(() => {
            waitsForPromise(() => {
                return new Promise(resolve => {
                    resolved = true
                    window.setTimeout(resolve, 10)
                })
            })
        })

        it('resolve', () => {
            expect(resolved).toBe(true)
        })
    })
})
```

If I remove the `setTimeout` and call `resolve` directly it does run correctly. However, my own code being tested is based on socket and process events.

Are there any additional steps I need to perform in order for async code to run correctly? I'm getting the distinct impression that the main event loop is not running.

Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.14
git 2.17.0

**Comment by 50Wliu** [comment]
For legacy reasons, we [mock setTimeout](https://github.com/atom/atom/blob/7ca92a260361d2b94b69d4a32cda7cb93cab646c/spec/spec-helper.coffee#L73) and a few other time-related methods.

There's two ways to get around that:
1. Call `advanceClock(time)` with the time in milliseconds that you want to move the clock forward by (in your case, 10).
2. Call `jasmine.useRealClock()` before using any of the mocked time methods.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by twifty** [comment]
This is NOT a question. The example given is written exactly as the docs state the method should be used.

Now, while the example I gave does use a timer, it only does so to provide a reproducible sample. The actual code uses real promises which are resolved when a socket connection is established.

However, I have worked around the issue by not using atoms built in tester. That does not mean the bug doesn't exist!
