### ISSUE TITLE
Blinking two cursors at once in an Atom text editor

### ISSUE THREAD

**Issue by isopen** [atom/atom#17320]
### Description

Just working. Periodically, there are two cursors in the editor.
Does not depend on the operating system. Repeated for different computers.
I can not attach the material. this is somehow unpredictable.
Appeared on Atom without extensions.

### Steps to Reproduce

I'll try again. I'll try to attach the video. Perhaps this is due to the effect of highlighting text and copying it.

**Expected behavior:**
One cursor in a text editor. I think one is enough :)

**Actual behavior:**
Periodically, two cursors appear in a text editor

**Reproduces how often:**
Approximately once a day with intensive work.

### Versions
atom: <= latest
os: windows 10, debian 9.3

### Other

It is also possible that the past state of the cursor is not always cleared and the link is lost.
Maybe it's a browser bug. It is necessary to check :)

**Comment by rsese** [comment]
Thanks for the report - does pressing <kbd>Esc</kbd> make the extra cursor disappear?  If so, my best guess would be that you might be accidentally creating multiple cursors by ctrl-clicking?

https://flight-manual.atom.io/using-atom/sections/editing-and-deleting-text/#multiple-cursors-and-selections

> atom: <= latest

Please mention the specific version of Atom you're using with the output of `atom -v` since "latest" will change over time.

Also, please keep the `Prerequisites` section of the template - if some part of it doesn't apply, just mention why in that section.

I'm going to close for now since there's no consistent steps to reproduce and no other recent reports of this but we can reopen if necessary.

**Comment by isopen** [comment]
Oh. Thanks. Now it became clear why this is happening.:)
Can I withdraw this opportunity for default?

**Comment by rsese** [comment]
> Oh. Thanks. Now it became clear why this is happening.:)

👍 

> Can I withdraw this opportunity for default?

Sorry it's not possible to disable multiple cursors right now - you can subscribe here if you'd like though:

https://github.com/atom/atom/issues/7595
