### ISSUE TITLE
Atom's spell-check

### ISSUE THREAD

**Issue by Coder443** [atom/atom#17327]
I have just started using Atom, and I have found this small issue with Atom's spell-checker 'spell-check'. It seems to work all right with normal files by detecting the wrong spellings. But, when I move on to my Python code, it doesn't detect any spelling mistake at all. 

I was wondering if this issue could be solved?

**Comment by the-j0k3r** [comment]
@Coder443 

I think you are best served by reporting bugs with a specific atom package in that package repository.

In this case you should do this at https://github.com/atom/spell-check, reporting it here will probably get lost in a black hole.

**Comment by rsese** [comment]
Thanks for reaching out @Coder443!  If you have questions about using Atom, you should use one of the resources below.  So if @the-j0k3r's suggestion doesn't help or you still have trouble, please reach out on the Atom Slack or the message board.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by the-j0k3r** [comment]
@rsese 

facepalm on canned response.
