### ISSUE TITLE
Atom crashes when trying to open files on private network sshfs mount point

### ISSUE THREAD

**Issue by bceylan** [atom/atom#17333]
### Description

Atom crashes after trying to open files on sshfs mount point.

I have sshfs mounting a directory from private network servers. Atom works normal except sometimes directory listing lags if there are more than 100-200+ files inside. However, after some time when computer isn't connected to the private network, but it is connected now, I can edit/save files that are already open but 

1. can open some of them
2. can't open some of them. EIO: i/o error, close. Unable to open 'path'
3. crashes while trying to open.

### Steps to Reproduce

1. Work on your sshfs mounted directory, private network, in Atom
2. Quit Atom and disconnect from private network and wait some time
3. Reconnect to private network and launch Atom. Window restores the last state / reopen last item from file menu.
4. Do whatever with already opened files.
5. Can't open new ones, crashes.

I can say it happens almost always.

### Versions

macos 10.13.4 (17E202)

```
~$ uname -a
Darwin Kernel Version 17.5.0

~$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.14
git 2.15.1

~$ atom --version
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

~$ sshfs --version
SSHFS version 2.10
OSXFUSE 3.7.1
FUSE library version: 2.9.7
```

**Comment by rsese** [comment]
Thanks for the report -

> However, after some time when computer isn't connected to the private network, but it is connected now,

Hmmm, sounds like https://github.com/atom/atom/issues/10271?

Also x-ref: https://github.com/atom/atom/issues/2456

**Comment by SSnoda** [comment]
Atom crash sometimes working with atom-ctags.
then i solve by 
1.deleting all ctags files in PROJECT_PATH/*.ctags
2.restart atom and ctag-packages

**Comment by maofree** [comment]
Hi
I get a similar problem with sftp on my local lan where I edit files from my pc to the local server.
In my case when I save "ctrl + s" the content of small file size is cleaned, so I get a void file in the server, instead for big file like 100kb it is not saved but the content is not cleaned.
In both cases I need to save more time to save the last change.
probably it is due from gvfs with bluefish I got the same problem of bceylan (at this moment they have solved the problem on bluefish).

with other editors it is ok

I use archlinux with gnome 3.28.1 on my pc and debian 9.4 on the server
with the last upgrade of atom the problem is bigger because now I cannot see if the file is saved in the correct mode, before the blu point remains blue and only after more save it saved correctly

Is it necessary to create a new bug ticket for this problem?

thanks
bye
