### ISSUE TITLE
Pale Colors

### ISSUE THREAD

**Issue by schu-r** [atom/atom#17356]
### Description

Due a Bug in Chrome If you have a Color Profile all Colors are displayed wrong

From google Forum:
Temporarily for Chrome 61, you can disable color correct rendering by setting chrome://flags/#enable-color-correct-rendering to Disable.  Then close and restart Chrome.

Temporarily for Chrome 62, you can set chrome://flags/#force-color-profile to sRGB.  Then close and restart Chrome.

### Steps to Reproduce

1. Configure Display Profile on Ubuntu 18.04:
    1. Navigate to _Settings_ > _Devices_ > _Color_ and click on your current monitor. [[screenshot](https://user-images.githubusercontent.com/2988/40238014-0bdd5692-5a80-11e8-9315-3d155871226a.png)]
    2. Click _Add Profile_.
    3. Select on _Standard Space - Compatible with Adboce RGB (1998)_ and click _Add_. [[screenshot](https://user-images.githubusercontent.com/2988/40444431-69ceef52-5e97-11e8-8d3f-9cbdf30533ce.png)]
2. Start  Atom

**Expected behavior:**
Normal Colors

**Actual behavior:**
All Colors are Pale and Images have complete wrong Colors

**Reproduces how often:**
100%

### Versions
Atom    : 1.28.0-beta0
Electron: 2.0.0
Chrome  : 61.0.3163.100
Node    : 8.9.3

From Ubuntu 18.04 PPA

**Comment by jasonrudolph** [comment]
@schu-r: Thanks for opening this issue. I wasn't familiar with the steps for adding a display profile on Ubuntu, so I've updated the issue body to explain the steps I followed to reproduce this issue. If those steps are incorrect, please let me know.

**Comment by schu-r** [comment]
@jasonrudolph
Ich dont know If its correct. I used DisplayCAL to calibrate my Monitors. I'm a photographer and coder at the Same time. So i need correctly calibrated Monitors and a good coding tool at the same time.

**Comment by jasonrudolph** [comment]
I captured a few screenshots for reference. All screenshots below are taken using Ubuntu 18.04 with a color profile configured. (See _Steps to Reproduce_ in the issue body.)

## Using Atom's Default "One Dark" Theme

### Atom 1.27.0

<img width="1259"  src="https://user-images.githubusercontent.com/2988/40238513-6059f3d2-5a81-11e8-9c29-bae52f884a53.png">

### Atom 1.28.0-beta0

<img width="1265"  src="https://user-images.githubusercontent.com/2988/40238512-604948a2-5a81-11e8-8c41-8d4d173539f9.png">

## Using Atom's "One Light" Theme

### Atom 1.27.0

<img width="1370" src="https://user-images.githubusercontent.com/2988/40242496-d4de1e2c-5a8b-11e8-9f04-20c7bf99f10e.png">

### Atom 1.28.0-beta0

<img width="1374" src="https://user-images.githubusercontent.com/2988/40242495-d4c86be0-5a8b-11e8-88f5-9415fb0051bc.png">

**Comment by jasonrudolph** [comment]
https://github.com/atom/atom/commit/d65a0971f95b39bac326e195c903c34e438b0328 seems to restore the previous color behavior on Linux:

<img width="1209" src="https://user-images.githubusercontent.com/2988/40259378-d2248742-5ac3-11e8-99a6-6881838d15e1.png">

However, according to [this Google Doc](https://docs.google.com/document/d/1jMokB_OBkZVELu22li8vnHxAUoL1eGnLedP-1Gttv40/edit#), this fix might *not* be what we want on macOS:

> In Chrome 62 and later, in chrome://flags, there is a “Force color profile” option. This tells Chrome to ignore the operating system settings and use some other value instead. Setting this to “sRGB” will make Chrome behave as it did before on Linux and Windows (for 99% of content). This setting will not have that effect on macOS (it will just clip all colors to the sRGB gamut).

I'll need to take a closer look at how this affects macOS. Once I do that, I hope to open a pull request with a proposed fix.

**Comment by demetris** [comment]
Over at Atom Discussion (https://discuss.atom.io/t/any-way-to-change-color-rendering-in-atom-1-28-0-beta-electron-2-0-0/55234) @jasonrudolph asked if those of us seeing the issue have color profiles configured.

Here is my info:

I do have a color profile configured.

I generate the color profiles with DisplayCAL and i1Display Pro. The issue appears on both desktop systems I use, Windows 8.1 and Debian Sid (with Gnome v. 3.28, IIRC).

Also (which may or may not be relevant), my displays are wide-gamut, that is, they have over 95% AdobeRGB coverage.

Cheers!

**Comment by jasonrudolph** [comment]
:wave: @schu-r @demetris : I'm still getting up to speed on color profiles, but I think I have a better understanding of the situation now. Would you mind reviewing my findings below? If I'm misunderstanding any of this, please let me know. :bow:

## About the different color rendering

> Due a Bug in Chrome If you have a Color Profile all Colors are displayed wrong -- https://github.com/atom/atom/issues/17356#issue-324353404

As far as I can tell, the Chrome team intentionally updated Chrome's color rendering. In https://github.com/electron/electron/issues/10732#issuecomment-341481598, a member of the Chrome dev team shares this background on the change:

> Chrome as of 61 started (finally!) respecting the color profile that the OS specifies on all desktop platforms. As a consequence, CSS specification of the color ##ABCDEF, when drawn to the screen, will not necessarily be ##ABCDEF -- it will depend on the monitor that you draw it on.

## Different, but for a good reason, right?

While the Chrome team acknowledges that the color rendering is different now, they contend that the difference is due to the old behavior failing to respect color profiles and the new behavior correctly respecting color profiles.

With that in mind, while Atom's color rendering did indeed change in 1.28.0-beta0, this change seems like an improvement, since it now respects a display's color profile.

## Let's make sure we're seeing the same thing ...

The gifs below show the behavior that I'm seeing on Ubuntu 18.04. Does that match the behavior you're seeing? If not, can you please share some gifs or screenshots to so that we can better understand the issue?

## Examples

The examples below compare Chrome's rendering of `#282c34` with Atom 1.28.0-beta1's rendering of that color (which is used as the background editor color in Atom's [One Dark syntax theme](https://atom.io/themes/one-dark-syntax)). Colors are measured using the _Digital Color Meter_ app on macOS.

<details>
<summary>Sample HTML used for the Chrome demos below</summary>

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <style media="screen">
      body {
        background-color: #282c34;
      }
    </style>
  </head>
  <body>
  </body>
</html>
```
</details>

### Ubuntu 18.04 without custom color profile

Chrome 66 and Atom 1.28.0-beta1 both render `#282c34` as `#282c34`, since there's no color profile to instruct Chrome and Atom to behave differently.

![demo](https://user-images.githubusercontent.com/2988/40440345-cfe48d6c-5e8b-11e8-879f-f0ef09765639.gif)

### Ubuntu 18.04 with custom color profile (Adobe RGB 1998)

When applying the Adobe RGB 1998 color profile, Chrome 66 renders `#282c34` as `#2d3037`, and Atom 1.28.0-beta1 renders `#282c34` as `#2e3027`. This seems to be consistent with the behavior described in https://github.com/electron/electron/issues/10732#issuecomment-341481598:

>> CSS specification of the color ##ABCDEF, when drawn to the screen, will not necessarily be ##ABCDEF -- it will depend on the monitor that you draw it on.

I think the slight difference between Chrome and Atom might be due to color accuracy refinements that occurred between Chrome 61 (used in Atom 1.28.0-beta1) and Chrome 66 (used in the demo below).

![demo](https://user-images.githubusercontent.com/2988/40439553-4110523a-5e89-11e8-9a26-97313f34d3a2.gif)

**Comment by jasonrudolph** [comment]
@ryran: Since [you observed](https://github.com/electron/electron/issues/10732#issuecomment-390008244) this change after updating to Atom 1.28, I wanted to share the notes in https://github.com/atom/atom/issues/17356#issuecomment-391450897 with you in case it helps. I'd love to know if those notes accurately describe the behavior you're seeing. If not, would you mind sharing some gifs or screenshots to so that we can better understand the issue? :bow:

**Comment by simurai** [comment]
For those that...

- use the `One Dark Syntax` theme
- and like to keep using a color profile that makes the colors in Atom 1.28 look pale

...there is the [One Dark Vivid Syntax](https://atom.io/themes/one-dark-vivid-syntax) theme. It's identical except that the colors are a bit lighter and more saturated.

One Dark Syntax | One Dark Vivid Syntax
--- | ---
![one-dark](https://user-images.githubusercontent.com/378023/40457875-e5935fbe-5f33-11e8-96e0-6bd22914106b.png) | ![one-dark-vivid](https://user-images.githubusercontent.com/378023/40457874-e52bdace-5f33-11e8-8fd4-1d4a4877e28e.png)

There are also lots of other [One dark based themes](https://atom.io/themes/search?utf8=%E2%9C%93&q=one+dark+syntax&commit=Search) with tweaked the colors.

**Comment by thomasjo** [comment]
@schu-r What is your monitor's color profile set to? The profile seems to be incorrectly calibrated to an extreme extent. Also, are you seeing equivalent problems with Chrome 66?

**Comment by demetris** [comment]
Color calibration and color profiles go over my head for the most part, but my feeling is that something is not right in the way Chrome approaches this issue.

Why I am saying that?

In [I want my old colors back!](https://docs.google.com/document/d/1jMokB_OBkZVELu22li8vnHxAUoL1eGnLedP-1Gttv40) --which I think has been written by a member of the Chrome team-- it says this:

> Should Chrome respect the color profile settings on these systems (allowing users with wide color gamut monitors to view [wide color gamut](https://webkit.org/blog-files/color-gamut/comparison.html) photos)? Or should Chrome ignore this setting (making the assumption that no users intentionally use these settings, and lock all users forever into 1996-era technology)?

But here is the thing:

On my wide-gamut monitors Firefox displays the right parts of the wide-color-gamut photos on the test page just fine (for instance, the WebKit logo in the right part of the first image appears perfectly), and it does that without deviating from the way the rest of the system renders colors.

Why is that possible in Firefox but not in Chrome? Maybe there are technical reasons. I would understand that. But if there are no such reasons, maybe it would be possible for Chrome to offer the same options that Firefox does.

In Firefox’s ``about:config`` (advanced options like Chrome’s ``chrome://flags``) there is a preference named ``gfx.color_management.mode``, first documented here: https://developer.mozilla.org/en-US/Firefox/Releases/3.5/ICC_color_correction_in_Firefox -- it takes one of three values:

0 -- Color management disabled. (Default in Firefox 3.)
1 -- Full color management.
2 -- Color management applied only to tagged images.  (Default in Firefox 3.5.)

In my quick tests measuring the RGB values of solid color blocks, *Full color management* in Firefox produces the same result as recent versions of Chrome. But it is not the default. If you want full color management, it is there for you to select it: you simply switch the value from 2 to 1.

Now, I understand that adding options upon options is not good. I also understand that not everyone needs the same things in a computer monitor. I spend more on monitors than on any other part of my system because I have poor eyesight and my eyes complain easily, not because I am a designer, a photographer or a videographer. I know that, where I see an annoyance, other people may see an improvement. It is just my feeling that in this case, if I understand what Firefox does correctly, we could have our cake and eat it too.

Thank you, everyone, for your time!

**Comment by simurai** [comment]
> @schu-r it is completely unusable for me.

👍 Agreed, that looks unusable.

> @thomasjo What is your monitor's color profile set to?

Based on [this comment](https://github.com/atom/atom/issues/17356#issuecomment-390230724), @schu-r used `DisplayCAL` to calibrate the monitor. [Same](https://github.com/atom/atom/issues/17356#issuecomment-391081403) in @demetris's case.

> @thomasjo Also, are you seeing equivalent problems with Chrome 66?

I wonder that too, but my guess is that @schu-r set `chrome://flags/#force-color-profile` to `sRGB`, so it overrides DisplayCAL's calibration. And @demetris uses Firefox? that "only has color management for tagged images". Which makes me wonder about this paragraph in the [Google Doc](https://docs.google.com/document/d/1jMokB_OBkZVELu22li8vnHxAUoL1eGnLedP-1Gttv40/edit):

> On Linux, X11 also has color management support, but, like Windows, most applications ignore the color management settings.

"most applications"! Could it be that DisplayCAL's calibration is off, but it hasn't been noticed because most applications ignore it? Just now with Chrome and Atom beta it becomes noticeable. I have to add that I never used DisplayCAL, so I don't wanna imply anything. It's just a wild guess. :innocent:

@schu-r @demetris have you tried to switch the color profile to the default? Just to test how it affects Atom Beta. You might not wanna do that, if your custom profile isn't saved and you can't change back to it.
