### ISSUE TITLE
watching open files for changes is broken after `git pull`

### ISSUE THREAD

**Issue by artm** [atom/atom#17355]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * [x] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
  * [x] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
  * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
  * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
  * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

We have a deploy script that merges current feature branch into the integration branch then deploys that and checks out the feature branch again. I have noticed that after executing it the open files contents is reset to the state in the integration branch before the merge. Further investigation showed that it is actually a `git pull` of the integration branch that causes the problem.

I have created a minimal "model" of our script that demonstrates the problem on a toy repository: https://github.com/artm/test-atom

I think it has to do with the file operations that `git pull` performs when replacing files and would thus affect other scenarios where an external software uses the same operations. I don't know exactly which operations or why it is a problem. 

### Steps to Reproduce

1. fork the repository (the script executes a `git push`, so simply cloning is not enough)
2. clone the repository
3. `git checkout feature`
4. `atom --safe README.md`
5. edit and commit the `README.md` to the `feature` branch
6. `./repro`

**Expected behavior:** the `README.md` open in atom contains the changes from step 5

**Actual behavior:** `README.md` contains the version from `deploy` branch before merging the `feature`

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Ubuntu 18.04

```
$ atom --version
Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python 2.7.15rc1
git 2.17.0

$ uname -a
Linux parurak 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

### Additional Information

This happens with any **File System Watcher** setting.

In most of my tests the problematic `git pull` actually had nothing to do and would report:

```
Already up to date.
Current branch deploy is up to date.
```

Nevertheless it would cause the problem and commenting it out would solve it.

**Comment by lee-dohm** [comment]
@smashwilson do you have any ideas as to what could be the problem here?

**Comment by wwwutz** [comment]
For me this sounds like the return of #8888 . I stumbled upon this when two days ago I found an old version of my sources in the editor in contrast to a fresh `git pull --rebase` on disk. I didn't have the time to investigate deeper, but for short I did the following:

At home: atom / save / commit / git push leave atom window open
At work: `git pull --rebase` / open in atom / edit / commit / push
At home: `git pull --rebase` and it seems atom was not refreshing. Still had the old sources open, but on disk everything was latest & greatest as `git log` showed. Would I have saved, I would have overwritten my 'work' version.

There was no 'blue'  file-has-changed indicator and `git-diff`indicator bars showed a lot of changes ( which didn't make sense, since it were the changes I did at home the day before and not the changes I did at work as far as I remember. No screenshots, no proof 8-)

Stopping, restarting atom didn't do the trick, it still loaded the old version from some cache location. I planned to `strace -e file` it but for a first test I exited atom and opened it with the filename on the commandlilne supplied and then it loaded the current disk version. I didn't try to reproduce since I was fed up.

home: atom 1.26 on debian
work: atom 1.25 on LFS linux

sorry if I can't get into more detail.

**Comment by smashwilson** [comment]
@lee-dohm text-buffer is still using pathwatcher, so it isn't an atom/watcher bug (and changing the "file system watcher" setting won't help). This might be a failure to create a watch descriptor? I'm not sure offhand why that might happen, though, especially in such a specific scenario.

**Comment by smashwilson** [comment]
For reference, [these lines](https://github.com/atom/text-buffer/blob/0045f3a87bad99ce33ba1134385991f3419b0819/src/text-buffer.coffee#L2006-L2027) are where we establish the watch on the buffer's file.

**Comment by asheren** [comment]
After consulting with @smashwilson , it looks like there are still a few steps to fix this bug. Mainly, get text-buffer to use @atom/watcher instead of node-pathwatcher; then verify that this fixes it, or at least see what the error is and address it in @atom/watcher.

**Comment by baverhey** [comment]
still an issue on september 2019
