### ISSUE TITLE
atom-runner error

### ISSUE THREAD

**Issue by harmloh** [atom/atom#17369]
`/usr/bin/bash: module: line 1: syntax error: unexpected end of file
/usr/bin/bash: error importing function definition for `module'
/usr/bin/bash: switchml: line 1: syntax error: unexpected end of file
/usr/bin/bash: error importing function definition for `switchml'
/usr/bin/bash: scl: line 1: syntax error: unexpected end of file
/usr/bin/bash: error importing function definition for `scl'
Ignoring bindex-0.5.0 because its extensions are not built. Try: gem pristine bindex --version 0.5.0
Ignoring bootsnap-1.3.0 because its extensions are not built. Try: gem pristine bootsnap --version 1.3.0
Ignoring byebug-10.0.2 because its extensions are not built. Try: gem pristine byebug --version 10.0.2
Ignoring ffi-1.9.23 because its extensions are not built. Try: gem pristine ffi --version 1.9.23
Ignoring msgpack-1.2.4 because its extensions are not built. Try: gem pristine msgpack --version 1.2.4
Ignoring nio4r-2.3.1 because its extensions are not built. Try: gem pristine nio4r --version 2.3.1
Ignoring nokogiri-1.8.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.2
Ignoring puma-3.11.4 because its extensions are not built. Try: gem pristine puma --version 3.11.4
Ignoring sqlite3-1.3.13 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.13
Ignoring websocket-driver-0.7.0 because its extensions are not built. Try: gem pristine websocket-driver --version 0.7.0`

first time using atom , but i got this when runmy first ruby code after ALT+R

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-runner](https://github.com/lsegal/atom-runner) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
