### ISSUE TITLE
Atom 1.27.0 Often exit abnormally when the network is disconnected

### ISSUE THREAD

**Issue by Witee** [atom/atom#17385]
macOS High Sierra 10.13.4

Often exit abnormally when the network is disconnected.

Where cat I copy the crash logs?

**Comment by rsese** [comment]
Thanks for reaching out!

You can copy the crash log and add a `.txt` extension to upload or just copy/paste it.  But as mentioned below, please provide the issue template information - the information is helpful for us when triaging issues.

Additionally, please check https://github.com/atom/atom/issues/17161 as a possible duplicate.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
