### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by BenjaminZekavica** [atom/atom#17388]
I love Atom, but its so so slow :-( Please help me.
I dont can open large projects..

**Comment by rsese** [comment]
Thanks for reaching out!  

As mentioned below, please fill out the issue template, the information in the template is helpful for us when triaging issues.  Please describe the issue in more detail, how to reproduce, etc. and we can go from there.

Also, please see the reference mentioned in the `Prerequisites` section:

https://flight-manual.atom.io/hacking-atom/sections/debugging/

Let us know if you tried safe mode any other of the suggestions there.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
