### ISSUE TITLE
Alert icons aren't displayed properly on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by szmarczak** [atom/atom#17398]
![screenshot from 2018-05-23 19-40-40](https://user-images.githubusercontent.com/36894700/40441413-4426914a-5ec1-11e8-874f-414d3bf8d836.png)

```bash
$ apm -v
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.1
python 2.7.15rc1
git 2.17.0
```

**Comment by rsese** [comment]
Thanks for reaching out! Can you update the issue body and fill out the issue template? The information is super helpful for us when investigating issues.   Once you add those details we can re-open and go from there.

Also, did you install Atom using one of officially supported installation methods?

https://flight-manual.atom.io/getting-started/sections/installing-atom/

I was unable to reproduce with 1.27.1 on Ubuntu 18.04.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
