### ISSUE TITLE
Atom theme breaks when there is a missing bracket on hsl color values in a theme.

### ISSUE THREAD

**Issue by dann254** [atom/atom#17397]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Atom theme breaks when there is a missing bracket on **hsl** color values.

### Steps to Reproduce

1.  create a new atom theme following the steps [here](https://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/#creating-a-ui-theme) 
2. set this new theme as your current theme in `dev mode`
3. navigate to the file in the project `/styles/ui-variables.less`
4.  Remove closing bracket from one of the `hsl` values like `@background-color-success: hsl(160, 70%, 36%;`
5. save the file.

**Expected behavior:** 
Get an error message like 
![image](https://user-images.githubusercontent.com/20391526/40423556-9e63be2e-5e9b-11e8-843a-40151504d502.png)

**Actual behavior:**
Atom breaks and the result is as in the image below.
<img width="1440" alt="screen shot 2018-05-23 at 15 19 05" src="https://user-images.githubusercontent.com/20391526/40423940-b8052eca-5e9c-11e8-9cf5-4030252b5041.png">

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
`atom --version`
Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

`apm --version`
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.1

`OS`
OS : macOS Sierra 
version 10.12.6

**Comment by thomasjo** [comment]
This is essentially the expected behavior; you have a syntax error in your theme, and we have no safe guards in place to protect you against that. If this is something you think we should implement, open a new issue written as a feature request detailing how you think such a safe guard should behave.

Your problem goes away if you start Atom in safe mode, since no installed (or linked) packages are loaded then. Also note that the error notification tells you what and where the problem is, which should be sufficient to fix syntax errors such as this.

Thanks for the report!

**Comment by thomasjo** [comment]
Sorry, I didn't notice that the notification was in the "Expected behavior" section. Then I would tend to agree that this is something that we might need to handle better.

Recovering from the syntax error is non-trivial, but we might be able to produce a notification. We might be already be doing that, but possibly this type of syntax error is preventing it from being rendered correctly.

/cc @50Wliu @Arcanemagus @Ben3eeE @abe33 @lee-dohm
