### ISSUE TITLE
Atom connection to gh-contractor-zcbenz.s3.amazonaws.com

### ISSUE THREAD

**Issue by arkadiyt** [atom/atom#17394]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hi,

I run Little Snitch on my laptop and I frequently see Atom attempting to make a connection to the `gh-contractor-zcbenz.s3.amazonaws.com` s3 bucket:

<img width="679" alt="screen shot 2018-05-22 at 10 23 28 pm" src="https://user-images.githubusercontent.com/2279289/40407909-b4e514e4-5e1a-11e8-9fff-a8f4011ee9a3.png">

Sometimes this happens when an update is being installed, when I open Atom, or when I download a new package.

I see that zcbenz is one of the top contributors to Atom and I'm sure this is all above board but the name is a bit disconcerting to me. Can you clarify how this bucket is used, and under what circumstances a connection is made? Is it in a personal AWS account or in a Github owned AWS account? etc

Thanks,

### Steps to Reproduce

Not 100% clear

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202

$ atom --version
Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.1
python 2.7.10
git 2.15.1
```

**Comment by Arcanemagus** [comment]
From https://github.com/atom/apm/issues/322#issuecomment-90477573 it appears that several of the `atom.io/download` links are 302 redirects to that bucket. I'm guessing that you are seeing this when Atom is checking for package updates. That particular comment is rather old, but I'm guessing that you are hitting similar redirects to that bucket 😉.

Thanks for reaching out!

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
