### ISSUE TITLE
PHP Highlighting breaks

### ISSUE THREAD

**Issue by Joseph310** [atom/atom#17408]
The highlighting does not seem to match the following PHP code. 

It breaks completely. The code following these lines also display with the wrong color-coding. It interprets everything as a string.

```
  $sql  = 'INSERT INTO table (id, userId, locale, number, timestamp) VALUES (';
  $sql .= '\''.randomString(8).'\', \''.$userId.'\', \''.$locale.'\', \''.$number.'\', '.$timeStamp.')';
  $conn->query($sql);
```

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
