### ISSUE TITLE
config.cson randomly reset

### ISSUE THREAD

**Issue by 1dal** [atom/atom#17413]
### Description

Editor resets the configuration randomly once in a while, seems after reboot/shutdown.

### Steps to Reproduce

1. idk

**Expected behavior:** 

Keep my config untouched.

**Actual behavior:**

Configuration is lost, theme changed. 

**Reproduces how often:**

### Versions

1.25.1 x64, running on Linux Debian Stretch (9)

### Additional Information

My clue is that it is related to package updates.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
