### ISSUE TITLE
fails to build Atom

### ISSUE THREAD

**Issue by xionghui19920922** [atom/atom#17411]
Node:	v10.2.1
Npm:	v5.3.0
Installing script dependencies
Installing apm
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom unknown
python 2.7.12
git 2.7.4
Installing modules ✓
Wrote Dependencies Fingerprint: /home/test/my_Code/atom/node_modules/.dependencies-fingerprint 2ca9ead19ef3142da3b6f595696fe150b2bf1035
Deleting problematic package-lock.json files
Copying assets to /home/test/my_Code/atom/out/app
Transpiling packages with custom transpiler configurations in /home/test/my_Code/atom/out/app
 transpiling for package github
Installing modules ✓
Transpiling Babel paths in /home/test/my_Code/atom/out/app
Transpiling CoffeeScript paths in /home/test/my_Code/atom/out/app
Transpiling CSON paths in /home/test/my_Code/atom/out/app
Transpiling PEG.js paths in /home/test/my_Code/atom/out/app
Generating module cache for /home/test/my_Code/atom/out/app
Generating pre-built less cache in /home/test/my_Code/atom/out/app/less-compile-cache
Generating metadata for /home/test/my_Code/atom/out/app/package.json
Generating API docs at /home/test/my_Code/atom/docs/output/atom-api.json
Dumping symbols in /home/test/my_Code/atom/out/symbols
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Unable to find the "dump_syms"
Error: Unable to find the "dump_syms"
  at /home/test/my_Code/atom/script/lib/dump-symbols.js:26:15
  at Object.module.exports.dumpSymbol (/home/test/my_Code/atom/script/node_modules/minidump/lib/minidump.js:65:5)
  at /home/test/my_Code/atom/script/lib/dump-symbols.js:23:14
  at new Promise (<anonymous>:null:null)
  at dumpSymbol (/home/test/my_Code/atom/script/lib/dump-symbols.js:22:10)
  at Array.map (<anonymous>:null:null)
  at module.exports (/home/test/my_Code/atom/script/lib/dump-symbols.js:15:36)
  at Object.<anonymous> (/home/test/my_Code/atom/script/build:75:21)
  at Module._compile (internal/modules/cjs/loader.js:702:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
  at Module.load (internal/modules/cjs/loader.js:612:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
  at Function.Module._load (internal/modules/cjs/loader.js:543:3)
  at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
  at startup (internal/bootstrap/node.js:238:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**Comment by rsese** [comment]
Thanks for reaching out!  Please use the issue template as much as possible when opening issues (e.g. what operating system are you running) and we can take a look.  Have you already tried a `./script/clean` before trying to build again already?

/cc https://github.com/atom/atom/issues/15925 where "Unable to find the "dump_syms" is also mentioned.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
