### ISSUE TITLE
Closing multiple unsaved files creates multiple unusable "Do you want to save" dialogues

### ISSUE THREAD

**Issue by MaPePeR** [atom/atom#17429]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When closing multiple files with unsaved changes using the "Close all" or similar functionality creates multiple "Do you want to save this file before closing" dialogues. But only one of these dialogues can be used, because the other dialogues are opened "on top" of each other, so every other dialog is blocked until the they are resolved in order.

### Steps to Reproduce

1. Open multiple files and make changes to them without saving
   * <kbd>Ctrl</kbd> + <kbd>n</kbd>, Random letters, <kbd>Ctrl</kbd> + <kbd>n</kbd>, Random letters, <kbd>Ctrl</kbd> + <kbd>n</kbd>, Random letters, ...
2. Right click the tab-bar and select "Close all"

**Expected behavior:** Multiple dialogues are opened, but the order in which i resolve them does not matter. (The main Atom window stays blocked until all dialogues are resolved)

**Actual behavior:** Multiple dialogues are opened, but only one of them reacts to clicks.

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.27.1
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1
```

```
$ uname -r
4.16.11-1-ARCH
```

**Comment by rsese** [comment]
> Atom    : 1.27.1
> Electron: 1.8.4

Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by MaPePeR** [comment]
Great... i think i'm using the official package from the arch repositories...

**Comment by 50Wliu** [comment]
The Atom team does not maintain any packages in the Arch repositories.
