### ISSUE TITLE
Problem to save changes from SFTP on private LAN

### ISSUE THREAD

**Issue by maofree** [atom/atom#17448]
Hi

### Description

When I work from my pc (with archlinux + gnome 3.28.1) on my local server with sftp from Nautilus, using Atom often I get problems to save changes.
When I push "ctrl + s" the code is deleted, so after I need to push on "ctrl + z" and then push again to "ctrl + s" one or more times.
This happens when there is little code in the file, instead for big file I get an error to notify the impossibility of saving and then with "ctrl + s" the changes are saved.

the problem almost always happens, perhaps it is due to the increased time in the rescue operation

with gedit or other editor I don't get this error

### Steps to Reproduce

1. connect to a server using Nautilus by sftp
2. open a file with Atom
3. made some changes into it
4. save it
5. look if it can save the changes

### Versions

~$ uname -a
Linux maofree 4.16.12-1-ARCH #1 SMP PREEMPT Fri May 25 23:30:31 UTC 2018 x86_64 GNU/Linux

~$ apm --version
apm  1.19.0
npm  6.1.0
node 10.3.0 x64
atom 1.27.1
python 2.7.15
git 2.17.1

~$ atom --version
Atom : 1.27.1
Electron: 1.8.4
Chrome : 59.0.3071.115
Node : 8.2.1

**Comment by rsese** [comment]
Thanks for reaching out - 

> Atom : 1.27.1
> Electron: 1.8.4

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by maofree** [comment]
ok thanks
it is the official package of archlinux, I installed it from pacman
https://atom.io/packages/language-archlinux

**Comment by maofree** [comment]
I'm using the default one

https://www.archlinux.org/packages/community/x86_64/atom/

**Comment by rsese** [comment]
Ahh sorry, that package is unofficial and not supported by us, the only officially supported install methods are documented in the Flight Manual:

https://flight-manual.atom.io/getting-started/sections/installing-atom/

There's unfortunately no official releases for Arch though we have instructions for [building from source](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/).

Though still an unofficial build and not supported by the Atom team, I believe the `atom-editor-bin` from the AUR uses the correct Electron version at least if you want to give that a try.
