### ISSUE TITLE
./atom: symbol lookup error: ./atom: undefined symbol: g_bytes_unref

### ISSUE THREAD

**Issue by WillaLuo** [atom/atom#17440]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
I am using atom-1.27.1-amd64.tar.gz
Want to use Atom at RedHat 6.7, happen this issue
./atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./atom)
./atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./atom)
./atom: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./atom)
./atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /scratch/shuluo/tools/software/atom-1.27.1-amd64/libnode.so)
./atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /scratch/shuluo/tools/software/atom-1.27.1-amd64/libnode.so)
So according to the workaround https://github.com/atom/atom/issues/5172#issuecomment-295940464
Have add softlink  to a newer version libstdc++.so.6.0.20 to /usr/lib64/libstdc++.so.6, but still have issue.
-bash-4.1$ ./atom
./atom: symbol lookup error: ./atom: undefined symbol: g_bytes_unref

Can anybody help me how to solve this problem？
Thanks!

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
atom-1.27.1-amd64

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for contributing!

It looks like you found https://github.com/atom/atom/issues/5172 - since this is a duplicate, we'll close this issue.  That's probably the best issue for help since people in the community that are trying to run Atom on RHEL are sharing suggestions there.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by WillaLuo** [comment]
OK, @rsese Do you have any idea, what this message means? Thanks!
-bash-4.1$ ./atom
./atom: symbol lookup error: ./atom: undefined symbol: g_bytes_unref

**Comment by rsese** [comment]
Sorry I don't - from Google-ing a bit I found this that might have useful information for you?

https://github.com/electron-userland/electron-prebuilt/issues/182

**Comment by WillaLuo** [comment]
Thanks! @rsese
