### ISSUE TITLE
Lost Progress

### ISSUE THREAD

**Issue by paixlukee** [atom/atom#17453]
**Hello,**

I have been spending days on this one project.

Atom stopped working for me. (My PC just needed to reboot; didn’t know it at first) So, I was wondering if it was just the file, or the whole app. So I opened the same file on another text editor. On this other text editor, it didn’t show all of the file. I didn’t know it at first, and I saved the project on that text editor.

I rebooted my PC, and now when I open my file on Atom, it only shows a portion for my file.

Anyways, I was wondering if there was a way to revert back to other saves. I worked hard on this project, and I don’t want it to go to waste.

**Thank you,**
Luke

(I also put this on https://discuss.atom.io/ but i wasn’t sure how long it would take to respond.)

**Comment by rsese** [comment]
Thanks for reaching out @paixlukee and sorry for the trouble here - based on your description, it sounds like only part of the whole file was saved in an another editor and this is what's reflected in Atom?  If that's the case (and there are no backups or version control being used), I can't think of a way in Atom to recover the file as it was previously.  It looks like there's similar feedback in your Discuss post.

Sorry again for the trouble and if you have more questions, feel free to reach out on the message board or chat.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues  [that don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
