### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by eric645** [atom/atom#17451]
This was reported by Windows Issues by Windows
Details:
# The editor has crashed
The editor crashed by mistake because it was open for too long.
# The editor has crashed
The editor crashed by mistake because it was open for too long.
# The editor has crashed
The editor crashed by mistake because it was open for too long.
# It was programmed correctly
The editor was programmed correctly.
# Close
IMMEDIATELY close this issue.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by pzrq** [comment]
@eric645 @rsese 

Please accept my apologies for commenting on a closed issue, there are plenty of other issues like #17120 likely far more deserving of our time and attention, or perhaps a future improvement such as a more specific error message in the dialog when a crash occurs.

This just happened to me when I came back to an Ubuntu 18.04 LTS machine and unlocked it. I have also not tried to reproduce it and am satisfied that the `Reload` button worked for me.

![the editor has crashed](https://user-images.githubusercontent.com/1217010/40949474-95d3c28e-68b1-11e8-857a-3a8ba7192446.png)
