### ISSUE TITLE
Code coloring error

### ISSUE THREAD

**Issue by sanada01** [atom/atom#17458]
Atom version: 1.27.2 x64

![coloring_bug](https://user-images.githubusercontent.com/28780118/40912672-8f1ea130-67f2-11e8-8ff4-12a0d86b115a.gif)

**Comment by Zireael07** [comment]
You didn't close the bracket, what happens if you do close it?

**Comment by sanada01** [comment]
This happens:

![coloring_bug2](https://user-images.githubusercontent.com/28780118/40914300-eaf41058-67f7-11e8-8571-045aa889a7ba.gif)

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
