### ISSUE TITLE
Window10 Jump list not showing recent projects

### ISSUE THREAD

**Issue by darron1217** [atom/atom#17450]
### Description

![image](https://user-images.githubusercontent.com/8064923/40882685-64701b7c-6724-11e8-8694-7edc24209611.png)

### Steps to Reproduce

1. Install Atom 
2. Right Click on taskbar icon
3. Look at it

**Expected behavior:** [What you expect to happen]
It should show recent projects 

**Actual behavior:** [What actually happens]
It shows only basic actions

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
1.27.2

**Comment by vikramojha89** [comment]
Hello

I don't this issue to be reproduced! 
![taskbarprojectsnotseen](https://user-images.githubusercontent.com/6462220/40883618-412f4624-671f-11e8-9d05-c2c2960648ad.png)

Can you please check if other applications are showing it, as I have seen this can be sometime due to your system configuration

Vikram Ojha

**Comment by darron1217** [comment]
![image](https://user-images.githubusercontent.com/8064923/40883655-9504e6e6-673d-11e8-9079-dc828a425bb1.png)

Yes, other programs are working well

**Comment by darron1217** [comment]
Reinstalling (with complete `.atom` folder removal) didn't solve my issue

But I solved it by clearing project histories... such a weird bug

**Comment by darron1217** [comment]
This should be re-opened
I experienced same bug when I started opening multiple projects at a time

**Comment by darron1217** [comment]
It's working well on `1.28.0`
