### ISSUE TITLE
If you continue this project when Github purchased by Microsoft

### ISSUE THREAD

**Issue by youngjuning** [atom/atom#17454]
Sorry for my poor english.But I so worry about this qustion

**Comment by neilc314** [comment]
I do too, I mean it would be funny if [https://atom.io/](https://atom.io/) redirected to [https://code.visualstudio.com/](https://code.visualstudio.com/). It would be nice to have a developer comment though, as the GitHub deal will likely close soon.

**Comment by danger89** [comment]
Move to Gitlab?
Github is acquired by Micro$oft.
https://www.theverge.com/2018/6/3/17422752/microsoft-github-acquisition-rumors

**Comment by lee-dohm** [comment]
Thanks everyone for your concern.

Atom remains key to GitHub. Our product roadmap is set, and the team will continue all of their work. 

-----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by youngjuning** [comment]
@lee-dohm Thanks for you work

**Comment by atomiks** [comment]
I'm glad Atom development will continue. It's far more polished with better UX + more extensible than VSCode.

**Comment by daviwil** [comment]
If you want to be further reassured that Atom will continue, see this comment by GitHub's future CEO: https://www.reddit.com/r/AMA/comments/8pc8mf/im_nat_friedman_future_ceo_of_github_ama/e0a235q/

>Developers are really particular about their setup, and choosing an editor is one of the most personal decisions a developer makes. Languages change, jobs change, you often get a new computer or upgrade your OS, but you usually pick an editor and grow with it for years. The last thing I would want to do is take that decision away from Atom users.
>
>Atom is a fantastic editor with a healthy community, adoring fans, excellent design, and a promising foray into real-time collaboration. At Microsoft, we already use every editor from Atom to VS Code to Sublime to Vim, and we want developers to use any editor they prefer with GitHub.
>
>So we will continue to develop and support both Atom and VS Code going forward.

**Comment by BurhanDanger** [comment]
It's better to merge these two projects. That's just my opinion.

**Comment by ino76** [comment]
**atomiks**
I get it .. you like Atom, good for you but VSCode is by far best editor I've used, so pls stop being microsoft hating sheep.
I hated them because of actions they did .. bude those were different people in different time and world.
But when they do tools like this it's nothing negative. Its positive even for atom. Without competition you became lazy ;)

**Comment by lee-dohm** [comment]
@ino76 your comment was hidden as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by ino76** [comment]
**lee-dohm**
is it good now or people can't post comments here because of biased censorship?

**Comment by julesvicious** [comment]
I gonna have to learn to take others comments so comments and 

Julesvicious 

On Aug 5, 2018, at 7:50 PM, ino76 <notifications@github.com> wrote:

lee-dohm
is it good now or people can't post comments here because of biased censorship?
