### ISSUE TITLE
racer.racerBinPath is not set in your config.

### ISSUE THREAD

**Issue by addityasingh** [atom/atom#17463]
[Enter steps to reproduce:]

1. Install the packages mentioned below
2. Open a `RUST` project and add a new file `demo.rs`
3. Start typing in the file to reproduce the error

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

racer.racerBinPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -0:56.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:53.1.0 core:save (input.hidden-input)
  2x -0:29.5.0 core:move-left (input.hidden-input)
     -0:29 datatip:toggle (input.hidden-input)
     -0:28.8.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:28.5.0 datatip:toggle (input.hidden-input)
  4x -0:21.8.0 core:backspace (input.hidden-input)
     -0:12.9.0 core:save (input.hidden-input)
     -0:05.2.0 editor:newline (input.hidden-input)
     -0:04.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.12.0 
file-icons 2.1.21 
ide-rust 0.16.3 
language-docker 1.1.8 
language-html-snippetless 0.44.1 
language-javascript-jsx 0.3.7 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.8.5 
linter-ui-default 1.7.1 
racer 0.20.0 
rustfmt 0.1.3 
```

**Comment by alexheretic** [comment]
I just happened to see this, and this is not an atom issue. Rather an issue with the racer package. However, I would say you seem to have a few too many rust packages.

I'd recommend you just use **ide-rust** and uninstall or disable ***linter-rust, racer, rustfmt***. ide-rust provides racer, rustfmt & linting on its own _(built into RLS)_. If you have issues come over to https://github.com/mehcode/atom-ide-rust.

Also atom-ide-ui should have prompted you to disable ***linter*** as it replaces the linting functionality _(you shouldn't need **linter-ui-default** either)_.

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [racer](https://github.com/edubkendo/atom-racer) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
