### ISSUE TITLE
Atom open multiple windows when opened

### ISSUE THREAD

**Issue by TungBox** [atom/atom#17470]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
I usually have a habit of closing application as fast I can so Command Quit its the easiest way to do so. This problem started to happen to me recently and it popped up many windows, like about 15+ and the app frozed. Took me a while to close all of them.
### Steps to Reproduce

1. [Use Command+Quit to close Atom immediately (repeat a few times)]
2. [Reopen it]

**Expected behavior:** [What you expect to happen]
- Atom would open as usual and nothing would happen
**Actual behavior:** [What actually happens]
- Atom open tons of windows at a time, increased my computer memory usage and use all of my ram.
**Reproduces how often:** [What percentage of the time does it reproduce?]
- 60%
### Versions
Atom 1.27.2 x64
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
Computer specs: 
MacBook Air (13-inch, Mid 2012)

**Comment by TungBox** [comment]
Screenshot
https://i.imgur.com/b8OguTS.png

**Comment by rsese** [comment]
Thanks for the report - can you expand on your steps to reproduce?  E.g. what does Atom look like before your step 1?  Do you start Atom and then open multiple windows or do you have only a single window open?

If you close all the windows that are opened and then quit and restart Atom, do all the windows still reopen?  Was there any difference when you started in safe mode?

**Comment by TungBox** [comment]
Atom it's completely normal before I quit the application before step 1 (I open it by left clicking on the app).
I only start Atom with single window open.
If I close all the windows that are opened and then quit and restart Atom then its not reopening anymore. 
The problem is not happening in safe mode.

**Comment by rsese** [comment]
> The problem is not happening in safe mode.

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. You can disable each community package one by one to try and pinpoint which is causing the problem, or if you have a lot of installed packages, some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
