### ISSUE TITLE
Open dialog isn't displaying text enconding properly

### ISSUE THREAD

**Issue by devyaz** [atom/atom#17473]
![screenshot_20180605_153847](https://user-images.githubusercontent.com/20435017/40983416-e01b4104-68df-11e8-9cd7-99591aff3157.png)

**System: Archlinux(Bluestar linux)
Version:Atom (atom)  1.27.1-1**
**EDIT**
if i open from terminal as ROOT the it behaves as normal!! but why do i have to use terminal and not from the app launcher?

**Comment by rsese** [comment]
Thanks for reaching out!  Can you add the issue template information?  The information in the template is super helpful for us when triaging issues - once you add those details we can re-open and go from there.

For example, please confirm if you tried the steps in the `Prerequisites` section (in particular [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) and [temporarily resetting to factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults)).  Also, please share the specific version information from `atom -v` and confirm if you installed Atom using one of the [supported installation methods](https://flight-manual.atom.io/getting-started/sections/installing-atom/).

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
