### ISSUE TITLE
Hanging

### ISSUE THREAD

**Issue by 8Web8Designer8** [atom/atom#17472]
I have installed Atom recently, it is hanging when i open it,but not every time. I am getting alerts by windows that this program is not responding and asked me to force close it or keep waiting..
 
i5 5th gen
win 10 Home
x64
2.2GHz
8 gigs DDR 4
4 GB NVIDIA
DELL

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
