### ISSUE TITLE
Outdated packages (& misc. errors) when running bootstrap script on AWS Ubuntu 16.04

### ISSUE THREAD

**Issue by hwaltman19** [atom/atom#17487]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When running script/bootstrap, I receive the following errors:

> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
> npm WARN deprecated coffee-script@1.8.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
> npm WARN prefer global typescript@1.4.1 should be installed with -g
> npm WARN prefer global jasmine-node@1.10.2 should be installed with -g

### Steps to Reproduce

1. Clone atom
2. Change to atom directory
3. Run script/bootstrap

**Expected behavior:** The bootstrap script completes

**Actual behavior:** The bootstrap script fails

**Reproduces how often:** 100%

### Versions

Ubuntu 16.04
Node 8.11.2
Npm 5.6.0
Python 2.7

### Additional Information

I'd certainly be OK with fixing this myself, but I'm new here and don't know where to start

**Comment by thomasjo** [comment]
None of those entries you listed are errors, they are warnings. Unless you've configured things in a very specific way, they will not cause any build failures.

I suggest you look at how we run automated builds in [atom/ci](https://github.com/atom/ci). If that doesn't resolve your problem, please open a new issue and provide enough details for us to reproduce the problem and verify that this is actually a problem in Atom. Since this is unlikely to be a problem with Atom itself based on your description, I would recommend asking for the community help in our [Slack](https://discuss.atom.io/t/discussion-join-us-on-slack/25406) or on [Discuss](https://discuss.atom.io/).
