### ISSUE TITLE
open file in line:column from command line

### ISSUE THREAD

**Issue by fedelibre** [atom/atom#17515]
## Summary

Many editors allow to open a file in a precise position from the command line. The usual syntax is something like `editor +line:column file`. Here are a few examples (gedit and Visual Studio Code):

    gedit +line:column file
    code -g file:line:column

## Motivation

This is useful especially when you are debugging/grepping the code in a terminal and you want to jump to the exact location of a file you want to fix.

I have also a very specific use case. I write sheet music using an open source software called [lilypond](http://lilypond.org). lilypond converts music written as plain text to PDF. It can create PDF files containing textedit URIs to the precise point in the source file which generated the object in the PDF file that you clicked. This feature is called, in lilypond terms, point-and-click.

lilypond supports already a few editors (emacs, gvim, gedit and jedit), but I'd like to add more editors, including Atom. Without this feature I cannot include it.

## Describe alternatives you've considered

I've tried the [open package](https://atom.io/packages/open), but could not make it work. It opens the file but not at the desired line and column.

Also,  I believe this is a feature that should be part of Atom core and not be available only as plugin.

**Comment by lee-dohm** [comment]
Thanks  for reaching out.

Atom already supports this with the second syntax. For example, in this repo you could do `atom README.md:5:13` and end up with the cursor just before the "A" in "Atom" on this line:

```
[![Join the Atom Community on Slack](https://atom-slack.herokuapp.com/badge.svg)](https://atom-slack.herokuapp.com)
```

-----

Additionally, we require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

**Comment by lee-dohm** [comment]
I apologize about the issue template remark. I thought the new feature request template still included a requirement to test out things in Safe Mode. I was a little quick on the trigger there. My apologies :pray:

**Comment by fedelibre** [comment]
@lee-dohm This is great news! I've tested it and it works great alone and in combination with lilypond point-and-click.

However, this feature and its syntax is hidden, as it's not documented in `atom --help`. Can I change the title of this issue to reflect this request? Or better open a new issue?

**Comment by Ben3eeE** [comment]
@fedelibre Documenting this in `atom --help` sounds like a great idea. But I would suggest opening a new issue for this. Since this is a documentation change and not a feature request I would recommend using the issue template. For the steps to reproduce you could give an example of where you tried to find the documentation and expected to find it.

Even better would be if you open a PR or a series of PRs to add this documentation where you expected to find it 🙂
