### ISSUE TITLE
atom package install 

### ISSUE THREAD

**Issue by hanbing5210** [atom/atom#17526]
中国的atom无法使用官方提供的安装源但是中国国内有自己的安装源希望可以在atom中提供安装源切换或者自定义的方法。

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
