### ISSUE TITLE
Uncaught TypeError: ref.is is not a function

### ISSUE THREAD

**Issue by florianRichy** [atom/atom#17539]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Ubuntu 18.04
**Thrown From**: 'tree-view-open-files-updated' package vundefined

### Stack Trace

Uncaught TypeError: ref.is is not a function

```
At /home/florian/.atom/packages/tree-view-open-files-updated/lib/tree-view-open-files.coffee:27

TypeError: ref.is is not a function
    at /packages/tree-view-open-files-updated/lib/tree-view-open-files.coffee:27:27)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -1:54.9.0 tree-view:toggle (div.tool-panel.tree-view)
     -0:48.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.12.0 
atom-monokai 0.10.9 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
django-templates 0.5.0 
file-icons 2.1.21 
git-diff-details 1.4.0 
git-plus 7.10.2 
git-time-machine 2.1.0 
goto-definition 1.3.4 
highlight-selected 0.13.1 
ide-python 1.0.0 
intentions 1.1.5 
language-django 0.1.1 
linter 2.2.0 
linter-flake8 2.3.0 
linter-pydocstyle 0.4.7 
linter-python 3.1.2 
linter-ui-default 1.7.1 
MagicPython 1.0.12 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
monokai 0.24.0 
monokai-seti 0.9.0 
python-autopep8 0.1.3 
python-indent 1.1.5 
python-tools 0.6.9 
seti-ui 1.10.0 
split-diff 1.5.2 
todo-show 2.3.0 
```

**Comment by steveward** [comment]
Thanks for the report @florianRichy.

Can you confirm a few things for us?

- What were you doing at the time of the error?
- Is the error is reproducible?
- If reproducible, do you see the error in safe mode (atom --safe)?

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [tree-view-open-files-updated](https://atom.io/packages/tree-view-open-files-updated) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
