### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 1545, Calling function ArcanistService/isAr...

### ISSUE THREAD

**Issue by JaimeMoralesFB** [atom/atom#17543]
[Enter steps to reproduce:]

1. Set www-hg as working directory
2. open a terminal
3.  arc pull.
4.  Arc pull stops and terminal froze.

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 1545, Calling function ArcanistService/isArcSupported. Nuclide was trying to call to the remote Nuclide server. This usually means the server was not reachable, or the network connection is unreliable.

```
At /opt/facebook/nuclide/0.291.99692496/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

RpcTimeoutError: Timeout after 60000 for id: 1545, Calling function ArcanistService/isArcSupported. Nuclide was trying to call to the remote Nuclide server. This usually means the server was not reachable, or the network connection is unreliable.
    at Call._timeout (/opt/facebook/nuclide/0.311.112314201/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:178:20)
    at Call._timerId.setTimeout (/opt/facebook/nuclide/0.311.112314201/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:140:14)
```

### Commands

```
     -7:17.2.0 atom-ide-terminal:new-terminal (textarea.xterm-helper-textarea)
  3x -7:12.5.0 core:confirm (textarea.xterm-helper-textarea)
     -6:43.1.0 core:copy (textarea.xterm-helper-textarea)
     -6:24.4.0 diagnostics:toggle-table (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
 21x -5:57.3.0 core:undo (input.hidden-input)
     -5:24.2.0 fb-interactive-smartlog:toggle (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
file-icons 2.1.21 
highlight-selected 0.13.1 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
nuclide 0.315.113461661 
nuclide-format-js 0.0.46 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by JaimeMoralesFB** [comment]
Seems like this is an issue related to my devserver.
