### ISSUE TITLE
Atom Integration with KDE (using kwallet)

### ISSUE THREAD

**Issue by thommierother** [atom/atom#17575]
Current Atom release 1.28.x does not use the kwallet password repository in KDE. Instead atom calls gcr-prompter from Gnome and then starts gnome-keyring-daemon. But on a KDE system (plasma 5) normally there is no Gnome keyring, all passwords are stored through kwalletd instead. There should be a connector to kwallet and also a possibility to select the password manager through config.

**Comment by rsese** [comment]
Thanks for reaching out!

The issue template information is helpful for us when triaging issues - if you can add the template information to this issue we can re-open or if you can open a new issue with the template filled out, that would be super helpful.

In particular, in what context are you seeing this, through the GitHub package (https://github.com/atom/github/)?  Then what happens on KDE, is there an error of some kind?

Possibly related though it's been closed so it would be great to know more about what you're describing x-ref: https://github.com/atom/node-keytar/issues/17

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by thommierother** [comment]
@rsese: if you tell me how I can access the issue template either through the browser or atom, I could use it ;-) - until that, here are my answers to your questions:

**in what context are you seeing this?**
Atom 1.29 x64 as provided by SUSE through RPM package

**Then what happens on KDE, is there an error of some kind**
The issue appears if you store GitHub login information in atom. The data are stored in a local gnome keyring, where the KDE environment already has a keymanager (kdewallet database). The popup for the gnome keyring data delays the startup and there is no information that atom does NOT use the standard KDE environment here. People get confused if they already have a central password manager - there is no need for a gnome keyring file on KDE.

**Functional Requirements**
1. Add detection for KDE environment
2. When operating on KDE, save locally stored github login data in the kwallet database instead of a gnome keyring

**About https://github.com/atom/node-keytar/issues/17**
The mentioned patches/PRs (from @jalcine and @jathpala - dated back to 2015/16!) are not present in the current release 1.29 although this issue has been closed
