### ISSUE TITLE
cannot search for packages inside atom editor GUI inside virtual box behind corporate proxy

### ISSUE THREAD

**Issue by justdoGIT** [atom/atom#17617]
I am unable to search for packages inside the atom editor GUI. Although `apm `via command line is running fine. I am able to install packages via `apm install` command. 
But with GUI it throws some error:
`getaddrinfo EAI_AGAIN atom.io:443`
The atom version I am using is
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3 
I am working behind a proxy network and proxy settings are taken care off in the `~.apmrc `file.
One more thing that I am able to install featured packages via GUI but not search the new ones
I am working on 64-bit ubuntu 16.04 inside a virtual box with the host is Windows 10
Also, the atom is working fine with another Linux 32-bit machine in the same host inside a virtual box.

**Comment by rsese** [comment]
Thanks for the report @justdoGIT - this seems at least related or maybe a duplicate of  https://github.com/atom/settings-view/issues/1063 maybe if the general issue is `.apmrc` settings aren't used in the Settings view while they work fine using `apm` directly on the command line?

Also, have you always seen this behavior or is it new for you in 1.28/recent versions of Atom?

> Also, the atom is working fine with another Linux 32-bit machine in the same host inside a virtual box.

Is this VM also running Atom 1.28.0?

Lastly, for future issues please fill out the issue template.  The information in the template is super helpful for us when triaging issues.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by justdoGIT** [comment]
@rsese the atom version in the 32-bit machine is as follows
Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

Well I just shifted to a 64-bit ubuntu and before in 32-bit machine atom was working fine and regarding that template filling, I am still not able to understand what are you trying to say.

**Comment by jjakenichol** [comment]
I found the same issue on a corporate redhat machine. `apm install` works for me as well, after setting up the proxy settings. Interestingly, the GUI will still prompt to install package dependencies and they install successfully using the prompt. The issue seems isolated to the settings panel package installer.
