### ISSUE TITLE
Atom UI Seems to be blurry over all for some reason??

### ISSUE THREAD

**Issue by bhaviljain68** [atom/atom#17621]
Ok so this seems to happen randomly, but more recently its been consistent.
The Atom UI gets blurry, as you can see in the image. The code is shown crisp in the top part, but blurry in the bottom part. I tried changing the theme, but no difference (Default light and dark themes).

It gets clearer when I hover mouse over an element of the UI or a part of the code, and get blurrier and blurrier as I pull the mouse away from that element or part of code. 

I've check the windows display settings and the DPI is set to 100% only. 
 
![screenshot 78](https://user-images.githubusercontent.com/40825956/42272047-8f2dcc92-7fa2-11e8-989a-b0be5cd12cc0.png)

Running on Latest windows 10, 1080p 60hz screen. 
Asus ROG g751jy

UPDATE : 

Version ----
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

Debugging -----
Safe Mode : Tried , getting the same result with UI elements, but code if fine. Then again as i said this issue seems to be pretty random.
Other debugging suggestions such as clearing saved state etc. didn't seem relevant to this issue.
There are no incompatible packages. And all packages are up to date

Disabling GPU seems to have done the trick, but I think its best to check it for a few days, as agagin, it a pretty random issue. Though it seems that This would be a permanent solution :)  
Thank you for directing me to the GPU debugging suggestion.

PS : Any specific reason that this is happening on my GPU? Its a pretty powerful card GTX 980M (4GB). At least for running atom it is. Can it be caused because of certain change in GPU settings?? because this is happening only since a few days. Previously, since the past year or so that I have been using Atom io, atom never had this issue on this machine. Any ideas?

Also, am I loosing anything by disabling GPU?

Thanks,
Bhavil Jain

**Comment by rsese** [comment]
Thanks for reaching out!

The information in the issue template is super helpful for us, can you update your issue with that information?  E.g What version of Atom are you running (`atom -v`)?  Have you tried safe mode or any of the other suggestion in the debugging guide (https://flight-manual.atom.io/hacking-atom/sections/debugging)?  In particular have you tried this section?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by TheDecryptor** [comment]
Have you forced on AA or something in the Nvidia control panel or other utility? I vaguely remember Firefox having similar issues with ATI cards because their driver thought it was a game.

**Comment by bhaviljain68** [comment]
Hi Alex,

These are my global settings in nVidia Control Panel.
![screenshot 81](https://user-images.githubusercontent.com/40825956/42434806-11af6aa4-8372-11e8-8dec-507f86a5e28f.png)

**Comment by bhaviljain68** [comment]
So forced GPU disabled and setting nVidia to "Let 3D application Decide" instead of "Use advance 3D settings". Have not really helped much.
It better, but not fixed. 
I notice that the blur usually occurs when I've leave atom on the screen without doing anything for a few seconds (20-30s).
