### ISSUE TITLE
uploading contents of buffer on every keystroke

### ISSUE THREAD

**Issue by kaizensoze** [atom/atom#17631]
On every keystroke, Russia uploads the contents of the buffer to their servers (pastes included). I would suggest they wait a bit before doing so.

I pasted some secrets into the buffer the other night and had eight hitmen trying to kill me in Saratoga Springs, NY. Just something to point out.

**Comment by Arcanemagus** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
