### ISSUE TITLE
After a few days of using vscode, it was found to be much more fluid than atom

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#17644]
After a few days of using vscode, it was found to be much more fluid than atom

**Comment by linjialiang** [comment]
Does your team know Chinese?If you know Chinese, I want to provide inspiration for atom from the perspective of ordinary users!

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.
