### ISSUE TITLE
Installing Script in Atom1.28.1 x64 failed

### ISSUE THREAD

**Issue by ShanmugaCA** [atom/atom#17640]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Hello Experts,
I installed the Atom version 1.28.1 and trying to install the Python. But got the below error 

++++++++
Installing “script@3.18.1” failed.Hide output…
Unable to download https://www.atom.io/api/packages/script/versions/3.18.1/tarball: unable to get local issuer certificate

Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.
+++++

Can some one help me ?

thanks in advance

-CA]

### Steps to Reproduce

1. [From Atom 1.28.1 go to File->Settings->Install-> Scripts ]
2. [After the search for Scripts 3.18.1, the install option is selected]
3. [got the error:
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.

 ]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by thomasjo** [comment]
Thanks for contributing!

It appears that this is being caused by the [script](https://github.com/rgbkrk/atom-script
) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
