### ISSUE TITLE
Atom 1.28.1 won't start

### ISSUE THREAD

**Issue by Josh-Cropper** [atom/atom#17645]
As title states, I had to delete the app-1.28.1 folder within the AppData/Local/atom folder to get atom to launch. I can only assume there's a bug within it that was preventing it from launching on my system:

- Windows 10 Pro 64bit
- Version: 1803

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
