### ISSUE TITLE
Could not open the browser

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#17646]
![default](https://user-images.githubusercontent.com/8848263/42416227-765df574-829b-11e8-83e1-d3d9453db354.png)

**Comment by linjialiang** [comment]
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.1
python 3.6.5
git 2.18.0.windows.1
visual studio

**Comment by linjialiang** [comment]
> The link on the markdown file cannot be opened

![default](https://user-images.githubusercontent.com/8848263/42416264-98eda1b0-829c-11e8-8a5d-543dda9350eb.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
