### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Bikefast** [atom/atom#17650]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lee-dohm** [comment]
@Bikefast I'm not sure what it is you want help with, but it doesn't seem like Atom is the problem here. Atom isn't a picture viewing application.

In any case, we _require_ the issue template to be completed on all new issues, which you've ignored twice now. Continuing to open new issues while ignoring the issue template will be considered harassment under the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) and will result in your temporary or permanent banning from the Atom organization. You may consider this an official warning.

**Comment by Bikefast** [comment]
Sorry I'm new at this. Was trying to figure out how to open these encrypted files

**Comment by lee-dohm** [comment]
Atom doesn't handle encrypting or decrypting files. You'll need some other tool for that.
