### ISSUE TITLE
Crash and unable to reopen after download of 1.28.1 

### ISSUE THREAD

**Issue by jlc-christie** [atom/atom#17654]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Not sure if this is related to a previous issue I posted #17599 or not, but Atom downloaded 1.28.1 in the background and then atom wouldn't open after that. Deleted the folder in C:/Users/{user}/AppData/Roaming and renamed the .atom directory but didn't fix the issue. 

Eventually fixed the issue by deleting the app-1.28.1 directory in C:/Users/{user}/AppData/Local/atom

Not entirely sure how atom updates work but not sure if atom was running on 1.28.1 when it wouldn't open or if it was just downloaded and not installed?

Hope this helps some people. 

### Steps to Reproduce

1. Can't confirm it happens every time it downloads, will keep updated if it happens again. 

**Expected behavior:** Atom to update/be able to continue to use atom after an update

**Actual behavior:** 

**Reproduces how often:** Does not open after restarts, and after doing things I tried above etc. but haven't reproduced since.

### Versions

```
C:\Users\jlc_c>atom --version

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

C:\Users\jlc_c>apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python
visual studio

```

**Comment by rsese** [comment]
Thanks @jlc-christie - it's hard to say if there's a specific new issue here or if it's related to the crash you started seeing in 1.28.0.  E.g. though the circumstances are different, there was [another report of a crash with 1.28.1](https://github.com/atom/atom/issues/17663).   There's also an open issue about updating Atom on Windows that I can't find right now but could be related.

Is there any difference if you just download the installer and use that rather than updating?  If that still crashes right away in safe mode, do you see any output if you start Atom in the foreground?

```
atom --foreground
```
