### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reset' of null

### ISSUE THREAD

**Issue by czfadmin** [atom/atom#17678]
**Atom**: 1.29.0-beta1 x64
**Electron**: 2.0.4
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of null

```
At C:\Users\chen28\AppData\Local\atom\app-1.29.0-beta1\resources\app\src\tokenized-line.js:20

TypeError: Cannot read property 'reset' of null
    at TokenizedLine.module.exports.TokenizedLine.getTokenIterator (~/AppData/Local/atom/app-1.29.0-beta1/resources/app/src/tokenized-line.js:20:39)
    at SymbolStore.recomputeSymbolsForEditorInBufferRange (~/AppData/Local/atom/app-1.29.0-beta1/resources/app/node_modules/autocomplete-plus/lib/symbol-store.js:156:49)
    at ~/AppData/Local/atom/app-1.29.0-beta1/resources/app/node_modules/autocomplete-plus/lib/symbol-provider.js:420:43
    at ~/AppData/Local/atom/app-1.29.0-beta1/resources/app/node_modules/underscore/underscore.js:768:25
```

### Commands

```
     -1:03.5.0 application:open-folder (atom-pane.pane.active)
     -0:54.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.22 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.7 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.3 
seti-icons 1.5.4 
tool-bar 1.1.7 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by czfadmin** [comment]
@rsese 
This problem occurs when I check Enable Extended Unicode Support in the Autcomplete plus plugin. When I don't select this option, the problem will disappear.
![13](https://user-images.githubusercontent.com/13393959/42666342-0fb32eb8-8677-11e8-9e50-ebfd44c81a65.png)

**Comment by rsese** [comment]
Thanks @czfadmin - so just to clarify, if you toggle that box while running in safe mode, the error pops up or do you have to do something specific first before the error shows up?

**Comment by czfadmin** [comment]
@rsese 
When I do this in safe mode,this  problem does not happen when writing a file (.ts).This should be caused by the plugin I installed.

**Comment by rsese** [comment]
> When I do this in safe mode,this problem does not happen when writing a file (.ts).This should be caused by the plugin I installed.

:+1:  Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem.  You can disable all community packages and re-enable one-by-one or some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Comment by tonypine** [comment]
Hi, I'm having this issue, from a the [atom-aligner](https://github.com/adrianlee44/atom-aligner) package, but I was trying to figure out the problem, and it seems that this line in the [three-sitter-language-mode:449](https://github.com/atom/atom/blob/master/src/tree-sitter-language-mode.js#L449) is simply passing `null` as the `tokenIterator`, and later on the [tokenized-line:15](https://github.com/atom/atom/blob/master/src/tokenized-line.coffee#L15) it assumes that the `tokenIterator` is defined.

Do you guys have any idea of what is the real problem? If someone could give me a north of what should be happening, I could do a PR to fix this.
