### ISSUE TITLE
Atom editor opacity backgroud wandted

### ISSUE THREAD

**Issue by GHLandy** [atom/atom#17695]
I've using Atom editor for a long time. 
I now want to set Atom editor opacity backgroud by settings,
but there is no entrance to my need.
Although there is some way to reach, ie, build from source code.

Can Atom provide this feature in Atom settings for end users.

**Comment by rsese** [comment]
Thanks for the suggestion - it looks like this was asked for in https://github.com/atom/atom/issues/9321 and discussed in [posts](https://discuss.atom.io/t/background-transparency) on the message board but it's not something the team has prioritized looking into.  Since https://github.com/atom/atom/issues/9321 was eventually closed as stale, I don't think that will change unfortunately anytime soon so I'll close this for now.  The team would however be willing to look at a well-written pull requests if someone in the community puts one together.
