### ISSUE TITLE
Atom IO build not working or Bootstrap/script

### ISSUE THREAD

**Issue by BooRar** [atom/atom#17697]
> script/bootstrap

>Node:   v8.11.2
>Npm:    v5.6.0
>Python: v2.7.10
>Installing script dependencies
>npm ERR! Unexpected end of JSON input while parsing near '..."_hasShrinkwrap":fals'

>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Jono\AppData\Roaming\npm-cache\_logs\2018-07-16T08_00_29_037Z-debug.log
>child_process.js:624
    throw err;
    ^

>Error: Command failed: npm.cmd --loglevel=error install
>npm ERR! Unexpected end of JSON input while parsing near '..."_hasShrinkwrap":fals'

>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Jono\AppData\Roaming\npm-cache\_logs\2018-07-16T08_00_29_037Z-debug.log

>    at checkExecSyncError (child_process.js:601:13)
 >   at Object.execFileSync (child_process.js:621:13)
>    at module.exports (C:\eleclearn\atom\atom\script\lib\install-script-dependencies.js:9:16)
>    at Object.<anonymous> (C:\eleclearn\atom\atom\script\bootstrap:28:1)
>    at Module._compile (module.js:652:30)
 >   at Object.Module._extensions..js (module.js:663:10)
 >   at Module.load (module.js:565:32)
>    at tryModuleLoad (module.js:505:12)
>   at Function.Module._load (module.js:497:3)
>    at Function.Module.runMain (module.js:693:10)

**Comment by BooRar** [comment]
[2018-07-16T08_00_29_037Z-debug.txt](https://github.com/atom/atom/files/2196967/2018-07-16T08_00_29_037Z-debug.txt)

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
