### ISSUE TITLE
Using latest RegExp features in package

### ISSUE THREAD

**Issue by mstmustisnt** [atom/atom#17748]
I would like to use latest regexp features like `s` flag, or named groups etc. Currently, electron is using a bit old chromium version
> $ npm i -D electron@latest
> Electron   2.0.5
> Node       8.9.3
> Chromium   61.0.3163.100

After electron v3 release new regexp features will work. But I need to get them work now. 
How can I add [babel-plugin-transform-modern-regexp](https://www.npmjs.com/package/babel-plugin-transform-modern-regexp).

**Comment by rsese** [comment]
Thanks for reaching out!

I see that you've asked this question in the Atom Slack and you've received some feedback there :+1:  Along with the message board, those are the best places to ask questions.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
