### ISSUE TITLE
Error fetching from carbon: 500 - Internal Server Error

### ISSUE THREAD

**Issue by pajaskowiak** [atom/atom#17778]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 18.04.1
**Thrown From**: Atom Core

### Stack Trace

Error fetching from carbon: 500 - Internal Server Error

```
At undefined

undefined
```

### Commands

```
  6x -3:53.3.0 core:move-left (input.hidden-input)
     -3:52.2.0 core:move-down (input.hidden-input)
  3x -3:52.1.0 core:move-left (input.hidden-input)
     -3:51.4.0 core:backspace (input.hidden-input)
     -3:49.9.0 core:move-down (input.hidden-input)
     -3:49.6.0 core:delete (input.hidden-input)
     -3:49.3.0 core:move-down (input.hidden-input)
     -3:48.9.0 core:delete (input.hidden-input)
  4x -3:48.5.0 core:move-up (input.hidden-input)
     -3:47.6.0 editor:move-to-first-character-of-line (input.hidden-input)
     -3:47.4.0 editor:newline (input.hidden-input)
     -1:08.8.0 carbon:copy (input.hidden-input)
     -1:06.9.0 core:select-all (input.hidden-input)
     -1:03.0 carbon:copy (input.hidden-input)
     -0:36.3.0 settings-view:open (input.hidden-input)
  2x -0:13.5.0 carbon:copy (div.tool-panel.tree-view)
```

### Non-Core Packages

```
carbon 0.3.0 
carbon-now-sh 2.0.3 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [carbon](https://atom.io/packages/carbon) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
