### ISSUE TITLE
context menu sometimes close themselves in random fashion

### ISSUE THREAD

**Issue by acrixl** [atom/atom#17773]
### Prerequisites

no debug steps performed, float problem

### Description

context menu sometimes close themselves in random fashion

### Steps to Reproduce

try to open context menu after start and wait

**Expected behavior:** no random behavior

**Actual behavior:** wild behavior

**Reproduces how often:** not often

### Versions

tags/v1.29.0

### Additional Information

debian

not sure it bug or feature?

**Comment by lee-dohm** [comment]
Have you tried reproducing the problem in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? Behavior such as this could be caused by one of the packages you have installed. Using Safe Mode allows us to exclude that as a variable. This is why we require it as part of the issue template.

-----

Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
