### ISSUE TITLE
Unable to start atom beta error: unexpected

### ISSUE THREAD

**Issue by gemal** [atom/atom#17786]
Came back from vacation and updated a few program and suddenly atom does not start.

it starts the process but no interface:

```
C:\Users\gemal\AppData\Local\atom\app-1.30.0-beta1>atom --version

C:\Users\gemal\AppData\Local\atom\app-1.30.0-beta1>
Atom    : 1.30.0-beta1
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3


C:\Users\gemal\AppData\Local\atom\app-1.30.0-beta1>atom --foreground

C:\Users\gemal\AppData\Local\atom\app-1.30.0-beta1>
unexpected
[stdin]:1:1: error: unexpected
```

I tried to uninstall and remove the "Atom" folder in `C:\Users\gemal\AppData\Roaming\`

when it starts it just creates an empty Atom folder plus a empty logs folder

What can I do to help?

I updated JRE to version 1.8

**Comment by rsese** [comment]
Thanks for reaching out!

The information in the issue template is super helpful for us when triaging issues - if you can edit the issue body to include the template information we can re-open and go from there.  For example, have you tried any of the suggestions in the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/) like safe mode or temporarily resetting to factory defaults?  What version of Windows are you running?

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by gemal** [comment]
config.cson was corrupted. Filled will "NUL" entries
Removing that file make it start again

**Comment by rsese** [comment]
Thanks for the details - temporarily resetting to factory defaults would have gotten Atom running too but it's useful to see that you narrowed it down to the config file :+1:
