### ISSUE TITLE
Atom editor crashes on opening MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by William-N** [atom/atom#17787]
GUI window displays empty with blueish tint on application opening, when background color turns white and error message displays 'The editor has crashed'. Application deletion and reinstallation does not resolve the issue, previous versions held no issues.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
