### ISSUE TITLE
I cant RUN ATOM after install 

### ISSUE THREAD

**Issue by syauqiragi** [atom/atom#17793]
I have problem. my atom cant show but in the background process atom running. how should i do????
i have install and uninstall several times but still doesnt work.
HELP PLEASE

**Comment by gemal** [comment]
same as #17786 I think

**Comment by rsese** [comment]
Thanks for reaching out!

> same as #17786 I think

Thanks @gemal - that could be what you're running into @syauqiragi so you can check your config.cson file, but I'd recommend going through some of the debugging steps in the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/) as mentioned in the issue template.

Try safe mode and temporarily resetting to factory defaults and if you still have trouble, please open a new issue and fill out the issue template and we'll take a look.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
