### ISSUE TITLE
CSS classes do not match reported cursor scopes with Tree-Sitter parser

### ISSUE THREAD

**Issue by robertrossmann** [atom/atom#17859]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With Tree-Sitter parser enabled, the CSS classes attached to a DOM node representing a piece of JavaScript code do not match the scopes listed via the `Log Cursor Scope` command. As per the [Flight Manual](https://flight-manual.atom.io/behind-atom/sections/scoped-settings-scopes-and-scope-descriptors/#scope-names-in-syntax-tokens), they should be identical:

> Scope names work just like CSS classes. In fact, in the editor, scope names are attached to a token's DOM node as CSS classes.

### Original intent

I wanted to customise the look of a particular syntax structure using CSS. I expected that if I write the following CSS override it would match the intended parts of the code with the new look:

```css
.object .pair .property-identifier {
  // custom CSS here
}
```

However, the snippet did nothing, which lead me to realise that the DOM node does not have this class.

### Steps to Reproduce

1. Enable Tree-Sitter parsers
1. Open JavaScript file
1. Place the cursor on an object literal's property identifier
1. Open DevTools and inspect that element
1. Log the cursor scope (Command Pallette -> Log Cursor Scope)
1. Observe difference in the scopes listed in the notification and the scopes listed on the DOM node

**Expected behavior:**

The DOM node would have the same classes attached as the scopes shown in the notification

**Actual behavior:**

The DOM node has CSS classes which do not correspond to any of the listed scopes

**Reproduces how often:**

All the time in JavaScript files with Tree-Sitter enabled

### Versions

```
Atom    : 1.31.0-nightly7
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
apm  2.1.0
npm  6.2.0
node 8.9.3 x64
atom 1.31.0-nightly7
```

### Additional Information

Screenshot follows.

![screenshot 2018-08-14 at 12 40 07](https://user-images.githubusercontent.com/3058150/44087603-a606248a-9fc0-11e8-8293-6d2050ff3ff9.png)

**Comment by Aerijo** [comment]
The translation of nodes to scopes is defined [here](https://github.com/atom/language-javascript/blob/master/grammars/tree-sitter-javascript.cson#L50). I don't know if this is customisable yet.

**Comment by robertrossmann** [comment]
Thanks for the pointers, but even after looking at that translation the attached css classes still do not fully match with the `.syntax--` prefix everywhere. Not sure if this is by design (I assume as much) and if so, I think the Flight manual is not accurate in that case...? 🤔

**Comment by Aerijo** [comment]
Yep, `syntax--` is intentional. I couldn't see an obvious reference to it in the flight manual, but it's mentioned in [appendix B](https://flight-manual.atom.io/shadow-dom/sections/removing-shadow-dom-styles/#syntax--)

**Comment by maxbrunsfeld** [comment]
Yeah, I'm not sure what to do about this.

With Tree-sitter, there's a difference between the HTML classes and the syntax tree. We use the nodes in the syntax tree to construct "scope descriptors", which are the basis for scoped config settings and other things. The HTML classes that are used for syntax highlighting are derived from the syntax tree based on scope mappings, as @Aerijo [mentioned](https://github.com/atom/atom/issues/17859#issuecomment-412842064).

With TextMate grammars, there was no difference. Every thing that came out of the grammars was translated directly into HTML classes.

When Tree-sitter is enabled, should we change the `Log Cursor Scope` command to print the HTML classes instead of the scope descriptor? I tend to think we should leave it as is, because `Log Cursor Scope` is the main way to discover scope descriptors, which the user might want for scoped settings, whereas if you're writing a syntax theme, you can always find the HTML classes you need by opening up the dev tools.

Does anyone have suggestions about how to solve this?

**Comment by Aerijo** [comment]
> When Tree-sitter is enabled, should we change the Log Cursor Scope command to print the HTML classes instead of the scope descriptor?

We could make two separate functions to do both.
- `Log Cursor Scope` always for CSS scopes
- `Log Cursor Tree Path` for the syntax tree path... name is open to changes. When using a non-Tree-sitter grammar, it would make the notification say something like `The syntax tree is only available for Tree-sitter grammars`

Related; we should also have a way to target the syntax nodes directly. For the end user, it might look like 
```javascript
atom.grammars.getGrammar("javascript").addScopes({
  "node": "css-selector"
})
```

Or it could go in a dedicated JSON / CSON file like this
```cson
javascript: # the id of the grammar
  scopes:
    "node": "css-selector"
```

I added `scopes` in the middle, because it allows for the other grammar properties to be added. The final result could then be a merge of the package file & the user file, and even other packages that want to add their own node-to-selector rules. Conflict handling can be done by specificity, or with a "important" flag, like `"!important node": "css-selector"`

**Comment by maxbrunsfeld** [comment]
Alright, came to a decision. We're changing scope descriptors to make them match the CSS, not the syntax tree. Maybe later we'll add a command for conveniently displaying the tree path as @Aerijo suggested. We can always dig up the previous code from the git history if needed.
