### ISSUE TITLE
Atom keeps loading the output forever..

### ISSUE THREAD

**Issue by blazenoob** [atom/atom#17878]
the title says it all. I am running python atom on windows and there is one particular file that it isn't running. it is running other commands and strings but not this one:

import os
import time
source = ['"C:\\takebackup"']
target_dir = 'E:\\putbackup'
if not os.path.exists(target_dir):
    os.mkdir(target_dir) 
today = target_dir + os.sep + time.strftime('%Y%m%d')
now = time.strftime('%H%M%S')
comment = input('Enter a comment --> ')
if len(comment) == 0:
    target = today + os.sep + now + '.zip'
else:
    target = today + os.sep + now + '_' + \
        comment.replace(' ', '_') + '.zip'
if not os.path.exists(today):
    os.mkdir(today)
    print('Successfully created directory', today)
zip_command = 'zip -r {0} {1}'.format(target,
                                      ' '.join(source))
print('Zip command is:')
print(zip_command)
print('Running:')
if os.system(zip_command) == 0:
    print('Successful backup to', target)
else:
    print('Backup FAILED')

Please help.

**Comment by lee-dohm** [comment]
Atom doesn't execute code by itself. See the [Atom FAQ](https://discuss.atom.io/t/how-do-i-build-or-execute-code-ive-written-in-atom/25341) for more details.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
