### ISSUE TITLE
Alignment mismatch in atom about page/tab

### ISSUE THREAD

**Issue by amoghesturi** [atom/atom#17896]
With Love from Github seems to be misaligned. It is not aligned to the middle vertically.

<img width="580" alt="screen shot 2018-08-22 at 10 07 38 am" src="https://user-images.githubusercontent.com/8497808/44444048-72206c00-a5f8-11e8-8aeb-8afa3a2f1f35.png">

**Comment by rsese** [comment]
Thanks very much for the report!

I'm honestly not sure if this is intentional (I thought it was?) but would you mind reopening this issue in the https://github.com/atom/about repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

If you can also use the issue template in the new issue, that would be helpful too.

Thanks for meeting us half way 👍
