### ISSUE TITLE
Atom 1.29.0 editor has crashed on startup in windows 7

### ISSUE THREAD

**Issue by tobassum** [atom/atom#17890]
Hello
I install atom version 1.29.0 in windows 7 64 bit version. its work fine but now its crashed on startup. Solve this issue i really need this tool.
![capture](https://user-images.githubusercontent.com/12109257/44410135-756e1600-a56c-11e8-9a1a-f426e0da6c23.PNG)

**Comment by rsese** [comment]
Thanks for reaching out!  As mentioned below, please fill out the template details and we can re-open and go from there.

In particular, please confirm which debugging steps you've tried and if they had any effect (safe mode, temporarily resetting to factory defaults, etc.).

And just to confirm, Atom worked fine with previous versions but once you installed 1.29 it started crashing on startup?

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by tobassum** [comment]
open in safe mode is working good but not working in normal mode. I install and reinstall the previous version and new version get same problem here.

**Comment by Aerijo** [comment]
> open in safe mode is working good but not working in normal mode

This indicates a problem in a community package, or your init script. You will need to debug this yourself (disabling packages until you isolate it), and raise the issue with the relevant repo if you find it.

**Comment by rsese** [comment]
> OK i fix this problem. I delete the folder from C:\user.atom and re launch the application is working fine.

Installed community packages are placed in this directory so deleting it basically uninstalled all the community packages you have.  If you end up reinstalling the packages you had before, you could end up with the same issue - in this case, you need to figure out which package is causing the issue like @Aerijo mentioned (you can disable all packages and enable them one-by-one for example) and then open an issue in that package's repository.
