### ISSUE TITLE
Atom racer is not properly configured.

### ISSUE THREAD

**Issue by Maxgy** [atom/atom#17916]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.7
**OS**: linux 4.18.3-arch1-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Atom racer is not properly configured.

```
At undefined

undefined
```

### Commands

```
  2x -2:07.2.0 intentions:highlight (input.hidden-input)
     -2:06.3.0 platformio-ide-terminal:toggle (input.hidden-input)
     -1:52 intentions:highlight (input.hidden-input)
     -1:52 core:save (input.hidden-input)
     -1:41 intentions:highlight (input.hidden-input)
     -1:40.7.0 core:close (input.hidden-input)
     -1:23.9.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
     -1:02.1.0 application:add-project-folder (textarea.)
     -0:51.6.0 intentions:highlight (input.hidden-input)
     -0:51.5.0 core:save (input.hidden-input)
 11x -0:17.6.0 core:move-up (input.hidden-input)
  2x -0:16.3.0 editor:newline (input.hidden-input)
  2x -0:16 core:move-up (input.hidden-input)
  4x -0:14.4.0 core:backspace (input.hidden-input)
     -0:04.2.0 autocomplete-plus:confirm (input.hidden-input)
     -0:04.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Non-Core Packages

```
atom-beautify 0.33.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 1.4.3 
file-icons 2.1.24 
intentions 1.1.5 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.9.0 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.8.4 
racer 0.20.0 
rustfmt 0.1.3 
teletype 0.13.3 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [racer](https://atom.io/packages/racer) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
