### ISSUE TITLE
Feature request: Create multiple files over the file dialog

### ISSUE THREAD

**Issue by lenovouser** [atom/atom#17919]
Same as #13102, I can't reopen it... Why does it get closed automatically without an option to reply?

I'd love to be able to use something similar to the UNIX `touch` or `mkdir` syntax in order to create multiple folders and / or files with the file create dialog. Something like this:

![](https://i.lenovouser.me/tpLBHe1a0X9KQGRd.png)

**Comment by rsese** [comment]
Sorry about that @lenovouser - we should have replied after your comment in your original issue and  either closed it or added a label to it so it wouldn't get closed.

I went ahead and double checked with the team for you about this particular functionality and while they think it's a useful shortcut, it's not something that would be prioritized.  Additionally, the functionality could be provided through a package and it looks like it already was for a while with https://github.com/sedabull/new-file-plus and https://atom.io/packages/advanced-new-file, but those packages aren't maintained anymore unfortunately.

So since this isn't something the team would work on and because it could be provided with a package, we're going to close this for now but we can re-open if anything changes.
