### ISSUE TITLE
Editor crashed after packages installation

### ISSUE THREAD

**Issue by martin-sk** [atom/atom#17931]
Hello,
I use Ubuntu 18.04 and Atom 1.29.0 x64 for Linux.
I use only this packages without error:
https://github.com/Feridum/atom-html-templates
https://github.com/file-icons/atom
https://github.com/james2doyle/atom-jquery-snippets
https://github.com/abe33/atom-pigments.

Every time, when I try install other new package, Editor go to error (stop working). When I manually remove package everything is OK.

**Comment by rsese** [comment]
Thanks for reaching out!

The information in the issue template is super helpful for us when triaging issues - if you can edit the issue body to include the template information we can re-open and go from there. 

Also, you say:

> when I try install other new package, Editor go to error (stop working). When I manually remove package everything is OK.

So after installing the 4 packages you mentioned above, installing any other package will cause Atom to crash?  Or is it only a specific package?

Lastly, can you confirm how you installed Atom on Ubuntu?

----

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by vceron** [comment]
I have a pure (no installed packages) install of Atom 1.29.0 x64 on an Ubuntu 18.04, and it crashes very often.
![image](https://user-images.githubusercontent.com/2420834/45870942-7624e280-bd8c-11e8-9282-dbe2574e4a86.png)

I installed it using apt

PS . I choosed "Sent an error report ..." option, do you receive this kind of information or where does it go?

**Comment by rsese** [comment]
@vceron - go ahead and open a new issue and fill out the issue template and we can take a look.



> PS . I choosed "Sent an error report ..." option, do you receive this kind of information or where does it go?

I believe that's [Ubuntu specific error reporting](https://wiki.ubuntu.com/ErrorTracker#Anatomy_of_a_crash) and doesn't come to us.
