### ISSUE TITLE
Tree-Sitter: Invalid scope detected for empty JavaScript lines

### ISSUE THREAD

**Issue by robertrossmann** [atom/atom#17942]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With Tree-Sitter enabled, inside a JavaScript file, the scope is reported as `*` if the cursor is placed on an empty line. This causes JavaScript code snippets to not work at all.

As soon as I place the cursor on any piece of code the scope is properly reported as being `source.js` + whatever syntax node is currently under the cursor.

### Steps to Reproduce

1. Enable Tree-Sitter parsers
1. Create a new, empty JavaScript file or open an existing JS file and place the cursor on an empty line (ie. the last line)
1. Log the cursor's scope
1. Observe scope being reported as just `*` instead of `source.js`

**Expected behavior:** Scope is always reported as `source.js` regardless of whether or not there is a syntax node under the cursor

**Actual behavior:** Scope is reported as `*` when there is no syntax node under the cursor

**Reproduces how often:** All the time, for JavaScript files only (tested with `Makefile`, `.json`, `.yaml`, `.sql`, scopes work correctly here)

### Versions

```
Atom    : 1.32.0-nightly3
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

I think this started happening sometime around 1.31.0-nightly6, not sure precisely when.

**Obligatory screenshot** with the scopes Atom reported as I tested it with various files.

![scopes](https://user-images.githubusercontent.com/3058150/44769816-1f016880-ab66-11e8-9abc-f3d38deaaa63.png)

**Comment by thomasjo** [comment]
Just a minor correction here to avoid any confusion for whomever decides to tackle this issue; the cursor scope is **not** being reported as `*` by Tree-sitter. The `*` is simply a Markdown rendering artifact caused by producing an unordered list item with no body. In other words, we're only producing an asterisk because the scope reported by Tree-sitter (or possibly something in Atom core) is blank.

For reference:
* https://github.com/atom/atom/blob/2f827bfc23260eece024b8f179421fa833b1834d/src/register-default-commands.coffee#L330-L335
* https://github.com/atom/atom/blob/bc00369f7f4e42f3275f11e81b47310fd1d60a6a/src/text-editor.js#L3880-L3882

**Comment by maxbrunsfeld** [comment]
Actually, we're going to ship the fix before that PR lands. It'll go out in 1.31.0-beta1.
