### ISSUE TITLE
itsNotATrap show up in autocomplete.

### ISSUE THREAD

**Issue by amirh3n** [atom/atom#17954]
every time I try to write code itsNotATrap show up.

![image](https://user-images.githubusercontent.com/26250189/44865836-a9e28000-ac98-11e8-8345-85099bfd7d66.png)

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
