### ISSUE TITLE
 I can not install the beautify plugin!!.

### ISSUE THREAD

**Issue by AngeelMt** [atom/atom#17965]
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated jscs-preset-wikimedia@1.0.1: Deprecated in favour of eslint-config-wikimedia. -- https://phabricator.wikimedia.org/T118941
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! Darwin 16.7.0
npm ERR! argv "/private/var/folders/5q/cpnv31tx7vdg6gqw4g5bsdhh0000gn/T/AppTranslocation/19B49AF1-137B-4CF0-9895-255D89BF3BD5/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/5q/cpnv31tx7vdg6gqw4g5bsdhh0000gn/T/AppTranslocation/19B49AF1-137B-4CF0-9895-255D89BF3BD5/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/luismartinez/.atom/.apm/.apmrc" "--userconfig" "/Users/luismartinez/.atom/.apmrc" "install" "/private/var/folders/5q/cpnv31tx7vdg6gqw4g5bsdhh0000gn/T/d-11881-13844-8c6lsj.3vxuyds4i/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/luismartinez/.atom/.apm/marko/4.13.3/package.tgz archive: ENOENT: no such file or directory, open '/Users/luismartinez/.atom/.apm/marko/4.13.3/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/5q/cpnv31tx7vdg6gqw4g5bsdhh0000gn/T/apm-install-dir-11881-13844-750qy6.jaen17zaor/npm-debug.log

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), questions like this would be better for the official message board (https://discuss.atom.io/).  The package repository's issues list could be helpful too - in particular, it seems like the same error was reported here:

https://github.com/Glavin001/atom-beautify/issues/2219

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
