### ISSUE TITLE
Atom crashes after installing atom-compile-less

### ISSUE THREAD

**Issue by theking2** [atom/atom#17975]
### Description

after installing package atom-compile-less atom crashes upon start.
### Steps to Reproduce

1. open atom
2. under Settings install package atom-compile-less
atom crashes after install, and from thereon everytime it is openend

### Versions
npm  3.10.10
node 6.9.5 x64
atom 1.30.0

Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://atom.io/packages/atom-compile-less package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
