### ISSUE TITLE
Updating Atom takes more than one "Restart and Install..." click (macOS)

### ISSUE THREAD

**Issue by robertrossmann** [atom/atom#17976]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When updating Atom with a project opened (see below for explanation), I have to click "Restart and install..." twice. The first time I click from the `About` package - this closes the Atom's window but keeps the application running. Then I have to click "Restart and install..." from the menubar to actually update Atom.

### Steps to Reproduce

1. Open Atom
1. Wait for an update
1. From the `About` package, click "Restart and install"
1. Observe Atom window closing but Atom app still running in foreground
1. From the menubar, click "Restart and install..." again
1. Finally have Atom restart itself and install the update

**Expected behavior:** Clicking the button from the `About` package immediately restarts Atom and install the update.

**Actual behavior:** Clicking the button only closes Atom window but keeps the app running in foreground, forcing me to click the menubar's "Restart and install..." menubar item to actually update Atom

**Reproduces how often:** All the time for Atom, Atom Beta and Atom Nightly

### Versions

```
Atom    : 1.32.0-nightly6
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

Only tested on macOS (High Sierra and Mojave).
This has been happening for several months now, I just did not find the time to report this. 😇

**While there is only a single, empty (non-project) Atom window opened, the update procedure works as expected:**

1. Open fresh new Atom window only (tested from CLI via `atom-nightly --new-window`
1. Wait for an update
1. From the `About` package, click "Restart and install"
1. Atom updates as expected

It looks like some project-related code path is keeping the Atom app from restarting itself correctly. 🤔

**Comment by rsese** [comment]
Thanks for the report @robertrossmann - since I started using the nightlies, I've noticed this too.

> While there is only a single, empty (non-project) Atom window opened, the update procedure works as expected:

Similarly, if there are no windows open (but Atom is still running) updating works with a single `Atom > Restart and install` from the menubar.

**Comment by jsg2021** [comment]
This has hit everyone in my office using Atom. On every update. It has never worked as expected. I'm happy to provide any info if need be... just let me know what to gather.

**Comment by daviwil** [comment]
Here are some notes from the investigation so far:

If you comment out [this line](https://github.com/atom/atom/blob/master/src/main-process/atom-application.js#L388), the "Restart and Install Update" action restarts Atom as expected but Atom's state is not reloaded correctly after the update is installed.  The result is that it starts up an Atom window with no project loaded.  Apparently the `this.quitting = true` line was [added](https://github.com/atom/atom/commit/844cfcb7aeb87589710d0a56fe24155a08872b81) to fix this precise problem in https://github.com/atom/atom/pull/7234

With the `this.quitting = true` assignment in place, one thing you'll see in Atom's console log output is the following statement right before the update process stalls:

```
Sending message to WebContents with unknown ID 1
```

My suspicion here is that since the browser window is not prevented from being closed here (`event.preventDefault()` is not called in [this event handler](https://github.com/atom/atom/blob/master/src/main-process/atom-window.js#L168)), the window closes before some future message passing occurs between the main process and renderer process,   causing Atom's shutdown process to stall before the app fully shuts down.  We may need to inherit some of the logic of the non-`quitting` code path so that the shutdown process can complete its operations and close cleanly.
