### ISSUE TITLE
Config error when changing electron version

### ISSUE THREAD

**Issue by andrewmiller1** [atom/atom#17973]
I need some help building atom with electron 4. I'm willing to fix all the errors with the actual code. However, I'm having trouble navigating unrelated things like node-pre-gyp and other build configurations.

I'm used to things breaking when changing dependencies to major versions. But I can't see what possible errors will happen if I can't get the build steps to agree to try.

I got fiddle and also xray to work just fine. But I need a serious editor and was hoping to hack atom.

4.0.0-nightly.20180821

**Comment by rsese** [comment]
Thanks for reaching out!

The best places to get this type of help are the Atom Slack and the message board, linked to below.  I haven't tried building Atom with a different version of Electron so can't provide any advice myself unfortunately.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
