### ISSUE TITLE
Can't install packages, but themes work fine

### ISSUE THREAD

**Issue by MarwanB1** [atom/atom#18037]
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\bakrm\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\bakrm\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\bakrm\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\bakrm\\.atom\\.apmrc" "install" "C:\\Users\\bakrm\\AppData\\Local\\Temp\\d-118811-12940-uk4yx.1fvz1o47vi\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\bakrm\.atom\.apm\typescript-compiler\1.3.0\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\bakrm\.atom\.apm\typescript-compiler\1.3.0\package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bakrm\AppData\Local\Temp\apm-install-dir-118811-12940-8mia8w.q3k0kq33di\npm-debug.log

I've been trying to download packages, but none of the packages work. This is the error message shown when I tried to install preview-plus. Can anybody help with this?

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), questions like this would be better on the official message board (https://discuss.atom.io/) unless a specific bug in Atom is identified.  

Also you mentioned preview-plus - it looks like the install error you shared for that particular package has been reported already e.g.:

https://github.com/skandasoft/preview-plus/issues/58

So to clarify, you're getting this same error for any other packages you've tried to install?  Which other ones have you tried?

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
