### ISSUE TITLE
linter and atom-ide-diagnostics conflict and cannot be permanently disabled

### ISSUE THREAD

**Issue by warden** [atom/atom#18036]
### Prerequisites

The problem obviously doesn't occur in safe mode.

### Description

When linter plugin is installed, I constantly get `You have both linter and atom-ide-diagnostics enabled, which will both display lint results for Linter-based packages.`. No matter if I click "disable atom-ide-diagnostics` by the button, when atom is restarted the message again pops up.

### Steps to Reproduce

1. Install linter plugin
2. Restart atom and see the warning
3. Click Disable atom-ide-diagnostics
4. Restart Atom and see the message again.

**Expected behavior:** [What you expect to happen]

atom-ide-diagnostics should be permanently disabled.

**Actual behavior:** [What actually happens]

No effect of disabling.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

```
$ atom --version
Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0
python 2.7.15
git 2.15.2

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

**Comment by rsese** [comment]
Thanks for the report!

It appears that this is being caused by the https://github.com/facebook-atom/atom-ide-ui package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by rsese** [comment]
Was also going to mention, looks like someone opened an issue already:

https://github.com/facebook-atom/atom-ide-ui/issues/306
