### ISSUE TITLE
Treat numeric keypad the same as numbers on the top row in keybindings

### ISSUE THREAD

**Issue by jrial** [atom/atom#18063]
## Summary

Some keybindings use number keys, but they only work with the numbers on the top row of the keyboard and not the ones on the keypad. An example that comes to mind is the different folding levels: CTRL-K, CTRL-n (where n is a number between 1 and 9). It would be nice if the numerical keypad would be treated the same as the numbers on the top row.

## Motivation

On non-US keyboards, the numbers on the top row are not necessarily a one-key affair. For example, the Belgian keyboard requires you to press shift to reach the numbers. Thus, CTRL-n becomes CTRL-SHIFT-n, which in turn may clash with other keybindings that effectively expect you to type CTRL-SHIFT-n.

Even on US keyboards it would be convenient if the user was offered the choice between upper row or numpad.

## Describe alternatives you've considered

I didn't consider any alternatives; the less-than-ideal keybindings when using non-US keyboard layouts is a known issue and various bug reports have been raised about this already. I don't consider this a bug per se, so I'm filing it as a feature request.

## Additional context

See example non-US layout at https://en.wikipedia.org/wiki/AZERTY where you can clearly see that the numbers are the "uppercase" portion of the key, as opposed to the US layout.

**Comment by Ben3eeE** [comment]
Thanks for your interest in Atom!

The numeric keypad is handled differently because it conflicts with unicode entry on Windows. This was intentionally changed in https://github.com/atom/atom-keymap/pull/198. We are not interested in changing the default behavior back.

If you want this to work differently you can change the behavior with a custom keystroke resolver or by changing your keybindings to include bindings for numpad.

Doing this in your keymap would look something like this:

```json
'body':
  'alt-numpad1': 'pane:show-item-1'
```

Doing this with a custom keystroke resolver could be something like this in your `init.coffee`:

```coffee
atom.keymaps.addKeystrokeResolver ({event}) ->
  {location, key, ctrlKey, altKey, shiftKey, metaKey} = event

  if location isnt 3
    return

  if not event.getModifierState('NumLock')
    return

  keystroke = ''

  if ctrlKey and event.type isnt 'keyup'
    keystroke += 'ctrl'

  if altKey and event.type isnt 'keyup'
    keystroke += '-' if keystroke
    keystroke += 'alt'

  if shiftKey and event.type isnt 'keyup'
    keystroke += '-' if keystroke
    keystroke += 'shift'

  if metaKey and event.type isnt 'keyup'
    keystroke += '-' if keystroke
    keystroke += 'cmd'

  keystroke += '-' if keystroke
  keystroke += key

  return keystroke
```

Because there are ways to configure Atom to get the behavior you want and because we are not interested in changing the default behavior at this time I am going to close this. Thanks again for your interest in Atom!
