### ISSUE TITLE
Code collapse feature wanted

### ISSUE THREAD

**Issue by GHLandy** [atom/atom#18073]
Hi there, I use Atom editor more than one year now.
But Atom editor's code collapse style make some inconvenience.
I'v tried Atom's configuration panel for collapse option but found nothing.

As the following code:

```js
// for example
if (true) {
  // some code here
} else {
  // other code here
}
```

I want to collapse the `if` (line 1 - line 3), it got:

```js
// collapse in fact
if (true) { //...  collapsed
  // other code here
}
```

And then I want to collapse the `else`, but where's the `else`.
Actually, the collapse like:

```js
// but actually i want this
if (true) { //...  collapsed
} else {
  // other code here
}
```

will be more reasonable. Right?

Any way to modify the code collapse option?

thanks!

**Comment by rsese** [comment]
Thanks for reaching out!

The template details are always helpful, please fill out the issue template for future issues.

You don't mention but I assume this is JavaScript?  If so, the new tree sitter parsing system will provide improved folding behavior:

http://blog.atom.io/2018/03/15/atom-1-25.html#improved-syntax-highlighting-and-code-folding

It's not yet enabled by default but if you enable it by checking `Settings > Use Tree Sitter Parsers`, you'll get the behavior you want:

![tree-sitter-fold](https://user-images.githubusercontent.com/734194/45718395-780b5d80-bb62-11e8-956f-53145f30372f.gif)

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
