### ISSUE TITLE
Why does atom have a virtual font in my Deepin Linux? It looks like something else.

### ISSUE THREAD

**Issue by ikozo4** [atom/atom#18072]
Hello, developer, I use it under my deepin Linux.

But somehow the font that it rendered is very empty. It looks strange.

I haven't met before. What's the problem?
![deepin-screen-recorder_select area_20180918103202](https://user-images.githubusercontent.com/42143347/45661060-7031c600-bb2e-11e8-98d4-2371ba062b2f.gif)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by lee-dohm** [comment]
@ikozo4 You may also want to check the [Debugging section of the Atom Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/debugging/), specifically the section on [diagnosing font rendering issues.](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-font-rendering-issues)
