### ISSUE TITLE
Installing “atom-i18n@0.16.0” failed.

### ISSUE THREAD

**Issue by lopa90** [atom/atom#18083]
Request for package information failed: write EPROTO 101057795:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:openssl\ssl\s3_pkt.c:1493:SSL alert number 10
101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
 (EPROTO)
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.
 cosa devo fare ?

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by a dependency of the [atom-i18n](https://github.com/liuderchi/atom-i18n) package requiring build tools to be installed on your system, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
