### ISSUE TITLE
Please give us more control over soft wrapping.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18082]
Continuing from https://github.com/atom/atom/issues/13993,

right now the value of `500` seems to be hard coded. Even if we set "preferred line length" to higher than 500, soft wrapping still happens at 500 characters.

We should be able to configure this number as a new option (or it should at least just be "preferred line length" and if soft wrapping is turned off then it can default to the `500`). So at least we can make work with it.

`500` is relatively small. I bet most crashing happened at much higher numbers.

---

As a bonus, it'd be nice to configure it on a per-buffer basis, for the current session.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by Arcanemagus** [comment]
You may want to re-read https://github.com/atom/atom/issues/13993#issuecomment-337327464 as this _should_ already be addressed 😉.
