### ISSUE TITLE
crash in atom 1.30.0 and macOS 10.13.6

### ISSUE THREAD

**Issue by mamax12** [atom/atom#18084]
crash apear when I install haxe . now I cannot open atom. 
<img width="984" alt="nh ch p man hinh 2018-09-21 luc 17 47 27" src="https://user-images.githubusercontent.com/4360650/45876959-793cc480-bdc6-11e8-9d4d-f74eea7b9fea.png">

**Comment by Arcanemagus** [comment]
You should be able to run `apm uninstall haxe` to uninstall the package, or delete the `~/.atom/packages/haxe` folder to uninstall it manually. If that isn't working please try [Resetting to Factory Defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults).

If the above steps don't work please file a _new_ issue and fill out the template 😉.

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
