### ISSUE TITLE
Atom crashes when accessing properties and methods of an object using (->)

### ISSUE THREAD

**Issue by MartinGeldart** [atom/atom#18113]
In this particular case, it's a PHP PDO object that causes the issue.

I cannot access a method or property of a PDO object without Atom editor crashing.

This is what I want to write:

`$q->fetchColumn();`

But Atom crashes when I use the `>`, so I cannot get past this point without crashing:

`$q-`

If I write `$q->fetchColumn();` in Mac's TextEdit program, I can copy and paste the snippet in to the editor and it won't crash, which is my workaround, it's only when I manually type it that it crashes.

**Comment by rsese** [comment]
Thanks for reaching out!

The issue template details would be extremely helpful here - for example, can you reproduce in safe mode?  Can you share more detailed step-by-step instructions that we can use to try and reproduce?  What version of Atom are you running?  What operating system?

If you can update this issue with the template details or open a new issue with those details, we can go from there.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
