### ISSUE TITLE
Atom crashes after seconds

### ISSUE THREAD

**Issue by justin-s26** [atom/atom#18110]
I search for help. I can't use Atom anymore. So I hope someone can help me. I started Atom this morning and it frequently shows me that it crashes. Yesterday everything was fine and I did nothing since I turned  on my computer. I tried to open a new folder, installed a new version but it still crashes. I really need help to solve this. Thank you.

**Comment by Aerijo** [comment]
@justin-s26 Does it happen in safe mode? Atom stores community packages in a separate folder to where it is installed, so a reinstall does not reset that kind of thing. Safe mode disables these packages, to leave effectively unmodified Atom.

**Comment by justin-s26** [comment]
Yes, it also crashes in safe mode. Also it only takes seconds after it launched.

**Comment by justin-s26** [comment]
I found out something interesting. When every project is closed and I create a new file everything works out fine. But when I save the file it will crash again. I'm not sure how to solve this.

**Comment by justin-s26** [comment]
I can't even use Atom. So I think those are different issues. But I experienced another thing. I opened the whole computer as a project. The folders on the left are green, except for the atom folder. The files inside the atom folder are green as well. But the folder is orange. The same thing happend to the new project I opened. I saved a blank file inside a folder and the folder turns orange as well. Maybe it is just me who doesn't know enough about development, but the change of the colours can't be good :confused:

**Comment by Aerijo** [comment]
@justin-s26 The colour change is normally to represent uncommitted changes in a git repository. You may have inadvertantly made your home / root folder into one.

For the issue, does opening Atom on the command line with
```
atom --safe --clear-window-state
```
help?

**Comment by justin-s26** [comment]
No, the command didn't help :disappointed:

**Comment by sijn82** [comment]
Thanks Aerijo, I've just closed Atom and reopened again from the command line as you suggested.  I'll post again here the next time it crashes on me.

**Comment by justin-s26** [comment]
I'm happy for you, but I'm confused why it is not working for me. As soon as I open a folder (there is no difference if new one or previously used) it crashes.

**Comment by sijn82** [comment]
Ah that sucks, not knowing why something doesn't work or how to further diagnose the issue is very frustrating.  It's little comfort I know, but at least there are some good free alternatives to use while you try to find a better solution.  I'm now 2 hours without issue but as I've no idea what caused the crashes, I'm none the wiser as to whether they'll reappear later. 😄

**Comment by lee-dohm** [comment]
Sorry to hear that you two are having problems. However, we require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

**Comment by lee-dohm** [comment]
Also, you may want to try [the various debugging steps](https://flight-manual.atom.io/hacking-atom/sections/debugging/) in the [Atom Flight Manual](https://flight-manual.atom.io). If you are reporting a crash, the first thing that we're going to ask for (besides whether you tried Safe Mode) is [a crash log](https://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs).
