### ISSUE TITLE
why i need to make multiple unnecessary saves to correctly run Makefile ?? (C++)

### ISSUE THREAD

**Issue by aGOOdKrisYRice** [atom/atom#18136]
**first of all sorry for my bad english, im Mexican.**

_I always used IDEs to make my codes so ive never used a Makefile before. i dont know why but to run my program successfully i need to make a save on every file in my project folder (even if i didnt modified anything of the code in the file) and i dont like that._

_i want to only save the files that ive modiffied to see all the changes in my program when i running it._

**heres my Makefile:**

output: list.o main.o menu.o song.o
	g++ list.o main.o menu.o song.o -o actividad06

list.o: list.cpp list.h
	g++ -c list.cpp

main.o: main.cpp
	g++ -c main.cpp

menu.o: menu.cpp menu.h
	g++ -c menu.cpp

song.o: song.cpp song.h
	g++ -c song.cpp

clean:
	rm *.o actividad06

_am i doing something wrong or theres a way to prevent this??_

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

I would recommend reading more about `make` files and how C++ programs are compiled and if you are still unsure about what is going on there try to find [a place](https://stackoverflow.com/) that is meant to help out with C++ questions.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
