### ISSUE TITLE
Support Tab Size options for panels

### ISSUE THREAD

**Issue by jsg2021** [atom/atom#18164]
## Summary
Currently when a panel has more than one view docked to it besides the center document area Tabs split the panel's title area.  I would like to have a preference to make them minimal/even spaced just like my document tabs. :)

**Comment by rsese** [comment]
Thanks for the suggestion!

The details in the issue template are really useful for the team when considering feature requests (especially since as mentioned in the template, the team is unlikely to have the bandwidth to work on feature requests).  And in this case, screenshots and a specific example might be helpful too since I'm not quite sure I understand what you're describing?

We'll close this for now but if you can share more details, that would be super helpful.

--- 

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by jsg2021** [comment]
I've updated the OP with the template filled in.

**Comment by jsg2021** [comment]
```
atom-dock .tab-bar[location=bottom] .tab {
    &, &.active {
        flex-grow: 0;
        flex-basis: auto;
    }
}
```
