### ISSUE TITLE
atom editor changing default project location

### ISSUE THREAD

**Issue by fynxgloire** [atom/atom#18209]
I changed that setting as shown below but it is NOT changing the default project location.
I have it pointing to my NAS, I wonder if this program has an issue setting the default project location there:
https://imgur.com/a/to6xIkx
Actually I even tried D:\Download and it did not work either.
The NAS path is not a drive its just \\.
Does it work for anyone, can you change it to something like C:\temp?

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

--- 

In particular, please share steps to reproduce, it'll be helpful to know exactly what you're doing when you expect that settings to be used.

**Comment by fynxgloire** [comment]
Hello,
can u tell me where is a template or how I can fill one out?

Regards
