### ISSUE TITLE
Debian package has missing dependencies

### ISSUE THREAD

**Issue by mmstick** [atom/atom#18200]
The current `1.31.1` release has missing dependencies, which cause https://github.com/atom/github/issues/1680 to occur. The solution is to ensure that the debian packages include these two as dependencies:

```
libcurl3 libcurl-openssl1.0-dev
```

**Comment by rsese** [comment]
Thanks for contributing!

Discussion for this issue is in https://github.com/atom/github/issues/848 so feel free to chime in there, but we'll go ahead and close this as a duplicate.

Also, for future issues please use the issue template, the information in the template is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
