### ISSUE TITLE
Atom 1.31.2 segfaults on Ubuntu 18.10 beta

### ISSUE THREAD

**Issue by mikesi** [atom/atom#18213]
Installed the .deb package from atom.io
Tried to run via the startup script, getting:
 /usr/bin/atom: line 157:  2696 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

started atom with gdb, backtrace result is:
Reading symbols from ./atom...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/share/atom/atom 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000dbf060 in ?? ()
(gdb) bt
#0  0x0000000000dbf060 in ?? ()
#1  0x00007ffff7d83072 in node::http2::Http2Session::Callbacks::Callbacks(bool) () from /usr/share/atom/libnode.so
#2  0x00007ffff7d83135 in ?? () from /usr/share/atom/libnode.so
#3  0x00007ffff7fe398a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe2a8, env=env@entry=0x7fffffffe2b8)
    at dl-init.c:72
#4  0x00007ffff7fe3a89 in call_init (env=0x7fffffffe2b8, argv=0x7fffffffe2a8, argc=1, l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffe2a8, env=0x7fffffffe2b8) at dl-init.c:119
#6  0x00007ffff7fd40ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in ?? ()
#8  0x00007fffffffe589 in ?? ()
#9  0x0000000000000000 in ?? ()

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Also, I think this might be resolved by https://github.com/atom/atom/pull/18012, but that fix is only available in the latest beta (currently 1.32.0-beta3) right now .  Can you try the beta and let us know if you still get the segfault?

**Comment by mikesi** [comment]
Yes, the Beta-3 works fine! Thanks!
