### ISSUE TITLE
Atom creates lots of blank pages

### ISSUE THREAD

**Issue by VAdamec** [atom/atom#18218]
Please see https://github.com/akonwi/git-plus/issues/764 it's mainly connected to git-plus but I saw this also for other plugin. Not sure if it's not Atom issue instead plugin ones.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
