### ISSUE TITLE
Where can I find the .spec file for the Red Hat Atom RPM?

### ISSUE THREAD

**Issue by kfiresmith** [atom/atom#18241]
Hello,
At work, I have to rebuild Atom from the published source tarball for _reasons..._

I cloned the repo and poked around looking for a spec file, eg: atom.spec, and came up empty.  I'm guessing that this file lives in some CICD pipeline somewhere - any chance you could point me to a copy I can grab so that I'm building something close to the actual release RPM?

Thanks!

**Comment by Arcanemagus** [comment]
As described in the Flight Manual's [Hacking on Atom Core](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#scriptbuild-options) section, you simply need to add `--create-rpm-package` to have the script generate an RPM package for you.

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
