### ISSUE TITLE
folded code stuck the scroll

### ISSUE THREAD

**Issue by unluisco** [atom/atom#18265]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have an HTML document with many characters. when folding different parts of the document, the document loses its fluidity.

You can see a video that I recorded of the behavior. in a certain part of the video, you can notice the speed of the scroll between the zone with folded code, and the zone without folded code.

### Steps to Reproduce

*Edit step 2 by @rsese to mention specific lines to fold*

1. save this gist: https://gist.github.com/unluisco/cb6d39da5f33117618dd0ab728219dce 
2. open it with atom
3. fold the svg code (lines 18, 29, and 31)
4. scroll it

**Expected behavior:** [What you expect to happen]

I think the scrolling should be fluid

**Actual behavior:** [What actually happens]

the scrolling is stuck.

**Reproduces how often:** [What percentage of the time does it reproduce?]

whenever I fold a lot of code

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.31.2
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.2
python 2.7.10
git 2.19.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

this is the video: https://www.dropbox.com/s/b23i0cmzf2hdzem/atom.mp4?dl=0

**Comment by rsese** [comment]
Thanks for the report!  I see Atom isn't in safe mode in the video - can you confirm the behavior is the same in safe mode?  Also, what operating system are you running?

**Comment by unluisco** [comment]
Thanks Robert, I opened atom in safe mode today and there is not the problem again.
I am using macOS Mojave 10.14 (18A391)

so this problem is from an extension, right?

**Comment by rsese** [comment]
> I opened atom in safe mode today and there is not the problem again.

Ahh great, thanks for confirming :+1:

Since this doesn't reproduce in safe mode, you're correct, it's likely that a community package is causing the issue.  It may be that there is still a bug in Atom but if so, we'll need the maintainer of the package that is causing the problem to help track that down.  You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from.

To figure out which package is causing the issue, you can disable all community packages and enable them one-by-one until you see the behavior again or you could try [package-cop](https://atom.io/packages/package-cop) which some people have found helpful. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Comment by unluisco** [comment]
I tried the installed packages one by one and is [pigments](https://atom.io/packages/pigments) the culprit.

@rsese how can I move this issue to the [pigments](https://github.com/abe33/atom-pigments) repo?
cc @abe33.
