### ISSUE TITLE
Sign up  New issue  Atom not appearing on Start Menu (or anywhere) on Windows 10 after first install

### ISSUE THREAD

**Issue by hqasraful** [atom/atom#18271]
Here is the solution I have found that If you direct install it then you will face this issue. I have just uninstall it and install it "Run as Administrator". Hope it will solve the problem.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
