### ISSUE TITLE
file opened twice with fuzzy finder and treeview

### ISSUE THREAD

**Issue by slang800** [atom/atom#18306]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

You can open the same file twice in the same pane if it's opened once with the fuzzy finder and once with the tree view.

### Steps to Reproduce

1. Open a file using the fuzzy finder.
2. Click on the same file that you've already opened in the tree view
3. Observe that there are now 2 tabs opened, both containing the same file.

**Expected behavior:**
Only one tab gets opened for the file, no matter how many different ways you try to open it.

**Actual behavior:**
You can open the same file twice in different tabs

**Reproduces how often:**
Every single time. This happens pretty often throughout the day and I usually don't notice it until I've made edits within both tabs.

### Versions

```
$ atom --version
Atom    : 1.30.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ apm --version
apm  2.1.2
npm  6.4.1
node 10.11.0 x64
atom 1.30.0
python 2.7.15
git 2.19.0
```

### Additional Information

I'm using fuzzy finder `1.8.2` and tree view `0.222.0`.

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce with Atom 1.32.0 on Ubuntu 18.04 but also:

> Atom    : 1.30.0
> Electron: 2.0.9

Based on these version details, we've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
