### ISSUE TITLE
The editor has crashed.

### ISSUE THREAD

**Issue by prasad442** [atom/atom#18309]
After opening the editor and if we do something and save, there pops up a window saying  "the editor has crashed"
![capture](https://user-images.githubusercontent.com/31914540/47417233-2d01ed00-d795-11e8-82d4-953d6a7e81d5.PNG)

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
