### ISSUE TITLE
Unfinished SQL code inside Python strings breaks syntax highlighting

### ISSUE THREAD

**Issue by ivanivkovic** [atom/atom#18301]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When an unfinished SQL is inside of a Python string, all following Python code is highlighted as if it was a string.

**Expected behavior:** When an unfinished SQL is inside of a Python string, it should be highlighted either as string or as SQL (at least the valid part of the SQL). A programmer should be able to write SQL in variables in segments if they choose to.

**Reproduces how often:** Always.

### Versions 
1.31.2 x64 Ubuntu 18.04.1 LTS

![image](https://user-images.githubusercontent.com/5861940/47369005-06837980-d6e3-11e8-8e13-d111ec097707.png)

**Comment by Arcanemagus** [comment]
Thanks for the report!

This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not on the beta channel, you can enable it manually by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 to be released to the stable branch.

For future reference, issues related to a specific language should be filed on the package that provides that language, such as [language-python](https://github.com/atom/language-python).

If you are interested in fixing this bug for the TextMate grammar system used in other projects (such as VSCode) we would be happy to accept a PR, however we probably won't prioritize work on these kinds of things ourselves, as Atom has moved away from using TextMate for this language.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), I'm closing this issue as it no longer affects Atom.
