### ISSUE TITLE
External scripting interface

### ISSUE THREAD

**Issue by edahlseng** [atom/atom#18314]
## Summary

Does Atom have a scripting interface for other processes to control it? (I cannot find any information about this, so my guess is not.)

I'm imagining something similar to an AppleScript interface, whereby other applications and scripts could control Atom to do things like close tabs/panes, collapse or expand items in the tree view, etc.

## Motivation

Many times a day I switch between different tasks. Almost every time the first thing I do is close all open tabs within Atom to refocus on the next task at hand. I already have scripts for setting up my git repos when beginning a new task, and thought it would be fun to set up Atom at the same time.

## Describe alternatives you've considered

I'm wondering if this could be handled by a package instead, but I'm not familiar enough with the internals of Atom or IPC mechanisms in general to properly weigh the tradeoffs of this approach. Any input or thoughts would be greatly appreciated!

## Additional context

N/A

**Comment by rsese** [comment]
Thanks for reaching out!

If I understand you correctly, yes there's no scripting interface per se, but the Atom API is what people use to customize what they can do with Atom in [packages](https://flight-manual.atom.io/using-atom/sections/atom-packages/) or your [init script](https://flight-manual.atom.io/hacking-atom/sections/the-init-file/):

https://atom.io/docs/api/latest

Particular packages can also expose a [service API](https://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/) to allow other packages to interact with them in specific ways.

> Many times a day I switch between different tasks.  Almost every time the first thing I do is close all open tabs within Atom to refocus on the next task at hand. I already have scripts for setting up my git repos when beginning a new task, and thought it would be fun to set up Atom at the same time.

There's already a command for closing all tabs (`Tabs: Close All Tabs`) but additionally, commands and composed commands might be something that can help you with some of the customizations you want to do:

* https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#commands
* http://blog.atom.io/2018/10/09/automate-repetitive-tasks-with-composed-commands.html

Taking a look at how existing packages work could be helpful too, e.g. around tab closing there's quite a few:

https://atom.io/packages/search?q=close+tabs

I hope these notes are helpful but in any case, the best place to have discussions like this would be the [Atom Slack](http://atom-slack.herokuapp.com/)) or the [message board](https://discuss.atom.io), especially if you want to get into more lower level detail.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by edahlseng** [comment]
Thanks for the response @rsese!
