### ISSUE TITLE
GitHub seems not working in atom

### ISSUE THREAD

**Issue by Anandesh-Sharma** [atom/atom#18330]
I've the full privileges to this repository [BitsPlease Hacktoberfest](https://github.com/BitsPleaseMSI/Hacktoberfest2018), but still whenever I am trying to push something on to the upstream it throws this error.

```
remote: Permission to BitsPleaseMSI/Hacktoberfest2018.git denied to Anandesh-Sharma.
fatal: unable to access 'https://github.com/BitsPleaseMSI/Hacktoberfest2018.git/': The requested URL returned error: 403
```
When I do the same push thing using terminal it works. I don't know why it's happening. Any suggestions would be appreciated.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

One thing you can check is if maybe Atom is using incorrect cached credentials?  I'm not sure why that would be the case though if pushing through the terminal works for the same repository 🤔 

For example, if you're on macOS, you can try to delete `github.com` related credentials so you're prompted for credentials again:

https://help.github.com/articles/updating-credentials-from-the-osx-keychain/

If you still have trouble, feel free to post on our [message board](https://discuss.atom.io/) and ping me in your post.
