### ISSUE TITLE
1.32.0 Broke hyperclick package

### ISSUE THREAD

**Issue by teod** [atom/atom#18337]
https://atom.io/packages/hyperclick

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
