### ISSUE TITLE
` One Dark UI ` or ` One Ligth UI ` problem

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#18335]
@Arcanemagus  `You're not solving this problem, you're removing functionality.Is that the solution`

> The cause of the problem

![tim 20181026112309](https://user-images.githubusercontent.com/8848263/47542783-93ac1580-d911-11e8-8f97-fffe702d07ab.png)

**Comment by lee-dohm** [comment]
@linjialiang, you have been warned multiple times that you must use the template when filling out new issues so that we can help you properly. Despite this, you have continued to open new issues without using the template. In addition, you have begun targeting specific Atom community members with accusations that they've broken things. All of this is considered harassment under the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md). If this behavior continues, you will be banned from accessing the [atom organization](https://github.com/atom). You may consider this an official warning.
