### ISSUE TITLE
System tray feature

### ISSUE THREAD

**Issue by alxpettit** [atom/atom#18345]
Since the previous issue thread (from back in 2015!) on this topic, I will open a new one.  #7526

I often need to quickly edit something and then want the editor to quickly go away. On my system, Atom takes an agonizing time to load compared to a C++ compiled app, but it does not take that much system resources while _running_.

So ideally I'd keep it open but in the background. The problem is that I like to minimize the amount of windows I have open to avoid clutter, so in my workflow, Atom ends up closed most of the time. Which means I never actually end up using it. I will end up reaching for things like Gedit or Xed instead because they open much faster, and anything that eats up precious seconds will be skipped. So, I think a system tray option would vastly improve the usability of this app for my workflow.

Thoughts?

**Comment by rsese** [comment]
Thanks for reaching out!

Personally, I think it's an interesting idea in relation to startup performance rather than minimizing clutter (though I can see how that could definitely help some people's workflows) - besides the issue you referenced, running Atom in the background has been brought up in other startup performance issues like https://github.com/atom/atom/issues/3673 for example.   So it seems like if startup performance were improved, it sounds like that would somewhat help with the issue you're describing?  And there are already issues open about this like https://github.com/atom/atom/issues/2654 that you can subscribe to if you'd like.

And there has definitely been work around this (e.g. see our [performance blog post](http://blog.atom.io/2018/01/10/the-state-of-atoms-performance.html#startup-time)) and it's something the team thinks about improving where/when they can.  

As far as a Windows specific enhancement to in the system tray specifically however, as far as I know Damien's [comment](https://github.com/atom/atom/issues/7526#issuecomment-213796330) still stands today (and as mentioned in the feature request template, we're generally unlikely to work on feature requests any time soon with the work the team has on their plate).   

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by alxpettit** [comment]
Hmm. I was under the impression the template was more of a bug submission thing, since it's easy for people to not give enough details in those cases -- but for feature suggestions, details about logs, version numbers, etc, are all pretty much N/A. But if it makes it any easier to process my input, I'll definitely try to stick to the template in the future! Sorry about that.

And yes, improving the startup time would help majorly!

**Comment by Ben3eeE** [comment]
> but for feature suggestions, details about logs, version numbers, etc, are all pretty much N/A.

There is a specific feature request template that has different questions from the bug report template. When you create a new issue you get a choice between them.

**Comment by alxpettit** [comment]
Ah, okies! I'll keep that in mind, thanks. ^.^
