### ISSUE TITLE
Atom IDE getting blurried

### ISSUE THREAD

**Issue by xlysander12** [atom/atom#18355]
Hi, I have a problem that is very annoying and I really want to fix it. My Atom IDE is getting blurried with no apparent reason and when I click under the blurried space it goes normal again.
![screenshot_2](https://user-images.githubusercontent.com/30909482/47675703-85305900-dbb2-11e8-9770-777db6ca6142.png)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
