### ISSUE TITLE
Gemfiles detected as Ruby with Tree-sitter

### ISSUE THREAD

**Issue by gsmetal** [atom/atom#18352]
### Description

Hello. I am using atom with ruby on rails projects and since 1.32 all ruby files treates as `ruby` grammar. For example, there is special grammar for `Gemfile`, but it's opened and highlighted as `ruby`. Downgrading for 1.31 worked for me, but now I updated ubuntu to 18.10 and 1.31 is not working there.

### Steps to Reproduce

1. Open Rails project.
2. Open Gemfile.

*Edit by @rsese to provide an example project and Gemfile*

Tested with https://github.com/railstutorial/sample_app_rails_4 and https://github.com/railstutorial/sample_app_rails_4/blob/fd4f6f5b528736225a59ff56048fec1cd380e2c9/Gemfile to confirm.

**Expected behavior:** 

Gemfile is opened with `Gemfile` grammar.

**Actual behavior:** 

Gemfile is opened with `Ruby` grammar.

### Versions

Since 1.32. 1.33-beta is affected too.

*Edit by @rsese to add Additional Information*

### Additional Information

Noted that in 1.34.0-nightly5 I didn't see any syntax highlighting color differences but I did in 1.32.0.  But the grammar is shown as `Ruby` in both 1.34.0-nightly5 and 1.32.0.

**Comment by gsmetal** [comment]
Looks like this is connected (or duplicate?) with #18342. Tried to disable `useTreeSitterParsers` as suggested in comments there — now it works as expected.

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce the grammar showing `Ruby` instead of `Gemfile` on macOS 10.12.6 with 1.34.0-nightly5 in safe mode - I cloned https://github.com/railstutorial/sample_app_rails_4 and opened https://github.com/railstutorial/sample_app_rails_4/blob/fd4f6f5b528736225a59ff56048fec1cd380e2c9/Gemfile to confirm. 

If I disable Tree-sitter and open the same file, the grammar shows as `Gemfile`.

I didn't particularly see any syntax highlighting differences though on 1.34.0-nightly5 but I did on 1.32.0 so it seems like some recent updates affect this issue.

I'll update the issue with some of these notes (it's always helpful to have a specific code snippet or file to test with).

**Comment by lee-dohm** [comment]
Thanks for the report!

This was an intentional change because Gemfiles are Ruby and we're trying to reduce the number of individual custom grammars we're supporting. Thanks again!

**Comment by FunkyloverOne** [comment]
@lee-dohm, but that's not the only problem with Tree-sitter at the moment, it also screws highlighting on normal ruby files, take a look, here's proper highlighting with Tree-sitter disabled:

![proper highlighting](https://i.imgur.com/SIQIeK3.png)

And here's with Tree-sitter enabled:

![screwed highlighting](https://i.imgur.com/4lGrpXO.png)

The second is much worse, and it also causes errors on some other packages, like [blocky](https://atom.io/packages/blocky).

**Comment by lee-dohm** [comment]
If you have specific issues about how the syntax highlighting is worse, please take a look at the [open issues on atom/language-ruby](https://github.com/atom/language-ruby/issues). If the specific problem that you're experiencing is not already tracked there, please open a new issue on that repository.

What we're mostly looking for are situations where the underlying scopes of tokens are _incorrect_, not that the color is different than it was before. Tree-sitter is a new grammar system that enables a number of advanced features including more rigorous syntax highlighting, which means more tokens will be detected correctly or more correctly than in the past. This means that colors may change because of this new information. In general, we don't consider that a bug.

If you want to see how tree-sitter identifies the token at the current cursor position, you can open the Command Palette using <kbd>Cmd+Shift+P</kbd> on macOS or <kbd>Ctrl+Shift+P</kbd> on other platforms, then search for and execute "Editor: Log Cursor Syntax Tree Scope". If the scope at the bottom is incorrect, please file an issue and describe what you expected instead.

Thanks!

**Comment by Ben3eeE** [comment]
In addition to everything @lee-dohm also make sure that you run the latest version of Atom stable or beta because I can see issues there that were already fixed in the latest hotfix. Like symbols being scoped as constant identifiers.

**Comment by FunkyloverOne** [comment]
Thanks guys, so I believe that it is actually fixed in latest version of Atom (1.32.1), so I will just wait for an update for Atom in my linux distro, and then confirm that it's all good now :)
