### ISSUE TITLE
Uncaught TypeError: Cannot read property 'activeTasks' of null

### ISSUE THREAD

**Issue by Darrellrp** [atom/atom#18386]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: 'npm-plus' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'activeTasks' of null

```
At /Users/darrellpoleon/.atom/packages/npm-plus/lib/npm-plus.js:33

TypeError: Cannot read property 'activeTasks' of null
    at dropTask (/packages/npm-plus/lib/npm-plus.js:33:28)
    at reducer (/packages/npm-plus/lib/npm-plus.js:81:24)
    at dispatch (/packages/npm-plus/lib/npm-plus.js:118:13)
    at /packages/npm-plus/lib/npm-plus.js:141:9)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -0:52.9.0 command-palette:toggle (input.hidden-input)
     -0:50.3.0 core:move-down (input.hidden-input)
     -0:49.6.0 core:confirm (input.hidden-input)
     -0:49.6.0 npm-plus:start (input.hidden-input)
     -0:38.3.0 settings-view:open (input.hidden-input)
     -0:33.1.0 core:paste (input.hidden-input)
     -0:32.2.0 core:undo (input.hidden-input)
     -0:32 editor:select-to-first-character-of-line (input.hidden-input)
     -0:31.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-bootstrap3 1.2.12 
atom-clock 0.1.16 
atom-live-server 2.3.0 
atom-ternjs 0.18.3 
autocomplete-modules 2.2.4 
autocomplete-paths 2.12.2 
css-snippets 1.1.0 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.26 
Hydrogen 2.6.0 
jquery-snippets 11.0.0 
language-babel 2.85.0 
language-blade 0.41.4 
language-markdown 0.27.0 
language-r 0.4.2 
language-vue 0.23.1 
laravel 0.7.1 
minimap 4.29.9 
php-cs-fixer 4.1.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
script 3.18.1 
todo 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 1.1.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://atom.io/packages/npm-plus package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
