### ISSUE TITLE
Couldn't launch swift (swift).

### ISSUE THREAD

**Issue by fevziomurtekin** [atom/atom#18397]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Ubuntu 18.10
**Thrown From**: Atom Core

### Stack Trace

Couldn't launch swift (swift).

```
At Please make sure that swift is installed, and either put it into your PATH or enter its location in the plugin settings.

undefined
```

### Commands

```
     -2:50 core:undo (input.hidden-input)
     -2:46.5.0 find-and-replace:show (input.hidden-input)
     -2:30 markdown-preview:toggle (input.hidden-input)
     -2:19.6.0 command-palette:toggle (input.hidden-input)
     -2:14.4.0 editor:paste-without-reformatting (input.hidden-input)
 12x -0:59.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
ide-swift 0.1.8 
language-swift 0.5.0 
```

**Comment by thomasjo** [comment]
Thanks for contributing!

It appears that this is being caused by the [ide-swift](https://atom.io/packages/ide-swift) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
