### ISSUE TITLE
Update to  https://github.com/atom/electron/issues/2617 by  @nathansobo

### ISSUE THREAD

**Issue by niagarajohn** [atom/atom#18409]
As a temporary workaround, create the following file at `~/Library/KeyBindings/DefaultKeyBinding.dict` (or add these entries to the existing file):

``` plist
{
    "^@\UF701" = "noop:";
    "^@\UF702" = "noop:";
    "^@\UF703" = "noop:";
}
```

_Originally posted by @nathansobo in https://github.com/atom/atom/issues/1669#issuecomment-135503562_

May need to swap ^ and @.  Works in HighSierra.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
