### ISSUE TITLE
Everything I write is in my autocomplete.

### ISSUE THREAD

**Issue by axe-z** [atom/atom#18427]
When in jsx (babel langage selected... or javascript with jsx), everything I write is showing in my autocomplete and it refers to ... nothing:
 
[capture d ecran le 2018-11-12 a 16 59 32](https://user-images.githubusercontent.com/27289270/48377626-56c77900-e69c-11e8-81f1-780622e18af9.png)

if I press enter, ( cause sometimesI need to ... ) I loose the surrounding brackets, got to code all over again ... It's driving me mad. 

React has won, the editor should handle react wayyyyy better, and render props are common these days. Many issues with it ... But the pictured one is telling me every second to listen to everyone and go over VScode.

**Comment by rsese** [comment]
Thanks again for reporting - can you fill out the issue template details?  I'm not 100% sure I follow the steps to reproduce and want to make sure we're on the same page.  And it would be helpful to know what version of Atom you're running or what operating system, etc.  Also, it's not clear if you tried in safe mode or not or if this behavior just started recently or if you've seen this for a while.

I do see your screenshot is using snippets though?  If it's an issue with how the snippets are auto-completing, this might be better in https://github.com/atom/autocomplete-snippets?  

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
