### ISSUE TITLE
Uncaught Can't find name file

### ISSUE THREAD

**Issue by tlandmangh** [atom/atom#18429]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find name file

```
At C:\Users\Gebruiker\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11

undefined
```

### Commands

```
     -0:16.4.0 emmet:encode-decode-data-url (input.hidden-input)
```

### Non-Core Packages

```
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.26 
pigments 0.40.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

x-ref: https://github.com/atom/atom/issues/17830

**Comment by tlandmangh** [comment]
See between the lines,


Op 14-11-2018 om 4:20 schreef Robert Sese:
>
> Thanks for the report! Can you confirm a few things for us?
>
>   * What were you doing at the time of the error?
>
Editing a PHP file with a piece of JavaScript.
var initialJSON = {
     "locale" : "en",
     "pages": [
       {
         name: "page1",
         "elements": [
           {
             "type": "radiogroup",
  ...
The name was highlighted by me. When I then press Ctrl+" I got the message.
>
>   * Is the error is reproducible?
>
Yes. I now have also checked if highlighting any other word causes the 
same crash.
>
>   * If reproducible, do you see the error in safe mode (|atom --safe|)?
>
No. I suspect that one of the packages I have installed is causing the 
problem. Other than the standard packages I have: docblockr 0.13.7, 
emmet 2.4.3, file-icons 2.1.26 and pigments 0.40.2

**Comment by rsese** [comment]
Great thanks @tlandmangh :+1:

> No. I suspect that one of the packages I have installed is causing the problem. Other than the standard packages I have: docblockr 0.13.7, emmet 2.4.3, file-icons 2.1.26 and pigments 0.40.2

I looked through some of the other referenced issues from https://github.com/atom/atom/issues/17830 and it looks like everyone had emmet installed.  If you disable emmet, can you no longer reproduce?

**Comment by rsese** [comment]
Thanks for confirming :+1:

Since it appears that this is being caused by https://atom.io/packages/emmet, you should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from.  It may be that there is still a bug in Atom and if so, we'll need the maintainer of the package that is causing the problem to help track that down. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
