### ISSUE TITLE
Crashing all time

### ISSUE THREAD

**Issue by durancanyilmaz** [atom/atom#18422]
### Prerequisites
Safe mode working 
but i can not open my project file
I deleted my all packages and using only "remote ftp" but still crashing.

### Description

I've been using the atom editor for a long time. Facebook started crashing while making php login system. It was after installing the Facebook SDK.

### Steps to Reproduce

1. open
2. 3 character writing
3. crash
4. repeat

### Versions
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report -

> Safe mode working
> but i can not open my project file
> I deleted my all packages and using only "remote ftp" but still crashing.

If there's no problem in safe mode, then that means a community package or possibly something in your init script is causing the issue.  Since remote-ftp is the only community package you left installed, if you disable it does the crashing stop?

Going to go ahead and close the issue since the issue looks like it's related to a community package.
