### ISSUE TITLE
Error fetching from carbon: TypeError: Error processing argument at index 0, conversion failure f...

### ISSUE THREAD

**Issue by Beyarz** [atom/atom#18440]
[Enter steps to reproduce:]

1. ... Run ALT+CMD+V

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: Atom Core

### Stack Trace

Error fetching from carbon: TypeError: Error processing argument at index 0, conversion failure from undefined

```
At undefined

undefined
```

### Commands

```
     -2:24.2.0 core:confirm (input.hidden-input)
  2x -1:15.5.0 carbon.now.sh:toggle (input.hidden-input)
     -0:43.3.0 core:confirm (input.hidden-input)
  3x -0:24.4.0 carbon:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
atom-ide-ui 0.13.0 
atom-mysql-snippets 0.3.1 
atom-typescript 12.6.3 
autocomplete 0.47.0 
carbon 0.3.0 
git-blame 1.8.0 
git-time-machine 2.1.0 
gitlab-integration 0.4.7 
ide-dlang 1.11.7 
ide-typescript 0.7.9 
language-x86-64-assembly 2.2.11 
markdown-writer 2.10.3 
multi-cursor 2.1.5 
open-html-in-browser 0.2.1 
prettier-atom 0.55.2 
run-command 0.5.0 
seeing-is-believing 15.0.0 
split-diff 1.5.3 
w3c-validation 0.4.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://atom.io/packages/carbon package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
