### ISSUE TITLE
RPM is 3x the size of DEB

### ISSUE THREAD

**Issue by p-e-w** [atom/atom#18452]
For Atom 1.32.2 we have:

* `atom.x86_64.rpm`: 268 MB
* `atom-amd64.deb`: 86 MB

Even stranger is the recent growth, compare with Atom 1.30.0:

* `atom.x86_64.rpm`: 134 MB
* `atom-amd64.deb`: 83 MB

So in the course of just 2 releases, the RPM package has grown by 134 MB (doubled in size!) while the DEB has grown by just 3 MB, when it seems they should be more or less the same size since the architectures are the same.

What is going on here?

**Comment by rsese** [comment]
I don't remember this coming up in any discussions or issues but just noting that this difference in size for the .rpm looks like it started in 1.31.0 (260 MB): https://github.com/atom/atom/releases/tag/v1.31.0.

Going to close just for now since it's not a task to be completed at the moment, but we can re-open depending on what I hear back from the team.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by shiftkey** [comment]
Please read the details I provided in this comment about ASAR and symlinks: https://github.com/desktop/dugite-native/issues/138#issuecomment-438070892

**Comment by p-e-w** [comment]
@shiftkey I did see that and understand the background. What I meant by "followup steps" is the fact that the question "Should I report this to Atom, to Electron, *or are you going to take further steps here?*" received only a link to the bug reporting guidelines as a response, which doesn't answer the question and I suspect might be the reason why nothing has happened since.

**Comment by shiftkey** [comment]
@p-e-w it's an Atom-specific issue so there's no point bringing it to Electron or `dugite-native` currently. I just wanted whoever was involved to read the guidance from the Atom maintainers before submitting an issue, to save time.

**Comment by p-e-w** [comment]
Followup issue filed at https://github.com/atom/atom/issues/18490.
