### ISSUE TITLE
Cannot open file from inside atom if it is part of gitignore

### ISSUE THREAD

**Issue by Samnan** [atom/atom#18465]
### Description

It's more like a question because it seems to be a feature, but I am not sure why it works the way it does.

My project is on git, and I have some files that are ignored from the git repo. So whenever I open the command bar (Cmd+P) and start typing the name of the file, it does not show on the list. Shouldn't the autocompletion works for all files in the project? why does it ignore those files that are ignored by git?

The only way to open those files it to use explorer/finder to drag and drop them into atom or open manually. Git ignore files are also not showin in the file tree, maybe there is a shortcut to enable showing all files in the treeview, regardless of whether they are part of git repo or not?

**Comment by nemanjaglumac** [comment]
@Samnan this article covers a few possible solutions to your issue.
https://stackoverflow.com/questions/22727463/hide-hiddendot-files-in-github-atom-editor

**Comment by rsese** [comment]
Thanks for reaching out!

There are settings to control this behavior, as mentioned by the SO post pointed out by @nemanjaglumac (:bow:).

For tree view it's `Settings > Packages > Tree view > Hide VCS Ignored Names` (you can also toggle this with the tree view focused and then press <kbd>i</kbd>).  There's also a `Settings > Core > Exclude VCS Ignored Paths` setting that will adjust fuzzy finder's behavior, read the setting description for more details.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
