### ISSUE TITLE
Ok, thanks for reporting back. We'll be releasing Atom 1.32.0 (stable) shortly, which will contain the same fix.

### ISSUE THREAD

**Issue by joshcangit** [atom/atom#18477]
_Originally posted by @maxbrunsfeld in https://github.com/atom/atom/issues/18170#issuecomment-432422276_

**Comment by joshcangit** [comment]
Still not fixed in the snap version.
![atom-snap-fetch](https://user-images.githubusercontent.com/33022160/48852766-f58f5c00-eda5-11e8-8600-aea76dc24cfe.png)
It's not an issue in the flatpak version.

**Comment by thomasjo** [comment]
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by joshcangit** [comment]
It's still better to use the official repository. I have used the flatpak version and there were errors with the packages especially ide-php and ide-python.

**Comment by joshcangit** [comment]
PackageCloud.io is down for now.
Going back to the Snap version.

**Comment by joshcangit** [comment]
I forgot to mention. This may be related to Issue #17012.
