### ISSUE TITLE
better keyboard events handling when focus in Tree View

### ISSUE THREAD

**Issue by yarozar** [atom/atom#18470]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tree View has several bugs when used using keyboard:
(1) When browsing through files with keyboard's up and down arrows the currently highlighted file is NOT shown in preview mode in Editor pane or if there is already active tab with that file opened - it should be then made as selected - this is exactly the behavior when you highlight file with a mouse click.

(2) When clicking fn+Up or fn+Down (on mac) scroll is going PgUp or PgDwn but the file selected is NOT changed. Cursor/currently highlighte/selected file should follow scroll in that case. This is exactly how Editor pane is behaving

### Steps to Reproduce

Check description.

**Expected behavior:** In description.

**Actual behavior:** In description.

**Reproduces how often:** 100%

### Versions

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!

There's a separate repository for tree view:

https://github.com/atom/tree-view

But these issues in particular are duplicates if you want to subscribe:

> (1) When browsing through files with keyboard's up and down arrows the currently highlighted file is NOT shown in preview mode in Editor pane or if there is already active tab with that file opened - it should be then made as selected - this is exactly the behavior when you highlight file with a mouse click.

https://github.com/atom/tree-view/issues/834

The workaround mentioned in https://github.com/atom/tree-view/issues/834#issuecomment-327499017 seemed to work last time I tried it.

> (2) When clicking fn+Up or fn+Down (on mac) scroll is going PgUp or PgDwn but the file selected is NOT changed. Cursor/currently highlighte/selected file should follow scroll in that case. This is exactly how Editor pane is behaving

https://github.com/atom/tree-view/issues/1021

For future issues, please open one issue per report, it makes it easier for the team to manage.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by yarozar** [comment]
Thanks @rsese, will do!

p.s.: wow, these issues are like 2 years old!.. did not expect Atom to have known (reported and confirmed) and SO old bugs. This is not good. :(

**Comment by rsese** [comment]
Thanks @yarozar :bow:

About the issues themselves - with finite resources the team isn't able to work on everything unfortunately (as you've seen, there are a number of open issues besides those 2 tree view issues).   But if you or anyone in the community submits a well-written pull request to address an open issue, I can definitely ask the team to take a look.
