### ISSUE TITLE
Pending Pane not closing automatically

### ISSUE THREAD

**Issue by BenjaminZimbal** [atom/atom#18491]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am using the pending pane feature pretty regularly and after some update (not sure anymore if it was atom itself or some packages) the pending panes won't close anymore. It just creates more tabs with italic titles.

**IMPORTANT**
Using Safe-Mode closes pending panes again as expected.

### Steps to Reproduce

1. Single click on file (opens pending pane)
2. Single click on a different file (opens another pending pane)
3. Repeat to get new tabs all over the place.

**Expected behavior:** 
First pending pane dissappears and a new one with the new file opens.

**Actual behavior:**
A second pending pane gets opened, now there are two tabs with italic titles.

**Reproduces how often:**
100%

### Versions

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

Microsoft Windows 10 v1803

### Additional Information

None.

**Comment by rsese** [comment]
Thanks for the report:

> Using Safe-Mode closes pending panes again as expected.

If there's no problem in safe mode, then that likely means a community package or possibly something in your init script is causing the issue:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

You can disable each community package one by one to try and pinpoint which is causing the problem for you.  Once you find the responsible package, you should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from.  It may be that there is still a bug in Atom and if so, we'll need the maintainer of the package that is causing the problem to help track that down. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
