### ISSUE TITLE
Unexpect identification 

### ISSUE THREAD

**Issue by Dadapas** [atom/atom#18507]
Atom version
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

Can't open after updating to a new version
```
unexpected indentation
[stdin]:14:10: error: unexpected indentation
    style:
         ^
```

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
