### ISSUE TITLE
Get rid of the update dialog

### ISSUE THREAD

**Issue by gemal** [atom/atom#18534]
## Summary

Integrate the update dialog into the main About tab. The About tab can just be made into showing the same information as the popup dialog.

## Motivation

It's not needed

## Additional context

![image](https://user-images.githubusercontent.com/69105/49363743-cbf9fd00-f6e2-11e8-9467-87ffd2988776.png)

**Comment by rsese** [comment]
Thanks for the suggestion!   I can see how that particular dialog might not be necessary since we already have the About tab (though if you don't have the About tab open, opening the About tab to show that there's no updates might be a bit much?).

In any case, we've passed along your suggestion to the rest of the maintainers team - because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.
