### ISSUE TITLE
Theme <Chestnut Light Atom> syntax highlighting not working correctly in latest release(1.33.0)

### ISSUE THREAD

**Issue by Xdudu** [atom/atom#18533]
Does anybody have the problem same as I do? I've tried two installed theme, they all miss some syntax highlighting...

![image](https://user-images.githubusercontent.com/19299469/49352744-86dec680-f6f4-11e8-8ed9-e486c743820c.png)

The one I'm using here is [Chestnut Light Atom](https://atom.io/themes/chestnut-light-atom-syntax)

**Comment by benjeske** [comment]
I'm having issues with syntax highlighting as well. Words like "app" were red before and now they're not highlighting. Haven't been able to fix by changing the theme/syntax theme, it does it with all of them

![screen shot 2018-12-03 at 2 41 48 am](https://user-images.githubusercontent.com/4838934/49365836-0b095d80-f6a5-11e8-8b6f-623da70ac69d.png)

**Comment by rsese** [comment]
Thanks for the report!

Atom v1.32.0 enabled a [new parsing system](https://blog.github.com/2018-10-31-atoms-new-parsing-system/) by default. If you have specific issues about how the syntax highlighting has changed that you feel are mistakes, please take a look at the open issues on the appropriate language repository (e.g. https://github.com/atom/language-javascript for JavaScript). If the specific problem that you're experiencing is not already being tracked there, please open a new issue on that repository.

Tree-sitter is a new grammar system that enables a number of advanced features including more rigorous syntax highlighting, which means more tokens will be detected correctly or more correctly than in the past. This means that colors may change because of this new information. What we're mostly looking for are situations where the underlying scopes of tokens are _incorrect_, not that the color is different than it was before. Some differences may be _expected_, such as variables now being recognized the same in every location they appear instead of differently based on the context. In general, we don't consider that a bug.

If you want to see how Tree-sitter identifies the token at the current cursor position, you can open the Command Palette using <kbd>Cmd+Shift+P</kbd> on macOS or <kbd>Ctrl+Shift+P</kbd> on other platforms, then search for and execute "Editor: Log Cursor Scope". If the scope at the bottom is incorrect, please file an issue and describe what you expected instead.

Thanks!

> I'm having issues with syntax highlighting as well. Words like "app" were red before and now they're not highlighting.

About this in particular, see Max's comment here for more details: https://github.com/atom/atom/issues/18307#issuecomment-432807134

**Comment by Xdudu** [comment]
Thx so much! I found an issue related to this under [language-babel](https://github.com/gandm/language-babel/issues/510#issuecomment-433466949) repo, that could be a solution for now.
