### ISSUE TITLE
Rename Atom.app

### ISSUE THREAD

**Issue by jjerome00** [atom/atom#18546]
## Summary
I want to rename Atom.app to a different name, and have two copies work as a completely separate apps. I use atom for both development and notes (and some other uses), so it would be useful to have my Mac treat them as separate apps.  For example, switching between them would be easier.

Am I looking at building form source?  
Do I just need to change a few values in a build file?  
Will doing this break the app and I shouldn't bother?

I also opened an issue at Electron, solely because I saw some past issues where people tried to rename their app.  I'm not sure why they were under the Electron repo.

I wasn't sure where to ask, so I thought I'd go directly to the source to see where I can start.  Thanks for your time.

**Comment by rsese** [comment]
Thanks for reaching out!

> I wasn't sure where to ask,

See the details below for more details, but the [Atom Slack](http://atom-slack.herokuapp.com/) and the [message board](https://discuss.atom.io) are the best places for questions rather than here on the issues list.

> have two copies work as a completely separate apps. I use atom for both development and notes (and some other uses), so it would be useful to have my Mac treat them as separate apps.

You can use the `ATOM_HOME` variable when launching Atom to use 2 different configurations:

https://flight-manual.atom.io/using-atom/sections/basic-customization/#controlling-where-customization-is-stored-to-simplify-your-workflow

I believe there was an issue running 2 instances of Atom like this at the same time but that was resolved in https://github.com/atom/atom/pull/16458.

If you have trouble with the setup, feel free to reach out in the Slack or message board.

--- 
Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
