### ISSUE TITLE
snippets package causing freeze

### ISSUE THREAD

**Issue by JackyRachel** [atom/atom#18562]
Hi,
The snippets package which comes built-in with atom freeze the whole program to the point its asking close/reload. In both stable / beta version.
If the snippets plugin is disabled on start than enabled it works perfectly, can read the snippets.

Howto recreate the issue:
1. Install atom / atom-beta
2. Install atom-cform-yaml package.
3. Update the snippets with the build.sh (it will generate more files as the CF support more and more)
4. Start atom

However, I find a bypass but its getting annoying to this every time.
1, my config.cson
`   core:
    disabledPackages: [
      "snippets"
      "about"
      "archive-view"
      "autocomplete-atom-api"
      "autocomplete-css"
      "autocomplete-html"
      "autoflow"
      "autosave"
      "background-tips"
      "bookmarks"
      "command-palette"
      "dalek"
      "deprecation-cop"
      "dev-live-reload"
      "encoding-selector"
      "exception-reporting"
      "fuzzy-finder"
      "git-diff"
      "github"
      "go-to-line"
      "grammar-selector"
      "image-view"
      "incompatible-packages"
      "keybinding-resolver"
      "language-c"
      "language-clojure"
      "language-coffee-script"
      "language-csharp"
      "language-css"
      "language-gfm"
      "language-git"
      "language-go"
      "language-html"
      "language-hyperlink"
      "language-java"
      "language-javascript"
      "language-json"
      "language-less"
      "language-make"
      "language-objective-c"
      "language-mustache"
      "language-perl"
      "language-php"
      "language-property-list"
      "language-python"
      "language-ruby"
      "language-rust-bundled"
      "language-sass"
      "language-shellscript"
      "language-source"
      "language-sql"
      "language-toml"
      "language-typescript"
      "language-xml"
      "line-ending-selector"
      "link"
      "markdown-preview"
      "metrics"
      "notifications"
      "open-on-github"
      "package-generator"
      "spell-check"
      "status-bar"
      "styleguide"
      "symbols-view"
      "timecop"
      "update-package-dependencies"
      "welcome"
      "whitespace"
      "wrap-guide"
      "language-ruby-on-rails"
    ]`
2, chattr +i on config.cson
3, start atom, enable snippets plugin.
4, everything works fine with my settings.

**Comment by rsese** [comment]
Thanks for reaching out!

As mentioned below, please fill out the issue template when opening issues - in particular, the format is very helpful for us when triaging issues.  For example, can you reproduce in safe mode (relatedly, do you have to install `atom-cform-yaml` to reproduce the problem?  If so, this may be an issue for the maintainers of that package)?  What version of Atom are you running and what operating system?

We'll go ahead and close this issue but if you can share the template details, please open a new issue in https://github.com/atom/snippets so we have it in the right place.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
