### ISSUE TITLE
Guys, please synchronize the menu bars between Atom and GitHub Desktop! (GitHub Desktop's looks like the new VS Code's, but Atom's looks like the older VS Code's!)

### ISSUE THREAD

**Issue by FlipperCanoe163** [atom/atom#18560]
## Summary

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered. Be sure to explain why Atom's existing customizability isn't suitable for this feature.

**Comment by rsese** [comment]
Thanks for reaching out!

We'll go ahead and share your feedback with the team but for future issues, please fill out the issue template with as much detail as possible.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
