### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by induts** [atom/atom#18573]
Every time I open atom It says editor has crashed

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Additionally, I'd suggest trying some of the suggestions in the debugging guide as mentioned in the `Prerequisites` section of the issue template, like safe mode and temporarily resetting to factory defaults for example:

https://flight-manual.atom.io/hacking-atom/sections/debugging/
