### ISSUE TITLE
Takes too much of time when enter is hit at the start of the page.

### ISSUE THREAD

**Issue by naval-kishore** [atom/atom#18582]
I'm using atom on Macbook Air. I'm using version 1.33.0

While editing an already created page and try to create a new line on the top of the file atom doesnot respond.

It keeps saying wait or force close.

Immediate fix is much appreciated.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
