### ISSUE TITLE
Cannot see Atom window on Ubuntu after Upgrade

### ISSUE THREAD

**Issue by phenobarbital** [atom/atom#18587]
### Description

after an upgrade to Ubuntu 18.04, atom won't show up any window (only a frame with a transparent window)
I have NVIDIA Quadro 2100.

I try to uninstall, purge and reinstall both versions (stable and beta) without success, even with --safe mode, I got a transparent screen.
Delete .atom folder doesn't help either.
### Workaround

I could run Atom successfully after delete the ~user/.config/Atom folder (without touching ~/.atom folder).

**Comment by rsese** [comment]
Thanks for the report -

> I could run Atom successfully after delete the ~user/.config/Atom folder

Just to clarify, it sounds like the Atom window is showing up now?  I believe this directory is where project saved state is stored on Linux - if deleting this directory helped, then it looks like clearing saved state is what fixed things (you should run Atom as described in the docs instead of manually deleting the directory):

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

The debugging guide is mentioned in the issue template, please fill out the issue template for future issues.
