### ISSUE TITLE
Precision scrolling on Linux with Wayland

### ISSUE THREAD

**Issue by ssfrr** [atom/atom#18592]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

First to clarify some definitions that often get conflated:

* smooth scrolling - adding animated transitions between scroll positions to smooth out the document motion. This is usually the best you can do with mouse wheels, which themselves usually have fixed rotation increments.
* Precision scrolling - touchpads can provide scroll events that are tied directly to your finger position, so the user has continuous control of the document position. This is also sometimes called "pixel-perfect" scrolling (but that seems like a misnomer to me because there isn't a 1-to-1 mapping from touchpad pixels to screen pixels, and AFAICT scroll events are reported as floating-point values).

This issue is about precision scrolling, not smooth scrolling.

There's [an issue](https://github.com/atom/atom/issues/5359) that's mostly focused on "smooth scrolling", but I wanted to try to extract the precision scrolling, which is a separate issue.

In [this comment](https://github.com/atom/atom/issues/5359#issuecomment-340161559) @damianmoore says that precision scrolling is working on Linux but that he hasn't tested Wayland. I'm using Wayland and it does not seem to be working.

If you're interested in how Wayland / GTK handle scroll events I did a pretty deep dive [here](https://gitlab.gnome.org/GNOME/gtk/issues/1308#note_336954). Not sure how much is relevant to Atom though.

### Steps to Reproduce

1. Set up a linux machine with Gnome-Shell / Wayland (I'm using Arch Linux)
2. Install atom 
3. scroll a document with a touchpad

**Expected behavior:** scrolling should precisely follow my fingers

**Actual behavior:** document scrolls in fixed step sizes

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.33.0
Electron: 3.0.11
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

Wayland 1.16.0
Gnome-shell 3.30.2

**Comment by rsese** [comment]
Just looking through some issues that haven't had a reply yet - thanks for the definitions for precision vs. smooth scrolling, it's not something I pay much attention to to be honest but I know others do :+1:

One initial comment though:

> Atom    : 1.33.0
> Electron: 3.0.11

Based on this version information, we can see that you're currently using an unofficial build or distribution of Atom (i.e. the current release version of Atom, 1.35.1 is on Electron. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

I believe on Arch people have mentioned that the atom-editor-bin package from the AUR at least uses the correct Electron version - does using this version make any difference?

**Comment by ssfrr** [comment]
Thanks for the extra info, that's totally reasonable.

I installed using the AUR as you recommended and am still not seeing precision scrolling, the scroll jumps by discrete increments.

Here are my current versions:

```
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
