### ISSUE TITLE
About adding HTML functionality

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#18616]
## Summary

> `autoclose-html` `emmet`  `tag`
> These plug-ins affect the atom completion system itself, but they are exactly what atom needs！

## Motivation

> 1. Atom's HTML auto-completion plug-in supports tag validation(The latest version also doesn't seem to support HTML tag validation)
> 2. But neither plug-in validates HTML tags, which means that any character can be a tag
> 3. This directly invalidates atom's own built-in HTML tag validation

## Describe alternatives you've considered

> Due to personal knowledge and energy issues, I have no time to modify the source code

## Additional context

![default](https://user-images.githubusercontent.com/8848263/50380989-d130e300-06b5-11e9-9950-9cf32bffe650.gif)

**Comment by rsese** [comment]
Thanks for the suggestion!  Though this sounds like a neat idea for some people's workflows it's not something the team would work on, and it also seems like a good idea for a package.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). But I'm also going to label this with `package-idea` so that others searching for suggestions here can find this.

**Comment by linjialiang** [comment]
> @rsese I used to use VPN all the time, but now VPN is not working well

**Comment by rsese** [comment]
> This has nothing to do with your official websites.

:+1:  If you find a reproducible issue with https://atom.io that isn't related to how you connect to the internet, you can let us know in https://github.com/atom/atom.io.

**Comment by linjialiang** [comment]
> ok
