### ISSUE TITLE
Atom editor does not come to foreground in Windows 10

### ISSUE THREAD

**Issue by ps374** [atom/atom#18610]
Hi, 

When I click Atom icon then it never comes to foreground, just runs in the background. I have tried Atom version 1.32, 1.33 and 1.34 (Preview release) but the problem persists. Here is a screenshot depicting Atom is running in the Background (Windows 10):
![49720983-32ed5800-fc87-11e8-9cfe-81ed4c67a425](https://user-images.githubusercontent.com/10158104/50328007-4f0ab800-0517-11e9-8b28-1e113c891eae.png)

Thank you very much for any help!

**Comment by steveward** [comment]
Thanks for opening this @ps374. Are you able to reproduce this issue when launching Atom in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? It would also be helpful if you could fill out the issue template so that we can verify you have followed the recommended [debugging steps](https://flight-manual.atom.io/hacking-atom/sections/debugging/#debugging).

**Comment by ps374** [comment]
It worked this time :) 

I am not sure how but I had just deleted the **.atom-backup** directory from **C:\Users\<USER>** profile folder and then run **Atom** as Administrator that worked like a charm.

Lovely :)

**Comment by rsese** [comment]
Not sure what the issue was but glad things are working for you again, we'll go ahead and close for now.
