### ISSUE TITLE
close save

### ISSUE THREAD

**Issue by tonycody** [atom/atom#18618]
When closing the atom, what must be said to save the open tab? Like notepad++, can't it? The tab created by notepad++ support is only for temporary use. To close notepad++, you don't have to save the open tab. The next time you open it, the unsaved tab is still there. It is meaningful to save the data temporarily. I hope to support it.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

> When closing the atom, what must be said to save the open tab? 

I'm not sure I understand the question completely but it seems like you're wondering why you're not prompted to save unsaved files when you close Atom?  If that's the case, it's expected behavior when you have a project open, that unsaved file is saved in the project state and will be restored when you reopen the project.
