### ISSUE TITLE
TextMate syntax colors are nicer than with tree siter.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18626]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I like that with non-tree-sitter mode I get better coloring:

<img width="751" alt="screen shot 2018-12-27 at 10 38 28 pm" src="https://user-images.githubusercontent.com/297678/50505387-265b5480-0a28-11e9-9850-330b1a487b7b.png">

while here's the same thing with tree-sitter enabled:

<img width="769" alt="screen shot 2018-12-27 at 10 39 10 pm" src="https://user-images.githubusercontent.com/297678/50505405-3d9a4200-0a28-11e9-9b78-3cadf6c19465.png">

It's more bland, for example the `this` keyword is no longer distinctly highlighted, and the `last.nested.key` in a path of key accesses is also no longer distinctly highlighted (f.e. look at `this.state.heldKeys`).

Both however do highlight method calls blue.

### Steps to Reproduce

1. just compare both

**Expected behavior:**

It'd be great for the tree-sitter coloring to be as nice as TextMate

**Actual behavior:** 

as above

**Reproduces how often:** 100%

### Versions

<details>
  <summary>debug info with package info</summary>

```json
{
  "atom": "1.33.1",
  "platform": "darwin",
  "release": "18.2.0",
  "vmpVersion": "1.36.0",
  "vmpConfig": {},
  "activeCommunityPackages": [
    "language-javascript-jsx: 0.3.7",
    "atom-material-syntax: 1.0.8",
    "aligner-javascript: 1.3.0",
    "atom-vim-like-tab: 1.5.2",
    "autocomplete-modules: 2.2.2",
    "autocomplete-paths: 2.12.2",
    "better-git-blame: 0.4.7",
    "busy-signal: 1.4.3",
    "cursor-history: 0.13.1",
    "docblockr: 0.13.7",
    "ex-mode-sort: 1.0.0",
    "file-icons: 2.1.21",
    "file-watcher: 1.2.6",
    "git-plus: 8.1.0",
    "hey-pane: 1.1.0",
    "highlight-line: 0.12.0",
    "highlight-selected: 0.14.0",
    "hyperclick: 0.1.5",
    "imdone-atom: 2.4.29",
    "indent-guide-improved: 1.4.13",
    "intentions: 1.1.5",
    "keystroke: 0.4.0",
    "linter: 2.2.0",
    "linter-eslint: 8.4.1",
    "linter-ui-default: 1.7.1",
    "linter-ui-plus: 0.3.2",
    "local-history: 4.3.1",
    "minimap: 4.29.9",
    "minimap-bookmarks: 0.4.2",
    "minimap-git-diff: 4.3.1",
    "minimap-highlight-selected: 4.6.1",
    "minimap-linter: 2.2.1",
    "minimap-pigments: 0.2.2",
    "minimap-quick-highlight: 1.0.1",
    "persistent-undo: 1.3.0",
    "pigments: 0.40.2",
    "prettier-atom: 0.56.2",
    "project-plus: 1.0.0",
    "quick-highlight: 0.13.0",
    "split-diff: 1.5.3",
    "teletype: 0.13.2",
    "todo-show: 2.3.0",
    "trailing-spaces: 0.4.0",
    "tree-view-git-status: 1.5.0",
    "undo-tree: 1.0.0",
    "vim-mode-plus: 1.36.0",
    "vim-mode-plus-keymaps-for-surround: 0.2.1",
    "zentabs: 0.8.9",
    "editorconfig: 2.2.2",
    "language-pug: 0.0.22",
    "language-vue: 0.23.1",
    "language-jenkinsfile: 0.1.1",
    "atom-typescript: 12.7.3",
    "termination: 0.7.0"
  ]
}
```

</details>

**Comment by trusktr** [comment]
Above is a TypeScript example, but the color differences seem about the same in JS files too.

I know about the performance benefits of tree-sitter, but so far I like to keep it off as the speed difference doesn't outweigh the nice TextMate coloring for me.

**Comment by rsese** [comment]
Thanks @trusktr :+1:

As mentioned in other issues (e.g. https://github.com/atom/atom/issues/18307#issuecomment-432738165 and this other issue you found https://github.com/atom/atom/issues/18120#issuecomment-424906547) some color changes are expected with Tree-sitter.  What we're mostly looking for are situations where the underlying scopes of tokens are incorrect, not that the color is different than it was before. Some differences may be expected, such as variables now being recognized the same in every location they appear instead of differently based on the context. 

If you want to see how Tree-sitter identifies the token at the current cursor position, you can open the Command Palette using Cmd+Shift+P on macOS or Ctrl+Shift+P on other platforms, then search for and execute "Editor: Log Cursor Scope". If the scope at the bottom is incorrect, please file an issue in the appropriate language repository (e.g. https://github.com/atom/language-typescript/ for Typescript) and describe what you expected instead.

Thanks!
