### ISSUE TITLE
Ctrl-Shift-f not work on atom-text-editor(window10)

### ISSUE THREAD

**Issue by zhangbg** [atom/atom#18645]
### Description
When I use atom editor in win10, "Ctrl-Shift-f" is not work on atom-text-editor(selector)， but it can work on body(selector).

### Steps to Reproduce
1. work on body(selector)
![image](https://user-images.githubusercontent.com/6231441/50681560-eb1fdd80-1046-11e9-9204-2419981cccab.png)

2. not work on atom-text-editor(selector)
![image](https://user-images.githubusercontent.com/6231441/50681605-1d313f80-1047-11e9-923f-7b3b981acdc3.png)

### Versions
![image](https://user-images.githubusercontent.com/6231441/50681686-5bc6fa00-1047-11e9-9c8f-ab2980018076.png)
![image](https://user-images.githubusercontent.com/6231441/50681707-6aadac80-1047-11e9-9e06-c595cb05bfe0.png)

**Comment by Arcanemagus** [comment]
It sounds like you have an external program grabbing that keyboard shortcut before it reaches Atom, otherwise it would be showing in the Keybinding resolver.

You can follow the steps in [this answer](https://superuser.com/questions/11308/how-can-i-determine-which-process-owns-a-hotkey-in-windows/1204019#1204019) in order to determine which program it is if you don't know one that might be doing it. For example I've had my graphics driver globally grab <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> before and found it using that tool.

**Comment by zhangbg** [comment]
@Arcanemagus I don't think so, because "ctrl + shift + f" can work on the **settings** pane, but it can't work one the **atom-text-editor** pane.

**Comment by zhangbg** [comment]
I find the reason by myselt, It is affected by **Microsoft Input**  shortcut in win10. 
@Arcanemagus Thanks, anyway.
![image](https://user-images.githubusercontent.com/6231441/50828461-6e5d6e00-137c-11e9-90cd-5e72e9e3b281.png)
