### ISSUE TITLE
Bug #8951 is still a bug. Atom opens files in the wrong instance.

### ISSUE THREAD

**Issue by marc1uk** [atom/atom#18654]
With Atom 1.33.1x64 on Windows 10, I have several files open. I need to edit another file, but due to windows restrictions, it must be opened with a program running as administrator, so i start a new instance of Atom as administrator. However, using File->Open to open the file from the new instance results in the file being opened in the old instance. I can't save the changes. 
This bug was reported previously, receieved no feedback, and was closed because of inactivity. Ignoring a bug does not make it go away.

**Comment by rsese** [comment]
Thanks for reaching out - we do sometimes miss following up on issues but in any case, the issue template should be filled out for new issues to help us triage.  Not sure if this would fall under this larger startup issue at https://github.com/atom/atom/issues/10517 but once the template details are filled in, we can reopen and go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
