### ISSUE TITLE
Atom refuses to close command prompt

### ISSUE THREAD

**Issue by scrembo** [atom/atom#18653]
Hi - I have a bug with Atom.

Working on c++ file and running the compiler with f5 but it refuses to close - command prompt remains open and I am no longer able to run the compiler, not sure what to do in order to close it!

I am also getting this error once I try running it again on Atom
"c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot open output file C:\Users\User\AppData\Local\Temp\save.exe: Permission denied 
collect2.exe: error: ld returned 1 exit status"

Can you guys help me ?

**Comment by scrembo** [comment]
It is also not working to close form the task manager.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Additionally, it sounds like you're having trouble with a community package - in this case, you should reach out to the package maintainers for help.  The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
