### ISSUE TITLE
Docker integration and build request icon in UX

### ISSUE THREAD

**Issue by hmwoliul** [atom/atom#18677]
## Summary

Add Docker build request icon in window.

## Motivation

This help user to request build to docker repo.

## Describe alternatives you've considered

If it add as a feature this could help user. Other wise if its add as package this will need install after atom installation.

## Additional context

Add as a debug mode icons.

**Comment by rsese** [comment]
Thanks for the suggestion!  I'm not sure if I understand exactly what you're describing but you mentioned:

> Other wise if its add as package this will need install after atom installation.

If this can be achieved with a package, we prefer that folks take advantage of Atom's customizability especially since we're unlikely to work on feature requests at the moment as mentioned in the issue template.   So since this can be done in a package and it's something the team wouldn't prioritize, we'll close for now but thanks again for your interest.
