### ISSUE TITLE
atom can't phase config file with eslintrc.js

### ISSUE THREAD

**Issue by zhengwenjiee** [atom/atom#18671]
This my problem.
I use vue-cli create a project, the project has .eslintrc.js config file.
when opening a js file with es6 syntax.  atom gave a w119 warning.
I don't want add another file  like jshintrc. 

can atom support eslintrc.js file as linter ?
thanks for the help.

**Comment by Arcanemagus** [comment]
Thank you for reaching out!

It would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
