### ISSUE TITLE
Atom javascript error

### ISSUE THREAD

**Issue by iAMxGiGO** [atom/atom#18673]
hi i got this error after updating a few plugins, and im not sure which one is causing this issue. i get this pop up when i start atom, of course the program doesnt open at all. any help is appreciated.
![atom error](https://user-images.githubusercontent.com/43787034/50967601-9dddb900-14e9-11e9-8160-6b486e2b0935.jpg)

**Comment by rsese** [comment]
Thanks for reaching out!

As mentioned below, please fill out the issue template when creating issues, the information in the template is super helpful for us when triaging issues.

In particular, as mentioned in the `Prerequisites` section, please confirm if you have the same trouble in safe mode and if any other suggestions in the debugging guide help (like temporarily resetting to factory defaults for example).

Once you add more details we can take a look.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
