### ISSUE TITLE
Break between welcome guide and welcome

### ISSUE THREAD

**Issue by HarsheetKakar** [atom/atom#18683]
there are 2 ways we can tackle this problem

1. by removing the welcome guide which has already been raised
2. by removing the "break" b/w welcome guide (and possibly the opened file with it) and the welcome tab so everything can be closed with ctrl-w (currently u need to use shift tab to get on the "welcome" side and then you can use ctrl-w)

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

In particular, I'm not 100% sure I understand the issue so specific numbered steps to reproduce the problem you're describing would be helpful along with the rest of the template details.
