### ISSUE TITLE
Auto-save untitled buffers not working

### ISSUE THREAD

**Issue by MicWit** [atom/atom#18681]
I currently use Sublime and am looking at moving to Atom and the main feature it lacks is opening an unsaved file when launching Atom. The initial request for this was #942 and according to the report it was implemented in 1.4.0. I am now using 1.34.0 and it is not working, so I have submitted it as a bug. If this is a feature that was removed, this should be submitted as a feature request.

One way I think this could work well would be to have a setting that would be auto-save location. Then basically it is implementing an auto save feature where every open "file" (it may not be a saved file open, rather just an unsaved New File in Atom) would auto save to that location. Then Atom just needs to remember which files were open and in what order when it is opened and re-load the auto save file (or in some cases the files that have been saved out in different locations).

When a file is saved or closed (with or without saving), the auto save file is deleted.

By doing it this way, the auto save directory could be stored on a cloud service (maybe along with the list of opened files when Atom was last closed) so that when Atom is opened on a different device, the same files will open again. This way you can leave code snippets, notes, lists etc open and not have to save them out anywhere and know they will be there next time. This would be similar to how Sublime works, and like with Sublime, that may cause issues for files you opened locally, left open and then opened Sublime (in this case Atom) on another machine. Sublime just removes those files, I think a better idea would be to have a tab grayed out that if you go to, informs you that the original file can not be found, so there would be no content in it if it had been saved, if not it would have the auto save file and would tell you you can not save changes back to the original file as its not available. That way you can decide to close that tab or leave it there and when you go back to the machine the file is on it would become available again.

**Comment by rsese** [comment]
Thanks for reaching out!

As mentioned below, the template details are super helpful for us when triaging issues.  Please fill out the issue template and we can reopen and take a look.

In particular, steps to reproduce would be helpful - https://github.com/atom/atom/issues/942 was resolved by saving unsaved files in project state I believe.  E.g. with these steps:

1. Open some existing project `atom myProject`
2. Create a new file
3. Type something in the new file e.g. "hello world"
4. Quit Atom
5. Start Atom `atom myProject`

Expected and actual behavior is the untitled new file created in step (2) to be opened with "hello world" in the file.

There is a particular case where untitled buffers aren't automatically saved however as described in https://github.com/atom/atom/issues/13318 (when there's no project, but in that case you're prompted to save the file or not).

Without steps to reproduce however, it's not clear what you're running into.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
