### ISSUE TITLE
Context menu in MacOS: "Show in File Manager" should be "Show in Finder"

### ISSUE THREAD

**Issue by mjrodgers** [atom/atom#18694]
When I right-click a file in the tree explorer on MacOS, I no longer have an option for "Show in Finder"; it now says "Show in File Manager". This is rather confusing. I don't have a program called "File Manager", since that is a Windows thing.

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report - this change was intentional I believe, see the "Possible Drawbacks" section in https://github.com/atom/tree-view/pull/1266.  So we did it so that Atom would use whatever file manager a person might have configured but the mentioned drawback is that it's not possible through Electron to know which file manager is used and "File Manager" was the generic term used (I think it's "Windows Explorer" in Windows, a Windows-specific term wasn't chosen).  Let me know if I mis-understood anything in that pull request @50Wliu :v:

So since the team is in favor of the benefit of using whatever file manager someone set for their computer vs. the drawback of using a generic term for referring to the file manager, we'll go ahead and close this.

Lastly, please use the issue template when creating issues, the template details and format is super helpful for us when triaging issues.

**Comment by mjrodgers** [comment]
Ah okay, it is "File Explorer" not "File Manager" in Win10. Sorry for assuming this was a Windows-centric change.

I'll use the issue template in the future, some of the "test in safe mode" stuff seemed not applicable for this particular issue but I can understand that it is useful to have in general.

**Comment by mattlubner** [comment]
Is there a way to opt out of this change, or perhaps override it via a preference setting?

I only ask because this has noticeably hurt the usability of Atom for me. I run macOS and find myself constantly tripping over the non-standard nomenclature (ie. on macOS, it's standard for this menu item to be named "Reveal in Finder", which is what every Mac user has been trained to look for since before I became one).

I'd be surprised if Windows users aren't also tripping over the nomenclature change.

**Comment by 50Wliu** [comment]
You could try the following in your init.coffee, though this will not remove the existing menu item, only add a new one.
```coffee
atom.contextMenu.add({
  '.tree-view .full-menu': [{'label': 'Show in Finder', 'command': 'tree-view:show-in-file-manager'}]
  'atom-pane[data-active-item-path] .tab.active': [{'label': 'Show in Finder', 'command': 'tree-view:show-in-file-manager'}]
  'atom-text-editor:not([mini])': [{'label': 'Show in Finder', 'command': 'tree-view:show-in-file-manager'}]
```

**Comment by mattlubner** [comment]
Thanks, @50Wliu, but I still believe we should still address the default naming choice, as it hurts usability for more people than benefit from this change.

The issue for me is that "Show in File Manager" sounds like some new / custom Atom functionality, not "Open in your chosen file manager application, which is probably just Finder / Windows Explorer". Keep in mind that platforms (macOS / Windows) have been training us to expect standardized nomenclature for as long as we've been users. Those norms deserve to be respected, because they help to keep applications out of the way of the user.

How would you feel about reverting just the name-change portion of atom/tree-view#1266? That would mean Windows users would see "Show in File Explorer", but it would still open the selected file/folder in the user's third-party file manager application. And similarly for Mac users, they'd see "Show in Finder" (although it should really be "Reveal in Finder"). That might be slightly confusing at first for the rare dev that actually uses a third-party file manager, but in exchange, the majority of users won't trip over this non-standard nomenclature. Would this be an acceptable compromise?

**Comment by 50Wliu** [comment]
@mattlubner would you mind creating a new issue in [atom/tree-view](https://github.com/atom/tree-view) and cc-ing me on it? I'll ask the team what they think.

**Comment by mattlubner** [comment]
No problem!
