### ISSUE TITLE
Installation has failed (windows 7)

### ISSUE THREAD

**Issue by Sasha1259** [atom/atom#18701]
So bassicly I tried to reinstall the Atom and this error showed up,everything worked before the reinstallation.Please help!

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

For Windows install problems, please share your `%LocalAppData%\atom\SquirrelSetup.log` file.  Also, if you have anti-virus software running try temporarily disabling it and then install again.
