### ISSUE TITLE
Atom snaps in ubuntu slow start due to spell-check package

### ISSUE THREAD

**Issue by araviaravi** [atom/atom#18716]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode [x]
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/ [x]
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq [x]
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom [x]
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages [x]

### Description

The default plugin spell-check never worked for me. It added hell alot of load time to atom IDE. I am using Ubuntu 18.04 and atom snaps.

### Steps to Reproduce

1. Enable spell-check plugin and reboot atom snap package. - 3 to 5 mins
2. Disable spell-check plugin and reboot atom snap package. less then 10 seconds

**Expected behavior:** As guided in  package, I have hunspell installed in ubuntu. But this package never started with IDE. Due to failure, its adding up too much time.

**Actual behavior:** Plugin failure is ok. But the boot time and slow behavious is too much.

**Reproduces how often:** Every time you restart atom snap / inbetween working 
### Versions
aravind@comp:~$ apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15rc1
git 2.17.1

### Additional Information

1) Ubuntu 18.04
2) Atom Snapd any stable release.
3) hunspell-en-gb

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
