### ISSUE TITLE
Atom still asks me a ssh passphrase

### ISSUE THREAD

**Issue by devcline** [atom/atom#18721]
I am able to push and pull successfully, but I am prompted for my passphrase every time, even though I put my identity into ssh-agent and in git bash it works without asking a passphrase. How can I stop atom from prompting me for my passphrase every time?

- ` ssh-agent `is running
- i can pull fetch from bash without asking me passhrase (asked only first time)
- a git on my server (not GitHub repository) and as client windows 10
- im my `.ssh` folder there is a `config, id_rsa and known_hosts`
- i use `ssh://` url
- `git config --global credential.helper wincred` dosent help cause its for https
 - followed [this guide ](https://help.github.com/articles/working-with-ssh-key-passphrases/)
- **GIT GUI** and **ATOM** Asks me a passphrase, but not bash

the config file
```
Host *
    IgnoreUnknown UseKeychain
    UseKeychain yes
    AddKeysToAgent yes
    IdentityFile ~/.ssh/id_rsa
```

From Git Bash:
```
XXXX@DESKTOP-6A5PT MINGW64 /h/Develop/XXX (master)          
$ git push -u origin master                                                      
stdin: is not a tty                                                              
Everything up-to-date                                                            
Branch 'master' set up to track remote branch 'master' from 'origin'.
--
```

the .bashrc
```
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env
```

the agent.env
```
SSH_AUTH_SOCK=/tmp/ssh-lG207sSiLY2x/agent.1752; export SSH_AUTH_SOCK;
SSH_AGENT_PID=16064; export SSH_AGENT_PID;
echo Agent pid 16064;
```

Why doesn’t ssh-agent works as it needs to? Im missing something?

![image](https://user-images.githubusercontent.com/617020/51380043-13acda80-1b11-11e9-9a1a-c3f9d4246627.png)

thanks

**Comment by Aerijo** [comment]
I believe generating and using a token in the prompt for Password should work.

**Comment by devcline** [comment]
@Aerijo im sorry can i have more info? where is it ? its for github no ?

**Comment by rsese** [comment]
@devcline - did you also try manually running `ssh-add` from the command line and then starting Atom?

For reference, there's a general issue requesting the GitHub package remembers your passphrase (separate from ssh-agent) at https://github.com/atom/github/issues/1747.

As Ash mentions in https://github.com/atom/github/issues/1747#issuecomment-430596421, using ssh-agent should work as a workaround so it seems like there's some issue with your setup (it looks like you've run through https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-windows and https://help.github.com/articles/working-with-ssh-key-passphrases/#platform-windows). 

But you also mentioned "GIT GUI and ATOM Asks me a passphrase" so it sounds like an issue not specific to Atom?   Since it's not specific to Atom, we're going to go ahead and close, but feel free to reach out on the [message board](https://discuss.atom.io), the [Atom Slack](http://atom-slack.herokuapp.com/), or the [GitHub Community Forum](https://github.community/) - there's a number of community members that are happy to help.  If you reach out on the message board, feel free to @ mention me and I can try to help as well.
