### ISSUE TITLE
Atom electron crashes at startup while running under nvidia-xrun

### ISSUE THREAD

**Issue by minecraft2048** [atom/atom#18724]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With Xfce4, under LightDM and using Intel graphics card Atom works just fine, but if I run Xfce4 under nvidia-xrun when I try to start Atom it crashes with this error message:
```
 feanor  silmaril  ~  $  atom --safe
/usr/bin/electron: symbol lookup error: /usr/bin/electron: undefined symbol: _ZN2v87Context3NewEPNS_7IsolateEPNS_22ExtensionConfigurationENS_10MaybeLocalINS_14ObjectTemplateEEENS5_INS_5ValueEEENS_33DeserializeInternalFieldsCallbackE
```
### Steps to Reproduce

1. Run a DE under nvidia-xrun, in my case I'm using Xfce4 with startxfce4 as its launcher
2. Start Atom

**Expected behavior:** [What you expect to happen]

Atom can starts

**Actual behavior:** [What actually happens]

Atom crashes with symbol lookup error

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions
```
feanor  silmaril  ~  $  atom --version
Atom    : 1.34.0
Electron: 3.0.13
Chrome  : 66.0.3359.181
Node    : 10.2.0
 feanor  silmaril  ~  $  apm --version
apm  2.1.3
npm  6.5.0
node 11.6.0 x64
atom 1.34.0
python 2.7.15
git 2.20.1
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Aerijo** [comment]
@minecraft2048 Does this happen to VS Code as well? If so, it could be an Electron or higher problem (which the error indicates).

**Comment by minecraft2048** [comment]
If I run electron command it does crash with the same error message

**Comment by rsese** [comment]
Looks like the Electron issue was closed and you mentioned you can't reproduce with Electron 4?  But in addition to that:

> Atom : 1.34.0
> Electron: 3.0.13

Based on the version details, we've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
