### ISSUE TITLE
lock bot spam

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#18736]
Any chance you guys could turn down the lock bot spam, I have a lot of issues subscribed and I get about 20 notifications per day just from those bot actions and there does not seem to be a away to ignore them.

**Comment by simurai** [comment]
I got 1470 in only a single day.. :upside_down_face:

![image](https://user-images.githubusercontent.com/378023/51647651-01271b00-1fc1-11e9-80f6-028c14e5702d.png)

I wish there is an option to turn off notifications for lock and stale bot.

**Comment by Aerijo** [comment]
I just set up email filters for all Atom GitHub notifications. Bots are completely silenced, and messages are sorted and archived automatically once a day. No manual effort required.

Keeps the inbox clean, and you only see what you let through.

**Comment by Aerijo** [comment]
Wait, is this not about email notifications? I’ve never set up the website notifications that @simurai is showing it seems. My comment wouldn’t apply to that.

**Comment by Arcanemagus** [comment]
This is due to a bug in the GitHub API having been fixed: https://github.com/dessant/lock-threads/issues/5#issuecomment-455517081

These issues were originally _supposed_ to have been locked way back when we first enabled the lock bot in https://github.com/atom/atom/pull/17041, but were missed then due to this API bug. As we still feel that having these issues locked is the right thing unfortunately there isn't much that can be done other than marking the notifications as read if you are using the web interface for managing them. (And since I am, I definitely feel your pain!)

Thanks for reaching out!

We have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.

**Comment by Arcanemagus** [comment]
I haven't seen any new ones in a few hours, we might finally be caught back up again 🎉.

**Comment by dessant** [comment]
The progress can be checked with this query: https://github.com/search?q=repo%3Aatom%2Fatom+updated%3A%3C2018-07-28+is%3Aissue+is%3Aclosed+is%3Aunlocked

**Comment by Arcanemagus** [comment]
Okay _now_ it looks to be done. There are only 54 issues in the backlog query posted above, and it is back to locking individual issues here and there instead of large batches.
