### ISSUE TITLE
Command list: Make key binding boxes a button that adds it to keymap.cson

### ISSUE THREAD

**Issue by DiThi** [atom/atom#18740]
A very common issue with customizing keybindings is that one doesn't know the command (e.g. `'editor:toggle-line-comments'`) even if it's literally the command you see in the command list, but lower case and with dashes. The issue is probably worse when the editor is localized (I don't even know how one changes the language, but that's another issue).

The change I propose is very simple: When you click the box you see in the command list, have that command and key added to keymaps.cson.

And for commands without key binding, have a key box that says "no key" or something.

For commands with key at least you can find them in settings -> keybindings, the main confusion comes with unbound commands. An alternative would be to show all possible commands in that list.

A third alternative, have a tiny "copy to clipboard" icon to the command list, just like in settings -> keybindings.

**Comment by rsese** [comment]
Thanks for reaching out!

In addition to filling out the issue template, command palette suggestions should go in https://github.com/atom/command-palette.  But from this idea:

> A third alternative, have a tiny "copy to clipboard" icon to the command list, just like in settings -> keybindings.

Though not in the command palette, you can copy keybindings from the keybinding resolver, added in https://github.com/atom/keybinding-resolver/pull/62:

![copy-keybinding](https://user-images.githubusercontent.com/734194/51714671-9c3ce680-1ffb-11e9-99bb-79e2ddebe5ae.gif)

> For commands with key at least you can find them in settings -> keybindings, the main confusion comes with unbound commands. An alternative would be to show all possible commands in that list.

There's an issue for this if you want to subscribe: https://github.com/atom/settings-view/issues/165

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
