### ISSUE TITLE
How to use it with HDPi? 

### ISSUE THREAD

**Issue by sambuev** [atom/atom#18768]
Hello, how to scale up entire UI in Atom? I run 4K screen on 17inch laptop, I would like to scale entire interface two times to make text visible. Thanks.

**Comment by daviwil** [comment]
Atom currently doesn't have a built-in mechanism for scaling its UI components.  However, you can try the following community package to achieve it:

https://atom.io/packages/hidpi

**Comment by rsese** [comment]
Thanks for reaching out!

Going to close since David answered the question but also please keep in mind for future issues that because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
