### ISSUE TITLE
Scrolling does not work in tree-view/settings after some time

### ISSUE THREAD

**Issue by malnvenshorn** [atom/atom#18780]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After some time working with atom it is not possible to scroll with the mouse wheel anymore within the tree-view and settings pane. Scrolling in files is still working.

### Steps to Reproduce

1. Start Atom
2. Load project
3. Start working
4. Wait...

**Expected behavior:** [What you expect to happen]

That the scrolling works

**Actual behavior:** [What actually happens]

Scrolling stops working

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%, but the time till this happens varies

### Versions

```
atom --version
Atom    : 1.34.0
Electron: 3.1.1
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

```
apm --version
apm  2.1.3
npm  6.7.0
node 11.9.0 x64
atom 1.34.0
python 2.7.15
git 2.20.1
```

### Additional Information

Unfortunately I haven't found out what triggers this behavior.

**Comment by rsese** [comment]
Thanks for the report!  Just to clarify, you were able to reproduce the behavior in safe mode?  Also, it's just the settings and tree view that don't work, you can still scroll in a file?

**Comment by malnvenshorn** [comment]
Yes it also happens in safe mode and yes I can still scroll in a file.

I can also scroll in the tree view and settings by dragging the scroll bar. It's just not possible using the mouse wheel. Reloading the window (ctrl+shift+f5) temporarily solves the issue.

**Comment by rsese** [comment]
Oh sorry, I missed this:

> Atom : 1.34.0
> Electron: 3.1.1

Based on these versions, we've determined that you are currently using an unofficial build or distribution of Atom (the official stable release of Atom 1.34.0 is on Electron 2.0.16). Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by malnvenshorn** [comment]
Ah, thanks for that information. I've never noticed that my distribution ships atom with an unsupported version of electron as dependency.

I installed atom using the official deb package and haven't noticed this bug the whole day.

```
atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by rsese** [comment]
Great thanks for confirming, glad you're not seeing that issue anymore - we are updating to Electron 3 soon (/cc https://github.com/atom/atom/pull/18603) so if you do notice issues with the official release, please let us know :v:
