### ISSUE TITLE
Atom hide closing html tag when folding

### ISSUE THREAD

**Issue by chepkasoff** [atom/atom#18806]
I want to always fold endling/closing tag when folding.
In HTML it doesn't work :-(
Is that possible to config?

I tried this one but it doesn't work:
```
".basic.html.text":
  editor:
    foldEndPattern: true
```

Thanks in advance for help!

![image](https://user-images.githubusercontent.com/12602510/52352972-e7a8b900-2a2d-11e9-8a75-5d49344f69bc.png)

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

I went ahead and double checked with the other maintainers and found that with the move to [Tree-sitter](https://blog.atom.io/2018/10/23/atom-1-32.html#tree-sitter) the folding behavior isn't adjustable in settings though this could change in the future.  We'll let the team know it's something you're interested in.

If hiding the closing tag on fold is super important to your workflow, you could temporarily disable Tree-sitter at `Settings > Core > Enable Tree Sitter Parsers` but the folding in general is much improved with Tree-sitter.

**Comment by chepkasoff** [comment]
Thanks a lot @rsese !
