### ISSUE TITLE
Multi-language Project

### ISSUE THREAD

**Issue by SarcasticWatermelon** [atom/atom#18814]
Hello, I am currently trying to run a program that combines the languages of Javascript, HTML, and CSS all into one project that will do something. I am confused as to how I can run all of them at once. Can someone please provide some more detail on how I might run this project? Here is a link to the website that I am learning the code from: https://enlight.nyc/tracks/web. Thanks! I am aware that this issue was posted on the rgbkrk/atom-script issues section, but I decided to post it here because I am a  newcomer to GitHub and am not sure which one would fit better.

**Comment by Arcanemagus** [comment]
Atom itself doesn't provide any functionality for running code, you'll have to contact whatever community package you are using for this functionality if you need help with it.

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
