### ISSUE TITLE
Downloading an update without asking causes problem for users on mobile data plans

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1882]
Halp ticket:
* support/95b88d8ac5d011e388dbf5393005f408

> Please make Atom ask before downloading an update or make the auto-update configurable.

> I am working on the road a lot and it ruins my mobile data package.

So, asking before downloading an update or providing an option to turn off auto-updating might be helpful in these cases, I suppose.

**Comment by zyklus** [comment]
+1 -- I just had to block Atom's access to the internet in order to actually get anything done.

- I'm in Indonesia, internet here sucks in most places
- There's an atom update out and whenever atom is open is _always_ tries to download this update
- It's using 100% of my bandwidth to attempt to download a file that will _never_ succeed
- My internet basically goes from slow-as-a-turtle to non-existent because of this
- I can't disable it

**Comment by artcommacode** [comment]
+1

Maxing out my 60KB/s for an hour with no way to disable it is extremely frustrating.

**Comment by Zireael07** [comment]
Slows my net down to a crawl and makes me avoid my limited bandwidth backup connection. Please make it configurable.

**Comment by mastazi** [comment]
After every update Atom creates an unwanted icon on desktop and deletes the link from my Windows taskbar which is clearly super-annoying... 
Sometimes there are several updates per week and this user-unfriendly behaviour has become unbearable, I need to disable auto-updates and only update maybe once a month.

**Comment by 50Wliu** [comment]
> creates an unwanted icon on desktop and deletes the link from my Windows taskbar

Both of these are bugs (#8789 and *maybe* #7374?).

**Comment by jtlowe** [comment]
Yes, this will be a very appreciated feature. I too have a limits on bandwidth and data allocation, and would like to download updates at an ideal time. This is very important for me.

**Comment by mastazi** [comment]
> Both of these are bugs (#8789 and maybe #7374?).

Thanks @50Wliu,
#7374 Might have been fixed with the last update (v1.0.16) according to the release notes ( https://atom.io/releases), even though #7374 might be slightly different from the problem I'm experiencing (my taskbar icon is not duplicated, it just disappears). 
Observing the link properties, I can see that it now points to the version-agnostic path [...]/atom/update.exe instead of [...]/atom/1.0.XX/atom.exe, this might be a good sign.
I have temporarily re-enabled the connection in my firewall preferences and I'll see what happens with the next update.

**Comment by mastazi** [comment]
I confirm that both #7374 and #8789 seem to be fixed as of Atom v1.0.18, updated this morning and no problem whatsoever.
Anyway I still support this very issue (#1882) because it can be problematic for users with slow/unreliable connection.

**Comment by robyoder** [comment]
+1

**Comment by TGOS** [comment]
+1 Since the first day I started using Atom I search for the option to disable Auto Update. Every damn Software on this planet allows that, Atom is really the only App I know that forces me to download updates and this is the reason why I hardly ever use it! It just sucks that whenever I open it it downloads an update. And no, I cannot block it's Internet Access, I need Internet Access in Atom (I have plugins that need it) I just want that Atom stops updating without my permission, what is so hard to understand about that?

**Comment by hwestbrook** [comment]
+1, atom v1.2.3 breaks plugins for me, specifically spark-dev. I have to downgrade each time I want to use it.

**Comment by jtlowe** [comment]
This issue is a main reason why I am no longer using Atom. I really enjoyed the interface and community but auto-downloads on a limited connection and performance issues keep getting in the way. I hope the team can resolve this.

**Comment by idmit** [comment]
Is there a reason why it's not implemented yet? Seems like a fairly easy thing to add.

**Comment by zaczh** [comment]
+1 in China the download is unreliable and slow. It really shouldn't be enabled by default.

**Comment by rbq** [comment]
I checked out Atom a couple of months ago and immediately removed it because of this extremely annoying behaviour. It's just not acceptable that an applications downloads/executes binaries from the web without permission, randomly changes it's behaviour from time to time or maybe brakes plugin compatibility just because you happened to restart it. This is insane as a default and even worse if you can't opt out. Please fix this.

**Comment by paspil** [comment]
+1 wan't to stay on 1.2.4 because of #666 and #10136

**Comment by 50Wliu** [comment]
I believe that this has been fixed by #9990 and will be available in 1.5.0.
