### ISSUE TITLE
Cant figure out how to set atom as my PCs default editor?

### ISSUE THREAD

**Issue by legoman8304** [atom/atom#18834]
## Summary

Hey all, I cannot seem to figure out how to set atom as my default editor for code files. I'm not sure if this feature has already been implemented or not. This is much like #4893 however that fix was for windows 7 and text files. My feature would work much like VSCode: When installed it sets itself as the default program for most code files (.html, .css, .js, .cpp, etc.) It makes it much eaiser to simply open the file I want rather than constantly right click > open with > atom

## Motivation

Expected outcome: Simply a button in settings to set it as the default program for a set of files, or on install a checkbox to set it up like that.

## Describe alternatives you've considered

I can not think of any other alternatives that would work for this.

**Comment by rsese** [comment]
Thanks for the suggestion! 

> Hey all, I cannot seem to figure out how to set atom as my default editor for code files.

Just to clarify, are you having trouble using Windows to set Atom as the default application for a particular file type?  So the right click, choose `Open with > Choose another app`, select Atom, check the `Always use this app to open .extension files` isn't working?  I remember there was a Windows 10 bug that made this not stick but I think that's been fixed since.

About your suggestion in general, though it's a bit tedious at first to set Atom as the default application for whichever file types you're interested in, once it's set, you won't have to do it again.  And though I do think an option during install would be a neat shortcut for folks, it's not something the team would prioritize right now with the work they currently have on their plate but if anything changes we can always revisit this.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that [don't represent a task to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html) so we'll go ahead and close this out.

If you're having trouble setting Atom as your default program for a particular file type, feel free to reach out on the [official message board](https://discuss.atom.io/) and tag me and we can take a look.
