### ISSUE TITLE
Show changelog for new version in the Updates in Settings.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18833]
I often want to see the CHANGELOG for a package to see if I want to update to the latest version.

However, clicking the `CHANGELOG` button,

<img width="232" alt="screen shot 2019-02-11 at 4 58 13 pm" src="https://user-images.githubusercontent.com/297678/52604059-3be0de00-2e1e-11e9-9372-454f2d582eb7.png">

opens the CHANGELOG for the current version that I have installed of the given package, so we don't see any changes relating to the new version.

It'd be nice if it opened the updated CHANGELOG from GitHub, or similar.

**Comment by rsese** [comment]
Thanks again for sharing suggestions @trusktr - this belongs in https://github.com/atom/settings-view but it looks like there's an existing issue for the general idea at https://github.com/atom/settings-view/issues/282 so we'll close in favor of that issue.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
