### ISSUE TITLE
Error fetching from carbon: 404 - Not Found

### ISSUE THREAD

**Issue by ryotlee** [atom/atom#18846]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: Atom Core

### Stack Trace

Error fetching from carbon: 404 - Not Found

```
At undefined

undefined
```

### Commands

```
     -6:35.7.0 core:confirm (input.hidden-input)
     -6:35.7.0 window:install-shell-commands (atom-pane.pane.active)
  4x -3:36.8.0 core:backspace (input.hidden-input)
     -3:35.9.0 core:move-right (input.hidden-input)
 12x -3:35.5.0 core:backspace (input.hidden-input)
     -0:44 command-palette:toggle (input.hidden-input)
     -0:39.3.0 core:move-down (input.hidden-input)
     -0:31.3.0 core:confirm (input.hidden-input)
     -0:31.3.0 carbon:copy (input.hidden-input)
     -0:26.6.0 command-palette:toggle (input.hidden-input)
     -0:23.8.0 core:confirm (input.hidden-input)
     -0:23.8.0 carbon:copy (input.hidden-input)
     -0:09.1.0 core:copy (input.hidden-input)
     -0:07.9.0 command-palette:toggle (input.hidden-input)
     -0:03.6.0 core:confirm (input.hidden-input)
     -0:03.6.0 carbon:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-wx 0.1.1 
auto-complete-wx 0.12.0 
carbon 0.3.0 
docblockr 0.13.7 
language-vue 0.23.1 
language-vue-component 0.5.0 
vue-autocomplete 0.1.1 
vue-format 0.4.0 
```

**Comment by Aerijo** [comment]
Thanks for contributing!

It appears that this is being caused by the [carbon](https://atom.io/packages/carbon) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
