### ISSUE TITLE
TextBuffer.setTextInRange is deprecated.

### ISSUE THREAD

**Issue by honghaijs6** [atom/atom#18847]
The `undo` option is deprecated. Call groupLastChanges() on the TextBuffer afterward instead.
```
TextBuffer.setTextInRange (<embedded>:11:487488)
TextEditor.setTextInBufferRange (<embedded>:11:15252)
AtomReact.autoCloseTag (C:\Users\DellH2\.atom\packages\react\lib\atom-react.coffee:348:27)
<unknown> (C:\Users\DellH2\.atom\packages\react\lib\atom-react.coffee:379:24)
Function.simpleDispatch (<embedded>:11:1172318)
Emitter.emit (<embedded>:11:1173759)
```

**Comment by Aerijo** [comment]
The React package appears to be passing a deprecated optional param to the `setTextInRange` TextEditor method. It's still handled as before, so it shouldn't be broken (by that at least), but they really should be making an undo checkpoint and grouping explicitly now.
_____
Thanks for contributing!

It appears that this is being caused by the [react](https://atom.io/packages/react) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
