### ISSUE TITLE
Key binding by file type

### ISSUE THREAD

**Issue by ayanez17** [atom/atom#18853]
### Description
I'm trying to create a key binding that behaves differently based on the file type.
Ideally what id like to do is the following:

If the file type is _.md_ then run the command `markdown-preview-plus:toggle`
else run the command `script:run`

I know it's something along the lines of:

```
editor.command('custom:command', e => {
  if ( of file type .md) {
    markdown-preview-plus:toggle
  } else {
    script:run
  }
})
```

Then in the keymap.cson i have to add something like:

```
'atom-text-editor':
    'cmd-i': 'custom:command'
```

But obviously this is pseudocode. I've tried reading the documentation specifically [this](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#overloading-key-bindings)
but there isn't enough information.

**Expected behavior:** key binding is file specific 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by rsese** [comment]
Sorry pressed comment early :smile: - meant to add that in particular for this question, the best places to get help are the Atom Slack and the message board mentioned above.  I know related questions have come up in the message board in particular.  If I could help I would but I don't think I can get you to the actual implementation (or if it might even be more straightforward).

**Comment by ayanez17** [comment]
For anyone looking for the answer here it is:
https://stackoverflow.com/questions/54699933/key-binding-by-file-type/54712491#54712491
