### ISSUE TITLE
Why Packages not working in PHP files?

### ISSUE THREAD

**Issue by nriddhi** [atom/atom#18870]
I have downloaded portable Atom version 1.25.1. Also installed some packages. Packages working in html files, but not working in php files, any solution? My installed packages are, 
![screenshot_1](https://user-images.githubusercontent.com/8566791/52962942-bc787f00-33c8-11e9-80a0-80e56edc916f.png)

**Comment by lee-dohm** [comment]
Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
