### ISSUE TITLE
Rename Split Tab

### ISSUE THREAD

**Issue by theInfiTualEr** [atom/atom#18875]
For example, you got **_index.html_** and **_style.css_**. now **split right** _style.css_. then try to **rename** _style.css_ file from the **tab**, it gonna show _index.html_ to you to editing, **NOT** _style.css_. 
Atom 1.34.0 on Ubuntu

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
