### ISSUE TITLE
Please provide checksums for Atom releases [not for security]

### ISSUE THREAD

**Issue by snow8gaia** [atom/atom#18895]
### Prerequisites

* [x] The desire to install Atom.
* [x] Read https://github.com/atom/atom/issues/7635

### Description / Rationale

Same as https://github.com/portapps/portapps/issues/11

**Expected behavior:** Checksums are provided.

**Actual behavior:** They are not provided.

**Reproduces how often:**  Whenever the download is through a browser.

### Versions

1.34.0 and recent releases

### OS 
All supported by Atom.

### Example of Solution

Repo: https://github.com/neard/neard/releases
Website: https://neard.io/release/latest/

### Example of Super-Awesome Solution

Let me know I will insert it here.

**Comment by lee-dohm** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/7635. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
