### ISSUE TITLE
clean install of atom on osx fails to open a new window

### ISSUE THREAD

**Issue by tschellenbach** [atom/atom#18891]
A clean install of atom on osx fails to open a new window.

**step 1 - remove your configs:**

```
rm -rf ~/.atom
rm -rf /usr/local/bin/atom
rm -rf /usr/local/bin/apm
rm -rf /Applications/Atom.app
rm -rf ~/Library/Preferences/com.github.atom.plist
rm -rf ~/Library/Application Support/com.github.atom.ShipIt
rm -rf ~/Library/Application Support/Atom
rm -rf ~/Library/Saved Application State/com.github.atom.savedState
rm -rf ~/Library/Caches/com.github.atom
rm -rf ~/Library/Caches/Atom
```

**step 2 - download a fresh copy of atom**

**step 3 - start atom**

either via the CLI or by clicking the app

actual:

the atom icon shows up
![image](https://user-images.githubusercontent.com/265409/53205561-e493f800-35eb-11e9-8273-ee35ac2c227e.png)

expected:

a new atom window to open

expected 2:

a way to debug why atom fails to start

**Comment by rsese** [comment]
Thanks for reaching out!  Looks like you didn't use the issue template, can you update the issue body with that information?  The template information and format is super helpful for us when triaging issues.  In this case for example, it would be helpful to know if you went through the `Prerequisites` section - do you see the same behavior in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?  Have you tried any of the other [debugging suggestions](https://flight-manual.atom.io/hacking-atom/sections/debugging/)?  

Also, what version of macOS are you running?  You mention downloading a fresh copy of Atom but there is stable and beta, did you download 1.34.0 stable?

Lastly, you mention that starting Atom doesn't bring up any windows but does trying to open a new window after Atom is started do nothing?

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
