### ISSUE TITLE
Allow enable package in Safe mode

### ISSUE THREAD

**Issue by tbenst** [atom/atom#18907]
## Summary
Allow for enabling packages in Safe mode to aid in debugging. Keep to current behavior of booting with all packages disabled

## Motivation

I encountered a bug in a package that might be a conflict with another installed package. I'd like to test on atom with only this package enabled. Right now that would require clicking disable on every single other package I have installed, which is not a reasonable workflow.

## Describe alternatives you've considered

I looked at other packages to do this like https://atom.io/packages/enable-packages and https://atom.io/packages/package-switch, but these would require even more work than clicking every single other package.

**Comment by Arcanemagus** [comment]
Atom already supports specifying a custom profile via the [`ATOM_HOME` environment variable](https://flight-manual.atom.io/using-atom/sections/basic-customization/#custom-home-location-with-an-environment-variable). When testing similar situations before I have simply pointed that at a location where I want a test profile created, then installed the package to test there.

**Comment by lee-dohm** [comment]
Thanks for the suggestion.

The purpose of [Atom's Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) isn't just to disable all packages. It is to load Atom in a completely default configuration so that we can determine whether an issue is occurring because of Atom itself or something else. Adding this feature would make it so that Safe Mode could not be relied upon to provide the functionality it was designed for.

Besides what @Arcanemagus suggests, you could write a script that interrogates the `~/.atom/packages` directory and calls `apm disable` on each package in there, then you could `apm enable` just the one you want to use. There's probably a couple other ways to implement a script or a package that does the same thing.

Because of the above, we're not going to implement this suggested change. Nor would we accept a pull request to do so.

Thanks for your passion and interest in Atom.
