### ISSUE TITLE
How to solve format file ?

### ISSUE THREAD

**Issue by appasaheb4** [atom/atom#18918]
<img width="1388" alt="screenshot 2019-02-27 at 2 31 50 pm" src="https://user-images.githubusercontent.com/24726539/53478846-c58adf80-3a9d-11e9-9a55-605f0b3973af.png">
only save file to auto generate this format.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Additionally, if you have a question about Atom there are a lot of resources you can use, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
