### ISSUE TITLE
Deactivate "Atom" name translation in Spanish

### ISSUE THREAD

**Issue by danielramos001** [atom/atom#18920]
It is translated to "Atomo", it does not sound good and "Atom" is more used to refer to the editor in the Spanish community.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
