### ISSUE TITLE
Segmentation Fault, deleting directory with missing permissions Linux

### ISSUE THREAD

**Issue by frederik-b** [atom/atom#18933]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

1. [First Step]
 try to delete empty folder which is owned by root

**Expected behavior:** 
  appropriate error message

**Actual behavior:** 
nonsense error message about gvfs not being installed
and tty output with a reasonable error message:
Enter a value: /usr/bin/atom: line 157:  9698 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
gio: file:///home/name/path: Unable to trash file /home/name/path: Permission denied

**Reproduces how often:** 
stupid error messages happen everytime, I'm rather unsure if the Segmentation fault is new, I usually don't see it

### Versions

```
$ atom --version
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.15
git 2.20.1
```

### Additional Information

I don't exactly remember how, but the fedora installation was broken with no gfvs being installed and I set usage of gio somewhere.
I might've disabled the new tree-sitter because it doesn't correctly work with the TODO plugin (provided in core installation)

I searched for a Segmentation fault with the exact ` /usr/bin/atom: line 157:  9698 Segmentation fault` but couldn't find any, so I wanted to report this.

**Comment by rsese** [comment]
Thanks for the report -

> error message about gvfs not being installed

Issues with gvfs are being tracked in https://github.com/atom/atom/issues/17452 so we'll close in favor of that issue.

Not sure if the crash is related but you mention you're on 1.32.1 and 1.36.0 was just released today so we'd also recommend updating.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by smac89** [comment]
In your `init.coffee`, can you try adding:

```coffee
process.env.ELECTRON_TRASH='gio'
```
