### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 9, Calling function FileSystemService/exist...

### ISSUE THREAD

**Issue by ethanchu** [atom/atom#18947]
[Enter steps to reproduce:]

1. log in devserver from nuclide
2. try to access smartlog

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 9, Calling function FileSystemService/exists. Nuclide was trying to call to the remote Nuclide server. This usually means the server was not reachable, or the network connection is unreliable.

```
At /opt/facebook/nuclide/0.364.129692217/nuclide/node_modules/rxjs-compat/bundles/rxjs-compat.umd.min.js:42

RpcTimeoutError: Timeout after 60000 for id: 9, Calling function FileSystemService/exists. Nuclide was trying to call to the remote Nuclide server. This usually means the server was not reachable, or the network connection is unreliable.
    at Call._timeout (/opt/facebook/nuclide/0.425.141437258/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:248:20)
    at Call._timerId.setTimeout (/opt/facebook/nuclide/0.425.141437258/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:204:14)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
file-icons 2.1.24 
intentions 1.1.5 
language-babel 2.85.0 
language-capirca 0.2.0 
language-graphql 0.10.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
lint 0.0.1 
linter 2.2.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
nuclide 0.434.143924434 
nuclide-format-js 0.0.47 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
vim-mode-plus 1.34.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://github.com/facebookarchive/nuclide package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

For reference, also see: https://blog.atom.io/2018/12/12/facebook-retires-nuclide-extension.html
