### ISSUE TITLE
Crash after install compile-watch

### ISSUE THREAD

**Issue by avatec** [atom/atom#18949]
After install https://atom.io/packages/compile-watch atom has freeze. After force close it and reopen I see message:

The editor crashed
Please report this issue to https://github.com/atom/atom

I was trying to keep it open (this dialog shows again), reload (same), close window (nothing happens)

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Try uninstalling compile-watch from the command line with `apm uninstall compile-watch`.  If Atom starts ok after that, then it seems like an issue with https://atom.io/packages/compile-watch, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

If uninstalling compile-watch doesn't help and you still have trouble after that, feel free to post on the official message board and ping me in it: https://discuss.atom.io/.
