### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by YousifAbozid** [atom/atom#18959]
Hi everyone ..
Recently I encountered a problem running the Python code file, I have written some code in Python and saved my code to a file in my desktop like this:
C:\Users\Yousif\Desktop\test.py

![capture](https://user-images.githubusercontent.com/43423040/54033902-6e0a0500-416a-11e9-922b-a330cac1b4ab.PNG)
![captufghfghre](https://user-images.githubusercontent.com/43423040/54034097-e375d580-416a-11e9-9f65-441f3a082113.PNG)

My code now works good, I created a copy of this file and placed it inside a folder and the path to my file inside the folder was as follows:
D:\مجرد ملف عادي\test.py

![captur e](https://user-images.githubusercontent.com/43423040/54033903-6e0a0500-416a-11e9-8e06-ef9c197adbf6.PNG)
![capffffffffffffffffffffture](https://user-images.githubusercontent.com/43423040/54034151-00120d80-416b-11e9-92be-c4fc89491262.PNG)

Now, my code does not work for the file in this path and I do not know enough reason for this,
This did not happen to me before when I used Atom, I think this is probably a bug in this version, I'm using version 1.34.0 x64 

![capt ure](https://user-images.githubusercontent.com/43423040/54033904-6ea29b80-416a-11e9-8042-9f689f76245f.PNG)
 
This is the latest one on windows 8 , Actually I think the problem lies in the name of the folder that contains my Arabic language but the code was already working Before I updated to this version so I do not see what the solution to this problem. Can you help me ,please ? .. ♥

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [script](https://github.com/rgbkrk/atom-script
) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by YousifAbozid** [comment]
I am using this package :
![Capture](https://user-images.githubusercontent.com/43423040/54068146-1f0daf80-41fe-11e9-97c8-466a97ab1a5f.PNG)
[Script](https://atom.io/packages/script)
I will try to find out what is going wrong here .. Thanks ..♥
