### ISSUE TITLE
Mac OS diagonal scrolling

### ISSUE THREAD

**Issue by cnrkirkby** [atom/atom#18952]
## Summary

Mac OS supports diagonal scrolling on many applications when using the trackpad. Examples can be seen on Firefox or GitKraken (GitKraken is notable as it's built on Electron similarly to Atom).

## Motivation

To improve the overall user experience.

## Describe alternatives you've considered

There aren't really any alternatives as scrolling is fundamental to Atom and shouldn't really be in a package or anything else.

**Comment by lee-dohm** [comment]
Thanks for the feedback.

We [intentionally disabled diagonal scrolling](
https://github.com/atom/atom/issues/1666#issuecomment-46993020) because people found it disconcerting and hard to control. We don't have any plans to reverse that decision since it's been nearly five years and we've had very, very few mentions of a desire for it.
