### ISSUE TITLE
Opens new (duplicate) windows for already-open projects

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#18967]
### Description

If you launch Atom from the command line multiple times in the same directory, it should re-use the same Atom window each time.

### Steps to Reproduce

1. Open a directory with Atom (e.g., `atom /path/to/directory`)
2. Open the same directory with Atom a second time (e.g., `atom /path/to/directory`)

**Expected behavior:** One Atom window should be open showing files for the directory

**Actual behavior:** Two Atom windows are open showing files for the directory

**Reproduces how often:** 100%

### Versions

macOS 10.14.3

```
$ atom-nightly --version
Atom    : 1.37.0-nightly15
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ apm-nightly --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.37.0-nightly15
python 2.7.15
git 2.21.0
```

### Additional Information

This also causes Atom to open a new window when you're using Atom as your Git commit editor. As a result, we lose the [performance benefits introduced in Atom 1.25](https://blog.atom.io/2018/03/15/atom-1-25.html#performance-and-responsiveness) for people wanting to use Atom as their Git commit editor.

**Comment by jasonrudolph** [comment]
Note: The latest Atom beta (`1.35.0-beta0`) does _not_ exhibit this bug, so it must be a fairly recent regression. 🤔

**Comment by jasonrudolph** [comment]
> The latest Atom beta (`1.35.0-beta0`) does _not_ exhibit this bug, so it must be a fairly recent regression.

I built the [current tip of the `1.36-releases` branch](https://github.com/atom/atom/tree/4e77f0c5cb27141b72c6162ae015aabff7938f41), and it _does_ exhibit this bug. 😬

**Comment by lee-dohm** [comment]
@smashwilson is this related to the opening behavior change that you made?

**Comment by smashwilson** [comment]
Ah. Yes, this is... not "intended behavior", but an expected side-effect of the changes to start-up behavior that I introduced in #18608. There's quite a bit of discussion there about this; see the "New launch behavior" heading and the back-and-forth with @rsese and @lee-dohm.

My primary goal was to improve the _predictability_ of our handling of command-line behavior - I was attempting to address the user feedback of "I don't know what's going to happen when I run `atom <path>` - sometimes a new window opens, sometimes an existing window is focused, and I don't know which before I run it." I had #10517 open while I was digging in, and I tried to address each of those scenarios with a consistent command-line invocation.

With that said, we definitely lost a valuable launch scenario with that change: **open Atom with (set of paths), in an existing window if one already exists, or a new window if one does not**. You can get part of the way there by explicitly using `--add` when you intend paths to be opened in an existing Atom window, but `--add` will fall back to adding the paths to the last-opened window if none "own" all of the paths you pass. (@Arcanemagus brought this up as well, so it isn't just you.)

I can see a few paths forward:

1. Revert the default launch behavior changes introduced by #18608 (but keep the single-file-without-project-root bits). This stops us from breaking anyone's existing workflow or scripts, but also loses any progress this gave us on #10517.
2. Add a new command-line flag to restore the lost `--add-if-exists` behavior, but only if you actually know to ask for it. This gives "expert users" a way to get the old launch behavior back, but suffers from a discoverability problem for non-expert users.
3. Open an existing Atom window only if there's an _exact_ match on the project root paths you pass. That might be just enough magic to solve some common scenarios where automatic window re-use is desired without being as jarring to users who aren't used to it. I feel like this path is full of rough edges and odd corners, though.

Also: I'm happy to help with or tackle this one, since I was the one who broke it 😅 .

> This also causes Atom to open a new window when you're using Atom as your Git commit editor.

Try appending `--add` to your editor command. If any Atom windows are open, the commit message editor will use one of them. (This feels like what you'd want for a git editor usage in any case. We should update any documentation about this accordingly.)

**Comment by OverByThere** [comment]
I'm also seeing this in Panic's Transmit when I open files, but not sure how I can add `--add` into the command:
<img width="692" alt="Screenshot 2019-03-13 at 16 42 54" src="https://user-images.githubusercontent.com/6248551/54297603-1d9e0780-45af-11e9-8f3c-92dcd5be9ce4.png">

**Comment by UziTech** [comment]
It seems to me that the "expected" behavior, when launching atom with a file path that already exists, would be to open the file in that window (old behavior).

A fourth option could be to prompt the user in an ambiguous situation. When an Atom window is already open but no flag is given to tell atom what to do. This would be intuitive for "non-expert users" and could give them the flags they need to become "expert users"

**Comment by smashwilson** [comment]
Okay, I've opened #19028 to implement option (1).
