### ISSUE TITLE
TreeSitterLanguageMode.tokenizedLineForRow appears to have a bug

### ISSUE THREAD

**Issue by pbhogan** [atom/atom#18973]
### Description

Just for context, I came across this while digging in to figure out an issue in the `atom-aligner` package (https://github.com/adrianlee44/atom-aligner/issues/78) but that is not directly relevant to the issue.

The issue happens when Tree Sitter is enabled.

`TreeSitterLanguageMode.tokenizedLineForRow` explicitly passes in `null` for the `tokenIterator` parameter of the `TokenizedLine` constructor here:
https://github.com/atom/atom/blob/97f7ab3438498b7eb3c3d22396decd81ff7de6a6/src/tree-sitter-language-mode.js#L442-L452

This causes an error if the `getTokenIterator` function of `TokenizedLine` is called:
https://github.com/atom/atom/blob/c1d270dd2a4ebb42100d25cf65537110b5a4d985/src/tokenized-line.coffee#L15

Which, of course, happens by just using `TokenizedLine` at all.

So either `TreeSitterLanguageMode` needs a more complete backwards compatibility shim, or `TokenizedLine` needs to handle the null token iterator and create something to fill the void, but it's clearly broken as is.

### Versions

Atom    : 1.35.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by maxbrunsfeld** [comment]
The `tokenizedLineForRow` method and `TokenizedLine` class are both private implementation details. Unfortunately, a fair number of packages use them. Some of these packages don't actually use the `tokenIterator` or `tokens` properties; they just access the `text` or `grammar` fields, so we added this shim to `TreeSitterLanguageMode` so that at least *some* of these packages would continue to work without errors when using Tree-Sitter.

The `atom-aligner` package uses the `tokens` getter, so if we want to prevent that package from breaking, we need to create a shim for that getter.

This is probably doable, but we may also want to decide on a better public API for this.

**Comment by adrianlee44** [comment]
Thanks for opening this ticket. I'm the maintainer for aligner and would love to fix this bug.

If I don't use `TokenizedLine` to traverse through characters, are there other suggested ways I can use the grammar tree to find these characters? I'm also open to working with the Atom team to decide on public API for retrieving these tokens.
