### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by ylh980324** [atom/atom#18972]
Argument to `path.dirname` must be a string
```
Object.dirname (D:\Atom x64\resources\app.asar\src\electron-shims.js:9:10)
<unknown> (C:\Users\yy\.atom\packages\atom-beautify\src\beautify.coffee:364:115)
tryCatcher (C:\Users\yy\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
Promise._settlePromiseFromHandler (C:\Users\yy\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
Promise._settlePromise (C:\Users\yy\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
Promise._settlePromiseCtx (C:\Users\yy\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:606:10)
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by https://github.com/Glavin001/atom-beautify, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
