### ISSUE TITLE
Packaging Atom in Debian repositories

### ISSUE THREAD

**Issue by ghtmtt** [atom/atom#18989]
## Summary

Why not providing Atom in Debian package manager?

## Motivation

Updating Atom every time by downloading the deb etc is a little bit uncomfortable. 

I saw this closed and old issue: https://github.com/atom/atom/issues/2293. I just'd like to know if there are some work in progress for this.

Thanks

**Comment by Arcanemagus** [comment]
Instructions for adding the official package repository for automatic updates on Debian, Ubuntu, Red Hat, CentOS, Fedora, and SUSE can be found in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux) 😉.

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
