### ISSUE TITLE
Auto "safe mode" if atom stalls on start-up

### ISSUE THREAD

**Issue by aubergine10** [atom/atom#19012]
## Summary

If atom hangs on startup, this line of code gets called:

https://github.com/atom/atom/blob/2e9e57fa1329a0e8873d7aae005d6d90d67d21dd/src/main-process/atom-window.js#L183

If user chooses to force quit the app, it should start in safe mode on next launch to make it easier for them to resolve the issue.

## Motivation

Reduce user frustration by making it easier to get the app up and running again (rather than force them to spend an hour googling).

## Describe alternatives you've considered

Upon googling to find out how to resolve the issue with app hanging on launch, it became apparent that the most common solution is to start it in safe mode and disable community packages.

It would be nice to remove the "google for an hour" part of that process.

## Additional context

![0979a01e54079be00022589ecf7159d88043d53b](https://user-images.githubusercontent.com/1386719/54639069-67419300-4a84-11e9-8a3c-7dce35221663.png)

Have a "Force quit + use safe mode" option on that dialog?

**Comment by lee-dohm** [comment]
Thanks for the feedback.

This isn't something that I think we should do because Safe Mode is only one possibility out of a number of debugging tactics and Safe Mode is not guaranteed to work. I do, however, agree that we could direct people to the debugging documentation in that dialog. This would also potentially ameliorate the "google for an hour" part of the process.

**Comment by aubergine10** [comment]
Yes, link to troubleshooting guide would be very useful.

However, for many users, they already have rough idea of the problem (based on the googling I did) - for me I was pretty sure it was a linter installed during previous editing session. Having safe mode would have let me get atom back up and running quickly so I could disable the linter in the UI and get back to work until more time was available to address the linter issue.

If the 'start in safe mode' option isn't accepted, then please ensure the debug guide mentions the `--safemode` option its opening content, as it's very useful to know about for users who haven't run in to this problem before.

On a related note, is there somehow the main process could do something like `timecop` to try and identify stalled packages on startup?

**Comment by Aerijo** [comment]
I don’t think safe mode is what you want if you’re trying to disable a community package. They will all appear with an “install” button, not disable.

Instead you will want to run `apm disable packageName` in the command line

**Comment by aubergine10** [comment]
Maybe, but that stuff is not known to a new user who isn't familiar with the command line options.

Using `--safe`, rightly or wrongly, got atom up and running again. I closed some 30+ open documents, then relaunched in normal mode and it worked fine. I suspect some sort of filelock issue on a recently installed linter.

I just checked again and you are correct that in safe mode the subscribed community packages are listed but show 'install' button, rather than 'uninstall', which is confusing.

**Comment by Aerijo** [comment]
> community packages are listed but show 'install' button, rather than 'uninstall', which is confusing.

@aubergine10 Yeah, that's a bug IMO. I think it should offer an enable/disable button, or none at all. There's probably an open issue somewhere for that( maybe in the settings view repo itself).

**Comment by lee-dohm** [comment]
With regard to the behavior where the "install" button shows up in Safe Mode, the [issue tracking it](https://github.com/atom/settings-view/issues/925) can be found in the settings-view repo.

As far as the suggested change, as I said above, we would rather that people go through the debugging steps in the Atom Flight Manual than be forced into something that they don't understand and may not actually help. Because of this, we're not going to make this change. We would, however, be open to a well-written pull request that added the option to open the Debugging section of the Atom Flight Manual on the next open.

Thanks for the suggestion.
