### ISSUE TITLE
this can not be disabled

### ISSUE THREAD

**Issue by nikoladim123** [atom/atom#19032]
how to hell do i disable git diff? i disabled it in atom and its still runing! 
i runed atom --safe and still runing!!
cant trun it off anyhow! wtf did you do with atom??

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

**Comment by lee-dohm** [comment]
Additionally, I just tested this using Atom Nightly v1.37.0-nightly22 on macOS 10.14.3. I disabled the git-diff package and the colorization in the gutter on an open file with changes immediately disappeared. When I re-enabled the package, the colorization immediately reappeared. So the issue, as described, is not reproducible.

Finally, Safe Mode doesn't disable built-in packages. See the [Atom Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) for more details on what it actually does do.
