### ISSUE TITLE
The editor has crashed 

### ISSUE THREAD

**Issue by jimenezadrian** [atom/atom#19050]
### Atom Crashed

Good day
I've been working with Python on Atom and had no problems, but for the last few days every time I type "try:" the crashed editor and only the "Close Window", "Reload" and "Keep Go Open" options appear.
I'm using version 1.35.1

**Comment by rsese** [comment]
Thanks for reaching out!

Can you fill in the issue template details?  The issue template information is super helpful for us when triaging issues.  For example, it would be helpful to know if you tried the suggested debugging steps like safe mode and what operating you're running.

Once you add those details we can go from there.

----

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
