### ISSUE TITLE
Unable to save file: Operation not supported on socket '/run/user/1000/gvfs/ 

### ISSUE THREAD

**Issue by isalirezag** [atom/atom#19092]
I am opening a file in my server using sftp and that error happens when i want to make changes and save the file

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

It would also be helpful to know if this is specifically an issue when using a community package or not?

Thanks for understanding and meeting us half way :grinning:
