### ISSUE TITLE
Can't see any text in text boxes on MacOs Mojave

### ISSUE THREAD

**Issue by sulemankm** [atom/atom#19093]
Just installed atom 1.35.x on MacOs mojave.  But I can't see any text that I enter in the text boxes (such as in the package settings or package installer screens.  The text in the editor looks ok.

Also tried to change the UI theme, both dark and light ones, but to no avail.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Also, 2 suggestions you can try:

* Check if updating `Settings > Color Profile to Use sRGB color profile` to `Use sRGB color profile` makes any difference.
* Check if disabling your GPU with Atom makes any difference: https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem
