### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by LouisVann** [atom/atom#19099]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (E:\Atom\Atom x64\resources\app.asar\src\text-editor-element.js:13:10)
MarkdownScrlSync.getVisTopHgtBot (C:\Users\lyf21\.atom\packages\markdown-scroll-sync\lib\utils.coffee:20:34)
MarkdownScrlSync.setMap (C:\Users\lyf21\.atom\packages\markdown-scroll-sync\lib\map.coffee:25:14)
MarkdownScrlSync.startTracking (C:\Users\lyf21\.atom\packages\markdown-scroll-sync\lib\main.coffee:75:12)
<unknown> (C:\Users\lyf21\.atom\packages\markdown-scroll-sync\lib\main.coffee:58:23)
Function.simpleDispatch (<embedded>:11:1172354)
```

**Comment by lee-dohm** [comment]
Thanks for contributing!

It appears that this is being caused by the [markdown-scroll-sync package](https://atom.io/packages/markdown-scroll-sync), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
