### ISSUE TITLE
Disable Close Empty Windows by default

### ISSUE THREAD

**Issue by jedwards1211** [atom/atom#19100]
I'm griping because Ctrl-W quitting Atom annoyed me dozens of times times before I was motivated to go to the trouble to look up if there was a way to turn it off.  Is there any concrete justification for enabling it by default?

**Comment by rsese** [comment]
I wasn't around back then so don't have any context and search isn't working for me right now so can't poke around old issues.

In any case though, I do know that at this point we're not likely to change current defaults unless there's a very strong reason to make the change.  But I can at least mention it to the other maintainers for you since I can see how Atom closing like that can be disruptive.

Since this is more of a question/feedback issue we're going to close it since we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog) and we close issues that [ don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).
