### ISSUE TITLE
I wish the text were not microscopic.

### ISSUE THREAD

**Issue by Evotron** [atom/atom#19107]
It would be amazing to be able to read the text so that I can use Atom as an text editor. Currently it is too tiny. Not even a magnifying glass can help me read it. Even at the default font size of 14px, the text is microscopic.

![atom super small text](https://user-images.githubusercontent.com/46901105/55599388-251f7f00-571d-11e9-9d0c-99ff6678ba8a.jpg)

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Looks like the font got zoomed in?  I'd suggest trying `Window: Reset Font Size` from the command palette (or <kbd>cmd-0</kbd> on macOS, <kbd>ctrl-0</kbd> on Windows).
