### ISSUE TITLE
Web browser

### ISSUE THREAD

**Issue by wooden-utensil** [atom/atom#19112]
So Atom is secretly a web browser, the interface of Atom is inside `index.html`, except for the menu-bar. If you press <kbd>Ctrl</kbd>+<kbd>&#x21e7; Shift</kbd>+<kbd>I</kbd> you can open the web console. If you switch to the console tab, and type `open("https://www.example.com/")`: Atom will open another window that redirects to https://www.example.com/! <kbd>![Example](https://i.imgur.com/K5jZY11.png)</kbd>

**Comment by 50Wliu** [comment]
Yes, it's built on [Electron](https://electronjs.org).

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by lee-dohm** [comment]
@wooden-utensil It's not really a secret. The team specifically [said that Atom was built using web technologies back in February 2014](https://blog.atom.io/2014/02/26/the-nucleus-of-atom.html) when Atom was first announced publicly.

**Comment by wooden-utensil** [comment]
@lee-dohm 

> @wooden-utensil It's not really a secret. The team specifically [said that Atom was built using web technologies back in February 2014](https://blog.atom.io/2014/02/26/the-nucleus-of-atom.html) when Atom was first announced publicly.

Never knew that, and I was just joking saying it was. Just thought it would be funny? :laughing: :rofl:

**Comment by wooden-utensil** [comment]
<sup>This also happens in [Visual Studio Code](https://code.visualstudio.com/)</sup>

**Comment by lee-dohm** [comment]
Again, not a revelation, since Visual Studio Code is also [built on Electron](https://github.com/atom/atom/issues/19112#issuecomment-480549608).
