### ISSUE TITLE
How can I change tree-view default width?

### ISSUE THREAD

**Issue by bl00mber** [atom/atom#19127]
## How can I change default width of the tree-view?

I've tried to modify contents of the package tree-view and styles.less to modify the default width of tree-view `atom-dock-mask` container, but it doesn't appear to have any effect and I can't find the place in the code of module that defines this value. For example, package `tree-view` not even contains `300` (default value of the width) whatsoever.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

I poked at this a tiny bit and I'm not positive but I think the default width of 300 comes from the default width of a dock?  

https://github.com/atom/atom/blob/2f827bfc23260eece024b8f179421fa833b1834d/src/dock.js#L10

In any case, as mentioned above the best place to ask questions like this is the Atom Slack or the Message Board.
