### ISSUE TITLE
Can Not Install ANY Packages!

### ISSUE THREAD

**Issue by Ahmed-muhammed50** [atom/atom#19121]
### Description

I am trying Install Eslint Package in atom on windows. Installing Starts but there is no progress and it still stuck. 

I am NOT using any proxies and internet connection is well.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

And just to clarify, what other packages besides ESLint have you tried to install?  Are you seeing any errors?

And were you trying to install to install https://atom.io/packages/linter-eslint or https://atom.io/packages/eslint?
