### ISSUE TITLE
TextEditor.onDidChangeScrollTop is deprecated.

### ISSUE THREAD

**Issue by maxtcarry** [atom/atom#19122]
This is now a view method. Call TextEditorElement::onDidChangeScrollTop instead.
```
TextEditor.onDidChangeScrollTop (<embedded>:11:9378)
registerEvents (C:\Users\Administrator\.atom\packages\jshint\index.js:324:32)
Function.simpleDispatch (<embedded>:11:1172354)
Emitter.emit (<embedded>:11:1173795)
Workspace.didActivatePaneContainer (<embedded>:11:424001)
WorkspaceCenter.paneContainer.onDidActivatePane (<embedded>:14:38543)
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://atom.io/packages/atom-jshint package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
