### ISSUE TITLE
RAML API workbench package not highlighting errors/warnings with red/yellow dots

### ISSUE THREAD

**Issue by ttomato1** [atom/atom#19139]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[The API Workbench package stops identifying RAML syntax errors when Linter is upgraded to 2.3.0]

### Steps to Reproduce

1. [I have Atom 1.35.1 installed with the API Workbench package 0.8.48 - everything worked]
2. [In installed packages in Settings, both busy-signal and linter packages had upgrades ]
3. [I upgraded busy-signal to 2.0.1]
4. [I upgraded litner to 2.30]
5. [Now looking at a .raml file in the editor, it recognizes it as RAML and provides tooltips,.]

**Expected behavior:** [ It red dot/yellow dots RAML lines containing syntax errors or warnings.]

**Actual behavior:** [It no longer red dot/yellow dots RAML lines containing syntax errors or warnings.]

**Reproduces how often:** [Consistently doesn't work.]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
[as per above]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://atom.io/packages/api-workbench package or perhaps the linter packages you're using, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
