### ISSUE TITLE
Atom / Hydrogen error "unexpected EOF while parsing" for python `if` statement!? 

### ISSUE THREAD

**Issue by bridgesra** [atom/atom#19132]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
Note--hydrogen doesn't seem to work in safe mode, so couldn't fully check, but the `if` statements won't fold indicating it's still a problem. 

    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

1. type any `if` statement in a saved Python script 
2. put cursor on the `if` line 
3. execute w/ Hydrogen (Shift + Enter) 

**Expected behavior:**
Should run the whole `if` statement

**Actual behavior:** [What actually happens]
If there is no `else` in the `if` statement it produces "Unexpected EOF while parsing " error . 
If there is an `else` in the `if` statement if runs the first `if` portion of the statement but not the `elif` or `else` part(s). 

**Reproduces how often:** 
100%

### Versions

Editor name and version: 
Atom 1.35.1
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python 2.7.15
git 2.14.3

Platform: Mac OS Sierra 10.12.6

Color scheme: One Dark/Solarized Dark

### Additional Information

Seems to be a problem w/ how Atom / Hydrogen interprets the code. `for` loops it will give me the option to "fold" or "collapse" by clicking the carrot in the line number. Yet, `if` blocks/statements have no such luck.

[![picture of errors on if: ][1]][1]

    ## this works: 
    for i in range(10): 
    	print( i)
    
    ## this doesn't: 
    if not False: 
    	print("test worked")
  
    ## this example doesn't throw an error, but only executes the "if" and not the else parts: 
    x= False
    if x == True:
    	print("test")
    elif x == None:
    	print ('test anyway')
    else:
    	print('test again')

  [1]: https://i.stack.imgur.com/c7JP4.png

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [hydrogen](https://atom.io/packages/hydrogen) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
