### ISSUE TITLE
MacOSX Command+q hold for close support

### ISSUE THREAD

**Issue by stevus** [atom/atom#19134]
Chrome does this and it's a super helpful feature to prevent accidental closes. Since Q is so close to the number fields, I frequently doing this when quickly changing file tabs.

Instead of just hitting command+q to close, would be nice to require it to be held down for a period of time.

**Comment by rsese** [comment]
Thanks for the suggestion!  For future issues, please fill out the issue template - the information and format of the templates are super helpful for us when triaging issues.

And as mentioned in the template, the team is currently very unlikely to prioritize feature requests right now - but with Atom's customizability and with community packages, you can often get the functionality you need without requesting changes to Atom itself.  In this particular case I know there's at least a couple of packages that provide the behavior you're looking for - I use this package and it's worked well for me:

https://atom.io/packages/warn-before-quitting

But you can search for other packages as well if you'd like:

https://atom.io/packages

Since this functionality is already provided by a package, we'll go ahead and close this issue.
