### ISSUE TITLE
CI on pull request fails to detect package-lock.json version error

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#19148]
### Description
When working on https://github.com/atom/atom/pull/19130, I ran into a situation where all CI checks passed on the pull request, leading me to believe that everything was fine with changes. However, when I merged the pull request, one of the CI checks failed.

On the pull request, CI ran two checks:

- ✅ [**Azure DevOps** - *Atom Pull Requests* Pipeline](https://github.visualstudio.com/Atom/_build/results?buildId=37525)
- ✅ [**AppVeyor **- *continuous-integration/appveyor/pr * context](https://ci.appveyor.com/project/Atom/atom/builds/23745368)

After merging the pull request, CI ran three checks:

- ✅ **Azure DevOps** - *Atom Production Branches* Pipeline
- ✅ **AppVeyor** - *continuous-integration/appveyor/branch* context
- ❌ [**Travis CI** - *continuous-integration/travis-ci/push* context](https://travis-ci.org/atom/atom/builds/518371554#L737)

The Travis CI check identified a legitimate issue, but CI should have alerted us to that issue before the pull request was merged:

> `npm ERR! Invalid: lock file's fuzzy-finder@https://www.atom.io/api/packages/fuzzy-finder/versions/1.12.1/tarball does not satisfy fuzzy-finder@https://www.atom.io/api/packages/fuzzy-finder/versions/1.13.0/tarball`

### Screenshots

<img width="772" alt="Screen Shot 2019-04-12 at 11 50 56 AM" src="https://user-images.githubusercontent.com/2988/56050407-d45de680-5d19-11e9-9e8d-a6a78e0b3838.png">

CI checks on pull request:

<img width="776" alt="Screen Shot 2019-04-12 at 11 51 11 AM" src="https://user-images.githubusercontent.com/2988/56050412-dcb62180-5d19-11e9-8274-8d597c2435ce.png">

CI checks after merging:

<img width="784" alt="Screen Shot 2019-04-12 at 11 51 53 AM" src="https://user-images.githubusercontent.com/2988/56050413-dcb62180-5d19-11e9-9df7-ecaa1b7eb3f5.png">

### Expected vs. actual behavior

**Expected behavior:** CI fails when a `package-lock.json` problem is present on the pull request.

**Actual behavior:** CI passes when a `package-lock.json` problem is present on the pull request.

**Comment by smashwilson** [comment]
My guess is that we're inconsistent about when we run `apm ci` instead of `apm install`. The use of `apm ci` is triggered within our build scripts by an explicit `--ci` argument being given to `script/build`, or the `CI` environment variable holding the value `"true"`:

https://github.com/atom/atom/blob/4a29f442bb88dd1aba5166d7223e86c23b01b32a/script/bootstrap#L21-L27

I bet Travis is setting `CI` as we expected but Azure DevOps and AppVeyor are not. Ideally we should always enable "ci" builds in CI, because (a) it will catch issues like this, (b) it's slightly faster most of the time, and (c) it produces more consistent builds (i.e. the CI build won't accidentally run with a newer version of a dependency that matches the `package.json` range, but not the locked version).
