### ISSUE TITLE
newWindow false for windows context ment

### ISSUE THREAD

**Issue by 7evenmikser** [atom/atom#19155]
Hello!

Is there any way to set opening new window false by default when opening files via windows context menu (open with atom)?

Searched through the google, github and stackoverflow and still didn't find any solution. Only this unanswered issue #9399

Thanks!

**Comment by rsese** [comment]
Thanks for reaching out!

Since the template wasn't used I don't know what version of Atom you're running but I'm going to guess you updated to 1.36.0?  If so, I think you're running into this issue: https://github.com/atom/atom/issues/19147 and you can subscribe there for updates if you'd like.  If you're working on files in the same directory,  a workaround for now is mentioned in https://github.com/atom/atom/issues/19147#issuecomment-482634342 (you can open the containing directory and any files you open from your file manager from that directory will open in the same window).  There's otherwise no setting at the moment that you can enable so that files always open in the same window.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

Additionally, please use the issue template when creating issues, the information in the template is helpful for us when triaging issues.
