### ISSUE TITLE
linux.cson makes it difficult to set custom console alternate routes

### ISSUE THREAD

**Issue by stavesecty** [atom/atom#19179]
Hey I am new to this atom, but i am having problem to set a custom console to other routes
running atom under linux Fedora 28.

any suggest on how to fix this??

Atom : im using the updated version 
![picture1](https://user-images.githubusercontent.com/49761603/56377620-ac332380-6202-11e9-944b-554f84708890.png)

**Comment by HusseinMccoin** [comment]
the way i see this problem is you are trying to duplicate the key, don't try to duplicate the key.
CSON is only an alternate syntax structure for JSON. In JSON, similar to customary JS objects, you can't delineate same key to various diverse qualities. That was the reason there is a blunder about copy keys.

so just put the previous and next into the same 
atom-text-editor:not([mini]);
previous (code)
next (code)

**Comment by stavesecty** [comment]
ah thanks, i see the problem now
