### ISSUE TITLE
Atom doesn't launch on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by ghzut** [atom/atom#19188]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I recently had to reinstall the WSL Ubuntu on my laptop and now updated it directly from 18.04 to 19.04, before installing atom like the first time, following this:

[https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux](url)

but now every time I want to use `atom <filename>` or `atom .` in a directory 
I get an error and the file `nohup.out` ist created in the `.atom` directory.

### Steps to Reproduce

1. Install Atom following [https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux](url)
2. Try to launch atom
`$ atom <filename>`
`$ atom .`
`$ atom --safe`
`$ atom --clear-window-state`

**Expected behavior:**

Atom launches

**Actual behavior:** 

Always get the error 

`/usr/bin/atom: line 186:  3228 Trace/breakpoint trap   (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1 `
` shared memfd open() failed: Function not implemented--`

**Reproduces how often:** 100%

### Versions

`$ atom --version`                                                            
`    Atom    : 1.36.0`                              
`    Electron: 2.0.18`                                                     
`    Chrome  : 61.0.3163.100`                                                             
`    Node    : 8.9.3`

### Additional Information

As an XServer I use VcXsrv Version 1.20.1.4
If I run top at the same time, it shows an atom process until the error appears.
Also there are two atom processes dormant all the time.

On my PC I still use Ubuntu 18.04 and Atom doesn't do anything, like mentioned here:
[https://github.com/atom/atom/issues/17874](url)
but I already have installed the same XServer.

**Comment by Anakael** [comment]
I have the same trouble on my Arch Linux. Atom doesn't launch without any errors.

**Comment by rsese** [comment]
Thanks for the report @ghzut - I checked with the other maintainers and we're not specifically supporting Atom installed through WSL at the moment.  If you have Atom installed on Windows, there's an issue open about starting that Windows-install Atom via WSL here https://github.com/atom/atom/issues/18126, but otherwise, we're not prioritizing investigating issues related to Atom installed in WSL.

Because of this, I'll close this because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), so we close issues that aren't [tasks needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).
