### ISSUE TITLE
how big can the .py file be, because my one is crashing 

### ISSUE THREAD

**Issue by amazingDamian** [atom/atom#19185]
Description
my .py wont open, i think the file is too big. is there a way of opening a huge .py

**Actual behavior:**atom crashes

Reproduces how often: 100%
Versions
Atom : 1.35.1
Electron: 2.0.18
Node : 8.9.3
Running on Mac OSX 10.11.6 (El Capitan)

Additional Information
LOG FILE INFORMATIONS

Process: Atom Helper [4623] Path: /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper Identifier: Atom Helper Version: 1.35.1 (1.35.1) Code Type: X86-64 (Native) Parent Process: Atom [4619] Responsible: Atom [4619] User ID: 501

Date/Time: 2019-03-15 14:47:01.756 +0100 OS Version: Mac OS X 10.11.6 (15G22010) Report Version: 11 Anonymous UUID: 3991DE16-BD30-32E0-AA61-4D5C66CB473D

Time Awake Since Boot: 19000 seconds

System Integrity Protection: enabled

Crashed Thread: 14

Exception Type: EXC_CRASH (SIGABRT) Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information: terminating with uncaught exception of type std::length_error: vector abort() called

**Comment by HusseinMccoin** [comment]
one way you can get around this problem is by disabling your tree sitter parser.
if you go on setting> core> use tree sitter parsers and if you untick the box. then try to open your file again.
![image](https://user-images.githubusercontent.com/35459369/56420727-0e3d6880-6297-11e9-8634-174344f01606.png)


if this keeps happening then share the file with the staff, they can sort it for you.

**Comment by maxbrunsfeld** [comment]
Hey @amazingDamian Sorry for this really poor experience. This crash has been fixed, and the fix will ship in Atom 1.37.
