### ISSUE TITLE
Top menu disappeared

### ISSUE THREAD

**Issue by jonathanhatch** [atom/atom#19197]
Application menu is missing after upgrading to Disco Dingo.

Step 1: Upgrade to Disco
Step 2: Notice missing application menu.

Oddly enough, it reappears if I click on a window outside of the application, but disappears again when I focus on it's window again.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Looks like this is Ubuntu 19.04 - seems like the same issue as https://github.com/atom/atom/issues/18535?  Were you running 18.10 and didn't see this issue or did you update from 18.04?
