### ISSUE TITLE
How to changing the active code page to UTF-8 using chcp and specifying 65001?

### ISSUE THREAD

**Issue by stramzik** [atom/atom#19210]
Hi All,

The File encoding is set tp UTF-8 from the settings.

Even then when ever I try to stream tweets from tweepy API
I get the 

``` return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f447' in position 73: character maps to <undefined
 ```

When I contacted tweepy help they told me its an issue with ATOM and I have to change **active code page to UTF-8 using chcp and specifying 65001** But its already UTF-8 but not sure what CHCP and 65001 mean need help.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

It sounds like you're using a community package to execute code so the Atom Slack and the message board mentioned above would be the best places to ask about that.
