### ISSUE TITLE
some different minds to increase speed

### ISSUE THREAD

**Issue by Fuehrerstand** [atom/atom#19215]
I'll try to give some minds, which are improving the efficency of this great work. Everything i say is constructive like, no bashing. 

## Proof of Concept from Time to Time

As a coder i know, what should be resulted and going step by step backward up to the beginning point. To check out the experience i set my own up as a noob. The result is an installation as plain and the maximum of packages/extensions additional. 

I did it on win32, x86 and x64 on Debian. 

The startup from the plain was slow - maybe a part of the complexity. 

The startup from the maximum needs even longer, no question why for.

## Summary

I'll suggest a improvement, through outsourcing into services on the loopback-device with direct adressable feature. So the requirements of ressources to the Javascript-Inferno could be reduced to a minimum. The parsing is that, what slows down into the unusuability.

Example:

The system-timecode is available ever. We can decode it, to have a ID-set for a infrastructure in directories like "./year/week/month/day/hour/minute/second/". So its nice to use it for a map in the RAM. As RAM-disc or reserved like - whatever. The point of speed comes from the base. If you know, how to adress, the workarounds no longer required. Combined with a passive database is more stability inside.

When this concept is mirrored as system-atomcode, we have a fullrange feature. If the system-atomcode is arranged as ticket-code, and a second map is available to logging for debuggings, the interactivity is phantastic to every developer and user. Every element haves an own ID and we have a linear jump into the alinear of suitabilities from the top. Its an sandbox-instance too, without great words. The service is upgradable with operational functionality. 

I tested this concept in my CMS, which written in Perl. The speedup against the CMS of  PHP/MySQL was important! (>1000x) This are "many" decimals per job i think. 

## Motivation

I would like use the editor for liquid working. This time its lagging massive and this is not really that, what a great tool might sign for.

**Comment by rsese** [comment]
Thanks for the feedback!  Though I admittedly couldn't follow all the details you shared, my understanding is that you're describing how you experience slow startup time and you have suggestions about improving performance. 

About startup time in general, it's definitely something the team looks at for opportunities for improvement.  You can see specific issues which are tracked with the `startup-time` label:

https://github.com/atom/atom/issues?q=is%3Aopen+is%3Aissue+label%3Astartup-time 

https://github.com/atom/atom/issues/13253 in particular is a good issue that dives into some details around Atom's startup time.

And about your suggestions, I'll go ahead and share them with the other maintainers and if there are specific questions for you, we'll reach out.

Since your feedback will be shared with the maintainers, we'll close this issue because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog) and to help keep our backlog clean and focused.

Thanks again for your suggestions!
