### ISSUE TITLE
Format died in agony

### ISSUE THREAD

**Issue by bshekhaw** [atom/atom#19229]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Format died in agony

```
At 💡 More details in Developer Tools console

undefined
```

### Commands

```
     -0:34.2.0 core:backspace (input.hidden-input)
  2x -0:33.7.0 editor:newline (input.hidden-input)
     -0:31.8.0 core:backspace (input.hidden-input)
     -0:30.2.0 autocomplete-plus:confirm (input.hidden-input)
     -0:29.5.0 editor:newline (input.hidden-input)
     -0:25.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:24.8.0 editor:newline (input.hidden-input)
     -0:23.6.0 autocomplete-plus:confirm (input.hidden-input)
     -0:22.1.0 core:move-down (input.hidden-input)
     -0:21.3.0 core:move-up (input.hidden-input)
  5x -0:20.1.0 core:backspace (input.hidden-input)
     -0:18.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:18.1.0 snippets:expand (input.hidden-input)
     -0:18.1.0 editor:indent (input.hidden-input)
     -0:15 core:select-all (input.hidden-input)
     -0:11.8.0 oracle-format:formatEditor (div.line)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
autocomplete-oracle 1.4.4 
build 0.70.0 
build-oracle 1.6.1 
busy-signal 2.0.1 
language-oracle 1.9.0 
oracle-format 0.4.0 
plsql-linter 2.3.2 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [oracle-format](https://atom.io/packages/oracle-format) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
