### ISSUE TITLE
Where is git reset --hard

### ISSUE THREAD

**Issue by mkungla** [atom/atom#19249]
## Summary

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered. Be sure to explain why Atom's existing customizability isn't suitable for this feature.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

In addition to filling out the template, I did want to mention that `git reset --hard` isn't supported in the GitHub package.  The [Github package](https://github.com/atom/github/) isn't meant to replace all Git functionality so for some things, you would need to drop to the command line for example.

If you want to keep up with changes to the GitHub package, you can keep an eye on the blog: 
 https://blog.atom.io/
