### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 7

### ISSUE THREAD

**Issue by illvart** [atom/atom#19252]
[Enter steps to reproduce:]

1. This problem often.
2. When I scroll and make changes to the javascript files, the atom doesn't run (freeze), I force it to stop using **xkill**.
3. A crash notification appears when I open the atom again.

**Atom**: 1.36.1 x64
**Electron**: 4.1.4
**OS**: linux 5.0.10-arch1-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 7

```
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 7
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:148:17)
    at /usr/lib/electron/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
```

### Non-Core Packages

```
javascript-snippets 1.2.1 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-minify 0.8.0 
atom-monokai 0.10.9 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.2 
autoprefixer 3.7.1 
chrome-color-picker 0.8.0 
color-picker 2.3.0 
css-snippets 1.1.0 
custom-title 1.0.1 
docblockr 0.13.7 
double-tag 1.7.0 
es6-javascript 1.0.0 
file-icons 2.1.32 
gulp-control 0.5.0 
highlight-selected 0.16.0 
ide-css 0.3.2 
javascript-snippets 1.2.1 
language-nunjucks 4.2.1 
lorem 4.0.0 
markdown-preview-plus 3.8.1 
markdown-writer 2.11.5 
material-colors 0.1.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
pigments 0.40.2 
pretty-json 2.1.2 
scroll-through-time 0.3.1 
sort-lines 0.19.0 
tag 0.5.0 
terminal-tab 0.5.7 
todo-show 2.3.2 
tree-view-sort 0.11.3 
zentabs 0.8.9 
```

**Comment by rsese** [comment]
Thanks for the report!

> **Atom**: 1.36.1 x64
> **Electron**: 4.1.4

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
