### ISSUE TITLE
--help and other command line flags shows nothing

### ISSUE THREAD

**Issue by MarcoSulla** [atom/atom#19267]
I installed atom using

    sudo snap install atom --classic

Then I tried to do

    atom --help

No output. The same for `--version`.

I tried also with `--safe` for good luck, but nothing.

Atom 1.36.1, ***L***ubuntu 18.04.2

**Comment by 50Wliu** [comment]
> sudo snap install atom --classic

Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
