### ISSUE TITLE
Atom doesn't support my language(Arabic) I can not rely on it 

### ISSUE THREAD

**Issue by jemy-2020** [atom/atom#19260]
I have tried to edit my article (was written in Arabic ) but I can't move the cursor any where , I can not select any text to delete or edit or even change any thing in it  :( 
### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

**Comment by Fuehrerstand** [comment]
@lee-dohm @jemy-2020 

Notice: The arabic language (not the only one this kind, can ask the jews) haves an inverted direction of context reading. So it maybe, that a reading from left to right, breaks on the parsing, when try to do something.

I tried to replicate the error from description and here are my results by following ways:

1'st i leeched a **mixed content** html-file from a popular arabic newspaper.

The presence of both inside a document like a html-file gives an notice of blue, that says "Could not find any solution".  The **keys are operational**.

**2'nd way** i made a text-file and putted just the arab letters into that.

The **presence of once the arab signs** in a document like a text-file, gives same notice too, but the **cursor hangs on the right side and is not accessable through the direction keys**!!!

**3'rd pass** i enhanced the textfile with idiotic tags. So i have now <text>arabic signs</text> and it happens the blue notice and functionally keys are back.

[https://www.sendspace.com/filegroup/efSpApTdsNPKLVz7sG%2Bu6Q](url)

The demonstration of primary effect i putted into two text-files, so that the audience can listen, replicate and find a solution.
