### ISSUE TITLE
Auto Indent Empty Line Above

### ISSUE THREAD

**Issue by doakey3** [atom/atom#19288]
In Geany, notice that when an indented line is sent to a line below, indentation is added to the newline above so that indented text can quickly be added to that newline:

![geany](https://user-images.githubusercontent.com/16495887/57446907-696dd580-721b-11e9-8d7c-fa8a97066a25.gif)

In Atom, the indentation must be added manually:

![atom](https://user-images.githubusercontent.com/16495887/57446945-7d193c00-721b-11e9-84f7-fa0a219a31a3.gif)

My feature request is for the geany-like behavior to be implemented by default in atom.

**Comment by rsese** [comment]
Thanks for the suggestion! For future issues, please fill out the issue template - the information and format of the templates are super helpful for us when triaging issues.

And as mentioned in the template, the team is currently very unlikely to prioritize feature requests right now - but with Atom's customizability and with community packages, you can often get the functionality you need without requesting changes to Atom itself. In this particular case, I poked around and found this package that looks like it can help:

https://atom.io/packages/atom-cursor-indent

With your example and this package:

![cursor-indent](https://user-images.githubusercontent.com/734194/57475435-f5065700-7259-11e9-9bdc-a8263b35581f.gif)

Since this functionality is already provided by a package, we'll go ahead and close this issue.
