### ISSUE TITLE
Go to Line Number, add two Shortcuts

### ISSUE THREAD

**Issue by ManuelTS** [atom/atom#19290]
## Summary

Enable in the _go to line view_ the usage of the two characters _s_ for _go to start-_ and _e_ for _go to end of the line_.

## Motivation

Faster navigation and shortcut usage in the _go to line view_.

## Describe alternatives you've considered

Press additional _pos 1_ or _end_ keys when using _go to line view_.

**Comment by rsese** [comment]
Thanks for the suggestion @ManuelTS!  While I can see how this shortcut could be useful (especially for going to the end of a line since like you noted, adding `:1` to the line number is basically the same as your suggested `s` flag), as mentioned in the issue template, the team isn't prioritizing feature requests at the moment.  Additionally, besides going to the start of the line, going to the end of the line has a reasonable (though an extra key command) workaround like you mentioned.  So we'll go ahead and close for now but thanks again for your interest!
