### ISSUE TITLE
Opening project with empty window open results in blank git panel

### ISSUE THREAD

**Issue by elzo-d** [atom/atom#19299]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When opening a project with an empty window open (the one which appears when opening atom, on macOS), opening the git panel will result in it being blank. This only happens if the opened project replaces the empty window. If opening a project creates a new window, the git panel works correctly. Reloading the window (`Window:reload`) when the git panel is not functioning also fixes it.

### Steps to Reproduce

1. Open Atom, which opens an empty window (with an empty untitled file).
2. Use File->Open (or File->Open recent) to open a project (replacing the empty window).
3. Open the git panel, and observe how it is blank.
4. Close the window, leaving the (macOS) menubar.
5. Open a project again (now creating a new window, because no windows were open).
6. Open the git panel again, and observe how it is now correctly populated.

**Expected behavior:** The git panel to always correctly populate with its contents.

**Actual behavior:** The git panel being blank when opening a project with an empty window open.

**Reproduces how often:** 100%.

### Versions

atom --version:
```
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
apm --version:
```
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 2.7.10
git 2.20.1
```
Running on macOS Mojave 10.14.4.

### Additional Information

Screenshot of empty git panel:
![Schermafbeelding 2019-05-09 om 22 58 42](https://user-images.githubusercontent.com/32901471/57486591-961efd00-72ae-11e9-9268-1cd994eb3325.png)

**Comment by rsese** [comment]
Thanks for contributing!

Though not the exact same repro steps, this sounds very much like https://github.com/atom/github/issues/1718 so we'll close in favor of that issue for now and you can subscribe there for updates if you'd like.  If it's not the same issue, we can always open a new if necessary.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
