### ISSUE TITLE
Serialization method gets repeatedly called even not at shutdown

### ISSUE THREAD

**Issue by aviatesk** [atom/atom#19303]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [ ] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [ ] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`serialize` method for any package's view serialization seems get called repeatedly e.g.: while editing/clicking on a view etc.

### Steps to Reproduce

1. Git clone [active-editor-info](https://github.com/atom/active-editor-info) and enable it as a package
2. Disable all the other non-core packages
3. Modify [the lines in active-editor-info-view.js](https://github.com/atom/active-editor-info/blob/master/lib/active-editor-info-view.js#L52-L56) like:

```javascript
serialize() {
    console.log('ActiveEditorInfoView is being serialized');
    return {
        deserializer: 'active-editor-info/ActiveEditorInfoView'
    };
}
```

4. Reload Atom and open the view via `Active-Editor-Info:Toggle` and open chrome developer tool
5. Everytime you do some action, the console emits `ActiveEditorInfoView is being serialized`

**Expected behavior:** `serialize` method should be called only when shutdown/reload

**Actual behavior:** It seems to get called repeatedly, which seemingly can be a source of performance problem ?

**Reproduces how often:** Everytime I did the repro steps

### Versions

> `atom --version`

```bash
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

> `apm --version`

```bash
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 3.7.1
git 2.21.0.windows.1
visual studio
```

### Additional Information

This is NOT [active-editor-info](https://github.com/atom/active-editor-info) specific issue. I confirmed the exactly same behavior with other packages with serialization.

**Comment by rafeca** [comment]
Thanks for reporting @aviatesk !

I've tracked down the issue and this seems to be an intentional behaviour which was introduced on https://github.com/atom/atom/pull/10605 (more specifically in this commit: https://github.com/atom/atom/commit/df83078d741164a32840396527911a0bb2e10496).

Basically, the state of the workspace (and therefore any package that's opened on a pane) is serialized for every `mousedown` or `keydown` event (with a debounce timeout of 1 second).

The most optimal solution here would be to make packages `emit` their changed state whenever it changes, which then Atom would store accordingly. Unfortunately, this requires major breaking changes to the package ecosystem so I wouldn't want to go through this path.

I can't think of any other reliable and easier to implement way of saving the state of Atom without doing what https://github.com/atom/atom/pull/10605 is doing... 

Maybe @kuychaco, @nathansobo or @as-cii have better ideas, if not I'm afraid we're not going to be able to change this behaviour.

**Comment by as-cii** [comment]
> The most optimal solution here would be to make packages `emit` their changed state whenever it changes, which then Atom would store accordingly. Unfortunately, this requires major breaking changes to the package ecosystem so I wouldn't want to go through this path.

Agreed. I am not sure they necessarily need to be breaking changes (e.g., we could introduce an API and avoid serializing state periodically for those packages which use the new API), but the cost of implementing it would certainly be non-zero.

**Comment by aviatesk** [comment]
@rafeca 
Thank you for tracking this down !
Now I understand why this behaviour is needed and the other possible workaround for this.

As far as I see the benchmarks in #10605 these serializations don't seem so much costly that I'm not sure it's worth introducing the API as @as-cii says...

Anyway, thanks for responding this issue ! I'm totally ok if you guys close this issue.

**Comment by lee-dohm** [comment]
Thanks very much for bringing this up @aviatesk. I'm glad we were able to get it explained for you. We're going to go ahead and close this but please let us know if you have any other questions.
