### ISSUE TITLE
Non-printable characters are displayed zero-width on macOS , correctly on other platforms

### ISSUE THREAD

**Issue by wesinator** [atom/atom#19307]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Non-printable characters in a file, such as null (0x00) , `0x0f` are displayed with zero-width when opening the file on macOS, but are displayed as proper-width characters on Linux and Windows.

### Steps to Reproduce

1. File containing non-printable characters ([non_printables_text.txt](https://github.com/atom/atom/files/3169199/non_printables_text.txt))
`004E0065 0077000F 0E`
2. Open in atom on Windows or Linux, and macOS

**Expected behavior:** On macOS, non-printable characters are displayed with width as characters , like they are on Linux and Windows

Windows 8.1:
![image](https://user-images.githubusercontent.com/5124946/57571654-c9f94000-73de-11e9-8bec-2cc2fe64d041.png)

Ubuntu 18.04:
![image](https://user-images.githubusercontent.com/5124946/57571656-d54c6b80-73de-11e9-8efd-501f4b916ec3.png)

**Actual behavior:** Non-printable characters are present but zero-width on atom in macOS
<img width="106" alt="image" src="https://user-images.githubusercontent.com/5124946/57571567-dfba3580-73dd-11e9-8bde-3789cabf027b.png">

VS Code on macOS shows non-printable characters with width
![VS code on mac showing unprintable characters](https://user-images.githubusercontent.com/5124946/57406979-1874c780-71b0-11e9-816e-992aa8c98a59.png)

**Reproduces how often:** 100

### Versions
```
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 2.7.10
git 2.20.1
```
macOS 10.14.4

**Comment by rsese** [comment]
Thanks @wesinator - closing in favor of https://github.com/atom/atom/issues/12157 where various issues with invisibles are being tracked.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by wesinator** [comment]
@rsese I would say this is a separate issue, since it is working on some platforms
