### ISSUE TITLE
ReactJs: Cannot read property '0' of null

### ISSUE THREAD

**Issue by nriddhi** [atom/atom#19313]
I'm trying to code for React js in Atom text editor, but it giving me an error like below image. when I type HTML code in return, the codes getting distorted. any solution or package suggestion.

![Screenshot_1](https://user-images.githubusercontent.com/8566791/57578234-dac2b800-74a9-11e9-83ed-b0de3cf31c63.png)
![Screenshot_2](https://user-images.githubusercontent.com/8566791/57578235-e0b89900-74a9-11e9-9f3a-d111d9ca6ed0.png)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
