### ISSUE TITLE
"Open link" stopped working

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19353]
### Description

"Open in link" has stopped working on the Electron v3 branch ([source](https://github.com/atom/atom/pull/18916#issuecomment-493272816)).

### Steps to Reproduce

1. Download an Atom v.138.0-beta0.
2. Open a file that contains a url.
3. Right click on the url and click on "Open link"

**Expected behavior:** The URL should be opened in the default web browser.

**Actual behavior:** Nothing happens

**Reproduces how often:** 100% of times

### Versions

Atom v1.38.0-beta0
Atom v1.39 nightlies

### Additional Information

To open external links we use  [the electron `shell.openExternal()` API](https://electronjs.org/docs/api/shell#shellopenexternalsyncurl-options), but in other places inside Atom links seem to get opened correctly (for example the ones on the `welcome` package), so it may be something to do with the handling logic for the `link:open` action ([code pointer](https://github.com/atom/atom/blob/master/packages/link/lib/link.js#L21-L34)).

**Comment by rafeca** [comment]
This seems to only be happening on JSON files, and is caused by the extracted token from the editor ([code pointer](https://github.com/atom/atom/blob/master/packages/link/lib/link.js#L55)) containing quotes.

Based on that information, my hypothesis is that this is caused by https://github.com/atom/language-json/pull/68, but that wouldn't explain why it's only happening on Electron v3...

**Comment by rafeca** [comment]
Oops, I've just download [the latest Atom nightly](https://github.com/atom/atom-nightly-releases/releases/tag/v1.39.0-nightly6) which runs on electron v2 and this issue is present there as well, so indeed that's a problem in the treesitter grammar of `language-json` and not related to electron.

**Comment by 50Wliu** [comment]
@Ben3eeE I believe you were close to a resolution with this, right?

**Comment by Arcanemagus** [comment]
The solution depended on https://github.com/atom/atom/pull/19336 as far as I understand. Now that that is in place we just need to fix it in `language-json` (and the other languages that distinguish URLs from what I understand).

**Comment by jasonrudolph** [comment]
@ben3eeE: I think this is related to the changes in https://github.com/atom/language-json/pull/68 and https://github.com/atom/language-json/pull/73, so I want to check in with you to see if you have thoughts on the preferred way to resolve this issue. 

## Findings
Here's what I'm seeing so far:

When viewing a JSON file in Atom 1.37.0, when the cursor is positioned inside a double-quoted string containing a URL, the scopes appear as follows:

<img width="472" alt="atom-stable" src="https://user-images.githubusercontent.com/2988/58034180-f2c2b900-7af3-11e9-994f-75ee27198050.png">

In Atom 1.39.0-nightly9, the scopes appear as follows:

<img width="483" alt="atom-nightly" src="https://user-images.githubusercontent.com/2988/58034179-f2c2b900-7af3-11e9-9101-2e5e5a34e186.png">

Because of that difference, the link package gets different results when it tries to identify the URL in the JSON file. When running the `Link: Open` command in Atom 1.37.0, the resulting token contains only the URL string:

<img width="772" alt="Screen Shot 2019-05-20 at 11 25 08 AM" src="https://user-images.githubusercontent.com/2988/58034189-f7876d00-7af3-11e9-83f6-ce788be0fadf.png">

When running the `Link: Open` command in Atom 1.39.0-nightly9, the resulting token contains a URL string wrapped in double quotes:

<img width="772" alt="Screen Shot 2019-05-20 at 11 21 31 AM" src="https://user-images.githubusercontent.com/2988/58034188-f7876d00-7af3-11e9-958f-2fde8fcd2c12.png">

When Atom 1.39.0-nightly9 tries to use the double-quoted string as a URL, it fails.

## Potential resolutions
I see a couple potential resolutions:

- We could change language-json so that it generates scopes in the same way it did in previous versions. Specifically, instead of generating a `string.quoted.double.markup.underlink.link` scope for the double-quoted URL string, it would generate a `string.quoted.double.json` scope for the double-quoted string, and a `markup-underlink.link.https.hyperlink` scope for the URL itself (without the surrounding double quotes).
- Alternatively, we could probably change the link package to strip the surrounding double quotes when it encounters a `string.quoted.double.markup.underlink.link` scope.

@ben3eeE: Given your familiarity with the recent enhancements to language-json, do you have a preference for which approach I take? Or, if there's another approach that would work better, just let me know. :bow:

**Comment by jasonrudolph** [comment]
A quick update:

@Ben3eeE and I discussed the potential resolutions described in https://github.com/atom/atom/issues/19353#issuecomment-494044274:

> - We could change language-json so that it generates scopes in the same way it did in previous versions. Specifically, instead of generating a `string.quoted.double.markup.underlink.link` scope for the double-quoted URL string, it would generate a `string.quoted.double.json` scope for the double-quoted string, and a `markup-underlink.link.https.hyperlink` scope for the URL itself (without the surrounding double quotes).
> - Alternatively, we could probably change the link package to strip the surrounding double quotes when it encounters a `string.quoted.double.markup.underlink.link` scope.

The first option benefits all consumers of language-json, so that feels like a more desirable resolution, whereas the second option is more of a patch job. :innocent: With that in mind, I'm heading in the general direction of the first option above.

To make these changes to language-json, we first need to enhance tree-sitter-json to provide a syntax node for the internal content of JSON strings. (For example, given the string `"abc"`, we need tree-sitter-json to provide a syntax node for `abc`.) I *think* https://github.com/tree-sitter/tree-sitter-json/commit/7252a04fe549642e6505a11bdb106101e755aa66 will meet this need. Before opening a pull request in tree-sitter-json with that change, I'll first try to get language-json using that change locally, and then see if I can use my local version of language-json to resolve this issue. If all of that works out, then I'll open pull requests for each of these changes. Stay tuned. :smile::tv:

**Comment by jasonrudolph** [comment]
> Before opening a pull request in tree-sitter-json with that change, I'll first try to get language-json using that change locally, and then see if I can use my local version of language-json to resolve this issue. If all of that works out, then I'll open pull requests for each of these changes.

I've got things working locally now. I've pushed up the changes in https://github.com/atom/language-json/commit/6595ca72b45e707cb01998a0d7b41bebbe60ea74. That commit currently depends on my fork of tree-sitter-json, so my next step is to open a pull request in tree-sitter-json to introduce the changes in https://github.com/tree-sitter/tree-sitter-json/commit/7252a04fe549642e6505a11bdb106101e755aa66. Once that's done, I'll open a pull request for the language-json changes and ask for review.
