### ISSUE TITLE
Atom Editor Doesn't Come to Foreground on Windows 10 if already open

### ISSUE THREAD

**Issue by kendonB** [atom/atom#19361]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom on Windows 10 does not gain focus if a window is already open.

### Steps to Reproduce

1. In `git bash` run `atom test.txt` (Atom opens in foreground)
2. Return to `git bash` and run `atom test2.txt` 

**Expected behavior:** [What you expect to happen]
Atom opens test2.txt in new tab and gains focus.

**Actual behavior:** [What actually happens]
Atom opens test2.txt in new tab and doesn't gain focus

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always
### Versions

Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
OS    : Windows 10 x64

Related issues do not appear to be focused (excuse the pun) on this specific consistent behavior: #6201 #18610

**Comment by rsese** [comment]
> Related issues do not appear to be focused (excuse the pun) on this specific consistent behavior: #6201 #18610

There's a number of open issues so some things haven't been prioritized unfortunately (though the team is always willing to review well-written pull requests).  Since #6201 is still open we'll close in favor of that issue.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
