### ISSUE TITLE
Accidental opening of installer has no way out

### ISSUE THREAD

**Issue by rbertoche** [atom/atom#19363]
### Description

If by any reason the user accidentally runs AtomSetup he is forced to wait until it's done since it's impossible to cancel the installation.  It's not that bad if Atom isn't already installed, but if you already have it installed you end up getting to uninstall it and then you have to wait for it to install again to be able to get back to work. In other words, one misclick ends up either overwriting or uninstalling atom from your system.

In my case I was running an Atom instance so I knew installation would fail on windows since files are locked for writing. So I tried to kill the installer, and then it uninstalled my previous atom installation. Also if I didn't killed it it would fail to overwrite some open file and would fail to install eventually and give the same result.

### Steps to Reproduce

1. If you don't have Atom installed, install it.
2. After installation, invoke AtomSetup again
3. Kill the Update process;

**Expected behavior:**

It would be nice if the installer did any one of these things:
- Detect that's overwriting an installation and prompt the user for confirmation;
- Detect that's overwriting an installation of the same version and prompt the user for confirmation;
- Don't start installing just after InstallAtom is called; Instead open some window with any kind of "Install" button;

**Actual behavior:**

Atom is uninstalled from the system

**Reproduces how often:**
100%

### Versions

1.37.0 and 1.36.0;

### Additional Information

I have this issue on windows and I have no idea whether it's windows only or not. I'm running Windows 8.1 x64 if that may be relevant in any way

### Off-topic query
Also, as a off-topic observation, don't you guys miss a cancel button on the installer? What if you notice you're installing the wrong version or on a wrong remote desktop session?
That wouldn't help in this case though. Cancel would probably uninstalling Atom as killing it did.

This is my first issue here so I hope I'm not breaking rules much

**Comment by rsese** [comment]
Thanks for the report!

> It would be nice if the installer did any one of these things:
>
> * Detect that's overwriting an installation and prompt the user for confirmation;
> * Detect that's overwriting an installation of the same version and prompt the user for confirmation;
> * Don't start installing just after InstallAtom is called; Instead open some window with any kind of "Install" button;

I was chatting with another maintainer about this and wanted to share a couple of notes from what we talked about - basically, the framework we use for updates/installs (https://github.com/Squirrel/Squirrel.Windows) is designed to provide a simple install experience;  no prompts for where you want to install and generally no prompts/dialogs asking questions.  And in addition to that, on our end we don't currently plan to customize the install/update experience.  For folks that need a bit more control (like where to install the application), we provide a .zip file that people can use, no installer involved: https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode.

Since this isn't something the team would work on I'm going to close this out but I'll share your feedback with the rest of the team.

> ### Off-topic query

...

> This is my first issue here so I hope I'm not breaking rules much

No problem :smile:  If you have an Atom-related general question or just want to have a discussion about something Atom-related, the best places to go are the official [message board](https://discuss.atom.io) or the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638).

**Comment by rbertoche** [comment]
Ok then.

But allow me to add that from a HCI point of view simplicity of features or
widgets usually doesn't lead to a simple interaction.

One of the many reasons for that is probably the tendency in software that
things manage to go wrong even when you're sure they can't due to both
programmer's and user's mistakes.

In fact I think that's actually the opposite: a communicative interface -
it doesn't need to be too verbose of course - is almost always better and
more simple to use than one based on such strict "no dialogs no prompts"
policy. That is a simple interface to design more so than to use.

This silence gets in the way even more so if you decide that your software
shouldn't adapt to the circumstances that affect it's behavior. Also it's
idiomatic in windows installer's that they even ask if the user wants to
reinstall, uninstall or upgrade your application once it's already
installed.

If those points don't look that worth the trouble to you maybe you can
simply bail out and ask the user to uninstall it himself instead of
silently ovewriting a previous installation. It would be tremedously better
than just doing always the same thing regardless of a different outcome.

Thanks for answering the report!

Em qua, 29 de mai de 2019 03:23, Robert Sese <notifications@github.com>
escreveu:
