### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addItem' of undefined

### ISSUE THREAD

**Issue by becky26** [atom/atom#19380]
[Enter steps to reproduce:]

1. drag Debugger to the right part of Atom Window

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'addItem' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'addItem' of undefined
    at Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:460436)
    at Object.end (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1108549)
    at HTMLLIElement.TabView.element.ondragend (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:876291)
```

### Commands

```
     -7:08.5.0 core:close (input.hidden-input)
     -3:38.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:22.2.0 atom-ide-terminal:new-terminal (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:20.5.0 core:paste (textarea.xterm-helper-textarea)
  2x -3:18.8.0 core:undo (textarea.xterm-helper-textarea)
     -3:08.7.0 core:paste (textarea.xterm-helper-textarea)
     -1:41.4.0 golang:godef (input.hidden-input)
     -1:36 golang:gofmt (input.hidden-input)
     -1:30 golang:hide-coverage (input.hidden-input)
     -1:20.2.0 find-and-replace:select-next (input.hidden-input)
     -1:17.2.0 datatip:toggle (input.hidden-input)
     -1:17 golang:showdoc (input.hidden-input)
  3x -1:15.5.0 datatip:toggle (input.hidden-input)
     -0:45.9.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:28.9.0 debugger:reset-layout (nuclide-react-mount-root.debugger-container)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-typescript 13.2.1 
go-debug 1.6.2 
go-plus 6.1.0 
highlight-selected 0.16.0 
ide-vue 0.1.9 
language-javascript-jsx 0.3.7 
minimap-split-diff 0.3.7 
remote-ftp 2.2.2 
split-diff 1.6.0 
tree-view-filter 0.5.5 
```

**Comment by jmooree30** [comment]
I can look into this tonight if it's up for grabs.

**Comment by rsese** [comment]
Thanks for the report!

> 1. drag Debugger to the right part of Atom Window

Guessing this isn't reproducible in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) and happened when using `go-debug`?  The best place to start in this case is by filing this issue on [their repository](https://github.com/lloiser/go-debug) so they can either fix the problem or tell us where the problem is coming from.  It may be that there is still a bug in Atom and if so, we'll need the maintainer of the package that is causing the problem to help track that down.  The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
