### ISSUE TITLE
one-dark-syntax keyword.operator should be colored

### ISSUE THREAD

**Issue by dan1wang** [atom/atom#19385]
In `one-dark-syntax/styles/syntax/_base.less`, **operator** is of color _@mono-1_ . This makes [no sense](https://discuss.atom.io/t/why-logical-operators-are-not-colored-in-one-dark-syntax-theme/22496/2).

In `c.less`, `cpp.less`, `java.less`, `javascript.less` and `python.less`, the color is redefined as _@hue-3_

Oddly, in `typescript.less`, the color is _@hue-1_ (why the break from JavaScript?)

IMHO, **operator** should be defined as _@hue-3_, and language-specific overrides should be removed.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
