### ISSUE TITLE
Atom does not signal about a file changed on disk 

### ISSUE THREAD

**Issue by Marco-Sulla** [atom/atom#19384]
I have Dropbox on two machines, and I modify a file on both of them. Atom does not signal that the file is changed on disk. I tried all the options (Polling, native etc) but nothing. Now I'm using gedit for that file.

OS: ***L***ubuntu 18.04.2 64bit
Atom 1.37.0 64bit

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

-----

I noticed that this is the third issue you've opened and ignored the issue template. Continuing to do so will be considered harassment under the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) and may result in being temporarily or permanently blocked from the organization. You may consider this an official warning.
