### ISSUE TITLE
Move and select to first letter(a-zA-Z)

### ISSUE THREAD

**Issue by jefferyyuan** [atom/atom#19395]
- Usually, we want to move/select to the first letter(a-zA-Z), not the first character.
- there are some prefix text
  - most for syntax: such as in markdown: header: #### or -
```markdown
#### the title I want to change(cursor here)
```
- in the above example, I want to move to the first letter and select the whole title

**Comment by lee-dohm** [comment]
Thank you for the suggestion!

That sounds like an interesting idea for a community package :+1: Unfortunately, the Atom maintainer team is already full up handling all of the support and maintenance of the current core packages. There are a couple options:

* Someone may have already created this and we're not aware of it. Have you searched [the Atom package registry](https://atom.io/packages/)?
* You can post a message on [Discuss, the official Atom and Electron message board](https://discuss.atom.io/c/packages) to see if anyone from the community is willing to try and build it

In any case, because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). But I'm also going to label this with `package-idea` so that others searching for suggestions here can find this.

Thanks again for your interest in Atom :grinning:
