### ISSUE TITLE
Difficult-to-see controls

### ISSUE THREAD

**Issue by uaninna** [atom/atom#19400]
Hey.
Try to see any controls (at the bottom left(open fullscreen to see them)). It's very hard to do it because the controls are gray there...
So, how to change their color to white?
![image](https://user-images.githubusercontent.com/32965278/58321006-9a5a2700-7e25-11e9-87e0-21378e2180ba.png)
_____
OS: Ubuntu 19.04

**Comment by uaninna** [comment]
And, they are normal if window is not focused
![Screenshot from 2019-05-24 13-50-31](https://user-images.githubusercontent.com/32965278/58322900-0723f000-7e2b-11e9-9556-77ddf8e513b3.png)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
