### ISSUE TITLE
Atom should signal about a file changed on disk

### ISSUE THREAD

**Issue by Marco-Sulla** [atom/atom#19411]
## Summary

Atom should signal about a file changed on disk

## Motivation

Files opened in Atom and changed elsewhere are silently updated

## Describe alternatives you've considered

Atom should not update the file automagically, but signal the change as gedit does. The user is free to load new contents, or save old contents, or save old contents on another file.

**Comment by Marco-Sulla** [comment]
See also  #14709

**Comment by rsese** [comment]
Thanks for contributing!

Looks like #14709 missed https://github.com/atom/atom/issues/3594, closing in favor of that issue if you want to subscribe there.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
