### ISSUE TITLE
Opening German smart quote „ is not recognized as such

### ISSUE THREAD

**Issue by getreu** [atom/atom#19424]
### Opening German smart is not recognized

In English typing “  shows “” and places the cursor in between. Atom is aware of matching English quotes.

The same behaviour is expected for the German opening and closing quotes: 

Type „ and it should show „“ and place the cursor in between.

**Comment by rsese** [comment]
Thanks for reaching out!

As mentioned below, please fill out the issue template when opening issues otherwise your issues may be closed.

About your report, you can customize Atom to support this at `Settings > Packages > Bracket Matcher > Autocomplete Characters`, just add `„“` to this field.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by getreu** [comment]
Thank you to point me out to "atom-bracket-matcher". I filed the PR [Add German single and double quotes](https://github.com/atom/bracket-matcher/pull/385) there.

**Comment by getreu** [comment]
I firmly disagree with your rejection of [Pull Request #385 · atom/bracket-matcher](https://github.com/atom/bracket-matcher/pull/385)

This is not a customization matter or a matter of personal taste concerning default values! 

This is about (German) localization. By refusing the German quotes that come with this PR, you keep Atom unusable for high quality typesetting in German language. 

This is a general policy issue, I will put up for discussion.
