### ISSUE TITLE
Atom background syntax issue dark mode ubuntu 19.04

### ISSUE THREAD

**Issue by StarrKiss** [atom/atom#19439]
I have an issue using a dark atom syntax theme I made myself where the background is different under blocks of text. I know this issue was closed before because the bug had been fixed, however, it seems to reappear and not of the fixes suggested in the og thread work. I am using the newest version of Atom and Chromium:
![reee](https://user-images.githubusercontent.com/13007697/58820733-fa588680-85f8-11e9-9cfb-245c6312fefb.png)

I have already followed all the apropriate steps as laid out by the original issue.

**Comment by rsese** [comment]
Thanks for reaching out!

As mentioned below, please fill out the issue template when opening issues otherwise your issues may be closed.

About your report, see if the suggestion in https://github.com/atom/atom/issues/19394#issuecomment-495316015 helps.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
