### ISSUE TITLE
the command 'shift + cmd + /' for comment files *.html.eex in Phoenix Framework error is incorrect

### ISSUE THREAD

**Issue by romenigld** [atom/atom#19458]
### Description
I'm using the command `shift + cmd + /` for comment in `*.html.eex` files  with the  Phoenix Framework and the Atom app puts comments in those file like this:
`<!-- comments  -->`
but this comments don't works on those file. For example I put an Issue [here](https://github.com/phoenixframework/phoenix/issues/3423)
And this was the problem.
So the correct way for comment on those files is like this:
```
 <%#= for key <- connection_keys(@conn) do %>
    <%#= render("key.html", key: key) %>
  <%# end %> 
```
> atom --version
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

```
```
> apm --version
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.37.0
python 2.7.15
git 2.20.1

```
OS name and version: Mac OS Mojave 10.14.5

**Comment by rsese** [comment]
Thanks for the report!  I believe this should be handled by whatever language package you're using for `html.eex` files (i.e. if I create a `.html.eex` file, toggling comments does nothing because I don't have a language package to handle `.html.eex` files).

It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
