### ISSUE TITLE
Settings: Default file format

### ISSUE THREAD

**Issue by ShalokShalom** [atom/atom#19456]
I always work in FSharp.
So, it would be nice if every new file is a .fs. 
Currently, there seems to be a way by editing the init.coffee file, while I appreciate a GUI way in the settings.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

> Currently, there seems to be a way by editing the init.coffee file

Yes this is true (link for anyone that comes across this issue: https://discuss.atom.io/t/how-can-i-make-all-new-files-open-with-a-specific-grammar-or-syntax/20754).

Additionally, as mentioned in the issue template, the team is very unlikely to prioritize feature requests right now, especially when Atom's customizability can provide the necessary functionality as is the case here.
