### ISSUE TITLE
Atom is not saving

### ISSUE THREAD

**Issue by ceremcem** [atom/atom#19486]
Like in #18114, Atom has started this behavior about two months ago, after installing a newer version of Atom (I'm really sorry, I can't recall the exact working version). I started using another editor while waiting #18114 to get solved. 

* I'm using Debian 9 testing, 
* Atom 1.36.1 x64, 
* there are no errors in the console output, 
* as mentioned before, another editor works just fine 
* file system is local

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by ceremcem** [comment]
That's fair. Thanks for your nice comment.
