### ISSUE TITLE
Flaky test: Timeout in test of find-and-replace:copy-path

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#19480]
https://github.visualstudio.com/Atom/_build/results?buildId=42708&view=logs&jobId=6de74252-975b-522d-7a3d-227ca79ca6c1&taskId=b7ded238-9370-50c9-8500-e02f948495a4&lineStart=468&lineEnd=473&colStart=1&colEnd=78

**Comment by jasonrudolph** [comment]
We had hoped that this issue was resolved by #19505, but we saw this flake again last night:

https://github.visualstudio.com/Atom/_build/results?buildId=43605&view=logs&jobId=6de74252-975b-522d-7a3d-227ca79ca6c1&taskId=b7ded238-9370-50c9-8500-e02f948495a4&lineStart=473&lineEnd=477&colStart=1&colEnd=9

That build includes the changes from #19505 (i.e., the upgrade to find-and-replace v0.218.13), so I think that means that this flake is still an issue. With that in mind, I'm going to re-open this issue. If I'm interpreting these results incorrectly and this issue should remain closed, just let me know.
