### ISSUE TITLE
Does exist something like Better comments?

### ISSUE THREAD

**Issue by Vanals** [atom/atom#19485]
I am one of the few developers who use Atom in my team and we want to introduce something like
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

Does exist anything like that for Atom? I looked for it but I haven't found it.

Thank you.

**Comment by Arcanemagus** [comment]
I'm not sure anything exists that matches that exactly, the closest that I know of would be [docblockr](https://atom.io/packages/docblockr). You may have better luck finding an alternative by posting in Discuss (linked below).

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
