### ISSUE TITLE
Atom Error: Syntax: extra token "parameters" after end of expression

### ISSUE THREAD

**Issue by vikas9087** [atom/atom#19545]
Hi,

I am using Atom for Julia. And trying to define some parameters as below:

System Details: 
Atom-1.91.
Julia-Client-0.8.9
uber-juno-0.2.0
#=------------------------------------------------
Fixed paramters
------------------------------------------------=#
e=0.74
alpha=15
tau=[288.66e9,108.2475e9,36.0825e9]
phi=0.01
rho=4
nr_t=length(tau)
time_index=Dict(1=>"Jan-Aug",2=>"Sep-Nov",3=>"Dec")
nr_scenarios=10

**it gives me the error message as "syntax: extra token "parameters" after end of expression.**

Thank you for your support.
Vikas

**Comment by Arcanemagus** [comment]
It appears you are asking about support for something related to your Julia code, since Atom is a text editor this doesn't appear to be related to Atom in any manner other than that happened to be the editor you were using while writing this. You will want to find a community to help you with your Julia code issue, such as the many options listed here: [Julia Community](https://julialang.org/community/).

Thanks for reaching out!

----

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
