### ISSUE TITLE
After ~5 seconds cannot save or open files from project tree sidebar

### ISSUE THREAD

**Issue by thesecretmaster** [atom/atom#19550]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

On only one of the many projects that I use atom for, when I open the editor (as I usually do) from the project directory with `atom .` it will open and appear to be fine, and I'll be able to open a file in the first few seconds and even edit it. Then, after that brief period ends, I cannot open files from the project tree sidebar. I will click on the files and they just won't open. Files that are open cannot be saved.

I thought this might be an issue where atoms state got corrupted somehow, so I ran with the --clear-window-state flag, tried in --safe mode, etc. I even tried cloning the repository of the project I'm trying to work on into a new directory and it still failed. I think it must have something to do with the project itself, and I have no idea how to troubleshoot that further.

When I've tried this on another computer (running Ubuntu) it runs fine and I see no problem, so it seems like some combination of the project, atom state, and the OS.

### Steps to Reproduce

(can only reproduce on my machine)
1. Clone project repo
2. atom .
3. Try to edit a couple files

**Expected behavior:**

The edits to be saved

**Actual behavior:**

Files cannot be saved or opened after the first few seconds

**Reproduces how often:**

Every time I open the project on my Arch Linux machine. 

### Versions

```
Atom    : 1.38.1
Electron: 4.1.4
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

OS: Arch Linux

**Comment by Aerijo** [comment]
> Electron: 4.1.4

Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by thesecretmaster** [comment]
Hello! Sorry, I had no idea I was using an unofficial build of atom. Is [the version that's in the arch linux official repo](https://www.archlinux.org/packages/?name=atom) not an official build?

**Comment by thesecretmaster** [comment]
I think I'm on an official build now, and I'm still seeing this problem.

atom --version gives

```
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
