### ISSUE TITLE
Package for Anaconda Integration

### ISSUE THREAD

**Issue by PunnyBoi** [atom/atom#19587]
## Summary

I want to request a package for anaconda integration into atom just like VSCode. It should allow us to select the desired environment out of many environments made using anaconda.

## Motivation

Let us say I am working on two projects simultaneously. I made appropriate environments for them with required packages using anaconda. Now every time I have to run the code, I have to go to Anaconda Prompt and then activate that environment and then open Atom from that prompt. If I want to run the other code (in a different environment), I again have to go to Anaconda Prompt and activate the environment and again launch atom from the Prompt. Life would have been much simple if I have a drop-down menu in Atom where I can select the environment without going back and forth to the Anaconda Prompt. 

## Describe alternatives you've considered

Currently, I am using Anaconda Prompt to activate the required environment and then launching the atom from the Prompt so that Atom knows that I am in that particular environment. This procedure works fine but becomes painful when I have more than one project.

**Comment by rsese** [comment]
Thanks for the suggestion!  Though this sounds like a useful idea for some people's workflows, we're  not prioritizing feature requests right now as mentioned in the issue template.  Also, this sounds like a good idea for a community package rather than a core package since we're not looking to take on and maintain more core packages right now.

Since this isn't something the team would work on, I'm going to close this out but thanks again for the idea :bow:
