### ISSUE TITLE
How to check if the macOS version is code-signed?

### ISSUE THREAD

**Issue by gooiey** [atom/atom#19598]
Hello,

I'm wondering how to check the if the macOS version is code-signed. Thanks!

**Comment by Arcanemagus** [comment]
A quick Google search turns up this page: http://osxdaily.com/2016/03/14/verify-code-sign-apps-mac-os-x/

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
