### ISSUE TITLE
File Tree not updating

### ISSUE THREAD

**Issue by katsar0v** [atom/atom#19606]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Whenever there are a lot of files, the tree view does not refresh as wished. On new folders Atom's file tree works fine.  Example:

`mkdir /tmp/test/ && atom /tmp/test/` would not reproduce this issue, **but** running atom in a folder with lots of inodes (in my case `find . | wc -l` says `132328`) produces this issue:

![gif](https://im.ezgif.com/tmp/ezgif-1-3f75c8197a81.gif)

When running atom in `/tmp/test/` as mentioned the issue disappears (probably because of the less inodes)

## Atom version

```
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by jconstable02** [comment]
I have been trying to unsubscribe from this fir a week. I am job searching and between the constant tittering back and forth from thus and two other grouos I cant get 5 mins of focused work done.This is an issue I will outsie with github and any higher ups needed in order to simply be unsubscribed. I have unmatched the repositories...logged out...i guess next step is deleting my account. Sorry for the angry tone but I am nowhere near the group knowledge and skill set. Please, someone empathize and advise me here!While compisinh this message I have received 6 notifications from 3 github repositories. It's a f##king nightmare.

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 27, 2019 at 2:55 AM, Kristiyan Katsarov<notifications@github.com> wrote:   
Prerequisites
   
   - [ X] Put an X between the brackets on this line if you have done all of the following:      
      - Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
      - Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
      - Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
      - Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
      - Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages


Description

Whenever there are a lot of files, the tree view does not refresh as wished. On new folders Atom's file tree works fine. Example:

mkdir /tmp/test/ && atom /tmp/test/ would not reproduce this issue, but running atom in a folder with lots of inodes (in my case find . | wc -l says 132328) produces this issue:

https://im.ezgif.com/tmp/ezgif-1-3f75c8197a81.gif

When running atom in /tmp/test/ as mentioned the issue disappears (probably because of the less inodes)

**Comment by rsese** [comment]
Sorry for the trouble @jconstable02 - if you've [unwatched](https://help.github.com/en/articles/watching-and-unwatching-repositories#unwatching-a-single-repository) atom/atom (that's the first thing I would double check) but are still getting notifications in this repository, I'd suggest reaching out to GitHub Support for help: https://github.com/contact.  The GitHub Community Forum is another good resource for help from the larger GitHub community: https://github.community/.

**Comment by jconstable02** [comment]
Ty for that. Sincerely.

**Comment by rsese** [comment]
Thanks for the report @katsar0v - looks like there's an issue with your GIF?

Also, I'm assuming you're on Linux?  If so, this is expected behavior on Linux as far as I know, e.g. see the discussion here: https://github.com/atom/atom/issues/16250#issuecomment-421983384.

The team has investigated the possibility of using a different file watching system but nothing concrete at the moment.  If you're working on a very large project with a lot of files, you could try the different `Settings > File System Watcher` settings or if it's something you can adjust on your system, try increasing `fs.inotify.max_user_watches` (see the same issue for some discussion about adjusting that value https://github.com/atom/atom/issues/16250#issuecomment-358233796)

**Comment by katsar0v** [comment]
Oh, the gif went missing. Yes, I am using Linux Ubuntu. I will try the settings and report, thank you for the update!

**Comment by katsar0v** [comment]
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` actually helped! Thanks!
