### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by WCihan** [atom/atom#19605]
[Enter steps to reproduce:]

1. Move a tab right side and other to left side
2. Then try to move back

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At C:\Users\cihan\AppData\Local\atom\app-1.38.2\resources\app\static\<embedded>:11

Error: Pane has been destroyed
    at Pane.activate (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:462165)
    at HTMLElement.handleDrop (/app.asar/src/pane-element.js:62:23)
```

### Commands

```
     -4:39.2.0 intentions:highlight (input.hidden-input)
     -4:39 core:close (input.hidden-input)
  2x -4:36.6.0 intentions:highlight (input.hidden-input)
     -4:34.8.0 core:copy (input.hidden-input)
 20x -3:11.6.0 intentions:highlight (input.hidden-input)
     -2:00.4.0 core:backspace (input.hidden-input)
  3x -1:53.2.0 core:move-down (input.hidden-input)
     -1:52.1.0 core:move-up (input.hidden-input)
  3x -1:51.8.0 core:move-down (input.hidden-input)
  5x -1:50.7.0 core:move-up (input.hidden-input)
  5x -1:38.8.0 core:backspace (input.hidden-input)
  2x -1:30.2.0 core:move-down (input.hidden-input)
  6x -1:09.5.0 core:backspace (input.hidden-input)
     -1:07.0 core:confirm (input.hidden-input)
     -0:48.7.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:26.6.0 tabs:close-all-tabs (div.title.icon.gear-icon)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-symfony2 0.3.0 
atom-wordpress 0.3.0 
autocomplete-html-entities 0.2.0 
autocomplete-wordpress-hooks 0.2.3 
busy-signal 2.0.1 
es6-javascript 1.0.0 
file-icons 2.1.33 
git-plus 8.7.0 
hyperclick 0.0.0 
ide-json 0.2.1 
ide-php 0.7.18 
ide-typescript 0.9.1 
intentions 1.1.5 
language-sql-mysql 0.3.1 
remote-ftp 2.2.2 
symfony-commands 0.4.3 
symfony-snippets 0.3.0 
sync-settings 0.8.6 
teletype 0.13.4 
wordpress-api 1.2.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by WCihan** [comment]
Nope tested. Not exist in safe mode.

**Comment by rsese** [comment]
> Not exist in safe mode.

Thanks for confirming :+1: If there's no problem in safe mode, then that likely means a community package is causing the issue:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

You can disable each community package one by one to try and pinpoint which is causing the problem so you can file this issue on their repository.  They can then either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
