### ISSUE TITLE
Is there some reason the MSI was removed between May'19 and Jul'19? We use it!

### ISSUE THREAD

**Issue by michael-crawford** [atom/atom#19624]
## Summary

I last obtained a version of AtomSetup-x64.msi around May 24, 2019, based on the timestamp of the installer in my S3 bucket used for product installs. I recently went to update this and noticed the MSI no longer seems to exist. I searched older release assets and it seems to have been removed for every one I looked at going back months. We prefer this format - is there some reason this has been removed? Do you have a workaround for non-interactive installs?

## Motivation

We create infrastructure in AWS using CloudFormation. When creating instances, we use the AWS-native cfn-init program within CloudFormation templates to configure instances, including Windows. We want to pre-install Atom on our Windows Bastion hosts, as CloudAdmins need to first get to a bastion before they can reach internal resources in our Production environment as we must conform to FedRAMP standards. The cfn-init method has a package installer that can install an MSI, which we're using to do this. If you're taking away the MSI, which is installed non-interactively, not sure how we can install the EXE as a replacement. First, it does not have the same native package format support, and next, I think the EXE may require interactive feedback.

**Comment by Arcanemagus** [comment]
As far as I can tell [v1.18.0](https://github.com/atom/atom/releases/tag/v1.18.0) was the last release to actually publish a `.msi` build to it. I'm not entirely sure where you have been getting `.msi` builds from past that point but they don't appear to be builds we are producing.

Are you able to use the `.zip` artifacts? Those are intended to simply be extracted and ran with no installation, however I believe  automated updates are disabled for that platform so you would need to be handling that elsewhere.

**Comment by Ben3eeE** [comment]
> Because they were not the kind of installer anyone was expecting. It was
not an msi alternative to the setup but rather an msi that simply added the
regular setup exe to everybody's auto run.
https://github.com/atom/atom/issues/11087#issuecomment-365103649

**Comment by michael-crawford** [comment]
Whatever it was, it worked via the CloudFormation cfn-init package:msi install method in a non-interactive way.

Not all of us are installing this manually on desktops. I need this installed non-interactively on a bastion currently running Win2012R2. These are in Auto-Scaling groups that destroy and re-create bastions daily. Users ideally need a recent copy which CAN be updated quickly by hand if they go to use them, so not sure if zip is a realistic alternative.

MSI is like an RPM or DEB - the standard way to install packages non-interactively on Windows. Is there some reason why it's too difficult to package in this manner? Seems like it should be trivial for someone who's worked with Windows software for any length of time.

**Comment by rsese** [comment]
Just following up here - chatted with the other maintainers and see that as mentioned above ([1], [2]), we last published the MSI in Atom 1.18.0 which shipped in June 2017 but not since then.  Additionally, we've already generally decided to not maintain additional installation packages beyond the current package formats we already provide.  And with the team's current priorities and resources, it's not something we would commit to maintaining.  So for these reasons we're going to close the issue - though we don't have more specific suggestions for non-intertactive installs beyond using the .zip file, it's possible folks in the [community](https://discuss.atom.io/) may have ideas. 

[1]: https://github.com/atom/atom/issues/19624#issuecomment-507958445
[2]: https://github.com/atom/atom/issues/19624#issuecomment-507949304
