### ISSUE TITLE
Atom empty input fields

### ISSUE THREAD

**Issue by cre-mer** [atom/atom#19637]
My input fields in atom are always empty.
I have a macBook Pro at home (High Sierra) and an macPro at work (High Sierra) and my ~/.atom folder on both are exactly the same (https://github.com/cre-mer/.atom)
I have tried this "atom --safe --disable-gpu" from another issue 
https://github.com/atom/atom/issues/17094#issuecomment-379344427_ and I have visited the debug website of atom and tried every command/solution.

My problem is, my macPro at work doesn't show the text in the input field, but the macBook at home does. Although they have the same .atom configurations. I assume it may be a problem from the macPro?

I have

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
