### ISSUE TITLE
Atom Sublime style text selection on UI.

### ISSUE THREAD

**Issue by senceryazici** [atom/atom#19636]
Hello, I love atom and use it on everyday work, I'm using some UI themes and syntax themes to make it even better. 

Here is one suggestion, I really love how the selections are shown in sublime text 3,

<img width="709" alt="image" src="https://user-images.githubusercontent.com/15329726/60671235-583bf080-9e7b-11e9-8f4f-303050b66856.png">
 
The selection(highlighted area) has this lighter look, just over the text of the selected lines, not the whole line, and the white dots representing the whitespace characters, and the highlight have some nice round edges.

I know that the atom already has those features by usage, but this kind of ui look will be perfectly looking one.

And I also know this is like a UI theme suggestion, it's not for atom core, but i didn't know where to write to...

So all in all, It looks perfect in sublime text 3, if this is the wrong place to write this can you guide me to right place, or I'm looking for a package or a guide for this to create it myself as a ui theme.

Thanks.

**Comment by Arcanemagus** [comment]
> The selection(highlighted area) has this lighter look, just over the text of the selected lines, not the whole line, ... and the highlight have some nice round edges.

This can be accomplished using a package, [outline-selection](https://atom.io/packages/outline-selection) being the first example I found. You could also likely accomplish this using [pure CSS in your `styles.less` file](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks).

> the white dots representing the whitespace characters

This is built into Atom already, you can enable it with the Editor -> Show Invisibles setting 😉

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
