### ISSUE TITLE
Cannot copy text from atom alert

### ISSUE THREAD

**Issue by wesinator** [atom/atom#19647]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Text in an atom alert is not copyable

### Steps to Reproduce

1. To generate alert:
  - Install https://atom.io/packages/tablr

2. Open [invalid CSV](https://github.com/atom/atom/files/3369925/invalid_csv_to_generate_alert.zip)
)  to generate error alert (`alert-danger`)

3. See the red alert message
  Select text, Cmd-C

**Expected behavior:** able to copy text from alert element
Use case : for debugging/searching

**Actual behavior:** text cannot be copied from alert element
<img width="425" alt="image" src="https://user-images.githubusercontent.com/5124946/60836480-c4786600-a193-11e9-81a2-c8b4dc1ca3d7.png">

**Reproduces how often:** always

### Versions

macOS 10.14.5
```
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 2.7.10
git 2.22.0
```

**Comment by lee-dohm** [comment]
I could not reproduce this user Atom Nightly v1.40.0-nightly23 on macOS 10.14.5. I used the following code in my `init.coffee` to throw an error and pop up an Atom notification:

```coffee
atom.commands.add 'atom-workspace',
  'custom:throw-error': ->
    throw new Error
```

I selected text from the ensuing notification and was able to copy it using <kbd>Cmd+C</kbd>.

Thanks for contributing!

It appears that this is being caused by the [tablr package](https://atom.io/packages/tablr), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by wesinator** [comment]
> I could not reproduce this user Atom Nightly v1.40.0-nightly23 on macOS 10.14.5. I used the following code in my `init.coffee` to throw an error and pop up an Atom notification:
> 
> ```coffee
> atom.commands.add 'atom-workspace',
>   'custom:throw-error': ->
>     throw new Error
> ```
> 
> I selected text from the ensuing notification and was able to copy it using Cmd+C.
> 

@lee-dohm that is not the `alert` to which I'm referring. 
Please follow the exact steps and see. 

the one I'm referring to I think is at https://github.com/atom/atom/blob/08063d67dd58676c5a497b1f49f57caa452e68c9/static/atom-ui/styles/private/alerts.less#L112 , based on : 
https://github.com/abe33/atom-tablr/blob/3e8c2b8bd857a362214568cd249a7ff941dc49d6/lib/csv-editor-form-element.js#L379 , 
https://github.com/abe33/atom-tablr/blob/3e8c2b8bd857a362214568cd249a7ff941dc49d6/lib/csv-preview-element.js#L24

I think this is a UI element controlled by atom itself, not a custom UI in that app package.

**Comment by lee-dohm** [comment]
If the problem cannot be reproduced in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it is almost always a problem with that individual package. This is why our issue template requires the use of Safe Mode to reproduce problems.

The code you point to describes the [tablr package](https://atom.io/packages/tablr) specifically creating a UI element of its own, not using any functionality provided by the Atom API. The way Atom is designed, we can't prevent an individual package from using its own methods to display alert or error messages. We do provide a [Notifications API](https://atom.io/docs/api/latest/NotificationManager) for packages to use to display notifications, though the package you're describing may predate that API being created. But, as I've shown, the Notifications API does not share the problem you're pointing out.

Because of all of the reasons above, and because the Atom team doesn't own or control the code that is causing the problem, there's not a lot we can do.
