### ISSUE TITLE
Unsaved file exit atom recovery

### ISSUE THREAD

**Issue by tonycody** [atom/atom#19648]
From the first version of the atom used, the latest version still does not support unsaved files to exit the program recovery, like sublime, vscode have been supported, but the atom still does not support, do not understand ~~~ have to build a Project Useful, very difficult to use

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Also, without the extra information in the template, I'm guessing you're asking about https://github.com/atom/autosave/issues/11?  If that's the case, you can subscribe there if you'd like.
