### ISSUE TITLE
Unable to open Atom

### ISSUE THREAD

**Issue by gk65408** [atom/atom#19640]
I was using Atom text editor for few months for my coding exercising. Suddenly when I tried opened it today, Atom opens but instead of actual application, the developer tools open and i can see below errors in console log. please can somebody help to solve. I have reinstalled it but nothing changed

The log says
![Atom error](https://user-images.githubusercontent.com/50331545/60761415-b9142600-a03f-11e9-8bc6-7f9e5e383a6a.png)

**Comment by pierreneter** [comment]
Can you open it with admin permission?

**Comment by gk65408** [comment]
yes i can but it shows same error

**Comment by 1170300812** [comment]
You can try to change environment variables or try to migrate your program to other paths to execute.

[How to do this](https://flight-manual.atom.io/using-atom/sections/basic-customization/#controlling-where-customization-is-stored-to-simplify-your-workflow)

**Comment by Arcanemagus** [comment]
Please try:
1. Closing all instances of Atom
2. Deleting the `C:\Users\Gurpreet\.atom\compile-cache` folder entirely
3. Starting Atom again

If that doesn't work please file a _new_ issue with the template correctly filled out.

Thanks for reaching out!

----

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
