### ISSUE TITLE
atom --version produces no output (Ubuntu snap)

### ISSUE THREAD

**Issue by mcandre** [atom/atom#19643]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

`atom --version` produces no command line output for debugging purposes.

### Steps to Reproduce

1. Run `atom --version`

**Expected behavior:**

The version number is displayed.

**Actual behavior:**

No content is emitted to either stdout or stderr. A zero value exit code is generated.

**Reproduces how often:**

Always

### Versions

Atom snap v1.38.2

Host: Ubuntu 19.04 Disco Dingo amd64

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

> Atom snap v1.38.2

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
