### ISSUE TITLE
atom --dev yields "nslog was compiled using a different version"

### ISSUE THREAD

**Issue by AxelJunker** [atom/atom#19646]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I am trying to run Atom in Dev Mode following [these instructions](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/). When I run `atom --dev` I get the following error:

```
Uncaught Exception:
Error: The module '/Users/junker/web/atom/node_modules/nslog/build/Release/nslog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/junker/web/atom/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/Users/junker/web/atom/node_modules/nslog/lib/nslog.js:15:4)
```
This is what I've tried:

- `script/clean` and `script/bootstrap` again

- Rebuilding with `npm rebuild` and [electron-rebuild](https://github.com/atom/node-keytar/issues/64#issuecomment-301621222).

- Using node versions 6, 7, 8, 9, and 10. Same error.

Also worth noting is that `script/bootstrap` takes about 10 min to complete.

### Steps to Reproduce

https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/

**Expected behavior:**
It runs

**Actual behavior:**
Get error

**Reproduces how often:**
100%

### Versions
macOS 10.14.3
Node.js 8.16.0 (but I've tried with 6, 7, 9, and 10 as well)
npm 6.4.1
Python v2.7.16
Command Line Tools for Xcode

**Comment by Arcanemagus** [comment]
The error is due to a mismatch in the Node.js versions used to compile the module. In this case it isn't your _system_ Node.js, but the one embedded in Atom itself. The current stable release of Atom bundles Node.js 8.9.3 while the beta (and `master`) bundle Node.js 10.2.0.

I'm assuming that you are trying to use `ATOM_DEV_RESOURCE_PATH`, which means you need to be running a compatible version of the Atom binary, either `atom-beta` or the result of running `script/build`.

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
