### ISSUE TITLE
Can't open file by typing path with keyboard

### ISSUE THREAD

**Issue by softwarecreations** [atom/atom#19653]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
Can't open a file by typing in the file path

### Steps to Reproduce

1. Press Ctrl-O
2. Try type in /etc/hosts press Enter
3. *See* that /etc/hosts has opened

I'm testing on KDE Plasma Ubuntu 18.04 but that's probably irrelevant.
The fileopen dialog that opens doesn't allow me to type in a filepath anywhere.

**Expected behavior:**
Look at KWrite for example
![image](https://user-images.githubusercontent.com/28704571/60964531-d8e36c80-a313-11e9-88fb-b88bd700eff1.png)

**Actual behavior:**
A fileopen dialog opens that's unusable via the keyboard. Extremely unproductive and tediously requires mouse-only operation.
![image](https://user-images.githubusercontent.com/28704571/60963269-a08e5f00-a310-11e9-945e-28d9a3ea9a7b.png)

**Suggested fix**
Fixing this should be trivial. KWrite (for example) shows a more useful (but standard) fileopen dialog that allows entering a path, so it's probably a trivial setting that needs to be changed.

**Reproduces how often:**
Always

### Versions
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
Ubuntu 18.04

Not sure if these are relevant
ii  plasma-desktop                                  4:5.12.7-0ubuntu0.1
libgtk-3-bin                                    3.22.30-1ubuntu3
libgtk2.0-bin                                   2.24.32-1ubuntu1
qt5-default:amd64                               5.9.5+dfsg-0ubuntu2.1
libqtgui4:amd64                                 4:4.8.7+dfsg-7ubuntu1

Similar to previously closed issue
https://github.com/atom/atom/issues/4777

**Comment by Arcanemagus** [comment]
The dialog you are seeing is coming from your OS, Atom has no control over what it looks like. It looks to me like Kwrite has created a custom file open dialog there, but I can't say for sure.

It _may_ be that there is a way to select some "better" dialog from the operating system, but if so that would unfortunately need to be changed within [Electron](https://github.com/electron/electron/), the platform Atom is built on.

It looks like you have a few options here:
* See if you can [enable this functionality in the OS file picker](https://askubuntu.com/questions/547688/default-to-showing-and-using-pathbar-in-ubuntu-file-dialogs)
* Check if there is an issue on your OS's bug tracker about the lack of functionality (by default?) in their file picker
* Use the [advanced-open-file](https://atom.io/packages/advanced-open-file) package linked in the other issue, or something similar
* Check if there is already an issue filed on Electron about this

Since it appears there isn't anything that can be done about this inside Atom itself, I'm going to close this issue. Thanks for taking the time to file an issue though!

**Comment by softwarecreations** [comment]
Thanks @Arcanemagus in the mean time I've installed and tested advanced-open file. It does indeed get the job done, quite well actually.

I don't think the file open dialog is specific to KWrite. It must be some standard thing.

For interest's sake here's what Pinta's file open dialog looks like:
![image](https://user-images.githubusercontent.com/28704571/60999331-32bb5500-a35b-11e9-9f7b-c59a3ce6ff65.png)

Interestingly also, sublime has the same crappy file open dialog as Atom.io is showing.

Furthermore, LibreOffice Writer has the exact same fileopen dialog style as KWrite, and the 2 pieces of software aren't related at all.
![image](https://user-images.githubusercontent.com/28704571/60999622-e290c280-a35b-11e9-8019-65bb546398f9.png)
