### ISSUE TITLE
Attempting to create a Range via the Atom API

### ISSUE THREAD

**Issue by ncurtislinkeng** [atom/atom#19656]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I am trying to use the "Range" feature in the API in an extension, but every time I create a range (using a Range Compatible Array) the start and end point of the range are both (0 , 0). This is preventing me from placing decorations where I want to. Also, better documentation on how to use the decoration feature of the TextEditor API would be greatly appreciated! Lastly, when I attempt to use the "Point" implementation of the API, Atom throws an error.

### Steps to Reproduce

1.)   Simply attempt to create a Range with a Range Compatible Array and see that the start and end are 
       both (0 , 0).

**Expected behavior:**

A Range with the appropriate bounds to be created.

**Actual behavior:**

A junk Range is created.

**Reproduces how often:**

100%

### Versions

Windows 10 and atom 1.38.2

### Additional Information

N/A

**Comment by Arcanemagus** [comment]
You haven't provided any example code, but I'm _guessing_ you haven't done `import { Range, Point } from 'atom'` in your package... meaning you are getting the [Range](https://developer.mozilla.org/en-US/docs/Web/API/Range) and [Point](https://developer.mozilla.org/en-US/docs/Web/API/Point) generic web APIs instead of Atom's implementation.

If that isn't the case I would recommend either posting to Discuss or joining the Slack instance and chatting in the `#packages` channel. Regardless of which direction you go without example code to look at it's unlikely anyone will be able to help you beyond the above.

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
