### ISSUE TITLE
It is not appropriate for a text editor to mangle files by default

### ISSUE THREAD

**Issue by loganmurray-infor** [atom/atom#19659]
## Summary

This is really just common sense, but an editor should not (by default) include any behavior enabled that can unexpectedly modify a user's file without their consent or knowledge.

## Motivation

To my absolute disbelief, I just checked my SVN diff and discovered hundreds of line endings changed in files that I opened in Atom only to modify one or two lines. This is absolutely inappropriate behavior for a text editor.

I'm talking of course about the whitespace package and its default settings of stripping whitespace from the end of lines, as well as inserting newlines at the end of files, as well as any other functionality that modifies a file without consent. Don't get me wrong, these are handy features to have in a text editor, but they can _not_ be enabled by default.

## Describe alternatives you've considered

Any such destructive features that you otherwise want to draw attention to could be either made more obvious in the main settings of the program, or configured by some initial setup questionnaire that gets consent from the user before enabling them.

A simple question can serve two purposes:

1. It lets the users know that the functionality exists, and
2. It requires the user to consent to the automatic modification of their files

## Additional context

I think we can all agree that a text editor should _never_ mangle a user's files without their knowledge or permission.

**Comment by rsese** [comment]
Thanks for the feedback - I think you may have seen it already but in case you haven't, this has been brought up and discussed before here:

https://github.com/atom/whitespace/issues/10

Though the issue is fairly old at this point, as far as I know the maintainers' position hasn't changed since then but I'll go ahead and share your feedback with the team.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
