### ISSUE TITLE
syntax theme

### ISSUE THREAD

**Issue by hopeinformer** [atom/atom#19669]
The original theme was perfect but now it change and nothing I do will change it back. All themes in the syntax editor result with the same window. It's difficult to view in this setting. Anything that is commented out has this highlight bar over the text. 
I'm using Ubuntu 19.04 OS
![syntax](https://user-images.githubusercontent.com/52873265/61178840-89b76900-a5ab-11e9-9a17-9126805904ad.png)

**Comment by Arcanemagus** [comment]
It's possible you modified your `styles.less` to cause that, or installed a package that is doing this.

Thanks for reaching out!

----

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
