### ISSUE TITLE
Ignored names doesn't accept .* as a valid input (to hide all files beginning with a '.', standard unix philosophy) 

### ISSUE THREAD

**Issue by lutzee** [atom/atom#1966]
Inputting ```.*``` into the Ignored Names setting does not read it as a valid wildcard for any files/folders beginning with a ```.``` 
In unix and things based off/designed around, files and folders beginning with a ```.``` are classed as hidden and by default should be hidden by things listing the directories unless they are explicitly told to list the hidden files. I'm not asking for this, but at least a way to achieve this, through the use of ```.*```. 

I believe the Ignored Names setting should be accept any form of wildcard, be it ```*.file```, ```*somefilename*``` or ```.*```. And currently believe that this is a bug in the system currently implemented.

**Comment by izuzak** [comment]
Seems like this was fixed in the meantime. Here's a GIF where I'm trying out various patterns with `*` -- notice how the list of files in the tree view changes as I update the ignored names config setting:

![ignore](https://cloud.githubusercontent.com/assets/38924/9845016/4fed0996-5ac8-11e5-97d3-56a8388a3e08.gif)

Let me know if you can still reproduce this and please provide an example. Thanks!
