### ISSUE TITLE
Overlay decorations wrapped in a div not displaying

### ISSUE THREAD

**Issue by ncurtislinkeng** [atom/atom#19666]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When I attempt to add a decoration that is wrapped in a div (to effectively create a tool tip),
it does not render in the workspace.

### Steps to Reproduce

1.  Run code akin to this:

`      var wrapper = document.createElement("div");
      wrapper.className += "tooltip";

      var message = document.createElement("span");
      message.className += "tooltiptext";
      message.innerText = err.Text;
      wrapper.appendChild(message);

      var toolTip = editor.decorateMarker(marker, {type: 'overlay', item: wrapper});`

**Expected behavior:**

A tool tip is displayed wrapped in a styled div.

**Actual behavior:**

No tool tip is rendered in the workspace.

**Reproduces how often:**

100%

### Versions

node 8.9.3 x64
atom 1.38.2
Windows 10

**Comment by Arcanemagus** [comment]
The element is definitely there, your issue is that you are applying the `tooltip` class to it, which is only intended for things like this tooltip:
![image](https://user-images.githubusercontent.com/427137/61072007-44d2dd00-a3c7-11e9-95e0-d8d4a3c16a36.png)

The problematic part of that class making it not show up in your use case is the `opacity: 0`:
![image](https://user-images.githubusercontent.com/427137/61072073-659b3280-a3c7-11e9-8fa9-b22169fb3c3c.png)

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
