### ISSUE TITLE
Bug in TextEditor::bufferPositionForScreenPosition(bufferPosition)

### ISSUE THREAD

**Issue by ncurtislinkeng** [atom/atom#19665]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
When ever I make this call as follows:

```js
'use babel';

import {Range, Point} from 'atom';

export default class ToolTipManager {
  constructor() {
    atom.views.getView(atom.workspace).addEventListener('mousemove', (event) => {
      this.OnMouseMove(event);
    });
  }

  OnMouseMove(event) {
    console.log(event);

    var activeEditor = atom.workspace.getActiveTextEditor();
    var markers = activeEditor.getMarkers();
    var screenPoint = new Point(event.screenX, event.screenY);

    console.log(screenPoint);
    console.log(activeEditor.bufferPositionForScreenPosition(screenPoint));

    console.log('\n');
  }
}
```

the function activeEditor.bufferPositionForScreenPosition returns a point of (0, 23) every time.

### Steps to Reproduce

1.  Copy and paste the above code and run it.

**Expected behavior:**

The point to be translated properly.

**Actual behavior:**

I get a junk point in return.

**Reproduces how often:**

100%

### Versions

atom 1.38.2 on windows 10

**Comment by Arcanemagus** [comment]
It sounds like you are confusing the [Point](https://developer.mozilla.org/en-US/docs/Web/API/Point) web API and [Atom's Point class](https://atom.io/docs/api/v1.38.2/Point). They are _very_ different things, in this particular case Atom's `Point` expects _character_ coordinates, not screen coordinates, and will clip the given values to the available ones in the document.

Is that accurate for what is going on here?

**Comment by ncurtislinkeng** [comment]
> It sounds like you are confusing the [Point](https://developer.mozilla.org/en-US/docs/Web/API/Point) web API and [Atom's Point class](https://atom.io/docs/api/v1.38.2/Point). They are _very_ different things, in this particular case Atom's `Point` expects _character_ coordinates, not screen coordinates, and will clip the given values to the available ones in the document.
> 
> Is that accurate for what is going on here?

May is ask what you mean by character coordinates? I'm trying to take my mouse's position in the atom workspace and convert it into the coordinates of my active text editor, if such a conversion is possible.

**Comment by Arcanemagus** [comment]
I mean exactly as it is described in the documentation that I linked:

The row (in lines within the document), and column (in characters within the document).

For example:
```
foo
bar
```

In that document `new Point(1, 2)` would represent the point just after the `a` in `bar`.

**Comment by ncurtislinkeng** [comment]
Oh okay, thanks for the clarification. So there exists no what to convert the workspace's mouse coordinates to a text buffer's coordinates?

**Comment by Arcanemagus** [comment]
Atom at its core doesn't prevent packages from doing _anything_, so there is definitely a way to do that... but you absolutely shouldn't be rolling your own method. Atom provides [DisplayMarker](https://atom.io/docs/api/v1.38.2/DisplayMarker)s for exactly this purpose, so the editor can handle that for you.

As I've told you several times in Slack, your best bet is to look at how one of the existing packages that already implement the functionality you are creating works. For example [here is how `linter-ui-default` does it](https://github.com/steelbrain/linter-ui-default/blob/c8c3e4be95e60c9657b75a824f8de321a3a27c44/lib/tooltip/index.js#L28-L36).

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
