### ISSUE TITLE
Trouble Trying to Install Atom

### ISSUE THREAD

**Issue by DrasTical** [atom/atom#19687]
Since I just installed Kali on my PC, my friends were telling me to install Atom in order to get anywhere, as it was extremely hackable. I tried to do that, following all the instructions at https://flight-manual.atom.io/getting-started/sections/installing-atom/ but it didn't work, and this happened.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 atom : Depends: gconf2 but it is not installable
        Depends: gconf-service but it is not installable
        Depends: gvfs-bin but it is not installable
E: Unable to correct problems, you have held broken packages.

Well, some people resolved this by getting the dependencies, but when I download them and  try it again, the same thing happens, (I'm probably doing everything wrong because I'm very new so don't judge me too much ;_;)

**Comment by tan10vir** [comment]
This question was raised in Reddit. Here's the link:
https://www.reddit.com/r/Atom/comments/8jvn99/help_cant_install_atom_on_kali_linux_unmet/

You can also install ``atom`` using ``snap`` as snaps don't have dependencies. 

```
sudo snap install atom --classic 
```

**Comment by Arcanemagus** [comment]
Unofficial distributions (like the `snap` one) are **_not_** supported, and are known to cause issues.

Since this is a Kali Linux question, and doesn't actually have anything to do with Atom directly I'm going to close this issue, it looks like @tan10vir already linked some instructions specific for that distribution to get you started.

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
