### ISSUE TITLE
Does Lockbot help or hurt the project?

### ISSUE THREAD

**Issue by wbt** [atom/atom#19680]
Lockbot recently visited [this issue](https://github.com/atom/atom/issues/18662) and autolocked it due to lack of recent activity.  

Whenever someone is coming to file a new issue, GitHub presents a popup to "Avoid opening an issue that may already exist by quickly scanning through related issues with similar titles and content." This is because duplicate issues are generally not good for the community.

The issue raised in [18662](https://github.com/atom/atom/issues/18662) is well documented there and continues to exist, continuing to cause the same friction and problems as when it was documented.  (The issue was closed WONTFIX without explanation even though reasoning was specifically requested.)  It would not surprise me at all if someone else came to file a duplicate of the same issue, but not do as thorough or quality a job of documenting it.  Even if they found the issue it duplicates, they can't add their voice to point out that this is an issue for them as well, nor can anyone add reasoning behind the WONTFIX decision, or easily find newly opened issues referencing that one.

How does the community benefit from this automatic locking?

**Comment by lee-dohm** [comment]
> How does the community benefit from this automatic locking?

It saves the maintainers and the community members time that would otherwise be spent on comments that are:

1. Unrelated to the actual issue (by forcing people to open new issues and follow the issue template, we get valuable information that helps us determine the root cause of what is going on)
1. Spam on old, closed issues that send out notifications to large lists of people
1. Necroing an old, resolved discussion that only the new person wants to continue but everyone else is done with
1. Emotional reactions to some comment in the issue but [don't take into account the entirety of the discussion](https://blog.codinghorror.com/because-reading-is-fundamental-2/)
1. Other stuff I've probably forgotten

The community further benefits from this in that because the maintainers time isn't spent on the above things, the maintainers can spend more time working to improve Atom.

For similar reasons, we have rules about requiring the issue template to be filled out and not answering questions in issues. If you would like to continue this discussion with me, please feel free to send an email to atom@github.com.

-----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by wbt** [comment]
>Because we treat our issues list as the Atom team's backlog, we close issues that are questions since they don't represent a task needing to be completed.

First, the [issue prompting this](https://github.com/atom/atom/issues/18662) is not a question.  It describes an actual problem in the UX which **can** be fixed by alterations to the code, follows the issue template, and does a good job of documenting the issue.  It may not be a priority for the Atom team to address, but if this were a truly open project, it should be open for others to contribute code which addresses issues the contributors believe are important to address, discuss its relative priority, and discuss whether it's a good idea to do at all or not. 

For example, an Issue saying "Store the important passwords file as plaintext" might generate a response like "current code behavior using encryption here is intentional and a good idea **because...** <reasons>," which in a meritocracy of ideas might persuade contributors that's not worth spending time on.  In such a case, a better technical solution might result, which addresses the reasons motivating the original post while also addressing the reasons behind the status quo.  

Just [saying](https://github.com/atom/atom/issues/18662#issuecomment-454632452) something like "we reached a decision that this should not be fixed, in a closed-door meeting for unknown reasons that we will not disclose" does NOT advance the conversation in a helpful way and is an illustration of how "open-source" projects core to development efforts are not truly open; see discussion on [this issue](https://github.com/trufflesuite/truffle/issues/2140) for more detail.

Using the "main" repository's issues list, unfiltered, as one specific team's backlog is another such illustration.  To exclude something from the core team's backlog while allowing others to find and fix issues they think of as higher priority, you could use a `coreteam-wontfix` label and add the [qualifier](https://help.github.com/en/articles/searching-issues-and-pull-requests#search-by-label) `-label:coreteam-wontfix` to your backlog display.  Then, hopefully, lockbot's behavior could be changed so that duplicates of good issues can be marked as such, references can be added, and issues that are important for contributors but not the Atom team might be discussed and resolved, even if on a slower timeframe than those that are a high priority for the core team.  Those actionable steps are tasks that could be completed under this Issue, if it were reopened.  *I suspect this issue probably won't be reopened, because Atom is not a truly open project and the Issue has already been quickly closed by a core team member seen as having the final word.  However, I still make this request anyway.*

Having a more open project would also benefit the community by encouraging community contributions beyond the Atom core team itself.  The current closed-door nontransparent decisionmaking, automatic shutting down of discussions, and other signs that this is not a truly open project, strongly discourage potential contributors.
