### ISSUE TITLE
Some emoji not rendering in 1.39

### ISSUE THREAD

**Issue by chrisdrackett** [atom/atom#19693]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

In atom 1.38 the following text:

`// 🧮 Context`

is rendered like this:

![1.38 example](https://cl.ly/5b40f46d55c4/Screen%20Shot%202019-07-23%20at%209.51.17%20AM.png)

however in 1.39 I get the following rendering:

![1.39 example](https://cl.ly/a480f5f2fee4/Screen%20Shot%202019-07-23%20at%209.53.05%20AM.png)

I know that some other emoji work, and I didn't test extensively to see if any others are missing.

### Steps to Reproduce

1. type or paste `🧮` into an editor

**Expected behavior:**

🧮 is displayed

**Actual behavior:**

a "unknown character" box is displayed

**Reproduces how often:**

100%

### Versions

Atom    : 1.39.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

### Additional Information

This is on the Mac OS version of atom. I did not check other versions.

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce with 1.39.0 on macOS 10.14 by pasting 🧮and also confirmed it works on 1.38.

**Comment by rsese** [comment]
Just adding that it looks like it's not all emoji causing the problem - for example, copying the Smileys section from https://getemoji.com/:

![emoji-1.39.0](https://user-images.githubusercontent.com/734194/61731977-362ee300-ad42-11e9-8fae-5d75b413f8bd.png)

**Comment by chrisdrackett** [comment]
good call, my title wasn't very clear!

**Comment by jasonrudolph** [comment]
> I can reproduce with 1.39.0 on macOS 10.14 by pasting 🧮and also confirmed it works on 1.38.
> 
> Doesn't reproduce on 1.41.0-nightly1.

Based on these findings, this appears to be a known issue with Electron 3.  (https://github.com/electron/electron/issues/11874)

- ✅ This issue is not present in Atom 1.38, which uses **Electron 2**.
- ✅ This issue is also not present in Atom 1.41.0-nightly1, which uses **Electron 4**.
- ❌This issue seems to be limited to Atom 1.39.0 and 1.40.0-beta0 which both use **Electron 3**.

The Electron team [recommends](https://github.com/electron/electron/issues/11874#issuecomment-434161482) upgrading to Electron 4 to resolve this issue. Given the complexity of an Electron upgrade, it's unlikely that we'll be able to fix this issue for Atom 1.39 and 1.40. Instead, we'll likely need to wait for Atom 1.41 for this issue to be resolved.

In the meantime, if you're affected by this issue, using the [Atom Nightly channel](https://atom.io/nightly) might provide a workaround for you until Atom 1.41 is officially released.

**Comment by karlschwaier** [comment]
Beside the emoji issue you can also see that the text is now rendered bolder than before.

**Comment by chrisdrackett** [comment]
@karlschwaier i believe that is related to: https://github.com/atom/atom/issues/19356
