### ISSUE TITLE
Broken package atom-1.39.0-0.1 for CentOS 7

### ISSUE THREAD

**Issue by GRArmstrong** [atom/atom#19690]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
The build of Atom (v1.39.0-0.1) for CentOS 7 is broken.

No error is reported unless running with option `-f` in which case the output is:
```
$ atom -f
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:15:4)
```

The binary has been built against GLIBCXX_3.4.21 which isn't available for CentOS 7.

```
$ strings /usr/lib/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

### Steps to Reproduce

1. Add the Atom repo as described here: https://linuxize.com/post/how-to-install-atom-text-editor-on-centos-7/
2. Install atom with `$ sudo yum install atom`
3. Attempt to launch Atom with `$ atom`

**Expected behavior:**

Launch Atom

**Actual behavior:**

Failure to launch Atom 

**Reproduces how often:**

100% of the time

### Versions

Affecting **atom-1.39.0-0.1.x86_64**

### Additional Information

Current workaround is to downgrade `$ sudo yum downgrade atom-1.38.2-0.1`

**Comment by jasonrudolph** [comment]
@GRArmstrong: Thanks for reporting this issue.

I'm able to reproduce this issue on a CentOS 7 VM, and it seems like Oracle Linux 7.6 has this problem as well (https://github.com/atom/atom/issues/19682). We're looking into a resolution. In the meantime, I recommend that affected users do two things:

1. Follow your workaround to downgrade to Atom 1.38.2:

    `sudo yum downgrade atom-1.38.2-0.1`

2. Subscribe to this issue so that you'll be notified when it gets resolved

**Comment by cdmackay** [comment]
"sudo yum downgrade" will downgrade to the previously installed version, on any RPM distro, where the actual versions may be different between distros (e.g Centos vs OL). That's only helpful if your previous version was the working one, of course :)

**Comment by jasonrudolph** [comment]
This problem appears to have been introduced as part of a recent change to the build system for Atom's Linux builds. For Atom 1.39.0-beta2 and earlier, Linux builds were [produced on Ubuntu Trusty (14.04)](https://github.com/atom/atom/blob/v1.39.0-beta2/.travis.yml#L18) on Travis CI. Starting with Atom 1.39.0-beta3, Linux builds were [produced on Ubuntu Bionic (18.04)](https://github.com/atom/atom-docker-ci/blob/00328f18ea06d6474aa3685f8e2a746f6e125971/Dockerfile#L1) running in a Docker container on Azure Pipelines. <sup>†</sup>

As far as I know, this change in Ubuntu versions was not intentional. Rolling back to the previous build system would be a significant undertaking, so we're looking into our options for resolving this problem.

---

**†** The Azure Pipelines build for Atom [runs in an Ubuntu 16.04 VM](https://github.com/atom/atom/blob/v1.39.0-beta3/script/vsts/platforms/linux.yml#L8-L12), but it uses an [Ubuntu 18.04](https://github.com/atom/atom-docker-ci/blob/00328f18ea06d6474aa3685f8e2a746f6e125971/Dockerfile#L1) Docker container to perform the build.

**Comment by jasonrudolph** [comment]
:wave: @GRArmstrong: I think we've got a fix for this issue. You can find an rpm with the proposed fix at https://github.visualstudio.com/Atom/_build/results?buildId=46092&view=results:

<img width="1052" alt="screenshot" src="https://user-images.githubusercontent.com/2988/61814920-203f2200-ae17-11e9-9378-ef2c3826fcda.png">

Would you mind trying it out and letting us know if it resolves the issue for you? If it does, then we'll publish a new release with this fix.

**Comment by bdelepine** [comment]
@jasonrudolph It worked for me. Thanks!

**Comment by jasonrudolph** [comment]
Thanks, @bdelepine!

Atom 1.39.1 and 1.40.0.beta1 are out now with this fix, so I'm going to close out this issue.
