### ISSUE TITLE
Error fetching from carbon: 401 - Unauthorized

### ISSUE THREAD

**Issue by amirhosseinhpv** [atom/atom#19697]
[Enter steps to reproduce:]

1. Select Code
2. Choose Carbon menu from Packages
3. You get nothing but this silly error!

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Error fetching from carbon: 401 - Unauthorized

```
At undefined

undefined
```

### Commands

```
     -0:09.6.0 carbon:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autoclose-html 0.23.0 
block-comment-plus 0.5.1 
busy-signal 2.0.1 
carbon 0.3.1 
carbon-now-sh 2.0.3 
change-case 0.6.5 
code-stats-atom 2.0.6 
color-picker 2.3.0 
devmind-beautifier 1.3.0 
figletify 0.2.2 
file-header 1.13.9 
file-icons 2.1.33 
file-path-picker 1.0.0 
highlight-selected 0.16.0 
html-entitize 1.1.0 
intentions 1.1.5 
language-autoit 0.2.1 
linter 2.3.0 
linter-php 1.6.1 
linter-ui-default 1.7.1 
open-recent 5.0.0 
pigments 0.40.2 
pretty-json 2.1.2 
remote-ftp 2.2.2 
svg-preview 0.14.0 
sync-settings 0.8.6 
uglify-html 2.0.0 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [carbon](https://atom.io/packages/carbon) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
