### ISSUE TITLE
Can't type pipe character using PHP and HTML grammar

### ISSUE THREAD

**Issue by vertigofactory** [atom/atom#19691]
Hi, while working on PHP and HTML files in Atom editor I can't type the pipe character. 

When I press `|` Atom shows `>`.

If I switch to a different grammar (eg. JavaScript) it works without any hassle.

Opening the developer console and typing:
`document.addEventListener('keydown', e => console.log(e), true)`

this is the output when I press "|":
`KeyboardEvent {isTrusted: true, key: "|", code: "Backquote", location: 0, ctrlKey: false, …}`

Any idea? Thank you!

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

From the information you provided you might want to include what you see from the [Keybinding Resolver](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings) when you press `|` in the situation where it doesn't work. Make sure you follow the instructions in the template while filling it out to try Safe Mode as well.

Thanks for understanding and meeting us halfway :grinning:
