### ISSUE TITLE
Node upgrade to 10.2.0 between 1.38.2 and 1.39.0?

### ISSUE THREAD

**Issue by demogorgonzola** [atom/atom#19705]
There seems to be an upgrade from node version ```8.9.3``` to ```10.2.0``` which Atom uses that is causing ```atom-ide-ui```'s terminal to crash, since it has no prebuilts for ```pty``` that constitute ```NODE_MODULE_VERSION = 64```.

Also looking at the source between the releases there doesn't seem to be any explicit changes to the node version either.

Was this an intentional change?

Currently running on Ubuntu 18.04 with atom version ```1.39.0```

**Comment by Arcanemagus** [comment]
Node.js comes from the platform Atom is built on: Electron. The upgrade was done in https://github.com/atom/atom/pull/19419, you can see the details there.

You'll need to rebuild any native modules that don't include a pre-built binary for your system.

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
