### ISSUE TITLE
{... operator not working in Atom, working fine in StackOverflow

### ISSUE THREAD

**Issue by Sarah-Kaybee** [atom/atom#19708]
See my code here: https://stackoverflow.com/questions/57219770/spread-operator-not-working-javascript

Every time I try to run this code in Atom, I get "unexpected token" at { ... person }. It doesn't expect the . after the {. But the code runs fine elsewhere.

Please help me out with this. I am trying to learn NodeJS using Atom. I copy-pasted the code directly from the text editor. It's not a problem with Linter like some has suggested (I've tried multiple) nor a problem with .jshintrc esversion (again, I've tried all after 6). 

It should also be noted that fast-ESLint says there's an error in the first line of my code and two other errors, but there clearly isn't.

**Comment by idoo** [comment]
@Sarah-Kaybee could you specify where are you trying to run this code?

**Comment by Arcanemagus** [comment]
Thank you for reaching out!

Because Atom doesn't run code as it's an editor, it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

Note that for programming help places like StackOverflow or your classmates are your best bet for help. Since you mention JSHint I would highly recommend you look into ESLint instead as it is a far better linter ([Getting Started guide](https://eslint.org/docs/user-guide/getting-started)).

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
