### ISSUE TITLE
integrated terminal does not show up (Windows)

### ISSUE THREAD

**Issue by vladcenan** [atom/atom#19702]
I tried with lots of versions but on windows, any integrated terminal it's not starting any windows CLI (powershell, cmd, gitbash); it's just hanging.
Atom version: 1.39.0
![tokamak_terminal_issue](https://user-images.githubusercontent.com/3841211/61847937-179d2900-aeb5-11e9-93f6-2b080eb12c44.jpg)

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [tokamak-terminal](https://atom.io/packages/tokamak-terminal) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
