### ISSUE TITLE
Editor crash while installing julia-client from uber-juno on macOS 10.14.6

### ISSUE THREAD

**Issue by mrkite92** [atom/atom#19709]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Editor crash

### Steps to Reproduce

1.  Install uber-juno
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

 100 %

### Additional Information
Crash report attached
[Atom Helper_2019-07-26-164641_macprojb.crash.gz](https://github.com/atom/atom/files/3436279/Atom.Helper_2019-07-26-164641_macprojb.crash.gz)

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://github.com/JunoLab/uber-juno package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
