### ISSUE TITLE
1.39 has crippled Nuclide's OmniSearch for filenames (based on folders?)

### ISSUE THREAD

**Issue by stowball** [atom/atom#19718]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * N/A Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * [X] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * [X] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * [X] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * [X] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I still use Nuclide because its OmniSearch is the best thing ever. Unfortunately, after upgrading from 1.38.2 to 1.39.1, it can no longer find many files, especially when searching by folders for files called `index.js`.

### Steps to Reproduce

1. Create a project with the following folders: foo, bar, baz
2. Create an index.js file in each of these
3. Open Nuclide's OmniSearch (typically Cmd+T) or Filenames (Cmd+Option+T)
4. Type `foo`
5. Type `bar`
6. Type `baz`

**Expected behavior:**

The index.js file matching the relevant folder should be returned, as it used to (like the normal Fuzzy Finder does)

**Actual behavior:**

No results.

**Reproduces how often:**

Every time you try and search based on folders, which is the entirety of my codebase.

### Versions

Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [nuclide](https://nuclide.io/) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. Unfortunately for you Facebook has abandoned the `nuclide` codebase so it's unlikely they will be fixing whatever issue there is in their package. Note that in Atom v1.37.0 there was a [dramatic increase in fuzzy-finder performance](https://blog.atom.io/2019/05/12/atom-1-37.html#dramatic-fuzzy-finder-performance-boost), you might want to check it out 😉.
