### ISSUE TITLE
Atom replace my work by my old work in a distant server, after white page

### ISSUE THREAD

**Issue by Raf-sns** [atom/atom#19729]
Atom planted on a blank screen and replaced my work on a remote server registered for one hour by the old code present at the opening on the remote server. For some time Atom crash and replace all my files by old files already modified and saved on the server. The most disturbing is that it replaces alone files that are on a remote server ... I work with ftp-remote, it's amazing, if I worked locally I would understand but there on a remote server ... I I am terrified because I am working on a very complex application but I also have 8 to 10 servers connected permanently to Atom ... I used Atom not because it is free but because the adorais ... But there Atom looks like a big malware that will change alone remote files ?? - I code big applications in JS / PHP, I work on big projects and since I'm worried that he has modified other files on other servers ... Simply amazing !!

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
