### ISSUE TITLE
change the color of links in comments

### ISSUE THREAD

**Issue by rpalloni** [atom/atom#19722]
Hi,
I tried to change the color of links in comments in the stylesheet with this code but nothing is happening

.editor .markup.underline.link.hyperlink {
  color: #F9EE98;
  text-decoration: underline;
}

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
