### ISSUE TITLE
Maximum number of lines capped at 1597830?

### ISSUE THREAD

**Issue by raysanders** [atom/atom#19739]
Attempting to open csv's or similar flat text files with several million lines.  
The files open fine with vim, however atom cuts the text files off after just under 1.6 million lines. 

Is there a "max_lines" config setting that can be overridden? 1.6 million lines seems a bit low for a modern text editor.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

-----

No, there isn't a configuration value that can be changed.
