### ISSUE TITLE
Atom crashing when Package Manager is opened

### ISSUE THREAD

**Issue by zabimalik098** [atom/atom#19730]
Atom keeps on crashing as I open Package Manager in it

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by zabimalik098** [comment]
So what's the fix. Or how to get it fixed?
Should I download earlier version?

**Comment by Arcanemagus** [comment]
You haven't given us enough information to understand your problem, much less offer any potential solutions. Please follow the instructions to file a new issue with the template, that you removed here, **completely** filled out, making sure you try the suggested steps in it.
