### ISSUE TITLE
path.extname is deprecated.

### ISSUE THREAD

**Issue by evilover** [atom/atom#19743]
Argument to `path.extname` must be a string
```
path.extname (C:\Users\lenovo\Desktop\atom-x64-windows\Atom x64\resources\app.asar\src\electron-shims.js:20:10)
ATPOutputView.getCwd (C:\Users\lenovo\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:1874:17)
BuiltinVariables.parseFull (C:\Users\lenovo\.atom\packages\atom-terminal-panel\lib\atp-builtins-variables.coffee:188:77)
BuiltinVariables.parseHtml (C:\Users\lenovo\.atom\packages\atom-terminal-panel\lib\atp-builtins-variables.coffee:111:16)
ATPOutputView.parseTemplate (C:\Users\lenovo\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:664:36)
ATPPanel.updateStatusBar (C:\Users\lenovo\.atom\packages\atom-terminal-panel\lib\atp-panel.coffee:190:50)
```

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
