### ISSUE TITLE
UncaughtException: TypeError: Cannot read property 'getProp' of undefined. Restarting Server...

### ISSUE THREAD

**Issue by chengheai** [atom/atom#19750]
When I write javascript-vue code, the error pops up in the upper right corner of the atom. Why?

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

I'm assuming you can't reproduce in safe mode?  Also, based on the error message I might guess that you're using atom-ternjs?  If so, you might want to check out this issue: https://github.com/tststs/atom-ternjs/issues/328.
