### ISSUE TITLE
Can't scroll through file selector

### ISSUE THREAD

**Issue by adam-kelsey** [atom/atom#19751]
This is a little odd to explain so I will try my best...

Whenever I open a project in atom, and I start to go to navigate through the folders and files to get to the correct file I need, the scrollbar and scroll ability suddenly disappears. When I get to the first file that I need and there are enough folders open to cause a horizontal scrollbar to appear, the scrolling ability suddenly stops. Like I can't scroll up and down in the file navigator using the mouse scroll wheel or the scrollbar as the scrollbar disappears.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

--

In particular, it's always helpful to know what operating system you're running, what specific version of Atom you're on, can you reproduce in safe mode, detailed step-by-step repro steps, etc.

If you can open a new issue with the template filled out, we can take a look with you.
