### ISSUE TITLE
Atom's GUI is not displaying/appearing blank.

### ISSUE THREAD

**Issue by Wookolentze** [atom/atom#19769]
Hi guys, I need your help,

For some reason Atom's GUI is not displaying properly. I could interact with it yet is not displaying, so I cannot see what I am doing. Additionally,  when I open Windows Task Manager there is sub process that is appearing and disappearing so fast that I cannot do anything but observe the issue. I am experiencing the exact same issue with Visual Code Studio, but not with Brackets nor Sublime.  (the issue coincided with installation of Media Player Classic and some codecs-maybe no relation) I really prefer using Atom, and would like to get to the bottom of this, please give some suggestions? (I tried updating drivers for Intel HD graphics 3000 and NvidiaQuatro 1000M and Intel, but it is still the same). Thanks for looking into this, cheers.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Have you tried any of the [debugging suggestions](https://flight-manual.atom.io/hacking-atom/sections/debugging/) linked to from the `Prerequisites` section of the issue template like safe mode?

In particular, since you're seeing the same issue in VS Code go ahead and try this section and see if disabling your GPU when running Atom helps: https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem.

**Comment by Wookolentze** [comment]
Hi rsese, I finally resolved the issue. When my laptop overheats it somehow triggers graphic card to switch from nVidia to Intel. So I just had revert to appropriate driver, and than disable the switch. Thanks
