### ISSUE TITLE
[Arch Linux] electron4 / libevent-2.1.so.7 - Can't open atom or check atom version

### ISSUE THREAD

**Issue by MrPop2213** [atom/atom#19768]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When attempting to run atom via `atom` `atom --safe` `atom --clear-window-state` etc. I get `/usr/bin/electron4: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory` and atom doesn't open.
Running `atom --version` does not display any error, version information, etc.

### Steps to Reproduce

1. Run atom

**Expected behavior:**

Atom opens

**Actual behavior:**

Error: `/usr/bin/electron4: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory`
`

**Reproduces how often:**

100% of the time

### Versions

pacman (via `pacman -Qi package_name`) states that my atom version is 1.39.1-1, my electron4 version is 4.2.8-2, and my libevent version is 2.1.10-1

**Comment by Aerijo** [comment]
The pacman package is not official, and is using a different major version of Electron to what is currently intended.
________
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
