### ISSUE TITLE
Atom editor 1.39.1 x64 fails to install packages

### ISSUE THREAD

**Issue by Souravgoswami** [atom/atom#19775]
### Description
Atom editor crashes when trying to install packages...

### Steps to Reproduce

1. Open Atom
2. Install Packages

**Expected behavior:**
![err](https://user-images.githubusercontent.com/37468605/62826263-fa1acf80-bbd5-11e9-9b95-cf32fe6a330c.png)

### Versions
```
atom --version
```
Atom    : 1.39.1
Electron: 4.2.8
Chrome  : 69.0.3497.128
Node    : 10.11.0

### Installation Source
I have installed it from the Arch Linux community repository.

**Comment by rsese** [comment]
Thanks for the report!

> Atom : 1.39.1
> Electron: 4.2.8

Based on these versions, we've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
