### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by flov3rh** [atom/atom#19782]
Hello, I am not really sure which one is the issue here. 

![image](https://user-images.githubusercontent.com/42297973/62989493-db068280-be0d-11e9-969c-f4b4577c9264.png)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
