### ISSUE TITLE
How to assign double commands in a key

### ISSUE THREAD

**Issue by Mackenzil** [atom/atom#19785]
For instance, how can I assign control-j Backspace and Enter?

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

If you post on Discuss, feel free to @ mention me and I can try to help - I think you can do this with a small bit of code in your [init file](https://flight-manual.atom.io/hacking-atom/sections/the-init-file/) along with a new keybinding for <kbd>Ctrl-j</kbd> in your [keymap](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/).
