### ISSUE TITLE
bottom of editor : kite icon shifted after disabling it

### ISSUE THREAD

**Issue by ccppoo** [atom/atom#19791]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

icon at the bottom of atom is wierd
![image](https://user-images.githubusercontent.com/46418312/63080798-fcd24780-bf7c-11e9-8889-7cc14a250982.png)

### Steps to Reproduce

1. installed python-autocomplete
2. disabled kite (because of aggressive auto complete, e.g) print([val], [...]) pops up every time)

**Expected behavior:**

icons should be shown horizontally 

**Actual behavior:**

it's squeezed

**Reproduces how often:**

some times

### Versions

Atom : 1.40.0
Edition : windows home 10
Version : 1903
OS Build : 18362.267

### Additional Information
None

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the https://github.com/kiteco/atom-plugin package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

---

My guess is the issue with https://github.com/kiteco/atom-plugin since with other packages  (e.g. the GitHub package or Teletype), any icons added to the status bar are removed when the package is disabled.  But again though, if the package maintainers think it's an Atom issue, they can let us know where the issue is or help with a fix.
