### ISSUE TITLE
Atom still requires python 2.7 to build

### ISSUE THREAD

**Issue by Nathan-Furnal** [atom/atom#19794]
Hi there,

Atom 1.40 still requires python 2.7 to build and it's basically the sole application forcing me to have python 2.x on my clean system (Ubuntu 19.04) for now.

Is there any option to update to python 3.x ?

Thanks

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

From past discussions my understanding is that this dependency comes from node-gyp's dependency on Python 2.7 (e.g. see https://github.com/atom/atom/commit/596fe5fae3adc369eaad145ad274371a3d04e087#commitcomment-26986619).

Not sure about any recent information or details about the situation though but as referenced above, the best place to talk about topics like that would be the Atom Slack.
