### ISSUE TITLE
I need a save button visable at all times so i dont have to use menus!

### ISSUE THREAD

**Issue by jamieduk** [atom/atom#19822]
I need a save button visable at all times so i dont have to use menus!
Also require auto save features and customisble timings for auto save! want to also be abe to change the font and have spell checker features and even code syntax checking options (on and off features for all these things is a good thing too)!

**Comment by lee-dohm** [comment]
Thank you for the suggestion!

That does sound like an interesting idea for a package :+1: Unfortunately, the Atom maintainer team is already full up handling all of the support and maintenance of the current core packages. There are a couple options:

* Someone may have already created this and we're not aware of it. Have you searched [the Atom package registry](https://atom.io/packages/) or [Atom theme registry](https://atom.io/themes/)?
* You can post a message on [Discuss, the official Atom and Electron message board](https://discuss.atom.io/c/packages) to see if anyone from the community is willing to try and build it

In any case, because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). But I'm also going to label this with `package-idea` so that others searching for suggestions here can find this.

Thanks again for your interest in Atom :grinning:
