### ISSUE TITLE
Unable to create custom set of actions

### ISSUE THREAD

**Issue by JPUnD** [atom/atom#19827]
Hi there,

After searching around i've seen a huge number of issues pop up about atom being unable to map several actions to the same keybinding by using the `keymap.cson` file, so after a while i found an answer that wasn't outdated from [this post](https://stackoverflow.com/a/56888588) on stackoverflow.

Using that same stackoverflow answer i tried to make my own command, that was able to toggle tree-view focus twice - because since a package that i have installed to switch between projects the cursor loses focus, so i must focus on the tree-view, then focus on the editor again and close the tree-view to get my default view.

So after reading that answer, this is my `init.coffee` located in `~/.atom`:
```
atom.commands.add 'atom-editor', 'custom:get-focus', ->
atom.commands.dispatch(atom.workspace.element, 'tree-view:toggle-focus')
atom.commands.dispatch(atom.workspace.element, 'tree-view:toggle-focus')
atom.commands.dispatch(atom.workspace.element, 'tree-view:toggle')
```

And this is my `keymap.cson`:
```
'atom-editor':
  'ctrl-alt-m': 'custom:get-focus'
```

This, however, doesn't do anything at all.
Hopefully i'm not missing anything obvious and i must say that the documentation on this part is not so obvious and i really wish a simpler syntax were available to map several commands to a keybind in atom directly from keymap.cson

Thanks in advance!

> System:
OS: Linux 4.19.66-1-MANJARO x86_64
WM: i3 
Atom: 1.39.1
Electron: 4.2.8
Chrome: 69.0.3497.128
Node: 10.11.0

**Comment by Arcanemagus** [comment]
CoffeeScript is a whitespace based language, as such your `init.coffee` is [currently translating into](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=true&loose=false&evaluate=true&stage=full&code=atom.commands.add%20'atom-editor'%2C%20'custom%3Aget-focus'%2C%20-%3E%0D%0Aatom.commands.dispatch(atom.workspace.element%2C%20'tree-view%3Atoggle-focus')%0D%0Aatom.commands.dispatch(atom.workspace.element%2C%20'tree-view%3Atoggle-focus')%0D%0Aatom.commands.dispatch(atom.workspace.element%2C%20'tree-view%3Atoggle')):
```js
atom.commands.add('atom-editor', 'custom:get-focus', function() {});
atom.commands.dispatch(atom.workspace.element, 'tree-view:toggle-focus');
atom.commands.dispatch(atom.workspace.element, 'tree-view:toggle-focus');
atom.commands.dispatch(atom.workspace.element, 'tree-view:toggle');
```

You'll either need to change over to `init.js`, or fix the indentation 😉.

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by JPUnD** [comment]
Given that this is not an issue, i've made a [post on atom discussion forums](https://discuss.atom.io/t/cant-create-a-custom-set-of-actions/67858/4) because putting that exact script in my `init.js` didn't work, hopefully you can move this discussion there and give me a hand because nothing i've tried so far seems to work, so i'm thinking this might be something deeper and it's not running the init at all since somebody else suggested me to try something else, which should have put a few commands in my menu bar, and nothing happened.

Thanks for the help anyways tho!
