### ISSUE TITLE
Duplicate run atom.exe (window)

### ISSUE THREAD

**Issue by Routhgen** [atom/atom#19829]
### Steps to Reproduce

1. Start Atom and open some file doesnt matter. 
2. Open file from diff folder or from FTP/SFTP connection (file is downloaded to some cached temp folder of commander)
3. Voila its gonna start new Atom without any reason (bug)

**Expected behavior:**

Open file in actual and only one window, like it works in EVERY IDE!

**Actual behavior:**

starts duplicate session of Atom! New window.

**Reproduces how often:**

Everytime opens new file from FTP/SFTP connection, or diff folder than first file is opened

### Versions

W10, Atom 1.40.1 x64

Why is this stupid bug still present? Over 5 years?
Its still the same issue like here: [https://github.com/atom/atom/issues/1722](url)

Hope dev team is able to fix this bug.

**Comment by rsese** [comment]
It looks like the `Prerequisites` section of the issue template is removed, please fill that out when opening issues and don't remove it - is the behavior reproducing in safe mode?

> * Start Atom and open some file doesnt matter.

Can you please be more specific here?  When you start Atom, do you have a project open or is this an empty Atom window before you open a file?

> * Open file from diff folder or from FTP/SFTP connection (file is downloaded to some cached temp folder of commander)

...

> starts duplicate session of Atom! New window.

I can't reproduce with 1.40.1 on Windows 10.  With 2 separate directories /a and /b and performing these steps:

1. Start Atom with an empty window
2. Open /a/test.xt with <kbd>Ctrl+O</kbd>
3. Open /b/test.xt with <kbd>Ctrl+O</kbd>

The file from step 3 is opened in the same window as the file from step 2.

If I change step 1 so I start Atom and have a project open (say project directory /a), if I then open /b/test.txt from that window with <kbd>Ctrl+O</kbd>, that file opens in the same window.

If you have a project open and then want to open another project in the same window, in that case you should use `Add Project Folder` (<kbd>Ctrl-Shift-A</kbd>) rather than `Open Folder` (<kbd>Ctrl+Shift+O</kbd>).
