### ISSUE TITLE
Installing any package in APM results in a stack overflow

### ISSUE THREAD

**Issue by thetakodev** [atom/atom#19830]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Every time I try to install a package, APM crashes with a Maximum call stack size exceeded error

### Steps to Reproduce

1. Start installing a package
2. Wait a bit

**Expected behavior:**

Get a package that can be deleted through APM, and be able to use it.

**Actual behavior:**

Get an "installed" package, which cant be deleted (other than by deleting its folder from .atom/packages/ and a Maximum call stack size exceeded error

**Reproduces how often:**

100%

### Versions

atom --version
```
Atom    : 1.39.1
Electron: 4.2.8
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

apm --version
```
apm  2.4.2
npm  6.11.1
node 11.15.0 x64
atom 1.39.1
python 2.7.16
git 2.23.0
```
neofetch --stdout
```OS: Arch Linux x86_64 
Host: Latitude E6430 01 
Kernel: 5.2.9-arch1-1-ARCH 
Uptime: 1 hour, 40 mins 
Packages: 637 (pacman) 
Shell: zsh 5.7.1 
Resolution: 1366x768 
DE: i3 
Terminal: urxvt 
CPU: Intel i5-3320M (4) @ 3.300GHz 
Memory: 2526MiB / 11958MiB 
Disk (/): 11G / 442G (3%) 
```

### Additional Information

I tried reinstalling atom. Didn't help.
Installed package from:
https://www.archlinux.org/packages/community/x86_64/atom/

**Comment by thetakodev** [comment]
![2019-08-23-101543_687x265_scrot](https://user-images.githubusercontent.com/32229391/63577496-cacd7080-c58e-11e9-9855-73972cc94377.png)

**Comment by rsese** [comment]
Thanks for the report!

> Atom    : 1.39.1
> Electron: 4.2.8

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
