### ISSUE TITLE
Atom keep hanging after editing JSON and css

### ISSUE THREAD

**Issue by syednoor6208** [atom/atom#19833]
Atom get hanging after editing more than 100 kb files with extension as  .JSON and .CSS 

ATOM VERSION :1.39.1

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

In addition to filling out the template, if you can share a specific file where you see this behavior, that would be helpful so we can test with it.

> ATOM VERSION :1.39.1

The latest stable release version of Atom is 1.40.1 - go ahead and update and see if that makes any difference as well.
