### ISSUE TITLE
Atom makes unhidden files hidden with Gnome

### ISSUE THREAD

**Issue by ITwrx** [atom/atom#19847]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom is not working properly with hidden files in Gnome Files (Nautilus). Atom (or something) is changing "show hidden files" to "don't show hidden files"(unchecked) when accessing the directory containing shown hidden files from Atom. The option is actually unchecked in Gnome Files after simply navigating to the directory in the file open dialogue in Atom, if you can believe that. :)

### Steps to Reproduce

1. 
Get yourself an Arch Linux computer or maybe any Gnu+Linux distro with nautilus 3.32.3-1.
2. 
set a directory that contains dot files (like ".env") to "show hidden files" in nautilus file manager/browser.
3. 
try to open any revealed hidden file from Atom. It won't be shown in "open" dialogue. Cancel the "open" operation. Navigate back to the directory in Nautilus and now you will find the "show hidden files" option has been unchecked!
**Expected behavior:**

I expect that i can open, edit and save the revealed file without Atom (or something) changing settings in Nautilus.
**Actual behavior:**
Atom can't "see" the file and somehow Nautilus file visibility settings are modified.

**Reproduces how often:**

every time.
### Versions

Atom 1.39.1
ArchLinux
nautilus 3.32.3-1
### Additional Information

Does not happen with gedit or geany.

**Comment by Arcanemagus** [comment]
> You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line.

Could you please post the full version information as requested in the issue template? Thanks!

**Comment by ITwrx** [comment]
atom --version
Atom    : 1.39.1
Electron: 4.2.8
Chrome  : 69.0.3497.128
Node    : 10.11.0

apm  2.4.2
npm  6.10.3
node 11.15.0 x64
atom 1.39.1
python 2.7.16
git 2.22.0

BTW, i read the issue template and tried to oblige, but the part about getting version info is ambiguously worded. It just asks for "Versions" and then says i *can* get that info from running the aforementioned commands. Since i had the atom version already i didn't know i needed more software version info. Rewording that might save devs from having to clarify. If devs need the output of specific commands, consider just asking for that explicitly.

thanks

**Comment by Arcanemagus** [comment]
```
Atom : 1.39.1
Electron: 4.2.8
```

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
