### ISSUE TITLE
Not working scroll

### ISSUE THREAD

**Issue by kotko** [atom/atom#19848]
earlier.
when you do a search for a project, you open some kind of result. and then again return to the search page.
then the scroll remains at the place where you clicked. now it just folds up

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
