### ISSUE TITLE
The line in the middle of the editor shouldnt be default

### ISSUE THREAD

**Issue by asdf337** [atom/atom#19872]
That big ugly line in the middle of the editor shouldnt be on by default, it should be OFF.

**Comment by lee-dohm** [comment]
Thanks for the feedback. We disagree and we'll be leaving the default the way it is.

Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
