### ISSUE TITLE
Atom starts but the window is blank

### ISSUE THREAD

**Issue by Dr-Mart** [atom/atom#19885]
Im using elementary os 5.0 and when I´m staring atom the window open but with no UI. I reinstalled it a coupel times but it didn´t work. Thanks in advance.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
