### ISSUE TITLE
Will Atom ever make use of Web Assembly ?

### ISSUE THREAD

**Issue by Minabsapi** [atom/atom#19897]
## Summary

After some complaints I made to myself about many hangs and problems I did encounter with Atom (mostly performances issues) and the fact that many coders depicted Atom as a slow-as-hell IDE, I was wondering if by any chance there would be, beyond all the hard work of optimizing this software, use of some sort of compilation one day.

## Motivation

Atom uses mainly JS (With Node.js and Electron) to work. Making use of this versatile language to make an hackable text editor is a really good idea by itself.
However, everyone knows how terrible this language can be with resources. One wrong line of code and you can end up with a computer nearly dying with its RAM filled to the top.

Reason why I'm wondering if, to speed some things up as much as possible in this awesome editor, using WASM (if it's not already the case) would be a good idea. 
Is it actually doable ? I know it's hard to do with Node, but without making it directly to Node and just "compiling" some scripts (core features for instance) without breaking the "hackability" of the editor ?

## Describe alternatives you've considered

Many peoples are waiting for better performances from an IDE. If peoples with a war machine for PC run Atom fine, peoples like me with an average PC have real trouble. And here I was just talking about the CPU, RAM is also a thing ! 
Though I know you never stopped to improve this marvelous initiative, I think that trying to find solutions about performances issues by considering such idea (may it be useful) is urgent, just to stop the majority from thinking about Atom as a gag/toy IDE perfect for little stuff but not suitable for real projects and going for VSCode (for instance) instead.
My really honest point, hope I didn't feel rude.

**Comment by Arcanemagus** [comment]
Atom already makes use of [native modules](https://nodejs.org/api/addons.html) for many of the most critical aspects of the editor, such as [managing the buffer contents](https://github.com/atom/superstring/), [searching within project files](https://github.com/atom/fuzzy-native), and [parsing code for syntax highlighting](https://github.com/atom/node-tree-sitter). For most code though the overhead of calling out to a native module outweighs the benefits of moving the code there in the first place. As the team continues to work on performance improvements that is always an option that is considered though.

Thanks for reaching out!

We have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.
