### ISSUE TITLE
Windows crash on write "con***" 

### ISSUE THREAD

**Issue by josopu** [atom/atom#19907]
![image](https://user-images.githubusercontent.com/26584841/64842637-1b227600-d603-11e9-88a5-d2c07a77e67b.png)

Every time I try to write "contact" it crashes.

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by Aerijo** [comment]
@josopu 
> Put an X between the brackets on this line if you have done all of the following:
>
 >   Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

This was not just a suggestion; safe mode separates Atom issues from package issues. Those completions are not provided by core packages of Atom. You should identify which package is providing them, and raise the issue there. It may still be a bug on Atom's side, but we will the package maintainers to identify it first.

**Comment by Arcanemagus** [comment]
I would strongly suspect `Hydrogen` as the culprit myself as it executes code as you type it from what I understand, and `CON` (of any case) is a special file on Windows.

**Comment by josopu** [comment]
On safe mode no error occurs. Now I did try it again but it didn't crash (normal mode with/without Hydrogen).
