### ISSUE TITLE
XSS within Atom

### ISSUE THREAD

**Issue by shifty0g** [atom/atom#19909]
not too sure if this is an issue or a feature of atom but i can get a few cross-site scripting payloads to execute within atom using the find function.

atom - 1.40.1 x64

# Replication  Steps
------------------
1) Create a new file and add the following 

```
error
https://blahwebsite.co.uk/admin/default?error=<script>alert(222)</script>
```

![2019-09-13_16h16_34](https://user-images.githubusercontent.com/18333460/64874412-dcacab80-d642-11e9-8c42-f569ff85a97d.png)

2) Use the find function – CTRL + F 
Search for something which is on the same line as the XSS code –  for example error which is on the same line 

![2019-09-13_16h17_16](https://user-images.githubusercontent.com/18333460/64874460-f5b55c80-d642-11e9-9383-2832d17c915a.png)

3) Click back on the main window of text document then to trigger the payload  do CTRL + F again  which will execute the XSS Payload 
 

![2019-09-13_16h17_49](https://user-images.githubusercontent.com/18333460/64874396-d4ed0700-d642-11e9-9e2d-5bd281a0aaf0.png)

The XSS payload has been executed 
Confirmed payloads to work
<script>alert(222)</script>
<script/v>confirm(/@test/)</script>

**Comment by rsese** [comment]
Thanks for the report!  I was unable to reproduce so might be misunderstanding your repro steps but can you update the issue body to use the issue template?  Some of the details would be helpful to know like whether this is an issue in safe mode from the `Prerequisites` section and what operating system you're running from the `Versions` section.

**Comment by shifty0g** [comment]
ok didnt knwo about safe mode. so ran it in safe mode and cant replicate the issue. would this suggest its a plugin responsible ?

win 10 1908

![image](https://user-images.githubusercontent.com/18333460/64907341-dffa7280-d6e8-11e9-8a13-d81a5febfc7d.png)


![2019-09-14_12h10_47](https://user-images.githubusercontent.com/18333460/64907330-ca854880-d6e8-11e9-908e-82c76ebc9233.gif)

**Comment by Arcanemagus** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
