### ISSUE TITLE
Atom is now missing a few heavy plug-ins

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#19914]
atom is now missing some of the heavyweight plug-ins, like the excellent IDE plug-ins.
Officials can organize a group of active users in the open source community to solve this problem

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.
