### ISSUE TITLE
Atom 1.38.2 is the only version of Atom that works with PyMakr

### ISSUE THREAD

**Issue by jdcrunchman** [atom/atom#19913]
I save all when done with my work session.   But when I restart Atom again,   I get a blank screen.  The project path does show up in the window title bar.   I cannot seem to find what version of PyMakr I have,  but all I know is that it works.   I've had to disable auto-update, so I can continue using 1.38.2

So now,  when I restart Atom it comes in the blank screen,   is there any workaround for this problem.

This has the be the flakiest application program I've had the displeasure of dealing with.

It's a great program when it works.

I'm running it on a Mac 10.13.6 - It's an older mac,   and cannot get further upgraded.

I really can use some help here.

John
jdcrunchman@gmail.com

**Comment by jdcrunchman** [comment]
has anyone found a work around?   please help me,  my financial survival depends on a least having a working IDE?

**Comment by Arcanemagus** [comment]
Thanks for contributing!

Unfortunately it looks like this is an issue with that package that they have yet to address:
https://github.com/pycom/pymakr-atom/issues/131
https://github.com/pycom/pymakr-atom/issues/132
...

It appears that this is being caused by the [pymakr](https://atom.io/packages/pymakr) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

----

> my financial survival depends on a least having a working IDE?

Since this problem is almost certainly a `pymakr` issue, this may not help you but from [their site](https://pycom.io/solutions/software/pymakr/) it appears they also offer integration with Visual Studio Code. It may be that they have a better working version of their package for that editor.
