### ISSUE TITLE
Please, please, PLEASE DOUBLE CHECK BEFORE ALLOWING A FULL DELETE OF A PROJECT!!!!!!!!

### ISSUE THREAD

**Issue by michealjroberts** [atom/atom#19938]
As the title suggests, this has happened numerous times where a whole folder can be accidently deleted in one swoop, without any safety check or anything!!!!!!!!!!!!

Also, don't allow folders to be dragged into other folders without another confirmation check!!!!!!!!!

I am now going through Dropbox events one by one restoring them. Absolutely awful experience.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

-----

I attempted to reproduce this by deleting a folder using the tree-view and this is what I saw:

<img width="377" alt="Screen Shot 2019-09-20 at 4 39 35 PM" src="https://user-images.githubusercontent.com/1038121/65364241-5f92b080-dbc5-11e9-9804-61e68f11eef4.png">

Then I get a confirmation dialog:

<img width="477" alt="Screen Shot 2019-09-20 at 4 39 45 PM" src="https://user-images.githubusercontent.com/1038121/65364248-6b7e7280-dbc5-11e9-8c7d-18974fbad5ae.png">

So I'm not sure what it is you're talking about. But if you fill out the template next time, you'll probably give us the information we need to actually help.

**Comment by michealjroberts** [comment]
NO! This is not what has happened - several thousand files have been deleted - over 60,000!!!! This isn't the first time this has happened.

**Comment by michealjroberts** [comment]
ASK BEFORE DELETING!

**Comment by michealjroberts** [comment]
Scarp that, it's mysteriously deleted 240,000 files!!! Without asking. I have had similar experiences happen before with hot keys. I have also experienced that by accident you can move a whole folder inside another, without any safety checks. Upwards of tens of thousands of files - moved. Without a check. Unbelievably awful for our project. Atom has cost use 2 days work at least.
