### ISSUE TITLE
Include UTF-8

### ISSUE THREAD

**Issue by Crockos** [atom/atom#19959]
Hi everybody, I have a problem with all the themes in general but I has been using this theme and can't change now. For me and a lot of people we don't speak english, so we write different and we use special character like ñ, í, ú, ó among others.

All my code is defined in spanish so if i declare a class i don't write "signal" y write "señal" becouse its akward for me and my coworkers when we mix english with spanish so here is the think. The request its include the "ñ" in particular as a valid syntaxt and not exclude it from the grammar if this is UTF-8. I check the Atom code and the "ñ" and the other letters after it are excluded from the span so the char and the rest of the word are a "non word character" and atom only give us the option to exclude in the "non word characters input" from the editor but it not gives the option to include it. Sorry if I am wrong, maybe its an Atom problem and not depends from the theme but I hope this can be more inclusive to other languajes.
Note: The grammar in Atom its already utf-8.
![Captura de pantalla de 2019-09-25 09-53-40](https://user-images.githubusercontent.com/37781986/65602641-975d7780-df7a-11e9-95c1-2e2c3aa58ef5.png)
![Captura de pantalla de 2019-09-25 09-54-48](https://user-images.githubusercontent.com/37781986/65602646-9af0fe80-df7a-11e9-94ae-ebf2e312c9e5.png)
![Captura de pantalla de 2019-09-25 09-58-51](https://user-images.githubusercontent.com/37781986/65602936-1eaaeb00-df7b-11e9-8a88-1e240dcc5b65.png)

**Comment by lee-dohm** [comment]
Atom itself supports UTF-8 and a wide variety of other encodings. It sounds like what you're looking for is for the identifier rules in the Python grammar to support the full range of Unicode characters, [as specified in Python v3.0 and above](https://docs.python.org/3.7/reference/lexical_analysis.html#identifiers). For that, a change would need to be made to [the underlying grammar definition](https://github.com/tree-sitter/tree-sitter-python). Once that is done, then the [language-python package](https://github.com/atom/language-python) could be updated with the new definition.

For your reference, I've opened [an issue](https://github.com/tree-sitter/tree-sitter-python/issues/53) on the grammar repository for this. You may want to subscribe there for updates.

Because this isn't an issue with Atom itself but with a dependency, I'm going to close this issue.
