### ISSUE TITLE
Java debugging packages not working

### ISSUE THREAD

**Issue by legoman8304** [atom/atom#19960]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I am trying to use atom for debugging java. when installing the 3 needed packages: 
[atom-debugger](https://atom.io/packages/atom-debugger)
[atom-ide-ui](https://atom.io/packages/atom-ide-ui)
[ide-java](https://atom.io/packages/ide-java)
but upon opening the debugger tab, it says I [have no debuggers installed](https://drive.google.com/file/d/1lXrByKbo7AXdE27wdPMVwalUlQow0QLH/view?usp=sharing) hence i cannot attach them for use. I clicked the link shown [here](https://drive.google.com/file/d/1lXrByKbo7AXdE27wdPMVwalUlQow0QLH/view?usp=sharing) 
sidenote, I also found this message in the terminal: ```Error starting process:
Error: Cannot find module 'C:\Users\nultonw1\.atom\packages\atom-ide-ui\node_modules\nuclide-prebuilt-libs\pty\build\pty-node-v64-win32-x64\pty.node'```

### Steps to Reproduce

1. Install packages
2. Open debugging panel on the right side
3. See error

**Expected behavior:**

Be able to debug java file

**Actual behavior:**

Tells me I have no debugger attached

**Reproduces how often:**

Every time I try to use it.

### Versions

1.40.1 Windows 10

### Additional Information

n/a

**Comment by lee-dohm** [comment]
Thanks for contributing!

It appears that this is being caused by the one of the packages you listed, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://flight-manual.atom.io/faq/ has information on [how to contact the maintainers of any Atom community package or theme](https://flight-manual.atom.io/faq/sections/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/).
