### ISSUE TITLE
Tabs not restored on second atom instance (using `ATOM_HOME`)

### ISSUE THREAD

**Issue by Andrade** [atom/atom#19961]
### Description

When using two different atom instances via `ATOM_HOME` the tabs of the second instance are not reopened. The session doesn't appear to be properly restored.

Note: I reported this previously [here](https://github.com/atom/atom/issues/19425) but was told my installation method at the time (snap) was not supported. I now have installed atom using the deb file download from the official website. Problem still occurs.

### Steps to Reproduce

**Setup:**
1. Terminal 1: `ATOM_HOME=~/.atom-foo atom` -- open a project and a few tabs
2. close atom
3. Terminal 2: `ATOM_HOME=~/.atom-bar atom` -- open a project and a few tabs
4. close atom

**Steps for bug:**
1. Terminal 1: `ATOM_HOME=~/.atom-foo atom` -- all tabs are reopened as expected
2. Terminal 2: `ATOM_HOME=~/.atom-bar atom` -- tabs are *not* reopened (but they should)
3. close both atom windows
4. Terminal 2: `ATOM_HOME=~/.atom-foo atom` -- tabs are now back again

**Expected behavior:**

Tabs should always be reopened.

**Actual behavior:**

Tabs of the second atom are not reopened.

**Reproduces how often:**

Always.

### Versions

```
$ atom --version
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

Ubuntu 18.04

**Comment by rsese** [comment]
Thanks for confirming with a supported install :+1:  I was able to reproduce with Atom 1.40.1 on Ubuntu 19.04.

Poking around more I see this error in devtools console:

> Could not connect to indexedDB 

I'm guessing you see this error as well?  This is the same error you would see if you tried to run 2 versions of Atom at the same time (e.g. stable and beta at the same time).  So I think the problem is both can't update/access saved state at the same time so whichever Atom is opened second will have the issue.

To workaround this I think you can create an `electronUserData` directory in one or both of your Atom home directories (this is touched on in the description of [portable installs of Atom](https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-notes)).  This way each instance of Atom will store saved state in different locations.

I gave this a try and can no longer reproduce with your repro steps - can you confirm if it works for you too?

**Comment by Andrade** [comment]
Creating an `electronUserData` fixes the issue, thank you.

I was getting the same error in devtools console.

![Screenshot from 2019-10-03 10-37-17 - atom-dev-tools-conn-indexedDB](https://user-images.githubusercontent.com/4957940/66118295-eab07500-e5cd-11e9-998d-e92680690f4d.png)

**Comment by rsese** [comment]
Thanks for confirming, glad that helped :+1:   Going to close for now but I'll see if other maintainers think we should keep it open (or do something else like mention this in the documentation).
