### ISSUE TITLE
Ubuntu 18 CPU 100%

### ISSUE THREAD

**Issue by comarius** [atom/atom#19977]
After few minutes gets 100% CPU.

```
11824 user    20   0 1110400 182960  65004 R 100.0  1.5  23:03.24 atom   
```
OS:  4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rsese** [comment]
Thanks for reaching out!

As mentioned below, please fill out the issue template as much as possible - without the template information, there's not enough details for us to take a look, try to reproduce, etc.  

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
