### ISSUE TITLE
Monospace not aligned when using emoji

### ISSUE THREAD

**Issue by Redsandro** [atom/atom#19982]
### Description

Certain emoji draw wider than a single monospace character.

### Steps to Reproduce

Write some lines with emoji. E.g.:

```javascript
function test(str) {
    return str
        .replace(/xsmal-case\.jpg]/g, '👝') // Lines out
        .replace(/large-case\.jpg]/g, '🧳') // Lines out
        .replace(/small-case\.jpg]/g, '💼') // Lines out
}
```

**Expected behavior:**

Monospace will be monospace, no matter what. All lines with the same amount of visible characters are equally wide.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/1702193/65948976-95dcf500-e43b-11e9-915e-b3cdb2be9a4b.png)

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.41.0-beta1
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0-beta1
python 2.7.15+
git 2.17.1

Linux Mint 19.2 Tina Cinnamon x64
Linux 5.2.0-050200rc7-generic
AMD Ryzen 5 3400G with Radeon Vega Graphics
```

**Comment by lee-dohm** [comment]
Thanks for reporting the problem.

If you follow [these instructions from the Atom Flight Manual on debugging font rendering issues](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-font-rendering-issues), you'll note that the line with the color emoji is rendered using two fonts. Here's what the results for mine looks like:

<img width="320" alt="Screen Shot 2019-10-01 at 8 16 21 AM" src="https://user-images.githubusercontent.com/1038121/65975668-cfa20180-e423-11e9-80bb-b9db92f85075.png">

Because the two fonts may have differing font metrics, we have two choices:

1. Respect the font metrics and accept that lines containing emoji (as well as other characters such as Chinese, Korean, or Japanese) may not be completely monospace
1. Force all "secondary" fonts to conform to the font metrics of the "primary" font (leaving aside the problem of determining what exactly a primary and secondary font are), which means that characters may be squished together or abnormally spread far apart and, in general, look bad or possibly even illegible

We've chosen to err on the side of legibility at the expense of lines not conforming to a single set of font metrics. As such, we won't be changing this behavior.
