### ISSUE TITLE
The file that was saved is not part of this project's git repository. 

### ISSUE THREAD

**Issue by devcline** [atom/atom#19987]
i got this message today when i save a file in git local to unstaged changes ;
where an i dig about, i didnt find any info ?

`The file that was saved is not part of this project's git repository. Therefore no WIP checkpoint was saved. If you're sure this file is part of the current project's repo, make sure you don't have multiple top-level folders open.`

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [git-wip](https://atom.io/packages/git-wip) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
