### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.53.104.55:8080

### ISSUE THREAD

**Issue by jklydon** [atom/atom#19994]
[Enter steps to reproduce:]

1. Install 'uber-juno' package.
2. Install interrupted by closing editor.
3. Re-open editor which continues installation.
4. Install fails - "This is likely a bug in Atom."

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise 2016 LTSB
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.53.104.55:8080

```
At internal/streams/legacy.js:57

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.53.104.55:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
  2x -5:33.9.0 window:increase-font-size (atom-pane.pane.active)
     -2:54.2.0 settings-view:uninstall-packages (atom-pane.pane.active)
```

### Non-Core Packages

```
indent-detective 0.4.0 
ink 0.11.1 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.2.0 
uber-juno 0.2.0 
```

**Comment by jklydon** [comment]
This occurred in a moderately-restrictive corporate Internet environment. Not surprised by the timeout ("tunneling socked could not be established") but rather by the uncaught exception. I will try a similar install in a less restrictive environment.

**Comment by jklydon** [comment]
'Uninstall' then re-'Install' resolved this issue. As planned, I tried a similar install in a less restrictive environment. The less-restrictive-environment install completed without any observed problem.

**Comment by rsese** [comment]
> As planned, I tried a similar install in a less restrictive environment. The less-restrictive-environment install completed without any observed problem.

Thanks for that update - it does seem like your work environment is part of the issue, maybe some kind of network security service?  There are settings for using Atom behind a [firewall](https://github.com/atom/apm#behind-a-firewall) or with a [proxy](https://github.com/atom/apm#using-a-proxy), but not sure if there's something your network admins can help with here - we otherwise don't currently have the resources to dig into these types of network issues but we're tracking related problems in issues like https://github.com/atom/apm/issues/772 (see https://github.com/atom/apm/issues/772#issuecomment-445298119 for example) so we'll close in favor of that issue for now.

Curious, is it just that package that gives you trouble or any package you try to install?
