### ISSUE TITLE
atom editor won't display unicode characters correctly

### ISSUE THREAD

**Issue by jhuntergit** [atom/atom#20002]
_Windows 10 using Atom 1.40.1 x64_

I have a text file with a single character in it being this unicode bullet, I'll paste it here "•". In Sublime Text the character displays properly as "•" and in Windows notepad it's also displayed properly as "•". In atom it displays as "�". How do I get this diamond with a question mark to properly display as a bullet, in atom editor? I think this is a bug.

---

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

**Comment by Arcanemagus** [comment]
It sounds like the file encoding isn't being properly detected, you'll want to double check that the encoding shown in the lower right is the same as what you would expect for the file.

Thanks for reaching out!

----

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
