### ISSUE TITLE
Implement a more userfriendly proxy configuration method

### ISSUE THREAD

**Issue by phgogo** [atom/atom#20004]
## Summary
Using a proxy with Atom (or more specific: with APM) is already possible today. Currently the configuration has to be made in the .apmrc file, where (when using a proxy with Authentication) the credentials are stored in plaintext. I suspect this method to be unsecure and not user friendly.

## Motivation
- Storing passwords in plaintext, accesible with user-permissions,  is never a good idea
- Proxy passwords tend to change frequently in most companies. If i forget to change the password in the config file, atom retries the login until my account gets blocked by DDOS protection

I would appreciate a method of entering the credentials when needed, optimal would be an option to save the username

**Comment by rsese** [comment]
Thanks for the suggestion - though we can see how useful this could be (maybe with some kind of user prompt?), as mentioned in the issue template we're not prioritizing new functionality at the moment.  I'll share your idea with the other maintainers but since this isn't something the team will work on, I'm going to close this out but thanks again for the suggestion 🙇

**Comment by phgogo** [comment]
Thanks for that kind answere! I understand that new features aren't your focus right now but i still wan't to add, that this is an feature that maybe would allow atom to get more popular in big companies. At least it's the main reason why our team does not adopt to it.
