### ISSUE TITLE
Allow packages to be project specific.

### ISSUE THREAD

**Issue by wadethestealth** [atom/atom#20016]
# Summary

This feature allows for certain packages to be disabled when certain projects are open.

## Motivation

Say you are in dev mode developing on your favorite package. Generally, I like to keep this dev package enabled while in dev mode for testing. But say I also develop for another package in dev mode. Now both dev packages are enabled when I would just like to have the dev package I am currently working on enabled.

Another interesting use case this supports is when one person may use a package for editing in their favorite project, but when they switch projects they don't want that package enabled because it "gets in the way".

Note this feature shouldn't just apply to dev mode.

## Describe alternatives you've considered

Current work around is disabling and enabling packages when switching projects.

**Comment by lee-dohm** [comment]
Thank you for the suggestion!

That does sound like an interesting idea for a package :+1: Unfortunately, the Atom maintainer team is already full up handling all of the support and maintenance of the current core packages. There are a couple options:

* Someone may have already created this and we're not aware of it. Have you searched [the Atom package registry](https://atom.io/packages/) or [Atom theme registry](https://atom.io/themes/)?
* You can post a message on [Discuss, the official Atom and Electron message board](https://discuss.atom.io/c/packages) to see if anyone from the community is willing to try and build it

In any case, because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). But I'm also going to label this with `package-idea` so that others searching for suggestions here can find this.

Thanks again for your interest in Atom :grinning:

**Comment by wadethestealth** [comment]
Seems like `package-switch` is what I am looking for, but it is 4 years out of date. Might do some hacking and release a newer version.
