### ISSUE TITLE
Sometimes I can't continue typing text after I type in Chinese

### ISSUE THREAD

**Issue by qaralotte** [atom/atom#20017]
Environment：Windows 10 1903
When this happens, I have to switch the English input method and then switch the Chinese input method to continue typing.
Previously this problem did not occur on Ubuntu 18.04.

**Comment by lee-dohm** [comment]
In order to have any hope of reproducing and fixing this, we're going to need some detailed steps to reproduce the problem. This is one of the reasons we require the issue template to be filled out ...

-----

Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
