### ISSUE TITLE
Atom Crash 1.40.1 x64

### ISSUE THREAD

**Issue by shahprog** [atom/atom#20019]
When I open Atom in my computer and from the welcome guide tab I click on Choose a theme and then click on 'Open the theme picker' and scroll a little bit to see the themes available, Atom crashes and i have three option
<b>1. Close Window
2. Reload 
3. Keep It Open</b>
Like this :
![Screenshot (19)](https://user-images.githubusercontent.com/40076722/66822024-3ddade00-ef65-11e9-80ce-d539e3142a45.png)

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

The issue template information is super helpful for us when triaging issues - for example, it would be helpful to know if you tried the suggested debugging steps like safe mode or temporarily resetting to factory defaults.

Once you share those details we can go from there.
