### ISSUE TITLE
Uncaught SyntaxError: Unexpected number in JSON at position 93

### ISSUE THREAD

**Issue by cailingxiao** [atom/atom#20020]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Unexpected number in JSON at position 93

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:6

SyntaxError: Unexpected number in JSON at position 93
    at JSON.parse (<anonymous>)
    at /Users/cailingxiao/Documents/code/dynamiclayout/dynamiclayout/dynamic-layout-kit/lib/dynamic-manager.js:56:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
```

### Commands

```
     -0:34.7.0 core:save (input.hidden-input)
     -0:21 core:cut (input.hidden-input)
  2x -0:20.5.0 core:save (input.hidden-input)
     -0:17.3.0 core:paste (input.hidden-input)
     -0:17.1.0 core:save (input.hidden-input)
     -0:07.8.0 core:cut (input.hidden-input)
  2x -0:07.4.0 core:save (input.hidden-input)
     -0:02.5.0 core:paste (input.hidden-input)
  2x -0:02.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 1.4.3 
dynamic-layout-kit 0.0.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
```

**Comment by lee-dohm** [comment]
Thank you for your submission!

It appears that this is being caused by the dynamic-layout-kit package that you appear to be developing, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need you or the maintainer of the package that is causing the problem to help track that down to supply us with steps to reproduce the problem.
