### ISSUE TITLE
Turning off Soft Wrap does not turn it off

### ISSUE THREAD

**Issue by Valinwolf** [atom/atom#20036]
### Description

When Soft Wrap it set to "off" it still wraps when the max screen size is met. This is undesirable behavior because a user expects an off switch to turn it off. You wouldn't want your light bulb in your bedroom turning on at 3am because it was off for 500 minutes even though the switch was in the off position would you?

### Steps to Reproduce

1. Ensure that soft wrap is off
2. Put 500+ characters (under default settings) on one line

**Expected behavior:**

When soft wrap is off, it NEVER soft wraps.

**Actual behavior:**

When soft wrap is off, it still soft wraps after the number of characters specified in max screen size.

**Reproduces how often:**

Reproducible 150% of the time

### Versions

Atom    : 1.40.1
Electron: 4.2.11
Chrome  : 69.0.3497.128
Node    : 10.11.0

Arch Linux
Kernel version 5.3.5, 64-bit

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

> Atom : 1.40.1
> Electron: 4.2.11

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by Valinwolf** [comment]
I installed it from Arch repos but regardless this issue, based my own research, is not just caused by the version-mismatched install I have.

**Comment by Arcanemagus** [comment]
> I installed it from Arch repos

The Arch distribution unfortunately distributes a broken version as their own "official" version (not to be confused with an actual official Atom version!). Users installing that are a _very_ large percentage of the issues that get closed due to bizarre behavior that isn't reproducible in official builds.

> based my own research, is not just caused by the version-mismatched install I have.

Reading your issue it looks like what you are describing is a performance decision by the editor to break **extremely** long individual lines up into multiple visual lines, to allow the editor to render them quickly. You can see the details behind this decision in https://github.com/atom/atom/pull/13820

A configuration option was added in https://github.com/atom/atom/pull/14495, so if this limit is an issue for you you can set it to a much larger limit yourself by typing this into the developer console:
```js
atom.config.set('editor.maxScreenLineLength', 123456)
```

**Comment by Valinwolf** [comment]
> > I installed it from Arch repos
> 
> The Arch distribution unfortunately distributes a broken version as their own "official" version (not to be confused with an actual official Atom version!). Users installing that are a _very_ large percentage of the issues that get closed due to bizarre behavior that isn't reproducible in official builds.

I just found it frustrating that you closed it before actually looking at it.

> > based my own research, is not just caused by the version-mismatched install I have.
> 
> Reading your issue it looks like what you are describing is a performance decision by the editor to break **extremely** long individual lines up into multiple visual lines, to allow the editor to render them quickly. You can see the details behind this decision in #13820
> 
> A configuration option was added in #14495, so if this limit is an issue for you you can set it to a much larger limit yourself by typing this into the developer console:
> 
> ```js
> atom.config.set('editor.maxScreenLineLength', 123456)
> ```

Actually you don't even need to use the developer console, it's in the options window. I just find it extremely irritating that there is no way to _truly_ turn off word wrap. I cannot stress enough how much I ***HATE*** word wrap and will be more than happy to take the performance hit in the extreme use case scenario that is presented by that. If soft wrap cannot be disabled, there should not be a option to do so. This is not a feature, it's an anti-feature. If I uncheck something in the settings, I expect it to, at very least after a restart, respect the setting and Atom's soft wrap does not turn off. Period. Atom currently has redundant settings because it was hackishly implemented from the start. I would like to see it reverted and the default soft wrap set to 500, just because a user expects a setting to work and this one doesn't.
