### ISSUE TITLE
docker-compose build causes crash

### ISSUE THREAD

**Issue by SumNeuron** [atom/atom#20038]
I am putting this here so that whatever this funk is, it is documented.

I am on Ubuntu 16.04 LTS.
Latest version of atom.

docker-compose build with an atom editor open sometimes crashes.

Only once did I ever see any logs / warnings. In the terminal shell from which I opened atom:

```
/usr/bin/atom: line 141: 10405 Illegal instruction     (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: worker.js:71:22
Remote event names: destroyed, crashed

#
# Fatal process OOM in deserialize context
#

```

no idea what this is, or what causes it other than running docker-compose, but it has happened enough that maybe someone else has an idea

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

I haven't used Docker myself so without the template information it's hard to take a look (maybe someone with more experience using Docker can chime in).  For example, what version of Atom is installed and how is it provided through Docker (is it from the official .deb or the official package repository [1])?    Which debugging suggestions from the `Prerequisites` section have you tried?  

[1]: https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt
