### ISSUE TITLE
Hide window tabs in fullscreen (Mac)

### ISSUE THREAD

**Issue by sergeyfilimonov** [atom/atom#20047]
## Summary

Hide window tabs on Mac in fullscreen mode just like the Safari does in fullscreen mode with the panel hidden.

## Motivation

I have about 20 active projects. Keeping all of them in one window is impossible as the space gets cluttered very quickly. So I keep a few windows — each window represents a workspace. But I don't need all of the workspaces at once and want more focus on the current workspace. So I would like to hide them (windows tabs) in fullscreen and get access to them only when I hover at the top of the screen. 

## Describe alternatives you've considered

The alternative is to have each workspace in separate desktops but this method clutters Mission Control and you can't always use `tab+cmd` to switch between Chrome and Atom for instance because switching brings you to the nearest desktop with Atom opened not necessarily the one you need (to fix this you have to place the desktop you need closer to Chrome).

**Comment by rsese** [comment]
Thanks for the suggestion! Though this sounds like it could be useful for some people's workflows, as mentioned in the template, the team is currently very unlikely to prioritize new functionality right now.  We also encourage folks to use community packages and/or Atom customizability when possible:

> I have about 20 active projects. Keeping all of them in one window is impossible as the space gets cluttered very quickly.

Not sure if it will help your workflow, but perhaps a project manager type package could be helpful?  For example, https://atom.io/packages/project-manager makes it easier to switch from one project to another.

In any case, we'll mention your idea with the other maintainers but since this isn't something the team would prioritize now, we'll close this out but thanks again for sharing your idea.
