### ISSUE TITLE
Can't save files (and other issues)

### ISSUE THREAD

**Issue by fwsGonzo** [atom/atom#20090]
Hello all, as a long-time user of Atom I am having an issue after the latest update.

I have reduced the issue down to github integration (as far as I can tell). The behavior will seem like it's failing to save files (working for a little while and then failing), but what really happens is that after a few seconds after starting Atom it will fail even simple things like opening the preferences window, and also not save files anymore. Starting Atom and then immediately disabling Github integration solves the issue for me. Did not have this issue on any of my other laptops.

Have a nice day.

**Comment by calebmeyer** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by RomanJos** [comment]
Thanks, I could not save anything and Edit > Preferences didn't worked, disabling Github package seems to have fixed it 
Atom    : 1.41.0-beta1
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
