### ISSUE TITLE
Atom erodes text!

### ISSUE THREAD

**Issue by TopoR1** [atom/atom#20100]
Hello! I use the editor Atom and I'm already tired of the fact that it erodes or lathers the text. It is unpleasant for my eyes. I would like to know how to deal with this problem?
![image](https://user-images.githubusercontent.com/19995663/68057710-ce584300-fd07-11e9-9ea4-598f4fd7ee53.png)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
