### ISSUE TITLE
disable or override alt hotkey

### ISSUE THREAD

**Issue by mighty9245** [atom/atom#20136]
after hiding menu bar alt becomes a hotkey to show and hide it, but i change my keyboard layout with alt+shift combination and every time i do it the menu either shows or hides and that's so god damn annoying when your editor is basically jumping. how to deal with that? i saw #6037 but it doesn't seem to work anymore, at least for me. i'm on arch linux and atom 1.41

found that my issue is a duplicate of #16443, but it was created 2 years ago and still nothing is fixed. it really annoys me.

**Comment by lkashef** [comment]
Hey @mighty9245, Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by WilSnoop** [comment]
Add the following in your `keymap.cson` file.
```cson
'*':
  '^alt': 'abort!'
```

**Comment by p-boiko** [comment]
> @mighty9245:
> 
> Add the following in your `keymap.cson` file.
> 
> ```coffee
> '*':
>   '^alt': 'abort!'
> ```

doesn't help

**Comment by mighty9245** [comment]
@p-boiko iirc that's actually helps but you need to restart atom after this

**Comment by p-boiko** [comment]
> @p-boiko iirc that's actually helps but you need to restart atom after this

Of course I restarted. More than once. Other suggestions worked partially, but I think I have to accept it, because the same issue is with other Electron apps (Code, Skype etc). So it should be fixed in Electron first, then affected apps should updated. So it is possible that it will never be fixed...

**Comment by mighty9245** [comment]
why not just report the issue to electon?

**Comment by p-boiko** [comment]
> why not just report this issue to electron?

reported, here for example: https://github.com/electron/electron/issues/22213

I hope that there is a way to workaround it on the app side, and Atom is the Electron app I use 99% of time. Electron was unable to fix it through 2 major versions, so I don't expect it to be fixed soon by their team.

**Comment by p-boiko** [comment]
Hei, I just found the (temp) workaround :smile:

I use Shift-Alt instead of Alt-Shift: layout is switched (fbxkb in my case) and Atoms' menu bar remains hidden

**Comment by MurzNN** [comment]
Same problem is in recent VS Code: https://github.com/microsoft/vscode/issues/85405
