### ISSUE TITLE
problem is that no one even look at this appp and realize is has no names for anything idiots

### ISSUE THREAD

**Issue by Adam1884** [atom/atom#20140]

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
