### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.41.0\package'

### ISSUE THREAD

**Issue by ChakritDev** [atom/atom#20155]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Chakrit\AppData\Local\atom\app-1.41.0\package'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\Chakrit\AppData\Local\atom\app-1.41.0\package'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1008510)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1015683)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:989070)
```

### Commands

```
  2x -5:48.5.0 project-find:show-in-current-directory (span.name.icon.icon-file-directory)
     -5:07.7.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -5:00.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
