### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 2475

### ISSUE THREAD

**Issue by chrispatterson** [atom/atom#20183]
[Enter steps to reproduce:]

1. Unfortunately unsure - came back to my laptop and the error popup was in place (I assume that points to a memory leak, but that's speculative on my part)

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 2475

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 2475
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
intentions 1.1.5 
language-slim 1.0.1 
linter 2.3.1 
linter-rubocop 2.5.3 
linter-ui-default 1.8.0 
minimap 4.29.9 
pigments 0.40.2 
shared-settings 0.0.6 
svn 0.0.14 
sync-settings 0.8.6 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
