### ISSUE TITLE
CTRL+V shortcut calls /bin/dd?

### ISSUE THREAD

**Issue by Vox1984** [atom/atom#20188]
when editing specific yaml file ctrl+v calls /bin/dd 

```
7172 [/snap/atom/242/usr/share/atom/atom --type=renderer --no-sandbox --enable-experimental-web-platform-features --enable-features=SharedArrayBuffer --service-pipe-token=1034506054481476771 --lang=en-US --app-path=/snap/atom/242/usr/share/atom/resources/app.asar --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Atom/1.41.0 Chrome/69.0.3497.128 Electron/4.2.7 Safari/537.36 --node-integration=true --webview-tag=true --no-sandbox --background-color=#fff --disable-blink-features=Auxclick --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=1034506054481476771 --renderer-client-id=5 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101] (owned by unix-user:user)
Nov 27 14:37:23 pkexec[11940]: user Error executing command as another user: Request dismissed [USER=root] [TTY=unknown] [CWD=/home/user] [COMMAND=/bin/dd]
```

ATOM
1.41.0
18.04.2-Ubuntu

**Comment by WilSnoop** [comment]
Firstly - what kind of behaviour were you expecting?

There is doubt that this is a problem relating to Atom's core functionality. Consider asking your question at [discuss.atom.io](discuss.atom.io); your Github identity will work there.

I suggest you to open the Keybinding Resolver (mentioned: https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings). Use <kbd>Ctrl .</kbd> to open/close the panel. Use the shortcut button again and see which process is being triggered in the background.

I expect an add-on package is giving this behaviour.

**Comment by Arcanemagus** [comment]
This sounds like an issue with a third-party package, since you didn't fill out the template, or follow the instructions it asks you to before filing an issue though we can't be sure. Feel free to file a new issue with the template filled out, making sure you try Safe Mode first!

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
