### ISSUE TITLE
Delete file when moving win 10

### ISSUE THREAD

**Issue by Waiker** [atom/atom#20208]
Hello. When I try to move the file from the ftp server explorer to the Atom window, the file is deleted.
My system is Windwos 10.
Atom 1.41.0 x64
![GIF 05 12 2019 14-08-54](https://user-images.githubusercontent.com/5464086/70221207-c4dc5380-1769-11ea-8b58-6ab4fc05cdee.gif)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
