### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 692

### ISSUE THREAD

**Issue by sairus7** [atom/atom#20214]
[Enter steps to reproduce:]

Opened two different instances of Atom and wait ~24 hours while pc was in sleep mode several times. Then one of Atom instances show this error.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 692

```
At C:\Users\user\AppData\Local\atom\app-1.41.0\resources\electron.asar\renderer\api\remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 692
    at throwRPCError (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:148:17)
    at ~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
```

### Non-Core Packages

```
hyperclick 0.1.5 
ink 0.11.5 
julia-client 0.11.2 
language-julia 0.19.1 
minimap 4.29.9 
multi-cursor 3.0.0 
selection-highlight 0.1.6 
tool-bar 1.2.0 
uber-juno 0.3.0 
```

**Comment by sadick254** [comment]
Thank you for opening this issue. This was issue present in electron versions 4 and below. The latest atom version `v1.51.0` uses electron version `5.0.3`. The issue was fixed on this commit https://github.com/electron/electron/commit/a8f2646ba682d65f94ea628ac11b1a5521bcedcd. The fix has been available from electron version `5.0.0`. I would advice you to upgrade to the latest atom version. I am closing this for now but happy to reopen if you still experience the issue.
