### ISSUE TITLE
Autoclose tags, autocomplete htmlentities, highlight selected should be core features

### ISSUE THREAD

**Issue by kpatrickos** [atom/atom#20219]
Hello Atom Dev team, 

Atom is really one of the best and IDE of choice for coders and it should rank up there. However, I think the following features should be included as core and not just installed. For example:-

- Autoclose tags,
- highlight similar selected words or variables
- a caret to display a dropdown of opened tabs or autoscroll, without having all of the tabs stack at the top and their title names barely visible.

This would great!

**Comment by WilSnoop** [comment]
Hello.

As I understand, Atom is a text editor, it is not an IDE. Though packages do transform Atom to having IDE type functionality. 

I use Atom for coding SCL (structured code language). 
Which advantage is for someone like me to have "autoclose tags"?

More to the point - 
1. Why would you want to see the mentioned functionalities be part of the core?
2. What difference is there between these being in the core vs a package?
3. What advantage do you see [for you] to have these in the core?
4. What advantage do you see [for everyone] to have these in the core?
5.  Which program languages would benefit for these?

There is a group of volunteers looking into building up the IDE abilities of Atom - consider joining in to help code and test.

**Comment by kpatrickos** [comment]
Hey, what is this? Are you answering my suggestions or you're asking your own questions? Why not create your own topic then?!
It's good you recognized that Atom can be extended to full-featured IDE, so quit explaining it as a text editor or switch to Notepad.

Kindly let the developers of Atom attend to these suggestions, not newbies!!

Thanks

**Comment by kpatrickos** [comment]
Hey @WilSnoop , what is this? Are you answering my suggestions or you're asking your own questions? Why not create your own topic then?!
It's good you recognized that Atom can be extended to full-featured IDE, so quit explaining it as a text editor or switch to Notepad.

Kindly let the developers of Atom attend to these suggestions, not newbies!!

Thanks

**Comment by kpatrickos** [comment]
Hello @lkashef , I hope the @Atom team can consider the above mentioned features and also include 'Open Recent Files', with a list of last closed files not only one, as another core feature

**Comment by lee-dohm** [comment]
Thanks for reaching out.

This is something that Atom has struggled with since its public release in early 2014: where do we draw the line between what should be "in Atom core" and what should be a community package? Over the months and years that I've worked on this project, it became quite clear that no matter where we draw the line, some people will want it drawn in a different place. Some people will believe that certain features must be in core, some will believe that they're nice-to-have, and others will not want those features bloating their pristine editing environment.

Since we don't have a great way of gauging community sentiment on these things, we've opted for what we feel is the next best strategy: is there already a community package for it or do we believe that the maintainer team has the bandwidth to properly maintain the added feature in perpetuity? One of the major benefits of open source and relying on the community to make and maintain certain features is that the greater Atom community (including the Atom maintainers) can be far more responsive, agile, and creative than the Atom maintainers can be by themselves. In essence, it is better to have something reasonably well-maintained by community members than something barely supported by an overstretched and overloaded Atom maintainer team.

So while we agree that having the features you're asking for "in core" would be useful to some, we simply don't have the people and time available to take them on. Additionally, since most, if not all, of these requests already have great community packages that implement them, there's even less reason for us to take them on.

Thanks again for the feedback and I hope you can understand!

**Comment by calebmeyer** [comment]
For your reference, here are some community packages (that I haven't vetted, but appear to be what you're looking for):
https://atom.io/packages/autoclose-tags
https://atom.io/packages/highlight-selected
https://atom.io/packages/multiline-tab or any of the many tab switcher packages can get you a dropdown. Tabs already support horizontal scrolling. If you're having trouble with lots of tabs, I recommend https://atom.io/packages/tidy-tabs to set a maximum and automatically close old ones as you open new ones.
