### ISSUE TITLE
Unable to run package specs from cmd Atom Nightly

### ISSUE THREAD

**Issue by wadethestealth** [atom/atom#20249]
OS:
>Windows 10

Atom Versions:
>Atom: 1.44.0-nightly2
>Electron: 4.2.7
>Chrome: 69.0.3497.128
>Node: 10.11.0

Apm Versions:
>apm  2.4.3
>npm  6.2.0
>node 10.2.1 x64
>atom 1.44.0-nightly2
>python
>git 2.19.1.windows.1
>visual studio 2015

Currently my user's `PATH` contains `C:\Users\Wade\AppData\Local\atom-nightly\bin\`.

I don't have any alias commands set up and use `atom-nightly` and `apm-nightly` for cmd commands. 
I don't know why, but updating to `1.44.0-nightly` had removed my `PATH` and once I added it back I now get `Error spawning Atom: spawn atom.cmd ENOENT` when running `apm-nightly test`. 
Obviously its looking for `atom.cmd` but shouldn't it just uses its neighbor/sibling `atom-nightly.cmd`

Also interestingly `ctrl+shift+y` still functions as expected and does not seem to have any problems.

**Comment by Arcanemagus** [comment]
It looks like you may simply need to re-install the nightly? You can also add the location back to the `PATH` if that doesn't work.

Note also that `apm test`, although it still _works_, is not the preferred method. You should be using `atom --test path/to/specs` 😉.

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
