### ISSUE TITLE
Cannot input Chinese after backspace

### ISSUE THREAD

**Issue by Duya07** [atom/atom#20269]
After I typed a string of Chinese, there was a word wrong. I couldn't type several letters after using backspace. I think this is the problem of backspace key. In other editors, I didn't find that I couldn't input because of backspace key. Thanks

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
