### ISSUE TITLE
move .atom to .config/atom

### ISSUE THREAD

**Issue by slavachertanovo** [atom/atom#20283]
that's all

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by lee-dohm** [comment]
Additionally, [you can move the Atom home folder to wherever you like](https://flight-manual.atom.io/using-atom/sections/basic-customization/#custom-home-location-with-an-environment-variable) and use the `ATOM_HOME` environment variable to tell Atom where to find it.
