### ISSUE TITLE
Crazy memory use on macOS

### ISSUE THREAD

**Issue by mjrodgers** [atom/atom#20285]
I just recently upgraded to 1.42.0, and Atom is using crazy amounts of RAM all of the sudden (Atom Helper currently using 13GB with one window open (2 tabs, a tex file and its 1-page pdf).

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Open Atom
2. Type stuff for 10 minutes
3. Notice system slow to a crawl

**Expected behavior:**

Editing a text file using about 1.6GB RAM

**Actual behavior:**

Editing a text file using 13GB RAM

**Reproduces how often:**

I quit Atom and reopened about a half hour ago because everything was running slow.

### Versions

Atom 1.42.0 on macOS 10.14.6

**Comment by lee-dohm** [comment]
Since Atom doesn't render PDFs in its native [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) state, I'm going to assume that you haven't reproduced this in Safe Mode? If you can reproduce this in Safe Mode, please let us know and give us a sample file or project that we can use to reproduce the problem. For reference, my current instance of Atom Nightly v1.44.0-nightly2 has been running for days with intermittent typing going on and its memory use is a total of a few hundred megabytes.
