### ISSUE TITLE
Object.basename is deprecated.

### ISSUE THREAD

**Issue by Cristishor201** [atom/atom#20284]
Arguments to `path.basename` must be strings
```
Object.basename (D:\Atom\app-1.39.1\resources\app.asar\src\electron-shims.js:34:10)
Object.htmlu (C:\Users\Cristian\.atom\packages\preview-plus\lib\lang\html.coffee:80:20)
Object.toggle (C:\Users\Cristian\.atom\packages\preview-plus\lib\preview-plus.coffee:233:36)
StatusView.updateCompileTo (C:\Users\Cristian\.atom\packages\preview-plus\lib\status-view.coffee:275:27)
CompilerView.confirmed (C:\Users\Cristian\.atom\packages\preview-plus\lib\status-view.coffee:49:23)
CompilerView.confirmSelection (C:\Users\Cristian\.atom\packages\platformio-ide-terminal\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [preview-plus](https://atom.io/packages/preview-plus) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
