### ISSUE TITLE
Installer should allow selection of installation location / path

### ISSUE THREAD

**Issue by wbt** [atom/atom#20296]
Following up on [this issue](https://github.com/atom/atom/issues/20202), I tried following [these instructions](https://discuss.atom.io/t/error-while-installing-atom/69666) to reinstall Atom, using the AtomSetup-x64.exe for [v1.42.0](https://github.com/atom/atom/releases/tag/v1.42.0).  

The first few times, the installation failed, sometimes silently (after "Atom will launch when the installation is complete, that view disappeared and nothing else happened) and sometimes with an explicit error.  Clicking to view details, I found a "squirrelSetup" file noting that that Atom was attempting to install into the Microsoft Teams installation directory.  Why? No clue.  The issue was further confused because pinned shortcuts still worked to open Atom, despite Windows reporting that the app had been completely uninstalled, and the directories in the provided instructions no longer existing.  (Apparently it had been opening code at C:\Users\username\Programs\Atom x64\atom.exe, perhaps from a portable version.)  These difficulties reinforced the perception that upgrading Atom is not quick & easy and that it's important to wait until a time when greater disruption can be tolerated and more time is available for debugging. 

Further, there are some use cases for allowing people to choose where to install an app.  This is why many other applications allow you to specify the install directory as part of the installation procedure. 

I don't know specifically why my installation attempts repeatedly failed or eventually succeeded; that would be filed as a separate issue even if I had reproducible steps handy.  However, I do know that not being able to know where Atom was installing to made the issue harder to debug, and it definitely shouldn't have been trying to install into the Teams subdirectory.  I also know that in other installations I have sought to customize the install location when running the installer and been unable to do so, and would like to be able to do that.  **This feature request is exclusively for adding an option to customize the install path to the installer.**

**Comment by wbt** [comment]
As a follow-up, in addition to the automatically linked issues above, [#20299](https://github.com/atom/atom/issues/20299) contains some additional information about the install failures.  However, this present issue should remain focused on adding an option to customize the install path in the installer.

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

-----

Also, this is a specific design decision that reduces the support load. If you want to customize where Atom is installed you can use the zip file method.

**Comment by wbt** [comment]
@lee-dohm FYI, your link to the issue template returns 404.  

However, the issue template for feature requests (which this is, so that template is what this post started with) is relatively thin.  It requires a **summary** (which I put in the summarizing title, and in bold), **motivation** (*Why are we doing this? What use cases does it support? What is the expected outcome?*) which is the bulk of the text, and why I included information about the installation failures that I think is otherwise not particularly relevant, **additional context** which is incorporated in providing a context-rich description, and **describe alternatives you've considered.**

Only the latter is missing from the above post and that's because the primary alternative is the status quo: Atom installs to wherever it currently installs to, with no user option.  To me, the "status quo alternative" is always implicit and I didn't think it needed to be made explicit, but here it is as an addition to the post. 

Further, I could go through [each](https://flight-manual.atom.io/using-atom/sections/basic-customization/) of the [lines](https://flight-manual.atom.io/using-atom/sections/atom-packages/) in [documentation](https://flight-manual.atom.io/hacking-atom/) about how to customize Atom *after* it's been installed, but none of them address how to customize in the **installer** and there is no documentation about installer customization options because there currently are none.  I also thought going into detail describing that would be a waste of time and more an obstacle than a help to all the more useful tasks you enumerated ("fixing bugs, implementing enhancements, and reviewing and merging pull requests").

IMHO, I think this issue satisfies the template requirements and should be reopened.

**Comment by lee-dohm** [comment]
Thanks for the pointer on the broken link 🙇‍♂️

As far as whether your submission includes all the required information from the template or not, we require people to use the template so that we can more efficiently evaluate the submissions that people give. One of the ways that this is achieved is that people who have less experience or in depth knowledge of the project can quickly skim to verify that all the right information is there, then someone with more experience can go back, read the whole thing, and evaluate it. This saves the maintainer team time overall, which, as I stated in my response before means that more time can be spent fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Regardless of whether this satisfies the template requirements, we aren't going to be adding an option to the installer to customize the installation location. Your suggestion of improving the documentation to talk about how to install atom in a custom location is a good one though. An issue or pull request for this kind of change in https://github.com/atom/flight-manual.atom.io would be welcome.

**Comment by lee-dohm** [comment]
Also, this is a duplicate of [this previous issue](https://github.com/atom/atom/issues/7504).

**Comment by wbt** [comment]
@lee-dohm Thanks for the dupe-pointer.  I had [searched](https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=is%3Aissue+install+location) for "install location" with a non-default to include closed issues, but hadn't found that one. 

Reading through other related issues, I think a PR in documentation might be appropriate.  However, after reinstalling, I seem to have lost the "Open with Atom" item in context menus, even after restoring preferences via the instructions in the second link in the Issue, and can't seem to get Pin to Start working when unzipping to install.  I would not want to recommend the ZIP install strategy without documenting workarounds to get these pieces of functionality back, to allow people to reopen Atom after first installation.
