### ISSUE TITLE
No MOOSE application executable found

### ISSUE THREAD

**Issue by CDmaterial** [atom/atom#20309]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
I do not have such problem before I upgrade my mac to OS Catalina. In atom, I installed packages `autocomplete-moose` and `language-moose`. Now when I update my input file, atom shows such error message: No MOOSE application executable found.
What does this mean? 

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by one of the [autocomplete-moose](https://atom.io/packages/autocomplete-moose) or [language-moose](https://atom.io/packages/language-moose) packages, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
