### ISSUE TITLE
Option to control Ctrl-left behavior from start of a line and Ctrl-right from end of a line

### ISSUE THREAD

**Issue by kendonB** [atom/atom#20304]
OS: Ubuntu 18.04

In some editors (e.g. gedit, atom, vscode), Ctrl-left from the start of a line will move you to the left of the last word on the previous line.

In others (e.g. sublime, notepad++) Ctrl-left from the start of a line will move you to the end of the last word on the previous line.

Would be nice to be able to customize this on Atom. Is this possible?

**Comment by lkashef** [comment]
Hey @kendonB, Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

You could check if it's doable via [customizing your keymaps file](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/)
