### ISSUE TITLE
1.43.0 Broke Nuclide Remote Development

### ISSUE THREAD

**Issue by paulchill** [atom/atom#20324]
My team uses the deprecated facebook/nuclide package for remote development on EC2's.

Yesterday we all could not connect from around 1pm GMT.

Below is the atom error, this is for sure a client issue:
The server successfully started, but we were unable to connect.
Original error message:
 ENOENT: no such file or directory, open 'nuclide://XXXXXXXXXXXX.compute.amazonaws.com/var/www/.**git/commondir**'

Can anyone tell me how to fix this? 6 devs cant work on their VM's

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [Nuclide](https://nuclide.io/) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by paulchill** [comment]
@Arcanemagus  This is incorrect, i installed an old version of atom and turned off automatic updates and its fine. It works fine in the December release of atom. Therefore it is an atom issue.

I reverted the version and all the team could use it with nuclide straight away no issues.

This happened with the automatic update that came out yesterday.

**Comment by lee-dohm** [comment]
@paulchill While you are most certainly correct about the behavior of the individual Atom versions, because Atom doesn't have the functionality that you're describing without the Nuclide package, it is still the case that the error wouldn't happen without the Nuclide package. The simple fact of the matter is, we don't maintain the Nuclide package and we aren't going to be investigating a bug that can only be reproduced by using it.
