### ISSUE TITLE
Are my crash reports uploaded?

### ISSUE THREAD

**Issue by hoall** [atom/atom#20335]
Hello,
regarding the discussion in #9816:

Do I have to fear that possible data is leaked when atom crashes while opening a file with sensitive data?
My configuration in config.cson look like:
`"*":
  core:
    telemetryConsent: "no"
  "exception-reporting":
    userId: "will-not-tell"
  welcome:
    showOnStartup: false`

I am pretty afraid that file content could be send.

Also, if the data is not sent, why is there a configuration for exception reporting? That troubles me.

@50Wliu can you tell me something about it please?

Hoping for your response.

Best Regards

**Comment by hoall** [comment]
Found the explanation of the measure plugin and just hope it works like this.

**Comment by Arcanemagus** [comment]
Even if you had crash reporting enabled (which it looks like you don't), then file data wouldn't be being sent.

The _only_ way that information beyond the crashing location within Atom code could be sent was if you manually uploaded a memory dump, something that would be requested by a team member only if there was no other way to get the information, and certainly wouldn't be shared in a public place since we have no way of controlling what private information might be in the dump.

**Comment by hoall** [comment]
@Arcanemagus, I just wanted to be sure, but I guessed it would be that way. 

Thank you for the clarification :)
