### ISSUE TITLE
Failed to activate the node-resolver package

### ISSUE THREAD

**Issue by tsdeveloper** [atom/atom#20344]
### Versions
Atom:  1.42.0 x64 | 1.43.0 x64
NodeJs v13.7.0

Guys, you're showing this error whenever you open Atom. I already reinstalled Node, I already ran Atom as an administrator and even then the error continues

Failed to activate the node-resolver package

**Comment by tsdeveloper** [comment]
![atom-error-node-resolver](https://user-images.githubusercontent.com/5727326/72901045-cc4ec080-3d07-11ea-8007-5965c6d90da0.png)

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [appropriate issue template](https://github.com/atom/.github/tree/master/.github/ISSUE_TEMPLATE) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
