### ISSUE TITLE
support in android

### ISSUE THREAD

**Issue by PerachBD** [atom/atom#20343]
hi, can u do an android version?

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [appropriate issue template](https://github.com/atom/.github/tree/master/.github/ISSUE_TEMPLATE) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

-----

Also, we have no plans for a version of Atom on any mobile platform.
