### ISSUE TITLE
youcompleteme error

### ISSUE THREAD

**Issue by kebaren** [atom/atom#20342]
After I configured YCM, Atom reported a message:"[YCM] Error :Error: EISDIR: illegal operation on a directory, read"! How can I resolve the problem>

**Comment by WilSnoop** [comment]
Have you visited the package's project page?
It sounds like a package related issue.
https://github.com/Qusic/atom-youcompleteme

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [appropriate issue template](https://github.com/atom/.github/tree/master/.github/ISSUE_TEMPLATE) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
