### ISSUE TITLE
--wait is ignored (snap)

### ISSUE THREAD

**Issue by feldgendler** [atom/atom#20368]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The `--wait` command line option seems to be ignored. When Atom is already running, `atom --wait` does open the specified file but finishes instantly and doesn't wait for the tab/window to be closed. This makes it impossible to use Atom as the commit message editor for git.

### Steps to Reproduce

1. Start Atom.
2. In a terminal, run `atom --wait /path/to/some/file`.

**Expected behavior:**

The specified file is opened in Atom. The `atom --wait` command blocks until the file is closed.

**Actual behavior:**

The specified file is opened in Atom. The `atom --wait` command finishes immediately.

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

Ubuntu 19.10

Snap package:
```
snap-id:      Lf1MF6tizzusVuA6l13ETyH5VDXxwA0D
tracking:     stable
refresh-date: 15 days ago, at 15:19 CET
channels:
  stable:    1.43.0 2020-01-14 (246) 231MB classic
  candidate: ↑                             
  beta:      1.43.0 2020-01-14 (246) 231MB classic
  edge:      1.43.0 2020-01-14 (246) 231MB classic
installed:   1.43.0            (246) 231MB classic
```

### Additional Information

Some of the other command line options work, others don't.

`atom --version` and `atom --help` silently exit with code 0 without any output.
`atom --new-window FILE` works as expected.

Running `/snap/atom/current/usr/share/atom/atom` directly fixes `--help` and `--version` but not `--wait`.

**Comment by feldgendler** [comment]
A similar problem on Windows: #20152

**Comment by Aerijo** [comment]
:wave: @feldgendler  Atom does not maintain a Snap distribution. You would need to contact whoever is providing it. You can find the official distributions [in the flight manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/#installing-atom-on-linux)

_____ 

Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
