### ISSUE TITLE
process.env is corrupted on Fedora 31

### ISSUE THREAD

**Issue by PerBothner** [atom/atom#20389]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode
    * Followed all applicable steps in the debugging guide:
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: 
(The issue has been filed before - for example issue #13451 - but they are closed as not reproducible in safe mode.  I have some more information, including how to reproduce in safe mode.)

### Description

The `process.env` contains garbage values when Atom is started on Fedora 31.  This seems to be related to [Environment Modules](http://modules.sourceforge.net/) which puts certain Bash functions with unusual names (such as `BASH_FUNC_switchml%%`)  into the environment - see `env1.txt` attachment, which contains the result of the `env` command before starting Atom.  My guess is whatever (Node?) code is initializing `process.env` is confused by this function, producing garbage - see attachment `process-env.txt`, which is from the debugger console.

This is almost certainly the cause of strange error message in terminals and other packages.  See issue #13451 

[process-env.txt](https://github.com/atom/atom/files/4172083/process-env.txt)

[env1.txt](https://github.com/atom/atom/files/4172006/env1.txt)

### Steps to Reproduce

1. If not running with Environment Modules (such as under Fedora 31), you can probably reproduce the problem by defining the `BASH_FUNC_switchml%%` functions as shown in the `env1.txt` attachment.
2. Start atom, optionally with `--safe`.
3. Open Developer Tools, and type `process.env` in the console.

(I would not surprised if the bug is easy to find by just looking at the relevant code, but I am not familiar with the Electron/Atom/Node code-base.)

**Expected behavior:**

A proper object, with one entry for each environment value.

**Actual behavior:**

Certain environment entries are spread out over multiple entries.  For example notice an extra entry for `" IFS"` (with initial space):

    process.env[' IFS']
    "$_mlIFS;"

Note I don't see this when starting DomTerm in a recent Electron, so this may have been fixed upstream, unless Atom does something weird.

**Reproduces how often:**

Always.
### Versions

    Atom    : 1.43.0
    Electron: 4.2.7
    Chrome  : 69.0.3497.128
    Node    : 10.11.0

Fedora 31 with Gnome/Wayland on x86_64.

**Comment by xdelaruelle** [comment]
@TJProgrammer also opened a [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1795425) for this on the Fedora side. I am currently digging into this especially that every related tickets incriminates at some point either `scl` or `environment-modules`.

As far as I can tell, this issue impacts every shell functions defined over the `/etc/profile.d/*.sh` scripts. As most common tools defining a shell function in this setup location are scl and environment-modules, this issue is almost always reported with error messages related to the `scl`, `module` or `switchml` shell functions. But if another shell function is defined in `/etc/profile.d/*.sh` scripts, it will also get the issue.

It seems there is a different behavior whether you start atom through the desktop application link or from a shell terminal. The latter is not impacted by these error messages.

This difference comes from the setup of the `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT` environment variable which is explicitly set to `false` when starting Atom from the desktop application link. When started from a shell terminal, `/usr/bin/atom` script sets [this variable to `true`](https://github.com/atom/atom/blob/master/atom.sh#L28-L31) as it is not found defined.

From my understanding, when `` equals `false`, [`getEnvFromShell`](https://github.com/atom/atom/blob/1d9a4cafcf6cc288d675512db8fd984e13aab869/src/update-process-env.js#L65) is run and if we [look at how the environment result is composed](https://github.com/atom/atom/blob/1d9a4cafcf6cc288d675512db8fd984e13aab869/src/update-process-env.js#L123-L131):

```
  let result = {};
  for (let line of stdout.split('\n')) {
    if (line.includes('=')) {
      let components = line.split('=');
      let key = components.shift();
      let value = components.join('=');
      result[key] = value;
    }
  }
```

This parsing method, working over the result from the `env` command run through shell, does not cope with the shell function definitions returned in `env` output.

So I think, something should be done in this `getEnvFromShell` function to handle shell functions.

**Comment by PerBothner** [comment]
A work-around is to call `env` with the `--null` flag, and split on NUL characters instead of newlines.   I don't know how portable that flag is: It should work on Linux systems that have GNU coreutils; it may not be available on BSDs, including MacOS.

But the more fundamental problem is what is the purpose of `getEnvFromShell` and `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT`? I  started atom with `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=true`, and it seemed to work fine.  Starting the [atom-domterm](https://atom.io/packages/atom-domterm) works without warnings and running `env` inside the new terminal gives expected results.

Perhaps someone can explain why `getEnvFromShell` exists. If not, I suggest using `git blame` to see when it was added and why.

**Comment by xdelaruelle** [comment]
@PerBothner I totally second you regarding this question: what is the purpose of `getEnvFromShell` and `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT`?

In the mean time, I am proposing with #20393 a minimal change to fix the whole thing for Atom and its packages: excluding shell functions from the result returned by `getEnvFromShell`.

And for the record, 1a1468b seem to have made the issue reappeared recently. From my understanding, before this commit `getEnvFromShell` were not used anymore as `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT` was set to `true` by Atom launch script.

**Comment by PerBothner** [comment]
The rationale for `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false` appears to be https://github.com/atom/atom/issues/18318 .

However, that assumes that Atom (when started from the desktop) *should* see the result of running `.bashrc` in interactive mode.  I have the feeling that is wrong.  As long as Atom gets the definitions from running `~/.bash_profile` or`~/.profile` that should be enough.
