### ISSUE TITLE
Remote Repo Clone Error in Atom

### ISSUE THREAD

**Issue by seeuuaye08** [atom/atom#20403]
In the remote repo I'm trying to clone in Atom there are some backslashes in a filename. This is causing the entire clone to error and not finish. Is there a way to ignore the backslashes so the clone can complete or does the filename need to change in Github first?

![image](https://user-images.githubusercontent.com/23037619/74267776-574e2580-4ccc-11ea-9ea5-38359bc4d932.png)

**Comment by lkashef** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
