### ISSUE TITLE
Providing an easy way of using C/C++/WASM code [Performance]

### ISSUE THREAD

**Issue by aminya** [atom/atom#20407]
## Summary

Providing an easy of using C/C++ code can enhance many different aspects of the Atom's performance. This means providing required compilers for each operating system, so the package developers can easily without the fear of "adding a compiler to the dependency" use fast alternatives like Native addons, WASM, etc.

## Motivation

1) Asking `file-icons` developers to use `node-re2` which is a fast regular expression library to improve the performance of the package. But they are afraid of adding a dependency that requires compiling C/C++ code.
https://github.com/file-icons/atom/issues/565#issuecomment-585569401

2) there is no documentation in the flight manual for using WASM or C/C++ code to write Atom packages.
 
## Describe alternatives you've considered

Delivering the code as WASM or as a binary that doesn't require recompiling.

## Additional context

To have a desktop-like experience on the Electron platform, we need to use the native power of the system. That means using code that is fast, statically compiled, parallelized (SIMD, multi-threaded, etc), etc.

Related discuss post: https://discuss.atom.io/t/why-is-atom-so-slow/11376/

**Comment by Arcanemagus** [comment]
Thanks for taking the time to write this up, however this isn't something we will be adding.

Bundling a C/C++ compiler for all supported platforms is an exercise in futility due to the myriad of different ways this can be done, and how often it can break. Package authors can definitely add compiled dependencies that rely on this if they are willing to take on the support for helping all users  install compiling chains on OSs like Windows.

A much simpler solution _for the end users_ if this is desired is to create the dependencies as WASM bundles, this does require the package author to know how to create and interact with them, however that is nothing specific to Atom and other places provide far better tutorials on this advanced topic.
