### ISSUE TITLE
Beautifier runs on the main thread and locks UI on large files

### ISSUE THREAD

**Issue by derMart** [atom/atom#20408]
Hi,

the title describes basically the problem. When running the beautifier on a larger file, the UI blocks and after some time even the 'keep wait / force close' dialog appears.

Expected behaviour: When running beautify (or in general just ANY long running task) the beautifying buffer should not be editable and a progress bar or at least loading icon should appear.
However,  the UI thread should not be blocked and atom should be responsible while beautifying.

A generalized issue would be:
ALL long running tasks should NOT run in the UI thread.
-> ALL non UI related tasks should NOT run in the UI thread....
I am emphasizing this as a general problem, as this seems to be a major issue occuring all over atom generating many problems.

This applies to Atom <= 1.44.0

kind regards
Martin

**Comment by UziTech** [comment]
This seems like an issue for [atom-beutify](https://github.com/Glavin001/atom-beautify)

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-beautify](https://github.com/Glavin001/atom-beautify) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
