### ISSUE TITLE
Python script run error

### ISSUE THREAD

**Issue by Tejaswgupta** [atom/atom#20414]
### Prerequisites

* [.] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

On running python code on atom with script, it does not function properly

### Steps to Reproduce

Run
""
agent_name = 'James Bond'
kill_count = 777

print('{0} has killed {1} enemies '.format(agent_name,kill_count))

print(f'{agent_name} has killed {kill_count} enemies')

""

**Expected behavior:**

It should output "James Bond has killed 9 enemies 
James Bond has killed 9 enemies"

**Actual behavior:**

It raises error saying:
 File "/Users/tejasw/Documents/python/fstring.py", line 8
    print(f'{agent_name} has killed {kill_count} enemies')
                                                        ^
SyntaxError: invalid syntax
[Finished in 0.073s]

### Versions

OS : macOS 10.15.3
Atom version : 1.44.0
Script version : 3.25.0

### Additional Information

None

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [script](https://atom.io/packages/script) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
