### ISSUE TITLE
Atom installed a dependency, but didn't install a nested dependency until atom was restarted.

### ISSUE THREAD

**Issue by TZubiri** [atom/atom#20428]
Read the following issue.

https://github.com/AtomLinter/linter-tidy/issues/156#issuecomment-587210691

This happened in version 1.40 before I updated to 1.44

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [linter-tidy](https://github.com/AtomLinter/linter-tidy) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
