### ISSUE TITLE
Atom always in setup mode

### ISSUE THREAD

**Issue by DylanCABELLO** [atom/atom#20432]
I've downloaded Atom recently and I can't find it ok the quick start. I have the atom setup.exe.
Everytime I open it it says installing, then I restart my Laptop and it still the setup version

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

It sounds like you might need to check where your OS has applications installed to for where to launch Atom? The installer isn't going to turn into a shortcut for the app.

Thanks for understanding and meeting us halfway :grinning:
