### ISSUE TITLE
Works finely! @alimary i just had this same issue. The link given by @damieng has a solution you may want to try.

### ISSUE THREAD

**Issue by RajaramRajamani** [atom/atom#20437]
Thank you so much! It works finely!!

@alimary i just had this same issue. The link given by @damieng has a solution you may want to try.

C:\Users\__username__\AppData\Local\atom\app-1.8.0\resources\cli

_Originally posted by @sayhelloelijah in https://github.com/atom/apm/issues/547#issuecomment-225393582_

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
