### ISSUE TITLE
Horizontal lines on editor

### ISSUE THREAD

**Issue by jmbyars** [atom/atom#20430]
I am using Atom Nightly and just recently horizontal lines have appeared in the editor. I am trying to find documentation in removing them, but haven't found any leads. Does anybody have a recommendation?

![Screenshot from 2020-02-18 09-34-32](https://user-images.githubusercontent.com/9964645/74745435-e78eec00-5231-11ea-8ca2-e506ffd516d3.png)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Part of the template you removed involves running Atom in Safe Mode which disables all community packages. Since these lines look to only be showing up with new "sections" I strongly suspect this is a package you have installed.

Thanks for understanding and meeting us halfway :grinning:
