### ISSUE TITLE
Atom is crashing with in one minute of opening it

### ISSUE THREAD

**Issue by Maheswar6040** [atom/atom#20443]
The editor has crashed this is the error message I am getting within one minute of opening the atom.
I uninstalled the atom and deleted .atom, AppData/Roaming/Atom, AppData/Local/Atom folders still the editor is crashing.

![Screenshot (284)](https://user-images.githubusercontent.com/45171169/75155846-e597c200-5736-11ea-91ee-4fff285afb75.png)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by Maheswar6040** [comment]
@Arcanemagus  What template should I need to fill?

**Comment by Arcanemagus** [comment]
The one you had to remove to post this issue 😉.
