### ISSUE TITLE
Atom has stopped opening files and has grayed out everything

### ISSUE THREAD

**Issue by 80kk** [atom/atom#20475]
My Atom has stopped opening files, if I open a project everything is grayed out and won't open for editing any file. How to fix that?

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
