### ISSUE TITLE
apm search is currently returning a 500, even from the website

### ISSUE THREAD

**Issue by krainboltgreene** [atom/atom#20473]
> Searching packages failed: Application error

This also means the editor can't search and gives a very strange error:

<img width="823" alt="Screen Shot 2020-03-04 at 11 07 24 PM" src="https://user-images.githubusercontent.com/334809/75956516-edf5a880-5e6c-11ea-827a-8afe50844de1.png">

Of course I also checked the website.

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by krainboltgreene** [comment]
@darangi What, exactly, would you have filled out here?

**Comment by darangi** [comment]
@krainboltgreene We require issue templates to be properly filled in a certain way so we can troubleshoot properly, Take a look at how this issue was reported https://github.com/atom/atom/issues/19968

**Comment by krainboltgreene** [comment]
I understand what you're saying, but that issue you linked pertained to atom. This is (was?) an issue with the search API. apm, atom, and the website were all affected.

How would the standard template help?

**Comment by darangi** [comment]
Okay, now I get it, I have tried searching for packages but I can't reproduce this, I have tried both from the editor and the website.

**Comment by krainboltgreene** [comment]
I regret not getting a request id or something. Thanks for looking into it, perhaps it resolved!
