### ISSUE TITLE
Can you support more programming language highlighting? Such as lua

### ISSUE THREAD

**Issue by zzzxb** [atom/atom#20490]

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by calebmeyer** [comment]
Also, you may be interested in https://atom.io/packages/language-lua , which provides what you're asking for
