### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sectionHeadings' of undefined

### ISSUE THREAD

**Issue by Katafotic** [atom/atom#20518]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Debian GNU/Linux
**Thrown From**: 'simplified-russian-menu' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'sectionHeadings' of undefined

```
At /home/viacheslav/.atom/packages/simplified-russian-menu/tools/settings.coffee:85

TypeError: Cannot read property 'sectionHeadings' of undefined
    at applySectionHeadings (/packages/simplified-russian-menu/tools/settings.coffee:85:3)
    at HTMLAnchorElement.applyInstallPanelOnSwitch (/packages/simplified-russian-menu/tools/settings.coffee:68:3)
```

### Commands

```
     -0:24 core:confirm (input.hidden-input)
  5x -0:23.3.0 core:backspace (input.hidden-input)
  2x -0:22.4.0 core:confirm (input.hidden-input)
  2x -0:21.7.0 core:backspace (input.hidden-input)
  3x -0:20.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-i18n 0.22.0 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [simplified-russian-menu](https://atom.io/packages/simplified-russian-menu) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
