### ISSUE TITLE
017-07-14 11:57:23> Program: Starting Squirrel Updater: --install . 2017-07-14 11:57:23> Program: Starting install, writing to C:\Users\Dubey\AppData\Local\SquirrelTemp 2017-07-14 11:57:24> Program: About to install to: C:\Users\Dubey\AppData\Local\Postman

### ISSUE THREAD

**Issue by ananddubey2020** [atom/atom#20528]

**Comment by ananddubey2020** [comment]
017-07-14 11:57:23> Program: Starting Squirrel Updater: --install .
2017-07-14 11:57:23> Program: Starting install, writing to C:\Users\Dubey\AppData\Local\SquirrelTemp
2017-07-14 11:57:24> Program: About to install to: C:\Users\Dubey\AppData\Local\Postman

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
