### ISSUE TITLE
atom的bug

### ISSUE THREAD

**Issue by Cactus521** [atom/atom#20535]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0-beta0 ia32
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At E:\Program Files\Atom\AtomBeta\Atom Beta\resources\app\static\<embedded>:14

TypeError: Cannot read property 'version' of undefined
    at E:/Program Files/Atom/AtomBeta/Atom Beta/resources/app/static/<embedded>:14:2600377
    at E:/Program Files/Atom/AtomBeta/Atom Beta/resources/app/static/<embedded>:11:937604
    at r (E:/Program Files/Atom/AtomBeta/Atom Beta/resources/app/static/<embedded>:11:934610)
    at n (E:/Program Files/Atom/AtomBeta/Atom Beta/resources/app/static/<embedded>:14:1128190)
    at ChildProcess.o.process.on.e (E:/Program Files/Atom/AtomBeta/Atom Beta/resources/app/static/<embedded>:14:1128396)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -6:06.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-simplified-chinese-menu 0.6.5 
chinese-translator 1.1.2 
```

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

--- 

The version number is weird though, if you do a fresh download and install from atom.io, I think it should solve your problem
