### ISSUE TITLE
get list of stored states?

### ISSUE THREAD

**Issue by modernNeo** [atom/atom#20589]
I am trying to determine if there is a way to determine how many projects my atom instance has a state of?

By this I mean that if I open a folder I had previously had open, Atom will remember I had that folder opened and will offer to restore its state in a new window if I want.

I would like to know if there is a way to get a list of all the folder that my atom instance has a state for.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by UziTech** [comment]
@modernNeo I think `atom.history.getProjects()` would help

**Comment by modernNeo** [comment]
@UziTech thanks, that ended up being just what I needed
