### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.45.0\ 12 47 ...

### ISSUE THREAD

**Issue by ebeers-png** [atom/atom#20595]
Hi, I was trying to move some image files from a folder I downloaded into a new subfolder I had just created in Atom. One image was titled "Photo May 18, 12 47 34 PM.jpg" -- it seems like the comma in the title caused the error.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Elizabeth\AppData\Local\atom\app-1.45.0\ 12 47 34 PM.jpg'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\Elizabeth\AppData\Local\atom\app-1.45.0\ 12 47 34 PM.jpg'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1005297)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1012226)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:985857)
```

### Commands

```
     -0:34.9.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:30.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ide-css 0.3.3 
ide-html 0.6.0 
language-haskell 1.19.4 
language-ocaml 1.9.5 
language-racket 0.4.0 
language-rust 0.4.12 
universe-master undefined 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
