### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by tina80lvl** [atom/atom#20607]
<img width="1552" alt="Screenshot 2020-04-09 at 17 18 28" src="https://user-images.githubusercontent.com/27859234/78905212-4fb9bb80-7a86-11ea-9a2a-d0764bada5b6.png">

Appeared while installing terminal package. Rebooting doesn't help.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

One of the most important steps of the template is to try launching Atom in Safe Mode, this would allow you to uninstall the offending package.

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
