### ISSUE TITLE
Hi, I can't seem to lighten the UI in the Atom app. (Atom 2). I am following through on some advice showing me how to use it but I can barely see anything the app is so dark. When I try to find a lighter theme, the theme section just tells me where to find it again - while I am already there. When I click on 'the blue button' it's own instructions tell me to, it only opens example code in my browser rather than in the app. I want to continue using Atom, just so that I'm getting to know a variety of text editors, and it seems to have some cool features, like having two pages visible side by side, but the darkness is driving me crazy. I think it's wasting my time not being able to see where panels are and aren't. Has anybody else encountered this problem and found a way around it? Sorry if this issue seems to have been solved, or doesn't have enough specifics, I am a new user, and there are probably a lot of areas where I don't know what to look for?

### ISSUE THREAD

**Issue by heidimaybe** [atom/atom#20603]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by constantinexisc** [comment]
Why did you put the entire body of your question as the title?

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Some things to keep in mind, the template issue is there for a reason, so please help us address your reports and contributions more efficiently, also the title should be short and descriptive of the issue.

Finally as issues serve as our backlog, questions could be addressed via the below support channels:

# Atom Support

If you're looking for support for Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
