### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/ sun rising.jpg'

### ISSUE THREAD

**Issue by bananman741** [atom/atom#20619]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Kali GNU/Linux
**Thrown From**: Atom Core
**User**: root

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/root/ sun rising.jpg'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '/root/ sun rising.jpg'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (/usr/share/atom/resources/app/static/<embedded>:14:1005283)
    at TreeView.onDrop (/usr/share/atom/resources/app/static/<embedded>:14:1012212)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:985843)
```

### Commands

```
     -2:58.4.0 core:save (input.hidden-input)
  9x -0:35.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.10.0 
terminal-plus 0.14.5 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
