### ISSUE TITLE
atom-bootstrap4 problem

### ISSUE THREAD

**Issue by WebbieFrank** [atom/atom#20638]
Hi everyone,
Sorry if I am putting this in the wrong place, but I didn't have a clue where else to look (although I did try).
My issue is: I installed the atom-bootstrap4 package, but every time I start up atom, I get a whole bunch of red popups to the right, saying:
`Failed to load snippets from 'C:\xxx\xxxx.atom\packages\atom-bootstrap4\snippets\components-button_group.cson'

C:\xxx\xxxxx\.atom\packages\atom-bootstrap4\snippets\components-button_group.cson: Duplicate key 'Button group - Bootstrap 4'`
Apart from that, the package seems to work, but I find it quite annoying always having this on opening atom. So, does anyone know how I can stop that?

Then, a question on making a change in the package: When Bootstrap and/or JQuery gets updated, how can I change the link(s) the package generates for the CDN so that Bootstrap and JQuey are always up-to-date when coding a website?

Thank you in advance and stay safe, everyone.

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-bootstrap4](http://atom.io/packages/atom-bootstrap4) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
