### ISSUE TITLE
Doesn't work right click in editor Error - Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type

### ISSUE THREAD

**Issue by sd-design** [atom/atom#20654]
/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

[Enter steps to reproduce:]
**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.13.6 ( High Sierra) Hardware MacPro 2012
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type
    at callFunction (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:258:17)
    at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:409:10
    at EventEmitter.ipcMain.on.args (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atomic-chrome 0.3.3 
busy-signal 2.0.1 
codeigniter 0.4.0 
codeigniter-utilities 0.2.0 
emmet 2.4.3 
git-gui 0.1.27 
git-plus 8.7.1 
intentions 1.1.5 
linter 2.3.1 
linter-stylelint 4.5.0 
linter-ui-default 1.8.1 
tag 0.5.0 
website-minifier 1.4.0 
```

**Comment by sd-design** [comment]
I found decision - I deleted all packages like Emmet and other. All begin to work

**Comment by sd-design** [comment]
The reason of bug is website-minifier 1.4.0. I checked how work editor with other packages and when install "website-minifier 1.4.0"  - bug is done

**Comment by lee-dohm** [comment]
Thanks for contributing!

It appears that this is being caused by the [website-minifier package](https://atom.io/packages/website-minifier), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://flight-manual.atom.io/faq/) has information on [how to contact the maintainers of any Atom community package or theme](https://flight-manual.atom.io/faq/sections/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/).
