### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by hthomison** [atom/atom#20664]

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by hthomison** [comment]
[IDC.Report.-.How.open.source.is.the.key.to.innovation.pdf](https://github.com/atom/atom/files/4530109/IDC.Report.-.How.open.source.is.the.key.to.innovation.pdf)




[lawenforcement.pdf](https://github.com/atom/atom/files/4530120/lawenforcement.pdf)
[PayPal Live Site.pdf](https://github.com/atom/atom/files/4530123/PayPal.Live.Site.pdf)
