### ISSUE TITLE
Forcing files to terminate with an empty line is a critical bug

### ISSUE THREAD

**Issue by federico-razzoli** [atom/atom#20671]
Forcing a file to terminate with an empty line possibly does 2 things:

- Add an empty line to a files that ends with '//EOF';
- Remove extra empty line(s).

In both cases, the program is deliberately changing something that the user clearly did on purpose. This is because the user wishes to do so, or because the project maintainer chosen so.

Note: this has nothing to do with what anyone thinks about how a file should end. Ultimately, an editor must be something that produces the file that the user wants to produce. Any different behaviour should be considered as a most critical bug (regardless it was introduced on purpose or not).

**Comment by Aerijo** [comment]
Hi @federico-razzoli, the behaviour you are describing is provided by the [`whitespace`](https://github.com/atom/whitespace) builtin package. You can configure it (globally or on a per language basis), or disable it by disabling the package. Additionally, it is a matter of opinion whether such behaviour is a bug or not. Personally, I find it convenient that whitespace is consistently handled in all my files. But it's a moot point because either behaviour can be configured.

It doesn't look for EOF comments, so you'd need to find / make a community package that does so if you want that functionality.
