### ISSUE TITLE
atom setting issue

### ISSUE THREAD

**Issue by mahbub004** [atom/atom#20686]
![Annotation 2020-05-02 095349](https://user-images.githubusercontent.com/64674894/80854701-2262c680-8c5c-11ea-84e7-503cea34b8e6.jpg)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
