### ISSUE TITLE
The Editor has crashed 

### ISSUE THREAD

**Issue by yolanda716** [atom/atom#20682]
Keep getting error message: The Editor has crashed

**Comment by swrobel** [comment]
I'm seeing this as well with the Nightly release on my Mac. Is there some way to provide a crash log?

**Comment by yolanda716** [comment]
I’m not on it daily, but I’ll be sure to report it again if it happens. Thanks.

**Comment by fredcallaway** [comment]
Ditto, just upgraded some packages and I am getting this message every time I start Atom.

**Comment by lojza3d** [comment]
Atom has started crashing with a new Vue.js project I created today. It was OK with the initial state of the project, but after first build, the crashes appeared and so far I was unable to find out what's wrong. Atom is still OK with the previous projects and is able to open them.

Here's the crash report from Atom:
![screenshot_1693](https://user-images.githubusercontent.com/19929447/81102540-130ba380-8f10-11ea-861b-0e1f2fcd1194.png)

Here's the Vue.js project folder content (if it's of any help):
![screenshot_1692](https://user-images.githubusercontent.com/19929447/81102590-261e7380-8f10-11ea-8659-d1151689d525.png)

Here's list of Atom community packages in use:
![screenshot_1694](https://user-images.githubusercontent.com/19929447/81103053-c83e5b80-8f10-11ea-9256-0f8859fa83fe.png)

===
Latest finding: if I disable all of the community packages, Atom will load the problematic Vue.js project with no crash! It seems that some of the package may be the culprit. Will continue investigating...

**Comment by lojza3d** [comment]
OK, that was quick... This community package caused the crash with Vue.js project:
![screenshot_1697](https://user-images.githubusercontent.com/19929447/81104631-19e7e580-8f13-11ea-81c5-54d832459a83.png)

When disabled, Atom loads the project/starts with no problem.

Hope it helps...

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

---

Thanks @lojza3d, since the problem appears to be a community package conflict, I will go ahead and close this one.

If you are still seeing this issue, please submit a new issue following the issue template.

**Comment by shaman2527** [comment]
Hello I have the same problem but every time I start it I get an error I have the latest version is just installed
