### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by clown-b** [atom/atom#20697]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\BaiYu\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:14

TypeError: Cannot read property 'version' of undefined
    at ~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:2638307
    at ~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:939815
    at r (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:936821)
    at n (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1125047)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1125253)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
  6x -9:44.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
