### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/ await'

### ISSUE THREAD

**Issue by CrazyCatCZ** [atom/atom#20698]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/jakub/ await'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '/home/jakub/ await'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:1005283)
    at TreeView.onDrop (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:1012212)
    at HTMLDivElement.<anonymous> (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:14:985843)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-liquid-snippets 0.3.0 
atom-live-server 2.3.0 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autocomplete-javascript 0.0.2 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.39 
highlight-selected 0.17.0 
hyperclick 0.1.5 
intentions 1.1.5 
kite 0.178.0 
linter 2.3.1 
linter-ui-default 1.8.1 
minimap 4.29.9 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
vim-mode-plus 1.36.4 
```

**Comment by CrazyCatCZ** [comment]
I was replacing files and this happens

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
