### ISSUE TITLE
Uncaught Can't find print('Hello World') file

### ISSUE THREAD

**Issue by thombaum** [atom/atom#20709]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find print('Hello World') file

```
At C:\Users\55519\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11

undefined
```

### Commands

```
     -7:34.9.0 core:confirm (input.hidden-input)
 35x -5:40.1.0 core:backspace (input.hidden-input)
     -0:09.2.0 emmet:encode-decode-data-url (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-python 1.16.0 
emmet 2.4.3 
file-icons 2.1.40 
git-control 0.9.0 
highlight-selected 0.17.0 
ipython-run 0.3.1 
kite 0.182.0 
language-ini 1.23.0 
MagicPython 1.1.1 
minimap 4.29.9 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
run 0.0.1 
script 3.26.0 
unity-ui 2.1.11 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [emmet](https://atom.io/packages/emmet) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
