### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.46.0\COVID-1...

### ISSUE THREAD

**Issue by Robertignolo** [atom/atom#20715]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\ASUS\AppData\Local\atom\app-1.46.0\COVID-19_TRACKER_HTML_CSS_JAVASCRIPT-master'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\ASUS\AppData\Local\atom\app-1.46.0\COVID-19_TRACKER_HTML_CSS_JAVASCRIPT-master'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1002525)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1009698)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:983085)
```

### Commands

```
  2x -4:03.9.0 editor:newline (input.hidden-input)
  2x -3:52.7.0 core:backspace (input.hidden-input)
  2x -3:46.6.0 editor:newline (input.hidden-input)
  4x -3:44.3.0 core:backspace (input.hidden-input)
  2x -3:36.1.0 editor:newline (input.hidden-input)
  7x -3:30.5.0 core:backspace (input.hidden-input)
     -3:06.6.0 editor:newline (input.hidden-input)
     -2:46.6.0 core:copy (input.hidden-input)
     -2:45 editor:newline (input.hidden-input)
     -2:44.2.0 core:paste (input.hidden-input)
     -2:42.7.0 editor:newline (input.hidden-input)
  2x -2:38.6.0 core:move-left (input.hidden-input)
  6x -2:37.2.0 core:backspace (input.hidden-input)
     -1:29 core:cut (input.hidden-input)
     -1:22.5.0 core:backspace (input.hidden-input)
     -0:59.7.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Non-Core Packages

```

```

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

---

Although based on the error message, seems like the folder doesn't exist anymore.

If my assumption is correct and you are trying to open `COVID-19_TRACKER_HTML_CSS_JAVASCRIPT-master`, try running in the bash/cmd `cd 'C:\Users\ASUS\AppData\Local\atom\app-1.46.0\COVID-19_TRACKER_HTML_CSS_JAVASCRIPT-master'` to confirm it doesn't exist.

**Comment by Robertignolo** [comment]
Ciae

Il Ven 8 Mag 2020, 19:53 Mazen Elkashef <notifications@github.com> ha
scritto:
