### ISSUE TITLE
Uncaught Can't find walletBalance file

### ISSUE THREAD

**Issue by alexpodchikov** [atom/atom#20729]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find walletBalance file

```
At C:\Users\podch\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11

undefined
```

### Commands

```
     -1:15.1.0 intentions:highlight (input.hidden-input)
     -1:14.8.0 core:copy (input.hidden-input)
     -1:09.1.0 intentions:highlight (input.hidden-input)
     -1:08.7.0 core:paste (input.hidden-input)
     -1:08.1.0 intentions:highlight (input.hidden-input)
     -1:07.8.0 core:save (input.hidden-input)
     -0:52.5.0 intentions:highlight (input.hidden-input)
     -0:52.3.0 emmet:encode-decode-data-url (input.hidden-input)
     -0:18.5.0 intentions:highlight (input.hidden-input)
     -0:18.2.0 editor:toggle-line-comments (input.hidden-input)
     -0:17.3.0 intentions:highlight (input.hidden-input)
     -0:17 core:undo (input.hidden-input)
     -0:16 intentions:highlight (input.hidden-input)
     -0:15.7.0 emmet:encode-decode-data-url (input.hidden-input)
 17x -0:06.9.0 intentions:highlight (input.hidden-input)
     -0:05.9.0 emmet:encode-decode-data-url (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-csslint 2.0.6 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [emmet](https://atom.io/packages/emmet) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
