### ISSUE TITLE
Atom 1.47.0 | JSON - bug in his syntax

### ISSUE THREAD

**Issue by duboloms** [atom/atom#20765]
Now, in last atom version (1.47.0) json syntax bug:

![image](https://user-images.githubusercontent.com/54753636/82467283-2ef37580-9aca-11ea-820e-f83c26562eb7.png)

Must be:

![image](https://i.github-camo.com/0631bf882e84b803601df5cd7833285eb64a3a0a/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4c756b617348656368656e6265726765722f61746f6d2d6a736f6e2d656469746f722f6d61737465722f73637265656e73686f742e706e67)

Yet image:

![image](https://i.stack.imgur.com/QluiS.png)

**Comment by UziTech** [comment]
probably an issue that needs to be fixed in https://github.com/atom/language-json

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
