### ISSUE TITLE
constantly crashes

### ISSUE THREAD

**Issue by bday1978** [atom/atom#20770]
I have never seen such a unstable text editor, what a BIG PIECE OF SH I T.

F U C K   Y O U   A T O M

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
