### ISSUE TITLE
guardn facbook

### ISSUE THREAD

**Issue by Sofyaan707** [atom/atom#20781]
pkg install python -y 
pkg install git -y 
pip install requests 
gitclonehttps://github.com/Noxturnix/guardn
cd guardn 
chmod +x * 
python guardn.py

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
