### ISSUE TITLE
[CI/CD] Last deployment failed after merged PR

### ISSUE THREAD

**Issue by vivi90** [atom/atom#20783]
Deployment failed because of failed test:
```
DecorationManager
  decorations
    it DecorationManager decorations can add decorations associated with markers and remove them
      timeout: timed out after 60000 msec waiting for promise to be resolved or rejected
TextEditorRegistry
  .build
    it TextEditorRegistry .build constructs a TextEditor with the right parameters based on its path and text
      timeout: timed out after 60000 msec waiting for spec promise to resolve
```
See log: https://github.visualstudio.com/Atom/_build/results?buildId=69565&view=logs&j=4fbced83-508e-5fe0-c978-5c71ec0fc506&t=0cce7676-f298-5a2d-7f62-c11c27855377&l=2432
See PR: https://github.com/atom/atom/pull/20741

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
