### ISSUE TITLE
global search no results;mac os

### ISSUE THREAD

**Issue by jinruozai** [atom/atom#20869]
atom:1.47.0 x64
os:mac os 10.15.4
des:create folder on desktop,create a .py file.   like the img below.
command+shift+f,search "print", no results.

and I try many other projects,the same result~

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/59407754/83474373-6b59a500-a4be-11ea-903d-2d4a3de6100c.png">

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
