### ISSUE TITLE
Digit grouping symbol to match system setting

### ISSUE THREAD

**Issue by AlsoScratch** [atom/atom#20863]
I learned that comma is technically the wrong symbol to use for digit grouping. It should always be a space. Fortunately, Windows and macOS have the option to change it.

I wish it was possible for Atom's displaying of numbers to follow my system's language & region settings and not be forced with commas.

<img width="265" alt="Screenshot 2020-05-31 at 11 52 22 PM" src="https://user-images.githubusercontent.com/48752273/83356632-f9883b00-a399-11ea-800c-78ecc3d17954.png">

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
