### ISSUE TITLE
Supporting unstable versions

### ISSUE THREAD

**Issue by Amazeryogo** [atom/atom#20866]
I want atom to support unstable versions of languages like Python 3.9 etc

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
