### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by AmeenSadeqAmeenQasem** [atom/atom#20895]
Markup language, markup language, or text markup language, a set of hints on text that defines how it is organized, described, or formatted, and these languages have been in use for decades, and in recent years they have been used in letter-row systems, word processing, and page editing World Wide Web.

_Originally posted by @AmeenSadeqAmeenQasem in https://github.com/atom/atom/issues/20893#issuecomment-640124821_

**Comment by AmeenSadeqAmeenQasem** [comment]
Welcome <em>Ameen!</em>

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
