### ISSUE TITLE
Sudden problems with saving files

### ISSUE THREAD

**Issue by mattvonrocketstein** [atom/atom#20943]
I suddenly began to experience the same problem described by many people in the (old, closed) issue here- https://github.com/atom/atom/issues/18114

My version info follows: 
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
OS: ubuntu bionic

When I began to experience this problem, I've not attempted to change my configuration, update plugins, or update atom.  Just close/reopen atom itself, and afterwards I could not save the file I was editing, could not open more than one file outside of safe mode.  Obviously an editor which cannot save is useless, and this is extremely frustrating considering I don't think I did anything to trigger the change.  Do I need to turn off auto-updates or atom or atom-plugins or both to have some guarantee that if my editor works today, it will work tomorrow?

I was able to fix the problem by disabling autosave/github packages (a hint from somewhere in the previous ticket ~1 year ago), hopefully this will help someone else.  

Both packages I see are both part of atom core so they cannot be uninstalled.  Maybe they should be disabled by default if they aren't stable.

**Comment by Arcanemagus** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
