### ISSUE TITLE
disable shelling out for environment

### ISSUE THREAD

**Issue by omexlu** [atom/atom#20942]
Hello,

Since a few days, every time I open Atom, 2 windows are opened inside the editor under Ubuntu 20.04.

This was not the case before and do not know how to fix it?
![Bildschirmfoto vom 2020-06-17 14-02-29](https://user-images.githubusercontent.com/3801660/84896000-75c19480-b0a3-11ea-8724-23bd53839035.png)

Is the latest Atom version.

Thanks in advance.

**Comment by micahlt** [comment]
Same issue.  This is incredibly annoying, can we get a fix?

**Comment by yagicandegirmenci** [comment]
Same, also when you add Atom's apt-repository, after `sudo apt update` it says `E: The repository 'http://ppa.launchpad.net/webupd8team/atom/ubuntu focal Release' does not have a Release file.`

**Comment by omexlu** [comment]
This problem seems to be related to the Ubuntu 'Snap' store.

I removed my Atom from the Ubuntu-Software-Center and then installed it via the official Atom repository:
https://flight-manual.atom.io/getting-started/sections/installing-atom/

Now this problem has disappeared.

This snap of Ubuntu is a bit annoying.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by omexlu** [comment]
@Arcanemagus 

No No, this is not from an unofficial release of Atom, but from the official Ubuntu Software Store
![Bildschirmfoto vom 2020-06-17 23-21-31](https://user-images.githubusercontent.com/3801660/84951868-5f422a00-b0f1-11ea-9d95-99094aa9ed3f.png)

And that's where this problem arises.

**Comment by Aerijo** [comment]
@omexlu Atom does not have a snap release, if it exists then it is being distributed by a third party and you should raise any issues with them. See the links in the closing message for why we don’t support unofficial releases and how to install an official release.

**Comment by mib85** [comment]
I edited the file `/var/lib/snapd/desktop/applications/atom_atom.desktop` and changed

`Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/atom_atom.desktop /snap/bin/atom ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom %F`

to

`Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/atom_atom.desktop ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /snap/bin/atom %F`

and now it is working.

**Comment by parsgit** [comment]
This problem reappears after each update 
v : 1.50.0 ubuntu 18

**Comment by ag-hcoder** [comment]
How to fix this issue?

**Comment by parsgit** [comment]
> How to fix this issue?

[https://discuss.atom.io/t/whenever-i-start-atom-it-opens-a-file-weird-file/75721/13](https://discuss.atom.io/t/whenever-i-start-atom-it-opens-a-file-weird-file/75721/13)

1) run in terminal :  sudo snap remove atom
2) [download atom](https://atom.io/download/deb)  and install
