### ISSUE TITLE
Atom 1.48.0 opens with 2 weird files

### ISSUE THREAD

**Issue by dpcat237** [atom/atom#20941]
### Description

Since a few days ago Atom opens with two weird files, as you can see on the attached screenshots. Looks like Atom's tries open them without success. 

PS. I tried reinstalled Atom after removing Atom's files in the config folder of my user.

![atom issue2](https://user-images.githubusercontent.com/388031/84881027-fed1cf00-b095-11ea-8181-ff98235168b9.png)

![atom issue](https://user-images.githubusercontent.com/388031/84881004-f5486700-b095-11ea-9c1c-b68e869660ac.png)

### Steps to Reproduce

1. Open Atom

**Expected behavior:**

Open a last open project.

**Actual behavior:**

Opens two empty files which don't exist:
- ~/ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false
- /usr/bin/atom

After closing these files Atom works as usual.

**Reproduces how often:**

Always

### Versions

1.48.0 

### Additional Information

Atom is installed on Ubuntu 20.04. Correct Atom's path `/snap/bin/atom`.
Let me know if I should provide some additional information.

**Comment by Aerijo** [comment]
`/snap/bin/atom`

Atom does not have a snap distribution, if you are getting it from there then it is distributed by a third party and you should raise the issue with them.
____
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
