### ISSUE TITLE
White screen between window switching

### ISSUE THREAD

**Issue by AlexeyPavlyuck** [atom/atom#20967]
Please Help!!!
OS: Catalina 10.15.5

<img width="1792" alt="Снимок экрана 2020-06-22 в 19 00 58" src="https://user-images.githubusercontent.com/63820958/85309562-73a07100-b4bb-11ea-9539-4afa12a4dd82.png">

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
