### ISSUE TITLE
Atom Crashes frequently in 1.48 version

### ISSUE THREAD

**Issue by blueedgetechno** [atom/atom#21001]
Atom version 1.48
os: windows

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
