### ISSUE TITLE
When i create folder with symbol colon (  :  ) atom goes crazy

### ISSUE THREAD

**Issue by duboloms** [atom/atom#21050]
When i create folder with symbol colon (  :  ) atom goes crazy, he create tab with name of folder and will crashes when i click on this tab!
Folder file icon shows like a file without an extension.

P.S.
If you want a video of this happening, I'll provide it

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
