### ISSUE TITLE
ATOM_DISABLE_SHELLING_FOR_ENVIRONMENT=false

### ISSUE THREAD

**Issue by mohamedsgap** [atom/atom#21098]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * [X] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * [X] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * [X] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * [X] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Every time I open Atom, I found 2 black pages
2. First page with title "ATOM_DISABLE_SHELLING_FOR_ENVIRONMENT=false"
3. Second page with title "atom ---- /user/bin" 

**Expected behavior:**
So every time I open Atom I should find the last project I was working on it 

**Actual behavior:**
Two weird blank pages showed, every time open Atom

### Versions

apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.49.0
python 2.7.18rc1
git 2.25.1

running on Ubuntu Linux, 20.0.4
### Additional Information

![atom_error_2](https://user-images.githubusercontent.com/30293804/88253969-efa4f900-ccb3-11ea-978c-5bcbc6012643.png)

![atom_error_1](https://user-images.githubusercontent.com/30293804/88253992-f6cc0700-ccb3-11ea-8607-5d8ab8ca9d9f.png)

**Comment by Aerijo** [comment]
This issue has only been seen on the unofficial Snap distribution, so you will have to raise this issue with whoever is providing it.
____
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by mohamedsgap** [comment]
@Aerijo Thanks for your response, I think I'm sure that I already installed the official version of Atom 9 months ago on Ubuntu 18.0.4, before snap integrated in 20.0.4, so let me check and come back to you and fill the new issue if it any problem raises!
