### ISSUE TITLE
battery save mode

### ISSUE THREAD

**Issue by EzekielParis** [atom/atom#21148]
atom seems awesome...
one of the best second to Vs code...
but quite a sucker for CPU usage and battery.. but not everyone enjoys using a whole lot of processing power (game) running a ide

I thought disabling some of the inbuilt language support like in Vs code reduces battery usage  but no ... it but it seems some packages are still loaded

I would like to request for a slimmer atom and 
more hackable atom that has battery save mode (having laoading less package and some optimization features) to help in utilizing less battery resources... I believe

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
