### ISSUE TITLE
About char ✓ 's question

### ISSUE THREAD

**Issue by PC-Max** [atom/atom#21149]
Saying directly, l find you can't input '✓' and save in atom
You can input this code to try about it.
`
#include <stdio.h>
int main(void)
{
        printf("✓");
        return 0;
}
`
if you input this in atom, you can find that you can't save.
if you click "save as", when you turn into the file again, you can find that the '✓' and below's content isn't load.
![show](https://user-images.githubusercontent.com/64883070/89374989-51874900-d71f-11ea-9ce1-bce5ccd222d7.gif)

**Comment by Arcanemagus** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
