### ISSUE TITLE
error showing "the editor has crashed"

### ISSUE THREAD

**Issue by suraj220797** [atom/atom#21154]
![image](https://user-images.githubusercontent.com/44130242/89513620-697bcd00-d7f2-11ea-96a6-c286f2c60941.png)

showing this error while trying to open it

**Comment by NjeTeXeQ** [comment]
+1

**Comment by sadick254** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
