### ISSUE TITLE
error "the editor has crashed"

### ISSUE THREAD

**Issue by NjeTeXeQ** [atom/atom#21157]
**pls help me**

![image](https://user-images.githubusercontent.com/68875411/89654314-bdf17c00-d8c8-11ea-87d0-88a48c27aeca.png)

**Comment by sadick254** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
