### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by YDavid97** [atom/atom#21173]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At D:\Atom x64\resources\app\static\<embedded>:14

TypeError: Cannot read property 'version' of undefined
    at D:/Atom x64/resources/app/static/<embedded>:14:2635690
    at D:/Atom x64/resources/app/static/<embedded>:11:941157
    at r (D:/Atom x64/resources/app/static/<embedded>:11:938163)
    at o (D:/Atom x64/resources/app/static/<embedded>:14:1122275)
    at ChildProcess.n.process.on.e (D:/Atom x64/resources/app/static/<embedded>:14:1122481)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
  2x -1:26.4.0 core:confirm (input.hidden-input)
     -1:03.4.0 editor:newline (input.hidden-input)
  9x -1:00.9.0 core:backspace (input.hidden-input)
     -0:52.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
