### ISSUE TITLE
new install, and it's unresponsive

### ISSUE THREAD

**Issue by slf495** [atom/atom#21192]
First off, I barely know what I am doing. So my windows crashed and i am reinstalling everything. I am trying to use atom to modify marlin for my 3d printer, and it's unresponsive upon installing. I have tried reinstalling and such, with now luck. anyone have any ideas?
windows 10 64 bit if that help at all

**Comment by sadick254** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by slf495** [comment]
sorry, not sure what you mean? mind lending a hand so i can get this answered please?

**Comment by jeff-hykin** [comment]
I know redirection is annoying, but if you could to The Atom FAQ on Discuss it's built to have conversations about those kinds of challenges.

GitHub is used for reporting bugs with the editor itself

**Comment by slf495** [comment]
K, will try later when I get the chance
