### ISSUE TITLE
Uncaught Error: null

### ISSUE THREAD

**Issue by bopbud** [atom/atom#21191]
[Enter steps to reproduce:]

1. ...trying to connect to lisp.  Atom-slime works fine. I uninstalled atom-slime and tried slimea.  Won't connect.
2. ... /usr/bin/ccl is my lisp ~/src/slime-master is where slime resides.  Same as/works in emacs and atom slime. Slima won't start slime apparently.  Kubuntu 20.04

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04.1
**Thrown From**: 'slima' package vundefined

### Stack Trace

Uncaught Error: null

```
At /home/gkhouri/.atom/packages/slima/node_modules/temporary/lib/file.js:100

Error: null
    at /packages/slima/node_modules/temporary/lib/file.js:100:73
    at FSReqCallback.oncomplete (fs.js:150:20)
```

### Commands

```
     -2:03.1.0 slime:restart (input.hidden-input)
  3x -1:52.3.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-slime 2.8.0 
language-common-lisp 0.9.5 
language-lisp 0.2.0 
lisp-paredit 0.7.0 
```

**Comment by bopbud** [comment]
I tried starting from a clean install with no ~/.atom folder as well

**Comment by sadick254** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-slime](https://atom.io/packages/atom-slime) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
