### ISSUE TITLE
'type undefined not recognized'

### ISSUE THREAD

**Issue by melaniewilson** [atom/atom#21213]
After toggling, I am getting this error. on Mojave 10.14.6
![Screen Shot 2020-08-23 at 11 53 30 AM](https://user-images.githubusercontent.com/6945649/90986449-ba502d00-e537-11ea-99df-c14e3c3a63ee.png)

**Comment by sadick254** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
