### ISSUE TITLE
นน

### ISSUE THREAD

**Issue by takumi1128** [atom/atom#21215]
https://<redirect url>?apiKey={apiKey}&responseToken={jwtToken}

**Comment by sadick254** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by anwarnafa** [comment]
- _**

1. 

- [ ] 

>  @`
 #![45EF3BA0-E7CF-406D-AA88-9CEC3CB52518](https://user-images.githubusercontent.com/69494830/91675674-d3636a00-eb45-11ea-96fd-2eb58dba289c.jpeg)
`

**_
