### ISSUE TITLE
[atom 1.51.0] trap int3 - Atom does not start - Ubuntu 20.04.1 - snap

### ISSUE THREAD

**Issue by TehWan** [atom/atom#21291]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://flight-manual.atom.io/faq/>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom crashes on startup with an int3. Atom is installed through snap. Purged the installation and reinstalled, followed all debugging advice, to no avail.

### Steps to Reproduce

1. Launch atom

**Expected behavior:**

Atom launches as usual.

**Actual behavior:**

Atom reports a sigtrap through `dmesg`: (from 4 different attempts)
```
[85449.742298] traps: atom[88594] trap int3 ip:55a25bcab627 sp:7ffdef0a18f0 error:0 in atom[55a259d87000+5024000]
[85652.644715] traps: atom[88840] trap int3 ip:55ae5acaa627 sp:7ffd1cefe730 error:0 in atom[55ae58d86000+5024000]
[85655.479822] traps: atom[88866] trap int3 ip:558216a46627 sp:7fffb4e5f630 error:0 in atom[558214b22000+5024000]
[85657.797158] traps: atom[88893] trap int3 ip:55ba5f605627 sp:7ffdaaa43180 error:0 in atom[55ba5d6e1000+5024000]
```

**Reproduces how often:**

100% since 1.51.0

### Versions

```
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.51.0
python 3.8.2
git 2.25.1
```

### Additional Information

Running through gdb produces the following output:
```
Reading symbols from atom...
(No debugging symbols found in atom)
(gdb) r
Starting program: /snap/bin/atom 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5b2c700 (LWP 94112)]
[New Thread 0x7ffff532b700 (LWP 94113)]
[New Thread 0x7ffff4b2a700 (LWP 94114)]
[New Thread 0x7fffeffff700 (LWP 94115)]
[New Thread 0x7fffef7fe700 (LWP 94116)]
[New Thread 0x7fffeeffd700 (LWP 94117)]
[Thread 0x7fffef7fe700 (LWP 94116) exited]
[Thread 0x7fffeeffd700 (LWP 94117) exited]
[Thread 0x7fffeffff700 (LWP 94115) exited]
[Thread 0x7ffff4b2a700 (LWP 94114) exited]
[Thread 0x7ffff532b700 (LWP 94113) exited]
[Thread 0x7ffff5b2c700 (LWP 94112) exited]
process 94108 is executing new program: /snap/core/9804/usr/bin/snap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7d3d700 (LWP 94118)]
[New Thread 0x7ffff753c700 (LWP 94119)]
[New Thread 0x7ffff6d3b700 (LWP 94120)]
[New Thread 0x7ffff653a700 (LWP 94121)]
[New Thread 0x7ffff5d39700 (LWP 94122)]
[New Thread 0x7ffff5538700 (LWP 94123)]
[Detaching after vfork from child process 94124]
[Thread 0x7ffff5d39700 (LWP 94122) exited]
[Thread 0x7ffff5538700 (LWP 94123) exited]
[Thread 0x7ffff653a700 (LWP 94121) exited]
[Thread 0x7ffff6d3b700 (LWP 94120) exited]
[Thread 0x7ffff753c700 (LWP 94119) exited]
[Thread 0x7ffff7d3d700 (LWP 94118) exited]
process 94108 is executing new program: /snap/core/9804/usr/lib/snapd/snap-confine
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
need to run as root or suid
--Type <RET> for more, q to quit, c to continue without paging--
[Inferior 1 (process 94108) exited with code 01]
(gdb) 
```

Somehow it is asking for root permission.

**Comment by Aerijo** [comment]
Atom doesn't provide a snap distribution. You would need to contact whatever third party maintains it in this case. Official installation methods can be found in the flight manual
_____
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
