### ISSUE TITLE
racer.racerBinPath is not set in your config.

### ISSUE THREAD

**Issue by hunxinkeji** [atom/atom#21330]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: Atom Core

### Stack Trace

racer.racerBinPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -3:24.9.0 core:copy (input.hidden-input)
     -3:23.5.0 editor:newline (input.hidden-input)
     -3:23.1.0 core:paste (input.hidden-input)
     -3:06.5.0 core:backspace (input.hidden-input)
  3x -2:53.7.0 core:save (input.hidden-input)
  2x -1:43.1.0 core:backspace (input.hidden-input)
 10x -1:37.1.0 core:save (input.hidden-input)
  2x -1:02.5.0 core:undo (input.hidden-input)
  2x -1:00.0 core:save (input.hidden-input)
     -0:28.7.0 editor:newline (input.hidden-input)
     -0:27.6.0 core:backspace (input.hidden-input)
     -0:24.4.0 core:copy (input.hidden-input)
  2x -0:23.3.0 editor:newline (input.hidden-input)
     -0:22.6.0 core:paste (input.hidden-input)
  2x -0:21.1.0 core:backspace (input.hidden-input)
     -0:01.8.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
autocomplete-solidity 0.3.4 
busy-signal 2.0.1 
go-debug 1.7.0 
go-plus 6.1.0 
go-rename 0.3.0 
go-signature-statusbar 1.2.3 
intentions 1.1.5 
language-ethereum 0.3.9 
language-rust 0.4.12 
language-scala 1.1.10 
language-solidity 0.1.1 
linter 2.3.1 
linter-rust 1.0.1 
linter-solium 0.0.5 
linter-ui-default 1.8.1 
racer 0.20.0 
rust-api-docs-helper 0.5.1 
```

**Comment by sadick254** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-racer](https://github.com/edubkendo/atom-racer) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
