### ISSUE TITLE
Image displaying issue

### ISSUE THREAD

**Issue by mittal96** [atom/atom#21408]
I have been trying to put images in my code but they are not showing in preview mode.  I have attached the screenshot below for more details.

![img](https://user-images.githubusercontent.com/62978452/94530380-a7c4c400-0258-11eb-8f59-7a6b5bf02a01.png)

**Comment by sadick254** [comment]
@mittal96 What package are you using for the preview?

**Comment by mittal96** [comment]
Hello,


I am using *Preview HTML*. Actually inages were showing some days ago but
suddenly they are not displaying. I don't know why.

**Comment by sadick254** [comment]
Could you provide a link to the package?

**Comment by mittal96** [comment]
Yeah sure.

atom.io/packages/atom-html-preview

**Comment by sadick254** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom html preview](https://github.com/harmsk/atom-html-preview) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
