### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages\livereload\lib/../no...

### ISSUE THREAD

**Issue by IgorSSG** [atom/atom#21436]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: 'livereload' package vundefined

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\USR\.atom\packages\livereload\lib/../node_modules/livereload-js/dist/livereload.js'

```
At fs.js:122

Error: ENOENT: no such file or directory, open 'C:\Users\USR\.atom\packages\livereload\lib/../node_modules/livereload-js/dist/livereload.js'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:138:31)
    at Object.readFileSync (fs.js:353:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at Server.handleRequest (/packages/livereload/lib/server.js:216:37)
    at Server.emit (events.js:194:13)
    at parserOnIncoming (_http_server.js:694:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
```

### Commands

```
  4x -9:12.6.0 core:save (input.hidden-input)
     -1:00.5.0 link:open (span.syntax--markup.syntax--underline.syntax--link.syntax--http.syntax--hyperlink)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
color-picker 2.3.0 
emmet 2.4.3 
minimap 4.29.9 
open-in-browser 0.5.2 
```

**Comment by sadick254** [comment]
Thanks for contributing!

It appears that this is being caused by the [livereload](https://github.com/taggon/livereload) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
