### ISSUE TITLE
Slash substitution problem; atom.cmd location

### ISSUE THREAD

**Issue by saizai** [atom/atom#21448]
https://github.com/atom/atom/blob/6b50aed572df30776403219bbb48e4be85251df1/resources/win/atom.sh#L14-L15

1. after line 14:
```
echo $ATOMCMD
/home/saizai/atom.cmd
```

after line 15:
```
echo $ATOMCMD
/\//\h/\o/\m///\s//\i/\z//\i/\///       /\o/\m/\./%     
```

Um… probably not what was desired.

2. For that matter, there isn't a `~/atom.cmd`. It's in `C:\Users\saizai\AppData\Local\atom\bin\atom.cmd`…

So, shouldn't this be using the same method as https://github.com/atom/atom/blob/master/resources/win/apm.sh, i.e. `"$(dirname "$0")/../app/apm/bin/atom" "$@"` ?

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by saizai** [comment]
@darangi Um… I documented everything in the template (and more) — just not with the template's format.

Doesn't make the issue go away. Closing is not a reasonable way to say ¨please document X better¨, if indeed there is anything to document better.

**Comment by saizai** [comment]
@aminya

**Comment by aminya** [comment]
@saizai Just open another issue with the proper format. The text of the issues seems vague to me as well.
