### ISSUE TITLE
Atom Local Development env setup failure - node_module failure

### ISSUE THREAD

**Issue by gopipofficial** [atom/atom#21460]
Hi team, as part of hactoberfest I would like to contribute myself to the editor I'm using the day to day life. I ran up to script\bootstrap as given in this [document](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/) I dint faced any issue till this command execution. but when I run atom --dev I got the error as mentioned in the below screenshot. 

![image](https://user-images.githubusercontent.com/18674571/95534281-003b5480-0a03-11eb-90e0-4e9faaaca9b9.png)

kindly help me to fix this issue

**Comment by darangi** [comment]
Hi @gopipofficial , do you still have this issue?

**Comment by gopipofficial** [comment]
Yes please help me. I dunno what to do now. I have started to do some participation in atom contributor but due to this issue I cant proceed further.

**Comment by sadick254** [comment]
Hey @gopipofficial, this is caused by mismatch of node version. It could be you are using a different node version than what is required. Try using [nvm](https://github.com/nvm-sh/nvm) to set the node version to `12.0.0` and then you could run `npx electron-rebuild -v 5.0.13`. You could also check out the [node releases](https://nodejs.org/en/download/releases/). `NODE_MODULE_VERSION` is stated for every release.

**Comment by sadick254** [comment]
The above information should get you up and running.

----

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
