### ISSUE TITLE
Help me with Hacking Atom Core 

### ISSUE THREAD

**Issue by ducky123456** [atom/atom#21511]
I cant seem to get setting up atom with the github repo working. can someone give me a step by step tutorial and the requirements for the setup??? Thanks, Ducky123456

**Comment by darangi** [comment]
Hi @ducky123456 what problems are you facing? have you tried https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/

**Comment by ducky123456** [comment]
I have this problem that atom is not in path. can you give me step by step

**Comment by UziTech** [comment]
@ducky123456 if you build Atom from source instead of running an installer you will have to add atom to your path manually. You can search google to find out how to do that in your OS.

**Comment by sadick254** [comment]
What @UziTech described should be sufficient to get you up and running. Am going to close this for now.

---
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
