### ISSUE TITLE
Terminal issue 

### ISSUE THREAD

**Issue by davidchinonso123** [atom/atom#21549]
My terminal in atom is not giving me an output 
Running atom from terminal returns an error: "-bash: /usr/local/bin/atom: No such file or directory."

**Comment by UziTech** [comment]
Which terminal package are you using? And what version of Atom are you using?

**Comment by davidchinonso123** [comment]
I am using the latest atom 1.39.1 and I am using platformio-ide-terminal

Sent from Mail for Windows 10

**Comment by davidchinonso123** [comment]
I also installed python 3.9 from Microsoft store I am new to python please I need help


Sent from Mail for Windows 10

**Comment by davidchinonso123** [comment]
This is another error I am getting, I cannot see the output of what I did such as hello world

Sent from Mail for Windows 10

**Comment by davidchinonso123** [comment]
This are the errors I am having please help me out what should I do Tony Brix
Sent from Mail for Windows 10

**Comment by UziTech** [comment]
> I am using the latest atom 1.39.1 and I am using platformio-ide-terminal

The latest Atom version is 1.52.0 and platformio-ide-terminal is not maintained. You should download the latest version of Atom from https://atom.io and try [x-terminal](https://atom.io/packages/x-terminal) or [terminus](https://atom.io/packages/terminus) for a terminal.

**Comment by sadick254** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by davidchinonso123** [comment]
Okay thank you so much Tony Brix I would do just that now

**Comment by davidchinonso123** [comment]
I have deleted the Atom and downloaded pycharm
I did what you said I should I downloaded the latest version and downloaded
the terminal but it still not working out so I had to delete it and
download pycharm
