### ISSUE TITLE
Reading and Editing .xlsx or .xls ?

### ISSUE THREAD

**Issue by tassosblackg** [atom/atom#21574]
Hi, 
Is there a way to read and edit .**xlsx** or .**xls** files with atom? I am using many different datasets files for my work sometimes.csv but other it is an excel file, which I want at least to **preview** it and maybe the editing something small without moving to excel/spreadsheet.
The only package I found is open-unsupported-files which practically makes xdg-open with the spreadsheet.

VS code has a similar package, is a pity that atom doesn't

**Comment by Amazeryogo** [comment]
can this package help you in any way? 

https://atom.io/packages/open-unsupported-files

**Comment by Close2Angelz** [comment]
Borders has accessibility to govern rule in set lang. Research will be beneficial.. Prayers for you all enjoy your night buttons..

**Comment by Close2Angelz** [comment]
Compare in an active cross platform..  ```
IOS PKG Linux has border issues compared to iOS .. card replacement nessicary.
```
```
```

**Comment by Close2Angelz** [comment]
NLP Tools & Boda from Berkeley's many strong.. an excellent example of language variable integration.. compare consult..

**Comment by therobgirl** [comment]
What the fuck is this shit
Anyways... 🤓🤩✌️🦅🤔🤔🤔🤔🤔

**Comment by tassosblackg** [comment]
@Amazeryogo if you read carefully my question I mention this package, it just opens the .xlsx with excel when double click.
I want at least a package to preview my files before using them without opening more windows/programs. there is something similar in VS code, but not in Atom ;) .

**Comment by tassosblackg** [comment]
@therobgirl It seems like a spam bot or someone is high 😄😄!

**Comment by therobgirl** [comment]
Well shit . Haha 😂

**Comment by Close2Angelz** [comment]
Depfu;  codebased cod3ship,orSentry.. I prayed for you buttons.. all of y'all.LeeAnn Clark615456761610026 Mona RdMurfreesboro,%N. 37129leeannclark2017@gmail.comSent from my REVVL 4+On Oct 23, 2020 5:41 AM, Tassos Karageorgiadis <notifications@github.com> wrote:
Hi,
Is there a way to read and edit .xlsx or .xls files with atom? I am using many different datasets files for my work sometimes.csv but other it is an excel file, which I want at least to preview it and maybe the editing something small without moving to excel/spreadsheet.
The only package I found is open-unsupported-files which practically makes xdg-open with the spreadsheet.
VS code has a similar package, is a pity that atom doesn't

**Comment by Youseifhussein** [comment]
Stop this spam
Don't enjoy with me🔪

في الأحد، ٢٥ أكتوبر ٢٠٢٠ ١٠:٤٠ ص Close2Angelz <notifications@github.com>
كتب:

> Depfu;  codebased cod3ship,orSentry.. I prayed for you buttons.. all of
> y'all.LeeAnn Clark615456761610026 Mona RdMurfreesboro,%N.
> 37129leeannclark2017@gmail.comSent from my REVVL 4+On Oct 23, 2020 5:41

**Comment by therobgirl** [comment]
[]()Hey! **do any of you guys have a code for the new iPhone 📲 _** also @tassosblackg why u gonna call me out like that haha it's cool tho you probably right anyways I hope all y'all have a great day/night and I saw the new GitHub site omg I love it 😻 beautiful 🤩 I'm so proud to be maybe even a little tiny part of it ✌️💙😀

**Comment by jeff-hykin** [comment]
So this issue is that nobody has made a package for excel files? That would be a great feature, but I don't know that posting an issue on the Atom core repo makes sense. The repo is only for atom core, and specifically asks that you disable packages because bugs in packages are someone else's responsibility. You might want to ask about it in the Atom discourse to see if someone knows of an extension or is interested in building one.

**Comment by sadick254** [comment]
You can post a message on [Discuss, the official Atom and Electron message board](https://discuss.atom.io/c/packages) to see if anyone from the community is willing to try and build it

-----
In any case, because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). But I'm also going to label this with `package-idea` so that others searching for suggestions here can find this.

Thanks again for your interest in Atom :grinning:
