### ISSUE TITLE
autocomplete not working at all

### ISSUE THREAD

**Issue by hahamuffingobrr** [atom/atom#21592]
the autocomplete is not working at all ive tried everything like literally everything. i tried reinstalling and yeah i want it to work

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
