### ISSUE TITLE
This kind of OpenType tags

### ISSUE THREAD

**Issue by AlsoScratch** [atom/atom#21678]
## Summary

I hope Atom can implement this form of OpenType: (not sure if there's a proper name for it)
<img width="835" alt="Screenshot 2020-11-09 at 5 31 27 PM" src="https://user-images.githubusercontent.com/48752273/98523961-86241700-22b1-11eb-9972-6b79477ff1cc.png">
It uses numbers after the OpenType tag for separate variants.
## Motivation

This is being used by a font called [Iosevka](https://typeof.net/Iosevka/). You may check it out under _Variants à la Carte_.

**Comment by Arcanemagus** [comment]
You can configure this using [Style Tweaks](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks).

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by AlsoScratch** [comment]
Nevermind, I made a mistake. My bad!
