### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sectionHeadings' of undefined

### ISSUE THREAD

**Issue by denjiius** [atom/atom#21689]

**Comment by denjiius** [comment]
> [Enter steps to reproduce:]
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.51.0 x64
> **Electron**: 5.0.13
> **OS**: linux 5.4.0-26-generic
> **Thrown From**: Atom Core
> 
> ### Stack Trace
> Uncaught TypeError: Cannot read property 'sectionHeadings' of undefined
> 
> ```
> At /home/denis/.var/app/io.atom.Atom/data/packages/simplified-russian-menu/tools/settings.coffee:85
> 
> TypeError: Cannot read property 'sectionHeadings' of undefined
>     at applySectionHeadings (/packages/simplified-russian-menu/tools/settings.coffee:85:3)
>     at HTMLAnchorElement.applyInstallPanelOnSwitch (/packages/simplified-russian-menu/tools/settings.coffee:68:3)
> ```
> 
> ### Commands
> ```
>   2x -9:16.4.0 core:paste (div.line)
>  20x -9:03.5.0 core:backspace (input.hidden-input)
>      -4:59.8.0 core:paste (span.syntax--text.syntax--plain.syntax--null-grammar)
> ```
> 
> ### Non-Core Packages
> ```
> atom-beautify 0.33.4 
> atom-i18n 0.24.0 
> auto-encoding 0.7.2 
> autoclose-html 0.23.0 
> django-atom 0.2.4 
> file-icons 2.1.44 
> fold-lines 0.2.2 
> highlight-selected 0.17.0 
> minimap 4.29.9 
> pigments 0.40.6 
> python-autopep8 0.1.3 
> simple-drag-drop-text 0.5.0 
> svg-preview 0.14.0 
> ```

**Comment by sadick254** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
