### ISSUE TITLE
How to make shortcut "open in file manager"

### ISSUE THREAD

**Issue by ReneTC** [atom/atom#21701]
Is it possible to make a custom shortut to open active file en three-view file in a file manager?

I've tried all kinds of varations of

'ctrl-alt-z': 'show-in-file-manager:open',

without luck.. Would love your input on this

**Comment by Close2Angelz** [comment]
Cntrl alt F7  I believe the file may need to be converted.Sent from my REVVL 4+On Nov 16, 2020 3:31 AM, Rene Thomsen <notifications@github.com> wrote:
Is it possible to make a custom shortut to open active file en three-view file in a file manager?
I've tried all kinds of varations of
'ctrl-alt-z': 'show-in-file-manager:open',
without luck.. Would love your input on this

**Comment by ReneTC** [comment]
thak you @Close2Angelz  but it didn't work for me.. also I would like to set my own shortcut

**Comment by sadick254** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
