### ISSUE TITLE
What's the icon in screenshot of atom.io webpage?

### ISSUE THREAD

**Issue by ghsgz** [atom/atom#21921]
I just found that icons in the screenshot of atom.io are awesome, and the atom editor in my machine(Win10) is different. If there is an icon theme I can download to keep the same as this screenshot? Thanks!

![](https://github-atom-io-herokuapp-com.freetls.fastly.net/assets/index-teletype-screenshot-1de356892e9bab0f5a1e95b4a003dfecaab0d9e67a91fd60b63006a32f147db0.png)

**Comment by sadick254** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
