### ISSUE TITLE
Atom cannot quit

### ISSUE THREAD

**Issue by ThatXliner** [atom/atom#21931]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I cannot quit Atom

### Steps to Reproduce

1. Close all Atom windows
2. Quit Atom from the dock like this:

<img width="287" alt="Screen Shot 2021-02-05 at 2 27 06 PM" src="https://user-images.githubusercontent.com/66848002/107095758-3b397300-67be-11eb-88ee-87bc4a320ba9.png">

**Expected behavior:**

Atom to quit

**Actual behavior:**

It doesn't quit

**Reproduces how often:**

100%

### Versions

`atom --version | cat <(apm --version) | strip-ansi |  pbcopy`:

```
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 3.6.12
git 2.24.3
```
### Additional Information

I haven't tested safe mode. Also, I'm on macOS 10.15.17

**Comment by M3TIOR** [comment]
Thanks for submitting the issue @ThatXliner! :tada: I'm really sure the core dev team appreciates it; I'm just a heavy user and soon to be contributor.

* __If you could, please follow the instructions in the issue `prerequisites` section.__ It helps the developers diagnose where issue submissions are comming from. Those steps could even help you resolve the problem on your own. 

Perhaps it's being caused by an issue within a package you recently installed? It could be an issue with Electron; the engine that Atom is built upon too. If either were the case, then this isn't really the place to post the issue.

**Comment by elliotcubit** [comment]
Possible duplicate of #21823

**Comment by ThatXliner** [comment]
> Possible duplicate of #21823 

#2183 didn't specify Atom version

**Comment by ThatXliner** [comment]
I can't reproduce anymore after force-quitting Atom
