### ISSUE TITLE
Move .atom config to $XDG_CONFIG_HOME on linux

### ISSUE THREAD

**Issue by ReAzem** [atom/atom#2199]
From feedesktop.org:

$XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

Source: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

Thanks!

**Comment by kevinsawicki** [comment]
There is now full support for configuring the config location via the `ATOM_HOME` environment variable via #5385.

I'm going to close this issue out since changing the default location at this point is unlikely given how many Atom installs are already out there.

**Comment by ReAzem** [comment]
So Atom will never ever respect the freedesktop standard? Its a shame, 1.0 wasn't released yet. Now should be the right moment to make things right.

**Comment by kevinsawicki** [comment]
Switching to this standard would require reworking more than just one path since `XDG_CACHE_HOME` should be used for Atom's compile cache, and `XDG_RUNTIME_DIR` should probably be used for installed packages & themes.

Currently these are all stored under `~/.atom`. Having all of them co-located makes it incredibly easy to backup, transfer, and clean out your machine of all Atom related files. Also using the same path on all platforms makes Atom predictable for people using multiple platforms.

**Comment by cgtx** [comment]
One of the benefits of XDG Base Directory Specification is that a user can back up configurations and data, but not cache.  Forcing all of Atom's data under one directory means that it is much more difficult to do this.

**Comment by vially** [comment]
> using the same path on all platforms makes Atom predictable for people using multiple platforms

I think people using multiple platforms are accustomed with different operating systems having different file system layouts. If we were to take this reasoning to the extreme you might be tempted to install the Atom binary in a "/usr/Program Files" directory while on a Linux/Mac machine and I don't think there's anyone who would argue that that's just plain wrong.

Given that Atom is still not considered stable I think it's still not too late to change this to support the XDG standard. And while I agree that doing it properly requires a little bit more work to be fully compliant, I think that if the Atom team shows interest in supporting the standard, someone might be able to come up with a pull request to implement it.

**Comment by malko** [comment]
:+1:

**Comment by malko** [comment]
:+1: 
I'm working on different platforms and i'm always looking first for platform specific path in first place.

**Comment by Dremora** [comment]
Changing default location should never be an issue as long as it's done in a backwards-compatible way, no matter how large the user base is.
A common workaround is to define not one, but multiple config paths, and pick up the first existing one. This list of paths should be OS-specific, with `$ATOM_HOME` taking the precedence over everything else. Then, if the config directory is nowhere to be found, it should be created at the first OS-specific location.

I've noticed, however, that on OS X, the configuration is spread across two directories — `~/.atom` and `~/Library/Application Support/Atom`. The latter seems to be used for blink-specific files, while the earlier is for user configuration. This unfortunately doesn't help, because `~/Library/Application Support/Atom` is the default location for non-plist configuration on OS X, and it's the one where `~/.config` should go. [Looks like](http://stackoverflow.com/questions/23621181/how-to-uninstall-atom-text-editor-on-linux) the Linux version has an additional directory ` ~/.config/Atom-Shell` which is likely the same (strangely enough, it's called `Atom`, not `Atom-Shell` on OS X).

**Comment by rbellamy** [comment]
I'm on Linux (Arch) and have both $ATOM_HOME/.atom (because I set it in my .profile to $XDG_CONFIG_HOME/.atom) and ~/.config/Atom (*NOT* ~/.config/Atom-Shell).

**Comment by colemickens** [comment]
I also have `.atom` and `.config/Atom`. Is one of them old now?
