### ISSUE TITLE
pdf-viewer does not work as of 

### ISSUE THREAD

**Issue by bububox** [atom/atom#22224]
Hi,

pdf-viewer does not work anymore as of version 1.56.0. After compiling my latex document, a tab opens but it is empty.  Downgrading to 1.55.0 fixes the problem and pdf-viewer shows normally.

**Comment by sadick254** [comment]
Which pdf-viewer are you using?

**Comment by MeindertHH** [comment]
Also raised at https://github.com/izuzak/atom-pdf-view/issues/238.

**Comment by sadick254** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-pdf-viewer](https://github.com/izuzak/atom-pdf-view) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
