### ISSUE TITLE
two windows open; increase/decrease font size in one => does the same for the other. this is bad

### ISSUE THREAD

**Issue by rodeezy** [atom/atom#22254]

**Comment by UziTech** [comment]
Why is it bad?

**Comment by sadick254** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by rodeezy** [comment]
@UziTech not having the option is bad. my use case is two monitors of uneven sizes/resolutions.
@sadick254 kk i'll get around to making a new issue, thank you

**Comment by sadick254** [comment]
@rodeezy let me know once the new issue is created. For now I will close this one.
