### ISSUE TITLE
PDF files do not open

### ISSUE THREAD

**Issue by vis2x** [atom/atom#22274]
I have these packages installed:
- build
- build-latex
- busy-signal
- language-latex
- latex
- latexmk
- latextools
- pdf-view
it builds successfully: https://i.imgur.com/D0qKPcB.png

This is what the Latextools console shows when I do the build https://i.imgur.com/0qGFCCN.png

and the changes to the pdf are made, i can open it in the browser etc

the problem is that it doesn't open in atom itself.. it's completely blank

this is what it looks like in atom https://i.imgur.com/lWM2qKR.png 

Does anyone know how to fix this? Thanks

**Comment by sadick254** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-pdf-viewer](https://github.com/izuzak/atom-pdf-view) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
