### ISSUE TITLE
racer.racerBinPath is not set in your config.

### ISSUE THREAD

**Issue by N7954** [atom/atom#22338]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

racer.racerBinPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -0:52.7.0 core:move-right (input.hidden-input)
 11x -0:51.8.0 core:select-left (input.hidden-input)
     -0:46.1.0 intentions:highlight (input.hidden-input)
     -0:46 core:save (input.hidden-input)
  2x -0:34.2.0 editor:newline (input.hidden-input)
  2x -0:33.4.0 core:move-up (input.hidden-input)
     -0:32 editor:newline (input.hidden-input)
     -0:31.4.0 snippets:next-tab-stop (input.hidden-input)
     -0:31.4.0 snippets:expand (input.hidden-input)
     -0:31.4.0 editor:indent (input.hidden-input)
  2x -0:11.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy-signal 2.0.1 
essence-dark-syntax 0.2.1 
ide-rust 0.22.0-beta.3 
intentions 1.1.5 
kite 0.204.0 
language-rust 0.4.12 
linter 3.3.1 
linter-rust 1.0.1 
linter-ui-default 3.3.1 
racer 0.20.0 
rust-dark-syntax 0.2.0 
rusty-dark-syntax 0.7.0 
script 3.31.1 
```

**Comment by ThatXliner** [comment]
This seems to be related to the [Racer](https://github.com/edubkendo/atom-racer) package. You will have better luck posting your issue there.

**Comment by sadick254** [comment]
Thanks for contributing!

It appears that this is being caused by the [Racer](https://github.com/edubkendo/atom-racer) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
