### ISSUE TITLE
Atom 1.56.0 crash on click of a package author

### ISSUE THREAD

**Issue by set-killer** [atom/atom#22383]
### Description

When i click on the author of a package the Atom crashes. When i reopen it all projects opened in the side panel are missing and i have to open them again. Using the "Reopen a project" functionality does not work after that.

### Steps to Reproduce

1. Open an Atom packages list
2. Click on the author of the package (or is it a github page? see the attached screenshot)
3. kaboom.

![atom-issue](https://user-images.githubusercontent.com/4090555/117656522-1f6cb100-b1a1-11eb-9be5-f1b7186a1b47.png)

This happens with all of the packages, not just the one shown in the screenshot.
Also this happens only in the list of the packages. If i open the package' settings page (or the info page) and then click on the author - it opens a browser correctly and everything works fine.

### Versions

Atom version 1.56.0 x64
OS: Archlinux

**Comment by ThatXliner** [comment]
I can reproduce too:
```
Atom    : 1.56.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
OS: Big Sur 11.2.1
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0
python 3.7.9
git 2.30.1
```

**Comment by UziTech** [comment]
Can reproduce on Windows 10 as well.

**Comment by jhondev-code** [comment]
The problem is still in Atom 1.57.0

**Comment by Ciocias** [comment]
I have the same problem
```
Operating System: Ubuntu 20.10
Kernel: Linux 5.8.0-53-generic
Architecture: x86-64

Atom    : 1.57.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1

apm  2.6.2
npm  6.14.13
node 12.14.1 x64
atom 1.57.0
python 3.8.6
git 2.27.0

```

**Comment by DeeDeeG** [comment]
Weirdly enough, Atom is still open in the background for me after triggering this bug.

The window goes away, but Atom is still running in the background, and I can open new windows. (Sounds normal _for macOS_, but I'm on Ubuntu.) This kind of behavior is pretty weird for Linux.

**Comment by DeeDeeG** [comment]
Another weird thing is, this link generates a `will-navigate` event, as if the Electron window itself was going to browse/navigate to `https://atom.io/users/[some_username]` ...

https://github.com/atom/atom/blob/v1.57.0/src/main-process/atom-window.js#L266-L269

(`url` ends up being `"https://atom.io/users/[some_username]"`, and `this.browserWindow.webContents.getURL()` returns `"file:///usr/share/atom/resources/app.asar/static/index.html"`, so the `event.preventDefault()` is triggered to stop the navigation.)

All the other links don't try to navigate within Atom/Electron, and instead effectively tell your system's default browser to open the page. I have no idea why Atom is trying to visit these URLs, and only these ones in particular... or why it closes the window abruptly instead of visiting the page.

**Comment by ThatXliner** [comment]
So this issue should be in the [settings-view](https://github.com/atom/settings-view) package, right?

**Comment by ThatXliner** [comment]
I just noticed that this is happening for every single [`PackageCard`](https://github.com/atom/settings-view/blob/ee41dcd553297f22780f6c8686d4cbccfabda574/lib/package-card.js#L12) is acting like this

Does the fact that it's an`https` URL matter (https://github.com/atom/settings-view/blob/ee41dcd553297f22780f6c8686d4cbccfabda574/lib/package-card.js#L107)? I'll do some more diving later.

**Comment by DeeDeeG** [comment]
For what it's worth, on older unaffected versions of Atom, the links don't seem to actually be followed, you click on them and you just go to the package information view in Atom. (Despite the link clearly being to a user page at the atom.io website.) Then, once the user is viewing the package details view, the links start to work. (The links launch atom.io, or GitHub.com, as appropriate, in whatever external web browser.)

**Comment by ThatXliner** [comment]
I just noticed https://github.com/atom/settings-view/blob/ee41dcd553297f22780f6c8686d4cbccfabda574/lib/package-detail-view.js#L41-L105 . Seems like that the event shouldn't even get the point of `will-navigate`. And for

https://github.com/atom/settings-view/blob/ee41dcd553297f22780f6c8686d4cbccfabda574/lib/package-card.js#L90

it's handled via https://github.com/atom/settings-view/blob/ee41dcd553297f22780f6c8686d4cbccfabda574/lib/package-card.js#L244-L250

I think the problem here is that the package author link is an href, which isn't being handled, and will bubble up to the `will-navigate` event handler in `src/main-process/atom-window.js`.

**Comment by mehronkugler** [comment]
I experienced this issue in Atom `1.58.0` for Windows, today. I had just installed the application and was enjoying the interface, and shortcuts shared with Sublime Text, which I was looking to migrate from. However, picking a theme proved dangerous, as I decided to click on an author's profile, and the app crashed. Upon reopening, it had lost my project settings and open files. As a new user, I was immediately turned off from using the application any further due to this.

**Comment by DeeDeeG** [comment]
Yes, it's a pretty bad bug. The workaround is to force-quit Atom and reopen it. You will most likely get your open project(s) back that way, as long as your running Atom was not severely hung or frozen _in addition to_ experiencing this bug

I find handling these events (such as `will-navigate`) a little tricky... If I understand correctly, they involve a lot of back and forth between C/C++ code and JavaScript, and potentially between the render process and the main process, and potentially between Electron and OS APIs... It always feels so simple in theory but so complicated in practice, so close yet so far away. Hmm.  In other words, I wish I knew the fix, but I haven't found it yet...

The other workaround is sadly to not click those icons, which I agree new users should not have to learn to avoid doing. I wonder if this still happens with Electron 11...
