### ISSUE TITLE
[noob question] how do i disable the welcome guide at startup? 

### ISSUE THREAD

**Issue by jamesfranklinnetsec** [atom/atom#22534]
https://discuss.atom.io/t/how-do-i-make-the-welcome-screen-stop-showing-up/40403
googling only gives outdated response from 2017 where the welcome guide used to have a tick box that let you disable it.

how do I do this now? my welcome guide page doesn't have that tickbox?
This issue should double as a feature request to reinstate that tickbox by the way.

**Comment by sadick254** [comment]
On your home directory, there is a config file `~/.atom/config.cson`. Add this config setting in your config file.
```cson
welcome:
  showOnStartup: false
```

---

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
