### ISSUE TITLE
1.52 update broke syntax

### ISSUE THREAD

**Issue by premiare** [atom/atom#22736]
My atom has just updated to 1.52 after I restarted my computer.

I restarted my computer because clicking on files in a project wouldn't open the file, I had to right click the file manually and Split Right. After my computer restarted, I opened Atom and I've lost all my styling, syntax highlighting, basically back to default. Everytime I load Atom up I get error messages about deprecated packages. If they're deprecated just turn them off by default?

How can I revert to a previous version OR get my custom syntax highlighting and styling back. This has really ruined my workflow.

**Comment by sadick254** [comment]
Hey @premiare, You can download previous versions on Atom. On the [releases page](https://github.com/atom/atom/releases) you can find the necessary binaries to the version you may want to install.

---
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

On [Github Discussions](https://github.com/atom/atom/discussions), there are a bunch of helpful community members that should be willing to point you in the right direction.
