### ISSUE TITLE
Latest 1.58.0 RPM for CentOS7 will not upgrade with yum due to dependency error

### ISSUE THREAD

**Issue by robert914** [atom/atom#22786]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The latest RPM release 1.58.0 will not upgrade / install on CentOS7 systems. It fails with the following error:

```
❯ sudo yum upgrade atom
...
Resolving Dependencies
--> Running transaction check
---> Package atom.x86_64 0:1.57.0-0.1 will be updated
---> Package atom.x86_64 0:1.58.0-0.1 will be an update
Error: Invalid version flag: or
```

If I try to instead upgrade from an older version to 1.57.0, it works fine:

```
❯ sudo yum upgrade atom-1.57.0
...
Resolving Dependencies
--> Running transaction check
---> Package atom.x86_64 0:1.49.0-0.1 will be updated
---> Package atom.x86_64 0:1.57.0-0.1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================
 Package                      Arch                           Version                             Repository                    Size
====================================================================================================================================
Updating:
 atom                         x86_64                         1.57.0-0.1                          atom                         194 M

Transaction Summary
====================================================================================================================================
Upgrade  1 Package
```

### Steps to Reproduce

1. Have a version of Atom installed < 1.58.0 on a CentOS7 (or RedHat 7)
2. Use `yum` to upgrade package: `yum install atom`
3. Upgrade will fail with above messages.

**Expected behavior:**

Package should upgrade and install to version 1.58.0

**Actual behavior:**

Error in dependency resolution occurs:
```
Error: Invalid version flag: or
```

**Reproduces how often:**

Everytime now since 1.58.0 was released.

### Versions

1.58.0

### Additional Information

I've also tried upgrading to `atom-beta` and `atom-nightly` and they both fail with the same error.

**Comment by sadick254** [comment]
@DeeDeeG You have been helping troubleshoot alot of the linux issues. I would appreciate if you can take a look at this.

**Comment by DeeDeeG** [comment]
Hello @robert914,

Sorry to say, but over time, Atom has become increasingly incompatible with CentOS 7 (which was [first released in 2014](https://en.wikipedia.org/wiki/CentOS#CentOS_version_7) and is mostly stable since then -- a lot of old dependencies there).

Atom actually doesn't compile on CentOS 7 anymore (there are errors during compile) or run on CentOS 7 anymore. See these discussions for info about why:

- https://github.com/atom/atom/discussions?discussions_q=centos
- Particularly: https://github.com/atom/atom/discussions/22568

Furthermore, as to the specific problem you are reporting in this GitHub issue, Atom's `.rpm` package now won't install when your `rpm` installer program is too old. We started using [boolean dependencies](https://rpm.org/user_doc/boolean_dependencies.html), which are only supported in `rpm` 3.14 or newer. CentOS appears to have `rpm` 3.11 (https://pkgs.org/search/?q=rpm).

So, there are multiple reasons that make it difficult to build, install, and/or actually use Atom on CentOS 7. I would recommend staying on an older version of Atom if you want to keep using Atom on CentOS 7, or try to update to a newer OS if you can.

Sorry for the bad news...

Best Regards,

\- DeeDeeG

**Comment by robert914** [comment]
I suspected this was going to be the answer, but thought I would submit to find out for sure. Thanks for the information. I will just `versionlock` the CentOS7 setups to 1.57.0 which still installs and works.

Thanks.

**Comment by DeeDeeG** [comment]
Hmm. I had thought the incompatibilities I mentioned in my previous comment were enough to prevent even Atom 1.57 from running on CentOS 7.

(An aside: From my perspective, that might be worth further investigation (when I get some free time) to confirm what the exact limits are with new Atom/old CentOS... Maybe upgrading to 1.57 from and older version is somehow a workaround? Or maybe it's just the Docker image that is incompatible? Hmm...)

I'm not sure if this is doable in the CentOS world, but you could try updating with `dnf` or a manual `rpm` command of some kind instead of `yum`? Maybe one of those is new enough to handle it? Not sure. I'm mostly an Ubuntu/Debian person. I have dabbled in Arch. Not much Red Hat exposure for me personally.

Best Regards.

**Comment by robert914** [comment]
I had tried installing with `dnf`, but all it does is install `1.57.0` and lists `1.58.0` as skipped due to dependency errors. Although, I just tried pulling up 1.57.0 and it does not seem to start. So you may still be correct. I am able to run version `1.49.0`. I'm trying now to determine when it stops working.

**Comment by robert914** [comment]
Ok, looks like `1.51.0` is the latest version I can still successfully open on CentOS7. So I will lock our version to that on the CentOS7 machines, as that seems to be my only option for these. Thanks.

**Comment by sadick254** [comment]
@DeeDeeG Thank you for taking a look into this.

**Comment by helge000** [comment]
@robert914, thanks for the legwork!
