### ISSUE TITLE
THeme 

### ISSUE THREAD

**Issue by YordanYovev** [atom/atom#22873]
my Atom always start whit this theme ("One- ...........") and I don`t want it. 
How can I delete this ?
Please help

**Comment by ThatXliner** [comment]
You can choose some other theme instead. Reload your Atom afterwards. One-dark/light is a core theme

**Comment by YordanYovev** [comment]
I am choosing other theme every time when I start Atom, but after I turn it off, next time I turn it on it start whit One-light theme, not whit the 1 I choose.

**Comment by haneenmahd** [comment]
You should try updating to latest version.

**Comment by ajinsunny** [comment]
Try restarting your machine and updating Atom to it's latest version

**Comment by haneenmahd** [comment]
And Clean The generated cache files

**Comment by sadick254** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
