### ISSUE TITLE
> > Fixes [atom/teletype#208](https://github.com/atom/teletype/issues/208)

### ISSUE THREAD

**Issue by pomnt** [atom/atom#23174]
> > Fixes [atom/teletype#208](https://github.com/atom/teletype/issues/208)
> > This is similar to what we do for macOS keymaps:
> > https://github.com/atom/atom/blob/6cbc9988ecf935ab3905700a68bf3ce4f854cb3b/keymaps/darwin.cson#L108-L163
> > 
> > And would fix an issue teletype users are noticing when using editor commands in the popover. Since the popover is located outside the workspace (i.e. because it is a tooltip), keyboard shortcuts are not working for Linux and Windows users. I assume this is an issue with every package that attempts to use an editor outside the `atom-workspace` element.
> > @atom/maintainers: what do you think?
> > /cc: @AlexWayfer, who originally reported the issue on atom/teletype.
> 
> _Originally posted by @pomnt in [#16206 (comment)](https://github.com/atom/atom/pull/16206#issuecomment-955657684)_

_Originally posted by @pomnt in https://github.com/atom/atom/issues/23173#issuecomment-955657826_

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
