### ISSUE TITLE
Open file from `Open With` dialog messes up file URL

### ISSUE THREAD

**Issue by orschiro** [atom/atom#2320]
I opened a file from the `Open With` dialog in PCManFM. However, this messes up the file URL and thus causes the editor to open just an empty file.

![image](https://cloud.githubusercontent.com/assets/170947/3032736/9ac95dea-e05b-11e3-929b-804b00197807.png)

Basically it constructs an URL path in the form of:

`/home/<username>/file:/home/<username>...`

I am using the latest git version on Arch Linux.

Let me know if I can provide you with more information.

**Comment by bparmentier** [comment]
I have this issue for some time too. I am currently running PCManFM 1.2.3 and Atom 0.205.0 from AUR ([atom-editor](https://aur.archlinux.org/packages/atom-editor/)).

That's strange since it only happens with Atom.

So, if I type `atom /home/user/myfile.txt` in the terminal, the file is correctly opened, but if I open it from PCManFM, the file is empty and the path in the status bar looks like `file:/home/user/myfile.txt`.

**Comment by jonmast** [comment]
The issue here is that atom.desktop has `Exec=/usr/bin/atom %U`. The [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) says that %U is for URLs and files can be represented using either the path or a `file://` URL. PCManFM uses a file URL, which atom doesn't handle. Since atom doesn't handle URLs at all, the %U should be changed %F.

**Comment by bparmentier** [comment]
I confirm that files are correctly opened when replacing `%U` with `%F` in `atom.desktop`.

**Comment by VoidNoire** [comment]
I am still experiencing this issue. I was able to fix it by manually changing the relevant line in my atom.desktop file, but my change got reverted when I updated atom. Perhaps the issue ought to be reopened? I am on Arch and my atom is version 1.10.0 (according to the "Help drop-down menu in atom).

**Comment by 50Wliu** [comment]
This is only fixed starting in Atom 1.11.0-beta0 and onwards.
