### ISSUE TITLE
Atom dosen't match the style of the native title bar's style.

### ISSUE THREAD

**Issue by xyzwt** [atom/atom#2334]
Atom dosen't match the style of the native Mac OS X title bar's style.

Either this can be "fixed" by intergrating the tabs in the title bar (like in Google Chrome) or by making the style bar black in the default theme (see [Zed](http://zedapp.org) and [Brackets](http://brackets.io) (both are built on JavaScript)).

I don't know if this is a issue with Atom-shell and not Atom.

_Thanks._

**Comment by humberaquino** [comment]
+1

**Comment by mnquintana** [comment]
This probably won't be changing anytime soon - Atom's UI appearance is controlled by UI themes, and One Dark (the current default theme) is probably never going to change to match OS X's (or other platforms') shells. However, because Atom's UI is so easily customizable with themes, you can still *make* Atom match the style of OS X's title bar - check out [unity-ui](https://atom.io/themes/unity-ui) for a UI theme designed to match OS X's appearance.

Related to https://github.com/atom/atom/issues/4599

Also see the related discussion at https://discuss.atom.io/t/hide-system-window-title-bar/14578/17?u=mnquintana
