### ISSUE TITLE
thank u! Gonna check that

### ISSUE THREAD

**Issue by michal-sz** [atom/atom#23441]
thank u! Gonna check that

_Originally posted by @pitser90 in https://github.com/atom/atom/discussions/23437#discussioncomment-1892071_

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
