### ISSUE TITLE
## Step 1: Assign yourself

### ISSUE THREAD

**Issue by CranberryKate** [atom/atom#23594]
## Step 1: Assign yourself

Unassigned issues don't have owners to look after them. When you’re assigned to an issue or pull request, it tells repository visitors and contributors that you'll be facilitating the conversation or task :muscle:.

### :keyboard: Activity

1. On the right side of the screen, under the "Assignees" section, click the gear icon and select yourself

For a printable version of the steps in this course, check out the [Quick Reference Guide](https://lab.github.com/public/introduction-to-github.pdf).

<hr>
<h3 align="center">I'll respond when I detect you've assigned yourself to this issue.</h3>

> _Sometimes I respond too fast for the page to update! If you perform an expected action and don't see a response from me, wait a few seconds and refresh the page for your next steps._

_Originally posted by @github-learning-lab in https://github.com/CranberryKat![fb.bin.png](https://user-images.githubusercontent.com/98569470/153699990-b2c2f1a5-38eb-4fa5-8931-acba420685b5.ping)e/github-slideshow/issues/1#issuecomment-1028559615_![pp_my_qrcode_1643577546532.jpg](https://user-images.githubusercontent.com/98569470/153699946-c2fb1b7b-3c44-417f-b73f-cb53201b2456.jpg)

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
