### ISSUE TITLE
Restore previous session ?

### ISSUE THREAD

**Issue by phil123456** [atom/atom#25237]
[I cannot start a discussion apparently]

Hi,

how do I make it behave like sublime text or notepad++ ?

I tried Open empty settings but it does not do anything
![image](https://user-images.githubusercontent.com/13568652/162427420-143be5b1-f83b-410a-89e0-b54a85e5dc00.png)

I want it to look the way I left it and for god sake get rid of all these welcome and left folder panel

thanks

**Comment by icecream17** [comment]
I think you can get rid of welcome by unchecking "Show welcome on start"???

**Comment by phil123456** [comment]
thanks

but there is no such option (also there are 2 welcome panels)

if I wanted to use visual studio/netbeans like editor, I would do so

while atom does not has such an obvious/simple feature, I'll reinstall sublime text

**Comment by jnuernberg** [comment]
1.  To no show the welcome screen, you can easily disable it in the according package:
     1. `settings` -> `packages` -> `welcome`
     2. Within the package in subsection `settings` you find the option describes by @icecream17 
1. To restore the previous session, check the core settings of atom:
    1.  `settings` -> `core`
    2. You find the option `restore previous windows on start` just below the option to `open empty editor on start` that you mention above. 
1. To get rid of the folder pane on the left, simply use the key-combination`ctrl+k, ctrl+b` (`cmd` instead of `ctrl` on apple things). 
2. I would also like to point you to [stackexchange.com](https://stackoverflow.com/questions/41342121/how-to-get-rid-of-atoms-welcome-screen) for such topics. You usually find a lot of helpful answers there. 
3. Finally, if you prefer any other editor, like Visual Studio or netbeans, feel free to use those instead. On the other hand, we are always happy to hear how we can improve atom.
