### ISSUE TITLE
500 Error on packages on atom.io

### ISSUE THREAD

**Issue by UziTech** [atom/atom#25438]
### Description

https://atom.io/packages/x-terminal shows a 500 error and when trying to publish a new version with apm I get the error:
`Creating new version failed: Application error`.

https://github.com/bus-stop/x-terminal/runs/6253087623?check_suite_focus=true#step:6:108

**Comment by smcenlly** [comment]
We create a couple of popular extensions for Atom and are having the same problem:

* https://atom.io/packages/atom-quokka (62,332 downloads)
* https://atom.io/packages/atom-wallaby (21,315 downloads)

---

Our publishing token expired and since refreshing it, we now get "Application error" (with no details, server: 500) when attempting to publish. If we revert to the expired token, we get the error: `Requires authentication. Please update your token if you haven't done so recently.`.

Could someone from the atom team please help with this issue?

**Comment by UziTech** [comment]
@sadick254 if there is anything I can do to help get this resolved faster just let me know. If you need more help with maintaining atom I would love to help. 😁

**Comment by sadick254** [comment]
@UziTech We are working on resolving this as soon as possible.

**Comment by smcenlly** [comment]
Could you please provide an update and ETA on when this may be fixed?

**Comment by smcenlly** [comment]
@sadick254 @darangi - we're trying to work out what to do since we can't pubish using `apm` and can no longer release the latest version of our extensions. Is there a set of manual steps that we can follow as an alternative?

Thanks

**Comment by SunderB** [comment]
I can confirm that I'm having the same issue when trying to publish a new version of [sb-atom-sonic-pi](https://github.com/sunderb/sb-atom-sonic-pi). (Although I have messed up the versioning a bit, which probably doesn't help)

**Comment by smcenlly** [comment]
@sadick254 @darangi - you able to provide an ETA on the fix? This issue has been opened for almost a month now. Is there something we can do to help?

Fortunately the reason we want to publish an update is because of functional changes but we would be in a pretty bad place if we need to publish because of a security issue.

As requested above:

> Is there a set of manual steps that we can follow as an alternative?

Right now, our products are available in a number of editors (VS Code, JetBrains, Sublime Text, Atom, Visual Studio). If we can't publish updates and there's no alternative we can follow then we will likely drop our support for Atom.

**Comment by smcenlly** [comment]
For others in this thread who may not have seen: https://github.blog/2022-06-08-sunsetting-atom/
