### ISSUE TITLE
Integrating Atom and Github for Windows

### ISSUE THREAD

**Issue by batjko** [atom/atom#2545]
So I am in awe of the aesthetics of the Github client for Windows. It's minimalist, neat, clean, functional, just very pleasing all around.
And it successfully abstracts from the nitty bitty pieces of command-line git.

Atom seems to want to be the same thing for code editing, only allowing for all that extra customizability via packages and css styling etc...

Now that I have been trying both for the last few days, it seems to me a logical next step to open and edit files directly from the github client. I can imagine both: Atom being just another module or "page" inside the github client, or the github client gets removed and all its functionality integrated into the Atom tree view, via context menu entries or a second tree view pane with repositories etc...

Has any thought been given to this kind of thing?
I'd love to see that, and given Atom's extensibility, I'm sure a package is just around the corner.

**Comment by damieng** [comment]
We did a little bit of work in apm to automatically use the version of git installed by GitHub Desktop despite it's unusual and regularly moving path.

Further integration is still being explored and any updates will be covered on the Atom or GitHub Desktop blogs rather than noted against this issue.

I'm going to close down this issue as it isn't directly actionable here but rest assured this request is not forgotten.
