### ISSUE TITLE
copy/paste bug: carriage return inserted on paste + How can I turn off Auto-indent/Auto-reformat on paste?

### ISSUE THREAD

**Issue by dgm3333** [atom/atom#25485]
SOLUTION: ctrl-shift-V provides "paste without reformatting" (as per the edit menu - DUH)

As below some of this is a problem only in "normal mode" and doesn't happen in safe mode - but the autoindent on paste happens in all circumstances. It also seems to have been a recurring problem for people over the years but I can't find a fix (I've started another issue rather than appending to an existing one because of the LF issue).

I have text in the following format (the \n is plain text in the file NOT me showing where the LF is). Spaces are used for the indentation in my actual text but github is removing them so I've replaced them with dots for visibility (.). 
I presume it doesn't make a difference for a modern editor but JIC the text confirms to Unix standard so only has a LF (0x0A) rather than the windows standard CRLF.

XaFti,Budgie serum antibody level
..Units,mgA/L
..Description,Budgie serum antibody level\n_
....Is a measure of allergy to budgies...\n

If I copy and paste a line/s which already has indenting it will add whatever indenting was in the line above - so if I was to copy the "Is a measure..." line directly below itself then it would end up doubly indented - so I then have to manually delete the indents.
This issues occurs if I copy it and paste anything (eg copy the entire block to start a new identical one) - then Atom incorrectly autoindents entire blocks it even when running in safe mode. 

In addition (only if NOT running in safe mode) it also messes up and randomly adds a bunch of additional carriage returns to this particular text - although I don't know what addin seems to be causing it (I haven't added any so it must be one installed as part of the default package). Some of this is an issue at the point of copy - so if I copy the text then paste it to notepad it will already have the \n text randomly moved.
Thus for me pasting it back not in safe looks like this (with some but not all \n text randomly moved to the next line, and random blank lines added in...:

```
    XE25B,Immunoglobulin A level

      Units,g/L

      Description,Immunoglobulin A level
\n_
        Description (will be shown as hovertext)\n
      Weblink,https://labtestsonline.org.uk/tests/sodium-test

```

An *EXCELLENT* solution (used by every other IDE I use) would be to paste with changes, but to allow ctrl-z to backstep the change so that so you could be left with the text inserted in it's vanilla (unmessed-up) copied form...

**Comment by raer0** [comment]
Hi, I'm unable to reproduce this issue at this time on Atom v1.60 on Ubuntu 22.04. However, I am aware of what you are describing and have experienced this issue myself. I cannot recall *which* package I have installed that fixes the issue, however, I know that one of them does the job. I don't have the time to parse the list myself, however, I have included my atom packages list in this reply so that you may go through them and find which one solves this issue for you. 


[raer0-pacakge-list.txt](https://github.com/atom/atom/files/8783802/raer0-pacakge-list.txt)

**Comment by dgm3333** [comment]
Thank you for your suggestion.
I was starting to look up your packages, when I suddenly reaslised ctrl-shift-V is "paste without reformatting" (I can't believe I've never seen that it's annoyed me for months". However the problem is now solved without additional packages.

**Comment by raer0** [comment]
Atom is abandonedware. Due to complications with github being acquired by microsoft, it is unclear if/when this will ever be formally acknowledged. To give an idea of how abandoned this software is: 

- The discussions section was deleted without notice after getting spammed despite methods existing to fix discussion board spam. 
- None of the original maintainers/devs have committed to the repo since 2020
- There are, as far as I can tell, two official maintainers for this repo these days.
- The CI pipeline is broken with no indications of being fixed


This software should not be used. Nearly all of its dependencies are ancient, and nobody is left to pass the torch. It is too big, has been touched by too many hands, and has been left to die for too long to be rescued. 

If you would like to explore a de-microsfted text editor based on Electron, try [VSCodium](https://github.com/VSCodium/vscodium), a repackaged binary of VSCode's open source codebase with all the microsoft telemetry stripped out, and which uses an open source extension distribution platform separate again from Microsoft. 

I personally find it to be quite adequate.
