### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by flashtechstudios** [atom/atom#25513]
Go on with your V$ Code. Even though I use VS Code it still doesn't make sense to shut down Atom.

**Comment by iamunadike** [comment]
Vscode is Jealous of atom

**Comment by flashtechstudios** [comment]
I uninstalled VSCode, fuck Microsoft

**Comment by pegvin** [comment]
hey there, atom's source code is public, you can maintain it yourself, there's no reason to curse anyone and this isn't even a issue so please goto twitter and argue there.

**Comment by quenbyako** [comment]
vscode has also community version, what's wrong? vscode also opensourced as well as atom...

**Comment by raer0** [comment]
VSCode is:

- built on the same tech (electron) as Atom
- open source
- has a binary version built on the open source without MS telemetry (https://github.com/VSCodium/vscodium/)
- has many of the same features as atom, albeit slightly different
- is just as configurable as atom
- can be used more or less... the same ways as atom.


This isn't the place to bicker or complain. This is just kind of what happens when a company makes an open source project, and gets bought by another company with a similar/competing product. VSCode isn't bad. Its got good intent, and takes advantage of whatever resources a large corp wants to throw behind it. It is what it is. The people making VSCode are the same kinda devs who wanted to make something good with Atom, and the featureset reflects that if you take the time to get over how slightly different it looks. 

The world moves on. Software gets abandoned. New projects emerge from the ashes of the old. Atom helped create Electron, which is an invaluable platform for developing desktop apps. Lets not bring toxic bickering into a *f%$king* github issue. Take your disappointment and anger somewhere else.

**Comment by flashtechstudios** [comment]
> hey there, atom's source code is public, you can maintain it yourself, there's no reason to curse anyone and this isn't even a issue so please goto twitter and argue there.

I don't have a twitter account 🤣

**Comment by pegvin** [comment]
> I don't have a twitter account 🤣
So this is not a place to show your bullshit, if you really have a issue like a bug or something then raise a issue.

**Comment by FinnT730** [comment]
> I uninstalled VSCode, fuck Microsoft

Then why use Github? Github is owned by Microsoft :P

**Comment by pegvin** [comment]
@FinnT730 You're Absolutely Right.

**Comment by flashtechstudios** [comment]
> > I uninstalled VSCode, fuck Microsoft
> 
> Then why use Github? Github is owned by Microsoft :P
> 
> And like the others said, there is no reason to hate the people behind Atom. it is time consuming having to maintain a Hackable Editor, and be happy that the source code will still be there in 10 years, you can always make your own, that is why it is on Github. You can make your own text editor with the base of Atom if you truly want. Don;t hate on the people, sunsetting was foreseen already, since it didn't get a lot of updates anymore, and it slowly died over time. At least we got an anouncment

Yeah makes sense
