### ISSUE TITLE
error in first line of atom intro

### ISSUE THREAD

**Issue by Aryan-patel-12** [atom/atom#25517]
<img width="836" alt="Screenshot 2022-06-11 at 10 09 29 AM" src="https://user-images.githubusercontent.com/88919755/173172809-9cfcbbdc-2299-4279-bfe4-358f91a7a28a.png">
 
It is written that "atom is an **HACKABLE** text editor" which has a wrong meaning

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
