### ISSUE TITLE
Is alive 

### ISSUE THREAD

**Issue by Author01** [atom/atom#25606]

**Comment by Author01** [comment]
R3saidso whole world against a genius

**Comment by Author01** [comment]
@anthonysidesapps

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
