### ISSUE TITLE
Changes not displaying on Git panel

### ISSUE THREAD

**Issue by Tofutush** [atom/atom#25746]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * *I haven't checked the FAQ because the link leads to 404.
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * *I remember -- being yesterday or the day before that -- seeing the same issue here. But now I can't find it, so I guess it was only in me head or something.
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When I change a file and save it, it was supposed to pop up in the Git panel immediately in the "unstaged changes" section. But just a couple days ago this failed to work. If there is already some changes in either staged or unstaged sections, I can make my new change show up by spam clicking "stage all" or "unstage all". But if there are no changes on there initially, I can't make any changes show up.

### Steps to Reproduce

1.  Open a github project.
2.  Make a change in one of the files and save.
3.  Look at Git panel.

**Expected behavior:**

Change shows up on Git panel.

**Actual behavior:**

It doesn't.

**Reproduces how often:**

I've left Atom unopened for like at least a month before I decided to make another project with it, just a couple days earlier. Or three days. This bug's been there ever since. And it doesn't seem to have anything to do with the newest version; it was there before I upgraded.

### Versions

The newest, and the one before that.

### Additional Information

**Comment by chriskorosu** [comment]
I've noticed the same issue when I upgraded from `v1.60.0` to `v1.63.0`. Extremely annoying if you use version control.

Rather than spam-clicking to see the changes, you can try executing a `Window Reload` command (`Ctrl-Shift-F5` by default). This worked for me, but since it takes a while for the window to reload, requires manual input, and my workflow is highly reliant on viewing staged/un-staged changes, I ended up taking more extreme measures.

I ended up downgrading to a previous version, `v1.60.0`. If you're on Windows 10, you may find the previous versions installed under `c:\Users\[username]\AppData\Local\atom`.

**Comment by Tofutush** [comment]
Windows reload works for me! And I think for me that's good enough already.

Thank you!
