### ISSUE TITLE
unable to select, advance cursors to end of line

### ISSUE THREAD

**Issue by maxheld83** [atom/atom#2616]
This is odd:

![md-bug-2](https://cloud.githubusercontent.com/assets/5372770/3281957/b5a09f3a-f4cd-11e3-8b38-3fb11de0811d.gif)

I can't advance by arrow keys towards the end of the line I am in.
I also can't click there or select (my frantic mouse movements are indicating that I'm trying).

I'm running:
- OS X 10.9.3
- Atom 0.103.0
- 2 Panes at the same time
- softwrap fixed at 80
- not sure which other package might be relevant.

This might be a duplicate/related to #1894 and also atom/markdown-preview#92

**Comment by benogle** [comment]
Closing as this has not been an issue for several months

**Comment by abieler** [comment]
I had the same problem.
On OSX this problem was there right from the first session. Under Linux mint it worked
well for weeks, then this started to happen.
On the linux box I could resolve the problem by disabling
 "vim-mode", "vim-mode-plus", and "vim-mode-visual-block". 

After enabling all of them again the problem was gone.

I will do a more systematic error search should this happen again.
