### ISSUE TITLE
Clicking and dragging up in gutter does not scroll

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#2696]
Clicking on the gutter and dragging up does not expand the selection and scroll the editor when you reach the top of the gutter.

This didn't work in the old editor but I noticed in the new editor it doesn't work either.

It does scroll down though correctly when clicking and dragging.

**Comment by mingliangfeng** [comment]
+ 1

Same problem when using Atom on Windows.

**Comment by mnquintana** [comment]
Can't reproduce this on OS X 10.10.3, Ubuntu 15.04, or Windows 8.1.

**Comment by izuzak** [comment]
I can still reproduce this, but the issue is a bit different than before -- the editor scrolls a bit up, but stopps after a few rows.

**Comment by izuzak** [comment]
@nathansobo Sorry for pinging you all over the place :sweat_smile:, but just remembered this old issue and you were looking at something very similar recently. :v:

**Comment by nathansobo** [comment]
No apologies needed. I appreciate it and will take a look. Would be good to knock out all selection and scrolling related stuff in this phase so keep the mentions coming.

**Comment by alexander-jiang** [comment]
Reproduced on v1.0.6 on Windows 7.

The issue seems to depend on the window size. When maximized on 1920x1080 display, it seems to only scroll upwards to show 48 selected rows, but the actual selection continues up to a maximum of 53 rows. When maximized on a 1366x768 display, only scrolls to show 32 rows of the selection, which continues up to a maximum of 37 rows.
