### ISSUE TITLE
PHP and HTML Syntax Coloring issue

### ISSUE THREAD

**Issue by phikal** [atom/atom#2734]
I am using Elementary OS and version 0.107.0, and when I write PHP and this happens:
![screenshot from 2014-06-24 18 59 36](https://cloud.githubusercontent.com/assets/6370419/3374663/022c136c-fbc1-11e3-8108-f2331315bf33.png)

The surrounding HTML code is highlighted, but PHP isn't.

It's even worse when you have a string in the PHP code, because the whole following text (even after `?>`) is seen as html value and has the same color.

I believe this package should be responsible for this: https://atom.io/packages/language-php , please tell me if this is the wrong place, but i'm not sure if it is a general atom issue.

Please note that javascript and CSS are highlighted when written inside of the HTML.

**Comment by mhayati** [comment]
@phikal To resolve this problem I simply left the first line in my .php files blank and start from the next line that in most cases in <!doctype html> and Atom will color the code as it should.

**Comment by KristobalJunta** [comment]
Maybe an option in settings menu would be really good.
Anyway, I find current behaviour pretty strange

**Comment by vollyimnetz** [comment]
please fix

**Comment by LouWii** [comment]
Same problem here
![screen shot 2015-04-17 at 4 13 24 pm](https://cloud.githubusercontent.com/assets/2750789/7212496/c2e08ada-e51c-11e4-8b4a-95d2b5674064.png)
Inside a .php file

**Comment by jazzpi** [comment]
Same goes for Rails HTML files if they start with `<!doctype html>`. As a workaround, would it be possible to add an override option to the first line matching option? Another solution would be to let users specify grammars for filetypes in their config.

The [file-types](https://atom.io/packages/file-types) package doesn't work anymore, but there is a workaround: https://github.com/execjosh/atom-file-types/issues/17#issuecomment-109758274

**Comment by alepore** [comment]
a config like this should work on atom 1.0.8+:

```coffee
"*":
  core:
    customFileTypes:
      "text.html.ruby": [
        "erb"
      ]
```

**Comment by thomasjo** [comment]
As mentioned by @alepore, this scenario has a workaround now, so I'm closing this issue.

**Comment by claviska** [comment]
What's the workaround for PHP? Can't seem to get anything in the config that triggers the correct behavior.

**Comment by kelunik** [comment]
An existing workaround is not a solution. This issue shouldn't be closed.

**Comment by charlesmudy** [comment]
Same here, can't seem to find a workaround for PHP

**Comment by Ingramz** [comment]
@nathansobo is there anything that would necessarily break if the current scoring system was changed?

I don't see any other way of fixing this for PHP (and similar) other than prioritizing file extension matching over first line matches and only take account the first line match if the file extension is unknown or if there are multiple grammars that match the same file extension.

I'd definitely like to give a try implementing that approach.

**Comment by nathansobo** [comment]
> prioritizing file extension matching over first line matches and only account the first line match if the file extension is unknown or if there are multiple grammars that match the same file extension.

I'm honestly not totally sure of the implications of this, but it makes intuitive sense to use the file contents only in situations where there is ambiguity. Maybe add it as an option that defaults to enabled so people can disable it if it causes problems in the other direction? If we don't hear from anyone, then we can drop the option.

**Comment by Ingramz** [comment]
Sounds like a plan.

**Comment by Ingramz** [comment]
I figured out how it should be based on my proposal. See https://github.com/Ingramz/atom/commit/49f391ff81ec2407738a018a0f3e3f86a9ffba50

This will return Infinity as a score for the overridden grammar, which in my opinion is a little more elegant than 2 + length of file path.

The path scoring system is already good as-is. Longer match will get a higher score, plus 0.5 bias for user defined file types. I find it very clever that the user can select between two grammars by adding the file type in question to the user defined list, even if it already was defined in grammar so one of the two grammars always gets priority with the same matched longest file type.

Also there is a bias of 0.25 so that a non-bundle package would win over a bundled package, if their matches were the same length (ergo the file types matched are the same), this is the same as the code that was on lines 39/40. However one thing to note - if we get -1 as a file type score for all grammars and there is a non-bundle grammar, then that would win over all bundled grammars with a score of -0.75, it seems that this oddity exists also in original code. I think that this bias shouldn't be applied if the path score itself is -1.

Finally a bias for the case where the first line of the file matches a file, which is currently the weakest - 0.125. This should help in case the two grammars were equal in the previous cases. Setting this with the smallest bias makes more sense to me as it should be used only as a last resort, which works really well for files which the type is unknown.

The missing parts are the user-selectable fallback to original scoring and the positive score check for non-bundle bias. But I'd like to hear your feedback if the scoring is fine the way I just explained.

**Comment by ronnyandre** [comment]
Still an issue with PHP syntax detection.

**Comment by Ingramz** [comment]
@ronnyandre please provide following information:
1) atom version
2) file extension that is being used for testing
3) first line of that file
4) whether it is also happening when you open `atom --safe` and open that file from there

**Comment by odahcam** [comment]
I still with the problem in Atom Dark, Base16, custom themes, etc.

![image](https://cloud.githubusercontent.com/assets/3942006/17890476/a9d8e5da-690c-11e6-9bdb-800370f0307c.png)

I want the `PHP` tags to be diferent of the string, if it's just a theme configuration, where can I change this?

**Comment by 50Wliu** [comment]
@odahcam Please file a new issue at https://github.com/atom/language-php.

**Comment by odahcam** [comment]
See https://github.com/atom/language-php/issues/151.
