### ISSUE TITLE
High DPI handling (blurry window content due to scaling)

### ISSUE THREAD

**Issue by batjko** [atom/atom#2833]
Hi guys,

I am working on a laptop with a high DPI screen (Sony Vaio Pro 13, 1920x1080 resolution,166 PPI), and many programs that don't cater for it will be automatically scaled up by Windows (and assume other OS's as well?).

Here's what that looks like on Win8.1 build, with the example of pane titles:
![image](https://cloud.githubusercontent.com/assets/7287076/3486263/8f0c2d54-042b-11e4-9ab2-532ee799f781.png)

Now, of course I can turn the scaling off in the atom.exe compatibility settings which makes the typography much smaller though, and I wanted to log this issue anyway, in case someone knows what to do about it in core.

Also, note that the tree view does not suffer from this, nor the actual code in the editor panes, btw.

Cheers

**Comment by darklow** [comment]
I fixed blurry fonts problem by adding /force-device-scale-factor=1 to app shortcut.
UI is now very small, but at least fonts are not blurry.
"C:\Program Files (x86)\Spark Dev\atom.exe" /force-device-scale-factor=1

**Comment by DiThi** [comment]
@darklow That creates a new file with name `/force-device-scale-factor=1` to me. I have `atom.exe` in 
`AppData\Local\atom\app-0.175.0` (same issue with 0.174).

**Comment by darklow** [comment]
@DiThi yes, it opens new tab for me too, but at least it fixes blurring. I haven't found any other way yet.

**Comment by paulcbetts** [comment]
I'm seeing this too now, and it appears that enabling DirectWrite fixes this issue, change `src/browser/atom-window` and switch `direct-write` to `true` to see the effect (must restart app, not just Reload)

**Comment by CMCDragonkai** [comment]
Is there a way to zoom into Atom on Windows 8? Right now everything looks really small on my surface pro.

**Comment by jcarmena** [comment]
@CMCDragonkai, I have tried this:

body { zoom: 2.3; -moz-transform: scale(2.3); -moz-transform-origin: 0 0}

looks good, but then the mouse events goes crazy (Ubuntu)

**Comment by alexanderadam** [comment]
calling atom with `$ atom --force-device-scale-factor=1` also fixes blurry fonts for me in Ubuntu. Is there any way to set it as a default in the config?

**Comment by CreamyCookie** [comment]
If you have this problem, maybe installing this awesome package could help: https://atom.io/packages/hidpi

**Comment by barryvan** [comment]
On my Surface, with two external monitors, Atom is beautiful when it's on the Surface -- but when I move the window onto a (standard DPI) screen, everything is blurry. Chrome does the same thing. If it helps, Firefox recently resolved this issue (https://bugzilla.mozilla.org/show_bug.cgi?id=890156); I'm guessing that because Atom is built on Electron, we'll have to wait for Chromium bug https://code.google.com/p/chromium/issues/detail?id=426656 to land to resolve this issue?

**Comment by klaszlo** [comment]
fresh ubuntu 16.04 install, atom 1.7.3 package.
The fonts are blurry inside the text editor.

Here is a comparison gif, one from the browser (firefox), other is from atom.io editor window.
![atom-blurry](https://cloud.githubusercontent.com/assets/140974/15442490/d4c0cd64-1ee1-11e6-85f9-e795dd7c7245.gif)

Is it possible to make antialiasing more sharp?

**Comment by SimonSelg** [comment]
Same here as @klaszlo on Atom 1.9.0 beta (and on stable, too). 

A temorary workaround is to start atom with `--force-device-scale-factor=1` and then manually increase the font size.

But that doesn't work well on all parts of atom - for example the menu bar is no way to tiny.

Let me know if I can provide more information that'd help to fix this problem.

Cheers

**Comment by madispe** [comment]
Have you tried the `--enable-use-zoom-for-dsf` flag instead? This fixes a very similar issue in Google Chrome and VS Code for me. With the editor, adding the `--disable-gpu` flag was also required.

Eventually zoom for DSF should be enabled by default. See [crbug.com/485650](https://crbug.com/485650).

**Comment by SimonSelg** [comment]
Thanks! That worked for me.

**Comment by felixrieseberg** [comment]
It's worth pointing out that Chromium M53 will [enable "use zoom for dsf" by default](https://codereview.chromium.org/2173243002/patch/1/10001), meaning that this change should eventually trickle down to Electron and fix a lot of the blurriness discussed here.

**Comment by ntomallen** [comment]
The DPI scaling issue has been known for two years now - I've seen several issues beating around the bush, referencing now closed future features. On Windows 10 Pro, with scaling set to 150% in Windows because of my 28" 4K monitor, it's nearly unusable. It scales to the correct size, but all the text and UI components are blurry. I'm sure you guys know what I'm talking about! Of course, you can change the comparability settings to make it scale 1:1, but that's unseasonably small for me. The HighDPI plugin does work to an extent (it's not perfect by any means, and it hasn't been developed for Windows.. but it works), but it seems like those of us with High DPI monitors have to compromise in our editor choice when we use Atom with this big monitors. Does anyone know when this will "Just Work" (tm)? I know there are mentions of the Chromium bug with per-monitor DPI scaling not switching properly between displays, but that's sort of ignoring the point that scaling to a high DPI with the OS's settings doesn't work automatically in the first place. Unless I'm missing something, and I totally could be, is this fix in the works or still just sort of projected down the road? I love Atom, and I'd hate to leave it for short time over this!

Some other notable culprits of improper DPI scaling are Office 2016 and Spotify. I was hoping three years after my first foray into high DPI that things had sharpened up a bit (heh heh), but apparently not.

**Comment by damieng** [comment]
It seems that a lot of the issues relating to overall size, proportions and bluriness on high dpi are now gone with the exception of ClearType/font smoothing which is being tracked on the other issues referenced.

I'm proposing we close this issue down now and raise very specific ones for remaining issues as it's not clear what's left to do here.

**Comment by 50Wliu** [comment]
Electron support for high DPI screens has progressed to the point where it should be safe to close this issue.  As @damieng mentioned, please open new issues for any DPI-related bugs you come across.
