### ISSUE TITLE
Changing selected text's color

### ISSUE THREAD

**Issue by probablycorey** [atom/atom#2886]
Via https://github.com/atom/atom-dark-ui/issues/19

> Currently it's quite easy to change the background colors for selections.
> 
> ```
> .selection .region { background-color: @red }
> ```
> 
> But it seems to be impossible to change the foreground color, due to the fact that the `selection` container simply overlays the text, and does nothing to change the actual `.line` element containing the text. (see screenshot)
> 
> ![screen shot 2014-03-11 at 14 55 11](https://f.cloud.github.com/assets/430875/2385944/05910024-a925-11e3-949e-a856fc6e5449.png)

**Comment by kevincoleman** [comment]
Call me crazy, but doesn’t this seem like a structural issue with the way styles are applied? It should be as easy as `::selected {color: #ff0000;}`, but the scope seems limited. I’m new to atom, but should the styling approach be reconsidered?

**Comment by benogle** [comment]
> should the styling approach be reconsidered?

We're not using the default browser selection. The entire editor view is custom, rendering text, the cursor, and the selection as individual DOM nodes. 

At some point in the future, we may be able to wrap the selected text with a `<span class="selection"/>` or something. But it's something we'd need to talk about. 

Sorry about this, it is a crappy limitation.

**Comment by kevincoleman** [comment]
Thanks for filling me in—do you know the reasoning behind that? I’m all for a custom implementation if we gain things from it. I guess I’m just unfamiliar with what Atom gains by bucking the standard styling model.

If it were worth switching, what would it even take?

**Comment by benogle** [comment]
The custom implementation gives us control over how and when things render, and gives the user / theme author more control over styling.

**Comment by kevincoleman** [comment]
Fair enough—makes sense to do whatever gives us the most access. Do you know if there are already edits that add styling to markup like that? I see the `.editor` class, but it seems like even `.selected` doesn’t apply styles to the selected text.

I don’t really understand just how the `z-index` layers are used to structure the view just yet, but I’ll dig in. I’d love to see if I can find out where this sort of fix would take place.

So, if `.selected` currently just affects the underlayer, we would just need to add a similar `selected` selector to the active text layer, yes?

Sorry if this is just annoying to have a noob asking all about the rendering structure. Is there a breakdown of how Atom renders? I can dig in the view code, but there’s a lot to take in without knowing the overall structure first. Thanks!

**Comment by benogle** [comment]
The selection is a `highlight` decoration rendered under the lines. You dont need to dig into the code, you can see it in the inspector:

![screen shot 2015-03-13 at 1 41 04 pm](https://cloud.githubusercontent.com/assets/69169/6646936/d444952a-c986-11e4-8c65-a1e49ef1f254.png)

Currently the the actual text (in each `.line` in this image) has no idea what bit of it is selected. To make that work, we could probably wrap the text in the lines with a span. Though, wrapping the tokens, or bits of tokens, will likely not be easy.

**Comment by kevincoleman** [comment]
Oh, cool! thanks for pointing me to that. It seems to me like whatever function is creating `<div class="highlight selection" ...` should also be responsible for applying a `<span class="selection">` around the selected text, so they always agree, and use the same styling selector. Or, maybe that’s too idealistic of me.

I ran my own little test of selecting text, inspecting it, then adding properties to make the text another color right in the `<div class="line">` elements. I had mixed success. If I changed color on an existing div, it applied just fine. However, If I added a span in the middle of the line of text within the div it just rendered the span tag as text. Plus, it occurred to me that we would be wrapping an inline element around several block elements, which (at least in the regular web world) isn’t supposed to happen.

All things considered, it seems like the default mechanic for highlighting selected text should be to apply styles to the live text layer. All the syntax highlighting gets applied that way, so it’s definitely *possible*.

Thoughts? Is this just a waste of time?

**Comment by mark-hahn** [comment]
>  it seems like the default mechanic for highlighting selected text should
be to apply styles to the live text layer. All the syntax highlighting gets
applied that way,

Wouldn't that cause the source DOM elements to require being broken up into
overlapping non-related pieces?  Also, don't elements have more
background capabilities than foreground?  Your suggestion would reduce the
spectrum of highlighting techniques?

**Comment by kevincoleman** [comment]
@mark-hahn definitely a good concern. It just seems like if all the syntax highlighting and line separations are applied in such a way that they break up the DOM elements already, we might as well not limit our selection abilities by abstracting them to another layer. What makes syntax highlighting the special child? Or, really, shouldn’t there be a centralized function set so that styling can be applied to over, under and live layers all at once, using the same position indexing system? It seems like the scope of the CSS selectors should be broad enough to cover all layers.

Again, I’m new to Atom, so I don’t know all of how we got to where we are. It just seems like an odd model to break apart the styling in a prohibitive way.

**Comment by jeffgran** [comment]
:+1:  I would like to see this addressed. After looking through the code, it seems like it would be possible to do this by augmenting the Grammar system.

- Grammars already do the "divide up the text into non-overlapping spans", but they can (currently) only do it based on the regex-based "rules" in a grammar file.
- The main function that does this (if I am understanding the code correctly) is `Grammar#tokenizeLine` : https://github.com/atom/first-mate/blob/master/src/grammar.coffee#L101
- This function (and the functions higher up the call stack which call it) could be augmented to take a set of markers and take them into account when generating the spans.
- Using the new "Marker Layers", it could be made more efficient by only taking into account the markers on a special "visual" layer... or only markers tagged with a tag, so that we don't waste time processing markers that aren't intended to have styles.
- I think there are some optimizations that help this code to only re-run on changed lines, and that would have to be updated to also trigger updates when the markers are changed, for example : https://github.com/atom/atom/blob/590c2da211ba6328df1707609bdac7e840b93b27/src/tokenized-buffer.coffee#L251

**Comment by kevindeleon** [comment]
This would definitely be nice for implementing a ST like "show invisibles on highlight" type option, which I love for quickly determining if a file has spaces or tabs, without having to constantly display the noise of "show invisibles."

**Comment by Fen1kz** [comment]
We also can't use selection border/outline, since there're multiple selection divs. Any news if this will be changed?

**Comment by felipecrp** [comment]
What do you think about duplicate the selected text on .highlight.selection .region section?

**Comment by lee-dohm** [comment]
@felipecrp The duplicated text would still be behind the actual text, so changing the attributes of the duplicated text would not have the desired effect.

**Comment by felipecrp** [comment]
@lee-dohm understood. May be the way is use something like <span class="selection"/> (as @benogle  suggested)

**Comment by lee-dohm** [comment]
@felipecrp To my recollection, there were significant performance implications for that approach.

**Comment by felipecrp** [comment]
@lee-dohm do you have any suggestion to solve this?

**Comment by lee-dohm** [comment]
No, I don't. It isn't going to be simple to solve. It will require a deep dive into the tokenization, line rendering, marker and decoration code.

**Comment by brumm** [comment]
For what it's worth, I ended up with this in the meantime:

```less
atom-text-editor .highlights {
  z-index: 1;
  mix-blend-mode: color-dodge;
}
```

This works particularly well with dark themes, resulting in a more vibrant color for selected text. I don't usually use light themes, but playing around with the blend would be a good thing to start experimenting with.

Yes there might be Problems™️ with pulling the highlights layer up over the text. I haven't encountered any, but your mileage may vary.

shown here with One Dark syntax theme
![image](https://user-images.githubusercontent.com/170500/44266534-2e5de900-a22b-11e8-9d2d-0456aff85edd.png)

**Comment by Ugotsta** [comment]
@brumm excellent workaround. I was able to somewhat desaturate highlighted text with this:
```
atom-text-editor .highlights {
  z-index: 1;
  mix-blend-mode: color;
}
```
From a theme-in-progress:
![atom-selected-blend-mode](https://user-images.githubusercontent.com/532645/45241651-0ef23300-b2a2-11e8-953a-a0a9ecb3cdf3.png)
