### ISSUE TITLE
Rightclick in the treeview doesn't focus the selected item directly

### ISSUE THREAD

**Issue by philipgiuliani** [atom/atom#2991]
I was not sure if this belongs to treeview, or to the atom context menu, so i decided to open it directly here.

If i press rightclick on a treeview, the item behind my mouse won't be selected. If i click it again, it gets the selected item. So im not sure which one is selected currently and i always have to do left-click and then a right click.

![rightclick in treeview](https://cloud.githubusercontent.com/assets/5446019/3599270/eae7ef68-0cec-11e4-8138-02e78b9d8367.gif)

Atom Version: 0.115.0

**Comment by alex-martin-xactium** [comment]
Interested too. Very useful.

**Comment by thomaslindstrom** [comment]
This is related: #3502

**Comment by hannes-landeholm** [comment]
I have the same problem in Atom 1.0.5 and Mac OS X 10.10.4. It's very annoying to not see what you are right clicking.

**Comment by sstur** [comment]
As @kevinsawicki has eluded to, this is an underlying problem with Electron/Chromium on Mac OS that the context menu blocks the UI thread while shown, so any UI updates that are deferred (requestAnimationFrame?) will not show until after the context menu has been dismissed. This will probably not be an easy fix but I'm guessing we need to either hack together a solution so that context menu does NOT block the UI thread (difficult) or we will need to implement our own context menu (ugly). Should we file a more generic task for fixing the context menu?

**Comment by zcbenz** [comment]
Related: https://github.com/atom/electron/issues/1854.

**Comment by mnquintana** [comment]
FWIW, I imagine that there is some workaround possible for this, if for no other reason than that VS Code managed to do it with their tree view.

**Comment by ssorallen** [comment]
A delay of just 10ms works for me, the same thing @kevinsawicki did above. 10ms still feels instant to me.

```cs
@subscribe $(document), 'contextmenu', (e) ->
  e.preventDefault()
  setTimeout(() ->
    atom.contextMenu.showForEvent(e)
  , 10)
```

**Comment by Zireael07** [comment]
Can @kevinsawicki's solution be incorporated into core?

**Comment by sstur** [comment]
The only issue with picking a timeout value is it seems so arbitrary. I mean it works for one person on one set of hardware but is it robust enough to count on? No matter what it's better than the current, broken behavior but a more elegant solution should be possible. I wonder if requestAnimationFrame in combination with setImmediate would be better.

    @subscribe $(document), 'contextmenu', (e) ->
      e.preventDefault()
      requestAnimationFrame () ->
        setTimeout () ->
          // TODO: Check e.target is still in the DOM?
          atom.contextMenu.showForEvent(e)

This would make sure any rendering that uses rAF has had the chance to update the UI. Does this work for you?

**Comment by ssorallen** [comment]
@sstur That only works **sometimes** for me, and that seems worse than always or never. It appears dependent on how much work is done in response to the `contextmenu` event, and I suspect the same problem would happen with `setTimeout`. The following is what I tried:

```cs
@subscribe $(document), 'contextmenu', (e) ->
  e.preventDefault()
  requestAnimationFrame () ->
    setImmediate () ->
      if document.contains(e.target)
        atom.contextMenu.showForEvent(e)
```

**Comment by sstur** [comment]
Yes, sometimes is much worse than always/never. I guess we should use the setTimeout with 10ms unless anyone can find a better solution...

**Comment by sstur** [comment]
I'm curious to know how they are doing it in VisualStudio Code. Is that open source? I can't seem to find any link to the source..

**Comment by sstur** [comment]
VS Code is now open source so it might be interesting to see how they work around this issue. As @zcbenz mentioned Chromium devtools also works around this. And in https://github.com/atom/electron/issues/1854 @Mingling94 mentioned a [workaround](https://github.com/Mingling94/Sia-UI/blob/61cfdf6bbdda25f36d9bc6409c2f0def69594330/index.js) using IPC although I haven't verified that.

**Comment by vjeux** [comment]
Seems like visual studio code is sending it via a timeout: https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/src/vs/workbench/services/contextview/electron-browser/contextmenuService.ts#L37

**Comment by scb00** [comment]
The same is happening to me in Atom 1.17.2 on Windows, but not only a visual issue! 
The actual file that the contextual menu action is applied to is the highlighted one, not the one under the cursor. This is only happening if you right click the tree view after focusing the file pane (if the focus is already in the tree view, it works fine).
To clear it a bit:
1. Click on a file in the tree view, in order to highlight it.
2. Click in the open file pane, in order to focus it.
3. Right click a different file in the tree view in order to open the contextual menu.
4. Select an action, for instance Rename.
5. The file path in the rename dialog is the first one, NOT the one under the cursor.

**Comment by zhanwenchen** [comment]
Still an issue for me. I wanted to delete an output file but inadvertently deleted my main program. I think a right-click highlight would have helped distinguish the two, especially if you click somewhere in between two files.
