### ISSUE TITLE
Have a browser version?

### ISSUE THREAD

**Issue by icode** [atom/atom#3088]
A browser vserion?core feature and smaller, ace a big editor

**Comment by jabbrass** [comment]
+1 for interest. Watching...

**Comment by djindjic** [comment]
I'm also interested to install atom on my private vps and edit vps's files from my client computer over browser. Is it possible now?

**Comment by thedaniel** [comment]
This is not currently planned.

**Comment by batjko** [comment]
Now, this issue being re-opened is going to spawn some heart flutter.

**Comment by rnorris7756** [comment]
This is definitely a feature I would be interested in.  Being able to set up a dedicated VPS to run one or more persistent atom sessions would be a very nice option to have.

**Comment by icode** [comment]
`Now, this issue being re-opened is going to spawn some heart flutter.`
+1

**Comment by thedaniel** [comment]
Don't get your hearts fluttering. This issue is currently a non-starter for many reasons. Even modifying just TextEditor so that it can be used in a webapp like Ace is likely to be opposed by the core team (at least by me and I expect @nathansobo) because TextEditor's performance within Atom is paramount, and making that extremely difficult task more difficult by worrying about environments that are not whatever stable Chromium release is tied to Atom is not appealing.

I don't care if we leave it open for discussion, just know that "run Atom in a browser" is on the "years, but probably not" timescale not the "months" timescale.

**Comment by batjko** [comment]
Perhaps it would be better then to close it off again and move any discussion into Discuss
For example here:
https://discuss.atom.io/t/can-the-editor-be-embedded-in-a-single-web-page

**Comment by weichert** [comment]
Looking at the desolate state of Posix on Windows it would be nice to be able to run the backend in a Linux VM for example and the frontend on Windows.
There are alternatives to this of course but I doubt they are faster.

For this you wouldn't need the frontend to be run in a browser, with all the compatibility concerns.

**Comment by batjko** [comment]
@weichert Technically there is no back end and front end with Atom. It's one application.

**Comment by weichert** [comment]
Alright, then  I'll remove my comment to reduce clutter.

**Comment by matanster** [comment]
What a pitty ;( this would have been nice..

**Comment by lextiz** [comment]
+1 for the feature request, even if the architectural change is significant it would drastically increase number of users and contributors.

**Comment by LeifRoss** [comment]
Hey,
On this issue, me and a friend has developed a platform that could be used to run Atom in the browser. 
Basically it is a "web operating system" with a filesystem that connects cloud storage systems into it.
The core philosophy behind the project is to create a open, free and hardware-independent portal, so you can access all your apps and files everywhere.

The system contains a IDE, and lets you write web applications that can take advantage of the file system. 

You can make applications with this sort of [architecture](https://github.com/LeifRoss/MultiplexExamples/tree/master/Applications/Personalize)

Atom would still need to be reformatted to work in the browser, but then it can access a desktop like file system to handle actual data etc, and then you would be able to access Atom from any device, with your own files.

[User Tutorial](https://www.youtube.com/playlist?list=PLXImnawFQOhJtIoz6cyJXn5ftrfjzVITN)
[Dev Tutorial](https://www.youtube.com/playlist?list=PLXImnawFQOhIFZWeM93ZYWWgRUuEPcdZL)

The developer tutorial is a bit old, contains the old IDE, but it does show some of the basics.

Going to open source the platform, starting with a few of the applications already written. We need to clean up the code a bit first tho. Anyways if anyone is interested in helping on the project when it is open-sourced, just send me a message, and I will notify you when we open the repository.

[Project landing page](https://getmultiplex.ninja)

// Don't mind the t-shirt slide, we tried to finance server hosting by selling t-shirts, but the response was quite limited. And the TOS, we are not fluent in legalese, so we need help to reformat it to reflect a more open system.

**Comment by AdrianDroid** [comment]
+1

**Comment by lee-dohm** [comment]
This is not something we are planning to work on in either the near or mid terms. It is something we would like to do someday. Until we have something more definite than "someday", because [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), we're going to close this.

We are interested in hearing people's ideas along these lines. Please feel free to discuss them on [the Atom message board](https://discuss.atom.io).

**Comment by drtangsoverlinevisit** [comment]
obviously a simpler version with a intelligent tab and a non-frame atom client overwrite web area will be very much easier to hack
