### ISSUE TITLE
Feature Request: add setup panel for proxy settings

### ISSUE THREAD

**Issue by muescha** [atom/atom#3119]
User should have a settings panel in Atom Settings for proxy.

PS: 
i know can can add manually a proxy here:

 `~/.atom/.apmrc` 
(Windows: `Atom\resources\app\apm\node_modules\atom-package-manager\.apmrc`)

but for newbe users of atom it would be better to have a settings panel

**Comment by jackmaney** [comment]
Please implement this. Ever since updating to roughly `0.165.0`, I can't even view my packages that are available to be updated. Instead, I get

```
Request for package information failed: tunneling socket could not be established, cause=140735192392464:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:
```

I want to use Atom heavily at work, but these proxy issues are getting in the way of that.

And yes, I've edited my `.apmrc`. No, it has no discernible effect.

**Comment by martincmelik** [comment]
Hi,
please consolidate proxy settings among other modules as well. For example Atom editor itself can recognize my proxy settings (somehow), but Atom package manager not.
Above of that as on windows you have separate folder structure for each version (Atom.0.X.Y\), I'm loosing setup from previous versions after update. Otherwise I will be fine with .apmrc proxy setup, but it is lost with every update.
Thank you

**Comment by emcek** [comment]
Still there is some issue with proxy. I set it form apm and npm as well:
```npm config set https-proxy="http://server:8080"  --global```
```apm config set https-proxy="http://server:8080"```

```npm config set proxy="http://server:8080"  --global```
```apm config set proxy="http://server:8080"```

But update some packages failing, due to 'no route to github:443'. 

```npm ERR! git fetch -a origin (https://github.com/Benvie/harmony-collections.git) fatal: unable to access 'https://github.com/Benvie/harmony-collections.git/': Failed connect to github.com:443; No error
```npm ERR! Windows_NT 6.1.7601```
```npm ERR! argv "c:\\Users\\gtqk84\\AppData\\Local\\atom\\app-0.175.0\\resources\\app\\apm\\bin\\\\node.exe" ``````"c:\\Users\\gtqk84\\AppData\\Local\\atom\\app-0.175.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" ``````"c:\\Users\\gtqk84\\AppData\\Local\\atom\\app-0.175.0\\resources\\app\\apm\\.apmrc" "--userconfig" "c:\\Users\\gtqk84\\.atom\\.apmrc" "install" ``````"C:\\Users\\gtqk84\\AppData\\Local\\Temp\\d-115026-108492-116ttze\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2010"```
```npm ERR! node v0.10.35```
```npm ERR! npm  v2.1.18```
```npm ERR! code 128```

```npm ERR! Command failed: fatal: unable to access 'https://github.com/Benvie/harmony-collections.git/': Failed connect to github.com:443; No ```error
```npm ERR! ```
```npm ERR! ```
```npm ERR! If you need help, you may report this error at:```
```npm ERR!     <http://github.com/npm/npm/issues>```

So, I add proxy for git as well:
```git config --global https.proxy http://server:8080```
```git config --global http.proxy http://server:8080```
but it doesn't work

**Comment by animedbz16** [comment]
Any updates on this?

This issue is one of the main reasons why I don't really use Atom since it is very difficult to set up behind a corporate environment.

I don't like having my AD/LDAP password stored in a configuration so Atom can connect through our proxy, especially since I'm required to change this frequently and if I forget to change this Atom will attempt to connect out through the proxy with an incorrect password and cause my AD/LDAP account to lock itself.

Other IDEs such as Webstorm allow for configuring the URL endpoint for the Automatic Proxy Configuration and can prompt the user for username / password per session.
