### ISSUE TITLE
Atom erasing the content of files when there is not enough disk space

### ISSUE THREAD

**Issue by xaviervia** [atom/atom#3158]
I have a hard time replicating this issue since it will require me filling up the disk again, but in a nutshell the problem is that when I edit a file in Atom, if the disk space is not enough to save it, I find that the file content is erased. 

This happened to me more than once (yeah I need more Gbs of disk space) so I can certify that it is Atom the one causing the issue. The issue appears whenever I edit the file, not when I just open it. The problem is not that Atom is not being able to save the file (that would make sense if there is no disk space available), the problem is that Atom _removes all the content_, and of course I'm afterwards not able to recover it.

I have no clue of why may this be happening

**Comment by jonas-schievink** [comment]
The same thing happens for me, and I still have more than 80 GB free (I'm on Windows). Why does Atom not tell me that something went wrong? Why doesn't it create backups before saving? Not cool!

**Comment by Zireael07** [comment]
An error message is definitely needed in such a case.

**Comment by forivall** [comment]
Yeah, this happened to me and it wiped out my config file, leading to me being unable to open atom due to conflicting packages that were disabled.

**Comment by alexandernst** [comment]
Not really sure why such a ridiculos and dangerous bug hasn't been fixed already. This should be nominated as "stop-everything-and-fix-this-right-now" instead of "1.0-roadmap" imho.

**Comment by xaviervia** [comment]
Right. I think there has a been a weird distortion in which the developers do not run at all into this issue and they are overlooking the fact that people with passable equipment are running into this once and again. Now, the issue with solving this is that it touches a very core part of how Atom works, I don't think anybody is ready to just contribute with a quick fix considering that it has architecture implications.

It would be nice to hear more thoughts from the core team though. If writing contents to a temporary file and then renaming is considered a reasonable idea then it is possible to fix it soon.

**Comment by 50Wliu** [comment]
This is already on the 1.0 roadmap, so it'll most likely get fixed in the coming weeks/months.

**Comment by bronson** [comment]
Hoping for 1.0.1...?  I'm definitely concerned that Atom is writing important data without using the [save-to-new-file-and-rename](http://stackoverflow.com/questions/1812115/how-to-safely-write-to-a-file) trick.

**Comment by nathansobo** [comment]
After a bit of research into this, I'm not sure that atomic saves are a good trade-off. Sublime Text 3 added them, but they're now disabled by default due to several issues with permissions, file metadata, and problems with other processes losing track of files they're trying to observe. I'm worried that adding this feature will create a bunch usability problems that will result in it just being disabled by default, which makes me feel like it's not worth the added complexity.

* What about checking that there's room to write the file before writing it? That would still leave us open to a hard crash or power outage in the middle of a save, but at least we would not be willingly walking off a cliff.
* Additionally, what about adding an option to create a backup of the files before writing it. If everything goes according to plan, this backup can be deleted. If anything goes wrong, it will be sitting there for later retrieval.

**Comment by xaviervia** [comment]
Good point. If it messed with watchers and whatnot, I would rather not have atomic saves.

Saving a backup on the other hand sounds like a good idea.

**Comment by bronson** [comment]
Interesting!  Good discussion [on stack overflow](http://stackoverflow.com/questions/20634684/what-is-sublime-text-doing-when-i-save-a-file) and the sublime forums ([overview](https://www.sublimetext.com/forum/viewtopic.php?f=2&t=11531), [encoding](http://www.sublimetext.com/forum/viewtopic.php?f=3&t=12947&p=50695), and [breaking hard links](http://www.sublimetext.com/forum/viewtopic.php?f=3&t=12660&start=0)).  In addition to the mentioned breaking observers and deleting resource forks / extended attributes, file encodings and breaking hard/soft links are problematic.

As for your first suggestion, checking for room before writing is racy and notoriously incorrect.  For example, if you're out of inodes, you'll see 20 GB free but get ENOSPC when you try to write.  And forget getting any meaningful number from a network share!  I'm not sure it buys anything.

Your second suggestion, writing a backup file before writing to the original file, definitely seems prudent.  I don't like the idea of needing to enable safety, though.  Seems like Atom should be safe by default, no?

If the user experience is an issue, what about putting a 500ms timeout on writing the backup file?  If it expires, put up an alert saying, "Writing the backup file is taking longer than expected.  You can disable them in the Settings Panel"?  But, given Atom's current filesize limitations, even network-attached users will probably rarely see it.

Remember to fsync before writing the main file...  Otherwise the user could end up with an empty backup file and an empty main file.

Overall, yes, I agree with your direction.

**Comment by nathansobo** [comment]
If anyone would like to take a look at https://github.com/atom/text-buffer/pull/87, I'd appreciate it. I'm going to start with this as an option that's off by default so we can have some folks test it out, then I'll flip the default. Let me know if there are oversights in the current implementation.

**Comment by bronson** [comment]
I left some pseudocode to fsync the files in an inline comment.  Tell me if you want me to expand that into a clean PR.  Should be pretty straightforward.

Syncing the data is required on posix and windows, syncing the directory is only needed on posix.  I assume fsyncing a dir is a no-op on windows but I've never tried.

**Comment by phord** [comment]
More scary details on the things that can go wrong with atomic-saves (even though they are the right way to do it) and ways to get around them, here:  http://stupidpythonideas.blogspot.com/2014/07/getting-atomic-writes-right.html

**Comment by Zireael07** [comment]
As pointed out in #10609, Atom should check if the backup is not empty.

Also, what are the advantages of atomic saves if so much can go wrong with them?

**Comment by jiangyy** [comment]
@Zireael07 Atomic saves work perfectly on POSIX environments. Cross-platform seems to bring much trouble.

Still, I am considering overwriting a file without backup is not to be a very good choice (though problems occur only in very rare cases). This problem not only happens when the disk is full (disk full is one extreme case), it may lose the entire file at system crash, even if there are plenty of spaces, just because the file is opened with O_TRUNC. File contents are truncated, then, system crashes, and then, everything is lost.

I am not a Node developer, just found such issues by an automated tool (I am even not expecting to find such issue in Atom!). Is there any more reliable library that can safely handle this situation?

**Comment by eriklarson33** [comment]
This issue doesn't appear to be closed despite it being labeled as such.  I'm fairly new to programming but I've used numerous editors and 3 times now over the past 6 months while using Atom I've had it completely delete all contents in my file.  This always happens after I click SaveAll.  Until, this issue is actually fixed I'm considering not using Atom.  I like the editability of Atom, but it's not worth the headache or insecurity of possibly losing all of my work even with using Github and duplicating my saves for backup.  Using an editor shouldn't involve risking your entire project.  This problem is specific to Atom and how it saves files.

**Comment by pkhateri** [comment]
This problem happened to me last night while I was using atom. Although I save the file every few second the content of the file disappeared after no disk space alarm. I lost the result of half day of my work. Lucky that I had the old version in git.. won't use atom any more unless this issue is solved.

**Comment by jemilsson** [comment]
This just happened to me. Lost a couple of hours work on a new project. This is really unfortunate behavior.

**Comment by yazdavar** [comment]
This problem just happened to me. So frustrated by this bug. Lost my 3 days efforts.

**Comment by hjohns12** [comment]
this issue happened to me just now. would love to see it fixed
