### ISSUE TITLE
feature request: Open... dialogue should contain option to see hidden directories on *nix OS'.

### ISSUE THREAD

**Issue by faddah** [atom/atom#3205]
On Unix/Linux systems (Mac OS X, BSD/Dawin, Ubuntu, Debian, Red Hat, Suse, CentOS, etc.), when using the **Open...** dialogue from either the **File** menu or **cmd.-key-O**, one should be able to have a checkbox option in the dialogue to see hidden files (files with a "." in front of them, or *Nix system directories). This would make it much easier to open and edit system environment variables from within Atom. Please add this feature.

best,

—  faddah wolf
     portland, oregon, u.s.a.
     github.com/faddah

**Comment by sworisbreathing** [comment]
+1 for adding this option. It's a relatively small change from an end-user perspective, and it has a tremendous impact on usability.

Since the dialog opening code is actually in Chromium and not Atom, how about at least adding a FAQ entry or something to the documentation, if not opening an enhancement request upstream? I didn't know about <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd> before I came across this issue, and I suspect even a lot of seasoned Mac users wouldn't know about it either.

Here are some common files I've needed to edit in a text editor lately. I've been falling back to VIM until now because I didn't know how to open them in Atom.

* `~/.kitchen/config.yml` (local machine configuration for Test Kitchen)
* `~/.m2/settings.xml` (local machine configuration for Maven)
* `~/.gradle/gradle.properties` (local machine configuration for Gradle)
* `~/.gitignore_global` (local machine configuration for Git ignores)
* `~/.ssh/known_hosts` (host public keys for SSH sessions)

**Comment by ccg** [comment]
I ended up here by googling "atom editor open dot file," because it is not at all obvious how to do this. I've been using a Mac for a long time but had no idea about <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd>. Also, this might be a problem with Mac OS X 10.10.5 itself, but the usability of that dialog is pretty bad. If I hit <kbd>Cmd</kbd>+<kbd>O</kbd> to open the Open Dialog and then hit <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd>, it does not initially display any dot files. I have to change to a different directory and then change back to the previous directory to see the dot files after I hit <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd>.

Even weirder, when Atom is working out of my home directory, if I hit <kbd>Cmd</kbd>+<kbd>O</kbd> to get the Open dialog, then <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd> to "show" (not really) my dot files, and then hit <kbd>Cmd</kbd>+<kbd>O</kbd> again, it opens my `.bash_profile`, even though I can't see it, and it wouldn't be the first dot file in the list if I could see it.

Anyway, the upshot is that, if I'm working in Atom and I want to open a dot file, I have to hit <kbd>Cmd</kbd>+<kbd>O</kbd> for the Open Dialog, then <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd> to reveal (but not really) dot files, then switch to some random directory, then switch back to the directory I was in, then select my file. Or I can open a terminal and do `atom /path/to/my/.dotfile`. Either way, it's kind of clunky, and it's not easily discoverable for a new user.

Thanks for taking the time to think about a fix for this problem. It sounds like it would be a fair amount of work.
