### ISSUE TITLE
Apple’s Text to Speech stopped working in a recent update

### ISSUE THREAD

**Issue by scottmartin** [atom/atom#3288]
https://discuss.atom.io/t/apples-text-to-speech-stopped-working-in-a-recent-update/11518

I am visually impaired and I use OS X's feature "Speak selected text when the key is pressed" located in the Dictation & Speech preference pane. I just noticed that this feature no longer works in Atom as of one of the last two versions. It now only reads the window's title bar no matter what text I have selected. It was working just fine before. It also works just fine under Chrome itself.

I'm not sure what caused this to break, but I depend on this feature all the time and can't really do without it. Does anyone have any ideas as to why?

I'm currently on v0.122 and I know it was working on v0.120 or v0.119. I'm also pretty sure I had enabled the React Editor before I noticed this being a problem, so I don't think that caused it.

**Comment by scottmartin** [comment]
Okay, I'm currently running Atom 1.0.19 and have just upgraded to OS X 10.11 and it seems this problem has come back. The text to speech engine is no longer seeing what I have selected. It just reads me the line numbers and bottom status bar information. Not sure if this is due to an Atom update or the OS update.

**Comment by izuzak** [comment]
Thanks for letting us know, @scottmartin -- I'm reopening the issue.

> The text to speech engine is no longer seeing what I have selected. It just reads me the line numbers and bottom status bar information. 

That's strange. I'm unable to reproduce that behavior, but I'm seeing strange behavior as well. When I first start Atom and select some text -- OSX reads that just fine. However, if I select some other text after that (in the same tab) -- OSX starts reading something completely different (the list of items in the tree view), and if I switch to a different tab in Atom and select some text -- OSX refuses to read that text.

@zcbenz Wondering if you have any ideas about this since you fixed this issue the first time. :pray:

**Comment by scottmartin** [comment]
@izuzak What you described is what I'm getting now. I swear when I did it last night it started reading the line numbers to me. Not sure what I did to make that happen.

**Comment by zcbenz** [comment]
It is probably because the accessibility tree is wrong some how, I'm cc-ing @theojulienne for help here since he [fixed the accessibility with VoiceOver](https://github.com/atom/electron/commit/ddfd2bc4bea7d016874b8be5ebc373219c72e2c7).

**Comment by theojulienne** [comment]
@zcbenz thanks for the ping!

Just to confirm, is VoiceOver active at the same time?

This looks like something has changed in Chrome. With the VoiceOver patch, I mimicked Chrome's behavior of enabling the accessibility tree when VoiceOver was active, and disabling the tree when inactive. This has the effect of allowing speech services to speak the selected text without the accessibility tree while VoiceOver is inactive (which uses an OS X built-in to find the selected text). When the accessibility tree is there, OS X tries to use the tree instead, and Chrome's implementation doesn't seem to work well with the "speak selected text" feature.

As of the latest Chrome and Electron on OS X 10.10, I'm seeing the full accessibility tree regardless of whether VoiceOver is active or not, which suggests Chromium has changed its implementation, either a bug or they decided they don't need the optimization of removing the accessibility tree (perhaps something related to support for 10.11?).

On 10.10 in Chrome, it always reads the entire page regardless of selected text, in Atom it fails completely and Speech Services is no longer in the Edit menu like it was before, and on the latest Electron it does the same as Chrome (reading the whole window), also without the Speech Services menu item. Hrmph.

On 10.11, does the text to speech engine work in Chrome as expected? I'm going to try and get a 10.11 VM up and running and trace this down.

**Comment by theojulienne** [comment]
Looks like this works in Chome on both 10.10 and 10.11 providing VoiceOver isn't turned on. As soon as it's turned on, it starts reading the whole page content from then on because the accessibility tree persists. Since it happens in Chrome, Atom and Electron it seems like that VoiceOver issue is the same. That was just due to my testing of VoiceOver first.

Opening a fresh copy with VO disabled, I can reproduce that Chrome speaks selected text and Atom reads the whole page on 10.11 and sometimes fails to read at all, but works fine on 10.10 as far as I can see. This is almost certainly a change in the way 10.11 handles accessibility, and Chrome has probably patched this. I'm going to take a look and see if I can find how they patched it and do something similar.

**Comment by theojulienne** [comment]
On 10.11 with VoiceOver disabled, the `AXEnhancedUserInterface` property is being set to `1` on the first TTS which is enabling the accessibility tree for the subsequent TTS calls. This means the previous patch which attempts to enable accessibility only when VoiceOver is enabled no longer does that, which breaks the "speak selected text" feature because Atom implements selection itself and doesn't pass this on to the OS. In Chrome this is fine since they now fully populate the accessibility tree, so I guess nobody has noticed the difference.

In Electron with an example page (not Atom), the whole window's text is being read rather than the selected text, since there is no focused form element. In Atom the "actual" currently selected text (the value of the hidden focused text box) is read for me, depending on where keyboard focus is. If some other element gets focus, that text is read instead. If no element has focus, then the whole window is read.

I guess the ideal fix here is to work out how OS X is querying the accessibility tree for the selected text and implement that, or make Atom fill in the hidden text field with the actually selected text.

For now, I've submitted https://github.com/atom/electron/pull/3040 which simply checks that VoiceOver is really enabled before enabling the accessibility tree, which should bring it back to the previous behavior.

**Comment by scottmartin** [comment]
I just got Atom 1.2.0-beta0 last night and it looks like it has caught up with the changes in Electron. Thank you @theojulienne, @zcbenz, and @izuzak. Once again you guys have saved me from a lot of frustration. This feature seemed to work so much more before Apple changed it into a set of APIs. It use to just copy highlighted text to the clipboard and read it from there. Now I just seem to have constant problems with it. A handful of apps like the official Twitter app still don't work with it.

**Comment by theojulienne** [comment]
@scottmartin Awesome, glad to hear the patch made it work again for you!
