### ISSUE TITLE
if statement without braces breaks indentation on many languages

### ISSUE THREAD

**Issue by SylvainBigonneau** [atom/atom#3333]
Using atom's latest verison, let's say I type something like this:

```
if (true)
  i = 1;
else
  i = 2;
```

And use auto-indentation on this block. It changes it into:

```
if (true)
  i = 1;
  else
    i = 2;
```

This happens at least with C and JavaScript, haven't tried others. To me, the first version that I typed should be correct. Is this considered normal behavior?

**Comment by lee-dohm** [comment]
Fixing auto indentation at this level will require an overhaul of the grammar system. It's something that we have in mind for the future but it isn't something we're actively working on. When we get a chance to rework the grammar system, I'll remind the team of this issue. Since we aren't working on this actively, I'm going to close this for now.
