### ISSUE TITLE
Opening a folder won't work until you try it again.

### ISSUE THREAD

**Issue by keeev** [atom/atom#3406]
Like I mentioned [here in my comment](https://github.com/atom/atom/issues/3405#issuecomment-53685094) opening a folder won't work for the first time you open it, wether if you drag&drop it or just open it via the shortcut. 

Same Problem on two different computers with Atom (0.124.0) running on Mac OS X (Mavericks).

**Comment by 50Wliu** [comment]
Bump-this is really hurting packages that rely on "properly" opening a folder in order to work.  Travis CI Status is completely useless with this bug (at least for me) since I basically have to open Atom twice.  I can deal with the fact that opening the folder the first time doesn't re-open the previously-open files, but it's really the fact that some packages don't work that get me :(.

Either that or the Travis status is doing something wrong.

**Comment by 50Wliu** [comment]
This seems to have been fixed a long time ago - I'm no longer experiencing this bug.  Maybe it's just because of the automatic session restore though.

**Comment by yves-vogl** [comment]
Same here on macOS.

```
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
