### ISSUE TITLE
[Windows] File menu opens up on different monitor

### ISSUE THREAD

**Issue by loktar00** [atom/atom#3415]
![menu atom](https://cloud.githubusercontent.com/assets/174857/4079329/127d686a-2ed4-11e4-99ee-c09ad0ef8d9a.png)

I have a 3 monitor setup, when atom is maximized on any monitor but the left most one the file menu opens up one monitor to the left.

Windows 7 
Atom vs 0.124.0

**Comment by Mellbourn** [comment]
It's still happening. 
Unfortunately, for me it is extremely consistent. I get it 100% of the time on my two screen computer.
Maybe reopen bug?

**Comment by 50Wliu** [comment]
This bug was never closed.  It's still a known issue.

**Comment by batjko** [comment]
Do we know yet where that behavior comes from? Is it definitely a Chromium thing, and if so, is there an open bug for it?

**Comment by kevinpas** [comment]
I think I caused a problem here.

When I first entered my post I hi-jacked another bug.

So, I am pretty sure that there are two bugs being talked about here.

The first bug is the menu not showing up in the correct place.
The second bug is then whole program not showing up (not visible) at all.

You might want to close this and open two others?

Sorry.

**Comment by batjko** [comment]
I was referring to the originally posted issue, i.e. the menu opening in the wrong spot. 
I'm sure if we stay focused on that one, this issue will be fine.

**Comment by onovotny** [comment]
Chrome had the same issue a while back (it's fixed now). Perhaps a newer version of Chromium would solve it?

**Comment by bpasero** [comment]
Any update?

**Comment by jayflo** [comment]
I have the issue where pop-up menus (spawned from right-click or via clicking an item on the menu bar, e.g. File, Edit, ...) show up at the edge of the monitor which is *not* displaying Atom in a dual monitor setup.  I experience the following behavior:

1-4 occur when Atom is aligned with the *right* side of my *right* monitor.

1) Opening Atom so that it's window width is 1/2 the width of the screen size keeps all pop-up menus in their correct position.
2) If I then drag Atom's window width past 1/2 the width of the screen, all pop-up menus begin to spawn at the edge of the opposite screen *except* those that appear when right-clicking on _text_ within an editor pane.  Right-clicking on empty space (when you can scroll past the last line) still causes the pop-up to appear on the left screen.
3) Then, dragging Atom's window size to be 1/2 screen width or less seems to correct the right-click menu positions.  However, it seems the pop-up menus spawned by the menu bar "gradually" correct themselves.  That is, when Atom's window width is dragged to be large enough, all menu bar pop-ups appear on the left screen.  As you decrease Atom's window width, pop-up menus corresponding to menu bar options further to the right correct themselves first, e.g. first Help appears correctly, then Packages, etc..  
4)  If, instead of dragging Atom's window width to be smaller, I use the Windows window manager short cut (Windows Key + right arrow) to resize Atom's window to be 1/2 the screen width, all pop-up menus are fixed.

When Atom is fit to the left side of my right monitor, it seems the pop-menus always spawn on the left monitor, regardless of size/dragging.

Atom: 1.0.2 (latest)
Windows: 8.1 (fully updated)

**Comment by StarrWulfe** [comment]
I use Atom on a laptop that when docked, also uses a 23" Dell monitor as a secondary screen.

If I close Atom where the last window was on that screen, when I reopen it later with just my laptop display active, Atom shows up on my taskbar but doesn't spawn in the screen-- it's still trying to appear in the secondary monitor! 

Thankfully, my laptop is also a 2-in-1 convertible device so I can simply change to tablet mode and bring it back up.  But it's a bit of a PITA when I forget!

**Comment by batjko** [comment]
@StarrWulfe I have seen that before, with quite a number of applications that had nothing to do with Chromium.
Upon de-serializing the window's state when opening the application, if the previously saved position was on the off-monitor (now closed or otherwise unreachable), the new window position isn't adjusted to the new dimensions (i.e. one monitor instead of two).

Not sure what it would take to change that behavior, though.

**Comment by StarrWulfe** [comment]
@batjko so is it a framebuffer/windows manager issue, or Atom not making proper calls to either one to get the updated condition of said windows manager? 

All my other programs have no issues with this BTW, so it seems to me that Atom may have left something out of it's display code somewhere.

**Comment by jackmaney** [comment]
I'm still having this issue on Win7 x64, Atom 1.0.7

**Comment by nathansizemore** [comment]
This issue also effects me.

Not sure if various scaling per monitor make the issue reproducible, but setup is to extended, and the extended monitor has scaling to 100% while the main monitor has scaling set to 125%. When using Atom in the extended monitor, the window will open docked to the far right of the main monitor.

Windows 10 x86_64
Atom v1.0.11

**Comment by demiazz** [comment]
Mac OS X version affected too.
