### ISSUE TITLE
Elastic scrolling not working on editors

### ISSUE THREAD

**Issue by dgraham** [atom/atom#345]
Can the rubber band scroll effect at the top and bottom of the editor when reaching the end of the scrollable area be enabled?  I'm not sure if this works yet on scrollable divs, but it would be nice.

**Comment by mnquintana** [comment]
:+1: 

This issue is ancient at this point, but I managed to resurrect it in [Discuss](https://discuss.atom.io/t/scrolling-with-rubber-banding/4413) so why not here! :smiling_imp: 

This enhancement would go a long way toward making Atom feel even more native on OS X. For those who dislike the effect there could always be a config setting to disable it.

@zcbenz Would this be possible in atom-shell right now? I couldn't tell from looking at the docs.

**Comment by zcbenz** [comment]
@mnquintana If we want to implement native elastic scrolling the editor view has to be a native `NSView`, however in Atom the editor view is just a normal DOM element, so the only way to have elastic scrolling is to implement it with JS and CSS.

**Comment by ioquatix** [comment]
Could you instantiate a NSScrollView in the background and throw events at it and measure the scroll offset?

**Comment by mnquintana** [comment]
Does standard Chrome / Chromium implement native elastic scrolling, or is it simulated with JS and CSS?

> Could you instantiate a NSScrollView in the background and throw events at it and measure the scroll offset?

I'd be curious to find out if this would work too.

**Comment by zcbenz** [comment]
> Could you instantiate a NSScrollView in the background and throw events at it and measure the scroll offset?

Why do we need to do this? There is already some algorithms to calculate the scroll offset of elastic scrolling.

> Does standard Chrome / Chromium implement native elastic scrolling, or is it simulated with JS and CSS?

In Atom the whole interface including tabs and tree-view is just a web view. we can not do the same with Chrome, in Chrome everything except the web view is a native view.

**Comment by ioquatix** [comment]
@zcbenz if the algorithm is exposed some other way then sure it should be used. I've never looked. If you just try and copy the algorithm, it might look odd if you don't get it exactly right.

**Comment by fulldecent** [comment]
#5588 has an animation, for people that are not clear on what is being discussed

**Comment by edwellbrook** [comment]
+1

**Comment by steverandy** [comment]
It may not improve anything in term of functionality, but on OS X, it makes the app feel more native.

I'm currently building an app with electron, and trying to look for any CSS property that may enable elastic scrolling on OS X for <webview> tag. But so far no luck.

**Comment by duongel** [comment]
+1
Still the killer feature i miss..

**Comment by ApricumMedia** [comment]
I'd wholeheartedly would like to bump this for 2017. Coding the entire day on a laptop with a trackpad makes scrolling gestures a crucial part of the experience. Safari and Chrome both support elastic scrolling (even though Chrome doesn't feel as native, the elasticity is different). Is this part of Electron?

**Comment by AJB99** [comment]
+1
The hard stop of the scroll is making my back hurt.

**Comment by atomiks** [comment]
Here is a CodePen demonstrating a JS/CSS way of achieving the effect:
https://codepen.io/anon/pen/ZadKOx?editors=1010

Please improve it if possible 😃 

It's not 100% perfect as the translating seems to slightly glitch randomly sometimes. Also, moving the mouse stops the wheel event from firing, which is why there is a transition to put it back to the default position when the mouse moves.

**Comment by ioquatix** [comment]
- It's still an issue with 1.33.0
