### ISSUE TITLE
unexpected behavior (focus on the folderview)

### ISSUE THREAD

**Issue by ericrange** [atom/atom#3542]
when i select a file in the folder view (left side)... why this do not change the focus to the content of the file??

because my workflow is:
1. select a file
2. press Ctrl+f to search something (but nothing happens because the focus is still on the folder view)

everytime i have to click on the content of the file to get the focus... this is a bit disadvantageous

**Comment by binarylogic** [comment]
Couldn't this be an easy configuration setting? It is rather annoying.

**Comment by YemSalat** [comment]
@lee-dohm shouldn't `Ctrl + 0` reset the font size?

**Comment by lee-dohm** [comment]
@YemSalat On OS X <kbd>Cmd+0</kbd> resets the font size. But yes, it does appear that there is a collision between <kbd>Ctrl+0</kbd> the two functions on Windows/Linux.

**Comment by brkattk** [comment]
I'd be willing to spike on making this a configurable setting if someone can point me in the right direction. It's endlessly frustrating to click on a file once and expect to begin editing, especially since tabs can now be "preview tabs"

**Comment by msmaili** [comment]
Assuming making this a setting would take up too much time, is there any way we could put logic in the init script that listens for the tree view event and puts focus on the editor?  I feel like that may be a fair compromise for now, as long as it's possible to do :)

**Comment by murdoch** [comment]
Did anyone have any luck with this? Is it a configurable setting now?

**Comment by lee-dohm** [comment]
Single-clicking leaves the focus in the Tree View. Double-clicking shifts focus to the editor.

**Comment by murdoch** [comment]
Sure but it is configurable? I really don't like having to click twice to gain focus on the code. I often forget that you need to click twice, because I've been using Sublime for so long, which results in me clicking once and typing a bunch of stuff, before realising after 2 or 3 seconds that it's nothing is coming out on the screen. It interupts my flow. I've stopped using Atom because of this. And every few months I return to this issue tracker to see if it's been made into a configurable setting. Is this a hard thing to fix?

**Comment by 50Wliu** [comment]
@murdoch you may be interested in https://atom.io/packages/single-click-open

**Comment by lee-dohm** [comment]
@murdoch Everything is configurable in Atom but not everything is a configuration option with a quick switch or selection. Some configurations may require you to install a package, as @50Wliu pointed out, or even customize code yourself. There are only so many configuration options that a team of maintainers can support. This is one that we've decided not to support so that we can put our efforts in other places that we feel are more important.
