### ISSUE TITLE
File duplicated in different project

### ISSUE THREAD

**Issue by kiwitotoro** [atom/atom#3646]
Hello, This is a step by step of what I remember happening leading up to the duplication of the file.

Opened a Wordpress theme package in Atom, when I was finished I closed that window (I did not close atom).
Selected 'Open...' from the menu and opened a different project.
Opened a few pages and made some edits.
Opened settings and saw that a theme was out of date so I updated it.
Pasted some info from a website into a file and saved it.

It was when hitting 'control s' that I noticed a new file appear (page.php):

![atom-files](https://cloud.githubusercontent.com/assets/775993/4430240/52a763d8-4625-11e4-9b1a-d94cf6d6feea.png)

This file was from the previous Wordpress project and it was now in the new project.
I can't recall if I had been editing that file or if it was open when I closed the previous project.

I have since upgraded to version 0.132.0 (The request to upgrade was in the menu) So I guess the version was the one before this.
The theme I updated was Monokai (https://atom.io/packages/monokai).

**Comment by kevinsawicki** [comment]
This is a pretty old issue and a lot has changed since September regarding saving editors and some bugs in autosave which sometimes caused issues.

Please comment if you are still seeing this on Atom 1.0.3 and if you see it when running `atom --safe` since it might be being caused by a third-party package.
