### ISSUE TITLE
getCurrentWordBufferRange doesn't seem to work correctly for words like change-case

### ISSUE THREAD

**Issue by deiga** [atom/atom#3650]
I'm trying to get the current word under the cursor and the default options of `getCurrentWordBufferRange` should AFAIK enable matching words with non-space separators, but currently the regex seems to have been misconfigured so that it doesn't match word correctly.

Current code:

``` coffee
wordRegExp: ({includeNonWordCharacters}={}) ->
includeNonWordCharacters ?= true
nonWordCharacters = atom.config.get('editor.nonWordCharacters')
segments = ["^[\t ]*$"]
segments.push("[^\\s#{_.escapeRegExp(nonWordCharacters)}]+")
if includeNonWordCharacters
  segments.push("[#{_.escapeRegExp(nonWordCharacters)}]+")
new RegExp(segments.join("|"), "g")
```

Correct code:

``` coffee
wordRegExp: ({includeNonWordCharacters}={}) ->
includeNonWordCharacters ?= true
nonWordCharacters = atom.config.get('editor.nonWordCharacters')
segments = ["^[\t ]*$"]
if includeNonWordCharacters
  segments.push("[#{_.escapeRegExp(nonWordCharacters)}]+")
  segments.push("[^\\s]+")
else
  segments.push("[^\\s#{_.escapeRegExp(nonWordCharacters)}]+")
new RegExp(segments.join("|"), "g")
```

**Comment by izuzak** [comment]
@deiga Can you share an example which demonstrates the problem and explain why you expected different behavior? Does using a different `editor.nonWordCharacters` help you get the behavior you expected?

**Comment by izuzak** [comment]
I'm unable to reproduce. For the string `foo-bar-baz` and the cursor positioned like this `foo-b|ar-baz`, the result of calling `getWordUnderCursor()` is `bar` which is expected given the default config setting for non word characters which includes `-`. If I change that config setting so that it doesn't include `-`, `getWordUnderCursor()` returns `foo-bar-baz`, which is again expected. If you can still reproduce this problem -- please provide a full example.

**Comment by izuzak** [comment]
Re-opening this since another issue I was just looking at helped me understand and reproduce the problem: https://github.com/atom/atom/issues/6538#issuecomment-140348629.
