### ISSUE TITLE
Folder colors don't update to reflect git changes

### ISSUE THREAD

**Issue by gmmeyer** [atom/atom#3656]
If I save a file, the file (in the sidebar) will change colors to tell me that it has changed, but only if the folder tree is open to that file. If I save it otherwise, the folder will change colors. If the folder tree is collapsed and I save it with a new change to the git repo, the folder will change colors to reflect new changes in the sub folders.

But, this process does not work in reverse. If I am removing git changes (whether through saving from an open file, or git checkout from the command line) the file itself will change colors, if the folder tree is open all the way down. But, the folders above it will not change colors. Likewise, if the folder tree is collapsed at any point, the folders will not change colors to reflect the changed status below them. The folder tree below the folder I am on will change colors (when I open it, of course it updates) but the folder I am on itself will not.

This is a bit hard to explain, so I will illustrate it with an image. 

![atom folders](https://cloud.githubusercontent.com/assets/3253673/4446071/57bf8414-47ff-11e4-9850-465d0120b71a.png)

The sub-tree has no files changed in it, they were changed, but I removed the changes. The folder was collapsed to the folder that is currently selected. While the folders below expressed the change once it was expanded, the folder that I was on did not express the change, neither did the folders above it. The behavior is a bit confusing. The expected behavior is that the folders above the current one would change to the new updated git status.

**Comment by nazarioa** [comment]
I have a similar issue. I have a repo which has files and folder in the side bar who's colors do not reflect their actual state. In my guess there are several yellow or green items but if on the command line i do a > git status on that repo, it tells me everything is up to date.

The interesting thing is that other repos do not seem to exhibit this behavior.

How is it that you have generated that nifty gif; I ask so that I can send you what I see.

- Mac OS 10.10.3
- Atom Version 0.211.0 (0.211.0)

**Comment by gmmeyer** [comment]
Ah, I never updated this, I have not had this issue in a very long time. I should have closed it long ago. :-/

**Comment by nazarioa** [comment]
You are correct, this is a none issue. I compared the files that acted normally from those that did not and I noticed that they had different permissions for the executable bit. I changed the file permissions of my files to 755 and atom was then able to display modifications correctly. I am not sure if this is by design or not. 
Thanks for the patience.
