### ISSUE TITLE
Add a grunt task that publishes directly to Launchpad.

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#3717]
- [BuildingASourcePackage](https://help.launchpad.net/Packaging/PPA/BuildingASourcePackage)
- [Uploading](https://help.launchpad.net/Packaging/PPA/Uploading)

Seems like it's a matter of having the right key installed on the right box, and running

```
debuild -S -sa
dput ppa:atomeditor/ppa <filename>.changes
```

Relevant, of course is the [Ubuntu Packaging Guide](http://packaging.ubuntu.com/html/)

**Comment by Joshua-Anderson** [comment]
Ok. I have confirmed that the [launchpad builders have no internet access](https://answers.launchpad.net/launchpad/+question/260227). I would pre-install the node modules first, but I don't think I can do that because atom needs to build native architecture dependent packages, right? Any advice on how to approach this? Would it be possible to build atom without intenet access

**Comment by jedahan** [comment]
Would also love to see this

**Comment by Nagendhiran** [comment]
Its really awesome if we have this in place. It will really help most of Ubuntu and debian members. Waiting on it. :)
