### ISSUE TITLE
Add new editor.tabType scoped setting

### ISSUE THREAD

**Issue by benogle** [atom/atom#3719]
While digging into scoping `editor.softTabs` in https://github.com/atom/atom/pull/3718, it's pretty clear that the setting has very little influence on the actual value chosen. It's effectively the worst-case fallback: it only works on an empty file.

I propose doing a couple things:

* adding a new `editor.tabType` setting that accepts 3 values: Auto, Hard, Soft. With the default being `auto`. Then in the scoped settings for each language, they can set it to whatever they want. 
* Changing `TextEditor::setSoftTabs` to being a settings override accepting 4 values: unset / use-the-settings, Auto, Hard, Soft
* Reading the settings on each time we need to get the tab type. Something like (pseudo code): 

```coffee
getTabType: (scopeDescriptor) ->
  @userTabTypeOverride or atom.config.get(scopeDescriptor, 'editor.tabType') or atom.config.get(scopeDescriptor, 'editor.softTabs') or 'soft'
```

See https://github.com/atom/atom/blob/4231d6942101c3e77a1d0371cf3b61045b8fa6fb/src/text-editor.coffee#L93 and https://github.com/atom/atom/blob/4231d6942101c3e77a1d0371cf3b61045b8fa6fb/src/text-editor.coffee#L2319 for reference.

Refs 
* https://github.com/atom/atom/issues/3584 

Comment if you know of more issues, complaints. I know there have been several complaints about this, but cant find issues.

**Comment by jplatte** [comment]
+1, I would really appreciate a fix!

**Comment by TeckniX** [comment]
+1 on getting this actually working properly, since certain file extensions do not respect the tab/spacing rules

**Comment by lexicalunit** [comment]
:+1: This would be neato!

**Comment by remillc** [comment]
+1 This soft tab issue is pretty annoying...

**Comment by NioTeX** [comment]
:+1: We need this

**Comment by ScottPeterJohnson** [comment]
:+1:  Really hard to work in indentation-sensitive languages when suddenly Atom inserts spaces instead of tabs.

**Comment by alexandernst** [comment]
Not really sure how such a critical issue didn't make it for 1.0. Shame on Atom for still not being able to manage spaces/tabs

**Comment by xaviergmail** [comment]
:+1: I find myself having to replace all tabs with spaces and re-open a file to get tab to insert spaces properly, which isn't very intuitive.o

**Comment by JeffreyVdb** [comment]
This should be made possible language specifically. Most languages have their own coding conventions. This is a critical bug if you ask me.

**Comment by pbhogan** [comment]
:+1: Can't even *think* of switching to Atom for actual work until this is fixed.

**Comment by fedorov** [comment]
+1

**Comment by unRob** [comment]
+1

**Comment by thomasjo** [comment]
All the +1's only add noise at this point, so I'm locking this issue until someone begins working on it. At that point we may re-open it for discussion purposes.

**Comment by jeffmcneill** [comment]
Most reports of issues seem to be closed without resolving the underlying problem. There is only one open I could find (on cursory clicking):

## Closed

- #5497 
- #3719
- #5192

## Open 

- #4054

The big issue as reported is the inaccurate "guessing" combined with the inability for an editor-wide setting (and not per-file setting). It may be that several preferences may be required instead of having one monolithic setting which is clearly causing unhappiness:

- Default for all files (y/n)
- Default for certain files (by file extension)
- Setting on per file basis

The idea would be to be able to re-order these in terms of priority, based on the needs of the user.

**Comment by asbjornu** [comment]
I'm with @jeffmcneill on this one; it's still a problem in Atom 1.16.0 and the current settings just doesn't work. The [editor-settings package](https://atom.io/packages/editor-settings) outlines a lot of the functionality I would like to see in Atom wrt. whitespace handling, but it also does not work correctly as it seems to be fighting with Atom on what tab type should be used. Couple that with the [whitespace package](https://atom.io/packages/whitespace) and you have complete chaos.

I would love to see the current settings, packages and everything related to whitespace wiped from the face of the earth, because it's bug-ridden junk that Just Doesn't Work. Then, I would like to see something implemented along these lines:

1. A base setting for tab preference that did not try to be smart in any way. Just a clear "hard tab" or "spaces" (the phrase "soft tab" is just confusing; please get rid of it) that perhaps can have a checkbox for "change existing whitespace on save".
2. A way à la [editor-settings](https://atom.io/packages/editor-settings) to configure tab preference for every language (and/or file type). This should override the previous setting.
3. Support for [EditorConfig](http://editorconfig.org/). If there's an `.editorconfig` file in the project file hierarchy that is an ancestor or sibling to the current file, use that to adjust the tab setting of the file. This should override previous settings.

With these three levels all supported within Atom without any packages, I believe it's possible to reach sanity and get rid of a lot of bug-ridden, "intelligent" code that obviously doesn't work and also serve the needs of most people.
