### ISSUE TITLE
ctrl+alt+f2 does not add a bookmark

### ISSUE THREAD

**Issue by combiths** [atom/atom#3930]
I'm having trouble adding / removing bookmarks using ctrl+alt+f2. According to my keybindings that should toggle a bookmark for a certain line which isn't the case. When I go to the menu and click Edit > Bookmark > Toggle bookmark it works. Please advise. Thanks.

**Comment by LoneBoco** [comment]
You may have something on your computer that has registered a global hotkey with Windows.  The Intel graphics and media control panel is one of those that registers CTRL+ALT hotkeys.  Its always caused a problem for me with Sublime Text as it uses CTRL+ALT+Up/Down to expand the selection (Atom uses this keybind too) and Intel defaults to using those key strokes as global hotkeys for rotating your display.  And even disabling it will sometimes not give you control over those key combinations, so sometimes you have to re-bind them to some other combination.

**Comment by 50Wliu** [comment]
Heh, I just tried to test this on Linux and forgot that Ctrl+Alt+F2 shunted you off the graphical display and to the terminal...whoops.
I do have some Intel stuff on Windows, but I don't think I have hotkeys enabled for it.  I'll check when I get back on Windows.

**Comment by WadeShuler** [comment]
@LoneBoco I haven't tested or verified what you said. If it is true that those keys are not available on Intel PCs, then it would make sense that it is a design flaw on Atom's shoulders (copied from Sublime). You can't simply say that ALL Intel users have to re-setup their bindings for the CTRL+ALT keys. 1, that just will be a never ending supply of complaints and support issues popping up for many years. 2, it affects way too many people to ignore it. - Atom should, out of the box, use different key binding combinations to completely eradicate this issue.

**Comment by 50Wliu** [comment]
I can confirm that my issue is due to Intel's keybindings (that no one knows about since they're documented only in like the 10th result of a Google search...).

Echoing what @WadeShuler said: Atom should use different key bindings for this, just as the key binding for changing encoding was switched on Linux to avoid a conflict.

**Comment by jwfeng** [comment]
@LoneBoco This approach solves my problem，Disable Intel graphics shortcuts.

**Comment by ignotus0001** [comment]
Disabling the Intel graphics keyboard bindings also worked for me on Windows 7 (yes I'm still using it at work :-(   ) Anyway, this article has details: http://superuser.com/questions/279756/how-to-disable-the-screen-orientation-hotkeys-in-windows-xp

**Comment by carlosacp** [comment]
I have this issue too on Mac OSX 10.10.3 . When I do cmd+f2 (or cmd+fn+f2 in case of my laptop) it emits a beep sound and nothing works. When I click Edit > Bookmark > toggle bookmark it works.

**Comment by WadeShuler** [comment]
I think Atom by default, needs to change the keybindings on the function keys. As stated, this is probably due to something else on your system bound to those keys (ie: Intel graphics), breaking them in atom.

Until recently, I was using CTRL+ALT+B:
    'atom-text-editor':
        'ctrl-alt-b': 'bookmarks:toggle-bookmark'
        'ctrl-alt-2': 'editor:fold-at-indent-level-2'

However, I just realized that CTRL+ALT+B is used for Beautify as well. CTRL+B and ALT+B are used up too. I changed it to CTRL+SHIFT+B, which the keybinding resolver indicates its the fuzzy-finder:toggle-git-status-finder. I don't use git inside Atom anyways, I just like to see the colors in a project under git so know visually what files have been edited before committing.

**Comment by msemp** [comment]
If you're using a Mac (I'm using OS X Yosemite 10.10.3), the problem is likely in the basic keyboard setup for function keys. See https://support.apple.com/kb/PH13982?locale=en_US for details. After I selected the “Use all F1, F2, etc. keys as standard function keys” checkbox, my bookmarks key bindings worked fine.

**Comment by mjrev** [comment]
i had the same problem. disabling `hkcmd.exe` from startup on windows solved the problem

**Comment by lianyi** [comment]
Got the same issue! win7 64bit

**Comment by WadeShuler** [comment]
We have established that it has to do with intel or similar, hijacking the command for it's own uses.

Easy solution, create a key map yourself for something unused. I prefer ctrl-alt-space. Works nicely.

**Comment by lianyi** [comment]
@WadeShuler thanks, the workaround works for me!

**Comment by vijayyadav1002** [comment]
Use in User Keybind setting the below code:
 'atom-text-editor':
   'ctrl-f2': 'bookmarks:toggle-bookmark'

**Comment by damieng** [comment]
Confirmed working in recent Atom builds - appears to be an issue with Intel's video driver systray app also using this shortcut. Either unbind it there or rebind to something else in Atom.
