### ISSUE TITLE
Setting Atom as default file editor not working in Ubuntu 14.04 with LXDE (Lubuntu)

### ISSUE THREAD

**Issue by matkoniecz** [atom/atom#4036]
To reproduce: install Atom following https://github.com/atom/atom/blob/e6e039293add0173bc71b89333b9d051b49d23b6/docs/build-instructions/linux.md

Use "Open with" and select "Set selected application as default (...)" checkbox.

Expected: double clicking on file will open Atom with clicked file opened
Actual: Atom is opened with a new file with name the same as clicked file. It is necessary to manually open files from Atom.

It may be Ubuntu/LXDE bug, but other software has no problems like this.

**Comment by StevenGFX** [comment]
I came across this issue as well. I'm running Lubuntu (LXDE) and installed atom via atom-amd64.deb. Files were displaying as empty when opening them in Atom. I had to add project folders to the tree view and choose the files there in order to see their contents. I also found that changing the Atom command for default programs in the LXSession config from `/usr/bin/atom %U` to `/usr/bin/atom` seemed to correct the issue. Not sure what %U does but other programs use it and seem to be fine.

**Comment by matkoniecz** [comment]
> It will be closed if no further activity occurs. 

Well, that is an interesting approach. I already encountered projects where reporting bugs is pointless as due to project size number of bugs is massive and probably nearly everything was reported already (it probably makes sense to report security issues).

But "let's ignore bug reports and close them because we ignored them" is a new one.

**Comment by 50Wliu** [comment]
Closing until it can be confirmed that this is still an issue on Atom 1.19.3.

**Comment by matkoniecz** [comment]
I should remember to never waste time reporting issues in this or other Github's sideprojects.
