### ISSUE TITLE
Indent-guess isn't working correctly after switching between spaces and tabs

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#4054]
Auto-guessing indent isn't working correctly after changing between spaces and tabs indent style.

Please see video: http://youtu.be/IP11Y8H2Q70

**Comment by alexandernst** [comment]
@benogle Now that #3719 got fixed, can we get this one?

**Comment by alexandernst** [comment]
Still happening with 1.0.19

**Comment by alexandernst** [comment]
Still happening with 1.3.2
This was supposed to be fixed before 1.0, or shortly after. What is the problem? Is there some other issue that must be fixed before this one?

**Comment by alexandernst** [comment]
Still happening with Atom 1.4 stable and 1.5.0 beta

**Comment by 50Wliu** [comment]
Retagging to bug since it seems more like a bug than a feature.

**Comment by alexandernst** [comment]
Still happening with Atom 1.7

**Comment by sandrodz** [comment]
yep still here.

**Comment by jeffmcneill** [comment]
Most reports of issues seem to be closed without resolving the underlying problem. There is only one open I could find (on cursory clicking):

## Closed

- #5497 
- #3719
- #5192

## Open 

- #4054

The big issue as reported is the inaccurate "guessing" combined with the inability for an editor-wide setting (and not per-file setting). It may be that several preferences may be required instead of having one monolithic setting which is clearly causing unhappiness:

- Default for all files (y/n)
- Default for certain files (by file extension)
- Setting on per file basis

The idea would be to be able to re-order these in terms of priority, based on the needs of the user.

**Comment by sandrodz** [comment]
@jeffmcneill 

> It may be that several preferences may be required instead of having one monolithic setting which is clearly causing unhappiness

well we have editorconfig for that don't we? I don't want atom taking on the functionality of editorconfig. But I'd love it to guess better and play nicely with editorconfig settings.

**Comment by pdf** [comment]
Since issues related to soft-/hard-tabs seem to get closed without the root problem being fixed, I'll just add comments here rather than create a new issue, or commenting on one of the closed issues, even though the comments are slightly tangential to the original issue.

Auto-detection of indentation is certainly desirable, especially if it works reliably.  That said, per-language indentation settings are not just desirable, they're a requirement.  Most languages have some opinion on preferred indentation, and linters will complain if the wrong format is used, some languages with significant white-space will simply break if the wrong indentation is used.

One-size-fits-all indentation makes Atom extremely cumbersome for anyone who works across multiple languages that have incompatible indentation standards.

It appears that #3719 may provide some foundation to build per-language indentation, is this the case?  Is there an issue to track this?  What's involved?

**Comment by 50Wliu** [comment]
The tab type and size can already be scoped per-language, and each language can specify their own indentation rules.  Some examples are:
https://github.com/atom/language-python/blob/master/settings/language-python.cson
https://github.com/atom/language-sass/blob/master/settings/language-sass.cson
https://github.com/atom/language-yaml/blob/master/settings/language-yaml.cson

**Comment by pdf** [comment]
@50Wliu thanks, I tried searching, but either my google-fu isn't working, or the documentation is lacking.  Would also seem sensible to mirror the global tab settings in the language package settings GUI.

**Comment by 50Wliu** [comment]
> Would also seem sensible to mirror the global tab settings in the language package settings GUI.

Can you elaborate?  I believe they already are.

**Comment by pdf** [comment]
Language packages display a GUI setting for `tabLength`, but not for `tabType` or `softTab`.

**Comment by 50Wliu** [comment]
@pdf Can you please open a new issue for that?

**Comment by Ben3eeE** [comment]
@50Wliu https://github.com/atom/settings-view/issues/835

**Comment by pdf** [comment]
Thanks @Ben3eeE, just came to open the issue, have added a note that both settings should probably be displayed.
