### ISSUE TITLE
File readable in atom is unreadable in vim and gedit

### ISSUE THREAD

**Issue by nylki** [atom/atom#4133]
In Atom 0.145 I had some problems with the file encodings. A file with special characters (umlauts -> ü,ä,ö) was readable in atom after saving and trying different encodings. But in vim and gedit, it looks like 
`@d^@t^@ ^@a^@n^@d^@ ^@t^@h^@e^@ ^@e^@p^@i^@p^@h^@a^@n^@y^@ ^@o^@f^@ ^@t^@h^@e^@ ^@f^@a^@c^@e^@ ^@(^@K^@o^@e^@r^@n^@e^@r^@)^@
^@K^@o^@e^@r^@n^@e^@r^@ ^@a^@n^@a^@l^@y^@s^@i^@e^@r^@t^@ ^@d^@i^@e^@ ^@I^@n^@t^@e^@r^@p^@r^@e^@t^@a^@t^@i^@o^@n^@m^@ö^@g^@l^@i^@c^@h^@k^@e^@i^@t^@e^@n^@ ^@d^@e^@s^@ ^@G^@e^@s^@i^@c^@h^@t^@s^@ ^@i^@n^@ ^@d^@e^@r^@ ^@K^@u^@n^@s^@t^@,^@ ^@i^@n^@s^@b^@e^@s^@o^@n` etc.

**Comment by jtkiley** [comment]
This issue is related to this [Discuss thread](https://discuss.atom.io/t/viewing-non-printable-characters-in-text-files/6539).

It would be really nice to see these kinds of things displayed visually and have some way of seeing what they are (with the various encoding representations). BBEdit does this really well. It's not as a big deal for one file (as, presumably, you could copy the visually displayed character and replace all with nothing), but it's nice to know what to clean up in a script when it's hundreds of thousands of files.
