### ISSUE TITLE
Feature request: Most recently used (MRU) files and folders

### ISSUE THREAD

**Issue by ghost** [atom/atom#4241]
I would like to be able to find files or folders that I have recently opened in previous editing sessions. On Windows this is usually done under the File menu. For example: File > Recent Files > (displays a sub menu of top 10 most recently used files in descending order).

File

> Recent Files
>        > (top 10 most recent files)
> Recent Folders
>        > (top 10 most recent folders)

**Comment by mnquintana** [comment]
:+1: This would be an awesome addition. I think the issue title and tags should be updated though because this isn't actually a Windows-only enhancement – all OSes should get some kind of File > Open Recent menu item and Windows and OS X should both get recent files / directories listings on their taskbar / dock right-click menus, respectively.

(It might've been lost in that whole paragraph, but to reiterate **the `windows` tag should be removed and the issue title should be updated to remove "Windows"**)

**Comment by 50Wliu** [comment]
I think I do have a "Most recent" on Ubuntu when I do File-->Open Folder.

**Comment by mnquintana** [comment]
@50Wilu Isn't that "Recently Used" Place in the File > Open Folder dialog on Ubuntu just "recently used" by *any* program, not just Atom?

**Comment by 50Wliu** [comment]
Ah, yes, you're correct.

**Comment by jerone** [comment]
There's a package for this https://atom.io/packages/open-recent

**Comment by Zren** [comment]
Hey, author of open-recent here. The one thing I was wondering about if I wanted to merge the plugin into atom itself is if using `localStorage` for serializing the recent paths is okay.

Using atom's config to serialize the paths doesnt seem right since it updates the file every time you open something and might annoy people whove synched/use version control on their `config.cson`.

**Comment by lee-dohm** [comment]
This feature was recently added for OS X and I believe Windows too in https://github.com/atom/atom/pull/9609.

Leaving this open and labeling it for Linux.

**Comment by pflannery** [comment]
> This feature was recently added for OS X and I believe Windows too in #9609.

This isn't working on Windows 10 in Atom 1.6.2.

**Comment by 50Wliu** [comment]
@pflannery Can you try Atom 1.7.0?

**Comment by pflannery** [comment]
@50Wliu ok. I've just tried 1.7.0 and I've managed to get files to appear but only when using the "File->Open File" menu.

![image](https://cloud.githubusercontent.com/assets/1727302/14233130/64304524-f9b7-11e5-8ed3-dba648ac46ba.png)

It's not working when right clicking a file in explorer and choosing "Open with Atom".
It's also not working for folders.

**Comment by pflannery** [comment]
there is also an issue when clicking on the file in the jump list

![image](https://cloud.githubusercontent.com/assets/1727302/14233169/c5723670-f9b8-11e5-93a3-ee1110661fd0.png)

package.json is definitely there and available

**Comment by 50Wliu** [comment]
Ok, thanks!  Can you please open a new issue for what you're experiencing?

**Comment by plbowers** [comment]
Not sure if I should comment here or open a new issue.

Normally in windows if you right-click on an icon in the taskbar it shows a MRU list there and you can jump right into it. Atom shows some files there (can't figure out which ones, though - they have no connection with my MRU from the menu) but the most important list would be project directories and they don't seem to show up there.

(1) Request to have this list updated by Atom whenever a file is opened
(2) Request to have this list updated by Atom whenever a project directory is opened 
(3) It would be nice if these to MRU lists would be separated as they are in the menus

**Comment by VisualTrauma** [comment]
Maybe a recent files list like **PhpStorm** `ctrl+tab` that can be searched as well?
