### ISSUE TITLE
Non-leading tab invisibles are not properly aligned to the indent guides

### ISSUE THREAD

**Issue by D1SC0tech** [atom/atom#4265]
Any tab invisibles that are not leading a line get bunched together instead of being evenly spaced. 

**Expected Behavior**
![screen shot 2014-11-20 at 17 32 45](https://cloud.githubusercontent.com/assets/3586264/5135240/16d6088c-70dc-11e4-9435-5ca757428c54.png)
*Notice how each tab is spaced evenly on a 4-character grid*

**Observed Behavior**
![screen shot 2014-11-20 at 17 32 40](https://cloud.githubusercontent.com/assets/3586264/5135243/1fdc99fa-70dc-11e4-88f5-dc27c0cf716c.png)
*The tabs are all bunched up at the beginning of the whitespace*

**Comment by izuzak** [comment]
Thanks for this report and sorry for the delay in replying.

> The tabs are all bunched up at the beginning of the whitespace

I don't think that's true. If you add another tab between the names and values of those defines, you'll see this:

<img width="272" alt="screen shot 2015-09-17 at 17 37 52" src="https://cloud.githubusercontent.com/assets/38924/9937871/eaa10ad6-5d62-11e5-9dbb-e82bf10b8a77.png">

In other words, what you observed is a consequence of the tab width you chose and the specific text. If the text ends 1 character before the next tab stop, then pressing `tab` two times cause the invisible characters representing a tab to be next to each other because there's no other place to put the first invisible character. That's the difference between these two lines:

<img width="242" alt="screen shot 2015-09-17 at 17 41 06" src="https://cloud.githubusercontent.com/assets/38924/9937962/4d5a6f1e-5d63-11e5-93ab-2b340c3589cc.png">

On line 2, there's no other place to put the first invisible character for the tab.

In SublimeText3, that problem doesn't exist since it uses a different way of representing tabs:

<img width="235" alt="screen shot 2015-09-17 at 17 42 37" src="https://cloud.githubusercontent.com/assets/38924/9938029/9964517c-5d63-11e5-82ab-85b8b81158b6.png">

That might be a solution to consider, but that would be a different issue for discussion.

I'm going to close this since I think it works as expected, but let me know if I misunderstood. :v:
