### ISSUE TITLE
Make Atom run on Debian 7 Wheezy

### ISSUE THREAD

**Issue by frankgerhardt** [atom/atom#4335]
Related to #2131 #3926

https://github.com/atom/atom claims that Atom runs on Debian. It doesn't. 

The .deb file can not be installed because of a naming conflict. 

I can buld it on Debian it still doesn't run. 

GLIBC_2.14 and/or GLIBC_2.15 is required. No, installing that from the experimental repo is not a good idea. 

So, please make Atom run on Debian 7 Wheezy.

**Comment by slashsBin** [comment]
:+1:

**Comment by schipplock** [comment]
I'm on debian 7.8 and get the same error:

> a@a:~$ /usr/share/atom/atom: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/libchromiumcontent.so)
/usr/share/atom/atom: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/libgcrypt.so.11)
/usr/share/atom/atom: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /usr/share/atom/libgcrypt.so.11)

This specific glibc version is from 2011-06-07 and has several security flaws. Kind of strange that most big projects completely ignore debian. StarUML the same. I wonder what they use to create these binaries. Probably Ubuntu 12.04 LTS.

**Comment by NDavidBrown** [comment]
I got Atom working very quickly by following the [unofficial instructions here](http://axiacore.com/blog/atom-editor-debian/).

**Comment by SiIky** [comment]
I'm not sure if my problem is related to this issue but i didn't find other issues about this and could be related.
I installed Atom 1.0.0 a few days ago on a Debian 8.1 (Jessie) Virtual Machine (with the VBoxLinuxAdditions installed). I didn't find any trouble during the install process (downloaded the .deb package from GitHub and ran 'dpkg -i' on it). It was all fine and good until i opened some files and tried to edit something with it. Changing through tabs and opening menus was really slow and buggy.
My problems were the following:
* If i opened one of the menus (the File menu, for example) and moved the mouse cursor to any other menu (Edit, View,...), File menu would still be open and the other menus wouldn'd open.
* When switching between tabs of opened files it would take about 1 or 2 seconds for them to change.

At first i thought it was a problem with my PC (i had some more programs running), so i tried restarting it, and run the VM only. The problem persisted, so i thought it was because of being a VM (even though i haven't had any problems with other programs before).
To test it, I installed Atom on Win8.1 (my host System) and it's working well, i wrote this text with Atom!

Both problems seemed to be of graphical nature.

I'm using a laptop with these specs:
* Intel i5 4200U @1.6
* 4GB RAM
* HDD with space to spare
* Win8.1 64-bit
* nVidia GeForce GT740M, 2GB dedicated (this probably isn't helpful, but just in case)

I'm using the latest version of VirtualBox and, as said above, i have the additions disc installed.

Didn't intend the post to be this big, sorry about that :D

**Comment by Dillybob92** [comment]
Sorry for the long response, but any update to this? :8ball:

**Comment by 50Wliu** [comment]
Is anyone still experiencing this problem?

**Comment by dizzyking** [comment]
Hi, I'm using Debian on VirtualBox (on a Windows laptop).
I have just tried installing Atom and Brackets on it.

Brackets was buggy, it had issues with overlapping windows and virtual desktops. I supposed they had to do with Unity, so I disabled it and Brackets runs flawlessly since.

Then I tried installing Atom, via `dpkg -i atom-amd64.deb`, but when I launch it, I get a black window with some white artifacts in it.

(Installed In Windows, Atom works great.)

**Comment by dizzyking** [comment]
Hi, I'm using Debian on VirtualBox (on a Windows laptop).
I have just tried installing Atom and Brackets on it.

Brackets was buggy, it had issues with overlapping windows and virtual desktops. I supposed they had to do with Unity, so I disabled it and Brackets runs flawlessly since.

Then I tried installing Atom, via `dpkg -i atom-amd64.deb`, but when I launch it, I get a black window with some white artifacts in it.

(Installed In Windows, Atom works great.)

**Comment by 50Wliu** [comment]
@dizzyking You are running into a VirtualBox bug.  To get around it, run Atom using `atom --disable-gpu`, or disable 3D acceleration in VirtualBox, or downgrade Guest Additions to (I believe) 5.0.19.

Since no one has answered my question, I'm closing this issue.

**Comment by cielavenir** [comment]
I put a tips for those who visit this issue from googling.
http://qiita.com/cielavenir/items/7835e3d110d7ad79c407

**Comment by dizzyking** [comment]
@50Wliu Thank you so much. Sorry I'm late, I missed the mail notification for your reply. 

Atom does work on Debian with the `--disable-gpu` param. Amazing. Thank you.

**Comment by cielavenir** [comment]
Let me write down a note that (although 1.17.2 works) 1.18.0 will not work on Wheezy since we cannot install libsecret.
