### ISSUE TITLE
Undo grouping is too eager

### ISSUE THREAD

**Issue by postcasio** [atom/atom#4372]
Undo grouping seems to group any editor changes no matter what kind of change it was, which results in confusing/unexpected behaviour.
1. Create a new file
2. Paste some text into it
3. Immediately begin typing
4. Undo

Atom will group both the pasting and the typing, so the undo removes everything. Ideally it should only remove the typing, with the paste being a separate undo. ST2 has this behaviour and its much nicer. I'll often start typing after pasting some code, and want to undo something I just typed. It's infuriating when the whole lot disappears!

The same problem happens for many editor commands such as `editor:auto-indent`. Perform an auto indent, then begin typing (or run another command). Undo will revert both.

My suggestion is that Atom should only group sequences of identical commands. Disparate commands should never be grouped.

Are there cases where grouping disparate commands makes more sense than keeping them separate?

**Comment by hnsl** [comment]
I was annoyed by this behaviour just now (eager undo grouping) and hope it can be fixed. I believe there are very few editors out there, if any, that would consider typing and pasting the same action in the undo history. So I doubt this behaviour was by design and it could arguable be considered a bug.

**Comment by clozach** [comment]
I'd like to second @mehcode's suggestion: typed character groupings should end on click, paste, copy, cut, etc. It's quite jarring to have far more text disappear than you expected when undoing. Equally frustrating, it's possible for a selection change to get grouped with a text change. This causes the editor to jump before one gets a visual on the changed text, making it very difficult not to make mistakes when undoing after navigation.

**Comment by clozach** [comment]
Incidentally, I wonder if the reason this hasn't had any attention is that the label was downgraded from `bug` to `enhancement`. Given that the current behavior causes actual emotional distress when encountered (seriously!), please consider reverting it to `bug`.

**Comment by clozach** [comment]
(No, stalebot, no! 🙀)

If someone can point me to the right package in core, I'm happy to re-submit the issue there and/or attempt a PR fix. 😬

Also, @maxbrunsfeld, please reconsider the `enhancement` label. As @hnsl suggested, this is a bug, not an enhancement. Cheers!

**Comment by doughsay** [comment]
Please reconsider looking into this issue again.  I've been using Atom for quite a while now and I love it, but this issue is a complete blocker for some people to start using Atom.  My co-worker will absolutely not consider atom because of the "horrendously broken undo-behavior" (his sentiment).

Here is a GIF comparison I made of ST3 vs Atom undo behavior:

Default ST3 behavior:
![sublime-undo](https://user-images.githubusercontent.com/221693/39549673-941bfe88-4e13-11e8-8ad5-e86918dd5616.gif)

Default Atom behavior (300ms grouping interval):
![atom-undo](https://user-images.githubusercontent.com/221693/39549705-ac835674-4e13-11e8-811b-ec17eb82830f.gif)

I seem to be able to ignore this behavior and work just fine with Atom, but (maybe especially fast typers) just can't get over it.
