### ISSUE TITLE
Atom Cursor causes high CPU load (20% x 2 processors.)

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#4378]
The way atom does cursors causes a high CPU load when debugging anything inside of atom because it is constantly causing chrome inspector to update which is apparently very expensive.  It would be nice if the cursor would also pause when the inspector is in focus, or for there to even be an option to simply disable the blink entirely since it has many performance problems (actually, if the cursor weren't blinking there would be no CPU usage in general with Atom on my Linux system.)

There is probably a ticket for the latter but the former is an issue of it's own I think (I searched.)

**Comment by DarkArc** [comment]
I don't really notice an issue with this, but if there is still a problem, it may be in relation to atom continuing to toggle the classes for the cursors even when the editor pane is not in focus. It's worth noting, this issues has no visual manifestation since the selector for the cursor's visible state is ".is-focused .cursor". 

This is more likely to have some more significant performance impact if many cursors are used, over many editor panes.

**Comment by wmertens** [comment]
@DarkArc I too noticed that the cursor classes are toggled even when the cursors are invisible. These wakes cause a constant battery drain when the app is in the background.

**Comment by nathansobo** [comment]
I've been thinking about this too. We should probably just completely disable the blinking when an editor isn't focused instead of using CSS to do it. I will see what I can do about this today.
