### ISSUE TITLE
HTML/CSS auto-indent shouldn't trigger when code is in a variable

### ISSUE THREAD

**Issue by pistou** [atom/atom#4448]
Hi,

I use Atom to code in PHP and I often insert HTML into PHP strings.
Auto-indent shoudn't be "calculated" _on_ HTML into the var, but on PHP since I'm writting PHP code.

Here is an example of what I'm saying. The left part is what it is actually doing. The right part is what it sould do.

![example](https://cloud.githubusercontent.com/assets/6703711/5340842/5fe566da-7ef1-11e4-8418-4f81cacd6e96.jpg)

**Comment by chfritz** [comment]
@maxbrunsfeld this is related to the same issue I was pointing out [here](https://github.com/atom/atom/pull/10384#issuecomment-171802354): using regexes for indentation is not very stable because it doesn't make good use of the tokenizer. In this case, e.g., the tokenizer would already have told us that the recognized regex match is inside a string, and would be ignored. This is fixed in my pull request, but I'm also thinking of completely new indent logic that uses tokens directly (rather than just using tokens to see which matches are in strings).
