### ISSUE TITLE
Editor selections API not working in code, works when run manually in DevTools

### ISSUE THREAD

**Issue by ilanbiala** [atom/atom#4565]
I have a snippet that is part of a package, and it hasn't been working in the last couple versions of Atom. At one point it was working, but that was maybe 1-2 months ago. The code would only format selected pieces of text in a file, but it doesn't work now. When the code is run in the app, it doesn't seem to work, but when it is run manually in DevTools, it works properly.

The `formatJavascript` method is the first one that is called, which then calls `selectionsAreEmpty` to see if there are any selections. That snippet always returns `true` when run through the package though.

```coffee
  formatJavascript: (editor) ->
    editorSettings = atom.config.get('editor')

    opts = atom.config.get('jsformat')
    opts.indent_size = editorSettings.tabLength
    opts.wrap_line_length = editorSettings.preferredLineLength

    editorText = editor.getText()
    beautifiedText = jsbeautify(editorText, opts)

    if (editorText != beautifiedText)
      if @selectionsAreEmpty(editor)
        editor.setText(beautifiedText)

      else
        for selection in editor.getSelections()
          selection.insertText(jsbeautify(selection.getText(), opts), { select: true })

  selectionsAreEmpty: (editor) ->
    for selection in editor.getSelections()
      return false unless selection.isEmpty()
    return true
```

Has something changed in the API that isn't in the latest version of the API docs?

**Comment by ilanbiala** [comment]
This is all the information I have. The code is running in an Atom package, so anyone can do some investigating. Maybe I'm missing something or maybe something in the API isn't working as it should, but this has been open for a while now and I haven't gotten any response.

**Comment by ilanbiala** [comment]
@benogle have you experienced this issue yet?

**Comment by izuzak** [comment]
@ilanbiala I'm trying to reproduce this, but having trouble. Here's what I did:

1. Added this to my init.coffee file:

  ```
  atom.commands.add 'atom-text-editor', 'test:selectionsAreEmpty', ->
    return unless editor = atom.workspace.getActiveTextEditor()
  
    for selection in editor.getSelections()
      if selection.isEmpty()
        console.log("Empty selection")
      else
        console.log("Non-empty selection: #{selection.getText()}")
```

2. Reloaded Atom
3. Opened a new file
4. Typed some text
5. Placed a few cursors in the text, but no selections
6. Triggered the "test:selectionsAreEmpty" command via the command palette
7. Opened the devtools console and observed that there were only "Empty selection" logs there
8. Closed devtools
9. Pressed `esc` to remove extra cursors, then placed a few cursors again and added a few selections
10. Triggered the "test:selectionsAreEmpty" command via the command palette 
11. Opened the devtools console and observed that there were the correct number of "Empty selection" and "Non-empty selection" logs there

I also observed the same expected behavior with this in my init.coffee file:

```
atom.commands.add 'atom-text-editor', 'test:selectionsAreEmpty', ->
  return unless editor = atom.workspace.getActiveTextEditor()

  selectionsAreEmpty = ->
    for selection in editor.getSelections()
      return false unless selection.isEmpty()
    return true

  console.log(selectionsAreEmpty())
```

It always logged "true" if there were no selections, and always logged "false" if there was at least one selection.

Can you provide similar step-by-step instructions which reproduce the problem for you?

**Comment by ilanbiala** [comment]
@izuzak it's been about 6 months, so I'd assume that something about this has changed..It's probably safe to close because the bug has been fixed.
