### ISSUE TITLE
--wait should not auto-focus the next open window but return to where it was opened from

### ISSUE THREAD

**Issue by mtodd** [atom/atom#461]
My scenario to explain my problem:

I have Atom open editing. I commit changes and then `--amend` with `EDITOR="atom --wait"`. When I close the `COMMIT_MSG` file to return to the terminal, it automatically focuses the next open Atom window instead of going back to the terminal.

Not sure if that's possible, but I was expecting to go back to the Terminal window I had open before to continue.

**Comment by Dru89** [comment]
:+1: 

This seems to have been left open for a while, so I'm not sure if anyone's still looking at it.  I got here through https://discuss.atom.io/t/atom-w-doesnt-behave-like-other-editors/13383/2

It seems to me like the best way to handle this would be the way that Sublime handles it:

1. User types `atom --wait foo.txt`
2. If a window already exists, open a new tab and load `foo.txt`.  If no window exists yet, open a new window with a new tab and load `foo.txt`.
3. When the user closes the tab (not the window), the `--wait` is over and can be relinquished back to the terminal.  Ideally, the terminal would focus here, as well.

Is this the plan here, or what are people thinking specifically?

**Comment by mmindenhall** [comment]
Before switching to atom, I was using TextMate as my git editor (mate -w -l 1).  It sounds like TextMate also behaves like Sublime -- i.e., returning the focus to the terminal that launched the editor in "wait" mode, regardless of whether other TextMate windows are open.  

It would be really great to have atom work the same way, as I keep tripping on this in my habitual git workflow:

1. Write some code
1. commit from terminal with `git commit`, which launches `atom --wait`
1. Type commit message and close window
1. Type `git push ...` :boom: I'm typing in another atom window (possibly on another display) instead of the terminal

**Comment by humansounds** [comment]
:+1: to this.  this is one of the reasons i'm still using sublime :cry:

**Comment by carolineschnapp** [comment]
:+1: very much needed

**Comment by dougshamoo** [comment]
bump, anything new on this one?
