### ISSUE TITLE
Want API for changing the cursor blink rate

### ISSUE THREAD

**Issue by masochist** [atom/atom#4825]
I don't see any documentation for this, so maybe it's my fault, but I would like an API for changing the cursor blink speed. It's faster than most other apps on OS X, and the inconsistency squicks my CDO. I definitely don't need or want it changed in the base app, but would like the ability to make a package for it. I am aware of [ease-blink](https://atom.io/packages/ease-blink) but I don't see the API it uses in the documentation, and the search isn't finding it. I will freely admit that I am brand new to Atom and thus am probably missing something; pointers to the manual would be greatly appreciated, if that's what I'm missing!

**Comment by lee-dohm** [comment]
There is a topic on [Discuss, the official Atom forum,](https://discuss.atom.io) that talks about the feature you're asking for and suggests a hack for a workaround:

https://discuss.atom.io/t/how-to-set-cursorblinkperiod-in-new-react-js-editor/11064

**Comment by apeiron** [comment]
I knew there was a hackish way to do it--that's [what ease-blink](https://github.com/miraks/ease-blink/blob/master/lib/ease-blink.coffee#L28) does--but I'd like something documented so that it survives implementation changes.

**Comment by mostafaeweda** [comment]
:+1:

**Comment by lee-dohm** [comment]
It's already possible to customize the cursor blink rate or style using the `styles.less`. You can see examples here:

* [Make the cursor pulse instead of blink](https://www.atom-tweaks.com/users/lee-dohm/tweaks/80aecdac-9676-4912-ab24-6b774cbf3de2)
* [Stop the cursor from blinking](https://www.atom-tweaks.com/users/lee-dohm/tweaks/ad269434-86a7-4405-9ea8-cb01107fa948)

Since we aren't intending to add a feature for this to the Atom API, I'm going to close this issue. Thanks very much for the feedback!
