### ISSUE TITLE
Replacing ^ and $ broken with "only in selection"

### ISSUE THREAD

**Issue by DiThi** [atom/atom#4838]
In search and replace, enable the *Use Regex* and *Only In Selection* buttons and replace ^ or $ by any string. I expect the string to be prepended or appended to all selected lines.

In most combinations of selection (dragging down, up, starting or ending at a start or end of the line or not...) it leads to unexpected results, such as the replacement string being prepended/appended to somewhere before or after the selection, to all lines but the last one, to the beginning of the file or nothing at all.

It works as expected when *Only In Selection* is disabled.

**Comment by lee-dohm** [comment]
`^` and `$` have [special meanings in regular expressions](http://www.regular-expressions.info/refanchors.html) (and you state that `Use Regex` was enabled), so the fact that they work *without* being escaped when `Only In Selection` is disabled is most likely due to atom/find-and-replace#303. The behavior you mention with regard to them being used in conjunction with `Only In Selection` is almost assuredly expected behavior.

If there is behavior that you believe is inconsistent with how these anchor characters are supposed to work, please open a new bug on the [find-and-replace package](https://github.com/atom/find-and-replace). It would be most helpful if you could include some repro steps outlining what you did, what happened as a result and what behavior you expected to happen.

**Comment by DiThi** [comment]
Did you even read what I wrote? Anyway I opened thee issue here https://github.com/atom/find-and-replace/issues/336
