### ISSUE TITLE
Windows 64bit release

### ISSUE THREAD

**Issue by MetaMemoryT** [atom/atom#4881]

**Comment by zcbenz** [comment]
Refs https://github.com/atom/atom-shell/issues/980.

**Comment by dbpolito** [comment]
would love to see this!

**Comment by wesleyhf** [comment]
I want this please. My machine beg. :+1:

**Comment by sabas** [comment]
Electron x64 has been released, it's possible to add x64 build? Thanks

**Comment by Zireael07** [comment]
Would be brilliant - I'm on a x64 OS.

**Comment by Stanzilla** [comment]
Would be good to know what's actually missing to get it working or if it is "just" release eng./setting up tests that needs to be done.

**Comment by paulcbetts** [comment]
I actually think this might be somewhat complicated because it fucks the .atom folder. Consider the following scenario:

1. Everyone's using 32-bit Atom because it's the only Atom
1. "Hey, a new 64-bit Atom exists!", they download it
1. All of their ~/.atom folder is built for 32-bit. Kerplowie.

Separate from that, the steps to make a 64-bit build isn't too hard, Slack only ships a 32-bit build then silently upgrades amd64 machines to the 64-bit version by changing the Squirrel update URL

**Comment by call-a3** [comment]
:+1:

**Comment by Stanzilla** [comment]
Any news about this?

**Comment by vgturtle127** [comment]
@Stanzilla No, but I'm sure they are considering it. I mean, 64-bit has been around for years, and there isn't a whole lot stopping them from compiling it for 64-bit platforms.

**Comment by KevinMartin** [comment]
Bump

**Comment by paulcbetts** [comment]
> and there isn't a whole lot stopping them from compiling it for 64-bit platforms.

https://github.com/atom/atom/issues/4881#issuecomment-145319657

**Comment by KevinMartin** [comment]
@paulcbetts isn't that what the `--squirrel-updated` option is for? To take the time to upgrade dependent resources such as those in the `.atom` folder?

**Comment by paulcbetts** [comment]
@KevinMartin You're not wrong, but the problem is that you only get a certain amount of time in that hook, 15sec. Recompiling every node module in that folder could take 5-10+ minutes if you're really unlucky - basically, Atom would need to create an interactive UI around upgrading this folder, because otherwise users will kill it ("Why is node.exe using 100% CPU?!?!?! Task Manager!"), or if it's tied to Atom.exe's lifetime, people will close Atom and then trash their .atom folder

**Comment by DamnedScholar** [comment]
@paulcbetts Does that have to be interactive? A dialog box that says, "Please wait, Atom is upgrading the contents of your .atom folder," with a progress bar or even just an estimated time frame would be sufficient.

**Comment by paulcbetts** [comment]
@DamnedScholar When I say "Interactive" I just mean, "It has like a flow of "Start this thing => It's Running! => We're done"

**Comment by Stanzilla** [comment]
@paulcbetts maybe make it work for new installations only then, for now?

**Comment by Splike** [comment]
Any news on this?

When running the 64 bit installer, it should detect that Atom is already installed. The new installer will mention this and ask if we would like to upgrade from 32 bit to 64.

If this is not possible, then just detect that a 32 bit installation is present, and ask us to uninstall it first, before running the 64 bit installation file.

**Comment by gluons** [comment]
electron/electron#980 closed.
Any news for Windows 64 bits release?
I subscribed this issue. 😳

**Comment by NFiorentini** [comment]
Personally, I'm more than willing to re-install Atom from scratch if it meant getting 64 bit Atom.  Let's make this happen!

**Comment by damieng** [comment]
Atom now supports a 64-bit version on 64-bit Windows.  If you build from source with a default node that is x64 you will get an x64 build of Atom and apm (make sure you build both).

Dev builds are available on appveyor, will try and get this included in the next beta. (Still some testing to do on the update pipeline)

**Comment by RodriguesCosta** [comment]
Where to download 64bit version?

**Comment by Stanzilla** [comment]
@RodriguesCosta https://github.com/atom/atom/releases/tag/v1.14.0-beta0 scroll to downloads

**Comment by RodriguesCosta** [comment]
@Stanzilla thank you

**Comment by damieng** [comment]
It's currently only for 1.14-beta builds - it should appear on https://atom.io/beta if you're on a 64-bit version of Windows.
