### ISSUE TITLE
Atom 0.166.0 Windows fails to open in dev mode after editing package.json

### ISSUE THREAD

**Issue by AustP** [atom/atom#4883]
I wanted to work a bit on [atomatigit](https://github.com/diiq/atomatigit). So the first thing I did was run `apm develop atomatigit`.

I tweaked the main file to alert when loaded, started Atom in dev mode, and got the alert.

I then made one tweak to the package.json file and now Atom won't load in dev mode. The only way I can get it to load again is if I undo the changes that I made to that file and end all of the atom.exe processes.

Also as a note, editing a package.json file while not in dev mode produces the same result of the application not starting at all. Therefore, I have 2 suggestions to make Atom better.

1. If a package.json has been tampered with, instead of not loading the entire program, just don't load that one package.
2. If in developer mode, skip the package.json tampering check.

**Comment by lee-dohm** [comment]
What did you do to the `package.json`? Did you change the dependencies? Did you install or update the dependencies after you did so but before you launched Atom?

**Comment by AustP** [comment]
@lee-dohm No I didn't change the dependencies. The only change I made was removed [lines 6-8](https://github.com/diiq/atomatigit/blob/master/package.json#L6-L8) so the package would start automatically.

**Comment by lee-dohm** [comment]
You changed the `package.json` to activate on load. I suspect the package assumes certain things to be in place before it is activated, since it is designed to be activated by a user action. That could be causing the problem you're seeing.

Now, if Atom is simply refusing to load and not giving any sort of feedback, dialog or what have you, then that is an issue ... but it isn't really anything to do with the `package.json`.

**Comment by AustP** [comment]
@lee-dohm Right. I'm sorry if I wasn't clear enough before. I edited the package.json before I opened Atom. After editing the file, I would try to open Atom and it would not open. I didn't get any error messages or anything. I gave it a few minutes and after nothing happened I tried again. Same thing. I had been using the context menu `Open with Atom` so I then tried to open it with the command line. I also tried adding the `--dev` flag. I then tried to just open Atom from the executable. It all resulted in the same thing.

So I opened task manager and started trying again. I saw that when I tried to open Atom, a few atom.exe processes would start up. There were about 4. But even though they would start up, Atom would not open and if I wasn't looking at the processes I would have no indication that Atom even tried to start (other than a spinner mouse for a few seconds after opening).

The only way I could get Atom to start again was to add those 3 lines back into the package.json file and to kill all of the atom.exe processes.

**Comment by lee-dohm** [comment]
Thanks for the extra detail. I'm not sure I can track down what atomatigit is doing to cause Atom to spin in this manner. Can you reproduce the issue if you take out the alert box but still remove the `activationEvents`? Perhaps the alert box shows up ... but is in some way invisible because the UI hasn't been shown yet? And then the whole thing is waiting for you to click an Ok button you can't see.

Just a guess.

**Comment by AustP** [comment]
@lee-dohm Wow. You were totally right haha. I removed the alert and tried again and Atom opened right up. Note to self: Don't alert on init. =) Thanks for your help on this.

**Comment by lee-dohm** [comment]
You're very welcome! Glad I could help :grinning:
