### ISSUE TITLE
Periodically check for available updates

### ISSUE THREAD

**Issue by ultramiraculous** [atom/atom#4936]
Could we get an indicator when there's an update available for Atom, in addition to the file menu?  If someone leaves Atom open for days at a time, they could easily end up several versions behind.

I'm picturing something like Chrome's indicator, where the hamburger icon goes from green->yellow->red depending on how stale the user's version is.  Maybe just a little light in the status bar.

**Comment by benogle** [comment]
Doesnt the squrrel icon serve this purpose? Do you ever see a blue squirrel in the bottom right of your status bar?

**Comment by lee-dohm** [comment]
@benogle Does Atom check for updates periodically while open? If it does, I haven't noticed. It seems to only check on startup and when manually requested from the menu. The scenario @ultramiraculous mentions of leaving Atom open for several days at a time would explain why maybe they haven't seen the squirrel.

**Comment by kevinsawicki** [comment]
> Does Atom check for updates periodically while open?

Definitely doesn't on Windows, I don't think it does on Mac but I'd have to dig into the squirrel code to be sure.

Atom only triggers update checks via the Squirrel APIs at startup.

**Comment by ultramiraculous** [comment]
Yeah, what @lee-dohm says makes sense for the situation I'm noticing.  If Atom isn't checking periodically, I'd imagine I'd never see the icon.

**Comment by lee-dohm** [comment]
I hope you don't mind me revising the title, @ultramiraculous :grinning:

**Comment by abe33** [comment]
I like @lee-dohm idea of the color changing squirrel, but I'd rather use blue->red gradient rather than green->red. Maybe it could be completed with a a blinking animation that gets more insistent the wider the gap between version gets.

**Comment by mark-hahn** [comment]
>  a blinking animation

Arrghh.  Please don't.

**Comment by lee-dohm** [comment]
> I'd rather use blue->red gradient

Actually, given the recent discussion about color-blindness, I think this is a wiser choice too.

**Comment by ultramiraculous** [comment]
>I hope you don't mind me revising the title, @ultramiraculous :grinning:

No problem!

>Arrghh.  Please don't

Seconded

**Comment by abe33** [comment]
> Arrghh. Please don't.

Hahaha, I was sure it would raise objections :wink:.

More seriously, animations in UI/UX/DX design (not loving all these buzzwords, but people have been accustomed to them) are useful, when used properly, and I think this is a situation that clearly make sense for that kind of animations, rather than a blink (I should have thought twice before using that word) I think an opacity pulse should be more appropriate, let say that the pulse doesn't appear before the gap in versions reach at least 2 or 3 versions, so that people making their update regularly doesn't get annoyed by it, starting with a 4 version gap the pulse could last 2 seconds with opacity between 0.5 and 1, get to 10 it drop to 1s with opacity between 0.3 and 1, etc.

**Comment by mark-hahn** [comment]
I abhor any animation on the screen while I'm trying to code.  Also, this
seems like an attempt to force me to update. I should be able to put off
upgrades if I want, especially since there has been more than once that I
had to stay on old versions waiting for a change in core.

**Comment by simurai** [comment]
The turning to red, the further you're behind is a great idea. Maybe with a tooltip how many.

@kevinsawicki I'll un-assign myself for now. If somebody can add an attribute with how many versions Atom is behind, I can do the coloring. Something like `data-versions-behind="3"`.
