### ISSUE TITLE
Editor Removes Whitespace Unneccessarily

### ISSUE THREAD

**Issue by codeblooded** [atom/atom#4944]
I recognize that extra whitespace is rather unfortunate, but I have to question Atom's solution.  As of right now, the editor removes all unnecessary whitespace like spaces at the ends of lines and spaces on lines without any other content.  However, as I have contributed to several projects, I've gotten questions from the owners of the projects in my Pull requests as to why I unnecessarily adjusted the whitespace. I have to explain that it was my editor.  

Personally, I understand that code should be clean without these things, but owners can seem somewhat agitated with little whitespace changes alongside the fixes for the actual issue at hand.  I feel like there should at least be some way to disable this.

**Comment by izuzak** [comment]
> I feel like there should at least be some way to disable this.

Yep, there's a way to disable this. Go to the settings, then find the Whitespace package, and then disable it or tweak the options:

![screen shot 2015-01-09 at 13 11 40](https://cloud.githubusercontent.com/assets/38924/5679542/27e9b42e-9801-11e4-9786-0458d1df4418.png)

Also see https://github.com/atom/whitespace/issues/10.

**Comment by gregmac** [comment]
Generally speaking, code etiquette is to maintain the original style of the code. When using Atom to edit other people's code, because of the defaults in the whitespace plugin, you end up inadvertently doing changes that would be just as offensive in a PR as changing to tabs, or changing variables to `underscore_case`, or changing line endings to Windows format. 

I think this is actually so harmful that if the defaults aren't changed in atom/whitespace, the whitespace plugin should be removed as a core/default package in Atom.
