### ISSUE TITLE
Windows: Atom installer very aggressive, no confirmation whatsoever

### ISSUE THREAD

**Issue by leranus** [atom/atom#4987]
Yesterday I installed Atom for the first time with the new installer. While I expected to be presented with at least *some* options, the installer just started installing right away.

Secondly, in Explorer every context menu now has an item `Open with Atom`. I don't want that, Windows has 'Open with' functionality built in and it just clutters these menus (besides the fact that is shows up for *all* files and folders, while I for example don't expect to ever open an image with Atom). 

So I find the installer to behave very aggressive, I at least expect to be presented with a confirmation screen ("This will install Atom in C:\...\AppData, do you want to proceed?"). That it started installing right away really wasn't the behavior I expected. And it would be useful to be able to choose whether or not I want Atom as an item in the context menu.

**Comment by 50Wliu** [comment]
At least for right now, the philosophy behind Squirrel (which is the installer that Atom uses) is to be ["Wizard-Free™"](https://github.com/Squirrel/Squirrel.Windows#installation).

**Comment by leranus** [comment]
Aha, I was not sure if I had to post this in Squirrel.Windows or here. 

I think it isn't desirable behavior for an installer to just start installing right after clicking it. The installers of e.g. Opera or Firefox are what I see as a perfect example here: After launch, the provide the choice between just clicking Install to start the installation, or change some options (which are then shown on the same page).

**Comment by mark-hahn** [comment]
I posted an issue to squirrel bitching about a half-dozen things wrong with
their installer.  There answer for all of them was to make the install so
fast nothing mattered.  They really have their heads in the sand.

**Comment by paulcbetts** [comment]
> Yesterday I installed Atom for the first time with the new installer. While I expected to be presented with at least some options, the installer just started installing right away.

This is WontFix, sorry. If you double click on Setup.exe, you don't need a second "Do you want to do that thing, that you already said you wanted to do?" dialog

> Secondly, in Explorer every context menu now has an item Open with Atom

This might be nice to have as a preference in Atom, so that folks who don't want the menus can disable them. While Atom works far better if you open folders rather than files, I also can totally see not wanting Atom on _every_ folder's menu

**Comment by lee-dohm** [comment]
Thanks for the response @paulcbetts. I'm going to go ahead and close this since the main issue is the launch behavior of the Squirrel.Windows installer.

@leranus, could you open a new issue (on atom/atom) for the "Open with Atom" preference that @paulcbetts suggests? (The relevant code to add or remove the Open with Atom context menu item is in https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee.) I think this will help get that concern of yours addressed even if it isn't in the way you would prefer.

**Comment by leranus** [comment]
@lee-dohm Thanks, opened a new issue. Making it a prefence so it can be turned off is better anyway, despite that I indeed prefer an option on install time.

**Comment by leranus** [comment]
Further discussion of the "Open with Atom" entry is in #4695.
