### ISSUE TITLE
Updates fail

### ISSUE THREAD

**Issue by FELS-Zak** [atom/atom#4989]
Open preferences, select updates, then update all
You get a Unable to download error.
See attached.

![screen shot 2015-01-11 at 11 50 38](https://cloud.githubusercontent.com/assets/1165906/5695113/b1f8f926-9988-11e4-875b-dd05a3c7b534.png)

**Comment by Moter8** [comment]
`getaddrinfo ENOTFOUND` means that the client was not able to connect to the given address.

Can you try and open the shown URL in your browser?

**Comment by FELS-Zak** [comment]
Hi
It didn't work before but yeah this gets a file - https://www.atom.io/api/packages/autocomplete-plus/versions/1.1.0/tarball:
I've retried this - and it seems to work ok now. so I'd like to close this 

Thnx

**Comment by Moter8** [comment]
@lee-dohm As per https://github.com/atom/atom/issues/4985#issuecomment-69505677 should this be re-opened?

**Comment by lee-dohm** [comment]
@Moter8 No, these aren't the same kind of thing. #4985 was an *uncaught* error. Uncaught errors look like this in the UI:

![screen shot 2015-01-11 at 11 04 48 am](https://cloud.githubusercontent.com/assets/1038121/5696341/c0a4c998-9981-11e4-90f5-7d81becbc803.png)

and have a button to create an Issue that ends up looking like the initial post in #4985 (among others).

The problem that FELS-Zak mentions is a *caught* error and is displaying exactly as I suggested should be done in the comment on the other Issue.

**Comment by Moter8** [comment]
@lee-dohm thanks for the explanation :tada:

**Comment by ozra** [comment]
Please re-open! 

I've had this error since I started using atom basically. And the weird thing - I've reinstalled my computer completely, and it's still the same!! Infuriating!!

`"Request for package information failed: getaddrinfo ENOTFOUND"`

- It's the "check for updates" function I'm talking about
- Same thing happens at "install packages"
- _Sometimes_ (if retrying dozens of times) it works (but all these times I've also tried the 'netstat' trick, see below, so plenty red herrings here, sorry. desperation you know).
  - The few times I finally get a list of updates (after a looong time), the "update all" works flawlessly (!)
- The first few versions of Atom I ran worked fine (in the 'very beginnings' of atom)
- At some point it stopped working.
- Current version is 0.200.0
- I ran Ubuntu 14.04 32bit, but re-installed computer completely w. 14.04 64bit. Same thing.
- I'm currently using atom apt-pkg, I only installed from source in the beginning, dunno if it affects.
- At one point in the prev. OS install (32bit) I discovered by accident that if I ran netstat **simultaneously** (!) it worked - _might be purely coincidental!_
- I have **no other problems with net** on my computer.

I would love a solution for this, it's driving me nuts!
