### ISSUE TITLE
Atom starts with no tabs, "dev tools" open on startup, unable to open files

### ISSUE THREAD

**Issue by TLausmaa** [atom/atom#5014]
Version 0.170.0, 
Windows 8 Pro 64-bit

After the dev tools are closed you're unable to open any files. Atom lets me choose a file to open but nothing happens.

View on startup:
![atom_1](https://cloud.githubusercontent.com/assets/3340958/5709882/1ba84a52-9aa6-11e4-8298-5b7567a4d238.png)

View after I close the dev tools:
![atom_2](https://cloud.githubusercontent.com/assets/3340958/5709890/29ef5754-9aa6-11e4-838c-c02bb9338d38.png)

No tabs visible, cant open files. New file or ctrl + n does nothing.

Could not find this issue from the existing ones, I apologize if it exists.

**Comment by kevinsawicki** [comment]
Can you click the `Console` tab from the `>>` icon in the dev tools and see what error displays there?

**Comment by TLausmaa** [comment]
Here is the error it displays:
![atom3](https://cloud.githubusercontent.com/assets/3340958/5710010/53c5d0b6-9aa7-11e4-88a6-a9636c0b3f40.png)

**Comment by kevinsawicki** [comment]
Can you keep that tab open and click Reload from View menu and see if it displays a more comprehensive stack trace?

**Comment by kevinsawicki** [comment]
Closing this out since the stack trace wasn't provided and it won't be possible to track down without this.

This looks like a require or parsing error and lots of improvements to error handling for both of those have been added since Atom 0.170.0.

Please comment if you still see this happening on Atom 1.0.3+.
