### ISSUE TITLE
Move from LESS to Postcss

### ISSUE THREAD

**Issue by vanesyan** [atom/atom#5076]
In #5075 I proposed to componentizing CSS, So I also wanna propose to use  [POSTCSS](https://github.com/postcss/postcss) instead of LESS, cause it faster and allow us to use new CSS features, like CSS variables, nested media (by plugins) and desclude features that we really don't need.

Also, we can use autoprefixer to prefixing properties that really need it instead of hard typing prefixes like `display: -webkit-flex` and other.

**Comment by simurai** [comment]
Same reason as in #5075, it's already too close to the API freeze to be considered, at least for the 1.0 release.

Good point about the `-webkit` prefix for Flexbox. That could actually already be un-prefixed. I made a new issue for that: #5078. Otherwise autoprefixer isn't really needed, since Atom only runs in Chromium.

**Comment by vanesyan** [comment]
Autoprefixer is for future-proof CSS.)

**Comment by simurai** [comment]
> Autoprefixer is for future-proof CSS.)

Yes, that's right. I'm just not sure if it warrants having another dependency and the extra compile step. Next to Flexbox, there isn't that many other prefixes needed. Maybe for `keyframes` animation or `user-select`. And it looks like Chrome is moving away from prefixing and using flags instead.

**Comment by danielbayley** [comment]
I just thought of this while [comment]ing on #12903…

I think this would be **awesome** for `2.0`! This would let package authors use _any_ pre/post process they please given that it can already parse [Less], [Sass], and can even be used with [Stylus] (which would have been the more natural choice to pair with CoffeeScript IMO).

so Atom itself wouldn't even _need_ to migrate all the internals for it to work. You could just look at the `main:`/`index.*` file and pass the correct `parser:` flag for PostCSS to compile everything. I think this could be awesome for package authors rather than [kind of] forcing Less on them…

[less]: https://npmjs.com/package/postcss-less
[sass]: https://npmjs.com/package/postcss-scss
[stylus]: https://npmjs.com/package/poststylus

[comment]: https://github.com/atom/atom/pull/12903#issuecomment-281522676
