### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenizeLine' of undefined

### ISSUE THREAD

**Issue by MetaMemoryT** [atom/atom#5081]
TypeError: Cannot read property 'tokenizeLine' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedTokenizedLineForRow (c:\Users\Sean\s\atom-windows\Atom\resources\app\src\tokenized-buffer.js:428:27)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (c:\Users\Sean\s\atom-windows\Atom\resources\app\src\tokenized-buffer.js:261:43)
  at c:\Users\Sean\s\atom-windows\Atom\resources\app\src\tokenized-buffer.js:243:26
  at c:\Users\Sean\s\atom-windows\Atom\resources\app\node_modules\roaster\node_modules\underscore\underscore.js:666:47

I think this is error is caused by https://github.com/benjohnson/atom-django-templates/blob/master/grammars/html%20(django).cson

but I think atom error messages should be better at helping me pin down the offending expression

**Comment by izuzak** [comment]
Which version of Atom are you using? Can you reproduce the problem in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by MetaMemoryT** [comment]
0.165.0

I "broke on exceptions"

the this.grammar.tokenizeLine property IS defined

the line variable is:
"{% load url from future %}"

I now think the package has something to do with language-html

**Comment by batjko** [comment]
It would be good to know which steps to follow to reproduce this error.
What exactly do you do when this occurs?

**Comment by harrislapiroff** [comment]
I also just got this one upon waking my computer for sleep.

**Comment by izuzak** [comment]
@nathansobo Any thoughts on this old issue? I'm guessing things might have changed since January, but still maybe you see something that we can use to decide if this can be closed or needs to be fixed.

The exception message is "Cannot read property 'tokenizeLine' of undefined" and as far as I can tell, the only place left in that file where `tokenizeLine` is called is here:

https://github.com/atom/atom/blob/ddb519ce7be8d8fd90788c9880a119fa3a9e0cbd/src/tokenized-buffer.coffee#L364

which would mean that `@grammar` is undefined. Should that be possible (or was possible and no longer is)? Is that something we can guard against?

**Comment by nathansobo** [comment]
Considering our planned major changes to the `DisplayBuffer` and `TokenizedBuffer`, I'm reluctant to investigate this too much further at this time.

**Comment by 50Wliu** [comment]
Old issue with no reproduction and a drastically changed codebase.  Closing.
