### ISSUE TITLE
Ctrl-0 doesn't reset the font-size zoom back to 100%

### ISSUE THREAD

**Issue by greatwolf** [atom/atom#5131]
According to Key Binding Resolver (actived w/ <kbd>ctrl + .</kbd>), it tells me that <kbd>ctrl + 0</kbd> resolves to `tree-view:toggle-focus` first and below that it resolves to `window:reset-font-size` which is really what I want.

My first attempt on fixing this, I tried to look for "Atom/resources/app/node_modules/tree-view/keymaps/tree-view.json" which is the file listed by keybind resolver but when I try to actually find this file in my atom folder that file doesn't actually exist!

Any idea how to reset the font zoom back to the default 100%? Why does the resolver point to a non-existing file for the tree toggle focus setting? Where does atom actually get this setting from if not from that non-existing file?

**Comment by greatwolf** [comment]
Okay, I found it. After doing a `findstr`/`grep` for <kbd>ctrl-0</kbd>, I located "G:\Atom\resources\app\package.json" which is where the key for the `tree-view:toggle-focus` setting really exist. I prompted deleted all occurrences of that key and saved the `package.json` and a quick restart later of atom with the modified settings gives the behavior I want.

Incidentally, I had to use a different editor like notepad++ to modify the package.json file since atom slowed to a crawl.

**Comment by lee-dohm** [comment]
The proper place to customize key bindings is in your `~/.atom/keymap.cson`. See the [Customizing Atom document](https://atom.io/docs/latest/customizing-atom#customizing-key-bindings) for a little more information or the [Keymaps advanced document](https://atom.io/docs/latest/advanced/keymaps) for a detailed understanding of how key bindings are created and resolved.

Making changes inside your `Atom/resources` directory is not advised because changes there can be (and often are) overwritten when Atom is next updated.

Adding this to my `keymap.cson` made `window:reset-font-size` the active key binding:

```coffee
'atom-workspace':
  'ctrl-0': 'window:reset-font-size'
```

Let us know if that does not work for you.

**Comment by QUIPQUOPRO** [comment]
If you prefer to use the zero on the number pad, then add this code:

```cson
'atom-workspace':
  'ctrl-numpad0': 'window:reset-font-size'
```
