### ISSUE TITLE
Package latest packages in Atom

### ISSUE THREAD

**Issue by steelbrain** [atom/atom#5155]
__A LOT__ of this Repository's commits are of package version upgrade.
I wonder why aren't you guys `latest` instead of a specific version (npm supports `latest` as version, does apm too?). That would make the commit history a lot more readable.

**Comment by mnquintana** [comment]
While I can't speak for the maintainers of course, my understanding is that they don't do that because they want to be able to curate dependency updates and only update a package in core when they feel it's ready for release.

**Comment by steelbrain** [comment]
@mnquintana , If that's the case. Then the atom teams owns the APM project, maybe they could support `latestStable` as a version that only tracks the latest major or minor builds instead of patches.

**Comment by kevinsawicki** [comment]
apm does not currently support the `latest` keyword as the dependency version.

**Comment by steelbrain** [comment]
@kevinsawicki Lets add it then :wink: Adding support for `latest` keyword would be waaay better than manually updating each package's version.

**Comment by mnquintana** [comment]
So, the reasoning behind all the package version bump commits (and the pinned package versions in `package.json`) is so that each commit (and relatedly, each release) can be a consistent, version-controlled snapshot of all of the exact versions of each package used at any given time. This makes it much easier for debugging, for instance, in case a specific version introduced a bug. How would you revert a bug introduced by a version if the version field was `latest`? If they used version ranges or `latest`, there wouldn't be any way to lock down a core package version in a commit. The only alternative would be some workflow involving `npm shrinkwrap`, but the file that generates isn't meant to be read by humans, to put it lightly. :laughing:
