### ISSUE TITLE
Lines jump to the left while editing

### ISSUE THREAD

**Issue by demisx** [atom/atom#5180]
(Atom 0.174.0 on Mac OSX Yosemite)

Editing objects in this block of code makes each line jump to the left (confirmed in safe mode). Indentation gets messed up:

```js
'use strict';

exports.seed = function(knex, Promise) {
  return knex('sections_i18n').insert([
    { section_id: 1, locale_id: 1, name: 'Section 1' },
    { section_id: 2, locale_id: 1, name: 'Section 2' },
    { section_id: 3, locale_id: 1, name: 'Section 3' },
    { section_id: 4, locale_id: 1, name: 'Section 4' },
    { section_id: 5, locale_id: 1, name: 'Section 5' },
    { section_id: 6, locale_id: 1, name: 'Services 6' }
  ]);
};
```

**Comment by maxbrunsfeld** [comment]
I've noticed this too. It's because of the [`autoDecreaseIndent`](https://github.com/atom/atom/blob/master/src/selection.coffee#L386) code path, intended to handle curly braces etc at the ends of indented blocks. Maybe we need to tweak the [`decreaseIndentPattern`](https://github.com/atom/language-javascript/blob/master/settings/language-javascript.cson#L15) for javascript?
