### ISSUE TITLE
pressing tab inconsistent

### ISSUE THREAD

**Issue by Cipa** [atom/atom#5192]
I have 2 js files
In one a tab key press generates a tab in the other one it generates 4 spaces

Any ideas what could be wrong?
The key binding resolver generates the same lines

**Comment by 50Wliu** [comment]
One of your files probably is being identified as a soft tabs file while the other is being detected as a hard tabs file.

**Comment by Cipa** [comment]
I edited the file in other editor(replaced all the .... with tab), updated to 175 and now everything is ok.
Seems that if I want to use tabs in files that use soft tas I need to first convert all the soft tabs to hard tabs. Not sure if this is a bug or future, please close if needed

**Comment by Cipa** [comment]
Hi,
I am not sure how to debug this
While I was coding the hard tab functionality switched to soft tab for apparently no reason  
Now when I press tab or hit return to go to next row I get soft tabs even if the whole file is using regular tabs

I'm on 0.175.0

Let me know if there is some log you want me to send

![screen shot 2015-01-26 at 12 54 40 pm](https://cloud.githubusercontent.com/assets/293377/5905007/d210fa32-a55a-11e4-8fba-7d4067e020b1.png)

**Comment by Cipa** [comment]
After restart and after I reopened the file the problem is still there. Copy pasting the same code transforms tabs into soft tabs

![screen shot 2015-01-26 at 1 01 56 pm](https://cloud.githubusercontent.com/assets/293377/5905098/892b2c38-a55b-11e4-968d-b1228a091e1c.png)

Here are my settings
![screen shot 2015-01-26 at 1 03 36 pm](https://cloud.githubusercontent.com/assets/293377/5905119/c590acc0-a55b-11e4-86dc-15875abe7285.png)

**Comment by Cipa** [comment]
What seem to have fixed the problem
restarted in safe mode
edited the first line of the js file(it had a 1space tab ????? I should have saved the code)
closed the js file with the problem
quit atom
restart atom in normal mode
open js file

Note: php files were working correctly while this was happening

Please let me know if you need some logs if this still happens and how should I get to those logs
Thx

**Comment by benogle** [comment]
It does auto detection. So if you open a file with some soft tabs at the top of the file, but the rest are hard tabs, it will still use soft tabs, despite the setting and despite the existence of hard tabs in the file. We plan to fix this with https://github.com/atom/atom/issues/3719.

For now, just make sure your entire file has hard tabs, and it should pick hard tabs.

**Comment by benogle** [comment]
If this is still an issue, please reopen

**Comment by jeffmcneill** [comment]
Most reports of issues seem to be closed without resolving the underlying problem. There is only one open I could find (on cursory clicking):

## Closed

- #5497 
- #3719
- #5192

## Open 

- #4054

The big issue as reported is the inaccurate "guessing" combined with the inability for an editor-wide setting (and not per-file setting). It may be that several preferences may be required instead of having one monolithic setting which is clearly causing unhappiness:

- Default for all files (y/n)
- Default for certain files (by file extension)
- Setting on per file basis

The idea would be to be able to re-order these in terms of priority, based on the needs of the user.
