### ISSUE TITLE
Can not open atom from command line

### ISSUE THREAD

**Issue by bhoskins** [atom/atom#5222]
When I try to open atom from the command line using: atom .
I get this error
FSPathMakeRef(/Applications/Atom.app) failed with error -43.

I reinstalled the shell commands, closed and opened Atom, closed and opened the command prompt and the error still persists.

**Comment by mnquintana** [comment]
Can you post:
- your Atom version number
- your installed packages
?

Do you still get this error if you try opening it with `atom --safe .`?

**Comment by bhoskins** [comment]
Atom version: 0.175.0(0.175.0)

packages:
emmet
linter
linter-htmlhint
linter-scss-lint
tag
And Core Packages

does not open in command with: atom --safe .

Hope ths helps,
B. Hoskins

**Comment by postcasio** [comment]
How did you install Atom? Was it using Homebrew? Could be related to https://github.com/atom/atom/issues/3224

**Comment by GingerBear** [comment]
I get the same issue after I unzip the official `atom-mac.zip` file and move to /Applications, where there is actually already a old atom existing. The new app is renamed to `Atom 2`. I didn't aware that and thought it maybe the some version name. Then I remove the original `Atom`. After that I get the same error in terminal.

After I remove the `Atom 2`, move the unzip file to /Applications and run `Install Shell Command` again, everything works fine. 

I guess the `Install Shell Command` is installing the shell script that based on assumption that atom is installed at `/Applications/Atom` ([atom/atom.sh](https://github.com/atom/atom/blob/cbc8ad146726d38ff50140d3a429ecc3c8e26d3a/atom.sh#L48)). Otherwise it will fail.

**Comment by bhoskins** [comment]
Thanks, I think you are right. I uninstalled all atoms and reinstalled it
and its working now. I had forgotten that I had installed it and installed
it twice. Thanks for the info.
Peace,
Beth H.

**Comment by piyushbajaj0704** [comment]
On Windows 7 and above, add the %LOCALAPPDATA%\Atom\bin to your user PATH variable. You test it out from the command line by running the following command:
SET PATH=%PATH%;%LOCALAPPDATA%\Atom\bin
Then you should be able to run Atom directly from the command line.

**Comment by wd990** [comment]
@piyushbajaj0704  works great. Thanks mate
