### ISSUE TITLE
Editor styles break on theme update

### ISSUE THREAD

**Issue by lucasbrendel** [atom/atom#5258]
When performing a theme update in 0.175 of Atom for Windows, the tab interface shrunk down and wasn't clickable during the update.

![atomimage](https://cloud.githubusercontent.com/assets/1765755/5899816/cc981ed4-a526-11e4-9845-32490fee42cd.PNG)

Then after the update the tabs returned to normal.

![atomimage2](https://cloud.githubusercontent.com/assets/1765755/5899820/e34266a8-a526-11e4-959c-8d84b2148ad0.PNG)

It doesn't happen when on the install page of Settings. I also don't currently have another package to update at the moment to test if this is specifically seen with the theme i am using or if it is an Atom issue.

Is this normal behavior during updates though? I Also noticed that the package buttons to update, uninstall, or settings also expand during the update.

**Comment by benogle** [comment]
Were you currently using isotope ui while updating it?

I have seen this while updating UI themes I _was not_ currently using. So, using one dark, and updating Unity UI, and I see some styling from Unity UI get injected.

**Comment by lucasbrendel** [comment]
Yes I was using Isotope UI.

**Comment by simurai** [comment]
I could reproduce this with two other themes:

![update-theme](https://cloud.githubusercontent.com/assets/378023/5913698/e6483a20-a62b-11e4-9422-919809222b9e.gif)

![update-theme-jonikorpi](https://cloud.githubusercontent.com/assets/378023/5913700/ebd5faae-a62b-11e4-92b1-58c9c97d0230.gif)

It's not just the tab size, also the whole tree-view is "unstyled" during the update. And interestingly I can also reproduce it with a Syntax theme:

![update-theme-dusk](https://cloud.githubusercontent.com/assets/378023/5913823/5657e800-a62d-11e4-902e-2ed954f83eaf.gif)

 But only when I **was currently** also using **that** theme.

I don't know enough how the internals work, but could it be that during an update, it doesn't keep the styles "cached" and you would see it styled like there is no theme installed? Or whatever the styles are set in Atom core. Because if I remove all tab styles in a theme, they look exactly the same (shrunk down). The strange thing is, why doesn't the un-styling happen to the settings view too? Maybe because they are part of a different cache since originally they weren't meant to be themeable?
