### ISSUE TITLE
Add badge UI component

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#5271]
It seems like it would be really useful to have some kind of badge component ([like Bootstrap's](http://getbootstrap.com/components/#badges)). The most immediate use for this I can think of would be any of the numbers in the headings in Settings > Packages (or Themes). They're currently in parentheses, but that's really just a text approximation of a badge anyway. :smile:

Something like:
![screenshot 2015-01-27 09 11 47](https://cloud.githubusercontent.com/assets/823545/5919727/8caae02a-a604-11e4-89b5-ca2f44a3cfb5.png)

Instead of:
![screenshot 2015-01-27 09 12 54](https://cloud.githubusercontent.com/assets/823545/5919753/c0167230-a604-11e4-8c5a-ca0b4be88ff2.png)

(I'm opening this here and not in [settings-view](https://github.com/atom/settings-view) because this seems like a useful UI component to add to core, rather than a styling just useful for settings-view.)

**Comment by simurai** [comment]
There is the `highlight` class that could be used. Would look like this (also depends on the theme):

![screen shot 2015-01-30 at 10 15 30 am](https://cloud.githubusercontent.com/assets/378023/5969599/32682f66-a869-11e4-9fc0-137619e81f0c.png)

Maybe ok, but `highlight` is typically used inside text. A **round** badge component would fit better in that context.

**Comment by simurai** [comment]
oh, wait. Atom already imports Bootstrap's badges: https://github.com/atom/atom/blob/master/static/bootstrap.less#L22 So we probably can just use them.

**Comment by mnquintana** [comment]
> Maybe ok, but `highlight` is typically used inside text. A round badge component would fit better in that context.

Yeah, that wouldn't be great for semantics either.

> oh, wait. Atom already imports Bootstrap's badges: https://github.com/atom/atom/blob/master/static/bootstrap.less#L22 So we probably can just use them.

Well how about that! Just to make sure, @kevinsawicki @benogle et al., are Bootstrap components still okay to use, or are they deprecated?

**Comment by benogle** [comment]
I would like to remove bootstrap at some point. The settings view relies on it, but other than that, we dont get much from it.

**Comment by thedaniel** [comment]
Sounds like if we want to keep using bootstrap in settings-view we better vendor it immediately to make it easier to deprecate it from core. ... but do we want to keep using it? I gather from interacting with @simurai on this repo that he's eyeing a fairly deep overhaul of the UI eventually (fixed width side panel etc) but that realistically might not happen for months if at all.

**Comment by simurai** [comment]
Yeah.. not a high priority, but I still can't forget about the "fixed width side panel etc". And in that case, also stir away again from having the settings themed by default. It **IS** cool, but at the same time it also has some flaws. Mainly:

- For every change we make in the settings, we have to think how it will look in all themes and maybe only do it in a way that is okayish for most.
- It's not always that clear what variables to use. For example this badge component uses `@background-color-selected` and `@text-color-selected`. Which sounds a bit odd, but seemed the most fitting visually.
- It adds more extra work for theme creators. Well, most themes are fine. But not if they really wanna fine tune it.

> Sounds like if we want to keep using bootstrap in settings-view we better vendor it immediately to make it easier to deprecate it from core.

What does "vendor it" mean? Move it under `atom/atom/vendor/`? And in that case community packages shouldn't use it directly?

We could also make it only a dependency of the settings-view, since it's mostly used there. The button groups in find-and-replace and probably a few other places would break, but I think only when disabling the settings since all styles are global. Then we could start move bootstrap components to core, if it's something commonly used, like for the button groups.

**Comment by thedaniel** [comment]
> What does "vendor it" mean?

Sorry, that's a bit of rubyist terminology, I think. It means checking external dependencies into your source. In other words, if we want to keep using bootstrap we should include what we need from it directly in settings-view rather than relying on its presence in atom core.

**Comment by lee-dohm** [comment]
> Sorry, that's a bit of rubyist terminology, I think.

Yeah, that's the only place I've encountered the term.

**Comment by mnquintana** [comment]
Implemented in #5316

@thedaniel Do you think it's worth opening a separate issue for vendoring Bootstrap?

**Comment by thedaniel** [comment]
sure - if we include it explicitly here it will make it easier to pull it
out of core eventually.
