### ISSUE TITLE
Find and Replace All in a project doesn't add the file changed icon in the sidebar until you view that file

### ISSUE THREAD

**Issue by tommyp** [atom/atom#5301]
If you use Find and Replace All to make changes in files in the project which aren't currently open, the sidebar won't show that the file has changed until you click to open and view the file.

**What should happen** - The sidebar should show that the file has changed, or open all those files in the editor with the changes. Sublime does this and leaves them unsaved, forcing the User to Save All.

**Comment by benogle** [comment]
So you mean the file doesnt pickup the git modified status (change color) immediately? Or what sidebar notifications are you referring to?

**Comment by tommyp** [comment]
Sorry, yes, the git change status doesn't update until you open the file.

**Comment by as-cii** [comment]
*Disclaimer: it's the first time I hack on Atom, therefore please excuse me if any of my assumptions (or code snippets) is totally wrong (or too cumbersome).* :pray: :pray: :pray: 

Now onto the interesting things!

I have read through the three main repositories related to this issue:

* `atom/atom`
* `atom/tree-view`
* `atom-find-and-replace`

The last two basically operate through **Atom** core and are based on `Workspace` and `GitRepository`. **Find and Replace** uses `Workspace#replace` function to actually change files. On the other hand **Tree View** listens to `GitRepository` `change-status` events to reflect file changes into the sidebar. Nothing triggers a `change-status` event whenever files changes, thus causing this issue.

That said, I thought I could come up with a simple fix for this issue; here's the a draft (I am sorry if I do not open a Pull Request for this but I thought these changes were relatively short and for now could be kept as a snippet here for us to discuss a better improvement; keep reading :eyeglasses: ). You can `pbpaste | git apply` after copying it:

```diff
diff --git a/spec/workspace-spec.coffee b/spec/workspace-spec.coffee
index b9642e1..1a484f9 100644
--- a/spec/workspace-spec.coffee
+++ b/spec/workspace-spec.coffee
@@ -869,6 +869,17 @@ describe "Workspace", ->
       fs.writeFileSync(filePath, sampleContent)
       fs.writeFileSync(commentFilePath, sampleCommentContent)
 
+    it "refreshes repository on replacing", ->
+      repository = atom.project.getRepositories()[0]
+      spyOn(repository, "refreshStatus")
+
+      waitsForPromise ->
+        atom.workspace.replace /items/gi, 'items', [filePath]
+
+      runs ->
+        expect(repository.refreshStatus).toHaveBeenCalled()
+
+
     describe "when a file doesn't exist", ->
       it "calls back with an error", ->
         errors = []
diff --git a/src/workspace.coffee b/src/workspace.coffee
index fc2a12c..70b4872 100644
--- a/src/workspace.coffee
+++ b/src/workspace.coffee
@@ -953,6 +953,9 @@ class Workspace extends Model
       replacements = buffer.replace(regex, replacementText, iterator)
       iterator({filePath: buffer.getPath(), replacements}) if replacements
 
+    for repo in atom.project.getRepositories()
+      repository.refreshStatus()
+
     inProcessFinished = true
     checkFinished()
```

However this solution has a couple of drawbacks:

1. Repositories get refreshed even when no file was changed;
2. Tests may be inaccurate: I am particularly sorry for this one. Since other tests in that file touch the filesystem, it may be better to use a real Git repo instead of using a mock. I don't know what policy you have for mocks in your tests, but it could be better to use a real repo here;
3. It solves this problem, but it won't solve any related problem in the future;

The first two issues are relatively straightforward and could be easily fixed if the change is ok. But let me explain this last one (it may be based on wrong assumptions, so please bear with me if I am wrong). The fact that Atom doesn't notice that files have been changed lets me think that it refreshes only on Atom related events:

```coffee
# src/git-repository.coffee
@subscriptions.add @project.eachBuffer (buffer) => @subscribeToBuffer(buffer)
```

```coffee
# src/git-repository.coffee
if refreshOnWindowFocus
      onWindowFocus = =>
        @refreshIndex()
        @refreshStatus()
```

Instead of handling *file-changed* events through Atom, `GitRepository` could rely on a file system watcher which would notify it for any change in files/directories (e.g. via calling `refreshStatus` whenever something interesting happens).

I am not a Node.js pundit, but I think there's [already something out there](http://nodejs.org/api/fs.html#fs_class_fs_fswatcher) and I suspect that Atom uses something like this already (for config files?).

Not only this would simplify the code (e.g. no subscription to buffers, or to window focus), but it would enhance the UX (e.g. avoiding issues like this altogether). What drawbacks could this have? Did you evaluate this option already?

Sorry if this comment was a bit too long, but I wanted to dump what I had found during this quick hack.

Thank you! :dancer:

**Comment by benogle** [comment]
Can you make a PR for your proposed changes? They will be easier to talk about. It seems reasonable. But maybe there is a better way to watch the paths.
