### ISSUE TITLE
.gitignore patterns with trailing spaces not handled as expected

### ISSUE THREAD

**Issue by rumpelsepp** [atom/atom#5317]
The gitignore integration seems to have an issue with `*.fls` files in latex projects. I have attached a screenshot. Git on the commandline actually ignores these files properly.
![screenshot 2015-01-30 12 43 44](https://cloud.githubusercontent.com/assets/1961699/5975213/fe3fd274-a87d-11e4-9b92-9fd0436bc8c7.png)

**Comment by izuzak** [comment]
@rumpelsepp I'm having trouble reproducing that:

![screen shot 2015-01-30 at 14 09 09](https://cloud.githubusercontent.com/assets/38924/5976040/9dce80dc-a889-11e4-9a81-f7060b6a6379.png)

Can you please provide more [debugging information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)? Also, if you can reliably reproduce the issue -- can you share the steps which reproduce the issue for you?

**Comment by rumpelsepp** [comment]
Maybe a caching issue or sth. like that? I played around a bit and also edited the `.gitignore`. Now the problem is gone.

```
$ atom --version
0.176.0

$ apm links           
/home/stefan/.atom/dev/packages (0)
└── (no links)
/home/stefan/.atom/packages (0)
└── (no links
```

**Comment by izuzak** [comment]
Not really sure. If you manage to reproduce this behavior -- please let us know. Going to close this for now.

**Comment by rumpelsepp** [comment]
> If you manage to reproduce this behavior -- please let us know.

Yeah. I will ping you if it appears again and I know why, thx!

**Comment by rumpelsepp** [comment]
@izuzak I can reproduce it on my machine. Try adding a trailing whitespace in your `.gitignore`. I found it by accident in my git history.

![bildschirmfoto vom 2015-02-02 08 19 15](https://cloud.githubusercontent.com/assets/1961699/5996953/36865198-aab4-11e4-907b-ffe58a3a8016.png)

**Comment by izuzak** [comment]
Thanks for digging into this, @rumpelsepp -- I was able to reproduce that behavior. 

Seems like a problem in either [git-utils](https://github.com/atom/git-utils) or [libgit2](https://github.com/libgit2/libgit2) (which git-utils use under the hood) -- perhaps there's a libgit2 flag git-utils can set so that such spaces are ignored in .gitignore files.

Without the trailing space in the .gitignore, `repo.isPathIgnored` returns `true` for a path which should be ignored, but when the trailing space is added -- `repo.isPathIgnored` returns `false`. Command line Git ignores the file in both cases, however. 

Gonna reopen this and cc @kevinsawicki. 

Thanks again!
