### ISSUE TITLE
Rename 'linux' label to 'GNU'

### ISSUE THREAD

**Issue by muchweb** [atom/atom#5348]
Proposal: To appropriately use word 'linux' and to rename `linux` label to `GNU`

---

What you're referring to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU `corelibs`, shell utilities and vital system components comprising a full OS as defined by POSIX.

Through a peculiar turn of events, the version of GNU which is widely used today is often called 'Linux', and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.

Thus, making it incorrect to list 'linux' tag among 'mac' and 'windows'.

1. Bugs, that were currently labelled 'linux' do not apply directly to the Linux kernel. But to the whole stack of GNU operating system: including it's core utilities, X window system. This can lead to confusion.

2. Atom can be run on many kernels, including [FreeBSD's](https://github.com/atom/atom/blob/master/docs/build-instructions/freebsd.md). It would be wrong to file BSD-related bugs under the tag of 'linux'. On other hand, 'GNU' tag would cover such variations, as [Debian GNU/kFreeBSD](https://www.debian.org/ports/kfreebsd-gnu/).

3. GNU operating system can be run many other kernels, such as GNU HURD or Darwin’s XNU kernel, which users too might run Atom editor. 'GNU' tag will cover this.

4. To call the whole system 'Linux' is both unfair and confusing, because it does not give the GNU Project credit and makes it hard to distinguish the whole system from the kernel alone.

Read more about 'GNU' and 'linux' confusion:

- [Linux and the GNU System](https://www.gnu.org/gnu/linux-and-gnu.html)
- [Why GNU/Linux?](https://www.gnu.org/gnu/why-gnu-linux.html)
- [GNU Users Who Have Never Heard of GNU](http://www.gnu.org/gnu/gnu-users-never-heard-of-gnu.html)

**Comment by mark-hahn** [comment]
>  it is basically the GNU system, developed by the GNU Project.

So Linus Torvaldis did not develop Linux?  I think he might disagree.
Knowing his temperament I think you might hear a few colorful words.

**Comment by paulcbetts** [comment]
> Bugs, that were currently labelled 'linux' do not apply directly to the Linux kernel. But to the whole stack of GNU operating system: including it's core utilities, X window system. This can lead to confusion.

At this point in 2015, it is almost guaranteed that the label 'gnu' would confuse **much more** people than the label 'linux'. This proposal is Technically Right, but wildly impractical. Whereas, approximately zero FreeBSD users will see 'linux' and think this tag isn't related to what they run. This simply doesn't reflect reality, no matter how much RMS wishes it. 

The term 'Linux' is practical shorthand that is well-understood, even if it is technically incorrect. :-1: to changing this.

**Comment by lee-dohm** [comment]
I have to agree with @paulcbetts on this one.

**Comment by muchweb** [comment]
>So Linus Torvaldis did not develop Linux?  I think he might disagree.

@mark-hahn, Linus did develop the Linux kernel, that has filled the last missing part, forming the free GNU operating system (that was developed at that time). Because of this, many people got confused by mistakenly calling the whole operating system (including GNU C Compiler, text editor, corelibs, etc.), 'Linux'.

**Comment by AnthonyFoley** [comment]
In all cases, we should use words that make our meaning clear. In human language, words to not have inherent meaning. Words mean what the general language-speaking population thinks that they mean, and if other people understand what you mean when you use a word, then you are using it correctly. Furthermore, the meaning/correctness of a word can be context-dependent. The fact that the meaning of a word is not clear in certain contexts does not mean that it is incorrect to use that word in other contexts.

If I say to someone knowledgeable about computers, "I use Linux", they will know that I mean that I use some variant of GNU/Linux, and I have therefore used that word correctly. If I use Windows on all of my computers except for my Android phone, it would be incorrect to tell people that I use Linux, because the the thing that that means to them is not the same as the thing that I am trying to say, even though technically I do use the Linux kernel. In that case, it would be necessary to clarify. On the other hand, if I use the word "Linux" in a conversation about kernels or in a conversation with a kernel developer, I would not need to clarify, and if I wanted to mention the whole operating system in such a conversation, I would probably use the distribution name, i.e. Gentoo. GNU/Linux is a useful term in some contexts, but it not usually necessary to use it when talking about Linux.

Linux is one of an endless list of words that have multiple meanings. This is NOT a problem. It is a natural part of how human language works. All that it means is that you have to consider the context when you use the word.

**Comment by benogle** [comment]
> The term 'Linux' is practical shorthand that is well-understood ... :-1: to changing this.

I totally agree with this.

**Comment by kevinsawicki** [comment]
Yeah, I'm going to close this issue out, I think renaming it will add confusion, not remove it.
