### ISSUE TITLE
"exclude vcs ignored paths" does not work.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#5423]
In that, when I uncheck it, the files are still ignored by the sidebar and do not show up, they are still in-fact ignored, this is unexpected behavior for the sidebar (and even the alternate open dialog - fuzzy open.)

**Comment by izuzak** [comment]
@envygeeks The sidebar (= the tree view) has config options of its own:

![screen shot 2015-02-09 at 13 43 49](https://cloud.githubusercontent.com/assets/38924/6106457/cc83f210-b061-11e4-97ae-dd637c3549ff.png)

Can you give those options a try and let us know if it doesn't help? Also, please provide a bit more [debugging information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) to help us investigate (specific examples and screenshots are always helpful).

**Comment by envygeeks** [comment]
I feel slightly silly for not even trying to search there! On a side note perhaps can a note be added to that option to hint at that and make it plainly obvious for the too lazy to search?

**Comment by izuzak** [comment]
> On a side note perhaps can a note be added to that option to hint at that and make it plainly obvious for the too lazy to search?

Adding a note to that specific option sounds sub-optimal since other users might be confused in the same way about other options as well (which wouldn't have that note). Perhaps adding a note at the top of "Editor Settings" section which tells the user that some settings are also per-language would be more helpful? I'd be :+1: if you'd like to create an issue over in https://github.com/atom/settings-view to discuss this problem.
