### ISSUE TITLE
A lot of key-bindings are NOT shown in the menu

### ISSUE THREAD

**Issue by DLade** [atom/atom#5462]
I miss a lot of key-bindings shown in the menu - maybe there is a way to read the original keymappings and show them in menue.

**Comment by izuzak** [comment]
This is similar to https://github.com/atom/atom/issues/5343, but that issue is just about the View > Panes keybindings. There are many more missing and not just multi-stroke keybindings as far as I can tell (https://github.com/atom/atom/issues/5343#issuecomment-72579184). For example, the keybinding for Select All is missing (`cmd-a`):

![screen shot 2015-02-09 at 12 29 07](https://cloud.githubusercontent.com/assets/38924/6105431/5b2fec18-b057-11e4-98c3-d9b2db2d3e07.png)

I'm not sure but guessing this is related to the `MenuManager.includeSelector` method which determines whether a keybinding will be included for a command or not:

https://github.com/atom/atom/blob/6a86a00c663b4333258cbbf4f4357580d926e4ab/src/menu-manager.coffee#L102

For example, `  'cmd-a': 'core:select-all'` is defined under  `'atom-text-editor'` and it's keybinding is not shown in the menu (see screenshot above):

https://github.com/atom/atom/blob/c33b154e7378774823bac190dc44f94781880158/keymaps/darwin.cson#L132

but `'cmd-c': 'core:copy'` is listed under `'body'` in the keymaps file and it's keybinding is shown in the menu (see screenshot above):

https://github.com/atom/atom/blob/c33b154e7378774823bac190dc44f94781880158/keymaps/darwin.cson#L51

cc @kevinsawicki @nathansobo for :eyes:

**Comment by izuzak** [comment]
:zap: @kevinsawicki
