### ISSUE TITLE
UTF-16LE file is opened with UTF-8 and only 7-bit ASCII characters are correctly decoded

### ISSUE THREAD

**Issue by espresso3389** [atom/atom#5516]
When I open files of UTF-16LE, ATOM magically decodes only 7-bit ASCII characters but no other characters are decoded. I think there are many \0 characters on the file so that ATOM can detect UTF-16 in better way.
Furthermore, even with UTF-16LE files with BOM could not be loaded correctly :(

**Comment by espresso3389** [comment]
Wow, I found that even \0 characters are decoded correctly and stay there but they are anyway invisible:( I hope some visible character should be shown for them...

**Comment by lee-dohm** [comment]
Support for autodetect with BOM is tracked by atom/encoding-selector#18. Autodetect in general is tracked in #4160. Please subscribe to those issues for updates. I'm going to close this as duplicate.

Until those are fixed though, there is an encoding selector in recent versions of Atom:

![encoding-selector](https://cloud.githubusercontent.com/assets/1038121/6172632/e53ff3e4-b296-11e4-9d77-e3106ff70e9a.png)

You can always manually select the encoding to use by clicking on the selector.

And the null bytes that you mention are one half of the two byte sequence for most characters in UTF-16. If the encoding is properly set, those bytes should not be shown at all since they aren't characters in their own right.
