### ISSUE TITLE
Export documented API through require('atom')

### ISSUE THREAD

**Issue by jessegrosjean** [atom/atom#5543]
I think the [documented Atom API](https://atom.io/docs/api/v0.179.0/Atom) classes should be exported through require('atom'). At least for all classes where it would make sense for a package developer to instantiate. e.g. Workspace shouldn't be exported since no one needs to instantiate that, but Disposable, and CompositeDisposable should be exported since it makes sense for a package developer to instantiate them.

That's pretty much how things already work... Except for `File` and `Directory` which are documented, but not exported. This causes two problems.

1. First reading through the API, I see those classes and want to use them, but when I try `{File} = require 'atom'` it doesn't work. Which is very confusing since it does work for the rest of the API.

2. The workaround is to including the underlying `pathwatcher` package into my own package. That's fine, but makes my package bigger, slower to load, and now I've got an extra dependency to manage. It seems unnecessary since `File` and `Directory` are already a documented part of Atom.

Here's a pull request that exports those classes #5499

**Comment by lee-dohm** [comment]
I disagree that all classes documented in the API *must* be exported. There are valid reasons that an API would want to be the sole source of instances of a class (a factory class or factory method for example), *not* have those classes instantiated by the user of the API, but still have those classes documented for the people that wanted to use said API.

The `File` and `Directory` classes may not be examples of that principle but we shouldn't create a blanket policy that all documented APIs *must* be exported. What that causes is a reason for *not* documenting things just to avoid having to export them because that's not how the API is intended to be used ... which I think we can all agree is a solution far worse than the initial problem.

**Comment by jessegrosjean** [comment]
> I disagree that all classes documented in the API must be exported.  There are valid reasons that an API would want to be the sole source of instances of a class (a factory class or factory method for example),

Yes, that makes perfect sense. I qualified my "export all" with "for all classes where it would make sense for the package developer to instantiate", which might not have been very clear. Maybe a clearer rule would be all classes that have a publicly documented constructor method.

Anyway just my idea. I'm new to this project and maybe don't fully understand the ramifications.

**Comment by lee-dohm** [comment]
Yeah, I didn't quite grasp the qualification there especially given the title of the issue. I think the documentation could be enhanced to give an indication of how to instantiate a class or if it isn't intended to be.

**Comment by kevinsawicki** [comment]
> but Disposable, and CompositeDisposable should be exported since it makes sense for a package developer to instantiate them.

These are now exported :+1:

> Except for File and Directory which are documented, but not exported.

These are now exported as well :+1: 

Closing this out.
