### ISSUE TITLE
Combined/Shared UI + Syntax theme

### ISSUE THREAD

**Issue by nevir** [atom/atom#5596]
I would like to be able to build a UI and syntax theme that share a color palette (and font/misc stylistic choices). However, I also want to let users customize the shared color palette, which makes things difficult.

Ideally, I think, I would want to have a shared package that both the syntax and UI themes depend on, and pull configuration from. That seems like it's a ways away, however.

So: maybe as a short term compromise: would it be reasonable to have a single package define both a UI _and_ syntax theme? That's one idea at least

**Comment by simurai** [comment]
> I also want to let users customize the shared color palette

Ya, the "changing Less variables from the settings" wasn't as easy as initially thought. Still hope there is a way one day.

> Ideally, I think, I would want to have a shared package that both the syntax and UI themes depend on

That would be nice. Also for themes that have light and dark versions. For example the One themes have a light and dark UI version that are almost identical except for the `ui-variables.less`. So in that case, having a shared package would remove the need to always update them both.

I saw somebody using git submodules. Maybe it was you? Did that work out?

> So: maybe as a short term compromise: would it be reasonable to have a single package define both a UI and syntax theme? That's one idea at least

Hmm.. in theory, yeah, a UI theme could style everything (with the `atom-text-editor::shadow` selector), but in the settings, there will always be a selected Syntax theme. And then they would clash. I think [graphite-ui](https://atom.io/themes/graphite-ui) tried to do that, but now it only overrides the Syntax background + gutter.

Maybe a better option is to use `syntax-variables.less` as your main color palette. And then import it also into your UI theme and use the colors there too. Something like this:

```less
// in syntax-variables.less
@syntax-background-color: tomato;

// in ui-variables.less
@import "syntax-variables";
@base-background-color: @syntax-background-color;
```

The [https://github.com/ignism/polymorph-ui](polymorph-ui), [isotope-ui](https://github.com/braver/isotope-ui) and [one-dark-ui](https://github.com/atom/one-dark-ui) do it like that. I like this way because then UI themes match with any kind of Syntax themes, not just its pair.
