### ISSUE TITLE
Failed to spawn command clang

### ISSUE THREAD

**Issue by larsw1997** [atom/atom#5610]
Hello, I just installed atom. I've installed both linter and linter-clang. Every time I try to open a c file, I get the error:

 Uncaught BufferedProcessError: Failed to spawn command `clang`. Make sure `clang` is installed and on your PATH

Does anyone have an idea how to solve this? I am on linux-mint cinnamon

**Comment by larsw1997** [comment]
Nevermind, I had to install the clang package.

**Comment by ogzd** [comment]
I had the same problem with Ubuntu 14.04 LTS where linter and linter-clang was installed. 

Even though you install clang-3.x package, you need to rename the clang command since it is default by clang-3.x. There are two options here, either change the name of the command:

```
sudo mv /usr/bin/clang-3.x /usr/bin/clang
```

or

update init.coffee to:

```
clangCommand: 'clang-3.x'
clangPlusPlusCommand: 'clang++-3.x' 
```

**Comment by tgaurnier** [comment]
I just started having this issue out of nowhere, the problem is I already have clang installed, and there is already a 'clang' file. This is the output of `ls /usr/bin | grep clang`:
clang
clang++
clang-3.4
clang++-3.4
clang-3.5
clang++-3.5
clang-apply-replacements
clang-apply-replacements-3.4
clang-apply-replacements-3.5
clang-check
clang-check-3.4
clang-check-3.5
clang-query
clang-query-3.5
clang-tblgen
clang-tblgen-3.4
clang-tblgen-3.5
clang-tidy
clang-tidy-3.4
clang-tidy-3.5

**Comment by tgaurnier** [comment]
Just upgraded to Ubuntu 15.04, and did a `sudo apt-get install --reinstall clang`, issue still persists.

**Comment by mnquintana** [comment]
@tgaurnier et al. this is an issue with https://github.com/atomlinter/linter-clang – it would probably better to move the discussion there because it doesn't have anything to do with Atom core.

**Comment by tgaurnier** [comment]
@mnquintana, it can't just be linter-clang that is the issue, because ctags-atom also gives the same error.

**Comment by tgaurnier** [comment]
OK, I don't know what specifically was causing this error for me, but it seemed to have been fixed by removing ~/.atom/storage, very strange, but I'm just glad it's fixed now and I can continue my work.

**Comment by isopropylcyanide** [comment]
Wrote this figuring it would be of help to somebody. I had the clang-3.5 which was messing up with the programs that just required clang period. Following fixed it for me.

__C compilation__ :
As suggested above, the following worked perfectly for C but not for C++

     sudo mv /usr/bin/clang-3.5 /usr/bin/clang

__C++ compilation__:
Problem was that clang++-3.5, though working, wouldn't replace the default clang++.
Simply, create an alias worked.
    
    alias clang++='clang++-3.5'
To avoid creating an alias every time I added it to my bashrc file.

**Comment by AndersonFirmino** [comment]
I had passed by the same problem.
The solution that I found was:

Go in the autocomplete-clang plugin settings and change the field "Clang Command"
for the version that you installed in your machine. 

:coffee: :smile:
