### ISSUE TITLE
join-lines should do the right thing when lines have a prefix (e.g. # or // comments)

### ISSUE THREAD

**Issue by dmnd** [atom/atom#5627]
```
// line 1
// line 2
```

becomes

```
// line 1 // line 2
```

My feature request is for `editor:join-lines` to realize that both lines are comments, that comments have a common prefix, and thus to strip the prefix from the second line. So the result would instead be:

```
// line 1 line 2
```

**Comment by karloluis** [comment]
This should be tied to some syntax or file-types in specific. This behavior is slightly unwanted in files where this might occur without code affiliation. But I hear you out that comments might benefit from this procedures. Good Catch! +1

**Comment by priithaamer** [comment]
Makes sense. Another thing that's been bugging me is single space between joined lines that cannot be configured. For example, when joining lines in this HTML code:

```html
<span>
  Text content
</span>
```

I end up with

```html
<span> Text content </span>
```

Which is not quite what i wanted. In editor i used prior Atom, join lines command did not leave space between joined lines and i never wanted space there. In atom i join lines, then move cursor forward and press backspace, which is cumbersome. I'm not saying current join-lines implementation with space between lines is wrong, but shouldnt be it a configurable behavior?

**Comment by Yajo** [comment]
This also happens when writing Markdown or RST files.

Prior to joining:
![captura de pantalla de 2016-03-29 11-23-24](https://cloud.githubusercontent.com/assets/973709/14103549/fd8350d8-f5a0-11e5-90f7-35a62f20fbd0.png)

After joining:
![captura de pantalla de 2016-03-29 11-23-39](https://cloud.githubusercontent.com/assets/973709/14103538/f9019010-f5a0-11e5-9655-599f60600d63.png)

What I expected:
![captura de pantalla de 2016-03-29 11-24-02](https://cloud.githubusercontent.com/assets/973709/14103536/f508e9fe-f5a0-11e5-9b55-67c95c8db43a.png)

And it's even worse with numbered lists.

**Comment by dmnd** [comment]
Thanks stalebot. I just confirmed this repros so the issue shouldn't be closed.
