### ISSUE TITLE
When adding a Root Folder all other root folders are expanded

### ISSUE THREAD

**Issue by nikolaydyankov** [atom/atom#5663]
When adding a Root Folder all other root folders are expanded.

**Comment by karloluis** [comment]
Unreplicable on my end. Any further info that you can provide?

Start with OS and current version of Atom please.

**Comment by nikolaydyankov** [comment]
Atom 0.182.0
OSX 10.10.2 (14C109)
![untitled-3](https://cloud.githubusercontent.com/assets/1205055/6313566/0147f312-b9bc-11e4-86f4-e61cbe96761c.png)

**Comment by karloluis** [comment]
Well that's silly and easily replicable. Just confirmed it on my end, this is probably some iffy line of coding in the action button. Hopefully it get's patch very fast, should be an easy fix.

Good catch.

**Comment by wvanlint** [comment]
If you haven't started working on it, would you mind if I take a look?
It also seems that the directory expansion states are not maintained over restarts since they got stored as a list.

I tried something out here: https://github.com/wvanlint/tree-view/compare/save_expansions
It seems to work when I try it out but I'm still working on getting the tests to pass.
Due to the data structure, root folders got collapsed by default and a lot of the tests are relying on it.
However, there are still some test failures after calling expand or click on the root folders so I'll have to look into it.

**Comment by maxbrunsfeld** [comment]
@wvanlint that'd be awesome; I'd definitely merge a PR fixing this issue. Can you add a test for this too? I can give you some guidance if you have any issues working w/ our test suite. Thanks!
