### ISSUE TITLE
Atom icon is still pixelated in certain occasions

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#5670]
This was mentioned in a different issue (https://github.com/atom/atom/issues/5500#issuecomment-73915709) but its own dedicated issue was never opened, so here we are.

The Atom icon still shows as pixelated (#4811) when the "No Update Available" box appears:
![image](https://cloud.githubusercontent.com/assets/2766036/6316455/58492bb6-b9f5-11e4-9ee4-c0452663dc72.png)

Something interesting to note is that unlike the main Atom window/taskbar icon, the popup has the white border, which makes me think that Windows is again trying to downsize the 1024px icon.

And unrelated: It would be nice if all the icon sizes could somehow get the white border applied to them for consistency :).

/cc @zcbenz?

**Comment by simurai** [comment]
> And unrelated: It would be nice if all the icon sizes could somehow get the white border applied to them for consistency :).

Ya, consistency would be nice. The white border isn't added only to very small sizes.. I think `16px + 32px`. The reason is so that it leaves more space for the actual "atom" icon that is kinda complex and looks fuzzy when it's very small. Also, a white border almost needs a shadow so you would see it on a white background, which would leave even less room for the "atom".

**Comment by jimgraham** [comment]
This error occurs at:
https://github.com/atom/atom/blob/master/src/browser/auto-update-manager.coffee#L92

and 

https://github.com/atom/atom/blob/master/src/browser/auto-update-manager.coffee#L103

Commenting out those lines in the corresponding `.js` files in my 0.183 install gives the correct icon look (since the change made to `atom-shell`)

![atom](https://cloud.githubusercontent.com/assets/430293/6379378/d569367e-bcff-11e4-9b42-d6f3e7dceed2.png)

Need to grep the source to find items like `icon: path.resolve(__dirname, '..', '..', 'resources', 'atom.png')`
