### ISSUE TITLE
Single Equals in Conditional - likely :bug:

### ISSUE THREAD

**Issue by kans** [atom/atom#5675]
I ran into the some [odd code](https://github.com/atom/atom/blob/master/src/package.coffee#L526
) trying to fix a different bug in atom.

```coffeescript
  isCompatible: ->
    return @compatible if @compatible?

    if @path.indexOf(path.join(atom.packages.resourcePath, 'node_modules') + path.sep) is 0
      # Bundled packages are always considered compatible
      @compatible = true
    else if packageMain = @getMainModulePath()
      @incompatibleModules = @getIncompatibleNativeModules()
      @compatible = @incompatibleModules.length is 0
    else
      @compatible = true
```
I can't believe the ```else if``` does what was intended-  *packageMain* isn't used anywhere, and the expression evaluates to true when *@getMainModulePath* returns something truthy.

edit:
This sort of stuff is everywhere in atom...  please consider not doing this! In the one case, you must guess at the intent of the author by examining the entire context of this line.  In the other case, you just have to look at the line.  There is no good reason to use this sort of construct, ever.

Douglas Crockford says
[*Avoid forms that are difficult to distinguish from common errors...*](https://www.youtube.com/watch?v=taaEzHI9xyY#t=2420):

**Comment by thomasjo** [comment]
> There is no good reason to use this sort of construct, ever.

You are of course entitled to that opinion — and I strongly disagree with it. This construct can make CoffeeScript code cleaner and easier to read. It certainly isn't always the case however, so it needs to be used carefully since it *can* make code harder to understand.

For the specific code block in question, since `packageMain` is never actually used, it should perhaps be changed to avoid confusion.

---
I vote for this being closed, but I'll defer that to @kevinsawicki, @nathansobo, @benogle.
/cc @lee-dohm, @izuzak

**Comment by lee-dohm** [comment]
My personal opinion is that if the code is working properly and there are specs covering the code in question then, while it may be an issue for readability or maintainability, it isn't a bug.

On the other hand, CoffeeScript doesn't (commonly) use `==` or `===` for equality. [CoffeeScript uses the keyword `is` for equality](http://coffeescript.org/#operators), specifically to deal with this kind of ambiguity. So since `=` and `is` are easily distinguishable, I would say that this *isn't* a readability or maintainability issue.

**Comment by batjko** [comment]
I can see how that kind of thing could easily be confused, but only on first sight for someone who isn't used to it. So it does seem to be a personal style issue. 
While the use of `is` is not mandated for equality it is very much in the spirit of CoffeeScript, and should be recommended in potentially ambiguous constructs like this. 

I'm glad this came up though, it's an educational example.

**Comment by nathansobo** [comment]
If we aren't actually using the variable then there's no reason to assign it. But I'm not ready to prohibit combined conditional tests and assignments. It's subjective, but I like the compactness it can bring to certain patterns and I'm not convinced it's incomprehensible. Obviously, local discretion needs to be applied.
