### ISSUE TITLE
omnisharp-atom toggle

### ISSUE THREAD

**Issue by VirtualOverride** [atom/atom#5682]
![error](https://cloud.githubusercontent.com/assets/6830923/6320369/64e4b53a-bb16-11e4-8487-54ccb5e24fdb.png)

i install atom via brew cask then install packages like omnisharp-atom and autocomple-plus. then when i toggle the omnisharp-atom i have this error.

"Omnisharp Atom needs the package `language-csharp` (version ^0.3.0) to be installed. You have an older version 0.5.0."

Note: language-csharp plugin is already install when i install the atom.

**Comment by lee-dohm** [comment]
This message is from code in the [omnisharp-atom package](https://github.com/OmniSharp/omnisharp-atom) because Atom doesn't have the concept of package dependencies like this. Specifically here:

https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/dependency-checker.coffee

Please file a bug on the omnisharp-atom package for this.
