### ISSUE TITLE
language-lua should be installed by default

### ISSUE THREAD

**Issue by Zireael07** [atom/atom#5691]
Many other programming languages are supported out-of-the-box, but not Lua.
This led me to think for a moment that there is no syntax highlighting in Atom.

Please include language-lua package in core in future versions.
Thanks in advance.

**Comment by izuzak** [comment]
Thanks for the suggestion, please see my reply on a similar issue https://github.com/atom/atom/issues/3716.

If it was hard for you to discover that it's possible to add Lua support with a package, I'd suggest opening another issue with a suggestion about how to improve the documentation or the first-run experience so that it's easier to discover.
