### ISSUE TITLE
 Ctrl-shift-right at end of line doesn’t select EOL and next line whitespace up to first word

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#5712]
I expect that a ctrl-shift-right with the cursor at the end of the line, selects the end-of-line and the white-space at the beginning of the next line, but it doesn't.

[see also](https://discuss.atom.io/t/ctrl-right-at-end-of-line-doesnt-select-eol-and-next-line-whitespace-up-to-first-word/14889)

**Comment by izuzak** [comment]
> I expect that a ctrl-right with the cursor at the end of the line, selects the end-of-line and the white-space at the beginning of the next line, but it doesn't.

@stijnsanders Can you share more details about why you expected that to happen? Is that the default behavior in some other editors? Normally, selections don't happen if you don't hold `shift` (there are exceptions, though), so I'm wondering if you're asking about `ctrl-shift-right`? Also, which OS are you using -- different OSes have different keybindings for some commands.

`ctrl+right` and `ctrl+shift+right` currently move/select to the end of the word on Windows (not the beginning of the word). If the cursor is not within a word, then it will select whitespace up to the next words and the next word:

https://github.com/atom/atom/blob/0bf0c0527f70731da154dc6027001bf0b6ac34c3/keymaps/win32.cson#L84-L86

**Comment by stijnsanders** [comment]
I'm on Windows. Yeah just try it on a plain textarea here: write this

    aaa
    bbb
    ccc

then put the keyboard cursor right of `aaa`, press Ctrl-Shift once, and the EOL between `aaa` and `bbb` is selected, press again and `bbb` and its EOL is selected as well, press again to add `ccc` to the selection. (I don't know if this is different on Mac)

So in other words, I guess I'm asking that `editor:select-to-(beginning|end)-of-word` not stop at an EOL and continue on preceding/succeeding lines.

**Comment by Yajo** [comment]
I think I understand what he means.

Let's suppose `|` is the caret:

    somevar = (|
        this)

Now press `Ctrl+right`. Happens:

    somevar = (
        this|)

I would prefer:

    somevar = (
        |this)

The same with `Ctrl+Del` and `Ctrl+Shift+Right`, etc.

**Comment by stijnsanders** [comment]
Yes, that's it. Thank you.

**Comment by izuzak** [comment]
@stijnsanders @Yajo -- thanks for explaining. :bow: Could you please also answer these other questions I asked above?

> Can you share more details about why you expected that to happen? Is that the default behavior in some other editors? 

Basically, could you explain the motivation for changing this behavior (some users might be used to this behavior already)? 

Also, would adding a new command which you could bind to a keystroke be a solution you could use as well, instead of changing the behavior of the current command bound to that keystroke (so that you can bind `ctrl-right` to this new command if you want, but the default would stay the same)?

**Comment by stijnsanders** [comment]
It is the default behaviour in most, if not all, other editors. I doubt any users are used to this behaviour already (but those things are hard to get metrics on, aren't they.)

In case you disagree, yes a new command would do fine.

**Comment by izuzak** [comment]
> It is the default behaviour in most, if not all, other editors.

For completeness, could you give a few examples of popular text editors where this is the behavior?

**Comment by stijnsanders** [comment]
Examples of popular text editors that select up to the start of the first word on the next line with Ctrl-Shift-Right with the cursor in front of an EOL:

* Notepad (Windows)
* a plain `<textarea>` in any browser, (I checked IE, Firefox/Waterfox on Windows, and Chrome but there selection goes all the way to the start of the second word?!)
* Notepad++
* LibreOffice Writer
* Embarcadero RAD Studio
* Microsoft Visual C++
* (I tried http://jsfiddle.net but there it selects to the end of the first word of the next line?!)

**Comment by Yajo** [comment]
Every editor I ever used did this. I can remember Netbeans and Enki. In fact, when I considered using Gedit, I discarded it because of this.

Also, it just seems more *natural*. Let me explain following the example in https://github.com/atom/atom/issues/5712#issuecomment-75956006:

    somevar = (|
        this)

Now press `Ctrl+right`. Happens:

    somevar = (
        this|)

Now press `Ctrl+left`. Happens:

    somevar = (
        |this)

What I mean with *natural* is that if I press `Ctrl+right` and then `Ctrl+left` somehow I expect to get to the same place  I was (or at least near), in this case:

    somevar = (|
        this)

But that doesn't feel like a good behavior for `Ctrl+left`. The same applies to `Ctrl+right`.

**Comment by tstrimple** [comment]
Would love to see this. It's definitely one of the pain points moving from Sublime (or Visual Studio, Notepad++, etc)

**Comment by vlykarye** [comment]
Hello, noticed that this bug is still a bug.
I was wondering if there has been any movement on the subject or if a new package fixes this.

**Comment by trick2011** [comment]
this is indeed a big pain point for me when moving from notepad++(windows) and kate(ubuntu). It really slows my programming down because I then constantly have to deselect the beginning of words and select the right parts when deleting things when deleting thins instead of 2 fluent consecutive actions
