### ISSUE TITLE
Files are scrolled to top when updated externally

### ISSUE THREAD

**Issue by NickWhiu** [atom/atom#5730]
steps to reproduce
1. open a log file in atom
2. scroll part way down the file
3. add new line to end of log file with an external tool/editor and save
4. go back and view the log file in atom

expected
- log file is reloaded
- log file scroll position is still part way down (same as in step 2 above)

actual
- log file is reloaded (PASS)
- log file scroll position goes back to top (FAIL)

Every time a new line is added externally the editor reloads it (as it should) but it jumps to the top which makes it impossible to read log files while they're been written because atom constantly jump back to the top.

**Comment by lee-dohm** [comment]
Related atom/markdown-preview#178

**Comment by ipaintcode** [comment]
FWIW I believe this is a stopgap for the issue at hand: [remember-files-positions](https://atom.io/packages/remember-file-positions "remember-file-positions")

**Comment by mjmasn** [comment]
Same issue with running `eslint --fix` on save. Doesn't happen every time, but when it does the file clearly goes blank beforehand so may be due to the file taking too long to write and/or Atom trying to read it as it's being written? 

I appreciate the file could change considerably externally, but could Atom not remember the absolute scroll position and return there (or clipped to bottom of file if it gets shorter than the scroll position)? This would at least resolve the issue for append-only writes (e.g. logs) and (mostly) inline changes (e.g. eslint). For complete file re-writes the scroll position would be messed up but what can you expect in that situation if all the content has changed?

(@ipaintcode remember-files-positions doesn't work for me)

**Comment by adamreisnz** [comment]
Can't seem to reproduce this anymore in 1.25
