### ISSUE TITLE
Code highlight issue -- support Jekyll front matter

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#5745]
Jekyll front matter may be added to the top of any file and it is signified by `---` and `---` to contain extra content.

This is erroneously being interpreted as HTML by Atom. In this example you can see the `&` symbol showing an error because it is not valid HTML.

![screen shot 2015-02-25 at 2 31 36 pm](https://cloud.githubusercontent.com/assets/382183/6378706/12f8eb60-bcfb-11e4-8620-770c889f078e.png)

**Comment by izuzak** [comment]
> This is erroneously being interpreted as HTML by Atom. 

You opened an HTML file as far as I can tell, so Atom interpreted it as HTML. What did you expect would happen instead and why?

**Comment by izuzak** [comment]
> Jekyll front matter may be added to the top of any file

Can you share some links to language specifications which back this up (e.g. HTML, which you use in the screenshot)? The fact that Jekyll (a single specific tool) can interpret that doesn't mean that every language grammar should report it as a valid string (because it's not). 

You might consider building a package which adds support for that, though (since it's related to a specific tool and use-case). What do you think about that?

**Comment by fulldecent** [comment]
Yes, language is specified here:

http://jekyllrb.com/docs/frontmatter/

Front matter can be prepended to any text file. 

I do note that it is correctly detected and highlighted in this markdown file. Architecture-wise I am not sure where/how this should be implemented in Atom.

![screen shot 2015-02-25 at 3 05 58 pm](https://cloud.githubusercontent.com/assets/382183/6379380/db0de5de-bcff-11e4-9b11-cdb49760211d.png)

**Comment by izuzak** [comment]
> Yes, language is specified here:
> http://jekyllrb.com/docs/frontmatter/
> Front matter can be prepended to any text file.

That's Jekyll's documentation, which is a single specific tool. Does the HTML spec allow front matter? 

I'm :-1: on adding support for this in all languages as something that should be included by default. If anything, it should be supported by a package. That's why packages are here. Otherwise, would we be discussing adding support for every type of such extensions which can be added to any file for a specific tool (imagine frontmatterTurbo released tomorrow for JekyllMega, with a similar, but different syntax).

**Comment by fulldecent** [comment]
Yes, this should be a package.

Frontmatter is a generic pre-processor. Front matter is not valid HTML (of course). After running through Jekyll, a HTML-with-front-matter source file will spit out HTML. Detecting Front matter in a file is unambiguous.

Less than 50% of users writing HTML will be using Front matter. But the number will be significant enough that someone else will report this issue.

**Comment by izuzak** [comment]
> Yes, this should be a package.

Agreed. Suggestion: open a feature request on the [existing jekyll package](https://atom.io/packages/jekyll), create a new one, or suggest it on [the forum](https://discuss.atom.io/c/packages) and maybe someone picks it up.
