### ISSUE TITLE
What happens here? space,space,"[",enter

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#5764]
I'm on Windows with version 0.182.0. Open a new window. Press space, space, "[" and then enter. What happens here? Why are the two spaces not repeated on this new line? Why has "]" moved to a third line?

Is there a setting I can change to disable this behavior?

**Comment by batjko** [comment]
![image](https://cloud.githubusercontent.com/assets/7287076/6393216/1e3410b6-bdc0-11e4-93bc-8f85bf86c2d5.png)

Well, for one thing, by default Atom will assume you want to close your brackets and always creates that closing counter part.
Then it puts the cursor before that so you can immediately start filling in your array content.

As to why your initial indentation isn't being maintained... not sure. I'm guessing it's because there is no content anywhere higher that starts at the first character of the line, so there's no reason for it to assume you actually never wanted to start at the beginning of the line.

What were you trying to create here?

**Comment by stijnsanders** [comment]
I was trying to create

      [
      |]

where `|` would be where the cursor is. I also notice the indentation is missing even with allsorts of content higher.

**Comment by batjko** [comment]
It also depends on which language file you're using.
For example if I save my new file as a .json file, and then repeat what you tried above, I get what you want:

![image](https://cloud.githubusercontent.com/assets/7287076/6395731/e4713798-bdd1-11e4-8678-58ff9a47f65d.png)

**Comment by 50Wliu** [comment]
Plain text files will remove all indentation on creating a newline regardless of previous indentation.

**Comment by stijnsanders** [comment]
aah, ok, label this one 'works by design' or 'won't fix' or 'no issue' or what have you.
(I guess I'll have to put some time in trying to write me a grammar for http://xxm.sf.net/ files...)
