### ISSUE TITLE
editor:split-selection-into-lines keybinding not on settings

### ISSUE THREAD

**Issue by mamoit** [atom/atom#5765]
editor:split-selection-into-lines does not show up on settings.
version: 0.184.0
Platform: Debian

**Comment by izuzak** [comment]
That's because the Keybindings section shows _keybindings_, and there's no keybinding for that command by default on linux: 

https://github.com/atom/atom/blob/master/keymaps/linux.cson

Does it show up if you add a keybinding for that command in your keymap.cson file?

https://atom.io/docs/v0.184.0/customizing-atom#customizing-key-bindings

**Comment by mamoit** [comment]
It does show up on the key bindings, but on the menu (Selection > Split into lines) the binding is not updated (even after reload) nor the binding actually works.
Tried that same keystroke with another command (in the keymap.cson) and it did what it was supposed to do for that other command.

**Comment by izuzak** [comment]
Can you share how exactly you defined the keybinding, together with a screenshot of the keybinding resolver?

https://github.com/atom/atom/blob/master/docs/debugging.md#check-the-keybindings

I'm not sure if menus dynamically update when you change keybindings, but the keybinding should work, so let's try and figure that out first.

**Comment by mamoit** [comment]
Here it is
![atom-keys](https://cloud.githubusercontent.com/assets/4675358/6394692/16e97886-bdcb-11e4-8eb6-082bbe6937c7.png)

**Comment by izuzak** [comment]
The keybinding resolver says that the command was triggered. How do you know that it didn't work? If you made a single selection of both lines 1 and 2, then triggered the command -- you should see the same selection, but from two cursors. Try pressing left arrow or right arrow and see if you have two cursors.

Also, is the result different if you run the command from command palette?

**Comment by mamoit** [comment]
I did press left and right and it didn't have multiple cursors
the following screenshot is the result of selecting the "split into lines" option directly from the menu.
![atom-keys2](https://cloud.githubusercontent.com/assets/4675358/6394891/9bedc554-bdcc-11e4-9082-8f0584d52e7e.png)

**Comment by izuzak** [comment]
Ah, I think I see a typo. Instead of `editor:split-selection-into-lines` try using `editor:split-selections-into-lines` (notice the extra `s` in `selections`).

**Comment by mamoit** [comment]
Typo bug, yeeey -.-'
Thank you, I don't know where I got the `editor:split-selection-into-lines` from.
The key binding is updated on the menu upon reload.
So it's just left the fact that `editor:split-selections-into-lines` doesn't show up in the keybinding list if not manually defined.

**Comment by izuzak** [comment]
Great to her that.

> So it's just left the fact that editor:split-selections-into-lines doesn't show up in the keybinding list if not manually defined.

As I explained, that's expected because there's nothing to show -- the keybinding is undefined until you defined it and the Settings View shows only keybindings, it doesn't show commands. Does that make sense? 

There's already an issue to show all commands in Settings View, even if they don't have a keystroke defined. https://github.com/atom/settings-view/issues/165

I'm closing this in favor of that, since we seem to have figured out the other stuff.

**Comment by mamoit** [comment]
Thank you for your time,
and sorry for the false alarm.

**Comment by merqurio** [comment]
:+1: Thanks, super useful ! :grin:
