### ISSUE TITLE
Manual change of font size leads to visual frobnication in Atom 0.184

### ISSUE THREAD

**Issue by davepeck** [atom/atom#5771]
A recent build of Atom seems to have introduced a race condition when manually changing font size with `Cmd =` and `Cmd -`. 

To reproduce, simply repeatedly and rapidly press `Cmd =`, for example.

**Comment by izuzak** [comment]
@davepeck Is this the behavior you're observing? (Including a GIF is always helpful. :wink:)

![fonty](https://cloud.githubusercontent.com/assets/38924/6401252/6928a296-bdff-11e4-825d-96d9500ca094.gif)

I'm pretty sure I've observed that behavior even before 0.184.0. 

cc @nathansobo

**Comment by davepeck** [comment]
Yes that's the behavior. Thanks.

**Comment by nathansobo** [comment]
Yeah, I've seen that too. Not sure if I introduced it via recent changes but we can prioritize it to be fixed sometime before 1.0 or soon after.

**Comment by lee-dohm** [comment]
I was able to reproduce it as well and that's exactly what I saw.

**Comment by nathansobo** [comment]
This seems to be caused by a weird feedback loop when config changes are made in rapid succession:

When we increment the font size quickly, this happens:

1. Change the font size from 10 to 11 in config.
2. This triggers a write of the config to disk.
3. Change the font size from 11 to 12 in config.
4. Then we detect the config change to the file based on the disk write in step 2.
5. Then we load the newest values from the disk, setting the font size from 12 back to 11.

Maybe we could disable change detection when disk writes are in flight?
