### ISSUE TITLE
Support running atom commands from CLI

### ISSUE THREAD

**Issue by gregmac** [atom/atom#5779]
It would enable a number of useful scenarios to allow specifying commands to execute from the CLI when opening Atom.

For example, using the [merge-conflicts](https://atom.io/packages/merge-conflicts) package, it would be possible to use Atom as a merge resolution tool that could be launched from a source control client:

```
atom --exec 'merge-conflicts:detect' path/to/repository 
```

There are undoubtedly other, better ways for this syntax to work, but using the same commands that appear in Keybinding settings in the UI would be good for usability. 

If there are other scenarios people can think of that would benefit from being able to do something more complex than running a single command, that feedback would be useful here as well to help define how this could work.

**Comment by mark-hahn** [comment]
I would suggest making a package to do this but I happen to know it can't
be done . I wanted to open web pages using the CLI and my web-browser
package.  I found it was impossible because Atom doesn't pass on the CLI
arguments to openers.  It opens everything as a text file.
So Atom core would have to change to support this.
