### ISSUE TITLE
Weird vertical text selection behaviour

### ISSUE THREAD

**Issue by Fank** [atom/atom#5788]
![optimised](https://cloud.githubusercontent.com/assets/1900106/6416808/2e4526c2-bea9-11e4-9e35-873a2210f9b5.gif)

I used alt + shift + arrow up/down
Syntax perl
```perl
my $sth = $dbh->prepare(q~
	SELECT
		TableA.id																AS TaskObserverId
		,TableA.i_user_id														AS TaskObserverUserId
		,TableB.s_displayname													AS UserDisplayName
		,TableB.s_email															AS UserEMail
	FROM
		TableA WITH(NOLOCK)
		LEFT OUTER JOIN TableB WITH(NOLOCK)ON TableA.id = TableB.i_user_id
~);
```

Atom 0.184.0 on Ubuntu 14.10 x64

**Comment by mark-hahn** [comment]
What package are you using to do this?  You should really post this
question at the package's repo.

**Comment by Fank** [comment]
yea sorry i thought this were a base feature from atom

**Comment by Fank** [comment]
I only see this feature in linux (ubuntu 14.10), on windows i can't use this feature.
I removed all custom packages to validate that this is an core feature, tested with latest 0.186.0 version.

**Comment by izuzak** [comment]
@Fank could you explain what's going on on that GIF in the issue? I've watched it 5 times and I'm not sure what you're trying to do or what the problem is. If you could use a simpler example and explain what exactly is the problem and what you expected to see instead, that would be helpful. Step-by-step instructions for reproducing using the snippet you provided would be great.

**Comment by Fank** [comment]
Ok sorry i thought a gif may be better. So the main issue is that if you use a vertical text selection (not shift + click), the multiple cursors should be at the same position on the vertical axis, but they won't as shown in the gif.
If you try the to select multirows on the front part of the text it spawn all cursors on the same position.
But if try to select something surrounded of tabs it spawns the cursors on random positions and not in the same position as it should do, same behaviour on the right part (near `AS ...`)

**Comment by izuzak** [comment]
> Ok sorry i thought a gif may be better. 

It is better and thank you for posting that GIF, it's just that it's sometimes hard to understand what's going on -- it's not clear what you're clicking or which keys you're pressing and when. That's why it's always helpful to have step-by-step instruction which explain what you're doing, what happened and what you expected instead. One thing which helps with this is the keybinding resolver: https://github.com/atom/keybinding-resolver. If you record a GIF with that turned on, then everyone can see which keys you're pressing.

Anywaaay, I first tried to reproduce this by copy/pasting the example you provided, but it didn't copy/paste the tabs correctly -- I only got spaces. After I replaced the spaces with the tabs, I could reproduce the problem you reported in the latest version of Atom on OSX:

![tabs](https://cloud.githubusercontent.com/assets/38924/6489084/f41722a6-c29b-11e4-919d-0436aff8bad0.gif)

That's not the behavior I expected to see as well, so I'm labeling this as a bug. Thanks for reporting and reopening.
