### ISSUE TITLE
Marker::copy seems to do nothing

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#5789]
No matter how I call `Marker::copy` I get `undefined` returned.

See https://discuss.atom.io/t/marker-copy-question/15150

Windows 8.1
atom 184

**Comment by Veedrac** [comment]
The current implementation is:

    return this.displayBuffer.getMarker(this.bufferMarker.copy(properties).id);

I believe this alternative implementation will work:

    return this.displayBuffer.markBufferRange(this.getBufferRange(), properties);

**Comment by izuzak** [comment]
This still seems to be a problem. /cc @benogle @maxbrunsfeld for :eyes:

**Comment by izuzak** [comment]
Ahhh, this seems to be happening for markers which are associated with selections. `MarkerStore.destroyMarker` gets called right after the marker was copied, because TextEditor is merging selections:

![screen shot 2015-08-01 at 08 12 09](https://cloud.githubusercontent.com/assets/38924/9020855/43b39016-3825-11e5-9c75-093b1c0d2ff8.png)

In other words, it seems that it's not possible to copy markers which are associated with selections. (As far as I can tell, this problem doesn't happen with non-selection markers). Not really sure what to do here, but perhaps we could update the docs for the Marker.copy method? /cc @nathansobo 

Currently, the docs [say this](https://github.com/atom/atom/blob/f850750707950cf7d022e467cd5079c75cdf0f4d/src/marker.coffee#L70-L75):

> Essential: Creates and returns a new {Marker} with the same properties as this marker.

Which is a bit misleading since there are cases when a new marker might not be returned? :thought_balloon:

**Comment by nathansobo** [comment]
One thing you could do to avoid this when copying a selection's marker is to change the *type* of the marker so it's not considered a selection.

```js
marker.copy({type: null})
```

Maybe it's worth documenting this?

**Comment by izuzak** [comment]
> One thing you could do to avoid this when copying a selection's marker is to change the type of the marker so it's not considered a selection. Maybe it's worth documenting this?

:+1: I like that idea, @nathansobo.
