### ISSUE TITLE
Cursor scope incomplete when tag is closed (html)

### ISSUE THREAD

**Issue by joeferraro** [atom/atom#5803]
Atom version 0.184.0
Mac OSX 10.10.1

Steps to reproduce:
1. Open HTML file
2. Type `<div s` (cursor should be after the "s")
3. Run the following in the console:
   
   ```
   editor = atom.workspace.getActiveTextEditor()
   cursor = editor.getLastCursor()
   cursor.getScopes() // **rightly** produces: ["text.html.basic", "meta.tag.block.any.html", "entity.other.attribute-name.html"]
   ```
4. Type `<div s >`
5. Move cursor back to after the "s"
6. Run `cursor.getScopes()` in the console:
   
   ```
   // cursor.getScopes() **wrongly** produces: ["text.html.basic", "meta.tag.block.any.html"]
   ```

**Comment by lee-dohm** [comment]
You can get the scopes at the cursor much more easily using <kbd>Alt+Cmd+P</kbd>.

Are you meaning to say that you believe that the HTML grammar is incorrect? Or that the tokenizer's behavior is incorrect?

The behavior you're specifying is consistent with other instances. For example (where `|` is the cursor position):

* `<div | s>` &mdash; `meta.tag.block.any.html` because the cursor is before whitespace which isn't part of any scope over and above the tag block
* In a Markdown file: `&co|py;` &mdash; `constant.character.entity.gfm` because the character following the cursor is part of a character entity
* In a Markdown file: `&copy;| ` &mdash; `source.gfm` because the character following the cursor is whitespace following the end of the character entity
* In a Markdown file: `# fo|o` &mdash; `markup.heading.heading-1.gfm`
* In a Markdown file: `# foo|` &mdash; `markup.heading.heading-1.gfm` because [the end-of-line is part of the pattern](https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson#L98-L107), the cursor is still part of the heading scope

If you're suggesting the HTML grammar is incorrect, then this should probably be reopened on the [language-html repo](https://github.com/atom/language-html). If you're suggesting the tokenizer implementation is incorrect, how else should it behave?

**Comment by joeferraro** [comment]
@lee-dohm thanks for the shortcut tip :+1: 

I'm not sure whether this is a grammar or tokenizer issue – hopefully that's something you can help me with. The impetus for the issue, for me, was an attempt to make one of my autocomplete-plus providers smarter. 

Example: 

When the cursor is here (and the tag is **not** closed) `<div s|`, because the cursor scope chain includes `entity.other.attribute-name.html`, I know to provide a list of attributes starting with the letter "s" for the `div` tag. 

However, if for some reason, the tag has already been closed `<div s| >`, `entity.other.attribute-name.html` is missing from the scope chain and it becomes difficult (if not impossible) for me to know that I need to present a list of attributes starting with the letter "s".

**Comment by lee-dohm** [comment]
You're welcome :grinning:

There's also this additional wrinkle: `<div s|>`. In this instance, the scope is, in my opinion, rightly `punctuation.definition.tag.end.html`. So if the cursor's scope is always determined by the character immediately following the cursor ... then your instance of `<div s| >` is correct ... the character following the cursor isn't part of the attribute, but is still part of the tag.

I think what you really want is the scope of the character immediately preceding the cursor. Perhaps something like this:

```coffee
{row, column} = cursor.getBufferPosition()
column = column - 1
column = 0 if column < 0
editor.scopeDescriptorForBufferPosition([row, column])
```
