### ISSUE TITLE
Error when adding quotes to multiple line selection

### ISSUE THREAD

**Issue by rafaelzimmermann** [atom/atom#5809]
Atom: 0.185.0-71272f5
System: 10.10.2

When using multiple line selection to add quotes, it replaces all selected text with the last selected line.

![multiline_selection_issue](https://cloud.githubusercontent.com/assets/2369982/6442981/970cdbf2-c0d2-11e4-9dbd-1c294628a208.gif)

**Comment by izuzak** [comment]
@rafaelzimmermann The text is replaced with `c` because you selected all lines and typed `"c"` (as far as I can tell).

Instead of doing that, try doing this (you can see which keys I'm pressing in the keybinding resolver at the bottom):

![quotes](https://cloud.githubusercontent.com/assets/38924/6445142/53f4b4fe-c102-11e4-88cf-95e9256d3522.gif)

You'll need to have the "Wrap selections in brackets" option enabled in the settings of the bracket matcher package:

![screen shot 2015-03-02 at 17 34 34](https://cloud.githubusercontent.com/assets/38924/6445168/79789a60-c102-11e4-9dfc-9cd2776a719e.png)

Hope this helps. If I misunderstood your report, please record the GIF again, but with the keybinding resolver shown (`cmd+.`).

**Comment by rafaelzimmermann** [comment]
![multiline_keybinding](https://cloud.githubusercontent.com/assets/2369982/6445733/ccb85d50-c0e4-11e4-8860-90c7c00d4d1d.gif)

**Comment by izuzak** [comment]
@rafaelzimmermann do you have the config option I mentioned enabled? Could you share a screenshot of that settings page?

Also, which keyboard layout are you using? Which keys are your pressing after you press `cmd-shift-right` to select all rows?

**Comment by rafaelzimmermann** [comment]
I think that happens because I am using "U.S. Internation - PC" keyboard layout. When I change my layout to "U.S." it works just fine.

Yes, my Atom is configured as you said. 

![screen shot 2015-03-02 at 3 08 04 pm](https://cloud.githubusercontent.com/assets/2369982/6447028/fefafaa8-c0ed-11e4-96ab-24f4482d84d3.png)

I pressed cmd-shift-right and then "

**Comment by izuzak** [comment]
Yep, it's a keyboard layout issue -- just noticed it's already reported here: https://github.com/atom/bracket-matcher/issues/68. Follow that for updates and thanks for helping investigate.
