### ISSUE TITLE
Large Files Cause Hangups

### ISSUE THREAD

**Issue by smiffy6969** [atom/atom#5816]
Hi,

Been using atom for a while now, love it and totally swapped full time from sublime, great work guys!

I have been having a few issues with large files.... I have to edit large files some times, a PHP file that has approx 5395 lines and another JS file with approx 9672 lines.... ;) 

I currently have a custom theme in use (my own razor-atom-syntax-theme) and have a lot of other packages installed... linters, save-session, file-icons, highlight-selected, lesscompile, color-picker, minimap, open-recent.....

I seem to be getting really sluggish performance on these files, with the UI refresh update taking a good second or two on every key press.... The laptop is more than capable, new, plenty of ram, SSD so it is defo not the laptop as sublime is fine.

I just wondered what large file size support is like in Atom? What sizes should we be good for?

turning the linters off most certainly helps but still has a slight lag, any thoughts?

thanks

Paul

**Comment by izuzak** [comment]
@smiffy6969 Thanks for the feedback. There's already an issue which discusses large files and such slowdown, so I'm going to close this in favor of that issue (best to have all feedback in one place so that it's not lost of forgotten). If you'd like to leave more feedback or ask more questions -- please feel free to do so there: https://github.com/atom/atom/issues/307

Also, I'm not sure if there's a clear answer for your question "What sizes should we be good for?". It kind of depends on what you consider sluggish and which packages you use. Personally, I don't even observe some slowness which other users looking at the same screen do, and as you noticed -- installing lots of packages will slow things down. Improving large file support is on the [roadmap](https://github.com/atom/atom/issues/3684), and something we'd love to do.
