### ISSUE TITLE
typing `atom .` opens the directory twice in the file explorer pane

### ISSUE THREAD

**Issue by corsen2000** [atom/atom#5826]
When I type `atom .` from the terminal the directory is seen twice in the file explorer on the left.

This only started happening recently and I am not sure what caused it.

Platform: windows
Version: 0.182.0

How can I help debug this further?

Thank you.

**Comment by thomasjo** [comment]
A few bugs relating to multiple root folders have been fixed since v0.182.0. Please upgrade to the latest version and let us know if the problem persists. Be sure to check in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode) as well, after upgrading.

**Comment by corsen2000** [comment]
Issue exist in safe mode as well.  

I'm not sure why I am on an old version.  Atom does not seem to be auto updating past 0.182.0.

**Comment by corsen2000** [comment]
To clarify, it actually tells me 0.182.0 is the latest version.

**Comment by corsen2000** [comment]
I re-installed Atom which updated me to the latest version and resolved my issue.
