### ISSUE TITLE
Error compiling Less stylesheet (font-awesome)

### ISSUE THREAD

**Issue by LiquidFlame** [atom/atom#5864]
Hello,

I just downloaded the latest Windows release (v0.186.0) and when I tried installing Linter, I get an error saying that it couldn't find '../node_modules/font-awesome/less/variables.less'   Does this font automatically come with Atom still?

**Comment by kevinsawicki** [comment]
> Does this font automatically come with Atom still? 

I don't think Atom ever shipped this font.

**Comment by LiquidFlame** [comment]
So would this be a Linter issue?

**Comment by kevinsawicki** [comment]
I'm not 100% sure, was there more to the error like a stack trace?

**Comment by LiquidFlame** [comment]
I just figured out part of my problem.  I'm trying to install Linter manually, by unzipping the file into my `...\Users\...\.atom\packages`  Our company has pretty strict security regulations, and I was just able to get them to approve the downloaded for Atom and Linter, but we have to download everything through OLEX, which points us straight to the zip file.  I'm guessing that doing the regular `apm install linter` installs the `font-awesome`  So my question is how do I install Linter manually from the zip?

**Comment by izuzak** [comment]
> So my question is how do I install Linter manually from the zip?

I'm not sure there's a general solution to this, so for specific cases you'd need to look into it yourself -- figure out what Linter's installation script does and replicate that behavior (you might also consider asking on Linter's issue tracker). The reason it might not be possible to write a general solution is that the install script might not just download and extract files -- it might be a lot more complex: it might run some other scripts on your system and set up processes by downloading something at run time from the web. 

Since this doesn't seem to be a problem in Atom, I'm going to close this out. Let me know if I misunderstood anything, though. :v:
