### ISSUE TITLE
autoIndentOnPaste should allow pasting white space

### ISSUE THREAD

**Issue by thedug** [atom/atom#5891]
I enjoy the autoIndentOnPaste feature but when I'm working on a markdown file I sometimes want to paste whitespace.

It would be nice if this feature would exclude any "pastes" that contain only whitespace.

**Comment by krngrvr09** [comment]
Hello. I have been wanting to contribute to open source for quite some time now. I would like to start now and I would like to contribute to atom.
This enhancement issue seems doable, so can I try my hand at this?

I'll keep you guys updated about the progress.

Thank you.

**Comment by krngrvr09** [comment]
I am building atom from source, so that I can change the source code and build it again to preview them. Is this the correct way?

**Comment by krngrvr09** [comment]
Hi @thedug just to confirm, you mean that this string -> "                                       ", when pasted in atom, must be excluded by the AutoIndentOnPaste feature. Am I right?

**Comment by thedug** [comment]
That is my thought. I was trying to copy/paste white space to but the white space was removed

**Comment by lee-dohm** [comment]
I see this as a bug, not an enhancement. I am able to reproduce this using Atom v1.4.3 on Mac OS X 10.11.3. Here's what I did:

1. Launch Atom
1. Go into the [whitespace package](https://atom.io/packages/whitespace) settings and disable "Remove Trailing Whitespace"
1. Open a new file using <kbd>Cmd+N</kbd>
1. Press <kbd>Space</kbd> ten times
1. Highlight the ten spaces using <kbd>Shift+Cmd+Left</kbd>
1. Copy the ten spaces to the clipboard using <kbd>Cmd+C</kbd>
1. Paste the ten spaces eight times using <kbd>Cmd+V</kbd> eight times
1. Press <kbd>Enter</kbd> (since "Remove Trailing Whitespace" is off, you should now have two lines with 80 space characters)
1. Press <kbd>Enter</kbd> again
1. Highlight to the beginning of the third line using <kbd>Shift+Cmd+Left</kbd>
1. Delete the third line of spaces using <kbd>Backspace</kbd>
1. Highlight to the beginning of the file using <kbd>Shift+Cmd+Up</kbd>
1. Copy the two lines of 80 space characters to the clipboard using <kbd>Cmd+C</kbd>
1. Delete the two lines of 80 space characters by pressing <kbd>Backspace</kbd>
1. Paste the two lines of 80 space characters by pressing <kbd>Cmd+V</kbd>

**Expected:** Two lines of 80 space characters to be inserted
**Actual:** Two lines with no contents at all are inserted

Disabling the "Auto Indent On Paste" setting allows the two lines of 80 space characters to be pasted as expected.
