### ISSUE TITLE
Implementing download accelerator into update functionality of Atom

### ISSUE THREAD

**Issue by duytrung** [atom/atom#5896]
Hi,

I'm just wonder anyway to implement a multi-threading download accelerator alike wget into update functionality of Atom editor. This will make the update process take less time to download rather than traditional update. Whenever I update Atom, I feel like it never complete.

Conclusion: A functionality that allows Atom to update itself including major and plugins with:
1. secure https download accelerator + 
2. integrity check (md5, sha512 hash).

How do you think about this?
Thanks for consideration.

**Comment by paulcbetts** [comment]
We already do an integrity check on the update, and I don't think downloading is the longest part of the update process. The most time consuming part of the Atom update process is reconstituting and applying the packages because there are so many small files (>11k files). This will improve considerably once Atom moves to ASAR and updates will be *much* faster (almost an order of magnitude)

**Comment by mehcode** [comment]
For reference, this amazing improvement is being tracked in #5382

**Comment by damieng** [comment]
That PR has now been merged and should provide a faster update experience. Closing here.
