### ISSUE TITLE
cannot disable packages in safe mode

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#5987]
I can't load atom in anything but safe mode presumably because of a bad package.  Unfortunately I can't use package-cop because it doesn't work in safe mode.

I went to the settings page to disable packages.  There were two problems ...

1) When I scroll down, go into settings for a package, I can't go back, can I?.  I have to click on packages again and start at the top.  This is a serious problem when you have 100 packages.

2) All enabled packages show the `Install` button which makes no sense.  And since there  is no `Settings` button I can't disable anything.

I'll use the command-line but that is a lot of typing. The above problems need fixing.

windows 8.1
atom 187

**Comment by mark-hahn** [comment]
Weird.  I don't see any disable command in `apm --help`.  

I guess I'll move packages out of the folder but this skit is getting silly.

**Comment by izuzak** [comment]
@mark-hahn I agree that some of those things could be improved, thanks for pointing them out. In the meantime, you should be able to disable packages by editing your config.cson file, even in safe mode. 

https://atom.io/docs/latest/using-atom-basic-customization#configuration-key-reference

Example from my own config.cson file:

```
"*":
  core:
    disabledPackages: [
      "the-closer"
    ]
```

Does that help? Also, I think this issue should be opened on the settings view package, would you mind moving it over there? (Minus the apm-related things -- I believe that's working as expected since enabling/disabling packages isn't an apm concept, it's an Atom concept.)

**Comment by forivall** [comment]
I had this same issue where my config file got wiped out when my disk got full (runaway log file, related to #3158 ).

**Comment by bronson** [comment]
FWIW, apm's missing disable command is being tracked in https://github.com/atom/apm/issues/358.

**Comment by mnquintana** [comment]
Addressed by https://github.com/atom/apm/pull/400
