### ISSUE TITLE
Ctrl+Shift+Up should be the same as Shift+Up

### ISSUE THREAD

**Issue by Siecje** [atom/atom#6045]
If I am highlighting a words and then decide to highlight items on the line above I should be able to hold Ctrl.

**Comment by izuzak** [comment]
Which OS are you using, @Siecje? `ctrl-shift-up` on OSX adds a new selection above the current selection:

https://github.com/atom/atom/blob/2efee4a1a79657d3cebbcf4f927f703d226d4677/keymaps/darwin.cson#L158

So, using that keybinding for something else is not an option.

**Comment by Siecje** [comment]
On Linux and Windows Ctrl+Shift+Up does not highlight anything. It does the same thing as pressing up. This applies to Ctrl+Shift+Down

**Comment by izuzak** [comment]
Thanks for clarifying, @Siecje, seems like these keybindings are responsible for that behavior: [Linux](https://github.com/atom/atom/blob/2efee4a1a79657d3cebbcf4f927f703d226d4677/keymaps/linux.cson#L54-L55), [Windows](https://github.com/atom/atom/blob/2efee4a1a79657d3cebbcf4f927f703d226d4677/keymaps/win32.cson#L58-L59). It should be possible to change those to use `core:select-up` and `core:select-down`, but just wondering (since I haven't used Linux or Windows in a while) -- is it common that `ctrl-shift-up` does the same thing as `shift-up` on Linux/Windows (e.g. in other editors)? 

In the meantime, you should be able to override those keybindings locally:

https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings
https://atom.io/docs/latest/behind-atom-keymaps-in-depth

**Comment by mnquintana** [comment]
@Siecje Is there another editor on Windows that has this behavior? From doing just some cursory research, I found that Brackets moves the current line up / down with <kbd>Ctrl+Shift+Up/Down</kbd> and Sublime moves everything to the right of the cursor up / down by one line with <kbd>Ctrl+Shift+Up/Down<kbd> on Windows.

**Comment by J4G-** [comment]
I would like this behavior added as well. Shift-up is too useful for me in regards to selection, so I've always had it bound to ctrl-shift-up.

**Comment by mnquintana** [comment]
I'm still a little unclear on this – could anyone post a screencap of the behavior we're talking about?

I still haven't found an IDE on Windows that does this out of the box, but I might be missing something.

**Comment by J4G-** [comment]
http://stackoverflow.com/questions/16411714/sublime-text-swap-line-keyboard-shortcuts
Default in Sublime.

**Comment by Siecje** [comment]
@J4G- Unfortunately (for what I want) that is different than Ctrl+Up.

When I am using Shift+Ctrl+Arrows to select text and then I decide to select the line and parts on the previous line I press Up.

I guess I need to add a custom binding for it or learn to release the Ctrl key.
