### ISSUE TITLE
Selection > Split into Lines positions cursor incorrectly when  soft wrap is enabled

### ISSUE THREAD

**Issue by exalted** [atom/atom#6059]
Hi,

with "Soft Wrap" setting enabled (but not "Soft Wrap At Preferred Line Length" necessarily), when you select multiple lines and do `Selection > Split into Lines`, I was expecting that my cursor would position on the first (and actually the only hard line) line, but instead the cursor is positioned on the last soft line. (`Cmd-left` on Mac.)

Here's a quick screencast: http://quick.as/25JqhgorV

I think this is a bug.

Am I missing something?

Thanks.

**Comment by as-cii** [comment]
Hi @exalted, thank you for reporting this issue (and for mentioning me :sweat_smile:).

I am not sure, however, we can consider it a bug since it's not related to how selection works. In facts, when you're on a soft-wrapped line, hitting <kbd>Cmd</kbd><kbd>←</kbd> will position the cursor at the beginning of the soft-wrapped line (not the, so to speak, physical line).

Sublime Text behaves the same way and I am quite confident this is the behavior want as well.

![soft-wrapping-selection](https://cloud.githubusercontent.com/assets/482957/6769451/b58f5f30-d09c-11e4-802c-a0e1221a8b16.gif)

Closing this for now :rainbow

**Comment by exalted** [comment]
Weird, I would argue that both Sublime and Atom got it wrong then :wink: 

Do you have any idea how would you move to the beginning of the hard line then?

**Comment by izuzak** [comment]
> Do you have any idea how would you move to the beginning of the hard line then?

Have you tried pressing just `left` and not `cmd-left`, after executing Split selections into lines? That works for me.

**Comment by izuzak** [comment]
You could also execute "Editor: move to beginning of line" from the command palette (or bind that command to a keystroke and hit that).

**Comment by exalted** [comment]
@izuzak both solutions work like :sparkles: . Thanks both of you guys!
