### ISSUE TITLE
Wrong conversion from screen to pixels and screen to buffer with soft wrap enabled

### ISSUE THREAD

**Issue by abe33** [atom/atom#6063]
A screenshot is more telling so let's start here: 

![color-marker-element-spec_coffee_-__users_cedric_github_pigments_-_atom](https://cloud.githubusercontent.com/assets/247140/6770695/4f9e5164-d0c8-11e4-9e85-529dfcfa7c04.png)

This is the only wrapped line of the file. As you can see, when querying the pixel position for the first column of the first line after the text wrap, the pixel position is still the one of the last char of the line above. This is true for every columns of the hanging indent (see the screenshot below). I guess the issue comes from the handling of the hanging indent, but the result shouldn't be a position at the end of the line above anyway.

![color-marker-element-spec_coffee_-__users_cedric_github_pigments_-_atom](https://cloud.githubusercontent.com/assets/247140/6770769/35679794-d0cb-11e4-912b-95831c192dff.png)

But, it's not the only problem, converting position from the screen to the buffer space coordinates gives also weird result:

![color-marker-element-spec_coffee_-__users_cedric_github_pigments_-_atom](https://cloud.githubusercontent.com/assets/247140/6770718/7bc4199e-d0c9-11e4-8741-6554240be401.png)

As you can see, here the converted buffer range starts one character before what's the editor element displays.

Config: 

Atom Version 0.188.0-f42a62d
OSX 10.10.3

**Comment by as-cii** [comment]
Thank you for the detailed report issue, @abe33: it's really clear and helpful :+1: 

> This is the only wrapped line of the file. As you can see, when querying the pixel position for the first column of the first line after the text wrap, the pixel position is still the one of the last char of the line above. This is true for every columns of the hanging indent (see the screenshot below). I guess the issue comes from the handling of the hanging indent, but the result shouldn't be a position at the end of the line above anyway.

This behavior isn't related specifically to hanging indent, but rather to the whole soft wrapping feature. When `DisplayBuffer#clipScreenPosition` gets called without any option, it will assume, by default, that you don't want to `skipSoftWrapIndentationToken` and, therefore, clips the passed position to the end of the previous row.

If I think about it, however, I'd say this is consistent with the other display buffer features. If, for example, you pass an invalid position, such as `[0, Infinity]` it will automatically clip to the end of the line, rather than going to the next one. The default is to always clip backwards, as far as I know.

I agree, however, that we may allow developers to pass in how they want clipping to occur when calling `pixelPositionForScreenPosition`. Namely, I am referring to introduce these options:

```coffee
{ wrapBeyondNewlines, wrapAtSoftNewlines, skipSoftWrapIndentation }
```

> But, it's not the only problem, converting position from the screen to the buffer space coordinates gives also weird result.

I see what you're pointing out there. Could you attach here the specific file you're mentioning, please?

**Comment by abe33** [comment]
> Could you attach here the specific file you're mentioning, please?

Sure, this is the aforementioned file: https://github.com/abe33/atom-pigments/blob/master/spec/color-marker-element-spec.coffee#L128 (This is a WIP rewrite of `atom-color-highlight` and `project-palette-provider` to merge both packages in one and improve the overall performances)

FWIW, the origin of the problem is that I need to render a marker as one or several regions, but I also need to attach the text of the marker for each of the regions to display the text of a color with enough contrast. As highlight decorations doesn't allow for extra attribute or content I can't use them. 
I also want to prevent the region to fill the remaining editor space when spanning several lines as decorations normally do. Colors decorations could be too distracting if they were behaving like normal decorations.

Here's the code that is responsible to creates the regions: https://github.com/abe33/atom-pigments/blob/master/lib/renderers/region-renderer.coffee

As you can see on lines 67-68 and line 79, if I want to retrieve the real text content for a region I have to apply an offset to the buffer range depending on whether the following screen line is soft wrapped or not and whether the current region screen range end with `Infinity`. This is only needed because of the second point mentioned in the issue.
