### ISSUE TITLE
 No option to show the menu when disabled.

### ISSUE THREAD

**Issue by kwrnel** [atom/atom#6079]
When I turn off the menu has no option to reactive it.

Used solution: rm -rf ~ / .atom / config.cson

**Comment by 50Wliu** [comment]
Have you tried pressing the `Alt` key?

**Comment by kwrnel** [comment]
Thank you! I have not read the manual because I am out of time.

**Comment by 50Wliu** [comment]
All right, I'm going to close this for now.  If you still can't get the menu to reappear feel free to comment.

**Comment by mark-hahn** [comment]
FWIW, in ubuntu unity, when I put atom in full-screen mode there is no way
to see the menu.  The alt key does nothing.  I have to take atom out of
full-screen and then the menu is visible again.

Note that the menu is at the top of the unity screen, just like the mac.
It is not connected to the Atom window.  I don't use a mac.  Does it have
the same problem when Atom is made full-screen?

Maybe this is the expected behavior but it is a pita.

ubuntu 12.04
unity
chromeos using crouton
atom 187
