### ISSUE TITLE
Warn before quitting

### ISSUE THREAD

**Issue by eddiemonge** [atom/atom#6082]
It'd be nice to have an option to warn before quitting when hitting Cmd+Q as its too easy to close all your editors when trying to close a single tab. Chrome has this option and its a time saver.

**Comment by mnquintana** [comment]
:+1:

Personally, I'd love if we could adopt Chrome's approach too – pressing <kbd>Cmd+Q</kbd> pops up a message telling you to hold <kbd>Cmd+Q</kbd> to quit, and holding down <kbd>Cmd+Q</kbd> for some amount of time actually quits. (ie. instead of a dialog box asking you to confirm your quit, which I've always found too obtrusive)

**Comment by stevus** [comment]
+1 all day

**Comment by ismay** [comment]
There is some interesting discussion on this here: https://discuss.atom.io/t/quit-confirmation/5572. One of the suggestions was to just make sure work can't be lost (by saving unsaved changes somehow), and to require the user to press `[command] + [q]` twice in order to quit. I personally agree with both these recommendations, and would love to see this implemented (as I tend to fat-finger closing a tab and accidentally close atom all the time).

**Comment by chrishough** [comment]
+!

**Comment by ThinkGraphical** [comment]
Another option is adding the following to your keymap.cson (Atom -> Open your keymap)
```
'body':
    'cmd-q': 'core:save'
    'cmd-q cmd-q': 'application:quit'
```

**Comment by stevus** [comment]
@ThinkGraphical So does this basically require two `Cmd-Q` keypresses?

**Comment by ThinkGraphical** [comment]
@stevus Yes correct. This overwrites the basic behaviour for 'cmd-q' to save the current file. Because an action is required (empty string doesn't work) I chose this because it seemed like a safe option.
And it now requires 2 'cmd-q' keypresses to quit Atom.

**Comment by chrishough** [comment]
This works perfectly!

**Comment by mjswensen** [comment]
+1ing this while I wait for Atom to start up again

Definitely going to try out @ThinkGraphical 's solution (thank you!!!)

**Comment by adrianoresende** [comment]
My atom quit acidental but not is save >:(
All need this feature.

**Comment by jesperronn** [comment]
The workaround from @ThinkGraphical  is nice. Much better than default behaviour. https://github.com/atom/atom/issues/6082#issuecomment-196381781


However, default behaviour should change in order to prevent new users from being bitten by the quit. Google Chrome behaviuor would be the gold-plated nirvana. The workaround here is accessible. But still, it's not default for all.

Who can make a pull request that changes default behaviour?

**Comment by zhang-z** [comment]
It happened to me so many times that I hit Cmd+Q when I wanted to Cmd+A

**Comment by artdiniz** [comment]
@ThinkGraphical workaround is pretty nice! But other thing that bothers me is when I am closing tabs in a hurry and press Cmd+W one time more than necessary. That closes Atom window and is almost a quit. Many times doing that and I decided to make [a package named "quit-control"](https://atom.io/packages/quit-control) that solved all those problems related here, at least for me.

Maybe its UI can be a reference for a future default implementation by Atom.

**Comment by mnquintana** [comment]
@artdiniz You can change that window close behavior by disabling `Close Empty Windows` under Core settings, so that way the window won't close if you accidentally hit <kbd>Cmd-W</kbd> too many times.

**Comment by artdiniz** [comment]
@mnquintana I used to turn off "Close Empty Windows" option, but the funny part is that I missed closing empty windows on `Cmd+W`. That is the default  beahvior of many apps, including Atom.

I know that sounds like I don't know what I really want from Atom hahaha But as a UX enthusiast I tried to solve these problem. 

I looked to some browser extensions that does that and first implemented a Time/Debounce based approach. That didn't work for many reasons. So I looked forwards to maybs-quit package and tried a confirm based approach. After some tweaking and testing I found out that it really worked in both `Cmd+Q` and `Cmd+W` cases:

If I'm closing tabs in a hurry and hit `Cmd+W` too many times, I just need to hit `Esc` and keep going.

If I really want to close the empty window I can hit `Cmd+W` and press `Return`. Window is closed.

If I mistype `Cmd+Q` I just need to hit `Esc` and keep going.

If I really want to quit I can hit `Cmd+Q` and press `Return`. Atom quits.

Those simple key combinations doesn't added any perceivable time to the actions and enhanced my perception of control over Atom.

If my problem happens not to be a problem for most of Atom users it really makes sense tho solve it in a [package](https://atom.io/packages/quit-control). But since I saw many people raise up this issue over time, I think an Atom default implementation would be welcome.

**Comment by nathanbuchar** [comment]
This has been bugging me too and liked @ThinkGraphical's solution, so I turned it into a package. It's my first ever Atom package, so I hope it's not written too poorly.

![screenshot](https://cloud.githubusercontent.com/assets/1815367/24824415/6c0396fe-1bbf-11e7-9e23-626e8eb1a89d.png)

Take a look :)!  https://atom.io/packages/warn-before-quitting

**Comment by chrishough** [comment]
I have not tried both plugins from @nathanbuchar and @artdiniz.  To note the package that @artdiniz mentioned also closes all of the window panes in atom when quitting.  I regularly keep windows open in many panes so this was a huge net loss, even though I liked having more control via the UI.  After uninstalling it and installing @nathanbuchar packaged, I ran the same tests.  Only @nathanbuchar retains all of the window panes.

**Comment by MoiCJarod** [comment]
Thanks nathanbuchar, on my AZERTY keyboard, Q key is so near of S key that I very often quit with saving ... Your extension is so cool :-)

**Comment by nirabhratapaswi** [comment]
Is this issue solved? Or can I try it out? @eddiemonge 
Does the pull request from @nathanbuchar include "ctrl+w" to pop up warning before closing? If no then can I work on that?

**Comment by nathanbuchar** [comment]
@nirabhratapaswi It's not a PR but rather a separate package. Would love if it could be integrated into atom core though :-)

Mine does not warn about closing a window when pressing ctrl+w. If you'd like to re-open a recently-closed tab you can press ctrl+shift+t, or if you don't like that the whole window closes when the only tab is closed you uncheck the "Close Empty Windows" option in your Atom settings

**Comment by nirabhratapaswi** [comment]
@nathanbuchar , I really never made an atom package, but I located where to make changes for inntegrating the feature to core. Can you help me with how you displayed the text warning popup saying Press cmd+Q again to quit, or press esc to exit

**Comment by nathanbuchar** [comment]
@nirabhratapaswi, I'm not sure how much help I'll be able to give, but here's the core logic of the package:

https://github.com/nathanbuchar/atom-warn-before-quitting/tree/master/lib

**Comment by amlcreative** [comment]
Here is what I mapped and it works well. For all of my important dev apps I use cmd-opt-q to quit. On a Mac, normally you can just go to System Preferences > Keyboard > Shortcuts and add the custom keyboard commands there. But Atom is special. Also, the Option key on a Mac is equivalent to the Alt key on Windows. Since Atom only uses alt in the keymap, you have to use that instead of opt -- but it's the same key function.

`'atom-text-editor':
      'cmd-alt-q': 'application:quit'
      'cmd-q': '//nothing'`

Hope this helps someone.
