### ISSUE TITLE
Clicking on package names in the Settings > Install UI often doesn't do anything

### ISSUE THREAD

**Issue by mcandre** [atom/atom#6094]
Especially when the package has not been installed

**Comment by thomasjo** [comment]
Clicking on a package name opens the package's page on [atom.io](https://atom.io). It always works for me, and I'm reasonably sure we have automated tests for the behavior. If you reproduce the behavior in [safe mode](https://atom.io/docs/v0.188.0/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode), re-open it on the [settings-view package](https://github.com/atom/settings-view/) since that's where this functionality lives.
