### ISSUE TITLE
Editor does not autoscroll to undo location

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#6110]
* Open `package.json` from atom/atom in Atom
* Type an `a` on the first line
* Scroll to the botom
* Undo

Editor is still scrolled to the bottom instead of to the top where the edit was just undone.

**Comment by kevinsawicki** [comment]
:green_heart:

**Comment by kevinsawicki** [comment]
I'm seeing this happen again on master

**Comment by kevinsawicki** [comment]
Actually issue is different now and is cursor position related, not scrolling related.

**Comment by kfranqueiro** [comment]
Since Atom auto-updated me to 190, I have noticed numerous times that when I undo, Atom scrolls to a seemingly arbitrary location having absolutely nothing to do with what was undone (it may not have actually needed to scroll at all).  I'm not sure whether this is a regression related to this, but it makes undo completely unwieldy.  (Should I report this separately?)

**Comment by kevinsawicki** [comment]
> Should I report this separately?

I think that would be best, thanks.

**Comment by wwoods** [comment]
Can we get a link to the new issue in this one?  I also am getting undo -> arbitrary scroll location, which is really frustrating.  This is the first relevant bug I found, so the other one must not be as searchable.  Thanks!

**Comment by MentalGear** [comment]
This issue is back again as of 2.0.8
