### ISSUE TITLE
publish Atom Editor as a Chrome App in the Chrome Web Store

### ISSUE THREAD

**Issue by triune** [atom/atom#6189]
Should be a simple re-packaging as the app is already natively html, no?

**Comment by thomasjo** [comment]
Atom is built on Chromium and io.js, but is not a "native" web app, so this will most likely never happen.

**Comment by triune** [comment]
Most likely will never use it since it doesn't run on ChromeOS, sad :(

**Comment by mark-hahn** [comment]
> Most likely will never use it since it doesn't run on ChromeOS, sad :(

But it runs great on a chromebook.  I use atom, crosh shells, and the
browser, each in their own chromeos window.  I've heard rumors it doesn't
work as well with an arm as it does with an x86, but people do use it on
arm.

**Comment by triune** [comment]
Could you explain how to get atom going on a ChromeOS machine that is not in dev mode?

**Comment by mark-hahn** [comment]
You have to be in dev mode of course.  It takes just a minute and dev mode
doesn't affect any normal operation of the chromebook.  Dev mode just
removes physical security on the OS.

The cool thing about crouton is that it just adds X11 to the existing linux
kernel.  There is no VM or dual-boot.  Linux gui apps from run in chromeos
windows, including Atom.

I'd be happy to help anyone set it up.  It is unofficially supported by
Google.  There is a strong community.

See https://github.com/dnschneid/crouton/wiki/Community-Links.

**Comment by triune** [comment]
I travel a lot and prefer to have all my data on my Pixel encrypted (no dev mode for me). I also have 4 Linux and OSX machines I can remote desktop into, so there is no need for me to put Linux / crouton on my Pixel either. I'd just prefer to find something better than Super Neutron Drive (which has a Chrome App) to use as an editor. I am of the thinking that with software, anything is possible, so getting Atom to run on ChromeOS as either a ported Android app, or a native ChromeOS app must be possible.

**Comment by mark-hahn** [comment]
> I travel a lot and prefer to have all my data on my Pixel encrypted

That is a fully-supported crouton option.  I'm not sure what kind of
experience it is.  I would assume you just have to put in the password on
every login.

> I also have 4 Linux and OSX machines I can remote desktop into,

That is exactly what I've done for years.  I am much happier running
locally.

> I am of the thinking that with software, anything is possible,

That is news to me.  (grin).  Atom includes Node which requires full access
to the OS file system.  There is no way that could run in a web browser and
that is what you are asking for.

For years I've looked into running different programming editors on the web
and was disappointed in all 4 or 5 I tried.  I've ended up with what I
wanted but I never expected it to be a linux laptop like my Chromebook
Pixel (awesome, right?).

Linus Torvaldis said that Linux finally arrived when it appeared in the
pixel (paraphrasing).  He uses one for all his work.

Sorry to talk your ear off.  This just happens to be something I'm excited
about since my wife let me pop for the new pixel a week ago.

**Comment by triune** [comment]
Running any Chromebook in standard mode, all user data partitions are encrypted via ecryptfs. Once you flip the dev-switch, all that encryption disappears. 

I do stand by my claim that anything is possible in software... two ideas come to mind: 

1) using ARC ~ App Runtime for Chrome
2) Using Native Client

**Comment by justinfagnani** [comment]
It would be really great if the node APIs could be abstracted enough so that core Atom and most extensions wouldn't need to use them directly and APIs like the filesystem could be implemented for ChromeOS.

I know quite a number of Chromebook users who would jump at ability to use Atom.

**Comment by mark-hahn** [comment]
Atom works quite nicely in the chromebook now.  See
https://discuss.atom.io/t/atom-on-chromebook-was-lets-talk-chromeos-resolved/8644/34

**Comment by justinfagnani** [comment]
That's cool, but not everyone wants to, or is allowed to, run developer mode and install Crouton.

**Comment by drcmda** [comment]
Brackets, also based on Node, has been ported to Chromebooks. Node can be emulated and the Chrome API has access to the filesystem. Googles Dev Editor also accesses the file system. I think ChromeOS is pretty close to Atoms original ideals and shouldn't be ignored because it's web-based. I wonder how this wasn't even thought of in the very beginning as these two are literally a match for one another.

Also, Crouton, as nice as it is, has drawbacks that are simply swept under the rug in such discussions. Hows Crouton doing once someone opens up the laptop and presses a random key at startup. Hows Crouton after ChromeOS updates that have kernel changes in them, etc. Not to mention that some of us really dig the minimal OS as it is and just wish there'd be a more convenient way to code.

**Comment by paulcbetts** [comment]
> Brackets, also based on Node, has been ported to Chromebooks. Node can be emulated and the Chrome API has access to the filesystem. Googles Dev Editor also accesses the file system. I think ChromeOS is pretty close to Atoms original ideals and shouldn't be ignored because it's web-based. I wonder how this wasn't even thought of in the very beginning as these two are literally a match for one another.

I don't think anyone's opposed to getting it running on ChromeOS from a moral perspective, it just seems quite Technically Challenging, given that Atom's value proposition is deeply tied to node integration vil Plugins, that would be Hard™ to stub out.

**Comment by justinfagnani** [comment]
Yes, it would be hard to get all packages converted to run in ChromeOS, but given the right APIs to abstract over filesystems and other APIs that node and ChromeOS provide, packages could migrate on their own if they want to be ChromeOS compatible.

This kind of abstraction could eventually make it possible to run Atom as a hosted site, competing with or integrated with IDEs like Cloud 9. I bet github.com could even make use of it for online editing :)

**Comment by 1340641314** [comment]
go

**Comment by rkhayat** [comment]
I have been using a Chromebook Pixel LS 2015 running crouton for development but Atom / Sublime seem to be extremely slow when switching between files 'ctrl+p'. I would love to see it as a native ChromeOS app.

**Comment by Thesola10** [comment]
found https://github.com/substack/node-browserify this. Could be helpful for porting

**Comment by ha1dfo** [comment]
So, the biggest blocker of running atom as a chrome app is its need for "unrestricted" access to the filesystem.
However, I believe in 2018 many of the developers are already editing source files remotely (whether it is JavaScript, C++, Python, etc) to take advantage of server CPU power to build, run their programs, and also to minimize risk of data loss.
Since access to on-demand servers are easier than ever (think about free micro instances in GCP), running node.js remotely becomes an easily accessible option thus exploring this angle may become a very attractive feature to many.
