### ISSUE TITLE
Sync update of overlay decorations with editor's DOM update/read lifecycle

### ISSUE THREAD

**Issue by benogle** [atom/atom#6196]
The overlay decoration updates happen out of phase with the editor update/read cycle. See this gif:

![autocomplete-recompute-bad](https://cloud.githubusercontent.com/assets/69169/6933057/114d2514-d7d7-11e4-85b2-3083c4c639b3.gif)

Note how the shorter autocomplete list sticks around for a second in the old position before it is remeasured and re-rendered. What's happening is this:

1. type char
1. editor renders
1. the autocomplete suggestion list updates 
1. `pollDOM` picks up the size change, and re-renders :hankey: 

If we can update the autocomplete list in the editor's update cycle, the new size is read immediately, and we get a smoother render:

![autocomplete-recompute-better](https://cloud.githubusercontent.com/assets/69169/6933058/1730b00e-d7d7-11e4-9d22-bc39226fe03a.gif)

I've hacked this in like so. In the `text-editor-component`

```coffee
requestUpdate: =>
    atom.views.updateDocument =>
      @editor.horribleUpdateMethod?()
      @editor.horribleUpdateMethod = null
      @updateSync()
    atom.views.readDocument(@readAfterUpdateSync)
```

In autocomplete suggestion list element

```coffee
itemsChanged: ->
  atom.workspace.getActiveTextEditor()?.horribleUpdateMethod = =>
    @renderItems()
```

### How even?

Of course, the hack is not ideal, but how would folks feel about some mechanism to allow for synchronizing the editor render with something external?

I like the `atom.views.updateDocument()` method, but I am not guaranteed to get in the same cycle as the editor. Could we provide another method? `editor.onWillUpdateDocument()`? I know we used to have an event similar to this, and it wasnt great as package authors were abusing it.

cc @nathansobo @as-cii

**Comment by as-cii** [comment]
> Of course, the hack is not ideal, but how would folks feel about some mechanism to allow for synchronizing the editor render with something external?
> 
> I like the atom.views.updateDocument() method, but I am not guaranteed to get in the same cycle as the editor. Could we provide another method? editor.onWillUpdateDocument()? I know we used to have an event similar to this, and it wasnt great as package authors were abusing it.

@benogle: this is definitely my biggest concern: our rendering core shouldn't be affected by factors which we do not control (read: that we cannot optimize). Allowing updates in the same animation frame where the editor actually needs to render something may go out of hand very quickly, since we've a very short timeframe there. That said, I totally understand this requirement and if we manage to understand how to make it work, it'd be really awesome. :fire:

My current understanding of the problem makes me think that we *could* be able to deliver such mechanism (i.e. `onWillUpdateDocument`) on a best-effort basis. What I mean is that we may put some constraints around these packages updates. For instance, we may say that when the editor takes less than `x ms` to render (where we should choose `x` in order to get smooth animations) we will call that function, otherwise it will have to wait for polling as it's doing right now. We may even take this further by measuring how long the external rendering usually takes and decide accordingly how and when to schedule it. For performance-critical operations (e.g. scrolling) we could even say that it will *never* be in sync with the editor.

Rendering aside, it is also true that right now there are a whole bunch of other external factors that could slow down Atom significantly (e.g. an event handler in a package that takes 200ms). If we say we want to introduce such scheduling mechanism for rendering operations, should we use something similar for other external elements as well? Probably we could simply write guidelines in our documentation, but I am not sure how much that could help.

I definitely want to take this discussion further, so thanks @benogle for bringing this up :bow: 

@nathansobo: you have much more experience than me in this field. What are your thoughts on this? :bulb:

**Comment by nathansobo** [comment]
> I like the atom.views.updateDocument() method, but I am not guaranteed to get in the same cycle as the editor.

Have you tried this approach? So long as the editor update hasn't started yet you will end up getting grouped with the editor's update. I introduced `atom.views.updateDocument` in anticipation of just this sort of issue.

There will still be a 1 frame delay before reacting to the consequences of the overlay measurement, but this seems fine compare to waiting multiple milliseconds to poll the DOM to perform the measurement in the first place. If this 1-frame delay is an issue, we can address it.

**Comment by benogle** [comment]
> Have you tried this approach?

Yeah, it is still often out of the update cycle and picked up by the poll, giving the same jumpy behavior. Less often than without, but still > 50% of the time. I want to be able to guarantee the autocomplete code getting in the same update cycle as the editor.

> If this 1-frame delay is an issue, we can address it.

The 1 frame delay is not an issue. It's really smooth with the `horribleUpdateMethod` approach.
