### ISSUE TITLE
Changing the "Soft Tab" setting wasn't effective on already opened documents.

### ISSUE THREAD

**Issue by ye** [atom/atom#6203]
And I have to close the current document and then reopen it in order to see the tab=>space changes.

```
$ atom --version
0.188.0
```

**Comment by mpdehaan** [comment]
also in 1.0.7.

Perhaps a slightly larger issue, if unrelated - I was noticing that atom was inserting spaces instead of tabs and ignoring the SoftTabs setting I had opened the document with, and tried to "fix" this by toggling the setting, and it was having no effect.

Closing atom, the problem went away and my setting loaded correctly.

So I think there's a scenario where SoftTabs on load doesn't work even if so set.  I haven't pinned down the parameters for reproducibility around this, though the file in question was Python (.py)

First time I've seen this this after about a month of using Atom.
