### ISSUE TITLE
Chinese (and nonlatin) chars become 〄〄〄 in 0.189.0

### ISSUE THREAD

**Issue by chloerei** [atom/atom#6214]
Text:

> 这上面的夜的天空，奇怪而高，我生平没有见过这样奇怪而高的天空。他仿佛要离开人间而去，使人们仰面不再看见。然而现在却非常之蓝，闪闪地睒着几十个星星的眼，冷眼。他的口角上现出微笑，似乎自以为大有深意，而将繁霜洒在我的园里的野花草上。

![3](https://cloud.githubusercontent.com/assets/49931/6959354/a30f8266-d94a-11e4-9167-35ea308a5ad2.png)

It happen after update to 0.189.0, and it's normal in 0.188.0 .

I try disabled all community packages or star with `--safe` mode, still happen.

Update: Ubuntu 14.04

**Comment by lee-dohm** [comment]
I can't replicate this using Atom v0.190.0-7c2b9fa on Mac OS X 10.10.2.

**Comment by 50Wliu** [comment]
Related to/duplicate of #6160.

**Comment by mingjunyang** [comment]
Font Family............

**Comment by izuzak** [comment]
@chloerei Which font are you using? Does this happen with every font? Does this happen randomly or can you reliably reproduce?

**Comment by chloerei** [comment]
@izuzak I set font family empty. When I set one, Chinese display normal. But not setting font family work normal in the previous version.

**Comment by zhangsoledad** [comment]
@izuzak  The problem also happen on my ubuntu14.10 when i updated atom 0.189.0.  I set font family `monaco`, it display normal in the previous version.

**Comment by izuzak** [comment]
Similar problem described in https://github.com/atom/atom/issues/6232

**Comment by izuzak** [comment]
Reported in #6263 and #6264 as well.

**Comment by cakecatz** [comment]
Emoji also.

**Comment by cakecatz** [comment]
FWIW,I was build with atom-shell 0.22.2, and it worked perfectly.

**Comment by gabriel-tessier** [comment]
Is there a temporary fix for this problem or a soon release?
I try to set the font family to monaco as zhangsoledad but it didn't help. 
All the Japanese text is displayed with empty square. I try several font family without success.

FYI The problem appear after upgrading to 0.189.0 
Now I run 0.190.0 the problem is still here.
Kubuntu 14.10

**Comment by zhangsoledad** [comment]
Hmm, you can set two or more font family,like css
![set](http://7fvk4m.com1.z0.glb.clouddn.com/Fn1KJfv_kMUQ5uRHoEE67iMn8f0z)
you can use font family which support your language character

**Comment by chloerei** [comment]
@gabriel-tessier Try `Droid Sans Mono, Droid Sans Fallback`, or replace with other Japanese font.

I think atom still need to fix it.

**Comment by gabriel-tessier** [comment]
@zhangsoledad I already try monaco the Microsoft one didn't try but not sure that it work on linux.
@chloerei Try the Droid font now Japanese display!!
Thanks for your help! :100:

**Comment by Zireael07** [comment]
I'm using Droid Sans Fallback in game deving and it has a lot of CJK characters.

My suggestion would be to make Droid Sans Mono, Droid Sans Fallback the default setting.

**Comment by zcbenz** [comment]
Chrome41 on Linux seems to be using its custom freetype lib.

**Comment by despairblue** [comment]
Installing and setting `Symbola` as second font family fixes at least the emoji support. So using `Your Monospace Font of Choice, Symbola, Droid Sans Fallback` will enable atom to render emojis and chinese characters, at least if you have *Symbola* and the *Droid* fonts installed.

**Comment by TylerTemp** [comment]
@chloerei Thx, `Droid Sans Fallback` works for Chinese chars on Ubuntu 14.10 :-)

**Comment by hz** [comment]
@zcbenz , should we create one issue for Electron to address Chrome custom freetype lib compatibility?

**Comment by arthurtalkgoal** [comment]
Wow, ***Droid Sans Mono, Droid Sans Fallback*** font family works!

Even 細明體 doesn't work before

**Comment by chloerei** [comment]
@arthurtalkgoal It depends what fonts has been install in system, `Droid Sans Mono, Droid Sans Fallback` is default in Ubuntu.

**Comment by hz** [comment]
my styles.less on Ubuntu 15.04

```
* {
  font-family: Droid Sans Mono, Droid Sans Fallback;
  font-size:12px;
}

.tree-view {
}

.editor {
  font-size:14px;
  font-family: Droid Sans Mono, Droid Sans Fallback;
}
.terminal {
  font-size:12px;
  font-family: Droid Sans Mono, Droid Sans Fallback;
}
.markdown-preview {
  h1,h2,h3,h4,h5,h6 {
    font-family: Droid Sans Mono, Droid Sans Fallback;
  }
}
```

**Comment by avdg** [comment]
It would be great to see symbols like 🚀 in atom just fine :-)

**Comment by rumpelsepp** [comment]
The fonts:

```
CamingoCode, Liberation Mono, DejaVu Sans Mono, monospace
```
work for me when using the tasks package.

**Comment by 0atman** [comment]
Can confirm out-of-the-box experience on ubuntu 14.04 atom v1.0.0 can't display unicode (eg Chinese) chars.
Chars like 大大 becomes ▯▯
Changing font-family to `Droid Sans`, as above, fixes it.

**Comment by cjwelborn** [comment]
I'm experiencing this with every font mentioned. I want to use 'DejaVu Sans Mono' (my system default for monospace, and also set in Atom Settings). Every application I've tried displays these characters correctly for `DejaVu Sans Mono` and `UTF-8` encoding except Atom.

This specific string isn't important to any project of mine, I just wanted to make sure Atom could do it. Sadly, it failed.

Atom:
![image](https://cloud.githubusercontent.com/assets/3335984/8491453/6f06ffb6-20fe-11e5-8611-a7c1c6495da2.png)

Sublime Text:
![image](https://cloud.githubusercontent.com/assets/3335984/8491418/de11d396-20fd-11e5-8a73-1c1274b5bf4f.png)

Konsole:
![image](https://cloud.githubusercontent.com/assets/3335984/8491469/d2ad187a-20fe-11e5-9091-6a777b9c485b.png)

All using the same font and encoding...

I've checked the dev tools to make sure that it is actually using the correct font, and it is. I'm not sure where the problem is.

**Comment by chloerei** [comment]
@cjwelborn If you are using kubuntu, setting `DejaVu Sans Mono, Droid Sans Fallback`. System usually have a fallback font to display chars not in specified font, but atom do not work correct.

**Comment by cjwelborn** [comment]
@chloerei I have 'Droid Sans Fallback' installed, but setting Atom's font to `DejaVu Sans Mono, Droid Sans Fallback` does not help. I've tried setting it and then reloading the file, or reloading Atom altogether but still.

Test text:
𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷

I will say that Sublime has problems copying/pasting these characters, and that Konsole selection is weird. I think because they are wide characters. They display them fine though.

Here is some more information on these types of characters: [https://codepoints.net/U+1D51E](https://codepoints.net/U+1D51E)

**Comment by muojp** [comment]
Modifying font family to utilize Droid Sans Fallback solved tofu issues on editor pane, but no effects on preview/toolbar. Might need further CSS hacks (e.g. https://github.com/atom/atom/issues/6214#issuecomment-97629963 )📛📛📛

**Comment by cuihq** [comment]
Setting three fonts and `UTF-8` encoding
> DejaVu Sans Mono, Source Han Sans CN, Android Emoji

Font Family | Support
------------ | -------------
DejaVu Sans Mono | Ruby programming language
Source Han Sans CN | Chinese chars
Android Emoji | Emoji

ATOM(v 1.0.0):
-----------
![dispaly](https://cloud.githubusercontent.com/assets/5662489/8586553/91f2edfe-2622-11e5-986e-c19b269597b3.png)

**Comment by avdg** [comment]
If the font is an issue, I found this https://www.google.com/get/noto/ and https://www.youtube.com/watch?v=AAzvk9HSi84

**Comment by nengxu** [comment]
Same problem happened for Atom 1.0.7 on both Arch Linux 64 bit, and Lubuntu vivid 32 bit. I fixed by using Google Noto fonts on Arch Linux:

  font-family: "Noto Sans", "Noto Sans CJK JP", sans-serif;

On Lubuntu, somehow the fonts-noto package did not cause Atom to recognize Noto fonts. I had to use Droid Sans Mono, Droid Sans Fallback, as other people suggested.

**Comment by 50Wliu** [comment]
I'm going to close this since Atom 1.0.12 (which includes the new Electron version) should have fixed this (see atom/electron#2014).  If that is not the case, please leave a comment!

**Comment by code-tree** [comment]
I'm still getting a problem with Ubuntu Mono.

Font family setting:
* "Ubuntu mono, Dejavu sans mono" -- "á" does not fallback to Dejavu and is instead displayed as "a" with a box on top
* "Dejavu sans mono" -- "á" displays fine

Ubuntu 15.04, Atom 1.0.19

**Comment by code-tree** [comment]
Just realised that the problem is when the accent is a separate character:
* á (`&#225;`) displays fine
* á (`&#97;&#833;`) has the problem described above
