### ISSUE TITLE
Setup CI on Travis and AppVeyor

### ISSUE THREAD

**Issue by as-cii** [atom/atom#6222]
As discussed on Slack, it would be great to make CI available for everyone :heart:

Ideally we should be able to provision a cibuild on both Travis and AppVeyor, so that we can check if specs pass on Windows and *nix environments.

**Comment by mnquintana** [comment]
:+1: Yesssss this would be awesome!

**Comment by thomasjo** [comment]
The free AppVeyor offering is such a slow, unstable product though. I've had to disable it for my projects since it produced so many false negatives. Randomly failed downloading and installing Atom for instance. They really need to improve their stability, or the Atom team needs to work out some sort of deal to get access to AppVeyor's "Pro" infrastructure which is reportedly more stable.

**Comment by paulcbetts** [comment]
@thomasjo It's not :(
