### ISSUE TITLE
editor:cut-to-end-of-line slooow

### ISSUE THREAD

**Issue by dvorka** [atom/atom#6233]
Killing to end of line takes >1 second and makes it difficult to use Atom when pressed multiple times on clean installation w/o any additional packages installed. Surprisingly, *mark & cut line* it is super fast...

```
dvorka@raider:~$ atom --version
0.187.0

dvorka@raider:~$ uname -a
Linux raider 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

dvorka@raider:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

Intel Core i7/16GB RAM/SSD/NVIDIA Quadro K200M
```

**Comment by izuzak** [comment]
@dvorka Strange, it works instantly for me. Can you share the file you are using for testing this and specify which line you're running the command on?

**Comment by dvorka** [comment]
I started to use Atom just recently and as ex-Emacs user, I created Emacs-style binding. Therefore I use `ctrl-k` frequently. I attempted to record for you a short video (hopefully it will be readable) - I demonstrate command performance (there seems to be *no* relation to document length and most probably also line length), how pressing ctrl-k multiple times has undefined result, and finally that pressing `ctrl-k` and other key (like `arrow down`) has undefined/unexpected consequences (in this case it opens new window):

  * high quality OGV: http://mindforger.com/video/atom-ctrl-k-slow.ogv (should play in your browser)
   * low quality YouTube: https://youtu.be/CRUReJ7Iqvw

**Comment by izuzak** [comment]
> I started to use Atom just recently and as ex-Emacs user, I created Emacs-style binding. Therefore I use ctrl-k frequently.

That's relevant information here, thanks for including it. Try opening the Keybinding resolver ("Keybinding Resolver: Toggle" from the command palette) and then try pressing `ctrl-k`. You'll notice many command matched because many commands use `ctrl-k` as a part of the keybinding. For example, the keybinding to split panes down on Linux is `ctrl-k down` (see [here](https://github.com/atom/atom/blob/master/keymaps/linux.cson#L63)).

So, you're using both `ctrl-k` and `ctrl-k some_other_keystroke` in Atom. This meant that when you press `ctrl-k`, Atom doesn't know if it should execute the command bound to `ctrl-k` or if it should wait a bit more for `some_other_keystroke` so that it could execute the command bound to `ctrl-k some_other_keystroke`. The way Atom handles that situation currently is that it waits a short period of time and then makes a decision. That's why you're seeing the delay -- [it's here to resolve the ambiguity](https://github.com/atom/atom-keymap/blob/411ae894194e6563019498c7a9b60a28f22513b7/src/keymap-manager.coffee#L56-L64) you introduced in your keybindings. That's also why you're seeing the new pane opened -- you triggered another keybinding when you pressed `ctrl-k down`.

I'm not sure I understand what you meant by "undefined results" -- can you clarify that and explain what you expected to observe and in what way the behavior you observed didn't match that?

**Comment by dvorka** [comment]
Thank you for the great problem identification and detailed clarification! This explains all my problems.

> I'm not sure I understand what you meant by "undefined results" -- can you clarify that and explain what you expected to observe and in what way the behavior you observed didn't match that?

I meant a situation when I was pressing `ctrl-k` multiple times with *various* delays - you explained Atom behavior in such situation clearly. 

I'm closing this issue as there is none.

Thank you!
