### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeName' of undefined

### ISSUE THREAD

**Issue by ATNC** [atom/atom#6235]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.189.0
**System**: linux 3.13.0-48-generic
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'scopeName' of undefined

```
At /opt/atom/resources/app/src/text-editor.js:2263

TypeError: Cannot read property 'scopeName' of undefined
    at TextEditor.module.exports.TextEditor.usesSoftTabs (/opt/atom/resources/app/src/text-editor.js:2263:28)
    at TextEditor.module.exports.TextEditor.handleTokenization (/opt/atom/resources/app/src/text-editor.js:2803:44)
    at /opt/atom/resources/app/src/text-editor.js:205:24
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
    at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (/opt/atom/resources/app/src/tokenized-buffer.js:306:22)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/opt/atom/resources/app/src/tokenized-buffer.js:299:21)
    at /opt/atom/resources/app/src/tokenized-buffer.js:247:26
    at /opt/atom/resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 17
  }
}
```
### Installed Packages

``` coffee
# User
atom-django, v0.2.1
django-templates, v0.4.0
linter-jshint, v0.1.0
linter-pep8, v0.1.0
script, v2.18.0
seti-ui, v0.6.3
terminal-panel, v1.10.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@ATNC Can you share some steps which reproduce the problem? Can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by zdennis** [comment]
Putting the following in your init script reproduces the above issue for me:

```
atom.workspace.observeTextEditors (editor) ->
  unless editor.getPath()
    editor.setGrammar(atom.grammars.grammarForScopeName('source.md'))
```

**Comment by izuzak** [comment]
@zdennis Thanks for providing some steps to reproduce this -- not sure if that's the same thing though, since you're manually setting the grammar to `undefined` there.

@nathansobo Seems like the exception is being thrown [here](https://github.com/atom/atom/blob/3bbbadd0903d6d0e02fd6177fbd64410f3ab334f/src/text-editor.coffee#L2275):

```coffee
usesSoftTabs: ->
    return false if @getGrammar().scopeName is 'source.makefile'
    ...
```

Can you think of a scenario where `getGrammar()` would return undefined (other than the user setting it to `undefined`)? Should we worry about this or just guard against the call on an `undefined`?

**Comment by nathansobo** [comment]
Tokenization occurs in chunks because we're still parsing on the UI thread and need to yield for browser updates when editing large files. This is why you see underscore at the top of the stack trace... we're using `_.defer`.

It seems like what may have happened is the grammar somehow got set to `null` in between two calls to `tokenizeNextChunk`. What's a bit confusing to me is how the grammar could have been assigned to `null` without throwing an exception itself. So, I don't have any answers here.
