### ISSUE TITLE
Linux 32 bit distributions

### ISSUE THREAD

**Issue by Bobbyjoness** [atom/atom#6252]
There should be binaries for 32-bit. A lot of potential users may not be able to build from source.

**Comment by alinex** [comment]
+1
some machines still running on 32bit

**Comment by Maslor** [comment]
:+1:

**Comment by hbayindir** [comment]
Being able to download a 32bit .zip/.deb/.rpm would be great.
Not everyone has transitioned to 64bit yet.
I'm running Debian Testing (8.1+) 32 bit, first installed as 4.0 Beta 1. I didn't migrated it to 64 bit since I had no time.

**Comment by 1dot75cm** [comment]
32-bit build pass for rpm, but no test.
https://copr.fedoraproject.org/coprs/mosquito/atom/build/132760/

**Comment by franlu** [comment]
+1
:+1: deb package for 32 bit linux  :+1:

**Comment by Slavenin** [comment]
for ubuntu 32 bit http://askubuntu.com/a/558751/671782

**Comment by alinex** [comment]
Against my posting 2 years ago I don't need it anymore. All machines now x64 arround me.

So -1 for me.

**Comment by CyberManifest** [comment]
+1 here, need it on a distro only released in a 32 bit variation https://www.raspberrypi.org/downloads/raspberry-pi-desktop/
Also, I imagine there are 3rd world countries still using 32 bit, and this could alleviate e-waste by recycling / upcyling old hardware.

**Comment by lee-dohm** [comment]
Thanks everyone for the feedback.

Unfortunately, we only have the bandwidth to support a certain number of installation methods and we had to decide which ones were going to be our top priorities. 32-bit installers for Linux fell below the bar. Because of this, we aren't going to be providing 32-bit pre-built installers for Linux in the foreseeable future.

Thanks for everyone's interest.
