### ISSUE TITLE
[Keybindings] Make note about alt/option key for OS X

### ISSUE THREAD

**Issue by mitchwd** [atom/atom#6265]
Is it worth noting in the documentation at https://atom.io/docs/latest/behind-atom-keymaps-in-depth, and in the Keymap file (~/.atom/keymap.cson) that custom keybindings should use 'alt' rather than 'opt' in their commands? 

Thanks for a great project!

Versions:
atom: 0.189.0
OS: Mac OS X

**Comment by izuzak** [comment]
Hey, @mitchwd :wave: -- thanks for the feedback!

Since the [default keymap.cson file](https://github.com/atom/atom/blob/master/dot-atom/keymap.cson) includes a link to [that docs page](https://atom.io/docs/latest/behind-atom-keymaps-in-depth), I think that modifying the docs page would be enough. However, the docs page already lists the possible modifiers as: `cmd`, `ctrl`, `alt`, `shift`, which seems pretty clear. May I ask why you thought of using `opt` instead of `alt`, even after checking that docs page? (I'm guessing some other editor uses `opt`? I just checked SublimeText and it uses `alt` as well, as far as I can tell.) Just trying to get a clearer picture about what was confusing and why.

**Comment by mitchwd** [comment]
Hi @izuzak, thanks for the speedy response!
I only considered using `opt` because it's what OS X documentation and most keyboards I use name that key. Modifying the docs page would be great. 
Thanks!

**Comment by izuzak** [comment]
@mitchwd I guess I'm still a bit confused about how you'd like the docs page to be updated -- the docs page currently clearly lists the modifier keys users should be using. "don't use `opt`, use `alt`" sounds redundant when compared to "use `alt`" (also, my keyboard has `option` written on the `alt` key, not `opt`, so we'd need to list that as a "don't use X" option as well?). If you'd like to make a PR with a suggestion to update the docs (https://github.com/atom/docs), that would be a good way to continue this discussion. Thank you! :bow:
