### ISSUE TITLE
Installation crashes on language-php module installation!

### ISSUE THREAD

**Issue by mirkojovanovic** [atom/atom#6311]
I got this error in terminal, `Unable to download https://www.atom.io/api/packages/language-php/versions/0.22.0/tarball: 503`. This is weird because file is downloadable from browser. I'm using Arch linux and AUR.

**Comment by 50Wliu** [comment]
atom.io relies on the Github backend in order to serve packages, so it might just be Github that's having a few problems right now.  I just checked status.github.com and it does look like there's a recent spike in some of the metrics.

To clarify, what is crashing?  Are you attempting to build from source?

**Comment by mirkojovanovic** [comment]
No I'm getting it from package manager. It just stops the installation with error message above and asks if I want to try again. I tried but the same issue appeared again.

**Comment by mirkojovanovic** [comment]
I tried same thing again and it works now. Something was bad with that link
