### ISSUE TITLE
ATOM_HOME environment variable should be used if available.

### ISSUE THREAD

**Issue by Zoltu** [atom/atom#6349]
If ATOM_HOME is set then `(HOME|USERPROFILE)\.atom` should not be used.  This is violated in the following locations:

https://github.com/atom/atom/blob/master/build/tasks/clean-task.coffee#L17-L20
https://github.com/atom/atom/blob/master/script/clean#L11-L28
https://github.com/atom/atom/blob/master/script/cibuild#L8-L85
https://github.com/atom/atom/blob/master/build/Gruntfile.coffee#L44-L101

This is tangentially related to https://github.com/atom/atom/issues/6345 in that USERPROFILE should not be used.  However, in these cases you can't override the incorrect current behavior with an environment variable.

**Comment by damieng** [comment]
ATOM_HOME is intended for end-user scenarios rather than for build environments - all the files you reference there are part of the build process.

**Comment by kierans** [comment]
As someone who's started hacking on Atom core, this actually caused me grief.  Given `apm` respects `ATOM_HOME` when installing packages, why can't the rest of the build process respect the var as well?  

It makes sense you don't want to clobber you `~/.atom` due to hacking on Atom, which is why I thought `ATOM_HOME` existed; to be able to have separate builds of Atom coexist.

Can this issue be reopened?

**Comment by damieng** [comment]
The build system has been completely rewritten since this issue was filed and closed.  Can you please create a new issue with the full details of the problem you are having?  Thanks!

**Comment by kierans** [comment]
@damieng Done.  Can my PR get reviewed as it's a simple fix.

**Comment by damieng** [comment]
Now merged, thanks for addressing this.
