### ISSUE TITLE
Some subfolders displayed in grey and not searched via fuzzy search

### ISSUE THREAD

**Issue by jancborchardt** [atom/atom#6416]
Some subfolders are displayed in grey and the files in there are not searchable/indexed unfortunately. I haven’t found out why that is or how to fix it:
![atom sidebar](https://cloud.githubusercontent.com/assets/925062/7202151/e91efc70-e50f-11e4-8d34-c2545807470f.png)
* 3rdparty is a git submodule – perfectly searchable
* .git and .idea are hidden folders, not searchable – also fine
* apps is also a normal folder with a few differences:
  * most of the subfolders are separate git clones of apps – they are grey and none of them are searchable
  * even the subfolders which are not git clones, there by default and not greyed out are _not_ searchable
  * the folder is owned by my user but by the webserver group – that’s not a problem for another folder though where stuff is searchable

Digging further it might have something to do with the .gitignore? [Our .gitignore](https://github.com/owncloud/core/blob/master/.gitignore) has this part:
```
# ignore all apps except core ones
/apps*/*
!/apps/files
!/apps/files_encryption
!/apps/encryption
!/apps/encryption_dummy
!/apps/files_external
!/apps/files_sharing
!/apps/files_trashbin
!/apps/files_versions
!/apps/user_ldap
!/apps/user_webdavauth
!apps/provisioning_api
```

So that might be a factor. However as I said above
> even the subfolders which are not git clones, there by default and not greyed out are _not_ searchable

And as you can see, these are also un-ignored in the .gitignore. Maybe that isn’t correctly parsed?

**Comment by jancborchardt** [comment]
:D I just found the »Exclude VCS Ignored Paths« setting. I was so focused on the »Follow symlinks« setting that I didn’t even see the other one.

Now the stuff is searchable. However the incorrect parsing of the .gitignore still stands as the folders prefixes with `!` should be un-ignored.

**Comment by jancborchardt** [comment]
Also, setting the »Exclude VCS Ignored Paths« doesn’t reflect in the sidebar as the folders stay grey. Depends on what the greying out is for – in this case though it’s confusing.

**Comment by mnquintana** [comment]
@jancborchardt To hide VCS ignored files in the tree view, you'll need to go to Settings > Packages > tree-view > Hide VCS Ignored Files.

**Comment by jancborchardt** [comment]
@mnquintana thanks – I don’t want to hide them though, this is not what this issue is about.

**Comment by izuzak** [comment]
> However the incorrect parsing of the .gitignore still stands as the folders prefixes with ! should be un-ignored.

I believe that problem is being tracked in [this issue on the tree view package](https://github.com/atom/tree-view/issues/196). 

> Also, setting the »Exclude VCS Ignored Paths« doesn’t reflect in the sidebar as the folders stay grey. Depends on what the greying out is for – in this case though it’s confusing.

That's controlled by the theme you use. Most themes style such entries differently to inform the user that they are special in a way (ignored by Git). Atom allows you to [install and use a different theme](https://atom.io/docs/v0.192.0/using-atom-atom-packages), [build your own](https://atom.io/docs/v0.192.0/hacking-atom-creating-a-theme), or [change styling locally](https://atom.io/docs/v0.192.0/using-atom-basic-customization#style-tweaks), if you don't like the theme you're currently using.

I think this addresses your questions, so I'll close this out. If you have any other questions or suggestion related to this -- opening an issue on the tree view package or the theme would be :cool:. Thanks for the feedback, @jancborchardt.
