### ISSUE TITLE
Add start/stop and test button

### ISSUE THREAD

**Issue by tinganho** [atom/atom#6426]
I'm just wondering if you could add a start/build and stop and test button to Atom Editor?

I'm running `npm test` and `npm start` one hundred times a day.

Preferably they should be configurable by bash scripts.

**Comment by thomasjo** [comment]
This seems like an excellent opportunity for a community package. Check out the Flight Manual to get started: https://atom.io/docs/v0.192.0/hacking-atom-package-word-count

In short, it is highly unlikely that a core package will be created for this anytime soon, especially since Atom already supports [running Jasmine specs](https://atom.io/docs/v0.192.0/hacking-atom-writing-specs#running-specs) out of the box.
