### ISSUE TITLE
Notifications affect focus

### ISSUE THREAD

**Issue by vrinek** [atom/atom#6439]
> **GIVEN** the editor has unsaved changes,
> **AND** the "save on blur option is on,
> **AND** a notification is set to trigger on save (by some other function),
> **AND** I trigger a dialog to appear
> **THEN** the focus is moved from the editor to the dialog _briefly_ until it moves back to the editor (which is in the background).

The example below was made using the atom-typescript package's rename dialog & compile-on-save. The notification in this example was triggered by the compile-on-save feature. Roughly the same happens with the symbols dialog, the file dialog etc. In these cases though, the focus moves back to the editor and the dialog disappears.

![Example](http://i.imgur.com/iP0cEYg.gif)

Atom versions: 0.190 & 0.192

**Comment by batjko** [comment]
Can you replicate this with core dialogs, rather than packages, i.e. after launching atom in safe mode (`atom --safe`)?

**Comment by vrinek** [comment]
I can't find any core packages that produce these kinds of notifications.

**Comment by basarat** [comment]
Reproducible by running the following code in the dev console: 

```js
atom.commands.dispatch(atom.views.getView(atom.workspace.getActiveTextEditor()),'command-palette:toggle');
var noti = atom.notifications.addInfo("When I go away the command palette will close", {dismissable: true}); 
setTimeout(function(){noti.dismiss()},2000);
```

Note: you need to focus on the filterview inside the open command pallet and then the `noti.dimiss` will take focus *away* from the filter view and hence the command pallet will close. Demo: 

![noti hide](https://cloud.githubusercontent.com/assets/874898/7578455/8ef49f92-f898-11e4-8240-50551db07bc0.gif)


## Root cause
The offending code is `atom.workspace.getActivePane().activate()` https://github.com/atom/notifications/blob/4f783ca2a8711517a7d2f3e4822cef75af132e40/lib/notification-element.coffee#L187 called from `onDidDismiss` https://github.com/atom/notifications/blob/4f783ca2a8711517a7d2f3e4822cef75af132e40/lib/notification-element.coffee#L45

Note: this issue does not exist for the auto hiding view because it doesn't change focus : https://github.com/atom/notifications/blob/4f783ca2a8711517a7d2f3e4822cef75af132e40/lib/notification-element.coffee#L210-L211 

## Suggested fix
Since this focus change is intentional : https://github.com/atom/notifications/commit/5ef6fafc932c0c17233430794d6ce832fbc40391 

The only reason I am using a dismissable notification and dismissing myself is because the visibility duration : https://github.com/atom/notifications/blob/4f783ca2a8711517a7d2f3e4822cef75af132e40/lib/notification-element.coffee#L33 is not exposed as an option.

**Comment by izuzak** [comment]
Thanks for the report @vrinek and for the great reproduction steps @basarat. I think it we should consider making this a better experience (and not focus the editor when the notification is dismissed if the notification itself wasn't focused, for example).
