### ISSUE TITLE
Docs website 500ing

### ISSUE THREAD

**Issue by tinloaf** [atom/atom#6444]
Hi,

visiting https://atom.io/docs/v0.60.0/publish-a-package gives me a 500 error message and tells me to let you know if a refresh does not solve the problem. Well, it does not. ;)

**Comment by izuzak** [comment]
cc @thedaniel

**Comment by thedaniel** [comment]
Thanks!

**Comment by lee-dohm** [comment]
I suspect that this belongs on the [atom/docs repository](https://github.com/atom/docs)? The documentation has been *significantly* rewritten since v0.60.0. There is information around publishing a package in the new documentation here:

https://atom.io/docs/v0.192.0/hacking-atom-package-word-count#publishing

**Comment by tinloaf** [comment]
Sure, I'm aware that that piece of information is out of date, but it should still not raise a 500 (i.e. "The server fell over").

**Comment by mnquintana** [comment]
It should really be a 404 error (that URL just points to a resource that doesn't exist)

**Comment by thedaniel** [comment]
@tinloaf is right, the app shouldn't be returning 500 ever - I'm not sure if that record exists in the DB or not - I'd guess it's probably malformed or missing some related record it needs to render the page since it's so old. This brings up an interesting question about just how much we care about the doc versions that are that old..

**Comment by 50Wliu** [comment]
@thedaniel none of the versions are working for me-try https://atom.io/docs/v0.186.0/publish-a-package for example.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#18
