### ISSUE TITLE
Shift-up at the end of input should select all.

### ISSUE THREAD

**Issue by bolinfest** [atom/atom#6445]
In `atom-text-editor:mini`, when I get to the end of the line, `shift-up` should select all of the text in the input like a native input box would. This is not working in Atom 0.192.0 on OS X.

**Comment by bolinfest** [comment]
@izuzak I'm pretty sure this is a bug, not an enhancement. Here's why:

When I have the key binding resolver open, I see that `core:select-up` is triggered, but the text fails to select.

Also, I could have sworn this used to work. If anyone has an Atom 0.185.0 or earlier around to verify, that would be helpful.

**Comment by izuzak** [comment]
Thanks for the details, @bolinfest!

> Also, I could have sworn this used to work. If anyone has an Atom 0.185.0 or earlier around to verify, that would be helpful.

Ahh, :cool:, yeah it should be easy to confirm then -- you can download that version here and try it out: https://github.com/atom/atom/releases/tag/v0.185.0

I'd be okay if you changed it to "bug". :+1: I put an "enhancement" label on it because 1) I don't remember this working before (but that's probably because I didn't use it), and 2) the information you provided in the issue and the way it was phrased made it sound more as a feature request to me. I'll ask for more information next time. :newspaper:

**Comment by bolinfest** [comment]
Hmm, OK, it didn't work in Atom 0.185.0 on Mac.

I still see `core:select-up` in the key binding resolver in 0.185.0, though.
