### ISSUE TITLE
Static analysis for XYZ language

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#6472]
I'm wondering if Atom can be tweaked (via plugins) so that it can act as a real IDE for XYZ language.
And by "real IDE" I mean smart autocomplete suggestions (don't suggest method `draw()` on the object `$person`, and don't suggest the method `walk()` on the object `$shape`), static analysis, etc.

Is that possible and if so, it would be nice to have some guide explaining how one would create such a plugin for his favorite language. Maybe even create one plugin, like a reference implementation.

**Comment by TomasHubelbauer** [comment]
Take a look at the OmniSharp project, it is specifically for .NET, but the way it works is you have a compiler server running and different text editors (including Atom) have their own plugins that provide things like auto-completion and error checking through facilities the individual text editors have. You can turn your favorite editor to a .NET IDE that way.

Since OmniSharp is available for Atom, you can take a look at [it's plugin implementation](https://github.com/OmniSharp/omnisharp-atom).

**Comment by mehcode** [comment]
@alexandernst Keep an eye on https://github.com/atom-community/autocomplete-plus/issues/351

**Comment by alexandernst** [comment]
Nice, will subscribe :) @mehcode

**Comment by alexandernst** [comment]
So... we actually have quite some languages already! https://github.com/atom/atom/issues/4364
Sadly, there isn't PHP :(

Are there any good static analysis tools that would allow to imiplement the same, but for PHP?

**Comment by mehcode** [comment]
I don't know much about PHP but would this work: https://github.com/steelbrain/AutoComplete-Hack

**Comment by Peekmo** [comment]
I develop a plugin for PHP ( https://github.com/Peekmo/atom-autocomplete-php ) based on autocomplete-plus, it will only works for composer projects, you can keep an eye on it, a first release will come soon. But you can also play with it already and contributing if you want :)

For the moment, it just support autocompletion on $this-> (methods and attributes) from a class, on locale variables (all variables declared in the current function), internal PHP functions, static functions from an internal PHP classes. (the autocompletion for 'new Class()' is currently disabled because I'm working on it)

For the first release, will come some a real index of all classes, with "use" added automatically, and a little autocompletion for classes variables (based on PHPDOC).

So thanks to the autocomplete-plus plugin, yes it's possible to act as a real IDE, but you have to develop all the analysis, or plug to an other external tool of course, but atom give you almost everything to have what you need for that purpose.

**Comment by alexandernst** [comment]
@Peekmo Holly! That is amazing! I have quite some questions, but I'll open issues in your repo rather than spamming this issue :)

And I think I'll close this bug as my question is pretty much answered. It is possible to do what I'm asking for!
