### ISSUE TITLE
rendering issue with submodules

### ISSUE THREAD

**Issue by olivierlesnicki** [atom/atom#6473]
I have a repo that contained a number of submodules.
All my submodules have been listed in the .gitignore file.

When I open a submodule with atom, it's not recognized as a git package and all its folders are greyed out. I assume it's because the parent .gitignore mentionned it.

**Comment by kunyan** [comment]
I have the same issue

**Comment by mnquintana** [comment]
I'm not sure I understand – if the submodules are in the .gitignore file then the intended behavior is that they'll be grayed out in the tree-view.

**Comment by olivierlesnicki** [comment]
@mnquintana that's the expected behavior if I open the top-most folder as the "project"
```
repo
| submodule1 // should be grayed out
| submodule2 // should be grayed out
.gitignore
```

However it's not the expected behavior if I open one of the submodule as the "project"
```
submodule1 // should not be grayed out
```

**Comment by kunyan** [comment]
@mnquintana for example

I have a vagrantfile repo, it is include a project source code as as git submodule.
I just want keep the repo clean, so I add source code folder into .gitignore.

the bug is: currently, all source codes in tree view are gray when I open its directory as root directory in Atom

another bug, Search can not search the submodule file.

Textmate not have those bugs, I think Atom should fix it too
