### ISSUE TITLE
Bookmarks removed after jsFormat(https://atom.io/packages/jsformat) formatting  

### ISSUE THREAD

**Issue by vinaymavi** [atom/atom#6487]
Bookmarks created successfully with Ctrl+Alt+F2 but I am configured jsFormat on **on save** after formatting Bookmarks removed.

**Comment by izuzak** [comment]
Hey @vinaymavi :wave:. We can't really debug other packages and look at what they're doing, but I'm guessing that the package is modifying the text in the editor somehow and that's causing the bookmark to be removed. If you can reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode), then please report the issue on the Bookmarks package's repository: https://github.com/atom/bookmarks and provide steps to reproduce so that we can take a look. Thanks!
