### ISSUE TITLE
Atom becomes non-responsive to keyboard

### ISSUE THREAD

**Issue by craigbeck** [atom/atom#6500]
On Ubuntu 14.10, Atom v0.190.0

Not sure why, but I've had Atom stop taking any keyboard input several times. Usually after switching back to Atom from another application. Mouse still works but no keyboard input does anything. Only workaround is to restart Atom.

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by craigbeck** [comment]
I’ll try. It’s already done it three times in the last couple of hours so I’ll just have to see if it happens again as I do’t have a clear repro case.


—

**Comment by izuzak** [comment]
Closing this since I don't remember seeing similar reports from other users and we haven't heard back from @craigbeck in more than 3 months (with an answer to [this question](https://github.com/atom/atom/issues/6500#issuecomment-95727701)). @craigbeck Let us know if you can still reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) on the latest version of Atom (1.0.11). :v:
