### ISSUE TITLE
Can't open settings by using ``Ctrl+comma`` when editing a file

### ISSUE THREAD

**Issue by superlin** [atom/atom#6533]
I can't open settings by using ``Ctrl+comma`` when editing a file, but I can open it when losing focus.

**Comment by 50Wliu** [comment]
Please open the keybinding resolver (<kbd>Ctrl+.</kbd>) and see what happens when attempting to open the Settings View.
Also, what Atom version is this?  I have a suspicion that this might be one of your packages causing the problem (in which case you can try opening Atom using `atom --safe` to check).

**Comment by superlin** [comment]
Thanks, it is ok in safe mode and I found the problem.
![1](https://cloud.githubusercontent.com/assets/3763687/7365611/726478e0-edc4-11e4-8ae8-6f495e306106.png)

**Comment by DrizzleX** [comment]
I have the same problem, and when I search "ctrl-," in the keybindings, there are only application:show-settings and settings-view:open. My version is 1.7.3

**Comment by jddxf** [comment]
@DrizzleX I have the same problem as yours.It turns out that "ctrl-," was used by my OS to switch to an input method.After I removed that binding, Atom works as expected.

**Comment by DrizzleX** [comment]
@jddxf Could you tell me how did you find that out and how to remove the binding?

**Comment by DrizzleX** [comment]
@jddxf Never mind, I've found the solution. Thanks anyway.
