### ISSUE TITLE
Confusing behavior of Cursor.getCurrentWordBufferRange()

### ISSUE THREAD

**Issue by DanEEStar** [atom/atom#6538]
I have a very simple file containing nothing but the text `-12`.
When I execute the `getCurrentWordBufferRange()`-method on this text with the cursor on different positions of the text I get 3 different results:
- "-" cursor position [0,0]
- "-12" cursor position [0,1]
- "12" cursor position [0, 2]

Is this really the expected behaviour of `getCurrenWordBufferRange()`? I would expect it to always return the string `"-12"` or at least not different results for the same word.

I tested it on atom 0.194.0 on Mac OS X.

Here is a simple jasmine spec with the confusing results which all pass on my machine:

```
getEditorElement = (callback) ->
  textEditor = null

  waitsForPromise ->
    atom.project.open().then (e) ->
      textEditor = e

  runs ->
    element = document.createElement('atom-text-editor')
    element.setModel(textEditor)
    callback(element)

describe 'getCurrentWordBufferRange tests', ->
  editor = null

  beforeEach ->
    getEditorElement (element) ->
      editorElement = element
      editor = editorElement.getModel()
      editor.setText('-12')

  describe 'getCurrentWordBufferRange tests', ->

    it 'current word at position [0,0] is "-"', ->
      cursor = editor.addCursorAtScreenPosition([0, 0])
      cursorText = editor.getTextInBufferRange(cursor.getCurrentWordBufferRange())
      expect(cursorText).toBe('-')

    it 'current word at position [0,1] is "-12"', ->
      cursor = editor.addCursorAtScreenPosition([0, 1])
      cursorText = editor.getTextInBufferRange(cursor.getCurrentWordBufferRange())
      expect(cursorText).toBe('-12')

    it 'current word at position [0,2] is "12"', ->
      cursor = editor.addCursorAtScreenPosition([0, 2])
      cursorText = editor.getTextInBufferRange(cursor.getCurrentWordBufferRange())
      expect(cursorText).toBe('12')
```

**Comment by tikotus** [comment]
Any updates on this? I'm having the same problem. Certainly doesn't feel right.

**Comment by izuzak** [comment]
@DanEEStar @tikotus Sorry for the delay in getting back to you. 

This looks like a bug to me -- maybe @benogle, @nathansobo or @as-cii can take a look? I also think this is related to https://github.com/atom/atom/issues/3650 where I was having trouble understanding and reproducing the problem so I closed the issue. However, I see the problem now -- for the text `foo-bar-baz` and the position of the cursor like this `foo-b|ar-baz`, I expected different results for these two calls:

```
> atom.workspace.getActiveTextEditor().getWordUnderCursor({"includeNonWordCharacters":true})
"bar"

> atom.workspace.getActiveTextEditor().getWordUnderCursor({"includeNonWordCharacters":false})
"bar"
```

Specifically, I expected the first call to return `foo-bar-baz` since `editor.nonWordCharacters` includes `-`:

```
atom.config.get('editor.nonWordCharacters')
"/\()"':,.;<>~!@#$%^&*|+=[]{}`?-…"
```

It seems that the `wordRegExp` method doesn't construct the correct regex when `includeNonWordCharacters` is `true`, which is what https://github.com/atom/atom/issues/3650 reported as well. That issue also includes a suggestion for fixing this problem.

**Comment by izuzak** [comment]
Update: I'm looking into this and have an idea about what's going on. There are no specs for this method (as far as I can tell), so my plan is to first open a pull request with some specs to confirm the intended behavior, and then use that to fix any problems. I'll post an update here once I get that PR going. :newspaper:

**Comment by benmccormick** [comment]
@izuzak this is causing problems for vim-mode https://github.com/atom/vim-mode/issues/868

**Comment by izuzak** [comment]
Thanks, @benmccormick. We're discussing these things over in https://github.com/atom/atom/issues/8906. Mind dropping in there and sharing your thoughts about what would be the expected behavior? That might help us feel more confident about moving forward.
