### ISSUE TITLE
Diff information getting stuck in gutter

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#6561]
1. Ensure that Atom is your editor for command-line Git commands `core.editor = atom --wait`
1. Check out a git repository (I used a random Atom one)
1. Open a file in the git repository
1. Add a bunch of text (my mechanical keyboard sounds awesome when monkey typing in random characters :grinning:)
1. Save the file with <kbd>Cmd+S</kbd>
1. In a Terminal window, type `git commit -a`
1. Wait for the new Atom window show up
1. Type "DELETE THIS COMMIT" as the commit message
1. Save the file with <kbd>Cmd+S</kbd>
1. Close the Git Commit Atom window with <kbd>Shift+Cmd+W</kbd>
1. Switch back to the original Atom window with <kbd>Cmd+Tab</kbd>

**Expected:** Git diff information to disappear
**Actual:** Same Git diff information as before the commit remains

To be clear, after this, the Git diff information will stick in the gutter even after scrolling (it stays connected to the lines they were attached to before the commit), switching to another tab *in the editor*, Cmd+Tabbing to other applications, for an indeterminate period of time. (Previous behavior was the diff information would stick around until a Cmd+Tab to *any* other application and immediate Cmd+Tab back.)

Screenshot taken *after* all repro steps above were executed:

![f72b852e-ed2d-11e4-85a0-5f3877f432d7 1](https://cloud.githubusercontent.com/assets/1038121/7384003/9b17bb66-edde-11e4-9f85-a020e55805ac.png)

Memory leak warnings that weren't there before the repro steps were begun:

![115fc392-ed2e-11e4-8264-946406f6f839](https://cloud.githubusercontent.com/assets/1038121/7384012/c8f57564-edde-11e4-9fe5-198472dcc6f2.png)

**Comment by lee-dohm** [comment]
No longer reproducing using Atom v0.195.0-192997c on Mac OS X 10.10.3. It appears that @nathansobo's last fix corrected this issue as well.

**Comment by nathansobo** [comment]
:dart:

**Comment by grizzilus** [comment]
I think I might have a reproduction of this issue, but it seems to be package related. I was watching the issue that prompted this one since I have been having the git-dif information stick in the gutter as well but never remembered what I did to do it.

The following steps are on atom 0.195.0-192997c (Mac OS X 10.10) with the git-tab-status package installed. No other config settings or anything else.

1. Open Terminal and navigate to a repository.
1. Enter `atom .`
1. Open any file in atom from the tree view.
1. Click on Terminal and enter `git checkout -b test`.
1. Click on the editor view and make a change to the file. (I just added a newline.) Save.
1. Click on Terminal and enter `git commit -a -m'test'`
1. Click on Atom and the git diff is stuck in the gutter.

I am not sure if this is a package issue, but it seemed relevant here (and the previous issue about line numbers and the gutter) so I thought I'd post it here and see if anyone can reproduce with my steps.

**Comment by lee-dohm** [comment]
@grizzilus Can you reproduce this after closing all instances of Atom and relaunching using `atom --safe`?

**Comment by grizzilus** [comment]
No, this doesn't happen in safe mode. Something in the `git-tab-status` package causes it. And I think the code in that package is generic enough that other packages might be having this effect if others have noticed it for a while (which seems to be the case based on these two issues).

**Comment by lee-dohm** [comment]
Taking a quick look over `git-tab-status` it polls every half second to see if something has changed. I believe it would be better using the [`GitRepository.onDidChangeStatuses`](https://atom.io/docs/api/latest/GitRepository#instance-onDidChangeStatuses) to be notified when anything changes. I'll open an Issue over there.

**Comment by grizzilus** [comment]
But would this causes the status to stick in the gutter permanently? The information remains after the 500ms has passed which is why I didn't initially think they were related.

**Comment by lee-dohm** [comment]
:confused: I don't know enough yet about the eventing system in Node/JavaScript to be able to answer that question. It is just what jumped out at me as different about the package. @nathansobo would be the expert on that kind of thing probably.
