### ISSUE TITLE
Feature request: Add built-in support for EditorConfig

### ISSUE THREAD

**Issue by treyhunner** [atom/atom#6589]
There is an [Atom](https://github.com/sindresorhus/atom-editorconfig#readme) plugin for EditorConfig, but native support (such as is included in BBEdit, Coda, WebStorm, etc.) would make the EditorConfig experience much easier for teams with Atom users.

Maybe this could be part of the per-project configuration file task (#5168)?

Disclaimer: I am biased as one of the EditorConfig project maintainers

**Comment by sindresorhus** [comment]
:+1: Or at least add APIs so that a plugin could implement the necessary functionality: https://github.com/sindresorhus/atom-editorconfig/issues

**Comment by Alhadis** [comment]
Strongly seconding this. I don't see much reason not to support this natively.

**Comment by cebor** [comment]
:+1:

**Comment by jbenner-radham** [comment]
+1

**Comment by KamranMackey** [comment]
:+1:

**Comment by rosshays** [comment]
+1

**Comment by nounoursheureux** [comment]
This would need per-project settings and I don't think that is implementented now. But this would be nice :+1:

**Comment by varemenos** [comment]
:+1:

**Comment by coliff** [comment]
+1

**Comment by merikan** [comment]
+1

**Comment by spencern** [comment]
:+1: subscribing.

**Comment by maxbrunsfeld** [comment]
> Or at least add APIs so that a plugin could implement the necessary functionality

Yeah, I'm strongly in favor of adding whatever APIs EditorConfig needs to work properly, but not really in favor of baking EditorConfig into Atom in any way. It seems like a perfect job for a package.

@sindresorhus, could you open separate issues for any missing APIs that you know of?

**Comment by joefitzgerald** [comment]
@maxbrunsfeld what are your objections to baking EditorConfig support into Atom? If it were baked in, it would encourage some form of consensus in a way that doesnt cause fragmentation with other editors. I'm about to embrace editorconfig for go-plus. It would be fantastic to have this support in core, such that atom.config.get(...) allowed editorconfig to supersede my package configuration on a project by project basis...

**Comment by thedaniel** [comment]
Tangentially, how popular is editorconfig? I'd never heard of it before seeing the atom-editorconfig package. Looking at the stars and forks on GitHub makes it seem fairly active.

In any case I'm with Max - it sounds nice, but it's more interesting to me as a use case to work out better config APIs for packages.

@joefitzgerald per-project config is something we're definitely planning to add, it seems like there could be some story there with providing a way for an editorconfig package to hook in.

**Comment by Alhadis** [comment]
@thedaniel : I'm guessing it'd be impossible to add a setting that allows users to switch a code's tabulation width even if it's using soft tabs?

I've been reading through the source of NPM modules over the last few weeks and I feel like I'm going blind. 2-spaces makes me want to fork my eyes out to git rid of the pain. Puns intended. Yes, it's driving me crazy.

**Comment by thedaniel** [comment]
@Alhadis Anything is possible. Let your dreams soar. Don't fork your eyes out. Here's a hacky solution for you off the top of my head, let's see if this works for scanning module source: just add letter-spacing between the space characters that make up the soft tabs in CSS!

in styles.less add something like:

```
atom-text-editor::shadow .source.js > span.leading-whitespace {
  letter-spacing: 1em;
}
```

Anyway this is a bit of a derail from the main topic of this issue. Feel free to file a separate issue about how your code browsing experience could be better if this hack doesn't work for you.

**Comment by svoop** [comment]
@thedaniel EditorConfig gains traction very much like Github once has. In any case, it's all about *enforcing* minimal standards, so eventhough a package is a great first step, it's IMO better suited for the core to actually serve it's purpose.

**Comment by Alhadis** [comment]
> Feel free to file a separate issue about how your code browsing experience could be better if this hack doesn't work for you.

@thedaniel : [Done](https://github.com/atom/whitespace/issues/96). Please let me know if I've filed it in the wrong repo.

**Comment by theaccordance** [comment]
As a bootcamp teacher who encourages his students to use Atom over Sublime, I'd like to see this type of functionality included in the core.  It would allow me to standardize aspects of the editor on a per-project-basis, and reduces the number of steps my students will have to follow to configure their developer environment.  Less time configuring environment = more time focused on the curriculum.  

May not the the typical use case for this product, but please take into consideration that absolute beginners to coding are using Atom

**Comment by awebdeveloper** [comment]
+1

**Comment by maur1th** [comment]
+1

**Comment by Alhadis** [comment]
@maur1th More like maur+1th, amirite? :D

**Comment by badlydrawnrob** [comment]
+1

**Comment by jaimeschettini** [comment]
+1

**Comment by pedzed** [comment]
+1

**Comment by NerdPad** [comment]
+1

**Comment by peteigel** [comment]
+1

**Comment by melck** [comment]
+1

**Comment by sandstrom** [comment]
+1

**Comment by melck** [comment]
I think this feature should be native, and / or may be add a option to enabling it . When atom is used on multiple projects with variant languages and rules of development, editorconfig is a excellent way to:
* support old projects with weird rules (like encoding ...)
* prevent many mistakes of beginners
* enforce codings standart between projects / language / os

I use projects manager and we can enable per projects settings. A option to handle editorconfig would permit to enforce standarts when we are in context of project.

To finish, I want to spread Atom as default ide at my work but this is clearly something i can't do until we can easily configure project's standarts and store them in git. We need to check quality of our code without depends on configuration of atom stored in computer of lead developer on project.

How could you / we do to implement this and when or for what release ?

**Comment by caseyw** [comment]
👍

**Comment by joefitzgerald** [comment]
I've come full circle on my opinion about EditorConfig support. I think what people are really asking for here is per-project configuration, built-in to Atom (as opposed to being done via a package like https://atom.io/packages/project-manager). So, 👎  on EditorConfig specifically, and 👍  on some mechanism for project settings built-in to Atom.

**Comment by dpwrussell** [comment]
@joefitzgerald https://github.com/atom/atom/issues/5168

**Comment by joefitzgerald** [comment]
@dpwrussell yup, thanks for linking it. That ^^.

**Comment by svoop** [comment]
@dpwrussell I would agree if all our devs used Atom... which is not and never will be the case. I guess the same is true for many if not most code construction sites.

**Comment by dpwrussell** [comment]
@svoop I don't think that was intended for me, but for @joefitzgerald.

I am certainly not advocating that #5168 be instead of EditorConfig support. On the contrary, I think they should be separate. The Atom project specific settings is more to configure things that are specific to Atom and do not really have a generic (like EditorConfig) alternative. A good example is configuration of a virtualenv to use for a project. If I open project-X I want to be in x-env virtualenv for code tab completion etc.

**Comment by svoop** [comment]
@dpwrussell Ah, my bad, I mis-mentioned. Indeed, my remark was for @joefitzgerald.

**Comment by mattscilipoti** [comment]
:+1: to working with the EditorConfig developers to improve support for configuration (for EditorConfig and other, similar packages).

:+1: to making the EditorConfig package a core package (like whitespace).
- It only comes into play if the .editorconfig file exists, otherwise it has no effect.  
- Our team uses many editors.  A common config, that worked across editors, would be wonderful.
- It would give me one more reason to recommend atom.io.

**Comment by kjostling** [comment]
+1 This really helps to comply with framework-specific coding standards when switching between projects.

**Comment by numbergames** [comment]
Apologies if already mentioned, but Github natively supports .editorconfig files and uses the settings there to change code rendering on a per repo basis.  Maybe I'm missing something, but with Atom being so closely affiliated with Github, I was surprised that it lacks support. On the project configuration goals -- perhaps extending the .editorconfig standard (atom-specific options in the file would be ignored by other parsers) would be solution instead of seeing this an either-or decision. But, I'm just an avid user of Atom and not involved in its development so I'm sure there are big complicating factors to my naive suggestion.

Here's a little background on Github support of .editorconfig files:
https://github.com/isaacs/github/issues/170

For anyone (like me until recently) here is the .editorconfig website for examples: http://editorconfig.org/

**Comment by Redsandro** [comment]
@numbergames that's interesting.. it often doesn't work for me. For example, it tabs with spaces even though tab style is set to `auto` and `.editorconf` is set to hard tab.

I need to explicitly install [atom-editorconfig](https://github.com/sindresorhus/atom-editorconfig) and then the rules are adhered.

**Comment by numbergames** [comment]
@Redsandro I think we're saying the same thing. In case there's still ambiguity, my point was that the rendering on *github.com* of a repo is affected by the content of the `.editorconfig` file, if present. The rules syntax is in the link above.  Agree that without that Atom package, `.editorconfig` is ignored by Atom.

**Comment by Moonbase59** [comment]
+1 for getting this in "standard" Atom!

**Comment by dpwrussell** [comment]
I still think that adding this support in core would make sense.

**Comment by GrayedFox** [comment]
>  subscribing.

:confused: 

For those people wondering why you are getting down-thumbed for posting nothing but "subscribed" or "+1" (or a thumbs up ): there is a pretty well established convention on GitHub whereby a user can show their support for an issue or feature simply by adding a "thumbs up" to the original post.

You can even add a thumbs down, if you think it's a bad idea. Cool huh?

This allows the maintainers to quickly see just how many people are keen on an idea and reduces the noise and pollution of the thread, so that comments remain constructive and centred around implementation strategy, estimates, concerns, etc. Posting "me too" or "sounds cool" just means we all have to spend more time searching the page for useful information.

I'm aware of the irony here (that this comment is also not specifically related to the task at hand) - I add it here in the hopes it will promote awareness and prevent further comments of this nature, thus helping to keep it clean.

**Comment by Redsandro** [comment]
> Personally I prefer to opt into coding/development/whatever styles instead of having to figure out how to get my IDE (or team!) to opt out of them, because they (or my work station) inherited some idea/method/principle without thinking about whether it was really needed in the first place.

I'm trying, but I see zero relevance to this discussion. How does support for `.editorconfig` do any of the things you say?

If you, your boss, or your team **decide**(s) that a certain convention **is to be used**, you/he/she/they can write down this consensus in an `.editorconfig` and since most IDE's follow this file, you can prevent every other (new) employee from making those annoying mistakes like using spaces when the team uses tabs or the other way around.

The kind of rules that are inside the `.editorconfig` are the kind of things that are not optional. If you ignore the consensus and make a commit to a repository, you will be asked to fix all the 'choices' you made before a PR is taken into consideration. These rules are stored in the repository not as a thoughtless inheritance, but **on purpose** to prevent these frequently occurring unnecessary little overheads caused by people who are stubborn in their refusal to adhere to the coding style of a given project/repo, or don't even know because their IDE is just set to do tabs, newlines and file endings a certain way. If only there was a way to dictate to Atom and all the other IDE's that the team might use that _this project_ uses _this certain way_, and then transparently adhere to it. (Spoiler: There is. `.editorconfig`.)

Although you could argue that this falls under the category of _"plug in what you need"_, I think many of us think that Atom in it's core already makes default decisions like tabs/spaces/eol/eof and while you can change the defaults, the defaults should (optionally) come _from the project_ so you can work on multiple projects at the same time without changing the settings again and again. 

**As long as Atom can write 4 spaces in stead of 1 tab when hitting the tab button _without a plugin_, it too should have a way of reading _whether or not that's actually wanted_ for a certain project _without a plugin_.**

Thus, it makes sense for Atom to support `.editorconfig` out of the box indeed.

**Comment by Redsandro** [comment]
@stale bot I think this can be marked as triaged, because the feature is not there. Can you ask a human for some triage labels?
