### ISSUE TITLE
Startup Performance: Why are we compiling modules all the time?

### ISSUE THREAD

**Issue by mehcode** [atom/atom#6593]
```
atom --profile-startup
```

![screenshot from 2015-04-30 14 55 40](https://cloud.githubusercontent.com/assets/753919/7426838/dfa9575c-ef83-11e4-97c2-46600d3ba4bc.png)

---

From the above it looks like we are compiling coffee script modules (see the 90+% of `Module._compile`) each time we load. If that is true, is there a way to alleviate this (isn't that what the coffee cache is supposed to be doing)? Or am I just seeing smoke here. For the record this happens no matter what (multiple startups, `--safe`, etc.).

**Comment by tolmasky** [comment]
Unless there is an identically named method special to atom, Module._compile is a node thing, unrelated to coffee script: https://github.com/joyent/node/blob/master/lib/module.js#L380. Its expected to be run for every required file. it *is* the running of the file (as well as js parsing/etc).

**Comment by mehcode** [comment]
For some reason, I was under the impression that the function was how the coffee compile hook was implemented. If its not then forget my comments.

The point still stands that we should look at this lovely profile (thanks @kevinsawicki) and figure out how to remove the few big numbers.

**Comment by kevinsawicki** [comment]
Just want to mention that running `atom --profile-startup --safe --one` is a good command to know and try as well.

This runs Atom without non-bundled packages and with deprecated APIs removed which gives a better picture of startup improvements that can be made from this repo.

**Comment by mehcode** [comment]
@kevinsawicki For completeness I ran that command. Not much difference.

![screenshot from 2015-05-04 16 50 58](https://cloud.githubusercontent.com/assets/753919/7464992/ca005d40-f27d-11e4-82b1-1fee98b19e57.png)

**Comment by mehcode** [comment]
Just had a random thought? Why don't we do what chrome / chromium does and run a background process that can spawn an atom window without all this startup time lag?

**Comment by kolis** [comment]
Yes, once the application is running there should be very little overhead to open new windows. This is currently not the case.

**Comment by lycon2014** [comment]
Which version

**Comment by lycon2014** [comment]
I'll be back I have something

**Comment by benogle** [comment]
cc @as-cii

**Comment by fuzzy76** [comment]
FWIW, this is still the case

**Comment by gmallard** [comment]
And it is still the case.

Atom starts on my OSX system take over 100 times what I can settle for.  I expect editors to start sub-second.  vi does.  VSCode comes close.

Atom can take 2-3 minutes.

Please give this some priority.

**Comment by MoritzKn** [comment]
The node team already worked on improving the performance of the `Module.prototype._compile` function and the time spend requiring modules in general: nodejs/node#5172. Hover, because [Atom overrides the `Module.prototype._compile` function](https://github.com/atom/atom/blob/master/src/native-compile-cache.js#L42) form node, not all of these improvements apply to Atom. For this reason the [replacement of an regex regex with a manual parsers](https://github.com/nodejs/node/pull/5172/files#diff-d1234a869b3d648ebfcdce5a76747d71L381) from the mentioned PR does not apply for Atom and with it the potential performance boost. I thought about porting these changes to Atoms own `Module.prototype._compile` function, but found out that #13916 reduced the amount of calls to nodes require function (and therefore calls to `Module.prototype._compile`)  *a lot* by caching snapshots. Now the `Module.prototype._compile` function is invoked only around 20 times during startup. Therefore optimizing this function wouldn't produce a significant performance increase.
I think this issue can be closed.

**Comment by MoritzKn** [comment]
I have to correct myself the snapshots are only created for build in modules. For community modules there is probably still some space for optimization.

**Comment by gmallard** [comment]
A few comments.  There has been quite a bit of improvement since my last post.

I just stay up to date with new versions.

I am currently seeing project start times in the 2-3 second range on OSX.  Which I can live with.

I am sure further improvements can be made, but it is much better than it was.

**Comment by 50Wliu** [comment]
> I am sure further improvements can be made

Just wait a few more versions :wink:.  We have some awesome PRs that will be helping startup speed such as #14080, #14038, #14024, #13949, #13940, #13916, and more!

#14080 might also be enough to close this issue.
