### ISSUE TITLE
Developer tools won't open

### ISSUE THREAD

**Issue by codepuncher** [atom/atom#6597]
Recently started having an issue where whenver I launch developer tools, it doesn't show anything.
It shows that the window is in fact "open" in my taskbar, but doesn't actually have anything inside of it.
![atom-devtools](https://cloud.githubusercontent.com/assets/8135396/7430791/7f4c5d46-f00f-11e4-9918-3ce196cae51c.jpg)

Things were working fine when I was on 0.194 (am on 0.196 at the moment)
Atom v0.196
Windows 7 Pro SP1 x64

Disabling all packages and using default themes make no difference either.

Anyone else having this issue?

**Comment by reubn** [comment]
+1

**Comment by diagramatics** [comment]
+1 too, and I'm running on Windows 10 with Atom 1.0.3.

Is it docked or in a separate window? If you focus on the Developer Tools and press Ctrl+Shift+D (a shortcut for docking it to the editor) it might appear. Worked for me, but if it's on a separate window this would happen.

Steps to reproduce since it's needed:
1. Open DevTools
2. If DevTools is opened as docked on the editor, Ctrl+Shift+D or undock it to a separate window
