### ISSUE TITLE
Error while loading shared libraries: libchromiumcontent.so

### ISSUE THREAD

**Issue by baelter** [atom/atom#6633]
The 0.196.0 release does not run on Linux 3.16.7.9-1-MANJARO when built from source using the atom-editor package from AUR.

Install runs without errors but when trying to open atom I get:
`/usr/share/atom/atom: error while loading shared libraries: libchromiumcontent.so: cannot open shared object file: No such file or directory`

Rolling back to 0.194.0 saved my day.

**Comment by lee-dohm** [comment]
> when built from source using the atom-editor package from AUR.

What does this part mean? Did you not build Atom from source at https://github.com/atom/atom? If not, why not?

**Comment by baelter** [comment]
It means I installed it with pacman using this package: https://aur.archlinux.org/packages/atom-editor/

**Comment by izuzak** [comment]
@baelter Do you see the same problem if you git clone https://github.com/atom/atom and follow the [build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md)?

**Comment by baelter** [comment]
Worked fine, thanks. Sorry for filing the issue at the wrong place.

**Comment by baelter** [comment]
Just uninstalled atom-editor package via pacman and cloned and built latest tag from source. All build steps was successful but still get the same error when trying to run atom.

**Comment by baelter** [comment]
Using a precompiled package (https://aur.archlinux.org/packages/atom-editor-bin/)  worked fine.

**Comment by KapuzenSohn** [comment]
Having the same Porblem with Atom 0.196.0
I followed the Build instructions, no Errors. When I try to start Atom with ```atom .``` the following Error comes:
```/usr/local/share/atom/atom: error while loading shared libraries: libchromiumcontent.so: cannot open shared object file: Error 40```

When I now look in the ```/usr/local/share/atom/atom``` it redirects me to ```/usr/local/share/atom```. Here I can see the missing file.

I am using Ubuntu 14.04
Node version: v0.10.38
Npm version: 2.9.0

Just tested to start Atom with ```sudo``` this works fine. But I think this is not the fine way. I hope this helps to solve the Problem.

**Comment by theNth** [comment]
I encountered the same issue with Atom v0.190.0. After building Atom as per the directions in docs/build-instructions/linux.md, I tried to run Atom out of the directory /usr/local/bin resulting in the message:
/usr/local/share/atom/atom: error while loading shared libraries: libchromiumcontent.so: cannot open shared object file: No such file or directory

At least for me, the file libchromiumcontent.so really did exist in /usr/local/share/atom. After searching around in /usr for a couple minutes and comparing with the directory structure from a separate version of atom that I installed with apt-get, I noticed that my /usr/local libchromiumcontent.so didn't have the read permission set for all users. Changing the permissions to 644 led me to a new error which I solved in a similar manner. After a couple more iterations of this, I gave up and ran
sudo chmod +r -R
in /usr/local/share/atom. After doing this, Atom worked as expected. 

It appears that there's a bug in the build script that creates the /usr/local/share/atom directory with incorrect permissions. However, I haven't tracked down where that bug is; I have some more pressing things to do right now.

Linux version: Ubuntu 14.04
node version: v0.10.25
npm version: 2.10.0
