### ISSUE TITLE
Autoindent not working properly

### ISSUE THREAD

**Issue by muppetjones** [atom/atom#6655]
Version: 0.192.0
## Problem

1) `autoindent` fails to indent parameter lists. Note: If I hit enter after `fake_function(`, `param=` would be indented 3x -- class > def > foo.

``` python
class Bar(unittest.TestCase):
    def test_indentation(self):
        foo = fake_function(param='hello',
        second_param='world', # should have indented this line
        ) # and this one, too
```

After saving, `atom-beautify` correctly indents the parameters

``` python
class Bar(unittest.TestCase):

    def test_indentation(self):
        foo = fake_function(param='hello',
                            second_param='world', # fixed!
                            ) # me, too!
```

2) But now, `autoindent` fails to reset indentation back to the beginning of the line

``` python
        [...]
        foo = fake_function(param='hello',
                            second_param='world',
                            )

                            bar = 'after_continuing typing' # ach!!
```

Unfortunately `atom-beautify` doesn't quite fix this ever time.

``` python
        foo = fake_function(param='hello',
                            second_param='world',
                            )
            bar = 'after_continuing typing'
```
## Note

I recently updated atom-beautify as an attempt to help resolve the issue, but I am now getting errors there. The problems mentioned above still exist, but I will update if anything changes.
## Update

Here's some testing in 
#### Sublime3:

``` python

def testing_indentation_in_sublime(some_var):
    first_line = "works"
    second_test = func_indentation(multiple_param,
        auto_indents,
        still_here,
        ) # parenthesis auto matched when typed!

    third_test = alt_indentation(
        looks_just_like above,
        which_was_wrong,
        but_this_works,
        )

        fourth_line = existing_indentation('retry last pasting',
                                       'broken') 
        and_indent_is_kept

    fifth_line = backspace_only_does_one_space('testing existing indent',
                                               'testing')
    indentation = "working!!"

    if check_nested_indent is not None:
        basic_indent = True
    elif check_indent:
        also_works = True
        if nested:
            so_far = so_good
        else:
            also_good = True
        else:
            uh_oh = 'is this really that hard?'

    return end_of_function

    def still_indented():
        '''sigh.'''
        indentation = 'not perfect here, either (but way better)'
```
#### Eclipse

``` python
def indent_test_eclipse(some_var):
    first_line = 'smoke test'
    second_test = func_with_param(style_one,
                                  hey_it_works,
                                  )
    back_to_the_beginning = 'holy crap.'
    third_test = func_with_alt_style(
                                     hrmmm,
                                     )

    if nested_indent is not None:
        basic_indent = True
    elif reindents_on_space_not_colon:
        still_okay = True
        if nested:
            so_far = so_good
        else:
            also_good = True
        else:
            must_be_difficult = True

    return end_of_function

def correctly_indents_after_return():
    '''Woo hoo'''

    return True
```

**Comment by muppetjones** [comment]
I updated to 0.198.0, and I still get this problem.

I've found a few other possibly related issues (though different languages, so maybe not):
[javascript](https://github.com/atom/atom/issues/4983)
[coffee](https://github.com/griiin/atom-auto-indent/issues/5)

**Comment by muppetjones** [comment]
After updating to 0.199.0:
```python
def testing_indentation_in_199(some_var):
    first_line = "auto complete enabled by default?"
    second_line = func_indentation(bracket_matched,
    but_indentation,
    still_broken,
    )
    
    third_line = alt_indentation(
    long_param_list,
    still_not_working,
    )
    
        fourth_line = existing_indentation('auto ident paste not turned on',
                                           'so this is expected')
                                           this_is_not = 'indent error!'
                                           
                                    
    fourth_line = existing_indentation('retry last pasting',
                                       'this works fine')
                                       raise IndentationError('ARGH!')
                                       
                                       enter_does_not_clear = 'still bad'

                                       even_with_blank_line = 'tab puts here'
                                    
    if check_nested_indent is not None:
        basic_indent = True
    elif can_you_hear_me_now == False:
        also_works = True
        if this_works:
            no_surprise = True
        else:
            same_here = 'yep'
        else:
            very_frustrating = True
            
    another_test = 'split_line' + \
    'should be indented' + \
    'at least once'
    
    return check_this
    
    def still_indented(other_var):
        '''Yay.'''
        indentation = 'hopelessly broken'
```

**Comment by muppetjones** [comment]
Not just python:

### C++
```c++
void main() {
  bool does_indentation_work = 1;
  if (does_indentation_work) {
    printf("woot");
  } else {
    printf("ugh");
  }

  if (alternate_style_indentation)
  {
    printf('still works');
  }

  else {
    printf('hmmm...');
  }

  int test_function = function_with_param(this_param,
  that_param
); // strange dedent after typing semicolon

  int test_function = function_with_param(
    this_param,
    that_param
  );

  int test_function = function_with_proper_indent(param1,
                                                  param2,
                                                ); // strange dedent again
                                                uh_oh = 1;

                                                still_after_blank_line = 1;

  return;                                                
}
```

**Comment by nmccready** [comment]
Whomever is in charge of this should look at https://atom.io/packages/atom-beautify . As the indenting works perfectly there for CoffeeScript.

**Comment by muppetjones** [comment]
It does work great--for python, too. I would not be using Atom (in the current state) without it.

**Comment by nmccready** [comment]
Yes atom-beautify is pretty much what kept me on atom. My biggest pet peeves w/ atom are:
- indenting issues
- many bogus plugins (there should be some kinda QA checking for defects/deprecations to warn you)
- (non) handling of large files

**Comment by muppetjones** [comment]
@nmccready Yes, yes, and yes. Though the [`view-tail-large-files`](https://atom.io/packages/view-tail-large-files) package helps with the last one.

**Comment by nmccready** [comment]
Yeah I have used the large file thing.. but then just use tail or vim. It would be nice if you could stream or handle files similar to vim. I am trying to convert to vim, but learning all the cryptic keyboard 'shortcuts' is sucking my life force. Not to mention vim's plugin space is ripe with crud as well.

**Comment by AsaAyers** [comment]
http://vim-adventures.com/ is a great way to learn and you build up instead
of being presented with everything at once.

I actually switched from vim to Atom with vim-mode. It doesn't have all of
vim's shortcuts, but it has almost everything I care to use.

**Comment by alexandernst** [comment]
Same issue for JSON: https://github.com/atom/language-json/issues/20

**Comment by muppetjones** [comment]
I'm honestly surprised this hasn't been addressed yet. Technically, it is a minor bug, but it's a huge frustration if you're doing any sort of coding.

I love Atom, but honestly, if there was another viable option, I would switch to it because of this bug alone. I'm hoping it'll be fixed soon.

I haven't had any extra time to sit down and see if this is something that could be fixed with a plugin. Again, does anyone have any leads on where to start looking for fixing this bug?

**Comment by mattdeboard** [comment]
This seems to be a duplicate of atom/language-python#22

**Comment by ttsirkia** [comment]
I think this is somehow related to this problem:

```javascript
var a = {
  foo: {
    a:1, b:2}
  };
  
  var b = 2;
```
If the contents of `foo` are in the different line (as in the example), `var b` is indented incorrectly. If I change the code so that `foo` is only a single line, everything works.

**Comment by eexit** [comment]
Also having this issue while typing some well indented JavaScript. This is really annoying :(

**Comment by GradyD** [comment]
For my package, https://atom.io/packages/sfdc-toolbox, if I paste in some code it does not auto indent. If I go to edit > lines > Auto Indent it fixes the file.

**Comment by JulianLeviston** [comment]
Same issue in clojure... https://github.com/atom/language-clojure/issues/23

**Comment by JesseLeite** [comment]
I'm noticing indenting inconsistencies as well, and I'm not convinced it's related to the 'Auto Indent' setting.  Here are a few examples, with all community packages disabled (in case of package conflict)...

PHP with Auto Indent enabled:
![1](http://g.recordit.co/Ap2vV3QE0o.gif)

JS with Auto Indent enabled: (the only one that behaves as expected)
![2](http://g.recordit.co/AO2DQLI3bE.gif)

PHP with Auto Indent disabled:
![3](http://g.recordit.co/ZosuEkxuBD.gif)

JS with Auto Indent disabled:
![4](http://g.recordit.co/g7PYTzrbyI.gif)

There is clear inconsistency when pressing enter between brackets :(

**Comment by JesseLeite** [comment]
See PR here: https://github.com/atom/language-php/pull/96

**Comment by envygeeks** [comment]
/cc #8576

Adding that we would like to be able to disable auto-indentation when we start typing period.  Atom should not be trying to indent in the middle of typing assuming it knows better than you where you want to format your code.

**Comment by Zireael07** [comment]
+1 to disabling auto-indentation while typing.

**Comment by muppetjones** [comment]
I like and prefer auto-indent while typing, but it depends on how you identify "typing"--hitting `ENTER`?

In a bash script, for instance, if I have a variable that starts with `fi`, it will auto-deindent immediately after typing the `fi`. This happens despite the fact that I have the autocomplete set to three, so it shouldn't mess with it at all

**Comment by JesseLeite** [comment]
Ultimately, it is a user option, and the user should have that choice.  The editor should behave as expected, based on that choice :)

**Comment by cunhaax** [comment]
Atom simply doesn't have autoindent, they should remove this from the editor because THIS DOESN'T WORK at all!
Autoindent is really a mess in html files...
I'm starting to look for alternatives.. maybe vim?

**Comment by socketubs** [comment]
Python auto indent seems to be still broken.

**Comment by 50Wliu** [comment]
@socketubs This issue is still open, therefore it hasn't been resolved yet.

**Comment by alexandernst** [comment]
@50Wliu This issue is, IMHO, very big/important as it affects most of (all?) the languages that Atom supports. Is there anybody working on it/making any progress?

**Comment by socketubs** [comment]
@alexandernst @envygeeks I agree with both of you. :+1:

**Comment by alexandernst** [comment]
@envygeeks Yeah, we all agree that Atom is still far away from being the ultimate editor. Anyways, except the slow start, all other issues affect only 1 OS (which I use, btw), while this issue affects all OSes and all languages, so that makes it kind of more important.

**Comment by 50Wliu** [comment]
@alexandernst To my knowledge there is no one working on this bug.  I'll mark it as `help-wanted`.

**Comment by GetContented** [comment]
@envygeeks There's an argument for user-facing bugs being more important than system-related ones. An example is a designer friend uses an old crashy piece of software because it's vastly better than all the new stuff for him. He's happy with it crashing ten, twenty times a day. He knows what to do - he just restarts it. To technical people such as us, that's abhorrent, but to him, it's workable. 

To an ordinary user, having a feature not work properly is usually vastly more problematic than having a system-related bug.

**Comment by chfritz** [comment]
+1
I'm sorry, but wrong indentation is a deal breaker for me. I cannot make atom my editor if I cannot rely on it to tell me the scope in which I am currently.

I have taken a look at the language-mode.coffee file and tried to fix at least one issue but failed. The issue I noticed is with multiple blocks ending on the same line in javascript which is not handled correctly (indentation is not reduced by more than 1). This case seems to occur because of the way the indentation logic in language-mode is written: I'm not sure, but it seems to me that the logic only checks whether there is a scope that ends in the previous line, not how many.

I'm happy to try and help fixing this if someone can tell me how to go about it (e.g., how do I develop atom.io without having to rerun scripts/build all the time (which is slow)). I haven't been able to find a developer forum for atom where to ask that question.

**Comment by 50Wliu** [comment]
> how do I develop atom.io without having to rerun scripts/build all the time

Clone Atom into the `~/github/atom` folder (or if you already have Atom cloned somewhere else, set the `ATOM_DEV_RESOURCE_PATH` environment variable accordingly).  Then just start Atom with the `--dev` parameter: `atom --dev`.  After making a change reload Atom (View -> Reload, or in future versions of Atom View -> Developer -> Reload Window) for the changes to take effect.


> I haven't been able to find a developer forum for atom where to ask that question

The Atom Slack is a great place to ask developer questions (get an invite at https://discuss.atom.io/t/join-us-on-slack/16638/1).  Discuss (https://discuss.atom.io) is also very active, and as a last resort feel free to create an issue here.

Also, don't forget that each language has its own indentation rules defined in the `settings` folder (eg for language-javascript: https://github.com/atom/language-javascript/blob/master/settings/language-javascript.cson#L5-L12).

Thanks for taking this on!

**Comment by chfritz** [comment]
Thanks, 50Wliu.

I have reworked the logic in language-mode a little as seemed necessary. In particular I'm counting the number of scopes being opened/closed rather than just checking whether a scope is opening or closing. I've also updated the settings.cson for a number of languages. The examples mentioned in this issue all seem to be addressed by that. But now I need to figure out a way to get this into master. Since the language packages are separate git repos I don't see how to best coordinate that. For now I'll just create separate pull request.

A lot of what went wrong, btw, is a result of the introduction of the decreaseNextIndent concept, which hadn't been absorbed by the language packages yet.

**Comment by 50Wliu** [comment]
> But now I need to figure out a way to get this into master. Since the language packages are separate git repos I don't see how to best coordinate that. For now I'll just create separate pull requests.

I see you also mentioned `decreaseNextIndent` - I believe @svanharmelen introduced that, and he first created a pull request for atom/atom as well as a corresponding PR in language-go to demonstrate its use.  I would suggest following that as well (maybe choose Python because of the prevalence of Python auto-indent issues?), and if the PR gets accepted, to then add extra PRs to the remaining languages.

**Comment by chfritz** [comment]
@50Wliu, thanks for the suggestion! I did that, but used javascript as the example, since python is a whitespace-sensitive language, which means that python files cannot be auto-indented deterministically

https://github.com/atom/atom/pull/10367
https://github.com/atom/language-javascript/pull/300

**Comment by svanharmelen** [comment]
Did you check out #6808? It's a good read about the process that let to the final changes of the current auto-indent code.

I started with a completely different approach counting matches from the last increase (iirc), but the back tracking was assumed to be too heavy and would not improve the overall performance of Atom and so I continued to find a different, slightly less perfect way which in the end "seemed" to work for all cases.

At least it got through all known tests at the time...

**Comment by chfritz** [comment]
Thanks for the pointer @svanharmelen, I wish I had read that earlier. Not sure why I hadn't yet come across that. It helps a lot, both in understanding the rationale for your code and naming, and in setting expectations on how long it can take to get something like this merged.

Based on this I've also made another change to my PR, that will ensure a smoother transition for language packs.

https://github.com/atom/atom/pull/10384

**Comment by pvorona** [comment]
cant wait it to be fixed

**Comment by chfritz** [comment]
We are trying to come to an agreement on how to move forward. This is being discussed in PR #10384.

**Comment by chfritz** [comment]
@muppetjones I'm working on this. Unfortunately it is quite hard to get my pull request accepted because of some disagreements on which is the lesser evil in a case where not all requirements can be met.

For now what I have done is to go with a monkey-patching approach, i.e., you can adopt (and thereby vote) for my new logic by installing this package:
https://atom.io/packages/sane-indentation

This addresses some of the issues you pointed out about C/C++ and it also handles your original python code correctly (I believe):

![untitled](https://cloud.githubusercontent.com/assets/4239098/13545912/8ab82172-e250-11e5-928a-1483a1501c5c.gif)

My own motivation for this was javascript, which now seems usable.

Right now that package *only* supports c/c++, python, and javascript, but it's quite easy to add additional languages, so I'll proceed by trying to pick and fix the languages for which people have reported problems.

Please note that the indentation in my logic is not perfect either. But at least it is "sane", by which I mean that it doesn't get out of whack uncontrollably (the indentation does not increase arbitrarily for no reason).

Please let me know if you run into issues with it.

**Comment by frog42** [comment]
Today is the day it really started annoying me.  How do you mess up auto-indenting so amazingly?  Sublime Text did it perfectly, but I prefer the other features of Atom.

**Comment by facundoolano** [comment]
This completely impedes clojure programming for me, I guess it's back to Sublime, at least for a while.

**Comment by Zireael07** [comment]
I'm running into this when doing programming in Lua.

**Comment by Rockster160** [comment]
Agreed everywhere that says this is something that should be an editable option. Something like

Greatly desired functionality, I hoped @chfritz 's monkey patch would solve it- but no go. 
```
some_function(
with_a,
list_of,
parameters
)
````
Expected auto-indent:
```
some_function(
    with_a,
    list_of,
    parameters
)
```

**Comment by muppetjones** [comment]
@chfritz A little late back to the party, but I'll check out the monkey patch. Thanks for giving it a go!

**Comment by dan-higgins** [comment]
Can we please get this other ticket reopened? 
https://github.com/atom/atom/issues/8576#issuecomment-327645628

It's a much simpler problem to solve, and actually prevents Atom from being so annoying by messing up indentation on a line I'm just editing.

**Comment by phillynch7** [comment]
Adding my gif from #17015 to show an example from python:
![atom_tabs](https://user-images.githubusercontent.com/15858076/37781397-012c1a3e-2dc7-11e8-9362-c82949a62cb1.gif)

**Comment by jerome-diver** [comment]
For me, on linux atom installation version 1.35.1-1, this seems to be bugged again (since 2015 !).
For python language.
How is it possible to seriously use an editor for development if this one is just not able to correctly indent code ? (this is a big waste of time and a big frustration too).
Also, i use the vim-plus-plus package to try to get vim style short keys (but it is far to be vim or eveil mode in emacs).
So please, tell me if i can hope to see an evolution or if i have to uninstall it and put it inside "derecated" editor list ?

**Comment by chfritz** [comment]
@jerome-diver you may want to check out my [sane-indentation package](https://atom.io/packages/sane-indentation). I built it because I agree, an editor whose indentation confuses more than it helps is a non-starter. I have a [PR waiting to be merged into atom-core](https://github.com/atom/atom/pull/18321) that would make that behavior standard, but until that is merged you can use the package to get back some, uhm, sanity. As a caveat, I haven't tested python too much, so feedback is very welcome and will only make it better.
