### ISSUE TITLE
PHP files are no more colorized since 0.198

### ISSUE THREAD

**Issue by unicolored** [atom/atom#6701]
My PHP files are no more colorized since this morning. Works well yesterday.
Seems weird since 0.198 said "Fixed an issue where certain PHP files would not be colorized"

I tried to change the theme, to update again, to reload 0.197. Nothing works, any idea ?

**Comment by thomasjo** [comment]
It would be really great if you could provide us with a minimal example file that demonstrates the problem, as well as a screenshot of the problem. Thanks!

**Comment by jccrofty30** [comment]
I have experienced a similar issue, but with short-tags only. The issue seems rather "flukey".

If there are no spaces between an element and a short-tag opening there is no syntax highlighting for the rest of the line (i.e. <strong><?=date('l', strtotime($day))?></strong>).

However, placing a space before the opening tag corrects the issue (i.e. <strong> <?=date('l', strtotime($day))?></strong>).

It is the same issue anywhere there is a short-tag.

**Comment by unicolored** [comment]
I do not use shorttags. This is a screenshot of atom.
![Atom Screenshot](http://gilleshoarau.com/error_php.jpg)

I'll try to disable some packages relative to php now.

**Comment by unicolored** [comment]
Ok, i just click again the update squirrel, and it works. Fine.

**Comment by benogle** [comment]
@jccrofty30 can you open an issue on https://github.com/atom/language-html about the short tag problem? (yes, lang-html, not php!)

**Comment by jccrofty30** [comment]
Yes I will.
