### ISSUE TITLE
All atom terminals haven't sudo ability in ubuntu 14.04

### ISSUE THREAD

**Issue by asiniy** [atom/atom#6702]
Hello!

Firstly, I thank this is an `term2` package error: https://github.com/webBoxio/atom-term2/issues/118 but after little research I've understood that this is an all atom terminal plugins error, so `term` or `quantum-shell` plugins raise this error too.

When I try to implement any `sudo` command, I get this:

``` bash
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

How can I avoid this error? What's going wrong with my atom?

**Comment by sedabull** [comment]
@asiniy, Hello! I am not a member of atom/core, however I am the author of `quantum-shell` and I can tell you there is nothing wrong with your atom. This is a technological limitation that presents itself in all terminal packages. A truly interactive shell is very complex (and that's without throwing `sudo` commands in there), because there isn't an easy way to take user input and give it to the underlying processes. I hope to see this limitation overcome someday, however for now packages like `terminal-status`, `terminal-panel`, `quantum-shell`, and so on are really for output only operations. I hope that answers your question.

**Comment by asiniy** [comment]
@sedabull thanks you for your reply. It seems strange, because of on previous versions of atom `sudo` in `term2` worked well.

**Comment by ethe** [comment]
i also have this problem: `sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

**Comment by tebanep** [comment]
Same here with Kubuntu 14.04

**Comment by feber** [comment]
Same here Linux Mint 17.2 x64

**Comment by asiniy** [comment]
Hm. Good news guys!

I've installed `1.1.0` atom and `sudo` is working on both `term2` & `term3` packages.
