### ISSUE TITLE
Keymaps file is a hot mess to deal with.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#6718]
At the end of the day a user has to track down where and what needs to be overriden and it makes it hard considering there are a lot of things that scope in a lot of places, right now my keymaps file has 6 different selectors to override a few short keybindings I don't like.

Could we please get an easier way for users to override keymaps in that we shouldn't have to track everything down, \* should override all (which it currently doesn't at all...) and can the keymaps file support sub-selectors as a sub-key on the cson?

Here, let me clarify:

``` cson
"*"
  "ctrl-:": "comment-headers:insert"
```

The above should override anything that wants to use ctrl+shift+; but it doesn't, I have to scope under ".platform-linux atom-text-editor" but then things become a mess because in order to override "pageup" and "pagedown" I have to scope under ".platform-linux", which means I have two similar keys but one with an added scope.

Now I could be doing it wrong but when I tested with sub-selectors in the CSON it didn't work and neither did just doing "*".  It would be nice if this could be sorted out because users are used to working in specific ways so it becomes a side-job to manage a keybinding that has so many different scopes in so many different places.

**Comment by mnquintana** [comment]
It sounds like you're looking for the keymaps equivalent of CSS's `!important` flag then?

**Comment by envygeeks** [comment]
Pretty much, doesn't have to be exactly that description but just a way to tell Atom: "my keybindings are more important than anything anybody else wants since this is my environment!"

**Comment by mark-hahn** [comment]
Just do ...
```
"body":
  "ctrl-:": "comment-headers:insert"
```

**Comment by envygeeks** [comment]
That's just another workaround to another mess.

**Comment by mark-hahn** [comment]
> That's just another workaround

I'm not sure I understand.  Does it work or not?  Do you have a solution in mind that is easier?  I can't imagine an easier one.

**Comment by envygeeks** [comment]
What I meant by my comment was what you supplied was an example of what I was complaining about, the multitudes of ways to override things without anything being set in stone as to what is the most important and what is the "one that rules them all".  It was another workaround to the problem that I see as a problem (though all might not see it as a problem.)

I will test your solution though (I didn't mean to imply I won't -- I just haven't had time -- and because I'm hoping it will suffice for all my problems!) but at the end of the day it would be nice for users to have a single selector that implies what I said and what @mnquintana clarified.

**Comment by mark-hahn** [comment]
> the multitudes of ways to override things without anything being set in
stone as to what is the most important

Atom is built on nodejs and the DOM.  I can't think of any environment with
more ways to do things.  (grin)

**Comment by lee-dohm** [comment]
I agree with @envygeeks, that there should be an easy way to *definitively* override a key in all situations, scopes or what-have-yous :grinning: And we should probably use that method in all the introductory examples on keymaps in the documentation so people get what they want the first time :metal:

**Comment by envygeeks** [comment]
This is what I had to do to finally get everything targeted:

```
.platform-linux atom-workspace atom-text-editor, .platform-linux atom-workspace atom-text-editor:not([mini]), .platform-linux atom-workspace body, .platform-linux atom-workspace, .platform-linux body, atom-workspace atom-text-editor, atom-workspace atom-text-editor:not([mini]), atom-workspace body, atom-workspace, body
```

That allowed me to scope everything, I tried it @mark-hahn's way and it didn't work out, I ended up just figuring out where everything I use scopes out and how.  That's a lot of places where things are inconsistent making me have to make up for it, and then that's a lot to have to deal with for a new user IMO.

**Comment by thedaniel** [comment]
Keymaps in general need a bunch of polish, imo even a rethink from first principles. I think in the short term we should most likely provide UI / settings-view help for users that will take simple user actions and just write the (often unwieldy) keymap declarations.

**Comment by envygeeks** [comment]
I would love a UI!

**Comment by crucialfelix** [comment]
Someone could write a package with a UI that manages your keymaps.cson for you.

The selectors are a great way to implement keybindings, but its not fun to write them out manually and conflicts are frustrating. The need for more and more selectors (!important?) smells like an anti-pattern.

The UI would:

- Show key binding resolver without doing the action, 
- You can click to select which command gets priority
- Browse keybindings by name, package, key, modifier
- show what language scopes they are active in, (if and when we can scope them)
- learn key strokes

**Comment by envygeeks** [comment]
Learning keystrokes would be drastically annoying, as a programmer I'm not interested in my editor learning my keystrokes, I'm interested in it getting shit done and the UX to that learning were horrible and in the way then it just degrades speed and it's also prone to fat/new-finger annoyance.

New finger being I just got a new keyboard and most keyboards that are Mac's (and even Mac's now) have slightly different keyboard sizes this can even happen with like keyboards (in that I have two like computers -- one with a damaged key, I always miss that key because somehow my fingers can precision where a key should be on that keyboard.)

I don't think this should be an addon though, unless it plans to be a default addon because then it doesn't solve the problem, it merely offers you to opportunity to solve it, which puts it into the screw it I'll waste the time myself category so it definitely has to be a default addon IMO just so I'm forced to care about the addon and to use it.

**Comment by tmunro** [comment]
This isn't a perfect solution, but this change makes it easier to mass disable unwanted package keymaps: https://github.com/atom/atom/pull/8130

**Comment by mauricioszabo** [comment]
My problem with atom keymaps is that keymaps defined by me should **always** take precedence over others. These are the problems that I have:

1. I have an editor open and update vim-mode package (or other package that defines keymaps). Somehow, when Atom reloads the package to use the updated version, their keymaps take precedence over mine - I need to reload the whole editor so that it uses mine
1. Today, I updated atom and discovered that some keymaps in the past were namespaced in `atom-workspace`, and now are on `atom-workspace text-editor`. This means that (1) - my keymaps are not being used because they are in a more "generic" namespace and (2) - I now need to COPY AND PASTE a bunch of keymaps so that they work on editor AND on panes like Package Manager and Settings View...

I'm **very** upset by that second behaviour - somehow, I need to know the whole namespace of every keybinding I want to remap, and then I need to think of a more specific one, or put it in the same namespace and hope that things work right... 

Please, make a way for user-defined keybindings to **always** take precedence over Atom's ones, even if it is in a generic namespace. This is breaking my keymaps for every update I do in the editor **and** in the packages...

**Comment by envygeeks** [comment]
:100: on that, I've been upset by that behavior as well.

**Comment by fallanic** [comment]
+1

**Comment by bronson** [comment]
Plus, if I have two or more of the same selector in a file, the last selector deletes the mappings created by all the others.

For example:

```
'atom-workspace':
  'ctrl-cmd-t': 'rspec:run'
...
'atom-workspace':
  'ctrl-i': 'cursor-history:next'
```

You'd think that `ctrl-cmd-t` and `ctrl-i` would both be mapped.  Nope!  Because it's CSON, the last selector in the file wins out and the others are ignored.  `ctrl-cmd-t` is unmapped.

This means that I need to organize my keymaps file by selector, not by category or function.  That quickly turns into a steaming hot mess.

I notice that https://github.com/atom/atom-keymap/issues/81 was closed NOTABUG.  That's unfortunate.

**Comment by crucialfelix** [comment]
A cson linter would do the trick

**Comment by bronson** [comment]
True, a linter would prevent mappings from getting silently lost, but it wouldn't allow organizing keymaps files more sensibly.

**Comment by envygeeks** [comment]
I don't know that Atom could solve that (unless you are using multiple files) because that's a problem in the CSON parser itself and the way all double defines work ultimately... however, I like the idea of having multiple keymap files where this can happen because that is the max of organization for users.

**Comment by lee-dohm** [comment]
I agree that the better solution is multiple keymap files.

**Comment by bronson** [comment]
Yes, letting packages have their own local keymaps file sounds great.  I'd name them after the packages that they're modifying:

     ~/.atom/keymaps/project-find-navigation.cson
     ~/.atom/keymaps/vim-mode-plus.cson
    ...

Bit of speculation: then the package's settings pane could have an "Edit Keymaps" button.  When clicked, it would copy the package's keymaps file to the user's keymaps directory (if it doesn't already exist) and open for editing.  That would make overriding a package's keymaps a 5 second process and much more friendly to new users.

**Comment by danielbayley** [comment]
+1 to the last idea.

I'm currently trying to modularise my keymap utilising [multiple-keymaps](https://atom.io/packages/multiple-keymaps) but I haven't managed to get it working yet…

This should just work out of the box with any `.cson` file inside `ATOM_HOME/keymaps`

**Comment by danielbayley** [comment]
> I agree that the better solution is multiple keymap files.

My [modular-keymaps](https://atom.io/packages/modular-keymaps) package has been working well for me. I put all my custom keymaps organised across multiple files inside `ATOM_HOME/keymaps/` and it will automatically reload them on any changes.

Keymaps are a mess in general. I also think packages that include their own `package-name/keymaps/` should install with them disabled by default, to be enabled manually in their package settings.

**Comment by xh3b4sd** [comment]
Is there any update on this issue? I love Atom. Getting key bindings and the user experience right is quite important to us. I see there are so many hacks to work around this problem like there are users. I am also not a fan of something like `!import`. It stops make you thinking about what you are doing and at the end you are using this everywhere and wonder why nothing works anymore. It would be cool to learn from years of CSS incompatibility in internet explorers. Instead of such hacks there need to be a clean structure and users need to be educated to follow best practices on how to structure selectors. When there is a clean approach that lets users structure selectors in a convenient and easily understandable way, then there should be no need for something like `!important`.

Here you see the selector I am currently using to configure key mappings as I would like to use them. Note that I am using Atom since only three days, so this selector will grow over time.

```
'.platform-darwin, .platform-darwin atom-text-editor, platform-darwin .command-palette atom-text-editor, html body atom-text-editor, html body atom-workspace, atom-text-editor.vim-mode-plus:not(.insert-mode)'
```

From a user perspective I see lots of correct things that have been mentioned here already. 

- User defined key mappings should overwrite everything. I am sure this has potential to screw everything up. At the end the user needs to know what he is doing. There could be a notification ones, to make the user aware of overwriting system or native key bindings. Anyway, when I define a key mapping, I expect it to work. Then, I do not want to hustle with stuff other packages defined. 
- The feature of disabling key mappings on the package level is cool. What I miss is the ability to disable/enable separate key mappings per package. This can be done using a checkbox. 
- Organizing key mappings based on semantical grouping does not work at all. You only can define one selector ones. A second definition overwrites the former one. That way it is not possible to place custom keybindings per installed package into separate files. This would make the life of a user way more easy.

**Comment by bronson** [comment]
Have you looked at @danielbayley modular-keymaps plugin?  That should solve one of those three bullet points.

(I haven't tried it myself but it's on my todo list)

**Comment by danielbayley** [comment]
@xh3b4sd Yeah, my [modular-keymaps](https://atom.io/packages/modular-keymaps) has been working well for me for a while! Although I agree this should probably be in core… I might do a PR if I get chance.

**Comment by 50Wliu** [comment]
> User defined key mappings should overwrite everything.

I believe this is now the case starting with Atom 1.12.0.

**Comment by xh3b4sd** [comment]
Is there any documentation on this? What issue/PR achieved that?

**Comment by 50Wliu** [comment]
https://github.com/atom/atom/pull/12760

It's also listed in the notable changes section of 1.12.0-beta0.

**Comment by balderclaassen** [comment]
Can this issue be closed then, since "user-defined keybindings take precedence" now. Or is there something else this issue addresses that isn't fixed yet?

**Comment by 50Wliu** [comment]
Yes, I believe the main issue has been addressed.  Feel free to create follow-up issues for any other pain points related to keymaps.
