### ISSUE TITLE
Panes within tabs?

### ISSUE THREAD

**Issue by bhuga** [atom/atom#672]
I have a Vim workflow that I am having trouble recreating in Atom. Most of my tabs consist of a split, for a file and its tests:

![srt_imports rb _github_talks_app_concerns_talk - vim](https://f.cloud.github.com/assets/12676/896074/195b3ef8-fad9-11e2-8bcb-80e85ab7ab8e.png)

Thus I can `{` and `}` my way through tabs and `[` and `]` my way through splits within them, and all was right with the world. My splits are about keeping related files together, not separate panes or editors.

The modeling of `Pane` and `EditSession` doesn't really allow this right now. It's fairly easy to see a number of ways to do it, but I was stymied when I started to edit core stuff by things marked as internal. @kevinsawicki said to ignore that, so I'm going to slowly work on something that works for me. But he also said to make an issue, so here it is. I'm hoping that one of you core guys sees a super easy way to do it :)

**Comment by agquick** [comment]
+1 coming from Vim this is my biggest drawback right now. I use my tabs as different workspaces (like tmux also).

**Comment by gavriguy** [comment]
+1

**Comment by CompileThis** [comment]
+1

**Comment by bendavis78** [comment]
I could really use this as well. In my "pre-atom" workflow I used tmux and vim. It would be great to fire up a terminal, start my dev server, hop over to a new tab, and open a split-pane view of my html/css/js code.

**Comment by ScriptorNY** [comment]
+1

**Comment by c10b10** [comment]
Moving my comment from #11349 here:

When I code, I conceptually split work into logically separate sections of the project, each of which involves working with multiple files at once: Data flow, Styling, UI components, etc. Surely I'm not alone.

Atom's current tab model sadly makes it difficult to map this way of working to the current workspace. I think we would all benefit immensely from changing it to Vim's model.

**Comment by rugginoso** [comment]
+1

**Comment by tomkadwill** [comment]
+1

**Comment by xstasi** [comment]
+1

**Comment by nferruzzi** [comment]
+1

**Comment by JuliaSklyar** [comment]
+1

**Comment by BigfootN** [comment]
+1

**Comment by averyvery** [comment]
👍

**Comment by trusktr** [comment]
I would love in-tab splits. Maybe we can keep Atom's current functionality and just add onto it. The current commands for splitting panes can remain the same, and new commands can be added that can make split windows (perhaps call these ones windows instead of panes, in order to differentiate?) inside of a tab.  The end result would be that panes contain tabs, and tabs contain windows (named similarly to vim's windows).

**Comment by trusktr** [comment]
In NeoVim I like having files for a single component inside a tab. For example, a js file, html file, and css file, all split within a single tab. The workflow in Atom is quite different: it encourages bunching of similar files (for example, all CSS files in one pane, all HTML files in another pane, and all JS files in a third), so that the files for a single component can be visible all at once by selecting the appropriate tabs in each pane, but this will get in the way when trying to view other files that don't fit into the same component pattern. The splits-inside-tabs functionality would make it easier to group things (co-locate things) component-wise.

**Comment by trusktr** [comment]
Another idea could be to introduce an ability to switch `Workspace`s easily within a window, along with an extra UI around that feature to make it easy. Since Atom already has tabs on a per-pane basis, then maybe "workspaces" could be used to group panes together. After thinking for a little while, I like this idea better, and think that it would be better than NeoVim's. 

But, since thetab UX feature is already used on panes, how would the workspace switching look like? Would it be similar to OS X's Expose (Mission Control)? Or perhaps more like Gnome 3's vertical workspaces?

On a side note, I'm making a 3D library at http://infamous.io (demos and docs coming soon), and I might like to implement something useful with it (for example, workspace switching).

Does anyone reading this know if it's possible to have multiple Workspace instances in a single window currently?

**Comment by trusktr** [comment]
Hmmmm, after researching the API for a little while, it seems that Workspaces have some functionality that we may not want to duplicate across some form of end-user "workspaces".

Maybe we can instead call this new feature `PaneGroup`s, an have it strictly contain panes, so that the window's overall Workspace can still have things like top panels, etc, stuff that we wouldn't necessarily want to modify on a per-panegroup basis.

Question to anyone reading: would you like file tree instances on a per-panegroup basis? Or just one file-tree in the workspace, with pane groups containing literally nothing but panes (along with some way of navigating them)?

**Comment by trusktr** [comment]
Alright, so after taking a look at the [Workspace](https://github.com/atom/atom/blob/v1.7.4/src/workspace.coffee) class, it appears that Workspace is a proxy over [PaneContainer](https://github.com/atom/atom/blob/v1.7.4/src/pane-container.coffee) (Workspace contains a single PaneContainer).

It seems that in order to make this change I would have to modify (or extend) Workspace to make it possible for Workspace to contain multiple PaneContainers.

I'm completely new to Atom, so I'm not sure yet if it's possible to extend Workspace (and replace the class with the extended version) before it gets instantiated. If not, then it might not be possible to do this as an Atom package, and would need some modifications to Atom's Workspace class.

PaneContainer already is the pane-containing thing we'd want to take advantage of (rather than PaneGroup I suggested above).

I'm not yet sure how best to make this happen. If anyone has any ideas please do share. Will be back later...

**Comment by trusktr** [comment]
Some other things to note are that the current Workspace (souped-up PaneContainer) also contains things like a PackageManager instance, etc, things that we wouldn't want to duplicate. The change needed to make this effective might be to first separate those concerns so that it's possible to have multiple WorkSpaces in the same window without duplicate things like the package manager.

**Comment by trusktr** [comment]
Another idea might be to use PaneContainer inside of a tab, so then the UI would become a nested set of PaneContainers (the current commands for splitting panes would work on the focused PaneContainer or Pane). So inside of tabs we could have Panes with more tabs. I still have to get more familiar with the API...

**Comment by freebroccolo** [comment]
Setting aside whether or not it is a good idea to try and replace `Workspace`, it doesn't look like it will be easy to do it through a package if you look at how the atom environment is initialized:

You can see [here](https://github.com/atom/atom/blob/1c843e70a21aa1e496c0d7cf7d6542148019445a/src/atom-environment.coffee#L167-L192) that the `PackageManager` is created before the `Workspace`. However, [loadPackages](https://github.com/atom/atom/blob/1c843e70a21aa1e496c0d7cf7d6542148019445a/src/atom-environment.coffee#L658-L675) is not called until [startEditorWindow](https://github.com/atom/atom/blob/6e6771ad5c913313de2bf83fecb38cdd0d6724b8/src/initialize-application-window.coffee#L24-L32). By that time, `Workspace` has already been created and maybe used for several other things.

As far as trying to replace `Workspace`, that seems like a pretty heavy handed solution since it could potentially cause a lot of breakage for other packages. Maybe it could be done but if there was any other way it would probably be better to avoid it.

**Comment by benwyrosdick** [comment]
This has already gotten it's fair share of +1's but I would love this as it is my biggest drawback to sticking with atom. I have many years of a 'vim' workflow that involved splitting inside of a tab that is too hard to overcome

**Comment by pauldoerwald** [comment]
I too would love this. +1!

**Comment by laike9m** [comment]
+1

**Comment by bentford** [comment]
+1

**Comment by solsticedhiver** [comment]
+1

**Comment by SirensOfTitan** [comment]
> but I would love this as it is my biggest drawback to sticking with atom

Agreed, +1

**Comment by rikvanmechelen** [comment]
+1

**Comment by borisnadion** [comment]
+1, it's indeed the biggest drawback

**Comment by matt-paul** [comment]
+1

**Comment by colbydehart** [comment]
👍

**Comment by andremalan** [comment]
👍

**Comment by jesselatimer** [comment]
+1

**Comment by bfitch** [comment]
👍

**Comment by Dmitra** [comment]
![vim-ctrlspace](https://user-images.githubusercontent.com/280060/30851128-5a1caf5c-a2b0-11e7-8651-95727414f793.jpg)
I'm using this plugin https://github.com/vim-ctrlspace/vim-ctrlspace which makes even more use of panes within a tab. This plugin has a separate on demand pane with list of opened buffers in a tab. Together with ability to rename a tab this gives you even more structure.

Usually I have 6 - 12 tabs opened in VIM, named by project part. And within each tab I have 1-20 buffers (files) attached (opened) while only one or two are simultaneously visible (opened as panes).

While similar structure may be achieved by proper arrangement of files within a project folders, it's much more flexible to have an alternative "folder view" on the project functionality part in the editor.

Unfortunately this plugin is no more maintained and it makes VIM very slow soon.
So, not having panes within a tab is a show-stopper for me to enjoy great Atom infrastructure.

**Comment by trusktr** [comment]
True, panes within tabs make much organizational sense. If people took the time to learn Vim, then they'd realize how nice organization with panes inside tabs. If Atom took the time to make it, then they'd also realize how powerful it is.

**Comment by hoschi** [comment]
Also no one explains the ideas behind the concept used in Atom (VS Code, IntelliJ, ...), where I see writeups like @Dmitra why Vims version is better more often. Which are the use cases developers of these editors thought "hey lets do tabs in splits, it makes sense because XYZ"?

**Comment by michael-lumley** [comment]
+1

**Comment by novrian** [comment]
+1

**Comment by reducm** [comment]
+1

**Comment by tlball** [comment]
+1 for me as well. This may stop me from switching to Atom :(.

**Comment by trusktr** [comment]
Lately, there's a new plugin on the block that adds it's own tab system, so we can have panes inside tabs: https://atom.io/packages/atom-vim-like-tab

If you disable Atom's tab plugin, and use this one instead, you can split panes inside these tabs. It works great! You can, for example, map `gt` to go to next tab, `gT` for previous tab.

**Comment by DabeDotCom** [comment]
+1 — I, too, was surprised/disappointed to find out I couldn't make a "tab of tabs", so to speak...

**Comment by Dmitra** [comment]
Forget  it and use Neovim ;)

**Comment by lee-dohm** [comment]
Thanks everyone for the feedback.

At this point, we don't have any plans to change Atom's view system to enable this scenario. If this is functionality that you need, you may want to check out the [atom-vim-like-tab package](https://atom.io/packages/atom-vim-like-tab) that @trusktr mentions above.

Thanks again for everyone's input and especially the link to the great community package!
