### ISSUE TITLE
show-previous-item and next item order error

### ISSUE THREAD

**Issue by liyaodong** [atom/atom#6782]
This is my key map :
```
'body':
  'ctrl-,': 'pane:show-next-item'
  'ctrl-.': 'pane:show-previous-item'
```
When I hitting the `ctrl-.` shortcut , Sometimes not to switch to the next file , Seems to be the sort have a problem . Wish fixed it . Thanks all .

**Comment by kevinsawicki** [comment]
You can open the keybinding resolver from the command palette to see which commands are executed as you type them.

There might be another keybinding with a more specific CSS selector that is executing sometimes causing your local keybinding to not run.

They [keybinding-resolver](https://github.com/atom/keybinding-resolver) package should make this clear once you open it and run this keybinding since it shows all available ones for the keystrokes typed.

Closing this out, please comment if you are still having issues after checking out the keybinding resolver.
