### ISSUE TITLE
Select Next Unusable, Find Next Inconsistent

### ISSUE THREAD

**Issue by parlayvu** [atom/atom#6800]
1: fruit = "blueberry";
    2: fruitColor = "red";

Select Next (Cmd-D) does't match partial words. Selecting fruit on line 1 then pressing Cmd-D does not select fruit on line 2 as you would expect. I end up having to manually edit because I can't select all the occurrences I need.

Find Next (Cmd-G) is able to match partial words which seems inconsistent with Select Next. Selecting fruit on line 1 then pressing Cmd-F (to put it in search buffer), then Cmd-G does select fruit on line 2.

**Comment by chibicode** [comment]
Starting from recent versions, I can't select a word that the cursor belongs to using `Cmd-D`. Previously, if my cursor was between `r` and `u` on `fruit` and hit `Cmd-D`, I could select `fruit`, but this is no longer the case.

**Comment by afinne** [comment]
I have similar problems. I created a gif illustrating the issue: 
![atom-cmd-d](https://cloud.githubusercontent.com/assets/7114687/7743869/4db4b830-ffa7-11e4-8dc3-e56b4550c562.gif)

This has caused a few bugs in my code, since I think I've replaced all occurrences etc...

**Comment by SeanJM** [comment]
I also ran into the issue, :)

**Comment by shanemgrey** [comment]
cmd-d and ctrl-shift-g should use the current settings for Find so that Regex, Case, Only in Selection, and Whole word behaviour can be set as needed and be consistent across those functions. 

While I'm at it, Find in Project should also reference those settings if it doesn't already.  For some reason Find in Project doesn't have Whole Word as an option.
