### ISSUE TITLE
Are particular files outside index.less required for syntax package

### ISSUE THREAD

**Issue by mcdonnelldean** [atom/atom#6841]
When I created a blank package I get two files, `syntax-variables.less` and `editor-styles.less` do I need these files specifically or can I merge everything into one file. 

Perhaps the question would be better framed as, what are the minimum required specific variables or files in a syntax package for it to be valid.

**Comment by lee-dohm** [comment]
There are certain style sheets that are meant to be included in Syntax and UI theme packages so that package authors can include them to allow UI provided by their packages to blend in with those themes. I know that the [`ui-variables.less` style sheet](https://atom.io/docs/latest/hacking-atom-creating-a-theme#creating-an-interface-theme) is one of those for UI theme packages, I would assume that `syntax-variables.less` is also for Syntax themes. I don't know about `editor-styles.less`.

/cc @simurai

**Comment by simurai** [comment]
Well, the *really* minimum requirements to make a syntax theme work is a single `index.css` file. So you don't even need to use Less.

That said, it's highly recommended to also include the `styles/syntax-variables.less` since it gets used by other packages. If the `styles/syntax-variables.less` can't be found in a theme, Atom just falls back and uses the variables found in https://github.com/atom/atom/blob/master/static/variables/syntax-variables.less. And then other packages won't match the theme and things probably look odd or are even unusable.

So, yeah.. `styles/syntax-variables.less` is *kinda* required, but the rest can be organized however you like.

**Comment by mcdonnelldean** [comment]
Awesome! Thanks for the details info, both of ye :+1:
