### ISSUE TITLE
Add an option to auto-update certain packages

### ISSUE THREAD

**Issue by corysimmons** [atom/atom#6897]
Sick of every time I open Atom having to update stuff...

**Comment by benogle** [comment]
Sorry about that. We needed to raise awareness and get folks to upgrade everything before [June 1](http://blog.atom.io/2015/05/01/removing-deprecated-apis.html). An autoupdate mechanism is a good idea.

**Comment by corysimmons** [comment]
Yeah I don't have a problem with the small deprecation warning, I have a problem with the big tooltip in the top right popping up telling me packages are ready for update every other time I open Atom. :D

**Comment by bronson** [comment]
So do I, but I'm not sure I want auto-update!  That just turns the problem into once every ten times I open Atom, something is broken and now I need to figure out who added a keymap or changed an API.  This is _especially_ irritating when you're on a deadline.

At least, it was like that in my Sublime days...  Turning off auto-update was the only way to restore sanity.  Maybe, as you say, restricting it to certain packages would be OK.

What about an option to have no more than one "Update Yr Packages!" admonition per week?

**Comment by bronson** [comment]
And, I agree, I don't think the upgrade treadmill is going to slow down much after June 1st.

**Comment by lee-dohm** [comment]
@bronson Yes, you're understanding correctly.

**Comment by dcrystalj** [comment]
is this on a todo list?

**Comment by jarrodek** [comment]
My issue report was closed as a duplicate but it was suggested to copy the issue details here.

Allow auto updates for plugins by either selecting plugins that will be allowed to update automatically in the background or allowing all installed plugins to auto-update.

The auto-update should be performed (as is right now) in the background but some indication that plugins are now updating should be visible in the main UI (like a progress bar with name of the plugin that is being updated.

Steps which explain the enhancement

Application has auto-update plugin option set to true
Plugins are installed automatically as soon as new versions are discovered
A notification (like a status message) is displayed in the main UI to indicate upgrade process
User can stop auto-update that is performed at the moment if s/he don't like the update
Current and suggested behavior

Consider Android use case. In first few version users had to agree and take an action on every update. It was the worst update UX I've ever seen. With platform development they decided to add auto-update option for selected applications with option to enable auto-update for all apps. For years now, in Android, applications that don't need new permissions are auto-updated by default.

The same problem now has Atom. I have many plugins installed to enhance the editor and increase productivity. However, right now I'm starting my every day at work from updating plugins and then in the evening second time at home. Every day. It would be very beneficial to the users if there were an option to enable auto-update for plugins so they don't need to care about it anymore (as probably most of them don't care right now but they forced to do so).

Why would the enhancement be useful to most users

You may perform a user research and ask them if they care about what version of the plugin is currently installed and if they would like to have automatic update. I feel that the most may answer no for the first one and yes to second one.
It should increase productivity by not being distracted by plugins updates. It also increase confidence that the software installed in plugins directory is always up to date.

**Comment by bronson** [comment]
That's strange, my Android phone always prompts, "Install 12 updates?"  To which I can click "Install All"  It's almost identical to the Atom experience.  Nexus 5X, maybe there's a setting somewhere?

Also, Atom needs to restart after upgrading packages.  Would that be automatic too?

Finally, I find packages still break each other distressingly often...  Most recently for me, a Ruby test package added a keybinding that overrode some other binding (forget exactly which).  Since I initiated the update, I had a pretty good idea of what happened.

If I didn't know that packages were upgrading, this could be a huge time waster.  Spending 15 minutes tracking it down would wipe out any auto-install productivity gains.

I'm not against auto-upgrade but I would be cautious about it.  And I think the UI would need to be bulletproof.

**Comment by jarrodek** [comment]
As for an Android, it waits with updates until you plug in the phone to the charger. It's a battery saver mechanism.

About packages incompatibility, comapbility etc what's the difference to current model? Only difference is that user has to take an unescesrry action. 
As I mentioned, android checks permission state and if they had changed the user has to take the action and accept new permissions before installing the app. Similar solution you can applied here. If the package change the range of integration to the editor (or something similar, I'm not an expert on Atom API) then the editor can hold an update.

What I am saying is to take more user friendly approach. If you have to install packages updates every day  (because that often packages are updating) then you not even thinking about it and you are doing it automatically. Anyway it is a distraction and  it should not be performed this way.

As for wondering what has changes in the editor there's always list of packages. It should show this packages that has been recently updated on top of the list. It's still not a new pattern. This way user has the control over what's happening and is not forced to perform senseless tasks. It's the app's task. Besides, as I mentioned, while the update is performed it should be somehow visible to the user because some packages will be disabled during the update time. So the user has to know what is happening.

I'm not sure what do you mean that Atom has to restart after installing packages updates. It never happened to me that the editor asked to reload itself after updating packages.

**Comment by bronson** [comment]
> what's the difference to current model? Only difference is that user has to take an unescesrry action.

No, there's a difference.  When I see the list of packages that are getting updated, I know what's changing.  That way, when stuff breaks (WHEN it breaks), I have a head start figuring out what to fix.

> I'm not sure what do you mean that Atom has to restart

Run the beta.

**Comment by lee-dohm** [comment]
I've talked this over with the team and we don't really want to autoupdate packages. We feel that having the current package update flow is a reasonable balance between control and ease of use. If people want to have something more automated for certain packages, a script could easily be written to update specific packages on launch.
