### ISSUE TITLE
Position of cursor after undo+redo is incorrect

### ISSUE THREAD

**Issue by vincentisambart** [atom/atom#6915]
In most text editors after:
- typing some text (the text cursor ending at position A),
- moving the text cursor somewhere else (the text cursor ending at position B),
- undo,
- redo,

the cursor ends up at position A, but in Atom it end at position B.

**Comment by vincentisambart** [comment]
I generally do undo+redo as a way do go back to my last edit that works in any editor, but it working differently in Atom makes it inconvenient to use.

**Comment by below43** [comment]
Also, when redoing, it's important to see what the redo is.  By redoing then jumping to different cursor position, you cannot see what was redone.

**Comment by izuzak** [comment]
I'm guessing the cursor is put back to where it was because of how cursors and selections are handled in general with undo/redo snapshots -- e.g. if you edited something and selected some text after that, then an undo+redo will not only undo+redo the edit but also restore the selection. /cc @maxbrunsfeld who knows more about these things I believe :surfer:

**Comment by maxbrunsfeld** [comment]
@vincentisambart @below43 You are absolutely right. We'll fix this.

**Comment by vincentisambart** [comment]
Thank you!

**Comment by maxbrunsfeld** [comment]
The fix will be in 0.202.

**Comment by below43** [comment]
Thanks Max :)

--
Andrew Drake

**Comment by maxbrunsfeld** [comment]
A few more fixes were just merged that relate to this bug. They will be in Atom 0.207.
