### ISSUE TITLE
Developer Tools debugger stops but doesn't show values.

### ISSUE THREAD

**Issue by bobrocke** [atom/atom#6938]
The screenshot below shows the Developer Tools debugger that opened automatically in response to the `debugger;` statement in the code.

Even though the debugger was called, the Call Stack and Scope Variables panes claim that the debugger is not paused.

Do I have something set up wrong somewhere? Where can I start looking?

![www grav dev - atom](https://cloud.githubusercontent.com/assets/2962426/7796921/f19080f2-02b2-11e5-932e-7c58695e4c71.jpg)

**Comment by izuzak** [comment]
@bobrocke Please, provide _exact_ steps to reproduce the problem, with a link to a package. Happy to reopen the issue when you do.

**Comment by bobrocke** [comment]
I'm not sure of the best way to describe the steps. I wrote the `debugger;` command in the package code and ran the package via its single menu item Packages -> Open A Terminal -> Open A Terminal Here. The debugger opened as shown in the screenshot with no debug information.

The package is here: https://github.com/bobrocke/open-a-terminal

**Comment by izuzak** [comment]
> I'm not sure of the best way to describe the steps. 

Just list all the steps you would do to reproduce the issue if you sat down in front of a computer which has Atom installed. More details = better.

> I wrote the debugger; command in the package code and ran the package via its single menu item Packages -> Open A Terminal -> Open A Terminal Here. The debugger opened as shown in the screenshot with no debug information.

I just tried doing that with your package and it worked just fine for me:

![debugger](https://cloud.githubusercontent.com/assets/38924/7797542/b6d27048-02ed-11e5-98b7-0d31a5d683c5.gif)

**Comment by izuzak** [comment]
Do you see different behavior if you open the devtools manually _before_ calling the "Open a terminal: open" command? 

> The screenshot below shows the Developer Tools debugger that opened automatically in response to the debugger; statement in the code.

That'd doesn't happen for me. If I don't have the devtools already open, executing the "Open a terminal: open" command doesn't make the devtools show up and pause execution at the `debugger;` statement, and I believe that's expected behavior (except if there's a config setting in devtools to change that).

**Comment by bobrocke** [comment]
With the developer tools already open, I get nothing. It might have been that a left over breakpoint was set at the `debugger;` statement.

Hmm. Now with the Developer Tools already open, a breakpoint set, and the Open A Terminal file already loaded (executed at least once), it seems to be OK. ???? I get the expected behavior.

I guess I'm surprised that a `debugger;` statement won't drop into the debugger!

Thanks for looking into this - even if nothing was wrong with the code, you got me past whatever I was doing wrong.

**Comment by izuzak** [comment]
> I guess I'm surprised that a debugger; statement won't drop into the debugger!

From what I know, that's expected behavior (e.g. see [this](https://plus.google.com/+AddyOsmani/posts/B9evKzRwar9) -- esp. see comment _"Also bear in mind that this only breaks if you have dev tools open (which is a good thing, but just bear it in mind)."_). Basically, it's the same thing as setting a breakpoint, and those don't open the devtools if the devtools are not open.

> Thanks for looking into this - even if nothing was wrong with the code, you got me past whatever I was doing wrong.

Happy to help. :+1: I hope you don't run into any more of these :ghost: problems.
