### ISSUE TITLE
Surrounding multiple words with ` characters is broken

### ISSUE THREAD

**Issue by nshtg** [atom/atom#6940]
I'm not sure which package is responsible so I'm reporting the issue here. Tested with 0.202.0-ec5b807 in `--safe` mode.

When you select multiple words and surround them with " or ' signs everything works perfectly. However, when I try to do the same with `-signs something weird happens (gif is easiest to show). First the words disappear, then I press Space and they reappear - wrapped - but the words are wrong. Note that Cmd-Z removes the `-signs but can not restore the original words.

![atombug](https://cloud.githubusercontent.com/assets/5219415/7797508/51d03dd8-02ed-11e5-8af7-73aebe779bbd.gif)

**Comment by izuzak** [comment]
I'm not able to reproduce this with Atom 0.202.0-4bbfe37 in safe mode:

![quotes](https://cloud.githubusercontent.com/assets/38924/7797733/a827fb78-02f0-11e5-8338-fd207d46fa19.gif)

Anything in your init.coffee file or other local config files? Can you reproduce this if you move the .atom folder somewhere else (and restart Atom after that)? Which OS are you on (not sure how that would make a difference, but worth asking for completeness)?

**Comment by maschs** [comment]
Rebuild atom to `0.202.0-4bbfe37`, removed the `~/.atom` folder and tried again in `atom --safe` mode. Problem persists. I'm pretty sure it has to do with the OS, im on OSX. 

You can produce letters like á é ú by pressing \` and then a/e/u. OSX waits on the following character until. If I press space \` gets inserted, if I press a/e/u it inserts àèù:

![atombug3](https://cloud.githubusercontent.com/assets/5219415/7797995/355452be-02f4-11e5-99e6-ea450914260b.gif)

As soon as I press Space atom expands the one \` sign to \`\`. Not that much we can change about  that (OS behaviour), but why is atom replacing the first word

**Comment by izuzak** [comment]
> I'm pretty sure it has to do with the OS, im on OSX.

I'm on OSX as well. 

> You can produce letters like á é ú by pressing ` and then a/e/u. OSX waits on the following character to see if it should be replaced. 

Not on my machine:

![quotes2](https://cloud.githubusercontent.com/assets/38924/7798036/ca03eb90-02f4-11e5-8713-268150ff9916.gif)

Which keyboard layout are you using? Not US, I'm guessing?

**Comment by maschs** [comment]
No I have a german keyboard layout. Switching to US makes it behave like on your machine now and the surrounding works.

Question remains, why is atom replacing the first word? I would understand if it would delete both words but instead it does this weird thing.

**Comment by izuzak** [comment]
> Question remains, why is atom replacing the first word?

I'm not sure, but I'm trying to figure out one thing at a time. I think that's easier and less complicated than discussing 2 different issues at the same time.

I'd say that surrounding words with backticks isn't broken, it's more how the OS is handling those backtickts. If you select two words, as you did in the GIF, then press the backtick, and then press `escape`, what do you see then? Can you record a GIF of that with the keybinding resolver shown?

**Comment by maschs** [comment]
![atombug4](https://cloud.githubusercontent.com/assets/5219415/7798242/be4b27a2-02f7-11e5-805a-dfefd363e7f2.gif)

**Comment by izuzak** [comment]
Thanks -- that looks broken to me as well (pressing `escape` seems to do the same thing as pressing `space`, which is what you were doing originally, but just wanted to confirm). 

/cc @nathansobo for :eyes: -- any chance this is an easy fix :tm: ? :smile:

**Comment by nathansobo** [comment]
This seems to be related to our general issues with international keyboard support due to bugs in Chrome. The keybinding resolver seems to identify the keystroke as `Å` when I enter a backtick via the German layout. Can you guys confirm the same behavior. We already have a bunch of known issues on international layouts so add this to the list.

**Comment by maschs** [comment]
I can confirm that behaviour, you can see it in my latest gif too.

However, question remains, why does it replace the first word? I would totally understand if the wrapping failed or nothing happend at all, but the behaviour seems really odd. Why does it wrap the word at all if the keyboard layout is the main problem?

**Comment by slhck** [comment]
Still got the problem on 1.0.2 on OS X, using a German (QWERTZ) keyboard layout.

When I select multiple lines, then try to wrap them in backticks, confirm the (dead) backtick key with a space, it replaces all words with the first one, and, of course, there's no way to undo that either.

![](http://zippy.gfycat.com/EvenSoupyHectorsdolphin.gif)

**Comment by jeancroy** [comment]
Some idea: I believe the key point is when all text disappear.

When someone type "  ` " : 
 - you get GRAVE ACCENT \u0060 on keyboard that allow you to type directly.
 - but COMBINING GRAVE ACCENT \u0300 on keyboard that need two step to write.

COMBINING  + a = à
COMBINING  + space = GRAVE ACCENT `

----

Looking at the @slhck screenshot here are the events I see

- select all element, line per line.
- type \x0300 - all text disappear leaving multiple `
- type space - all text re-appear surrounded by \x0060 but have wrong value.

----
Pen & paper hypothetical stack trace:

**User input \x0300**
- enter [insertText](https://github.com/jeancroy/bracket-matcher/blob/master/lib/bracket-matcher.coffee#L48)
    - enter [wrapSelectionInBrackets](https://github.com/jeancroy/bracket-matcher/blob/master/lib/bracket-matcher.coffee#L148)
    - return false - because not an opening bracket [L156](https://github.com/jeancroy/bracket-matcher/blob/master/lib/bracket-matcher.coffee#L156)
- return true - because multiple cursor [L52](https://github.com/jeancroy/bracket-matcher/blob/master/lib/bracket-matcher.coffee#L52)

**editor default behavior: overwrite**
- like we typed the letter "a".

**User input "space"**

**OS filter**: backward replace COMBINING+ SPACE into GRAVE ACCENT `

Enter `insertText`
Enter `wrapSelectionInBrackets`
True `isOpeningBracket`
[selection.getBufferRange()](https://github.com/jeancroy/bracket-matcher/blob/master/lib/bracket-matcher.coffee#L167) - for some reason return previous value of last selected item. The way OS filter work skipped a buffer clean-up event.

We now have this everywhere:
````
`lastItem`
````
-----

**Comment by jeancroy** [comment]
Issue https://github.com/atom/atom/issues/8667 has been closed but add the important point that this current issue is not limited to the back-tick. This could occurs with any character that is both an accent and a bracket. `` ` ``, `'`, and possibly one day something like `^` and `~`

The range of character interesting to this issue could be
Spacing Modifier Letters (02B0-02FF)
Combining Diacritical Marks (0300–036F)
