### ISSUE TITLE
Towards unobtrusive notices and notifications

### ISSUE THREAD

**Issue by Caged** [atom/atom#6945]
This is more of a discussion than a concrete list of actionable items.  Since Atom's launch, I've started to notice more things seeking my attention in an increasingly aggressive manner.  They seem small in isolation, but when you add them up and make them recurring, Atom can begin to nag you.  

Below is the most recent example.  I wanted to take a quick look at some docs, so I run `atom .`  

![screen shot 2015-05-25 at 10 30 25 am](https://cloud.githubusercontent.com/assets/25/7800438/3c7af9e6-02ca-11e5-8dbe-b321bf2f7cde.png)

a. **Non-fatal errors are blocking content** - Is this dialog necessary given b.?
b. **Duplicate update notices** - How can Atom minimize these or get rid of them completely? 
c. **The `!` feels unnecessary** - Deprecation and update notices now contain an `!` mark.  It's small, but this changes the tone of the message from informing me, to shouting at me. 
d. **More packages.  more notices** - It seems logical that the longer you are an Atom user, the more package you install, the more notices you are going to get. 
#### Deprecation notices

When you click on the deprecation notice text in the status bar, you are taken to this screen:

![screen shot 2015-05-25 at 10 55 40 am](https://cloud.githubusercontent.com/assets/25/7800595/a39f238e-02cc-11e5-8864-90a7e4d5bf04.png)

This screen feels unnecessary to anyone _using_ Atom.  Unless I'm a developer or I'm specifically trying to debug packages, I'm not too concerned with what methods in what packages are deprecated.  I would like the deprecation message to go away so I can get back to work.  How can Atom help me do that?  Could the "Check for updates" step happen automatically?  Could updates be installed during relaunch or during idle time?
#### Package updates

![screen shot 2015-05-25 at 11 07 37 am](https://cloud.githubusercontent.com/assets/25/7800708/52e0e5fc-02ce-11e5-86ca-9e0fb9bc78df.png)

There's 1 update available.  When I click the notice in the status bar, I'm taken to this screen that runs an additional check for updates and then lists the packages that have updates.  Does Atom need to run this check again since it knows I have a package that needs an update already? 
#### Some considerations

In the spirit of GitHub Zen, here are a few things to consider:
- Atom should strive to not block content for non-fatal errors. 
- Atom should strive to keep notifications to a minimum.
- Atom should strive to reduce manual administrative overhead (updating packages, atom, etc.). 

:bow:  Thanks for the fantastic work

**Comment by 50Wliu** [comment]
a. has been discussed multiple times on Discuss - a good one is [this topic](https://discuss.atom.io/t/can-i-turn-off-the-notifications/17117).
b. I've been under the impression that the new notification is just a stopgap measure to encourage people to upgrade their packages until 1.0 is released.
c. Fully agree - I like the new text next to each item, but the `!` seems over-the-top.
d. See b.

Deprecation notice: I had that package disabled for a couple of months, precisely because it didn't really help me to know that xyz package was using a deprecated method.  The only thing in there that is helpful to a normal user is the `your styles.less file` notice.  It does help notifying package authors that their package has deprecations though.

Package updates: Already reported in atom/settings-view#409.

@atom/feedback thoughts?

**Comment by mark-hahn** [comment]
> is helpful to a normal user is the your styles.less file notice.

That was killing me.  I save constantly, often in the middle of edits.
That syntax error popped up so often I couldn't edit.  When combined with
the overall obnoxious intrusion of the pop-ups I have disabled them.  I've
been doing just great without them.

I used to use the error-status package which only had a small bar above the
status bar which allowed me to keep working.  That was awesome.

**Comment by 50Wliu** [comment]
@mark-hahn I was referring to deprecation notices specifically, not the notifications (which I definitely agree can be annoying).

**Comment by Caged** [comment]
>  Deprecation notice: I had that package disabled for a couple of months, precisely because it didn't really help me to know that xyz package was using a deprecated method.

Cool.  Seems like this could be disabled by default and conditionally enabled with the `--dev` flag since it's primary use is for development.  

> has been discussed multiple times on Discuss - a good one is this topic.

Seems sensible to want to get everyone as up-to-date as possible.  Seems Atom needs some type of information dialog that doesn't block content unless it's explicitly triggered by the user.  For instance, maybe there's a persistent dialog that originates from above the status bar item it belongs to.

> Package updates: Already reported in atom/settings-view#409.

Awesome.

FWIW, I'm fine with closing this thread once it has outlived its usefulness.

**Comment by benogle** [comment]
The upgrade nag notification and deprecation status bar icon will be going away soon, but are super necessary right now. We're on the cusp of removing all the old APIs (june 1), which would break a bunch of packages if we didnt do anything. 

When we started tracking deprecations in analytics last week, we noticed that there were a ton of people using very very out of date packages. They had the latest version of atom, but were, say, using a months-old vim-mode version. Since the new nag screen there has been a large uptick in package upgrades, and is helping flush the ecosystem of the old, deprecated packages. It is annoying, but it is working right now.

After the APIs are removed, this stuff will be a lot less invasive. The deprecation icon can just show in dev mode, the package upgrade link can go back to just a blue icon in the status bar, or we can come up with some way to auto-update the packages.

> The ! feels unnecessary

Yeah, we should have these gone by tomorrow's release.

> Could the "Check for updates" step happen automatically? Could updates be installed during relaunch or during idle time?

The main issue with auto updates is that of trust. Can we totally trust everything in the package store? What if someone makes a package, people install it, then the package is updated to do something totally sketchy? Viewing the updates for each package is the minimum gut check we can have the user do. If something looks off, they can disable.

> When I click the notice in the status bar, I'm taken to this screen that runs an additional check for updates and then lists the packages that have updates. Does Atom need to run this check again since it knows I have a package that needs an update already?

Yeah, this is crappy for sure.

> In the spirit of GitHub Zen, here are a few things to consider:

I agree with all of these. The noise at this time is necessary for the sake of user experience at the time of upgrade to the release with deprecated APIs removed. And there definitely needs to be work put into the update flow (app and packages).

**Comment by mehcode** [comment]
> The main issue with auto updates is that of trust. Can we totally trust everything in the package store? 

Selectively. I suggest we have a "badge of honor" / "approved" system for packages. These packages get marked to be auto updated (eg. everything in AtomLinter should be trusted). Other packages can selectively have auto updates turned on / off.

**Comment by Zireael07** [comment]
@mehcode : +1.

**Comment by thomaslindstrom** [comment]
@mehcode: :+1: 

A trust system seems like the easiest way to leap towards auto updating. There's a [featured](https://atom.io/packages) package section already – so I guess the folks at GitHub would be able to cherry pick what packages get approved. 

Periodical code reviews could be automated, too, looking for possible exploits programmatically. Or, maybe, a “trusted package” needs to be reviewed by GitHub after updates are pushed to `apm`?

**Comment by mark-hahn** [comment]
> a “trusted package” needs to be reviewed by GitHub after updates are
pushed to apm?

This would be like approved repositories for linux distributions.  They
work pretty well but you end up with really old versions of everything.

**Comment by thomasjo** [comment]
Considering that Atom packages have full, unrestricted system access at the level of current user context, we would need to change the entire package model to be able to safely provide automated updates. We would need to switch to a sandbox model, and have each package request access to e.g. the filesystem via a gated API. That way, when the user installs a package, they're presented with the level of system access required by the package to make them aware of potential security vulnerabilities present after installing the package, and have them explicitly accept that risk.

I sure as hell don't want to be a victim of someone going rogue, pushing an update to their previously harmless package, that now executes e.g. `rm -rf $HOME` or something similar. There are extremely good reasons that all (sensible) software systems that provide autoupdates of third-party software use sandboxing (or similar) along the lines I outlined.

Yeah, I'm :heavy_minus_sign::100: on the autoupdating packages (with the current security model, or lack thereof).

**Comment by mnquintana** [comment]
Refs https://github.com/atom/atom/issues/1763

**Comment by mehcode** [comment]
> I sure as hell don't want to be a victim of someone going rogue, pushing an update to their previously harmless package, [...]

What is to stop someone going rogue on a package you've already approved for file-system access? It's an endless rabbit hole.


---- 

I do like what @nathansobo outlined on https://github.com/atom/atom/issues/1763#issuecomment-82451310 and https://github.com/atom/atom/issues/1763#issue-29603475

**Comment by thedaniel** [comment]
>  a “trusted package” update needs to be approved by GitHub after being pushed to apm.

This is too labor-intensive for us right now and prone to human error. @atom/core and @atom/non-github-maintainers are fully subscribed with core development and community management.

The best compromise that I personally see for the immediate future is something similar to the popup added recently, but dismissable for a period of time, kind of like this dialog in OS X (but with longer time periods):

![](http://www.amsys.co.uk/wordpress/wp-content/uploads/Screen-Shot-2013-11-21-at-Thursday-21-November-2013-15.39.48-GMT.png)

In any case fully automatic package auto-update is also probably not something we'll pursue, at least with the current security model. Nathan is very interested in approaching the security model issues, and we have a GSoC student doing research as well.

**Comment by thomasjo** [comment]
> What is to stop someone going rogue on a package you've already approved for file-system access? It's an endless rabbit hole.

Nothing, but then I've explicitly granted it filesystem access, and such access is gated via a provided API and can as such have additional layers of "security" to (potentially) prevent evil.

But all in all, I'm just :-1: on this until we have an extremely good security model in place. Problem is that it makes it harder to develop packages, so I'm not convinced it's even worth the effort in the end. Maybe I'll change my tune when/if we get a security model in place.

**Comment by 50Wliu** [comment]
At this point I think the only issue left to tackle is the Package Updates one.
