### ISSUE TITLE
Open file in Atom and go to designate line

### ISSUE THREAD

**Issue by fishg** [atom/atom#6947]
In Unity 3D editor,dobule click the console log will invoke editor to open file with line number,Mono developer an sublime works perfectly,but Atom juse open the file,not goto the designate line.

**Comment by lee-dohm** [comment]
Atom will open a file at a designated line if you launch it with `atom filename.ext:nnn` where `nnn` is the line number you want the cursor to be on.

**Comment by dougireton** [comment]
Atom 1.0.2 on Windows 8.1 opens a blank tab with `filename.ext:nnn` instead of opening `filename.ext` at line `nnn`. Maybe this is a Windows-specific bug?

**Comment by lee-dohm** [comment]
@dougireton There is a different bug open for that, https://github.com/atom/atom/issues/7342

**Comment by dougireton** [comment]
OK. Feel free to close in favor of #7342.

**Comment by lee-dohm** [comment]
@dougireton I'd rather hear from @fishg that their issue is fixed. It doesn't sound like they had the same issue that you do.

**Comment by fishg** [comment]
I can't custom start params in Unity3D on OS X.
<img width="530" alt="qq20150713-1 2x" src="https://cloud.githubusercontent.com/assets/1423545/8643220/aa076fd4-2963-11e5-921f-6ded3e01a039.png">

My request is Atom open the file and goto the designate line when I double click Unity3d cosole log.Atom just open the file,not goto the line now.
<img width="274" alt="qq20150713-3 2x" src="https://cloud.githubusercontent.com/assets/1423545/8643312/cfcab7a2-2964-11e5-8e49-1ea64e6f6ce5.png">

**Comment by doggan** [comment]
This ^ is not an Atom bug. It has to do with the way Unity invokes the external editor. See this link for instructions on how to invoke correctly (the instructions are for Sublime, but it works the same for Atom): http://wiki.unity3d.com/index.php/Using_Sublime_Text_as_a_script_editor

https://github.com/atom/atom/issues/7342 IS definitely an issue, though, so even if you hook up Unity correctly, this may not work until #7342 is fixed.

**Comment by fishg** [comment]
@doggan Sublime 3 is not need any extra setting for support Unity3d console log double click for open file and goto specific line.It's not a bug for Atom, but may increase Atom's compatibility.

**Comment by izuzak** [comment]
@fishg Just to make sure I understand -- when you go to your terminal and when you run a command like this:

```
atom filename.txt:LINE_NUMBER:COLUMN_NUMBER
```

_(where filename.txt exists and has some text in it, and LINE_NUMBER COLUMN_NUMBER are numbers, e.g. `atom foo.txt:4:5`)_

does Atom open the correct file and is the cursor placed on the correct line and number?

**Comment by fishg** [comment]
```
atom filename.txt:LINE_NUMBER:COLUMN_NUMBER
```
works as expect.

As http://wiki.unity3d.com/index.php/Using_Sublime_Text_as_a_script_editor  write,Unity3D open file use this format:
<editor> file line column

Now sublimetext 3 is compatible that format and not need any extra config.I wish Atom have this compatible.

**Comment by izuzak** [comment]
@fishg Thanks for confirming. I'm going to close this since Atom is working as expected here and supporting all possible formats for all possible other tools that open editors is just not feasible. Imagine someone opening a new issue tomorrow asking that this format is supported: `editor file (line) (column)` because they're using some other tool. This is especially true for tools which offer a way to configure how the editor will be called.

Also, `atom foo.txt 3 4` might also be interpreted as "open these three files: foo.txt, 3, and 4" since 3 and 4 could also be filenames. If you pass multiple filenames as arguments to Atom, then Atom will open all of those.

Thanks for all the feedback here. I think this would be worth considering if the majority of other tools opened files using this format. If you know of other tools which do this -- please feel free to leave a comment here.

**Comment by fishg** [comment]
Fine.I use VisualStudio Code and Sublime Text for my Unity3d project.This is not a hard obstacle.

**Comment by tbriley** [comment]
@fishg and anyone else still needing this, i copied a bunch of stuff from the vscode project (https://github.com/dotBunny/VSCode) and while it's a bit of a hack, it seems to work ok:

https://github.com/tbriley/Atom
