### ISSUE TITLE
Regression: Log cursor scopes is off

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#7073]
![image](https://cloud.githubusercontent.com/assets/2766036/7950075/d2ff084a-0963-11e5-9a55-63d10121a4b3.png)
Here my cursor is right before the `=` on L12

![image](https://cloud.githubusercontent.com/assets/2766036/7950087/e574d3b0-0963-11e5-90a9-ce104c5716e4.png)
Right before `new`

![image](https://cloud.githubusercontent.com/assets/2766036/7950092/f0dc6312-0963-11e5-8867-d0a5b1cc1b40.png)
Right before the `e` in `new`

Most likely caused by #6733 (sorry I didn't catch this earlier :cry:).

/cc @nathansobo, @as-cii

**Comment by as-cii** [comment]
Hey @50Wliu, thanks a lot for catching this! :bow: 

However, I am not able to reproduce it with the files I have on my machine (I must be missing something): could you please provide a gist with a minimal example which shows this exact behavior?

Thank you!

**Comment by 50Wliu** [comment]
Hmm, it looks like there has to be a certain context around the broken lines.  Simply copying/pasting L12 into a blank file doesn't reproduce it.  I'll comment back with a gist if possible.

**Comment by 50Wliu** [comment]
And here we go:
```js
function someFunction(someParameter)
{
	something = new thisIsGoingToBeAwesome();
}
```
Reproduces exactly the same as in my bug report.  The scopes for the `function` and bracket lines work fine, it's once you hit the actual code within the function that stuff breaks :confused:.

**Comment by nathansobo** [comment]
@50Wliu Sorry, can you give me an exact screen coordinate, the scopes you expect there, and the scopes you get? Trying to figure it out in the meantime.

**Comment by nathansobo** [comment]
![screenshot 2015-06-04 00 37 49](https://cloud.githubusercontent.com/assets/1789/7973058/f2aef33c-0a51-11e5-871a-388c831b799a.png)

I'm able to log the correct scope with the cursor right before the `=`.

**Comment by 50Wliu** [comment]
Hmm, so this is harder to debug than I thought.  The initial file's still broken in safe mode as of 2f26de3e26cbf02cf7f9fcb63373b8eb33e62c44, but if I open up the example that I pasted (which was broken when I tested it), it works fine...
I added a bit to it to see what I needed in order for it to reproduce, and it turns out it seems to randomly work and break.

Here's a GIF to prove I'm not going mad:
![scopes](https://cloud.githubusercontent.com/assets/2766036/7994566/4cce5404-0adc-11e5-8122-263121a4ca05.gif)

And here's the full file just in case: https://gist.github.com/50Wliu/235fffc0113b0a5db4aa

**Comment by as-cii** [comment]
Thanks @50Wliu for the extensive explanation :bow: 

That's definitely weird: I am still unable to reproduce it, but I am quite skeptical it was caused by #6733 now that I look at it more closely. I might be missing something here but the way we log scopes shouldn't be affected by how we render lines.

@50Wliu: maybe you could try reverting that PR and see if it helps (simply going back in the commit history could not be effective, e.g. the regression could have been introduced after merging PR)? That might confirm my hypothesis and, hopefully, narrow the cause of the problem. If you encounter any issue while doing that (e.g. conflicts), I'll be glad to help you solving them. 

I'll keep an eye on this specific problem while I use Atom over the next days and see if I can spot *when* and *how* this happens.

**Comment by 50Wliu** [comment]
Definitely.  I realized that too right after I submitted the issue, but forgot to comment.
Might be a bit busy for the next few days, but I'll try to revert it by Monday and give it a go.

**Comment by nathansobo** [comment]
@50Wliu If you can reproduce it, setting a breakpoint in the method and investigating where we go wrong might help too. I feel like it might be blamed on the `TokenIterator` getting into a weird state or something.

**Comment by nathansobo** [comment]
Thanks @50Wliu. I found the issue. When I changed this code path I accidentally used the screen column instead of the buffer column. :grimacing:
