### ISSUE TITLE
Not building at all on OS X

### ISSUE THREAD

**Issue by clstudio** [atom/atom#7090]
I am not able to build atom at all. All requirements are met. I followed exactly the instructions - nothing happens. That's all the output I get within seconds before termination of the process:

```
script/build --verbose
Node: v0.12.4
npm: v2.11.0
Installing build modules...
```

**Comment by kevinsawicki** [comment]
Can you try `script/build --stack`?

**Comment by clstudio** [comment]
The outcome is the same

**Comment by williamtellme123** [comment]
I just downloaded the atom-mac.zip
from https://s3.amazonaws
Unzipped it. It appears to start then does not.

**Comment by naixn** [comment]
I cannot build from OSX 10.10.5 either:
```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/thibault.ml/Sources/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
More errors around.

The full log can be found here: https://gist.github.com/naixn/5b9fd3ecc017730971eb

**Comment by clstudio** [comment]
I still get the same output and am not able to build from source with the latest files . I think I'm missing one or more undisclosed steps. Can you be a bit more thorough in the install instructions?

**Comment by thomasjo** [comment]
@clstudio There are no undisclosed steps. The requirements listed in [the build instructions for OS X](https://github.com/atom/atom/blob/master/docs/build-instructions/os-x.md) are sufficient.

There is one minor caveat though; if you are not using the OS X bundled Python (2.7.x), you will have encounter problems due to node-gyp requiring Python 2.7. So if you're using a non-default Python, I highly recommend installing [pyenv](https://github.com/yyuu/pyenv/) to manage multiple Python versions.

**Comment by clstudio** [comment]
@thomasjo Ok, I just tried `/usr/bin/python` (2.7.10). Previously, I was using homebrew's 2.7.11. But still, nothing happens. All requirements are met. There has to be something missing, I believe. I also tried several things including, `npm install`, `grunt`... before executing
`script/build --build-dir /Users/clstudio/Desktop --install-dir /Users/clstudio/Desktop/Atom.app --verbose`
Even prepending sudo did not help. My output alway is:
```
Node: v6.1.0
npm: v3.8.6
Installing build modules...
```
No error, no log etc. I am aware of. So, what am I missing?

**Comment by thomasjo** [comment]
Are you sure nothing is happening? If you are behind a slow internet connection (or possibly a firewall/proxy), the build module step might seem like it has stalled since it downloads a bunch of npm packages (and builds some of them).

Start the build, then check via *Activity Monitor* (or `ps`, `top`, etc) whether there are running processes.

**Comment by clstudio** [comment]
The output returns immediately after I enter the command. The network is ok, I think, modules are normally always installed. In this case my network monitor does indicate that there is not even the attempt to make a connection.

**Comment by 50Wliu** [comment]
@clstudio Can you try running `script/build --verbose` and see if that logs any extra information?

**Comment by clstudio** [comment]
@50Wliu That's what I was using

**Comment by 50Wliu** [comment]
My apologies, didn't see the `--verbose` tacked onto the end :frowning:.

**Comment by clstudio** [comment]
No problem. I also tried many variations of `script/build`, always with the same output
