### ISSUE TITLE
Default install location of windows system.

### ISSUE THREAD

**Issue by decaylong** [atom/atom#7095]
Why the default install location is "C:\Users\name\AppData\Local\atom" , that's sh!t. Hope that can choosing by users.

**Comment by russlescai** [comment]
@decaylong download atom-windows.zip and copy it wherever you want...

**Comment by russlescai** [comment]
Where would you prefer it to be? Usually there are two options for installing - for all users, which requires administrator permissions and installs in program files, or this user, which installs it in the users profile directory (current behaviour).

**Comment by 50Wliu** [comment]
There are only two possible locations that Squirrel will install to at this time:
* `%LOCALAPPDATA%\atom` (the default which you experienced)
* `%PROGRAMFILES%\atom` (`AtomSetup.exe  --machine`)

I'm not aware of any plans to allow custom install paths - @paulcbetts can you confirm?

**Comment by decaylong** [comment]
ok，Im choose download zip file，and Im actully dont know about 
- %PROGRAMFILES%\atom (AtomSetup.exe --machine)
this option :)   ty @50Wliu  @russlescai

**Comment by paulcbetts** [comment]
Three are two possible locations that Squirrel will install to:

* `%LocalAppData%\Atom% - the default
* `C:\ProgramFiles\Atom\USERNAME` - the install location that is set when the first location cannot be written to / executed from, because of Group Policy

`AtomSetup.exe --machine` will just end up installing to one of these two places, but for all users (i.e. upon a new user logging in, we will proceed to install to that location)

> Hope that can choosing by users.

Squirrel will never offer this choice, sorry!

**Comment by hichris1234** [comment]
This is horrible. I have an SSD as my main drive and I typically want things on my regular HDD. How can I *not* choose where to install a program?

I'd even help contribute to change this.

**Comment by paulcbetts** [comment]
@hichris1234 Once the app is installed, you can move `%LocalAppData%\Atom` to wherever you want, then use `mklink /D %LocalAppData%\Atom D:\Path\To\Where\You\Put\Atom` and everything will work, even updates.

**Comment by hichris1234** [comment]
But I shouldn't *need* to. Look at *any* program on Windows. Try to install it. In the installer, 99% of the time there's an option for "where do you want to install this program?" (I can think of only a few exceptions, such as Chrome). However, for Atom, there isn't.

**Comment by paulcbetts** [comment]
> But I shouldn't need to. Look at any program on Windows. Try to install it. In the installer, 99% of the time there's an option for "where do you want to install this program?" (I can think of only a few exceptions, such as Chrome). However, for Atom, there isn't.

Don't care what 20 years of bad software has done in the past! Users shouldn't be asked arbitrary dumb questions like this, they double-click Setup and their program runs. That's it. Squirrel will never, ever, ever, ever, ever change this.

**Comment by hichris1234** [comment]
Why should I *need* to symlink a directory in order to put it on my non-SSD drive? Or say I had partitions, and I wanted it to be on a specific partition? Or say my main partition was 99% full. What now? I need to download a zip in order to install it then? So much for a setup program that knows what I want.

This is a program made for **developers**. If developers can't be allowed to choose where their text editor installs, then that's insane! They're smart enough to know where they want it (I hope). Atom is made to be configurable. If the install location isn't configurable, I'm afraid Atom has failed at the very basic stages of configuration.

**Comment by Hrxn** [comment]
I agree with hichris here.

A program intended for developers is not the same as a program for a end-user audience.

The location of the installation is definitely not a 'dumb question'..

That is just bad practice.

**Comment by paulcbetts** [comment]
> Or say I had partitions, and I wanted it to be on a specific partition?

Symlink.

> Or say my main partition was 99% full. What now?

Delete some files or move them.

> If the install location isn't configurable, I'm afraid Atom has failed at the very basic stages of configuration.

Sorry!

**Comment by kubetz** [comment]
I agree that not having an option for installation directory is unconventional these days .. but ...

I see opinions here that users of Atom are not "end-users", but developers and yet at the same time people are against creating a symlink. Actually developers should have no problems creating a symlink if they really need to move the atom directory if they really need to. They are used to way more "esoteric" things like that :see_no_evil: .

Some people were were also able to create a [portable versions of Atom](https://github.com/atom/atom/issues/2939).

**Comment by hichris1234** [comment]
> Actually developers should have no problems creating a symlink if they really need to move the atom directory if they really need to.

Almost every program we use everyday allows us to choose an install directory. Forcing users to symlink for something that basic is... not smart. Saying that just because we're developers, we should symlink is like saying just because we're developers, we should want to mess around with atom's code. We *can*, but some things we'd like to Just Work.

**Comment by kubetz** [comment]
> Almost every program we use everyday allows us to choose an install directory. 

.. on Windows ... and as you can see some people feel that it shouldn't be the case.

* linux packages are installed into predefined directories
* npm modules are installed into predefined directories (even on Windows)
* chocolatey packages are installed into predefined directories (unless you want to figure out what installer they are using and overwrite settings by hand)
* homebrew applications are installed into predefined directories (and symlinked)
* also Mac App Store is installing applications into predefined directory

(Don't kill me if I am wrong about last two, I don't own a mac :sweat_smile:)

> Saying that just because we're developers, we should symlink is like saying just because we're developers, we should want to mess around with atom's code.

You can say that. On the other hand you can say: *"Why if I want to have white tree-view in atom I need to tinker with `styles.less` or look for a specfic theme. I want a checkbox in settings for that."* Well, Atom developers didn't feel such thing is necessary so you have to mess around with styles for that. Same goes for the custom installer path where 95%+ of the people just don't care about special location (yup, I pulled this number out of my ...). Yeah, you will have to do it yourself and it will cost you writing a one-liner and being done with it.

**Comment by Hrxn** [comment]
> I see opinions here that users of Atom are not "end-users", but developers and yet at the same time people are against creating a symlink.

Sorry, but I think this is a classic catch-22. The installer is supposed to be very simple (Just works, one click, wizard free, etc.), yet the solution to a very common request (custom install location) is: Just create a symlink. So much for simplicity...

And don't get me started on the discussion about symlinks on Windows (mklink doesn't work on XP), and that flooding your directories with symlinks isn't an elegant solution either.

I get that installing a program into %LocalAppData% is a deliberate design decision, and it certainly has benefits, but as I tried to express, I can let an end-user program (Google Chrome, for example) get away with this behavior, but if you can safely assume that your target audience knows about this stuff, I won't give them the same benefit of the doubt.

Design decision is design decision, but this won't change the opinion of (many) users, who think that is bad practice, and I agree here.

And the [link](https://github.com/atom/atom/issues/2939) you provided to a 'portable' version.
Sorry, but that is just a really ugly hack. Uses its own environment variable, changes the location of %USERPROFILE% (Not a good idea. Not permanently, I know, but still), and creates a `\AppData\Roaming`subdir in your new location, just to avoid breaking some other things. Yup, ugly hack. Definitely not a simple "one-liner"..

And sorry, the notion that you can or at least should not change the location of program installations is just plain wrong. Even outside of the windows world.
> linux packages are installed into predefined directories

You can always use `./configure --prefix=/home/my/path/here`. No predefined directory needed.
Conf file location can be changed with `--sysconfdir=/etc` and so on..

The [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) is always a good occasion for heated debates, you can chime in eventually, if you are inclined. That is all just a big work in progress. A lot of old Unix cruft that you don't really need, and thankfully the Unices have always been flexible in that regard.

> homebrew applications are installed into predefined directories (and symlinked)

Yes, but Homebrew uses its own prefix, as it should be. You can easily modify that, if you want. The binaries are then symlinked back into your $PATH, or somewhere where your shell finds them.
But Homebrew does not write files outside of its prefix. They got Unix right..

**Comment by paulcbetts** [comment]
I appreciate all of the feedback, but this is kind of a done deal, and is extremely unlikely to change

**Comment by qubodup** [comment]
<blockquote>Don't care what 20 years of bad software has done in the past</blockquote>

It is still official that `Program Files` needs to be the default install directory of proper Windows software https://msdn.microsoft.com/en-us/library/windows/desktop/hh749939.aspx

It seems this decision is based on trying to apply a principle from the Mac/Linux world to the Windows world. Which does not work. It confuses and frustrates the users, as it deviates from the norm. The software installation step is not something that should be innovative unless you're trying to reject a share of potential users.

<blockquote>Why the default install location is "C:\Users\name\AppData\Local\atom"</blockquote>

It seems there was no answer. Or is it just to keep things minimal? Because it's normal to expect programmers to be able to use symlinks?

<blockquote>Atom is a text editor that's modern, approachable, yet hackable to the core—a tool you can customize to do anything but also use productively **without ever touching a config file**</blockquote>

Symlinks go way beyond config files.

**Comment by Zireael07** [comment]
First, Atom should be installed under Program Files and not C:\Users\name\AppData\Local\atom. Second, the install location should be configurable.

**Comment by paulcbetts** [comment]
> It seems this decision is based on trying to apply a principle from the Mac/Linux world to the Windows world

Nope! This decision is made so that updates can happen in the background without UAC prompts. If you want to read more about the reasons behind how the installer works, check here:

https://github.com/squirrel/squirrel.windows#what-do-we-want

**Comment by PaulWalkerUK** [comment]
I realise this conversation has probably run it's course, but for what it's worth, I'm also strongly in favour of allowing users to choose the installation location. I'd much rather have that choice, even if it means dealing with UAC during an update (I think we're pretty much all used to UAC now, it really isn't a problem). 

As an example use-case, I have access to install this kind of software on some machines, but only in certain locations - symlinks would not be an acceptable "workaround".

**Comment by paulcbetts** [comment]
> As an example use-case, I have access to install this kind of software on some machines, but only in certain locations - symlinks would not be an acceptable "workaround".

Atom will soon have a Portable Version that will let you run it from arbitrary locations and it'll still update

**Comment by itodorovic** [comment]
Portable Version is not a solution. Only proper solution, which doesn't confuse users, is installing Atom to %PROGRAMFILES%\atom and additionally allowing users to change that during the installation. User created during installing Windows itself doesn't need raising privileges to install into that directory. Talk about "raising privileges" is avoiding to comply to Windows standard practices, and force feeding Linux "install anywhere" norm to Windows users who are highly unaccustomed to this.

**Comment by 50Wliu** [comment]
> installing Atom to %PROGRAMFILES%\atom

`AtomSetup.exe --machine`

> User created during installing Windows itself doesn't need raising privileges to install software into that directory

Can you elaborate?  As far as I'm aware installing anything into `%PROGRAMFILES%` requires UAC privileges.

**Comment by itodorovic** [comment]
Default user created during Win7, Win8 & win10 installation has admin privileges. Absolute majority of non-domain loged users (environments without Active Directory) run their machines this way without even being aware of it, otherwise they would not be able to install anything since (almost) all Windows  software follows convention to install in %PROGRAMFILES%. Don't break the convention, don't protect users from themselves, don't force people to uninstall Atom, and then install again with "AtomSetup.exe --machine".

**Comment by paulcbetts** [comment]
The experience of installing Windows software by convention, is awful. Updates are awful, the install experience is awful. Nobody writes desktop software on Windows, because it's awful. Why would we follow that convention?

**Comment by jeancroy** [comment]
Does atom on Linux tries to avoid sudo ?
Does atom on OS X tries to avoid the drag to /Applications dialog ?
Those are basically the same as UAC. The purpose is to make user aware of important changes.

As thing are now update are seamless, but so would be infection by a malicious software.

**Comment by enlait** [comment]
It took me much more time and effort:
- to uninstall atom when it just placed itself wherever without asking me
- to read through everything related here and in other threads
- download another package (zip)
- configure environment variable
- and now I have to manually add it to context menu by editing registry

So much for simple installer.

**Comment by balthazar40** [comment]
So... I had to read 3 complete forum posts to finally understand what was happening and why atom was installing in appdata (which is just completely weird). Ugh.
https://imgs.xkcd.com/comics/standards.png

**Comment by estomagado** [comment]
My two cents, which being two Brazilian Real cents are worth almost nothing. Anyway...

1. This is open source. And it's on GitHub. Everybody is invited to branch away and hack the installer anyway they like it. Even rebrand the branched outcome if you like. 

2. That being said, things like "works for me", "if you want it your way do it yourself", "this is  free software, i'm not your slave, if you want support you have to pay", "you have to buy a $5,000 hardware for it to work on my code" and "this is kind of a done deal, and is extremely unlikely to change" are typical and are what scare people away from free/open software.

**Comment by finkiki** [comment]
Same here. I just don't understand why i need to type "where atom is installed ?" in google to find it...

**Comment by georgejost** [comment]
This is extremely sad; an arrogant software developer dismissing perfectly valid concerns and claiming 'everybody else's software for the last 20 years is "bad"'.    Basically, like everybody else, I installed atom, it ran and then, I couldn't find it. I literally had to google and find this discussion to know where it was installed to. THIS, is an example of "bad software design" the developer is so eager to eliminate. Now, if i also pinned to my desk top and still hid the installation location to a place for Application Data and not typically applications, that might be different. Then, it would at least have been plug and play. (Note: the actual interface looks great and the software is opensource and free but I'm addressing your arrogance.)  So 1) thanks for the hard work and 2) don't be so quick to dismiss feebback like this "why doesn't it work like every other windows program" with this "I don't care about what 20 years of bad software design does".   If you care about "good design", you actually have to listen to people and care about how they are using things. That said, I intend to happily exploit your unpaid hard work as I retool and learn web stuff.

**Comment by kossboss** [comment]
Wow! I was about to install Atom and realized it doesnt ask where to install. So then I research more about it. Maybe there is a cmd option or a zip file. I find no cmd option, and I see the zip file, but i question if the zip file will update.

Then I see this paulcbetts character, an angry illogical arrogant person. If he is one of the developers of this softwar, then Im very sorry for Atom as you just lost a user (and all of my references to it). My question to you, paulcbetts, is why on earth is it bad practice to choose your install location?  I prefer all of my apps to go to D:\Programs. Not C:. Because C is my main SSD for main OS. and D is my SATA drive for apps. C will only hold the OS and or any other apps/games that require SSD. (I can almost imagine your answer here, get a bigger SSD for your C drive .... well a#$@#$@#$ not everyone can afford that, or have time for that - in my case the latter). The fallacy in your statement just shows your lack of intelligence and open-mindedness. I wouldnt hire you even if you could write up the best code, because that code probably wouldnt agree with what 99% of the population wants... Why is changing install location bad developing? Thats like saying having an installer is bad developing. If having installers is bad developing, then just make atom one giant EXE that just loads and doesnt install (kind of like Putty - the portable one). You seem to understand humanity and software developers better then the rest of us, so lets let you lead the way... to failure.

People like having options, and when you take them away you become a dictator and noone likes you or anything you stand for or produce (Atom).

Im going to not recommend this app to anyone. Thank you.

Although I will give it a try, and try my best to not think about how it has one very arrogant developer behind its scenes.

**Comment by decaylong** [comment]
Looks like this issue should keep open.

**Comment by lee-dohm** [comment]
Name calling and personal attacks have no place in the Atom community. @georgejost and @kossboss, you might have had a case until you decided to attack someone on a personal level. Honestly, I didn't even read all of your comments because once you cross that line it doesn't matter if you have the best argument in the world ... you are a drain on the community and that attitude is not welcome.

@georgejost and @kossboss, you may both consider yourselves officially warned.

Thanks everyone for your passion and feedback. We have decided we are keeping things the way they are and sticking with the installer we have for now. If people want to have a *civil* and constructive discussion about this Issue and perhaps come up with **solutions** ... please feel free to talk about it on the official Atom forum at https://discuss.atom.io.
