### ISSUE TITLE
Can't save my files :(

### ISSUE THREAD

**Issue by Qinka** [atom/atom#7137]
There is a problem . When I sometimes want to save my files , and press down "Save" or "Ctrl+S" , the file wil be empty and it saved! And then all what I had typed is lost .

**Comment by mark-hahn** [comment]
> the file will be empty

How did it get emptied?  What exact seq emptied it?

**Comment by Zireael07** [comment]
I think I saw a report or two that were similar. @Qinka: Is the folder write-protected? Is your disk full? Is this a remote location?

**Comment by Qinka** [comment]
I found that when I press down "Ctrl+S" , the editor will be empty . And if I press down "Ctrl+Z" immediately , the file will appear again ,and the file is saved.

**Comment by Qinka** [comment]
This will happen when I select a folder , where I cloned from github or is  my repo , and choice " Open with Atom" . And the files  are haskell source files.

**Comment by izuzak** [comment]
@Qinka Does this happen with every file or only some types of files? Can you reproduce this in the latest version of Atom (1.0.11)? Can you try quitting Atom and starting in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) and see if you can reproduce the problem then? And can you perhaps record a GIF of this happening (e.g. with http://www.cockos.com/licecap/), with the [keybinding resolver panel](https://github.com/atom/keybinding-resolver#keybinding-resolver-package-) shown so that it's clear which keys you're pressing?

**Comment by damieng** [comment]
No response on request for more information and no repro available. Please re-open if you can supply more information.
