### ISSUE TITLE
Atom reopens files on reload but doesn't check to see if they still exist, opens empty tabs

### ISSUE THREAD

**Issue by frankhale** [atom/atom#7143]
Atom 0.207

Scenario: open files in Atom for editing, close Atom, move files, reopen Atom and it attempts to open the files but it cannot because they have been moved but it still opens empty tabs with the same names as the files previously edited.

**Comment by frankhale** [comment]
I recently stumbled upon this behavior because I've been editing files and then cleaning up my files and moving stuff around.

**Comment by andya9** [comment]
:+1:

**Comment by 50Wliu** [comment]
Can confirm.

**Comment by esam091** [comment]
This can be easily fixed by filtering non-existent URIs when deserializing the pane [here] (https://github.com/atom/atom/blob/96a7222b0d005a5ffb588f988e272c5c083ab00f/src/pane.coffee#L50), but I think the problem lies in [this spec] (https://github.com/atom/atom/blob/96a7222b0d005a5ffb588f988e272c5c083ab00f/spec/text-editor-spec.coffee#L25-L34). It fails on my machine (Ubuntu 14.04), and after digging through the code, I don't think that the `text-editor` deserialization could return undefined as expected.

**Comment by atrotors** [comment]
:+1:

**Comment by frankhale** [comment]
This doesn't seem to be an issue anymore (at least I cannot reproduce it anymore)
