### ISSUE TITLE
Atom cursor position is broken

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#7160]
Copy this text in a new atom instance (`atom --safe`) and change the type of the text from `Plain Text` to `GitHub Markdown`:

    <div style="text-align: center;">
        <![]()
    </div>

Now place the cursor at the end of the second line (`<![]()`) and hit enter.

There are a few bugs here:

* 4 spaces will be inserted, but the cursor will be placed after the second one.
* Hitting the right arrow won't move the cursor to the right (the cursor is stuck after the second space)
* I'm not quite sure if I should be getting 4 spaces or 1 tab, as I have enabled `Soft Tabs`

**Comment by thomasjo** [comment]
I'm unable to repro this with v0.208.0-f850750 on OS X 10.10.3.

@alexandernst What version of Atom are you using, and what OS?

**Comment by lee-dohm** [comment]
Reproduced using Atom v0.208.0-2a71c4e on Mac OS X 10.10.3.

## Steps to Repro

1. Add the following to `styles.less`

    ```css
    atom-text-editor::shadow div.line:not(.cursor-line) .trailing-whitespace {
      background-color: #cc0000;
    }
    ```

1. Ensure configuration is using soft tabs and two spaces per tab
1. Launch Atom using `atom --safe`
1. Open a new file using <kbd>Cmd+N</kbd>
1. Paste in the text above
1. Move cursor to the end of the second line
1. Press <kbd>Return</kbd>

**Expected:** Cursor location to be line 3, column 3
**Actual:** Cursor location is reported as line 3, column 5

It appears that the issue is caused by some of the trailing whitespace showing in the tile **inside** the newline span?

![napkin 06-07-15 1 00 22 pm](https://cloud.githubusercontent.com/assets/1038121/8025722/29615120-0d15-11e5-962e-662cba6b8bf4.png)

**Comment by izuzak** [comment]
@lee-dohm That's strange -- I'm unable to reproduce this on the same version of Atom and OSX. After performing those steps, the cursor is on column 5 for me (visually). Maybe some config option is relevant? Can you post your config file somewhere?

I do see the "strange" HTML snippet you pointed out. The `linebreak` token comes from [here](https://github.com/atom/language-gfm/blob/156f8c0f5435ad24144b096178622c3cdcd56292/grammars/gfm.cson#L863) in order to detect trailing double-spaces in Markdown documents (which have special meaning). I think `trailing-whitespace` within that token is okay, but we can ask @nathansobo to double-check. The snippet changes to this when you type something on that line:

![screen shot 2015-06-08 at 14 06 48](https://cloud.githubusercontent.com/assets/38924/8034412/a70d2eb4-0de7-11e5-99d0-e95abae3715b.png)

This is expected since there no more double-space at the end of the line, so there's no `linebreak` token.

**Comment by alexandernst** [comment]
I'll post here how I repro the bug:

My config:

    core:
      themes: [
        "atom-dark-ui"
        "monokai"
      ]
      audioBeep: false
    editor:
      invisibles:
        {}
      tabLength: 4
      fontSize: 14
      showInvisibles: true
      showIndentGuide: true
      fontFamily: "PragmataPro, Regular"
    "isotope-ui":
      customBackgroundColorPicker:
        red: 87
        green: 86
        blue: 66
        alpha: 1
    minimap:
      plugins:
        "color-highlight": true
    tabs:
      usePreviewTabs: true
    "atom-autocomplete-php":
      binComposer: "/usr/bin/composer"
      binPhp: "/usr/bin/php"

Steps:

1. Open Atom
2. Open new tab and paste this:

    <div style="text-align: center;">
        <![]()
    </div>

3. Place cursor at the end of the second line
4. Hit enter

**Comment by alexandernst** [comment]
Oops, sorry, missed one step.

Before step 3, change the type of the file from `Plain text` to `GitHub Markdown`.

**Comment by izuzak** [comment]
Yep, using 4 spaces per tab (instead of 2) allows me to reproduce this as well -- thanks, @alexandernst.

cc @nathansobo for :eyes:

**Comment by nathansobo** [comment]
I have a small reduction in the reproduction steps. Simply save the following file to `test.md`:

```md
    <![]()
```

Then insert a newline at the end of the first line. Doesn't matter when the GFM grammar is applied for me.

**Comment by nathansobo** [comment]
Found the issue. Working on test coverage for the fix now.
