### ISSUE TITLE
New file command does nothing with no windows open

### ISSUE THREAD

**Issue by samuela** [atom/atom#7171]
I'm running Atom 0.207 on Mac. I ran into a weird scenario today where hitting cmd-n and clicking "File -> New File" did absolutely nothing. Unfortunately, I'm not sure exactly what caused this. I was adding and renaming folders and maybe using Git Plus a little bit but that's all. Anyways, here's a gif of the behavior: http://g.recordit.co/njk9NwI6M8.gif.

**Comment by batjko** [comment]
I'm on Win8.1, but can't replicate this.

Did it only happen once, or can you recreate it after restarting Atom?
If so, does it still happen after starting atom in safe mode (`atom --safe`)?

**Comment by samuela** [comment]
Well, I closed the misbehaving window, opened things up again today, and still have the same issue.

**Comment by mnquintana** [comment]
@samuela Have you followed the steps in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? Have you tried seeing if you can reproduce this in safe mode? (`atom --safe`)

**Comment by fb55** [comment]
The problem is that `cmd+n` is a no-op when there is no focussed window (see [browser/atom-application.coffee#L170](https://github.com/atom/atom/blob/a6d9b0506c1fc4aab1eb7a9ec34cb6047729514c/src/browser/atom-application.coffee#L170), which will probably only occur on OSX. The usual behavior of similar applications (eg. Sublime) is to open a new window with a new file instead.

I've fixed this on my fork and would send a PR, but are unable to locate tests for key bindings. Are there any, or is this area simply not covered yet?

**Comment by mnquintana** [comment]
@fb55 It would be great if you could open a PR for this!
