### ISSUE TITLE
Uncaught TypeError: Cannot read property 'highlights' of undefined

### ISSUE THREAD

**Issue by izuzak** [atom/atom#7183]
I was editing a CoffeeScript file, so I don't think this is related to the latex and xmllint packages I had installed at the time. It happened a few seconds after I unfolded a fold while editor had some search results highlighted.

Will try to reproduce, but so far I've been unsuccessful. cc @nathansobo for :eyes:

**Atom Version**: 0.208.0-c06d62e
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'highlights' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1654

TypeError: Cannot read property 'highlights' of undefined
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateHighlightState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1654:25)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateDecorations (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1518:18)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:130:14)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:182:38)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:298:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:168:9)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61

```

### Commands

```
     -1:33.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:33.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:33.5.0 editor:indent (atom-text-editor.editor.is-focused)
  4x -1:33 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:08.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:07.6.0 core:backspace (atom-text-editor.editor.is-focused)
  6x -1:05.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  3x -1:03.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -1:02.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  3x -1:00.4.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:56.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:39.4.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:38.4.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:37.9.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:36.9.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:07.3.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 20,
    "invisibles": {},
    "softWrapAtPreferredLineLength": true,
    "showInvisibles": true,
    "tabLength": 4,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
linter, v0.12.6
linter-xmllint, v0.0.6

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
It looks like `tileState` was undefined [here](https://github.com/atom/atom/blob/f830623512fe69c287f17fd5e02b9ad9dca401ad/src/text-editor-presenter.coffee#L1274). This seems like it shouldn't happen, since `range.start.row` is forced to be between `@startRow` and `@endRow`. /cc @as-cii do you have any ideas here?

**Comment by as-cii** [comment]
@maxbrunsfeld: tiles could have been rearranged by the folding operation and, since `@updateDecorations` actually gets executed before `@updateTilesState`, that code path could be trying to delete a tile which doesn't exist yet. Ideally, `@updateTileState` should run before `@updateDecorations`, but this would break `@lineDecorationClassesForRow` (cause it needs to access a cache which is constructed by `@updateDecorations`).

This whole layer, although not executing complex operations, is getting tangled and I would love to refactor that at some point (IMHO this is something we can do only after `1.0`). So, I'd say a quick and dirty fix could be to simply take into the account the possibility of a certain tile to be `nil`, e.g.:

```coffee
delete tileState?.highlights[decoration.id]
```

Alternatively, we may have a separate `@setupTiles` operation (or something similar) whose job is to simply handle the `@state.content.tiles` object, deleting and instantiating tiles as needed. Then, `@updateTilesState` would simply calculate positions as well as calling `@updateLinesState`.

However, let me first try to reproduce it consistently and actually confirm my hypothesis. I'll take care of it and report my findings here (or in a PR) as soon as I have made some progress.

Sorry guys if this tiling stuff is causing all these headaches to you. :disappointed:
