### ISSUE TITLE
Plugin tooltips API change - was this intentional?

### ISSUE THREAD

**Issue by nycdotnet** [atom/atom#7193]
Hi,

Recently, the tooltips for types in both the **atom-typescript** and **omnisharp-atom** plugins broke simultaneously.  In recent versions of atom, regardless of where the scroll position was in the file, the tooltips displayed by these plugins would be appropriate for what appeared at the top and leftmost "screenfull" of the file based on the mouse position.

For example:

![ExampleBadTooltip](https://cloud.githubusercontent.com/assets/3755379/8022613/7f25bd5e-0cab-11e5-9501-e2e20f23ef11.png)

The `ICompilePromise` tooltip was appropriate for that x position on line 17 of the file - not line 207.

We reported it here: https://github.com/TypeStrong/atom-typescript/issues/381 and came up with this fix: https://github.com/TypeStrong/atom-typescript/pull/384 which was adding these two lines in the code that determines the mouse position:

```js
pixelPt.top += editor.displayBuffer.getScrollTop();
pixelPt.left += editor.displayBuffer.getScrollLeft();
```

These tooltips had been working correctly up until perhaps a week or two ago.  I suspect this was due to some sort of change in Atom to the output of `getBoundingClientRect()`, or `editor.screenPositionForPixelPosition()`, or `editor.bufferPositionForScreenPosition()`.

My questions are - do you believe that this is correct, and if so, was this intentional?  Do you think this new behavior will stand or is it a bug?  To my knowledge atom-typescript didn't have any calls that were marked as deprecated prior to this bug emerging.

I looked through the recent patch notes and didn't see anything that sounds like it should have caused this problem.  Thanks.

**Comment by Krzysztof-Cieslak** [comment]
Hello,

Same story for *atom-fsharp* plugin I create. From what I've seen I believe that `editor.bufferPositionForScreenPosition()` returns exactly same coordinates as it gets no matter how much editor is scrolled.

**Comment by nathansobo** [comment]
`screenPositionForBufferPosition` and vice-versa are referring to a different concept of "screen position" than you're thinking. They refer to "logical" screen position, meaning the row, column position after taking into account folds and soft wraps.

The actual position on screen is related to `TextEditorElement::pixelPositionForScreenPosition`. That did change recently due to a change in our rendering strategy. Previously we used one massive GPU texture that we translated up and down. Now we break the lines into tiles and shift the tiles around instead, so we don't have to have a massive, mostly empty GPU texture.

I'd suggest looking into overlay decorations. They seem like the could solve your problem. Absolute positioning over the content isn't going to work with this new scheme, but it was critical that we switched for performance and loading large files, since Chrome just gave up rendering anything beyond about 600k lines. If overlay decorations don't work, please articulate your use case and we'll see what we can do. Thanks!

**Comment by lierdakil** [comment]
I'm running into the same issue with this.

Use-case:
`ide-haskell` has a feature that it shows type of expression under mouse cursor. For that, I need to get buffer position for a given mousemove event position to pass to backend. I have used some math, `screenPositionForPixelPosition` and `bufferPositionForScreenPosition` to achieve this, but now it doesn't seem possible. Any suggestions?

**Comment by lierdakil** [comment]
Okay, after some research, `TextEditorComponent.screenPositionForMouseEvent` with `TextEditor.bufferPositionForScreenPosition` seems to work. Any caveats/downsides I should be aware of?

**Comment by nathansobo** [comment]
@lierdakil That should work. Our lines are now broken into tiles which are shifted on the GPU for performance reasons. We previously had one huge div that we translated on the GPU, now we have several small divs. This leads to faster scrolling but an unfortunate side effect is we lose the ability to work in absolute pixel positions relative to all of the lines. The `screenPositionForMouseEvent` method should account for scroll position correctly and therefore is a good way to go.

**Comment by lierdakil** [comment]
Great, thanks.
