### ISSUE TITLE
EditorView - Underlayer not displayed

### ISSUE THREAD

**Issue by JohnMurga** [atom/atom#7204]
In Atom 207 the EditorView "underlayer" went missing (at least on the Windows version) ...
However, if created on demand it still displayed (https://github.com/JohnMurga/rulerz/commit/d28cb13c54939d4c92c3a016b0ed2a734eae3320)

Now on version 208 it does not display, which neutralizes a few packages that depend on it.

**Comment by thomasjo** [comment]
Since v0.206.0, Atom is shipping with the v1.0 API. The model associated with a `TextEditor` is no longer `TextEditorView` (it's been deprecated for a while), but rather `TextEditorElement`. There's no "underlayer" anymore. 

Check out e.g. [wrap-guide](https://github.com/atom/wrap-guide) for an idea how to migrate. Specifically, check out https://github.com/atom/wrap-guide/commit/f434a7cf4102d5f7a6bff72dcb3f681ccca7b947.
