### ISSUE TITLE
"Open file with..." Atom ? Why you change folder every update ?

### ISSUE THREAD

**Issue by pierretusseau** [atom/atom#7205]
Hello,

I don't really know how to get the correct Google or GitHub search to find the solution to my problem : 

When Atom is updated, the folder name containing the atom.exe changes ! The problem is that Windows obviously doesn't get anything about this, and just tell me "There is no Atom.exe in here"

Updates are awesome, I really love them, but why change the folder everytime ? Is there a solution ?
The problem is mainly that finding my installation folder is long (deep into my Users folder) and FileZilla require that I link a file to a .exe to open a cache version of it

**Comment by benplumley** [comment]
I'm having another problem caused by the same thing. My start menu item points to the version of atom that was present when I installed it first. The auto-updater doesn't edit this item, so I'll only ever open an old version of atom unless I go through my start menu and manually edit the shortcut.

Atom should be installed in %AppData%/Local/atom/latest/, not /app-0.x.0/. Technically, atom should be installed in Program Files, but that's another issue.

**Comment by Zireael07** [comment]
@benplumley: Good point.

**Comment by pierretusseau** [comment]
@benplumley yeah, exactly this ! Rename the actual folder by "latest" is just the idea.
That's wonderful to have old version (just in case) so easily, but the actual version need to be in the same folder anytime. 

I guess it's a Windows only problem (I still don't know much about UNIX) but that's not the first time I got Windows-only problems on Atom on basics (like closing / reopening Atom on windows did not save your work for long)

So here is a question : Does they have problem on Windows troubleshooting ? Or it's exactly what we're doing here that we have to do, to get a better software ? :)

**Comment by benplumley** [comment]
@pierretusseau My guess is that Windows is the primary OS of few (if any) of the Atom developers. As such, we're going to see a few things that make sense in *nix but are alien to us Windows users, such as the .atom folder being stored in the user directory and (perhaps) this problem.

Don't forget that Atom's version number is still 0.x, so it's still being developed. All we can do for now - short of making a pull request - is make a bug report like you've done.

**Comment by 50Wliu** [comment]
This is an issue with Squirrel, the installer that Atom uses, so I'm going to just ping @paulcbetts again to see if he has anything to say about this.

Also, don't forget that the `atom.cmd` path never changes (though, as mentioned in a different issue, this workaround is pretty ugly).

**Comment by benplumley** [comment]
@50Wliu Thanks. I wasn't aware of that workaround. For the benefit of @pierretusseau and others, here's what I've done:
- Create a shortcut called Atom in /atom/ pointing to /bin/atom.cmd
- Set its icon to app.ico and its Run mode to minimised
- Pin it to the start menu, quick launch bar or desktop
- Set it as the default application for opening files you'd normally open in Atom

This will add a few hundred ms to the launch time but mean that you're always starting the latest version. The only other drawback is that files you'd open with Atom have the 'file' icon rather than the 'Atom' icon.

**Comment by pierretusseau** [comment]
Well thanks for the advice, but I'm not native english, and I'm not sure to understand the full way to do it properly (as properly as this method is :p)

**Comment by paulcbetts** [comment]
Don't create shortcuts by hand, you'll have a Bad Time. Atom will update shortcuts that it creates correctly

**Comment by benplumley** [comment]
@paulcbetts You'll see in my first comment that my old method of opening Atom was to use the shortcut automatically created by Squirrel. When Squirrel updated Atom, it didn't update the shortcut, hence my *auto-generated* Start Menu shortcut now pointed to an old version of Atom. This has been the case in every version of Atom I have ever used. The only way I've found to have an auto-generated shortcut point to the correct version is to completely remove Atom from my system and reinstall.

I realise it's probably Squirrel's intention to update my shortcuts, in which case this post is to report that this isn't happening and has never happened (on two separate systems running win 7 and 8.1). The workaround I've posted, and I'm sure the workaround you've posted, work just fine.

**Comment by benplumley** [comment]
@paulcbetts Thanks, that's cleaner than the one I made, I'll switch to using that.

**Comment by Encaitar** [comment]
I used the work around suggested by @paulcbetts but I still have two issues. Icons for shortcuts created with pin to taskbar and pin to start menu are still showing as the file icon even after pointing the shortcut (change icon) to "%USERPROFILE%\AppData\Local\atom\app.ico" and the "starts in" directory is still pointing to a directory with the version number in it.

**Comment by RockyTV** [comment]
Is there any other workaround available?

**Comment by paulcbetts** [comment]
@RockyTV It is

**Comment by paulcbetts** [comment]
So, there seems to be two separate issues in this thread:

1. Atom's `--squirrel-update` code isn't running, so Explorer is getting messed up. This is something the Atom team should investigate.
1. People who make custom shortcuts have weird things happen to them. 

Are people still seeing the former? I'm far more concerned with that

**Comment by 50Wliu** [comment]
> Atom's --squirrel-update code isn't running, so Explorer is getting messed up (so "Open with Atom..." does nothing useful). This is something the Atom team should investigate (SquirrelSetup logs will help).

If that code doesn't run, will the atom scripts (`atom.cmd`, `apm`, etc) start the wrong Atom version since they weren't updated?  If so, that's happening regularly to me, and sometimes it won't fire for two consecutive updates, meaning any attempt to run `atom` from the command line returns with "the file could not be found".

**Comment by paulcbetts** [comment]
> If that code doesn't run, will the atom scripts (atom.cmd, apm, etc) start the wrong Atom version since they weren't updated? If so, that's happening regularly to me, and sometimes it won't fire for two consecutive updates, meaning any attempt to run atom from the command line returns with "the file could not be found".

Dunno how atom.cmd is written but Start Menu shortcuts should still work

**Comment by kultom86** [comment]
Fresh install here. The install seems a mess on Windows 7.

No entry in the context menu. The application in it self works just fine. 
Trying to open with the atom.exe file in ...AppData\Local\atom\app-1.1.0 does nothing. Windows wont even recognize that atom.cmd found in the ...atom\app-1.1.0\resources\cli folder is capable of opening files it seems, just as the .exe. You can select it but it is not included as an option to open the .txt file besides the likes of wordpad, notepad etc. 

"atom" is not recognized in cmd, neither is "apm". The _Path_ environmental variable has no mention of atom. 

The SquirrelSetup.log seems to note that the following a bunch of times but nothing else seems noteworthy: 
_stance: Failed to grab lockfile, will retry: C:\Users\kjetilkul\AppData\Local\Temp\.squirrel-lock-CFD2B6BFD4DB0A99363314BE9A2185C7899774F1: System.IO.IOException: The process cannot access the file 'C:\Users\*user*\AppData\Local\Temp\.squirrel-lock-CFD2B6BFD4DB0A99363314BE9A2185C7899774F1' because it is being used by another process._

I really like Atom on my linux homecomputer but, at work, on Windows its really not up to the standard i would expect of a post version 1.0 product.

**Comment by damieng** [comment]
@kultom86 Are you still having these problems on Windows?  Also are you running an antivirus?

**Comment by kultom86** [comment]
@damieng The "Open with Atom" context menu entry is available now, still the other problems are the same and i cannot set Atom as the default application for any files.
But I have not reinstalled since then either. You want me to do that? I could try the beta branch if that would make any difference. 

 Yes, for antivirus there is some company policy Symantec solution.

**Comment by damieng** [comment]
The ability to associate Atom with file extensions without having to worry about the .exe path has been addressed as part of issue #4893 with commit  and will be available in Atom 1.7.0. See screenshots at  https://github.com/atom/atom/pull/10818

If you still have problem after upgrading to 1.7.0 please feel free to reopen this issue.

**Comment by MattDiMu** [comment]
I just upgraded to 1.7.0 and the possibility to associate file extensions is great!!!

I still have a (small) problem though. If i want to open a file outside the windows explorer (e.g. in FTP/WebDAV-Clients listing all files), i must specify an exe, which is used to open the corresponding files. As some sort of "latest.exe" is missing, I still have to adjust the path to the current atom.exe after each upgrade.

**Comment by damieng** [comment]
In those scenarios it's recommended you point at c:\users]<username>\appdata\local\atom\bin\atom.cmd.

That path doesn't change.

**Comment by MattDiMu** [comment]
@damieng Thx for your rapid response. That's what i thought first as well, but it doesn't work well (at least not when using CrossFTP):
- If atom isn't already opened, nothing will happen at all (when running atom.cmd manually, atom does open, though)
- if atom is already opened, sometimes (~30% probability) a new tab with the corresponding file will open

I can't tell, whether this is an atom/windows/crossftp issue, but when using ..app-1.7.0/atom.exe, it will work reliably. So I will keep using the exe path and change it from time to time...

**Comment by nnt25251325** [comment]
**> Atom should be installed in Program Files**

**Comment by yalov** [comment]
Total Commander's edit/view settings still need constant path to atom.exe, [screenshot](https://s14.postimg.org/ycgo94eg1/2016_11_29_172404.png).

`%LocalAppData%\atom\update.exe --processStart atom.exe` is working; is it appropriate way, or is there something better?

**Comment by damieng** [comment]
@yalov That works as does linking to the atom.cmd in the %localappdata%\atom\bin folder

**Comment by hoobtron** [comment]
same problem in WinSCP, by defining Atom as external editor... please see screenshots:

1. I have to edit the path manually after every update
![editor anpassen 2017-02-13 11 04 47](https://cloud.githubusercontent.com/assets/19549029/22879255/6ae64066-f1dd-11e6-8843-48042d248c7d.png)

2. while using `update.exe --processStart atom.exe`: Atom is called "Update" in the context menu
![editor anpassen 2017-02-13 11 02 33](https://cloud.githubusercontent.com/assets/19549029/22879274/798d9fec-f1dd-11e6-9f6c-eb25475efb67.png)

**Comment by damieng** [comment]
In Atom 1.14 and above you'll find an atom.exe in %appdata%\Atom (the parent folder above the app-x.y.z) that doesn't move between releases.
