### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by ghost** [atom/atom#7210]
To reproduce:
1. `dd if=/dev/zero of=largefile count=1 bs=1000M`; if this does not reproduce play around with adjusting `bs` and `count`.
2. Open atom and try to open `largefile`.

**Atom Version**: 0.208.0
**System**: Ubuntu 15.04
**Thrown From**: Atom Core
### Stack Trace

Uncaught RangeError: Invalid string length

```
At /usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:301

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:301:43)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
```
### Commands

```
  2x -3:24.1.0 release-notes:show (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "tabLength": 4
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Raynes** [comment]
Just got this as well.

**Comment by izuzak** [comment]
There's another report of this and more details in https://github.com/atom/atom/issues/7417.

/cc @nathansobo

**Comment by arindell** [comment]
[Enter steps to reproduce below:]

1. Atom was already open
2. try to open a 360 MB log file with Atom

**Atom Version**: 1.0.0
**System**: Windows 7
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length

```
At D:\xxx\Atom\resources\app.asar\node_modules\pathwatcher\lib\file.js:301

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (D:\xxx\Atom\resources\app.asar\node_modules\pathwatcher\lib\file.js:301:43)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by ButchDean** [comment]
Tried to open a 360MB text file and got this too.

**Comment by cutecreep** [comment]
76 MB file broke it

**Comment by buz-zard** [comment]
336MB file, also broke

**Comment by ssbarnea** [comment]
Anyone working on this? It does limit the use of ATOM, a lot.

**Comment by wismill** [comment]
Wow, I did not expect such limitation. Also broke here with 277MB.

**Comment by magic890** [comment]
Atom 1.2.4 on 324MB file gets broken. I've to keep using Sublime Text to deal with these situations. Fix this please.

**Comment by magic890** [comment]
After a bit of research ([source](http://blog.lycheejs.org/limits-of-using-v8-for-crunching-data/)) I think that I've found the cause:

`RangeError: Invalid string length` meant that the `String.prototype.length` property was not representable in 32Bit. The [IncrementalStringBuilder's part_length property](https://github.com/v8/v8/blob/master/src/string-builder.h#L406) is using a simple `int` to represent the length of a `String`.

Quoting [@mraleph here](https://twitter.com/mraleph/status/610039453424447488), v8 has a `String` length limitation of `(1 << 28) - 16`. I assume this limitation is due to sign and pointer allocations (or reserved types that is checked against inside the VM).

> (1 << 28) - 16
> 268435440  

This is the actual maximum size of all `String` lengths. As even the `Buffer` implementation in IOJS is using Strings to represent binary data, you can't exceed that limit with a single `String`. So, if you try to read or write a file synchronously that is larger than ~268.44MB, you know that you will get an error message.

An alternative solution would be either splitting up the database with a mask (easiest method) or implementing an asynchronous pointer-manager and `Stream` writer implementation that uses `String` chunks smaller than 268435440 bytes and has an own virtual memory stack with chunks.

**Comment by mitchellcash** [comment]
Steps to reproduce below:

1. Download Australian Company Dataset from http://data.gov.au/dataset/asic-companies/resource/a1df019f-cb11-43e8-8d5d-0f830115c8a6
2. You will download a CSV which is 815.4 MB on disk
2. Open CSV in Atom

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:317

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:317:38)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 11,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by magic890** [comment]
@kevinsawicki please have a look into this.

**Comment by jersten** [comment]
I want to confirm that this is still an issue:

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:307

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:307:38)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

**Comment by mitchellcash** [comment]
If I follow the steps in my previous comment (https://github.com/atom/atom/issues/7210#issuecomment-195286365) I still get the same issue, so it doesn't seem like this issue is solved.

Atom now seems to be directing me to issue https://github.com/atom/atom/issues/11690, so I have added 'Steps to Reproduce' there as well.

**Comment by 50Wliu** [comment]
@mitchellcash The issue has been fixed, it just hasn't reached a stable version of Atom yet.  We close issues as soon as the fix is merged into the master branch, not when it is released.

**Comment by iamtodor** [comment]
The same issue has happened. The .csv fIle is 278M. 
```
Uncaught RangeError: Invalid string length
/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:314
Hide Stack Trace
RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:314:44)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Also, it tells me: `This is likely a bug in Atom. This issue has already been reported.` and gives me link to the issue [#14229](https://github.com/atom/atom/issues/14229)

**Comment by maxbrunsfeld** [comment]
@iamtodor You might want to try opening this file with the Beta version of Atom, Atom 1.19. This issue should be fixed already.

**Comment by iamtodor** [comment]
@maxbrunsfeld thank you for the reply, for the suggestion. Could you please help me to update from stable `1.18.0` to `1.19.beta4`?

**Comment by 50Wliu** [comment]
@iamtodor You can install the Atom Beta at https://atom.io/beta.  You'll be able to freely switch between Atom and Atom Beta whenever you want (your existing Atom installation will not be overridden).
