### ISSUE TITLE
Why is the font so big by default?

### ISSUE THREAD

**Issue by Daniel15** [atom/atom#7220]
The default font size seems extremely large compared to every other editor I've used. Why is it so big?

**Comment by zurawiki** [comment]
I agree with @Daniel15. The default is way too big. I end up changing my config to 12px. I would even be happy with something smaller

**Comment by mehcode** [comment]
Because poor fools like me are blind. Defaults are just default.

**Comment by herkyl** [comment]
@mehcode :+1:

**Comment by Daniel15** [comment]
Defaults should be what most people want to use. There's some good uses for large text, but I think the majority of users would prefer a default text size similar to every other text editor.

**Comment by simurai** [comment]
Maybe it's because the default font (`Inconsolata`) is a lot smaller than other fonts, like `Input Mono`. See this issue with the mini editors: https://github.com/atom/one-dark-ui/issues/63#issuecomment-100432024

![font](https://cloud.githubusercontent.com/assets/378023/7548890/fe95d7ae-f658-11e4-8afc-434be3cec703.gif)

We could make it a bit smaller, but then also remove `Inconsolata` as default font. Also, since it's not a system font and only gets used if installed.

**Comment by mnquintana** [comment]
Also related to https://github.com/atom/atom/issues/4201

That totally explains the large font size (I've never had Inconsolata installed, so I didn't realize it was smaller than comparable fonts) and the low line-height.

If we do this, I think we should:
- Change the font-size to `14px`
- Change the line-height to something a little less cramped with non-Inconsolata (say `1.5`)
- Remove Inconsolata as a default font (I'd say we should keep everything as-is if we *shipped* with a default font, but since we don't and instead rely on the user having it installed, we're not really enforcing it anyway)

**Comment by Zireael07** [comment]
@mnquintana: Good point. I was long advocating for Droid Sans;Droid Sans Fallback duo as the default. Good readability and CJK support. I think there was an issue on CJK wrap where people pitched their choices.

**Comment by Daniel15** [comment]
> Maybe it's because the default font (Inconsolata) is a lot smaller than other fonts

That's possibly it - I don't have Inconsolata installed on my system. I don't think it's a good idea to rely on characteristics of a non-standard font, and just use standard fonts out of the box. If someone wants to use Inconsolata, they can just edit the config.

**Comment by simurai** [comment]
Made a PR #7281 which would change it to `Menlo`. Maybe good to do it pre 1.0.

**Comment by tj** [comment]
anything change here? in 1.25.1 the default font seems crazy massive

**Comment by lee-dohm** [comment]
No, the default is 14px like it has always been. Since whatever issue you're experiencing is pretty much guaranteed to not be related to this issue that has been closed for almost three years, I would encourage you to open a new issue and fill in the template if you're having a problem that you can reproduce in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode). Additionally, you can use all of the Chromium Developer Tools built-in to Atom to determine what the source of the problem might be.
