### ISSUE TITLE
Code sometimes improperly marked as comment

### ISSUE THREAD

**Issue by adamreisnz** [atom/atom#7256]
Sometimes, when copy/pasting some code around with comments, I notice that part of my code becomes improperly marked as comments. You can see it happened here, and it becomes normal again when you play around with the comment above it:

![ex](https://www.dropbox.com/s/74wmso8114588gg/commented%20code.gif?dl=1)

Unfortunately, I have not yet found out how it can consistently be reproduced, but I've seen it happen at least 5-6 times already. 

I suspect though that it has to do with comment blocks starting with /*. As you can see in the screen recording, the marking seems to end at the */ in the path definition, so it looks as if it's thinking the code above it is part of a comment block still.

This is on Max OS X, Atom 0.209.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/language-javascript?

**Comment by adambuczynski** [comment]
I don't think it's only javascript related, I recall seeing it happen in CSS as well. Is that possible?

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (`atom --safe`)

**Comment by adambuczynski** [comment]
Well, as I said, I haven't found a way to reproduce it yet consistently, but once it happens again I will try to analyze what I did and see if I can reproduce it.

**Comment by adambuczynski** [comment]
@mnquintana I have found a way to reproduce it consistently, see attached screencast:

![ss](https://www.dropbox.com/s/4k3lhd8aeam1ryp/commented%20code%202.gif?dl=1)

It appears to happen when a doc block comment is started and then completed via code completion. 

When you enter the first few characters ('/*'), the trailing code is marked as a comment, because there's no comment ending found (`*/`).

However, once the code completion is triggered and the comment ending is inserted, the rest of the code remains flagged as a comment and does not get updated.

Hope this helps.

**Comment by adambuczynski** [comment]
@benogle this issue also has consistent reproduction steps now, can you relabel it as a bug?

**Comment by benogle** [comment]
Sure. This seems like a `language-javascript` issue, no?

**Comment by adambuczynski** [comment]
I'm pretty sure it also happened to me in SCSS files once or twice, so not sure which package is responsible. It's not like the language detects it wrong, I think it's that the language detects it a split second before the comment is completed by the auto completer, and then never updates it afterwards.

**Comment by 50Wliu** [comment]
@adambuczynski How are you triggering autocompletion for the comment block?

**Comment by adambuczynski** [comment]
This is my snippet for the code block:

```cson
'.source':
    'Comment block':
        'prefix': '/*'
        'body': '''
            /**
             * ${1:Comment}
             */
        '''
```

And it's triggered by `/*` + `tab`

**Comment by 50Wliu** [comment]
I can't reproduce this using the provided snippet on Java, JS, or C files.  Please tell me if I'm doing something wrong (provided GIF is using language-c).
![comments](https://cloud.githubusercontent.com/assets/2766036/12936130/3347a51a-cf69-11e5-8b85-0732653b444e.gif)

`apm list --installed --bare`:
```
file-icons@1.6.14
find-and-replace@0.197.1
fizzy@0.16.0
language-c@0.51.1
language-coffee-script@0.46.1
language-csharp@0.11.0
language-gfm@0.84.0
language-git@0.11.1
language-html@0.44.0
language-java@0.17.0
language-javascript@0.110.0
language-latex@0.6.1
language-make@0.21.0
language-objective-c@0.15.1
language-php@0.37.0
language-python@0.43.0
language-ruby@0.66.0
language-sass@0.42.1
language-shellscript@0.20.0
language-sourcepawn@0.6.0
language-sql@0.19.0
language-toml@0.17.0
language-xml@0.34.1
language-yaml@0.25.1
linter@1.11.3
linter-coffeelint@1.1.2
linter-csslint@1.2.0
linter-eslint@6.0.0
linter-javac@1.5.0
merge-conflicts
pdf-view@0.39.0
script@3.4.1
tabs@0.89.0
travis-ci-status@1.0.0
tree-view@0.200.0
```

Atom 1.6.0-dev-d091a10, Windows 10 x64.

**Comment by adambuczynski** [comment]
@50Wliu can you try with the following code? This works consistently for me:

```js
function() {

  <insert comment here>

  //Comment
  return test;
}
```

This will turn the line `return test;` into a comment, after you tab complete the snippet.

**Comment by 50Wliu** [comment]
Still nothing.  I noticed you're using language-javascript@0.81.0 though, while the latest version is 0.110.0.

I would try to reproduce in safe mode but I don't think `snippets.cson` gets loaded in that scenario.

**Comment by adambuczynski** [comment]
I was using a development version of the package, as I had made some changes to it. Removed this now, and on 0.105.0 now (version bundled with 1.5.0 atom I suppose).

The issue is still reproducible though. Perhaps it only occurs on Mac due to some differences in keyboard input handling? Is there someone else on the dev team with a Mac that could check this behaviour?

**Comment by liatreis** [comment]
Same issue for me on Windows 7, so not for Mac only.

**Comment by adambuczynski** [comment]
Here's another demo of it happening inside a `describe` test block

![ss](https://www.dropbox.com/s/eol19xtbbkewzvn/comment-error-2.gif?dl=1)

I think the issue has to do with the fact that maybe the code highlighting isn't run again after the auto completed code is inserted, making the highlighter think that the comment was never closed, hence never un-marking the code from being a comment. Is that a possibility?

**Comment by adambuczynski** [comment]
In case anyone wants to reproduce, this is the snippet I use that's causing the issue:

```cson
'.source':
    'Comment block':
        'prefix': '/*'
        'body': '''
            /**
             * ${1:Comment}
             */
        '''
```

**Comment by Ben3eeE** [comment]
I did some investigating and managed to figure out when this happens I think, it has to do with whitespace/invisibles/indentation on all the lines. I did not manage to reproduce when copy/pasting as the original post stated but didn't test much with copy/pasting.

Example, if you expand this snippet in a js file it reproduces, this is with the default js snippet for block comments no custom snippets needed.
```
function a(b) {
    /**
<NON INDENTED EMPTY LINE WITH ONLY A CRLF OR LF CHARACTER>
    var c = b +15;
    return c;
}
```

But not if you expand this:
```
function a(b) {
    /**
    <INDENTED EMPTY LINE>
    var c = b +15;
    return c;
}
```

And not if you expand this:
```
function a(b) {
    /**
<NON INDENTED EMPTY LINE WITH ONLY A CRLF OR LF CHARACTER>
        var c = b +15;
    return c;
}
```

Also not if you expand this:
```
function a(b) {
/**
<NON INDENTED EMPTY LINE WITH ONLY A CRLF OR LF CHARACTER>
var c = b +15;
return c;
}
```

Also not if you expand this:
```
function a(b) {
    /**
<NON INDENTED EMPTY LINE WITH ONLY A CRLF OR LF CHARACTER>
        <TABBED LINE PAST THE SNIPPET LINE>
    var c = b +15;
    return c;
}
```

But it does if you expand this:
```
function a(b) {
    /**
<NON INDENTED EMPTY LINE WITH ONLY A CRLF OR LF CHARACTER>
<NON INDENTED EMPTY LINE WITH ONLY A CRLF OR LF CHARACTER>
    <TABBED LINE NOT PAST THE SNIPPET LINE>
    <TABBED LINE NOT PAST THE SNIPPET LINE>
    var c = b +15;
    return c;
}
```

I am on Windows 7 with Atom 1.8.0, I can maybe test the latest master later but I don't have it built now because I am on the node4 npm3 branch.

**Comment by adamreisnz** [comment]
I don't think this is happening anymore, so I'm going to close this issue. Must have gotten fixed somewhere along the line.
