### ISSUE TITLE
Thin or small fonts rendered on Windows appear colorfully blurry.

### ISSUE THREAD

**Issue by xFleury** [atom/atom#7261]
![Image of blurry/colorful font rendering](http://i.imgur.com/Crkn7gz.png)

Until looking through the code, I had thought Atom was using Microsoft's WPF graphics rendering interface for the GUI. In which case the solution is simply setting the text-formatting option to "Display" rather than the default "Ideal".

www.hanselman.com/blog/WPFAndTextBlurrinessNowWithCompleteClarity.aspx

I don't know what's causing blurry fonts on Atom, but it's certainly not my system configuration to blame; I'm not using any unusual settings/hardware; default DPI with a 1440x900 display. Other software (Notepad++, Visual Studio, Eclipse, etc) render fonts just fine.

**Comment by as-cii** [comment]
Hey @xFleury, thanks for leaving your feedback! :bow: We are aware that there are some issues with text rendering on Windows and we have already planned to work on them, although they usually arise with high-DPI screens.

Is this something that appeared recently? If yes, would you help us tracking down which version was the culprit? 

Atom doesn't use WPF internally, but it simply delegates to Chromium (and its internals) the hard work of rendering and painting on screen. Thus, I am afraid we're out of luck with the "Text Formatting" option. By having a look at the screenshot you provided, though, I can tell that the text is being render using sub-pixel antialiasing (which normally is a good thing). As a temporary workaround, you may try to force Chrome to ignore this setting by dropping the following snippet into your `styles.less`:

```less
atom-text-editor::shadow .lines {
  -webkit-font-smoothing: antialiased;
}
```

This will make text rendering fall back to grayscale anti-aliasing and should, at least, prevent this unfortunate *colorful blurriness* you're experiencing. Not sure, though, if it will make the experience reasonably acceptable.

My hope is that we will be able to fix this once for all as soon as we complete #6055: that will enable us to make use of the recent `subpixel-font-scaling` feature which, based on the [IE 9 blog](http://blogs.msdn.com/b/ie/archive/2010/11/03/sub-pixel-fonts-in-ie9.aspx), fixes blurriness for *normal* screens as well as high-DPI ones.

/cc: @nathansobo @paulcbetts

**Comment by paulcbetts** [comment]
The text on non-high DPI screens (i.e. 96DPI) actually looks pretty alright, it seems unique to high-DPI screens

**Comment by nathansobo** [comment]
@paulcbetts Do you think re-enabling subpixel font rendering could fix the issue. Seems like it might. In that case #6083, which fixes our character measurement, will enable us to turn that back on.

**Comment by paulcbetts** [comment]
@nathansobo I'm gonna try it on my machine that repros this issue on Monday (/cc @as-cii, was gonna do this on Friday but wasn't able to)

**Comment by paulcbetts** [comment]
So, it appears that subpixel font rendering doesn't actually have much of an effect - this isn't super surprising, on High DPI displays the pixels are already too small to be visible. 

However! Disabling `direct-write` does seem to improve text quality, at the (possible) expense of scroll speed. DirectWrite is also soon becoming the main (only?) render platform in Chrome, so disabling it is probably a short-term solution.

Another interesting facet of this bug is that it seemed as if the font _size_ had an effect - as I hit `Ctrl-+`, the font would go blurred => not blurred => blurred, which is Odd™.

**Comment by as-cii** [comment]
Thank you @paulcbetts for your extensive investigation! :clap: 

> So, it appears that subpixel font rendering doesn't actually have much of an effect - this isn't super surprising, on High DPI displays the pixels are already too small to be visible.

This is interesting: I have always assumed that the blurring could have been caused by pixels being scaled inappropriately, thereby introducing some rounding error which, in turn, made characters look blurry.

> Another interesting facet of this bug is that it seemed as if the font size had an effect - as I hit Ctrl-+, the font would go blurred => not blurred => blurred, which is Odd™.

This would seem to confirm the above hypothesis and sub-pixel font scaling *should* have an effect on text rendering I am not quite sure why it doesn't. @paulcbetts: could you confirm that lines (`.tile` and `.line`) are being positioned with integral coordinates (i.e. `Math.round(x) == x`) across font sizes? @nathansobo: could it be possible that something like e.g. `lineHeightInPixels` is the culprit?

Now that I think about it, I recall @paulcbetts reporting that `translate` worked just fine and, as far as I know, `translate` in Chrome rounds pixels automagically (http://stackoverflow.com/a/18259138/464250, not sure if this is actually correct though).

@paulcbetts: Also, I am wondering... Could you try reproducing this through a bare minimum example which makes use of `translate3d`? Probably you can simply try it in a Chrome web page, although it's probably better to build a simple Electron application which matches Atom's version. The idea is to have only something like the following:

```html
<html>
<body>
<div>
  <div style="-webkit-transform-3d: translate(0, 10px, 0); background-color; black; color: white;">
    <span>Hello World!</span>
  </div>
</div>
</body>
</html>
```

And check if it looks blurry. If it does, it could be interesting to check if changing the translation amounts (e.g. `9px`, `9.5px`, etc.) has any effect on text rendering.

@paulcbetts: I am sorry for asking you all this stuff; I'd love to investigate this without bothering people but I haven't got any High-DPI machines at hand, unfortunately. If you don't feel like giving this a try, it's totally fine and I would understand that. So, thanks anyway! :raised_hands: 

> However! Disabling direct-write does seem to improve text quality, at the (possible) expense of scroll speed. DirectWrite is also soon becoming the main (only?) render platform in Chrome, so disabling it is probably a short-term solution.

I agree we need to solve the issue in harmony with DirectWrite and I'll definitely do some more research on this in the meantime.

**Comment by as-cii** [comment]
@paulcbetts: also, how does the gutter render compared to text lines?

**Comment by as-cii** [comment]
On a side note, I have managed to reproduce it with the following configuration:

* Windows 8.1 Virtual Machine (virtualized via Parallels)
* 1080p display
* 150% scaling (both for all the displays, or just the current one)

I have been playing with the DOM under the above configuration and, apparently, everything looks crisp when I round `translateY(n)` to an odd number. This seems to be somewhat similar to the problem that was reported [over here](https://code.google.com/p/chromium/issues/detail?id=424394): I would classify this as a Chrome bug, though, and, as a result, we should probably collaborate with them to identify what's the root of this pesky issue.

@paulcbetts: as a stopgap, would you be willing to try out [this branch](https://github.com/atom/atom/tree/as-odd-tiles) and see how it performs on your machine? It basically applies to the code what I stated previously about the odd `translateY` value.

**Comment by paulcbetts** [comment]
> Now that I think about it, I recall @paulcbetts reporting that translate worked just fine and, as far as I know, translate in Chrome rounds pixels automagically (http://stackoverflow.com/a/18259138/464250, not sure if this is actually correct though).

`translate` seems to improve but not fix the situation - what completely fixes it is removing the translation altogether (but of course, breaks the app)

**Comment by paulcbetts** [comment]
> I have been playing with the DOM under the above configuration and, apparently, everything looks crisp when I round translateY(n) to an odd number. This seems to be somewhat similar to the problem that was reported over here: I would classify this as a Chrome bug, though, and, as a result, we should probably collaborate with them to identify what's the root of this pesky issue.

Could that multiple be related to `devicePixelRatio`? Or will it always be an odd number

**Comment by as-cii** [comment]
> Could that multiple be related to devicePixelRatio? Or will it always be an odd number

As far as I can tell it works just by using odd numbers on my machine, but Your Mileage May Vary™. The more I think about this, the more I am convinced it’s not an issue on Atom and Chrome 2d and 3d translations are the culprit instead.

@nathansobo: how should we proceed on this? Should we fallback to `top/left` positioning for High DPI Windows machines? Or it’s just better to contact the Chrome team and work with them to fix this problem?

**Comment by nathansobo** [comment]
@as-cii Good question. We should try to come up with a workaround if we can. Can we detect when we're in hi-DPI mode? If so, rounding to the nearest odd pixel could be an interesting route, since it probably won't be noticeable at that resolution. Then we can get some feedback on whether this helps and if it doesn't fix things in enough scenarios, drop back to a non-accelerated translation.

Either way, it would be good to open a bug on their issue tracker if one isn't already there. Maybe we can send some emails to direct attention to it.

**Comment by paulcbetts** [comment]
@nathansobo Yeah, it's just `window.devicePixelRatio > 1.0`

**Comment by as-cii** [comment]
@paulcbetts: using a multiple of `devicePixelRatio` doesn’t seem to work on my machine, whereas using odd numbers seems to be quite right. This has definitely something to do with this *invisible pixel grid* which comes from DPI and how the OS handles it. What is your experience with that branch? I have added a couple of commits more and I believe each one is worth a `git checkout`. Could you share how do those changes feel on a real high DPI machine?

@nathansobo: I am going to write down something and then I’ll report a bug where appropriate (either a new issue or a previous, yet similar one) in the next couple of days. :rocket:

**Comment by 50Wliu** [comment]
Just commenting to say that I now have this issue on a new laptop that's at 150% DPI (the recommended was 125%, but that was a bit too small for me).  I can confirm what @paulcbetts said about increasing the font size alternating between blurry and not-blurry.

Atom 1.9.0-dev-6991246, Windows 10 x64, 1920x1080 screen.

**Comment by kaamaru** [comment]
Yeah same problem as @50Wliu

**Comment by framerate** [comment]
Dell XPS 13 is a great device to test this on. 150% scaling by default, it's only $1000 and it's a great little machine (except atom and apparently all other electron-based apps are blurry)

**Comment by as-cii** [comment]
Closing this, as I think it has been solved by https://github.com/atom/atom/pull/15372.
