### ISSUE TITLE
Orphaned line numbers

### ISSUE THREAD

**Issue by benogle** [atom/atom#7306]
While screensharing with @nathansobo I got into a situation where there were some orphaned gutter elements. 

![screen shot 2015-06-16 at 2 59 54 pm](https://cloud.githubusercontent.com/assets/69169/8196572/e17cee08-1441-11e5-84fc-530848a900ce.png)

The gutter component only had a reference to the line numbers at the top of the screen. Not sure of exact repro steps, but i wasnt able to get rid of them.

I was working on a long md doc with softwrap on. I had been working on this doc for 2 days. The atom window had been through several resizes.

cc @as-cii maybe you have insight into this.

**Comment by as-cii** [comment]
I have just opened a PR which should fix this :bug:.

For posterity, here are some reproduction steps that worked for me:

1. Write a few paragraphs of text (ensure it enables vertical scrolling).
  a. It can be either soft-wrapped or not.
2. Scroll to the very bottom.
3. Split the pane (I split it right, but I think `left` or anything else will do).
4. Ensure that splitting the pane has caused the editor on the left to scroll up.
5. Scroll the left panel again to the very bottom;
6. Close the right panel;
7. :boom: 

The effect should be similar to the one you reported, e.g. line numbers that are not cleaned up after scrolling down/up or, worse, that overlap other line numbers.

**Comment by maxbrunsfeld** [comment]
I'm seeing another weird gutter behavior, and I'm wondering if you think it's the same bug. Occasionally the fold buttons in the gutter cause the incorrect fold operations:

![fold-bug](https://cloud.githubusercontent.com/assets/326587/8244236/4c4d7c6a-15d3-11e5-8876-10ecb7d95a8e.gif)

Unfolding works as expected, but when I click the fold icon next to line 9 to *create* a fold, instead of creating a fold at line 9, it scrolls the editor slightly, and then creates a fold at line 6. Creating folds from the keyboard (via `editor:fold-current-row`) works.

**Comment by as-cii** [comment]
> I'm seeing another weird gutter behavior, and I'm wondering if you think it's the same bug.

The previous bug was generated by a race condition that arose when multiple instances of `TextEditorComponent` were created.

> This only happens to me intermittently. Is there any code that I can run when I get into this state to verify whether or not it's the same bug?

I am not quite sure this is the exact same bug, as you don’t seem to have orphaned line numbers. If you want to make sure my hypothesis is correct, though, you could simply try to:

* Make sure you have only one open buffer.

* Delete everything from the current buffer.

* Execute the following snippet in Chrome DevTools:

  ```javascript
  document.querySelectorAll("html /deep/ .line-number").length
  ```

If the result is more than `2` (i.e. the dummy line number + the `1` line number), then some dangling line numbers were created. 

However, I suspect this could be caused by some stale event listener attached to the recycled gutter DOM node (https://github.com/atom/atom/blob/as-odd-tiles/src/line-number-gutter-component.coffee#L18-L19). 

@maxbrunsfeld: I am able to reproduce a similar :bug: and I am going to open a new issue so that we can tackle this bug separately. :+1:
