### ISSUE TITLE
Quickly growing large files freeze Atom

### ISSUE THREAD

**Issue by kankaristo** [atom/atom#7379]
Atom's large file support is working really well now. I can open files that are nearly a million lines long and tens of megabytes in size. Thanks for all the hard work! :+1:

However, if I have a file already open, and it grows from being empty to ~20 MB in a matter of seconds, Atom can't keep up and freezes (_indefinitely, just short of crashing_).

Closing the file and reopening it after it has stopped changing works fine, but Atom can't keep up with a big, rapidly changing file.

Maybe Atom could default to _not_ automatically reload large files when they change on disk, but instead show a popup with a manual reload button? This could be determined simply by how big the file is, or by tracking how often the file changes.

(The file in question is a program log with lots of debug messages, which grows to nearly 500 000 lines in about 10 seconds)

**Comment by emilesilvis** [comment]
I'm not entirely sure that my issue is related to this issue, but I have a Rails project with a lot of migrations in db/migrations, and whenever I open or close that directory in tree-view, it freezes for about 5 seconds. I'm assuming it's the same root cause.

![image](https://cloud.githubusercontent.com/assets/557338/8373340/3d0911dc-1bec-11e5-81f1-3bb412bec977.png)

**Comment by stramel** [comment]
#979 is still open, was on the 1.0 roadmap and 1.0 has been released. Atom still has major issues opening large files. Not to degrade the great work being done here but it is pretty sad when Microsoft's Visual Studio Code does a better job handling large files or long lines (Even on non-windows).

**Comment by dantarion** [comment]
I think what happens here is that every time the file changes size, Atom goes to reload the file. Since this happens sometimes hundreds of times as the file is being rewritten, Atom freezes up until it reloads the same file over and over again.

I think Atom should delay reloading a file until the file hasn't been updated for 1000ms or something similarly snappy. This limits the number of reloads/sec. We may want to look and see how other editors handle this situation.

**Comment by stramel** [comment]
Still an issue even in Beta version

**Comment by lee-dohm** [comment]
Thanks for the input.

While we understand that this is useful for some workflows, this isn't something that the Atom maintainers are going to be working on in the near term. Since we use our issues list as the Atom team's backlog, we close issues that we don't intend to work on. If at some point we decide to take this on, we'll reopen this issue. As things currently stand, we would most likely not accept a pull request for this.

Thanks again for all the feedback!
