### ISSUE TITLE
Subpixel anti-aliasing not working on some lines

### ISSUE THREAD

**Issue by burodepeper** [atom/atom#7382]
![schermafbeelding 2015-06-23 om 12 01 09](https://cloud.githubusercontent.com/assets/3703530/8303799/e064c7de-19a0-11e5-8284-0e75df171ea6.png)

I think the screenshot says it all.
I'm using Atom 0.211 on Max OS X 10.3

The brighter colors (although I prefer them) are "wrong". The are rendered with greyscale anti-aliasing, in contrast to the other lines which have normal subpixel anti-aliasing.

This particular occurrence of the bright lines is 12 lines high, one of them being soft wrapped.

The occurrence and position of a bright area is rather arbitrary. I can't readily reproduce it, because slightly resizing the window horizontally removes it or produces it elsewhere. Switching tabs seems to fix it.

**Comment by izuzak** [comment]
Thanks for the report, @burodepeper. Can you let us know which theme you're using and if you have any custom styles in your styles.less file? 

Also, this sounds a bit similar to https://github.com/atom/atom/issues/7316. /cc @as-cii

**Comment by burodepeper** [comment]
Definitely has similarities. Didn't find the issue because I was focusing on `color` etc.

UI Theme: Atom Light
Syntax Theme: Mac Classic

```css
atom-text-editor::shadow {
  .text {
    .source {
      background: transparent;
    }
  }
}
```

The fix in styles.less is to fix an issue in the theme I haven't updated in the repository yet. As karal17 mentioned in the other thread, this issue seems to have appeared quite recently.

**Comment by njoannidi** [comment]
I've noticed this too -- it seems to be most noticeable if a line scrolls off the side of the editor for me.

**Comment by burodepeper** [comment]
I've noticed that something similar can happen within a single line 
v1.0.2

![schermafbeelding 2015-07-11 om 11 51 27](https://cloud.githubusercontent.com/assets/3703530/8633347/a18580f4-27c3-11e5-9404-cad9579162e3.png)

**Comment by as-cii** [comment]
@izuzak: this is definitely related to the syntax theme being used: I haven’t had the time to have a look at it yet, but I think that some styling is preventing certain lines to make use of subpixel anti-aliasing. Thanks for the heads-up, anyway! :raised_hands: 

> I've noticed that something similar can happen within a single line
>
> ![screenshot](https://cloud.githubusercontent.com/assets/3703530/8633347/a18580f4-27c3-11e5-9404-cad9579162e3.png)

@burodepeper: I think this is a different issue from the one you originally reported. Subpixel anti-aliasing is working nicely in the screenshot, but for some reason the line is not being “colored” correctly, probably because of one of the following reasons:

1. The line is too long (we have a limit for how many tokens we parse in a single line).
2. The grammar is not parsing the source code correctly.

> The fix in styles.less is to fix an issue in the theme I haven't updated in the repository yet. As karal17 mentioned in the other thread, this issue seems to have appeared quite recently.

I have yet to inspect `Mac Classic`, but that `transparent` background could potentially be the root of the issue here. Does deleting it help solving the problem?

Also, could you suggest a way of reproducing the problem consistently, please? That would definitely help speeding up the resolution of this regression. Thank you! :pray:

**Comment by burodepeper** [comment]
@as-cii Okay, got it. I'll dig into it a bit further, and work on something more reproducable.

**Comment by burodepeper** [comment]
@as-cii The `background: transparent` seems to indeed have been the culprit. Is this that kind of bug you want to pretend doesn't exist? I haven't been able to consistently replicate it. It just seem to happen, rather at random actually.
