### ISSUE TITLE
Request to add "frame" and "transparent" as config settings

### ISSUE THREAD

**Issue by smaili** [atom/atom#7439]
Just wondering if the `frame` and `transparent` options can be added to the config setting that Atom loads on startup?  I'm thinking under the `editor` namespace.

Maybe something like:

```
'core':
  'excludeVcsIgnoredPaths': true
'editor':
  'frame': false
  'transparent': true
```

**Comment by izuzak** [comment]
@msmaili Can you clarify what exactly these config settings would do? Also, if they're not related, I suggest you open separate issues for this, instead of bundling two feature requests into a single issue.

**Comment by msmaili** [comment]
@izuzak, you're right!  Let me be more specific :)

The `frame` config refers to window chrome/title bar, and `transparent` refers to the window having a transparent background.

According to this post - https://github.com/atom/atom/issues/4599#issuecomment-73973658, the current way of having this enabled is by editing the `atom-window.coffee` file and having to re-build Atom, which I think for many people would be much better to have as a configuration that can be read on startup.

I apologize for creating a single issue for both properties, in my head they seemed related since they're both boolean values that can be set on the window.

**Comment by mnquintana** [comment]
@msmaili Thanks for the update! As to your first config suggestion (`frame`), I think it's well-covered by https://github.com/atom/atom/issues/4599 (if it were added as an enhancement, it would definitely need to be behind a config option). There are a lot of design consequences of frameless windows though - frameless windows have no window management buttons (ie. close, maximize, etc), for instance, so we would have to add native-looking window management buttons for each platform. 

However, even that isn't as straightforward as it sounds, because there are countless Linux distros and desktop shells each with their own visual design, each of which would have to have their own specially-styled window management elements added to this frameless window. In short, it's really not that straightforward. You can take a look at https://discuss.atom.io/t/hide-system-window-title-bar/14578 for more background.

`Transparent` might be more doable – I haven't looked much into that so I'm not sure what design considerations might need to be made.

**Comment by msmaili** [comment]
Excuse my ignorance, but because Atom uses the same framework that Google Chrome is based on, and Chrome has done an excellent job of providing a usable interface without having the top title bar for all different Operating Systems, couldn't Atom use that same design?  Or is the comparison an apples to oranges thing?

**Comment by Tribex** [comment]
@msmall Sorry, that is apples to oranges. :/
Chrome's interface has nothing to do with Atom's. It's just the engine that's the same.

**Comment by dustContributor** [comment]
> frameless windows have no window management buttons (ie. close, maximize, etc), for instance, so we would have to add native-looking window management buttons for each platform.

As I mentioned many times in the links you provided, this isn't the case and its **not** the conclusion you should derive from that discussion. 

The idea is that you don't need to provide "native" anything. All Atom needs to do it is to provide its **own** minimize, maximize and close buttons, just like Chrome does.

You're drowning in a glass of water. Its a problem that has been already solved and the solution works perfectly on one of the most used web browsers in the world right now across the same platforms Atom supports right now.

**Comment by MSmall** [comment]
Please stop including me on this conversation. The OP is msmaili, not msmall

**Comment by mnquintana** [comment]
> The idea is that you don't need to provide "native" anything. All Atom needs to do it is to provide its own minimize, maximize and close buttons, just like Chrome does.

I was just reiterating the design *considerations* (and they are just that, considerations - things to be considered during the design process) – we could certainly go the Chrome route. We would, nonetheless, have to create window management buttons for 3 platforms (Mac, Windows, and Linux), as Chrome does.

**Comment by drtangsoverlinevisit** [comment]
`npm install asar`Just exstract _Atom/resources/app.asar_ and add `frame: false,` then pack.
