### ISSUE TITLE
ATOM Update stuck on 0.211.0

### ISSUE THREAD

**Issue by Stoyvo** [atom/atom#7467]
With the latest release being 1.0, ATOM should see the next version.

Using "Check for Update" from the Help menu, ATOM returns:
No update available. 
Version 0.211.0 is the latest version.

Using Windows 7.

I have closed all instances of ATOM and restarted the machine, no success.

**Comment by Sigmanor** [comment]
try launch with admin permissions

**Comment by Stoyvo** [comment]
@mnquintana  What more information would help with this?

@Sigmanor  Corporate company. Computers are locked down. App updates shouldn't required admin permissions. EG: Google Chrome

**Comment by kubetz** [comment]
Was atom update working for you with older versions?
Are you able to install/update packages from atom?
[Are you behind a proxy](https://discuss.atom.io/t/is-there-any-proxy-settings/710)?

**Comment by Stoyvo** [comment]
@kubetz 
Worked for previous builds. Since 0.196.0.
Packages are updating
No proxy

**Comment by kubetz** [comment]
Is the update check timing out or do you get the info that there is no update pretty qucik?

I would try `atom --safe` and if that not work then renaming `.atom` directory temporarily and running it like that. I am not giving it a high change of working, though.

I found [this comment](https://github.com/atom/atom/issues/5935#issuecomment-86986053) solving (hotfixing) similar problem.

I was updating atom today on my company's notebook on Windows 7 and even behind a proxy and it worked, so it looks like this issue is pretty hard to reproduce :disappointed: .

**Comment by paulcbetts** [comment]
> try launch Atom with admin permissions

Don't do this

>  App updates shouldn't required admin permissions. EG: Google Chrome

They don't!

**Comment by Sigmanor** [comment]
@Stoyvo I know, but last time when i want to update Atom to latest version, nothing happened, just like in your case, and then I decided to run atom with admin permissions, and Atom was successfully updated. But true, apps updates shouldn't required admin permissions, but for some reason Atom was successfully updated after that.

**Comment by jonathandelgado** [comment]
I had this same issue. I had a zombie atom.exe running, once I ended it everything worked as normal with version 1.0.0.

**Comment by avdg** [comment]
Hmm I've tried to let atom update from 0.211.0 to 1.0.0.

Atom keeps updating 0.211.0. Though while checking C:\Users\<user>\AppData\Local\atom I found that the updater already downloaded 1.0.0 on the background.

Any thoughts why the files at C:\Users\<user>\AppData\Local\atom\bin weren't updated as it supposed to be?

**Comment by Stoyvo** [comment]
@jonathandelgado that was exactly the issue. After reading your comment, i closed all instances of Atom that were open, checked Task Manager and still saw 2 Atom processes. After killing these processes and starting Atom again, the version number shows 1.0.0 without updating.

It looks like Atom has a problem with it's shutdown where processes hang or are forgotten about...

A good idea would be to check what version is currently downloaded and give an option to restart Atom (which would kill all Atom processes). 

I hope this information helps.

**Comment by 50Wliu** [comment]
I think I also saw this.  The two relevant processes were `atom.exe --squirrel-obsolete=0.xxx.0` and `atom.exe --squirrel-updated=1.0.0` (these are from memory, so the command-line args might be slightly different).  In my case I actually *couldn't* kill the processes.
The Squirrel log just complains a ton about not being able to delete a bunch of files from the obsolete Atom version because they're in use.

**Comment by benogle** [comment]
This seems like it is no longer an issue
