### ISSUE TITLE
Move cursor when transposing characters

### ISSUE THREAD

**Issue by kgrossjo** [atom/atom#7515]
One subtle but unexpectedly cool feature of Emacs's "transpose" functionality is that it moves the cursor.  As of 1.0.0, Atom doesn't do that.  But it allows me to move a character by using transpose.

If you position the cursor to the right of x and then invoke transpose multiple times, you get the following.  (First line shows the starting point, second line shows after the first transpose, third line after the second transpose, and so on.)

```
aXbcde
abXcde
abcXde
abcdXe
```

Note that the user has just used <kbd>Ctrl-T</kbd>, no other key was pressed.  In Atom, I have to <kbd>Ctrl-T</kbd>, <kbd>right</kbd>, <kbd>Ctrl-T</kbd>, <kbd>right</kbd>, ... to achieve the same effect.

This is related to https://github.com/atom/atom/issues/5410 which also asks to improve the behavior of transpose.

**Comment by EvanBurchard** [comment]
I was going to open a bug on this, but I noticed this related issue. Shouldn't ctrl-t be modeled after readline (the emacs bindings in the terminal)? 

2 reasons for thinking this. First, rather than a specific editor, the terminal is a universal tool/interface. Second, the swap last two characters has a very obvious workflow justification: "I just typed the last two characters incorrectly, and now I can fix it with two keystrokes instead of 4 (delete delete char char)." In this ctrl-t behavior, I guess it's 3 but one of those is an arrow.

On a related note, is there any interest in an option-t for swapping two previous words?
