### ISSUE TITLE
Undo of actions taken by package results in corrupted display of buffer

### ISSUE THREAD

**Issue by iarna** [atom/atom#7516]
I wrote a package: https://atom.io/packages/joe-keybinds (github: https://github.com/iarna/atom-joe) and when I use the move operation it provides (https://github.com/iarna/atom-joe/blob/master/lib/joe.coffee#L56-L67) and then undo it with Cmd-Z, the resulting *display* of the buffer is corrupted. I can tell that the underlying buffer is fine because saving and reloading shows the undo occurred correctly. The display corruption shows duplicated lines where there are none, and things like what constitutes the end of the line no longer match the display.

The move operation uses `transact` to combine of the pieces of the move operation into a single undoable chunk.

**Comment by iarna** [comment]
![example breakage](https://cloud.githubusercontent.com/assets/983798/8398307/183abb54-1db7-11e5-8abd-8c305c343d5b.gif)

Example of what I see ↑

**Comment by lee-dohm** [comment]
## Repro Steps

1. Install `joe-keybinds` package
1. Start Atom
1. Open a file with some text in it (I used my `init.coffee`)
1. Move to a random location
1. Mark the start of a block using <kbd>Ctrl+K B</kbd>
1. Move someplace later on the line
1. Mark the end of a block using <kbd>Ctrl+K K</kbd>
1. Move to the next line
1. Move the block using <kbd>Ctrl+K M</kbd>
1. Undo the action using <kbd>Cmd+Z</kbd>

**Expected:** State of the file to return to where it was before the move
**Actual:** The state of the file itself returns to where it was, but the displayed text includes an extra copy of the line to where the block was moved

**Comment by azoerb** [comment]
I'm not sure if this is the same error, but I've been getting similar weird behavior when using undo/redo in vim-mode.  It seems to scatter lines all over the place, breaking them into seemingly random places.  I can't get the correct state back afterwards.  I'm not sure how to reproduce it consistently though.

**Comment by maxbrunsfeld** [comment]
This is happening because of two things:
* When a `Range` object is passed to `TextEditor::setTextInRange`, that range object is stored in the text-editor's history.
* This package `atom-joe` [reuses](https://github.com/iarna/atom-joe/blob/master/lib/joe.coffee#L61) `Range` objects, mutating their start and end points.

The result is that the text-editor's history gets modified into an inconsistent state. I think that rewriting the `blockMove` method as follows fixes the problem:

```coffee
  blockMove: ->
    return unless editor = atom.workspace.getActiveTextEditor()
    persistentBlock = getBlock(editor)
    moveFrom = persistentBlock.getBufferRange()
    toMove = editor.getTextInBufferRange(moveFrom)
    editor.transact ->
      editor.setTextInBufferRange(moveFrom, '')
      start = editor.getCursorBufferPosition()
      editor.insertText(toMove)
      end = editor.getCursorBufferPosition()
      persistentBlock.setBufferRange([start, end])
```

We should probably be calling `Object.freeze` on these (maybe all) `Range` objects, since they are not intended to be mutated in this way.

/cc @nathansobo should `Ranges` just always be frozen?

**Comment by maxbrunsfeld** [comment]
By the way @iarna thanks for this very detailed report; I'm sorry that you had to deal with this confusing behavior. Please let me know if you're still working on `atom-joe` and notice any other problems with the Atom API.

**Comment by nathansobo** [comment]
@maxbrunsfeld I do think we should freeze ranges and points as much as possible. I'm a bit concerned about the implications of doing it universally, since some packages mutate them for convenience. Starting with freezing stuff that goes into the history seems reasonable, and maybe exploring a way to freeze by default is also a good idea.

**Comment by iarna** [comment]
\o/ Awesome, glad to see this fixed! I'm sure I will continue to do even weirder things w/ my little module, so w/ luck I'll help find some more of the hard to find corner cases. =)
