### ISSUE TITLE
[Feature request]: Windows taskbar/system tray icon.

### ISSUE THREAD

**Issue by Shuudoushi** [atom/atom#7526]
Simple concept, make it so users have the option to minimize to system tray on close and add a system tray icon for reopening Atom.

**Comment by mnquintana** [comment]
Just out of curiosity, why? Atom doesn't run a background service once it's quit, and IMHO it shouldn't.

**Comment by Shuudoushi** [comment]
For me, it's an "ease of use" thing. Too often I'll think I'm through and just close out of the editor and end up having to reopen it, which at this point isn't much of an issue as Atom still opens very quickly, but as more users make more packages and other users install those packages, load times can eventually get insanely long (in a worst case scenario that is).

**Comment by Shuudoushi** [comment]
Oh, and the point of the request is to prevent Atom from quitting, and minimize to the system tray instead, if the option is set.

**Comment by Shuudoushi** [comment]
Oh, and much the same can be done with *nix systems, not too sure if OSX can/does support such things though.

**Comment by Stanzilla** [comment]
The system tray should not be used for apps that don't continue running while in the background, which Atom isn't.

**Comment by CrandellWS** [comment]
Speaking from a point of convenience, it is prefered that it is not running in the background but also desired to be conveniently located for reopening. So because of the agreement with @Stanzilla the `Quick launch` is used instead. 

Though regarding the Quick Launch there was an icon problem after the app updates. Using the File Explore, went to %appdata%/Microsoft/Internet Explorer/Quick Launch/User Pinned/Taskbar then selected the shortcut and changed the the icon from the application based icon to the image icon located in the parent folder. This is is good enough to satisfy my desire of convenience, it is has quickly become one of the primary programs used by me, so it seems like it is always there anyway.

**Comment by kit92** [comment]
I'm pretty sure this is the same issue, but I personally hate a cluttered desktop and I keep all my most frequent programs pinned to my task bar. Atom does not stay pinned after closing. There is no need for it to still be running, I just prefer it to be close to my other pinned icons and to obey the Windows command 'pin this program to the taskbar'

**Comment by damieng** [comment]
There were some problems with pinning and upgrades that have now been resolved. The recommendation here is to pin it to the task bar - we have no plans to allow it to continue running as a system tray icon.

**Comment by DavidHazeldenUK** [comment]
Notepad++, PSPAD both have the option to minimize to system tray on close. Bump.

**Comment by neochief** [comment]
There's a huge benefit in this in terms of opening speed. Instead of waiting 1-2 seconds each time for a fresh atom instance, it may reuse existing process for opening files. If it sounds crazy, take a look at Chrome  - it does just that with its background process.
