### ISSUE TITLE
Keymap with or without dot notation?

### ISSUE THREAD

**Issue by renestalder** [atom/atom#7538]
I'm not sure but I guess since Atom 1.0 the keymap seems to use classes without dots.

Here is the example from the keymap.cson:

```
# Here's an example taken from Atom's built-in keymap:
#
# '.atom-text-editor':
#   'enter': 'editor:newline'
#
# 'body':
#   'ctrl-P': 'core:move-up'
#   'ctrl-p': 'core:move-down'
```

So according to this, I would make a override of any keymapping like this, **which isn't working**

```
'.atom-workspace .atom-text-editor:not([mini])':
  'cmd-k cmd-d': 'editor:fold-all'
```

To make it work, I remove the dots from the classes
```
'atom-workspace atom-text-editor:not([mini])':
  'cmd-k cmd-d': 'editor:fold-all'
```

So it looks like the examples provided in the file comments are outdated or this is a bug, I don't know.

**Comment by mnquintana** [comment]
This is because they aren't classes – they're custom elements, hence no dot. [The examples are up-to-date](https://github.com/atom/atom/blob/master/dot-atom/keymap.cson#L12-L17) – if you had examples with a dot then it was from an old version of Atom (because Atom doesn't overwrite your `keymap.cson` or anything else in your config folder).

**Comment by renestalder** [comment]
Thanks for clarifying.
