### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by k4li** [atom/atom#7561]
Hello,

I followed your instructions on how to build on linux but they aren't working for me. 
If I run command 'atom' i get this error:
<code>nohup: failed to run command `/tmp/atom-build/Atom/atom': No such file or directory</code>

Help

**Comment by thedaniel** [comment]
Atom does not currently support ARM (the processor architecture of the Raspberry Pi). cf. https://github.com/atom/atom/issues/3783#issuecomment-113620012

**Comment by k4li** [comment]
I was buildin from source so I thil it should work ??

**Comment by jlord** [comment]
@k4li Atom doesn't work with the latest versions of Electron and the versions of Electron that support ARM are the latest, so while you can successfully build Atom on ARM, it's not actually useable, likely due to the Atom-Electron (latest) compatibility. 

You can play with Electron on it's own though since it does now work on ARM :sparkles:
