### ISSUE TITLE
File timestamp changes on every save

### ISSUE THREAD

**Issue by ttsirkia** [atom/atom#7588]
At least in Windows, it seems that the timestamp changes on every save although the file is not modified. This is kind of a problem when there are multiple files open and you save all the files.

**Comment by 50Wliu** [comment]
Refs #2871.

**Comment by lee-dohm** [comment]
Since #2871 has been closed, this should no longer be an issue. Please let us know if that is not the case.

**Comment by ttsirkia** [comment]
At least with my setup (Atom 1.1.0) this bug is still occurring and therefore this ticket should not be closed.

**Comment by ttsirkia** [comment]
Of course it is possible that #9249 is not part of this update.

**Comment by lee-dohm** [comment]
According to the commit in the merged PR, the fix first appeared in `v1.2.0-beta0`:

<img width="744" alt="napkin 12-05-15 10 37 09 am" src="https://cloud.githubusercontent.com/assets/1038121/11609473/24792a7e-9b3c-11e5-90eb-d3cc19db9562.png">

and has been in stable versions since `v1.2.0`. You should consider updating to the latest stable version.

**Comment by ttsirkia** [comment]
Hmm, strange. My 1.1.0 states that there is no newer version available. I'll try this with a newer version.

**Comment by ttsirkia** [comment]
OK, I have 1.2.4 in my other computer and there this bug is fixed. Sorry about the confusion.

**Comment by lee-dohm** [comment]
No problem :grinning: We have a bug open on the release notes thing already, sorry about the confusion there :blush:
