### ISSUE TITLE
Atom modify a lot of lines when I make some changes in my files

### ISSUE THREAD

**Issue by alvaro893** [atom/atom#7617]
When I do a "git diff" I can see these modified lines, the final result is that the file keeps just the changes I did, but it is very awful when you want to see what changes you did, and especially when you working with a team and others want to see what you have changed in the file.

As an example, this is the output of "git diff" when I do a simple change.

NOTE: I only changed the last line, however all of that "-+" couples appears. Not sure what's happening... :confused: 

```
        .fc-day,
-       .fc-widget-content
+       .fc-widget-content
        {
                background : #FFF !important;
        }
-
+
    .fc-day-header{
        background-color: #e86484 !important;
    }
@@ -72,7 +72,7 @@

 <div class="continer-fluid">
    <div class="row page-margin">
-       <!--
+       <!--
        <?php
               $path = "activity/";
                             $path_to_image = $path.$image;
@@ -142,9 +142,9 @@

       </div>
    </div>
-
+
@@ -177,7 +177,6 @@
        //]]>

 </script>
-<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js">
```

**Comment by thomasjo** [comment]
This is by design; the `whitespace` package strips trailing whitespace when a file is saved. It can be configured however:
![settings_-__users_thomasjo_-_atom_and_atom_modify_a_lot_of_lines_when_i_make_some_changes_in_my_files_ _issue__7617_ _atom_atom](https://cloud.githubusercontent.com/assets/3622/8450338/52647d2c-1fda-11e5-82f9-10d3e5c4eb81.png)

You might want to subscribe to https://github.com/atom/whitespace/issues/8.

**Comment by alvaro893** [comment]
you rock! thanks!

**Comment by Markieta** [comment]
:+1:

**Comment by garypaduana** [comment]
Should this be on by default?  It's really unexpected behavior.

**Comment by alfrrr** [comment]
@garypaduana It is not unexpected behavior. For instance Visual Studio 2013 comes with the feature that it automatically format the code you are writing, turned on by default. Is it unexpected behavior? No. It is annoying? Yes. Can I turn it off? Of course.

I do like the 'whitespace' package as it keep my code clean and POSIX compliant when writing C code. If you don't, just disable it or configure it like everyone else. Atom is extremely configurable (unlike other editors) and so are the packages.

**Comment by granthusbands** [comment]
It is clearly unexpected behaviour. You have hundreds of users complaining that Atom is silently corrupting their files and causing version control issues, and somehow this feature persists. This needs a big warning or needs to be off by default. Citing Visual Studio is disingenuous, given that all files handled by that are expected to be edited only in that. Atom should play well with others, not enforce an arbitrary extra standard on the files it touches.

**Comment by pixilz** [comment]
@granthusbands if it is unexpected and not intuitive enough to turn off it could always be added as a section in the welcome guide with a list of core packages that may or may not provide expected behavior. 

Other than that there really isn't a great solution. Disabling it can cause issues with new users having badly formatted files or within teams that are using Atom; and leaving it enabled obviously causes some unexpected behaviors for others.

**Comment by granthusbands** [comment]
An entry in the welcome guide or an early empty-pane tip, or both, would certainly help. That config items for plugins are non-trivial to even notice is something that might want fixing more generally - maybe those config items could specify where they want to be inserted into the standard settings tree?

Backwards compatibility can be important, yes. But, as someone who has been burned by this, I still maintain that Atom silently altering code I've not even seen (in files I've edited) is bad behavior. I guess I can just hope that someone finds time to work on #8
