### ISSUE TITLE
Invalid packages settings because of config.cson

### ISSUE THREAD

**Issue by ricardofbarros** [atom/atom#7637]
For example,
I install the package `xpto` and this package has two settings declared on init.coffee `foo` and `bar`. And then I decide to change the value of `foo`. So my preference will be stored on config.cson. But after a while the package developer decides to deprecate the setting `foo` and removes the setting `foo` from package settings. Now when I go to the settings page of `xpto` package I will still see the `foo` setting because it is still stored on config.cson. 

Shouldn't Atom at boot check if there is any dead/invalid settings from packages?

**Comment by gandm** [comment]
Just ensure that it doesn't delete values without informing me what the value of it was. My package has a deprecate function that reads previous config value and sets a new one before unsetting the old one. I use this when I have changed the key name of a config element . See https://github.com/gandm/language-babel/blob/master/lib/transpiler.coffee#L82

**Comment by code-tree** [comment]
I also find this very confusing. Perhaps the old setting can remain in config for the reason gandm states, however, surely it should not be displayed to the user. For example, in the linter package, I no longer know which setting will actually do anything, as quite a few have changed since I first installed.

**Comment by lee-dohm** [comment]
Leaving settings in that weren't defined explicitly in the config schema was an intentional choice. First, for compatibility with packages that were built before the config schema was designed. Second, because the config schema doesn't solve all config problems. Some packages want to have user-editable configuration items that are determined dynamically by other factors than a hard-coded schema.

Upgrading configuration settings from old systems to new ones is something that package developers should keep in mind as part of their strategy for migrating from one version to the next. It sounds like @gandm has a good system.
