### ISSUE TITLE
Bundled Node/IO.js inconsistencies on Windows 8.1 and 10

### ISSUE THREAD

**Issue by Cirex** [atom/atom#7687]
I'm trying access registry values in Windows that differ in location with each versions of Windows.
Example: https://github.com/Cirex/atom-metro-ui/commit/cfc0ec218a807c7d1e820862940b9c03c121535e

The preferred way to detect the current operating system version seems to be the use of `os.release`, but it's return value differs greatly when used from inside of Atom/Electron.

Locally installed IO.js:

```
> process.version
'v1.5.1'
> os.release()
'6.3.9600'
```

The same command run from the Atom developer console:

```
> process.version
'v1.5.1'
> os.release()
'6.2.9200'
```

My Windows release (8.1) as reported by running `ver` and `winver`:

```
Microsoft Windows [Version 6.3.9600]
```

This bug seems to be related to the embedded manifest file `node.exe.extra.manifest` in Node, and `os.release` use of `GetVersionEx` on Windows.

Can this please be fixed or do I need to use another way of determining the current version of Windows?

**Comment by paulcbetts** [comment]
This should be fixed in Electron, but Windows OS has decided that they never want to return the real OS version, only the version you _think_ it is via your manifest. The hack way to determine this is to check the File version of some DLL in System32 (kernel32.dll is a good candidate).

However in your case, it seems like you could just try the Win10 Regkey location, oops it doesn't exist, check Win8, oops it doesn't exist, we're on Win7

**Comment by Cirex** [comment]
Finding the version else where was never really the problem. I could always parse `ver` or pull the build directly from the registry. I was more concerned with what seemed to be breakage from the official Node API.

I was largely just trying to avoid having to spawn additional processes and slow the boot down even further just to pull in the accent color

**Comment by damieng** [comment]
There are no plans to expose the OS version number directly from within Atom - I'd go with the registry fallback Paul suggested.
