### ISSUE TITLE
'atom is not defined' is thrown when opening an 'atom://' URL

### ISSUE THREAD

**Issue by amirlivneh** [atom/atom#7773]
Whenever I try to open an 'atom://' URL, I get this exception in the console:

```
ReferenceError: atom is not defined
    at Function.module.exports.Package.isBundledPackagePath (/Users/alivneh/atom/src/package.coffee:31:11)
    at Function.module.exports.Package.loadMetadata (/Users/alivneh/atom/src/package.coffee:61:16)
    at PackageManager.module.exports.PackageManager.getAvailablePackageMetadata (/Users/alivneh/atom/src/package-manager.coffee:252:128)
    at AtomApplication.module.exports.AtomApplication.openUrl (/Users/alivneh/atom/src/browser/atom-application.coffee:769:35)
    at EventEmitter.<anonymous> (/Users/alivneh/atom/src/browser/atom-application.coffee:406:24)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
'
```

Apparently atom is not defined in https://github.com/atom/atom/blob/5dee3ce5950d972d3f275ad1a93d62f542d42aeb/src/package.coffee#L22. Interestingly, atomApplication is defined and contains the properties needed by isBundledPackagePath().
Simply adding `atom = global.atom || global.atomApplication` at the beginning of isBundledPackagePath() fixes this, but there may be an underlying issue that needs to be addressed here.

**Comment by thomasjo** [comment]
Can you provide some more details on exactly what you're doing to provoke this exception? Code that reproduces the problem would be great. In addition, what version of Atom are you running, and are you able to reproduce in safe mode?

**Comment by amirlivneh** [comment]
No code is needed to reproduce the issue. The easiest way to reproduce it:
- Install atom on OS X
- In your browser, type atom://foo
- In the OS X console, instead of the expected 'Opening unknown url: atom://foo', you'll get 'ReferenceError: atom is not defined'

Of course, the real world use case is when a package such as https://github.com/tclem/open-in-atom, that actually subscribes for URL events, is installed. But you can reproduce the issue without it.

It reproduces on both v1.0.0 and on master, and also in safe mode.

Adding ```atom = global.atom || global.atomApplication``` at the beginning of isBundledPackagePath() fixes it, because global.atomApplication is defined at the problematic point.

**Comment by thomasjo** [comment]
@amirlivneh Thanks for providing those crucial details.

@atom/feedback Does Atom truly support being launched via a URL handler? @zcbenz added `CFBundleURLSchemes` to `Info.plist` back in December 2013 (https://github.com/atom/atom/commit/753b11cf15b7302efd5cd8884f107478f53f48d6), but it doesn't seem like Atom is getting bootstrapped properly when launched this way.

I guess this worked at some point, but has since been broken. It's also worth noting that this functionality does not work in Chrome. I haven't tested Firefox, but I'm reasonably sure this only works in apps that are "properly" integrated with OS X.

**Comment by izuzak** [comment]
@thomasjo https://github.com/atom/atom/issues/2037 sounds a bit similar.

**Comment by thomasjo** [comment]
@izuzak They are related. Also related to https://github.com/atom/atom/issues/5262. But this issue is about an actual bug though. If we don't want to handle `atom://` schemes (yet), we need to :fire: the `CFBundleURLSchemes` from `Info.plist`, but hopefully one of the core devs who have touched the relevant code can find a fix for the problem.

**Comment by amirlivneh** [comment]
Handling atom:// is useful and as I mentioned above, using a small workaround I was able to verify that this feature works correctly other than the issue of initializing global.atom, so I encourage you not to remove it.
