### ISSUE TITLE
Follow symlinks in projects

### ISSUE THREAD

**Issue by febLey** [atom/atom#7782]
There's a unexpected behaviour with folders that are symlinked into the project folder.

The editor does provide the full path to the file instead of following the symlinks.
This will cause issues with the linter plugin.

Here's an example:
I've got a project which contains three symlinks to other folders with my code, some files like the coffeelint.json are static files in the project.

![screen shot 2015-07-08 at 09 18 51](https://cloud.githubusercontent.com/assets/1727958/8565071/6108cd7e-2552-11e5-9de0-9c3fafb7e17f.png)

The provided path of the main.coffee looks like this:

```
/Volumes/faxe/local/henne/fileadmin/templates/page/scripts/main.coffee
```

But it should look like this

```
/Volumes/faxe/projects/henne/page/scripts/main.coffee
```

Because of this the linter plugin won't work as expected, see here: https://github.com/AtomLinter/linter-coffeelint/issues/43

**Comment by lee-dohm** [comment]
Shouldn't both paths be valid? That's the point of symlinks ... that you can access a file from a different path.

**Comment by febLey** [comment]
But the linter is looking for the coffeelint.json, the path of it is in this case
```
/Volumes/faxe/projects/henne/coffeeelint.json
````
So the linter is just looking for files in the path:
```
/Volumes/faxe/projects/henne/**/*.coffee
```
But the symlink provides the real path of the file:
```
/Volumes/faxe/local/henne/**/*.coffee
```
So the linter isn't using coffeelint.json and uses the default settings.

**Comment by gandm** [comment]
Yeah I have real problems with symlinks in [my package](https://atom.io/packages/language-babel). I also need to traverse the directory starting at a source files that's been saved and working up to the project holding it. If symlinks are involved it's anyones guess what may happen. The project path returned by code like
````
    projectContainingSource = atom.project.relativizePath sourceFile
    absProjectPath = path.normalize(projectContainingSource[0])
````
Is often incorrect!

On ubuntu atom seems to work fine. e.g. Under `/home/graham/Javascript` is soft symlinked to `/home/graham/Javascript2`
![image](https://cloud.githubusercontent.com/assets/2313237/9939145/ab329eb6-5d60-11e5-8982-e7d991084f4f.png)
![image](https://cloud.githubusercontent.com/assets/2313237/9939159/be602d14-5d60-11e5-8fd1-e2136b128729.png)

On windows `c:\AtomFolder1\AtomFolder2-1` is soft symlinked to `c:\AtomFolder2\AtomFolder2-1`
![image](https://cloud.githubusercontent.com/assets/2313237/9939523/9bdf90ac-5d62-11e5-9b0f-4831c6413d1d.png)
![image](https://cloud.githubusercontent.com/assets/2313237/9939536/af68ce90-5d62-11e5-8260-f107019ccc1e.png)

On OSX it seems to vary!

**Comment by gandm** [comment]
Actually I was woking about Ubuntu. I was looking at the non-symlinked js file. The symlink one just stack dumps when using the following on a file in a symlink path.

![image](https://cloud.githubusercontent.com/assets/2313237/9941778/6a6ee934-5d6f-11e5-969b-c53ebdcc7910.png)


![image](https://cloud.githubusercontent.com/assets/2313237/9941695/f02fc59e-5d6e-11e5-9952-ded87fd4d420.png)

![image](https://cloud.githubusercontent.com/assets/2313237/9941713/0a9798d0-5d6f-11e5-8182-843ee9ac55d7.png)

**Comment by codrcodz** [comment]
I am having the same issue using Atom with Homebrew, (a common macOS package manager).  Homebrew keeps all it's packages inside of different directories using the following schema: 

`/usr/local/Cellar/package_name/package_version/bin/binary_name`

It then symlinks each binary so that they are accessible from here:

`/usr/local/bin`

This allows Homebrew to work without adding multiple directories to the `$PATH`; however, it seems to break the `build-python` Atom plugin I am using.  The plugin tries to find my `python3` and `python` binaries in order to compile some python source code, but since it can not traverse the symlink, it ends up just throwing an error and failing.  

My hacky work around is to add a direct link to the `python` and  `python3` binary via the Atom init script in order to prepend both directories to the path, but this breaks every time homebrew updates my python binaries, since the version number is hard-coded into the directory tree. :-(
