### ISSUE TITLE
Scrolling Markdown source code should also scroll preview

### ISSUE THREAD

**Issue by scls19fr** [atom/atom#7891]
Hello,

I'm new to Atom. It's a great app.
But I'm looking for a feature to edit Markdown.

Scrolling Markdown source code should also scroll preview
(and also inverse)

At least 2 modes should exists:

 - follow top
 - follow bottom

Kind regards

**Comment by mnquintana** [comment]
Thanks for the suggestion! This is a duplicate of https://github.com/atom/markdown-preview/issues/24 – please subscribe there for updates.

(Also, for future reference, the Markdown previewing functionality is provided by a separate repo, [atom/markdown-preview](https://github.com/atom/markdown-preview), rather than atom/atom.)

**Comment by scls19fr** [comment]
Sorry thanks

**Comment by mark-hahn** [comment]
I have a package called `markdown-scroll-sync`.

**Comment by scls19fr** [comment]
Thanks.
