### ISSUE TITLE
Showing line numbers disables sub-pixel AA on tabs, status-bar etc.

### ISSUE THREAD

**Issue by simurai** [atom/atom#7904]
In https://github.com/atom/one-dark-ui/issues/82, @wiox noticed that sub-pixel anti aliasing is not only disabled for the tabs, but also on the fuzzy finder and the status bar.

![sub-pixel](https://cloud.githubusercontent.com/assets/378023/8694250/9299865a-2b18-11e5-8f8d-936466ccedf6.png)

It seems it's caused by the line number tiles getting promoted to a GPU layer and probably related to #7101. Kinda strange that it affects different areas.

Something that might be worth looking into is using `will-change`. It also adds a GPU layer for the line numbers, but doesn't affect the rest. Notice the orange "composited layer borders" only appear in the status bar with `-webkit-transform: translate3d(0px, 0px, 0px);` but not with `will-change: transform;`.

![tiles](https://cloud.githubusercontent.com/assets/378023/8694309/0dae2350-2b19-11e5-8506-7201ba42ae5e.gif)

Now, I *heard* that `will-change` should only be used when interacting, like on hover or so.. and not kept permanently enabled. So not sure if that would help. /cc @as-cii @nathansobo 

__Edit:__ Sorry, I just realized that the `transform` is needed to actually move line numbers. So can't be replaced. :grin:

**Comment by as-cii** [comment]
Hey @simurai, thanks for the thorough report and explanations.

I traveled back in time to 7e9e8e03a39e8fde0d5e194b498585464a3a0c4d (namely, the commit before merging #7101) and I found out subpixel anti-aliasing was still not working as of that version and therefore I think we can exclude tiling as the cause of this issue.

Apparently the layer is being created because of two reasons:

![screen shot 2015-07-15 at 15 44 15](https://cloud.githubusercontent.com/assets/482957/8699874/e0de1778-2b08-11e5-91eb-e2cebffddf41.png)
![screen shot 2015-07-15 at 15 43 55](https://cloud.githubusercontent.com/assets/482957/8699875/e1113860-2b08-11e5-9a96-2c925a176675.png)

I think the elements that “may overlap”  are the tiles’ layer (or the whole `line-numbers`’s layer before #7101), but I am not sure what exactly should be squashed and why. Setting `overflow: hidden` or reducing the `height` of `line-numbers` doesn’t seem to improve the situation.

@simurai: would it be possible to simply give the status bar div a background color? That could enable us to get subpixel anti-aliasing back and hopefully stop worrying about the underlying layers creation. Nevertheless, I’d agree it may be interesting to understand why Chrome is automatically generating those layers.

**Comment by simurai** [comment]
>  would it be possible to simply give the status bar div a background color?

Yeah, that might work.

I randomly tried some stuff and adding `z-index: 0;` to the gutter seems to fix it.

```css
atom-text-editor::shadow .gutter {
  z-index: 0;
}
```

![tiles](https://cloud.githubusercontent.com/assets/378023/8700714/7bbbe614-2b48-11e5-834b-c4f72630c089.gif)

**Comment by as-cii** [comment]
> I randomly tried some stuff and adding `z-index: 0;` to the gutter seems to fix it.

I think we can use it then, but let’s make sure to document it so that it’s 100% clear why we’re setting it. Not sure if we should still set the `background-color` property: on one hand it seems like it could let us forget about this layering problems in the future, but on the other hand it feels like a workaround that shouldn’t be needed at all (given that we don’t want the status-bar to have its own layer).

@simurai: thoughts? :thought_balloon: If setting the `background-color` property is super straightforward I would probably add it as well.

**Comment by batjko** [comment]
Sorry to bud in, but would the explicit setting of the background color potentially interfere with future changes to the status-bar?

I'm thinking of open requests like extending the status-bar to the whole workspace, rather than just within editors and who knows what people want to do with it.

**Comment by simurai** [comment]
Ok, adding `background-color` to the status bar seems to work, but only when also creating a layer at the same time:

```
.status-bar {
  background-color: #333;
  transform: translateZ(0);
}
```

Future changes should still be ok, but not sure if that's bad for performance because on every key stroke it has to repaint the line/column count and push another layer? Also, the same would need to be done for the tabs and maybe other places.

Doing the `z-index: 0;` seems cleaner, no? It's strange, because the gutter already has an `overflow: hidden`, so there shouldn't be any overlapping. But somehow Chrome is extra cautious. And just by creating another stacking context Chrome feels save?

Anyways.. It's not super urgent and we can first test some more.
