### ISSUE TITLE
EACCES: permission denied, symlink '/Applications/Atom.app/Contents/Resources/app/atom.sh'

### ISSUE THREAD

**Issue by budda** [atom/atom#7956]
Noticed in the console when starting Atom 1.0.2 (OSX) there's a couple of EACCESS warnings

```
EACCES: permission denied, symlink '/Applications/Atom.app/Contents/Resources/app/atom.sh' -> '/usr/local/bin/atom'
EACCES: permission denied, symlink '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm' -> '/usr/local/bin/apm'
```

**Comment by izuzak** [comment]
I think this is Atom trying to set up the `atom` and `apm` commands so that you can use them in the terminal. I guess these warnings are a bit confusing and don't really tell you what's going on.

@kevinsawicki @maxbrunsfeld do you think there's something to improve here? I see those warnings myself in the devtools, perhaps because the symlinks already exist?

**Comment by mprinc** [comment]
At least you can fix it manually:

sudo ln -s '/Applications/Atom.app/Contents/Resources/app/atom.sh' '/usr/local/bin/atom'
sudo ln -s '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm' '/usr/local/bin/apm'

**Comment by tonmoyl** [comment]
How does a person "sudo"? Sorry, new user here and am trying to learn the basics.
