### ISSUE TITLE
Atom.io fails to run on redhat6.6

### ISSUE THREAD

**Issue by lambada** [atom/atom#7988]
$ uname -a
Linux MyMachine 2.6.32-504.23.4.el6.x86_64 #1 SMP Fri May 29 10:16:43 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 6.6 (Santiago)

When attempting to install and run the prebuilt binary
$ sudo yum localinstall atom.x86_64.rpm 
Reports that it will install 1.0.2-0.1.fc21 and Completes OK, but running gives the following error
$ atom
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/libchromiumcontent.so)
/usr/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/libchromiumcontent.so)
/usr/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/libgcrypt.so.11)
/usr/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /usr/share/atom/libgcrypt.so.11)

I'm going to guess that this is due to redhat6 being relatively old, but it's still fully supported by redhat.

**Comment by maxbrunsfeld** [comment]
Are you able to install newer versions of `glibc` and `libstdc++` on your system? Maybe we should list these library versions in the [requirements](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#requirements) section of our build instructions.

**Comment by ardeshirj** [comment]
Same issue here #5172.

I believe we are building rpm package via Fedora 21 docker image, which has the newer version of ```glibc```, and that is causing the issue here. 

Changing the docker image that builds the rpm package can be helpful in this case. We can change it to CentOS/Redhat image, where the version would be the oldest supported version (version 5 or 6)

I will try and test it to see if this still works for newest version of Fedora and make a PR for it.

CC: @kevinsawicki

**Comment by lambada** [comment]
@maxbrunsfeld I have the newest versions available in my repos according to yum. I'm unsure whether upgrading them would break other things, given it's redhat.

@ardeshirj That would be great, hope to see progress soon.

**Comment by a-schneider** [comment]
I am having the same problem. Has anybody found a solution yet?

**Comment by 1dot75cm** [comment]
build test. I want it to succeed.
https://copr.fedoraproject.org/coprs/mosquito/atom/build/132787/

**Comment by willowsmyth** [comment]
@ardeshirj 
I have the issue with GLIBC as well. Building a docker package will probably not solve this issue, because if GLIBC_2.14 is not on the system, then chances are that the system is not new enough to support the Docker container.  We are not (and cannot according to sysAd) run newer linux.  So maybe the proper thing would be to build the rpm with the GLIBC_2.14?

**Comment by wolverine2k** [comment]
+1 same issue with `GLIBCXX_3.4.21' not found. Any solutions?

**Comment by zielot** [comment]
+1 same issue. 
On CentOs release 6.7 the latest version of glib available is 2.12

**Comment by Rat-S** [comment]
This issue is occurs in RHEL 6.7 too.

**Comment by 50Wliu** [comment]
Closing in favor of #5172 - feel free to subscribe there for updates.

**Comment by biskandar** [comment]
I'm using centos 6 , same problem here .

[user@lenovo-t61 ~]$ cat /etc/*release*
CentOS release 6.8 (Final)
[user@lenovo-t61 ~]$ uname -a
Linux lenovo-t61 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[user@lenovo-t61 ~]$ yum list installed libstdc++ glibc
Installed Packages
glibc.i686                                                   2.12-1.192.el6                                             @base
glibc.x86_64                                                 2.12-1.192.el6                                             @base
libstdc++.i686                                               4.4.7-17.el6                                               @base
libstdc++.x86_64                                             4.4.7-17.el6                                               @base
[user@lenovo-t61 ~]$ atom
[user@lenovo-t61 ~]$ /usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/libnode.so)

**Comment by dm-blue** [comment]
A solution for me (and it still works since two years ago) was  to download glibc-2.14.1-6.x86_64.rpm
from <fedora 15> repository and unpack from /lib64 package folder the ld-2.14.1.so, libc-2.14.1.so, libdl-2.14.1.so library files (also their symnlinks) and copy them in the <atom-install-path>/share/atom folder (I'm using /opt/atom, if that matter). The same thing with libstdc++.so.6.0.16 from libstdc++-4.6.0.fc15.x86_64.rpm from the same repository.
With this solution, atom worked fine until 1.16.x.
