### ISSUE TITLE
Dynamic Grammar

### ISSUE THREAD

**Issue by archaeron** [atom/atom#7989]
Is there a way of of defining a dynamic grammar in atom?
If there is, this ticket is about improving the documentation.
if not it's about implementing a way of doing a dynamic grammar.

### What I mean by dynamic grammar

The clearest explanation I found is this screenshot in Scala:

<img width="155" alt="screen shot 2015-07-20 at 18 12 08" src="https://cloud.githubusercontent.com/assets/471043/8780779/85808fe4-2f0b-11e5-85f2-8b015c19f71f.png">

where `val` instantiates an immutable variable that is blue
and `var` a mutable one that is red.
This is not possible just through regular expressions.

**Comment by maxbrunsfeld** [comment]
I agree that this would be *very* cool. Unfortunately, it is not currently possible. At some point in the next year, we may put some work into making our grammar system more powerful. If and when we do this, we'll definitely blog about it, and you should bring up your desired features so we can talk about it in more detail. I'm going to close this out for now, assuming we'll have to continue this discussion much later, but let me know if you'd like me to reopen it.

**Comment by david-christiansen** [comment]
Is it possible to turn off the grammar system and manually highlight regions of a buffer? This is used to great effect in `idris-mode` for Emacs, where the compiler tells the editor precisely how to color source text by stating "make this subregion look like this, and this other one look like this". If I'm not mistaken, doing this is @archaeron's goal for the Atom mode for Idris.

**Comment by maxbrunsfeld** [comment]
@david-christiansen Good question. We don't support this ability right now. But as you know, the vast majority of our codebase (like emacs's) is written in a dynamic language, so you always have the option of hacking *deeply* into our `TextEditor` class for experimentation and prototyping. That said, we probably won't be able to give you too much guidance at this time, because we are focused on some other efforts (many of them performance-related).

**Comment by mark-hahn** [comment]
> This is not possible just through regular expressions.

You could at least highlight the declaration differently.  `val a` and `var
a` are different.

**Comment by archaeron** [comment]
@maxbrunsfeld too bad, this would have been really great.
If I understood this correctly: https://github.com/TypeStrong/atom-typescript/blob/d9e14dc4cf7daafb72897b471d754c2927706480/docs/grammar.md#dynamic-grammar someone tried to dig into the source and do it and gave up.

@mark-hahn this would work in this example even if it would not help too much as one would want to know later in the program is a variable is mutable or not. Plus my usecase is a bit more complicated thant this example.

**Comment by david-christiansen** [comment]
@maxbrunsfeld Emacs does provide an API for painting arbitrary regions of the buffer with arbitrary properties, though - there's no horrid `defadvice` or monkey-patching necessary in order to do these things. One can simply say "in line 4 columns 13-17, add this color, this tooltip, this mouse-over behavior, and this right-click menu". Thanks for the reply, though!
