### ISSUE TITLE
Atom does not render underscore characters (_) every few lines

### ISSUE THREAD

**Issue by rbu** [atom/atom#8026]
This is Atom 1.0.2 on Linux.

I am not seeing Underscore characters rendered every few lines, which is making the editor dangerous to work with in programming, as I cannot determine the difference between ```foo_bar``` and ```foo bar```.
![underscore_missing](https://cloud.githubusercontent.com/assets/65913/8825843/44fd6280-3082-11e5-857d-4897af03030c.png)

This screen shot is taken with Font size 15. The line height is set to 1.1. This happens every 12 lines, but not reliably.

It does not happen with font size 14, but also happens with 16 and above. See this video that shows the effect:
![atom_underscore](https://cloud.githubusercontent.com/assets/65913/8825897/9b2e950c-3082-11e5-8121-8234ff39f361.gif)

**Comment by batjko** [comment]
Could be a scaling issue.
Do you use a HiDPI screen by any chance?

**Comment by rbu** [comment]
96 DPI, standard screen (unfortunately!)

```
$ xrdb -query | grep dpi
Xft.dpi:	96
$ xdpyinfo | grep dots
  resolution:    96x96 dots per inch
```

**Comment by batjko** [comment]
I can't replicate this (at least on Windows, haven't tried Linux yet).
Using both One Dark themes, and Source Code Pro font:
![image](https://cloud.githubusercontent.com/assets/7287076/8826614/b6b3ea0a-307f-11e5-8016-baedfc8f1b76.png)


What Themes and font are you using?

**Comment by MichaelAquilina** [comment]
I cant reproduce this on Linux either (atom 1.0.2)

**Comment by batjko** [comment]
Another question, if it's not the font or themes: Are you running Atom a VM by any chance?

**Comment by mnquintana** [comment]
What font is this? Can you reproduce this in another font? What syntax theme are you using?

**Comment by abe33** [comment]
Hmm, the fact it every 12 lines seems indicates that it has to do with the editor tiles and the line height (AFAIK tiles contains 12 lines, so if the one below is opaque and overlap the one above by 1px it could hide the underscores), try disabling the tile's background color in the devtools, you should see the underscore appear, for a better fix I think increasing a bit the line height should do the trick.

**Comment by rbu** [comment]
Thank you for all the responses and questions so far, I'll try answering all of them:
* It's not a VM, this is my development machine
* It's Fedora 21 / x86_64
* I am using Atom Dark with the Monokai theme. The problem happens with other (default, non-community) themes as well
* The example uses no syntax highlighting / plain text mode
* According to the inspector, the used font is "DejaVu Sans Mono" which is my system's default monotype font (unconfigured)
* Increasing the line height from 1.1 to 1.15 fixes the problem.
* Changing the font from "DejaVu Sans Mono" to another monospace font (Inconsolata, Source Code Pro, Fira) fixes the problem
* I can confirm that the inspector shows the error happens at tile boundaries and that removing the background attribute at the following tile (i.e. line 13) shows of the characters on the previous line (i.e. line 12)

**Comment by benogle** [comment]
cc @nathansobo @as-cii @maxbrunsfeld

**Comment by as-cii** [comment]
The issue is indeed caused by two overlapping tiles. Because of subpixel anti-aliasing, we must assign a background color to all the tiles but, if they overlap as in this case, the resulting effect is quite ugly.

What’s interesting here is that the line height is set to a value that’s greater than `1`. In relative terms this should mean that two lines will never touch each other, and the same goes for tiles.

@nathansobo: do you think it would be possible that our lineHeight sampling is reporting a wrong value? Right now we are relying on a dummy line node which takes into account only the `x` character. It would probably be interesting to check whether it works for this particular case if we add `_` to the dummy span. The font could probably put underscores in a lower position than the *default* characters, thereby returning an incorrect result.

**Comment by nathansobo** [comment]
> It would probably be interesting to check whether it works for this particular case if we add _ to the dummy span. The font could probably put underscores in a lower position than the default characters, thereby returning an incorrect result.

@as-cii That's interesting and seems worth investigating. The fundamental question is whether Chrome ever renders pixels *below* the line height. Seems like it doesn't happen with descenders such as the bottom of a `g`, but maybe underscores are even lower? If this is the case, I worry a bit about tiling. We can always separate the lines enough to include `_`, but this might end up being a bit taller than the official line height.

**Comment by abe33** [comment]
Maybe it's stupid of me but can't you play with z-index to display the tiles with a reverse order? The tiles on top would then have a bigger z-index than the one below.

**Comment by as-cii** [comment]
> Maybe it's stupid of me but can't you play with z-index to display the tiles with a reverse order? The tiles on top would then have a bigger z-index than the one below.

It’s not stupid, but an ideal solution should take into account a scenario where, analogously, we have a character which is higher than the average glyph.

Tiling has proven to be an interesting technique but I agree with @nathansobo it could have certain drawbacks that make it cumbersome to work with.

**Comment by rbu** [comment]
Is it necessary for tiles to have a background instead of being transparent with the containing div providing a background? That would allow you to let each tile overflow, similar to how you allow a line  to to overflow to the next and previous line within a line.

There's all sorts of interesting things in Unicode - consider, for example the "x̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩̩". This "character" renders a very long line of combining vertical low lines below an x. While its rendering is completely broken in Atom (and most other editors, for that matter), it should show that there's technically an unbounded line height (or, depth?) that should be considered.

I am attaching a screen shot of the preview in case the character fails to render for you.

![image](https://cloud.githubusercontent.com/assets/65913/8890938/d2281572-3313-11e5-9d67-5c2f2b8b074d.png)

**Comment by dwt** [comment]
To which I say this:╰̩̩̩̩̩̻̍̍̍̍̍̊●̩̩̩̩̩̩̩̻̍̍̍̍̍̍̍̊ᴗ̩̩̩̩̩̩̩̩̩̩̪̺̍̍̍̍̍̍̍̍̍̍̆̑●̩̩̩̩̩̩̩̻̍̍̍̍̍̍̍̊╯̩̩̩̩̩̩̻̍̍̍̍̍̊

**Comment by as-cii** [comment]
> Is it necessary for tiles to have a background instead of being transparent with the containing div providing a background? That would allow you to let each tile overflow, similar to how you allow a line to to overflow to the next and previous line within a line.

Background on tiles is, unfortunately for this issue, mandatory. It's basically one of the main requirements to enable subpixel anti-aliasing (i.e. crispy text on displays without high resolution). But thank you @dwt and @rbu for giving your point of view on this! :bow: 

So, here's an idea that doesn't break tiling but would allow these kinds of lines to be rendered appropriately. I will describe it using a series of steps that an hypothetical implementation could employ, but keep in mind their purpose is just to explain the concept.

* When dispatching a new animation frame, render a fixed set of lines within each tile, as we're doing now.
* After the frame has been successfully dispatched, we measure all the new lines and we remember all those ones that cross their tile boundary.
* Request a new animation frame.
* We slide all the previously remembered lines into the subsequent tile. The degenerate case for this would be to have all the lines in a single tile (i.e. when the first line spans vertically over the whole document).
* As we scroll, we progressively (and, possibly, efficiently) store how many lines a certain tile can fit, so that we don't have to measure the same lines over and over and we can perform calculation for the next tiles appropriately.

@nathansobo: thoughts? It's clearly a workaround which wouldn't be otherwise needed hadn't we used tiling, and it definitely feels like more complex. Maybe using synchronous scroll events and ditch tiling will solve this problem once for all (assuming we manage to avoid creating a huge GPU layer)?

**Comment by nathansobo** [comment]
@as-cii Why don't we start with bumping the z-index on tiles that are higher up on screen. This won't be perfect because presumably there are characters that extend above the line, but it at least covers the common case of underscores for now. All this makes me want to revisit that synchronous scroll hack we were talking about to see if we can take advantage of GPU acceleration while rendering in a more normal way, or explore other more radical directions long term such as canvas.

**Comment by dwt** [comment]
I just noticed that the rendering of the unicode-testcase I inserted above is faulty on Chromium as well as in Firefox. :/ TODO: more bug reporting. For clarity, this screenshot shows on the left how it should render (Safari Mac) and then the misrenderings of Chromium and Firefox
![bildschirmfoto 2015-07-28 um 09 42 57](https://cloud.githubusercontent.com/assets/57199/8926097/51901ca6-350d-11e5-8da1-37896cd9eaf1.png)
