### ISSUE TITLE
Should open the last window with opened items when open the first window

### ISSUE THREAD

**Issue by allenhwkim** [atom/atom#8083]
When I quit the application, Atom re-open the last project that I was working on it.

![image](https://cloud.githubusercontent.com/assets/1437734/8891972/ab7bdcf8-330c-11e5-93bc-0dc4c92be0e0.png)

However, when I close the last window, and open the first window, it does not open the last open items 

![image](https://cloud.githubusercontent.com/assets/1437734/8891978/e68d6208-330c-11e5-8c60-221f0279a882.png)

It works the same as I click left-top x button assuming it share the same logic.

![image](https://cloud.githubusercontent.com/assets/1437734/8891995/8da73f0a-330d-11e5-89ef-eea21ffdf0de.png)

IMO, it should reopen the last window with files opened like it does on quitting the application, when there is no window active.

**Comment by 50Wliu** [comment]
This is intended behavior, and is how all OS X applications that save sessions work. Otherwise it would be impossible to remove windows from the saved session - you could only add windows and never remove them without resetting the entire saved session.

/cc @mnquintana since I copy/pasted your comment on the mega-issue.
