### ISSUE TITLE
BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d

### ISSUE THREAD

**Issue by bkerensa** [atom/atom#8137]
Atom[1956]: BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d

**Comment by rsese** [comment]
Trying to go through and cleanup some older issues - it's been a while since this report and Atom is currently at release version 1.14.4.  Also, I'm not sure if this was the case for you when you first reported but the error you mentioned was also noted in https://github.com/atom/atom/issues/7811#issuecomment-120431675 and related to the El Capitan beta.

I'll go ahead and close the issue for now but if you're still seeing an error with the latest release version of Atom, please feel free to open a new issue and fill out the issue template @bkerensa  ✌️
