### ISSUE TITLE
Please consider an option to disable plugin warnings, at least temporarily

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8152]
My eslint plugin is currently throwing warnings every time I hit a key, but only when working in the eslint project itself.

I'm fine with the plugin being broken, I'm not fine with it taking up half of my screen with a giant red warning box that I can't ever dismiss (because whenever I type anything another one just pops up).

I'm not sure what the best solution is here, or if there is one in place already (I couldn't find it), but I'd suggest something along the lines of chrome's "prevent additional alert messages" option that would disable all warnings from that plugin until the editor is restarted, projects switched, or some other trigger.

**Comment by benogle** [comment]
I really think that eslint package should capture those errors and handle them in a nice way. Turning off notifications is masking the actual issue which is that the package is not behaving. 

Can you open an issue on your eslint package's repo?

**Comment by zyklus** [comment]
@benogle -- Closing this dismissively is masking the issue ;)

My point is this -- Atom itself becomes _annoying_ when a plugin is mis-behaving.  The plugins are throwing errors, but Atom is the cause behind a giant red box that takes up a large portion of my screen.  And the reason that it's misbehaving isn't always critical enough to say "HEY, PAY ATTENTION THIS PLUGIN IS BROKEN!!!!".  In my specific case, I know why it's mis-behaving and am fine with it (I'm working on a branch of eslint itself that is incompatible with the version that the plugin is using, so there is a mismatch in config files, but only in that directory).

In a different case, I was seeing errors because a plugin was trying to access something via the internet and I was working offline.  Yes, the plugin shouldn't be throwing errors for that, but I as a user also shouldn't be forced to go into config, disable the plugin, then later remember to re-enable it.

What you're saying is akin to "put up with the warnings, or disable the plugin until it's fixed".  I'll reiterate that although the warnings are from plugins, the giant red boxes are not.

I'm not suggesting turning warnings off.  I'm suggesting an option that says "Yes, I realize there's an error here, I don't want to be notified of it for a while".

**Comment by benogle** [comment]
Are they all the same error? Maybe something like https://github.com/atom/notifications/issues/12 would help? Can you paste one of the errors into this issue (a screenshot is fine)?

**Comment by zyklus** [comment]
In this case, yes.  And as long as the "group by" has the ability to dismiss issues "permanently", I'm fine with it.

But the issue I'm concerned with is a bit different, as with the issue you linked I foresee:

- Error pops up, they all get grouped
- You close the group
- Another error pops up because now the group is closed

So you're still left with "deal with this giant red box or disable the plugin"

<img width="470" alt="screen shot 2015-08-01 at 9 25 19 am" src="https://cloud.githubusercontent.com/assets/320562/9020155/7e4c4588-382f-11e5-95d5-0a319dcb2c1b.png">

**Comment by 50Wliu** [comment]
I'm :-1: on disabling notifications globally for the following reasons:
* What if different, meaningful, errors pop up?  Then those will be ignored, which could lead to things breaking
* Similarly, some packages use notifications to alert you of something important

I can, however, see a button to disable *specific* notifications for the current session.

**Comment by zyklus** [comment]
@50Wliu -- Agreed, I suppose specific notifications are the more important point.  I wasn't aware of a plan to group them :)

**Comment by NullVoxPopuli** [comment]
Any progress on this? Omnisharp has non-critical errors out the wazoo.

**Comment by kanadskiy** [comment]
These warnings are seriously the most annoying thing in the world. I can't hide them because the plugin causing them keeps throwing them up until there are no more errors in my code, but it's hard to fix my code when these frustrating bubbles keep popping up. For the love of all that is holy, provide a config option to disable them!

**Comment by erykpiast** [comment]
I know that disabling notification is not right solution for the real problem (broken plugins), but sometimes it would be very useful to suppress errors from some plugins. It may be just an option. Even hidden behind developer console.

**Comment by elifoster** [comment]
Perhaps instead of disabling them or hiding them, a config option could be provided to easily decrease/increase the scale of them. Unless that already exists, but it doesn't look like it does.

**Comment by eranimo** [comment]
Would be really nice to have. This is an editor. I don't really care if a plugin isn't working. At least make it a small icon somewhere...

**Comment by tomduncalf** [comment]
While hiding the errors certainly isn't the right solution, it can help preserve our sanity ;) You can do this with a custom stylesheet (instructions for Mac):

1. Atom menu > Stylesheet...
2. Add the following to the bottom:

    ```
atom-notification.error {
    display: none;
}
```
3. Save

Voila, no more errors! (don't blame me if you miss something important though - sadly there's no information I can see in the markup to allow you to only hide notifications for a certain plugin)

**Comment by ericclemmons** [comment]
Here's my dilemma:

- Finished working on a project.  Ready to prepare for deployment!
- `rm -rf node_modules`
- `NODE_ENV=production npm i` (no more `eslint-*` or other dev-tools!)
- `npm run build` (It failed!)
- I open up Atom to start correcting files, removing dev-only code, etc., but all I see is:
  > https://cloud.githubusercontent.com/assets/320562/9020155/7e4c4588-382f-11e5-95d5-0a319dcb2c1b.png
- I "Close All", but every new file throws things errors up.

My recommendation is:

- Be able to ignore notifications **that only lasts for the current session/project**. Restarting Atom, or closing the window resets it.

**Comment by rapus95** [comment]
What about giving the errors their own tab rather than overlaying them?
Opposite direction: While every single window is based upon tabs and their individual placement, errors just pop up into the foreground screwing up the whole layout... in other words, why can't we easily make the errors part of our "workflow" layout (with their own space)?

**Comment by rickmills** [comment]
Agreed, if you really wont provide or allow a way of disabling them, they need to be a lot less intrusive. A big red box on top of your code is unacceptable. Either an icon in the bottom bar, or maybe a small box on the bottom of the sidebar would be much less annoying.

As an end user, it shouldn't be my concern or problem if a plugin's causing Atom to flip out, especially if its working fine.

Case in point, the PHPCS plugin - it causes errors to flag up a lot because if you start typing code, it's constantly running phpcs and naturally will cause a failure if you're in the middle of writing something. Yes, the plugin author needs a better way of doing that, but at the same time Atom needs a better way of handling when this does happen.

**Comment by joshwcomeau** [comment]
:+1: PLEASE allow a way to disable plugin errors. This has been driving me crazy. I'm about to disable all errors, but I worry that I may actually miss something important and it'll cause more harm.

**Comment by gerrywastaken** [comment]
The earlier idea of using a CSS override was fantastic, although I'd suggest using something like the following so that you can still see that there is an error (hover over to make it more visible), but are not restricted from working past it.

```css
atom-notification.error {
    opacity: 0.05;
}
atom-notification.error:hover {
    opacity: 1.0;
}
```

These boxes absolutely kill me on packages such as linter-reek where the author seems to think they should be used for notifying users of errors in their own (non-plugin) code, obscuring said code in the process: https://github.com/AtomLinter/linter-reek/issues/35#issuecomment-241183055

Another tip: Clicking inside one of the boxes and then hitting [Esc] on your keyboard will close all the currently open alerts.

**Comment by joshwcomeau** [comment]
Yeah the issue is linters. Every time I press any key, a new error pops up because the linter tries to lint (the error message has to do with some rule being configured incorrectly, but it's not a rule I've defined, it's within AirBnb's eslint package). 

It's incredibly frustrating, and if someone can point me in the right direction (disabling warnings from specific plugins) I'm happy to solve the problem myself.

**Comment by hiddentao** [comment]
Here's my style solution:

```css
atom-notification.error {
  width: 32px;
  height: 32px;
}
atom-notification.error:hover {
  width: auto;
  height: auto;
}
```

This will make the show up as consecutive small red boxes in the top-right. If you hover over them they become full-size. Out of the way but still catch your eye to let you know something's up.

**Comment by manuelmhtr** [comment]
My temporary solution is disabling **"Lint As You Type"** checkbox (in linter plugin). It stopped those annoying alerts unless I really make an error and save the file.

**Comment by chris-kahn** [comment]
My solution was that I stopped using Atom and switched to VS Code anywhere I would have used Atom.

**Comment by NullVoxPopuli** [comment]
Can vs code have vim-style hot keys?

**Comment by chris-kahn** [comment]
It has a vim extension, yes. It's also built on Electron, written in TypeScript, probably anything that's possible in Atom can be done in VS Code. But it seems to perform way faster and has less intrusive notifications.

**Comment by NullVoxPopuli** [comment]
Hmm, I'll have to give it a go. I have my atom customized pretty heavily.

Shortcut keys I use:
https://github.com/NullVoxPopuli/dotfiles/blob/master/home/.atom/keymap.cson
(the big thing for me is being able to customize everything to fit my
style, and I just am not aware of vs code's capabilities)

**Comment by 50Wliu** [comment]
@manuelmhtr as @benogle said in his original comment you should really open an issue on whatever linter is throwing those errors.  Linters shouldn't be using Notifications to present lint errors (linter already has its own UI/UX for that).

**Comment by gerrywastaken** [comment]
@50Wliu We have, apprently this expectation is not well communicated to Linter authors: https://github.com/AtomLinter/linter-reek/issues/35#issuecomment-241183055

**Comment by 50Wliu** [comment]
Yeah, that's **definitely** not what Notifications was designed for.  linter-reek should be taking advantage of linter's UI components, like linter-coffeelint does.
![unobtrusive-notification](https://cloud.githubusercontent.com/assets/2766036/21078465/227d7622-bf3e-11e6-8821-e0b5e05c9857.png)

Notifications should be one-time, "hey, look at this!" alerts.

**Comment by karlhorky** [comment]
First of all, let me thank the Atom contributors from building such a hackable, open editor. It is my editor of choice because of the integrations and its use of web tech.

That said, the notifications are the most annoying thing about Atom. Makes me really unproductive. The feeling is strong to want to switch editors.

**Comment by karlhorky** [comment]
For a workaround, here's some updated styles based on @hiddentao's solution:

```less
atom-notification.error {
  width: 30px !important;
  height: 42px;
  .close:before {
    display: none;
  }
}
atom-notification.error:hover {
  width: 32em !important;
  height: auto;
  .close:before {
    display: inline-block;
  }
}
```

**Comment by karlhorky** [comment]
The top solution out of what I've seen is:

- request: option to show notification indicator in status bar: https://github.com/atom/notifications/issues/14

A further list of issues that may end up panning out:

- Please consider an option to disable repeated warnings, at least temporarily:  https://github.com/atom/notifications/issues/88
- Make the plugin less annoying: https://github.com/atom/notifications/issues/104
- Group duplicate errors: https://github.com/atom/notifications/issues/12
- Allow us to block popup's from addons: https://github.com/atom/notifications/issues/90

**Comment by trevor-coleman** [comment]
A great option would be:
* Hide errors from this package until next restart

Selecting it would hide all errors from that package until the next time Atom is restarted.

It lets people hide unhelpful/annoying errors, but also addresses the "what if there's an important error" problem, because on the next restart you'll see the error the first time it happens.

**Comment by karlhorky** [comment]
> Hide errors from this package until next restart

I think that this may be a good option for developers who want to always know when something goes wrong.

---

However, for myself and I would guess others, I would propose to having an editor that doesn't scream at the user with errors (kind of like the concept of graceful degradation on the web). Often I need to open and finish something quickly, and don't want to have to deal with or even see the errors that come up. If something doesn't work, then I will work around it in the moment.

When I am not in a rush, I would like to be able to go back and fix any issues the editor has (with packages or with core or anything). This is why I think that a small notification on the status bar (like the ⚠️ 10 in the image below) is enough for this:

<img width="413" alt="screen shot 2017-07-25 at 11 58 13" src="https://user-images.githubusercontent.com/1935696/28566816-951ae210-7130-11e7-9207-8ffc41c213c2.png">

**Comment by BehemothTheCat** [comment]
Hard luck, bye bye notifications until they fix this.

**Comment by kyle-sama** [comment]
atompls

**Comment by Raemon** [comment]
FYI, I just did the "disable notifications completely" CSS hack - I haven't seen a single notification that was relevant to me, and lots that were not.

**Comment by sijpkes** [comment]
I really think a lot of this could be avoided if linter packages simply provided a button when you wanted to Lint rather than Linting continuously. Even if the linter only ran on Save, this would be better than the continuous memory leeching, resource intensive Linting that a lot of these packages use.

**Comment by 50Wliu** [comment]
[As I've said previously](https://github.com/atom/atom/issues/8152#issuecomment-265937059), Notifications are not meant to convey linting errors.  There are dedicated UIs for that.  If you are using a linter package that is using Notifications to display errors and warnings, I would encourage you to open an issue on that package asking them to move to the standardized linter UI instead.

**Comment by joshwcomeau** [comment]
> As I've said previously, Notifications are not meant to convey linting errors. There are dedicated UIs for that. If you are using a linter package that is using Notifications to display errors and warnings, I would encourage you to open an issue on that package asking them to move to the standardized linter UI instead.

If you look at the screenshots shared by @MarkKahn, you'll see that the issue isn't that lint plugins are using the notifications system for lint warnings; the issue is that the lint plugin is failing because of a dependency issue, and triggering a new notification about it on every keystroke (so, constantly).

The problem is that this is a legitimate error, but it's unimportant. I don't care that my linter package is being finicky today, I just want to get back to coding.

The desired solution is an ability to selectively disable the permissions for the notification on a package-by-package basis. Some way to block `eslint-plugin` from raising notifications, without missing crucial notifications from other packages or Atom itself. Frustratingly, this request has been brought up several times, without being acknowledged. This is a real pain point, and it hasn't been given a fair discussion.

To be clear, I have immense respect for OSS maintainers (I'm one too!), and I wholeheartedly believe that I am not "owed anything" by folks who spend their free time building tools to make my job easier. But, I also feel like folks who bring up an issue should be able to have a discussion about it (even if that discussion just leads to "I understand the issue, but this isn't a priority for us at all right now").

**Comment by 50Wliu** [comment]
> The desired solution is an ability to selectively disable the permissions for the notification on a package-by-package basis.

I think this can maybe be explored if we can find a good UI for it.  If you can flesh that idea out you should file a new issue on [atom/notifications](https://github.com/atom/notifications).

**Comment by Raemon** [comment]
The UI here should be pretty simple - on the error notifications, next to
where it currently says ‘hide all notifications of this type’, add a button
that says ‘disable all of this type’ (at least for a day)

As is, I’ve had to just CSS hide all notifications completely to make Atol
useable.
