### ISSUE TITLE
Atom is slow with backspace and cmd+z

### ISSUE THREAD

**Issue by alfredobarron** [atom/atom#8204]
Atom is slow with backspace and cmd+z

**Comment by mnquintana** [comment]
We're going to need [a lot more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) to help you debug this – what version of Atom are you using? What OS? Can you reproduce this in safe mode? (Quit Atom completely, then reopen with `atom --safe`)

**Comment by alfredobarron** [comment]
Atom 1.0.3, OSX Yosemite, I can not reopen in safe mode.

**Comment by mnquintana** [comment]
> I can not reopen in safe mode.

Do you mean that you can't reproduce this problem in safe mode, or that you can't open Atom in safe mode?

**Comment by alfredobarron** [comment]
$ atom --safe
command not found

**Comment by mnquintana** [comment]
Can you try running Atom > Install Shell Commands from the main menu first, then try opening Atom with `atom --safe`?

**Comment by alfredobarron** [comment]
ready to go

**Comment by mnquintana** [comment]
Can you try running `atom --safe` now and see if you can reproduce the issue?

**Comment by alfredobarron** [comment]
now not , but packages not found

**Comment by mnquintana** [comment]
Yup, that's what [safe mode](https://atom.io/docs/v1.0.3/hacking-atom-debugging) does – it prevents Atom from loading your installed community packages and your [Init Script](https://atom.io/docs/v1.0.3/hacking-atom-the-init-file) to make it easier to debug issues.

Since you can't reproduce this issue in safe mode, that means that one of your installed packages is causing this issue. You can try to find it by manually enabling and disabling packages until you find the one that makes this issue appear, then you can report this issue on that package's repo.

**Comment by alfredobarron** [comment]
Thanks for all
