### ISSUE TITLE
Atom is not installed in my system properly

### ISSUE THREAD

**Issue by Aravin** [atom/atom#8230]
I have installed 3 times atom application using .exe file.

First time atom gets open and I can perform any action.

After closing the atom application, it is not available in my sytem. It is not installed in my system.

Again I have to install exe file to open the atom.

INFO:
OS: Windows 8.1

**Comment by methodbox** [comment]
Sounds like a registry conflict.

Try installing Atom new then uninstall it immediately after, then restart.  This should wipe the registry entries and a fresh install should work.

If not, it may require that you manually remove the remaining registry entries.

This is sometimes also caused by a permissions issue. When you install the next time try the "Run as administrator " option under the right-click menu.

**Comment by Aravin** [comment]
Dear Methobox,

3 times i have installed.

2 times on user account. 1 time on Administrator account.

After many installation I found their is some issue in atom.io installation. Kindly try to identify and fix.

As of now I am using Portable version!

**Comment by damieng** [comment]
Hi Aravin, can you provide the squirrelsetup.log from %userprofile%\appdata\local\atom ?

**Comment by damieng** [comment]
No response, closing issue. Please re-open if still experiencing this issue.
