### ISSUE TITLE
"Check for update" says no update is available although a new one is available.

### ISSUE THREAD

**Issue by warpdesign** [atom/atom#8265]
I'm running version 1.0.4. If version 1.0.5 has been detected in the background, opening the release notes menu would show a "restart and update button" plus the 1.0.5 changes.

However, clicking on "check for update" will say "No update available. 1.0.4 is the latest version.":

![atomupdatewindows](https://cloud.githubusercontent.com/assets/199648/9133086/f9d04498-3cf8-11e5-8048-4dc7ea637dec.png)

This happens in Windows 10.

**Comment by batjko** [comment]
How quickly did you try it after 105 was release? It does take a little while after release before the app recognizes that the update is available.

**Comment by warpdesign** [comment]
Atom is running 24/24 on my computer. This morning, I switched to the app, and as usual, ran the "check for update" from the help menu, which returned "no updated available", but after some time, I noticed the blue squirrel indicating an update at the bottom of the window. I clicked on it, it opened the release notes tab, with the "restart and update" green button.

Curious, I ran the "check for update" (before updating) from the menu again, which said that "no update were available": that's when I took the screenshot above.

**Comment by Stanzilla** [comment]
I had the same. After I closed Atom and reopened it, it was already on 1.0.5 so it definitely updated, the UI just did not know about it. That's also probably because why it could not find a new update, because it actually already updated and was up to date. It usually happens when you resume the computer from standby. Maybe the update check task does not handle that correctly?

**Comment by worldspawn** [comment]
I have version 1.0.6 on windows and it says 

![image](https://cloud.githubusercontent.com/assets/819581/10775334/95f71584-7d5b-11e5-868a-669299d2d763.png)

Which is has done for days and no amount of rebooting, reopening seems to change its mind.

**Comment by rahlzel** [comment]
Confirmed in 1.11 before I manually updated to 1.12.6, and before 1.11 I also never had an update notification to update the actual program since I started using it. The package update notifications work fine, it's just Atom itself that does nothing to inform the user of an update (or lies about it by saying you have the latest version).

I'm using the portable ZIP version of Atom. Perhaps the updater doesn't work for the portable version but does for the installer?

**Comment by xgdgsc** [comment]
I' m stuck on 1.12.6 when there is 1.13.0 available.

**Comment by rahlzel** [comment]
@xgdgsc Are you using the portable ZIP version of Atom or did you install it to your computer with an .exe?

**Comment by xgdgsc** [comment]
exe version.

**Comment by axelson** [comment]
I'm still getting this. Very annoying since you can't clear the blue squirrel either. Currently running 1.14.4 but 1.15 is listed as the most recent non-beta version on https://atom.io/releases

**Comment by rabbitfang** [comment]
I'm getting this on Atom 1.14.4 on Windows, installed version. 1.15 has been out for 25 days now.

**Comment by flaviolaino** [comment]
Same issue here, with version 1.15.0 on Windows 10.
Check for update don't recognize latest versione (1.16 stable).
Safe mode doesn't help.

**Comment by rahlzel** [comment]
![Yarp](http://i.imgur.com/erIG90a.png)

**Comment by bennypowers** [comment]
termination plugin created an entry `termination` in config.cson without quotes. I surrounded the entry in quotes and was able to launch

**Comment by rahlzel** [comment]
Still an issue 2 years later. I've been updating Atom manually since I started using it around version 1.10 or so. I have it installed on my D: drive, and it's the portable version in case that helps.
Windows 7 64bit

![bugged](https://i.imgur.com/KCUKlu0.png)

**Comment by TylerDelRosario** [comment]
I know its a bit late, but I'm getting thise issue right now. I'm on version 1.20 when there is 1.23 available

**Comment by dschwen** [comment]
I am on 1.24.0 (and 1.24.1 is available). I got the "1.24.0 is the latest version" dialog when clicking "Check for update". My Atom processes are long running. I just quit Atom entirely and reopened it and without further intervention it proceeded to download the update :-/

**Comment by branditodesign** [comment]
I am on 1.28.1 x64 (Windows 10) and I'm being told theres an update from a little blue squirrel in the bottom right corner (does he/she have a name?) but the "Check now" button says I'm up to date. The release notes however point me to a 1.28.2 version.

**Comment by jeffreedzbc** [comment]
I'm on 1.27.1 and I see version 1.31.1 is available on atom.io, but my "Check for Updates" is saying "No update available".  I suspect it's something in the logic that is using a default response if the site is unavailable due to proxy or other connection issues, but whatever it is, it's not helpful.

**Comment by lee-dohm** [comment]
Is anyone seeing this currently and persistently? If so, please include steps you have to reproduce and as much information as you can include about the cause.

**Comment by Ben3eeE** [comment]
> Is anyone seeing this currently and persistently?

I see this issue every time an Atom update is released because I leave Atom running overnight and the releases are usually at night time in my timezone. If you leave Atom running for a couple of hours after the update downloads you get into this state.

Restarting Atom does start the new version so the only issue for me is that it reports incorrectly. I wonder if anyone reporting this is unable to update at all 💭 This issue might just be a combination of this incorrect reporting because you checked a few hours after the update was already installed and the portable version reporting the same thing when automatic updates are not supported for the portable version. A lot of the comments here mention the portable version.

I believe the portable version now reports that automatic updates are not supported instead of this message.

Steps to reproduce:
1. Ensure you have the setting to automatically download updates enabled
1. Install a version of Atom that is not the latest
1. Make sure the update is downloaded
1. Leave Atom running for several (8?) hours without restarting Atom
1. Check for updates

**Expected:** Atom to report that an update has been downloaded and a restart is required
**Actual:** Atom reports that the installed version is the latest

**Comment by cdusold** [comment]
Interesting. Launching a new window and checking About shows the expected behavior, then going back to the original window and refreshing yields the correct behavior, but I've never seen the About page work without doing that to date. I didn't even know what the expected behavior was supposed to look like yet, and I've been using Atom for over a year.

Definitely still not fixed in 1.32.2 on Windows 10.
