### ISSUE TITLE
Can't override key binding

### ISSUE THREAD

**Issue by gabriel** [atom/atom#8347]
Trying to override cmd-shift-d.

![2015-08-12 at 10 36 am](https://cloud.githubusercontent.com/assets/2669/9231646/1d229b06-40de-11e5-8d04-0f9205c08a5e.png)

![2015-08-12 at 10 38 am](https://cloud.githubusercontent.com/assets/2669/9231668/44499c5c-40de-11e5-8661-ce81e6550447.png)

But it doesn't work. It still does duplicate line.

I've tried both:

`'cmd-shift-d': 'fuzzy-finder:toggle-file-finder!'`
`'cmd-shift-D': 'fuzzy-finder:toggle-file-finder'`

I don't have an international or weird keyboard.

Is this because it's a Core binding?

**Comment by maxbrunsfeld** [comment]
It's because the selector that you're using `.editor` is less specific than [the one defined in core](https://github.com/atom/atom/blob/8bc5789828c06e98dd6313ce85cefc9864dca1d2/keymaps/darwin.cson#L147). So for now, I'd say do this:

```coffee
'atom-workspace atom-text-editor:not([mini])':
  'cmd-shift-D': 'fuzzy-finder:toggle-file-finder'
```

/cc @nathansobo do you know why we use a descendent selector within `atom-workspace` in that case? It seems like it makes the selector unnecessarily specific, making it more cumbersome for users to override.

**Comment by nathansobo** [comment]
@maxbrunsfeld Good point. I'm not sure why it's that way. Maybe we should try simplifying it.
