### ISSUE TITLE
Child Themes

### ISSUE THREAD

**Issue by jcuenod** [atom/atom#8374]
I hope that core is the right place to post this, feel free to close and redirect me if not.

I just installed a new theme and didn't like its command palette ui. I forked the theme and did what I wanted with the command palette but it made me think that it would be great to have a child-theme/theme-extension/plugin-to-modify-theme ability.

I'm pretty new to atom so I may have missed it but if it exists, it doesn't pop up very quickly on google.

**Comment by simurai** [comment]
There has been discussions about allowing themes to load dependencies. Or more general, allow packages to load other packages. But not sure if/when that will be possible.

Are you thinking about sharing your "command palette ui"? Or you just don't want to keep it as a forked theme because you won't get updates of the original?

Either way, instead of creating a fork, you could override the existing theme in your `styles.less` file. More infos in the docs under [style tweaks](https://atom.io/docs/v1.0.4/using-atom-basic-customization#style-tweaks). And maybe share it as gist?

Or if you want to "publish" it so that other people can install it too, you could create a new package with the styles in it. The package wouldn't change functionality, just restyle the UI. Probably you would need to increase specificity a bit.

**Comment by jcuenod** [comment]
A new package would do it.
I was mostly concerned about getting updates on the parent theme.
