### ISSUE TITLE
[doubts] Hello, I would like for this vertical menu on Linux

### ISSUE THREAD

**Issue by vinibudd** [atom/atom#8390]
<b>Hello, I would like for this vertical menu on Linux?</b>

<a href="http://i.imgur.com/eeGJM2D.png">
  <img src="http://imgur.com/eeGJM2Dl.png" />
</a>

**Comment by simurai** [comment]
That looks like it's the [tool-bar](https://atom.io/packages/tool-bar-main) package. Together with [toolbar-basic](https://atom.io/packages/toolbar-basic).

Or instead of the `toolbar-basic` package, you could also install [flex-tool-bar](https://atom.io/packages/flex-tool-bar) to customize the toolbar with your own icons.

**Comment by vinibudd** [comment]
This not work in Linux?

https://atom.io/packages/tool-bar-main

**Comment by simurai** [comment]
Ohh.. sorry, I posted the wrong link (corrected now). It's

1. https://atom.io/packages/tool-bar
2. https://atom.io/packages/toolbar-basic

**Comment by vinibudd** [comment]
This packages not work in Linux (Xubuntu 15.04) 32bits

**Comment by vinibudd** [comment]
Working! Thanks!
