### ISSUE TITLE
Bad line snapping (python)

### ISSUE THREAD

**Issue by foxx** [atom/atom#8410]
Take the following code snippet;
![screen shot 2015-08-17 at 14 44 08](https://cloud.githubusercontent.com/assets/651797/9306168/78c52b2c-44ee-11e5-8217-9be85ab74d11.png)

If I now press "Option + Left" to jump back to the previous "word", it jumps to the wrong position in the line, as you can see below. 

![screen shot 2015-08-17 at 14 45 24](https://cloud.githubusercontent.com/assets/651797/9306204/aeeeb646-44ee-11e5-8ee2-62d4b6439a2e.png)

It jumped onto the end of the `email_address` string, rather than the closing bracket. My guess is that it not detecting the code context and subsequently doesn't know to jump to the end of the bracket rather than the end of the word.

Instead, it should have jumped here;

![screen shot 2015-08-17 at 14 47 17](https://cloud.githubusercontent.com/assets/651797/9306232/dfc2c596-44ee-11e5-82a9-184a9fd83ba2.png)

**Comment by foxx** [comment]
Here's another one.

![screen shot 2015-08-17 at 14 54 13](https://cloud.githubusercontent.com/assets/651797/9306394/f4a9786e-44ef-11e5-9bb4-041cca0d89af.png)

When pressing "Option + Left" on the start of the first word of the line, it *should* jump to the start of the line before the whitespace, but instead it jumps up to the next line beyond the colon.

**Comment by maxbrunsfeld** [comment]
I can see how these behaviors could be surprising, but both of them are actually intentional. For the `editor:move-to-beginning-of-word` and `editor:move-to-end-of-word` commands, a "word" is defined as either a string of consecutive non-whitespace characters that are either all "word characters", or all "non-word characters". This is similar to what Vim and several other text-editors do.

Also, the definition of "non-word characters" is configurable through the `editor.nonWordCharacters` configuration setting, which can be set differently for different languages.

Also, if you have a different behavior in mind for `alt-left` and `alt-right`, you can map those keys to commands that you define.

@foxx I'm going to close this out, since I don't think this is a bug in Atom. Let me know if you do still think it's a bug; I can reopen it.

**Comment by benogle** [comment]
You can also remap to use the `editor:move-to-*-word-boundary` commands which might be more what you're looking for:

```coffee
'.platform-darwin atom-workspace atom-text-editor':
  'alt-left': 'editor:move-to-previous-word-boundary'
  'alt-right': 'editor:move-to-next-word-boundary'
  'alt-shift-left': 'editor:select-to-previous-word-boundary'
  'alt-shift-right': 'editor:select-to-next-word-boundary'
```

**Comment by foxx** [comment]
Thank you for the quick and detailed reply, appreciated

**Comment by Laufire** [comment]
@maxbrunsfeld, while this might not be a bug. It could be a glitch in UX, especially for the users migrating from other modern editors.

**Comment by jhasse** [comment]
+1. Please reopen

**Comment by VoronaPavel** [comment]
So how do i configure atom to jump in a way @foxx described in the beginning of the discussion?
