### ISSUE TITLE
All lines in search item - excluding the others

### ISSUE THREAD

**Issue by gberth** [atom/atom#8415]
New to Atom, looks very good.

As an old man ;-) having used Kedit for centuries, there is one functionality I look for in every editor, the 

ALL /search criteria/

that shows all lines satisfying the search criteria, excluding the others. (Kedit also has a LESS enabling a step wise display removal of lines with a new criteria)

Additional replace, change etc would only work on the displayed subset.

If the functionality is there, I will be very glad (if someone told me), if it could come in a later release - great.

**Comment by lee-dohm** [comment]
Do you mean like find in project listed here?

https://github.com/atom/find-and-replace/

**Comment by gberth** [comment]
Very promising, and excellent for global find / replace. To give you a
short example of Kedit, from your buffer-search.coffee

all 'emitter

[image: Inline image 1]

less 'TextBuffer

[image: Inline image 2]

And editorial can be done on this subset alone.

And

*ALL*

command and your back to view the whole file.


But - very promising :-)

Have a nice day - summer has suddenly reached Norway. :-)

Regards
Gunnar Berthelsen

On Tue, Aug 18, 2015 at 1:11 AM, Lee Dohm <notifications@github.com> wrote:

> Do you mean like find in project listed here?
>
> https://github.com/atom/find-and-replace/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/8415#issuecomment-131988777>.
>



-- 
Mvh

Gunnar Berthelsen
91545192

**Comment by izuzak** [comment]
@gberth Those images didn't come through (have a look at the version of the issue on the website to see what we see). Can you post a new comment via the website and include the images that way? I'm still not sure I understand your suggestion, so would love to see those images. 

Also, this seems like a good suggestion for a package, rather than something to be implemented in Atom core. Atom is based on providing features through packages and a core which runs those packages which you installed (in addition to providing a core editor for everyone). https://atom.io/packages

**Comment by gberth** [comment]
Done, and thanks for notifying me. As I said, just installed Atom, and
thinks it looks very promising. Looks like find-and-replace could be the
package.

Best regards
Gunnar Berthelsen

On Tue, Aug 18, 2015 at 5:44 PM, Ivan Žužak <notifications@github.com>
wrote:

> @gberth <https://github.com/gberth> Those images didn't come through
> (have a look at the version of the issue on the website to see what we
> see). Can you post a new comment via the website and include the images
> that way? I'm still not sure I understand your suggestion, so would love to
> see those images.
>
> Also, this seems like a good suggestion for a package, rather than
> something to be implemented in Atom core. Atom is based on providing
> features through packages and a core which runs those packages which you
> installed (in addition to providing a core editor for everyone).
> https://atom.io/packages
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/8415#issuecomment-132254490>.
>



-- 
Mvh

Gunnar Berthelsen
91545192

**Comment by izuzak** [comment]
Thanks for those images, @gberth -- that's very helpful. Yeah, I think this would be a neat idea for a new package, or even a new feature for find-and-replace (personally, I'm leaning towards having that in a new package). 

You might want to suggest that [on the forum](https://discuss.atom.io/) (perhaps someone likes the idea enough and builds the package) or even try [building it yourself](https://atom.io/docs). I've also added the "package-idea" label to this issue so that users looking for ideas can find it, even if the issue is closed.
