### ISSUE TITLE
The "whitespace" package should be migrated as a core feature, and exposed as a preference

### ISSUE THREAD

**Issue by groue** [atom/atom#8428]
Rationale:

1. The default behavior is whitespace aggressive.

2. One should expect the user to look into the preferences in order to turn it off, where the user can't find the solution to her problem.

3. One should not expect the user to find the page https://discuss.atom.io/t/why-is-atom-deleting-trailing-whitespace-why-are-there-all-these-changes-in-the-file-diff/19189, because, hey, it's too late, Atom has already lost 10 points of karma.

4.The whitespage package contradicts the "Auto Indent" preference, which makes Atom, by default, schizophrenic.

Related issues: #8425, #8424.

**Comment by izuzak** [comment]
@groue Thanks for providing all the feedback so far -- it's always helpful to know which bumps in the road new users run into. :car: 

It seems that the core problem you're having is that you didn't expect more settings to be available in different places (under packages). I agree that might not be the first thing you think of when you run Atom, and there's opportunity there to improve. There's already an open issue to include package settings on the main settings page: https://github.com/atom/settings-view/issues/284

Also, there's another issue related to disabling the functionality provided by that package by default: https://github.com/atom/whitespace/issues/10. You'll notice that there's lots of feedback already there and the issue has been closed and locked in favor of other issues (in that package and other packages, such as the settings view) which aim to improve the experience. 

> The whitespage package contradicts the "Auto Indent" preference, which makes Atom, by default, schizophrenic.

I didn't understand this. Could you open a new issue which clearly explains this, with exact steps to reproduce the problem? (Note: GIFs are often helpful when trying to demonstrate schizophrenic behavior. :wink:)

We're always interested in hearing your feedback, but we'd also like to give you a few tips so that you can provide that feedback in the most helpful way:

1. Read the [guidelines](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) for submitting issues.
2. Instead of suggesting a single possible solution you have in mind, try to describe the problems you're having in as many details as possible (steps to reproduce will earn you a :star2:), and try to leave out words like "schizophrenic" -- they're not helpful, which I'm sure you understand.
3. Describe a single problem in a single issue; describing multiple problems in a single issue makes it harder to track and manage issues, which is a concern for a project this big.
4. Before opening issues, try and search for existing issues on the same topic. Atom has been around for over a year, and you'll normally find at least one issue on the topic you want to discuss. Adding a comment to existing issues helps us keep discussions focused, it's easier to find all the related information and also helps us understand how many users are affected by the same problem or missing feature.

I'm closing this issue in favor the things I mentioned above. There's no reason to integrate the Whitespace package into Atom core from what I can tell, and packages are at the :heart: of Atom.

**Comment by groue** [comment]
It looks like https://github.com/atom/settings-view/issues/284 exposes well the trouble.

> Before opening issues, try and search for existing issues on the same topic

Seriously, I did :-) Yet please consider that the issues related to my problem, the ones that you linked to, were hidden in sub-repositories. I'm brave, but there are limits!

As you have very clealy understood, I'm totally new to Atom, and have opened issues about what did bother me after a few hours or work. This is the crucial time when an application loses users. So thanks again for your patience, and don't mix "flexible text editor for opinionated users" with "opinionated text editor that bully new users" :-)

**Comment by groue** [comment]
@izuzak https://github.com/atom/whitespace/issues/10 is closed and locked.

**Comment by izuzak** [comment]
@groue Notice my comment above:

> You'll notice that there's lots of feedback already there and the issue has been closed and locked in favor of other issues (in that package and other packages, such as the settings view) which aim to improve the experience.

**Comment by groue** [comment]
> Before opening issues, try and search for existing issues on the same topic. Atom has been around for over a year, and you'll normally find at least one issue on the topic you want to discuss.

That looks like a tough job, now that "issue has been closed and locked in favor of other issues" :-)

So the original problem which is "Atom is whitespace-aggressive by default" has been vaporized into smaller and nicer issues. OK, have a nice day, and thanks for your answers!
