### ISSUE TITLE
un-highlight non-directory files in directory pane ui

### ISSUE THREAD

**Issue by vincentschen** [atom/atom#8450]
I opened another file (test.java) from the terminal via `atom test.java`. It opened in my previous working directory, and it would be more intuitive if it unhighlighted in the working directory pane as well. 

A minor but helpful enhancement! 

![screen shot 2015-08-19 at 11 56 29 am](https://cloud.githubusercontent.com/assets/5819303/9366004/95fe2d3e-4669-11e5-8b45-57364ec30178.png)

**Comment by izuzak** [comment]
I'm having trouble reproducing this, @vincentschen -- the previously selected item is unhighlighted for me. Could I trouble you to:

1. specify the version of Atom you're using and OS
2. see if you can reproduce that in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)
3. provide step-by-step instructions so that we can try and reproduce
4. provide a GIF in which you go through the steps in 3) to clearly demonstrate the problem 

Thanks!

**Comment by vincentschen** [comment]
-Atom 1.0.11, OS X Yosemite 10.10.4
-Reproducible in safe mode

Steps to Reproduce
---
1. Open Working Directory, and select a file (such that the directory pane ui highlights that file)
2. Open Existing File 
3. Notice that the previous file is still highlighted. Should replicate the behavior of creating a new file in the working director, in which case the original file unhighlights. 

- ![ui-highlight](https://cloud.githubusercontent.com/assets/5819303/9823899/01e0876a-587e-11e5-9da3-607a6f932454.gif)

**Comment by izuzak** [comment]
This issue was moved to atom/tree-view#574

**Comment by izuzak** [comment]
Thanks for the GiF -- I'm seeing the problem now as well. I moved the issue into the issue tracker for the tree view.
