### ISSUE TITLE
Distribute Atom via the Windows Store

### ISSUE THREAD

**Issue by keirlawson** [atom/atom#8453]
With Windows 10 going live a lot of people will be finding software this way, would be great if Atom could be shipped via the store.

**Comment by visualcookie** [comment]
Why should this be needed? The Windows Store is only for Apps that use the Metro style plus I've never seen any developer ... ever ... using the store. :-1:

**Comment by keirlawson** [comment]
I believe the policy on the Metro style has changed with Windows 10? I'm a developer and I use the store when I can, its good to have a single place to go to get applications.

**Comment by thomasjo** [comment]
If you read the [*Windows Store Policies*](https://msdn.microsoft.com/library/windows/apps/dn764944.aspx?f=255&MSPPError=-2147217396), specifically the subsection surrounding security, it will become rather clear that Atom will never be distributed in the Windows Store. The limitations posed on Windows Store app are simply too great and far reaching. As a concrete example, the package system will not be allowed due to section 10.2.2 which reads

> Your app must not attempt to change or extend the described functionality through any form of dynamic inclusion of code that is in violation of Store Policies. Your app should not, for example, download a remote script and subsequently execute that script in a manner that is not consistent with the described functionality.

It's also quite telling that not even Microsoft's own Visual Studio Code is available on the Windows Store.
Thanks for the suggestion, but I'm closing this since this is simply impossible given the current policies imposed on Windows Store apps.

**Comment by batjko** [comment]
Also, I don't think "a lot of people" actually use the store to find and install apps.
Now, that may change if Windows 10's store really does improve over Win8, but from what I've seen so far... it's certainly a long way off before it's of any use to power users such as developers.
