### ISSUE TITLE
Config is loaded too late in the startup process

### ISSUE THREAD

**Issue by p-e-w** [atom/atom#8564]
I have been trying to solve https://github.com/atom/atom/issues/8287 but repeatedly hit a wall caused by the fact that the config is loaded very late in the startup process, after the window creation code is set up and indeed after all code in the [`browser`](https://github.com/atom/atom/tree/master/src/browser) source directory. This means that currently quite a few things, such as window parameters, are impossible to expose to the user through a config option.

It seems to me that loading the configuration should be *the very first thing* happening on startup, so that all following code can take settings into account.

**Comment by thomasjo** [comment]
> It seems to me that loading the configuration should be the very first thing happening on startup

I disagree with this. It doesn't make sense to load any configurations before we begin loading the core functionality and packages, since configuration only affects these things. All parts affected by configuration are expected to update dynamically in accordance with configuration updates—this doesn't seem like a possibility when it comes to tweaking `BrowserWindow` parameters. I believe that would require a full reload of the app (although I might be wrong). Given that hypothesis we would need some other form of configuration, or other means of changing startup parameters. Shoe horning this stuff into `~/config.cson` and loading it earlier only to support something it shouldn't be used for in the first place, seems like a bad idea at first glance.

**Comment by thomasjo** [comment]
@atom/feedback My initial reaction is to close this as `wontfix`, but I'll give others a chance to chime in and shed some light on this.

**Comment by lee-dohm** [comment]
I agree that this does not seem to be the right solution for #8287. Isn't customizing the browser window from inside a running instance of Atom what the [`WebFrame` class](http://electron.atom.io/docs/latest/api/web-frame/) is for? If it doesn't support changing the value that should be changed, then I believe that is where the modification needs to go.

**Comment by mnquintana** [comment]
I think this was something @benogle and I were talking about awhile ago re: https://github.com/atom/atom/issues/6605 – this is a case where we want a config option, but it's configuring something in the browser process, rather than the renderer.

I think at the time we thought of 2 options:

1. Manually read `config.cson` for this one entry, and require a restart
1. Load config in both the browser and renderer processes (and still require a restart)

Not really ideal either way.

I think *not* using `config.cson` for this is a bad idea from a user perspective though- why should this handful of settings not be stored in the de facto config file? That would also make whatever config options that need to be set in the browser process not portable, at least, not in a consistent way. Users shouldn't have to be concerned with the implementation details of our config options.

**Comment by lee-dohm** [comment]
They're not like other configuration options, though. We don't store everything in the `config.cson`. We have snippets and keymaps and other configuration files as well. So I don't think that it really is that much of a stretch to have maybe a `startup.cson`.

And as @thomasjo pointed out, everything in the `config.cson` currently is supposed to take effect immediately ... there is no Save button. With these browser configuration options, we'd have to add a "Restart Now" button or message that pops up whenever any of them are changed.

**Comment by darkmorpher** [comment]
CC @damieng if this should be closed

**Comment by lee-dohm** [comment]
The Atom config is now available in certain places in the main process for the auto-update features. I'm still not certain that the `config.cson` is the right location for window information that originally motivated this Issue, but the problem that is mentioned in the title is solved in v1.8.x.
