### ISSUE TITLE
The atom.notifications.getNotifications().length only growing

### ISSUE THREAD

**Issue by egorse** [atom/atom#8614]
If I add periodically (or by multiple invoke of plugin) some of notifications, 
after those got automatically removed (not seen anymore) from UI , 
the `atom.notifications.getNotifications().length` does not changes it size.

So I can see its only growing. 

atom 1.0.7

**Comment by izuzak** [comment]
I think that's expected -- there's a [`clear` method](https://github.com/atom/atom/blob/a32034978b5e0bb4f4a27f6dd44bbe034e7a6d86/src/notification-manager.coffee#L86-L91) which you can use to clear the list of notifications.

That method is not marked as public currently, but I think it should and there's already an issue for that: https://github.com/atom/notifications/issues/73. @kevinsawicki do you think it would be okay to make that method Public?

**Comment by egorse** [comment]
@izuzak in case there are two independent plugins generates notifications - who would be responsible for cleaning up? 

and how to know number of actually shows notifications?

**Comment by izuzak** [comment]
> @izuzak in case there are two independent plugins generates notifications - who would be responsible for cleaning up?

@egorse Can you link to the exact lines in two different plugins which are generating notifications? Just want to make sure I understand what you're referring to.

> and how to know number of actually showen notifications?

I'm not sure what you mean -- do you mean the number of notifications that are shown at the moment or the total number which has been shown? Can you share more details about what you're trying to do?

**Comment by egorse** [comment]
@izuzak Here is screenshot from quick and dirty hack - one plugin crash, another (I guess atom - but that should not be so different) catching that and makes additional notification. Before capturing the screenshot I had ran the plugin few times and used "Close all" button. But, the number of notifications in array still growing.

![image](https://cloud.githubusercontent.com/assets/1152410/9602277/c0f120aa-50af-11e5-8f64-290b227f55ee.png)

Event explicitly dismissable notifications after dismiss() are not removed from array.

Back to second question - I'd like to know how many notifications are currently on screen - so, for instance, I would not push there low priority notifications, if there is more than N notifications showen (ie those info notifications about size of notifications array :D)

**Comment by izuzak** [comment]
@egorse I'm not sure what your question is regarding the screenshot which you showed. Can you please state your question clearly? The notifications API allows any package and Atom itself to create notifications -- that's expected behavior, it's a public API https://atom.io/docs/api/v1.0.9/NotificationManager.

> Event explicitly dismissable notifications after dismiss() are not removed from array.

I believe that's expected -- dismissing a notification doesn't remove it from the underlying store of notifications, it only removes it from the UI. 

As for the second question -- perhaps you could use [this method](https://atom.io/docs/api/v1.0.9/NotificationManager#instance-onDidAddNotification) to get references to added notifications, and then use the [`onDidDisplay` and `onDidDismiss` callbacks](https://atom.io/docs/api/v1.0.9/Notification) on those notifications to get updates on when notifications are shown and dismissed? An alternative would be to go through all the notifications in the list and find all those for which `wasDisplayed` returns `true` and `isDismissed` returns `false`. However, [those two methods](https://github.com/atom/atom/blob/a32034978b5e0bb4f4a27f6dd44bbe034e7a6d86/src/notification.coffee#L70-L74) aren't marked as public either, even though they're used in the [Notifications package](https://github.com/atom/notifications). Again, I'd like to see if those can be marked as public. Does that help?

**Comment by egorse** [comment]
1. Not sure the problem from topic is the documentation problem.
The atom own notification - i.e. "Uncaught ReferenceError" - never removed out of NotificationManager.notifications

2. The NotificationManager.clear is not good to use from plugins at all as plugin A might remove the notifications generated by plugin B. So the plugin shall track by itself the notifications it has generated. But currently there is no way to remove own/one notification out of NotificationManager.notifications except direct manipulation.

3. So the notifications api usage cause mem leak. Am I wrong?

**Comment by izuzak** [comment]
> So the notifications api usage cause mem leak. Am I wrong?

I would call it a memory leak if storing notifications in this way is not intentional. Let's hear what @atom/core thinks about that and all of this.

**Comment by kevinsawicki** [comment]
> do you think it would be okay to make that method Public?

Yeah, I think that would be okay. Curious what @benogle thinks though.

**Comment by nathansobo** [comment]
I think it would be appropriate to remove dismissed notifications from the array. Not sure why @benogle wanted to keep them around, but there may have been a good reason.

**Comment by benogle** [comment]
> Yeah, I think that would be okay. Curious what @benogle thinks though.

Making it public is fine.

> I think it would be appropriate to remove dismissed notifications from the array. Not sure why @benogle wanted to keep them around, but there may have been a good reason.

The plan was to allow all notifications to be viewed in a log viewer panel (e.g. https://github.com/atom/notifications/issues/29), even those dismissed. Dismissing a notification would just dismiss it from the right panel, but it could still be available in the log viewer panel.

**Comment by thedaniel** [comment]
Sounds like that log can go on disk!

**Comment by nathansobo** [comment]
Or at the very least could you put a limit on the size of the array?
