### ISSUE TITLE
Default font size is too large?

### ISSUE THREAD

**Issue by benklebe** [atom/atom#8645]
The default font size [is still 14pt,](https://github.com/atom/atom/blob/master/static/variables/ui-variables.less#L70) a setting which I believe is carried over from when the default font was Raph Levien's [Inconsolata](http://levien.com/type/myfonts/inconsolata.html). Inconsolata is unusually small, so it made sense for the default size to be 14pt. However, now that [the default font is Menlo](https://github.com/atom/atom/blob/master/static/text-editor-light.less#L7) with Consolas as the fallback (I guess for Windows) and DejaVu Sans Mono as the second fallback (I assume for Linux), 14pt seems to me to be too large. Menlo 12pt is closer to Inconsolata 14pt then 12pt. Is this intentional? If it's not, I'd be happy to create a PR establishing the default font size as 12pt.

**Comment by simurai** [comment]
It used to be Inconsolata at `16px`. When it got changed to Menlo, `14px` seemed the closest: https://github.com/atom/atom/pull/7281

`12px` feels a bit small to me, but it also depends how large the screen is.

**Comment by benklebe** [comment]
Ah well Inconsolata at 16px is quite large as well. My apologies for misunderstanding the original intentions.

**Comment by simurai** [comment]
I think it's pretty hard to tell what the default should be. Personally I keep changing it with `cmd +/-` depending if I'm on a small laptop or large screen in the office.

My vote is to keep it at `14px`.

**Comment by izuzak** [comment]
> I think it's pretty hard to tell what the default should be. Personally I keep changing it with cmd +/- depending if I'm on a small laptop or large screen in the office.

I agree that it's hard to say what the default should be, and it's so easy to change the size that this shouldn't be a problem for most users really. Mine is at 16px :older_man:, for example.

> My vote is to keep it at 14px.

:+1: My vote would be to keep it as it is as well, so I'm going to close this for now. @benklebe -- thanks for taking the time to open an issue and ask about this. If we receive more feedback about the default size -- we can always reopen. I'll try to point users to comment on this issue if I notice such feedback so that we can collect everything in one place.
