### ISSUE TITLE
selection error

### ISSUE THREAD

**Issue by calidion** [atom/atom#8647]
<div class="alert alert-info" role="alert">...</div>

double click "..." will select "\">...</"
not just "..."

**Comment by mnquintana** [comment]
Can you give some sample text where you see this behavior?

**Comment by calidion** [comment]
@mnquintana 
I have given the sample text.
if the context is `...`, when you click `...` in side an html file. the `>` and `<` characters will be selected too, which should be ignored.

condition:
1. html file
2. only characters like `...,.&*^%$#@!`
3. click these characters will select `>` or/and `<` round html tag.

```html
<h1>...</h1>   //`>...</` will be selected
```

**Comment by 50Wliu** [comment]
It's selecting `>...</` for me, which I guess is technically correct because all of those are non-word characters?

**Comment by calidion** [comment]
@50Wliu 
it is correct for none html files.
but not for html files!

**Comment by villermen** [comment]
@calidion I believe this is the expected behavior. The dot character `.` is also defined as a non-word character in the default settings for the `language-html` package. Double clicking on a character string with only non-word characters should either select the entire string, or only the clicked on character. Neither is probably what you are expecting.

**Comment by 50Wliu** [comment]
Yeah, this is the correct behavior for Atom, but it can definitely be improved for language-html.
Please open a new issue on that repository.
