### ISSUE TITLE
Delete behavior of nested brackets.

### ISSUE THREAD

**Issue by scv119** [atom/atom#8655]
If I delete a pair nested brackets, the behavior seems strange:

Repo...
Write this...
```
(foo())
```
Place the cursor
```
(foo()|)
```
Press backspace
```
(foo(|)
```
Press backspace
```
(foo|
```
Hmmm!!! Most likely not the intended behavior.

**Comment by izuzak** [comment]
@scv119 Can you be more precise about which step exactly in the list of steps you provide is not expected? If you're referring to the last step, then I believe that's expected because of the [bracket matcher package](https://github.com/atom/bracket-matcher) which is included with Atom. If you disable that package and restart Atom -- you will see that the behavior is different. 

I'm going to close this, but if you still feel this is a problem -- please open a new issue on the bracket matcher's issue tracker and provide more details about what exactly you think is problematic and clarify which behavior you expected instead. Thanks!
