### ISSUE TITLE
Support external tokenizers

### ISSUE THREAD

**Issue by jpsim** [atom/atom#8669]
Formalizing [this forum question](https://discuss.atom.io/t/custom-grammar-based-on-external-tokenizer/19537) as a feature request here. Some languages don't lend themselves very well to regex-based grammars, and there are several languages out there that expose their tokenizers.

I'd love if Atom supported syntax highlighting based on external tokenizers. It would allow, for example, highlighting Swift code using the same mechanism Xcode uses (see https://github.com/jpsim/SourceKitten#syntax).

**Comment by mehcode** [comment]
:+1: A thousand times.

---

I work on my own [language](https://github.com/arrowlang/arrow) and updating the relevant syntax package feels like a lot of duplicated work.

Furthermore the regex-based grammar doesn't work very well as @jpsim said for many languages (which currently have inaccurate highlighting or outright bugs because of this).

**Comment by p-e-w** [comment]
https://github.com/p-e-w/language-javascript-semantic requires this in order to work. I'm getting tired of adapting the code to match Atom's ever-changing internal line representations. There should be a public API for connecting arbitrary tokenizers that are simply JavaScript functions.

**Comment by hedefalk** [comment]
+1. 

We have the need for this in the Ensime Scala plugin as well. https://atom.io/packages/ensime. Here is my forum question for reference: https://discuss.atom.io/t/marker-decorations-that-add-style-classes-to-the-actual-text-nodes/20254

The Ensime backend already supports semantic highlighting of Scala source but I can't find a way to leverage this without a programmatic async api.

**Comment by kpmeen** [comment]
+1

**Comment by nightscape** [comment]
:+1:

**Comment by jurStv** [comment]
+1

**Comment by maxbrunsfeld** [comment]
/cc @bolinfest - I know you were interested in using this kind of an API, but for Flow. Maybe you could share some of you thoughts here on how the API could work.

One thought about this: I think it would be awesome to eventually add this kind of feature, to enable packages like `ensime` and `flow` to provide IDE-like semantic highlighting (e.g. indicating unused variables or imports, or distinguishing constants from variables). That said, I don't think that this feature will help to address the *performance* problems of Atom's parsing, at least not in a general way.

The reason is that we will always need to provide at least basic syntax highlighting *synchronously*. If you type the word `if`, and 300ms later after you've already moved the cursor, the `if` turns yellow, that's not a good user experience. Syntax information that is obtained from external compilers via child processes or some kind of RPC is never going to be available quickly enough for synchronous syntax highlighting. IDEs like JetBrains, for example, perform tokenization synchronously, even though they do parsing and semantic analysis asynchronously.

Now for some languages, there may be a parser that we could call synchronously from javascript, but it would need to support things like nested languages (e.g. JavaScript within HTML within Markdown), this limits the number of languages that we could apply this technique to pretty severely.

Anyway, I may be missing something here, but it seems like we need to view this as enabling cool IDE features *on top of* Atom's built-in highlighting, not replacing it.

**Comment by jordwalke** [comment]
We would definitely be interested in this. There are things that are just very difficult to do without proper language tooling to actually parse and understand the grammar. We would still like the current Atom highlighting convention for "recovered" regions that our tooling detected invalid parses for, but for the large portion of the buffer that is a *valid* parse, we can provide a much more accurate highlighting (and furthermore we can do it much faster with `yacc` generated parsers). Our tooling would be capable of telling Atom exactly which regions of text should be highlighted using which token class, and we can tell Atom exactly which regions of text we were not able to parse at all (and should therefore fall back to some much less accurate (but easy to build) Atom specific interactive tokenizing).

**Comment by pmlodawski** [comment]
Anything new on this topic?

**Comment by laughedelic** [comment]
I'm not sure if the [tree-sitter introduction](http://blog.atom.io/2018/03/15/atom-1-25.html#improved-syntax-highlighting-and-code-folding) solves this issue, but anyway it's better not to close it without a triage.
