### ISSUE TITLE
Atom forgets the syntax coloring in Makefiles...

### ISSUE THREAD

**Issue by Wafflespeanut** [atom/atom#8722]
In a makefile, it's perfectly okay to have rules like this:

``` makefile
all:
	make TEMP

clean:
	rm -f TEMP

```

But, Atom was able to interpret only the first rule, as you can see here. The following ones are simply displayed as text.

![shot](https://cloud.githubusercontent.com/assets/6691262/9754610/9cf1209e-56e8-11e5-819a-4a348bdbf1e2.png)

**OS**: Ubuntu 14.04 (x64)
**Atom version:** 1.0.0

**Comment by mnquintana** [comment]
You're running a very old version of Atom - please update to the latest version (1.0.11), as this should be fixed in the latest version.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Comment by Wafflespeanut** [comment]
Atom often asks me to update my packages. Too bad that it doesn't ask me to update itself *(sigh)*. And, sorry about that...
