### ISSUE TITLE
Atom doesn't use gtk3 file dialog on Gnome 3

### ISSUE THREAD

**Issue by kostich** [atom/atom#8729]
Fedora 22 Workstation. Atom 1.0.11.

When opening or "saving as" a file, Atom uses gtk2 file dialog instead of using modern, gtk3 file dialog.

How currently Atom file open dialog looks:
![atom-gtk2-file-open-dialog](https://cloud.githubusercontent.com/assets/4953862/9760654/5b00662c-56f7-11e5-9357-e8939e5bf4f6.png)

How it could look if Atom was using gtk3 file open dialog window:
![atom-gtk3-file-open-dialog](https://cloud.githubusercontent.com/assets/4953862/9760663/6db8ba4e-56f7-11e5-9cb9-05c51f5a01f5.png)

**Comment by strelec** [comment]
Electron really should move to GTK3. Until then, there is no proper theming, no wayland support and outdated open file dialogs.

https://github.com/atom/atom/pull/4602
https://github.com/atom/electron/issues/765

**Comment by marcoms** [comment]
The officiale `electron` package in Arch Linux is built with Gtk3 enabled as far as I can tell -- https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/electron

![screenshot from 2017-06-29 15-01-46](https://user-images.githubusercontent.com/4211302/27691556-4482eaa4-5cdc-11e7-87e7-bb33c3363797.png)

Would be great if this was enabled by default...

**Comment by daviwil** [comment]
Stalebot just brought this to my attention.  Looks like Electron 2.0 fixed this for Atom 1.28.0+ by moving to GTK 3!

**Comment by onmeac** [comment]
This change has caused Atom to not be able to open from "networked" locations (e.g. smb/sftp) any more.

how it used to be:
![screenshot from 2018-07-16 22-32-05](https://user-images.githubusercontent.com/11853972/42782680-e4743758-8949-11e8-8538-fcd562aa81ec.png)

now:
![screenshot from 2018-07-16 22-28-01](https://user-images.githubusercontent.com/11853972/42782684-e8dc1022-8949-11e8-9131-ef177a937f30.png)


"other locations" with open file/folder in Atom
![screenshot from 2018-07-16 22-42-39](https://user-images.githubusercontent.com/11853972/42782693-eeef4d94-8949-11e8-9f19-f685ecb84eb3.png)

default gnome3/gtk3 "other locations"
![screenshot from 2018-07-16 22-46-22](https://user-images.githubusercontent.com/11853972/42782739-13385fec-894a-11e8-9622-4c1bff868c1c.png)

**Comment by kostich** [comment]
@onmeac, you can connect to your network location and then add it to bookmarks, to have it available in the sidebar.

**Comment by daviwil** [comment]
@onmeac It appears that you don't see networked file locations because Electron does not set GtkFileChooser's `local_only` option to `false`.  In [this file](https://github.com/electron/electron/blob/master/atom/browser/ui/file_dialog_gtk.cc) there is no reference to the [`gtk_file_chooser_set_local_only`](https://developer.gnome.org/gtk3/stable/GtkFileChooser.html#gtk-file-chooser-set-local-only) method so we can assume that the `local_only` option will be set to `TRUE`, preventing you from getting the networked file locations.

I'd recommend filing an issue against Electron to add an option to their API so that Electron apps can provide this features to users on Linux.  Thanks!
