### ISSUE TITLE
Remember code folding

### ISSUE THREAD

**Issue by jerone** [atom/atom#8764]
It would be great if Atom could remember code folding / collapse when a file closes and restored when reopened. 

I know Visual Studio supports this.

Ref: https://discuss.atom.io/t/remembering-collapse-expand-location-after-file-reopening/18155

**Comment by masavini** [comment]
confirm, it would be great!!

**Comment by RB-Lab** [comment]
+1! Brackets and WebStorm also support this.

**Comment by socketubs** [comment]
Nice feature ! :+1:

**Comment by dayAlone** [comment]
+1 It will be great!

**Comment by ianwesterfield** [comment]
:+1: 

Yup, this would be awesome for sure.

**Comment by Arcanemagus** [comment]
This is even more obvious with the better session state restore introduced recently. Files are being scrolled to the same scroll percentage that they were at before it seems, but since the code is no longer folded in the same manner it ends up being essentially a random position within the file on re-open of Atom.

**Comment by as-cii** [comment]
#11414 is going to enable persisting folds across Atom sessions: that is, if you quit the editor with a folded file open, it will restore it along with its folded regions. 

From what I understand, however, this issue is more about always remembering folds when a file is closed, and restore them when reopening it either in the same Atom session or in a future one. @jerone @dayAlone @ianwesterfield: is that correct?

**Comment by jerone** [comment]
> this issue is more about always remembering folds when a file is closed, and restore them when reopening it either in the same Atom session or in a future one. @jerone ..: is that correct?

For me that's correct. If code folding is only remembered when closing Atom, I always have to have the file open for it to keep remembering it folds.
