### ISSUE TITLE
Atom not visible under "Other programs" in order to "open with" or set as default in Ubuntu

### ISSUE THREAD

**Issue by ar-jan** [atom/atom#8781]
I installed the latest Atom 1.0.11 on Ubuntu 14.04 by opening atom-amd64.deb in Ubuntu's software center and installing from there. Next, when right-clicking a plain text file, Atom is not listed for "Open with", nor is it listed under "Other applications". This means it also wasn't possible to set it as the default program for .txt.

Adding `%f` at the end of the line `Exec=/usr/share/atom/atom ...` in ~/.local/share/applications/atom.desktop made Atom available in the `Open with` menu/tab. (not sure if this is Ubuntu-specific).

**Comment by ricardograca** [comment]
I'm using Ubuntu 15.04 with Atom 1.0.19 and I don't have any `atom.desktop` file under `~/.local/share/applications` and in my case Atom is listed in "Open with" and "Other applications". However I did install Atom for the first time a long time ago (version 0.17x maybe?)

**Comment by malakgeorge** [comment]
i had the same problem with Ubuntu 15.10. I fixed this problem using your solution.

**Comment by xasx** [comment]
Under Fedora, I cannot see Atom in the selection of a e.g. folder's OpenWith/All Applications list either.

In `atom.desktop` I find:
```
Exec=/usr/share/atom/atom %U
```

According to the desktop entry specification
> `%U`: A list of URLs. Each URL is passed as a separate argument to the executable program. Local files may either be passed as file: _URLs or as file path_.

I guess this is at the end a problem with the OpenWith dialog not recognizing such applications (desktop files) since - from how I understand what is written in the spec - the `%U` Exec entries could be handled just in the same way as the `%f`s.

The relation is somehow `%U` &sup; `%u` and `%F` &sup; `%f` and `%U` &sup; `%F`, conclusively `%U` &sup; `%f`; which means that each entry that can handle `%U` should also be able to handle `%f` - or am I wrong?

**Comment by OlivierBondu** [comment]
Same here with Atom 1.6.1 under Ubuntu 15.10, also corrected using the fix proposed in the initial report

also, in `atom.desktop` the `Name` entry seemed a bit random, namely: ```Name=untitled — /home/some(semi-?)randompath — Atom```

**Comment by gokhansolak** [comment]
I'm on Ubuntu 14.04, adding %f or %F didn't solve the issue for me. 

Tried many things with Desktop Entry: Adding removing properties, changing Exec to 'atom %F' (without path), adding MimeType of the file type I'm interested in, changing the Name to 'Atom1' (to avoid a possible collusion), and other minor changes. With and without %F or %U. None has worked.

I work with sudo, so file is saved properly.

**Comment by daltonmenezes** [comment]
Same here. :(
