### ISSUE TITLE
Snippet auto complete disappears at last character

### ISSUE THREAD

**Issue by atilkan** [atom/atom#8784]
I discovered this strange thing. I am on Ubuntu.
I created a snippet for "public function" with the prefix "pufu". When i type "puf" auto complete appears fine. But if i type all prefix like "pufu" auto complete window disappears. 
![screenshot from 2015-09-14 18 40 24](https://cloud.githubusercontent.com/assets/1254613/9854480/b173d9c6-5b11-11e5-9c1c-7a2b37a1548c.png)
I am aware if i type pufu and hit tab it works.

This is expected for complete code but in snippets this should work differently.
For example: if i type "function" i don't need to see it since i already typed all. But hey just tested it, it appears. I already typed all.
![screenshot from 2015-09-14 18 58 06](https://cloud.githubusercontent.com/assets/1254613/9854651/8dd9a74c-5b12-11e5-9122-ece4026b8a0d.png)

There needs to be a switch.

Since you may ask, here is my snippet.
![screenshot from 2015-09-14 19 03 29](https://cloud.githubusercontent.com/assets/1254613/9854800/511dac80-5b13-11e5-89da-bbfbf1b4c69f.png)

Edit: I found some more interesting things. if prefix is "pff" it works fine. I don't understand the logic there.

**Comment by MethodGrab** [comment]
@atilkan: I believe it only hides the autocomplete window when there are no other possible matches. The reason it doesn't hide the autocomplete for `function` is because there are still 2 other options available (shown in your screenshot) that match. I assume it's the same when you use `pff` as the prefix as it's less specific that `pufu` so there are other autocomplete options that match `pff`.

I agree though that it would be better to keep the autocomplete window visible until the snippet is expanded.

**Comment by benogle** [comment]
A lot of people are tripping on this. I will change it back to show when there is only one match.

**Comment by atilkan** [comment]
@MethodGrab Yes, i understand better now. Thanks.

**Comment by atilkan** [comment]
@benogle It should work different for snippets and keywords. If you do as you say, it is not the ideal  solution.

**Comment by benogle** [comment]
This is fixed on master. It will be in the beta channel release on the release tomorrow.
