### ISSUE TITLE
Command Palette slow to load

### ISSUE THREAD

**Issue by alex-ketch** [atom/atom#8960]
Triggering the command palette takes almost a second to appear after triggering the command using the default keyboard shortcut. It is twice, almost three times, slower than the similar _Open File_ panel.
It's slow enough to be a friction point in the workflow, and I haven't seen this being mentioned either in the Issues or on the forum.
This happens even when launching Atom in safe mode using the terminal.

I recorded Dev tools event timeline and saved the data if that helps.
https://gist.github.com/alex-ketch/0dd5d224f95b299c89f7

<img width="945" alt="atom - screen shot" src="https://cloud.githubusercontent.com/assets/1646307/10120212/9c233a62-64a8-11e5-900d-79cad3510c6a.png">

Atom 1.0.19, but the issue has been present before this.
MacBook Pro (2012), 2.7 GHz Intel Core i7, 16GB RAM
Running Yosemite 10.10.5

Is there any more data points I can provide that would be useful?

**Comment by jordwalke** [comment]
I notice the command palette is too slow as well (and my colleagues have also noticed this). Why is this slower than the file search modal?

**Comment by jordwalke** [comment]
I just did some basic profiling and it looks like there's a ton of time spent in jQuery - I measured the bottom up time and sorted by "self", and jQuery internals were at the top of the list.

**Comment by dktn** [comment]
Same issue here, Atom 1.9.8 and Command Palette showing up very slowly. In ST3 it is showing immediately in the same machine (MBP i7, 16GB).

**Comment by jordwalke** [comment]
This seems like a pretty high leverage fix. It's one of those things that makes people immediately dismiss Atom, even when the rest of the editing experience is pretty snappy.

**Comment by MoritzKn** [comment]
1. I think this issue belongs in the [atom/command-palette repo](https://github.com/atom/command-palette/)
2. I've also noticed that the command palette was a bit slow previusly but can't reproduce it anymore
3. I think this was fixed by [this](https://github.com/atom/command-palette/commit/7fd74416175ff73fe55fe82c22d85c6228ab0586#diff-029fe0d9da522daa27b556a694420c65L104) change. Since then jQuery isn't even used any more and this  heavy looking call has been removed: `$(':focus')`

So I think the issue is resolved and can be closed.
