### ISSUE TITLE
Emojis count as two characters

### ISSUE THREAD

**Issue by danieldiekmeier** [atom/atom#8974]
Expected behaviour: Emojis should only be counted as one character, to make counting easier. As you can see from the screenshot, Atom claims the cursor to be at position 1:5, even though it's at 1:3.

![screen shot 2015-09-28 at 14 44 49](https://cloud.githubusercontent.com/assets/2098462/10135611/ab3bfd16-65ef-11e5-8ac1-1c6f81a60364.png)

**Comment by kevinsimper** [comment]
It is because emoji's are 2 bytes, so I think this will never change as it in fact does take up 2 chars.

**Comment by freebroccolo** [comment]
@kevinsimper ideally the editor should not be counting position with respect to bytes but instead be counting with respect to graphemes. Of course, it is more complicated and potentially more expensive. However, since the navigation commands seem to work with respect to graphemes, and most lines are not that long, I don't see why this can't be done properly.

**Comment by danieldiekmeier** [comment]
This is probably related: http://blog.jonnew.com/posts/poo-dot-length-equals-two

**Comment by revelt** [comment]
@danieldiekmeier I kindly disagree with "to make counting easier". I've created quite few string processing libraries and when I work on unit tests I need to measure where the particular character (incl. emoji) is at the moment. For perf reasons I like to iterate through string using `for` loop (instead of separating it by character/emoji into array). This means, the index system I have to use is always native JS-one, where emoji is 2 characters length. This means, I need Atom status bar to show **real native indexes**.

Having said that, I dislike when people come in and deny the whole existence of my raised issues. I thought about your request and it's perfectly valid. Actually, if such feature was available I'd make use of it too.

### As a middle-ground solution, what if we output both per-index and per-grapheme counts in status bar?

For example:

<img width="295" alt="screen shot 2018-03-09 at 06 53 48" src="https://user-images.githubusercontent.com/8344688/37194806-dfcfa770-2367-11e8-8db6-d790a32d82af.png">

First number (`1` in mockup above) — selection's line count
Second number (`17` in mockup above) — selection's indexes total count
Third number (`15*` in mockup above) — selection's **grapheme total count**

All parties would be happy?

I would use the status bar **selection** report to show the count rather than status bar's **main index** (`98:22` in my screenshot) because selection's characters appear only by request and therefore would hog less resources compared to `98:22` that are shown all the time.

Additionally, by definition, selection is less than or equal to the whole file's contents, which means, there's a high chance that selection will be smaller than "everything", therefore, more performant compared to if we calculated the grapheme count of "everything". @freebroccolo perf point is very relevant. This grapheme count will consume resources. Atom is not the fastest editor ever and we should not make it worse.

What do you guys think?

**Comment by danieldiekmeier** [comment]
Yes, this is still happening, but I'm pretty whatever about it. I don't use Atom anymore (this was not the reason), so I'll close this issue, and if anybody still sees it, they can open another one!
