### ISSUE TITLE
Non-responsive editor due to regex deletes unsaved changes

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#9020]
Atom claims to preserve unsaved changes, yet this is repeatedly, frustratingly, proven false.

Steps to reproduce on vanilla Atom:

1. Open an important file, make important changes, do not save them.
2. Open a large text file, ≈ 500000 lines ASCII text, obtained from your client.
3. Open Find/Replace and type a regex that will hang Atom's engine, like `foo_bar_baz|` (notice the port accidentally typed at the end)
4. Atom stops responding.
5. Close window, and reopen.
6. Unsaved changes are lost.

Work should not be performed on the GUI thread, period. This is why.

**Comment by jeancroy** [comment]
This exist because pattern `foo_bar_baz|` allow zero length match.
Also regex engine place a zero length match before every char.

I'm not sure what's the state of multi threading in JavaScript so I'm going to search for something else.

The fundamental question then become: does atom crash inside the regex engine or while trying to display the results?

 If it's a the display stage, we should try to make to make 0 length match as inexpensive as possible. There was a 'recent' [commit](https://github.com/atom/find-and-replace/commit/9082bc451acf2004696ea3db236918ba2e90e516) on that topic, so maybe your version number is important. 

If the regex engine by itself crash, a solution could be to do the search in batch, a bit like atom/scandal [does](https://github.com/atom/scandal/blob/master/src/chunked-line-reader.coffee) in the 'Find in files' functionality, but for buffer in memory.

Until then a patch could be used to disable re search on large buffer, warn if pattern can match empty string or a combination of those. I'm assuming your file is in the 50-100 MB range ?

**Comment by benogle** [comment]
This is basically https://github.com/atom/find-and-replace/issues/145, which @nathansobo is working on. The goal is to make any amount of results fast on any size file. Nathan has ideas, and they are in progress.

**Comment by jeancroy** [comment]
It's good to know there's work on this.

In addition to efficient data structure effort, there's a few pointer I wish to contribute.

- People make mistake, there's little point at being performant to display half a million result when user expect half a dozen. This is even more important when there's search as you type.

- Internal regex engine might be a failure point with little to control except limit input size.

**Comment by nathansobo** [comment]
> there's little point at being performant to display half a million result when user expect half a dozen

Yeah, we've realized we're never going to be able to create markers for every result. There's just too much overhead and it's not worth it. We're going start on a new API, hopefully next week, that lets packages create "decoration layers" that just do work to return decorations that are visible on screen, and get called when the visible range changes.

**Comment by alexchandel** [comment]
> I'm assuming your file is in the 50-100 MB range ?

Actually 7.9M. And I agree, a zero-length, unconditionally true match should cost nothing.

@benogle  Please reopen, atom/find-and-replace#145 is only about 1/3 of this issue. There are two other problems that I haven't seen directly expressed elsewhere:

1. Find-and-replace hung the GUI thread. This just shouldn't be possible. Work should happen elsewhere in a non-blocking context. I don't care as much if F&R crashes; I care a great deal when my GUI hangs.
2. WORK WAS LOST (due to a purported background task hanging the GUI). What happened to preserving unsaved changes? That issue has been closed for a while.

**Comment by jeancroy** [comment]
Decided to open related issue https://github.com/atom/find-and-replace/issues/557 
Mostly because it's easy to reproduce and there's no clever way that I know of to side step making search in a new thread.
