### ISSUE TITLE
"Go to Declaration" menu option not working

### ISSUE THREAD

**Issue by eskinderg** [atom/atom#9034]
"Go to Declaration" menu option not working

**Comment by izuzak** [comment]
That option is provided by the Symbols View package: https://github.com/atom/symbols-view.

I recommend you read [the guidelines for submitting issues](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and re-open the issue on that package's issue tracker with more information. Also, make sure you read the README for that package https://github.com/atom/symbols-view and also these two issues: https://github.com/atom/symbols-view/issues/20 + https://github.com/atom/symbols-view/issues/9 (because they might be describing your problem as well, so no need to open a new issue).
