### ISSUE TITLE
Keybinding triggering when not calledK

### ISSUE THREAD

**Issue by cymruu** [atom/atom#9043]
![image](https://cloud.githubusercontent.com/assets/2981598/10267514/a93df8e6-6a97-11e5-98e1-6329b5e1b480.png)

Hello guys, this keybing is triggered on alt-o. Why? It's supposed to be like this?

Win 8.1
Atom v1.0.19

**Comment by izuzak** [comment]
Your screenshot shows the Keybindings panel of the Settings view, and when you use search on that panel you get a list of keystrokes which include `alt-o`, not which are triggered by `alt-o`. Specifically, `application:add-project-folder` is [triggered by `ctrl-alt-o`](https://github.com/atom/atom/blob/4b507be99769a38e0b8e9b26a950fc408951f986/keymaps/win32.cson#L20), not `alt-o`.

The keybinding resolver will show you which command is triggered when you hit a keystroke:

https://github.com/atom/keybinding-resolver#keybinding-resolver-package-

If I misunderstood your question, please provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and provide exact steps which reproduce the problem and explain what the problem is exactly. Thanks!
