### ISSUE TITLE
Allow grammar to override suggestedIndentForTokenizedLineAtBufferRow

### ISSUE THREAD

**Issue by patrys** [atom/atom#9059]
This would allow languages like Python to provide proper indentation. Current regex approach is not enough to provide proper PEP8 indentation:

``` python
foo = [
    'one', 'two']

bar = ['three',
       'four']


def bazzzz(
        param1,
        param2):
    pass


def icanhaz(bacon,
            cheezburger):
    pass
```

**Comment by radix** [comment]
Just in case it's not clear, the `def baz` example there may be a little bit misleading. The `param1` and `param2` aren't intended to be aligned to the open-paren in `baz(`, but rather just indented an extra level so as to be visually distinct from the body of the function. The example may be unclear/ambiguous because `baz(` happens to have 4 characters in it.

Another less ambiguous example would be:

```python
def bazaz(
        param1,
        param2):
    pass
```

**Comment by patrys** [comment]
I came up with the idea of implementing a separate grammar setting similar to Sublime's [`indent_to_bracket`](https://www.sublimetext.com/docs/2/indentation.html) but have hit another problem:

Atom's indentation rules only allow to set indentation in multiplies of the current tab width.
