### ISSUE TITLE
View → Reset Font Size

### ISSUE THREAD

**Issue by ircer** [atom/atom#9060]
Clicking on `View → Reset Font Size` changes the font back to the previous font size.

Shouldn't this reset the font size back to the standard font size which is how other text editors (Notepad++ for example) work?

**Comment by izuzak** [comment]
What exactly do you mean by "previous font size"? Can you share the exact steps which reproduce this problem for you?

The expected behavior is that the font size is re-set to the value which was set at window startup: https://github.com/atom/atom/pull/6539. As far as I can tell, this is the current behavior. 

From that pull request:

> This is, I think, far more useful behavior than restoring Atom's default font size, which you can do by just emptying the Font Size input in Settings View. If you've ever had to change the font size to make code more readable to others temporarily (ie. a presentation or a talk), having a command to return to what you had configured originally is a godsend. (I've found myself in that situation quite often.)

**Comment by mnquintana** [comment]
Sorry this has been confusing, but this was an intentional departure from other editors' behavior. 

The idea is this - not everyone likes the default font size (and maybe it doesn't even work well with your chosen font - Inconsolata for instance has a really small x-height, so you usually need to set it with larger font sizes for it to even be legible), so having a command to "reset" to that default can be rather useless. Instead, Reset Font Size here works analogously to how `Actual Size` works in Chrome and OS X's Terminal (and many other apps), resetting it to *your own* configured font size instead of Atom's default. There is no one-size-fits-all "standard" font size for editors - it should only be whatever your preference is.

**Comment by ircer** [comment]
@mnquintana it's just confusing that's all.

I started with the standard font size, then pressed CTRL + a couple of times, then later on I wanted to go back to the standard so I used that menu option, which just basically done a CTRL -, it took it down a notch.

So I ended up having to fiddle around with some config option and remove it, very strange behavior. There's a reason other text editors do it the way they do, I guess!
