### ISSUE TITLE
Inheriting from an existing grammar but excluding features on purpose

### ISSUE THREAD

**Issue by IngwiePhoenix** [atom/atom#9064]
I am trying to build up a grammar spec for AngelScript. AngelScript is heavily based on C++, so I want to add and remove specific features from C++. However, since the `#`-Macros are defined in both, C and C++, i would like to exclude these definitions alltogether. How do I do it? I tried to use an exclude statement - at least I gave it a try - but it di dnot do a thing.

What is to be done or is this even implemented?

Thanks!

**Comment by mjansing** [comment]
I'm also interested in a solution. Is there a way to inherit from an existing grammar definition (in the same package)`?

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
