### ISSUE TITLE
Allow package install/removal from command pallet

### ISSUE THREAD

**Issue by danielmelogpi** [atom/atom#9072]
Hello, everyone

This is supposed to be marked as a feature idea.
 There is a feature in Sublime that simplifies plugin/package management very much and I often find myself trying to use on atom: to use the command pallete to remove packages.
In fact, in sublime you can also do the installation process via the pallete. The pallete is able to unfold into  "submenus/suboptions" to be acessed from there.
I'd like this also in atom, if it can be considered. I'm also considering developing a plugin for that, but as I'm so out of time these days I decided to share the idea here.
Thanks a bunch for the editor. Web tech FTW

**Comment by arcticicestudio** [comment]
This sounds more like a good idea for a package instead of a core functionality.
Atom provides a way of installing packages CLI-based without using the GUI via the bundled [apm](https://github.com/atom/apm).

Example: `apm install northem-atom-syntax`
Check out all commands & options by using `apm --help`

**Comment by izuzak** [comment]
Thanks for the feedback -- there's already an issue for tracking that feature request: https://github.com/atom/command-palette/issues/53.
