### ISSUE TITLE
On Mac, binding anything to ctrl-/ produces a "whump" sound

### ISSUE THREAD

**Issue by artagnon** [atom/atom#9075]
I noticed it first in atomic-emacs triggering core:undo, but after some small experiments, it looks like the problem is in Atom.

**Comment by izuzak** [comment]
Thanks for the report. I'm pretty sure this is another instance of this issue: https://github.com/atom/electron/issues/2617 which is tracked in Atom here https://github.com/atom/atom/issues/1669 (for the `ctrl-cmd-down` combo). Can you add a comment to those issues so that we keep things in one place? 

I just tried `ctrl-/` in Chrome, and it produces a sound as well.
