### ISSUE TITLE
Tab Type "auto" overrides Soft Tabs setting.

### ISSUE THREAD

**Issue by rayfoss** [atom/atom#9098]
1. I should be able to make the tab button make tabs by disabling the Soft Tabs setting.
2. Tab Type "auto" should apply to "Auto Indent" when pressing enter after an indented line.

I think the only solution is to have a drop down for Soft Tabs, "Always", "Same as Tab Type" and "Never"

That would make Atom more usable with mixed language/mixed tab style files. Currently the best workaround is to Tab Type: "Hard" and Soft Tabs: "off" which will make Auto Indent create hard tabs on soft tabs documents.

**Comment by blainsmith** [comment]
Not to beat a dead horse evem more, but it would be nice if these settings were a littler clearer on what combinations of these do what. I have gotten into the habit of making a `.editorconfig` file in projects now since that makes it easier to understand and using https://atom.io/packages/editorconfig, however it makes working with other people's open source projects a nightmare when they don't have an `.editorconfig`. Atom seems to always set the `tabLength: 4` regardless of what I set it in Settings.

**Comment by thomasjo** [comment]
> Not to beat a dead horse evem more, but it would be nice if these settings were a littler clearer on what combinations of these do what.

That is being adressed in #9096.

**Comment by Reyncor** [comment]
![screenshot from 2015-10-10 12-02-34](https://cloud.githubusercontent.com/assets/876076/10412051/c1fd3c20-6f47-11e5-8aed-6847c0be381c.png)

I would love something like this next to LF... I'm sure Gedit wouldn't mind.
