### ISSUE TITLE
Indent guides malformed

### ISSUE THREAD

**Issue by bobrocke** [atom/atom#9115]
![www br dev - atom](https://cloud.githubusercontent.com/assets/2962426/10420057/e96d830e-7056-11e5-9c83-b0e6e7284e41.jpg)

**Comment by thomasjo** [comment]
Looks like you're using a invisible character marker for `space` that is wider than 1 character. What character are you using, and which font?

**Comment by bobrocke** [comment]
My marker is a KATAKANA MIDDLE DOT (`・`) from the Hack font. It's only 1 character, but it seems that Atom doesn't like it. If I switch to a `.` then the indent guides line up properly.

**Comment by thomasjo** [comment]
> My marker is a KATAKANA MIDDLE DOT (・) from the Hack font

That's a double-width character. If you want to use the Katakana (Japanese) mid dot, consider using the *HALFWIDTH KATAKANA MIDDLE DOT* instead. 

---
Note: I'm not entirely sure about this, but I believe your specific issue might be (at least partially) fixed after #8811 ships. /cc @as-cii.

**Comment by bobrocke** [comment]
I tried the halfwidth and it messed up the indention guides in the opposite way. :)

So I switched to the regular bullet and it works fine. But I wonder if it shows something that needs a solution in Atom?

I'll keep an eye out for https://github.com/atom/atom/pull/8811.

**Comment by as-cii** [comment]
Unfortunately I don't think #8811 will actually solve this, as the problem here lies in the space character not occupying the same width as _KATAKANA MIDDLE DOT_. 

So long as the character widths are not the same, indent guides will be misplaced: I feel like this might be considered a _bug_ in the existing implementation, as we assume that those characters have the same width when constructing the empty line guides. A better solution would probably read how large an indent guide is and set the related empty line `<span>`s' widths accordingly.

@bobrocke: thank you for reporting this issue. Fixing this should be pretty straightforward and I'll take a look at it in the future, but as a temporary workaround you could replace that character with one that has the same width as the space char. I'll definitely ping you as soon as we start working on a fix for this. :+1:

**Comment by burodepeper** [comment]
@chrissimpkins Could you check if the character mentioned might have the wrong width set in Hack?

**Comment by chrissimpkins** [comment]
I can confirm that we do not have a Katakana middle dot glyph (U+30FB) in the regular Hack font.  There is a middle dot (U+00B7) that will have the appearance that you are after here.  I can confirm that the U+00B7 glyph has the same fixed width spacing as the rest of the regular set (and all other variant sets).

<img width="446" alt="periodcentered" src="https://cloud.githubusercontent.com/assets/4249591/10548827/5fc4886a-740b-11e5-90ee-29c9e0ff305f.png">


Any chance that this glyph is coming from a fallback font if you are using the U+30FB character?

**Comment by dahjelle** [comment]
Another situation in which this occurs is using a proportionally-spaced font for editing.
