### ISSUE TITLE
Fix preview tabs

### ISSUE THREAD

**Issue by benogle** [atom/atom#9165]
_From @benogle on October 15, 2015 22:46_

There have been a lot of issues created related to preview tabs. It seems like nearly all of these issues could be solved by a couple things:

1. Create all tabs as 'permanent' by default and only open in a preview tab in a couple cases:
  * Single clicking in the tree-view
  * Single clicking in project find results pane
  * And eventually (when open files is suuuper fast) opening preview tabs when arrowing through the fuzzy finder
2. Close the preview tab when it loses focus

The issues

* https://github.com/atom/tabs/issues/170
* https://github.com/atom/tabs/issues/206
* https://github.com/atom/tabs/issues/202
* https://github.com/atom/tabs/issues/196
* https://github.com/atom/tabs/issues/180
* https://github.com/atom/tabs/issues/173
* https://github.com/atom/tabs/issues/170
* https://github.com/atom/tabs/issues/164
* https://github.com/atom/tabs/issues/207
* https://github.com/atom/tabs/issues/163
* https://github.com/atom/fuzzy-finder/issues/108

## The short term approach

Currently preview-tabs is implemented entirely in the tabs package. When a new pane item is opened, the tabs package closes the old pane item associated with the preview tab, and creates a new tab. So atom core (or other packages) has no idea that there are preview tabs. This is kind of crappy as

* There are hacks in the tabs package to handle things like double clicking in the tree view to make a tab permanent.
* There is no way for other packages to open preview tabs, or even know about them without accessing the tabs package
* Along the same lines, a couple folks want an API, and the only way to provide an API would be to add a service or hack to the tabs package.
  * https://github.com/atom/tabs/issues/188
  * https://github.com/atom/tabs/issues/185

That said, we could probably do a quick fix to change the default behavior to open a 'permanent' tab, and hack the other packages to open preview tabs in the exceptions listed above.

## The long term approach

A cleaner and more robust approach would be to bake the notion of a preview pane item into atom core. Packages could then decide to open preview items if they so choose. Then there would be no hacks: tree-view and the find results could open a preview item on single click; tabs could watch for preview items and have them all share one tab element.

@nathansobo @maxbrunsfeld not sure how much effort this longer term approach would be. Can you estimate how long it would take to add a new option to `open()` indicating the notion of a preview pane-item + related events?

cc @atom/feedback

_Copied from original issue: atom/tabs#218_

**Comment by benogle** [comment]
Moved to core cause the API is a core concern, and this discussion touches packages other than tabs.

**Comment by nathansobo** [comment]
Probably wouldn't be a huge investment to add this API.

Here's my initial thoughts.

We add a new method, `Pane.prototype.previewItem`. When called, this method notifies `onDidAddItem` listeners with a new `preview` property on the event object set to true. The preview item is *removed* if the pane receives and then loses focus. The preview item is *replaced* if `previewItem` is called again with another item. The preview item "graduates" to a normal item if `addItem` is called with the same item or the item implements `onDidChangeModified` and its status changes to `true`.

We'll need to add a new event subscription method so packages can track when preview items become normal items. I'm still struggling with the name of this method.

* `onDidStopPreviewingItem` Did we stop previewing because the item got removed or because the item is done being previewed.
* `onDidMakeItemPermanent` I want a good verb instead "make" plus an adjective. Plus the item really isn't "permanent". It can be removed. It's just a bit more permanent than the preview item.
* `onDidConfirmPreviewItem` Vague verb.
* `onDidRatifyPreviewItem` Sounds like a trade agreement.
* `onDidGraduatePreviewItem`
* `onDidAdoptPreviewItem`

Someone come up with a better idea for a name. What happens when a preview item becomes a normal item. What's that called? What's the verb for that?

**Comment by billybonks** [comment]
`onPreviewItemSelected` preview item upgraded
`onPreviewItemOpened` changed preview item

**Comment by nathansobo** [comment]
Now I'm liking `onDidRetainPreviewedItem` to describe the moment where a preview item is converted into a regular item.

**Comment by billybonks** [comment]
I like the verb but prefer the present tense `onDidRetainPreviewItem` you cant retain it if you didn't preview it.

**Comment by adambuczynski** [comment]
Glad to see this being progressed. Has there been a definite decision on whether the "short term approach" is going to be implemented?

**Comment by nathansobo** [comment]
Adding these core APIs and using them in select bundled packages is pretty near term on the roadmap.

**Comment by adambuczynski** [comment]
Great, thanks

**Comment by paulpflug** [comment]
Why is it added to the pane? Is there a use case other than previewing in a texteditor?
This is what I would need:
```coffee
atom.workspace.observeTextEditors (editor) =>
  if editor.isPreview
    editor.onClearPreview -> #something
    editor.clearPreview()
```

**Comment by kuychaco** [comment]
> Create all tabs as 'permanent' by default and only open in a preview tab in a couple cases:
> - Single clicking in the tree-view
> - Single clicking in project find results pane

@benogle curious to know why you want single clicking in project find results pane to result in a preview tab. For comparison, Sublime simply opens a permanent tab for this case

**Comment by adambuczynski** [comment]
@kuychaco sometimes I search for some code that I have elsewhere, but unsure in what specific file. In that case it's useful to be able to use find in project files, open a preview tab, copy the code I need, and not have the file clutter my tabs. 

I also think it's nice to have consistency with the tree view, so single click = preview tab, double click = permanent tab. Once you get used to it, it should be good.

**Comment by benogle** [comment]
> @benogle curious to know why you want single clicking in project find results pane to result in a preview tab. For comparison, Sublime simply opens a permanent tab for this case

Basically it makes the most intuitive sense to me. My thinking is similar to @adambuczynski. I dont necessarily want to commit to opening the file I click on, just have a better look at the context, or copy some code.

I just checked sublime. Both 2 and 3 has a text interface that just selects the line when single clicking on an item or match (no open file for me) then opening the file as permanent on double click. I have a totally vanilla sublime install in both cases.

**Comment by acontreras89** [comment]
Can we know what the progress on this is? I see @kuychaco has been making these changes where needed. Are we missing something?

**Comment by nathansobo** [comment]
@kuychaco's improvements are in 1.5.x, which is on the beta channel as I write this. We're still not bringing up the preview in many circumstances because work is still in progress ensuring a reasonable upper time bound on that operation. When it's fast, we'll preview in more circumstances. @benogle do you think this can be closed for now and perhaps replaced with an issue addressing any remaining work?

**Comment by benogle** [comment]
Let's close it. The only bit that might come later is opening in preview mode when moving through the fuzzy finder, but we need to be faster at opening files before that can happen.

**Comment by benogle** [comment]
Thanks @kuychaco :tada:

**Comment by acontreras89** [comment]
Great work! :clap:

**Comment by adambuczynski** [comment]
Thanks everyone, I will download the beta to check it out.

**Comment by kuychaco** [comment]
Thanks :smile:

**Comment by adambuczynski** [comment]
@benogle I've downloaded 1.5.0, but noticed that files opened from fuzzy finder or external sources are still opened as temporary tabs. Was this fix not supposed to be in 1.5.0?

**Comment by benogle** [comment]
It'll be out in 1.6

**Comment by adambuczynski** [comment]
Bugger! Was so looking forward to it already :)
