### ISSUE TITLE
Window position not remembered on second screen

### ISSUE THREAD

**Issue by garu57** [atom/atom#9172]
Atom 1.0.19 and 1.1.0-beta1, MS Windows release.

How to reproduce:
1. launch Atom (ensure window is NOT maximized)
2. move window on second screen (i have it mapped on the left of main one) and resize it
3. Go to View > Reload
4. The window is reopened in the first screen with previous size and position

The same happen if on step 3, instead of reloading it, the window is closed and Atom relaunched.

If window is MAXIMIZED then the screen is remembered and window reopen in the screen it were in when reload was clicked or window was closed.

But, once reloaded or reopened, the size and position it had before maximizing is lost, if restore down is clicked, the window borders are pushed outside screen margins (the restored window becomes larger than the maximized one and larger than the screen view area).

**Comment by garu57** [comment]
See issue #7555 that describe a similar behavior for Mac release.

**Comment by mastazi** [comment]
The same issue also happens on a single screen, (which might reflect more closely a common usage pattern), the way to reproduce is the following:

1. Atom is open not maximized
2. Maximize
3. Close Atom
4. Reopen Atom: it is maximized
5. **The "Restore down" button is now useless**, because the window stays maximized: the position and size as per point 1 (see above) is not remembered. **If you skip point 2** (maximize) then the size and position **is remembered** when atom reopens.

I think this might be an Electron issue, not an Atom issue.
However I think Atom should follow Visual Studio Code's example (VS Code is also an Electron app) and set a default window size and position which is used in those cases the previous size is not remembered across sessions. At least, **with the VS Code behaviour, the "restore down" button is not made useless**.

**Comment by mastazi** [comment]
This part of the bug:

> But, once reloaded or reopened, the size and position it had before maximizing is lost, if restore down is clicked, the window borders are pushed outside screen margins (the restored window becomes larger than the maximized one and larger than the screen view area).

is still present in Atom 1.7.0 despite the Electron update. 
Using Windows 10 Pro, 64 bit.

**Comment by mastazi** [comment]
Actually the bug characteristic that I have referenced above is better described here:
https://github.com/atom/atom/issues/10720
