### ISSUE TITLE
Atom Editor Not Responding

### ISSUE THREAD

**Issue by erinjerri** [atom/atom#9185]
I checked my Utilities and it is taking up so much energy, I haven't been able to code in it for a while and keep having this error pop-up. 

![image](https://cloud.githubusercontent.com/assets/3184381/10555760/36e34652-7429-11e5-83d6-16c678e2a44a.png)

**Comment by ciechomke** [comment]
When editor is responding have you something like "input lag" when typing? Because I have similar issue on Linux - Editor takes much more resources than earlier, I can't type because editor has big input lag and switching between tabs takes more than 10 seconds. Maybe mine issue is related to yours.

**Comment by erinjerri** [comment]
I don't have that issue with input lag, it just won't load. =(

On Sat, Oct 17, 2015 at 3:05 AM, Paweł Ciechomski <notifications@github.com>
wrote:

> When editor is responding have you something like "input lag" when typing?
> Because I have similar issue on Linux - Editor takes much more resources
> than earlier, I can't type because editor has big input lag and switching
> between tabs takes more than 10 seconds. Maybe mine issue is related to
> yours.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/9185#issuecomment-148901530>.
>



-- 
Erin Jerri
http://www.erinjerri.com

**Comment by methodbox** [comment]
You should read over #3426 to see if your issue is related.

**Comment by nathansobo** [comment]
Can you try running `atom --safe` and seeing if this still happens?

**Comment by markgarrigan** [comment]
This happens to me about every 10 minutes maybe more after the first time it happens. I have no packages installed and nothing custom. It's a fresh install of atom. Atom 1.3.2. OS X 10.11.2

**Comment by kexoth** [comment]
I'm having the same issue, tried the advice in atom/issues/9185, to delete the uneccessary files from `~/.atom/storage`  but it appears again & again ..

**Comment by lee-dohm** [comment]
@erinjerri Are you still having this Issue? Did `atom --safe` help?

**Comment by lee-dohm** [comment]
For others, can you replicate the issue using `atom --safe`?

**Comment by kexoth** [comment]
Right now I'm using Atom with `--safe` flag & it's fine, but still, this shouldn't happen :disappointed:

**Comment by lee-dohm** [comment]
If the problem doesn't reproduce with `atom --safe` that means the issue is with a community package you have installed. Some people have had good luck with using the [package-cop package](https://atom.io/packages/package-cop) to track these problems down.

We all agree that this shouldn't happen and we're looking into ways to mitigate these kinds of problems with runaway packages. Until that time though, there are ways to track down the root cause and get the information to the package maintainers so they can fix the issue.

**Comment by sompylasar** [comment]
Looks related: #10378

**Comment by Alexniver** [comment]
https://github.com/atom/atom/issues/7581 this helps me work out. delete .atom/storage works for me

**Comment by Ben3eeE** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Comment by karankashyap** [comment]
atom --clear-window-state works!
From https://github.com/atom/atom/issues/12983#issuecomment-254006953
