### ISSUE TITLE
Scrollbar not getting styled correctly on Windows and Linux

### ISSUE THREAD

**Issue by Aakash1312** [atom/atom#9189]
I just pulled the master branch and got this odd looking scrollbar in UI. 
![screenshot from 2015-10-17 15 08 12](https://cloud.githubusercontent.com/assets/10784031/10558100/51f57466-74e1-11e5-8536-459d3a704f44.png)

**Comment by thomasjo** [comment]
Are you able to reproduce this in safe mode? `atom --safe`

**Comment by thomasjo** [comment]
This could be related to the Electron bump, and thus the Chromium bump.

**Comment by 50Wliu** [comment]
I've reproduced this in Windows as well.  It doesn't happen all the time, and reloading the window isn't a guaranteed fix.

**Comment by nathansobo** [comment]
This seems to be a Chrome bug. I created a reproduction example and opened an issue on their tracker: https://code.google.com/p/chromium/issues/detail?id=554722

**Comment by simurai** [comment]
@nathansobo Isn't the Chrome issue more related to #9269. This issue seems more a visual glitch showing an unstyled scrollbar.

**Comment by flannelhead** [comment]
I can confirm this on stable 1.2.0 on Linux. When I open an Atom session and a file gets opened by default, the vertical scrollbar isn't styled correctly. If I open the settings view or any other new tab, the scrollbar gets styled correctly (and is refreshed even on the existing tab that was opened on start).

**Comment by tinchoz49** [comment]
exactly the same problem as flannelhead!

**Comment by flannelhead** [comment]
As far as I can tell, this didn't happen on v1.1.0 stable at all. I could try doing a `git bisect` between the versions during the weekend... Is there some procedure that could be followed to avoid recompiling everything at every step?

**Comment by nathansobo** [comment]
@flannelhead You could test them in development mode, available via `atom --dev` or the `Open Dev` command. I suspect it was the Electron upgrade caused it, but would be good to confirm. CSS styling should be applying to these scrollbars in all cases but for some reason it isn't.

**Comment by flannelhead** [comment]
@nathansobo According to my initial `git bisect`, the first bad commit seems to be 28ed6f3d9f66666c874ef0a499ad18ebc9da6824. I will still do clean builds of this and the previous commit, if that seems necessary.

**Comment by nathansobo** [comment]
That's surprising. Are you sure it's not intermittent?

**Comment by flannelhead** [comment]
The issue has been happening consistently everytime the application is started on the bad commits. I checked every commit by starting Atom for a few times and seeing if the issue appears.

When bisecting, I didn't do any cleanup between building the different commits... Should I run `script/clean` between builds just to be sure?

**Comment by flannelhead** [comment]
I did clean builds of 28ed6f3 and 52946db (the preceding commit). It seems that 52946db works while 28ed6f3 does not. This is consistent and happens in safe mode. I could continue testing 28ed6f3 and see if reverting some particular call to synchronous resolves the issue.

**Comment by as-cii** [comment]
@flannelhead: thanks for all the efforts you've put into this! :sparkles: 

> I did clean builds of 28ed6f3 and 52946db (the preceding commit). It seems that 52946db works while 28ed6f3 does not. 

This is interesting, although that particular commit doesn't seem to have introduced any change to the scrollbar behavior, but I might be missing something here.

Since you can reproduce this consistently, would you be able to tell which classes are being set on `atom-workspace` by inspecting Chrome DevTools? You should find it in the Elements pane, right under the `<body>` element.

![screen shot 2015-11-13 at 12 32 41](https://cloud.githubusercontent.com/assets/482957/11145122/c2db4efe-8a02-11e5-89ac-f29c758193a1.png)

Alternatively you can write this in Chrome Console:

```js
document.querySelector("atom-workspace").className
```

Hypothetically, we should find `scrollbars-visible-always` among the class that are being set. If it's there, could you make one more attempt by finding out this element:

```js
document.querySelector("html /deep/ .vertical-scrollbar")
```

Right click into what Chrome outputs and select "Reveal in Elements pane": 

![screen shot 2015-11-13 at 12 40 22](https://cloud.githubusercontent.com/assets/482957/11145224/b9080362-8a03-11e5-83f5-4fccf6624c0f.png)

And go through all the CSS styles that are being applied:

![screen shot 2015-11-13 at 12 41 13](https://cloud.githubusercontent.com/assets/482957/11145239/da7a5432-8a03-11e5-849b-2875da466758.png)

Can you find anything related to `::webkit-scrollbar` in there, as showed in the screenshot?

Thank you for your help!

**Comment by schlamar** [comment]
I can reproduce this on 1.2.0, too. Here are these results:

    <atom-workspace class="workspace scrollbars-visible-always theme-monokai theme-atom-dark-ui" tabindex="-1">

![1](https://cloud.githubusercontent.com/assets/238652/11149010/95ae50c0-8a20-11e5-9716-17d7d1597c8b.png)

**Comment by flannelhead** [comment]
@as-cii Bravo!
