### ISSUE TITLE
.log files are sometimes not discovered

### ISSUE THREAD

**Issue by Overdrivr** [atom/atom#9224]
I have a python project that generates a .log file. I've noticed since a few days this file is not discovered anymore by Atom. If I change the file extension to .md, everything is fine. It seems to concern only .log files.

I tried making a minimal test folder with just the log file, but in this case it is discovered.
I added my gitignore file with it, but file is also discovered.

I will try other things to find out what is going on, if someone wants to test it also I can provide an archive of the project.

Otherwise if you have python 3.4 installed, it is also possible to download the project at this commit <https://github.com/Overdrivr/DistantIO>, install the required module and run the application.py file once. This will generate the log file.

**Comment by izuzak** [comment]
Thanks for the report, @Overdrivr. Instead of us running your program, could you instead provide a ZIP file which contains everything that's created after the program is run? That way, we can just unzip and open the folder in Atom. Running random programs is a bit scary, as I'm sure you understand.

Also, can you please provide more information on the problem your seeing and your environment?

Which version of Atom are you using? 
Which OS and version? 
Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? 
Can you provide a GIF which clearly demonstrates the problem you described? I'm not sure i understand where exactly is Atom not discovering the file (in the tree view, in fuzzy finder, in search, ...)? A GIF would help us get a better understanding of that.

Also, you might want to check out the [guidelines for submitting issues](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues), in case you'll be opening more issues in the future. :v:

**Comment by thomasjo** [comment]
@Overdrivr You've got `*.log` in your `.gitignore` file: https://github.com/Overdrivr/DistantIO/blob/master/.gitignore#L84

Please check if the *Hide VCS Ignored Files* config option is checked
<img width="524" alt="settings_-_atom" src="https://cloud.githubusercontent.com/assets/3622/10629350/7c1287c6-77ce-11e5-846b-7fafd6181727.png">

I'm sure that's the problem. If this is the problem, please re-open the issue and follow the guidance provided by @izuzak.

**Comment by izuzak** [comment]
Dope, thanks for checking that gitignore file, @thomasjo -- should have done it myself before typing that book chapter above. :sweat_smile:

**Comment by Overdrivr** [comment]
Hum I'm not sure to understand what this button is really doing then.
On my home computer, the button is checked
![1](https://cloud.githubusercontent.com/assets/1294805/10629534/e12bd2d8-77cf-11e5-929f-7ce174a7b071.png)

Yet I can see the .log file
![2](https://cloud.githubusercontent.com/assets/1294805/10629543/ee44f440-77cf-11e5-8e9e-8169fee5380d.png)

Is it expected behavior ? Now I have the issue on my work computer, so I will check the settings and let you know.

**Comment by thomasjo** [comment]
> Hum I'm not sure to understand what this button is really doing then.
> On my home computer, the button is checked

Wrong settings page. Check my screenshot, it's for the tree-view package, not core settings.
Click *Packages*, then navigate to the *tree-view* and view its settings.

**Comment by Overdrivr** [comment]
Sorry about that, that was it.

Thank you for the support guys, much appreciated 

Regards
