### ISSUE TITLE
Highlighting lines takes 10% of the CPU?

### ISSUE THREAD

**Issue by Wulf** [atom/atom#9236]
### Repro steps:

1) Open a project folder
2) Open a file (must have some lines in it, more than 10 makes it easier to reproduce)
3) Hold double-click to select an entire line (keep holding it)
4) Move mouse down to select a few more lines
5) Wiggle your mouse up and down and notice that:
- two processes go from taking 0% of the processor to 10%+
- fan speed increases! (side effect)
#### Process 1:

/usr/share/atom/atom --type=gpu-process --channel=4927.0.1668123424 --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=2,27,30,43,52 --disable-accelerated-video-decode --gpu-vendor-id=0x10de --gpu-device-id=0x1187 --gpu-driver-vendor=NVIDIA --gpu-driver-version=355.11
- increases by 13% for a simply highlighting lines?
#### Process 2:

/usr/share/atom/atom --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-image-decoding --lang=en-US --node-integration=true --subpixel-font-scaling=false --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=2 --use-image-texture-target=3553 --disable-accelerated-video-decode --channel=4927.1.2045218742
- increases by ~12%

Expected behavior:
For a simple task such as highlighting lines, is it reasonable to not expect 10% of my processor being used?

Additional Information:
processor: i7-930
gpu: nvidia gtx 760

**Comment by nexhub** [comment]
I can reproduce this bug with ~25% cpu usage/one core.
I'm using the webupd8team repository on a fully patched ubuntu 16.04.1.

It only happens if you follow the instructions carefully:
Double-click to select whole line and then hold left mouse is necessary. 
Possibly relevant packages:
highlight-selected@0.11.2
minimap@4.25.6
minimap-highlight-selected@4.4.0
minimap-selection@4.4.0
