### ISSUE TITLE
Cannot move multiple files in tree view

### ISSUE THREAD

**Issue by thomdixon** [atom/atom#9245]
I tried searching for this issue, but didn't come up with anything. If this is a dupe, I apologize. 

I can select multiple files in the tree view, but when I try to move the selected files, it only moves one.

You can see this behavior in the following video: 
![moving_files_in_tree](https://cloud.githubusercontent.com/assets/461514/10645853/b6abce68-77e4-11e5-8124-3f0d2c177d60.gif)

This is on Atom 1.0.19 on Mac OS X 10.10.5.

**Comment by mnquintana** [comment]
This is most likely due to https://github.com/atom/tree-view/issues/232 - you can't move multiple files at all, not just by dragging and dropping. I'm going to close this out in favor of that issue - feel free to leave a comment there about ensuring that it works with both the move command and with dragging and dropping.
