### ISSUE TITLE
keeps reinstalling itself after reboot...

### ISSUE THREAD

**Issue by JourneyOver** [atom/atom#9250]
I want to uninstall atom, but every time I do and I reboot my computer at a later date it always seem to reinstall itself without my permission or anything, not even a single popup.. it just installs itself and puts a shortcut back on my desktop again -.- this is very annoying because it happens pretty much every reboot.. I have found no way to get it to stop doing this.

I've even tried deleting every trace of atom on my computer but it doesn't matter, as soon as I reboot it all comes back along with the reinstall.

This is happening on windows 10..

**Comment by Zireael07** [comment]
What version of Atom are you using? Have you tried apps such as CCleaner or Revo Uninstaller to get rid of Atom? Might be the Atom uninstaller doesn't work on Win10...

**Comment by paulcbetts** [comment]
>  Might be the Atom uninstaller doesn't work on Win10...

It does.

I suspect that you installed Atom as elevated administrator and got the machine install, then you're trying to manually remove it. Head on over to C:\ProgramData and delete any folder labeled Squirrel or Atom.

**Comment by JourneyOver** [comment]
@Zireael07 I'm using the latest version of Atom which is v1.0.19, I've tried both ccleaner and revo uninstaller to get rid of atom and while it does get rid of it for a bit as soon as I reboot it's all back again.. One funny thing I find is that when I go into the Atom folder when ever it's installed (by me or by the reboot doing it) there is no uninstaller at all, even running revo uninstaller doesn't bring up an uninstaller for atom at all.. 

@paulcbetts nope I just run the installer for Atom normally without elevated admin rights, but like I said  to zireael though that there is no uninstaller even present with atom at all when I install it manually or when my computer does it itself on reboot.. I've looked in C:\ProgramData and there are no folders present (even on reboot when it installs itself) that are labeled Atom nor Squirrel..

**Comment by paulcbetts** [comment]
@JourneyOver Contents of `HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Run` regkey?

**Comment by JourneyOver** [comment]
@paulcbetts deleted everything in there as well that has to do with Atom as well when getting rid of it, anyways the last time I rebooted my computer recently it didn't come back like all the other times so maybe it's gone for good or at least I hope so because it's annoying having to re-uninstall it every time I restart my computer.

**Comment by AmZaf** [comment]
@paulcbetts I stumbled upon the exact same problem with the latest Atom release on Windows 10. First, Atom installer failed repeatedly due to file access errors. I then thought running the installer as Administrator might help but it didn't. Next, I noticed Atom installs on system restart. Wow, how could this be! I uninstalled Atom and after another system restart Atom magically reappeared. I thought it was a prank until I found this thread. The morale of the story is that the Squirrel installer fails because Avira antivirus (silently) interferes with the installation process. As you mentioned here, Atom keeps coming back because I attempted to run the installer as Administrator. 
A workaround would be to disable the antivirus during the installation process (or run as Admin and restart!). But Atom updater would subsequently fail as long as antivirus protection is enabled. I think this behaviour has unintended consequences and the bug report merits reconsideration by either Atom or Squirrel developers.

**Comment by paulcbetts** [comment]
@AmZaf We've removed the machine installer behavior in the latest version of Squirrel and replaced it with MSI generation, so the install loop bit shouldn't happen. We can't really do much about Antivirus sabotaging us though

**Comment by Kerykz** [comment]
I've been using computers for years but I never seen a software as stupid as Discord. Everything was going well until today when the program decided to not open anymore. It also decided to not uninstall when I try to so I had to manually delete everything about it. And then it also decided to not install back again. I believe I lost more neurons today because of your software than I lost by using synthetic drugs for months. Not gonna use it again. Ever.
