### ISSUE TITLE
RegEx works in file search, but fails in "Find in Project"

### ISSUE THREAD

**Issue by paulchrablass** [atom/atom#9251]
Hi,

I don't know if this is really an error or I'm just missing something, but the following behaviour seems odd to me.

I'm using RegEx to find and replace some html patterns.

**Text to find**:
<pre>

&lt;/div&gt;
&lt;!-- end: main body --&gt;

</pre>

**Text to replace**
<pre>

&lt;/main&gt;
&lt;!-- end: main body --&gt;

</pre>

**RegEx I'm using**
<pre>
&lt;\/div&gt;(\s|\n)*&lt;\!--\send:\smain\sbody\s--&gt;
</pre>

This works fine when I use it in a single file, but fails when I use the **Find in Project** search feature.

I'm using **Atom 1.0.19** on **Mac OS X 10.10.5 (14F27)**.

I created a few files for testing, you can find them at https://www.dropbox.com/s/25wr27ys6mzy2o7/atom-test.zip?dl=0

You can recreate this error by searching in one file for
<pre>
&lt;\/div&gt;(\s|\n)*&lt;\!--\send:\smain\sbody\s--&gt;
</pre>
and then use it with the Find in Project search.

**Comment by jeancroy** [comment]
From what I understand `Find in Project` use atom/scandal which seems to do regex search on a line per line basis. Because your regex span multiple line, it'll never match.

Alternatively other operation are done on chunk of text, and while there's some check to ensure the chunk will cut on a newline, there's no grantee the chunk will not cut in between those lines.

**Comment by benogle** [comment]
Sorry about this and thanks for the report. Closing in favor of https://github.com/atom/scandal/issues/5
