### ISSUE TITLE
`atom.workspace.open()` with `split: 'left'` does nothing when a single pane is visible

### ISSUE THREAD

**Issue by blakeembrey** [atom/atom#9258]
I would expect splitting left to match the behavior of splitting to the right, but instead it opens items in its own pane emulating `split: undefined`.

**Comment by thedaniel** [comment]
Thanks for the report.

**Comment by benogle** [comment]
This is intentional at this point. The idea is that it will find or create the pane in the direction specified. When there is no right pane, it will create it, otherwise use the one that exists. There is always a top and a left pane, so it will always use the extant pane. 

It is different than `split: undefined` in that it will open in the left pane when the right pane is focused. This behavior is used [in find-and-replace](https://github.com/atom/find-and-replace/blob/cc0935ba235f537e066b9bcd949c0712e05d5d3f/lib/project/match-view.coffee#L48) when opening a file from the right pane.

For now. You can use [splitLeft](https://atom.io/docs/api/v1.1.0/Pane#instance-splitLeft), then activate the pane, and then use open with no parameters.

In the future, we can add some public APIs for finding panes relative to a given pane, then we can change this API to support the behavior you are expecting. One downside to that, though, is many packages may be relying on the current behavior.
