### ISSUE TITLE
Why is every Patchlevel++ commited?

### ISSUE THREAD

**Issue by martinoppitz** [atom/atom#9302]
No feature code added. Is there a commit highscore?

The package.json must change in a relationship of a feature and before test, build and deploy.

Or not?

**Comment by thedaniel** [comment]
I'm not sure what you're asking - do you mean our versioning strategy, or how we organize our development in commits and pull requests?

**Comment by martinoppitz** [comment]
I mean this ...

Why changing patch level of deps without new atom feature code? Only in relationship to new code or before code freeze.

sry, but so, we commit sometimes package.jsons without effect ... ???

@izuzak
:arrow_up: symbols-view@0.110.0
izuzak committed 5 days ago
3595666  
@izuzak
:arrow_up: whitespace@0.32.0
izuzak committed 5 days ago
4699fa4  
@izuzak
:arrow_up: welcome@0.32.0
izuzak committed 5 days ago
d5786a6  
@izuzak
:arrow_up: tree-view@0.193.0
izuzak committed 5 days ago
2dfc066  
@izuzak
:arrow_up: spell-check@0.62.0
izuzak committed 5 days ago
951c8e8  
@izuzak
:arrow_up: package-generator@0.41.0
izuzak committed 5 days ago
9ca97d3  
@izuzak
:arrow_up: open-on-github@0.39.0
izuzak committed 5 days ago
fad937b  
@izuzak
:arrow_up: notifications@0.61.0
izuzak committed 5 days ago
1e1c88a  
@izuzak
:arrow_up: markdown-preview@0.156.0
izuzak committed 5 days ago
efe815d  
@izuzak
:arrow_up: grammar-selector@0.48.0
izuzak committed 5 days ago
b0d38bd  
@izuzak
:arrow_up: git-diff@0.57.0
izuzak committed 5 days ago
9423af4  
@izuzak
:arrow_up: fuzzy-finder@0.92.0
izuzak committed 5 days ago
39fc1ee  
@izuzak
:arrow_up: find-and-replace@0.189.0
izuzak committed 5 days ago
8fe8aec  
@izuzak
:arrow_up: bracket-matcher@0.79.0

**Comment by izuzak** [comment]
@martinoppitz Those packages are [bundled with Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages). When a bundled package is updated, then you might consider that an update of Atom itself because those packages are a part of the core Atom experience. When we make an update to a bundled package, we need to tell Atom core to use those new versions of packages (otherwise, it will still use to old versions). That's done by updating the dependency version in package.json. Does that answer your questions? If not, can you explain what )exactly_ you expected to see instead and why?
