### ISSUE TITLE
Ligatures for strict inequality operator (!==) broken

### ISSUE THREAD

**Issue by FunkMonkey** [atom/atom#9372]
It will result in the nonstrict inequality operator ligature and an equality sign.

Thought the font was missing it first, but [Fira Code](https://github.com/tonsky/FiraCode) definitely has it, see tonsky/FiraCode#59.

Thanks

**Comment by FunkMonkey** [comment]
Update: It depends on the syntax highlighting. Some languages (JS, Java, Python) don't work, while others (plain text, C#) work just fine.

**Comment by izuzak** [comment]
Thanks for the report, @FunkMonkey. I'm going to cc @as-cii, our :crown: of ligatures. 

I was able to reproduce this. With JavaScript set as the grammar:

<img width="132" alt="screen shot 2015-11-01 at 19 08 24" src="https://cloud.githubusercontent.com/assets/38924/10870460/f3bf6e50-80cb-11e5-9786-aadf70461fb2.png">

With plain text set as the grammar:

<img width="150" alt="screen shot 2015-11-01 at 19 08 15" src="https://cloud.githubusercontent.com/assets/38924/10870459/f3bd384c-80cb-11e5-9547-f39a1bb5684f.png">

**Comment by as-cii** [comment]
This problem is intrinsic to how ligatures are rendered by Chrome. Chrome renders ligatures whenever a contiguous piece of text is not interleaved with other tags and the font provides a way to create a ligature or a contextual alternate out of a bunch of characters.

In the case of Javascript, the grammar is probably considering the second equal sign (i.e. the third character) as a separate token, thereby breaking what would otherwise be a contiguous piece of text eligible for being rendered as a ligature by Chromium. In other words, this is a limitation of the rendering engine and I think it can be solved only at a "grammar level" by grouping those three signs within a single token.

**Comment by 50Wliu** [comment]
I'll take a look at the JS grammar.  Should be an easy fix.

**Comment by alexandernst** [comment]
@50Wliu maybe all grammars should be checked (and modified if necessary) making the longest possible combination of chars to be matched first?

**Comment by braver** [comment]
> @50Wliu maybe all grammars should be checked (and modified if necessary) making the longest possible combination of chars to be matched first?

This is a good idea in general, but pretty much all grammars are sketchy in this area. It is the only right way to fix this, we can't expect Chrome to make ligatures for stuff that's in different tags.

**Comment by MaximSokolov** [comment]
This could be closed as JS `!==` operator is fixed. Create an issue on related language-* repo if you found an operator which isn't tokenized properly
