### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#9377]
Atom 1.2 beta shows "Atom 1.1.0" in the "About" menu.

**Comment by jsjain007** [comment]
Are you sure you have installed the beta version instead of the stable version
You can download the beta version from the link https://atom.io/beta
and to know its beta you'll have a yellow icon of atom instead of green one.
![capture](https://cloud.githubusercontent.com/assets/6463002/10866691/0d921248-8062-11e5-99ab-6b37f5060673.PNG)
See mine looks something like this.

**Comment by alexandernst** [comment]
Indeed, I was running the wrong version.
