### ISSUE TITLE
[Windows] Atom installer depends on .Net

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#9436]
Atom installer depends on .Net. There are quite some other alternatives (may I suggest NullSoft?) that don't need/depend .Net, and given the fact that Atom itself doesn't depend on .Net in any way, maybe porting the installer to something else would be a good idea.

**Comment by benogle** [comment]
cc @paulcbetts

**Comment by thomasjo** [comment]
Unless we swap out Squirrel, then dropping the .NET requirement is not possible as far as I can tell.
:-1: I vote `wontfix` on this one.

---
The .NET requirement will still be a requirement on Windows if someone wants to install a package that uses native modules, right? Even Python is required due to these requirements trickling down from node-gyp.

**Comment by alexandernst** [comment]
Squirrel is quite a good reason to keep .Net.

Btw, no, .Net per-se is not enough for node-gyp on Windows. You actually need VS.

**Comment by paulcbetts** [comment]
@alexandernst The version of .NET that we depend on is in-box on Windows 8 and higher, so this isn't as annoying a requirement as it seems
