### ISSUE TITLE
Provide different soft-wrapping rules for CJK languages

### ISSUE THREAD

**Issue by chloerei** [atom/atom#9447]
Text:

```
文字文字 English 文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字
```

1.2.0-beta0:

![8](https://cloud.githubusercontent.com/assets/49931/10838878/9e92ea9e-7f07-11e5-9f04-96b1c59071e5.png)

When mixing English and Chinese(or Japanese) with whitespace, Chinese(or Japanese) sentence can be break, instead of break in whitespace. 

Browser:

> 文字文字 English 文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字

**Comment by lee-dohm** [comment]
It looks like it is only lines that contain both CJK and non-CJK. If I shrink the window even further, the all CJK line wraps as expected:

<img width="583" alt="screen shot 2015-11-04 at 7 16 34 pm" src="https://cloud.githubusercontent.com/assets/1038121/10959000/9f01e456-8328-11e5-8308-e8163a78d1c7.png">

**Comment by as-cii** [comment]
The problem here lies in how soft-wrapping changes depending on the language. #9162 only addressed the _rendering_ part of it, which was causing issues because of the amount of space characters were occupying. The way word-wrapping works as of now is that we will soft-wrap if we manage to match a space before the hypothetical hard-wrap position: if we do, we break the line in two, otherwise we perform an hard-wrap at the desired position.

An hypothetical solution to this will need to take into account the language, because as far as I know, each language has its own soft-wrapping rules. There's a [good article on Wikipedia](https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages) which explains this in greater detail.

@nathansobo: our current solution was a great leap compared to the past, but I feel like I could put some effort into polishing this following the aforementioned rules. What do you think?

**Comment by mandel59** [comment]
Unicode provides [Unicode Line Breaking Algorithm](http://unicode.org/reports/tr14/).

**Comment by nathansobo** [comment]
@mandel59 Thanks for the link! Know any JS reference implementations?

**Comment by mandel59** [comment]
I found https://github.com/devongovett/linebreak

**Comment by wonderbeyond** [comment]
https://github.com/devongovett/linebreak seems good!

**Comment by yukihop** [comment]
Currently, this bug is making this editor essentially useless for editing CJK markdown documents, HTML and such, which naturally involve a small number of spaces and long CJK strings jumbled together. Atom often tries to break lines at the second column!

![image](https://cloud.githubusercontent.com/assets/7379497/11674724/e3a8470e-9e66-11e5-913a-aeef495196b7.png)

And editing markdown is one of the fields Atom should be exceptionally good at.

So is it possible to add a mode to suppress per-word soft wrapping **altogether** (even for English words)? That should quickly fix this problem.

While word processors such as Word definitely need complex wrapping algorithm suggested here, I doubt *editors* like Atom need this kind of sophisticated line-breaking algorithm. The goal of Atom is not to replace Word or InDesign.

At least in Japan, most popular domestic *editors* (such as [Hidemaru](http://hide.maruo.co.jp/software/hidemaru8/index.html})) do not respect line-breaking rules at all by default. They simply break lines everywhere, even in the middle of an English word. The users of such editors don't care if commas and closing brackets come at the beginning of a line. As a native speaker of Japanese, I'd say that's the preferred behavior when I feel like using Atom. Seeing split English words is much more tolerable than seeing soft-warp happening at the second column.

**Comment by nathansobo** [comment]
@as-cii Seems like we could detect CJK characters in our soft-wrap code and just break at the preferred wrap boundary instead of at whitespace if there are any in the line. Thoughts?

**Comment by as-cii** [comment]
@nathansobo: interesting, using Unicode's standard line breaking algorithm seemed quite tempting to me, although I am not sure how long it could take to implement it or to integrate an existing package (e.g line-break) with Atom.

I guess that detecting whether the character at the preferred wrap boundary is CJK could be fine. Opening a PR for this :soon:.
