### ISSUE TITLE
When opening multiple files Atom (1.3.0.beta0) creates a new window for each file

### ISSUE THREAD

**Issue by fabiospampinato** [atom/atom#9574]
In Atom 1.2.0 when I opened a lot of files at once from the finder it was just adding them to a previously opened window. Now I'm trying the version 1.3.0.beta0 and it created a new window for each file, each of them having the folder the file was into as the project folder.

This is the result:

![](http://s24.postimg.org/t05v8vdlh/Screen_Shot_2015_11_13_at_17_27_14.png)

Every white rectangle is an Atom window, a crashed one. Is it a bug or a minded change? If so I'd like to point out that those files where all part of a folder that had already an Atom window, if you want to keep this "feature" at least you should notice it, and in that case attach them to the already opened window.

**Comment by samrayner** [comment]
Seems like this is likely to be the same bug as https://github.com/atom/atom/issues/9526

**Comment by izuzak** [comment]
I've been able to reproduce this on latest master as well. Here's a GIF in which I open a file from atom/atom, and then open a few more files from the same directory and all of them are opened as separate windows. That happens if I open them from Finder, but doesn't happen if I open files from console -- opening them from console reuses the existing window.

![moar](https://cloud.githubusercontent.com/assets/38924/11215966/0e602810-8d49-11e5-8bd1-d8c028c721d0.gif)

cc @maxbrunsfeld @kevinsawicki for more :eyes: 

I was also able to reproduce this on v1.2.0, but wasn't able to reproduce on v1.1.0
