### ISSUE TITLE
Binary packages for 1.2.1 release are missing

### ISSUE THREAD

**Issue by alanfranz** [atom/atom#9645]
Hello, 
1.2.1 was tagged some days ago in https://github.com/atom/atom/releases , but it seems that's just the source that's available. Will the packages be uploaded, or it was a wrong tagging?

**Comment by abe33** [comment]
I believe it's because you went visiting the page before Hubot had build these files (I guess you just have to tag a commit and Hubot comes in to build all the package at that version). What I'm seeing now is: 
![releases_ _atom_atom](https://cloud.githubusercontent.com/assets/247140/11207749/4ad6432e-8d17-11e5-9a71-cb08961fbd5e.png)

And all the links point on a downloadable file (no 404).

I'll closing the issue as I believe there's no problem with the release system, just an issue of the delay to build them.
