### ISSUE TITLE
Missing icon on Ubuntu

### ISSUE THREAD

**Issue by miftahafina** [atom/atom#9667]
I just installed atom on my ubuntu 14.04 LTS (64bit) using atom version 1.3.0-beta3 and I found the atom's icon is missing from unity dash. I only see the gear icon.

**Comment by majcherek2048** [comment]
Just noticed the same thing after building 1.3.0-beta6 here.
It's been a long time since I did any build though, so I have no idea when this happened.
```
/usr/share/icons$ find . -iname "*atom*" | wc -l
0
```
I'll see if I have the time to dig up my laptop later today, and start upgrading one version at a time.

**Comment by majcherek2048** [comment]
Hehe, okay so... I'm running Debian here (Gnome 3), and was digging into the issue.
Soon I discovered that the icon was located in /usr/share/pixmaps, which is according to specification.
The icon is applied in the desktop-file located /usr/share/applications/atom.desktop.
It should be the [same in Unity] (https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles)

Anyway, simply restarting the Gnome-shell worked for me (If you're using Gnome, try Alt+F2, type "r", and press enter. All programs will remain open). If you aren't using Gnome, did you try rebooting?

If it's still not working for you, could you please confirm that the image atom.png is located in /usr/share/pixmaps/, and is working (you can just copy it to your home-folder and open the file).
Could you also please confirm that the desktop-file has the line "Icon=atom".

**Comment by majcherek2048** [comment]
Another location for desktop-files might be /usr/local/share/applications.
On both of my computers there's a desktop-file in here too (most likely the install script).
The location for the icon in this file is /usr/local/share/atom/resources/app.asar.unpacked/resources/atom.png in the new version.
In the older version, the desktop-file was named Atom.desktop (instead of atom.desktop), and the icon location was different (/usr/local/share/atom/resources/app/resources/atom.png).
This might point you in the right direction.

Did you upgrade from an old version, or was it a fresh install?

**Comment by miftahafina** [comment]
Finally I re-install it and the problem is gone. :smile: 
Thanks for your care.
