### ISSUE TITLE
big space between menu bar and drop-down menu

### ISSUE THREAD

**Issue by skittleys** [atom/atom#9771]
As shown in the included screenshot, a space is appearing between the menu bar and the drop-down menus. This only occurs at some times and not others, and I cannot tell what is different between those times. This occurs regardless of the chosen UI theme. This occurs in both atom 1.2.1 and 1.2.4.

<a href="http://tinypic.com?ref=2mg1mjq" target="_blank"><img src="http://i63.tinypic.com/2mg1mjq.png" border="0"></a>

**Comment by maxbrunsfeld** [comment]
What OS and Atom version are you using? Do you have any packages installed? Are you using full screen mode?

**Comment by skittleys** [comment]
OS: Linux (Debian stretch, using deb from your releases)
Atom: as said above, it happens with 1.2.1 and 1.2.4. I'm now using 1.2.4.
Packages: yes, but it also happens with `atom --safe`
Full-screen mode: it was not in full-screen mode. When I tried going to full-screen mode, the spaces disappeared, and when I went back to normal mode, the spaces were still gone!

**Comment by rsese** [comment]
Trying to go through and cleanup some older issues - it's been a while since this report and Atom is currently at release version 1.14.4.  A quick search didn't turn up any other similar reports either.

I'll go ahead and close the issue for now but if you're still seeing an error with the latest release version of Atom, please feel free to open a new issue and fill out the issue template @skittleys :v:
