### ISSUE TITLE
Atom uploading user data without explicit permission

### ISSUE THREAD

**Issue by akissa** [atom/atom#9816]
Hi

It seems like atom is sending "crash" data from my system to an online system without me configuring it to.

I think that is a vulnerability. There should be settings for a user to either accept or reject data being
sent to an online system. I should also be able to see what is being sent. I cannot find any in atom.

`/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler --database=/tmp/Atom Crashes --url=http://54.249.141.255:1127/post --handshake-fd=41`

**Comment by amytruong** [comment]
There was a recent discussion about Atom’s EULA here :point_down: and it mentions how Atom sends data to our servers:
https://github.com/github/legal/pull/542/files#diff-21816317faa283273c70717397bdce9aR26

In the meantime, I will ask the team if there's a way to disable this in any way (such as building Atom from source yourself) and label this issue as an enhancement.

**Comment by akissa** [comment]
Am appauled that you are callous enough to simply dismiss the issue as "read the eula" and then close the issue.

I should be asking myself why the heck am i using atom in the first place with this kind of nonchalant attitude to user data.

**Comment by izuzak** [comment]
@akissa Sorry, the issue was closed by mistake (that happens) and we just wanted to explain that it's something we want to communicate more clearly in an EULA in the future. Not trying to be dismissive here -- thanks for bringing this up. I do think it would be useful if it was possible to disable that.

Also, just wondering if you could explain which information exactly in the crash report you're concerned about sharing the most? Thanks again.

**Comment by amytruong** [comment]
@akissa: Apologies for that and I truly didn't mean to sound callous. I've just joined Atom recently and learning the ins & outs of working through issues and learning when to keep things open/closed for further details/discussion.

**Comment by mnquintana** [comment]
@akissa There actually is a way for you to disable that now, though - you can disable the exception-reporting package (go to Settings > Packages > search for exception-reporting and click disable)

**Comment by akissa** [comment]
@izuzak This issue is i do _not_ know what is being sent and _why_ it is being sent as well as why it is being sent in _sneaky_ way, i have been using this for months and did not know until i looked at my process list. All other crash processing systems request the user for permission to upload their data to a different location.

In the EU it may (stand to be corrected) actually be ilegal to transfer data to a differnet country / continent since as i see the data is being sent to an Amazon AWS server which would most likely be in the US.

**Comment by akissa** [comment]
@amytruong No prob, i understand

**Comment by izuzak** [comment]
@akissa I agree. As I said, I think it's something that should be improved. Thanks for caring about privacy :heart:

I believe that crash reporting functionality is in Electron, the framework Atom is built upon, specifically [here](https://github.com/atom/electron/blob/fe214e08068a36e4f98febecd62b31011de474af/atom/common/api/lib/crash-reporter.coffee). And the information that's sent is listed [here](https://github.com/atom/electron/blob/fe214e08068a36e4f98febecd62b31011de474af/docs/api/crash-reporter.md#crash-reporter-payload). Does that help?

**Comment by akissa** [comment]
@mnquintana disabling the exception-reporting package does not disable the process it is still running even after restarting atom.

**Comment by jeancroy** [comment]
The metric package then ?

**Comment by 50Wliu** [comment]
@jeancroy I don't think this has anything to do with Atom.  The process seems to be coming from Electron.

**Comment by akissa** [comment]
the metric package is disabled, anyway in a world awash with free code editors i am not going to waste any more of my time with an editor that spys on me by default.

@50Wliu Electron is installed on my system by Atom so it is an Atom problem not an Electron problem.

**Comment by 50Wliu** [comment]
> @50Wliu Electron is installed on my system by Atom so it is an Atom problem not an Electron problem.

Yes, it has to be installed, since Atom runs on Electron.  That being said it is *not* an Atom issue, as we cannot control what Electron is doing.

**Comment by akissa** [comment]
@50Wliu ???? -> https://github.com/atom/electron/blob/fe214e08068a36e4f98febecd62b31011de474af/atom/common/api/lib/crash-reporter.coffee#L24 of course you can. There is an option to not auto submit

**Comment by 50Wliu** [comment]
In that case, I'm wrong.  Sorry for the misinformation :(.

**Comment by jeancroy** [comment]
But if you look at that piece of code the process get started regardless of `autoSubmit`.
So it's possible the process act local only, even if it does have remote IP in command line.

Do you have a communication of that process with the autosubmit set to off ?

**Comment by akissa** [comment]
@jeancroy atom does not set the flag, it could even check if the user does not want reporting and not startup the process https://github.com/atom/atom/blob/ff812749e67ed55518f91fa9d56286f8f3ce4ed6/src/browser/main.coffee#L56

**Comment by yieldman** [comment]
I have experienced this first hand and i am not okay with this. Without any warning, without any confirmation , it uploaded data online . Who thought this is a good idea ? Are devs high on smack ?

**Comment by DFNCTSC** [comment]
This still isn't fixed.

**Comment by gerroon** [comment]
I would like to add my voice to this as well, I just stopped using this editor after realizing what was going on behind the doors. Now you might not care about individuals like me, given that it is a free editor but overall implementing proper privacy controls will bring more positive attitude towards your application.

**Comment by 50Wliu** [comment]
FYI we no longer auto-submit crash reports (https://github.com/atom/atom/blob/09ab7d68634c1603854acf03fd4b31926aeb450a/src/crash-reporter-start.js#L7), nor is the crash reporter URL even operational (last time I checked).

Other metrics data is now only submitted with user consent.

**Comment by DFNCTSC** [comment]
@50Wliu t might've taken you a year+ but good to hear it. I'll install the new version and let you know if I see anything.

**Comment by gerroon** [comment]
@50Wliu 
Everytime I start Atom it starts with a separate crashreporter process.

See yourself please
atom.exe --reporter-url=https://crashreporter.atom.io --application-name=Atom --v=1

**Comment by 50Wliu** [comment]
Yes, I never said it doesn't get started, but does it actually _do anything_?  At most it's collecting the crash reports since we're not auto submitting and it has nowhere to submit to. 

At least that's my thinking, which is why I asked others to confirm.

**Comment by 50Wliu** [comment]
Also, a clarification about why we bother to start a crash reporter if it doesn't report the crashes.  There's two main reasons: 
1. Without a crash reporter active, crash reports don't get saved to disk.  This is undesirable because when Atom crashes, we sometimes ask people to upload their reports so that we can get since insight into why Atom crashed.
2. I believe the eventual goal is to set up submitting so that it asks for consent first, but no one's done that yet. 

*Disclaimer: I am not a GitHub employee, so please do not take what I wrote as absolute fact.*

**Comment by gerroon** [comment]
@50Wliu 

Thanks for clarification, 

My desktop does not have internet so I personally do not care if it tries to uplload or not but my position is based on the fact that the user permission at least acknowledgement should be established before going forward with any of this stuff. 

I understand that GIthub has great interest in collecting as much info as possible about programmers, gain even deeper insignth into every programmers mind (like they are tracking everything I write here, the speed of typing, amount of undos I use etc, check ther js in the page), that is their issue but the user consent is a requirement, otherwise it is a form of mental rape if you ask me. 

ANyway I do not want to drag this issue further. I agree crash reports are important to product quality, but it would be nice this is made clear from the start.
