### ISSUE TITLE
Replace All button not active until find is done

### ISSUE THREAD

**Issue by smcavoy-travelbird** [atom/atom#9847]
I think the "Replace All" button should do a find then replace instead of having to click find and then click replace all. The user will be prompted to confirm so it seems like an unneeded step.

**Comment by izuzak** [comment]
I believe that's expected behavior for now -- please see https://github.com/atom/find-and-replace/issues/504 and https://github.com/atom/find-and-replace/pull/542. If you'd like, please add a comment to that issue (this isn't [the right repository for this](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)). Thanks! :v:
