### ISSUE TITLE
Selection:expandOverWord incorrectly selects delimiters if selection touches one

### ISSUE THREAD

**Issue by bhuga** [atom/atom#9851]
Using `-` as the start and end of a selection, when text like `"fo-oo-o"` is selected, `expandOverWord` correctly selects `"-foooo-"`. But if `"-fo-ooo"` is selected, `expandOverWord` incorrectly selects `-"foooo-"`.

A gif perhaps explains better:

![atom-wrong-selection](https://cloud.githubusercontent.com/assets/12676/11448890/c52215ea-9528-11e5-9f56-947f0b76ae12.gif)

This is used by vim-mode's `select-inside-word` (`diw`). A workaround for some cases was recently landed in https://github.com/atom/vim-mode/pull/890, but does not fix all cases, particularly the one I've illustrated here. cc @maxbrunsfeld

**Comment by TomLingham** [comment]
This is caused by the way that `Cursor.getEndOfCurrentWordBufferPosition()` behaves and seems like it might be unavoidable given the current implementation, without some nasty hacks.

This function receives the buffer from the position of the selection to the end of the file. It then uses the method `Cursor.wordRegexp()` to determine when the 'word' finishes by analysing that string.

'word' in this case defined by the regex pattern found in the `wordRegexp()` method, escaped below:
```
/^[	 ]*$|[^\s\/\\\(\)"':,\.;<>~!@#%\^&\*\|\+=\[\]\{\}`\?\-…]+|[\/\\\(\)"':,\.;<>~!@#%\^&\*\|\+=\[\]\{\}`\?\-…]+/g
```

So, for example, take the following, imagine with the 'r' in 'bar' selected/highlighted on the first line:
```javascript
this.foo('bar');
this.another(1);
```
In this case `Cursor.getEndOfCurrentWordBufferPosition()` only operates on the following:
```
');
this.another(1);
```
The regular expression above starts matching at the first character which is an apostrophe and keeps going until the end of the line so it matches `');`. You can force this to work properly **in this instance only** by forcing `Cursor.getEndOfCurrentWordBufferPosition()` to use a regex that will _not_ match the buffer at all (e.g. `Cursor.getEndOfCurrentWordBufferPosition({wordRegex: /^willnotmatch$/g})`). This will break all other instances of this function however.

A solution might be to check the resulting match (e.g. `');`) after the fact and see if it is a word itself using `Cursor.wordRegexp({includeNonWordCharacters: false})`. I'm not familiar with coffee script so can't make the changes myself but hopefully someone can get something useful from what I have added here :)
