### ISSUE TITLE
Atom reinstall everytime I start my computer

### ISSUE THREAD

**Issue by kuoruan** [atom/atom#9855]
I download Atom and install it on my computer,then I uninstall it from the control panel.but when I reboot my computer,I find Atom reinstalled! I have to uninstall it the second time,delete the folder in AppData\Local and in AppData\Roaming.reboot... Atom auto installed the third time.Now I have no idea.Can anyone help me?

OS: Windows 10 TH2 64bit Atom is from https://atom.io/

**Comment by kuoruan** [comment]
I found a atom.exe file in C:\ProgramData\SquirrelMachineInstalls, delete it, then fixed. But I don't know what is the folder used for?

**Comment by vgturtle127** [comment]
For installation, I believe. They are some of the log files generated by the installer processes.

I don't know why but, I always have some sort of trouble with the Atom installer.

**Comment by paulcbetts** [comment]
So, here's what happened:

1. You installed Squirrel via the --machine install (either that, or manually right-clicked on it and selected "Run as admin")
1. This means that on next login, we'll install it - this is because you can't install per-user apps for users that might not exist yet.
1. When you uninstalled it, we write a file that's a hint to the machine installer, "This particular user doesn't want the app, leave it be"
1. You deleted the folder in "AppData\Local", thereby _also_ removing the hint
1. It reinstalls
