### ISSUE TITLE
How do I set a command to delete current line?

### ISSUE THREAD

**Issue by smilence86** [atom/atom#9977]
Hi, I want to press 'ctrl & d' delete current line in atom, and try to write the code below but it didn't work, even thought atom restart.

in ~/.atom/keymap.cson, my system is ubuntu15.10, atom is newest version.
```cson
'atom-text-editor':
    'ctrl-d': 'editor:delete-line'
```

**Comment by BenSower** [comment]
I think this does not work, since 'ctrl-d' is by default assigned to the native command 'find-and-replace:select-next'.

You can check, if a Keybinding is already set with the Keybinding Resolver Package by clicking Packages -> Keybinding Resolver -> Toggle.
Then, you can press the desired combination and check, if it's already set.
(e.g. for me, 'ctrl-i' was still free, and I could set it to 'editor:delete-line').

Also, if it also works for you (e.g. if you are using a clipboard manager or so), you can just use 'ctrl-x' and cut the whole line.

**Comment by mnquintana** [comment]
I think this is a specificity issue - your custom keybinding isn't overriding the one set in find-and-replace because the selector you're using (`atom-text-editor`) is less specific than [the one defined in find-and-replace](https://github.com/atom/find-and-replace/blob/master/keymaps/find-and-replace.cson#L28).

Try this instead:

```coffee

'.platform-win32 atom-text-editor, .platform-linux atom-text-editor':
  'ctrl-d': 'editor:delete-line'
```

Does that work for you?

**Comment by smilence86** [comment]
@BenSower thanks，atom have a tip that say: You can override these keybindings by copying and pasting them into your keymap file, I think that means customize command will be use first than default. The reason isn't conflict,  because It also didn't work when I delete the default 'ctrl-d' command.

**Comment by smilence86** [comment]
@mnquintana thanks, It's perfect when I used your code. It can delete multi lines that I selected. not only current line.
