### ISSUE TITLE
Keybinding not consistent. Works one way through the command palette, different through the keybinding

### ISSUE THREAD

**Issue by nmaxcom** [atom/atom#9994]
I'm trying to invoke a command from the `atom-turbo-javascript` package:
>End New Line CTRL-ENTER
Terminates the current line with a colon or semicolon, followed with a new line. A comma is inserted when the cursor is inside an object literal, otherwise a semicolon is inserted.

I want the keybinding to be <kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>⏎</kbd> and so in my `keymap.cson` I have:

    'atom-text-editor':
        'cmd-shift-;': 'turbo-javascript:end-line'
        'cmd-shift-,': 'turbo-javascript:end-line-comma'
        'cmd-shift-enter': 'turbo-javascript:end-new-line'

Now, if I use cmd-shift-enter I get (i guess) the core functionality: a newline above the caret line. But if I search the same command in the command-palette, I see that it correctly has cmd-shift-enter and executing through the palette, it works!

![](http://i.imgur.com/FRVGTat.png)

So using the same shortcut the palette acknowledges directly, it gives me a new line above, not the turbo-javascript functionality. (in shift-cmd-enter order also doesn't work).

**Comment by lee-dohm** [comment]
Have you tried using the Keybinding Resolver (<kbd>Cmd+.</kbd> on OS X and <kbd>Ctrl+.</kbd> on other platforms)? It will show you what key Atom saw you press and the command that was triggered because of it.

To answer your implicit question about the Command Palette, the Command Palette lists the mapped keys. But since it doesn't have information about all the other mapped keys for wherever focus is at the moment you press the key, it can't predict all possible situations where the key may or may not apply. That's what the Keybinding Resolver is for, to help debug these things.

**Comment by nmaxcom** [comment]
I didn't know that existed ! Very useful, very worth while to mention it in the Keybinding settings or even in the keymap.cson

This is what I get:

![](http://i.imgur.com/tcbpXiX.png)

I thought your keymap.cson always have precedence over. At least [in these docs](https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings) it says:
>By default, ~/.atom/keymap.cson is loaded when Atom is started. It will always be loaded last, giving you the chance to override bindings that are defined by Atom’s core keymaps or third-party packages.

So... why is it not overriding that command and what's the best course to fix this?

**Comment by lee-dohm** [comment]
The Keybinding Resolver is mentioned in the [Debugging section of the docs](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings).

Keybindings use a CSS-like selector mechanism that is based on specificity rules. The reason why `editor:newline-above` is winning over your mapping (even though your mapping is loaded last) is because its selector is more specific. If you change your mapping to:

```coffee
'atom-workspace atom-text-editor:not([mini])':
    'cmd-shift-;': 'turbo-javascript:end-line'
    'cmd-shift-,': 'turbo-javascript:end-line-comma'
    'cmd-shift-enter': 'turbo-javascript:end-new-line'
```

then your version of <kbd>Cmd+Shift+Enter</kbd> will win. [This is also covered in the documentation.](https://atom.io/docs/latest/behind-atom-keymaps-in-depth#specificity-and-cascade-order)

**Comment by nmaxcom** [comment]
@lee-dohm I know (i searched for it when you mentioned it) it is in the debugging section, but it's too useful not to be mentioned at least in the keymap.cson where there's a huge block of text not even mentioning keybinding debugging.

Don't take it the wrong way, just my two cents. I really think it should be there giving how easy it is to not have the keybindings work the way they say they should work.

I'll fix my specificity, thanks.

**Comment by lee-dohm** [comment]
Fair enough :grinning: Added a PR.
